### ISSUE TITLE
Cannot open Hosted Web-Application with Chrome Browser

### ISSUE THREAD

**Issue by calgara12** [manga-download/hakuneko#1]
Im running Ubuntu server 16.04 and i was trying to set up the hakuneko web application.
I installed polymer-cli. but when i run polymer serve i get the message that everything is running:

`info:    Files in this directory are available under the following URLs
      applications: http://127.0.0.1:8081
      reusable components: http://127.0.0.1:8081/components/web/`

But when i access it inside the browser(Chrome) nothing shows up.

Thanks in advance and keep up the good work :)

**Comment by 27136773** [comment]
Project page is on sourceforge, there you will find binary distributions.

**Comment by 27136773** [comment]
Since of today the issue tracking has been moved from SourceForge to GitHub and therefore the issue will be discussed here.

I think this is the related thread:
https://sourceforge.net/p/hakuneko/discussion/support/thread/3ade5b8217/

**Comment by 27136773** [comment]
The bundled web-application cannot be opened with Chrome.
HakuNeko only works with the customized Desktop Client which is build with the electron Framwork.

The new quick start for developers may help:
https://github.com/manga-download/hakuneko/blob/master/README.adoc
