### ISSUE TITLE
Able to load manga list and manga chapters but when clicked download nothing happens

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1003]
> **From:** hamshams

**Version:** [6.1.7@d58cd6](https://github.com/manga-download/hakuneko/commits/d58cd6)

I am able to load the manga list from the bookmarks. When selecting the manga, the chapter list loads properly. But when clicking the download button, it jus shows 0 download. Check the website and it manga pages are showing fine. Tested with MangaFox and MangaHere and both showing the same problem. 

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Cannot be reproduced, provide sample manga and chapter

**Comment by hamshams73** [comment]
I checked today. Seems to be working fine now. Sorry for the inconveniences.
