### ISSUE TITLE
site add request manhuas.net

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1005]
> **From:** HakuNeko User

**Version:** [6.1.7@d58cd6](https://github.com/manga-download/hakuneko/commits/d58cd6)

Whenever you go a chance manhuas.net. Thank you

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Seems to be WordPress Madara Template
