### ISSUE TITLE
new manga crypted by japscan

### ISSUE THREAD

**Issue by megacin** [manga-download/hakuneko#1006]
Hello Hakunekto theme to day i was very sad becos japscan crypted all new mange just new i will show you some exmaple  and i want if you have abbluty to add this iste to this programe 
www.scan-fr.co
![001](https://user-images.githubusercontent.com/48812724/73539365-842d4d80-442d-11ea-84b1-52f71a2cd6f8.jpg)

**Comment by Ever4engel** [comment]
[966](https://github.com/manga-download/hakuneko/issues/996) Duplicate.

**Comment by 27136773** [comment]
JapScan has already been fixed
ScanFR works fine on my end
