### ISSUE TITLE
Site request: jaiminisbox.com

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1011]
> **From:** HakuNeko User

**Version:** [6.1.7@fc17fd](https://github.com/manga-download/hakuneko/commits/fc17fd)

Whenever you go the chance, please add jaiminisbox.com. Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
It is already supported
