### ISSUE TITLE
Distribute as Flatpak on Flathub

### ISSUE THREAD

**Issue by maxtron95** [manga-download/hakuneko#1012]
I was asking this because I wanted to see this on [Flathub.](https://flathub.org)

@ronny1982 I was wondering if you could be able to package HakuNeko as a Flatpak and submit it to Flathub?

If not, Would you be OK with someone else packaging HakuNeko for Flathub?

**Comment by 27136773** [comment]
I cannot, feel free to write and contribute a build script which can be integrated

**Comment by maxtron95** [comment]
@ronny1982 I created the files for flathub here https://github.com/creepertron95/flathub/tree/io.gihtub.hakuneko.HakuNeko. I just needed you to look over it and I need the SHA256 hash of the latest version and contact details from the author to finish it.

**Comment by maxtron95** [comment]
@ronny1982 Can you also try to rate the program with OARS https://hughsie.github.io/oars/generate.html and paste the results so I can accurately put the content ratings for HakuNeko in the file as well? This includes the Anime and Manga content that one would read or download.

**Comment by 27136773** [comment]
```xml
<content_rating type="oars-1.0">
    <content_attribute id="drugs-alcohol">intense</content_attribute>
    <content_attribute id="drugs-narcotics">intense</content_attribute>
    <content_attribute id="drugs-tobacco">intense</content_attribute>
    <content_attribute id="language-discrimination">intense</content_attribute>
    <content_attribute id="language-humor">intense</content_attribute>
    <content_attribute id="language-profanity">intense</content_attribute>
    <content_attribute id="money-gambling">intense</content_attribute>
    <content_attribute id="money-purchasing">intense</content_attribute>
    <content_attribute id="sex-adultery">intense</content_attribute>
    <content_attribute id="sex-appearance">intense</content_attribute>
    <content_attribute id="sex-homosexuality">intense</content_attribute>
    <content_attribute id="sex-nudity">intense</content_attribute>
    <content_attribute id="sex-prostitution">intense</content_attribute>
    <content_attribute id="sex-themes">intense</content_attribute>
    <content_attribute id="social-audio">intense</content_attribute>
    <content_attribute id="social-chat">intense</content_attribute>
    <content_attribute id="social-contacts">intense</content_attribute>
    <content_attribute id="social-info">intense</content_attribute>
    <content_attribute id="social-location">intense</content_attribute>
    <content_attribute id="violence-bloodshed">intense</content_attribute>
    <content_attribute id="violence-cartoon">intense</content_attribute>
    <content_attribute id="violence-desecration">intense</content_attribute>
    <content_attribute id="violence-fantasy">intense</content_attribute>
    <content_attribute id="violence-realistic">intense</content_attribute>
    <content_attribute id="violence-sexual">intense</content_attribute>
    <content_attribute id="violence-slavery">intense</content_attribute>
    <content_attribute id="violence-worship">intense</content_attribute>
</content_rating>
```

**Comment by maxtron95** [comment]
@ronny1982 I have posted the files for flathub I made for review here: https://github.com/flathub/flathub/pull/1357

**Comment by maxtron95** [comment]
@ronny1982 Do you have an email address that reflects the HakuNeko Development Team as a whole?

**Comment by maxtron95** [comment]
@ronny1982 I have gotten the flatpak to work and download manga as intended.

Here is the comment about the test build: https://github.com/flathub/flathub/pull/1357#issuecomment-585165676

I will tell you when the flatpak is approved.

**Comment by 27136773** [comment]
Sounds good.
You can just solve the issue when the package gets approved.

**Comment by maxtron95** [comment]
@ronny1982 The good news is that the Flatpak package is almost ready for approval, The bad news is that I need an email address to fix (https://github.com/flathub/flathub/pull/1357#issuecomment-597595795) to finally have the package approved.

**Comment by 27136773** [comment]
You may use hakuneko@byom.de

**Comment by maxtron95** [comment]
@ronny1982 Thank You.

**Comment by maxtron95** [comment]
@ronny1982 The package is now approved on Flathub. Here is the store link if you want to put a badge in the download section. https://flathub.org/apps/details/io.github.hakuneko.HakuNeko

**Comment by maxtron95** [comment]
@ronny1982 You also have an invitation for write access to the flathub repo here.

https://github.com/flathub/io.github.hakuneko.HakuNeko/invitations

**Comment by 27136773** [comment]
Seems really challenging to add a package to FlatHub...
Thank you for the hard work

**Comment by Quinntyx** [comment]
@creepertron95 jsyk the version of ffmpeg in the flatpak is broken 
![image](https://user-images.githubusercontent.com/70780971/153730553-252be7c3-623e-472c-b137-03f1354900f2.png)
-allowed_extensions isn't recognized as an option, so either don't call ffmpeg with that option or fix the version of ffmpeg used please :pray:

**Comment by Quinntyx** [comment]
(could also just be me, my system info is Kubuntu 20.04)
![image](https://user-images.githubusercontent.com/70780971/153730712-c4ebc21c-3f8b-47f9-9f90-9f75f444a00c.png)
![image](https://user-images.githubusercontent.com/70780971/153730728-dd58d431-b112-48ee-b632-86cc5ccdec1a.png)
![image](https://user-images.githubusercontent.com/70780971/153730738-b8982b8f-7e38-4cc4-bec0-f8b9b74024f7.png)
Not sure how much of this could be useful as I don't know how to distribute w/ flatpak or how that works :shrug:

**Comment by beedell-roke** [comment]
@FlareStormGaming, if you continue to experience that problem, please report it separately.
