### ISSUE TITLE
#1011 Jaiminisbox downloads .webp

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1014]
> **From:** HakuNeko User

**Version:** [6.1.7@fc17fd](https://github.com/manga-download/hakuneko/commits/fc17fd)

It shows now but couldn't pull it up previously. Download .webp files (not .jpg0 which don't open. Weird stuff. It shows on the preview like normal though. Thank you for the trouble.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See [FAQ#2](https://github.com/manga-download/hakuneko/wiki/FAQ)

**Comment by 27136773** [comment]
Duplicate of #1011
