### ISSUE TITLE
not downloading

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#102]
> **From:** HakuNeko User

recently i've been trying to download "tower of god" manga from kissmanga but its unable to download some chapters

**Comment by 27136773** [comment]
Which chapters are missing?

**Comment by 27136773** [comment]
HakuNeko provides 429 chapters => The website provides 429 chapters.
Random chapters have been tested and are working as expected.

Closed as there was no additional input provided to reproduce this problem.
