### ISSUE TITLE
add wecomics

### ISSUE THREAD

**Issue by Mammad211** [manga-download/hakuneko#103]
https://m.wecomics.com

**Comment by 27136773** [comment]
The website is region locked to US and may require a VPN to access its content

**Comment by 27136773** [comment]
Works with VPN/Proxy (US, Japan)

Mangalist: https://m.wecomics.com/comic/getIndexList/page/1
=> `data.comic_list: [ { comic_id, title, next_page }, ... ]`

Chapterlist: https://m.wecomics.com/comic/detail/id/36
=> `data.chapter_list [ { chapter_id, title }, ... ]`
