### ISSUE TITLE
Kiss Anime not downloading

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1031]
> **From:** HakuNeko User

**Version:** [6.1.7@c51c34](https://github.com/manga-download/hakuneko/commits/c51c34)

Videos will not download from Kiss Anime due to HydraX. Please switch to Beta Server. (Beta Server is the best to use when downloading directly from the web-site, please add it to HakuNeko so there are no problems)

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by maxtron95** [comment]
Huh, I was able to a successfully download an episode of Show by Rock!! Short!! from KissAnime with that version on a Windows Machine.

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Please provide Anime/Episode and the selected Resolution from Settings.

Beta Server will not be supported.
HydraX is the only one that does not require to solve the Captcha before watching each episode.

**Comment by 27136773** [comment]
No further response => closed
