### ISSUE TITLE
Mangafox download problems

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1032]
> **From:** HakuNeko User

**Version:** [6.1.7@c51c34](https://github.com/manga-download/hakuneko/commits/c51c34)

problems similiar to
https://github.com/manga-download/hakuneko/issues/958
but only mangafox
i don't really understand how to solve the problems, it's too hard for my understanding
please give the detail step to solve the problem

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Which manga/chapter?
Have you done Troubleshooting step by step?
Have you cross-checked that the manga/chapter is working on the website from your browser?

**Comment by 27136773** [comment]
No further response => closed
