### ISSUE TITLE
Cannot download from MangaPlus

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [manga-download/hakuneko#1041]
It still fetches the chapter list, but trying to download returns error "failed to fetch".

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Provide HakuNeko version, manga/chapter and output from developer console...

![image](https://user-images.githubusercontent.com/27136773/73612937-c81c8000-45f0-11ea-882b-748c448475a9.png)

**Comment by l-l-l-l-l-l** [comment]
Scratch that. It seems it was my version's fault. I updated it to the latest stable build and it works again.
