### ISSUE TITLE
1stkissmanga list doesn't synchronize

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1046]
> **From:** HakuNeko User

**Version:** [master@72fcb5](https://github.com/manga-download/hakuneko/commits/72fcb5)

yesterday, i tried to synchronize 1stkissmanga 6 times, and each time show the same files, today tried again without result. And affect all new uploads, not the old files, maybe it's from the crash of the site or other change.....

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction

</details>

**Comment by 27136773** [comment]
Cannot be reproduced with stable release 6.1.7
try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)

![image](https://user-images.githubusercontent.com/27136773/73677993-b520b300-46b7-11ea-8418-884a4ab89ccf.png)
