### ISSUE TITLE
japscan Problem with crypted images

### ISSUE THREAD

**Issue by megacin** [manga-download/hakuneko#1047]
Hello hakuneko team to day i was surprised when im tryed to download image they was crypted like this 
![001](https://user-images.githubusercontent.com/48812724/73653170-e0d87480-4688-11ea-9358-416a5d277e01.jpg)
![002](https://user-images.githubusercontent.com/48812724/73653171-e1710b00-4688-11ea-90ac-eabb7bd8daa1.jpg)
![Uploading 003.jpg…]()

**Comment by 27136773** [comment]
Please provide manga/chapter

**Comment by megacin** [comment]
High School Debut
Kanata Kara
Love Monster
Lovely Devil
Lovely Devil

**Comment by 27136773** [comment]
I accidentally transposed the digits of a number... weird that it worked for some chapters anyway
