### ISSUE TITLE
scantrad won't work

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1050]
> **From:** HakuNeko User

**Version:** [rev.3a8a8f](https://github.com/manga-download/hakuneko/commits/rev.3a8a8f)

impossible to get any chapter on scantrad (french)

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random mangas/chapters.
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and if the problem still occurs, create a new issue and provide at least the manga and chapter.
