### ISSUE TITLE
anime is downloaded in highest quality despite changing settings to "480p"

### ISSUE THREAD

**Issue by dogeatdogeatdog** [manga-download/hakuneko#1056]
i downloaded from 9anime, i tried both mp4upload and mycloud (hydrax doesnt work for me at all for some reason), I have the settings changed to 480p but it still downloaded in 1080p

**Comment by 27136773** [comment]
Not all streaming sources support the selection of the stream quality, it needs to be checked if mp4upload and mycloud have the ability to choose the stream and eventually implement a fix.

**Comment by dogeatdogeatdog** [comment]
Yes I checked, MyCloud has the option to support quality, and 480p is available when checking on 9anime in the browser.
