### ISSUE TITLE
#1011 FAQ 2 & 3

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1058]
> **From:** HakuNeko User

**Version:** [6.1.7@86dbf8](https://github.com/manga-download/hakuneko/commits/86dbf8)

I followed the instruction for post command conversion and all i get is an empty folder and it does it even if it's not .webp. Any ideas? I inputted; mkdir "%PATH%_conv" 2>nul & convert "%PATH%\*.webp" -scene 1 "%PATH%_conv\%03d.png" for mac. instructions mentioned adjustments neccesary for mac, but I have no idea what the adjustment would be.

Thanks. 

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
You may ask this in Discord and/or search google for installing and converting images with ImageMagick's `convert` command on macOS
HakuNeko just invokes a command in the terminal, what the command does is up to the users.
The developers cannot solve such issues as this is not the core competency of this project.
