### ISSUE TITLE
Mangabat

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1059]
> **From:** HakuNeko User

**Version:** [](https://github.com/manga-download/hakuneko/commits/)

unable to download many mangas from mangabat.  The chapters are there but not able to load and download the pages.  

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Please provide sample mangas/chapters for reproduction...
Try [Trpubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
Check if this is a duplicate of #991

**Comment by 27136773** [comment]
No further response => closed
