### ISSUE TITLE
Shonen Pocket Magazine image scrambled

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#1062]
something like this
![001](https://user-images.githubusercontent.com/23132217/74016197-9aef1980-49c4-11ea-94eb-5534b261e61f.jpg)

**Comment by 27136773** [comment]
Which manga / chapter

**Comment by 0xh3LL0** [comment]
https://pocket.shonenmagazine.com/episode/10834108156743736375

**Comment by 27136773** [comment]
Cannot be reproduced on my end
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) make sure using version 6.1.7

![image](https://user-images.githubusercontent.com/27136773/74084055-2a4f0800-4a6b-11ea-9229-097f4b2d8ae8.png)

**Comment by 0xh3LL0** [comment]
![haku](https://user-images.githubusercontent.com/23132217/74095876-88422500-4b29-11ea-85b8-4bff3b3e640c.jpg)

tried to delete the cache folder as well, still didnt work,
i dont mess with the settings, all default, aside from dark theme.

**Comment by 27136773** [comment]
It was possible to reproduce the issue after clearing HakuNeko's chrome cache

**Comment by 27136773** [comment]
It seems there are two different de-scrambling algorithms, `baku` and `usagi`.
While `baku` is already implemented, `usagi` needs to be added.

EDIT: `usagi` is not not scrambled and therefore needs not to be descrambled
