### ISSUE TITLE
Please add https://www.lecture-en-ligne.com/

### ISSUE THREAD

**Issue by snohboy** [manga-download/hakuneko#1063]
hi guys, can you add this site when you next update: https://www.lecture-en-ligne.com/

**Comment by snohboy** [comment]
it may sound silly but I don't know how we use it.

**Comment by 27136773** [comment]
You can't because it is not yet supported...
It will be available once the ticket is resolved.

**Comment by snohboy** [comment]
ok thank you ronny1982

**Comment by MikeZeDev** [comment]
Dead website. @Sheepux please :)

**Comment by Sheepux** [comment]
no alternative domain found
