### ISSUE TITLE
Not able to download chapters

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1064]
> **From:** HakuNeko User

**Version:** [master@44edf2](https://github.com/manga-download/hakuneko/commits/44edf2)

Hi i have download the latest version of hakuneko desktop 7.1.11 but i am able to load and view the chapters but unable to download them. It give me ! and show download failed. I am able to see the chapters from my browser too.

<details><summary>What has been done?</summary>

</details>

**Comment by suikodoen13** [comment]
download rev 6.1.7@86dbf8 and try to download the chapter but again failed. Can advice what to do next?

**Comment by 27136773** [comment]
Provide website / manga / chapter to reproduce

**Comment by suikodoen13** [comment]
Website: MangaHasu and MangaNelo
Manga: All mangas
Chapters: All chapters
![Error 1](https://user-images.githubusercontent.com/60792860/74074941-58bceb00-4a4b-11ea-9e60-0631a4b77567.PNG)

**Comment by suikodoen13** [comment]
Tried uninstall and reinstalling back  rev 6.1.7@86dbf8 a couple of times. It seems I cannot download chapters from all manga website. Running this software on windows 10.

**Comment by 27136773** [comment]
Cannot be reproduced on my end
Open the joblist, hover the mouse over the error icon and check the tooltip text.
Press F12 to open the developer tools, check console tab for errors, check network tab for connection issues.

Also try to download with the portable version of HakuNeko (without changing any settings).

![image](https://user-images.githubusercontent.com/27136773/74083257-3387a700-4a62-11ea-92e5-7f00dee5aa10.png)

![image](https://user-images.githubusercontent.com/27136773/74083277-72b5f800-4a62-11ea-9ceb-2276afc5ab86.png)

**Comment by suikodoen13** [comment]
download the portable version of  HakuNeko and copy the content over. Now when lanching the software, it give me blank screen. 
![Error 1](https://user-images.githubusercontent.com/60792860/74083940-78343200-4aa4-11ea-9587-28fd51e69d06.PNG)

**Comment by suikodoen13** [comment]
![Error 2](https://user-images.githubusercontent.com/60792860/74083956-95690080-4aa4-11ea-8710-2641ae07d15e.PNG)

**Comment by 27136773** [comment]
See: [Troubleshooting#3](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#3-is-the-screen-blankblack-when-starting-hakuneko)

**Comment by suikodoen13** [comment]
Tried troubleshooting mention and patch HakuNeko manually as described. Does not worked.

**Comment by 27136773** [comment]
What about error output?
Start HakuNeko executeable from terminal and check output.
Also press F12 to open the developer tools, check console tab for errors.

**Comment by suikodoen13** [comment]
How to start hakuNeko executeable from terminal?
Tried pressing F12...console tab is empty
![Error 1](https://user-images.githubusercontent.com/60792860/74085928-2b0e8b00-4ab9-11ea-856a-acc8ea9c8f52.PNG)

**Comment by 27136773** [comment]
1. Press windows `Start` button
2. Type `cmd` and press enter, a terminal will poupup
3. Drag hakuneko.exe into terminal and press enter

![image](https://user-images.githubusercontent.com/27136773/74086314-f7fcd500-4a81-11ea-9dfc-31752c4159c2.png)

**Comment by suikodoen13** [comment]
![Error 1](https://user-images.githubusercontent.com/60792860/74086414-8cd0f400-4abd-11ea-802c-68370f0ca0cf.PNG)

**Comment by 27136773** [comment]
You have placed HakuNeko in a directory where your windows user account that is executing HakuNeko has no write access.
Put it into a directory where you are allowed to write files, e.g. Desktop

**Comment by suikodoen13** [comment]
Thanks for the advice. I am able to launch the software after I move it to Desktop. Refresh the mangalist from MangaHasu and try the download. The download still doesn't work. Press F12 to open the developer tools, check console tab for errors shown below. 
![Error 2](https://user-images.githubusercontent.com/60792860/74087498-c575cb00-4ac7-11ea-8b18-c32a3b82deab.PNG)

![Error 3](https://user-images.githubusercontent.com/60792860/74087502-cc044280-4ac7-11ea-8955-0a961ce90507.PNG)

**Comment by 27136773** [comment]
HakuNeko has no access to write into the manga directory...

**Comment by suikodoen13** [comment]
i am able to download the chapters with the previous version 0.4.0. 
How this is version no access write? How to give it access right?

**Comment by suikodoen13** [comment]
Checked properties for hakuneko.exe on mydesktop...it allow read and write access. Not sure what else to do.

![Error 4](https://user-images.githubusercontent.com/60792860/74088471-e6431e00-4ad1-11ea-806e-10377c044560.PNG)

**Comment by 27136773** [comment]
You need to select  a manga directory where HakuNeko has write access.
Or to be more precise, the user that runs HakuNeko needs write access to the manga directory.
Check settings in HakuNeko 0.4.0 and use the same manga directory in HakuNeko 6.1.7

Permissions are not an issue of HakuNeko, this is related to the system and user administration, therefore this can be solved in various different ways and it is up to the system administrator to handle this...

**Comment by suikodoen13** [comment]
I did apply back the same manga directory in HakuNeko 0.4.0 for HakuNeko 6.1.7. 

To check the settings in HakuNelo 0.4.0....i need to reinstall back the software again? What are the settings to look out for? 

Sorry i don't understand how to check which users run HakuNeko in this pc. 

Thanks for being patience with me.

**Comment by 27136773** [comment]
Just select a manga directory where HakuNeko has write access.
I just pointed out to look for the manga directory from 0.4.0 because you said it worked.
You may just select `Desktop` as manga directory for testing purposes...

https://github.com/manga-download/hakuneko/wiki/Quick-Reference#settings

For further questions you may ask the community in [discord channel](https://discord.gg/A5d3NDf) as this seems to be no longer an issue of HakuNeko but more for individual system setup.

**Comment by suikodoen13** [comment]
Thanks for your help so far. The discord channel link doesn't work..i can't ask questions there.

**Comment by 27136773** [comment]
Fixed link
https://discord.gg/A5d3NDf
