### ISSUE TITLE
Japscan problem downloading and reading

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1065]
> **From:** KuraiShin

**Version:** [6.1.7@86dbf8](https://github.com/manga-download/hakuneko/commits/86dbf8)

Hello,

On Japscan, the images do not load correctly and it is impossible to download the chapter (Martial Arts Reigns chapter 1). Sometimes the image is loaded when I start reading, but it remains empty in the preview, while other times the images don't load at all.

The problem also occurs for other mangas except when there are few pages to load.

I tried with different wi-fi and on Windows 10 / Linux and I have this problem no matter where.

The console returns 2 main errors :
GET https://www.japscan.co/lecture-en-ligne/martial-arts-reigns/1/40.html 503
and
GET connector://japscan/?payload=eyJpbWFnZVVSTCI6Imh0dHBzOi8vd3d3LmphcHNjYW4uY28vbGVjdHVyZS1lbi1saWduZS9tYXJ0aWFsLWFydHMtcmVpZ25zLzEvNDIuaHRtbCIsImltYWdlRmlsZSI6Imh0dHBzOi8vYy5qYXBzY2FuLmNvLzc2ZjgyMDcxNDY2MTcwMTE1OGU4ODQ1OGI5OTg2NjExNjhmODMzOTgzNzExYzE1MTUwMjhjODU4NDEyMTY4NjgwMzM4NjBhOGQ3ZTFmOWQ4MzU5ODc2ZTE3MTgxNTBhMTYzMjgwODAxYS8wMjE3OTIxNDFlODkxNjhhMGQ4YTdlODE2MzExOTk4YzY0MTA4ODE3MWUxMDBjOGY0Mjg0MTg4MnphOGIwOTE3NzcyNDBiMmI5ZDI5NjIxMGFhMTEyYzEyNDQxNjhiMjNiMjg4MmExZmEvNTFkNWUyM2EwNzY3Yjg4OTU4M2JkNzU2Yjg2YmQ3NDhjMDBhNjk1MjA5YzRhOTcwZjkyNzcwNHo2Nzc4MTA1OWUwODc1MGI2OTk2ejE3NnlmOTM2OTkzNDE5Yzk1MDU3MjBjNjU5NHoyLzk2YjY3LnBuZyJ9 net::ERR_NOT_IMPLEMENTED

Thank you in advance if you can solve the problem.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Try HakuNeko version 6.1.7
In settings increase throttle to 1500 or 2000 ms
Also download the images first, because live preview causes to much concurrent connections to the server

**Comment by nzoba** [comment]
Thanks for your answer.
I'm already using version 6.1.7
I increased throttle to 2000 ms, downloading works now, thanks.

Will the live preview issue be fixed later or the problem comes from the website?

Thanks again for your awesome work !

**Comment by 27136773** [comment]
Fixing live preview will not be done, it would require a massive amount of work
