### ISSUE TITLE
Mangarock sync error

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#107]
> **From:** HakuNeko User

i think i found a problem, where in mangarock site mangarock.com some manga has updated chapter, but when search with hakuneko the manga doesnt update, it must wait around 1-2 hours until update in hakuneko, please fix it thank :)

**Comment by 27136773** [comment]
Duplicate of #94

**Comment by 27136773** [comment]
Due to lack of time and minor impact this will not be changed
