### ISSUE TITLE
Add portuguese content

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#1075]
There are still few options for reading in Portuguese so it would be great to add new sites, like the ones listed below:

https://mangatoon.mobi/pt/
https://lermangasonline.top/
https://leitor.net/
http://mangaspace.com.br/leitor/
https://mangalivre.net/
http://centraldemangas.online/
https://mangayabu.com/
https://mundomangakun.com.br/leitor-online/
https://saikaiscan.com.br/
http://animaregia.net/
http://leitor.mangascenter.com.br/
https://elitemangas.top/
http://mangafox-br.com/

hentai:
https://hiper.cool/
https://mundohentaioficial.com/
https://mundomangakun.com.br/leitor-online-18/
https://baixarhentai.net/
https://revistasequadrinhos.com/
https://www.superhq.net/
https://hentaikai.com/
https://www.superhentais.com/hentai-manga
https://meuhentai.com/
http://thehentaicomics.com/
https://www.hqdesexo.com/
https://www.tufos.com.br/
https://hentaitokyo.net/

I left several options as I don't know which ones can be added, some have exclusive works, like the mangatoon in Portuguese, and I would be happy if some suggestions could be added, thanks ..

**Comment by 27136773** [comment]
Please make a single issue per website, handling multiple websites within a single issue is not appropriate for development (e.g. PR linking) and feedback loops.

**Comment by RenanMenck** [comment]
Sorry about that, as soon as I have time, I will place an issue for each site listed ..
