### ISSUE TITLE
New essues with japscan

### ISSUE THREAD

**Issue by megacin** [manga-download/hakuneko#1082]
Hello hauneko team to day japscan have the samme problem with crypted image 
![001](https://user-images.githubusercontent.com/48812724/74101482-a2383380-4b3a-11ea-974b-4629cd6e339e.jpg)
![002](https://user-images.githubusercontent.com/48812724/74101484-a401f700-4b3a-11ea-8009-63c31002734a.jpg)
![003](https://user-images.githubusercontent.com/48812724/74101486-a401f700-4b3a-11ea-9c1c-c6624a20c10c.jpg)

Romance Papa
Hot-Blooded Woman
The One
True Love
Watashi No Ookami-Kun

**Comment by 27136773** [comment]
Tracked by #1084
