### ISSUE TITLE
please add this site http://www.jpmanga.com/

### ISSUE THREAD

**Issue by lucifer256** [manga-download/hakuneko#1083]
can this site http://www.jpmanga.com/ can be added

**Comment by speedycatfish** [comment]
I'll try adding this.

**Comment by lucifer256** [comment]
is it done.

**Comment by 27136773** [comment]
It is done when the issue is closed, which maybe somewhere between tomorrow and never...

**Comment by manh21** [comment]
Close this.
See: #2460

**Comment by 27136773** [comment]
See: #2453
