### ISSUE TITLE
Application Closed even when Canceling in Confirmation Dialog

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#11]
Import: https://sourceforge.net/p/hakuneko/tickets/89/
----
If there is a manga downloading and I close HakuNeko then a message pops up asking "Downloads are still in progress. Close application anyway?" If I click Cancel, HakuNeko closes. If I click OK, HakuNeko closes as well.

See also:
https://sourceforge.net/p/hakuneko/discussion/support/thread/b5d82fc37d/

**Comment by 27136773** [comment]
This issue seems to be so simple, but in fact it is quite troublesome to solve for the current versions of electron for the following reasons:

- the bundled chromium browser does not allow to call `confirm()` within the `onbeforeunload` event
- trying to use the dialog provided by electron did also not work since this seems not to be shown modal and the application will just quit ignoring the dialog
- showing the dialog outside of the render process will work, but then the web-application has no control over the decision when to show a confirmation and when not

**Comment by 27136773** [comment]
The implementation has been changed and the `confirm()` method has been replaced to call  a synchronous confirmation dialog in the render thread instead of the chromium confirmation dialog.

However, the window still closes even when cancel the confirmation dialog (except when the develper console is open, then it works as expected)

This seems to be a bug in electron itself: electron/electron#9966

**Comment by ronny1982** [comment]
References: a38cb1ca
