### ISSUE TITLE
Failed to update manga list for <site>

### ISSUE THREAD

**Issue by Skylead** [manga-download/hakuneko#110]
rev. 979d2f

Just clicking on randomly on different site bookmarks and hitting Synchronize will fail somewhere betwen 1/3 and 1/2 of the bookmarks with:

Failed to update manga list for <name>
Please report this broken website on HakuNeko's GitHub project page

Some of the sites I had login credentials for and signed into the web version that launches but while that will usually work it doesn't help the app to update the manga list.

Am I doing something wrong? Or are this many links just broken?

**Comment by 27136773** [comment]
You're not doing anything wrong, there might be plenty of websites that are broken and not yet reported, because no user cared for them yet.
Just open an issue for each website that is not working, so it can be fixed.

**Comment by 27136773** [comment]
Since there are no follow up posts, the question is assumed to be answered

**Comment by Skylead** [comment]
Ah, I should have left a reply. I've been working on a compresenhive test compilation and it's just taken a while since my free time is scattered and some of the sites take a good bit to populate the manga list.

I can just file a new issue or add the server status document in a pull request, whichever you prefer.

**Comment by armbandit82** [comment]
same issue on Isekaiscan

**Comment by 27136773** [comment]
> same issue on Isekaiscan

will be solved with the next update

You may also create a new issue if the broken website is different from the one in the existing ticket, or the ticket is already closed.

**Comment by eliotcdrmm** [comment]
this happens often with toonily (https://toonily.com) 
could you please fix it

thank you

**Comment by AhmadShaaban1** [comment]
Download the portable version , It doesn't have this issue
