### ISSUE TITLE
UnionMangas not loading

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#111]
> **From:** HakuNeko User

some manga sources doesn't load the chapter list. i usually uses unionmanga.top but most of them are not working. the only one that i tested and worked was readcomicsonline

**Comment by 27136773** [comment]
First thing to do: Check if the website is working in your browser.
If the website is working, create an issue here on GitHub for it (just as this one for unionmagas).
At least provide a manga and a chapter to reproduce the problem.

**Comment by 27136773** [comment]
UnionMangas website is offline, there is nothing that can be done in HakuNeko.

![image](https://user-images.githubusercontent.com/27136773/57582084-c8a04400-74c0-11e9-981d-7dba0b20a5e9.png)
