### ISSUE TITLE
Resume partial download instead of restarting from beginning

### ISSUE THREAD

**Issue by kokizzu** [manga-download/hakuneko#1110]
Sometimes when download failed, (because the manga site only uploaded whole volume instead of per chapter), when restarting download it doesn't resume from last downloaded part (eg. half already downloaded) it restart from 0% again

**Comment by 27136773** [comment]
Too much effort to implement such a system.
Furthermore it cannot be assumed that the previously downloaded images are not broken, because the download had failed.

**Comment by kokizzu** [comment]
The problem is, some large manga (1 chapter with 200s pages) always failed to download, but it consumes bandwidth even after when it failed.
just like https://github.com/manga-download/hakuneko/issues/1111 the preview keep downloading partial images (consumes bandwidth) but cancelling in the middle (1-15%) maybe because too short timeout and too late start.
