### ISSUE TITLE
Broken image (timeout) on reader mode

### ISSUE THREAD

**Issue by kokizzu** [manga-download/hakuneko#1111]
Because my bandwidth only 500KB/s max, sometimes when image partially downloaded on the reader mode (and the manga images was a lot (100+)), it got broken image after certain time, and cannot be refreshed (even when clicking other 
manga, then click back to that broken manga again)
![image](https://user-images.githubusercontent.com/1061610/74507986-88c72b00-4f30-11ea-9858-9a16e54b62aa.png)

**Comment by 27136773** [comment]
With the current UI it is not possible, the images are fetched by the browser.
A new UI framework may introduce some lazy-loading mechanism.
Currently there are no milestones for implementing a new UI framework, if it happens, lazy-loading will be considered.

As a workaround, just download the images before previewing them.
