### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1118]
It does not find any of the searches.(Chinese)

site;manhuaniu(Chinese)

İMG;
![Ekran Alıntısı2](https://user-images.githubusercontent.com/10929481/74541650-0f8cff80-4f53-11ea-9c4b-52e2f05cc789.PNG)

**Comment by 27136773** [comment]
Update your manga list as described in [Troubleshooting #6](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#have-you-updated-the-mangalist)

<img width="1232" alt="Screen Shot 2020-02-14 at 10 05 33 PM" src="https://user-images.githubusercontent.com/27136773/74567494-36a8f880-4f76-11ea-9c36-18cae9df8428.png">
