### ISSUE TITLE
MangaToon Manga not opening

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#112]
> **From:** HakuNeko User

MangaToon manga is not opening/viewing after 20th page 
21- end all the page only show 1 image but in website its available.

**Comment by 27136773** [comment]
Probably the chapters are locked for premium users.
Usually all (non-premium) chapters that are shown on the website should be available in HakuNeko.
Could you please provide a (non-premium) webtoon / chapter which is working on the website, but not in HakuNeko?

**Comment by 27136773** [comment]
HakuNeko will be improved to show watermarked images, if no other images are available.
For premium chapters there is nothing that can be done, a dedicated image will indicate that this chapter is locked.
