### ISSUE TITLE
unbalance x3

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1133]
> **From:** joe

**Version:** [6.1.7@d52927](https://github.com/manga-download/hakuneko/commits/d52927)

mangadex Won't show list at all

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Click [sync button](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#4-manga-list) and wait for the spinner to finish (this may take up to 2 hours).

Press F12 to open develpper tools and switch to network tab to trace the connections...
