### ISSUE TITLE
Download stuck on MangaHere

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#114]
> **From:** HakuNeko User

Sometimes the download stuck on one file and never go past it.
Example:
Site: MangaHere
Manga: Hunter X Hunter
The download window shows the chapter "Vol.30 Ch.390" as in progress and nothing happens. The only way to unstuck the applicaiton is to kill it.

There have to be eiter timeout to skip chapter if it is in download state for too long. Or a button in download window to abort current chapter and process the next one in queueu.

**Comment by 27136773** [comment]
There already should be a timeout for each request.
Maybe the problem lies somewhere else, what is shown in the [error console](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#making-an-informative-help-request)?

**Comment by 27136773** [comment]
After further investigation it was discovered that the timeout for the `fetchUI` methods is reset as soon as the browser-window is loaded and the javascript has been injected. When the injected script leads to an exception, the browser-window keeps pending for the result and the timeout is no longer running => deadlock.

The timeout must not be reset, before the injected javascript is completed.

Furthermore any javascript that is injected must not throw an error and should always return a rejecting or resolving promise. Currently the reader page for MangaHere has changed and therefore the injected javascript needs to be adapted as well.

**Comment by rakosi2** [comment]
I am now unable to download anything from Mangahere but I can download from another site like MangaNel
job.html:145
Error: Page "https://www.mangahere.cc/manga/knights_magic/c062/undefined" returned status: 404 - 
    at _wait.then.then.response (job.html:126)
    at <anonymous> ["https://www.mangahere.cc/manga/knights_magic/c062/undefined"]
