### ISSUE TITLE
gmanga bug

### ISSUE THREAD

**Issue by Nitro963** [manga-download/hakuneko#1141]
can't update gmanga.me chapters list nor download from it

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction).
Make sure you have the latest version which is 6.1.7 at the moment.
Some mangas may not have any chapters, check if they exist on the website.

----

![image](https://user-images.githubusercontent.com/27136773/74685213-1d9a8480-51ce-11ea-8676-4e1d320ca8f4.png)

**Comment by Nitro963** [comment]
It turns out it was from my end, I was using version 6.0
Thank you for your reply and sorry for the bothering
