### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by CHRIS-HENRY-M** [manga-download/hakuneko#1142]
App start in searching update after that just blank/white screen. Tried running it with cmd, it gives update error.
![Error](https://user-images.githubusercontent.com/57654587/74628096-ae9e3b00-518f-11ea-88f4-6cdfee0a4697.png)

**Comment by 27136773** [comment]
Issue is tracked in #13 
Make sure the shown update URL in the CMD can be reached.

**Comment by CHRIS-HENRY-M** [comment]
> 
> 
> Issue is tracked in #13
> Make sure the shown update URL in the CMD can be reached.

Tried entering the update URL in the browser. It shows File Not Found.
![Error](https://user-images.githubusercontent.com/57654587/74632973-903e3c80-519b-11ea-907d-a7430f446f3c.png)

**Comment by 27136773** [comment]
Your version of HakuNeko is outdated, download and install 6.1.7

**Comment by CHRIS-HENRY-M** [comment]
Updated the 6.1.7 with a nightly build (7.1.11). Now its working.
