### ISSUE TITLE
Download tidak sempurna

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1145]
> **From:** HakuNeko User

**Version:** [6.1.7@b28493](https://github.com/manga-download/hakuneko/commits/b28493)

ketika download, terdapat chapter yang tidak bisa didownload, padahal ketika di cek di websitenya, ada gambar/image nya, terima kasih

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
There are more than 500 websites, thousands of mangas and chapters.
Please be more specific, which website/manga/chapter?

**Comment by 27136773** [comment]
No further response => closed
