### ISSUE TITLE
KlikManga is not working

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#1150]
Preview and Download feature is error or just show an empty papper. sorry i not have a screenshot because my inet is slow.

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random mangas/chapters.
Please provide sample manga and chapter.

**Comment by MIRVOUS** [comment]
i'm sorry. i test again the manga but now it work. so i think maybe it because my internet is too slow. thanks
