### ISSUE TITLE
KomikIndoWebId is not work properly

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#1152]
when i click preview. it says `failed to fetch`. and download is not working

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random mangas/chapters.
Please provide sample manga and chapter.

**Comment by MIRVOUS** [comment]
i'm sorry. the site is look like maintenance. 
![komikindowebid](https://user-images.githubusercontent.com/45929526/75089996-f4447480-5590-11ea-9404-17e90351c83f.png)

**Comment by 27136773** [comment]
Tested again today and seem to work...
Guess this can be closed
