### ISSUE TITLE
mangazuki.site download fetch

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1154]
Let's set the number of image downloads. While downloading multiple connections, it keeps breaking.
"Manga Chapter 1 Picture 1/24
Manga Chapter 1 Picture 2/24
Manga Chapter 1 Picture 3/24"

I'm tired of pressing download again. I press 9 times again for 1 episode.

![dawdawdw](https://user-images.githubusercontent.com/10929481/74862288-f0301100-535c-11ea-85bd-492c0246eb4c.PNG)

**Comment by areglos** [comment]
When he tries too much, he downloads it one by one. If 40 images are downloaded one by one, it will not give any error.
 
![wwdqwd](https://user-images.githubusercontent.com/10929481/74863286-afd19280-535e-11ea-9a93-f41ce090558d.PNG)

**Comment by 27136773** [comment]
Cannot be reproduced on my end with stable version 6.1.7
I'm afraid here is nothing that an be done from within the application to solve your connection problems
