### ISSUE TITLE
Add BookLive (speedbinb)

### ISSUE THREAD

**Issue by unchartedmeridians** [manga-download/hakuneko#117]
BookLive.jp is the parent company of ComicMetor and consequently uses the same speedbinb unscrambling. I managed to figure out that much but unfortunately anything more is beyond my capabilities. I would like to be able to download shit off there because I resent them forcing me to use their shitty reader to translate their mangas. Well thanks, bye.

**Comment by 27136773** [comment]
The new SpeedBinb version used in BookLive ist quite complex, therefore the implementation will take longer than expected...

Related commits:

- 310158fc
- 35ab7a0d
- 22863170
- 2df222fa
