### ISSUE TITLE
Toomics social media login with manual website interaction

### ISSUE THREAD

**Issue by lickenchittle** [manga-download/hakuneko#1183]
Hi! I am unable to login to toomics with the manual website interaction using a social media sign in (facebook). Clicking on it redirects me to a blank page.
![1](https://user-images.githubusercontent.com/61282408/75104820-69bf4c00-5648-11ea-859d-2fe32607879d.PNG)
![2](https://user-images.githubusercontent.com/61282408/75104822-6cba3c80-5648-11ea-8ccc-27f25bf8434f.PNG)

**Comment by 27136773** [comment]
Google and Facebook are currently in HakuNeko's Blacklist, so they are blocked right now.
Need to improve Blacklist rules to block Google/Facebook tracking, but still allow login.

Affected rules:
```
*://*.accounts.google.com/*
*://*.facebook.com/*
```
