### ISSUE TITLE
téléchargement mangaScan

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1186]
> **From:** HakuNeko User

**Version:** [6.1.7@8ebc34](https://github.com/manga-download/hakuneko/commits/8ebc34)

Bonjour, je n'arrive pas à récupérer les scans à partir du site mangascan. Merci

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
There is no website called MangaScan.
Please be more specific, which website/manga/chapter does not work?

**Comment by 27136773** [comment]
No further response => closed
