### ISSUE TITLE
Can I use this with a vpn?

### ISSUE THREAD

**Issue by d-air1** [manga-download/hakuneko#1189]
The problem is that whenever I end up leaving my vpn on, the app won't load chapters that are not already downloaded. When I turn it off, It loads the chapters I have not downloaded, so that I can know that something is available. Is there anything I can do about this. Some setting for me to use?

**Comment by 27136773** [comment]
Sounds like HakuNeko switched to offline mode.
In general HakuNeko shouldn't have any issues with VPN, as this is not on application level.
You may start HakuNeko from terminal to check for any errors that may appear.

**Comment by d-air1** [comment]
Alright I'll give that a try and report back

**Comment by d-air1** [comment]
@ronny1982 Here is what the terminal outputs .but honestly it doesn't look useful.

hakuneko-desktop
Gtk-Message: 12:18:15.038: Failed to load module "appmenu-gtk-module"

Usage:
  /usr/lib/hakuneko-desktop/hakuneko [OPTIONS]

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default


--------------
Framework Info
--------------
Electron : 6.1.7
Chrome   : 76.0.3809.146
Node     : 12.4.0


-------------
Configuration
-------------
Update URL           : https://manga-download.github.io/hakuneko/6.1.7/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : /home/$USER/.cache/hakuneko-desktop
UserData Directory   : /home/$USER/.config/hakuneko-desktop

Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[2294:0224/121815.740046:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[2294:0224/121817.797581:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[2294:0224/121817.873876:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

**Comment by 27136773** [comment]
Nothing special in the output.
I'm afraid this is an isolated problem related to your system configuration, therefore it can not be solved remotely...

**Comment by thexavier666** [comment]
I am running it via the terminal, and I'm getting the exact same error. I'm using it in a university network, which is behind a proxy. I suspect that the application is **not respecting the proxy variables**, which is why it's getting a timeout error. 

I suspect that it's trying to download the url `https://manga-download.github.io/hakuneko/6.1.7/latest` but it can't. I can access it from my browser (behind the proxy).

**Comment by 27136773** [comment]
Setup your proxy rules in [settings](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#settings) as described in the corresponding tooltip

**Comment by thexavier666** [comment]
> Setup your proxy rules in [settings](https://github.com/manga-download/hakuneko/wiki/Quick-    Reference#settings) as described in the corresponding tooltip

When I start the app, I see a white window with "checking for update". After that, the app simply stops working. I can't even access the settings page. I tried it in i3 and Gnome; no difference. When I start the application from the terminal, I get the same error as OP but nothing else. I can't see/access the settings panel of the app.

**Comment by 27136773** [comment]
Cannot help with white screen...
See: [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#is-the-screen-blankblack-when-starting-hakuneko) for more details
