### ISSUE TITLE
connector Kissmanga CDN not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1195]
> **From:** HakuNeko User

**Version:** [6.1.7@46e887](https://github.com/manga-download/hakuneko/commits/46e887)

Hello i've tried to use KissManga (CDN) but it seems that HakuNeko isn't able to download the manga list (and I guess also there could be problems downloading the titles).

The error is the following:

Failed to update manga list for KissManga (CDN)

ERR_NAME_NOT_RESOLVED
http://kissmanga.hakuneko.download/cdn?ts=1582737784167&rd=0.5962128428543068

This is bad because KissManga CDN is one of the best providers for good quality scans. What makes me wonder is the actual address, never heard a .download website... it's correct ?

Please check if possible,

Best Regards

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Use KissManga directly, the CDN hasn't been updated for several month and is postponed to be removed.
