### ISSUE TITLE
Please insert an adblock like ublock origin inside the native browser

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1196]
> **From:** HakuNeko User

**Version:** [6.1.7@46e887](https://github.com/manga-download/hakuneko/commits/46e887)

It seems that HakuNeko uses an internal browser based on Chrome or Firefox for access websites interaction and so on. This websites are full of popups, and often they lead to virus or malware content with their heavy ad banners.

A good suggestion is to preinstall also ublock origin inside hakuneko browser module so that all this bad stuff is get rid of making safe using the application for website interaction.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Electron does not support extensions.
Try to avoid the internal browser as much as possible.
A [basic blacklist](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/engine/Blacklist.mjs) is already embedded into HakuNeko.
