### ISSUE TITLE
Mangahere tries to download from invalid URL

### ISSUE THREAD

**Issue by rakosi2** [manga-download/hakuneko#120]
I am now unable to download anything from Mangahere but I can download from another site like MangaNel

job.html:145
Error: Page "https://www.mangahere.cc/manga/knights_magic/c062/undefined" returned status: 404 -
at _wait.then.then.response (job.html:126)
at ["https://www.mangahere.cc/manga/knights_magic/c062/undefined"]

**Comment by 27136773** [comment]
In #114 the script for page link detection has been changed.
Unfortunately MangaHere seems to use both scripts, the single-page script and the multi-page script.
Therefore HakuNeko should implement a detection to decide which script shall be used instead of using the one or the other.
