### ISSUE TITLE
Most manga in MangaTown file turn to .bin

### ISSUE THREAD

**Issue by ZackCelestial** [manga-download/hakuneko#1201]
Hello I got problem with manga in mangatown when I try download black clover but not just that manga there a file .bin behind the page name and I can't open when I try change the .bin into picture it just show white page. I already enter mangatown website but there no problem at there please fix it.

**Comment by 27136773** [comment]
Please provide sample manga and chapter

**Comment by 27136773** [comment]
No further response => closed
