### ISSUE TITLE
Problème scan site ScanManga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1202]
> **From:** HakuNeko User

**Version:** [6.1.7@e4b911](https://github.com/manga-download/hakuneko/commits/e4b911)

Bonjour, je n'arrive pas à récupérer les scans du manga Skip beat du site ScanManga (https://www.scan-manga.com/?sm). J'ai essayé avec d'autre mangas du même site mais ca ne fonctionne pas. Merci pour votre aide!

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Cannot be reproduced, please provide the chapter

**Comment by 27136773** [comment]
Isolated probelm... cannot be solved
