### ISSUE TITLE
[Japscan] Images aren't displayed anymore

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1208]
> **From:** HakuNeko User

**Version:** [6.1.7@adffed](https://github.com/manga-download/hakuneko/commits/adffed)

Hello,

I can' read any more chapters from Japscan (error 404 for all images). I guess it comes from the images link that may have changed.
It's the same for every manga but for example The Ghostly Doctor chapter 205 and Pale Throne chapter 37.

If you can fix it, thank you very much.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
JapScan changed website layout (single image => webtoon) and also their image protection

**Comment by megacin** [comment]
where is the solution please

**Comment by megacin** [comment]
i do everhing but it style .bin iextention into images

**Comment by 27136773** [comment]
You have to wait until developer fix it.
As long as the issue is `OPEN`, the problem has not been solved...

**Comment by megacin** [comment]
thanx you very much sur
