### ISSUE TITLE
Japscan website doesnt appear any images

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1209]
> **From:** HakuNeko User

**Version:** [6.1.7@adffed](https://github.com/manga-download/hakuneko/commits/adffed)

Hello , i was trying to downlod images from japscan website but it seems doesnt working, and even if i downlead it , it gives me the bin format , Please fix it i really want to keep updated . Thanks in advance .

<details><summary>What has been done?</summary>

☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction

</details>

**Comment by ronny1982** [comment]
Use the latest version of HakuNeko

**Comment by 27136773** [comment]
See: #1208
