### ISSUE TITLE
ZeroScans manga list does not match website

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1217]
> **From:** HakuNeko User

**Version:** [master@917bf6](https://github.com/manga-download/hakuneko/commits/917bf6)

Hi, the manga list in HakuNeko does not match those available on the website (https://zeroscans.com/comics) e.g. missing Fatal Code, Yong Heng Zhi Zun, etc. Chapter list is showing 0/0 e.g. Peerless Alchemist (https://zeroscans.com/comics/79747-peerless-alchemist)

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Make sure to use the stable release of HakuNeko instead of a nightly build.
Synchronize your manga list to get latest mangas from website.
