### ISSUE TITLE
readcomiconline.to working ?

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#122]
> **From:** HakuNeko User

the website is still online on my browser, and the chapter list load's. but i can't download the chapters. it ends up in an error. what do i do?

**Comment by 27136773** [comment]
Cannot be reproduced, works fine with random comics / chapters.

Please provide additional information:

- comic
- chapter
- console output

See: [Making an Informative Help Request](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#making-an-informative-help-request)

**Comment by 27136773** [comment]
The issue could not be reproduced and there was no further response.
