### ISSUE TITLE
French site ScanManga problem

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1228]
> **From:** HakuNeko User

**Version:** [6.1.7@ed709a](https://github.com/manga-download/hakuneko/commits/ed709a)

Hey, thanks for the job.
I can’t download the scans from the ScanManga site.
I cannot update the manga list (i have an error message " Failed to update manga list for ScanManga - Unexpected end of JSON inpit). And when I click on the manga there is no chapter that appears for any manga on the site ScanManga.

(Sorry for my english...)

Thanks for your help

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
It seems the [manga list / search](https://www.scan-manga.com/scanlation/liste_series.html) on the website itself is broken.
The only option right now is to use the copy & paste feature.
