### ISSUE TITLE
Toomiccs Login

### ISSUE THREAD

**Issue by manhwa** [manga-download/hakuneko#123]
Hi,

Can you please add Toomics (english) log in functionality?

Thanks!

**Comment by 27136773** [comment]
Have you tried [manual login](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#3-account-login)?

**Comment by manhwa** [comment]
Yes, and it's not working. I've attached the main differences I've found between Chrome and HakuNeko

Steps taken:

1. Open HakuNeko
2. Search Toomics
3. Manual Login, then close window
4. Search for "Boys are Boys"
5. Expect a result of 7 chapters, only see the free 2.

HakuNeko Cookie:
``cookie:GTOOMICSpid_last=pid%3DdefaultPid%26subpid%3DdefaultSubPid%26channel%3DdefaultChannel; first_open_episode=Y; GTOOMICSremember_id=a%3A2%3A%7Bs%3A7%3A%22user_id%22%3Bs%3A20%3A%22${REDACTED}%40gmail.com%22%3Bs%3A3%3A%22key%22%3Bs%3A32%3A%2220a7f9dca5e08e687a19a66776f17774%22%3B%7D; GTOOMICSvip_chk=email; GTOOMICSlogin_attempt=Y; GTOOMICSlogin_chk_his=Y; GTOOMICScisession=a%3A7%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%22eed41de23952425793390b7e9dc8c257%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A13%3A%2271.94.197.114%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A120%3A%22Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10.12.6%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F62.16.1531.348+Safari%2F537.%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1558218764%3Bs%3A11%3A%22keep_cookie%22%3Bs%3A1%3A%221%22%3Bs%3A7%3A%22display%22%3Bs%3A1%3A%22A%22%3Bs%3A11%3A%22family_mode%22%3Bs%3A1%3A%22Y%22%3B%7D564d5e39580a5682f1369d17730cef3bc48b4470; GTOOMICSslave=sdb5; GTOOMICScountry=country%3DUS%26time_zone%3D-07%3A00; GTOOMICSpidIntro=1; GTOOMICSacc_log=71.94.197.114; _gat_UA-114646527-1=1; _ga=GA1.2.1287497793.1558218767; _gid=GA1.2.1770257391.1558218767; _fbp=fb.1.1558218767078.1784406676; content_lang=en; GTOOMICSpid_join=pid%3DdefaultPid%26subpid%3DdefaultSubPid%26channel%3DdefaultChannel``
``referer:https://toomics.com``

Chrome Cookie: ${REDACTED} my email
`cookie: _ga=GA1.2.1673413232.1547006793; _fbp=fb.1.1549315888572.106940688; MgidSensorNVis=1; MgidSensorHref=https://global.toomics.com/en/payment/success; GTOOMICSpid_join=pid%3DdefaultPid%26subpid%3DdefaultSubPid%26channel%3DdefaultChannel; ZZAMTOONpid_join_ko=pidko%3DdefaultPid%26subpidko%3DdefaultSubPid%26channelko%3DdefaultChannel; ZZAMTOONpid_last_ko=pidko%3DdefaultPid%26subpidko%3DdefaultSubPid%26channelko%3DdefaultChannel; ZZAMTOONfamily_info=Y; first_open_episode=Y; MZZAMTOONpid_join_ko=pidko%3DdefaultPid%26subpidko%3DdefaultSubPid%26channelko%3DdefaultChannel; MZZAMTOONpid_last_ko=pidko%3DdefaultPid%26subpidko%3DdefaultSubPid%26channelko%3DdefaultChannel; GTOOMICSpid_last=pid%3DdefaultPid%26subpid%3DdefaultSubPid%26channel%3DdefaultChannel; content_lang=en; GTOOMICSslave=sdb5; GTOOMICScountry=country%3DUS%26time_zone%3D-07%3A00; GTOOMICSpidIntro=1; GTOOMICSacc_log=71.94.197.114; _gid=GA1.2.2133996161.1558072443; GTOOMICSlogin_chk_his=Y; PHPSESSID=645259130201523d27418b10be623d69; GTOOMICSremember_id=a%3A2%3A%7Bs%3A7%3A%22user_id%22%3Bs%3A20%3A%22${REDACTED}%40gmail.com%22%3Bs%3A3%3A%22key%22%3Bs%3A32%3A%220ee32bea6aa21046a95b82c4c511c08e%22%3B%7D; GTOOMICSvip_chk=email; GTOOMICSlogin_attempt=Y; _gat_UA-114646527-1=1; GTOOMICScisession=a%3A5%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%22ce82d30c5cfe1389923cc5c484be706b%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A13%3A%2271.94.197.114%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A115%3A%22Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F74.0.3729.157+Safari%2F537.36%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1558218855%3Bs%3A11%3A%22family_mode%22%3Bs%3A1%3A%22Y%22%3B%7D2ed40e099fe60b246c18c9902d34f002b834d5c5`
``referer: https://global.toomics.com/en``

**Comment by 27136773** [comment]
OK, the problem is that HakuNeko has implemented Toomics to only show free chapters, even when logged in. The reason was to prevent users complaining that pages cannot be shown for (non-free) chapters.

Currently i cannot determine how purchased chapters are structured due to lack of a premium account for myself. The only possibility seems to show premium chapters to all users. It is required to decide how this shall be handled...

**Comment by manhwa** [comment]
Can I send you my log in information? Where can I send it

**Comment by 27136773** [comment]
Can you post a screenshot of your chapter-list when logged in, it may help to check which icon and therefore CSS class is applied to the coin type.

![](https://toomics.com/assets/web/img/icon/coin-type1.png) - .coin-type1
![](https://toomics.com/assets/web/img/icon/coin-type2.png) - .coin-type2
![](https://toomics.com/assets/web/img/icon/coin-type3.png) - .coin-type3
![](https://toomics.com/assets/web/img/icon/coin-type4.png) - .coin-type4
![](https://toomics.com/assets/web/img/icon/coin-type5.png) - .coin-type5

![DeepinScreenshot_select-area_20190519012930](https://user-images.githubusercontent.com/27136773/57975952-99646800-79d5-11e9-889d-763ac966449c.png)

**Comment by manhwa** [comment]
![image](https://user-images.githubusercontent.com/50088566/57975968-76f92d00-798a-11e9-8efe-f338deefc014.png)

`<span class="lock"><img src="/assets/web/img/icon/lock-white.png" alt="Purchase and start reading" width="11"></span>`

The lock icon doesn't exist

**Comment by 27136773** [comment]
Please check if it works now

**Comment by manhwa** [comment]
It works now! Thank you for fixing it.

**Comment by ItIsMeCall911** [comment]
Login with G-Account is broken
