### ISSUE TITLE
Japscan: Book downloads start to fail after 98 or 99 pages

### ISSUE THREAD

**Issue by FabLafarge** [manga-download/hakuneko#1247]
Retrying a lot might sometimes work in the end, but it seems to occur randomly
ex : https://www.japscan.co/lecture-en-ligne/saint-seiya-deluxe/volume-22/

nb; using build from master

**Comment by 27136773** [comment]
Try to increase throttle settings for JapScan and try again

**Comment by FabLafarge** [comment]
Throttle at 5000 doesn't help

**Comment by FabLafarge** [comment]
For information, it certainly looks like the bug is about the page determination logic.
Modifying the code for test purpose 
```js
        this.chapter.getPages( ( error, data ) => {
            if( !error && data ) {
                // manga pages
                if( data instanceof Array ) {
                    this._downloadPages( data.slice(90,95), directory, callback );
                    return;
                }
```
--> downloading works ok (just 5 pages obviously)
--> modifying the slice to 95,100 reliably fails the download
