### ISSUE TITLE
Manga not loading at all

### ISSUE THREAD

**Issue by VenomMage** [manga-download/hakuneko#1248]
I'm on Windows 10 and using v 6.1.7.

HakuNeko is not working at all: Nothing seems to load. I've checked the titles myself by visiting the respective websites but HakuNeko doesn't show any results at all. 

Please fix this.

Edit: The websites with the above problem are MangaDex, Manganelo.

**Comment by 27136773** [comment]
Cannot be fixed without knowing the mangas and chapters.
Also see: https://github.com/manga-download/hakuneko/wiki/Troubleshooting

**Comment by 27136773** [comment]
No further response => closed
