### ISSUE TITLE
Japscan

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1251]
> **From:** HakuNeko User

**Version:** [6.1.7@11d5cf](https://github.com/manga-download/hakuneko/commits/11d5cf)

Bonjour,
Je n'arrive pas à lire le manga Silver Wolf : https://www.japscan.co/manga/silver-wolf-blood-bone.
Merci de votre aide.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
See #1247
