### ISSUE TITLE
Cant load the website files

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1257]
> **From:** HakuNeko User

**Version:** [6.1.7@c24153](https://github.com/manga-download/hakuneko/commits/c24153)

Nhentai

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Use the copy & paste feature as stated in the popup dialog
