### ISSUE TITLE
Add manhuagui & other Chinese sites

### ISSUE THREAD

**Issue by su0su0** [manga-download/hakuneko#126]
Thank you for the awesome work! I'm using manga to learn languages and you've saved me a huge amount of time manually downloading ^^ 

If possible could you kindly consider supporting more Chinese sites?
(I'm not asking for all of them, just the one or two you find ok to work on, of course :-) 

https://www.manhuagui.com/ (one of the most popular)
https://www.manhua123.net/
https://www.dagumanhua.com/

and any of these since the 3 sites below are quite similar:
http://www.xueshine.com/
http://www.72qier.com/
http://www.bjeea.net/

**Comment by 27136773** [comment]
Created separate issues
