### ISSUE TITLE
Download problem (mangaherefun)

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1272]
"Mangahere Fun" started to make such mistakes today. It does not download but can be read from the right side. When it comes to downloading, the connection is broken.

![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/76169594-cb280480-618a-11ea-90e9-75100ad3af56.PNG)

**Comment by 27136773** [comment]
Image `19.jpg` is broken and therefore the chapter cannot be downloaded.
Report this to the website, there is nothing that can be done in HakuNeko...
