### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1273]
> **From:** HakuNeko User

**Version:** [6.1.7@9e2b66](https://github.com/manga-download/hakuneko/commits/9e2b66)

psl pls pls..add the acount for webcomicsapp so we can download more chapter..thank you

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Use Manual Login
https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#3-account-login
