### ISSUE TITLE
Chapters not appearing

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1275]
> **From:** HakuNeko User

**Version:** [6.1.7@9e2b66](https://github.com/manga-download/hakuneko/commits/9e2b66)

Chapters are not appearing on MangaWindow site, but manga names are appearing

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random mangas...
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting).
Provide which manga has no chapters.

**Comment by 27136773** [comment]
No further response => closed
