### ISSUE TITLE
site SCAN-MANGA

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1279]
> **From:** HakuNeko User

**Version:** [6.1.7@cf6f60](https://github.com/manga-download/hakuneko/commits/cf6f60)

impossible de télécharger les mangas de SCAN-MANGA

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Cannot be reproduced, please describe in more detail which manga/chapter

**Comment by 27136773** [comment]
Probably duplicate...
See: #1228
