### ISSUE TITLE
Add support for DaGuManHua

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#129]
https://www.dagumanhua.com

Separated from: #126

**Comment by dodieboy** [comment]
link change to https://www.dongmanmanhua.cn/

**Comment by dodieboy** [comment]
link change to https://www.dongmanmanhua.cn/

look like linewebtoon temple

**Comment by dodieboy** [comment]
Website no longer exist

**Comment by XenonR** [comment]
Confirmed. No longer exists.
