### ISSUE TITLE
lezhin free chapters issue

### ISSUE THREAD

**Issue by adsl3f** [manga-download/hakuneko#1290]
Hello,

why Hakuneko isn't able to download Lezhin free chapters anymore?

https://prnt.sc/reg1f9

**Comment by 27136773** [comment]
Cannot be reproduced...
Provide exact website (language), manga and chapter

**Comment by adsl3f** [comment]
Lezhin (english), Man up, girl, all free chapters

I guess the issue is only with adult series. though i browsed the website to check if adult filter is enabled. seems fine

**Comment by 27136773** [comment]
You need to be logged in with your lezhin account to show adult content in HakuNeko.
Even on the website you need to be logged in to view adult chapters.

**Comment by adsl3f** [comment]
@ronny1982 No i found that hakuneko for free chapter uses &purchased=true (it must only be for bought chapters), while it should be &purchased=false to work

**Comment by 27136773** [comment]
It works for me when logged in

----

![image](https://user-images.githubusercontent.com/27136773/76600132-9e674a80-6506-11ea-8d25-f336a36c1275.png)
