### ISSUE TITLE
Japscan again...

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1291]
> **From:** HakuNeko User

**Version:** [master@b9694c](https://github.com/manga-download/hakuneko/commits/b9694c)

malheureusement le telechargement ne marche pas sur japscan...

<details><summary>What has been done?</summary>

☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
It seems i will be busy until weekend and also got some trouble with electron for the implementation.
Don't expect a fix until next week...
