### ISSUE TITLE
Portuguese Sources Don't update manga list

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1297]
> **From:** HakuNeko User

**Version:** [6.1.7@aab591](https://github.com/manga-download/hakuneko/commits/aab591)

have problem with update all portuguese sources!

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting

</details>

**Comment by 27136773** [comment]
Cannot be reproduced with random websites.
Which websites?

**Comment by 27136773** [comment]
No further response => closed
