### ISSUE TITLE
Question: How can i build it as web-application ? 

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#1306]
As stated above i would like to build hakuneko as web-application, even better would be WS, none the less i have quite low understanding of electron and js apps, still though i have a hunch that it could be done cause adding parameter to exe file " --remote-debugging-port=9200" get me to the browser inside the browser...

**Comment by ronny1982** [comment]
HakuNeko is bound to electron, it relies on certain features and therefore it requires at least a virtual display to run.

**Comment by 27136773** [comment]
HakuNeko is bound to electron, it relies on certain features and therefore it requires at least a virtual display to run.

**Comment by Sheepux** [comment]
What is the use case ? Hosting it on the web as an indirect viewer via browser ? (with no ads).
I believe you could break up the engine to expose it as a webservice within nodeJS or Deno. Requires quite a lot of work though.
Edit: or maybe you were thinking about Progressive Web App ?

**Comment by ghost** [comment]
I would like to automate downloading by using the same list of anime i have in sonarr.

**Comment by Sheepux** [comment]
I don't think automated downloading fits within hakuneko policies. There will be new content notification, but probably no auto-downloading. Anyway from a technical point of view, yes it could be done with quite some rework.

**Comment by 27136773** [comment]
I think this can be assumed as answered
