### ISSUE TITLE
error descargando de muchohentai.com

### ISSUE THREAD

**Issue by Luixmc** [manga-download/hakuneko#1312]
tengo un error al intentar descargar de muchohentai y cualquier pagina de anime
en el apartado network me tira este error net::ERR_SPDY_PROTOCOL_ERROR 200, mas concretamente DownloadJob.mjs:215 GET https://par02-edge.tmncdn.io/wp-content/uploads/Kuroinu_Kedakaki_Seijo_wa_Hakudaku_ni_Somaru/episode_6/spanish.mp4.ts?start=1071.666&end=1082.083 net::ERR_SPDY_PROTOCOL_ERROR 200

**Comment by 27136773** [comment]
Cannot be reproduced, probably a server error of the host.

**Comment by Luixmc** [comment]
El error lo descubrí en muchohentai, pero me da en cualquier página de anime

**Comment by 27136773** [comment]
check your internet connection, make sure proxies/vpn are working and are not slow

**Comment by Luixmc** [comment]
No tengo proxy ni con, lo que si formatee el pc hace poco y puede que le falta algún Net framework o algo parecido, tengo una coneccion de 12 megas para subida como para bajadaSent from my Verizon, Samsung Galaxy smartphone
-------- Mensaje original --------De: ronny1982 <notifications@github.com> Fecha: 14/3/20  7:48 a. m.  (GMT-05:00) A: manga-download/hakuneko <hakuneko@noreply.github.com> CC: Luixmc <Luixmc@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [manga-download/hakuneko] error descargando de muchohentai.com (#1312) 
check your internet connection, make sure proxies/vpn are working and are not slow

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/manga-download/hakuneko/issues/1312#issuecomment-599055076",
"url": "https://github.com/manga-download/hakuneko/issues/1312#issuecomment-599055076",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
