### ISSUE TITLE
Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Luixmc** [manga-download/hakuneko#1318]
cuando intento descargar cualquier anime me sale esto: Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
cuando descargo mangas los descarga perfecto, el error es solo en animes, no tengo server proxy ni nada solo estoy conectado por wifi y mi internet funciona perfecto, la verdad no me imagino que sea
https://media.discordapp.net/attachments/581630792120401922/688453718492053528/unknown.png

**Comment by 27136773** [comment]
There is nothing that can be done in HakuNeko
See #1312

**Comment by kokizzu** [comment]
happened also when downloading manga with huge size (with cbz store format), after ~5 minutes then failed, it always show: net::ERR_SPDY_PROTOCOL_ERROR 200 every seconds after failing.

![image](https://user-images.githubusercontent.com/1061610/85231928-7d779500-b425-11ea-9e94-d85a1c7b0864.png)

after no more error (~20 minutes) we could resume again (or restart hakuneko or switching proxy, if not, all next download to the same domain will always failed).

to reproduce, limit your bandwidth to 300-500KB/s (which is already top tier on third world country) and download manga chapter that are larger than 200MB (eg. 200+ pages with 1.5MB each), example on Tsumino: "Watashi ga Toriko ni Natte Yaru" (~300MB) or "Fuwatoro ♥ Jusei Chuudoku" (~300MB) 

![image](https://user-images.githubusercontent.com/1061610/85232124-eca1b900-b426-11ea-8e54-bb3e6dd0b704.png)
