### ISSUE TITLE
website : scan-manga / manga : Mikami-sensei no Aishikata

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1327]
> **From:** HakuNeko User

**Version:** [6.1.7@af7149](https://github.com/manga-download/hakuneko/commits/af7149)

impossible de télécharger les mangas du site scan-manga

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Press F12 to open developer tools and check console/network tab for errors...

![image](https://user-images.githubusercontent.com/27136773/76795931-a3f4b700-67ca-11ea-934d-c653fa069128.png)

**Comment by zazouze** [comment]
Bonjour, j'ai suivis les taches précédentes demandé, je ne pas trouvé de solution. j'ai désinstaller puis réinstaller Hakuneko depuis la version présente sur ce site (https://github.com/manga-download/hakuneko/releases) et suivit les instructions pour mettre les caches a jours en suivant le manuel sur le site. Les problèmes similaires n'ont pas résolu mon problème. Je ne peut pas accéder au site, ni voir les chapitres

si joint les résultats de F12 :
![07](https://user-images.githubusercontent.com/62121714/76840088-e7850a80-6836-11ea-9b81-69f9d1800fbf.png)
![08](https://user-images.githubusercontent.com/62121714/76840093-e9e76480-6836-11ea-8bee-4d6dc9d7a07e.png)
![09](https://user-images.githubusercontent.com/62121714/76840103-ec49be80-6836-11ea-80b4-6d81fd48ae89.png)
![10](https://user-images.githubusercontent.com/62121714/76840113-eeac1880-6836-11ea-940c-df3c307ac2c0.png)
je peux pourtant acceder à la lecture en ligne depuis HakuNeko
![11](https://user-images.githubusercontent.com/62121714/76840277-3cc11c00-6837-11ea-85ec-689e526f81c1.png)

merci pour votre aide

**Comment by 27136773** [comment]
See #1228 
Use the copy & paste feature
