### ISSUE TITLE
Protocol Error.

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1336]
What is?  

Site; Hiperdex  
V; 6.1.7 (Last)
İmage;
![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/76962112-a7558300-692f-11ea-9ee3-d1d64bbf43ef.PNG)

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
This is probably based on connection problems or configuration issues on the website host.
Try to google the shown spdy protocol error, i cannot help with this...
