### ISSUE TITLE
suite problème #1327 scan-manga

### ISSUE THREAD

**Issue by zazouze** [manga-download/hakuneko#1338]
Bonjour, j'ai essayé le copier/coller mais cela ne fonctionne pas non plus. Les chapitres ne s'affiche pas.

![09](https://user-images.githubusercontent.com/62121714/76979037-b7716080-6937-11ea-8ec7-0020ff31d28e.png)
![02](https://user-images.githubusercontent.com/62121714/76979116-d2dc6b80-6937-11ea-889d-d732687e4457.png)
![03](https://user-images.githubusercontent.com/62121714/76979157-de2f9700-6937-11ea-8f0a-48a89bd984bb.png)
![05](https://user-images.githubusercontent.com/62121714/76979166-dff95a80-6937-11ea-9bbc-eaa3c4487739.png)
![06](https://user-images.githubusercontent.com/62121714/76979169-e12a8780-6937-11ea-98b5-169f3d2d988f.png)
![07](https://user-images.githubusercontent.com/62121714/76979173-e25bb480-6937-11ea-9796-d097df3b39ba.png)
![08](https://user-images.githubusercontent.com/62121714/76979177-e38ce180-6937-11ea-9b37-a25eae0b037f.png)

**Comment by 27136773** [comment]
Use the copy & paste feature for now

**Comment by zazouze** [comment]
le problème n'est pas résolu de mon coté. la liste des chapitres n'affiche aucun manga depuis la fenêtre de votre logiciel. alors que sur mon navigateur chrome elle marche.
![03](https://user-images.githubusercontent.com/62121714/77180423-30082680-6aca-11ea-8e95-514409d93308.png)

**Comment by 27136773** [comment]
ScanManga prevents searching when an ad-blocker is installed. HakuNeko has an integrated blacklist, so either synchronize the manga list or copy & paste the links from a browser without ad-blocker...

![image](https://user-images.githubusercontent.com/27136773/77187876-6c8d4f80-6ad5-11ea-90aa-839a4260fbfa.png)

**Comment by zazouze** [comment]
Bonjour, j'ai désinstallé adblock, accepté les cookies et changer mon navigateur par défaut avec un navigateur compatible mais le problème reste inchangé. Je vais faire autrement. Merci comme même pour votre aide et pour votre travail.

![07](https://user-images.githubusercontent.com/62121714/77226919-3f47ac80-6b7c-11ea-9a1f-af836c1de39f.png)
![08](https://user-images.githubusercontent.com/62121714/77226922-4373ca00-6b7c-11ea-8830-2b4a0c317aff.png)
![12](https://user-images.githubusercontent.com/62121714/77226926-479fe780-6b7c-11ea-9ebe-4f4c98b674fc.png)

**Comment by 27136773** [comment]
It is already fixed and works so far on my end.
You need to check on your own whats wrong with the request made to ScanManga in network tab.

<img width="1117" alt="Screen Shot 2020-03-21 at 2 27 05 PM" src="https://user-images.githubusercontent.com/27136773/77227379-42dd3280-6b80-11ea-834e-aae90a9f00ca.png">

**Comment by Ashley344** [comment]
Bonjour, j'ai essayer de télécharger sur un côté dont j'ai l'habitude mais je ne sais pas pourquoi il veulent plus montré les couleurs bleu pour montre que vous pouvez le télécharger. Je comprend pas, J'pensais que ce serait sûrement un beug
