### ISSUE TITLE
Manhwa18 does not work anymore

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1349]
> **From:** HakuNeko User

**Version:** [6.1.7@69073a](https://github.com/manga-download/hakuneko/commits/69073a)

Manhwa18.net and Manhwa18.com does not work anymore, the chapter won't load

<details><summary>What has been done?</summary>

☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction

</details>

**Comment by Ever4engel** [comment]
Work fine on my side. in Which manhwa/chapter you found errors ?

**Comment by 27136773** [comment]
No further response => closed
