### ISSUE TITLE
Timeouts 

### ISSUE THREAD

**Issue by K-snakes** [manga-download/hakuneko#1350]
Hello, im posting this issue because i have no idea whats going on. So i just recently reinstalled windows (I had **HakuNeko** before i reinsalled of course and it was fine)  and when i downloaded **HakuNeko** i started having this weird error.The timeout in 60 second. This one below:

![jkh](https://user-images.githubusercontent.com/49347243/77100851-5923ab00-6a27-11ea-8078-1080f1c03c80.PNG)
 
I tried reinstalling,i tried nightly and stable,i tried different connectors but it still gives me the same error. This is pretty frustrating since i've been trying to fix it for 2 days. So please help me, any help is appreciated!

**Comment by 27136773** [comment]
Carefully go through [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and post the information mentioned in the last point
Furthermore read this:
https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction

**Comment by K-snakes** [comment]
> Carefully go through [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and post the information mentioned in the last point
> Furthermore read this:
> https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction

Thanks for the replay, yes i've seen those beforehand and done whats required but still doesn't work
