### ISSUE TITLE
Mangasy does not work anymore

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#1354]
Update manga list and manga chapter not working at all

**Comment by K-snakes** [comment]
This is what you get when you write a very simple post:

Carefully go through Troubleshooting (https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and post the information mentioned in the last point
Go to number 9 at the bottom of the list  and post the information mentioned in it.

Furthermore read this:
https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction

**Comment by samanta-widjaja** [comment]
its okay @Okabe12322. i just found out they using manual captcha now. thanks

**Comment by K-snakes** [comment]
> its okay @Okabe12322. i just found out they using manual captcha now. thanks

Np
