### ISSUE TITLE
Timeouts every time!

### ISSUE THREAD

**Issue by K-snakes** [manga-download/hakuneko#1355]
***Operating System**: Windows 10 64bit*

***Desktop Client Version**: 6.1.7*

***rev. number**: d87ed9*

***Which website / manga / chapter did not work**: So far most dont work and sometimes kissmanga loads. When i try to preview any chapter of any manga it gives me the error mentioned below*

*(**Chapter Naming Format**: its empty)  (**Host Connections**: i cant find this in the settings)  (Output File Format: folder with images)*

*What is shown in the error log after the problem occurs* :
![fh](https://user-images.githubusercontent.com/49347243/77110262-58464580-6a36-11ea-91a2-94330636354b.PNG)

So i just recently reinstalled windows (I had HakuNeko before i reinsalled of course and it was fine) and when i downloaded HakuNeko i started having this weird error.The timeout in 60 second. This one below:

![jkh](https://user-images.githubusercontent.com/49347243/77109321-c2f68180-6a34-11ea-9c60-631b2623760b.PNG)

I tried reinstalling,i tried nightly and stable,i tried different connectors but it still gives me the same error. This is pretty frustrating since i've been trying to fix it for 2 days. Any help is appreciated! @ronny1982

**Comment by 27136773** [comment]
Have you checked if a captcha is blocking access to the site through HakuNeko?

**Comment by K-snakes** [comment]
> Have you checked if a captcha is blocking access to the site through HakuNeko?

I have but their isn't any captcha's. And i've also tried logging in my account at the site but no luck (inside HakuNeko ofc)

**Comment by K-snakes** [comment]
@ronny1982 Im sorry to mention you but do you know how i can fix this or no?

**Comment by 27136773** [comment]
No i cannot reproduce the issue, this is an isolated problem and needs to be analysed on the specific environment...

**Comment by K-snakes** [comment]
> No i cannot reproduce the issue, this is an isolated problem and needs to be analysed on the specific environment...

So do you think its Network connection related??

**Comment by K-snakes** [comment]
Does firewall effect it also?

**Comment by 27136773** [comment]
I cannot tell

**Comment by K-snakes** [comment]
> I cannot tell

Hmm, alright thanks for ur help and time. If someone has the same problem and its been resolved please mention  me!!

**Comment by 27136773** [comment]
Unable to provide support => closed
