### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by DVampire90** [manga-download/hakuneko#1375]
I am trying to download manga from site: https://myreadingmanga.info  but it's not working. Not long ago there wasn't such problem but not it found the manga but do not show chapter list and give error. Why is that?

**Comment by 27136773** [comment]
Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by 27136773** [comment]
No further response => closed
