### ISSUE TITLE
Comicfire/Hobbyjapan download error

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#1377]
all chapters are available for free, its not paid nor need for login,
open with firefox, no issue...

http://www.hobbyjapan.co.jp/comic/series/3/ 

![hakuerror](https://user-images.githubusercontent.com/23132217/77240966-f694ff80-6c1e-11ea-9d0e-91bd1486a308.jpg)

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting), especially post output from developer tools `console` and `network` tab

**Comment by 0xh3LL0** [comment]
hmm, looks like its just my network issue,
i tried to re-download them, and it works now.
sorry for the inconvenience.
