### ISSUE TITLE
Can't create folder ending in period

### ISSUE THREAD

**Issue by yobleck** [manga-download/hakuneko#1385]
When attempting to download a folder witha name ending in a period it will fail.
Running manjaro linux up to date. an option to edit folder names for just a filter that strips out illegal characters would be nice

tested with 'gaikotsu shotenin hondaa san vol 1 ch 1' kissmanga

**Comment by celiaaitouazzou** [comment]
yourPath = "rep\subrep\subrep\name."
yourPath = yourPath.substring(0, str.length - 1); 

So that now yourPath is without the dot,let me know if it solves the problem :) I'll try to find a way to generalizer that to edit folder names for just a filter that strips out illegal characters

**Comment by 27136773** [comment]
The [sanitizer](https://github.com/manga-download/hakuneko/blob/61f257309ed01a46cd11ba0c289fd830867fed68/src/web/mjs/engine/Storage.mjs#L802) does this currently for windows, but not for linux/mac

**Comment by yobleck** [comment]
> The [sanitizer](https://github.com/manga-download/hakuneko/blob/61f257309ed01a46cd11ba0c289fd830867fed68/src/web/mjs/engine/Storage.mjs#L802) does this currently for windows, but not for linux/mac

editing line 805 of that file to
return path.replace( /[/\r\n\t.]/g, '' ); //see the added period after the \t

worked as a temporary fix for the issue. But to be honest I'm new to github and I'm still learning about pull requests and such so I'm not sure how to request a change.
Also a more permanent fix would require checking to see if the last character of the path variable is a period (instead of removing all periods) sort of like @celiaaitouazzou suggested.

p.s. on an unrelated note I think 'sanatizePath' is misspelled. Should it be 'sanitizePath'?

**Comment by 27136773** [comment]
RegEx Playground: https://regex101.com/r/EQeWC4/1
Yes the method name looks like a typo, but when changing it, make sure all usings are renamed as well.
I make some comments to the linked PR before start to reviewing it
