### ISSUE TITLE
Problem download lectortmo.com 

### ISSUE THREAD

**Issue by devildonovash** [manga-download/hakuneko#1387]
Hi
I am downloading from lectortmo.com and all good, only that the chapters that are made by two allied scans cannot be downloaded.

Example,

Hero Chapter 104? I Quit A Long Time Ago, has the form
Chapter 104.00 [KID'z Scan, HUNTERFANSUB SCAN]
It is made by 2 scans, and chapters of this type cannot be downloaded.

While the Chapters that have the form
Chapter 124.00 [KID'z Scan]
It is performed by 1 single scan, if they can be downloaded.

Thank you so much.

**Comment by 27136773** [comment]
Cannot be reproduced on my end with macOS.
However, there is a line-break between the scanlation groups (as seen in the tooltip) which may lead to problems when storing the chapter.

Which output file format is selected in HakuNeko's settings?

**Comment by 27136773** [comment]
Please check if the problem still occurs after the latest auto-update

<img width="1100" alt="Screen Shot 2020-03-24 at 3 10 58 PM" src="https://user-images.githubusercontent.com/27136773/77434935-e6794d80-6de1-11ea-82aa-1efaeb33de7f.png">

**Comment by devildonovash** [comment]
Hello, After updating Hakuneko.
The images downloaded in the folder are now in the .bin format and have the same size 2,254 bytes.

**Comment by 27136773** [comment]
I cannot reproduce this problem, images are downloaded fine on mac and windows...
Seems to be an isolated problem with your system.
It's up to you to check for errors and perform network analysis with the developer tools (F12) on your system.

And just to make sure, the chapter and images are showing up in your web browser just fine?

**Comment by devildonovash** [comment]
Hello, I restarted my computer and I tried again and everything was fine, thanks friend. All perfect. Problem solved.
