### ISSUE TITLE
Problem lectortmo.com

### ISSUE THREAD

**Issue by devildonovash** [manga-download/hakuneko#1388]
Hi
I am downloading from lectortmo.com and all good, only that the chapters that are made by two allied scans cannot be downloaded.

Example,

Hero Chapter 104? I Quit A Long Time Ago, has the form
Chapter 104.00 [KID'z Scan, HUNTERFANSUB SCAN]
It is made by 2 scans, and chapters of this type cannot be downloaded.

While the Chapters that have the form
Chapter 124.00 [KID'z Scan]
It is performed by 1 single scan, if they can be downloaded.

Thank you so much.

**Comment by 27136773** [comment]
See: #1387
