### ISSUE TITLE
problem download in mangadropout

### ISSUE THREAD

**Issue by fajri411** [manga-download/hakuneko#1389]
there is a problem there mangadropout, can be downloaded but the file in the folder does not exist.
please fix it

**Comment by 27136773** [comment]
Which manga / chapter?
What settings are used for chapter name format?
What settings are used for output file format?

**Comment by fajri411** [comment]
all manga
jpg
jpg
i setting default

**Comment by 27136773** [comment]
It seems the redirection changed, chapters are now listed directly on the page.
The redirect link seems to follow to the original website where the files are sourced from.

**Comment by fajri411** [comment]
so can it be fixed?
