### ISSUE TITLE
Add support for website MangaHost

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#139]
Hello please add
Portugues
http://br.mangahost.com

Separated from: #138

**Comment by 27136773** [comment]
Manga Lists:
https://mangahosted.com/mangas/page/5 (Thumbnails)
https://mangahosted.com/scans/page/5 (Text)

**Comment by hypoflex** [comment]
403 page forbidden

**Comment by hypoflex** [comment]
seems to have blocked a few countries.

tried with vpn servers:
NL - 403
USA - Worked
Brazil - cloudflare IP ban
Germany - 403
Canada - cloudeflare ip ban
Greece - Worked
Belgium - cloudflare block (no ban)
France - Worked
Italy - Worked

**Comment by XenonR** [comment]
Already implemented as `mangahost`
