### ISSUE TITLE
Plenty of mangas are not found in Mangago

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1414]
> **From:** HakuNeko User

**Version:** [6.1.7@e802a9](https://github.com/manga-download/hakuneko/commits/e802a9)

Plenty of mangas are not found in Mangago
Sample titles:
http://www.mangago.me/read-manga/the_road_of_karma/
http://www.mangago.me/read-manga/asura_handol/
http://www.mangago.me/read-manga/vulcan/
http://www.mangago.me/read-manga/i_can_only_betray_earth/

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
See: [FAQ #5](https://github.com/manga-download/hakuneko/wiki/FAQ)
Currently there is no time to maintain the CDN, so it is outdated...
Use Copy & Paste
