### ISSUE TITLE
unable to download the manga in fast internet

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1415]
> **From:** HakuNeko User

**Version:** [6.1.7@e802a9](https://github.com/manga-download/hakuneko/commits/e802a9)

i am unable to download the manga pics berserk from the hakuneko. i tried restart and reinstallation. sometimes reinstallation works. but this time it wont even under high speed internet. please help

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Which website which chapter?

**Comment by 27136773** [comment]
No further response => closed
