### ISSUE TITLE
Site request: moae.jp

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#1416]

**Comment by 27136773** [comment]
Website does not exist, is this region locked?

**Comment by Ever4engel** [comment]
No this website exist, and not region locked.
![Sans titre](https://user-images.githubusercontent.com/47645041/77707652-13865580-6fc6-11ea-8ca4-8154015d0013.jpg)
Ip adress : 54.249.105.200

**Comment by 27136773** [comment]
I see, URL is http://www.moae.jp instead of http://moae.jp

**Comment by MikeZeDev** [comment]
CLosed. Points to "ComicDays", already supported.
