### ISSUE TITLE
can't access heaven manga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1418]
> **From:** HakuNeko User

**Version:** [6.1.7@e802a9](https://github.com/manga-download/hakuneko/commits/e802a9)

can't access heaven manga

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
There are two sources named HeavenManga / Heaven Manga.
Be more specific by providing the ID or URL which is shown in the tooltip.
Also describe which manga / chapter does not work.

**Comment by 27136773** [comment]
No further response => close
