### ISSUE TITLE
JAPscan bug

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1419]
> **From:** HakuNeko User

**Version:** [6.1.7@e802a9](https://github.com/manga-download/hakuneko/commits/e802a9)

How can I fix the problem with Japscan ? It's always written failed to fetch... Thanks a lot.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Which manga / chapter
If not already done, perform [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction)

**Comment by 27136773** [comment]
No further response => closed
