### ISSUE TITLE
mangarockteam problem.

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1421]
Connector; mangarockteam
Prob; Can't refresh the list and Manga does not open.
Site; There is no problem on the site.
![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/77784556-c78dec00-706b-11ea-948a-d413d84e462f.PNG)

**Comment by 27136773** [comment]
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction)...
This is probably DDOS protection, Captcha or Region Lock
