### ISSUE TITLE
new manga not found

### ISSUE THREAD

**Issue by fajri411** [manga-download/hakuneko#1423]
why new manga in mangasusu.mobi and mangadropout new manga not found ? i can't download new mangas

**Comment by 27136773** [comment]
Please give an example manga

**Comment by fajri411** [comment]
ajeosi from mangadropout
stolen from mangasusu,mobi

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Make sure you updated/synced your manga lists as described in the Wiki.

![image](https://user-images.githubusercontent.com/27136773/78022668-a5d78200-7355-11ea-935e-1dde7394b505.png)

![image](https://user-images.githubusercontent.com/27136773/78022603-88a2b380-7355-11ea-9a91-d4262e25571d.png)
