### ISSUE TITLE
Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.

### ISSUE THREAD

**Issue by MadaHaz** [manga-download/hakuneko#1424]
I am trying to download a manga from manganelo ( https://manganelo.com/manga/qe918974 ) but the chapters 1 to 4 give the following error:

**_Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added._**

The strange part is the the error is only given when downloading the files as a _**.pdf**_, if it is downloaded as a _**.jpg**_ or any other image file it downloads correctly. This has happened for many other mangas from multiple sites but I end up just converting them manually. Wanted to see if there is an easier solution.

**Informative Information:**
- Windows 10
- Hakuneko 6.1.7
- Rev. number e802a9
- Website: https://manganelo.com/
   Manga: https://manganelo.com/manga/qe918974
   Chapter: 1, 2, 3 and 4
- I have not set any Chapter Naming Formats or Host Connections.
  Output File Format: .pdf
  De-Scrambling Format: .jpg
  De-Scrambling Quality: 90
- Error Log: Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.

```
mjs/engine/DownloadJob.mjs:145 Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.
    at Object.b.addImage (jspdf.min.js:49)
    at Storage._addImageToPDF (mjs/engine/Storage.mjs:562) Array(41)
(anonymous) @ mjs/engine/DownloadJob.mjs:145

mjs/engine/DownloadJob.mjs:145 Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.
    at Object.b.addImage (jspdf.min.js:49)
    at Storage._addImageToPDF (mjs/engine/Storage.mjs:562) Array(37)
(anonymous) @ mjs/engine/DownloadJob.mjs:145

mjs/engine/DownloadJob.mjs:145 Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.
    at Object.b.addImage (jspdf.min.js:49)
    at Storage._addImageToPDF (mjs/engine/Storage.mjs:562) Array(29)
(anonymous) @ mjs/engine/DownloadJob.mjs:145

mjs/engine/DownloadJob.mjs:145 Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.
    at Object.b.addImage (jspdf.min.js:49)
    at Storage._addImageToPDF (mjs/engine/Storage.mjs:562) Array(29)
```
![image](https://user-images.githubusercontent.com/62794648/77822432-b7970a80-7146-11ea-8908-0277cd55bcfb.png)

Thanks in advance.

**Comment by celiaaitouazzou** [comment]
May I suggest this page :
This has the title 'AddImage does not support files of type 'UNKNOWN' ' . So  Maybe this could help
https://github.com/MrRio/jsPDF/issues/2058

**Comment by 27136773** [comment]
The related bug is tracked: MrRio/jsPDF#2258
I thought jsPDF in HakuNeko has been updated to support JPEG Raw, but seems it was not yet...
