### ISSUE TITLE
KissAnime not working at the moment.

### ISSUE THREAD

**Issue by maxtron95** [manga-download/hakuneko#1425]
I am trying to watch Anime from KissAnime. When I try to watch the anime from HakuNeko, I get the following error message:

`Cannot read property '1' of null`

**Comment by 27136773** [comment]
I cannot reach the website, either they are in maintenance to improve their protection, or they banned all my IPs somehow.

**Comment by 27136773** [comment]
Website is back.
It seems KissAnime no longer provides HydraX mirrors.
All other mirrors require a captcha to be solved before watching.
Need to evaluate how this should be handled...

**Comment by celiaaitouazzou** [comment]
Try gogoanime? Maybe this works, it's my usual anime website. Else, we could try some other anime websites until we find one that works. That's what I usually do in my other projects

**Comment by maxtron95** [comment]
@celiaaitouazzou Does gogoanime have as many anime as KissAnime does? I liked KissAnime because of the huge selection of anime they had.

**Comment by celiaaitouazzou** [comment]
I wish I could answer you but I don't know and I don't know how to quantify the number of anime in gogoanime , nor do I know how to quantify the number in KissAnime so I can't compare. But if we can make it so it works with multiple sites so we can choose the site we take our animes from, we can have more choices

**Comment by 27136773** [comment]
I suggest to create a ticket for gogoanime if you want it to be added.
In the meantime you can still download more popular animes from 9anime

**Comment by maxtron95** [comment]
@ronny1982 Cloudflare (what many manga websites use) is [planning to change its Captcha provider](https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/) to [this](https://www.hcaptcha.com/). I am not sure if this will break the websites that would be using cloudflare captcha already.

**Comment by Tankettekek** [comment]
Hey, Hydrax is back... does this mean it works again?

**Comment by maxtron95** [comment]
I don't think it is, I just tested HakuNeko on Windows 10 and I got this error:

`Failed to fetch`

**Comment by 27136773** [comment]
Yes it seems its back, but during this time HydraX has changed a lot and the current implementation to get streams from HydraX no longer works.

**Comment by 27136773** [comment]
Developer Notes
----

Actually from a brief view in HydraX source code, this looks suspiciously simple...
Maybe there are some hidden pitfalls which are not yet discovered

**Extracted from KissAnime's iFrame:**
_Parameter `v` contains the video slug._
`https://playhydrax.com/?v=4zvc86FYY`

**Stream Domain:**
POST: `https://ping.idocdn.com/`
Referer: `https://playhydrax.com/?v=4zvc86FYY`
Body: `slug=4zvc86FYY`

**Stream Info:**
POST: `https://7s5ce426kc.monster/`
Referer: `https://playhydrax.com/?v=4zvc86FYY`
Body: `slug=4zvc86FYY`

**SD Stream:**
_Subdomain seems to be lowercase of the video slug._
GET: `https://4zvc86fyy.7s5ce426kc.monster/`
Referer: `https://playhydrax.com/?v=4zvc86FYY`
Range: `bytes=0-` (optional range)

**HD Stream:**
_Subdomain seems to be www with lowercase of video slug._
GET: `https://www4zvc86fyy.7s5ce426kc.monster/`
Referer: `https://playhydrax.com/?v=4zvc86FYY`
Range: `bytes=0-` (optional range)

**Comment by maxtron95** [comment]
@ronny1982 While on the topic of KissAnime, Do you think the HakuNeko KissAnime CDN can be updated to add newer anime once the site starts working again?

**Comment by 27136773** [comment]
The CDN scraper is broken since months and i don't have time to fix it.
See: [FAQ#5](https://github.com/manga-download/hakuneko/wiki/FAQ)
