### ISSUE TITLE
Add Web Site

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1431]
Site; http://mangazuki.today/
Site2; http://mangazuki.mobi/
Site3; http://mangazuki.fun/
Site4; http://mangaread.xyz/

**Comment by 27136773** [comment]
Please make a single issue for each website request, multiple requests in a single issue may lead to confusion regarding discussions and related linking of pr/commits

Exception: mangazuj.today and mangazuki.mobi have the same template and may be grouped together in a single request
