### ISSUE TITLE
Tumanga / Lectormanga is not working

### ISSUE THREAD

**Issue by Uc690** [manga-download/hakuneko#1436]
Hi, al this week i've been trying to download mangas in Tumanga but is no working

thanks

**Comment by 27136773** [comment]
Please give an example manga/chapter that did not work

**Comment by Uc690** [comment]
Hi @ronny1982, is not just one manga, in my list i have many mangas from tumanga and kissmanga, the second one is fine but when i try to download mangas in tumanga always said "download failed"

here and example
![Untitled](https://user-images.githubusercontent.com/53823367/78009664-b3583080-7384-11ea-904d-6d1bcaa0ac7c.jpg)
