### ISSUE TITLE
Broken sources: ToonKor; ScanManga; ManhuaGui

### ISSUE THREAD

**Issue by su0su0** [manga-download/hakuneko#144]
HakuNeko rev.486f84

These sources seem to be broken in HakuNeko:
1. [Toonkor](https://toonkor.rest/): ID=toonkor
`Failed to update manga list for Toonkor`
I think this site changed its URL from toonkor.**pink** to toonkor.**rest**

2. [ScanManga](http://www.scan-manga.com/): ID = scanmanga
```
Failed to update manga list for ScanManga
ERR_CONNECTION_TIMED_OUT
https://www.scan-manga.com/?ts=1558443135678&rd=0.045900142174872816
```
(This site doesn't seem to load outside of HakuNeko, either)

3. [ManhuaGui](https://www.manhuagui.com/): ID = manhuagui
```
Failed to update manga list for ManHuaGui
ERR_CONNECTION_TIMED_OUT
https://www.manhuagui.com/?ts=1558442659507&rd=0.6767264064557872
```

(Tested on May 21, 2019. Windows 10)
For the record, I also tested the new sources [Naver Webtoon](https://comic.naver.com/) & [ManhuaTai](https://www.manhuatai.com/) and they're working perfectly :-)

**Comment by 27136773** [comment]
It seems ManhuaGui will ban your IP when scraping the manga list, therefore the scraping needs to be outsourced to HakuNeko's CDN which will then provide the full manga list.

**Comment by 27136773** [comment]
ScanManga works as expected on my end.
The timeout is set to 30 seconds, just keep trying until the initialization can complete within the timeout.

**Comment by 27136773** [comment]
HakuNeko's CDN has been updated to support ManHuaGui.
ManHuaGui has been changed to load the manga list from the CDN.

Related changesets:

- manga-download/cdn.hakuneko@610e349e
- a3bfe9fa

**Comment by 27136773** [comment]
All issues have been adressed
