### ISSUE TITLE
KissManga wont download

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1442]
> **From:** HakuNeko User

**Version:** [6.1.7@31a61c](https://github.com/manga-download/hakuneko/commits/31a61c)

Bookmarked Mangas wont download i'm using KissManga Site 

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Which manga/chapter?

**Comment by 27136773** [comment]
No further response => closed
