### ISSUE TITLE
mangapanda site not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1445]
> **From:** HakuNeko User

**Version:** [6.1.7@31a61c](https://github.com/manga-download/hakuneko/commits/31a61c)

mangapanda site not working, manga list wont update

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Try Troubleshooting again and provide the info from developer tools (F12) console and network tab.

**Comment by hypoflex** [comment]
Seems to be working fine. Did get a report from Anti Virus about possible injection script which is questionable ;HTML/ScrInject.B trojan;

**Comment by 27136773** [comment]
No further response => closed
