### ISSUE TITLE
Add options for the improvement of the program

### ISSUE THREAD

**Issue by sachet61** [manga-download/hakuneko#1446]
1. Add options to stop downloading a specific manga chapter. 
2. Add options to custom download a no.s of chapters instead of downloading whole chapters.
3. Add Options to simultaneous downloading of the chapters.

**Comment by 27136773** [comment]
1. See #8, See #651
2. Filter the chapter list as described in the [documentation](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#chapter-list) before download all
3. Only one chapter can be downloaded at a time per website to prevent server timeouts and users from getting IP banned. Images are already downloaded simultaneous except for websites that are known to IP banning, so their is not much gain for doing the same for chapters...
