### ISSUE TITLE
manganelo.com manga name detection

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1447]
> **From:** HakuNeko User

**Version:** [6.1.7@31a61c](https://github.com/manga-download/hakuneko/commits/31a61c)

since the list for manganelo.com was not able to update. I used the url of the manga for downloading. Everything works fine for the chapter detection and downloading but the name of the manga is not detected and shows randowm names like Manga #0Eb, It would be better if the name of the manga was also detected

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by hypoflex** [comment]
Issue could not be reproduced on my end.
both manga and chapter names are loaded to their respected names

screenshot example would be helpful
