### ISSUE TITLE
Image download fails for JapScan

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1451]
> **From:** HakuNeko User

**Version:** [6.1.7@31a61c](https://github.com/manga-download/hakuneko/commits/31a61c)

viewing and downloading on japscan I don't work anymore

<details><summary>What has been done?</summary>

☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting

</details>

**Comment by 27136773** [comment]
JapScan added some dummy images trying to fool HakuNeko...
I will look into it on the upcoming weekend

**Comment by 27136773** [comment]
From now on i will leave this ticket open as "onging" issue, since this is a non-stop battle against JapScan...
Users can add a comment whenever JapScan stops working, so a new fix can be added again.

**Comment by o01210o** [comment]
Thank you so much for your hard work 💯

**Comment by Krylanc3lo** [comment]
Indeed, thanks a lot for the very hard work!
Please let us know how we can help you :)

It seems that it is still unstable (not working for most of the manga), is it the case for others ?

**Comment by 27136773** [comment]
- Try to increase throttling for JapScan in settings to 3000 ~ 5000
- If a download fails, re-download it again to use the cached image files, but wait one or two minutes because residual image downloads are still running in the background (press F12 see network activity).
- Always download the chapters, never use the preview for non-downloaded chapters (this will start background tasks which will strain the connection to JapScan).

**Comment by Krylanc3lo** [comment]
Thanks a lot for all the advices, I will check right now :)

**Comment by stephvdl** [comment]
Thank you for your job and your advices for japscan. Unfortunetly, nothing works for me... and 50% of mangas I would like to have are only on japscan...

**Comment by darkihchigo13** [comment]
Hi, i have a new problem now with japscan, i change the parameter to increase throttling (4000), the download start and work at the beginning, but after few minutes the hakuno app crash with white screen. I try with an other source (KissManga) but the crash only appear when i download manga from japscan. Just for information i used hakuneko app in Window 10. Thank you for your work !

**Comment by 27136773** [comment]
> Hi, i have a new problem now with japscan, i change the parameter to increase throttling (4000), the download start and work at the beginning, but after few minutes the hakuno app crash with white screen. I try with an other source (KissManga) but the crash only appear when i download manga from japscan. Just for information i used hakuneko app in Window 10. Thank you for your work !

Probably because HakuNeko opens a (hidden) browser window for each webpage with an image. If to many browser windows stack up your systems performance will decrease drastically. Try to increase throttling even more to prevent browser windows from stacking up (e.g. 7500 ms).

**Comment by RMPR** [comment]
Hello, seems there's another regression with Japscan I'm using the latest nightly build hakuneko-desktop_7.1.11_linux_amd64.rpm and I had issues with Black Clover but after trying to download many times, it eventually worked, now no matter how many times I try with other mangas (D-Gray Man, Dr Stone, Fire Brigade Of Flames, ...) it simply doesn't work

**Comment by 27136773** [comment]
Cannot be reproduced on my end, D-Gray Man downloads just fine with stable release...

**Comment by RMPR** [comment]
Weird ... [here](https://youtu.be/9osQzevvt30) Is exactly what happens, do I need to use the stable release absolutely? One thing I may note is that my ~/config/hakuneko-desktop folder is copied from the previous install  (I didn't want to lose my bookmarks  and all) apart from that, I see nothing that can cause this.

**Comment by 27136773** [comment]
Have you read this: https://github.com/manga-download/hakuneko/issues/1451#issuecomment-615505322 and tried throttling 7500
It looks to me like your images are downloading way to fast...

**Comment by RMPR** [comment]
Seems it's working, thanks, out of curiosity why is the throttling by default so low? (For me it was 1000)

**Comment by 27136773** [comment]
Default is `2500`, some people may only download chapters with 5~10 images and have high end systems and fast internet where `1000` may work to speed up downloads.

If this value was set a long long time ago, HakuNeko does not silently overwrite the value set by the user with a new default as long as it is in the supported range, so this may be a relic from old times.

**Comment by XenonR** [comment]
Resolved. Enjoy!
