### ISSUE TITLE
Unable to download Japscan

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1453]
> **From:** Netsuko

**Version:** [6.1.7@31a61c](https://github.com/manga-download/hakuneko/commits/31a61c)

Hi. First of all, thanks for your work. If I can DL on the other websites, I cannot DL on Japsccan.co For exemple, I want to DL Garfiel n°65. The web scan is complet, I can see the Garfield comics, and I click on the n°65. After a while, an error appears: TypeError: Failed to Fetch
I use the last version of Hakuneko and I test somes sites, Japscan is the only with this problem. Thanks and have a good day.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
See #1451
