### ISSUE TITLE
Could not fetch data from nettruyen.com

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1458]
> **From:** HakuNeko User

**Version:** [6.1.7@31a61c](https://github.com/manga-download/hakuneko/commits/31a61c)

Hello there, as the title, I can no longer fetch manga from nettruyen.com. Could you please fix this? Thank you

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by hypoflex** [comment]
Seems like its blocking too many requests.
quickly threw a 5 second timer into the connector which made it work fine again.

**Comment by 27136773** [comment]
Works on my end after clearing the cache directory.
It seems that the initialization sometimes get stuck for some reason and then runs into the timeout...

I'm afraid there is nothing that can be done without a solid reproduction of the problem.

**Comment by zzvilzz** [comment]
Hi, I'm the OP. Clearing cache directory doesn't seem to work on my end. Is there anyway for me to get logs so you can take a look?

**Comment by 27136773** [comment]
as mentioned in troubleshooting press F12 and check Console / Network tabs

**Comment by zzvilzz** [comment]
Please refer to the attached files. The first 9 requests are fine, however the 10th request has no response data

[cache-1586531625202.log](https://github.com/manga-download/hakuneko/files/4462146/cache-1586531625202.log)

![requests](https://user-images.githubusercontent.com/4974305/79001738-37769900-7b79-11ea-987a-456ce5503460.PNG)

**Comment by XenonR** [comment]
Was it a fluke? Works for me (slow connection though, maybe throttling is an option). Or the website introduced throttling?
![Untitled-1](https://user-images.githubusercontent.com/18627623/80910213-3119ae00-8d2e-11ea-8e48-3e3059c59c1c.gif)

@zzvilzz Please test again

**Comment by 27136773** [comment]
I am afraid there is nothing that can be done from developers end.
As workaround use copy & paste feature, so the list is not required...
