### ISSUE TITLE
Add support for website: Funbe [KO]

### ISSUE THREAD

**Issue by su0su0** [manga-download/hakuneko#146]
**Site name**: Funbe
**URL**: http://funbe29.com/
**Language**: Korean
**Content**: Webtoons in Korean. This site is quite similar to [Toonkor](https://toonkor.bar/) (ID=toonkor) but the chapters seem to be more frequently updated.
**Free**: Yes, completely
**Require account/login**: No

**Comment by Ever4engel** [comment]
the last known website adress is :

[funbe](https://funbe29.com/)

Edit: it seem that he's right now down

**Comment by su0su0** [comment]
I can still access the site but it seems that the site has been flagged as phishing (probably due to the many banner ads & popups) so you must click the Proceed button to pass the warning, though. 
A similar site (https://spowiki15.com/) was also targeted.

But the site is slow at the moment. https://newtoki42.com/ is probably a better alternative.

**Comment by Ever4engel** [comment]
Last website adress is : 
[Funbe](https://funbe30.com)
