### ISSUE TITLE
Add Furio Scans (pt-br)

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#1464]
The site: https://furioscans.com, is a scanlation and also uses the WordPressMadara template, so it should be quick and easy to add it ..

**Comment by RenanMenck** [comment]
I didn't know if I should create a change suggestion, but I decided to leave two images that can be used in the Furio Scans logo ..
![furioscans - Copia](https://user-images.githubusercontent.com/55268400/81412257-fba00680-9119-11ea-92e8-ab0820b0df93.jpg)
![furioscans - Copia (2)](https://user-images.githubusercontent.com/55268400/81412262-fcd13380-9119-11ea-8a38-a4dad6738e35.jpg)

**Comment by 27136773** [comment]
Best way is to make a pull request for review

**Comment by RenanMenck** [comment]
How can I create a pull request about this?

**Comment by 27136773** [comment]
I suggest to search for tutorial on how to make a GitHub Pull Request.
Basically create a fork, create a branch, make the changes to the files, create a pull request of your branch to HakuNeko's master repository...

**Comment by RenanMenck** [comment]
I read for hours and I think I got the basics, but I couldn't see how to add a binary file to replace the old logo

**Comment by 27136773** [comment]
In your branch replace the file `src/web/img/connectors/myconnectorid` with the newer image, then commit the changes

**Comment by RenanMenck** [comment]
then this new image must be a link? for example: https://i.imgur.com/ofiTQB5.png, and should I put it as a bbcode, html or direct link?
is this part I did not understand, sorry for all the inconvenience

**Comment by 27136773** [comment]
I suggest to discuss this in discord
