### ISSUE TITLE
MangaToon (English)

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#148]
> **From:** HakuNeko User

- the images of some series are not loaded and can't be downloaded
- for the blocked episodes is no login possible

thank you for your hard work!

**Comment by 27136773** [comment]
Duplicate #112

All you can do is try [manual account login](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#3-account-login), but i think only the mobile app supports access to premium chapters.
