### ISSUE TITLE
Toonkor New URL

### ISSUE THREAD

**Issue by jrdp18** [manga-download/hakuneko#1487]
https://tkor.vip/

**Comment by jrdp18** [comment]
Tried updating manga list, still got

> Failed to receive content from "https://toonkor.yoga/%EC%9B%B9%ED%88%B0/%EC%99%84%EA%B2%B0?fil=%EC%A0%9C%EB%AA%A9" (status: 404) -

**Comment by 27136773** [comment]
Because the changes have not been merged into the 6.1.7 release branch
