### ISSUE TITLE
Cant download from Kisscomics 

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#149]
> **From:** HakuNeko User

Please fix downloading from kisscomics <3

**Comment by 27136773** [comment]
Provide the requested information (see #121, #122), otherwise i cannot help

**Comment by 27136773** [comment]
Also try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [Manual Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction)

**Comment by 27136773** [comment]
The issue could not be reproduced and there was no response providing further information.
=> closed
