### ISSUE TITLE
"Folder with images" chapter format: ability to generate simple index HTML files

### ISSUE THREAD

**Issue by reneguillot** [manga-download/hakuneko#1490]
Hello,

I've recently started using HakuNeko (the latest release 6.1.7@1069c5) and discovered a useability issue with the downloaded "folder with images" format, at least for many comics from the Toonily website.

The downloaded pictures seem to be relatively "fixed format" and they tend to frequently "split" the original comic picture when the images are positioned below each other (either in the HakuNeko reader or the PDF export print). In other words: the pictures have a margin around them that are quite annoying when reading the comics. Attached is an example screenshot, where two of those margins appear in a single comic picture.

![MangaPictureMargins](https://user-images.githubusercontent.com/10559449/78905700-af13cd80-7a7e-11ea-9721-c3e3c2f873d2.png)

I understand that this may be caused by the way how the Toonily website hosts the comic content and that HakuNeko cannot do too much about it by itself. And, I don't know which other of the comic websites would have the same issue.

However, as a workaround, would it be possible to enhance the "Folder with images" chapter format with functionality that automatically generates simple and straightforward HTML files that can serve as navigation (e.g. by chapter)?

I've experimented with this by manually creating an HTML file. This HTML file doesn't have any CSS layout formatting, but simply includes all images below each other, without any margin. This aligns all pictures seamlessly below each other and makes it able to scroll through the comic top-to-bottom without getting disturbed by the image margins.

html
head
titleStory X: Chapter 1/title
/head
body
center
img src="001.webp" br
img src="002.jpg" br
img src="003.jpg" br
img src="004.jpg" br
img src="005.jpg" br
img src="006.webp" br
img src="007.webp" br
img src="008.jpg" br
img src="009.jpg" br
img src="010.jpg" br
...
/center
/body
/html

I'm really interested in your feedback.

Thanks and best regards from The Netherlands.

**Comment by 27136773** [comment]
HakuNeko [Reader](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#reader) has the ability to increase and also decrease the padding between images.
Other reading software should support webtoon strips when reading images.

**Comment by mangatabar** [comment]
![image](https://user-images.githubusercontent.com/46851278/78923303-320a4780-7ac2-11ea-9c99-cb5869298d92.png)

**Comment by reneguillot** [comment]
@ronny1982 @mangatabar Many thanks for your responses. Until now, I did not discover the Reader Control Panel before, but now I've found it.

Great help, thanks again. I'll close this issue.
