### ISSUE TITLE
mangarock team need update/Fix

### ISSUE THREAD

**Issue by mangatabar** [manga-download/hakuneko#1491]
![image](https://user-images.githubusercontent.com/46851278/78922602-02a70b00-7ac1-11ea-94ea-8616b748617c.png)

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
The HTTP Error 503 may be a hint to a captcha, try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction).

**Comment by mangatabar** [comment]
already do that btw manually

**Comment by mangatabar** [comment]
ah nvm it aleady fixed now
