### ISSUE TITLE
 Request to update new website links and add a website to the program.

### ISSUE THREAD

**Issue by urbantbc** [manga-download/hakuneko#1492]
Hello, the links of these["www.mangawt.com", "www.mangagecesi.com", "https://mightyfansub.com/", ] sites need to be renovated/update/fix .... Can you add new updates?   
and finally, can you add ["https://mangaphoenix.com/", "www.serimanga.com"] to the new update?

**Comment by 27136773** [comment]
Please open a single ticket for each single issue.
