### ISSUE TITLE
https://lectortmo.com not support?

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#1493]
For two days the web has not appeared in the program interface. I would like to know if it will no longer have support.

**Comment by 27136773** [comment]
We are not daily monitoring 500+ websites in HakuNeko if they are working or not...
Users have to report broken websites and then they will be checked and fixed.
So if a website does not work that doesn't mean the support was dropped...

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random manga/chapters
Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by 27136773** [comment]
No further response => closed
Maybe the throttling introduced with the PR will resolve openers problems...
