### ISSUE TITLE
Manhuas is connecting but not showing any chapters

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1501]
> **From:** HakuNeko User

**Version:** [master@8b4197](https://github.com/manga-download/hakuneko/commits/8b4197)

Manhuas updates successfully and titles show but no chapters. This is on mac and I have the most recent version. They may have made some changes to the site which could be the problem.

Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Same reason as in #1502 
Probably a new version of WordPress Madara Theme

**Comment by 27136773** [comment]
No longer reproducible, probably fixed with #1525
