### ISSUE TITLE
Chapters not found [hiperdex]

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1502]
Site; https://hiperdex.com/
Prob; I guess it doesn't load the "NEW CHAPTERS" section on the site.
All Manga; They all have the same problem.

Pictures;
![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/79026860-d491fb80-7b92-11ea-8163-a6adc69da85d.PNG)
![Ekran Alıntısı3](https://user-images.githubusercontent.com/10929481/79027092-a103a100-7b93-11ea-837a-3de4fb7fa0fa.PNG)

For site verification purposes;
![Ekran Alıntısı2](https://user-images.githubusercontent.com/10929481/79026864-d8258280-7b92-11ea-85a8-9309716c17bd.PNG)

**Comment by 27136773** [comment]
Chapters are now downloaded via AJAX and inserted lazy...
`<div id="manga-chapters-holder" data-id="861"><i class="fas fa-spinner fa-spin fa-3x"></i></div>`
POST: https://hiperdex.com/wp-admin/admin-ajax.php
Body: `action=manga_get_chapters&manga=861`
