### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by snoopceril** [manga-download/hakuneko#1507]
Good day,

I have been downloading 2 chapter of a certain manga and i am having issues. the manga is ore wo suki nano wa omae dake ka yo. chapters 16 and 18. I have tried two different manga sites (manganelo and mangakakalot) as soure and both are failing. i have the latest app version (6.17@c15c4e). kindly see screen shots for reference. Thank you very much

regards,
snoopceril.

[download error.docx](https://github.com/manga-download/hakuneko/files/4465379/download.error.docx)

**Comment by 27136773** [comment]
Works on my end.
Press F12 and check Console/Network tab for errors...

**Comment by snoopceril** [comment]
Good day,

Tried it today. having the same problem. Kindly see attached file for the error log. thank you very much

regards,
snoopceril

[error log.docx](https://github.com/manga-download/hakuneko/files/4466369/error.log.docx)

**Comment by 27136773** [comment]
Probably duplicate of #1424
