### ISSUE TITLE
Tapas manga list not updating

### ISSUE THREAD

**Issue by jrdp18** [manga-download/hakuneko#1508]
It doesn't seem to recognize Tapas URLs? Tried updating manga list, it finished and got nothing, no error message either.

**Comment by 27136773** [comment]
Works on my end.
Provide sample manga/chapter link.

**Comment by jrdp18** [comment]
https://tapas.io/series/dreamcide
https://tapas.io/series/queenofgods

My bookmarks still work but adding any doesn't.

**Comment by 27136773** [comment]
Copy & Paste still works, but the manga list is no longer updating.
