### ISSUE TITLE
ComicWalker (jp) might change JPEG Encryption Since April 1st, 2020.

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1512]
> **From:** HakuNeko User

**Version:** [6.1.7@c15c4e](https://github.com/manga-download/hakuneko/commits/c15c4e)

In ComicWalker (https://comic-walker.com/), Download images go well, but downloadded .jpg file is not jpeg.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Please provide more details and an example manga/chapter to reproduce the issue

**Comment by Tallesche** [comment]
There is the achive of "アフリカのサラリーマン" Esisode-25、published and downloaded today.
Same result in Windows10 And Ubuntu18.
[第25話.zip](https://github.com/manga-download/hakuneko/files/4466420/25.zip)

Therefor all titles and episodes (include published pre Apr.1) might occur same problem.

**Comment by 0xh3LL0** [comment]
i can confirm this,
looks like the saved images all corrupted.

**Comment by Tallesche** [comment]
I confirmed everything go well. Lots of thanks.
