### ISSUE TITLE
Hiperdex changed their domain from "com" to "net"

### ISSUE THREAD

**Issue by LouVan** [manga-download/hakuneko#1516]
Heyya, could you please take a look on hiperdex? 

I think they changed their website from https://hiperdex.com/ to https://hiperdex.net/ now. It's like a new website, I guess they moved the server or something to be better, because for the past week the website was very slow to access. 

Tried to open the website through Hakuneko app, and it worked just fine, it redirected to the new website.

But when I tried to update the site, it's not working. And it's not showing any new chapters too.

**Comment by Sheepux** [comment]
Are we sure that it's the same site (sure they look alike). The DNS aren't registered with the same registar (could be normal).

**Comment by giaez** [comment]
idk about DNS but I'm redirected to the new domain (.net) when opening the site using its former link (.com/manga)

**Comment by LouVan** [comment]
I really have no idea about the DNS thing. 

But yeah, it's the same site. I've been using the site for a while so I'm sure of that. It might seemed like a new site because they go from ".com" to ".net" now. Might be an entire new site, but idk. 

Still, on Hakuneko it will redirected to the new site, but when it comes to update the list, it will be failed.

**Comment by 27136773** [comment]
Maybe related #1502

**Comment by Sheepux** [comment]
Oh right, i didn't see the redirect from the .com
I guess this one can be closed and we only handle the #1502 (and add the domain change in it)
