### ISSUE TITLE
Not working 1stkissmanga.com, isekaiscan and similar UI websites

### ISSUE THREAD

**Issue by masterbater** [manga-download/hakuneko#1529]
Today I notice any of the websites that has similar ui are not working. Thanks hope we could have a fix soon

**Comment by samanta-widjaja** [comment]
Yes. It's happen from yesterday. I thinks it's because there's a change in Madara. I also hope it's get fixed soon

**Comment by d-air1** [comment]
Here I thought I broke my system again. I'm also affected by this. Let me know if I can help.
