### ISSUE TITLE
tumangaonline changed the domain

### ISSUE THREAD

**Issue by syleniaa** [manga-download/hakuneko#1535]
tumangaonline doesnt work anymore because a few days ago they changed the domain to https://lectortmo.com

**Comment by 27136773** [comment]
Cannot be reproduced.
The domain is up-to-date, try [troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and create a new ticket if the problem persist.

![image](https://user-images.githubusercontent.com/27136773/79439313-f5b07d00-7fd4-11ea-9a57-c868ab52dd48.png)
