### ISSUE TITLE
Japscan failed again

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1538]
> **From:** HakuNeko User

**Version:** [6.1.7@fa9106](https://github.com/manga-download/hakuneko/commits/fa9106)

Thank you for you job ! But there are no amelioration with japscan...it always failed..

<details><summary>What has been done?</summary>

</details>

**Comment by darkihchigo13** [comment]
I also observed that the japscan site still does not work unfortunately. The download goes wrong from the start. 
I tested with the Linux version of HakuNeko and I observe the same problem ...

Thank you again for your work!

**Comment by 27136773** [comment]
See #1451 
Try to increase throttling for JapScan in settings
