### ISSUE TITLE
Folder View Is Not Working

### ISSUE THREAD

**Issue by jammangi** [manga-download/hakuneko#1540]
How to fix this problem 
Failed to update manga list for {Folder View]
ENOENT: no such file or directory, scandir

but when i first use the hakuneko the folder view working but after the update its not working anymore i don`t know how to fix it
![err0r](https://user-images.githubusercontent.com/54354640/79636066-a40c1c00-81a7-11ea-8de7-33930cba91b8.png)

**Comment by 27136773** [comment]
Select a valid folder in settings

**Comment by jammangi** [comment]
but in the bookmark is working just folder view is not working

**Comment by 27136773** [comment]
You need to understand what folder view is, read the tooltip in the settings for `Folder View`

![image](https://user-images.githubusercontent.com/27136773/79645203-1e3f9f00-81ae-11ea-8c93-9e4a11ca1eca.png)
