### ISSUE TITLE
[ReadMangaToday] Picture of Ads displayed instead of manga pictures

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/hakuneko#1541]
Problem : see title

https://i.imgur.com/pDpXlmB.png

How to reproduce : Try to view any chapter from any manga on ReadMangaToday.

Of course i am using latest version atm.

Apparently is not "replacing manga pages" but just an added ad, meaning the appropriate solution would be some kind of filtering

**Comment by Sheepux** [comment]
Indeed there are some ads with img inside
They can be detected with  center class="ad_inline_wrapper affiliate" > a > img

**Comment by Sheepux** [comment]
Found a better way > Filtering images that are of class "img-responsive"
