### ISSUE TITLE
Tumanga unable to view or download

### ISSUE THREAD

**Issue by Uc690** [manga-download/hakuneko#1547]
Hi, as the title said, since yesterday tumanga is unable to update

I attach a screenshot

![image](https://user-images.githubusercontent.com/53823367/79679871-f81d0c00-824c-11ea-87cb-352d40b39bf1.png)

thanks

**Comment by 27136773** [comment]
Solve the captcha
https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection
