### ISSUE TITLE
HakuNeko showing blank white screen on startup

### ISSUE THREAD

**Issue by EvilGodD** [manga-download/hakuneko#1548]
The issue is as the title says HakuNeko showing blank white screen on startup. I installed it just today. I use Haku Neko dekstop version 6.1.7. My windows version is Windows 10 64 bit. Heres an image as to what the screen looks like.
![Screenshot](https://user-images.githubusercontent.com/44601479/79684287-d7a38080-8251-11ea-9f02-d86732a051c0.jpg)

**Comment by 27136773** [comment]
See [FAQ#3](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#is-the-screen-blankblack-when-starting-hakuneko)
