### ISSUE TITLE
TuMangaOnline chapter list is not working anymore

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1549]
> **From:** HakuNeko User

**Version:** [master@a2529d](https://github.com/manga-download/hakuneko/commits/a2529d)

Once you click on Manga name to see its chapters, its not working

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Solve the captcha
https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection

**Comment by Uc690** [comment]
thanks men
