### ISSUE TITLE
Can't Use Kissmanga at All

### ISSUE THREAD

**Issue by d-air1** [manga-download/hakuneko#1552]
I have tried everything I can think of from reinstalling to using the master branch. I've even wiped all config files.

Steps to Reproduce:
1. Install Hakuneko
2. Click the providers button.
3. Search for KissManga
4. Load the manga chapters by clicking the green loading/refresh symbol

Observed Result:
Hakuneko quickly grabs a list of manga seemingly belonging to KissManga. However, clicking on any manga from the list that it has grabbed results in it looking for chapters, but never finding anything. This happens for every manga in the list, so I never make it to the download stage.

Expected Result:
The newly grabbed list of manga should load the chapters for the manga. Which would then proceed to give the user the option to download them.

Background Info:
OS: Fedora 31
Hakuneko Version: 6.1.7 installed through the arm64 rpm
Duration of bug: 4 or 5 days.

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction).
And (i'm repeating myself) always provide a sample manga/chapter, even if you think all mangas/chapters are not working. It is important to have a reference for reproduction.

![image](https://user-images.githubusercontent.com/27136773/79755297-341da300-8319-11ea-9208-87360eaa8c8a.png)

**Comment by d-air1** [comment]
Alright It looks like I must have been banned at some point. I'll close the issue. Thanks for your help.

**Comment by d-air1** [comment]
Looks like KissManga is doing some major up banning.
