### ISSUE TITLE
Site Request: mangapark.today

### ISSUE THREAD

**Issue by RayneSx** [manga-download/hakuneko#1555]
http://mangapark.today/

**Comment by RayneSx** [comment]
There is a mangapark in the list but, even if I tried several times, it cant download the manga list... Anyone knows why?

**Comment by dodieboy** [comment]
@RayneSx  the mangapark in the list work for me, but it take like 1 hour to get the list as it have like 1000+ manga to scan. And BTW the mangapark in the list is a different mangapark. It is https://mangapark.net/
