### ISSUE TITLE
[Manganelo] Some chapters download as blank files ; are not available on reader ; or both.

### ISSUE THREAD

**Issue by Sildran** [manga-download/hakuneko#1557]
Hi :) 

I'm having trouble downloading some of manganelo's mangas. It's been around a week since the issue appeared. 

Some of them download as blank files like "I Was Kicked out of the Hero’s Party Because I Wasn’t a True Companion so I Decided to Have a Slow Life at the Frontier" ch.0016. I can still read it on the reader though. 

Any ideas ?

**Comment by 27136773** [comment]
Probably because of a domain change to `m.manganelo.com`
Works: https://m.manganelo.com/manga-cu116640
Fails: https://manganelo.com/manga-cu116640

**Comment by 27136773** [comment]
Seems the analysis is wrong, while there are two different domains, this is probably not causing the issue.

**Comment by 27136773** [comment]
Can only be partially reproduced on my end.
Sometimes a http 502 error appears for some images, re-downloading solves the issue for me.

**Comment by Sildran** [comment]
Strange. 
I tried re-downloading many times, but I never achieved anything else than the error and blank files. :(

**Comment by samanta-widjaja** [comment]
me too, some of the manga i download only give empty folder such as isekai tensei soudouki

**Comment by 27136773** [comment]
Please provide the console output and check the network connection for errors in the developer tools (F12)

**Comment by ShadowEaglz** [comment]
According to Facebook page manganelo has moved to https://manganelo.link/ (website change post https://www.facebook.com/manganelo/posts/111718767175881?__tn__=-R) and the webpage link on the about section is the manganelo.link
and manganelo.com just hasn't shut down yet. 

EDIT* Now not so sure this is the official Facebook page, if you go to the link, and click on the Official Site in the top bar you go to https://www.mangastream.cc/ which appears to be the exact same layout and such.

**Comment by 27136773** [comment]
Probably same issue as #1674, which was solved in #1681 
If the problem still consist, create a new issue...
