### ISSUE TITLE
hey , i cant read manga from japscan is there anyway you can fix that issue , thanks in advence .

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1559]
> **From:** HakuNeko User

**Version:** [6.1.7@60dd33](https://github.com/manga-download/hakuneko/commits/60dd33)

hey , i cant read manga from japscan is there anyway you can fix that issue , thanks in advence .

<details><summary>What has been done?</summary>

</details>

**Comment by Sheepux** [comment]
duplicate #1451
