### ISSUE TITLE
Kissmanga not showing chapters

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#156]
> **From:** HakuNeko User

Hello, KissManga titles are showing but chapters are not. Previously noticed that connection was slowing down greatly but now simply times out. The site itself is working properly. 

Thank you

**Comment by 27136773** [comment]
Cannot be reproduced, works fine on my end.

Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [Manual Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction).
Please provide [detailed information](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#making-an-informative-help-request) to reproduce the issue (manga, chapter, console output, ...).

**Comment by 27136773** [comment]
No further information has been provided
