### ISSUE TITLE
mangafox and mangahere missing 1 page per chapter

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1562]
> **From:** HakuNeko User

**Version:** [6.1.7@60dd33](https://github.com/manga-download/hakuneko/commits/60dd33)

those two sites frequently have 1 page missing in majority of chapters of a lot of manga, the missing page is the last page pls fix, try kimi no koto ga daidaidaidaidai

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
This is a regression caused by 58b50127 (removing ad page)
Sample:
https://fanfox.net/manga/kimi_no_koto_ga_daidaidaidaidai_suki_na_100_nin_no_kanojo/c001/1.html#ipg60

**Comment by Sheepux** [comment]
Looks like some chapters don't include the ad (i tested quite a lot of them).
I guess we can rollback the commit.
