### ISSUE TITLE
[Mangadex] Mangadex not downloading correctly even with user logged in

### ISSUE THREAD

**Issue by syleniaa** [manga-download/hakuneko#1569]
I am trying to download this manga https://mangadex.org/title/35013/why-are-you-doing-this-duke ffrom mangadex, with my user i can acces it from the web, even i opened it in the viewer from the hakuneko app , i logged in how it is explained in the guide, but when i am trying to download it , it gave gave error.

**Comment by 27136773** [comment]
I can not access it from the website (with my account), so i cannot confirm if this is an issue or not

![image](https://user-images.githubusercontent.com/27136773/79924782-0891da00-8439-11ea-9dc1-5af7522dafe1.png)

**Comment by Ever4engel** [comment]
some mangas already have this problem. have to be solved from mangadex's discord 
(an admin must unlock something in your account)
i personnaly done this several months a go 

Without an account this occur 
![image](https://user-images.githubusercontent.com/47645041/80261741-9238e600-868b-11ea-850a-baa30c690f7f.png)

With locked account same problem 
![image](https://user-images.githubusercontent.com/47645041/80261887-0d020100-868c-11ea-8832-7407b7977d75.png)

With my account (unlocked one):
![image](https://user-images.githubusercontent.com/47645041/80261982-4fc3d900-868c-11ea-9412-0e7a37ff0b63.png)

i can read online and even download it so there is no problem here.
P.S: best practice is to not set your mangadex IDs in hakuneko you may be banned.

**Comment by 27136773** [comment]
Problem could not be reproduced/confirmed => closed
