### ISSUE TITLE
https://hayalistic.com/  

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1574]
> **From:** HakuNeko User

**Version:** [6.1.7@5af33d](https://github.com/manga-download/hakuneko/commits/5af33d)

could you add
manga site in Turkish
https://hayalistic.com/webtoonoku

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
URL: https://manga.hayalistic.com
Template: WordPress Madara
