### ISSUE TITLE
Site Request:mangaship.com

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1576]
> **From:** Collector

**Version:** [](https://github.com/manga-download/hakuneko/commits/)

manga site in Turkish
https://www.mangaship.com/

<details><summary>What has been done?</summary>

</details>

**Comment by newaccforhc** [comment]
@ronny1982 Isn't this site already added?? I think you forgot to close/mention this issue..

**Comment by 27136773** [comment]
Yes you are right, added in #608
Please check if the website exist before making a ticket
