### ISSUE TITLE
[Site Request] nicovideo.jp

### ISSUE THREAD

**Issue by Neutronoid** [manga-download/hakuneko#1588]
**Name of the website**
Niconico

**Website urls (examples below)**
- Site: https://seiga.nicovideo.jp/
- Manga List: https://seiga.nicovideo.jp/manga/
- Manga example: https://seiga.nicovideo.jp/comic/40198
- Chapter online viewer example: https://seiga.nicovideo.jp/watch/mg385240

**Languages**
Japanese

**Comment by Ever4engel** [comment]
Duplicate (issue [#25](https://github.com/manga-download/hakuneko/issues/25))
