### ISSUE TITLE
[MangaCross] Connector not working for some chapters

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#1599]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Some chapters' files are downloaded as .bin files, however are in fact .jpg files easily renamed to be as such. The page urls themselves end with .jpg.

**To Reproduce**
1. Name of connector
MangaCross
2. Name of manga (if connector update is working)
僕の心のヤバイやつ
3. Name of chapter (if manga update is working)
Karte.1
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
N/A

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
master@HEAD

**Comment by XenonR** [comment]
My wild guess is it because `Content-Type: image/jpeg` is not present in the response header of the image. Also I don't know how to fix that.

**Comment by 27136773** [comment]
Confirmed, some chapters are providing images without the `Content-Type` header, therefore the image format is unknown and `.bin` is used as extension
