### ISSUE TITLE
I can't find some Manga on Manga List "TuMangaOnline"

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1600]
> **From:** HakuNeko User

**Version:** [master@67ae3f](https://github.com/manga-download/hakuneko/commits/67ae3f)

I can't find some manga on Manga list for the website "TuMangaOnline" and this is an exemples:

City Superb Fairy
Kill The Hero
Sword Sheath's Child
The Rebirth Of The Demon God
Dungeon Reset
Guardian of the Witch

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
The manga list comes from a CDN and due to lack of time hasn't changed in the last 6 month.
Use copy & paste feature instead.
