### ISSUE TITLE
#1601 additional info

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1603]
> **From:** HakuNeko User

**Version:** [master@621fd6](https://github.com/manga-download/hakuneko/commits/621fd6)

on manhuaplus site, if you double click image contents an alert pops up saying, content is protected. Hope this helps.

THanks.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See: #1601
