### ISSUE TITLE
ADD mavimanga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1615]
> **From:** 

**Version:** [](https://github.com/manga-download/hakuneko/commits/)

https://mavimanga.com/
manga site in Turkish
theme: my manga reader

<details><summary>What has been done?</summary>

</details>

**Comment by newaccforhc** [comment]
@ronny1982 Close this... I've already added it (Duplicate of #1880 )

**Comment by 27136773** [comment]
See #1880
