### ISSUE TITLE
Add support for website: JisuManhua 极速漫画 (js518.net) [ZH]

### ISSUE THREAD

**Issue by su0su0** [manga-download/hakuneko#162]
**Site name**: JisuManhua (极速漫画)
**URL**:  http://www.js518.net
**Language**: Chinese (Simplified)
**Content**: Manga in Chinese (and some raws in Japanese)
**Free**: Yes
**Require account/login**: No

**Comment by MikeZeDev** [comment]
404 not found. Dead website?

**Comment by MikeZeDev** [comment]
Dead
