### ISSUE TITLE
Unable to Reply to Open Issues because Admin Closed them to Soon. 

### ISSUE THREAD

**Issue by Iloveboobs84** [manga-download/hakuneko#1629]
Concerning my other Issue that was Closed, Prematurely FAQ#5 Only said to use the  Link Copy & Paste feature to access the latest mangas within HakuNeko not the HOW TO part. Because that would help explain how to do that within the program and wouldn't need further comments. It's easier to wait and close an ISSUE once resolved not before.

**Comment by ronny1982** [comment]
You can still reply to closed issues.
An issue is closed when there is no work that needs to be done.

As already stated in #1628, the copy & paste feature is described in the [Quick Start - Manga List Panel](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list), the corresponding section is even linked in FAQ#5.

Use the Wiki or Discord if additional information is required.
