### ISSUE TITLE
#1601 & #1603 ManhuaPlus

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1634]
> **From:** HakuNeko User

**Version:** [7.1.11](https://github.com/manga-download/hakuneko/commits/7.1.11)

I issue was closed but the problem is still there without any info on what happened. Was the problem unsolvable?

Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
There only need to be one open issue, duplicates such as #1603 or #1634 are closed.
See #1601
