### ISSUE TITLE
[Webtoons (formerly Line Webtoon English)] - multiple pages

### ISSUE THREAD

**Issue by arromdee** [manga-download/hakuneko#1635]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Line Webtoon English (Webtoons) has manga on multiple pages.  hakuneko only shows the first page.  For instance, The Gamer has hundreds of chapters.  If you go to the page https://www.webtoons.com/en/action/the-gamer/list?title_no=88 you see ten chapters, plus more chapters on other pages at the bottom, up to 33 pages (some of which require going forward by 10 pages at a time),  hakuneko only allows downloading the ten chapters that appear on the first page.

**To Reproduce**
1. Name of connector: Line Webtoon (English)
2. Name of manga: The Gamer)
3. Name of chapter: 1
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): No relevant

**HakuNeko (please complete the following information):**
 Version 6.1.7

**Comment by XenonR** [comment]
After the first chapter page the second page will be an age verification instead. This can be circumvented by not providing the cookie information from the previous request in the consecutive queries request header. 
The connector itself seems to be aware of multiple pages but stalls when hitting the age verification.
