### ISSUE TITLE
gmanga site proplem

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1637]
> **From:** HakuNeko User

**Version:** [6.1.7@68781b](https://github.com/manga-download/hakuneko/commits/68781b)

the gmanga site is downloading an embty chpters and also the pics of the manga arent loading

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by XenonR** [comment]
Tested with Dokebi Cafe - Vol.0 Ch.2, works.
Can you pleas provide an example?

**Comment by 27136773** [comment]
No further response => closed
