### ISSUE TITLE
Hakuneko does not update manga list on mangago

### ISSUE THREAD

**Issue by eirinikl** [manga-download/hakuneko#1638]
**Describe the bug**
HakuNeko does not update the manga list of the mangago.me online reader, even though it updates the chapter list of existing manga without problems.

**Context (please complete the following information):**
 - OS: Windows 7 Enterprise N version 6.1
 - HakuNeko Version  6.1.7

**Comment by 27136773** [comment]
See [FAQ#5](https://github.com/manga-download/hakuneko/wiki/FAQ)
The list on the CDN hasn't been updated for months, use copy & paste to download manga
