### ISSUE TITLE
[Bug] reaperscans not working

### ISSUE THREAD

**Issue by Ognisty321** [manga-download/hakuneko#1641]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
**No**

**Describe the bug**
When i'm trying to read manhwa from reaperscans i have only see this red error
https://i.imgur.com/g2sqGU8.png

**To Reproduce**
1. Select random manhwa from reaperscans
2. Done

**Expected behavior**

**Screenshots**
https://i.imgur.com/g2sqGU8.png

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]
OS: Windows 10 x64
HakuNeku Version: 6.1.7@68781b

**Additional context**
==

Is it possible to fix this, or its only on my side?

**Comment by Ognisty321** [comment]
Neverming, i have seen https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction

You can close this, sorry for not checking

**Comment by 27136773** [comment]
Closed as requested
