### ISSUE TITLE
MangaEden image downloads are forbidden

### ISSUE THREAD

**Issue by Edogaroedogaro** [manga-download/hakuneko#1642]
Comics are not downloading, files are just a few kb. It is not possible to download anything...

**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Please fill the missing information, it does not even provide website, manga and chapter name to reproduce the issue...

**Comment by Edogaroedogaro** [comment]
It is failing on all mangas I have tried...

**Comment by 27136773** [comment]
Works for me, tested with random

![image](https://user-images.githubusercontent.com/27136773/80922034-9b584000-8d7a-11ea-882f-c90a9feb8595.png)

**Comment by Sheepux** [comment]
Also works fine for me.
Try going on the website with a chrome browser on your computer to see if there is something happening.

**Comment by Edogaroedogaro** [comment]
Ok, I will try it a bit later... Thanks!

**Comment by Edogaroedogaro** [comment]
I tried bleach from manga Eden and it does not work for me, it downloads very small files that do not open

**Comment by Edogaroedogaro** [comment]
Same problem with hinomaro zumou from manga Eden...

**Comment by Sheepux** [comment]
Did you try on the website itself with a chrome browser ?

**Comment by 27136773** [comment]
Access to images from MangEden is forbidden.
We probably need to adjust [_handleConnectorURI](https://github.com/manga-download/hakuneko/blob/0b789dad58e6e1fafb578adbc390fe8b2b0da723/src/web/mjs/connectors/templates/MangaEden.mjs#L102), maybe update the host or add the `x-referer` field to the `Header` ...

![image](https://user-images.githubusercontent.com/27136773/80956294-35fb6200-8e01-11ea-8d9a-0795ef242b2b.png)

**Comment by XenonR** [comment]
Same is true for the IT connector. Problem seems to be in here: https://github.com/manga-download/hakuneko/blob/91a70e99fc0688e74a6c1e2e1246e42c857cba22/src/web/mjs/connectors/templates/MangaEden.mjs#L90
The pages variable from one line above is good to go and includes `//cdn.mangaeden.com` but pageList contains some weird things eg. `//mangaeden-it/?payload=Imh0dHBzOi8vY2Ru…Tc5MGU4MTdjYzM2NDA2ZWVjYTVkM2FhZWFhNjM4LmpwZyI%3D`
What's the purpose of `createConnectorURI(...)`?
