### ISSUE TITLE
Could you please the sorting in alphabic by defualt or maybe make an option for it

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1646]
> **From:** HakuNeko User

**Version:** [6.1.7@68781b](https://github.com/manga-download/hakuneko/commits/68781b)

Could you please the sorting in alphabic by defualt or maybe make an option for it. thanks

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Need steps to reproduce...
What list are you referring to, mangas, chapters, settings, ...?
Which website/manga/chapter?

**Comment by 27136773** [comment]
No further response => closed

**Comment by Aces-and-Jacks** [comment]
chapters?
