### ISSUE TITLE
1st Kiss Manga not working

### ISSUE THREAD

**Issue by NatsukazeAi** [manga-download/hakuneko#1648]
I used Hakuneko for 3 months and after 2 weeks not opening the program some of web not working like this one. I only can open from LHscan only. and for English translation sometime same. How to fix this problem?
![bug](https://user-images.githubusercontent.com/50528325/80924658-62d55800-8db4-11ea-8d6d-9a97c0a1ae9e.png)

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Try [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) to check if the website is maybe region locked or protected by Captcha

**Comment by TurboUWU** [comment]
Hello there. 
Have the same issue with most of the big providers. 
<img width="830" alt="Capture" src="https://user-images.githubusercontent.com/64796003/80988958-edfa3080-8e3c-11ea-8b15-ce2c68522d88.PNG">

**Comment by NatsukazeAi** [comment]
> Hello there.
> Have the same issue with most of the big providers.
> <img alt="Capture" width="830" src="https://user-images.githubusercontent.com/64796003/80988958-edfa3080-8e3c-11ea-8b15-ce2c68522d88.PNG">

are you already in any web execpt that?

**Comment by TurboUWU** [comment]
Hello!

Yep, I could log onto most of the very small websites but
batoto/mangadex/japscan were all returning an error message.

**Comment by 27136773** [comment]
Please create separate issues for websites that are not working, i don't think the problems are related.
This issue is now assigned to `1st Kiss Manga`

**Comment by NatsukazeAi** [comment]
> Please create separate issues for websites that are not working, i don't think the problems are related.
> This issue is now assigned to `1st Kiss Manga`

Do you need the list of not working manga website? Perhaps i can make separates issues with that. So it's easy to know which one is working and not.

**Comment by 27136773** [comment]
Create a single issue for each website you really want to use, but that is not working.
Do not create issues for websites that are broken, but which you are not going to use.

**Comment by NatsukazeAi** [comment]
>Create a single issue for each website you really want to use, but that is not working.
understood.

**Comment by 27136773** [comment]
I think this issue cannot be resolved remotely, since this seems system/infrastructure specific ...
