### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1668]
> **From:** HakuNeko User

**Version:** [6.1.7@68781b](https://github.com/manga-download/hakuneko/commits/68781b)

after one dl, the progam crash thx

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Which website/manga/chapter?
What does "crash" mean exactly (there is no common interpretation of "crash" as discussed in previous issues ...)?
e.g. does the application closes unexpectedly, does it freeze, ...

**Comment by 27136773** [comment]
No further response => closed
