### ISSUE TITLE
Add support for website: FuManhua 腐漫画 (fmhuaa.com) [ZH]

### ISSUE THREAD

**Issue by su0su0** [manga-download/hakuneko#167]
**Site name**: FuManhua (腐漫画)
**URL**:   http://www.fmhuaa.com/
**Language**: Chinese (Simplified)
**Content**: Manga in Chinese, mostly aimed at women
**Free**: Yes
**Require account/login**: No

**Comment by dodieboy** [comment]
new URL: http://mh.fmhua.com/

**Comment by MikeZeDev** [comment]
Cant reach website?
