### ISSUE TITLE
[Feature] Multiple downloads in one click? Everything hotlinked to manganelo?

### ISSUE THREAD

**Issue by HighOnBuffs** [manga-download/hakuneko#1671]
Hi i love the tool but i feel like it needs a function to download from a certain chapter in one click (maybe with shiftclick).
Also what is this hotlinking? Soo many manga are hotlinked to manganelo and if there is a chapter missing i cant go to mangakakalot for example?

**Comment by 27136773** [comment]
See the download all button (2) in the Wiki section describing the [chapter list](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#chapter-list).
A hotlink means that the website did not provide the chapter, instead you must download it from the website mentioned in the message box, e.g. `MangaNel`
