### ISSUE TITLE
ADD SİTE MangaWAR

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1672]
> **From:** HakuNeko User

**Version:** [6.1.7@68781b](https://github.com/manga-download/hakuneko/commits/68781b)

mangawar.com
theme : wordpress madara

<details><summary>What has been done?</summary>

</details>

**Comment by XenonR** [comment]
The server is not reachable. Neither from US nor from EU. Possibly dead.

**Comment by 27136773** [comment]
Additional information required from opener:
Which country (IP) you used to access the website?

**Comment by XenonR** [comment]
It's back. https://mangawar.com
