### ISSUE TITLE
Crunchyroll Manga Fails to update and fetch list

### ISSUE THREAD

**Issue by z94fm** [manga-download/hakuneko#1673]
I am trying to get updates for "Tales of Wedding Rings" from Crunchyroll Manga but all I get is a pop up window saying 
     Failed to update manga list for CrunchyRoll* (Manga)

       Failed to recieve content from
      ...://api.crunchyroll.com/login.o.json?device_id=2fa9e3886d132f87&device_type=com.crun...
     (status:405) - 
can you or somebody please fix this? I did read the trouble shoot, Ican open the site in my browser( Chrome

**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end when logged in with free account and using proxy from germany.

![image](https://user-images.githubusercontent.com/27136773/81229294-d911ce80-8fef-11ea-8dc9-19043adc7ce7.png)

**Comment by z94fm** [comment]
I Admit i don't know much about code but when iI saw the revision 6.1.7 in your download page I went back and noticed that my version did not show 6.1.x only the numbers after. Even the update checker didn't find the updated verison. After doing a manual update everything now is working fine. So you can close this problem. Sorry for the trouble
