### ISSUE TITLE
Empty Manga Folder After Download

### ISSUE THREAD

**Issue by ZackCelestial** [manga-download/hakuneko#1674]
Hello I got weird problem when finish download some manga and the chapter folder are empty even thought the download are complete when I try click the image sometime it doesn't appear the page after I close the software and try open it again the page was appear but some page become white when I try click that white page it just jump to another page sometime it show that image page.This problem not just from one manga only.

**Comment by ZackCelestial** [comment]
and one more thing about the empty folder when finish download it I try check on software the image and the image was not there , when I delete the chapter and close the software and try open it again the  page in software appear even thought it doesn't after I download it and close many time.

**Comment by 27136773** [comment]
Please provide website/manga/chapter for reproduction...

**Comment by ZackCelestial** [comment]
https://manganelo.com/chapter/black_clover/chapter_123 this is one for example I try to download before and has probelm and I try to download again and no problem anymore.

**Comment by ZackCelestial** [comment]
oh yeah and not just from that website I try download manga but some are from another site but got same problem so Ithought maybe its because my internet speed?

**Comment by ZackCelestial** [comment]
https://manganelo.com/chapter/black_clover/chapter_187 and now this one chapter got same problem too when I just want download now it doesn't happen to this chapter before like this problem not just effect to same manga and chapter but sometime to other.
