### ISSUE TITLE
Add site request - martialscans.com

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1676]
> **From:** HakuNeko User

**Version:** [master@45bec1](https://github.com/manga-download/hakuneko/commits/45bec1)

When you get the chance, would you please add martialscans.com to the repertoire?

Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Template: WordPressMadara
