### ISSUE TITLE
Smut / Mature content from mangapark.net not showing [Bug]

### ISSUE THREAD

**Issue by ManhaReader** [manga-download/hakuneko#1680]
for example: My Stepmom 

:)

**Comment by 27136773** [comment]
Cannot be reproduced on my end, provide chapter

![image](https://user-images.githubusercontent.com/27136773/81331061-4fbad480-90a1-11ea-9d84-99da618e4455.png)

**Comment by ManhaReader** [comment]
oh right, it works with the ctrl+v option :)

**Comment by XenonR** [comment]
Issue resolved by user feedback.
