### ISSUE TITLE
kissmanga new manga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1684]
> **From:** HakuNeko User

**Version:** [6.1.7@a56e3c](https://github.com/manga-download/hakuneko/commits/a56e3c)

pls updatge the manga list for kissmanga there are so many new manga that i want to download tnx

<details><summary>What has been done?</summary>

</details>

**Comment by XenonR** [comment]
Works fast for me. Can you provide more information?

**Comment by XenonR** [comment]
Please provide an example manga/chapter.

**Comment by 27136773** [comment]
See [FAQ#5](https://github.com/manga-download/hakuneko/wiki/FAQ)
The list on the CDN hasn't been updated for months, use copy & paste to download manga
