### ISSUE TITLE
download speed

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1685]
> **From:** HakuNeko User

**Version:** [6.1.7@a56e3c](https://github.com/manga-download/hakuneko/commits/a56e3c)

kissmanga downlaods slower than the other sites pls like mangahere and fox pls fix

<details><summary>What has been done?</summary>

</details>

**Comment by XenonR** [comment]
Works fast for me. Can you provide more information?

**Comment by 27136773** [comment]
HakuNeko usually uses max. speed, if not then this is to protect the user from getting IP banned
