### ISSUE TITLE
site add request - ManhuaUs.com

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1694]
> **From:** HakuNeko User

**Version:** [master@7674e2](https://github.com/manga-download/hakuneko/commits/7674e2)

Yeah, there is an extra "U" so not to be confused with "manhuas.net".

Thank you for everything.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Template: WordPress Madara
