### ISSUE TITLE
KissManga (both of them)

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1695]
> **From:** HakuNeko User

**Version:** [master@f6d8a4](https://github.com/manga-download/hakuneko/commits/f6d8a4)

Sky Sword God shows on the site but not on HN. The update works fine so I can't figure it out. Not sure if other titles have this issue.

Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by XenonR** [comment]
Please refer to the [FAQ](https://github.com/manga-download/hakuneko/wiki/FAQ) point 5.
