### ISSUE TITLE
API mangarock error?

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#170]
> **From:** Mangarock Fan

last time i post here someone said it because the api just delay. but.. it has been 4 days the manga didnt get update some of them

**Comment by mangatabar** [comment]
well same problem here

**Comment by 27136773** [comment]
Which manga/chapter?

**Comment by 27136773** [comment]
Could be related to fmd-project-team/FMD#211

**Comment by mangatabar** [comment]
idk about the fmd project but after reinstell the hakuneko it back normal. but some manga still out off date

**Comment by 27136773** [comment]
Cannot be reproduced, tested various of the latest updated mangas/chapters from the website and HakuNeko can download all of them.

Please provide the manga/chapter that is not working, otherwise this issue cannot be analyzed and solved.

**Comment by PeterBurner** [comment]
I'm experiencing the same issue  
here an example:  Eiyuu Kyoushitsu  
<img width="1196" alt="grafik" src="https://user-images.githubusercontent.com/15011953/58974423-a26d7b80-87c2-11e9-8f29-6030646b74a0.png">  
  
<img width="556" alt="grafik" src="https://user-images.githubusercontent.com/15011953/58974451-b1542e00-87c2-11e9-94a6-d706d956fd07.png">

**Comment by 27136773** [comment]
Due to the provided information it was possible to reproduce and fix the issue.

**Comment by AnselmJeong** [comment]
Mangarock do not respond to update list command since 2 days ago.

![image](https://user-images.githubusercontent.com/1776524/59094491-34a38a00-8951-11e9-8fe9-3fc1ec5bfbe9.png)

It is not the matter of some mangas or chapters or any licence issue. I've deleted the downloaded cache and re-installed the program. Then I cannot retrieve any of the manga list.

**Comment by 27136773** [comment]
Cannot be reproduced on my end, list update works as expected.
Maybe the website was temporarily not available.
Is this still not working?

**Comment by mangatabar** [comment]
well it back to normal for now(?)

**Comment by 27136773** [comment]
Issue closed, please open a new issue if there is still a problem
