### ISSUE TITLE
Nightly or Stable?

### ISSUE THREAD

**Issue by K-snakes** [manga-download/hakuneko#1701]
Hello, im wondering which Hakuneko i should download;
Nightly or Stable?
**Whats the difference?**

**Comment by 27136773** [comment]
Latest Features vs. Stability ...
The Nightly Build description summarized when to use

<img width="651" alt="Screen Shot 2020-05-09 at 1 46 37 PM" src="https://user-images.githubusercontent.com/27136773/81472994-0e8b0780-91fc-11ea-9d85-7cbc4c8eec1e.png">

**Comment by K-snakes** [comment]
OK thanks
