### ISSUE TITLE
CDN - Link Copy & Paste

### ISSUE THREAD

**Issue by K-snakes** [manga-download/hakuneko#1702]
Im wondering how to manually update the CDN so i can update a manga list.
Also how do i use the Link Copy & Paste feature to access the latest mangas within HakuNeko?
I've read the FAQ but it doesn't show any steps or instructions. 
I've also tried downloading the CDN for the manga list but there seems to be no download button

**Comment by 27136773** [comment]
CDN infrastructure is going to be removed, only way is Copy & Paste.
See FAQ#5, for further questions discuss on discord
