### ISSUE TITLE
[Feature] Login option for Comic Days

### ISSUE THREAD

**Issue by newaccforhc** [manga-download/hakuneko#1704]
**Is your feature request related to a problem? Please describe.**
Some comics in comic-days are free but they don't say it's free... They label it as 0pt So, you can't view unless you login... So, You can't even download it without logging in. Also, someone might have a paid account and want to download the content.
Example: https://comic-days.com/episode/10834108156644703846 (this chapter is actually free but labelled as 0pt by comic-days)

**Describe the solution you'd like**
Just add an option to login like you added for crunchyroll and many other sites.

**Describe alternatives you've considered**
None

**Context (please complete the following information):**
I think it's latest version because it just did an update check when I started and didn't say anything about new version.

**Additional context**
see above link.

**Comment by 27136773** [comment]
Try login via [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#3-account-login)
I think there won't be added any website accounts to the settings in the future
