### ISSUE TITLE
[LoliVault] Connector not working

### ISSUE THREAD

**Issue by alan-ford** [manga-download/hakuneko#1712]
Please remove this connector, the site has closed.

**Comment by 27136773** [comment]
Works fine for me
https://lolivault.net/online/

![image](https://user-images.githubusercontent.com/27136773/81561344-58f2bc80-9393-11ea-8b27-c720c4936e32.png)

**Comment by alan-ford** [comment]
@ronny1982 For me no

![Istantanea_2020-05-11_14-55-13](https://user-images.githubusercontent.com/44990009/81564759-89892500-9398-11ea-800f-a2d1ffc3c967.png)

**Comment by 27136773** [comment]
Check if the website works for you, check manual website interaction as described in Wiki, perform troubleshooting, ...

**Comment by Sheepux** [comment]
I can confirm that https://lolivault.net/ is returning a 404 error from haku & external browser.
Could be a random temporary issue (that  could explain why it's working on your site Ronny).
To be checked for a few days.

**Comment by 27136773** [comment]
Just tested after your post...
Website works in browser (ensured it was not cached)
Website worked in HakuNeko (cleared chrome cache)

**Comment by Sheepux** [comment]
Maybe some kind of IP filtering ? Going to ask on the discord for user testings.

**Comment by Sheepux** [comment]
Location filtering probably  confirmed by https://geopeeker.com/fetch/?url=https%3A%2F%2Flolivault.net
It's not working for Ireland, and on discord users from France, Romania confirmed the HTTP 404.

Should we add some detailled information on the error message for this connector ?

**Comment by 27136773** [comment]
No other website that is region blocked is using any message yet, usually the troubleshooting guide covers this: Check if the website is working in your browser...

We should not be responsible to track all those 500+ websites from all possible countries and notifying users of possible region blocks, that would be to much effort.
