### ISSUE TITLE
[ManhuaTai] Connector not working

### ISSUE THREAD

**Issue by dodieboy** [manga-download/hakuneko#1714]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Get error when loading manga with url
![image](https://user-images.githubusercontent.com/9015764/81560375-dfbf8d80-93c3-11ea-976a-c46977f08984.png)

If possible, please add the mangalist support for this site too
Mangalist: https://www.manhuatai.com/sort/

**Comment by 27136773** [comment]
@dodieboy 
I added a new template `MHXK` or `123mh` which seems to be used for many more chinese websites.

If you encounter a chinese website you can verify if it is based on the `MHXK` template by opening any comic and check the network traffic for any URL containing `product_id`, `productname` and `platformname` parameters.

P.S. Based on the customer ID for Kai Manhua, there are at least 14 websites using this template...

![image](https://user-images.githubusercontent.com/27136773/82053950-776ff500-96be-11ea-9eba-a703b42bb136.png)

References #1715
References #1716
References #1717

**Comment by dodieboy** [comment]
Thks @ronny1982, was working on it too but too busy this week
