### ISSUE TITLE
add hayalistic

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1723]
> **From:** HakuNeko User

**Version:** [6.1.7@e322fb](https://github.com/manga-download/hakuneko/commits/e322fb)

http://manga.hayalistic.com/
turkhis manga web site
"madara"

<details><summary>What has been done?</summary>

</details>

**Comment by Sheepux** [comment]
Duplicate #1574

**Comment by komarna** [comment]
https://github.com/manga-download/hakuneko/issues/1574
https://hayalistic.com/webtoonoku
this site is not working anymore. Don’t add.

Hayalistic’s new site is in this topic.
https://github.com/manga-download/hakuneko/issues/1723
http://manga.hayalistic.com/ 
Please add this.

**Comment by Sheepux** [comment]
That's the same site anyway. This issue will stay as closed. you can comment on the other one if you want to.
Edit: Ronny already did.
