### ISSUE TITLE
[Site Request] Comic Trail

### ISSUE THREAD

**Issue by MaximilianoIkarus** [manga-download/hakuneko#1726]
**Name of the website**
Comic Trail

**Website urls (examples below)**
- Site: https://comic-trail.jp/
- Manga List: https://comic-trail.jp/series
- Manga example: https://comic-trail.jp/series/motokano
- Chapter online viewer example: https://comic-trail.jp/pt/motokano_00001_fB8SimYJ/

**Languages**
Japanese

**Comment by 27136773** [comment]
See: #1337
