### ISSUE TITLE
Failed to Download All Images From HentaiFox

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1727]
> **From:** HakuNeko User

**Version:** [6.1.7@e322fb](https://github.com/manga-download/hakuneko/commits/e322fb)

When I Download chapters from hentaifox it only selects 10 images to download and disregards everything else.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Please provide a sample manga/chapter where this problem occurs

**Comment by 27136773** [comment]
Reproducible with "GOOD"

**Comment by celiaaitouazzou** [comment]
KissAnime is now working : https://kissanime.ru.com/

**Comment by 27136773** [comment]
Create a new ticket for KissAnime RU COM
