### ISSUE TITLE
Save File

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1728]
> **From:** HakuNeko User

**Version:** [6.1.7@e322fb](https://github.com/manga-download/hakuneko/commits/e322fb)

Hello, is there any setting for save file without chapter folder ? Thanks

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
No, this wold lead name to collisions as any image in a chapter starts with 001
CBZ, PDF and EPUB can be used instead.
You can write a `Post Command` script in the settings that does what you want
