### ISSUE TITLE
[Feature] Auto download

### ISSUE THREAD

**Issue by HuyHuuNgocNguyen** [manga-download/hakuneko#1729]
Can I set up an automatic update tool for manga that is available by the hour?

**Comment by 27136773** [comment]
No, [HakuNeko's philosophy is against mass downloading](https://github.com/manga-download/hakuneko/blob/f8702cf43c2fba91d7a96e5497b4e5691de14333/README.asciidoc#3-introduction), it is for manga lovers not for manga leechers... you may use FMD instead

**Comment by HuyHuuNgocNguyen** [comment]
What is FMW? Can you explain FMW more clearly? Please!

Vào Th 6, 15 thg 5, 2020 vào lúc 16:21 ronny1982 <notifications@github.com>
đã viết:
