### ISSUE TITLE
Mangago new mangas for 2020 not working

### ISSUE THREAD

**Issue by mpolintan** [manga-download/hakuneko#1737]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Mangago new mangas for 2020 not working

**To Reproduce**
1. Mangago
2. Life as a Dog-Man Owner, Imprisoned and Bound in a Honey Flower, Dream Demon
3. All chapters
4. 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Check manual website interaction for captcha.
Open developer tools (F12) and check console/network tab for errors.

![image](https://user-images.githubusercontent.com/27136773/82141622-60a0de00-9837-11ea-895c-0de679195661.png)

**Comment by mpolintan** [comment]
> 
> 
> Cannot be reproduced on my end.
> Check manual website interaction for captcha.
> Open developer tools (F12) and check console/network tab for errors.
> 
> ![image](https://user-images.githubusercontent.com/27136773/82141622-60a0de00-9837-11ea-895c-0de679195661.png)

MAC is working but windows is not *image attached
![Screenshot 1](https://user-images.githubusercontent.com/65488651/82142790-7af7ad80-9871-11ea-8bd4-a7bb8350b154.png)

**Comment by 27136773** [comment]
This is expected behavior, as stated in the error message, there is no manga list available, you need to use copy & paste, see related [FAQ #5](https://github.com/manga-download/hakuneko/wiki/FAQ)
You probably still have a very old manga list on your mac which can no longer be updated...
