### ISSUE TITLE
[Kissmanga] Connector not working

### ISSUE THREAD

**Issue by Uc690** [manga-download/hakuneko#1740]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not possible to update and download

**Screenshots**
![image](https://user-images.githubusercontent.com/53823367/82144147-f7968600-9889-11ea-8997-510ecb4eeda0.png)

**HakuNeko (please complete the following information):**
 - Version 7.1.11

thanks

**Comment by 27136773** [comment]
This is expected behavior, as stated in the error message, there is no longer a manga list available on the server, you need to use copy & paste feature, see related [FAQ #5](https://github.com/manga-download/hakuneko/wiki/FAQ)
