### ISSUE TITLE
Toonkor not working

### ISSUE THREAD

**Issue by EveryoneAnyone** [manga-download/hakuneko#1749]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
The chapters from the website Toonkor are "OFFLINE" with the folder symbol in grey and the chapters of some manhwa don't load up. The other sites are working fine and the chapters show up in Toonkor when I visit it through a broswer.

**Screenshots**
![Chapters are offline](https://user-images.githubusercontent.com/65541805/82207492-806dfa00-993c-11ea-98f0-822dc5e50f2e.PNG)
Chapters are "OFFLINE".

![Chapters are not showing](https://user-images.githubusercontent.com/65541805/82207498-8237bd80-993c-11ea-810f-533194de0873.PNG)
Chapters are not showing.

**Context (please complete the following information):**
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Have you [solved the captcha](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection) before accessing the site?

Also Toonkor changes their domain regularly, so this might also be a problem...

**Comment by EveryoneAnyone** [comment]
> Have you [solved the captcha](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection) before accessing the site?
> 
> Also Toonkor changes their domain regularly, so this might also be a problem...

(I'm sorry for the wrong title.)
I haven't and I did it just now and it is now working again. Thank you for your assistance and sorry for any incovenience I may have caused you.
