### ISSUE TITLE
[Bug] New chapters not appearing when their display order is reversed on hakuneko

### ISSUE THREAD

**Issue by Sildran** [manga-download/hakuneko#1750]
**Describe the bug**
Hi, 
This has been on my hakuneko for some time now. At 1st it was only for the manga "I'm A Middle-Aged Man Who Got My Adventurer License Revoked" but now it's extending to a lot of other manga in my list. 

Instead of being displayed like this:

https://i.postimg.cc/9MvTgF19/haku-1.png

With the up > down order being from the latest to oldest It display like this:

https://i.postimg.cc/Y0YF5Kys/haku-2.png

From oldest to latest.

I need to clic on another manga and come back to it for the right order to come back. Only then will new chapters appear, as shown on this video:

https://www.youtube.com/watch?v=Z8JJGLh3ITU

"I'm a middle aged man....." is a case on it's own, as it was the 1st one to do this and I can clic and come back as much as I want, the order stay the same (I thought the team had dropped it until I check on manganelo: there are many new chapters):

https://i.postimg.cc/ryr50xFN/haku-3.png

Any ideas ?

**To Reproduce**
Unfortunately : No clues :/

**Expected behavior**
New chapters appears, and all chapters displays in the right order.

**Context (please complete the following information):**
 - OS: Windows10 LTSC
 - HakuNeko Version 6.17 @009a3b

**Comment by 27136773** [comment]
Have you tested it without applying any chapter name formating?

**Comment by Sildran** [comment]
I didn't think about trying as my chapter formatting is way older than the bug. I'll check that :)

**Comment by Sildran** [comment]
It doesn't help :(

**Comment by 27136773** [comment]
I cannot reproduce this issue locally on my end.

It loads all chapters from [I'm A Middle-Aged Man Who Got My Adventurer](https://manganelo.com/manga/mo918887) and the default sorting is the same as on the website, no matter how often i change selected mangas.

**Comment by 27136773** [comment]
Still unable to reproduce => nothing can be done
