### ISSUE TITLE
mangadiyari

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1754]
> **From:** HakuNeko User

**Version:** [6.1.7@009a3b](https://github.com/manga-download/hakuneko/commits/009a3b)

https://mangadiyari.com/

<details><summary>What has been done?</summary>

☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Template: WordPress Madara
