### ISSUE TITLE
[Site Request] GoComics

### ISSUE THREAD

**Issue by maxtron95** [manga-download/hakuneko#1757]
**Name of the website**
GoComics

**Website urls (examples below)**
- Site: https://www.gocomics.com/
- Manga List: https://www.gocomics.com/comics/a-to-z
- Manga example: https://www.gocomics.com/garfield
- Chapter online viewer example: https://www.gocomics.com/garfield/2020/05/20

**Languages**
English

**Additional details**
I viewed Page Info in Firefox and I found that the comic image files are being pulled from `https://assets.amuniversal.com/...`

**Comment by MikeZeDev** [comment]
There is no concept of chapters on this website and no proper chapter list for a comic therefore i fail to see how it can be added.
