### ISSUE TITLE
Chapter content 

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1758]
> **From:** HakuNeko User

**Version:** [6.1.7@b39de2](https://github.com/manga-download/hakuneko/commits/b39de2)

i downloaded new chapters of several manga and some of the fucking content had IMAGES of (trypophobia for example) i dont even want to fvkcing explain 

<details><summary>What has been done?</summary>

</details>

**Comment by XenonR** [comment]
Keep trying, because I do not understand what you're trying to convey here. Maybe an example would help?

**Comment by rngguy** [comment]
When I trying to preview or download something from kissmanga.com I get shockcontent. I think it's some kind of protection, maybe related to cloudflare browser-checking.

**Comment by XenonR** [comment]
Can you please give the exact sitename as stated in hakuneko and the manga and chapter you tried? I could not reproduce what you're describing.

**Comment by rngguy** [comment]
Site - KissManga (https://kissmanga.com)
Manga - any (tested on "Aishiteru", Uso Dakedo. - #1 in full list, Murenase! Shiiton Gakuen - from my bookmarks)
Chapter - any, that isn't already downloaded, 1st or last for example.
This is the result of preview or download (NSFW) http://www.imagebam.com/image/f60e421344464120
I use master@6fba9d version.

**Comment by Sheepux** [comment]
Works fine here.
Some kind of IP/host ban ?
Does it also happens when browsing with chrome ?

**Comment by rngguy** [comment]
Everything is working and was worked in browsers and through hakuneko browser. Today I deleted user data, and now kissmanga gives me "failed to update manga list" error. Paste from https://kissmanga.com/ and https://kissmanga.com/MangaList gives me an empty list without errors. BUT! If i paste the manga page directly, like https://kissmanga.com/Manga/Murenase-Shiiton-Gakuen, it gives me a chapter list, with ability to preview, download and bookmark like everything is ok. I think I can live with it, just need to update my bookmarks.

**Comment by 27136773** [comment]
I cannot reproduce the issue, no matter what i try...
Maybe they changed the manga links (old bookmarks) and provide fake images to these bookmarks

Unable to reproduce => closed

**Comment by 27136773** [comment]
It is also possible that KissManga already removed this protection due to [Manga Storm](https://web.facebook.com/mangastorm/posts/4073804312660219) bypassing it, so maybe we just missed the opportunity to analyze the problem...
