### ISSUE TITLE
Add website template for 1359mh / 517mh

### ISSUE THREAD

**Issue by kbnduy12** [manga-download/hakuneko#1759]
1 / Hello, now I'm very happy and suddenly there is a website that I want has been added to Hakuneko, I recommend a few more websites maybe more people will need like me: ohmanhua.com, 1359mh.com , www.517mh.net.
2 / Is the chapter chapter issue fixed? For example, there is no need to detect the number of chapters in the title of the manga.

**Comment by XenonR** [comment]
Hi, ohmanhua.com was already added in issue #1663 
Please split your website requests in one site per issue. That makes it easier to track and solve for us.
All the best!

**Comment by dodieboy** [comment]
1359mh.com and  www.517mh.net is using the same template

**Comment by 27136773** [comment]
Template: probably MHXK
