### ISSUE TITLE
[Site Request] Delitoon.com

### ISSUE THREAD

**Issue by don-masto** [manga-download/hakuneko#1763]
**Name of the website**
Delitoon

**Website urls (examples below)**
- Site: https://www.delitoon.com/
- Manga List: https://www.delitoon.com/genres
- Manga example: https://www.delitoon.com/webtoon/ombresetlumieres
- Chapter online viewer example: https://www.delitoon.com/lecture/ombresetlumieres/s1/1

**Languages**
French

**Comment by MikeZeDev** [comment]
Site is supported. @Sheepux pls.
