### ISSUE TITLE
Manganelo trouble

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1765]
> **From:** HakuNeko User

**Version:** [6.1.7@b39de2](https://github.com/manga-download/hakuneko/commits/b39de2)

I tried to download some of my favorite mangas put they were all hot-linked to another provider: manganelo (i was using mangakakalot.) and when i tried loading manganelo they told me there was a href issue. I don't know anything about coding, could you help me? Thank you!

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Which manga / chapter?

**Comment by 27136773** [comment]
No further response => closed
