### ISSUE TITLE
Add chapter wait time in settings for every site

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1766]
> **From:** HakuNeko User

**Version:** [6.1.7@b39de2](https://github.com/manga-download/hakuneko/commits/b39de2)

On some websites the default wait time used by the application is too short and this lead to being banned, can you put up a setting where you can increase the time between one chapter and the other ? It seems to being available only for few websites but it could be really useful for "every" website. Thank you

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
No, IP ban protection is sophisticated and managed within the application itself. A timeout does not always protect from IP ban, there might be certain HTTP headers, expected AJAX calls, ...

Just list the website which bans IP and it will be bypassed in HakuNeko

**Comment by 27136773** [comment]
Please open a separate ticket for each website which needs IP ban protection
