### ISSUE TITLE
[Failed to load bookmarks]

### ISSUE THREAD

**Issue by Pokewii** [manga-download/hakuneko#1771]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
I got an infinite loading when I search a manga and none of the connectors works.
When I press F12, I got these errors (see in screenshots)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/65857330/82755757-f7404280-9dd5-11ea-9c55-295f109a8850.png)
![image](https://user-images.githubusercontent.com/65857330/82755766-16d76b00-9dd6-11ea-98fd-cbc941bafa79.png)
![image](https://user-images.githubusercontent.com/65857330/82755795-425a5580-9dd6-11ea-9c1b-54c3a257d871.png)
![image](https://user-images.githubusercontent.com/65857330/82755813-57cf7f80-9dd6-11ea-9ed8-f7800b4fc71f.png)
![image](https://user-images.githubusercontent.com/65857330/82755825-70d83080-9dd6-11ea-8cbd-c6441e45e585.png)
![image](https://user-images.githubusercontent.com/65857330/82755841-95cca380-9dd6-11ea-8644-036140cdf168.png)
![image](https://user-images.githubusercontent.com/65857330/82755879-dfb58980-9dd6-11ea-8013-1d5fbef04f6d.png)

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 6.1.7

**Additional context**
I just installed Hakuneko for download et read some manga but I got this issue. I hope you will find my problem. Than you for your work and sorry for my english (I'm French 😄)

**Comment by 27136773** [comment]
The problem is not quite clear.
Please provide detailed steps to reproduce and include specific website manga and chapter names.

**Comment by Pokewii** [comment]
I open Hakuneko.
![image](https://user-images.githubusercontent.com/65857330/82757408-8e11fc80-9de0-11ea-841a-516c5a20def8.png)
Next, I choose the website (ex: MangaDex)
![image](https://user-images.githubusercontent.com/65857330/82757642-09c07900-9de2-11ea-8fc4-4e18e5338655.png)
Next, I choose a manga (ex: Fairy Tail)
![image](https://user-images.githubusercontent.com/65857330/82757543-63747380-9de1-11ea-8b71-7f51c1fbefc6.png)
Next, I click on the button to search the manga but I got nothing but an infinite loading.
![image](https://user-images.githubusercontent.com/65857330/82757666-47250680-9de2-11ea-8f89-4b639beac7d5.png)
Here is my settings.
![image](https://user-images.githubusercontent.com/65857330/82757765-ea761b80-9de2-11ea-8d79-4364cde14668.png)
I don't understand why it don't work.

**Comment by 27136773** [comment]
Thats not how HakuNeko works.
Read the Wiki / Ask on Discord.
