### ISSUE TITLE
[mangawow] Connector not working "Domain Change"

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1772]
Domain; https://mangawow.com/
New Domain; https://mangawow.net/

İmage;
![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/82759902-cf160b00-9df8-11ea-9693-80311c947357.PNG)

**Comment by 27136773** [comment]
Both domains are not available for me

**Comment by areglos** [comment]
> Her iki alan da benim için uygun değil

The site is very slow. Soon it will be OK.

**Comment by areglos** [comment]
> Both domains are not available for me

The site is very slow.. Soon it will be OK.
