### ISSUE TITLE
[Site Request] jpmanga

### ISSUE THREAD

**Issue by leongard108** [manga-download/hakuneko#1773]
**Name of the website**
jpmanga

**Website urls (examples below)**
- Site: www.jpmanga.com/
- Manga List: www.jpmanga.com/manga-directory/
- Manga example: www.jpmanga.com/manga-tower_of_god/
- Chapter online viewer example: http://www.jpmanga.com/manga-tower_of_god/ch480-690635/

**Languages**
English

**Comment by 27136773** [comment]
See: #1083
