### ISSUE TITLE
WuxiaWorld issue

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1775]
> **From:** HakuNeko User

**Version:** [6.1.7@b39de2](https://github.com/manga-download/hakuneko/commits/b39de2)

Hi, some wuxia doesn't work in WuxiaWorld. For example, chapters of Overgeared and Rebirth of a Thief who roamed the world can't be get. But no problem with "A Legendary Thief" or "The Great Thief".

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
The mentioned mangas are not working on the website, there is an 404 not found error.
HakuNeko can only download mangas that are available on the website.
