### ISSUE TITLE
Add log when updating sources / chapters?

### ISSUE THREAD

**Issue by idayrad** [manga-download/hakuneko#178]
Hey, thank you dev your app is great and works well on my Windows 10 tablet. Been looking for this kind of Manga app for ages...

But I notice it could take a few minutes to updating manga titles especially from large source like *****fox. Maybe a simple log or message like "Downloading database..." / "Downloading chapters..." is useful, so we know the app is still working and not bugging?

**Comment by 27136773** [comment]
You may check the visual indicators [③ and ⑦](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list), they will also provide a tool-tip with more details while a manga list is updated.

**Comment by idayrad** [comment]
> 
> 
> You may check the visual indicators [③ and ⑦](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list), they will also provide a tool-tip with more details while a manga list is updated.

Hmmm... Allright, but the animation is still loading even after I disconnect my internet. Here's a simulation:

1. Choose website (menu right of cable connector icon)
2. Here I choose a website I haven't used, Li** W**toon.
3.  Click the synchronize icon (arrow circle). The icon will start rotating, yes we know it is updating the database. But it also only showing "Mangas: 0/0" on the ⑦ indicator.
4. Then I disconnect my internet to simulate network error, the icon even still rotating...

One without patience will think your app fail. But in fact it is works greats (I think I waited around 5-10 minutes until it was done synchronizing the comic database from Li** W**toon)

I'm using Windows 10 32 bit. Thank you Dev....

**Comment by 27136773** [comment]
Cannot be reproduced on my end, the correct error will be shown and the indicators stop spinning as expected.
Is this only reproducible with LineWebtoon or also with other websites such as MangaDex?
What is shown in the [error log](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#making-an-informative-help-request)?

This could be a performance problem because the list contains more than 50000 mangas.
See also: #5
Is the application responsive or still frozen after waiting for 1 or 2 minutes?

**Comment by idayrad** [comment]
I'm sorry, seems I should using the latest version first. 😝

Now I am using latest version of hakuneko, and oh yeah, actually it does give alert like "failed to fetch..." or "timeout..." on some sources like Kissmanga and mangareader (which I don't care, because I'm never using them).

And mangadex, yeah I think I like waited about 5-10 minutes, the indicators keep spinning but it never done so I quit.

And yeah when accessing large database sources (> 1MB) like Mangafox (the database found on "/userdata" directory), although no freezing hakuneko become very unresponsive.
