### ISSUE TITLE
some chapters not loading - Mangahere

### ISSUE THREAD

**Issue by hiddenbunny** [manga-download/hakuneko#1789]
Solo Leveing is the comic, roughly 15 chapters out of 110 are not loading (see screen shot). The chapters can be accessed via browser, so likely some string for download is probably not correct somehow.
![error](https://user-images.githubusercontent.com/66016089/83020549-9d6a9300-9ff6-11ea-8768-4b97a039d064.jpg)

**Comment by 27136773** [comment]
You cannot download chapters if there are broken images, see [FAQ #6](https://github.com/manga-download/hakuneko/wiki/FAQ)
