### ISSUE TITLE
Problem with downloading images on gmanga

### ISSUE THREAD

**Issue by Dr-Shiro** [manga-download/hakuneko#1790]
Hello
When download a chapter from gmanga, the images appear as bin file type
I hope you fix this problem
Thank you

**Comment by 27136773** [comment]
Which manga/chapter?

**Comment by Dr-Shiro** [comment]
The problem with all chapter

**Comment by satyogi** [comment]
the problem still exists

**Comment by dodieboy** [comment]
the update has not been send out yet, pls wait

**Comment by 27136773** [comment]
As long as the ticket is "Open" it is not resolved ...

**Comment by Dr-Shiro** [comment]
I tried to download manga Black Clover Chapter 251+252 and still images show format BIN file
Please make sure again to fix the problem, thank you

**Comment by 27136773** [comment]
They changed the parameter again... probably an upcoming war between GManga and HakuNeko
`ak2` => `ak3`
