### ISSUE TITLE
[Site Request] Pixiv (Artwork)

### ISSUE THREAD

**Issue by newaccforhc** [manga-download/hakuneko#1792]
**Name of the website**
Pixiv (Artwork)

**Website urls (examples below)**
- Site: https://www.pixiv.net/
- Manga List: No Complete Manga list page
- Manga example: https://www.pixiv.net/user/102131/series/66543
- Chapter online viewer example: https://www.pixiv.net/en/artworks/77370947

**Languages**
Japanese

**Website relationship*
This website doesn't have any relation with other website. ALSO, THIS WEBSITE IS DIFFERENT FROM PIXIV COMIC (comic.pixiv.net)

**Additional details**
Ok... This part is important. This website serves you Low-quality images for guest... But, if you login to this website (free) then, it serves you original quality images. Original quality images are provided when we zoom image. So, see if you can make it so that it'll rip original quality images (after logging in from manual website interaction). Otherwise it won't be of much use.

Thank You!

**Comment by XenonR** [comment]
Hi, I fail to see how this is a manga website. HakuNeko is not a generic download manger. Could you please point us to a manga?

**Comment by lasersPew** [comment]
(2)

**Comment by Jaxk69** [comment]
Hakuneko is only for batch downloading anime or manga not for downloading artwork
