### ISSUE TITLE
Tapas.io not working anymore

### ISSUE THREAD

**Issue by don-masto** [manga-download/hakuneko#1796]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
Hakuneko finds no chapter regardless of the series

**To Reproduce**
1. Go to https://tapas.io/series/OutoftheBlue/info
2. Search Out of the Blue on Hakuneko

**Expected behavior**
There is no visible chapter for the 3 "Out of the Blue" results.
With a direct link, I get the same result.

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/65758133/83111539-0b7d8b80-a0c5-11ea-84be-040b3029329d.png)
![Sans titre](https://user-images.githubusercontent.com/65758133/83111591-251ed300-a0c5-11ea-9a43-677f99193a42.png)

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 7.1.11

Thanks for your help ! :)

**Comment by XenonR** [comment]
At least the paging is now JSON query based
