### ISSUE TITLE
MangaNT - Unable to update mangalist

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#1798]
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**HakuNeko (please complete the following information):**
 - Version 6.1.7

![mangaNT error](https://user-images.githubusercontent.com/60792860/83144968-a65a8200-a126-11ea-90a3-93938a20953e.PNG)

**Comment by Sheepux** [comment]
HTTP 522 means server side error (connexion timeout). The website itself might be encountering load issue.
Tested on my side, works fine.

**Comment by 27136773** [comment]
Try again until it works or use copy & paste feature
