### ISSUE TITLE
[Feature] Reading archived manga chapters

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#1801]
Reading .zip files, I'd like to have this feature.

**Comment by 27136773** [comment]
ZIP is not a valid comic book format, CBZ is already supported.
To the best of my knowledge there is no comic book reader that supports ZIP files...

**Comment by Sheepux** [comment]
@ronny1982 isn't CBZ the same as zip ? I believe that it's just a convention to use CBZ as file extension but there is no technical differences (might be wrong tho).
Comicrack was handling zip files. I believe CdisplayEx too.

**Comment by 27136773** [comment]
I think CBZ is a strict subset of ZIP, where each entry is a file of type image placed at the root level of the archive. A ZIP may contain any file types at any nested level.
If the ZIP mentioned by the opener is a valid CBZ, the solution would be to change the file extension, if it is not a compatible CBZ, then it should not be supported in HakuNeko.

I think HakuNeko should not add additional logic to scan if a ZIP archive is a valid CBZ or not, this would be too much effort for the reader which was intentionally just implemented as simple preview.

**Comment by Sheepux** [comment]
Agreed then. And it matches the fact that Hakuneko doesn't offer zip output by himself.
