### ISSUE TITLE
[Site Request] GuyaMoe 

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#1805]
**Name of the website**
Guya Moe

**Website urls (examples below)**
- Site: https://guya.moe
- Manga List: https://guya.moe/read/manga/Kaguya-Wants-To-Be-Confessed-To/
- Manga example: https://guya.moe/read/manga/Kaguya-Wants-To-Be-Confessed-To/
- Chapter online viewer example: https://guya.moe/read/manga/Kaguya-Wants-To-Be-Confessed-To/190/1/

**Languages**
English (gb)

**Website relationship**
////////

**Additional details**
[FMD support](https://github.com/fmd-project-team/FMD/commit/5c7a0c43c6d1394094014a0c278531f45180afdf)

**Comment by 27136773** [comment]
I think we should slow down adding websites that only provide a single manga, especially when there are direct download links or when the same images are already available at the corresponding Scanlator websites.

See also: #1799 (which includes Kaguya Sama as well)

**Comment by Ever4engel** [comment]
good idea !

you should add ""low priority"" tag for this type of websites.

**Comment by Sheepux** [comment]
My point of view : It's not even a low priority. It's a reject by hakuneko policy :  there is no ads, no tracers, a download option. There is absolutly no need to implement this connector.

**Comment by 27136773** [comment]
OK, lets close it...
