### ISSUE TITLE
[Site Request] readcomiconline.to

### ISSUE THREAD

**Issue by yiberan** [manga-download/hakuneko#1815]
Name of the website: Read Comic Online

Website:  readcomiconline.to

Manga List: readcomiconline.to/ComicList

Manga Example: readcomiconline.to/Comic/Power-Girl-2009

Chapter Example: readcomiconline.to/Comic/Power-Girl-2009/Issue-2?id=51277#5

Languages: English

There is another "Read Comic Online" but is not the "Good One". Plz add this! Thank You!

**Comment by 27136773** [comment]
KissComic is already supported

![image](https://user-images.githubusercontent.com/27136773/83336311-b7d09500-a2b2-11ea-97d8-427e1dd90470.png)
