### ISSUE TITLE
[Site Request] truyentop1.com

### ISSUE THREAD

**Issue by balabalok** [manga-download/hakuneko#1818]
Name website : Truyentop1

- Site: http://truyentop1.com/
- Manga List: http://truyentop1.com/danhsach/index.html?status=0&sort=2
- Manga example: http://truyentop1.com/cua-hang-tai-thien-gioi-1-0.html
- Chapter online viewer example: http://truyentop1.com/doc-truyen/cua-hang-tai-thien-gioi-chapter-0.html
**Languages**
Vietnamese
It would be great if you could add this site to Hakuneko. Thank you very much .

**Comment by MikeZeDev** [comment]
dead?

**Comment by MikeZeDev** [comment]
https://truyenvn.vip/ ?
