### ISSUE TITLE
MangaNT - Unable to load chapters for some mangas

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#1820]
Hi
Not able to load some chapters for some of the mangas - The images are blank.

Hope you can solve this problem. Thanks

eg 
1) https://mangant.com/manga/rebirth-super-goddess-32821
2) https://mangant.com/manga/lovable-and-dark-wife-32300
3) https://mangant.com/manga/dont-provoke-the-contract-wife-31769
4) https://mangant.com/manga/daddy-president-is-awesome-2789
5) https://mangant.com/manga/abduct-a-mommy-and-bring-her-home-29310
6) https://mangant.com/manga/mejaz-regulus-in-the-world-23818

![mangant error](https://user-images.githubusercontent.com/60792860/83351067-7c49cf80-a373-11ea-9706-355a4d8f84e6.PNG)

**Comment by 27136773** [comment]
Probably regression of commit cac67031
Images hosted on `*.mangapark.net` domain must not add a referer

**Comment by suikodoen13** [comment]
Hi thanks. 
still unable to see images for 
1) Mejaz- Regulus in the world chapter 30
2) https://mangant.com/manga/abduct-a-mommy-and-bring-her-home-29310
3) https://mangant.com/manga/spur-of-the-moment-marriage-to-loveable-wife-30048

Do i need to re-download hakuneko software? 

Thank you for your hard work.

**Comment by 27136773** [comment]
MangaNT and its affiliates are cross referencing images from various different websites, some of them requiring certain HTTP headers. Not all of those websites and the required headers are known yet, therefore there is a chance that some chapters are not working yet and needs to be reported to get fixed.

**Comment by suikodoen13** [comment]
ok i see...i understand a bit better now. I will raise a new ticket to report any manga/chapters i cannot view. Thanks for explaining to me.
