### ISSUE TITLE
Manganelo / Mangakakalot invalid image download

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1827]
> **From:** HakuNeko User

**Version:** [6.1.7@9043d9](https://github.com/manga-download/hakuneko/commits/9043d9)

isekai scan stopped loading , mangakakalot and manganelo download a 1 kb bin file instead of images 

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Please check the website before creating a ticket... IsekaiScan is in maintenance mode

**Comment by 27136773** [comment]
Cannot be reproduced on my end.

Please provide a sample manga and chapter to reproduce the problem for MangaNelo and MangaKakalot

**Comment by 27136773** [comment]
No further response => closed
