### ISSUE TITLE
Toomics (French) 18+

### ISSUE THREAD

**Issue by camisole26** [manga-download/hakuneko#1828]
Hello,

The manga list does not display manga 18+.
Normal?

**Comment by 27136773** [comment]
Any sample manga/chapter to reproduce the problem?

**Comment by camisole26** [comment]
https://toomics.com/fr/webtoon/episode/toon/4999

**Comment by Sheepux** [comment]
Indeed 18+ manga doesn't appear on the ranking URL that is used by hakuneko
https://toomics.com/fr/webtoon/ranking
(same for all languages)

**Comment by Sheepux** [comment]
@camisole26 can you check that it does appear in the list when connected to the website (this might require the user to log in to verify the age).
If that's the case you can use the manual website interaction from hakuneko to solve this.

**Comment by camisole26** [comment]
We must click on the "all public" button to display the +18.
A message verifies the age
No need to connect with login
"the manuel website interaction" ?
Thanks for help

**Comment by Sheepux** [comment]
Ok i see it now:
Technical details:
The cookie value " GTOOMICScisession=" is url encoded and contains a flag "family_mode" that remembers wether the all public was checked
s:11:"family_mode";
s:1:"N";


I've confirmed that using the manual website interaction works:
https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction
Using the embeded browser simply click the all public and say yes to are you 18.
Then simply refresh the connector (it will reuse the session) and will list all 125 mangas

Probably won't be improved within hakuenko for a while as there is a temp solution.

**Comment by 27136773** [comment]
In that case we may just call fetchUI with `https://toomics.com/fr/index/set_display/?display=A` within `_initializeConnector()` to let electron set the cookie for us ...

**Comment by camisole26** [comment]
It works by following the manual steps.
I assume that paid content cannot be downloaded without having an account?
Example, "Les filles d'à côté" just 2 chapters available

**Comment by 27136773** [comment]
No, downloading paid content from publishers without a valid subscription is against HakuNeko's philosophy

**Comment by camisole26** [comment]
ok we can close the ticker :)
