### ISSUE TITLE
scan-manga list

### ISSUE THREAD

**Issue by camisole26** [manga-download/hakuneko#1829]
Hello,
When I refresh the manga list, I get the error "Failed to update manga list for ScanManga. Unexpected end of JSON input'.
Problem with the '-' in the name? 
The error message indicates "ScanManga"?

**Comment by 27136773** [comment]
Cannot be reproduced on my end...

Please perform the following tasks first and let us know if the problem still exist:

- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works

--
_Please **do not** create a new ticket for replies_

**Comment by don-masto** [comment]
It's working with ScansMangas but not with ScanManga

**Comment by 27136773** [comment]
Works for me...
Please open developer tools (F12) and check console/network tab for errors when updating the list

![image](https://user-images.githubusercontent.com/27136773/83506734-d6f44000-a4c7-11ea-840a-16c00d7a966f.png)

**Comment by don-masto** [comment]
![Sans titre](https://user-images.githubusercontent.com/65758133/83511828-8bde2b00-a4cf-11ea-936e-7d3dcad8f451.png)
![Sans titre](https://user-images.githubusercontent.com/65758133/83511860-98fb1a00-a4cf-11ea-8a4d-ed71fd9ee616.png)

**Comment by 27136773** [comment]
Just to make sure, the website is fully working in your browser right?

Can you dump the list from your browsers development tools console (F12) by injecting the following code?
```javascript
(async function () {
    let response = await fetch('https://www.scan-manga.com/scanlation/scan.data.json', { headers: { 'x-requested-with': 'XMLHttpRequest' } });
    let data = await response.json();
    console.log('Found Mangas:', Object.keys(data).length);
})()
```

![image](https://user-images.githubusercontent.com/27136773/83524978-a8389280-a4e4-11ea-8a32-9913a92dd0c7.png)

**Comment by camisole26** [comment]
Hello,

scan-manga.com is working for me in Chrome or Firefox.
Simpler error than don-masto (see picture)
![scan](https://user-images.githubusercontent.com/66274638/83531872-cfe02880-a4ed-11ea-988d-bd9db83ecaf5.png)

How open .json on console?

**Comment by 27136773** [comment]
1. Open your Web Browser
2. Press F12 to open Dev Tools
3. Switch to console tab
4. Paste the code posted above and confirm with enter
5. Wait for output or errors

**Comment by camisole26** [comment]
See picture
![scan2](https://user-images.githubusercontent.com/66274638/83546676-57836280-a501-11ea-987e-dbade47e8519.png)

Thanks for help :)

**Comment by 27136773** [comment]
> 1. Open your Web Browser
> 2. Press F12 to open Dev Tools
> 3. Switch to console tab
> 4. Paste the code posted above and confirm with enter
> 5. Wait for output or errors

Seems i forgot the most important step which is required at the very beginning...

0. Visit https://www.scan-manga.com

**Comment by camisole26** [comment]
No errors.
Found Mangas: 6419

**Comment by 27136773** [comment]
This is an isolated problem, i'm afraid there is nothing we can do about it without being able to reproduce the issue.

**Comment by camisole26** [comment]
Don-masto has the problem but thanks.
Just for info, with a vpn, i have get the error below:
![scan3](https://user-images.githubusercontent.com/66274638/83580926-9afbc200-a53d-11ea-8533-e1ad0a5d34ef.png)
