### ISSUE TITLE
[Site Request]  https://queensmanga.com/

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#1831]
**Name of the website**
 queensmanga 

**Website urls (examples below)**
- Site: https://queensmanga.com/
- Manga List: https://queensmanga.com/manga/
- Manga example: https://queensmanga.com/manga/beware-of-the-villainess/
- Chapter online viewer example: https://queensmanga.com/manga/on-your-majestys-lap/43689302/

**Languages**
Arabic

**Comment by 27136773** [comment]
Template: WordPressMadara
