### ISSUE TITLE
downloading chapters

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1834]
> **From:** HakuNeko User

**Version:** [6.1.7@b098c9](https://github.com/manga-download/hakuneko/commits/b098c9)

at sometimes I read some chapters online before I decide to download it but choosing to download chapters from certien chapter option is not available 

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Please provide detailed steps to reproduce, and also the detailed expected behavior

**Comment by 27136773** [comment]
No further response => closed
