### ISSUE TITLE
女神宿舍的宿管君

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1835]
> **From:** HakuNeko User

**Version:** [6.1.7@b098c9](https://github.com/manga-download/hakuneko/commits/b098c9)

can't reload update list from manhwagui

<details><summary>What has been done?</summary>

</details>

**Comment by dodieboy** [comment]
hakuneko is working fine, error cause by manhwagui website down

**Comment by 27136773** [comment]
Please open a new ticket when the website is fully working, but HakuNeko still cannot download
