### ISSUE TITLE
manga doesn't load

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1836]
> **From:** HakuNeko User

**Version:** [6.1.7@b098c9](https://github.com/manga-download/hakuneko/commits/b098c9)

when i copy paste manga from kissmanga, the manga doesn't load, is this a bug i've repeated it over and over again

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
You need to [solve the captcha protection](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection) before using KissManga in HakuNeko
