### ISSUE TITLE
HeroScan downloading invalid chapters

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1837]
> **From:** HakuNeko User

**Version:** [master@11c2a9](https://github.com/manga-download/hakuneko/commits/11c2a9)

Downloads as unopenable files (mostly .bin files) and changing format doesn't work. The site itself is working fine. 

Also, not really any kind of big deal, but at times and at random manganelo titles shows no chapters but clicking a different title then clicking back shows everything properly. Thought it was weird so, just a heads up if anyone else mentions something.

Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Reproducible with `1 Second`, `Chapter 13` images have 403 error, therefore the issue might be request protection, e.g. with Referer Header

Related:
- #1820
- #1821
- #1832

**Comment by 27136773** [comment]
It seems HeroScan fixed the image link issue on their end, it can no longer be reproduced on my site
