### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AlexanderEvergarden** [manga-download/hakuneko#1838]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
I tried to download chapters 1 to 32 of Shuumatsu no Walkure from the KissManga site, yet they don't show up. I tried downloading other manga chapters, but they do not load either. This is specifically on KissManga. Also, there are two versions of Shuumatsu no Walkure showing up when I search for it, not sure what that means but I just thought I'd let you know. Any help would be much appreciated! :)

**To Reproduce**
1. Go to 'HakuNeko'
2. Click on 'KissManga'
3. Scroll down to 'Shuumatsu no Walkure'
4. Click on 'Shuumatsu no Walkure' 
5. See error

**Expected behavior**
I expected chapters 1 to 32 to load in the chapter list.

**Screenshots**
![HakuNeko Error](https://user-images.githubusercontent.com/66381034/83668721-b6fc7380-a5d0-11ea-81b5-c79b41a9a7fc.PNG)

**Context (please complete the following information):**
 - OS: Windows 7 Pro
 - HakuNeko Version 6.17

**Additional context**

**Comment by 27136773** [comment]
Check if #1836 solves your problem, this is probably a duplicate...

**Comment by AlexanderEvergarden** [comment]
> Check if #1836 solves your problem, this is probably a duplicate...

Thank you so much!! I wasn't sure on what to do but this helped!
