### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by McMaster68** [manga-download/hakuneko#1839]
**seri manga**
turkish manga site

****https://serimanga.com/?a=a
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**turkish**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Already requested #461
