### ISSUE TITLE
Kissmanga.com Offline

### ISSUE THREAD

**Issue by ZackCelestial** [manga-download/hakuneko#1840]
I try to download manga from kissmanga.com but it was offline is it kind of bug or because of the website because I try to go to the website there is no problem and all manga become white file and write offline.

**Comment by UnknownLink** [comment]
It appears that on each app launch kissmanga's captcha is what's preventing the download but as long as it's cleared it acts as it normally should within the app

**Comment by AlexanderEvergarden** [comment]
> It appears that on each app launch kissmanga's captcha is what's preventing the download but as long as it's cleared it acts as it normally should within the app

Is there anyway to get past it on the site and somehow have the HakuNeko app access the site? (That sounds highly unlikely but I just thought I'd ask lol) Also, I'm not sure if what I said on my bug report was the right thing to say, if it was even a bug in the first place

**Comment by ZackCelestial** [comment]
Then I should go to the website and clear the captcha first?

**Comment by ZackCelestial** [comment]
I try clear the captcha but it still offline even I start my computer and even I paste the link in app it won't work the app loading but the manga won't show up.

**Comment by chrisjiang1** [comment]
Kissmanga wasn't working until after I cleared the captcha. Then it works like normal again.

**Comment by ZackCelestial** [comment]
![Untitled](https://user-images.githubusercontent.com/59060327/83722927-63d9fd80-a670-11ea-930a-2ebf52ff8a7c.png)

**Comment by ZackCelestial** [comment]
still not work even clear captcha when i restart the computer the website will pop up the captcha again and try clear it still not work

**Comment by ZackCelestial** [comment]
it still offline on app

**Comment by UnknownLink** [comment]
![image](https://user-images.githubusercontent.com/10582562/83749546-e099b700-a631-11ea-86e1-147a260b8bda.png)
Specifically within the app website directory

**Comment by Ever4engel** [comment]
read this carefully : [Captcha protection](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection)

**Comment by ZackCelestial** [comment]
Ooo it working thank you for help I don't know I should click that one thank you very much 😁
