### ISSUE TITLE
Mangahasu - Unable to update mangalist

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#1841]
Hi

Unable to update mangalist in Mangahasu. Is this also a website loading issue?

![mangant error 2](https://user-images.githubusercontent.com/60792860/83761226-9b649c00-a6a8-11ea-9324-f98df5688457.PNG)

**Comment by LouVan** [comment]
I was going to ask the same thing regarding mangahasu. Not only failed on updating manga list but it won't show any chapters as well. Even though it used to be just fine.

![mangahasu](https://user-images.githubusercontent.com/28631958/83761873-76245d80-a6a9-11ea-8c59-ab43e0080dd1.PNG)

**Comment by 27136773** [comment]
It seems MangaHasu sometimes hangs when opening the website, this also happens when opening an URL, e.g. http://mangahasu.se/0/0.html directly in Chrome Browser...

There is nothing that can be done, restart HakuNeko and try again
