### ISSUE TITLE
[Bug] Error downloading the list from lectortmo.com and lectormanga.com

### ISSUE THREAD

**Issue by TheDoom95** [manga-download/hakuneko#1843]
Does not update the manga list on the website .

- Both websites are from Tumangaonline

![ERROR](https://user-images.githubusercontent.com/32015214/83799801-a7e7f500-a6a6-11ea-9ac1-10e733c16da1.PNG)

**Comment by 27136773** [comment]
As the error states, there is no manga list, you need to copy & paste the manga URL from the browser into HakuNeko

Further reading: https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list
