### ISSUE TITLE
[Source Request] Young Jump World (SpeedBinb)

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1845]
> **From:** HakuNeko User

**Version:** [6.1.7@b098c9](https://github.com/manga-download/hakuneko/commits/b098c9)

Thank you for your amazing work with Hakuneko!
I just found this site (youngjump.world) and I think you can add it very quickly. It should use SpeedBinb, according to what their own reader says. It's got both paid and free stuff. This is the free stuff: https://www.youngjump.world/free_yj/. The paid stuff is essentially identical, it just doesn't have the "free_yj" prefix in the links. You can probably add support for this site just slightly modifying the SpeedBinb connector you already use for other sites. Thank you very much if you'll add support for it!

<details><summary>What has been done?</summary>

</details>

**Comment by artsunjai** [comment]
Paid cannot be downloaded
