### ISSUE TITLE
[Bug] Error 503 failed to fetch on JapScan

### ISSUE THREAD

**Issue by daisukekun29** [manga-download/hakuneko#1847]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
I succeeded in downloading 2 volumes on JapScan but now each time I try I get an error 503 failed to fetch. I tried using HakuNeko on another website and it's working fine, so it seems its only JapScan :x

**Comment by 27136773** [comment]
Website is currently having performance issues, HakuNeko can only download if the website is available.
