### ISSUE TITLE
Error downloading some manhwa's from lezhin

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1858]
> **From:** HakuNeko User

**Version:** [6.1.7@0c11fe](https://github.com/manga-download/hakuneko/commits/0c11fe)

Can't download the free chapters in All I want is... and 1 plus 1 but those in secret crush and delicious worked

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Cannot be reproduced on my end, all free chapters from the website are also accessible in HakuNeko.

Please provide console output from developer tools as described in troubleshooting

**Comment by 27136773** [comment]
No further response => closed
