### ISSUE TITLE
[Bug]searching for connectors using the manga search

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#1862]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
when searching for connectors using the "manga" search
it seems to search what is currently in the list of connectors 
like it is doing one search then anding the next search 

**To Reproduce**
1. when you are on the search for connectors
2. search for "hunter hunter" 
3. delete that then search for "hunter x hunter" without searching for nothing between or clearing filters you get https://i.imgur.com/LqaNPOS.png
4. if you search for nothing or clear filters before the search for "hunter x hunter" you get https://i.imgur.com/3D9xmce.png and more

**Expected behavior**
I expected both times to have the same results, mistyping is common having to clear the search is clearly a bug 

**Screenshots**
a video if my explanation was bad
https://streamable.com/obccb7

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Behavior is correct. The search matches the **exact** term (case insensitive), therefore `hunter hunter` does not match `hunter x hunter`.

For clarification when does the search `one piece` would match:
- `Manga One Piece` => match
- `Manga One tiny Piece` => no match
- `Manga Piece One` => no match
- `Manga One` => no match
- `Manga Piece` => no match

The tooltip shall be adjusted to mention that the term is matched exactly.

**Comment by Robonau** [comment]
the issue wasn't that it matches the exact term, the issue is that if you search for something with no matches(or limited matches) it then uses the list on the right to do the next search
so if u do 

One tiny Piece = no match
then
One Piece = no match

;you could replace "One tiny Piece" with anything that comes up with nothing

where as 

 One Piece = match

these should be functionally the same thing 
having to clear the search between searches should not be necessary

a more clear video
https://streamable.com/w1af2u

you are also slightly wrong in how you think it works because searching just "one" or "piece" would both work, it would search for any manga that contain the search term, so "one" or "piece" respectively would include "one piece"

**Comment by Robonau** [comment]
this is not an Enhancement,it is a bug, why was the label changed?

**Comment by 27136773** [comment]
The label was changed before the details were explained

**Comment by 27136773** [comment]
Cause is probably in the UI which contains obsolete code that was designed for search while typing, therefore the result list was not cleared. Since typing search has been removed, the list should be cleared before each search
https://github.com/manga-download/hakuneko/blob/8c3c652c557461b5144007a6b091fd45c14b72d6/src/web/lib/hakuneko/frontend%40classic-light/connectors.html#L377

**Comment by Robonau** [comment]
you're gonna understand it much better than me, when it comes to actual code i aint of any use, thx for responding
