### ISSUE TITLE
Toonkor chapters appears but can't be downloaded

### ISSUE THREAD

**Issue by EveryoneAnyone** [manga-download/hakuneko#1872]
Pretty much what the title says. The chapters load but the folder symbol is gray.

I tried visiting the website and I was able to access it without any issues.

I tried vising the website through HakuNeko to do that CAPTCHA thing but there's no CAPTCHA there. The website opens as normal.

**Comment by 27136773** [comment]
Provide a sample manga / chapter that did not work for reproduction

**Comment by EveryoneAnyone** [comment]
> Provide a sample manga / chapter that did not work for reproduction

I'm sorry but I don't understand what you mean. Should I provide a screenshot of the problem or did you mean something else?

After trying again, I found out another problem. The manhwa from Toonkor that I added to the "Bookmark List" will display that grey folder, which says that it is OFFLINE and that it is only accessible in the manga directory (I admittedly don't understand what this means).

So I selected the Toonkor website and the list of manhwas appeared normally but when I tried clicking on the manhwas that I didn't bookmarked, none of its chapters load. The window is empty, no chapters will load up.
Unbookmarked manhwa, no chapters loads up.
![No chapters](https://user-images.githubusercontent.com/65541805/84412585-0af70000-ac42-11ea-9dee-1218cc02db58.PNG)

Bookmarked manhwa, chapters loads up but is OFFLINE
![Greyed chapters](https://user-images.githubusercontent.com/65541805/84412577-092d3c80-ac42-11ea-822b-1b0ad1663e1a.PNG)

I also tried pasting the link of the manhwa from the clipboard but it didn't work.

**Comment by XenonR** [comment]
He meant an example of a manga and his chapter that is not working.
As manga you provided now "1305", but no chapter. I tested and cannot reproduce your issue with chapter 32:
![image](https://user-images.githubusercontent.com/18627623/84494429-c8690e00-aca9-11ea-826e-5240bcec2d3d.png)
So it seems to be a client side issue.
Please provide your client version.

**Comment by EveryoneAnyone** [comment]
> So it seems to be a client side issue.
> Please provide your client version.

I'm sorry for this but I also don't know what  you mean by "client". Is it perhaps the version of HakuNeko I have right now? If so then it's 6.1.7
