### ISSUE TITLE
Can't download anything, always get a "cannot read property 'map' of null" error

### ISSUE THREAD

**Issue by contown** [manga-download/hakuneko#1873]
So it was working fine, but now every single time I try to download something from any website, it fails and I get the "cannot read property 'map' of null" error. No idea why it started, but hakuneko's just not functioning now. I'm on windows and made sure to update to the most recent version of hakuneko.

So does anyone know how to fix this?

**Comment by 27136773** [comment]
Provide a sample website, manga / chapter that did not work for reproduction

**Comment by sulizi** [comment]
I'm getting this too, I was trying to download Darling in the franxx off of KissManga, every chapter was affected.

**Comment by 27136773** [comment]
Use [manual website interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) and navigate to the chapter that did not work. Solve any captcha, puzzle or riddle that appears during navigation. After that downloads should work.

**Comment by 27136773** [comment]
No further response => closed
