### ISSUE TITLE
[Bug] Blogtruyen, Nettruyen not work.

### ISSUE THREAD

**Issue by robethang** [manga-download/hakuneko#1875]
fix this problem pls. thanks

![blogtruyen](https://user-images.githubusercontent.com/66782362/84385493-a2505900-ac2a-11ea-83cb-c7f73fba7d65.jpg)
![nettruyen](https://user-images.githubusercontent.com/66782362/84385514-ae3c1b00-ac2a-11ea-9b1a-ea604f595dd0.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Try to use copy and paste feature, these website will throw an error from time to time when downloading the whole manga list.

Possible solution: retry on failure

**Comment by 27136773** [comment]
Increasing retry number when download fails...
However, this is a problem on the website, not in HakuNeko.

![image](https://user-images.githubusercontent.com/27136773/85116217-45056a80-b21d-11ea-99aa-c508229e5485.png)
