### ISSUE TITLE
[Bug] Can't download manga from Nicovideo

### ISSUE THREAD

**Issue by Neutronoid** [manga-download/hakuneko#1877]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
- Download manga on seiga.nicovideo.jp giving "Error: Page "https://seiga.nicovideo.jp/image/source/[8-digit numbers unique to each chapter]" return status: 503 - Service Temporarily Unavailable
- No image downloaded

**To Reproduce**
1. Go to 'seiga.nicovideo.jp' connector
2. Click on any manga
3. Download any chapter

**Expected behavior**
- Chapter downloaded

**Screenshots**
![bug](https://user-images.githubusercontent.com/39527543/84532213-039e2800-ad10-11ea-914d-832001baa5ca.PNG)

**Context (please complete the following information):**
 - OS: Windows 7 Ultimate SP1
 - HakuNeko Version 6.1.7

**Additional context**
Preview working just fine

**Comment by 0xh3LL0** [comment]
https://github.com/AlexAplin/nndownload/issues/65

**Comment by 27136773** [comment]
It was reported, that new chapters uses a different server and therefore did not work

![](https://media.discordapp.net/attachments/581630792120401922/723096470059745370/sss.PNG)

**Comment by Neutronoid** [comment]
I just check it, look like it working normally again now (the website doing some maintenance yesterday).

**Comment by Ever4engel** [comment]
last chapters can't download 
Sample: 
https://seiga.nicovideo.jp/watch/mg485979?track=ct_episode

**Comment by 27136773** [comment]
New chapter uses DRM with encrypted images:

https://seiga.nicovideo.jp/manga/js/common.min.js?9zicqv
```javascript
    this.getFromCORSRequest = function(e, t, i) {
        if (/^data:/.test(t))
            return i(t);
        var o = this.getKeyFromUrl(t);
        e.open("GET", t, !0),
        e.responseType = "arraybuffer",
        e.onload = function(e) {
            var a = new Uint8Array(this.response);
            "" !== o && (a = n.decrypt(a, o));
            var s = n.getDataType(a)
              , u = n.toBase64String(a)
              , l = "data:image/" + s + ";base64," + u;
            r[t] = l,
            i(l)
        }
        ,
        e.send()
    }
```

Need to add support in HakuNeko ...
