### ISSUE TITLE
[Site Request] Seri Manga

### ISSUE THREAD

**Issue by zasfantr** [manga-download/hakuneko#1881]
**Name of the website**
Seri Manga

**Website urls (examples below)**
- Site: https://serimanga.com/
- Manga List: https://serimanga.com/mangalar
- Manga example: https://serimanga.com/manga/murabito-desu-ga-nani-ka
- Chapter online viewer example: https://serimanga.com/manga/murabito-desu-ga-nani-ka/16
**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #461
