### ISSUE TITLE
Add Pelateam

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1885]
> **From:** HakuNeko User

**Version:** [6.1.7@aa9bb2](https://github.com/manga-download/hakuneko/commits/aa9bb2)

Please add https://pelateam.it/Computer/, it's an Italian site.

<details><summary>What has been done?</summary>

</details>

**Comment by XenonR** [comment]
So few Italian connectors (10). Let's see what we can do about that.
