### ISSUE TITLE
[Lezhin ] Download failed on free chapters for a few series

### ISSUE THREAD

**Issue by XateAorora** [manga-download/hakuneko#1888]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
Download failed on free episodes for "1 Plus 1", "Paradise Lost", "Shades and Shadows", "Love or Hate", Head Over Heels", "Lady and Her Butler", "My Secret Brother", "Secret Alliance", "At the End of the Road". It worked flawlessly for "The Devil's Boy", "King's Maker", "Killing Stalking", "Peach Love", "Secret Crush" so far.

**To Reproduce**
1. Connect to Lezhin on HakuNeko
2. Search and click on "1 Plus 1" and other series
3. Click Download all available chapters (free and purchased)
4. Download failed for free chapters, successful for purchased ones

**Expected behavior**
All downloadable chapters such as free and purchased should download just fine. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/11598633/84628521-fe5cfb00-af12-11ea-8144-181d8bec2d4b.JPG)
The image link for 1 Plus 1 chapter 3 does not seem to be correct. This is the image link I get from Image Downloader plugin:
https://cdn.lezhin.com/v2/comics/4928603970994176/episodes/5537676345081856/contents/scrolls/7.webp?access_token=ee819a07-1c9a-45c9-be00-1af5a0ddc8ff&purchased=false&q=30&updated=1562055098341
I also copied and tweaked the the Console's link ending by coping from the correct one above and got it to work in Chrome browser:
Tweak 1: https://cdn.lezhin.com/v2/comics/4928603970994176/episodes/5537676345081856/contents/scrolls/1?access_token=ee819a07-1c9a-45c9-be00-1af5a0ddc8ff&purchased=false&q=30&updated=1562055098341
Tweak 2: https://cdn.lezhin.com/v2/comics/4928603970994176/episodes/5537676345081856/contents/scrolls/1?access_token=ee819a07-1c9a-45c9-be00-1af5a0ddc8ff&purchased=trueq=30&updated=1562055098341
I also tested a couple more tweaks below and these all worked for all series. It looks like **purchase=true** or **purchase=false** is not necessary in the link at all.
Tweak 3: https://cdn.lezhin.com/v2/comics/4928603970994176/episodes/5537676345081856/contents/scrolls/1?access_token=ee819a07-1c9a-45c9-be00-1af5a0ddc8ff&purchased=falseq=30&updated=1562055098341
Tweak 4 (got rid of **purchase=** all together): https://cdn.lezhin.com/v2/comics/4928603970994176/episodes/5537676345081856/contents/scrolls/1?access_token=ee819a07-1c9a-45c9-be00-1af5a0ddc8ff&q=30&updated=1562055098341
The tweaked ending **q=30&updated=1562055098341** seems to work for all series, as did all tweaks above.

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 6.1.7@aa9bb2

**Additional context**
Lezhin login info in HakuNeko all correct and adult mode enable on the website.

**Comment by Sheepux** [comment]
Worked fine for me on manga 1 Plus 1. (all 50 chapters)
HTTP 403 means access denied. Possibly a temporary deny  or bad luck ?
However, mine sent all requests with purchased=false but i don't have the "updated" as you do (but i don't have an account and didn't log in, could it be the issue?)

Example Request URL: https://cdn.lezhin.com/v2/comics/4928603970994176/episodes/5537676345081856/contents/scrolls/1?access_token=995dba2e-8c5d-4249-b601-38c5d3e092e5&purchased=false&q=40

**Comment by XateAorora** [comment]
I tried logging out of Lezhin and successfully downloaded the free chapters. Thank you for the tip!
However that is rather inconvenient that I have to log in to download purchased chapters and log out to download free ones. At least there is a work-around that works. 
I think maybe if the link structure is amended somehow then it can work for both free and purchased chapters all logged in?

**Comment by Sheepux** [comment]
Maybe ... or the status could be detected from the chapter list https://www.lezhin.com/en/comic/regnal_trigger_en

Episode 1 - Free
Episode 2 - Free
Episode 3 - Free in 2 days
Episode 4 - Free in 9 days

but if you confirm that tweak4 is working in both cases, then it could be quickly done.

I think that Ronny doesn't have an account, so it's "blind coding" on our side :D

**Comment by XateAorora** [comment]
I've tried all tweaks for all the series mentioned and they all worked. 
If I'm not logged in then the HakuNeko list only showed the ones that are already free atm, which is within expectation. There's only an issue when I'm logged in and only able to download purchased chapters and not the already free ones.
If you can test Tweak 4 on even more titles and confirm that it works then hopefully it can be a more convenient solution. I can test the update for you since I have an account with purchased chapters.

**Comment by 27136773** [comment]
I have a lezhin account for development with some coins in it, if you need for testing let me know
