### ISSUE TITLE
Toonkor: Chapters appears blank or OFFLINE

### ISSUE THREAD

**Issue by EveryoneAnyone** [manga-download/hakuneko#1891]
Chapters of manhwas from Toonkor is either blank or OFFLINE.

Chapters of bookmarked manhwas are OFFLINE.
![Chapters are offline](https://user-images.githubusercontent.com/65541805/84778171-2df42c00-b015-11ea-9692-c3b80f0c41ef.PNG)

Chapters of unbookmarked manhwas are blank/empty.
![Chapters are not showing](https://user-images.githubusercontent.com/65541805/84778218-3f3d3880-b015-11ea-881c-93be06d46f19.PNG)

- The website is accesible on both my browser and the website selection list and chapters appears normally
- There is no Captcha protection.
- Other websites are working normally e.g. Mangago.
- I deleted and redownloaded Hakuneko but the issue is still present.

I pressed the small refresh button but it said that "Failed to update manga list for Toonkor."
![Toonkor error](https://user-images.githubusercontent.com/65541805/84778910-3c8f1300-b016-11ea-8b12-1dcce1c06ba9.PNG)

My client version is 6.1.7
![Version](https://user-images.githubusercontent.com/65541805/84778996-5c263b80-b016-11ea-9688-bd4723ae337c.PNG)

A user tried replicating the issue and he/she said that the website is working normally so it seems to be a client side issue.

**Comment by 27136773** [comment]
Problem seems to be twitter API.
Since Toonkor changes their top level domain faster then some random guy his shorts, HakuNeko fetches the latest domain from twitter. If this fails, the Toonkor website may not be reached because the stored domain is probably outdated. This may lead to downloading problems...

=> TODO: Investigate why the domain cannot be fetched from Twitter

**Comment by 27136773** [comment]
Toonkor no longer have a Twitter account (suspended) to share their current domain:

![image](https://user-images.githubusercontent.com/27136773/85124676-9536f980-b22a-11ea-919c-1107f18fa723.png)

Looking for an alternative to get the latest domain for toonkor...
