### ISSUE TITLE
[Site Request] Futabanet Monster

### ISSUE THREAD

**Issue by newaccforhc** [manga-download/hakuneko#1894]
**Name of the website**
Futabanet Monster (I don't know what's the monster thing)

**Website urls (examples below)**
- Site: https://futabanet.jp/monster
- Manga List: https://futabanet.jp/list/monster/serial or https://futabanet.jp/list/monster/works (I can't really understand the difference)
- Manga example: https://futabanet.jp/list/monster/work/5e0471457765611021020000
- Chapter online viewer example: https://futabanet.jp/common/dld/zip/7b3ddd27d6c05ba0398a0d68a2cb228f/

**Languages**
Japanese

**Website relationship**
None.

**Additional details**
_SpeedBinb Reader_... use that template.

**Comment by newaccforhc** [comment]
@ronny1982 Should I close this issue?? Or keep it until Manga List is implemented?

**Comment by 27136773** [comment]
Either the opener or one of the maintainers may close the issue if they think the commit solved it.
If i would revise/re-assess open tickets as a maintainer and see a linked pull request that says `solves #1894`, i would probably close it...

Tip: If you write `Resolve` or `Fixes` in the pull request, the ticket gets closed automatically when the pull request is merged

**Comment by newaccforhc** [comment]
Okay... I’ll keep that in mind.. I’m the one who opened the issue and I think closing it will be better...
