### ISSUE TITLE
mangahanta add

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1898]
> **From:** HakuNeko User

**Version:** [master@8c3c65](https://github.com/manga-download/hakuneko/commits/8c3c65)

Turkey scans manga web site ♥
http://www.mangahanta.com/

<details><summary>What has been done?</summary>

☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Template: MAngaReaderCMS
