### ISSUE TITLE
[Feature] renaming bookmarks 

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#1911]
**Is your feature request related to a problem? Please describe.**
not really a problem, i just find it easier to remember English titles than Japanese/Korean/Chinese,
also as someone that keeps a list using a website being able to use the same names as that website is nice. 

**Describe the solution you'd like**
a way to rename bookmarks inside hakuneko.
right click>edit title
or something along those lines.

**Describe alternatives you've considered**
you can achieve the end goal by editing the bookmarks folder:
\AppData\Roaming\hakuneko-desktop\hakuneko.bookmarks
https://i.imgur.com/gfJtVpi.png
but doing this is rather tedious.

**Comment by 27136773** [comment]
As workaround this can be done by editing¹ the manga title of the bookmark directly in the `hakuneko.bookmarks` file which is located in the [User Data Directory](https://github.com/manga-download/hakuneko/wiki/User-Manual#22-user-data). Make sure to backup the file just in case...

¹ _while the application is not running_

<img width="767" alt="Screen Shot 2020-06-20 at 7 20 21 AM" src="https://user-images.githubusercontent.com/27136773/85193282-44c1a980-b2c7-11ea-8ae1-b7c4d67d93f8.png">

**Comment by Robonau** [comment]
thx for the response, but i did already mention that it could be done like that, see section under "Describe alternatives you've considered"
