### ISSUE TITLE
Chapters not downloading

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1916]
> **From:** HakuNeko User

**Version:** [6.1.7@aa9bb2](https://github.com/manga-download/hakuneko/commits/aa9bb2)

I have a problem with the following chapters from MangaNelo:

Dragon Ball Super: chapters 44, 45, 46 ,47, 49, 51, 52, 53, 54
Dragon Ball GT: chapters 37, 38, 39

No matter what I do, they won't download.
Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Robonau** [comment]
unable to reproduce, both gt and super download fine from MangaNelo. 
https://i.imgur.com/WZYA1zS.png
https://i.imgur.com/maqVbiy.png

Version: 6.1.7@aa9bb2
windows 10

**Comment by omegaknights** [comment]
I am on MacOS Catalina 10.15.5 and the issue is still happening... It "downloads" super fast and then gives me the exclamation mark in a red triangle.

**Comment by XenonR** [comment]
I'm afraid that is not enough to work with. Please open the development console (F12) before doing the final request in HakuNeko and take a look into the `Console` tab. Maybe there's more to find there.
*Not sure if it's also F12 on Mac

**Comment by 27136773** [comment]
Also not reproducible on my end...
No further response => closed
