### ISSUE TITLE
Special chars

### ISSUE THREAD

**Issue by enriqueism** [manga-download/hakuneko#192]
I have a problem with branch 0.4.0 compiling from source
`Error: EINVAL: invalid argument, open '/foo/bar/hakuneko/Nande koko ni sensei ga!?/[NineMangaES] - Nande koko ni sensei ga!? Capítulo 26.20.cbz'`
this happens with mangas names containing chars like '?', ':' I'm compiling in Ubuntu 19.04, Thanks.

**Comment by 27136773** [comment]
I'm not developing under Ubuntu, so i cannot investigate the issue.
Usually those characters are supporter for linux, i don't know if this is a restriction by Ubuntu or a bug in NodeJS that is bundled in the electron package of HakuNeko.

Path sanitize is done in [electron/storage.html#L760](https://github.com/manga-download/hakuneko/blob/cda6c98afd07e8ac3017b848883ee9c60c400557/web/lib/hakuneko/engine/electron/storage.html#L760), just add the characters you want to remove and redownload the chapter...

**Comment by enriqueism** [comment]
Thanks for your help
