### ISSUE TITLE
[Site Request] mangabob.com

### ISSUE THREAD

**Issue by naafx8** [manga-download/hakuneko#1922]
**Name of the website**
mangabob.com

**Website urls (examples below)**
- Site: https://mangabob.com/
- Manga List: https://mangabob.com/manga-tag/comics-list/
- Manga example: https://mangabob.com/manga/so-pure-so-flirtatious/
- Chapter online viewer example: https://mangabob.com/manga/so-pure-so-flirtatious/chapter-1/

**Languages**
english

**Comment by 27136773** [comment]
Template: WordPress Madara

**Comment by 27136773** [comment]
Website is already supported, check before making a request
