### ISSUE TITLE
serimanga mangalist missing

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1923]
> **From:** HakuNeko User

**Version:** [master@ba1659](https://github.com/manga-download/hakuneko/commits/ba1659)

serimanga mangalist missing
Example: 5 Toubun no Hanayome
There are 122 chapters.
there are 20 chapters in hakuneko

<details><summary>What has been done?</summary>

☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Robonau** [comment]
its only grabbing the 20 most recent (probably because of how the site is laid out(20 per page in descending order))
