### ISSUE TITLE
Viz not working through proxy

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1924]
> **From:** HakuNeko User

**Version:** [6.1.7@6c1215](https://github.com/manga-download/hakuneko/commits/6c1215)

I can access the chapters through Firefox just fine, using a proxy. But even if I try using the same proxy with Hakuneko, Viz's series don't work and say I'm geobanned. I tried changing the proxy, but it's still the same: it works with Firefox, it doesn't work with Hakuneko. I tried using the internal browser but it doesn't work either. But if I visit an IP finder site throught that same browser, it says I'm in USA. Am I missing something? Does Hakuneko leak my real IP somehow?

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 09morbab** [comment]
have you set the proxy settings in hakunako?
https://i.imgur.com/RmjoYyj.png
if not that would explain this behavior

**Comment by 27136773** [comment]
Have you applied proxy settings in the correct format (see tooltip)?
Have you checked the "How is HakuNeko recognized" button?

![image](https://user-images.githubusercontent.com/27136773/85421116-54194f00-b574-11ea-931d-67ce5f5a6f6f.png)

**Comment by 27136773** [comment]
No further response => closed
