### ISSUE TITLE
[Bug] Viz Hell's Paradise manga chapters not listing

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#1932]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
Unable to See the chapters for Hell's paradise in VIZ. However i am able to read in browser.
https://www.viz.com/shonenjump/chapters/hells-paradise-jigokuraku

**Comment by Robonau** [comment]
my guess is its dew to the 18+ tag that requires a login on viz
there is nothing in f12 console

**Comment by amit34521** [comment]
is it possible to add the login option for this then?

**Comment by 27136773** [comment]
See: https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#3-account-login

**Comment by amit34521** [comment]
It is still not working. I have attached a screenshot for the same. 
![New Bitmap Image](https://user-images.githubusercontent.com/14815570/85377733-22de5600-b557-11ea-9fa7-ac27830c36f7.jpg)


I also tried the login feature in WutopiaComics and it is also not working there. Even after logging in, i am able to see only 1 page of the chapter while i ca read them all in browser.
