### ISSUE TITLE
[Bug][minor]setting windows deselects manga in bookmarks

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#1933]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
when you confirm settings whilst in bookmarks it deselects any manga u have selected

**To Reproduce**
have a manga in bookmarks selected(so u can see chapters)
open settings 
click the tick
and it'l deselect the manga

**Expected behavior**
didn't expect it to deselect
streamable.com/yy0kjo
**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17] (same no nightly and the master)

**Additional context**
not really a problem, i just noticed it and figured i should report it
there is probably a good reason for this but it only happens with bookmarks and not when on a connector (as the video shows)

**Comment by 27136773** [comment]
This behavior is intentional because settings have limited events system, therefore selected manga will be cleared to force reloading of settings on next selection (e.g. when set credentials or proxy)

**Comment by Robonau** [comment]
so why dosn't it do it when the manga is selected form a connector?
also from what i have observed in the past restarting is necessary for any changes in settings to take effect, so the behavior may be intentional but isn't getting the desired effect.
