### ISSUE TITLE
[Bug] shonenjumpplus World's End Harem Fantasia download censored chapters

### ISSUE THREAD

**Issue by marconii2002** [manga-download/hakuneko#1934]
In World's End Harem Fantasia program download latest censored chapeters when on website reader this same chapter is uncensored.

To reproduce

Compare chapter 21-2 images from you program and online reader here https://shonenjumpplus.com/episode/13933686331662831375

In online reader images are uncensored but in your program images are censored.

Can you fix it ?

**Comment by 27136773** [comment]
I cannot see any difference.
Please provide sample image comparison.
Make sure HakuNeko runs under the same conditions as your browser (e.g. account login, user settings, ...)

**Comment by marconii2002** [comment]
Uncensored image from online reader https://imgur.com/Zr2FvLz censored image from program https://imgur.com/PAfu899

Difference is clear like sun.

**Comment by Robonau** [comment]
hakuneko is also grabbing the uncensored 
https://i.imgur.com/jwPtzoq.png

**Comment by 27136773** [comment]
Are you maybe using a proxy with your browser to avoid censorship?
Then you must apply the same settings to HakuNeko...

**Comment by Robonau** [comment]
actually nvm when using clipboard connector it isn't censored but going through the jump + connector it is censored
https://i.imgur.com/Ai2XhsC.jpg

終末のハーレム ファンタジア
it's the same site and same manga,but is different images,not a proxy thing

**Comment by 27136773** [comment]
Seems there are different chapters. I can only reach the censored chapters through the website...
How do you get the uncensored link?

| Chapter | 21-2 |
|---|---|
| Censored     | https://shonenjumpplus.com/episode/13933686331662831367 |
| Uncensored | https://shonenjumpplus.com/episode/13933686331662831375 |

**Comment by newaccforhc** [comment]
Looks like they are hiding the uncensored version both in Manga list as well as in search... (Interesting)
I was able to get the Uncensored one from Google search but, getting it from site looks impossible..

**Comment by newaccforhc** [comment]
I also tried creating an account to see if it gets visible... But, no... It doesn't... Also, I checked settings but there isn't any option of censorship filter or anything...

**Comment by newaccforhc** [comment]
I also tried searching for other mangas but, looks like this is the only exceptional manga having both censored and uncensored version on site...

**Comment by Robonau** [comment]
if it is truly the only exception then you could get the link from the rss feed
but you would have to do if for every exception that occurs.

**Comment by 27136773** [comment]
Nothing that can be done in HakuNeko about this, [終末のハーレム ファンタジア／公式サイト版](https://shonenjumpplus.com/episode/13933686331662831375) is not available in the manga list, only [終末のハーレム ファンタジア](https://shonenjumpplus.com/episode/13933686331662831367) is available.

It still works as expected with copy & paste => closed
