### ISSUE TITLE
Failed to update manga list for Tumangaonline/LectorManga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1936]
> **From:** HakuNeko User

**Version:** [6.1.7@c57aa8](https://github.com/manga-download/hakuneko/commits/c57aa8)

Its impossible to retrieve the manga and the chapters from this two websites

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
There is no manga list, use copy & paste feature.
If not clear, ask in discord for support how to use it.
