### ISSUE TITLE
[Feature] Mouse going invisible when not moving

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#1937]
**Is your feature request related to a problem? Please describe.**
having the mouse on the screen all the time can be kinda distracting 

**Describe the solution you'd like**
like when watching a video after a few seconds of not moving the mouse cursor would go invisible 

**Describe alternatives you've considered**
putting the mouse to the side works, but can cause scrolling to stop functioning and moving the mouse even slightly will make it stuck on the screen.

**Comment by Sheepux** [comment]
Needs full details of the use case:
Only for videos ? Delay before hiding the mouse (5s ?)
When mouse is on video or only for full screen ?

**Comment by Robonau** [comment]
I don't use haku for videos but if it isn't already on the video player i would say add it 
I mainly wanted it for reading manga (cursor is annoying)(if u just got comfortable but the cursor is in the middle of the screen)
3-5s seems about right
