### ISSUE TITLE
kissmanga downloads fail

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1938]
> **From:** HakuNeko User

**Version:** [6.1.7@c57aa8](https://github.com/manga-download/hakuneko/commits/c57aa8)

downloads fail in kissmanga or take too long to show

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Have you opened [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) and solved the Captcha that appears when navigating to a chapter?

![image](https://user-images.githubusercontent.com/27136773/85572821-9ce50c80-b635-11ea-9f11-8c2a318f4454.png)

**Comment by 27136773** [comment]
Probably duplicate of #1873
Re-open the issue if the solution did not work

**Comment by 27136773** [comment]
Re-opened

This issue will be used to solve the issue where KissManga has perma captchas for certain chapters.
This should be solved by showing the website to the user and ask to solve the captcha before the download begins.
(Same way as for CloudFlare's hCaptcha)

Samples:
https://kissmanga.com/Manga/Mairimashita-Iruma-kun/Vol--014-Ch-124----The-Desires-in-the-Bow?id=646707
https://kissmanga.com/Manga/Mairimashita-Iruma-kun/Vol--014-Ch-124-005----EXTRA?id=646708
