### ISSUE TITLE
[Feature]why not semi automate connector implementation

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#1942]
**Is your feature request related to a problem? Please describe.**
its clear that the devs spend allot of time implementing different connectors automating it (even partially would allow for more time to be spent making changes to the program itself)

**Describe the solution you'd like**
i imagine using a system somewhat similar to fetchrss.com would be able to grab all the necessary but would also be simple enough to data allow the average end user to add a connector

**Describe alternatives you've considered**
this has probably already been considered given the 300+ website suggestions in issues, i just figured ide point it out encase it hasnt

**Additional context**
its about time efficiency manually implement connectors forever or spend some(probably quite a bit) time making it so u don't have to (at least any ware near as often)
having an easy way for the end user to implement would be good, but having it as a tool only used by devs would still make it allot more efficient

**Comment by 27136773** [comment]
The API has already been simplified in a big rewrite.
There is even a detailed [developer tutorial](https://github.com/manga-download/hakuneko/wiki/Developer-Website-Tutorial) in the wiki.

I think if a developer is not going to take the current hurdles of Forging, Implementing and Pull Requesting, he won't contribute anyway, even if the Implementation part would be much simpler then it already is right now...

**Comment by Sheepux** [comment]
And even a user not particulary skilled on programmer was able to contribute by reusing the generic templates that helps to simplify the process
https://github.com/manga-download/hakuneko/pull/1551

I don't see how an "automated" process could be done.

Also, the dev tutorial is not really complex.
