### ISSUE TITLE
[Bug] VIZ After Login not working for some mangas

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#1945]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
After the login update, the chapters are not loading for some manga like One-punch Man, Blue Exorcist. But if i signOut of my account, it shows me the free chapters available. Please check.

**Comment by 27136773** [comment]
See: #1932

**Comment by amit34521** [comment]
This issue is a bit different. for some series i am able to see all chapters while for some i dont. I have membership.
![complete](https://user-images.githubusercontent.com/14815570/85751857-8a97cb00-b728-11ea-84da-2a6291812a1a.png)
This one here loads all chapters including the membership ones.
![missing](https://user-images.githubusercontent.com/14815570/85751950-9daa9b00-b728-11ea-9d47-6c39a968da2f.png)
Here not a single chapter is listed.

[DOM.txt](https://github.com/manga-download/hakuneko/files/4832386/DOM.txt)
DOM of the OnePunch Man which doesnt show any chapters in the list.

**Comment by 27136773** [comment]
Problem with parsing subchapter names (e.g. 123.5)

**Comment by amit34521** [comment]
That doesnt seem to be the issue. Hell's Paradise has subchapters and it is getting parsed properly

![Hells Paradise](https://user-images.githubusercontent.com/14815570/85760252-4825bc80-b72f-11ea-9703-0a7f4005d691.png)

**Comment by 27136773** [comment]
Because Hells Paradise provides an explicit name, if there is no name they are parsed from the URL
