### ISSUE TITLE
about mangapark website

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1946]
> **From:** ledaswan93

**Version:** [6.1.7@c57aa8](https://github.com/manga-download/hakuneko/commits/c57aa8)

mangapark is my favorite source of manga scanlations, but here on hakuneko mangas from this website are loaded only until letter D. is it possible to fix this problem?

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Use copy & paste (ask on discord for support if not clear)
See #463
