### ISSUE TITLE
[Site Request] es.niadd.com

### ISSUE THREAD

**Issue by djgerman10** [manga-download/hakuneko#1953]
- Site: https://es.niadd.com/
Manga List: https://es.niadd.com/category//
Manga example: https://es.niadd.com/original/10013625.html/
Chapter online viewer example: https://es.niadd.com/chapter/Cap_01/100086132/
**Languages**
List of languages supported by the website
Spanish

**Comment by 27136773** [comment]
See: #816
Related: #837
