### ISSUE TITLE
[Lezhin (English)] Unable to download any paid chapter

### ISSUE THREAD

**Issue by adsl3f** [manga-download/hakuneko#1955]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hakuneko is unable to download any paid chapter from lezhin english. i tried extracting images using an extension and compared images links with hakuneko's, and found out it has mismatch access token. tried with another lez account and it had the same issue.

**To Reproduce**
1. Name of connector: Lezhin (english)
2. Name of manga: any title
3. Name of chapter: any paid chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 403 ()

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/25125503/85912760-fbbda800-b826-11ea-9836-9527958db51f.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
See: #1951
