### ISSUE TITLE
Auto downloading/Scan for new issues[Feature]

### ISSUE THREAD

**Issue by xx255q** [manga-download/hakuneko#1959]
To be able to track a series on a site and when a new chapter is posted it auto downloads

User starts program, connect to manga site, looks up series, and have a button to track series. Then a list is created, you can set it to check once a day and it compares the older list to the new one and if a new entry is added is downloads it

**Comment by 27136773** [comment]
Auto-download will not be implemented, this is against HakuNeko's philosophy.
A request to add a check for new chapters which then can be downloaded manually is already in the queue.

Duplicate: #1729
Request: #653
