### ISSUE TITLE
ReadRawManga.com erratic

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#196]
> **From:** HakuNeko User

Since yesterday, periodic failures to connect to site. 

Thank you.

**Comment by 27136773** [comment]
Cannot be reproduced.
Try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting).
Provide [more detailed information](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#making-an-informative-help-request) such as manga/chapter and error log.

**Comment by 27136773** [comment]
No further response => closed
