### ISSUE TITLE
If a download fails for a series it checks another site[Feature]

### ISSUE THREAD

**Issue by xx255q** [manga-download/hakuneko#1960]
Say you have the option of caching a list of manga on other sites so that if your download fails or maybe even missing chapters it will look up those list see if another site has it (maybe give the option to rank alts) it will pick one do another scan to confirm series is still viable then download missing issues

**Comment by 27136773** [comment]
This cannot be achieved, mangas and chapters may have completely different IDs and names across different websites.
Workaround: If a manga from a website is expected to have download issues, bookmark the same manga from another website to quickly browse them afterwards from the bookmark list.
