### ISSUE TITLE
Smack Jeeves is not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1964]
> **From:** HakuNeko User

**Version:** [6.1.7@d8c08b](https://github.com/manga-download/hakuneko/commits/d8c08b)

When selecting Smack Jeeves as a connector it errors out on an update list. Using the Clipboard and downloading a single URL also fails.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Robonau** [comment]
![](https://i.imgur.com/dnpnc2Y.png)


![](https://i.imgur.com/ryy13f4.png)
