### ISSUE TITLE
NO PUEDO DESCARGAR

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1966]
> **From:** HakuNeko User

**Version:** [6.1.7@d8c08b](https://github.com/manga-download/hakuneko/commits/d8c08b)

EN LA VERSION ANTERIOR SI SE PODIA DESCARAGAR, PERO EN ESTA (6.1.7) YA NO ME DEJA, ¿POR QUE PODRIA SER?

<details><summary>What has been done?</summary>

</details>

**Comment by Sheepux** [comment]
Unable to understand (googletrad: incapaz de entender).
support is provided in english.

Also, CAPSLOCK is not helpfull.

**Comment by 27136773** [comment]
Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by djgerman10** [comment]
¿Que no puedes descargar? detalla tu problema y usa google traductor, todos los desarrolladores hablan ingles

**Comment by 27136773** [comment]
Issue was created through HakuNeko and it is very unlikely that the creator will follow it on GitHub.
Furthermore, it is already difficult to exchange information without language barrier.
=> Closed
