### ISSUE TITLE
ninjascan and tritonia  new chapters empty

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#197]
> **From:** HakuNeko User

The new chapters downloading empty folders and not showing any content on preview, Sorry for the hassle and thanks.

**Comment by 27136773** [comment]
Please try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) first before posting.
The NinjaScans website is offline, HakuNeko can do nothing about this...
