### ISSUE TITLE
[Madokami] Connector not working

### ISSUE THREAD

**Issue by Ruthalas** [manga-download/hakuneko#1972]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When madokami is selected and the "Synchronize local manga list..." button is pressed, Hakuneko searches for 60s, then times out with the following message:

![image](https://user-images.githubusercontent.com/27835519/86308661-67c65480-bc09-11ea-9fd2-6f66b1e6531b.png)

I believe this is probably due to Madokami requiring HTML auth, as mentioned in Issue #15. 
It seems it was eventually added anyway, but there isn't a spot to put in credentials in the settings pane. I don't know if it used to work or not.

I'd love to be able to utilize this tool for that site, if it isn't a huge amount of work to make that happen.

Regardless, thanks for this tool!

**To Reproduce**
1. Attempt to refresh manga list for Madokami

**HakuNeko (please complete the following information):**
6.1.7@d8c08b

**Comment by 27136773** [comment]
See #15
The website is [closed for registration to new users](https://manga.madokami.al/READ.txt), so i don't see a point in adding it.
Furthermore, none of the current contributors has an account (to the best of my knowledge) to work on this website.
There is a reference implementation in Pascal, but i don't think it would help blindly porting it to HakuNeko.

I guess it would make more sense to remove this website from HakuNeko
