### ISSUE TITLE
mangasee not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1976]
> **From:** HakuNeko User

**Version:** [6.1.7@989471](https://github.com/manga-download/hakuneko/commits/989471)

as mentioned in the title mangasee is not working since its url changed

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Robonau** [comment]
duplicate of [issue](https://github.com/manga-download/hakuneko/issues/1971)
