### ISSUE TITLE
KissManga add page loading delay to settings

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1977]
> **From:** HakuNeko User

**Version:** [6.1.7@989471](https://github.com/manga-download/hakuneko/commits/989471)

I see that from last version you updated the behaviour with the auto window of captcha getting in auto.

The problem is that even with capcha support Kissmanga captcha happens continuously, yes because after the captcha is cleared the next one happens again because the program doesn't pause enough. Also captchas are not shown anyways if the time distance between chapters is enough.

What I ask here and please please please please please please please please please please - (I ask here please 10 times):

Can you add a KissManga sleep time like you did with chrunchyroll, readmanga, viz, mintmanga and so on? I believe a pause of 10 seconds at least between each chapters will do, but with an editable field it could be tweaked without stress too much the remote website.

Best Regards

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Robonau** [comment]
i believe there is already a 5 second cool-down on doing anything on kissmanga

**Comment by 27136773** [comment]
I doubt a sleep has any affect on the captcha, during my tests some chapter seems always to require a captcha...
However if users would like to manually set the delay its just a simple change on the code

**Comment by MikeZeDev** [comment]
Old Kissmanga is dead. Issue need to be closed?

**Comment by MikeZeDev** [comment]
@Sheepux pls <3
