### ISSUE TITLE
Please Help after i restart my computer it goes to white screen Please Help me 

### ISSUE THREAD

**Issue by jammangi** [manga-download/hakuneko#1981]
![image](https://user-images.githubusercontent.com/54354640/86513685-c294c180-be3e-11ea-8385-d88b7cb445d9.png)
This is the error after i restart my computer

**Comment by 27136773** [comment]
See #1979

**Comment by jammangi** [comment]
i don`t know how to use that #1979 can you help me how to fix it!
i even format my pc for this hakuneko but it just the same
