### ISSUE TITLE
[Feature] Option to chose/enable latest version of chapter when downloading all chapters at once

### ISSUE THREAD

**Issue by xx255q** [manga-download/hakuneko#1982]
**Is your feature request related to a problem? Please describe.**
Sometimes when you download an entire series they will have something like Chapter 5 then Chapter 5 v2 and you end up downloading both

**Describe the solution you'd like**
A box in setting that when enabled skips over chapter 5 and downloads v2 or v3 instead

**Describe alternatives you've considered**
Right now you either manually click series or after downloading have to go delete it yourself

**Context (please complete the following information):**
HakuNeko Version [e.g. 6.17]

**Additional context**
I understand due to naming it may mistakes so it just being a feature you can click on/off would be best

**Comment by 27136773** [comment]
Naming is way to inconsistent across different websites
=> to much effort for minor improvement
