### ISSUE TITLE
[Feature] Option to remove Vol.#  when downloading

### ISSUE THREAD

**Issue by xx255q** [manga-download/hakuneko#1984]
**Is your feature request related to a problem? Please describe.**
series will sometimes have both chapter and Vol.# chapter

**Describe the solution you'd like**
After downloading it removes vol. from name

**Describe alternatives you've considered**
Going back to series and doing it yourself

**Context (please complete the following information):**
HakuNeko Version [e.g. 6.17]

**Comment by 27136773** [comment]
There is a setting to apply a custom chapter format which can be used to achieve the goal
Furthermore the `Post Processing` command can be used to rename the chapter via script

**Comment by xx255q** [comment]
So how does that work? I assume your talking about Chapter title format. What happens if i just write Chapter?

**Comment by 27136773** [comment]
You will find samples in the corresponding tooltips, if not clear ask in discord for help

![image](https://user-images.githubusercontent.com/27136773/86517235-a76a8780-be27-11ea-8a79-ab5335005a43.png)
