### ISSUE TITLE
Better downloads handle

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1985]
> **From:** HakuNeko User

**Version:** [6.1.7@989471](https://github.com/manga-download/hakuneko/commits/989471)

Could be it possible implement something like this?

- Cancel download: If you click on chapters in the list it says "No action can be performed", instead could be changed to remove the chapter from the queue ? Happens many times that you misclick on a chapter that you don't need, so you can remove it.. it seems that actually there's no way to remove chapters from the queue. The same could happen if you click a chapter with the clock icon in the download list so you can remove chapters from the list.

- Play / Pause queue: A play / pause button so that you can pause the current queue useful if you need to pause the download for some reasons or if you want further investigate about errors. Actually there's no way to stop the download queue, it tries endlessy until all the items are done. A play/pause would be perfect for this job.

Thanks!

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See #8
