### ISSUE TITLE
[Line Webtoon English] Connector not working

### ISSUE THREAD

**Issue by arromdee** [manga-download/hakuneko#1988]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Once again, you cannot get to later pages of a multiple page comic such as The Gamer.  I previously reported this as #1635 and it was reported again as #1861.  Commit https://github.com/manga-download/hakuneko/pull/1768 says "Maybe some more logic is required in the future since this basically reverts #1709" which was the fix for 1635.

**To Reproduce**
1. Line Webtoon (English)
2. The Gamer
3. All chapters on pages 2-up

**HakuNeko (please complete the following information):**
Nightly build, Linux 64 bit .rpm, about shows "rev. master@75349a".

F12 shows the following error twice:

index.html:1 A cookie associated with a cross-site resource at http://www.webtoons.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Also, the about says "75349a" but the version on Github is "75349a2" so there may be a display problem with the version.

**Comment by 27136773** [comment]
Cannot be reproduced on my end (not logged in to website)

![image](https://user-images.githubusercontent.com/27136773/86520733-17890580-be48-11ea-80d4-1f9cb73ec386.png)

**Comment by 27136773** [comment]
HakuNeko shows the first 6 chars of the revision hash, GitHub shows the first 7 characters, both are the same...

**Comment by arromdee** [comment]
I notice that your screenshiot uses the clipboard. 

When I find the page for The Gamer and copy it to the clipboard, then use [Clipboard], I do in fact get all chapters.

When I select "Line Webtoon (English)" instead of [Clipboard], then I only get the chapters on page 1.

**Comment by 27136773** [comment]
Your MangaList is probably outdated.
That said, LineWebtoon does not support to get the MangaList anymore, so Copy & Paste is the only way to get Mangas for now.
