### ISSUE TITLE
re: #1986

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1991]
> **From:** HakuNeko User

**Version:** [master@af81a8](https://github.com/manga-download/hakuneko/commits/af81a8)

I tried the stable version and the frame was indeed there but is removed when in fullscreen.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Sorry, no new tickets when answering an existing ticket this is way to confusing for the developers
=> This ticket will be ignored and closed
