### ISSUE TITLE
re : 1991

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1992]
> **From:** HakuNeko User

**Version:** [6.1.7@39507a](https://github.com/manga-download/hakuneko/commits/39507a)

Please disregard. It was an issue with my laptop which needed to a restart to resolve. I've never needed to restart from something like this before, but I should have been more thorough.  My apologies. The stable version frame is good to go even in fullscreen.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Sorry, no new tickets when answering an existing ticket this is way to confusing for the developers
=> This ticket will be ignored and closed
