### ISSUE TITLE
Using multiple Versions of HakuNeko?

### ISSUE THREAD

**Issue by K-snakes** [manga-download/hakuneko#1999]
Is it possible using more than just one version of hakuneko? 

_For example_ I have the stable version but if i were to download the nightly one while leaving the other one alone without deleting it can i switch between them?

**Comment by 27136773** [comment]
You can use as many as you want, but depending on `setup` or `portable` mix and HakuNeko's bookmark directory setting you may or may not share settings and bookmarks between different versions...

**Comment by 27136773** [comment]
Oh maybe i was wrong... when installing a new version it may update the previous installed version not sure about this, better ask in discord

**Comment by Robonau** [comment]
i mean you can have as many different portable versions as u want, and you could probably change the install directory for a setup ver

**Comment by K-snakes** [comment]
Ok thanks guys

**Comment by 27136773** [comment]
seems to be answered
