### ISSUE TITLE
Open Chapters in file Explorer & Remove MangaFox Bottom Watermark

### ISSUE THREAD

**Issue by randoomdude** [manga-download/hakuneko#2]
I'm coming off another manga downloader I used for a long time and noticed a couple features that I thought would make the program.

It would be really nice if from the chapter list you'd be able to open up the folder where the files are saved, instead it justs asks if you want to re-download the chapter when you click on the completed file when the cloud icon changes to a folder, which I don't think is that useful.

Also the old manga downloader I used before, Domsoft Manga Downloader had a feature with Mangafox the would crop the extra bit they add at the bottom of each chapter, I don't know how hard the would be to implement but it was an amazing feature that went a long way in making series I'd read more enjoyable without that annoying text at the bottom of each page.

**Comment by randoomdude** [comment]
Also maybe having automatic chapter download for new chapters in your bookmarks, and having newest downloaded chapters shown for quick access.

**Comment by randoomdude** [comment]
Also maybe optional automatic naming of chapters, either by Name/Chapter or Chapter/Name and chapter order convention of 1,2,3/01,02,03 etc.

**Comment by 27136773** [comment]
Project page is on sourceforge, discussions and issues will be tracked there.
I think some of your suggestions are already taken in consideration.

**Comment by 27136773** [comment]
The ability to open the manga folder for a chapter has been added in rev. e94b7192
Double click on the title of a chapter to show it in the file browser.

**Comment by 27136773** [comment]
Images hosted on MangaFox are really bad in quality, cropping and re-saving them would even reduce the quality more (or increase the file size when saving as PNG).

This will not be implemented, a workaround could be to use a more powerful external tool to do the job, or only use MangaFox for reading and download the images from other website resources with better quality.

**Comment by randoomdude** [comment]
Thanks, I appreciate the changes you've made since last year, by far the best downloader out there now.
