### ISSUE TITLE
mangadods has connecting issues

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2004]
> **From:** HakuNeko User

**Version:** [6.1.7@508cba](https://github.com/manga-download/hakuneko/commits/508cba)

It takes a few tries to successfully connect.

Thanks.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
This is an website error (Internal Server Error 500)
