### ISSUE TITLE
Please disregard #2004 

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2005]
> **From:** HakuNeko User

**Version:** [6.1.7@508cba](https://github.com/manga-download/hakuneko/commits/508cba)

Mangadods site is the issue itself. When I first checked it seemed the site was fine but I hit refresh a couple times realized the site itself takes a few tries.

Sorry.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Sorry, no new tickets when answering an existing ticket this is way to confusing for the developers
=> This ticket will be ignored and closed
