### ISSUE TITLE
[Feature]clicking on the chapter should open the preview

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2010]
**Is your feature request related to a problem? Please describe.**
having to click on the tiny preview kinda annoying

**Describe the solution you'd like**
when clicking where the mouse is in the pic
 ![](https://i.imgur.com/w89pYyb.png)
it should open the preview, as it is right now it does nothing
it just makes sense that clicking there would open the chapter

**Describe alternatives you've considered**
clicking the preview button

**Context (please complete the following information):**
 - Your current HakuNeko Version [master a couple days ago]

**Additional context**

**Comment by Sheepux** [comment]
Seems right to me. 
@ronny1982 are you thinking of any particular reason not to do it ?
Styleworthy: no anchor link (blue underline) should be displayed

**Comment by 27136773** [comment]
Some edge cases might need a second thought:
- It may interfere with double click to open the folder containing the chapter (accidental double-single-clicking, shared tooltip)
- If the preview is disabled (e.g. in offline mode when chapter is not downloaded) the click will not work and the user might think it is a bug, however the preview button is not visible in such a situation

**Comment by Robonau** [comment]
1. swap the open preview button to an open folder button and have click the way to open it
2. a popup msg when in offline mode and you attempt to open an online chapter saying "you are offline and can't open a non downloaded chapter"

just some possible solutions to the problems that you brought up
