### ISSUE TITLE
Mangasee URL change

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2011]
> **From:** HakuNeko User

**Version:** [6.1.7@d8c08b](https://github.com/manga-download/hakuneko/commits/d8c08b)

Hi, I got a problem to update from mangasee, it just recently changed from mangaseeonline.us to mangasee123.com, therefore it cause update to fail. So how should I resolve this? If possible in simple way (cuz I'm not an IT guy that really understand in coding) 

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by XenonR** [comment]
There is no possibility to update the URL 'localy'. If it's just an URL change it will be fixed quite soon.

**Comment by 27136773** [comment]
Your version is outdated, this change is already merged. Try to get support in discord to figure out why you don't get automatic updates...

https://github.com/manga-download/hakuneko/blob/508cba1a6126290510fe8b424ccb71d312706fd8/src/web/mjs/connectors/MangaSee.mjs#L10
