### ISSUE TITLE
[Bug] Academy.vn no longer works

### ISSUE THREAD

**Issue by NeverSm1le** [manga-download/hakuneko#2015]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes. I clicked the "open in new website" button and it's still working.
**Describe the bug**
The website has changed its name to hocvientruyentranh.net, so it's possible that the manga list is not updating because it connects to the old manga list.
**To Reproduce**
1. Name of connector: AcademyVN
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
There are 2 errors in the console:
Failed to load resource: net::ERR_FILE_NOT_FOUND
BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
Also a relevant warning: 
_getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'E:\Hakuneko\userdata\hakuneko.mangas.academyvn'
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
Since the website was never implemented, i suggest to rename it from `AcademyVN` to `Hoc Vien Truyen Tranh` and change the ID to `hocvientruyentranh`

Manga List: https://hocvientruyentranh.net/truyen/all

**Comment by newaccforhc** [comment]
This looks like an easy site.. Maybe I'll add it if I get time..

**Comment by newaccforhc** [comment]
Yeah.. This site wasn't even added before.. 
the code literally says, 
`Please report this broken website on HakuNeko\'s GitHub project page.`
LMFAO

**Comment by NeverSm1le** [comment]
Thank you for responding quickly!

**Comment by newaccforhc** [comment]
@NeverSm1le I've added the site.. Wait till it's verified by ronny...

**NOTE:** The Manga List has 217 Pages and will take hours to sync.. I haven't waited till it syncs all 217 pages but, I didn't get any error till page 10... So, technically it should work for all pages. Still I recommend URI method.
