### ISSUE TITLE
ManhuaPlus not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2016]
> **From:** HakuNeko User

**Version:** [6.1.7@508cba](https://github.com/manga-download/hakuneko/commits/508cba)

Seems they have changed there site to a different format and is no longer showing anything.

THanks.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
![image](https://user-images.githubusercontent.com/27136773/87220097-6f9c9c00-c361-11ea-8fc1-dab0d5ecd89d.png)
