### ISSUE TITLE
cryptojs

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2017]
> **From:** HakuNeko User

**Version:** [master@a36118](https://github.com/manga-download/hakuneko/commits/a36118)

hello, i have an issue with seveveral sites, such as, manganelo,1stkissmanga, wakamics, zinmanga, mangasy. Every time, it's "CryptoJs is not defined"......

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Provide sample website/manga/chapter, otherwise it cannot be reproduced

**Comment by 27136773** [comment]
No further response => closed
