### ISSUE TITLE
[Site Request] https://kissmanga.org/

### ISSUE THREAD

**Issue by Hisashi-Reyuga** [manga-download/hakuneko#2018]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
The ticket information was not filled properly,  a dev would not know what to do, especially why a clone of KissManga.com should be added...
