### ISSUE TITLE
[Bug] Silent error in discord presence

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#2022]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
No

**Describe the bug**
Discord presence throws an uncaught error when transitioning from `start` to `stop`

**To Reproduce**
1. Start HakuNeko (nightly), press press F12 to show error console tab
2. Open settings and change discord presence by applying changes in the following order:
`No presence` > `All but hentai` > `No presence`
3. See error when transitioning from enabled to disabled

**Expected behavior**
No error should be shown

**Context (please complete the following information):**
 - OS: any
 - HakuNeko Nightly or Development (master)

**Screenshots**
![image](https://user-images.githubusercontent.com/27136773/87225752-79d58f00-c38f-11ea-952c-3286b39c2895.png)

**Comment by XenonR** [comment]
Cannot reproduce. Is this with or without PR #2023 ?

**Comment by 27136773** [comment]
Maybe it has something to do with discord's game activity (which is disabled in my discord client)
Also haven't tested the behavior if discord isn't even running at all
Make sure to apply the settings after every change, just selecting the combobox won't apply the settings until saved.

It is with and without #2023

**Comment by XenonR** [comment]
Ok. I can reproduce the issue by changing status multiple times back to back. This edge case violates the 15 second update rule of discord. Working on a fix. I assume you hit the problem during development where you reloaded multiple times?

**Comment by 27136773** [comment]
If there is no further harm it might be enough to caught the error and wrap it into an informative warning

**Comment by XenonR** [comment]
Yes , but I have to handle the reconnection. I'll also try to avoid this edge case.

**Comment by XenonR** [comment]
This seems to be the closest i can get: 
![image](https://user-images.githubusercontent.com/18627623/93613092-af6ea800-f9d0-11ea-9c19-2a3b5e7d3429.png)
Do i miss something? Code @ https://github.com/XenonR/hakuneko/commit/1736c38cfce44cdbedd05aa228212ba9deaf533f
