### ISSUE TITLE
[loveheaven.net] Connector not working

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#2025]
Site; loveheaven.net
GN; RAW MANGA
Prob; 
Manga List does not download. Timed out.
Consol does not have any reaction. It doesn't even download any files.

Note; It may have been moved to the "kisslove" site.   They have abandoned "loveheaven".

![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/87228486-3f2d2000-c3aa-11ea-8df8-9329a0940bae.PNG)

**Comment by XenonR** [comment]
Not reproducable and works as expected here:
![image](https://user-images.githubusercontent.com/18627623/87230683-eceffd00-c3b1-11ea-800e-652c32741164.png)
loveheaven.net

**Comment by newaccforhc** [comment]
Are you sure loveheaven.net is abandoned?? Coz, it's working perfectly fine and the site shows latest update just 7 hours ago...

**Comment by areglos** [comment]
It still doesn't load the manga list. I am browsing the site, but when I say renew list, timeout occurs.
There must be an internet problem. If you don't have any problems.

**Comment by 27136773** [comment]
Try manual website interaction and then synchronize manga list again, sometimes it takes longer then 60 seconds to load all resources, so a manual website interaction may help to pull the resources into cache and prevent such a timeout...
