### ISSUE TITLE
[Allporncomics] Connector not working

### ISSUE THREAD

**Issue by tommyra** [manga-download/hakuneko#2027]
![Screenshot](https://user-images.githubusercontent.com/44010084/87229100-4593ab80-c35a-11ea-97ec-e17473fb6c43.png)
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced, maybe network/dns/antivir/... problem

Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by 27136773** [comment]
No further response => closed

**Comment by tommyra** [comment]
Now again same problem....please check and solve

**Comment by tommyra** [comment]
Thanks Manga-Download/Hakuneko
   Now again same problem ...please check and solve
