### ISSUE TITLE
re:  ManhuaPlus not working #2016

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2028]
> **From:** HakuNeko User

**Version:** [6.1.7@508cba](https://github.com/manga-download/hakuneko/commits/508cba)

Site was working at the time of the issues and is working now with the same problems.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Sorry, no new tickets when answering an existing ticket this is way to confusing for the developers
=> This ticket will be ignored and closed
