### ISSUE TITLE
[Site Request] Kurostream

### ISSUE THREAD

**Issue by kikuKeii** [manga-download/hakuneko#2029]
**Name of the website**
KuroStream - Nonton Anime Subtitle Indonesia

**Website urls (examples below)**
- Site: https://kurostream/
- Anime List:https://www.kurostream.com/anime-lists/
- Anime example: https://www.kurostream.com/anime/boruto-naruto-next-generations/
- Episode online viewer example: https://www.kurostream.com/boruto-naruto-next-generations-episode-155-subtitle-indonesia/

**Languages**
Indonesian

**Comment by MikeZeDev** [comment]
Website dead ? @Sheepux  please <3

**Comment by Sheepux** [comment]
no alternative domain found
