### ISSUE TITLE
[Japanread] Empty connector list & clipboard issue

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2036]
> **From:** HakuNeko User

**Version:** [6.1.7@508cba](https://github.com/manga-download/hakuneko/commits/508cba)

La manga liste ne se met pas à jours. L'utilisation du copier/coller de l'url de la page n'affiche pas le titre du manga mais Manga #CD0 (exemple manga Don't Mess With Me, Miss)

<details><summary>What has been done?</summary>

</details>

**Comment by Robonau** [comment]
1.support is provided in english (im using google translate to read what you said)
2.that's just how the clipboard function works (as far as i am aware)
3.if you bookmark the manga you can change the name using the solution given to #1911

**Comment by newaccforhc** [comment]
@09morbab 
>2.that's just how the clipboard function works (as far as i am aware)

Nope... This is definitely not how it should work (Ideally)
I think old connectors have these kind of issues. I just did some changes and it fixed the problem... But, now the code looks really messy... I'm thinking about rewriting the whole code for this connector instead..

**Comment by Sheepux** [comment]
Clipboard works, but the title is not the correct one.
However the list is working (i can see the website calls) but doesn't display in the end, going to check

(FR)
Ok vu pour le problème de nom du chapitre.
Bizarre pour la liste, cela devrait fonctionner (je vois les appels au site passer). Je confirme que la liste est anormalement vide.

**Comment by newaccforhc** [comment]
@Sheepux I've fixed it.. lemme create a pull request.

**Comment by newaccforhc** [comment]
@Sheepux The website change label is wrong... It should be 'Bug'
The website was completely same as earlier...

**Comment by Sheepux** [comment]
It only means "issue related to a connector", i'll ask ronny to change the label name ;)

**Comment by newaccforhc** [comment]
okay..

**Comment by Robonau** [comment]
im over here having never seen the correct name using clipboard so just thought it was how it works
