### ISSUE TITLE
[Tumangaonline] Connector not working

### ISSUE THREAD

**Issue by swordart16** [manga-download/hakuneko#2037]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
failed to update manga list

**To Reproduce**
1. Tumangaonline
4. Connector.mjs:553 Error: This website does not provide a manga list, please copy and paste the URL containing the chapters directly from your browser into HakuNeko.
    at TuMangaOnline._getMangas (TuMangaOnline.mjs:4)
    at TuMangaOnline._getMangaList (Connector.mjs:550)
    at Connector.mjs:105 
TuMangaOnline
**Screenshots**
![image](https://user-images.githubusercontent.com/55258719/87259082-2c7c1f00-c46e-11ea-9f75-04ba180e4e75.png)

**HakuNeko (please complete the following information):**
version: nightly(master) • 2020-07-05T00:14:37UTC

**Comment by Robonau** [comment]
it was one of the connectors that was provided by the no longer online cdn
do as the error says and use the clipboard feature to read manga from the site

**Comment by newaccforhc** [comment]
This isn't really an issue.. @ronny1982 close this.

**Comment by Sheepux** [comment]
The connector is working as intented (use the clipboard). However the "error" message should be improved.
Closing the request.
