### ISSUE TITLE
[NetEase Comic (manga BiliBili)] Connector not working

### ISSUE THREAD

**Issue by AetherniR** [manga-download/hakuneko#2044]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Download from HakuNeko not working. After chosing site, get error 400.

**To Reproduce**
1. Try to get site manga list from Hakuneko or try to get chapter list from copyboard of BiliBili title [for sample: https://manga.bilibili.com/detail/mc25820]
2. Console error screen. 
![изображение](https://user-images.githubusercontent.com/68249274/87351665-721a1400-c562-11ea-8b65-d11ab0cc7bc6.png)

**Screenshots**

![изображение](https://user-images.githubusercontent.com/68249274/87351592-4c8d0a80-c562-11ea-9cf2-9b0ea9f6047d.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
 - Master build [bd7d0b]

P.S. A few days ago all are working. Site opened from browser, even from mobile app to android or iOS and cache manga from them.
![изображение](https://user-images.githubusercontent.com/68249274/87352092-2451db80-c563-11ea-81fa-0113e8061cf8.png)

**Comment by Robonau** [comment]
i already made an issue for this #2043 (40 mins earlier)
though you do go more in depth on what is wrong, it should have been done in a comment on #2043
