### ISSUE TITLE
[Site Request] manga-raw.club

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#2046]
**Name of the website**
Manga-Raw CL

**Website urls (examples below)**
- Site: https://www.manga-raw.club/
- Manga List: https://www.manga-raw.club/browse/
- Manga example: https://www.manga-raw.club/manga/first-class-servant/
- Manga RAW "div":  onclick="showDivRaw()"  
- Chapter online viewer example: https://www.manga-raw.club/reader/first-class-servant-chapter-1/

**Languages**
"JP, CN, KR (RAW, Webtoon, Manhwa)

**Website relationship**
"----------?-------"

**Additional details**
"--------?---------"

**Comment by newaccforhc** [comment]
Is there any manga on that site having both Raw as well as English Chapters?

**Comment by newaccforhc** [comment]
nvm, I got it: https://www.manga-raw.club/manga/the-undefeatable-swordsman/

**Comment by areglos** [comment]
> Is there any manga on that site having both Raw as well as English Chapters?

Just give importance to "Raw". English may not be permanent.

**Comment by newaccforhc** [comment]
Nah... Whenever we implement site, we try to get everything.. Well... It'll take time to implement this site... I'm doing some other site right now..

**Comment by 27136773** [comment]
See: #2433
