### ISSUE TITLE
[Japscan] Small / unusual picture size get the download in error

### ISSUE THREAD

**Issue by satsukiyatoshi** [manga-download/hakuneko#2049]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
Some manga on japscan don't work each time i try (cancel at the end)

**To Reproduce**
1)Try to download "Air Gear" Volume 8 or Volume 9 for exemple or akane-chan overdrive volume 2
2)Wait for the download to complete
3)It'll crash at the end

**Context (please complete the following information):**
 - OS : Windows10 64 bits
 - HakuNeko Stable and nightly versions, 32bits and 64bits

Seem to be related to the scan picture size.
All the manga with this bug have a very small / unusual picture size in the manga (https://www.japscan.co/lecture-en-ligne/air-gear/volume-8/109.html or https://www.japscan.co/lecture-en-ligne/akane-chan-overdrive/volume-2/4.html for exemple)

![Screen Shot 014](https://user-images.githubusercontent.com/8547498/87428398-9289b300-c5e2-11ea-96e3-04342c87f42a.PNG)

![Screen Shot 015](https://user-images.githubusercontent.com/8547498/87428408-94ec0d00-c5e2-11ea-9e76-b8bc30745314.PNG)

**Comment by 27136773** [comment]
Actually it is not a crash, but a protection against fake images which needs to be adjusted

**Comment by 27136773** [comment]
First Image: `317 * 95 = 30115`
Second Image: `294 * 761 = 223734`

Need to discuss new limits ...

**Comment by satsukiyatoshi** [comment]
"Actually it is not a crash, but a protection against fake images which needs to be adjusted"
i understand fake picture need to be removed, but with in this case the downloading is canceled instead of just ignoring bad picture ?
or a simple way to do it would be to have one setting:
-"Ignore the pictures smaller than xxxx pixels"
so it will just ignore those pictures and not cancel the whole download, and anyone can try on the fly his best value in case of bugs ?

**Comment by 27136773** [comment]
I think there aren't fake images anymore, so simply reducing the detection value is the fastest and simplest solution for now. Don't want to invest too much time if it works with minimal investment.

**Comment by satsukiyatoshi** [comment]
Bug here again, for exemple impossible to download alice 19th volume 5:
https://www.japscan.co/lecture-en-ligne/alice-19th/volume-5/100.html

![Screen Shot 017](https://user-images.githubusercontent.com/8547498/87684104-234ac500-c782-11ea-98b4-d4597cc303f0.PNG)

**Comment by 27136773** [comment]
Is this the smallest image found so far, i would like to prevent adjusting the image detection on a regular basis?
