### ISSUE TITLE
Hotkey support for the Reader

### ISSUE THREAD

**Issue by fahim2690** [manga-download/hakuneko#205]
Would really appreciate it if I could use hotkeys for changing chapters, zoom level and changing between vertical scrolling and webtoon.

**Comment by 27136773** [comment]
propose keys

**Comment by fahim2690** [comment]
Best would be adjustable hotkeys but Page Up/Down for Chapters, Ctrl + +/- for Zoom and Shift + +/- for Page Gap respectively should be fine.

**Comment by 27136773** [comment]
Current findings:

- `Shift` key must not be used, e.g. some keyboard layouts require to press `Shift` to input a `+`, therfore it is impossible to press the `+` without `Shift` which may lead to unwanted collisions in the key-map
- The keypress event requires to keep focus on a certain element (e.g. the buttons bar) to work properly, therfore the focus must be somehow kept at the button bar
- As a result of the fixed focus, the arrow keys will no longer work to scroll the page and must also be implemented on the button bar
- For now the key-map will be hard-coded into the source code, it would be to complicated to add these into the settings with all the keys and the key combinations to configure by the user

**Comment by fahim2690** [comment]
If at least changing chapters + switching between zoom level works, I'm fine with that. I use scroll wheel scrolling either way so shouldn't be an issue.

**Comment by 27136773** [comment]
Keyboard shortcuts have been added to reader, mapping is shown in the tooltip of the buttons.

**Comment by fahim2690** [comment]
Thanks a lot, I really appreciate it.
