### ISSUE TITLE
[ニコニコ静画 (niconico seiga)] Connector not working

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#2052]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
For all NNS mangas I've tried, the chapters show in the chapter list and HakuNeko appears to download them, but their folders are empty.

**To Reproduce**
1. Name of connector: ニコニコ静画 (niconico seiga)
2. Name of manga: SSSS.GRIDMAN 新世紀中学生日記 (https://seiga.nicovideo.jp/comic/44580)
3. Name of chapter: The latest chapter, 第15話　未知との遭遇日記 (https://seiga.nicovideo.jp/watch/mg492192), although it's the same with all chapters for me.

**HakuNeko (please complete the following information):**
8.3.4

**Comment by 27136773** [comment]
You probably need to be logged in
https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#3-account-login
