### ISSUE TITLE
[Site Request] VRV Mondo

### ISSUE THREAD

**Issue by Ognisty321** [manga-download/hakuneko#2054]
**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]
6.1.7

**Additional context**
Hello, we have in hakuneko VRV Crunchyroll, HiDive and Rooster Teeth. Could you add VRV Mondo too? If not than it's a shame, but it would be great

**Comment by newaccforhc** [comment]
I think it's website suggestion... I'll change the label.
