### ISSUE TITLE
[Site Request] translate.webtoons.com

### ISSUE THREAD

**Issue by cloudsenpai** [manga-download/hakuneko#2055]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://translate.webtoons.com/
- Manga List: https://translate.webtoons.com/
- Manga example: https://translate.webtoons.com/webtoonVersion?webtoonNo=151&language=TUR&teamVersion=0
- Chapter online viewer example: https://translate.webtoons.com/viewer?webtoonNo=151&episodeNo=286&language=TUR&teamVersion=0

**Languages**
Turkish

Thank you.

**Comment by 27136773** [comment]
Website is already supported, please check the available websites before create a request.
