### ISSUE TITLE
mangasee123.com problem

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2058]
> **From:** HakuNeko User

**Version:** [master@c2b0e0](https://github.com/manga-download/hakuneko/commits/c2b0e0)

no chapters of any kind are apearing in any of their listed manga. the site is runing normaly in browser. i tried the latest stable and nightly releases with the same result. note the site just changed recently from mangasee.us to mangasee123.com

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Robonau** [comment]
![](https://i.imgur.com/S47IgEu.png)

can't replicate 
the url has already been updated to mangasee123.com
do you get any errors popup or in the f12 console

**Comment by kurama9t** [comment]
![Screenshot (377)](https://user-images.githubusercontent.com/68366163/87628803-68e39f80-c73a-11ea-888b-8f740a9533bc.png)
![Screenshot (378)](https://user-images.githubusercontent.com/68366163/87628808-6a14cc80-c73a-11ea-9333-a7b7f7968ed7.png)

**Comment by kurama9t** [comment]
sorry didn't know how to get the error report in text format. also site runs normally in pop up browser mode
![Screenshot (379)](https://user-images.githubusercontent.com/68366163/87629549-eb209380-c73b-11ea-907b-bc211af750f9.png)

**Comment by 27136773** [comment]
Make sure (stable) HakuNeko is up-do-date
Re-sync the manga list, they may have changed their manga links

**Comment by kurama9t** [comment]
thanks a million. seems the build i used was outdated just recently. tried the new 6.1.7 build and all is good. again thanks for all ur help

**Comment by ronny1982** [comment]
Check the Wiki,
e.g. https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list
