### ISSUE TITLE
[Manhuagui] Connector not working

### ISSUE THREAD

**Issue by SilverAsh4158** [manga-download/hakuneko#2059]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
There's no problem reading from the browser. I tried loading the list of Manhuagui for the first time, but I get 2 types of error message:
1) Can't be fetch
2) ERR_TIMED_OUT
And now i'm unable to read from browser without using a VPN

**To Reproduce**
1. Name of connector: **MANHUAGUI**
2. Name of manga (if connector update is working) **N/A**
3. Name of chapter (if manga update is working) **N/A**
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

> C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41 Uncaught (in promise) Error: ERR_TIMED_OUT (-7) loading 'https://www.manhuagui.com/?ts=1594864922362&rd=0.9868788830252777'
>     at rejectAndCleanup (C:\Program Files\HakuNeko Desktop\resources\electron.asar\browser\navigation-controller.js:67:29)
>     at WebContents.failListener (C:\Program Files\HakuNeko Desktop\resources\electron.asar\browser\navigation-controller.js:77:21)
>     at WebContents.emit (events.js:205:15)
> (anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:261
> metaToPlainObject @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:261
> error @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:217
> metaToValue @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:222
> (anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:214
> array @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:214
> metaToValue @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:222
> (anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
> (anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
> emit @ events.js:200
> onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
> 

**Screenshots**
![image](https://user-images.githubusercontent.com/68351191/87617636-46c43000-c6ee-11ea-907b-665aabd202cf.png)
![image](https://user-images.githubusercontent.com/68351191/87617907-e08bdd00-c6ee-11ea-92fe-1cdf989844e5.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Robonau** [comment]
![](https://i.imgur.com/QhDTOCZ.png)
when refreshing the list

![](https://i.imgur.com/sepLk6k.png)
when attempting to open in the haku browser

![](https://i.imgur.com/8ramFJn.png)
isitdown says its up

i guess they added a limit on requests per second that they didn't have prior and its banning the ip of anyone trying to get a list

**Comment by newaccforhc** [comment]
🤔 So, throttling needs to be added.

**Comment by Robonau** [comment]
it was a guess i don't actually know for sure

**Comment by newaccforhc** [comment]
I'll test it myself... I have dynamic IP So, I'll get to know easily..

**Comment by SilverAsh4158** [comment]
guess, for now we just have to copy and paste the links of manga.
I wonder if there's a limit of chapters we can download per minute oO? Last time i was able to download 3 chapters out of 255 before being blocked again. Problem is that i forgot to copy & paste those logs.

**Comment by newaccforhc** [comment]
IP got blocked while syncing the MangaList... But, didn't get blocked while downloading the chapters...
Downloaded 19 chapters of https://www.manhuagui.com/comic/33939/
and 7 chapters of https://www.manhuagui.com/comic/22942/ continuously without getting any error..

**Comment by newaccforhc** [comment]
And, it is an IP block... I restarted the internet (to get new IP) and the website works again.

**Comment by SilverAsh4158** [comment]
today i tried downloading https://www.manhuagui.com/comic/32864/
after 7 chapters i started to get connection time out and i suppose IP blocked since i couldn't load from browser either

> Connector.mjs:592 Error: ERR_CONNECTION_TIMED_OUT https://www.manhuagui.com/comic/32864/464440.html
>     at Request.mjs:381
>     at CallbacksRegistry.apply (F:\HAKUNEKO\resources\electron.asar\renderer\callbacks-registry.js:41)
>     at F:\HAKUNEKO\resources\electron.asar\renderer\api\remote.js:281
>     at EventEmitter.<anonymous> (F:\HAKUNEKO\resources\electron.asar\renderer\api\remote.js:271)
>     at EventEmitter.emit (events.js:200)
>     at Object.onMessage (F:\HAKUNEKO\resources\electron.asar\renderer\init.js:42) EventTargetfile: {name: "第18话", extension: "", full: "第18话"}id: "/comic/32864/464440.html"language: ""manga: EventTarget {connector: ManHuaGui, id: "/comic/32864/", title: "厨刀与小青椒之一日料理帖", status: "available", chapterCache: Array(25), …}pageCache: []pageProcess: falsestatus: "failed"title: "第18话"__proto__: EventTarget
> _getPageList @ Connector.mjs:592
> F:\HAKUNEKO\resources\electron.asar\renderer\callbacks-registry.js:41 Uncaught (in promise) Error: ERR_CONNECTION_TIMED_OUT (-118) loading 'https://www.manhuagui.com/comic/32864/464440.html'
>     at rejectAndCleanup (F:\HAKUNEKO\resources\electron.asar\browser\navigation-controller.js:67:29)
>     at WebContents.failListener (F:\HAKUNEKO\resources\electron.asar\browser\navigation-controller.js:77:21)
>     at WebContents.emit (events.js:205:15)

**Comment by newaccforhc** [comment]
Okay... So, I'll add Throttling while downloading images as well.. idk why I didn't get that error though..

**Comment by SilverAsh4158** [comment]
Thanks a lot for the help

**Comment by newaccforhc** [comment]
It's okay...
Wait till the pull request is approved and merged... 

I've added 2 values of throttle.. Use them accordingly from options menu... I couldn't test the best value for downloading chapters.. So, if you get blocked while downloading chapters then increase the throttle value... 
As for MangaList throttle value.. I've tested it and you'll get blocked below 4500...
