### ISSUE TITLE
[Mangakyo] Connector not working

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#2061]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site changed the url from : "https://www.mangakyo.com/"
to : "https://www.mangakyo.me/"

**To Reproduce**
1. Name of connector : Mangakyo
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MIRVOUS** [comment]
um sorry but, when i try to update the manga list it doesn't work(the manga list is blank)
![mangakyo-1](https://user-images.githubusercontent.com/45929526/88129047-50bfc480-cc01-11ea-84f9-09adf5afb4b9.PNG)

**Comment by newaccforhc** [comment]
Hmm... they changed real fast.. 🤔
Well.. Ronny fixed it so no problem
