### ISSUE TITLE
[Site Request] komiktap

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#2063]
**Name of the website**
komiktap

**Website urls (examples below)**
- Site: https://komiktap.net/
- Manga List: https://komiktap.net/a-z-list.html
- Manga : https://komiktap.net/manga/after-transformation-mine-and-her-wild-fantasy/
- Chapter online viewer : https://komiktap.net/manga/after-transformation-mine-and-her-wild-fantasy-chapter-66-bahasa-indonesia/

**Languages**
Indonesian

**Website relationship*

**Additional details**
i forget the template name, sorry.

**Comment by 27136773** [comment]
Lokks like `WordPressEManga` theme

**Comment by newaccforhc** [comment]
Lol... I opened this site, then saw a latest update of a hentai manga (Whose cover looked interesting).. then I searched for that manga on e-hentai and read it.. After I was done, then I realized that I opened that site to see if I can add it... LMFAO

**Comment by newaccforhc** [comment]
Okay... I'll try with `WordPressEManga` theme.
