### ISSUE TITLE
Chapter 51 of Made in Abyss on WebComicGamma fails to download

### ISSUE THREAD

**Issue by Atemu** [manga-download/hakuneko#207]
WebComicGamma -> メイドインアビス -> 最新エピソード大好評配信中!!［ハローアビス#&#8203;51］願いの形

The hover text in the download list gives me a generic and rather useless "Failed to fetch" error message after it fails.  
All other chapters work.

When I open the preview for the chapter it shows all pages except for page 28 which is page 29 on the website and that loads fine for me: http://webcomicgamma.takeshobo.co.jp/manga/madeinabyss/_files/051/

**Comment by 27136773** [comment]
Cannot be reproduced, image download works as expected (but is slow).
Anything suspicious in the developer tools (F12), e.g. console tab / network tab?

**Comment by Atemu** [comment]
It takes ~15s to load the image but that's it. Other images take >20s sometimes.

My internet connection is a bit unstable at the moment and TCP connections sometimes stall for multiple seconds but it loads just fine on the website and all the other pages and chapters work.

I believe I might have had this issue with one of the Made in abyss anthology chapters too but it worked after trying again once while I can't download this chapter even after countless retries.

Is there any way to increase verbosity in Hakuneko to help narrow down the issue?   "Failed to fetch" really doesn't tell me anything about exactly what went wrong.

**Comment by 27136773** [comment]
If there is no error log in the developer console or advanced info from the network tab than it is hard to locate the issue.

**Comment by Atemu** [comment]
Sorry, I'm not familiar with electron apps and didn't know they have an internal developer tools menu (makes sense though, it's just JS running in chromium afterall).   
So that's what you meant, not my browser's when I access the website normally *facepalm*.   

I did get a `ERR_CONTENT_LENGTH_MISMATCH` for 0025.jpg, `Failed to fetch` and `ERR_NOT_IMPLEMENTED` for 0025.ptimg.json and `Failed to fetch` for all chapter's ptimg.json in the console in the first try but for some reason the second just worked!  

I am not able to reproduce the issue anymore either, all my attempts work now.

**Comment by 27136773** [comment]
Glad to hear its working now, but to sad the problem could not be spotted.
Might be some cache in the network route that caused the trouble, but this is just a wild guess...
