### ISSUE TITLE
[Mangabat] Manga is hot-linked to a different provider

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2074]
> **From:** HakuNeko User

**Version:** [6.1.7@cc9029](https://github.com/manga-download/hakuneko/commits/cc9029)

Hello Devs, I had a little problems whenever I want to download all manga from mangabat.com it always shows:

"This manga is hot-linked to a different provider!
Please check the following website/connector"
https://read.mangabat.com"

Is there any way to fix this issue? I tried to check similar case but none shows.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Which manga/chapter?

**Comment by Sheepux** [comment]
Tried 1 (https://m.mangabat.com/read-kf388324) got the error
There is in fact a redirection from  mangabat.com to m.mangabat.com
TestOK (fixed with simple domain change)
Testing more  in the afternoon
