### ISSUE TITLE
[Bug] magic scroll next chapter not working sometimes

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2078]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
sometimes when getting to the bottom of a chapter with magic scroll it wont go to the next chapter
(no matter how many time i press space)

**To Reproduce**
1. 1st kiss manga 
2. hardcore leveling warrior
3. chapter 10
4. using magic scroll won't take you to the end of the page, and thus wont go to the next chapter
you have to scroll down a bit to use magic scroll to go the the next page

**Expected behavior**
it take you to the end of the page and then to the next

**Screenshots**
won't go to the next chapter and wont go to the end of it
![](https://i.imgur.com/ze2OdSG.png)

will go to the next chapter 
![](https://i.imgur.com/mnh8eA4.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [master]

**Additional context**
im in portrait idk if that's gonna make a difference

**Comment by Sheepux** [comment]
Able to reproduce with that specific chapter. That's probably a pixel perfect case.

**Comment by Robonau** [comment]
it happens allot in that mahwa 
at least at the start

**Comment by Robonau** [comment]
im having it happen in other manhwa on different sites as well now (isekaiscan : magic emperor : chapter 106-8 possibly earlier ones)

**Comment by Robonau** [comment]
i think it happens whenever the top of the last page isn't on screen (have tested, it is this)(i tested by switching from portrait to landscape on the same manga and it worked on portrait but not landscape)
which makes it just not work for most manga using landscape mode unless u zoom out a bunch

**Comment by Sheepux** [comment]
Ohhh, indeed. Thanks for the tests. That's going to be easier to fix.

**Comment by Sheepux** [comment]
Yep, pixel perfect case: "826.324 - 826 is not <0 " :D changing to <1

**Comment by Robonau** [comment]
that is an eerily similar fix to #1957
(changing a 0 to a 1 that is)
