### ISSUE TITLE
[Site Request] anirune

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2081]
> **From:** HakuNeko User

**Version:** [6.1.7@cc9029](https://github.com/manga-download/hakuneko/commits/cc9029)

https://anirune.com/
language : turkey
theme madara wordpress

<details><summary>What has been done?</summary>

</details>

**Comment by Sheepux** [comment]
I would advise contributors not to give a priority to this particular connector because of recent requests of turkish content stealers.
