### ISSUE TITLE
[Site Request] caisemh.com

### ISSUE THREAD

**Issue by MoonGoblinDev** [manga-download/hakuneko#2088]
**Name of the website**
CaiseMH

**Website urls** 
- Site: https://www.caisemh.com/
- Manga List: https://www.caisemh.com/booklist?end=0
- Manga example: https://www.caisemh.com/book/622
- Chapter online viewer example: https://www.caisemh.com/chapter/25041

**Languages**
Chinese

**Website relationship**
https://www.kelemh.com/ (Same content with different domain)

**Additional details**
Chapter in the site can only be accessed with mobile view browser. On PC I usually use developer tool in chrome / use responsive design mode in firefox

**Note :**
This is one of the best website containing CN Manhwa RAW.. adding this to Hakuneko will help us scanlator greatly, thank you~

**Comment by 27136773** [comment]
Template: <Looks familiar, but could not tell right now...>

**Comment by Robonau** [comment]
same as "Kuimh"(i think)
