### ISSUE TITLE
[Site Request] amote69.com (kkpMH)

### ISSUE THREAD

**Issue by MoonGoblinDev** [manga-download/hakuneko#2089]
**Name of the website**
kkpMH

**Website urls (examples below)**
- Site: https://amote69.com/
- Manga List: https://amote69.com/全部漫画/
- Manga example: https://amote69.com/comic/book/S-Mate
- Chapter online viewer example: https://amote69.com/s-mate-第20話-我這麼好色不好嗎/
- Register page: https://amote69.com/kkpmhregisteraa8011/
- Login page: https://amote69.com/login/

**Languages**
Chinese

**Website relationship**
http://kkpmh.ga/ = the whole family site bookmark (if they changed the domain, we can find the new one here)
kkpmh.com = will redirect to https://amote69.com/
https://wai36.com/ = same content with different domain

**Additional details**
Need to register and log in to see complete chapter

**Note :**
This one is also one of the best website containing CN Manhwa RAW.. adding this to Hakuneko will help us manhwa scanlator greatly, thank you~

**Comment by MikeZeDev** [comment]
Website is gone. @Sheepux please? :p

**Comment by Sheepux** [comment]
no alternative domain found, only bait leftovers
