### ISSUE TITLE
Raven scans spanish issue

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2092]
> **From:** HakuNeko User

**Version:** [6.1.7@cc9029](https://github.com/manga-download/hakuneko/commits/cc9029)

Hi, when i try to refresh the list of raven scans (spanish) gives me an error of language in query.works (uknown argument "language" on field "query.works". did you mean "languages"?

<details><summary>What has been done?</summary>

</details>

**Comment by Robonau** [comment]
![](https://i.imgur.com/BlpOc8V.png)

![](https://i.imgur.com/mNASVzm.png)

loads fine in browser (though its english cause it's the same url)
![](https://i.imgur.com/0BPbK9j.png)
