### ISSUE TITLE
clipboard

### ISSUE THREAD

**Issue by mangatabar** [manga-download/hakuneko#210]
can we download few link in one time . example
http;//mangakita.com/mangaku/ch1
http://mangakita.com/mangaku/ch2

**Comment by 27136773** [comment]
Select the manga and then use the "Download All Chapters" button as described in the [Quick Reference](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#chapter-list) ②

**Comment by 27136773** [comment]
Seems the there are no further questions => closed
