### ISSUE TITLE
Problem with Tumanga/Lectormanga

### ISSUE THREAD

**Issue by Uc690** [manga-download/hakuneko#2101]
Hi, I'm having a problem viewing the manga in Tumanga / Lectormanga and I don't know how to fix it. The problem I have is when I click on the page nothing loads, 0 mangas appear and when I try to update it says error, this have been happened in both pages and I don't know how to solve this problem
![Annotation 2020-07-23 095336](https://user-images.githubusercontent.com/53823367/88241403-5aaef980-cccd-11ea-88bd-ed028d848627.png)
![Annotation 2020-07-23 0953361](https://user-images.githubusercontent.com/53823367/88241407-5be02680-cccd-11ea-876b-e4cb7030ae73.png)

thanks

**Comment by Robonau** [comment]
as the error says 
tumanga does not provide a list (it is a connector that would take hours to get a list from)
if you want to read manga from tumanga you will have to get the url from the site (for any specific manga) and use the clipboard function

**Comment by 27136773** [comment]
Works as designed
