### ISSUE TITLE
kissmanga captcha

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2102]
> **From:** HakuNeko User

**Version:** [6.1.7@1b36ae](https://github.com/manga-download/hakuneko/commits/1b36ae)

do i have to captcha every manga i download? i mean 1 chapter 1 captcha then so on

<details><summary>What has been done?</summary>

</details>

**Comment by Cistmist** [comment]
If you check the website, you can see that they turned on the captcha on every chapter recently due to a copyright bot attack.

**Comment by 27136773** [comment]
See explanation from @Cistmist
