### ISSUE TITLE
[Mangabat] Hot linked to a different provider

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2103]
> **From:** HakuNeko User

**Version:** [6.1.7@1b36ae](https://github.com/manga-download/hakuneko/commits/1b36ae)

Hi, I saw other post shows problems which same with mine, whenever I click any manga it shows "This manga is hot-linked to a different provider!, Please check the following website/connector, https://read.mangabat.com"

I tried to download manga Tamarowa, Swweeet, Girlfriends, Killing Bites and many other manga, it appear this notification. Is it issue from the program?? If so, could you please help me how to fix this? Cuz I don't understand what to do by reading comment in other similar post like this.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction

</details>

**Comment by 27136773** [comment]
The dialog says exactly what to do, download your manga from MangaBat instead from the website you tried to download it.

That said, there is a pending PR #2086 (Draft) that will add support for cross-linking in case it is approved, so mangas from other affiliates websites can directly be downloaded.

**Comment by 27136773** [comment]
It would also be helpful to list the website / manga / chapter you tried to download...

**Comment by 27136773** [comment]
No further response with examples.
Right now it still works as intended as long as the PR/Draft is not accepted => closed
