### ISSUE TITLE
comic walker

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2107]
> **From:** HakuNeko User

**Version:** [latest](https://github.com/manga-download/hakuneko/commits/latest)

i tried to download from comic walker but it just black 

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
You forgot to mention which manga/chapter, without this information probably none of the developers will bother trying to reproduce the issue...

**Comment by Robonau** [comment]
i've looked at a couple different manga and all seem to work fine
it's most likely that the site does not have the chapter or is .bin files (broken)
![](https://i.imgur.com/trv9TT0.png)

can't reproduce the issue

**Comment by 27136773** [comment]
Not reproducible, no further response => closed
