### ISSUE TITLE
Dynasty-scans Download error (more detailed)

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2110]
> **From:** HakuNeko User

**Version:** [6.1.7@1b36ae](https://github.com/manga-download/hakuneko/commits/1b36ae)

Before, I could download chapters from Dynasty-scans. Unfortunately, whenever I try to download new chapters since a month ago, the error: supplied data is not a JPEG, would always appear. An example of this is the manga, Semelparous. Although, the error appears with most of the manga coming from this website. I would love to send a screenshot, but I do not know how. Thanks in advance.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Provide a sample manga/chapter and selected output format (e.g. PDF)

**Comment by fatezuru** [comment]
Hi, I was the one who reported this issue. Here is what I am talking about.
![hakuneko](https://user-images.githubusercontent.com/68878997/88601292-e399ac80-d0a2-11ea-82ae-dd359a603788.png)

**Comment by fatezuru** [comment]
Here is another one with the error written over it.
![haku](https://user-images.githubusercontent.com/68878997/88601546-82bea400-d0a3-11ea-9e84-c69868c478c5.png)

**Comment by 27136773** [comment]
See #1973
