### ISSUE TITLE
[Site Request] Bufftoon

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#2111]
**Name of the website**
Bufftoon

**Website urls (examples below)**
- Site: https://bufftoon.plaync.com/
- Manga List: https://bufftoon.plaync.com/webtoon/scheduled
                     https://bufftoon.plaync.com/novel/scheduled
                     https://bufftoon.plaync.com/comicbook/scheduled
                     https://bufftoon.plaync.com/comix/completed
                     https://bufftoon.plaync.com/rank
- Manga example: https://bufftoon.plaync.com/series/10099
- Chapter online viewer example: https://bufftoon.plaync.com/series/10099/3239431

**Languages**
Korean

**Website relationship*
no afiliate

**Additional details**
for webtoons/novels/mangas
just checked a bit and no security on the free chapters, it has an api call that just spits out all image urls. didn't try the paid ones
(or well more precisely the api asks for login creds on the paid ones)
tried on this one:

https://bufftoon.plaync.com/series/1002024/3064290 -> https://api-bufftoon.plaync.com/v1/series/1002024/episodes/3064290

**Comment by MikeZeDev** [comment]
dead?
