### ISSUE TITLE
Plot Twist No Fansub

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2114]
> **From:** HakuNeko User

**Version:** [6.1.7@62f10d](https://github.com/manga-download/hakuneko/commits/62f10d)

Download failed (ReferencEerror: obj is not defined)

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Which manga/chapter (provide at least one sample)?

**Comment by 27136773** [comment]
No further response => closed
