### ISSUE TITLE
[Feature] Crunchyroll manga Volume download

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#2115]
**Describe the solution you'd like**
If possible, please add option to download the volumes from CrunchyManga.

**Describe alternatives you've considered**
Providing option to save the volume covers as volumes are basically cover+Updated chapters.

**Comment by 27136773** [comment]
I don't see any volumes on CrunchyRoll, please explain in more detail and provide a sample.
Furthermore HakuNeko has no concept of volumes.

**Comment by amit34521** [comment]
![Capture](https://user-images.githubusercontent.com/14815570/88832571-a4787200-d1ee-11ea-9309-912b6ab54392.JPG)
Something Like the example above. every chapter has a volume id and chapter num. 
![Capture2](https://user-images.githubusercontent.com/14815570/88832905-1cdf3300-d1ef-11ea-8f13-95efee75c238.JPG)
So the list chapters returns the chapter page and associated volume cover details.

You can check 7ouma's CrunchyManga for the volume details. he has included the volumes download option starting line 345

**Comment by 27136773** [comment]
Technically it is possible to add the cover to each chapter, but i'm not sure if the other users would like to have the same cover at the beginning of each chapter, especially when the chapter also have a chapter cover...

**Comment by amit34521** [comment]
Instead of adding it to each chapter, why not put in the base manga folder? that way even if the user downloads multiple chapters, there will be only one unique cover image in base folder with format like "Cover-{volume_id_from_json}".
Also this can be made optional with downloadCovers as false by default. that way those who dont specifically look for it wont have any issues.

**Comment by 27136773** [comment]
HakuNeko has no mechanics to store additional data in the manga directories, therefore implementing such is way too much effort.
Compared to how easy it is for the users to manually download the manga cover images, there would be almost no added value for such implementation.

One task one ticket, only exception when they are strongly related

=> rejected
