### ISSUE TITLE
[Site Request] manhwas.men

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#2116]
**Name of the website**
manhwas men

**Website urls (examples below)**
- Site: https://manhwas.men/
- Manga List: https://manhwas.men/manga-list
- Manga example: https://manhwas.men/manga/company
- Chapter online viewer example: https://manhwas.men/manga/company/01/1

**Comment by 27136773** [comment]
Template: MangaReaderCMS

**Comment by 27136773** [comment]
See #2242
