### ISSUE TITLE
[Mangas.in] Continuously changing to defeat HakuNeko

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#2117]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
all mangas download 1kb .cbz files

**To Reproduce**
1. Mangas.in
2. All mangas
3. All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![E72RaUA](https://user-images.githubusercontent.com/65744036/88867685-31fe9680-d1dc-11ea-9d15-a956303f4e16.png)
Chapter download after the problem and before 
![image](https://user-images.githubusercontent.com/65744036/88867862-a89b9400-d1dc-11ea-9424-0d9d11c3e3a8.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Please provide a sample manga / chapter for reproduction

**Comment by rausina** [comment]
The file is empty
[⟶ #116.2                      Capítulo 116.2.zip](https://github.com/manga-download/hakuneko/files/5004459/116.2.Capitulo.116.2.zip)

**Comment by 27136773** [comment]
Reproducible with: `29 to JK`, `#29 Polvo de Estrellas y Chocolate`

Next time please provide a sample manga & chapter, the developers don't have time to search through thousands of mangas and chapters looking for one that didn't work...

**Comment by rausina** [comment]
Sorry for that, it is easier for me complain than to give solutions. Thank for all work you are doing.
Now it just doesn't load the mangas that had those problems
![image](https://user-images.githubusercontent.com/65744036/89096475-ffec6080-d3a4-11ea-8cc0-1c4584e4d944.png)
![image](https://user-images.githubusercontent.com/65744036/89096502-21e5e300-d3a5-11ea-88d7-977e822ad730.png)
![image](https://user-images.githubusercontent.com/65744036/89096619-07f8d000-d3a6-11ea-9596-68375c7737fd.png)
[cache-1596266616039.log](https://github.com/manga-download/hakuneko/files/5009976/cache-1596266616039.log)

**Comment by 27136773** [comment]
It seems MangAs entered a battle with HakuNeko, they are tracking changes in this git repository and updating their website accordingly.

Some websites are always trying to fight against HakuNeko:

2017 - KissManga
2018 - MagaGo
2019 - JapScan
2020 - MangAs

**Comment by 27136773** [comment]
Since more battles are expected, this issue will be kept open to track changes until the war is over ...

**Comment by Sheepux** [comment]
How about a warning on the connector in case of any error that would occur in the next few weeks ?

**Comment by rausina** [comment]
anyway thanks for your work.

**Comment by 27136773** [comment]
**Quick Check** for changes to the chapter list DOM:

Open [29 to JK](https://mangas.in/manga/29-to-jk) and inject `document.querySelector('ul.chapters li h5')`

----
2020-08-03

![image](https://user-images.githubusercontent.com/27136773/89228492-fdc21600-d5df-11ea-9328-7d01fbf30ffc.png)

**Comment by 27136773** [comment]
> How about a warning on the connector in case of any error that would occur in the next few weeks ?

I moved the code into the closed source plugin repository.
It should now be more sensitive and hopefully show an error when something failed instead of falling for the fake links (which ends with `#`)...

**Comment by 27136773** [comment]
No more changes within a week, it is assumed that the fight is over for now...

**Comment by Sheepux** [comment]
Reopening because changes just after closing (see #2166 )

**Comment by rausina** [comment]
There are some manga that I follow in which it only shows me the list of chapters that I already have downloaded. Regards
![image](https://user-images.githubusercontent.com/65744036/90450872-a4b2b180-e0b8-11ea-8859-0c1523b36a03.png)
![image](https://user-images.githubusercontent.com/65744036/90450948-cad85180-e0b8-11ea-9469-4214cdb6caeb.png)

**Comment by Sheepux** [comment]
Id changed, rebookmark with the new manga

**Comment by 27136773** [comment]
Oh look they changed their DOM structure for chapters on Tuesday again

**Comment by rausina** [comment]
[cache-1597791633670.log](https://github.com/manga-download/hakuneko/files/5093215/cache-1597791633670.log)

**Comment by 27136773** [comment]
Missing images is not an issue with HakuNeko, its an issue on the website

**Comment by 27136773** [comment]
No more changes within the last 3 weeks
Seems they make their inner peace => closed
