### ISSUE TITLE
[Bug] cbz format having issues with PNGs (and jpg)

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2119]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
when downloading some chapters containing pngs as a cbz the pngs fail to work when reading from any other cbz reading program. not sure if it is all pngs (and jpg)

**To Reproduce**
1. set output format to cbz
2. manga komi, tokyo ghoul:re, chapter 100 (has a bunch of different formats)
3. download
4. try to open with a reader other than HN
5. all the images that were .png s (and jpg) fail to work

**Expected behavior**
i would expect a .cbz to work in other readers

**Screenshots**
png
![](https://i.imgur.com/JvV0IA1.png)
webp
![](https://i.imgur.com/tsvmaQY.png)
jpg
![](https://i.imgur.com/Ai0fSVT.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**
downloading as a folder with images them compressing to a .zip and renaming to .cbz works fine
extracting the cbz to its files, the files all work fine
its just when HN turns it to a cbz that some of the images fail

**Comment by 27136773** [comment]
Cannot be reproduced.
The chapter contains `webp` images, except for one image which is `jpeg` (cannot find a single `png` inside).

The topic has already been discussed in the past. The `cbz` format is not standardized, therefore HakuNeko does nothing wrong. If images are broken, the website providing the images may be responsible. If a CBZ archive with `webp` is not working, the corresponding reader may add support for it.

It is a different story for PDF, as the format specs explicitly only support `png` and `jpeg` and therefore HakuNeko performs a conversion if necessary.

**Comment by Robonau** [comment]
@ronny1982 i know you probably won't respond but you have closed this issue early 
1. I redownloaded the chapter to make sure. it has webp, jpg and png see pic at bottom
2. i wrote an entire long ass response but it seems that it only sometimes fails, and other times works perfectly fine. there was another person in the discord having the same issue so i know it is reproducible 
(it seems to succeed in loading the PNGs and JPGs if u start on one) [vid](https://streamable.com/k6t5v0)
that is me opening the same file 3 times first two starting on a webp last starting on a jpg


![](https://i.imgur.com/MlgSeb4.png)

**Comment by 27136773** [comment]
The PNG and JPEG are correctly shown in the windows explorer thumbnail preview. If the PNG is broken, it is probably the websites fault.
Maybe it's just the image viewer that does not support the PNG / JPEG format.
Try some online service to detect file format, validate or repair images.

**Comment by 27136773** [comment]
Furthermore, I cross-checked the mime-type detection and it is already enabled for MangaKomi so the incorrect file extension provided by MangaKomi should be correctly adjusted

![image](https://user-images.githubusercontent.com/27136773/89224159-4b3a8500-d5d8-11ea-8a86-dc155e0d2df4.png)

**Comment by Robonau** [comment]
the JPEGs and PNGs are working fine (not broken).
and the reader supports all 3 formats used .

none of the readers i have tried (3) work if i start with a webp (as in jpeg and png are not viewable) 
if i start with a jpeg or png all 3 formats work fine.

I haven't checked if this is actually specific to CBZs made by HN (or images from HN) or is just a problem that is present in multiple cbz readers.
