### ISSUE TITLE
Hakuneko unable to update MangaDex list

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2123]
> **From:** HakuNeko User

**Version:** [master@0818dc](https://github.com/manga-download/hakuneko/commits/0818dc)

I am using Hakuneko master@0818dc on Debian 10 Buster.
I am attempting to download from MangaDex. I have tried pasting links using the Clipboard function, to no avail. If I try updating the manga list, I get:
'Failed to update manga list for MangaDex'
'ERR_NAME_RESOLUTION_FAILED https:mangadex.org?ts=1596180016137&rd=0.6501276633545099'
Some other details: The image server is set to s2.mangadex.org
The 'Throttle requests' setting is set to 3000.
Although I am reporting this from a nightly build, I have also tried this on the latest stable build with no success.
Note about website interaction: Attempting to open mangadex inside Hakuneko does nothing in the nightly build, and the stable build will only open a blank page.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Cannot be reproduced.
Looks like a (temporary?) network/DNS issue on your connection
