### ISSUE TITLE
add mangatepesi

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2135]
> **From:** HakuNeko User

**Version:** [6.1.7@170f3b](https://github.com/manga-download/hakuneko/commits/170f3b)

https://mangatepesi.com/
turkey

<details><summary>What has been done?</summary>

☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
You checked the box that you searched for similar issues, so why creating a duplicate?
See #1725
