### ISSUE TITLE
ManhuaGui

### ISSUE THREAD

**Issue by AmethystX-n** [manga-download/hakuneko#2144]
For some reason, when I try to search in manhuagui, it says that it cant get the manga list.. how do i fix that?

**Comment by 27136773** [comment]
Probably regression of #2059

**Comment by 27136773** [comment]
You got IP banned.
Do not update the manga list for now, use copy/paste and bookmarks only.

**Comment by AmethystX-n** [comment]
I haven’t used it since the last time I’ve emailed you o.o

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
