### ISSUE TITLE
kissmanga chapters

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2146]
> **From:** HakuNeko User

**Version:** [6.1.7@a47341](https://github.com/manga-download/hakuneko/commits/a47341)

why the fuck are the chapters full of dog pictures

<details><summary>What has been done?</summary>

</details>

**Comment by Cistmist** [comment]
![001](https://user-images.githubusercontent.com/49917604/89530756-b57d4080-d7f7-11ea-8c5e-db6d4a5fdbf9.png)
![002](https://user-images.githubusercontent.com/49917604/89530771-bca44e80-d7f7-11ea-9b6f-10ed22745f97.png)
![003](https://user-images.githubusercontent.com/49917604/89530782-bf9f3f00-d7f7-11ea-9fa1-cba9cc3a8015.jpg)
![004](https://user-images.githubusercontent.com/49917604/89530786-c0d06c00-d7f7-11ea-8730-340daa2c023b.jpg)
![005](https://user-images.githubusercontent.com/49917604/89530799-c4fc8980-d7f7-11ea-84c0-a09d2996d9fb.jpg)
Downloading from kissmanga downloads these 5 pictures dunno what the fk they are

**Comment by Cistmist** [comment]
It's like a damn plague...

**Comment by theduck749** [comment]
yes its happening to me as well wtf  but the thing Im curious about is wether the lady is a vet or an engineer

**Comment by 27136773** [comment]
Check Discord Channel for Workaround
