### ISSUE TITLE
[Bug] Dog Pics

### ISSUE THREAD

**Issue by theduck749** [manga-download/hakuneko#2147]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

bug description:
the client kept downloading this ladies report of some sort instead of downloading the actual chapters its really strange this usually happens with kissmanga. With mangadex it works perfectly and no Im being 100% honest

**Expected behavior**
to download the chapter 

**Screenshots**
![image](https://user-images.githubusercontent.com/65233085/89557194-08c9b000-d845-11ea-9eab-e2f5fbc63dac.png)
![image](https://user-images.githubusercontent.com/65233085/89557234-14b57200-d845-11ea-8a5d-4b010b415469.png)

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #2146 
Check Discord Channel for Workaround
