### ISSUE TITLE
[Feature] Manually invoke user scripts

### ISSUE THREAD

**Issue by RMPR** [manga-download/hakuneko#2149]
**Is your feature request related to a problem? Please describe.**
I want to export chapters to document formats to read with my Ebook reader

**Describe the solution you'd like**
A button to export the current opened chapter, batch export chapters will be good

**Describe alternatives you've considered**
Actually I use a script which is working quite fine
```
#!/bin/bash

echo -e "---\ngeometry: margin=2cm\n---" > $1
find -iname "*.jpg" | sort -n | sed 's/\(.*\)/![](\1)<br>/g'  >> $1
pandoc -f markdown $1 -o $1.pdf
```

**Context (please complete the following information):**
6.1.7@47341

**Additional context**
I recently discovered that I can do it with imagemagick using 
```
convert 001.jpg 002.jpg ... output.pdf
```
And it removes the margins automatically, but I think a built-in feature is the best way to handle this feature.

**Comment by 27136773** [comment]
See: https://github.com/manga-download/hakuneko/wiki/Quick-Reference#settings
See: https://github.com/manga-download/hakuneko/wiki/FAQ

Read the docs and ask on discord if still not clear how to do it...

**Comment by RMPR** [comment]
I'm well aware of that, I read all the docs before posting the issue mind you, that's why I shared the script I use. Maybe I wasn't very specific on why I'm asking this I'm sorry, my understanding is that the postscript runs after each download, (at least I couldn't find a way to run the postscript on demand) but in my case the bunch of chapters I want to apply the script to are already downloaded, so maybe it's more something like: how to trigger manually the postscript.

**Comment by 27136773** [comment]
It's not quite clear what you want to achieve...

Want to download each chapter as PDF/EPUB, then select output format in settings.
Want to run a script after each chapter download, then set it up in Post Command.
Want to combine multiple chapters into single, not possible need to be done outside of HakuNeko.

**Comment by RMPR** [comment]
> Want to run a script after each chapter download, then set it up in Post Command.

I want to trigger manually the postscript from the Hakuneko interface

**Comment by 27136773** [comment]
This would be way too much effort to implement for a feature that is probably only used by a handful of users.
Furthermore this can be achieved easily outside of HakuNeko
=>rejected

**Comment by RMPR** [comment]
I was thinking about linking the actual trigger of the postscript to a
button, but indeed it's a pretty niche use case, thank you for your
time. Keep up with the great work.

**Comment by RMPR** [comment]
Just for future reference, that's how I manage the bulk convert
```
for i in $(ls -d */); do convert $(find $i -maxdepth 1 -type f -name '*.jpg' | sort -n | paste -sd\ ) "${i%/}".pdf; echo; echo $PWD; echo; done
```
