### ISSUE TITLE
Mangant - Not loading pages

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#2156]
Hi

Unable to load pages for some manga

1. All chapters for https://mangant.com/manga/charming-grim-reaper-23660

2.  Chapter 20 for https://mangant.com/manga/the-great-wish-26073

3. chapter 43 for https://mangant.com/manga/deceaseds-soul-514

Hoping this issues can be resolve. Thanks

**Comment by 27136773** [comment]
Read [Troubleshoot](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#are-chapters-or-pages-not-shown-empty-list) before opening tickets
