### ISSUE TITLE
[Site Request] Mangaz

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#2160]
**Name of the website**
mangaz

**Website urls (examples below)**
- Site: https://www.mangaz.com/
- Manga List: https://www.mangaz.com/title/?type=official&category=
- Manga example: https://www.mangaz.com/book/detail/205051
- Chapter online viewer example: https://vw.mangaz.com/virgo/view/205051/i:0

**Languages**
Japanese & English (though only the site itself becomes English the mangas are still in Japanese)

**Website relationship**
 No affiliated with any site I am aware of to be honest.

**Additional details**
Really good site to read non-translated mangas for free for a limited or unlimited amount of time. I found it on a whim and would love to get some mangas on my folder if possible.

**Comment by 27136773** [comment]
See #34
