### ISSUE TITLE
[Mangas.in] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#2166]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
when I select a manga the list of chapters is not displayed
**To Reproduce**
1. Mangas.in
2. All
3. All)
4. Does not show any message.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/65744036/89974096-1eb5e700-dc30-11ea-9610-cbf7ca2e574c.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by rausina** [comment]
I know the site is at war with Hakuneko. Thanks for your work. Regards

**Comment by Sheepux** [comment]
Closing in favor of https://github.com/manga-download/hakuneko/issues/2117 (reopening) for better tracking.
Thank you for your report.
