### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bakugo0909** [manga-download/hakuneko#2171]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes/No
![Untitled-1](https://user-images.githubusercontent.com/69632029/90131542-d693e300-dd5b-11ea-936a-3599f90b7b6d.jpg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by Sheepux** [comment]
Will close unless the user replies to the questions ...
