### ISSUE TITLE
Kumanga Is not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2179]
> **From:** HakuNeko User

**Version:** [6.1.7@4544fa](https://github.com/manga-download/hakuneko/commits/4544fa)

Kumanga.com is not working anymore since hours

<details><summary>What has been done?</summary>

</details>

**Comment by Ilyed** [comment]
Hello, the issue seems to be back again. I haven't been able to use kumanga through hakuneko for 2 months now, approximately.
