### ISSUE TITLE
issue with webnovel comics 

### ISSUE THREAD

**Issue by cosmosg9** [manga-download/hakuneko#218]
Thanks for adding webnovel comics but it seems to be not working giving error unable to load www.webnovel.com within the given time of 60 secs. @ronny1982

**Comment by 27136773** [comment]
For some reason the website cannot be initialized within 60 seconds.
It was possible to reproduce this once, but now it is all working again and the problem cannot be investigated any further.

You may try to load different mangas after the timeout, once it succeed the initialization is complete and will not be occur again until you reload HakuNeko.

**Comment by 27136773** [comment]
Cannot be reproduced any longer => closed

**Comment by Juxn-rg** [comment]
> Cannot be reproduced any longer => closed

Still error with me
![Capture](https://user-images.githubusercontent.com/27928013/60314475-f23bfe80-998c-11e9-829f-ef488f5aae88.PNG)

**Comment by 27136773** [comment]
For some reason the last update did not find its way in HakuNeko and was only available on my local machine (probably my fault) => checked changes in

**Comment by hemantkgurjar** [comment]
it's working now thanks.
But for some reason only the starting 10-15 chapters have images and all other chapters are blank folders.

**Comment by 27136773** [comment]
Are these chapters available on the website?
Does these chapters require a registration/subscription?

**Comment by hemantkgurjar** [comment]
I just checked that they are available on the website but are needed to be unlocked before reading with virtual money of that website

**Comment by hemantkgurjar** [comment]
Can you add an login feature so that I can log in with my account to download as I don't have problem with buying virtual money of there website.

**Comment by 27136773** [comment]
> Can you add an login feature so that I can log in with my account to download as I don't have problem with buying virtual money of there website.

Have you already tried account login with [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#3-account-login)?

**Comment by hemantkgurjar** [comment]
Sorry I didn't know about it. As it's my first time using this software. I'll try it.
Thanks
