### ISSUE TITLE
Suggestions for a good manga site

### ISSUE THREAD

**Issue by K-snakes** [manga-download/hakuneko#2180]
Hello everyone, I would like to know which manga sites out there are really really good like **KissManga** that was just taken down, I've searched but the lists and whatnot aren't that good so If possible I'd like to hear suggestions from people.

Something with an account so it'll be easier to track your list

**Comment by 27136773** [comment]
The ticket system is for technical discussions related to the software.
Your question is more suitable to be placed in the discord channel.
