### ISSUE TITLE
[Feature] Download without series folder, just the chapter folder.

### ISSUE THREAD

**Issue by thebek87** [manga-download/hakuneko#2182]
I would like to be introduced as a download function without the series folder,  just the chapter folder.
When you download many manga you have many folders and it is slow to have to pull out the various chapters from each subfolder so I ask if it is possible to insert as a function the possibility of downloading without creating the series folders.
Also because in my case I have the folders of the series in another position and it is tedious to have to pull out the chapters from the folders that hakuneko creates and then put them in mine.
Thanks for the attention.

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7@4544fa

**Comment by 27136773** [comment]
This is technically not possible, HakuNeko relies on a manga folder.
Also this wouldn't make any sense to save all chapters from all mangas in the same directory, you would end up with dozens of `Chapter 1` from different mangas in the same directory.

**Comment by thebek87** [comment]
I do not say to make this default setting but to let me choose whether to enable it or not ... also because what you say is not exactly true, in the settings there is a field called "Chapther Title Format" and there if you enter as a value "%M% %CH% %T%" the chapter will no longer be called "Chapter 1" etc. but it will have the name of the manga with the chapter number and also the title of the chapter allowing you to understand which manga it belongs to and which chapter it is.
What I ask is that if one sets the "Chapther Title Format" he can also delete the manga folder because the chapters are already named with the manga name and the chapter number ... that's all!

**Comment by 27136773** [comment]
Despite of rewriting the core functionality (which is based on the concept of manga folders), there are way to many additional migration issues which needs to be handled starting with the very unreliable `Chapter Format` setting...
=> low severity enhancement for minority of users vs. massive amount of development cost

EDIT:
Besides, this can be easily achieved with the `Post Command` setting and a corresponding batch script to move the directories as desired...
