### ISSUE TITLE
uyuyanbalik.com

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2183]
> **From:** HakuNeko User

**Version:** [6.1.7@4544fa](https://github.com/manga-download/hakuneko/commits/4544fa)

https://uyuyanbalik.com/

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Sorry but we will be more strict in the future when assessing tickets.
Write in more detail what you want.
=> Rejected
