### ISSUE TITLE
Website Release https://hakuneko.download

### ISSUE THREAD

**Issue by Sheepux** [manga-download/hakuneko#2186]
Todo: as to officialy open the new website : https://hakuneko.download

**Website**
- [X] Move the user documentation to the website (but let the developper documentation on github)

**Github**
- [x] Put a link in the wiki pointing to the user documentation
- [x] Put a link to the website on the main Readme of the github (improve SEO)
- [x] Put a link on the top right of the github page (improve SEO), in place of the discord link( and put the discord link in the description?)
- [x] Reorder the issue templates so that connector is the first one

**Sourceforge**
- [x] Put a link on the sourceforge page
- [x] Make it clearer on sourceforge that this version is obsolete (still lots of downloads)

**App modification**
- [x] Remove the google form and replace with a link to github issue
- [x] Change the documentation link

**Google**
- [x] Register on google search

**Comment by Sheepux** [comment]
Looks good enougth

**Comment by 27136773** [comment]
All done now
