### ISSUE TITLE
Toomics status 404

### ISSUE THREAD

**Issue by xerzo** [manga-download/hakuneko#219]
Hello i got error in toomics
![toomic](https://user-images.githubusercontent.com/32761826/60118964-f8c14f00-97af-11e9-8249-2d720c3f55d7.png)

**Comment by 27136773** [comment]
Please try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) first.
The comic seem no longer to be available on the website.

**Comment by xerzo** [comment]
the comic are availabe i dont know what happend but it the apps no longer works with vip chapter it gave the status 404 
my account is already login 
its ok in browsing 
![vip](https://user-images.githubusercontent.com/32761826/60125562-9f145100-97be-11e9-9676-e24135f2cbe5.png)

but when i try to download it gave that status 404
![xxxxxxx](https://user-images.githubusercontent.com/32761826/60125371-3e851400-97be-11e9-9c9b-5233e50790e8.png)

**Comment by 27136773** [comment]
It was possible to reproduce the issue with ASURA chapter greater then 55

**Comment by 27136773** [comment]
Improve link parsing.

Free:
`onclick="location.href='/en/webtoon/detail/code/100588/ep/55/toon/4628'"`

Members:
`onclick="Base.popup('modal-login', 'login', '/en/webtoon/detail/code/100882/ep/57/toon/4628', 'N')"`

VIP:
`onclick="setCookie('ecc','eyJ0b29uX2lkeCI6IjQ2MjgiLCJhcnRfaWR4IjoiMTAxMDA2IiwidHVybl9vcmRlciI6IjU5In0=');Base.popup('modal-login', 'login', '/en/webtoon/detail/code/101006/ep/59/toon/4628', 'N')"`

**Comment by xerzo** [comment]
it only gave error in vip chapter 
![xcf](https://user-images.githubusercontent.com/32761826/60127058-ecde8880-97c1-11e9-93f1-afd54b719e45.png)
when i click the vip witch is 59 up the error happen it happend in all vip chapters
![acsdd](https://user-images.githubusercontent.com/32761826/60127229-3fb84000-97c2-11e9-96e2-732a43257468.png)

**Comment by 27136773** [comment]
Link detection for registered and VIP members has now been fixed, however since i don't have a VIP account i cannot confirm that it is now working...

**Comment by xerzo** [comment]
thank you now its working
![kcmd](https://user-images.githubusercontent.com/32761826/60128852-36c96d80-97c6-11e9-8f0c-027884a1ed14.png)

**Comment by 27136773** [comment]
I got some trouble when trying to login, so if it is not working you may click some links after login to ensure you really are logged in.

Also it might be best to first load any chapter list and then perform the login procedure, to ensure the connector is initialized before login.
