### ISSUE TITLE
[Site Request] MangaForFree

### ISSUE THREAD

**Issue by Blio21** [manga-download/hakuneko#2194]
**Mangaforfree**

**Website urls (examples below)**
- Site: http://mangaforfree.com/
- Manga List: http://mangaforfree.com/manga/
- Manga example: http://mangaforfree.com/yamemasu-tsugi-no-shokuba-ha-mao-jo/
- Chapter list: http://mangaforfree.com/yamemasu-tsugi-no-shokuba-ha-mao-jo-chapters-list/
- Chapter online viewer example: http://mangaforfree.com/yamemasu-tsugi-no-shokuba-ha-mao-jo-chapter-16b/

**Languages**
Eng

**Comment by 27136773** [comment]
Seems to have affiliate: http://mangayuca.com
Some chapter lists are cross-linked between these two websites
