### ISSUE TITLE
[Feature] Support for Novels 

### ISSUE THREAD

**Issue by snickerdooodle45** [manga-download/hakuneko#2195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Additional context**
Support to also download novels from sites like tapas, tappytoon, webnovel, novelcool, etc.

**Comment by 27136773** [comment]
- No detailed information for the task
- Novels are already supported
- Only one request per ticket
