### ISSUE TITLE
[Novels from Tapas, Webtoon, Mangatoon ] Connector not working

### ISSUE THREAD

**Issue by snickerdooodle45** [manga-download/hakuneko#2196]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
HakuNeko will be able to download the chapters from the novels, but will result in corrupt PDF and EPUB files that cannot be opened. The chapters as well cannot be accessed in the viewer of HakuNeko

**To Reproduce**
1. Tapas, Webnovel, Mangatoon
2. Tapas - Beastly Beauty, Webnovel - Trial Husband, Mangatoon - Divine Doctor, and basically all other novels.
3. All Chapters 
4. The book is corrupt.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screen Shot 2020-08-19 at 3 10 58 AM](https://user-images.githubusercontent.com/69394376/90556274-36124880-e1cb-11ea-865e-a54b6ae1ed5f.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
Please make one ticket for one website
Do not request websites that are already supported, or state that they are broken and what is broken

**Comment by 27136773** [comment]
If the problem is not clear ask in discord what to do
