### ISSUE TITLE
[Site Request] Mabushi Majo

### ISSUE THREAD

**Issue by cloudsenpai** [manga-download/hakuneko#2201]
Website urls (examples below)

Site: http://mabushimajo.com/onlineokuma/
Manga List: http://mabushimajo.com/onlineokuma/directory/
Manga example: http://mabushimajo.com/onlineokuma/series/16-life/
Chapter online viewer example: http://mabushimajo.com/onlineokuma/read/16-life/tr/0/1/page/1

Languages: TR

**Comment by 27136773** [comment]
Template: FoolsSlide
