### ISSUE TITLE
mangakakalot chapter

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2202]
> **From:** HakuNeko User

**Version:** [6.1.7@633faf](https://github.com/manga-download/hakuneko/commits/633faf)

pls fix broken chapters in mangakakalot for example chapter 24 of 1-nen a-gumi amonster 

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Read troubleshooting before creating a ticket
https://hakuneko.download/docs/troubleshoot/#is-the-manga-website-working-in-your-browser
=> https://mangakakalot.com/chapter/1nen_agumi_no_monster/chapter_24
