### ISSUE TITLE
[9anime] Connector not working

### ISSUE THREAD

**Issue by thisdudeiscalledsomeone** [manga-download/hakuneko#2204]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

I try to download anime from 9anime, however, it doesn't work as in the chapter preview, it always show "chapters: 0/0"

**To Reproduce**
1. Name of connector : 9anime
2. Name of manga (if connector update is working) : any (none of them work)
3. Name of chapter (if manga update is working) : any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**

![0151](https://user-images.githubusercontent.com/67941921/90853461-7d8b0700-e37a-11ea-93e0-05c1503206d0.JPG)

**HakuNeko (please complete the following information):**
Tested with
 - Version 6.1.7, windows 64bit
 - Version 6.1.7, mac

-hakuneko-desktop_8.3.4_windows-setup_amd64.exe

**Comment by 27136773** [comment]
Domain changed
