### ISSUE TITLE
[Site Request] Fakku

### ISSUE THREAD

**Issue by dex593** [manga-download/hakuneko#2215]
**Name of the website**
Fakku

**Website urls (examples below)**
- Site: https://fakku.net
- Manga List: https://www.fakku.net/tags/unlimited
- Manga example: https://www.fakku.net/hentai/sexual-entrapment-english
- Chapter online viewer example: https://www.fakku.net/hentai/sexual-entrapment-english/read/page/1

**Languages**
English

**Comment by Jaxk69** [comment]
Duplicate #177
