### ISSUE TITLE
(minor) documentation website issue

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2216]
(there was no section that i thought this issue fitted in)

The explanation images used use numbers to locate where you are describing and the descriptions just use bullet points, could make it difficult to understand the meaning of some of the later points

![](https://i.imgur.com/hhNTdkf.png)

**Comment by Sheepux** [comment]
Issue when converting ascidoc to markdown, numeral list was lost.
Also fixed missing link text : "???"

Fixed by https://github.com/manga-download/manga-download.github.io/commit/e610037b5f057d113f4d32f00a6cd8393e2815de
