### ISSUE TITLE
[Site Request] heros-web

### ISSUE THREAD

**Issue by 6mai** [manga-download/hakuneko#2217]
Website urls (examples below)

Site: https://viewer.heros-web.com/
Manga List: https://viewer.heros-web.com/series/heros ; https://viewer.heros-web.com/series/flat ; https://viewer.heros-web.com/series/wild
Manga example: https://viewer.heros-web.com/episode/13933686331695960379
Chapter online viewer example: https://viewer.heros-web.com/episode/13933686331695960379

Languages: Japanese

**Comment by 27136773** [comment]
Template: CoreView

**Comment by Sheepux** [comment]
Duplicate #1470 
This one is more detailed, should we close the other one ?

**Comment by 27136773** [comment]
Doesn't matter, both tickets are linked
