### ISSUE TITLE
[Site Request] Delitoon

### ISSUE THREAD

**Issue by Yunaxigf** [manga-download/hakuneko#2218]
**Delitoon**

**Website urls (examples below)**
- Site: https://www.delitoon.com
- Manga List: https://www.delitoon.com/genres
- Manga example: https://www.delitoon.com/webtoon/dites-moi-princesse
- Chapter online viewer example: https://www.delitoon.com/lecture/dites-moi-princesse/s1/1

**French**
List of languages supported by the website

**Comment by Sheepux** [comment]
Duplicate #1763
