### ISSUE TITLE
[Site Request] Explorer Scans

### ISSUE THREAD

**Issue by enzo20000** [manga-download/hakuneko#2220]
**Explorer Scans**
thewebsitename

**Website urls (examples below)**
- Site: https://scansexplorer.com.br/
- Manga List: https://scansexplorer.com.br/mangas-novels/
- Manga example: https://scansexplorer.com.br/manga/boku-no-hero-academia/
- Chapter online viewer example: https://scansexplorer.com.br/manga/boku-no-hero-academia/boku-no-hero-volume-26/capitulo-258/

**Languages**
Portuguese

**Additional details**
Madara template

**Comment by 27136773** [comment]
Website closed, scanlations are only provided as PDF through Twitter and Facebook
