### ISSUE TITLE
One title has an issue on Mangadex

### ISSUE THREAD

**Issue by doppler56** [manga-download/hakuneko#2221]
Using latest stable.
One title has an issue on Mangadex.  The page does not load on the left side box of hakuneko.  Only the reload is present.  Reload does nothing.  Tried on two different computers/and/locations.  The following Manga has the issue.

https://mangadex.org/title/43476/yakuza-reincarnation

Thanks

**Comment by 27136773** [comment]
Report this problem to MangaDex website, HakuNeko is a downloader and not responsible for content hosted on the websites

**Comment by doppler56** [comment]
Quick to close aren't cha.  Did you even try to get it using HakuNeko ?   I can read it on Mangadex.  I can download it using another down loader.  I can only not get it using HakuNeko.  Everything works using Mangadex.  So please explain it to me how this is a problem on Mangadex ?   I am a software programmer by profession.  My diagnostic analytical skills must be defective.  I just handed you  an easy lob of a problem.  If I sound pissed I am.  I don't have hours to spare to look thru HakuNeko and hand you the fix on a silver platter.
BTW, Think about this for more than 1 second.  If I report the problem on Mangadex, they will respond "If you can read it on Mangadex, but can't on HakuNeko.  Report the problem to HakuNeko Project."

**Comment by 27136773** [comment]
I cannot read it on MangaDex
![image](https://user-images.githubusercontent.com/27136773/91300240-3d28f000-e7a3-11ea-8043-dd339a241228.png)

EDIT:
To be fair, you didn't even mention that it worked for you on the website in your first post.
This misunderstanding could have been easily avoided by answering question number 2 in the ticket template for reporting broken websites.

**Comment by 27136773** [comment]
Maybe this manga is only unlocked for certain user accounts, but not open for public.
In that case, make sure HakuNeko is [manually logged in](https://hakuneko.download/docs/manual-website-interaction/#account-login) with the same MangaDex user account used to read this manga in the browser.

**Comment by doppler56** [comment]
Yes, that seems to be the case.  I logged out, tried to open yakuza-reincarnation.  Got stoned walled like you did.  Re-logged in.  Then refreshed the stonewalled page.  TADA, worked.  I am not a where of any user/guest rules on any Mangadex series.  The only rule applying to guests is all chapter content will be give by the MD@home network and not from the main website.

I will do my part to investigate events back on Mangadex.  I have 100's of series marked for reading.  Yakuza-reincarnation is the first with content access rules.  Thanks for your re-efforts to defined the problem.  And linking to https://hakuneko.download/docs/manual-website-interaction/#account-login for my follow up.

With this closed to some extent I will comment and close this ticket.
Thanks for your effort.  Now I just have to poke the Russian Bear (mangadex) without getting mauled.
