### ISSUE TITLE
[Site Request] CManga

### ISSUE THREAD

**Issue by vinh2201** [manga-download/hakuneko#2226]
**Name of the website**
CManga

**Website urls (examples below)**
- Site: https://cmanga.com/
- Manga List: https://cmanga.com/tags/Action ; https://cmanga.com/tags/Sports ; https://cmanga.com/tags/Manhua
- Manga example: https://cmanga.com/tro-lai-showbiz-lam-anh-hau-16483
- Chapter online viewer example: https://cmanga.com/tro-lai-showbiz-lam-anh-hau-chapter-19-ZWFiY2Jk

**Languages**
Vietnamese

**Comment by MikeZeDev** [comment]
Website dead. @Sheepux please :)

**Comment by Sheepux** [comment]
possible alternative? https://cmangab.com/
(must be confirmed)

**Comment by MikeZeDev** [comment]
Alternative need hcaptcha if no cookies btw. Not sure this info is relevant.

**Comment by MikeZeDev** [comment]
Alternative is a parking page
