### ISSUE TITLE
[Site Request] KissAnime NZ

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#2235]
**Name of the website**
KissAnime

**Website urls (examples below)**
- Site: https://kissanime.nz/kissanime-home.html
- Manga List: https://kissanime.nz/AnimeListOnline
- Manga example: https://kissanime.nz/Anime/hack-sign-dub.75738/
- Chapter online viewer example: https://kissanime.nz/Anime/hack-sign-dub.75738/01-Roleplay?id=90410

**Website relationship**
KissXXX

**Additional details**
Investigate if this is a continuation or just a dead mirror

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by MikeZeDev** [comment]
No alternate url found. Well there are other KA clones but who knows?
