### ISSUE TITLE
[Site Request] AnimeKisa

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#2236]
**Name of the website**
AnimeKisa

**Website urls (examples below)**
- Site: https://animekisa.tv
- Manga List: https://animekisa.tv/anime
- Manga example: https://animekisa.tv/hack--sign
- Chapter online viewer example: https://animekisa.tv/hack--sign-episode-1

**Additional details**
Some of the video mirrors are already implemented

**Comment by MikeZeDev** [comment]
Dead website (lack of founds)

@Sheepux please :)
