### ISSUE TITLE
[TuMangaOnline] Connector not working

### ISSUE THREAD

**Issue by KasukeLp23** [manga-download/hakuneko#2238]
**Did you read the troubleshooting guide**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The website not provide a manga list of TuMangaOnline

**To Reproduce**
1. Select TuMangaOnline
2. Click on the refresh mangas button

**HakuNeko (please complete the following information):**
 - Version 6.17@351716

**Comment by 27136773** [comment]
The message is describing whats going on:
The website does not provide a manga list.
Use copy & paste feature to download manga...
https://hakuneko.download/docs/FAQ/#copy-and-paste
