### ISSUE TITLE
[MangaDex] Connector Not Working (Infinite Loading)

### ISSUE THREAD

**Issue by dfaslfjasdlf** [manga-download/hakuneko#2239]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes.

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes.

**Describe the bug**
Upon trying to get the list of manga from MangaDex, the loading is infinite. The list never appears. 

**To Reproduce**
1. Select MangaDex
2. Select refresh icon

**HakuNeko (please complete the following information):**
 - Version 6.17 (Linux)

**Comment by 27136773** [comment]
Open developer tools and check for activity in the network tab, website is huge and it will take a long time...

**Comment by dfaslfjasdlf** [comment]
I see. Excuse my incompetence, but how do I open the developer tools on Hakuneko? Additionally, what has been the estimated amount of time to load a list from MangaDex?
