### ISSUE TITLE
[Site Request] Manhwas Men

### ISSUE THREAD

**Issue by Badr-Zh** [manga-download/hakuneko#2242]
Manhwas Men

- Site: https://manhwas.men/
- Manga List: https://manhwas.men/manga-list
- Manga example: https://manhwas.men/manga/secret-class-english
- Chapter online viewer example: https://manhwas.men/manga/secret-class-english/01/1

**Languages**
English
Korean

**Website relationship*
The website has a Spanish version.

- Site: https://es.manhwas.men/
- Manga List: https://es.manhwas.men/manga-list/
- Manga example: https://es.manhwas.men/manga/secret-class/
- Chapter online viewer example: https://es.manhwas.men/secret-class-01/

**Languages**
Spanish

**Comment by 27136773** [comment]
Template: MangaReaderCMS
