### ISSUE TITLE
[GManga] Failed to update list

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#2243]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It was working just fine, then suddenly the list failed to update. (Note that I made an account, so I wonder if it is related)

**To Reproduce**
1. GManga

**Screenshots**
![hakunekoox](https://user-images.githubusercontent.com/70113965/92155722-1c5a3d80-ee28-11ea-85d9-e0a7fa6f02c0.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end, what is shown in the console tab when opening developer tools (F12)?

**Comment by Robonau** [comment]
![](https://cdn.discordapp.com/attachments/581630792120401922/752522607093481522/Screenshot_5.png)
from someone else with the same issue on the discord
