### ISSUE TITLE
[Bug]when maximised on left monitor i get a white line on the right monitor

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2245]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
if i maximise HN on my left monitor i get a white line that goes the whole way down the left side of the monitor to the right of it (only if HN is on top of the window on the right monitor)

**To Reproduce**
1. maximise HN on left monitor
2. look at right screen

**Expected behavior**
no white line, idk why it happens in the first place
its hella annoying when fullscreen watching a video 

**Screenshots**
![](https://i.imgur.com/SEveIXh.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**
i can't confirm if its just me or is actually a HN thing, but HN is the only program to do this as far as i can see
im sure at least one of the devs has multiple monitors

**Comment by Sheepux** [comment]
Electron frameless issue
https://medium.com/@victoraremu/fix-electron-js-frameless-window-white-bar-bug-after-maximize-cycle-fc1c59f4758c
Probably won't fix if we plan to change framework. (bug also present in discord, teams etc...)

**Comment by Robonau** [comment]
fair (though its not present in discord, idk about teams)

**Comment by 27136773** [comment]
Very unlikely a new client will be rolled out that can fix the issue
