### ISSUE TITLE
[mangago]Failed to update list

### ISSUE THREAD

**Issue by applemann** [manga-download/hakuneko#2249]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update list.no manga listed

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
The popup explicitly states that there is no manga list and the user have to use the [Copy & Paste](https://hakuneko.download/docs/FAQ/#copy-and-paste) feature
