### ISSUE TITLE
[Site Request] mangaonline.fun

### ISSUE THREAD

**Issue by Psiplexser** [manga-download/hakuneko#2251]
**Name of the website**
Manga online

**Website urls (examples below)**
- Site: https://mangaonline.fun/
- Manga List: https://mangaonline.fun/search
- Manga example: https://mangaonline.fun/manga/solo-leveling_102
- Chapter online viewer example: https://mangaonline.fun/chapter/solo-leveling_102/chapter-0

**Languages**
English

**Website relationship*

**Additional details**

**Comment by 27136773** [comment]
Template: MangaHub
