### ISSUE TITLE
https://manhuasworld.com

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#2252]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: WordPressMadara
