### ISSUE TITLE
[UnionMangas] Connector not working

### ISSUE THREAD

**Issue by Jhoelious** [manga-download/hakuneko#2256]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The manga list never loads.

**To Reproduce**
1. UnionMangas
Connector.mjs:221 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\user\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.unionmangas'

**HakuNeko (please complete the following information):**
 - Version: 6.1.7

**Comment by 27136773** [comment]
Loads for me, but the website is very slow on my end, so this may take some hours...
244 pages * 13 sec/page => ~ 1hour

![image](https://user-images.githubusercontent.com/27136773/92528256-c0792580-f228-11ea-937d-e737225c8b2c.png)
