### ISSUE TITLE
[Feature] Downloading the Embedded Music in a Webtoons Episode 

### ISSUE THREAD

**Issue by dmr111** [manga-download/hakuneko#2258]
**Is your feature request related to a problem? Please describe.**

Currently when a episode is downloaded from Line Webtoons (English), it only includes the pictures in the episode. Normally, that's all there is in an episode most of the time, but occasionally an episode has background music. Chapters with background music has an music note icon in its title, example: ![image](https://user-images.githubusercontent.com/57851738/92543170-5f455800-f210-11ea-8b97-ade4d424af26.png) . 

HakuNeko doesn't download this background music (even if as a separate music file), and the author intends for the reader to listen to this music they included as they read (such as for atmospheric purposes).

**Describe the solution you'd like**

I would like for HakuNeko to download the music as a separate file so that if the reader wants to listen to the author's background music, they could open it and play it independently as they read the images in the regular HakuNeko manga folder.

**Describe alternatives you've considered**

Recording the music using the Voice Memos app on iPhone and playing it as I read is an alternative option, but the sound quality isn't the same.

**Context (please complete the following information):**

My current HakuNeko Version is 6.1.7

**Additional context**

To hear the music in such episodes, the music has to be turned on by clicking the icon on the upper right hand corner in the chapter: 
![image](https://user-images.githubusercontent.com/57851738/92545862-b1897780-f216-11ea-8a5a-5536b667bef9.png)
 --> ![image](https://user-images.githubusercontent.com/57851738/92544051-90268c80-f212-11ea-82a0-9ea2805d189f.png)

Using F12 [Network], it seems like the audio scripts or indicators could be detected. 

An activity sample from the last chapter of "Sweet Home":

Just entering the chapter:
![image](https://user-images.githubusercontent.com/57851738/92544886-9453a980-f214-11ea-860c-fd6c10a8e82d.png)

After letting the music play:
![image](https://user-images.githubusercontent.com/57851738/92544763-450d7900-f214-11ea-9e6c-2f5c349068f7.png)

**Comment by 27136773** [comment]
To much effort to integrate this into the current architecture
