### ISSUE TITLE
[www.ohmanhua.com] Connector not working

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#2261]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When clicking the preview, nothing shows up. And after downloading the manhua, there's nothing in the folder. Everything is showing up just fine on the website itself.

**To Reproduce**
1. Ohmanhua
2. All Manhua example: 虎x鹤 妖师录
3. All Chapters
4. 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
See #2241
