### ISSUE TITLE
[Feature] Manga download

### ISSUE THREAD

**Issue by KasukeLp23** [manga-download/hakuneko#2263]
**Is your feature request related to a problem? Please describe.**
Can't download episodes of user choice

**Describe the solution you'd like**
You could add the function of downloading from a chapter x to another chapter x, and thus save the work of downloading one by one.

For example: Download from chapter 50 to 100 and so on.

**Describe alternatives you've considered**
Add a function where you can choose which chapters to download

Thank you for your attention, and I hope you place this function. Thank you very much

**Comment by 27136773** [comment]
See #382
