### ISSUE TITLE
[CopyToon] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#2270]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't open CopyToon from HakuNeko anymore. I can still google and find it online though. I think the URL changed maybe.

**To Reproduce**
1. CopyToon

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
# Developer Notes

The old domain (copytoon85) does no longer redirect to the new domain (copytoon102).
A temporary fix would be to just add the new domain.
Need to find a way to detect the current domain (previously this was done through twitter, but their account got banned).
Maybe a brute force approach by incrementing the domain name until a one of them is reached?

**Comment by XenonR** [comment]
How about a settings variable with the current domain? For frequent users it can be updated semi-automatically when a redirect is detected on fetch. Others could change it manually if they find the option.

**Comment by 27136773** [comment]
Either a setting with automatic update to redirected URL / manual user update, or hosting the latest URL in a JSON file within the repository itself (also useful for HeavenManga, HolyManga and all the other manga hosts that are on the run from DMCA complains)
