### ISSUE TITLE
[Toomics (Korean) - Specific Manga only] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#2271]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Specific manga not listed on Toomics (Korean): "방주인은 전데요 (Excuse Me, This is My Room)".

**To Reproduce**
1. Toomics (Korean)
2. 방주인은 전데요

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
The mentioned manga [방주인은 전데요](https://www.toomics.com/uplmscg/episode/toon/5467) seems only to be listed on the [popular list](https://www.toomics.com/popular/popular_list) (which is not used by HakuNeko), but is missing in the [serialization list](https://www.toomics.com/webtoon/weekly) and [completed list](https://www.toomics.com/webtoon/finish/ord/latest) (which are used by HakuNeko).

**Workaround:** Copy & Paste the manga link directly into HakuNeko

# Developer Note

```javascript
// manga links are provided via a modal popup dialog, not yet sure which IDs are used to compose the URL
fetch('https://www.toomics.com/popular/popular_list/cut_type/P/ord/update', {
    method: 'POST',
    body: 'load_contents=Y&page=3',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    }
}).then(response => response.text());
```

**Comment by 27136773** [comment]
NOTE:
The provided manga seems to be accessible through https://www.toomics.com/uplmscg/episode/toon/5467, however when searching the manga on the website it requires age verification with a korean phone number and also has a different url https://www.toomics.com/webtoon/episode/toon/5200 (maybe the first link is a censored version?)

To fix the issue, the manga [가출천사 육성계약](https://www.toomics.com/webtoon/episode/toon/5254) will be used, which is only available in the popular list and does not require age verification.
