### ISSUE TITLE
Cannot read manually created .cbz files[Bug]

### ISSUE THREAD

**Issue by saqlainartazz** [manga-download/hakuneko#2272]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I downloaded a manga using hakuneko (the folder with images) format. then later i went to each folder and made an archive using winrar of only images present in each chapter folder.(note: i dint make archive of the folder itself but the pics inside). Later i changed the .rar file extension to cbz. Then i entered hakuneko and while trying to read the created .cbz file it gives this error :

cant find end of centraldirectory, is this a zip file!

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [stabe latest]

**Comment by 27136773** [comment]
The error is correct, `CBZ` is a zip compressed comic book archive, `CBR` is a rar compressed comic book archive.
HakuNeko only supports zip compressed archives, renaming the file extension is like trying to fool the software to believe the rar compressed archive is a valid zip compressed archive and therefore opening the archive fails.

It is the same as renaming a `webp` image to `bmp` and try opening it with paint => error

**Comment by saqlainartazz** [comment]
hmmm that makes sense! sorry i got 7zip to do the compressing now and that works. 
btw is there any plan to add cbr support since alot use winrar too
THANKS!!!

**Comment by 27136773** [comment]
No, `RAR` is not common on operating systems such as macOS and linux
Furthermore, rar is closed source

**Comment by saqlainartazz** [comment]
ah okay! thanks for letting me know!
