### ISSUE TITLE
[Site Request] manhuasworld

### ISSUE THREAD

**Issue by Obioha111** [manga-download/hakuneko#2273]
**Name of the website**
manhuasworld.com

**Website urls (examples below)**
- Site: https://manhuasworld.com/
- Manga List: https://manhuasworld.com/manga/
- Manga example: https://manhuasworld.com/manga/martial-master/
- Chapter online viewer example: https://manhuasworld.com/manga/martial-master/chapter-401/

**Languages**
English

**Comment by Sheepux** [comment]
Duplicate : see #2252 
Also, the connector was implemented wait for an update of HakuNeko
