### ISSUE TITLE
[Crunchyroll Manga] Hitting 429 when downloading large amounts of chapters

### ISSUE THREAD

**Issue by loocool2** [manga-download/hakuneko#2275]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When downloading large amounts of chapters using the Crunchyroll Manga connector, it returns a 429 too many requests error after some chapters. 

**To Reproduce**
1. Crunchyroll Manga Connector logged in with premium
2. Download a large number of chapters fast, I downloaded 400+ chapters Arakawa Under The Bridge and it stopped around the first 20
3. Subsequent chapters return a 429 too many requests error from the API

**HakuNeko (please complete the following information):**
 - Version master@a5c135

There's no throttle connection option so I don't know if slowing down requests might fix it

**Comment by 27136773** [comment]
How long did it take until the 429 error dissapeared?

**Comment by loocool2** [comment]
I didn't check exactly how long but it's less than 24 hours since I was banned last night and was unbanned this afternoon. 
Edit: Got myself banned again, I got unbanned after 2 hours, I'll see if it's less.

**Comment by loocool2** [comment]
Yeah it's 1 hour until an unban

**Comment by MikeZeDev** [comment]
This is marked as done? Closing?
