### ISSUE TITLE
[Feature] Zip Format Request

### ISSUE THREAD

**Issue by Sakurahime08** [manga-download/hakuneko#2278]
**Is your feature request related to a problem? Please describe.**
Normal Folder files. Would like a ZIP Format as well.

**Describe the solution you'd like**
Compress chapter folder to ZIP Format after downloading

**Describe alternatives you've considered**
Zip Manually per chapter/folder

**Context (please complete the following information):**
 - © 2020 HakuNeko rev.3a8a8f

Thank you!

**Comment by 27136773** [comment]
Use `cbz` which is a ZIP archive with the chapter images or use the `Post Command` to process the chapter after download.

**Comment by Sakurahime08** [comment]
Thank you for the reply! Can you tell me specifically what to put in the post command for the files to be in .zip?

**Comment by 27136773** [comment]
It depends on to many factors, such as what system is used, what archive software is installed, are chapters downloaded as CBZ, ...

You need to find a command based on your needs
Some unrelated sample commands are in the [FAQ](https://hakuneko.download/docs/FAQ/#kindle)

**Comment by Sakurahime08** [comment]
Thank you!
