### ISSUE TITLE
[Feature] remember per manga filtered language

### ISSUE THREAD

**Issue by Albirew** [manga-download/hakuneko#2280]
**Is your feature request related to a problem? Please describe.**
more a enhancement than a problem, having to choose language then scroll all the way down just to see if there's an update or not is a pain, especially on connectors like mangadex

**Describe the solution you'd like**
having language filter remembered on bookmark file would be a nice idea
maybe a new line in key like `"lang": "gb"`?

**Context (please complete the following information):**
nightly master@a5c135

**Comment by 27136773** [comment]
See: #2007
