### ISSUE TITLE
[Mangadex] cannot fetch mangas that have brackets or comma in name

### ISSUE THREAD

**Issue by Albirew** [manga-download/hakuneko#2281]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
unable to fetch mangas that have brackets (or comma?) in their name, either download or preview pages

**To Reproduce**
1. Mangadex connector
2. manga Tensei Shichattayo (Iya, Gomen)
3. chapter any
4. any relevant error message that appears in a popup or (advanced) within the console (press F12)
net::ERR_NAME_NOT_RESOLVED *(still working with all other mangas)*
TypeError: Failed to fetch
net::ERR_NOT_IMPLEMENTED
net::ERR_NAME_NOT_RESOLVED
all of these repeated a bunch of times

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/2805161/93020303-861ed800-f5dc-11ea-930b-c33ace67cb1e.png)

**HakuNeko (please complete the following information):**
 nightly master@a5c135

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Try to use a different server in MangaDex settings...

**Comment by Albirew** [comment]
working using cloudflare CDN
