### ISSUE TITLE
[Site Request] Manga3x

### ISSUE THREAD

**Issue by DAP021** [manga-download/hakuneko#2283]
- Site: https://manga3x.com/
- Manga List: https://manga3x.com/manga-hot
- Manga example: https://manga3x.com/manga/oroka-na-tenshi-wa-akuma-to-odoru
- Chapter online viewer example: https://manga3x.com/manga/oroka-na-tenshi-wa-akuma-to-odoru/chap-1/11814
**Languages**
Eng

**Website relationship*

**Additional details**

**Comment by 27136773** [comment]
Template: MojoPortalComic
