### ISSUE TITLE
Add chapter joining statement to FAQ

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#2284]
The question about merging multiple chapter into a single archive/folder is placed quite often on discord and i'm tired of answering this question over and over again, so it might be added to FAQ.

It should be explained that merging chapters is not possible due to ordering problems when chapter names are not chronological and when downloading only selected chapters in random order...

**Comment by Sheepux** [comment]
To force users to check the FAQ, we should add a welcome bot on discord starting that for any help request you have to read the doc & the FAQ & check for similar issue on github.

**Comment by Sheepux** [comment]
Could also work on a feature matrix so that people know what's implemented, what's not, and what never will

**Comment by 27136773** [comment]
I would say the tickets are the best source for this.
Filtering by `Enhancement` tag will list all "features" that have been... rejected

**Comment by Sheepux** [comment]
I'm starting to think that you were right and that an iframe could be a nice start page and could link to subpages

**Comment by 27136773** [comment]
Merged with #2233
