### ISSUE TITLE
[Site Request] Adonis Fansub

### ISSUE THREAD

**Issue by zasfan** [manga-download/hakuneko#2286]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can see manga names but when ı click the name manga is empty
**To Reproduce**
1. Name of connector Adonis fansub
2. Name of manga (if connector update is working) all mangas
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/55949767/93110591-36184200-f6be-11ea-839a-17a95b96868b.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Seems referer is required for request to work
`https://manga.adonisfansub.net`

**Comment by zasfan** [comment]
https://manga.adonisfansub.com/
thats new url

**Comment by MikeZeDev** [comment]
Added in Haruneko https://github.com/manga-download/haruneko/pull/344
