### ISSUE TITLE
[Bug] maybe? When bookmarks got close to 300, page layout changed (vertically challenged)

### ISSUE THREAD

**Issue by doppler56** [manga-download/hakuneko#2287]
Running 6.1.7 win 10 64 bit (both systems).
I run Neko on two systems.  (work/home) share data directory across google drive.  This pass week end I got close to 300 entries in my bookmarks.  The page layout changed drastically.  See attached picture capture:
![problem](https://user-images.githubusercontent.com/30833745/93112392-f33a7800-f685-11ea-81f6-30626ac0c0f4.jpg)

This is a new clipped url entry.  As you can see the dark and light areas do not connect.  The window frame is much larger than the work area of Neko.  Every other page within Neko will resize vertically.  If I restart hakuneko, the window and frame will fill out.  But this is temporary.  It will resize.

What I see.  My home system had the problem first.  After copying the data directory (from google drive) to my work system, it started up with the same problem.  The size of the bookmarks file is 58,357.  At home I was working with over 300 bookmarks.  (less I remember wrong)  Now my work system shows 293.  This make some sense.  I was wondering why things I thought I bookmarked did not show as being bookmarked.  Possibly my bookmarks became corrupted ??

What I suspect.  Bookmarks are always sorted by series name.  Done dynamically or at start?  Possible memory corruption with the bookmarks held in memory ?  Possible size problems (aka: 64k) ?  I looked at the bookmarks files content.  Looks right as far as I know.

I will help as far as sending my bookmarks to you also.
Thanks
I did go though the help system to see if an answer was provided.
My work system was changed only by using the new bookmarks file.

**Comment by 27136773** [comment]
You probably have `Reader` disabled in seetings and ran into #2274

**Comment by doppler56** [comment]
OK, I can't confirm it totally.  I did have the reader disabled.  Only because I use an external reader/viewer.  With the reader disabled I could pull the windows frame horizontally and make more room to read chapter list and manga list panels.  It's not possible to resize those panels vertically.  Reader on or not.  If you are wondering why I want to resize the chapter/manga panels sometimes multiple scan groups compete to release chapters.  I want to get and read the dominate scan group that put in the most effort and not waste my time downloading the dupe scan group chapters.  If I can't read all of the chapter list entry, I can't tell one from another.

When the reader is on resizing on horizontal only extends the reader panel.  No extra bump for the other panels.  They remain narrow.  Maybe a feature fix?

------------ Confirmation -----------------
I checked haku at home before overlaying the google drive bookmarks from work.  I can confirm I lost 13 entries between home and work.  My work computer has less memory and a just more than adequate processor.  Only means Hakuneko takes longer to boot.  Don't understand why it makes an impact.  I will keep a closer eye on contents/counts.  Work has 295 manga and home has the two added manga's in bookmarks now at 308.  I will not be using the work (haku data)  I will over write home haku data tomorrow.  Then watch it like a vulture for a change.

Never figured out the nightly updates.  Are they stuck on 7/5/20 ?  Only 6.1.7 is good to go?  Or will I see a dynamic update later.  I can't say to close this entry yet.  I have not see a working fix.
Thanks for the help, I am almost sure that these two problems are related somehow.

**Comment by Sheepux** [comment]
nightly is synched with the master branch and therefore is always the most up to date.
The 6.1.7 is receiving only features pushed into that branch (once a week).
When releasing new features there is no 6.1.8 (the versions are used for the exe)

**Comment by doppler56** [comment]
OK, it's the end of the day for me.  My brain is fried, typical Monday effect.  I looked for the nightly compiles.  To no avail.  Normally you would find the latest stable and then nightly beta's being separate downloads.  My difficulty is finding the nightly so I can try out the fix.  Like I said I am fried.  Can you point me to the nightly Please ?  If I have to compile I am S.O.L.

**Comment by Sheepux** [comment]
Butons on main github page or butons at HTTPS://hakuneko.download

**Comment by doppler56** [comment]
Sheepux I was over there but only found a nightly run from 7/5/20.  Assets show a revision number of 8.3.4  Is this the one you refer to ?  That revision would be greater than 6.1.7  Or is there a different one ?

edit:
I looked at the touch dates on source code of 7/5/20 nightly.  That is a older release nightly.

**Comment by Sheepux** [comment]
As stated in my previous comment, the build is not rebuilt, the code is downloaded & cached by the executable. Simply download the one from 7/5

**Comment by doppler56** [comment]
Ok, I have been pre-testing the 8.3.4 code.  Have not seen the problem crop up yet.
Thanks for the nightly insight Sheepux.  I would not expect nightly to use only 1 folder to compile from.  Normally new folders everyday to hold nighties.  So when multiple programmers can back date an update that did not help or caused problems.  This helps to not lose other fixes and features since the bad code got added.

I will test more thoroughly next couple of days.  Then put a nail in this coffin.
