### ISSUE TITLE
http://www.gntai.net/

### ISSUE THREAD

**Issue by 741596357qpwo789512357** [manga-download/hakuneko#2288]
**Name of the website**
GNTAI

**Website urls (examples below)**
- Site: http://www.gntai.net/
- Manga List: http://www.gntai.net/?s=
- Manga example: http://www.gntai.net/?s=Saimin+Seishidou
- Chapter online viewer example: http://www.gntai.net/mangas-hentai/saimin-seishidou-1-obata-yui-to-tachibana-daiki-no-baai/

**Languages**
Spanish

**Additional details**
Que se pueda acceder a la lista y se pueda actulizar ademas de tambien solo poner el link del doujin y que salga directo

**Comment by 741596357qpwo789512357** [comment]
Espero que se pueda hacer mi petición

**Comment by 27136773** [comment]
Website is already supported, but broken right now...
