### ISSUE TITLE
Manga Name Error while Using Clipboard method[Bug]

### ISSUE THREAD

**Issue by saqlainartazz** [manga-download/hakuneko#2290]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When i copied the manga url and the clicked the clipboard icon it loaded the manga which i wanted but there was a bug and the manga name didnt show. I tried multiple time but the name didnt show properly. I restarted multiple times too and usend tother websites to test. unfortunately the name didnt show.

**To Reproduce**
1. Go to 'https://wuxiaworld.site/novel/kill-the-hero-comic/'
2. Copy the url : 'https://wuxiaworld.site/novel/kill-the-hero-comic/'
3. Open HakuNeko and Click Clipboard Icon

**Expected behavior**
I expected to see the manga name!

**Screenshots**
![error name png](https://user-images.githubusercontent.com/68074135/93144166-ddb76380-f702-11ea-99b4-f06920944e49.PNG)

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [6.17] Stable Latest

**Additional context**

**Comment by 27136773** [comment]
Many of the old connectors did not provide this functionality yet and need to be adapted.

Workaround: Use the manga list (if possible)

**Comment by saqlainartazz** [comment]
hmmm okay.. i found a workaround. 
i changed the name of the manga in hakuneko.bookmarks file and it worked Perfectly!!!

**Comment by 27136773** [comment]
Re-opened, still needs to be fixed in code
