### ISSUE TITLE
[ScanManga] Connector not working

### ISSUE THREAD

**Issue by SaladFiinger** [manga-download/hakuneko#2291]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When i synchronize the local list, i have the error " Failed to update manga list for ScanManga. Unexpected end of JSON input." 

**Screenshots**
![image](https://user-images.githubusercontent.com/71297213/93148400-f3715c80-f6f3-11ea-90e3-7786b5501b12.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Make sure the [manga list](https://www.scan-manga.com/scanlation/liste_series.html) (website) is working in your browser (using same proxy/VPN connection as in HakuNeko in case of region block).

**Comment by SaladFiinger** [comment]
The website works correctly in my browser and i don't use any proxy or vpn.

**Comment by Sheepux** [comment]
Able to reproduce, getting HTTP 200 on json, but json is empty ( https://www.scan-manga.com/scanlation/scan.data.json )

**Comment by 27136773** [comment]
Thats because the google ad header and the XMLHTTPRequest header are missing.
HakuNeko provides both of them when making the request.

**Comment by Sheepux** [comment]
Yeah but i meant, empty from within hakuneko :D

**Comment by 27136773** [comment]
HakuNeko uses a random User Agent, maybe some of them are blocked...

![image](https://user-images.githubusercontent.com/27136773/93249986-6c26f600-f792-11ea-9790-4f3f0f7c932b.png)

![image](https://user-images.githubusercontent.com/27136773/93249908-4d286400-f792-11ea-9bcf-f31fa7c4c774.png)

**Comment by Sheepux** [comment]
Request seems the same. Agent or IP related? (i guess that we are both french with saladFiinger )
[http_request.zip](https://github.com/manga-download/hakuneko/files/5227046/http_request.zip)
Going to investigate this week to see if i'm able to find something.

**Comment by ronny1982** [comment]
Was able to reproduce the issue by simply accessing the website from france

**Comment by fcaylus** [comment]
Hi !
I may have found the issue (I am a French user too). The JSON file is empty when `accept-language` is set to `fr` (which is the default when you have a French machine), but has content for any other language.

That would explain why it was working for @ronny1982 but not for @SaladFiinger  and @Sheepux.

However, I don't have any explanation on the reason behind it.

I'll link a PR to this issue.

PS: That's an amazing project @ronny1982

**Comment by 27136773** [comment]
I have to admit, i would never have expected such weird logic... thats ScanManga for you
