### ISSUE TITLE
[Site Request] Novelgo

### ISSUE THREAD

**Issue by zenkijoe** [manga-download/hakuneko#2293]
**Novelgo**
Novelgo

**novelgo.id**
- Site: https://novelgo.id/
- Manga List: https://novelgo.id/novellist.html
- Manga example: https://novelgo.id/novel/atg.html
- Chapter online viewer example: https://novelgo.id/novel/atg-chapter-1-yun-che-xiao-che/

**Indonesian**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Novel, Indonesian**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
Duplicate #2294
