### ISSUE TITLE
[Site Request] Novelgo

### ISSUE THREAD

**Issue by zenkijoe** [manga-download/hakuneko#2294]
**Name of the website**
Novelgo

**Website urls (examples below)**
- Site: https://novelgo.id/
- Manga List: https://novelgo.id/novel/
- Manga example: https://novelgo.id/novel/atg/
- Chapter online viewer example: https://novelgo.id/atg/atg-prologue/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment]
#2388
