### ISSUE TITLE
[Bug] keeping a watch on this one.  Bookmarks go missing.  Not repeatable or traced yet.

### ISSUE THREAD

**Issue by doppler56** [manga-download/hakuneko#2296]
I am submitting this to keep a check mark in bug reports.  Over the week end I experienced another bug dealing with window frame and program frame changing vertically re: maybe related to reader being off.  I also commented about bookmarks going missing.
I use Hakuneko between home and work.  I copy the data directory to google drive to sync work and home.  Over this pass week-end 13 bookmarks went missing.  Screen shot of one of them.

![missing](https://user-images.githubusercontent.com/30833745/93213041-5cc39080-f731-11ea-8ebc-564f10807db4.jpg)

There is nothing abnormal about the entry.  Only being KISSxDEATH was added long before the week-end.  It went missing as part of the 13 mentioned before.  Winmerge is a file to file compare program.  Which can do line to line comparisons.  If I was missing 1 or 2 bookmarks, I could just say I forgot which computer to transfer to via google drive.  But 13 went MIA. I have never added 13 bookmarks over 1 day or several days.  That many is at least a week or more.  They went missing on my work computer.  (after GD transfer)

Config of my work computer:
4GB -vs- 16GB home.  Core 2 Duo -vs- I7 home.  Other than that everything else is the same or is irrelevant.

I don't expect an answer to this now.  I have too little to go on and provided just as much.  I am only for a better phrase "Bookmarking" this bug.  Stay tuned I might obtain a more definitive diagnostic conclusion.
BTW, work computer processed correctly the 310 entries from home not missing any.

**Comment by Sheepux** [comment]
I'll bet that your bookmarks versions aren't the same, the folders might be out of sync and therefore not serving the same versions.
Nothing hakuneko can do i'd say.

**Comment by 27136773** [comment]
I was under the same impression, it is easy to make a mistake when copying folders back and forth between different instances. Better use the portable edition and put it on USB drive.

**Comment by doppler56** [comment]
I am using a separate folder on a different drive for the user data (bookmarks/chapters).  This would not be so different than using portable version.  I have only been using 6.1.7 since about 3 weeks now.  So version of bookmarks don't understand ?

Please note I am running 8.3.4 now and have not seen the vertical window problem (with reader off).  Will test more.

**Comment by Sheepux** [comment]
Version : file on computer A vs file on computer B (one not being synchronised with the latest use : "therefore a different version").
I suggest closing as it's not a bug, it's about usage of filesync.

**Comment by doppler56** [comment]
Unless I remove bookmarks, the file will never get smaller.  I admit my file syncing is crude.  I just drop a copy of the data folder into GD and off it goes to home or work.  Wherever my butt sits next.  When I get there I must copy out the folder to the user data location.  In doing so, I see the file size difference before overwriting.  That's how I found out 13 bookmarks went poof.  My crudeness might miss 1 or 2 bookmarks, not 13.

When you mentioned version.  I was thing along the lines of an older Hakuneko data format -vs- new haku.  I expect in all likeliness, this bug will not be repeatable.  Hence not a real bug, but a burp.  Time will tell.

**Comment by 27136773** [comment]
It is very likely that if this really is a generic problem with HakuNeko, this would already have been reported by other users.

**Comment by doppler56** [comment]
I have not seen this happen again.  Like I said: "Not traceable at this time."  Or a figment of my imagination.  If it does come back in a traceable form.  New bug report for now this is closed.
