### ISSUE TITLE
Can't download in 

### ISSUE THREAD

**Issue by Juxn-rg** [manga-download/hakuneko#230]
Operating System : Windows 10
Rev number           : 75b03b

**Comment by 27136773** [comment]
It was possible to reproduce the issue once, but now it seems to work for me and can no longer be reproduced anymore.
I noticed that the preview seems to work just fine, only the download was affected.

**Comment by 27136773** [comment]
Please check if the problem is now solved by the change made for another issue, otherwise re-open this ticket.
