### ISSUE TITLE
Funmanga manga List error.[Bug]

### ISSUE THREAD

**Issue by saqlainartazz** [manga-download/hakuneko#2305]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
There is issue with the connector for website: Funmanga.com and mangalist is not showing up.

**Comment by saqlainartazz** [comment]
[FunManga.zip](https://github.com/manga-download/hakuneko/files/5233784/FunManga.zip)
Here is the fixed .mjs file for this connector
I am new to github so i dont know how to operate so this might be wrong place to do this!

**Comment by 27136773** [comment]
I think you can just browse to the file in GitHub and then edit it there.
It should automatically create a branch and also ask for a Pull Request to merge the changes...

The good thing is, you cannot break anything

**Comment by saqlainartazz** [comment]
ok
