### ISSUE TITLE
Theme/template of website :mangazone.cc

### ISSUE THREAD

**Issue by saqlainartazz** [manga-download/hakuneko#2306]
I am unable to find the template/theme of website mangazone.cc
it doest work properly with wordpressmadara
help please

**Comment by 27136773** [comment]
Website:
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/MangaZone.mjs
Template:
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/WordPressMadara.mjs

**Comment by 27136773** [comment]
I recommend to use Discord server for further questions, it is more convenient for discussions then using GitHub tickets

**Comment by saqlainartazz** [comment]
okay!
and does the connectors autosync with client?
