### ISSUE TITLE
[Site Request] Cmoa

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#2307]
**Name of the website**
cmoa

**Website urls (examples below)**
- Site: https://www.cmoa.jp/
- Manga List: 
https://www.cmoa.jp/genre/20/
https://www.cmoa.jp/genre/2/
- Manga example: https://www.cmoa.jp/title/115225/
- Chapter online viewer example: https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000115225_jp_0001&u0=1&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Ftitle%2F115225%2F

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Ever4engel** [comment]
@ronny1982  this could help https://github.com/xuzhengyi1995/Manga_downloader

**Comment by Ever4engel** [comment]
Use speedbind template
