### ISSUE TITLE
[Site Request] Request nHentai.com

### ISSUE THREAD

**Issue by CarterSnich** [manga-download/hakuneko#2308]
**Name of the website**
nHentai (but the dot-com version hehehe)

**Website urls (examples below)**
- Site: https://nhentai.com/
- Manga List: https://https://nhentai.com/en/latest
- Manga example: https://nhentai.com/en/comic/misty-wind-kirishima-fuuki-taima-senkiden-chinese
- Chapter online viewer example: https://nhentai.com/en/comic/misty-wind-kirishima-fuuki-taima-senkiden-chinese/reader/5

**Languages**
- English
- Chinese
- Japanese

**Website relationship*

**Additional details**
same website name with nHentai.net.
It's also not blocked by my organization. tee-hee

**Comment by MikeZeDev** [comment]
Since fetching the mangalist (400k+ entries) would for HN to perform a crapload of requests to their api it had been decided to only code the clipboard method.
