### ISSUE TITLE
[FunManga] Connector not working

### ISSUE THREAD

**Issue by ArwinRam** [manga-download/hakuneko#2310]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I click the green refresh button to load the list of manga, I get this pop-up message

"Failed to update manga list for FunManga
Please report this broken website on HakuNeko's GitHub project page."

**To Reproduce**
1. FunManga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. 
"Failed to update manga list for FunManga
Please report this broken website on HakuNeko's GitHub project page."

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="1279" alt="Hakuneko Error" src="https://user-images.githubusercontent.com/63857411/93474604-9200e780-f8c5-11ea-8588-8c6ef6e3994e.png">

**HakuNeko (please complete the following information):**
 - Version 6.17

EDIT:
https://www.funmanga.com/manga-list

**Comment by 27136773** [comment]
Needs to be implemented.
Same website layout/template as MangaInn
https://www.mangainn.net/manga-list
