### ISSUE TITLE
[Site Request] Manga Action

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#2316]
**Name of the website**
Manga Action

**Website urls (examples below)**
- Site: https://comic-action.com/
- Manga List: https://comic-action.com/series
- Manga example: https://comic-action.com/episode/13933686331709379577
- Chapter online viewer example: https://comic-action.com/episode/13933686331709379577

**Languages**
Japanese

**Additional details**
It uses the same system as Shonen Magazine Pocket and many others, so it probably shouldn't take too long to implement.

**Comment by 27136773** [comment]
Implying from the descripion, Template: CoreView
