### ISSUE TITLE
Synchronize won't work for MangaHasu

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#232]
> **From:** HakuNeko User

unable to update list. Thank you.

**Comment by 27136773** [comment]
Currently MangaHasu has more then 900 pages that needs to be checked for building the manga list. Depending on network speed this may take a while. Sometimes it may happen that the client or the server will face connection issues during synchronization.

When synchronizing list make sure no other heavy network activity is done in the background (e.g. file downloads).
