### ISSUE TITLE
Connector checkup #-E

### ISSUE THREAD

**Issue by XenonR** [manga-download/hakuneko#2321]
Connector | URL | Automatic Test | Europe | Asia | US
----- | ----- | ----- | ----- | ----- | ----- 
.MangaRock.mjs|https://mangarock.com|✔️|❌|❌|❌
.RawQQ.mjs|https://rawqq.com|❌|❌|❌|❌
ActionManga.mjs|https://www.action-manga.com|❌|❌|❌|❌
AdonisFansub.mjs|https://manga.adonisfansub.com|403|✔️|(✔️)|✔️
AHStudios.mjs|https://ahstudios.net|✔️|✔️|(✔️)|✔️
AjiaNoScantrad.mjs|https://ajianoscantrad.fr|❌|❌|❌|❌
AkaiYuhiMun.mjs|https://akaiyuhimun.ru|403|1020|1020|1020
AlianzaMarcial.mjs|https://www.alianzamarcial.xyz|❌|❌|❌|❌
AllHentai.mjs|http://allhentai.ru|✔️|✔️|(✔️)|✔️
AllManga.mjs|https://mangaarab.com|❌|❌|❌|❌
AllPornComic.mjs|https://allporncomic.com|✔️|✔️|(✔️)|✔️
AnataNoMotokare.mjs|http://motokare.xyz|403|✔️|(✔️)|✔️
AngelOfResistance.mjs|https://angelofresistance-tr.com|✔️|Susp.|Susp.|Susp.
AnimePahe.mjs|https://animepahe.com|✔️|✔️|(✔️)|✔️
AnimExtremist.mjs|http://www.animextremist.com|✔️|✔️|(✔️)|✔️
AniRune.mjs|https://anirune.com|✔️|✔️|(✔️)|✔️
Anivizyon.mjs|https://www.anivizyon.com|✔️|✔️|(✔️)|✔️
AntisenseScans.mjs|http://antisensescans.com|406|✔️|(✔️)|✔️
AOC.mjs|https://aoc.moe|❌|❌|❌|❌
ApollComics.mjs|https://apollcomics.xyz|✔️|✔️|(✔️)|✔️
ApollToons.mjs|https://apolltoons.xyz|✔️|✔️|(✔️)|✔️
ArangScans.mjs|https://arangscans.com|✔️|✔️|(✔️)|✔️
ArazNovel.mjs|https://www.araznovel.com|✔️|✔️|(✔️)|✔️
ArgosScan.mjs|https://argosscan.com|✔️|✔️|(✔️)|✔️
ArtemisNoFansub.mjs|https://artemisnf.com|522|522|522|522
AsmHentai.mjs|https://asmhentai.com|✔️|✔️|(✔️)|✔️
AstralLibrary.mjs|https://astrallibrary.net|✔️|✔️|(✔️)|✔️
AsuraScans.mjs|https://asurascans.com|✔️|✔️|(✔️)|✔️
AtelierDuNoir.mjs|http://atelierdunoir.org|404|❌|❌|❌
Atikrost.mjs|https://atikrost.com|✔️|✔️|(✔️)|✔️
AtmSubs.mjs|https://atm-subs.fr|✔️|❌|(✔️)|✔️
Authrone.mjs|http://www.authrone.com|✔️|❌|❌|❌
AzoraManga.mjs|https://www.azoramanga.com|✔️|✔️|(✔️)|✔️
BacaKomik.mjs|https://bacakomik.co|✔️|✔️|(✔️)|1020
BacaManga.mjs|https://bacamanga.co|503|✔️|(✔️)|✔️
BakaguyaScan.mjs|https://bakaguya-scan.tk|❌|❌|❌|❌
Batoto.mjs|https://bato.to|✔️|✔️|(✔️)|✔️
BestManga.mjs|https://bestmanga.club|✔️|✔️|(✔️)|✔️
Biamam.mjs|http://biamam.com|✔️|✔️|(✔️)|✔️
BlackDragonsFansub.mjs|https://bdsfansub.com|✔️|✔️|(✔️)|✔️
BlogTruyen.mjs|https://blogtruyen.vn|❌|✔️|(✔️)|❌
BookLive.mjs|https://booklive.jp|✔️|✔️|(✔️)|✔️
BoredomSociety.mjs|https://www.boredomsociety.xyz|✔️|httpd2|httpd2|httpd2
BunnysScans.mjs|http://bns.shounen-ai.net/read/|❌|❌|❌|❌
CanisMajorScans.mjs|http://cm-scans.shounen-ai.net|❌|❌|❌|❌
CentralDeMangas.mjs|http://cdmnet.com.br|✔️|✔️|❌|✔️
ChampionScans.mjs|https://read.ptscans.com|✔️|✔️|(✔️)|✔️
ChibiManga.mjs|http://www.cmreader.info|✔️|✔️|(✔️)|✔️
CiayoEN.mjs|https://www.ciayo.com/en|❌|❌|❌|❌
CiayoID.mjs|https://www.ciayo.com/id|❌|❌|❌|❌
CloverManga.mjs|https://clover-manga.com|✔️|✔️|(✔️)|✔️
ComicAction.mjs|https://comic-action.com|✔️|✔️|(✔️)|✔️
ComicBoost.mjs|https://comic-boost.com|✔️|✔️|(✔️)|✔️
ComicBorder.mjs|https://comicborder.com|✔️|✔️|(✔️)|✔️
ComicDays.mjs|https://comic-days.com|✔️|✔️|(✔️)|✔️
ComicEarthStar.mjs|https://www.comic-earthstar.jp|✔️|✔️|(✔️)|✔️
ComicExtra.mjs|http://www.comicextra.com|✔️|✔️|(✔️)|✔️
ComicFire.mjs|https://www.hobbyjapan.co.jp/comic|❌|❌|(✔️)|❌
ComicGardo.mjs|https://comic-gardo.com|✔️|✔️|(✔️)|✔️
ComicMeteor.mjs|https://comic-meteor.jp|✔️|✔️|(✔️)|✔️
Comico.mjs|https://www.comico.jp|✔️|✔️|(✔️)|✔️
ComicoNovel.mjs|https://novel.comico.jp|✔️|✔️|(✔️)|✔️
ComicRyu.mjs|https://www.comic-ryu.jp|✔️|✔️|(✔️)|✔️
ComicVN.mjs|https://beeng.net|✔️|✔️|(✔️)|✔️
ComicWalker.mjs|https://comic-walker.com|✔️|✔️|(✔️)|✔️
CopyPasteScan.mjs|https://copypastescan.xyz|✔️|✔️|(✔️)|✔️
DangolineNoFansub.mjs|http://lector.dangolinenofansub.com|✔️|_empty_|_empty_|_empty_
DarkSkyProjects.mjs|https://darkskyprojects.org|503|✔️|(✔️)|✔️
DarkYueRealm.mjs|https://darkyuerealm.site|406|✔️|(✔️)|✔️
DaumWebtoon.mjs|http://webtoon.daum.net|✔️|✔️|(✔️)|✔️
DeathTollScans.mjs|https://reader.deathtollscans.net|✔️|✔️|(✔️)|✔️
DemoneCeleste.mjs|https://www.demoneceleste.it|❌|✔️|(✔️)|✔️
Desu.mjs|https://desu.me|✔️|✔️|(✔️)|✔️
DigitalTeam.mjs|https://dgtread.com|✔️|✔️|(✔️)|✔️
DisasterScans.mjs|https://disasterscans.com|✔️|✔️|(✔️)|✔️
DokiFansubs.mjs|https://kobato.hologfx.com|✔️|✔️|(✔️)|✔️
DongManManhua.mjs|https://www.dongmanmanhua.cn|✔️|✔️|(✔️)|❌
DoujinDesu.mjs|https://doujindesu.info|✔️|✔️|(✔️)|✔️
DoujinHentai.mjs|https://doujinhentai.net|✔️|✔️|(✔️)|✔️
Doujins.mjs|https://doujins.com|✔️|✔️|(✔️)|✔️
DoujinYosh.mjs|https://doujinyosh.work|✔️|❌|❌|❌
DropeScan.mjs|https://dropescan.com|✔️|✔️|(✔️)|✔️
DynastyScans.mjs|https://dynasty-scans.com|✔️|✔️|(✔️)|✔️
EarlyManga.mjs|https://earlymanga.website|✔️|✔️|(✔️)|✔️
EcchiScan.mjs|https://ecchiscan.com|522|522|522|522
EdelgardeScans.mjs|https://edelgardescans.com|✔️|✔️|(✔️)|✔️
EGScans.mjs|https://read.egscans.com|❌|❌|❌|❌
EHentai.mjs|https://e-hentai.org|✔️|✔️|(✔️)|✔️
EightMuses.mjs|https://comics.8muses.com|✔️|✔️|(✔️)|✔️
EightMusesXXX.mjs|https://8muses.xxx|✔️|✔️|(✔️)|✔️
ElevenToon.mjs|http://www.11toon.com|503|✔️|(✔️)|✔️
EmirSUB.mjs|http://emirsub.com|❌|❌|❌|❌
EpikManga.mjs|https://www.epikmanga.com|✔️|✔️|(✔️)|✔️
EvilFlowers.mjs|http://reader.evilflowers.com|✔️|✔️|(✔️)|✔️
ExHentai.mjs|http://exhentai.org|❌|❌|❌|❌
EyeOnManga.mjs|http://www.eyeonmanga.com|❌|❌|❌|❌

**Comment by dodieboy** [comment]
I tested the list on my side too, for Asia(Singapore) and here is some connector that i revived error:
.MangaRock.mjs: Empty website (no manga)
.RawQQ.mjs: This site can’t be reached
ActionManga.mjs: This site can’t be reached
AjiaNoScantrad.mjs: This site can’t be reached
AkaiYuhiMun.mjs: Error 1020
AlianzaMarcial.mjs: This site can’t be reached
AllManga.mjs: This site can’t be reached
AngelOfResistance.mjs: This Account has been suspended.
AOC.mjs: Maintenance
ArtemisNoFansub.mjs: Error 522
AtelierDuNoir.mjs: Error 404
Authrone.mjs: Empty website
BakaguyaScan.mjs: This site can’t be reached
BoredomSociety.mjs: Empty website (no manga)
BunnysScans.mjs: This site can’t be reached
CanisMajorScans.mjs: This site can’t be reached
CentralDeMangas.mjs: This site can’t be reached
CiayoEN.mjs: This site can’t be reached
CiayoID.mjs:  This site can’t be reached
DangolineNoFansub.mjs:  Empty website
EcchiScan.mjs: Error 522
EGScans.mjs: Redirected to mangadex.org
EmirSUB.mjs: This site can’t be reached
ExHentai.mjs: This site can’t be reached
EyeOnManga.mjs: This site can’t be reached

**Comment by XenonR** [comment]
> I tested the list on my side too, for Asia(Singapore) and here is some connector that i revived error:

@dodieboy Thanks a lot! All not listed ones where working for you?

**Comment by XenonR** [comment]
20% Marked for removal (18/96):
- .MangaRock.mjs
- .RawQQ.mjs
- ActionManga.mjs
- AjiaNoScantrad.mjs
- AlianzaMarcial.mjs
- AllManga.mjs
- AOC.mjs
- AtelierDuNoir.mjs
- Authrone.mjs
- BakaguyaScan.mjs
- BunnysScans.mjs
- CanisMajorScans.mjs
- CiayoEN.mjs
- CiayoID.mjs
- DoujinYosh.mjs
- EGScans.mjs
- EmirSUB.mjs
- ~~ExHentai.mjs~~
- EyeOnManga.mjs
