### ISSUE TITLE
[Site Request] 古风漫画网 (GuFengMH8)

### ISSUE THREAD

**Issue by vinh2201** [manga-download/hakuneko#2330]
**Name of the website**
古风漫画网 (GuFengMH8)

**Website urls (examples below)**
- Site: https://www.gufengmh8.com/
- Manga List: https://www.gufengmh8.com/list/
- Manga example: https://www.gufengmh8.com/manhua/zhongshengxiangfenggeiniwodedujiachongni/
- Chapter online viewer example: https://www.gufengmh8.com/manhua/zhongshengxiangfenggeiniwodedujiachongni/1396074.html

**Languages**
Chinese

**Additional details**
The website uses template like 漫画牛 (ManHuaNiu) but this connector on HakuNeko is probably not working, and some addresses on this site (exactly are the websites to manga info) are different from 漫画牛 (ManHuaNiu).

**Comment by 27136773** [comment]
Theme: SinMH
