### ISSUE TITLE
WuxiaWorld failed to update

### ISSUE THREAD

**Issue by novelotaku** [manga-download/hakuneko#2333]
It **failed** when I've tried **to update** the **website**
![image](https://user-images.githubusercontent.com/71598747/93714096-015f2b80-fb93-11ea-88a0-444c346dc94f.png)

**Comment by Sheepux** [comment]
Unable to reproduce, working fine here.

**Comment by XenonR** [comment]
Working without issues. Due to the error code 503 it is very likely there was a web server error on the far end.
If problem persists please state your location.

**Comment by 27136773** [comment]
No problems on my end as well...

![image](https://user-images.githubusercontent.com/27136773/94169213-d88aaf00-fe8e-11ea-9db5-366fd90abc24.png)

**Comment by Sheepux** [comment]
Closing, issue was probably on website side. Reopen if still happening (make sure the site can be opened from hakuneko: use manual website interaction).
