### ISSUE TITLE
[Site Request] MangaOwl

### ISSUE THREAD

**Issue by saqlainartazz** [manga-download/hakuneko#2335]
**Name of the website**
MangaOwl

**Website urls (examples below)**
- Site: https://mangaowl.net/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://mangaowl.net/single/NTV6/one-piece
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
note:
manga list : https://mangaowl.net/list
reader example : https://mostraveller.com/reader/reader/841/606326/0?s=aHR0cHM6Ly9tYW5nYW93bC5uZXQ%3D

**Comment by MikeZeDev** [comment]
Dead website. Maybe exists with another url? Anyway @Sheepux  please :)

**Comment by Sheepux** [comment]
unsure about alternative domain
https://mangaowl.io/
https://mangaowl.to/

**Comment by MikeZeDev** [comment]
Hence the "we're back" in title bar. Nice find .
