### ISSUE TITLE
[Site Request] Mangacım 

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2336]
Name of the website:
Mangacım 

•	Site:  http://mangacim.com/manga/
•	Manga List: http://mangacim.com/manga/manga-list
•	Manga example:  http://mangacim.com/manga/manga/Vanitas_no_Carte
•	Chapter online viewer example: http://mangacim.com/manga/manga/Vanitas_no_Carte/1

Language: Turkish

**Comment by manh21** [comment]
Can't access the website

**Comment by 27136773** [comment]
Domain redirects to an almost empty forum (hosted on createaforum.com)
http://mangacim.com/forum/

**Comment by 27136773** [comment]
Works now: #2967
