### ISSUE TITLE
[Site Request] Liebe Schnee Hiver

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2344]
Name of the website:
Liebe Schnee Hiver

•	Site:  https://www.liebeschneehiver.com
•	Manga List: https://www.liebeschneehiver.com/adan-zye-liste/
•	Manga example:  https://www.liebeschneehiver.com/manga/chitra
•	Chapter online viewer example:  https://www.liebeschneehiver.com/1-bolum-2

Language: Turkish

**Comment by kaikai-chan** [comment]
Hi, this site is closed. Can you closed this topic? I want opened new site again.
