### ISSUE TITLE
Holymanga doesn't work

### ISSUE THREAD

**Issue by joseph619** [manga-download/hakuneko#235]
[Holymanga](http://ww1.holymanga.net) isn't working, chapters do not load after clicking on manga.

Operating System: Windows 10

Rev number: 86da11

Error log: 

Failed to load resource: net::ERR_NAME_NOT_RESOLVED

heavenmanga.html:103 TypeError: Failed to fetch HolyManga
fetchDOM.then.then.catch.error @ heavenmanga.html:103

_getUpdatedChaptersFromWebsite TypeError: Failed to fetch
connector.initialize.then.then.catch.error @ manga.html:144

![Capture](https://user-images.githubusercontent.com/34897862/60378719-b472c080-99f4-11e9-8d4f-a585cf636967.PNG)

**Comment by 27136773** [comment]
Has been fixed, but please be aware that holymanga has some dead image links that cannot be downloaded.
This is an issue on their end.
