### ISSUE TITLE
[JapScan] Connector not working

### ISSUE THREAD

**Issue by Icare666** [manga-download/hakuneko#2358]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes and No : the url of the website had changed (not japscan.to anymore) to japscan.se

**Describe the bug**
Impossible to access and download mangas from JapScan because the url had changed from japscan.to to japscan.se .

**To Reproduce**
1. Name of connector
JapScan
2. Name of manga (if connector update is working)
/
3. Name of chapter (if manga update is working)
/
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to update manga list from JapScan
ERR_NAME_NOT_RESOLVED
https://www.japscan.co/?ts=1600871863058&rd=0.04088912377866705

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
/

**HakuNeko (please complete the following information):**
 - Version [6.1.7]

**Comment by RithyNicolasTAN** [comment]
Hi

The new url is https://www.japscan.se/.
The connector must be updated.

Thanks for your awesome work !

**Comment by Sheepux** [comment]
Changing the domain seems to be working, but i still get a lot of manga download failure on some titles even with 7500ms of throtling. 
Need more testing to see if that's a new behavior or if it's just because it's still a crappy site

**Comment by Sheepux** [comment]
Issue is pinned because lots of duplicates are being created.
The domain change has been fixed and is now available in the nightly release.
The change will be pushed to 6.1.7 (non nightly) in a few days.

**Comment by Sheepux** [comment]
Changes pushed to 6.1.7

**Comment by Krylanc3lo** [comment]
thank you!
