### ISSUE TITLE
[Site Request] hentailx

### ISSUE THREAD

**Issue by nguyenbachb** [manga-download/hakuneko#2361]
Name of the website:

Hentailx

• Site: http://lxhentai.com/
• Manga List:
• Manga example: http://lxhentai.com/story/view.php?id=1482&token=MC4yNjA5ODQ0ODQ4Nzg4Mjg1MC4yODQyMjg2MzAzNzAxMTYyNQvv
• Chapter online viewer example: http://lxhentai.com/story/chapter.php?id=6702&token=MC43OTQ1MDM1MjQ3MjczMjgyMC41OTEwODg2NDQ5MzMxNjk2

Languages: Vietnamese

**Comment by 27136773** [comment]
Template: MojoPortalComic
