### ISSUE TITLE
[漫画牛 (ManHuaNiu)] Connector not working

### ISSUE THREAD

**Issue by vinh2201** [manga-download/hakuneko#2362]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Mangas and images on the website are working properly, but the connector on HakuNeko give back the error images.

**To Reproduce**
1. Name of connector 漫画牛 (ManHuaNiu)
2. Name of manga (if connector update is working) (C81) The World Is Mine
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![error](https://user-images.githubusercontent.com/63141930/94127858-a293fd80-fe83-11ea-972e-0f8c20878539.jpg)
![error_2](https://user-images.githubusercontent.com/63141930/94128090-e850c600-fe83-11ea-9c44-b6fe43d28ac8.jpg)
![error_3](https://user-images.githubusercontent.com/63141930/94128099-ea1a8980-fe83-11ea-969d-b0bfbeeeb7d6.jpg)
![error_4](https://user-images.githubusercontent.com/63141930/94128107-eb4bb680-fe83-11ea-92a6-22c6c8e2f037.jpg)

**HakuNeko (please complete the following information):**
 - Version: Nightly build v8.3.4 (nightly-20200705.1)

**Comment by 27136773** [comment]
Image links require referer, e.g.
`curl 'https://restp.dongqiniqin.com//images/comic/48/94205/1523201325cd1D7LPTc8m6QCJI.jpg' -H 'Referer: https://manhuaniu.com' > /dev/null`
