### ISSUE TITLE
[JapScan] Connector not working

### ISSUE THREAD

**Issue by tomJEAN2** [manga-download/hakuneko#2363]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
old url:https://www.japscan.co/
new url:https://www.japscan.se/
Thanks

**Comment by Sheepux** [comment]
Use the nightly.
Duplicate #2358
