### ISSUE TITLE
[JapScan] Connector not working

### ISSUE THREAD

**Issue by MisssBooks** [manga-download/hakuneko#2364]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The website has changed its address
the old : https://www.japscan.co
the new : https://www.japscan.se

**To Reproduce**
1. Name of connector [Japscan]
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MisssBooks** [comment]
![1234](https://user-images.githubusercontent.com/71828111/94146572-6907c600-fe74-11ea-9a7d-3939ccc9fada.png)

**Comment by Sheepux** [comment]
Use the nightly.
Duplicate #2358
