### ISSUE TITLE
[JapScan] Connector not working

### ISSUE THREAD

**Issue by ElGothiko** [manga-download/hakuneko#2365]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
The website change is URL to https://www.japscan.se/

**Describe the bug**
No manga list or chapters display in hakuneko
The website change is URL  to https://www.japscan.se/

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See: #2358
