### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by CaptnCookzer** [manga-download/hakuneko#2366]
**Name of the website**
JapScan

**Website urls (examples below)**
- Site: https://www.japscan.se
- Manga List: https://www.japscan.se/mangas/
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Already supported by HakuNeko, please check before making ticket.
See also: #2358
