### ISSUE TITLE
Adding a marker for unread chapters, new chapters etc..[Feature]

### ISSUE THREAD

**Issue by Djedae** [manga-download/hakuneko#2369]
**Is your feature request related to a problem? Please describe.** 

_I have no problem at all, i wish to add some marker for chapters reads and when there is new chapters on our favorite manga_

**Describe the solution you'd like**

_I was thinking about a marker "NEW" when there is update on some mangas in our favourites, and use some markers for a total of chapter to read, and those series who are complete would have no markers._

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17] 
_Nightmode "Master version"_

**Additional context**
![image](https://user-images.githubusercontent.com/71845236/94183317-86538900-fea2-11ea-9b87-fc3379704bd6.png)

_In yellow it's total chapter, in green what you have to read for example and maybe adding a red marker for missing chapter or new updates chapter you don't have_

**Comment by Sheepux** [comment]
Relates to #653

**Comment by newaccforhc** [comment]
Yeah.. Sounds like duplicate

**Comment by Sheepux** [comment]
Not exactly a duplicate, could be merged

**Comment by Djedae** [comment]
It's a feature i got on comickrack, but it's using a script to do that counter. But don't remember the name of the script.

**Comment by Sheepux** [comment]
We know this use case verywell. It's the same as #653, the difference here is in the way you suggest the UI design.
It will only be done with Hakuneko NextGen (2021) as it requires quite a lot of concept changes..
