### ISSUE TITLE
Add support for H website Indonesia

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#237]
- [x] https://mangadropout.net/

- [x] https://www.mangadropout.com/

- [x] https://www.doujindesu.wtf/

**Comment by 27136773** [comment]
The dropout websites have the same logo, are their any major differences (except visual appearance)?

**Comment by 27136773** [comment]
To me it looks like https://www.mangadropout.com is going to replace https://mangadropout.net
While https://mangadropout.net still provides more chapters, they don't have been updated within the last week.
The content of https://mangadropout.net is rapidly growing which may imply a migration.

On the other hand the domain registration date implies exactly the opposite with https://mangadropout.com registered in 2017 and https://mangadropout.net registered in 2019

**Comment by 27136773** [comment]
Both MDO websites have been added, until one of them may disappear...

**Comment by MIRVOUS** [comment]
Verry thanks ronny
