### ISSUE TITLE
Japscan Connector not working

### ISSUE THREAD

**Issue by barth1309** [manga-download/hakuneko#2370]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Japscan.co adress change to Japscan.se

Thanks for your help.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
See #2358
