### ISSUE TITLE
[blogtruyen.vn] Connector not working

### ISSUE THREAD

**Issue by thiennhing** [manga-download/hakuneko#2371]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can't use the website connector https://blogtruyen.vn/
When I click green button to update list, it has popup:
Failed to update manga list for BlogTruyen

Failed to receive content from "https://blogtruyen.vn/ajax/Search/AjaxLoadListManga?key=tatca&orderBy=1&p=162" (status: 500) -
 
I changed VPN to try but I didn't work also.

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - 6.1.7

**Comment by manh21** [comment]
This is a website error, not a HakuNeko connector problem. You should report it to the website admin (Don't mention you are using HakuNeko).
![image](https://user-images.githubusercontent.com/31276236/94993364-b72a7100-05ba-11eb-8145-2716899501d2.png)

**Comment by 27136773** [comment]
BlogTruyen's manga list update is very slow and unstable (because of their bad website host)
Use copy & paste instead
