### ISSUE TITLE
[Site Request] Japscan

### ISSUE THREAD

**Issue by EnzoPaketo** [manga-download/hakuneko#2372]
**Name of the website**
Japscan

**Website urls (examples below)**
- Site: https://www.japscan.se/
- Manga List: https://www.japscan.se/mangas/
- Manga example: https://www.japscan.se/manga/a-certain-magical-index/
- Chapter online viewer example: https://www.japscan.se/lecture-en-ligne/a-certain-magical-index/24/

**Languages**
French

**Website relationship*
idk

**Additional details**
The new japscan site

**Comment by 27136773** [comment]
Already supported by HakuNeko, please check before making ticket.
See also: #2358
