### ISSUE TITLE
FAILED UPDATE LIST ON JAPSCAN

### ISSUE THREAD

**Issue by snohboy** [manga-download/hakuneko#2374]
Hello I can not update the list of manga on japscan and also see the chapters there.
the error message that appears when I update is: "ERR_NAME_NOT_RESOLVED"

![Capture d’écran 2020-09-25 132402](https://user-images.githubusercontent.com/60775518/94273356-d3cc0680-ff33-11ea-9838-91556efd7af9.png)

**Comment by 27136773** [comment]
#2358
