### ISSUE TITLE
[CoreView] Getting weird title when URI method is used

### ISSUE THREAD

**Issue by newaccforhc** [manga-download/hakuneko#2376]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Get weird title when we use URI (copy-paste) method with coreview template sites like Shonenjumpplus

**To Reproduce**
1. Copy this URL: https://shonenjumpplus.com/episode/13933686331713121780
2. Paste it in HakuNeko
3. See the name (it should be something like Manga#970)

**Screenshots**
![ffffff](https://user-images.githubusercontent.com/51260976/94287197-a141fe00-ff73-11ea-89f1-895c1f9158a6.PNG)

**HakuNeko (please complete the following information):**
 - Version Nightly (master)

**Comment by 27136773** [comment]
See also: #2290
