### ISSUE TITLE
[https://www.japscan.co/] Connector not working

### ISSUE THREAD

**Issue by alexandre-philippeau** [manga-download/hakuneko#2377]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes and thanks for all the detailed information!

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**

Hello, first of all thank you for developing HakuNeko Desktop, this manga downloader is just awesome! My problem is very simple, the french Japscan website has changed URL. The new address is https://www.japscan.se/ (old URL: https://www.japscan.co/). Therefore it's not possible to download manga anymore since the connector is no longer valid. 

Can you please update the connector?
https://www.japscan.se/ instead of https://www.japscan.co/

Thank you in advance and good continuation, you are doing a very good job! 

A French user of HakuNeko ;) 

**To Reproduce**
1. Name of connector : https://www.japscan.co/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to update manga list for JapScan

ERR_NAME_NOT_RESOLVED https://www.japscan.co/?ts=1601074450028&rd=0.32692636119746377

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
#2358

**Comment by alexandre-philippeau** [comment]
Sorry for the duplicate topic, I didn't think to search if the problem was already solved. I downloaded the Nightly version while waiting for the fix in the stable version. Thanks a lot @ronny1982!
