### ISSUE TITLE
[JapScan] Multiple scrambled image

### ISSUE THREAD

**Issue by Neths** [manga-download/hakuneko#2378]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error after downloading chapter of manga
https://www.japscan.se/lecture-en-ligne/noblesse/543/

**To Reproduce**
1. Name of connector : JapScan
2. Name of manga (if connector update is working) : Noblesse
3. Name of chapter (if manga update is working) : 538/539/540/541/542/543
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

Connector.mjs:599 Error: Extraxtion of multiple scrambled images from a single page is not yet supported!
    at JapScan._getPagesScrambledSingle (JapScan.mjs:4)
    at JapScan._getPages (JapScan.mjs:4)
    at async JapScan._getPageList (Connector.mjs:596) 
EventTarget
file: {name: "543  FIN", extension: "", full: "543  FIN"}
id: "/lecture-en-ligne/noblesse/543/"
language: ""
manga: EventTarget {connector: JapScan, id: "/manga/noblesse/", title: "Noblesse", status: "available", chapterCache: Array(544), …}
pageCache: []
pageProcess: false
status: "failed"
title: "543 : FIN"
__proto__: EventTarget

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by 27136773** [comment]
See: https://github.com/inorichi/tachiyomi-extensions/blob/master/src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt

- Uses now screenshots to get images
- Seems to have implementations for single- and multipage reader

**Comment by 27136773** [comment]
No they don't have implementations yet for scrambled + single page mode
References: inorichi/tachiyomi-extensions#4759
Let's see how Tachiyomi will fix this, maybe we can save some time and effort

**Comment by az4521** [comment]
as the main contributor for the current tachiyomi japscan extension, i'd like to warn you in advance that the current method for unscrambling images is to apply custom CSS, inject JS to rearrange the DOM, and screenshot the webpage. any fix for tachiyomi will likely be unusable outside of it.

**Comment by 27136773** [comment]
References: tachiyomiorg/tachiyomi-extensions#6166
Let's see how Tachiyomi will fix this, maybe we can save some time and effort

**Comment by MikeZeDev** [comment]
Afaik they dont scramble pics anymore
