### ISSUE TITLE
[Mangastream] Connector not working

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#2380]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The site is down forever. No manga catalog from this website.

**To Reproduce**
1. Mangastream.com
2. Not applicable
3. Not applicable
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by newaccforhc** [comment]
btw, there are 3 MangaStream in HN... 
the site with `ID: mangastream` is dead.. Remove that only..
