### ISSUE TITLE
[Site Request]ReadOnePiece

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#2381]
**Name of the website**
readonepiece.com

**Website urls (examples below)**
- Site: https://ww7.readonepiece.com/
-Manga List: https://ww7.readonepiece.com/manga/one-piece/
- Manga example: https://ww7.readonepiece.com/manga/one-piece-digital-colored-comics/
- Chapter online viewer example: https://ww7.readonepiece.com/chapter/one-piece-chapter-988/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
The framework to use for this website is for a former website manga cruzers. This one does not work anymore.

**Comment by Sheepux** [comment]
Rejection Policy match : single manga site.
Requesting second review before rejecting.

**Comment by XenonR** [comment]
Rejection confirmed.
Please note that due to the shear amount of websites the team will not integrate websites with just one manga. Nevertheless we accept pull requests for such sites.
Thanks for you understanding.

**Comment by 27136773** [comment]
Website is already supported as part of `MangaCruzers`
