### ISSUE TITLE
[WutopiaComics] Connector not working

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#2383]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I have unlocked manga on my account but the app is still only downloading the first pages for the unlocked chapters.

**Comment by newaccforhc** [comment]
Few checks:
- [ ] Have you used Manual Website Interaction to Login into your account?
- [ ] If yes then press F12 and check console for any errors while downloading..

If there are any error then screenshot it and upload the screenshot here...

Ref: Manual Website Interaction - https://hakuneko.download/docs/manual-website-interaction/

**Comment by amit34521** [comment]
Logged in to my account with manual web interaction.

No errors during the download. its just returning only one page in the response.

**Comment by newaccforhc** [comment]
okay.. Then they must be serving images differently for paid chapters.. Maybe someone will look into it in the future.. But, one thing is clear... Whoever decides to add it needs an account having paid chapters..

**Comment by amit34521** [comment]
<img src="https://www.funmanga.com/uploads/chapter_files/14909/221/02.jpg"/>

Refer to this code in image. i am using the same code to read the licensed chapters.

**Comment by newaccforhc** [comment]
okay.. Thanks... I'll create an account..

**Comment by newaccforhc** [comment]
Redemption code is expired

**Comment by amit34521** [comment]
let me know some other way to contact. i will share mine for now

**Comment by newaccforhc** [comment]
Join discord.. All developers are active there..

**Comment by newaccforhc** [comment]
You can find discord link here: https://hakuneko.download/

**Comment by amit34521** [comment]
joined. whom should i contact there?

**Comment by newaccforhc** [comment]
Just drop a message in #help.. I'll respond

**Comment by newaccforhc** [comment]
Don't send account in the message..
