### ISSUE TITLE
[9anime] Connector not working

### ISSUE THREAD

**Issue by Whore-Hay** [manga-download/hakuneko#2393]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
so no matter what anime i choose from 9anime it always says 0/0 chapters and shows nothing

**To Reproduce**
1. 9anime
2. any anime on 9anime not showing
3. any anime on 9anime
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![Screenshot 2020-09-28 231902](https://user-images.githubusercontent.com/72058932/94520547-50cfd800-01e1-11eb-8e89-032767c7a092.png)
![Screenshot 2020-09-28 231954](https://user-images.githubusercontent.com/72058932/94520557-53323200-01e1-11eb-891f-ef48eda87b71.png)
![Screenshot 2020-09-28 232017](https://user-images.githubusercontent.com/72058932/94520562-54fbf580-01e1-11eb-943c-22b6cd402ce9.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
Looks to me like they messed up their website, i cannot see any episodes or play video with Chrome browser
