### ISSUE TITLE
[Futabanet] Connector not working

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#2394]
**Name of the website**
Gaugau Monster

**Website urls (examples below)**
- Site: https://gaugau.futabanet.jp/
- Manga List: https://gaugau.futabanet.jp/list/works
- Manga example:
https://gaugau.futabanet.jp/list/work/5dce85b27765612448020000
https://gaugau.futabanet.jp/list/work/5dce85b27765612448020000/episodes
- Chapter online viewer example: https://gaugau.futabanet.jp/common/dld/zip/0ccd44e4c5fbdd2401ab086b90934dc5/

**Languages**
Japanese

**Additional details**
Seems to use the same system as GammaPlus.

**Comment by newaccforhc** [comment]
I have the fix ready, I'll push it when I can access my laptop... It is broken and in the service shop rn..
