### ISSUE TITLE
Bulu Manga Connector not working

### ISSUE THREAD

**Issue by awangbaqy** [manga-download/hakuneko#2398]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Bulu Manga change its website link.

**To Reproduce**
1. Bulu Manga under name of MangaHay

4. 
![image](https://user-images.githubusercontent.com/37800718/94820138-4eac8a00-042a-11eb-9689-9ad5e1df963d.png)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Then, what is the new url ?

**Comment by awangbaqy** [comment]
https://ww3.bulumanga.net
