### ISSUE TITLE
[Bug] Discord link not working

### ISSUE THREAD

**Issue by BrownIndianGuy** [manga-download/hakuneko#2400]
THE DISCORD LINK IS NOT WORKING. PLEASE UPDATE IT.

**Comment by Sheepux** [comment]
Do not write in capslock, it's rude.
Seems to be ok here. What error message do you get ? (send a screenshot)

**Comment by Sheepux** [comment]
Will close unless more info is given

**Comment by newaccforhc** [comment]
Here use this link if the given one is not working for you (just created a new one).. 😂

https://discord.gg/kHFMZPt

**Comment by 27136773** [comment]
> Will close unless more info is given

=> closed
