### ISSUE TITLE
[Site Request] Rocaca

### ISSUE THREAD

**Issue by jesichakirkland** [manga-download/hakuneko#2402]
**Name of the website**
Rocaca

**Website urls (examples below)**
- Site: http://www.rocaca.com/
- Manga List: http://www.rocaca.com/directory/
- Manga example: http://www.rocaca.com/manga/dalkomhan_namja/
- Chapter online viewer example: http://www.rocaca.com/manga/dalkomhan_namja/mf/c001/2/

**Languages**
English

**Additional details**
This web is bugging. First page of each chapter not showing up

**Comment by MikeZeDev** [comment]
Website changed to mangago and mangago is supported.

@Sheepux please :)
