### ISSUE TITLE
[Site Request] Manga Rawr

### ISSUE THREAD

**Issue by Badass-Nemesis** [manga-download/hakuneko#2405]
**Name of the website**
Manga Rawr

**Website urls (examples below)**
- Site: https://mangarawr.com/
- Manga List: https://mangarawr.com/
- Manga example: https://mangarawr.com/manga/kanojo-okarishimasu/
- Chapter online viewer example: https://mangarawr.com/manga/kanojo-okarishimasu/chapter-158/

**Languages**
List of languages supported by the website - English

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").---------------- I don't think so, maybe.

**Additional details**
Add any other context details that you may have found (like template to reuse)-----------------------Sorry, I don't know about that.
![image](https://user-images.githubusercontent.com/71874901/95172299-bf5df880-07d4-11eb-85da-c3df43eddf27.png)
-------------This is the logo of that website.

**Comment by Badass-Nemesis** [comment]
please add support to https://mangarawr.com/ site
The quality of images in this site is awesome and I don't think it uploads fan-translation like what https://w11.mangafreak.net/ does all the time.
Please add the support for the Mangarawr site.
I tried to download 'Rent a Girlfriend' manga from many sites, from HakuNeko. But either the quality was not good, or it was a fan-translation. Then I found Mangarawr site. I can download the images using any image downloader, but If there is any chance that HakuNeko would support Mangarawr site for download, then I'd be very happy.
Also, I've tried many manga downloaders before, but HakuNeko is the best one.
Thank you for the app.

**Comment by manh21** [comment]
**Template**: Wordpress Madara
