### ISSUE TITLE
[Bug] Pop-up Box at random intervals. Box Content [Manga Title, Download Site]

### ISSUE THREAD

**Issue by RedwanRabbiHoque** [manga-download/hakuneko#2406]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I keep having the issue of something popping on the top corner of my screen for a fraction of a second and then vanishing. It happens randomly when  Hakuneko App is open. I tried recording then taking Screenshot of every frame to even see what did the little cancer box had written on it. 

As you can see from the image it saying "By Myself Mangadex", now I had this webtoon bookmarked in Hakuneko then removed it after I saw what the box had in it. Regardless it keeps on happening, not sure if it is the name of another manga I have bookmarked or not, or is it the same (By Myself).

**Expected behavior**

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/48180076/95197473-7a998800-07fb-11eb-98a6-4d76dd9bc80d.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**
I thought it was something to do with some faulty software I installed, then realized it only happens with Hakuneko on. The random pop-up just diving me crazy

**Comment by Sheepux** [comment]
Can you test the nightly to see if you still have the issue ?

**Comment by RedwanRabbiHoque** [comment]
> Can you test the nightly to see if you still have the issue ?

Will try it out. @Sheepux

**Comment by RedwanRabbiHoque** [comment]
So far haven't faced this issue on the "Nightly" version. Will wait out till tomorrow if I don't get any I will close the comment.

**Comment by 27136773** [comment]
Looks to me like a tooltip from the manga list.
Probably an issue with electron itself...

**Comment by RedwanRabbiHoque** [comment]
@ronny1982 
electron itself? what do you mean?
