### ISSUE TITLE
[wakamics] Connector not working

### ISSUE THREAD

**Issue by designateport** [manga-download/hakuneko#2408]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the connector fails to update list

**To Reproduce**
1. wakamics/manga3s
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Connector.mjs:221 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\admin\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.wakamics'
 Failed to load response data
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by manh21** [comment]
`hakuneko.mangas.wakamics` Is it exist inside `C:\Users\admin\AppData\Roaming\hakuneko-desktop\`?

**Comment by designateport** [comment]
nevermind, sorry for the complain; wakamics is now back. still thanks for reading
