### ISSUE TITLE
[Bato.to] Connector not working

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#2413]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update manga list
Copy link doesn't work

**To Reproduce**
1. Bato.to

2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![bato](https://user-images.githubusercontent.com/70113965/95476885-09d3a680-0988-11eb-8c2c-14db48bb6646.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by XateAorora** [comment]
I have the same exact issue and errors. Website works fine for all series I'm reading.
