### ISSUE TITLE
[Manganelo] Clipboard not working

### ISSUE THREAD

**Issue by korason7117** [manga-download/hakuneko#2415]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
- This manga in Mangakakalot.com: https://mangakakalot.com/read-of5ex158504840587
works fine as mentioned below
- The same manga in Manganelo.com: https://manganelo.com/manga/jf921342
Issues when pasting Link

- In Manganelo.com
Pasting doesn't load the manga tittle it appears as if I wasn't pasting a Link. 
Selecting the connector and loading manga list seems to be necessary to access any manga as everything from there  works fine
"Reader, viewing chapters list, and downloading"

- In Mangakakalot.com 
things happens as expected and everything works fine from pasting a link, loading the manga list, loading chapter list, and downloading chapters

- Differences
same manga in both websites can be read with "Reader" "Load Manga List" and "View/download Chaptes"
Clipboard  works fine in Mangakakalot but it doesn't in Manganelo

**To Reproduce**
1. Manganelo
2. On probably every manga hosted on Manganelo.com
3. in Manganelo loading the chapter list works fine as long as the Manga List is loaded first
4. CLIPBOARD: https://manganelo.com/manga/read_one_piece_manga_online_free4 Error: To many matching connectors found for URL https://manganelo.com/manga/read_one_piece_manga_online_free4
    at ClipboardConnector.mjs:62
    at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28)
    at HTMLElement.onUpdateMangaListClick (mangas.html:233)
    at HTMLElement.onPasteClick (mangas.html:339)
    at HTMLElement.handler (template-stamp.html:96)

**HakuNeko (please complete the following information):**
 - Version [6.1.7] [0d5665]
Got Hakuneko from the AUR

**Comment by Sheepux** [comment]
Dev note:
URL https://manganelo.com/manga/jf921342 matches KissMangaWebsite, MangaNeloInfo connectors because they extend MangaNel without invalidating the canHandleURI

Fixed by adding dedicated clipboard support for KissManga (even though it's dead) & MangaNeloInfo
