### ISSUE TITLE
[Site Request] TreDrage 

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2422]
Name of the website
TreDrage 

•	Site:  https://tredragefansub0.blogspot.com
•	Manga List:  -
•	Manga example:  https://tredragefansub0.blogspot.com/search/label/Satou-kun%20Ni%20Wa%20Kanawanai?&max-results=9
•	Chapter online viewer example: https://tredragefansub0.blogspot.com/2020/09/satou-kun-ni-wa-kanawanai-one-shot.html

Language: Turkish

**Comment by kaikai-chan** [comment]
Hi, this site is closed. Can you closed this topic? I want opened new site again.
