### ISSUE TITLE
[Site Request] Manga Şehri

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2426]
Name of the website:
Manga Şehri

•	Site:  https://mangasehri.com
•	Manga List: https://mangasehri.com/manga/
•	Manga example:  https://mangasehri.com/manga/the-sacred-ruins/
•	Chapter online viewer example:  https://mangasehri.com/manga/the-sacred-ruins/bolum-1/

Language: Turkish

**Comment by Sheepux** [comment]
Fixed by #2440
