### ISSUE TITLE
kuaikanmanhua

### ISSUE THREAD

**Issue by taitin916** [manga-download/hakuneko#2429]
**Name of the website**
kuaikanmanhua

**Website urls**
- Site: https://www.kuaikanmanhua.com/
- Manga List: https://www.kuaikanmanhua.com/tag/0
- Manga example: https://www.kuaikanmanhua.com/web/topic/4319/
- Chapter online viewer example: https://www.kuaikanmanhua.com/web/comic/185037/

**Languages**
simplified chinese

**Comment by 27136773** [comment]
Check before making a request...

![image](https://user-images.githubusercontent.com/27136773/95869564-cdc78980-0d6b-11eb-9edc-26a87527e268.png)
