### ISSUE TITLE
[Site Request] Manatoki

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#2430]
**Name of the website**
Manatoki

**Website urls (examples below)**
- Site: https://manatoki81.net/
- Manga List: https://manatoki81.net/comic
- Manga example: https://manatoki81.net/comic/5700381?publish=%EB%8B%A8%ED%8E%B8
- Chapter online viewer example: https://manatoki81.net/comic/5700388?publish=%EB%8B%A8%ED%8E%B8&spage=1

**Languages**
Korean

**Website relationship*
Maybe related to NewToki and Manamoa
**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Probably `GnuBoard5BootstrapBasic2` template such as https://tkor.kim
