### ISSUE TITLE
[Site Request] pururin.io

### ISSUE THREAD

**Issue by Buho28** [manga-download/hakuneko#2432]
**Name of the website**
pururin.io

**Website urls (examples below)**
- Site: https://pururin.io/
- Manga List: https://pururin.io/browse/tags/collection/21282/nine-to-five-lover.html
- Manga example: https://pururin.io/gallery/50658/nine-to-five-lover-1-3
- Chapter online viewer example: https://pururin.io/read/50658/04/9-ji-kara-5-ji-made-no-koibito-1-3-wa-soushuuhen-nine-to-five-lover

**Languages**
List of languages supported by the website

- English
- Spanish
- German

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website url is pururin.to btw.
