### ISSUE TITLE
[Toonily] Connector not working

### ISSUE THREAD

**Issue by marlozr3360** [manga-download/hakuneko#2435]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
None of the chapters show up for any of the titles.

**To Reproduce**
1. Toonily
2. All titles
3. All chapters

**Screenshots**
![SS](https://user-images.githubusercontent.com/72880517/96038168-5f96cb80-0e2c-11eb-955c-96161a9e1f6e.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dodieboy** [comment]
Tried adding cookie 'wpmanga-adault=1' but dont work :(

hakuneko not getting class 'site-content'
![image](https://user-images.githubusercontent.com/9015764/96247194-606e5f80-0fdc-11eb-89bd-807006790eb1.png)

**Comment by Robonau** [comment]
> Tried adding cookie 'wpmanga-adault=1' but dont work :(
> 
> hakuneko not getting class 'site-content'
> ![image](https://user-images.githubusercontent.com/9015764/96247194-606e5f80-0fdc-11eb-89bd-807006790eb1.png)

kind of a correction, it gets it, it just deletes it when doing :
this.createDOM( data );
