### ISSUE TITLE
[Feature] Improve connector loading and organization during startup

### ISSUE THREAD

**Issue by B13rg** [manga-download/hakuneko#2438]
**Is your feature request related to a problem? Please describe.**
When the program is first started up, it loads every single connector as part of initializing the connectors.  This creates some slowness to the first page load.

**Describe the solution you'd like**
My preferred solution would be to have a `Favorites` list of connectors, similar to how a list of bookmarked mangas can be kept.  On startup, the connectors that are on the favorites list are fully loaded, while the rest are partially loaded.  Non-favorite connectors would be loaded enough to display the connector on the connector list, but not load the entire template for the connector.  

This would firstly help keep the list of connectors more organized.  I assume users mostly use a small number of connectors from the large pool of available ones most of the time.  Users would no longer need to scroll through a long list of connectors they're not using to find the one they want.

This would also improve startup time, since every single connector wouldn't need to be loaded all at once.

**Describe alternatives you've considered**
A lesser solution to the preferred would be to lazy-load all the connectors instead of loading of them at the beginning.  Like above, loading a connector would only load the description/metainfo about the connector.  When an manga or new connector is selected, then it would check if a connector was fully loaded, then finish loading it if it wasn't.  

While this would work, having a list of favorite connectors makes it easier to find/organize the connectors used regularly.

**Context (please complete the following information):**
 - HakuNeko rev. 6.1.7@0d5665

**Additional context**
Connector loading takes place here: https://github.com/manga-download/hakuneko/blob/bef0c925b419ff187b18ad2998380fa98b80a5f6/src/web/mjs/engine/Connectors.mjs#L19
The majority of the time is spent in the register function, importing the connector files: https://github.com/manga-download/hakuneko/blob/bef0c925b419ff187b18ad2998380fa98b80a5f6/src/web/mjs/engine/Connectors.mjs#L41

**Comment by 27136773** [comment]
Too much effort.
The problem is addressed in HakuNeko NW by bundling all files and using SVG/Image Sprites
