### ISSUE TITLE
[Site Request] trakteer.id

### ISSUE THREAD

**Issue by damazh** [manga-download/hakuneko#2441]
**Name of the website**
trakteer.id

**Website urls (examples below)**
- Site: https://trakteer.id/
- Manga List: https://trakteer.id/explore/comics-and-cartoons
- Manga example: https://trakteer.id/megyuumi22227590/showcase?category=daddy-sugar-baby-innocence
- Chapter online viewer example: https://trakteer.id/megyuumi22227590/showcase/my-unknown-husband-episode-3-gqdtY

**Languages**
Indonesian

**Website relationship*
Maybe alternative domain or copy of Webtoon.

**Additional details**
-

**Comment by MikeZeDev** [comment]
Need Hcaptcha to solve...

**Comment by MikeZeDev** [comment]
https://trakteer.id/explore/comics-and-cartoons is not a manga list, its a person list.

**Comment by MikeZeDev** [comment]
Improper website structure
