### ISSUE TITLE
[Site Request] JPMANGAS

### ISSUE THREAD

**Issue by snohboy** [manga-download/hakuneko#2453]
**Name of the website**
JPMANGAS

**Website urls (examples below)**
- Site: https://www.jpmangas.com/
- Manga List: https://www.jpmangas.com/lecture-en-ligne-list
- Manga example: https://www.jpmangas.com/lecture-en-ligne/samura-comeback
- Chapter online viewer example: https://www.jpmangas.com/lecture-en-ligne/samura-comeback/4.4/10

**Languages**
french

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: MangaReaderCMS

**Comment by snohboy** [comment]
Thanks you
