### ISSUE TITLE
[Site Request] Comic Trail

### ISSUE THREAD

**Issue by pazergithub** [manga-download/hakuneko#2465]
Comic Trail (コミックトレイル)

- Site: https://comic-trail.jp/
- Manga List: https://comic-trail.jp/series
- Manga example: https://comic-trail.jp/series/ishesan
- Chapter online viewer example: https://comic-trail.jp/pt/ishesan_00001/

Language: JP

This should use the SpeedBinb template.

**Comment by 27136773** [comment]
Template: SpeedBinb
