### ISSUE TITLE
MangaRock - Can't download a specific chapter

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#247]
> **From:** HakuNeko User

Hi guys, :)

I've been trying for a week to download "yuragi sou no yuuna" chapter 165 on Mangarock without sucess (Error: Mangarock error: 108).

Every other chapters are downloading without issues and my problem is only for that specific chapter. All the other mangas are downloading with no issues as well.

Any ideas ?

Thank you, 
Best regards

**Comment by Tmp341** [comment]
Have you checked #184 ?

Edit ~~nvm.~~ Or actually do. :)

**Comment by 27136773** [comment]
It seems the chapter is available from the [website](https://mangarock.com/manga/mrs-serie-283326/chapter/mrs-chapter-200077713), but not through the [API (marked as removed)](https://api.mangarockhd.com/query/web401/pages?country=&oid=mrs-chapter-200077713).

Further investigation required.

**Comment by 27136773** [comment]
This will be fixed in the next version of HakuNeko but not in 0.4.0
