### ISSUE TITLE
[Newtoki] Connector not working

### ISSUE THREAD

**Issue by buratsy** [manga-download/hakuneko#2475]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When trying to download from newtoki##.com (newtoki82.com at the moment), no files are actually downloaded. The connector works and the chapter list gets fetched. When downloading, it creates the title folder and the chapter folders but they're empty. No errors appear even after finishing.

**To Reproduce**
1. Newtoki
2. 오늘도 해맑음
3. All chapters
4. No relevant error messages

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by GuPuSi7ff** [comment]
Issue was caused by an outdated domain.
Using this one works fine now:
https://newtoki469.net/
