### ISSUE TITLE
[Feature Request] Download all new manga in bookmarks

### ISSUE THREAD

**Issue by kokizzu** [manga-download/hakuneko#2483]
So, I have a lot of manga, took me a lot of time to click, wait for right side to load, click download all (repeat for all manga)
it would be nice if there's a feature that can do those things automatically.

probably the UI would be something like this
```
[ start/stop ] [ pause ]
[============ checking progress: 423/564 =====                  ]
```

**Comment by 27136773** [comment]
Notifications for new chapters of bookmarked mangas was already proposed in #653
Automatic download of all new chapters in bookmarks was rejected, because it is against HakuNeko's philosophy (on-demand consumption instead of aggregation/leeching)
