### ISSUE TITLE
[Site Request] Çizgi Roman Arşivi

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2485]
Name of the website:
Çizgi Roman Arşivi

•	Site:  https://cizgiromanarsivi.com
•	Manga List:  https://cizgiromanarsivi.com/seri/
•	Manga example:  https://cizgiromanarsivi.com/seri/huzunlu-canlilar/
•	Chapter online viewer example: https://cizgiromanarsivi.com/seri/huzunlu-canlilar/1-bolum-final/

Language: Turkish

**Comment by Robonau** [comment]
template:Madara
