### ISSUE TITLE
Leviatanscans mangalist is empty

### ISSUE THREAD

**Issue by giaez** [manga-download/hakuneko#249]
the link to mangalist changed after the site revamped. example case for Chronicles of Heavenly Demon:
old link: https://leviatanscans.com/manga/chronicles-of-heavenly-demon
new link: https://leviatanscans.com/comics/chronicles-of-heavenly-demon

error log:
leviatanscans.com/manga/chronicles-of-heavenly-demon/ Failed to load resource: the server responded with a status of 404 ()
leviatanscans.html:54 Error: Failed to receive content from "https://leviatanscans.com/manga/chronicles-of-heavenly-demon/" (status: 404) - 
    at fetch.then.response (connector.html:441)

**Comment by 27136773** [comment]
1. Make sure you have the latest auto-update.
2. Synchronize the manga list to get the new links.
3. If you have favorites from this website, remove the favorites and re-add them again.

![image](https://user-images.githubusercontent.com/27136773/60757913-0dec7800-a011-11e9-8ea8-1fcf76033a30.png)

**Comment by 27136773** [comment]
No further response => closed
