### ISSUE TITLE
[Batoto] Connector not working

### ISSUE THREAD

**Issue by buratsy** [manga-download/hakuneko#2493]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Unable to add mangas from bato.to

**To Reproduce**
1. bato.to
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. The only errors are: 
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load bookmarks: Invalid bookmark list!
ClipboardConnector.mjs:66 CLIPBOARD: https://bato.to/series/79241 TypeError: Cannot read property 'querySelector' of undefined
    at Batoto._getMangaFromURI (AnyACG.mjs:35)

**Screenshots**
![image](https://user-images.githubusercontent.com/73280892/97086629-14b05b80-1657-11eb-9d3c-77c30f1dd41a.png)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
Very likely a duplicate of #2413

**Comment by buratsy** [comment]
I'm trying to copy this: https://github.com/manga-download/hakuneko/blob/2eeac01f728dd16ff9c4798b9ccc072d1b692ad0/src/web/mjs/connectors/Batoto.mjs

But it says "Changes to this file were not save to file system" when I try to save it (using CTRL+S).

**Comment by buratsy** [comment]
> Very likely a duplicate of #2413

I'm trying to copy this: https://github.com/manga-download/hakuneko/blob/2eeac01f728dd16ff9c4798b9ccc072d1b692ad0/src/web/mjs/connectors/Batoto.mjs

But it says "Changes to this file were not saved to file system" when I try to save it (using CTRL+S). The Uncaught SyntaxError is still there too. Upon checking AnyACG.mjs, the Uncaught SyntaxError is also there.

Edit: Apparently, making any changes to the code triggers the error. Still, I can't seem to save the fixed Batoto.mjs and whenever I restart Hakuneko, it reverts back to the wrong code.

**Comment by 27136773** [comment]
Use Nightly Build or wait for changes to be merged into 6.1.7 Stable, modifying your application without the corresponding knowledge won't do any good and will probably cause trouble...

**Comment by buratsy** [comment]
I agree, I'm probably making it worse. So I should just wait for the next update, then?
