### ISSUE TITLE
[Bato.to] Connector not working

### ISSUE THREAD

**Issue by Neyesha** [manga-download/hakuneko#2502]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
1. When using manga link from clipboard, _getMangaFromURI, fails - the query for selecting manga title is wrong. Getting the manga list and proceeding from there works.
2. The uri for pictures got changed. In reader there only blank pages are visible. What gets downloaded is .bin file.

**To Reproduce**
1. Bato.to
2. Doctor Elise: The Royal Lady with the Lamp
3. Chapter 1
4. .bin contains error 404 Not Found (1)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version current master

**Comment by 27136773** [comment]
Very likely a duplicate of #2413

**Comment by Neyesha** [comment]
partially true
the first part is not working
the field queryMangaTitle should be updated
should the images be in .webp format?

**Comment by Robonau** [comment]
it's a duplicate of #2493 and was already fixed, use the nightly 
(i can view that chapter of that manga) [proof pic](https://i.imgur.com/k9ehqF1.png)

**Comment by ANETAIII** [comment]
I don't have Bato.to in my source what have I do? Sorry for the trouble
