### ISSUE TITLE
[Site Request] mangaproz

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#2503]
**Name of the website**
 mangaproz.com

**Website urls (examples below)**
- Site: https://mangaproz.com/
- Manga List: https://mangaproz.com/manga
- Manga example: https://mangaproz.com/manga/infinite-apostles-and-twelve-war-girls/
- Chapter online viewer example: https://mangaproz.com/infinostles-51/

**Languages**
arabic

**Comment by 27136773** [comment]
Template: WordPressMangastream

**Comment by 27136773** [comment]
See: #2427
Please search if issue already exist before create a new one
