### ISSUE TITLE
[NewToki] Connector not working

### ISSUE THREAD

**Issue by vinh2201** [manga-download/hakuneko#2506]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The image of the chapter of mangas is not shown after clicking the chapter and wait for more than 5 minutes.

**To Reproduce**
1. NewToki
2. 인어를 위한 수영교실
3. 인어를 위한 수영교실 75화
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://user-images.githubusercontent.com/63141930/97106731-eb92d800-16f5-11eb-898c-00be1bb2a320.png)
![image](https://user-images.githubusercontent.com/63141930/97106739-f3527c80-16f5-11eb-9193-aea585ddc9bf.png)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version: v8.3.4 (nightly-20200705.1)

**Comment by Robonau** [comment]
dupe of #2475
resolved by #2528

**Comment by 27136773** [comment]
Reopened => it is not yet resolved, PR is still open

**Comment by 27136773** [comment]
See: #2475
