### ISSUE TITLE
Not sure if it's an issue need understanding about connector login function and cookies

### ISSUE THREAD

**Issue by doppler56** [manga-download/hakuneko#2508]
Using mangadex as the connector and nightly master.  I understand about using the login feature to get content on a connector.  I use it to get a member restricted manga on mangadex.  Works just fine.

What I don't understand is: While I am logged in to mangadex, downloading chapters will mark the chapter as read on mangadex "nice feature, saves me the trouble of marking them".  If I shutdown Hakuneko and start again later, chapters can still be marked as read when downloaded.  This happens sometimes, more often not.  Using the login feature still shows me as logged into mangadex (re: not a guest).  I can shutdown for the day and next day start up.  The chapters would still be marking as read, but then again more often not.

Work-around:  I can logout and login.  Chapters will start marking as read for a time.

Please clarify:
Is the login feature of Hakuneko, session based/timeout based/time based ?  Or did I come across an unintended bug ?
Maybe this feature is not a function of Hakuneko, just a consequence of login. 
Or do I need to clarify, (not getting my point across to you).
Thanks ahead of time.  Hope I am not being a bother.

**Comment by newaccforhc** [comment]
Try using remember me (1 year) option while logging into MangaDex..
The logins in HakuNeko are stored as cookies (afaik) just like chrome browser...


PS: honestly, I haven't tried logging in option with MangaDex.

**Comment by doppler56** [comment]
@newaccforhc Exact what I thought, I did set the 1 year flag checkbox.  I am not doing anything to reset cookies in or out of Hakuneko.  Yet my Firefox browser shows the read flag (eyeballs) are not set after a time.  It would be nice to know where the cookie is being kept in haku,  I could monitor for changes.  I hope it's not in my default browser.
Frustrating to say the least.

BTW, newaccforhc there is one manga on Mangadex which requires login (yakuza reincarnation).  There could be others.

**Comment by newaccforhc** [comment]
Oh... Only @ronny1982 can help with such cookie issues and all...
Also, I didn't know that there are member only mangas on MangaDex.. I'll check it out..

**Comment by 27136773** [comment]
HakuNeko does nothing related to cookie behavior, cookie handling is fully managed by the Chrome instance bundled with https://github.com/electron/electron.

You can check cookies by opening the website from within HakuNeko, then open developer tools with F12 and switching to the application tab.

![image](https://user-images.githubusercontent.com/27136773/97175565-fef48080-1793-11eb-91df-7e0ab1e28685.png)

**Comment by 27136773** [comment]
It is probably a design flaw on MangaDex that they mark chapters as read when they are requested via the JSON API.
I would expect that chapters are only marked as read if they are opened from within the website...

**Comment by doppler56** [comment]
@ronny1982 I checked the cookie stale date it is 1 year out.  I also noticed my status with haku was guest (logged out), wasn't me who logged out.
You are likely 100% correct about being logged in and using the JSON API to read the chapter.  It becomes marked.  Until I get a better reason why, my login status changes.  I will close this thread.
Thanks for the help and insight.
