### ISSUE TITLE
[Site Request] 117漫画网 (bx117)

### ISSUE THREAD

**Issue by vinh2201** [manga-download/hakuneko#2509]
**Name of the website**
117漫画网 (bx117)

**Website urls (examples below)**
- Site: http://www.bx117.com
- Manga List: http://www.bx117.com/all/
- Manga example: http://www.bx117.com/gufeng/yuanlaishihuananchenga/
- Chapter online viewer example: http://www.bx117.com/gufeng/yuanlaishihuananchenga/803726.html

**Languages**
Chinese

**Additional details**
Looks like this website use the same template as 6mh7 (http://www.6mh7.com), 友绘漫画网 (seeym) (http://www.seeym.net), but it does not seem that these websites are currently listed in connectors in Hakuneko.

**Comment by Robonau** [comment]
too many dead manga for it to be worth implementing, same with http://www.seeym.net
http://www.6mh7.com will be added by #2505 tho

**Comment by vinh2201** [comment]
> 
> 
> too many dead manga for it to be worth implementing, same with http://www.seeym.net
> http://www.6mh7.com will be added by #2505 tho

I realized that the dead mangas work on mobile link: https://m.bx117.com.

**Comment by Robonau** [comment]
403 error

**Comment by vinh2201** [comment]
> 
> 
> 403 error

Oh sorry, I forgot to change the hyperlink to http. The working link is: http://m.bx117.com
