### ISSUE TITLE
[https://www.webtoons.com/en/action/the-god-of-high-school/list?title_no=66&page=15] webtoons english

### ISSUE THREAD

**Issue by MohammadNsearaty** [manga-download/hakuneko#2512]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
Connector already exists
