### ISSUE TITLE
[Lezhin] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#2517]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No chapters shown when select a title.

**To Reproduce**
1. Lezhin (english)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="1122" alt="Screen Shot 2020-10-26 at 10 22 53 PM" src="https://user-images.githubusercontent.com/70831806/97249284-ee66f900-17d9-11eb-9e55-c6d66c40599d.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Robonau** [comment]
you have to sign in and enable adult content to see adult content

**Comment by Robonau** [comment]
works fine [pic](https://i.imgur.com/OSbjDE3.png)

**Comment by adsl3f** [comment]
i can confirm the issue, it happens with non adult too. if you sign in using the hakuneko settings, the chap list wont load but if you removed the account from there and signed in through browser, it works, but you cant download any paid chapter

https://prnt.sc/v7xoh5

**Comment by Robonau** [comment]
if you sign in using [manual website interaction](https://hakuneko.download/docs/manual-website-interaction/) you should be able to see and download all the chapters you have access to (you have to enable adult to see adult content), i can't test the paid content as i don't own any paid content on Lezhin,

note: HN will not let you download content you don't have access to.(this is intended)

**Comment by Robonau** [comment]
if there is a difference between how Lezhin displays paid vs non paid content then there might be an issue, but only a dev with paid content available will be able to fix.

**Comment by Robonau** [comment]
@ronny1982 , you were the one to fix paid content to begin with, so i assume you have access to some

**Comment by Adenaro85** [comment]
Hello,
I have the same issue, I can't dowload anything from the site.
Yes, I am logged in, everywhere, adult is on, and yes, I bought the content, in the past I managed to download it already, but now the chapter list is completely empty. Actually it is empty for everything. I am playing with it for days now without any success. Could you please help me to find out what's wrong?

![image](https://user-images.githubusercontent.com/73607153/97472763-1b362000-1942-11eb-8a0a-ae715b07950c.png)

**Comment by newaccforhc** [comment]
@Adenaro85 Wait till it's fixed..

**Comment by adsl3f** [comment]
is there any updates regarding this issue?

**Comment by 27136773** [comment]
It is done when it is done, this can be sometime between tomorrow and never.
Currently none of the contributors is working on this (to the best of my knowledge).
If you want to push things forward there is no other option than trying to fix it yourself.

**Comment by jstefansson6** [comment]
wait..it's still not working for me/same problem as before. Is it just me?
