### ISSUE TITLE
Website Request: mag-garden

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#252]
> **From:** AthK

https://comic.mag-garden.co.jp/
http://kansai.mag-garden.co.jp/

Pretty simple to download images because they are sequencially placed.

For example: 
For Chapter
https://comic.mag-garden.co.jp/assets/files/fumisan190630/HTML5/pc.html

Images are located as below

Page1: 
https://comic.mag-garden.co.jp/assets/files/fumisan190630/books/images/2/1.jpg
Page2 : 
https://comic.mag-garden.co.jp/assets/files/fumisan190630/books/images/2/2.jpg
Page3 : 
https://comic.mag-garden.co.jp/assets/files/fumisan190630/books/images/2/3.jpg

And so on...

**Comment by 27136773** [comment]
Both websites are using WordPress (though templates seems to be different).
Both websites are using ActiBook reader.

Image links can be extracted by injecting the following script into the [page](http://kansai.mag-garden.co.jp/assets/files/ee1/HTML5/pc.html#/page/1):
```javascript
[ ...( new Array( App.book.lastPage ) ).keys() ].map( page => new URL( `${App.book.hd.get( 'pieceDirectory' )}/${page + 1}.jpg`, window.location.href ).href );
```

**Comment by newaccforhc** [comment]
This issue is from me only.. haha
Well... comic.mag-garden.co.jp is now magcomi.. And, already supported... So, need to add support for http://kansai.mag-garden.co.jp/
