### ISSUE TITLE
[Source Request Arabic] <manga.ae>

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2520]
**Name of the website**
Manga.ae

**Website urls (examples below)**
- Site: https://www.manga.ae/
- Manga List: https://www.manga.ae/
- Manga example: https://manga.ae/nice-to-meet-you/
- Chapter online viewer example: https://manga.ae/nice-to-meet-you/24/0/full

**Languages**
ARABIC

**Comment by 27136773** [comment]
This is just an add-on domain of `MangaArab` which is already supported

**Comment by nottyd** [comment]
.
