### ISSUE TITLE
Disaster Scans

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#2529]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/Non.  yes

**Describe the bug**
A clear and concise description of what the bug is. For the last few days the connection has slowed down lot though the site itself works quickly. I tried updating the list with no effect

**To Reproduce**
1. Name of connector. Disaster Scans
2. Name of manga (if connector update is working) All
3. Name of chapter (if manga update is working) All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12). No error messages

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
HakuNeko has a mechanism to bypass the optimized images that are served on the website from a fast CDN and instead directly downloads the un-compressed images from the website's server, probably at the price of lower speed since the website's server is not fast enough.

**Comment by tsentered** [comment]
Thnx for the scoop.

**Comment by tsentered** [comment]
So that means they (Disaster)upped their game a few days ago?
