### ISSUE TITLE
[crunchyroll anime] Connector not working

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2535]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update manga list fot crunchyroll" anime.

**To Reproduce**
1. Crunchyroll anime
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![IMG_20201028_234257_893](https://user-images.githubusercontent.com/68442725/97504639-89e1a080-1977-11eb-96cb-1ad286ae33b8.jpg)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #2416 
Please search if there is already a ticket, before creating one
