### ISSUE TITLE
[Site Request Arabic] mangalink

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2538]
**Name of the website**
mangalink

**Website urls (examples below)**
- Site: https://www.mangalink.cc/
- Manga List: https://www.mangalink.cc/mangas
- Manga example: https://www.mangalink.cc/mangas/18-solo-leveling
- Chapter online viewer example: https://www.mangalink.cc/mangas/18-solo-leveling/chapter/101

**Languages**
arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
dupe of #1170
