### ISSUE TITLE
[Site Request arabic] 

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2539]
**Name of the website**
mangaproz

**Website urls (examples below)**
- Site: https://mangaproz.com/
- Manga List: https://mangaproz.com/manga/
- Manga example: https://mangaproz.com/manga/freaking-romance/
- Chapter online viewer example: https://mangaproz.com/freaking-romance-ch-34/

**Languages**
arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
duplicate of #2427
