### ISSUE TITLE
[Site Request arabic]  golden manga

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2540]
**Name of the website**
golden manga

**Website urls (examples below)**
- Site: https://golden-manga.com/
- Manga List: https://golden-manga.com/manga/
- Manga example: https://golden-manga.com/manga/the-world-is-money-and-power/
- Chapter online viewer example: https://golden-manga.com/manga/the-world-is-money-and-power/05/

**Languages**
arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
already in HN

**Comment by REDAKUN** [comment]
..

**Comment by nottyd** [comment]
..

**Comment by REDAKUN** [comment]
....

**Comment by issam253** [comment]
Hi
