### ISSUE TITLE
[Site Request Arabic] rewayatcafe

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2545]
**Name of the website**
Rewayatcafe

**Website urls (examples below)**
- Site: https://www.rewayatcafe.com/search/label/reverend-insanity?m=0
- Manga List: https://www.rewayatcafe.com/2020/10/chinese-novels.html?m=0
- Manga example: https://www.rewayatcafe.com/2020/10/chinese-novels.html?m=0
- Chapter online viewer example: https://www.rewayatcafe.com/2020/10/397_21.html?m=0

**Languages**
Arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
a site that hosts literal PDFs
also
site: https://www.rewayatcafe.com
Manga List : https://www.rewayatcafe.com/search/label/%D8%B1%D9%88%D8%A7%D9%8A%D8%A7%D8%AA%20%D8%B5%D9%8A%D9%86%D9%8A%D8%A9
Manga List : https://www.rewayatcafe.com/search/label/%D8%B1%D9%88%D8%A7%D9%8A%D8%A7%D8%AA%20%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9
Manga List : https://www.rewayatcafe.com/search/label/%D8%B1%D9%88%D8%A7%D9%8A%D8%A7%D8%AA%20%D9%8A%D8%A7%D8%A8%D8%A7%D9%86%D9%8A%D8%A9%20%D9%88%D9%83%D9%88%D8%B1%D9%8A%D8%A9
the three origin language lists are seperate

sometimes the chapter is just a download novel button https://www.rewayatcafe.com/2019/08/blog-post_8.html

too inconsistent to really work imo

**Comment by MikeZeDev** [comment]
Like robo said
