### ISSUE TITLE
[Site Request] MangaPill

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#2549]
**Name of the website**
Mangapill

**Website urls (examples below)**
- Site: https://mangapill.com/
- Manga List: https://mangapill.com/search
- Manga example: https://mangapill.com/manga/2/one-piece
- Chapter online viewer example: https://mangapill.com/chapters/2-10100000/one-piece-chapter-100

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
duplicate of #2411

**Comment by 27136773** [comment]
Please search if a ticket already exists before creating one.
