### ISSUE TITLE
[Site Request] 动漫之家DMZJ

### ISSUE THREAD

**Issue by NO-MEANINGS** [manga-download/hakuneko#2550]
**Name of the website**
动漫之家DMZJ

**Website urls (examples below)**
- Site: https://www.dmzj.com/
- Manga List: https://www.dmzj.com/category
- Manga example: https://www.dmzj.com/info/njsjm.html
- Chapter online viewer example: https://www.dmzj.com/view/beibingjiaomeimeiaidesiquhuolai/108820.html#@page=1

**Languages**
Chinese

**Website relationship*
this website has an alternative domain whose information is listed below. It seems that if you visiting the website's manga list using different domains, you would get different results. So i suggest you use two domain at same time, and return the results both of them. You can also treat them as two different websites. If you do so, i suggest you use the name "动漫之家（新版）" for www.dmzj.com and "动漫之家（旧版）" for manhua.dmzj.com
- Alternative domain: https://manhua.dmzj.com/
- Manga List: https://manhua.dmzj.com/tags/category_search/0-0-0-all-0-0-0-1.shtml#category_nav_anchor
- Manga example: https://manhua.dmzj.com/sxlhyaria/
- Chapter online viewer example: https://manhua.dmzj.com/bukejiedewodeyiqie/77189.shtml#@page=1

**Additional details**
Nothing to complement

**Comment by 27136773** [comment]
Template: probably `SinMH` for first website, `MH` for second website

**Comment by Robonau** [comment]
https://manhua.dmzj.com/ literally links to https://www.dmzj.com/ for some of its chapters, not worth adding
