### ISSUE TITLE
[Site Request] Migudm

### ISSUE THREAD

**Issue by vinh2201** [manga-download/hakuneko#2551]
**Name of the website**
Migudm

**Website urls (examples below)**
- Site: https://www.migudm.cn
- Manga List: https://www.migudm.cn/comic/list/
- Manga example: https://www.migudm.cn/comic/090000006097.html
- Chapter online viewer example: https://www.migudm.cn/090000006097/chapter/121.html

**Languages**
Chinese

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
template sinMH (i think)
