### ISSUE TITLE
[Bato.to] Connector not working

### ISSUE THREAD

**Issue by sakuyakudou10** [manga-download/hakuneko#2564]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connector's not working, the clipboard feature is also not working.

**To Reproduce**
1. Bato.to
2. All Manga (if connector update is working)
3. The console shows this error:

ClipboardConnector.mjs:66 
CLIPBOARD: https://bato.to/series/75522 TypeError: Cannot read property 'querySelector' of undefined
    at Batoto._getMangaFromURI (AnyACG.mjs:35)
    at async hakuneko:/cache/mjs/connectors/system/ClipboardConnector.mjs:64
    at async Promise.all (index 0)

**HakuNeko:**
 - Version nightly-20200705.1

**Comment by Robonau** [comment]
the connector itself seems to be working, Clipboard as you mentioned isn't working tho
![](https://i.imgur.com/HtQvrSx.png)
