### ISSUE TITLE
Manga Ay is missing chapters

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2567]
Hi, 
Manga Ay is working, but we have a problem. 
The series link.
https://manga-ay.com/seriler/0

![2020-11-02_224110_manga-ay com](https://user-images.githubusercontent.com/65365181/97912586-0d2b3980-1d5e-11eb-921d-dfca3165157a.png)

 Please look this picture. There are 100 mangas per page. Program sees only first page. So only sees 100 manga. Can you fix it?

**Comment by Robonau** [comment]
it only has 1 page for me (geolock thing probably) (i was the one who implemented it)

**Comment by Robonau** [comment]
i'm going to leave this to someone that can test what they are doing

**Comment by Robonau** [comment]
though it should be just a _getmanga and _getmangapages with the next page system

**Comment by newaccforhc** [comment]
Actually, this is some open source website template (mostly MangaCat) inspired from MangaDex.. Even RawDevart uses it.. So, I think it can be added as templates..

I'm not sure tho..

**Comment by newaccforhc** [comment]
Also, tried opening the site with Turkey VPN.. Still only 1 page.. So, my guess is that the number of pages increase after logging into an account..

**Comment by Robonau** [comment]
given its an open source theme it's probably a good idea to make a template
