### ISSUE TITLE
[Site Request] ScansMangas

### ISSUE THREAD

**Issue by Yunaxigf** [manga-download/hakuneko#2571]
**Name of the website**
ScansMangas

**Website urls (examples below)**
- Site: https://scansmangas.xyz/
- Manga List: 
- Manga example: https://scansmangas.xyz/manga/a-returners-magic-should-be-special/
- Chapter online viewer example: https://scansmangas.xyz/scan-a-returners-magic-should-be-special-1/

**Languages**
French

**Comment by manh21** [comment]
Template: WordpressMangaStream
