### ISSUE TITLE
[e hentai] Connector not working

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2574]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
E HENTAI Connector not working in hn
And the The copy&paste feature not working too

**To Reproduce**
1. E hentai
2. All
3.all
4. 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![IMG_20201104_044655_266](https://user-images.githubusercontent.com/68442725/98067153-354b9300-1e59-11eb-9681-7cf5f3b83d49.jpg)

![IMG_20201104_044652_949](https://user-images.githubusercontent.com/68442725/98067159-3b417400-1e59-11eb-89eb-8981c03fc9c3.jpg)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Robonau** [comment]
the manga list not being functional is intentional (probably due to the 22 thousand pages it would have to go through).
the copy paste feature is working as intended .
![](https://i.imgur.com/N3qAmLZ.png)

**Comment by 27136773** [comment]
Too many requests (e.g. caused by the preview) will lead to an IP ban which needs to be addressed in HakuNeko

**Comment by Robonau** [comment]
I mean the preview causing ip bans is something that needs to be addressed in general, as it's not something we have a solution for currently.

**Comment by 27136773** [comment]
Just for reference: dazedcat19/FMD2#160
