### ISSUE TITLE
[discussion] 'gb' vs 'en' multilingual connectors

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2576]
why is English 'gb' and not 'En' in the languages for multilingual connectors, even as an Englishman it being 'gb' confuses me
great Britain includes Wales and Scotland, both of which have their own languages.

**Comment by 27136773** [comment]
Language tags are extracted from the website. I have no idea why MangaDex uses `gb`

**Comment by Robonau** [comment]
MangaDex uses gb for the flag(it's the gb flag) (lang_name = English, lang_code = gb)
is it worth just replacing gb with en?
or just using lang_name and use the full language name

**Comment by 27136773** [comment]
https://mangadex.org/api/manga/56402

The MangaDex API return `gb` in the `lang_code` field.
Yes there is an additional field labeled `lang_name`, but HakuNeko uses the language code as the name may not be unique.

When going for a replace, all codes needs to be replaced, not just `gb`, therefore it might be better to just use the language name (which will probably lose country information, such as en-US or pt-BR).
However, when the language is changed, this may lead to inconsistency with downloaded chapter detection.

**Comment by Robonau** [comment]
lang_name doesn't lose country info, "br" is "Portuguese (br)" there is no country info in lang_code its literally the flag code

![](https://i.imgur.com/Ol0DIM0.png)

**Comment by Robonau** [comment]
in the current system there are other languages that make no sense "Spanish (LATAM)" = "mx" , yes its mexican spanish but it doesn't seem right. "es-MX" would be fine but just mx makes no sense
![](https://i.imgur.com/WpW1789.png)
note: there is no 'es' `lang_code`
another example of it being wrong for the language
![](https://i.imgur.com/aR75QfD.png)

i've gone through about 200+ different manga worth of chapters and these stand out as not right.
The `lang_code`  is always tied to the `lang_name` so if the `lang_code` is 'gb' then the `lang_name` will always be 'English'
if `lang_code` 'US' were to exist the `lang_name` would probably be 'English (US)' 

the only downside to the change is the change in HN chapter names, it would screw with ppl with already downloaded chapters

**Comment by 27136773** [comment]
The new json API only has a single field which is called `language` and contains guess what... yes the country code (total obvious for a field labeled language).

The only way right now to get the real language name is either by using the HTML instead of the json API or introduce a  table to map country code to languages.

See: #2589

**Comment by Robonau** [comment]
was fixed, idk when, probably a while ago
