### ISSUE TITLE
[Site Request] 漫漫漫画 (ManManApp)

### ISSUE THREAD

**Issue by vinh2201** [manga-download/hakuneko#2586]
**Name of the website**
漫漫漫画 (ManManApp)

**Website urls (examples below)**
- Site: https://www.manmanapp.com
- Manga List: https://www.manmanapp.com/comic/category.html
- Manga example: https://www.manmanapp.com/comic-1403829.html
- Chapter online viewer example: https://www.manmanapp.com/comic/detail-1409749.html

**Languages**
Chinese

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment]
Duplicate of #390
