### ISSUE TITLE
[Site Request] Kissmanga.org

### ISSUE THREAD

**Issue by AHSANUL-KARIM** [manga-download/hakuneko#2591]
**Name of the website**
Kissmanga

**Website urls (examples below)**
- Site: https://kissmanga.org/
- Manga List: https://kissmanga.org/manga_list
- Manga example: https://kissmanga.org/manga/my_id_is_gangnam_beauty
- Chapter online viewer example: https://kissmanga.org/chapter/my_id_is_gangnam_beauty/chapter_91

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #2237 
Please search tickets before create a duplicate
