### ISSUE TITLE
OSX -> Multi download

### ISSUE THREAD

**Issue by K-MeLeOn** [manga-download/hakuneko#260]
With two or more downloads at the same time, the progress bar isn't a new instance for all. Is the same object and when one of them is update, all progress bars is updated.

**Comment by 27136773** [comment]
I'm afraid i don't understand what you are trying to explain, so here is a summary how HakuNeko is supposed to work:

- There can only be one chapter download at the same time per website (Fig. 01)
- When downloading chapters from multiple websites, each progress bar is updated individually for the corresponding download (Fig. 02)
- Each download (job) is implemented to be an independent instance, there are no shared properties or states between jobs, even when downloads are from the same websites

----

**Fig. 01: Downloading multiple chapters from the same website**
![image](https://user-images.githubusercontent.com/27136773/61145587-1db80080-a4d8-11e9-9200-63708a624ded.png)

**Fig. 02: Downloading chapters from multiple websites**
![image](https://user-images.githubusercontent.com/27136773/61145606-26a8d200-a4d8-11e9-8780-0f72e0f12693.png)

**Comment by 27136773** [comment]
No further response => closed
