### ISSUE TITLE
[Site Request] Aniwatch

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#2600]
**Name of the website**
Aniwatch

**Website urls (examples below)**
- Site: https://aniwatch.me
- Anime List: https://aniwatch.me/top?t=0&p=1
- Anime example: https://aniwatch.me/anime/1088 (Episodes Tab)
- Anime online viewer example: https://aniwatch.me/anime/1088/1

**Languages**
Multi-Lingual (mostly JP/EN)

**Additional details**
Login required to stream videos
Uses `POST: https://aniwatch.me/api/ajax/APIHandle` endpoint to get animes/episodes/streams

**Comment by MikeZeDev** [comment]
Website closed

**Comment by beedell-roke** [comment]
> https://github.com/manga-download/hakuneko/issues/2600#issuecomment-1540629577

@MikeZeDev, https://github.com/manga-download/hakuneko/issues/6878#issue-2181831304
