### ISSUE TITLE
Maybe not a bug, but a procedure to follow to make it work right re:Mangadex mark as read problem

### ISSUE THREAD

**Issue by doppler56** [manga-download/hakuneko#2607]
Windows 10 64 bit Haku 8.3.4 master@bbc7d9

This has been a stumper of a problem.  I finally figured it out.  If I follow the procedure I can live with it.  This is a tale of two cookies I think.  ie: Getting mangadex to mark a chapter as read from Hakuneko.

Preface: Using Firefox with Feedbro RSS reader (let's me know when new content happens)

Let's start with what I know doesn't work.
1. Notice new content in feedbro.
2. Open link to mangadex from freedbro provided link.
3. Start Hakuneko.
4. Go into follow folder on mangadex.  (provides new content links)
5. unread content does not have a blacken eyeball.  (the way Managadex does it. grey is not read)
6. Grab chapter content using Hakuneko.  Using clipboard copy or bookmark doesn't matter.
7. If I refresh the follow content page on Mangadex.  Chapter is not marked as read.

What does work every time: (edit2: change in sequence)
2. Start Hakuneko.  (edit2)
2a. get a directory of any manga.  (edit2: to exchange the cookie before Firefox can)
2b. Start Firefox. (edit2)
1. Notice new content in Feedbro.
3. Grab chapter content using Hakuneko.  Using clipboard bla, bla, bla.  Freedbro  as a reference to get content.
4. Open link to Mangadex from Freedbro provided link.
5. Go into follow folder on mangadex.  (provides new content links)
Chapters are being marked as read on Mangadex.  And other chapters using Hakuneko will too after a page refresh.

Epilogue:
I did get a fresh cookie for Haku using the login feature of Haku.  This cookie is much newer with a expire date much longer than the cookie used by Firefox.  I suspect mismatching cookies is the problem.  If I give the Firefox cookie before Haku gives there cookie the problem shows up.  Reverse the cookie order by procedure and no problem.

Is this a real problem, I don't know.  Was it intended to be feature of Haku (mark as read), I don't know.  Can I live the procedure that makes it work, sure can!  I suspect mangadex uses the first cookie given to track your reading.

**maybe Expected behavior**
Articles marked as read on Mangadex.  If I follow the procedure.

Sorry this is overly wordy and a pain in the process.  If this is not really fixable, I will live with the procedure.
Edit: Another factor is involved, but I think I am on the right track.  (procedure didn't work)  something might have changed since I started firefox and haku.
edit2: slight change in sequence.  This is it I hope.

**Comment by 27136773** [comment]
HakuNeko does not have such feature to mark chapters as read on MangaDex, this is a flaw in the provided API from MangaDex.
With the next update this will be solved and HakuNeko will stop marking chapters on MangaDex as read.
