### ISSUE TITLE
Add Ohtabooks

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#261]
http://webcomic.ohtabooks.com/

**Comment by 27136773** [comment]
Seems to use SpeedBinb reader (same as e.g. used in BookLive, ComicMeteor, Takeshobo).

**Comment by Ever4engel** [comment]
Yep it's speedbinb reader

**Comment by medmig** [comment]
Added support in b525a766238e558b58b148211eac787fd696956c.
