### ISSUE TITLE
[Feature] Login ability for tapas.io

### ISSUE THREAD

**Issue by Shirobaka** [manga-download/hakuneko#2614]
**Is your feature request related to a problem? Please describe.**
I would like to download comics from tapas which i bought with ink, only available with logged in account.

**Describe the solution you'd like**
A solution would be a way to add the login credentials for a tapas.io account which gives access to "hidden" chapters which were bought with ink.

**Describe alternatives you've considered**
An alternative solution would be to add from browser exported cookies which will be used when connected to tapas.io for chapter search.
(Browser-Extension for cookie export is needed)

**Context (please complete the following information):**
HakuNeko Version 6.17

**Additional context**
-

**Comment by 27136773** [comment]
Is [manual login](https://hakuneko.download/docs/manual-website-interaction/#account-login) not working?

**Comment by Shirobaka** [comment]
> 
> 
> Is [manual login](https://hakuneko.download/docs/manual-website-interaction/#account-login) not working?

Ok, didn't know that such a way exists, that works great.
Feature Request can be closed. Thanks
