### ISSUE TITLE
Type error failed to fetch

### ISSUE THREAD

**Issue by fokoa** [manga-download/hakuneko#2615]
Almost everything I upload to Hakuneko doesn't upload, and that's boring! I still get the same type of "Type error failed to fetch" error.

version is 6.1.7

**Comment by 27136773** [comment]
Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by 27136773** [comment]
No further response => closed
