### ISSUE TITLE
[Site Request Arabic] mangaka3rb

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2619]
**Name of the website**
mangaka3rb

**Website urls (examples below)**
- Site: https://www.mangaka3rb.com/
- Manga List: https://www.mangaka3rb.com/manga
- Manga example: https://www.mangaka3rb.com/manga/slam-dunk
- Chapter online viewer example: https://www.mangaka3rb.com/manga/slam-dunk/76/1/0

**Languages**
ARABIC

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dead website? No alternative found.
