### ISSUE TITLE
IsekaiRaw, Mangaraw online, Manhua Raw, RawLH, RawSenManga are NOT WORKING!

### ISSUE THREAD

**Issue by Blacklotis2** [manga-download/hakuneko#262]
It seems that none of the Raw manga websites are working on Hakuneko. Most Important websites are IsekaiRaw, Mangaraw online, Manhua Raw, RawLH and RawSenManga

**Comment by Blacklotis2** [comment]
https://lhscan.net 
https://www.readrawmanga.com

**Comment by 27136773** [comment]
Have you tried [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?

----
**http://isekairaw.com**
Website is not reachable from my end, HakuNeko cannot download if the website is offline
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61173003-451cd500-a58d-11e9-825a-b56ceb3518e7.png"/>
</details>


----
**https://lhscan.net**
Works for me, please provide which manga/chapter is not working
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61173009-7b5a5480-a58d-11e9-8eb6-5ebe460c3646.png"/>
</details>

----
**http://mangaraw.online**
Website is not reachable from my end, HakuNeko cannot download if the website is offline
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61173075-6d590380-a58e-11e9-91f7-29b7c75d7cd4.png"/>
</details>

----
**https://www.readrawmanga.com**
Works for me, please provide which manga/chapter is not working
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61172978-caec5080-a58c-11e9-9b96-16b67c926a37.png"/>
</details>

----
**https://rawmanga.site**
Website is not reachable from my end, HakuNeko cannot download if the website is offline
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61173100-c2951500-a58e-11e9-864f-ad47e09f02b2.png"/>
</details>

----
**https://rawqq.com**
Redirects to https://hanascan.com, but still works for me, please provide which manga/chapter is not working
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61173039-ef94f800-a58d-11e9-8933-b7ae87634465.png"/>
</details>

----
**https://rawqv.com**
Uses https://mangahato.com, but works for me, please provide which manga/chapter is not working
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61173047-118e7a80-a58e-11e9-8833-3e5383dfdf8b.png"/>
</details>

----
**https://raw.senmanga.com**
Works for me, please provide which manga/chapter is not working
<details><summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/27136773/61173117-fcfeb200-a58e-11e9-857c-bf99f003473f.png"/>
</details>

**Comment by Blacklotis2** [comment]
Yes, I have tried troubleshooting.It's not fixing it. I'm able to download from many other websites just the Raw ones I mentioned aren't working and I have confirmed from 3 other people that are using hakuneko and all of them tell me that these sites are not working. 
This is the error I am getting for all sites that you mentioned are working for you:

<img width="826" alt="11" src="https://user-images.githubusercontent.com/22255473/61173572-8ffb1480-a5ae-11e9-8471-d1f8bcf2953a.png">

**Comment by 27136773** [comment]
502 sounds like a CloudFlare error, LHScan is working in your browser?
Also try [Manual website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) to check if there are any problems.

**Comment by 27136773** [comment]
Cannot be reproduced, no further feedback => closed
