### ISSUE TITLE
[Site Request Arabic] andromedax

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2620]
**Name of the website**
andromedax

**Website urls (examples below)**
- Site: https://andromedax.net/
- Manga List: https://andromedax.net/
- Manga example: https://andromedax.net/series/the-great-mage-returns-after-4000-years/
- Chapter online viewer example: https://andromedax.net/z77rxk9/

**Languages**
ARABIC 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
wordpress ZManga, not that we have a template for it

**Comment by 27136773** [comment]
Website no longer available (domain for expired)
