### ISSUE TITLE
[Bug] Mangadex trasnlation group name not showing

### ISSUE THREAD

**Issue by RedwanRabbiHoque** [manga-download/hakuneko#2621]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Translation group name not showing

**Screenshots**
![1](https://user-images.githubusercontent.com/48180076/98788695-7c262380-242b-11eb-9c5b-34174b1ec5cb.png)
![2](https://user-images.githubusercontent.com/48180076/98788739-86e0b880-242b-11eb-856a-9a21f6c8656a.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Nightly Version (lastest release)

**Additional context**
Mangadex usually has the same chapter but from different translation group. So when I try to download and the name of the group isn't there anymore the files merge. I did check the difference in size and pages and both of them varied. Anyways if someone prefers a particular translation group it will be hard. I did check with the basic Hakuneko which didn't have the problem.

**Comment by 27136773** [comment]
They already breaking their new v2 API ... need to adapt group extraction
