### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by fajri411** [manga-download/hakuneko#2626]
**Name of the website**
sekaikomik

**Website urls (examples below)**
- Site: https://www.sekaikomik.com/
- Manga List: https://www.sekaikomik.com/daftar-komik/
- Manga example: https://www.sekaikomik.com/manga/eunhye-super/
- Chapter online viewer example: https://www.sekaikomik.com/eunhye-super-chapter-26/

**Languages**
indonesia

**Website relationship*
the website is very close to mangasusu

**Additional details**

**Comment by manh21** [comment]
Duplicate of #2627
