### ISSUE TITLE
[Site Request] sekaikomik

### ISSUE THREAD

**Issue by fajri411** [manga-download/hakuneko#2627]
**Name of the website**
sekaikomik

**Website urls (examples below)**
- Site: https://www.sekaikomik.com/
- Manga List: https://www.sekaikomik.com/daftar-komik/
- Manga example: https://www.sekaikomik.com/manga/eunhye-super/
- Chapter online viewer example: https://www.sekaikomik.com/eunhye-super-chapter-26/

**Languages**
indonesia

**Website relationship*
the website is very close to mangasusu

**Additional details**

**Comment by manh21** [comment]
Use MangaReader WordPress theme

**Comment by fajri411** [comment]
yes, use MangaReader WordPress theme

**Comment by fajri411** [comment]
can you add site in hakuneko?

**Comment by Robonau** [comment]
its up to a dev to decide whether they want to or not.
we don't have a template for WordPressMangaReader so itd have to be done from scratch

**Comment by fajri411** [comment]
OK, I hope it can be done
