### ISSUE TITLE
[Site Request] Kakaopage

### ISSUE THREAD

**Issue by Shinrol** [manga-download/hakuneko#2628]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://page.kakao.com/main
- Manga List: https://page.kakao.com/main?categoryUid=10&subCategoryUid=1005
- Manga example: https://page.kakao.com/home?seriesId=50289296
- Chapter online viewer example: https://page.kakao.com/viewer?productId=50290005

**Languages**
Korean

**Comment by 27136773** [comment]
See #200
