### ISSUE TITLE
Paid requests to contritbutors for work

### ISSUE THREAD

**Issue by JustAQuestionOkay** [manga-download/hakuneko#2634]
Do contributors accept paid requests via paypal?
If yes, would a contributor be interested in being paid for the following work-

**1) Add connector for TappyToon**
-     Site: https://www.tappytoon.com/en/
-     Manga List: https://www.tappytoon.com/en/genres?alias=bl  AND https://www.tappytoon.com/en/genres?alias=action
-     Manga example: https://www.tappytoon.com/en/comics/skeleton-soldier-failed-defend-dungeon
-     Chapter online viewer example: https://www.tappytoon.com/en/chapters/585252546?

**2) Fix the Lezhin English connector**
See Issue  #2517 for details.  https://github.com/manga-download/hakuneko/issues/2517 

If there's a better place to ask this, please let me know.  Thanks.

**Comment by 27136773** [comment]
The project does not accept donations.
If any contributors are willing to provide source code in return of a private "donation" may happen only outside of this project's scope.
Maybe ask in Discord or on reddit...

Related: #1824
