### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by mpolintan** [manga-download/hakuneko#2635]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
I can see the manga in my browser but not in Hakuneko  6.1.7

**Describe the bug**
I can see the manga in my browser but not in Hakuneko  6.1.7

**To Reproduce**
http://www.mangago.me/read-manga/the_tyrant_s_tranquilizer/
http://www.mangago.me/read-manga/she_and_the_beast/
http://www.mangago.me/read-manga/they_say_i_was_born_a_king_s_little_daughter/

**Screenshots**
https://ibb.co/5FHkNDx

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Manga list is no longer supported in MangaGo as stated in the dialog that is shown when trying to update the list.
You have to use copy & paste feature...

**Comment by mpolintan** [comment]
> 
> 
> Manga list is no longer supported in MangaGo as stated in the dialog that is shown when trying to update the list.
> You have to use copy & paste feature...

Hi i did use the copy paste feature but the chapters is not showing

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
I copy & pasted all manga links mentioned in this ticket into 6.1.7 and all are working...

![image](https://user-images.githubusercontent.com/27136773/99400001-bb022080-28e6-11eb-9125-294423def52f.png)
