### ISSUE TITLE
[TuMangaOnline] Some mangas are downloaded with empty chapters

### ISSUE THREAD

**Issue by syleniaa** [manga-download/hakuneko#2636]
I don't know what is happening but since yesterday TuMangaOnline is downloading some manga with empty chapters  but it shows as if the download finished with success. I tried with some other random and some download ok but others empty . Trying this my guess is that this is happening with +18 rated mangas, i am not sure but may be this could help , i will leave you some links that downloaded empty chapters in the test  https://lectortmo.com/library/manhwa/55043/watashi-no-obasan
https://lectortmo.com/library/manhwa/43893/como-atraer-a-ese-alfa

**Comment by newaccforhc** [comment]
Looks like the chapters for this manga are redirected to different domain..

**Comment by syleniaa** [comment]
why is this happening with those mangas? i have tried with many others and some are downloaded fine and some others no. until yesterday everything was working fine. i just checked what you said and yes , checking random mangas all +18 rated mangas are redirected to other domain (it is not always the same, testing i have seen two differents ones) and the under 18 rated are not redirected, in the url shows lectortmo. is there a solution to that??

**Comment by newaccforhc** [comment]
I don't know the solution. But, Ronny dealt with similar situation in past iirc.. So, he might do it again... But, don't expect it to be done soon.. He's super busy with HN NW

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Please provide a specific manga and chapter for the problem...

![image](https://user-images.githubusercontent.com/27136773/99591863-af4e5100-29ef-11eb-9193-8eeb82398e2e.png)

**Comment by syleniaa** [comment]
i tried with that same manga and the chapter 70 is downloaded as empty but doesn't show as error, the preview doesn;t even load, look 
![Image 1](https://user-images.githubusercontent.com/16405194/99610924-b3bf3d80-29e0-11eb-979d-0969b3e78a76.png)
i tried with some other manga of the same site , https://lectortmo.com/library/manhua/46631/badao-xiao-shu-quing-quing-liao , and the chapters and downloaded ok and the preview it's showed 
![Image 2](https://user-images.githubusercontent.com/16405194/99611896-7a87cd00-29e2-11eb-914e-662f473a6faf.png)

the main difference between them it's when i open a chapter in the browser of the first one (the one that doesn't download anything) , the url it's different, this is the url of chapter 70 , https://mistermanga.com/news/e63d3f98196514c1fe5f9b8116fe8b7b/cascade, looks like it is being redirected,  but when i open a chapter of the second manga the url is in the same domain of the site https://lectortmo.com/viewer/e53d062b19a94647c38bb9262f6325f8/cascade. 

 i tried opening the chapter 70 of the one that its downloaded wrong in my browser , in hakuneko browser and the chapter loads fine, the problem is when i tried to see the preview or downloading it, the same happens to me with any other chapter that it is being redirected. may be the problem it's on my side, i dont' know. i am using rev 6.1.7 of the application, any other manga that its chapters are not redirected are downloaded fine.

**Comment by syleniaa** [comment]
i don't know what was the problem but i redownloaded the application and now it's working OK. it's loading the preview of the chapters  and downloading them ok, thnanks. i don't know if it has nothing to do with the version but this one is 6.1.7@410c45 and the other one that was giving me problem was 6.1.7@1b36ae

**Comment by 27136773** [comment]
In this case HakuNeko is following the chapter redirects, so it shouldn't pose a problem.
It seems you didn't receive automatic updates for some reason since four month.
