### ISSUE TITLE
REPLACE THE NOT WORKING ANIME WEBSITES WITH THE WORKING ONES

### ISSUE THREAD

**Issue by DSG7757** [manga-download/hakuneko#2646]
In HakuNeko we can watch anime from 9anime. But the download feature for 9anime dosen't work. I tried other solutions too but they don't work. Crunchyroll and the other anime websites dosen't work too.

I would like you to fix it. if you cannot fix it then there are better websites too. Replace the current ones with the working ones

In my opinion [ANIMEKISA](https://animekisa.tv/) is the best alternative. please change these websites with the ones that work.

 My current HakuNeko Version [e.g. 6.17]

![ice_screenshot_20201120-091951](https://user-images.githubusercontent.com/74442723/99754349-6b07a180-2b12-11eb-81a5-e6ba303a5149.png)

![ice_screenshot_20201120-092125](https://user-images.githubusercontent.com/74442723/99754357-6e9b2880-2b12-11eb-8639-2a48a7a05dc7.png)

![ice_screenshot_20201120-092654](https://user-images.githubusercontent.com/74442723/99754475-a4401180-2b12-11eb-916d-e7e400c03f35.png)

If I try to use Animepehe it never stops loading
![ice_screenshot_20201120-092720](https://user-images.githubusercontent.com/74442723/99754533-c2a60d00-2b12-11eb-8587-ff672c4fc8a5.png)

**Comment by 27136773** [comment]
Please make separate tickets for each website that does not work and for each website that shall be added, otherwise feedback and discussions will be confusing and end up in a mess...

Related: #2416
Related: #2236
