### ISSUE TITLE
Canary Deployment of Test Candidates for next Release

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#266]
The [Test Candidates](https://sourceforge.net/projects/hakuneko/files/testing/) for the next release of the desktop client are now published.
I appreciate everyone who participate in testing and report problems/bugs on [GitHub](https://github.com/manga-download/hakuneko/issues) prefarable in Issue #266.

Before jumping in, make sure to backup the [UserData Directory](https://github.com/manga-download/hakuneko/wiki/User-Manual#22-user-data) (just in case).

**Comment by Ever4engel** [comment]
I specify to hakuneko 5 to save images to .png but he save it in .jpg 
![image](https://user-images.githubusercontent.com/47645041/61186645-04de5500-a668-11e9-8310-d10f213a61f9.png)

**Comment by 27136773** [comment]
Which website?
The de-scrambling format only applies to images that are puzzled, all other images that are not using an graphical encryption are always stored in their original format.

**Comment by Ever4engel** [comment]
On tonari no young jump

**Comment by 27136773** [comment]
Basically TonariNoYoungJump uses descrambles images, but some chapters are not scrambled, so they might be downloaded in their original format, e.g. All you need is Kill is scrambled and correctly converted to PNG for me.
Which manga/chapter is this?

**Comment by Ever4engel** [comment]
Oh i see !
this OPM [chapter](https://tonarinoyj.jp/episode/10834108156668686835) and with the dev console i can see that most of images are descrambled but not all

**Comment by 27136773** [comment]
From the download count it seems there were quite some users who joined testing.
There has been no bug reports, so testing phase is considered as success and the staging for release is now prepared.

![image](https://user-images.githubusercontent.com/27136773/61968821-444a6100-afd9-11e9-9123-5efab9b6b10f.png)

**Comment by MIRVOUS** [comment]
i tried. and i found like this
![Capture2](https://user-images.githubusercontent.com/45929526/62035945-05a3e900-b21b-11e9-84c3-088693d80b75.PNG)
