### ISSUE TITLE
[Site Request] Phoenix Fansub

### ISSUE THREAD

**Issue by TheDoom95** [manga-download/hakuneko#2662]
**Name of the website**
   Phoenix Fansub

**Website urls (examples below)**
- Site: https://phoenixfansub.com/
- Manga List: https://phoenixfansub.com/manga/release-that-witch/
- Chapter online viewer example: https://phoenixfansub.com/release-that-witch-capitulo-109/

**Languages**
Español (Spain - ES)

**Comment by 27136773** [comment]
Theme: WordPressMangastream
