### ISSUE TITLE
[Site Request] Manga.club

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#2665]
**Name of the website**
Manga

**Website urls (examples below)**
- Site: https://www.manga.club/
- Manga List: no manga list (fragmented to multiple parts)
- Manga example: https://www.manga.club/book/title/SBCEN-9784596781598
- Chapter online viewer example: https://www.manga.club/bv/t/SBCEN-9784596781598/v/1/s/1/p/1

**Languages**
English

**Website relationship**
nothing to say

**Additional details**
to de-encrypt base64 images https://www.manga.club/statics/js/sukima-book-viewer-ttb.js?v202011250020

**Comment by 27136773** [comment]
Picked a random chapter and it was english

Probably not related, but same logo as ReadMangaTV

**Comment by Ever4engel** [comment]
yeah i done a mistake with another website. This website have english webtoons.
