### ISSUE TITLE
[Site Request] kissmanga.cc

### ISSUE THREAD

**Issue by Lillibus** [manga-download/hakuneko#2669]
**Name of the website**
kissmanga.cc

**Website urls (examples below)**
- Site: http://kissmanga.cc
- Manga List: http://kissmanga.cc/popular-manga
- Manga example: http://kissmanga.cc/manga/orange-takano-ichigo
- Chapter online viewer example: http://kissmanga.cc/orange-takano-ichigo-chapter-1#1

**Languages**
English

**Comment by 27136773** [comment]
Same as http://kissmanga.website which is already supported
May update [`canHandleURI`](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/KissMangaWebsite.mjs#L27-#L30) to also support this domain...
