### ISSUE TITLE
Sixiang is not downloading chapters

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#267]
> **From:** HakuNeko User

The site is working and does show chapters but does not download. 
Thanks!

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Which manga/chapter is not working?
Have you tried [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?
what is shown in the [error console](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#making-an-informative-help-request)?

**Comment by 27136773** [comment]
It seems there is a certificate error for the website.
This works fine with the new test version of HakuNeko.
It will not be fixed in 0.4.0 anymore as the next release will be coming in a few weeks.
