### ISSUE TITLE
[Kissmanga.org] Connector not working

### ISSUE THREAD

**Issue by Lillibus** [manga-download/hakuneko#2670]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When trying to load the manga list from kissmanga.org, I get the message "Failed to update manga list for Kissmanga.org
Failed to receive content from "https://kissmanga.org/manga-list/?page=106" ".
The url of the manga list is indeed wrong and doesn't work on the browser, but the main domain (kissmanga.org) works, with manga list at "https://kissmanga.org/manga_list".

**To Reproduce**
1. Kissmanga.org
2. connector update is not working
3. connector update is not working
4. "Failed to update manga list for Kissmanga.org
Failed to receive content from "https://kissmanga.org/manga-list/?page=106" (status: 500)-"

**Screenshots**
![image](https://user-images.githubusercontent.com/75039660/100271340-a0b8ea00-2f59-11eb-82f2-8ead3858d9fe.png)

**HakuNeko (please complete the following information):**
 - 6.17@8b6722

**Comment by 27136773** [comment]
There is a typo in the link, the dash is actually an underscore, but it still fails...
https://kissmanga.org/manga_list/?page=106
This is an error on the website and cannot be solved in HakuNeko, possible workaround could be to ignore error `500`, but this will lead to an incomplete manga list

Use  copy & paste feature for now

**Comment by Lillibus** [comment]
Hi Ronny,
What do you mean by use copy and paste feature? 
Can we actually edit the url of the manga list anywhere?

**Comment by 27136773** [comment]
You may check the documentation
https://hakuneko.download/docs/FAQ/#copy-and-paste

**Comment by Lillibus** [comment]
Oh, thanks!
