### ISSUE TITLE
[Comic-walker] Connector not working

### ISSUE THREAD

**Issue by Neutronoid** [manga-download/hakuneko#2676]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error appear when click the dowload or preview button. 
TypeError: Cannot read property 'dataset' of undefined at mjs/connectors/ComicWalker.mjs:78

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
Looks like they updated their website, using the new Publus reader v.2020-11-10

**Comment by Robonau** [comment]
idk if they did much
replacing  `this.fetchDOM( request, 'div#cw-viewer' )` with `this.fetchDOM( request, '#app' )` in _getPageList fixes the issue

**Comment by 27136773** [comment]
Yes they just renamed the element from `div#cw-viewer` to `main#app`
Seems viewer was always based on Publus (or visually copying it), so no additional change needed
