### ISSUE TITLE
[StoriaDash] Connector not working

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#2677]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
didn't work

**To Reproduce**
1. copy this link http://storia.takeshobo.co.jp/manga/yomikiri-dash/_files_ecstasy/ecstasy/
2. paste to hakuneko
3. detected as manga(randomnumber)
4. no chapters available on the chapters column 

**Screenshots**

![hakkku](https://user-images.githubusercontent.com/23132217/100416282-aa089a80-30b0-11eb-8ef7-a0ab7342e497.png)

**HakuNeko (please complete the following information):**
 - Version 6.17@8b6772

**Comment by 27136773** [comment]
The link is wrong, HakuNeko requires a [manga link](http://storia.takeshobo.co.jp/manga/yomikiri-dash/), a direct [chapter link](http://storia.takeshobo.co.jp/manga/yomikiri-dash/_files_ecstasy/ecstasy/) will not work...
However, this still does not solve the issue as the connector in general does not support copy & paste yet

**Comment by pazergithub** [comment]
@ronny1982 

This doesn't seem to be fixed - Takeshobo series come up with zero chapters, whether selected from the list or added from the clipboard. Examples:

https://storia.takeshobo.co.jp/manga/himegimi/
https://storia.takeshobo.co.jp/manga/osi_stalker/
https://gammaplus.takeshobo.co.jp/manga/yuki_kannoh/
https://gammaplus.takeshobo.co.jp/manga/yukino_niiduma/
