### ISSUE TITLE
[Site Request] Scan FR

### ISSUE THREAD

**Issue by Yunaxigf** [manga-download/hakuneko#2679]
**Name of the website**
Scan FR

**Website urls (examples below)**
- Site: https://www.scan-fr.cc
- Manga List: 
- Manga example: https://www.scan-fr.cc/manga/slave-b
- Chapter online viewer example: https://www.scan-fr.cc/manga/slave-b/22/1

**Languages**
French

**Comment by 27136773** [comment]
ScanFR is already supported, but the old domain (why still working), may be updated
