### ISSUE TITLE
[Scanmanga] Connector not working

### ISSUE THREAD

**Issue by snohboy** [manga-download/hakuneko#2688]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**are you able to see the manga within your browser**
Yes

**Describe the bug**
I can't refresh the list on scanmanga.

**To Reproduce**
1. Scanmanga
2. Zui Wu Dao
3. chapter 48
4. Failed to update manga list for ScanManga Unexpected end of JSON input

**Screenshots**
![Scanmanga_error](https://user-images.githubusercontent.com/60775518/100514610-2319f780-316e-11eb-8cbf-61dfbe6d5cdf.PNG)

**HakuNeko**
2020 HakuNeko rev. master@f63e25

**Comment by 27136773** [comment]
See: #2291
