### ISSUE TITLE
[NameOfConnector] Connector not working 

### ISSUE THREAD

**Issue by hellokitty-chan** [manga-download/hakuneko#2704]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
It keep showing Database Error even when I refresh the tab

**To Reproduce**
1. Name of connector (I don't know)
2. Name of manga (Once More)
3. Name of chapter (5)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
HakuNeko neither has a database, nor a tab based interface.
Provide screenshots and provide steps to reproduce

**Comment by alinatsi99** [comment]
The loading button is dead, it doesn't work at all for me. So the connector isn't working at all.

**Comment by 27136773** [comment]
@alinatsi99 Please create a new ticket, rule of thumb is one problem one ticket, otherwise it will become confusing...

**Comment by 27136773** [comment]
I will close this ticket, i think it would be better to read the documentation on the website and/or ask in discord for help, since this seems to be more of a usability issue then a technical problem.
