### ISSUE TITLE
[Site Request] Glory Manga

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2711]
Name of the website:
Glory Manga
•	Site:  https://glorymanga.com
•	Manga List:  https://glorymanga.com/manga/
•	Manga example:  https://glorymanga.com/manga/i-became-a-maid-in-a-tl/
•	Chapter online viewer example: https://glorymanga.com/manga/i-became-a-maid-in-a-tl/bolum-1/
Language: Turkish
Madara

**Comment by 27136773** [comment]
Template: WordPressMadara

**Comment by dodieboy** [comment]
![image](https://user-images.githubusercontent.com/9015764/101610090-bee71580-3a42-11eb-9714-2dc78cdab760.png)
Is this website up? Getting error 404 for every manga, but I still did a connector for it
