### ISSUE TITLE
[Site Request] Manga Tepesi

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2712]
Name of the website:
Manga Tepesi
•	Site:  https://mangatepesi.com
•	Manga List: https://mangatepesi.com/mangalistesi
•	Manga example:  https://mangatepesi.com/manga/lightning-degree/5
•	Chapter online viewer example: https://mangatepesi.com/manga/lightning-degree/bolum-3/107

Language: Turkish

**Comment by 27136773** [comment]
See: #1725
