### ISSUE TITLE
[Site Request] Raindrop Fansub

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2713]
Website change 

Name of the website:
Raindrop Fansub

•	Site:  http://raindropteamfan.com
•	Manga List: http://raindropteamfan.com/manga-list
•	Manga example:  http://raindropteamfan.com/manga/koi-koi
•	Chapter online viewer example:  http://raindropteamfan.com/manga/koi-koi/1/1
Language: Turkish

My manga Reader

**Comment by 27136773** [comment]
Already supported, please check before making a request
