### ISSUE TITLE
[MangaNeloToday] Mangas redirecting to new domain

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#2733]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Almost any manga [found on manganelo.today](http://manganelo.today/search?s=Shikkaku+Mon+no+Saikyou+Kenja&post_type=manga) will redirect to a new domain which is not yet supported in HakuNeko.
It might make sense to add support for the new website, so copy & paste will work correctly...

**To Reproduce**
1. Load manga list for manganelo.today (by AnyACG)
2. Search and select manga `Shikkaku Mon no Saikyou Kenja`
3. Failed to load chapters probably because redirecting [source](http://manganelo.today/manga/shikkaku-mon-no-saikyou-kenja) to [target](http://manganelos.com/manga/shikkaku-mon-no-saikyou-kenja) with different domain and probably different CSS query...

**Comment by XenonR** [comment]
Fixed by #2746
