### ISSUE TITLE
mangaeden.com Connector not working 

### ISSUE THREAD

**Issue by manga2021** [manga-download/hakuneko#2736]
Please correct the URL -> https://beta.mangaeden.com and NOT -> https://www.mangaeden.com

Thx!

**Comment by 27136773** [comment]
What advantage has `beta.mangaeden.com` over `www.mangaeden.com`?
They looking both identical to me.

**Comment by manga2021** [comment]
the connection doesn't work
if i open www.mangaeden.com i got this:
Firefox can’t establish a connection to the server at www.mangaeden.com
strangely works with chrome...
using hakuneko... i got this:

![error](https://user-images.githubusercontent.com/75585032/101523956-9818d880-3989-11eb-84f7-23bb2c28f123.png)

**Comment by 27136773** [comment]
I cannot reproduce this on my end, works fine.
May be region locked, or maybe isolated system/network issues...

![image](https://user-images.githubusercontent.com/27136773/101529694-32c8e580-3991-11eb-8700-00d1299712f5.png)

**Comment by manga2021** [comment]
what you suggest to do?
all the others italians connectors works
Thx!

**Comment by 27136773** [comment]
Don't know, maybe try VPN?
May also ask in discord for suggestions...
