### ISSUE TITLE
[Site Request] manhuadex

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#2737]
**Name of the website**
manhuadex

**Website urls (examples below)**
- Site: https://manhuadex.com/
- Manga List: https://manhuadex.com/manhua/
- Manga example: https://manhuadex.com/manhua/yuan-zun/
- Chapter online viewer example: https://manhuadex.com/manhua/yuan-zun/chapter-275/

**Languages**
List of languages supported by the website
ENG

**Comment by Robonau** [comment]
template : Madara
