### ISSUE TITLE
anime not downloading

### ISSUE THREAD

**Issue by toxicbroly** [manga-download/hakuneko#274]
so i went and bookmarked some anime i wanted to get later.

so i finally got around to getting one and it wont download. it will start and immediately stop.
i don't know what to do, and its not where its from either, i don't know what to do and i already re-downloaded it.

anyone else haveing this problem?

**Comment by 27136773** [comment]
Which website/anime/episode?
Have you tried manual website interaction (e.g. solve [Captcha](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection))?

**Comment by toxicbroly** [comment]
kissanime
and none of them are working
also i try to stay away from the site directly bk of viraces and popups

**Comment by 27136773** [comment]
The fix has been made for the next version (which is currently in public testing), but will not be merged into the current version 0.4.0
