### ISSUE TITLE
[AstralLibrary] Connector not working

### ISSUE THREAD

**Issue by mikeyblitz21** [manga-download/hakuneko#2741]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Doesn't load manga list.

**Screenshots**
![Screenshot (727)](https://user-images.githubusercontent.com/20335976/101653048-e73e3680-3a79-11eb-9f86-d570a846dab0.png)
![Screenshot (726)](https://user-images.githubusercontent.com/20335976/101653055-e86f6380-3a79-11eb-8156-c84a2648aca5.png)
![Screenshot (725)](https://user-images.githubusercontent.com/20335976/101653058-e86f6380-3a79-11eb-85b0-2e6ae8b78967.png)

**HakuNeko:**
 - Version 6.17@d0b5e2

**Comment by vinh2201** [comment]
Seems like the file admin-ajax.php is not found in the website.
![image](https://user-images.githubusercontent.com/63141930/101657290-4a2dce80-3a76-11eb-882f-c4c167c0226a.png)
