### ISSUE TITLE
[Comic gardo] Connector does not load its new added mangas

### ISSUE THREAD

**Issue by dragows** [manga-download/hakuneko#2742]
https://comic-gardo.com/episode/13933686331755744875  does not recognize it when updating the list 

https://cdn.discordapp.com/attachments/581630792120401922/786287746791899216/Screenshot_1.png

**Comment by 27136773** [comment]
HakuNeko only shows mangas which are present on [this list](https://comic-gardo.com/series), the provided example is not on this list and therefore not shown in HakuNeko.

Use the copy & paste feature to get chapters and/or add it to your bookmarks...

**Comment by Ever4engel** [comment]
@ronny1982 i tried this ''new'' manga, done a previews (leads to error at certain moment). downloading it do the same error.

Edit: a done a second try. it worked for both previews and download.

**Comment by MikeZeDev** [comment]
Tested the mentioned manga, download works. Can be closed i guess. @Sheepux please?
