### ISSUE TITLE
Sixiang and Trititia not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#275]
> **From:** HakuNeko User

Tritinia is not showing any chapters and can't update list (status 404). Sixiang doesn't download listed chapters and and shows blank pages on preview.

**Comment by 27136773** [comment]
Sixiang is already tracked in issue #267, please respond there.

**Comment by 27136773** [comment]
Problem for Trititia can be reproduced

**Comment by 27136773** [comment]
Has been fixed for the upcoming version, but will not be merged into version 0.4.0
