### ISSUE TITLE
[Feature] Select image size

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [manga-download/hakuneko#2754]
**Is your feature request related to a problem? Please describe.**
Before discovering that Booklive was supported by Hakuneko, while looking for ways to backup my purchases, I noticed that the sizes of the images fed to the canvas vary with each series and the image gets rounded to the size that fits the viewport. The size of the original images for a book can be derived from the values shown in this part of the code:
> `<div id="content-p2" data-ptimg="binb://kM2GsSqvqq-ZoJwm" style="width: 685.75px; height: 975px; transform: translate(-687px, 0px) scale(1.00036, 1);"><div class="pt-img" style="width: 100%; height: 0px; padding-bottom: 142.18%;"><div style="width: 685.75px; height: 331.5px; transform: translate(0px, 0px);"><img src="blob:https://booklive.jp/3b5693c3-119a-40f8-9b8d-3e6a934f7e9a" alt="" width="844" height="408" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(0.8125, 0.8125) translate(0px, 0px);"></div><div style="width: 685.75px; height: 325px; transform: translate(0px, 328.25px);"><img src="blob:https://booklive.jp/ac1d1e1e-b94a-4d41-98b0-b20acc3cab72" alt="" width="844" height="400" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(0.8125, 0.8125) translate(0px, 0px);"></div><div style="width: 685.75px; height: 325px; transform: translate(0px, 650px);"><img src="blob:https://booklive.jp/92126fec-ae89-4f28-ae17-8bc63e2c7b43" alt="" width="844" height="400" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(0.8125, 0.8125) translate(0px, 0px);"></div></div></div>`

In this case, the image has been cut in three slices (the three &lt;img> tags) and we can see that the first &lt;div> has one of the size values set with decimals (it's always the width). If we scale that up until the value reaches an integer, this gives us a image size of 2743x3900. If you manage to set your browser viewport to a height of 3900 px and capture the image shown, the image is pixel perfect.
However, when using Hakuneko, any image downloaded with it would have a height of 1600 px (at least those with higher resolutin, I haven't tried yet with lower resolutions). 

**Describe the solution you'd like**
I would very well like a feature in Hakuneko that allowed to either download the images with their original resolution or to download a choice resolution as long as it's equal or lower to the max resolution of the book.
This could be, on the user side, to place in the settings menu just a tick box, a selection droplist (similar to the "image quality" other sites have) or a field for the max value for height.
On the programmer side, the scrapper would need to be able to find the width and height numbers on the code shown before (located at body>div#contents>div#content_base>div.pages#content, any nested div other than div#overswipe), apply simple math to find the minimum integer multiple value for the width and use the value to calculate the new height (if fed custom resolution, check which height is the lowest and use that), then adjust the portview size so that it can scrape the images at their best.

**Describe alternatives you've considered**
An alternative would be just giving a custom height and have the scraper run always with that size of viewport.

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]
6.1.7@d0b5e2

**Additional context**

**Comment by 27136773** [comment]
Images are directly acquired from the server provided by the endpoint `/bib-api/bibGetCntntInfo`, the render size in the browser has no effect on what HakuNeko receives.

For non-purchased chapters the images are always received from the trial server which usually provides 1200p. Since i have no account or purchases, i cannot confirm if purchased images are from another server / in higher resolution...

**For Developers:** https://github.com/manga-download/hakuneko/blob/a74baf110f622d80dd1ee2a0b11ca2f4a97475f9/src/web/mjs/connectors/templates/SpeedBinb.mjs#L306

**Comment by l-l-l-l-l-l** [comment]
Seems like it's true. It seems that, somehow, the canvas uses some kind of smoothing algorithm when upscaling that in most of the instances I had come across made it look quite natural; it took me finding the correct page and a last test to notice the aftereffects of said algorithm.

It didn't help that the JPEG artifacts for some reason manage to obscure it (some of the artifacts looked like they didn't fit in scale with the actual zoom used, like a 6 px tall artifact on a page that had been upscaled with a 4x zoom).
