### ISSUE TITLE
Watermark removal for mangafox

### ISSUE THREAD

**Issue by randoomdude** [manga-download/hakuneko#2757]
**Is your feature request related to a problem? Please describe.**
Mangafox downloads having added bottom space
**Describe the solution you'd like**
A way to cut off the bottom text on mangafox releases
**Describe alternatives you've considered**
Manually cropping every image myself?
**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]
v6.1.7
**Additional context**
![003](https://user-images.githubusercontent.com/6027132/102067076-dfeb9580-3db7-11eb-9577-0a9617ef1235.jpg)

**Comment by 27136773** [comment]
**Developer Discussion:**

Is this more something that shall be done in post-processing with appropriate tools for image processing?

Or should this be added as image handling in MangaFox connector directly (which probably requires to add a library to handle image block detection, or implement it our self)?

**Comment by Sheepux** [comment]
It's randomly included so it's not something we can handle as it cannot be identified (unless we work on a complex image detection).
So it's probably a post command on user decision.

**Comment by Ever4engel** [comment]
consider to study this script https://github.com/mfripper/mfripper

**Comment by 27136773** [comment]
I agree, this should be handled by a postscript, which checks if the image contains a signature, removes it and re-save the image.
Implementing in HakuNeko would require to much effort, such as implementing the signature detection and adding more confusing settings like `remove signature` or `signature removal format (jpg, png, ...)`

=> rejected
