### ISSUE TITLE
[Hentai2R] Connector not working & other errors 

### ISSUE THREAD

**Issue by Pancakes0** [manga-download/hakuneko#2762]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
**Yes**/No

**Describe the bug**
activity finishes in developer console but Mangalist/Chapterlist remains blank aka nothing happens 

**To Reproduce**
1. Name of connector Hentai2read
2. Name of manga (if connector update is working) X
3. Name of chapter (if manga update is working) X
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) None? 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screen Shot 2020-12-15 at 1 20 16 AM](https://user-images.githubusercontent.com/73923883/102226881-e434c180-3f23-11eb-8ed6-4b48c08d4996.png)
![Screen Shot 2020-12-15 at 1 20 49 AM](https://user-images.githubusercontent.com/73923883/102226889-e6971b80-3f23-11eb-8c08-3434dffdbfbb.png)

**HakuNeko (please complete the following information):**
 - Version [6.17] macbook, 

**Other** 
![Screen Shot 2020-12-15 at 1 24 46 AM](https://user-images.githubusercontent.com/73923883/102227890-0975ff80-3f25-11eb-84bd-da2821a3c3e1.png)
![Screen Shot 2020-12-15 at 1 27 23 AM](https://user-images.githubusercontent.com/73923883/102227906-0ed34a00-3f25-11eb-9f17-4405a53d73c9.png)
i dont know what this is??

![Screen Shot 2020-12-15 at 1 24 24 AM](https://user-images.githubusercontent.com/73923883/102228638-e26bfd80-3f25-11eb-83c2-4bd0a4f7f390.png)
i dont know why this didnt work, in my browser it does, and it only has 3k pages which is less than most?

thats all i got for now. thank you

**Comment by 27136773** [comment]
Please make one ticket per problem, otherwise it will be confusing.
This ticket is now only for Hentai2Read and not for LewdManga or 9hentai (as in the popup stated that is not an issue as all, there is no manga list)

**Comment by Pancakes0** [comment]
> Please make one ticket per problem, otherwise it will be confusing.
> This ticket is now only for Hentai2Read and not for LewdManga or 9hentai (as in the popup stated that is not an issue as all, there is no manga list)

I apologize for that, ill keep it separate next time! 👌
