### ISSUE TITLE
[ManhuaPlus] Chapters list empty

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#2763]
ManhuaPlus site is online and working but not showing chapters on Hakuneko. Updating list works fine though and titles show just not chapters

**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by tsentered** [comment]
Btw, I just upgraded from Catalina to Big Sur on MacOS. Not sure if this might be a contributing factor. It seems to be affecting the order of chapters listed on the connectors. But ManhuaPlus seems to be the only one that doesn't show the chapters.

**Comment by dodieboy** [comment]
![image](https://user-images.githubusercontent.com/9015764/102323833-f4987b00-3fbb-11eb-8895-50bb1f910f3d.png)
Error cause by website not able to load chapters list, not hakuneko error

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random mangas...

The fields of the ticket template were completely ignored, especially the steps to reproduce (missing sample manga)
=> closed

![image](https://user-images.githubusercontent.com/27136773/102415850-30056a80-3ff9-11eb-8c92-9f782ef468d6.png)

**Comment by tsentered** [comment]
As I mentioned before the website was working fine and I ignored none of the steps but thank you anyways.

**Comment by 27136773** [comment]
I was referring to these (see below), which are expected to be filled by the user, otherwise it may not be possible to reproduce the problem. A developer cannot go through hundreds of mangas and chapters and search for the one that is not working...

----

![image](https://user-images.githubusercontent.com/27136773/102415640-d3a24b00-3ff8-11eb-88eb-bb5075e6bd08.png)

**Comment by tsentered** [comment]
I see what you are saying but the problem is while all titles were showing but none of the chapters were. It was my mistake to not fill the list accordingly where you indicated so I apologize for that. Again I want to say thank you for taking the time to address these matters with me.

**Comment by tsentered** [comment]
In part, I also wanted to put it out there on the possibility if Big Sur was creating an issue since I had just upgraded in case others come across similar issues.

**Comment by 27136773** [comment]
I haven't noticed any problems with BigSur so far during daily development of HakuNeko
