### ISSUE TITLE
Bookmark to remember language setting

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#2764]
Can the bookmark function be setup to also to hold language setting?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
This will be partially covered by #2007 
I think we should not spend additional effort to extend the bookmarking system and the related UI elements.
=> rejected

**Comment by tsentered** [comment]
Cool. Thanks anyways.
