### ISSUE TITLE
[www.shosetsu-manga.org] Website is dead

### ISSUE THREAD

**Issue by Pancakes0** [manga-download/hakuneko#2766]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/**No**

**Describe the bug**
site probably dead (leads to host)

**To Reproduce**
1. Name of connector  go to: www.shosetsu-manga.org
2. Name of manga (if connector update is working) X
3. Name of chapter (if manga update is working) X
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
Open the site 

**HakuNeko (please complete the following information):**
 - Version [6.17]
Thanks

**Comment by Sheepux** [comment]
The first question is also the answer to your issue ....
"Is the website of the connector working properly / are you able to see the manga within your browser"
Website is not working, it's not hakuneko's fault.
Unless an alternative domain is found the connector will be removed.

**Comment by Pancakes0** [comment]
hmm i dont know. i searched on google found nothing (cdjapan, asadora wiki, Shueisha and amazon links except their ko-fi page maybe there down because no donations to keep the site up? idk. ill remember that if the website is down ill put " Website is dead" instead of "Website is not working" if its the websites fault. thanks
