### ISSUE TITLE
[MangaDao] Connector not working

### ISSUE THREAD

**Issue by Pancakes0** [manga-download/hakuneko#2768]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/**No** (checked on HN not browser, reason below) 

**Describe the bug**
"Page is unavailable"
**To Reproduce**
1. Name of connector Go to the website (i dont know the .domain so check on HakuNeko)
2. Name of manga (if connector update is working) X
3. Name of chapter (if manga update is working) X
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screen Shot 2020-12-16 at 1 39 50 PM](https://user-images.githubusercontent.com/73923883/102313407-8ea3f780-3fab-11eb-8a18-4a94f24fec56.png)

**HakuNeko (please complete the following information):**
 - Version [6.17]
thanks

**Comment by 27136773** [comment]
So the website is down...

Is this temporarily or permanent?
Did they change domain?
Finally, should this website be kept or removed from HakuNeko?

**Comment by Pancakes0** [comment]
> So the website is down...
> 
> Is this temporarily or permanent?
> Did they change domain?
> Finally, should this website be kept or removed from HakuNeko?

just found the site! http://mangadao.com/cgi-sys/suspendedpage.cgi (i didnt know before ><)

> 1) Did they change domain?
> 2) Finally, should this website be kept or removed from HakuNeko?

1&2). No idea.  2). maybe? i havent used it and was just trying it out so i dont know if anyone still wants it?

**Comment by Sheepux** [comment]
Still suspended, considering website is dead. Removing from HakuNeko
