### ISSUE TITLE
[fujoshibitches] Connector not working

### ISSUE THREAD

**Issue by Pancakes0** [manga-download/hakuneko#2769]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/**No**

**Describe the bug**
"404 Not Found | openresty" error

**To Reproduce**
1. Name of connector visit http://fujoshibitches.shounen-ai.net/ 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screen Shot 2020-12-16 at 3 04 54 PM](https://user-images.githubusercontent.com/73923883/102316097-463b0880-3fb0-11eb-9615-576bccb6eef6.png)
![Screen Shot 2020-12-16 at 3 05 03 PM](https://user-images.githubusercontent.com/73923883/102316111-4fc47080-3fb0-11eb-8439-3c752f1fbfb7.png)
![Screen Shot 2020-12-16 at 3 05 23 PM](https://user-images.githubusercontent.com/73923883/102316119-5226ca80-3fb0-11eb-9fd9-e8aeed76d9a2.png)

**HakuNeko (please complete the following information):**
 - Version [6.17]
thank you

**Comment by 27136773** [comment]
Seems the domain is still up, but they only releases on tumblr right now https://twitter.com/fujoshi_bitches
There seems not to be an ad wall and there are also (only) direct download links, which makes HakuNeko quite redundant i guess...
Should we remove support for this website?

![image](https://user-images.githubusercontent.com/27136773/102356877-0ecb5c80-3fae-11eb-8024-3587599a59ec.png)

**Comment by Pancakes0** [comment]
> Seems the domain is still up, but they only releases on tumblr right now https://twitter.com/fujoshi_bitches
> There seems not to be an ad wall and there are also (only) direct download links, which makes HakuNeko quite redundant i guess...
> Should we remove support for this website?
> 
> ![image](https://user-images.githubusercontent.com/27136773/102356877-0ecb5c80-3fae-11eb-8024-3587599a59ec.png)

Theyre also still active and uploading in mangadex too. the buttons/link in the side gave me 404 code it leads to their site ↝ http://fujoshibitches.shounen-ai.net/ 
![Screen Shot 2020-12-17 at 7 22 25 PM](https://user-images.githubusercontent.com/73923883/102482963-0010a280-409f-11eb-8e14-b6ee22f22cf2.png)


> Should we remove support for this website?

i dunno, you guys decide. i can always use md links since theyre still active and it works.

**Comment by 27136773** [comment]
Seems the website is not coming back, only direct downloads on tumblr are provided (through twitter links) ...
=> Remove support
