### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by DarkDiRaiZeL** [manga-download/hakuneko#2779]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I download any manga from **mangakatana.com** but the file change to **.bin**

**To Reproduce**
1. mangakatana.com
2. Hardcore leveling warrior
3. all chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![bin file hakuneko](https://user-images.githubusercontent.com/76126487/102397389-c5642700-4018-11eb-8338-f0a1f6cdf1aa.png)
![eg mangakatana](https://user-images.githubusercontent.com/76126487/102397396-c72dea80-4018-11eb-85ba-94648fc647c9.png)
![version haku neko](https://user-images.githubusercontent.com/76126487/102397406-cb5a0800-4018-11eb-8674-7724996e894a.png)

**Comment by 27136773** [comment]
Their server seems broken and provides wrong `Content-Type` header for image request...
Need to apply automatic mime type detection for the website.

**Comment by DarkDiRaiZeL** [comment]
thank you for your response..
i wanna ask this dumb question..
did i need do anything like adjust something or you will auto fix this?

**Comment by Robonau** [comment]
> thank you for your response..
> i wanna ask this dumb question..
> did i need do anything like adjust something or you will auto fix this?

it is currently in a pull request to be put in the the program,
you will have to wait for it to go through then you can use the nightly to use it, or you can wait for the next update to the release branch

**Comment by DarkDiRaiZeL** [comment]
owh..thank you for your explanation..

**Comment by DarkDiRaiZeL** [comment]
thank you for fixing this problem...
