### ISSUE TITLE
[Site Request] Qingman5

### ISSUE THREAD

**Issue by westward-MARTIAN** [manga-download/hakuneko#2781]
**Name of the website**
Qingman5

**Website urls (examples below)**
- Site: http://qingman5.com
- Manga List: http://qingman5.com/sort/1-1.html
- Manga example: http://qingman5.com/15669/
- Chapter online viewer example: http://qingman5.com/15669/518688.html

**Languages**
chinese

**Website relationship**
it may be related to Kuman55.com

**Additional details**
none

**Comment by Robonau** [comment]
if it is related to Kuman55.com then its template may be MH (unsure as the can look rather different from each other)

**Comment by MikeZeDev** [comment]
Dead website?
