### ISSUE TITLE
[Site Request] ShouManhua

### ISSUE THREAD

**Issue by westward-MARTIAN** [manga-download/hakuneko#2782]
**Name of the website**
受漫画 (Shoumanhua)

**Website urls (examples below)**
- Site: http://www.shoumanhua.com/
- Manga List: http://www.shoumanhua.com/all/
- Manga example: http://www.shoumanhua.com/gufeng/1544/
- Chapter online viewer example: http://www.shoumanhua.com/gufeng/1544/28550.html

**Languages**
chinese

**Website relationship**
none

**Additional details**
none

**Comment by vinh2201** [comment]
Template using: MH template.
Some comics near the top of the web page redirect to a weird page that has been taken down.
