### ISSUE TITLE
[toomics-en] Some pages are slow to load.

### ISSUE THREAD

**Issue by riodeblois** [manga-download/hakuneko#2785]
Hello guys,

I've got some issue about some of the pages doesn't load quickly (maybe about throttle? but already tried to increase to 10000, the sample chapter also got many pages).

sample:
Family Adjustments
https://www.toomics.uk/en/webtoon/detail/code/110571/ep/22/toon/5214

Thanks.

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Downloading chapters from [Family Adjustments](https://global.toomics.com/en/webtoon/episode/toon/5214) took me max. 5 seconds per chapter, which seems quite good.

Also there are no throttling settings for Toomics, so no idea where you changed it.
Besides, increasing the throttling means increasing the delay between requests so it will get slower...

Please note that the official domain seems to be https://global.toomics.com/en and not https://www.toomics.uk/en (which has no copy & paste support in HakuNeko)

**Comment by riodeblois** [comment]
Hello,

I tried to include throttling in between codes and on my side it seems having that delay gives the pages more room to load.

Anyways, I already check my ISP and the hell yeah they have the problem not in the app nor in my pc (I just waste time trying to experiment on the config hahaha). They were having a bottle neck on their severs and gateways. Thank you for checking this issue. You can already closed this ticket. Sorry for not checking all possibilities on my side.

Thanks and God bless.
