### ISSUE TITLE
[Tsumino] Connector not working

### ISSUE THREAD

**Issue by Pancakes0** [manga-download/hakuneko#2786]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
**Yes**/No

**Describe the bug**
i dont know if its a bug particularly but im getting an "net::ERR_SPDY_PROTOCOL_ERROR 200" half way of downloading. 
i tried other sources its happening with tsumino, nhentai, and hentai2read.

**To Reproduce**
1. Name of connector 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) 

DownloadJob.mjs:118 GET https://content.tsumino.com/parts/44187/182?key=pAW-rDXl4aHaUDare0Gmvw&expires=1609459200 net::ERR_SPDY_PROTOCOL_ERROR 200
(anonymous) @ DownloadJob.mjs:118
Promise.then (async)
(anonymous) @ DownloadJob.mjs:118
_downloadPages @ DownloadJob.mjs:116
(anonymous) @ DownloadJob.mjs:76
(anonymous) @ Chapter.mjs:116
_getPageList @ Tsumino.mjs:110
async function (async)
_getPageList @ Tsumino.mjs:80
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screen Shot 2020-12-18 at 9 16 29 AM](https://user-images.githubusercontent.com/73923883/102562824-dd1fd600-4112-11eb-8a1a-b0be62527217.png)
![Screen Shot 2020-12-18 at 9 16 54 AM](https://user-images.githubusercontent.com/73923883/102562839-e27d2080-4112-11eb-9c4c-f9b74a5b6403.png)

though the image is like that when i copy it on my browser it appears and some images appear in preview 

it just suddenly happens when i was downloading. i finished like 3 downloads and suddenly i got this error yesterday and it doesnt seem to change since now. i also tried manga and it works. send help 💀
**HakuNeko (please complete the following information):**
 - Version [6.17]
thanks

**Comment by Pancakes0** [comment]
OKAY NVM. literally after i posted this to get help i tried downloading again and it works! i tried again 2x now im sorry for this i apologize!

**Comment by Pancakes0** [comment]
i was downloading another one but it failed 2x then it worked again fin aka succeeded downloading. i dont know why its happening..

**Comment by 27136773** [comment]
It is not possible to resolve the `ERR_SPDY_PROTOCOL_ERROR` error.
You may google for it to find further details...
