### ISSUE TITLE
it does not show manga 

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#279]
> **From:** HakuNeko User

mac osx mojave it does not load manga in websites

**Comment by 27136773** [comment]
Are you using the regular 0.4.0 version or the testing release?
Which website/manga/chapter?
Did you read the [Documentation](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#4-manga-list)?
Have you done [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?

**Comment by 27136773** [comment]
No further response => closed
