### ISSUE TITLE
[Site Request] wbnovel

### ISSUE THREAD

**Issue by zenkijoe** [manga-download/hakuneko#2796]
**Name of the website**
Wbnovel

**Website urls (examples below)**
- Site: https://wbnovel.com/
- Manga List: https://wbnovel.com/novel/
- Manga example: https://wbnovel.com/novel/chaotic-sword-god/
- Chapter online viewer example: https://wbnovel.com/novel/chaotic-sword-god/chapter-2166/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: WordpressMadaraNovel

**Comment by 27136773** [comment]
See: #2796
