### ISSUE TITLE
Add Daum Webtoon

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#28]
http://webtoon.daum.net/

**Comment by su0su0** [comment]
This is also one of the most famous Korean webtoon sites (like Naver's LINE webtoon)

Has two main "system":
- Ongoing series: All chapters (except the latest one) are free. No need to log in.
- Completed series: The first few chapters are free. The rest are available for purchase; or available on a free-after-12-hour( or 1-2 days) basis. Purchases require an account.
