### ISSUE TITLE
Holy Manga not working

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/hakuneko#2800]
I use dev build. No manga can be displayed anymore apparently.

https://cdn.discordapp.com/attachments/581629183159959584/790714206466605076/unknown.png

**Comment by 27136773** [comment]
It is [not working on their website](https://ww1.holymanga.com/aishiteru-uso-dakedo-chap-2/), because they are cross referencing images from `MangaNel` affiliates, without providing the correct refer HTTP header.
While this can basically be fixed in HakuNeko, i'm not sure if it is a good idea to introduce workarounds for things that didn't even work on their website...

```bash
curl 'https://s6.mkklcdnv6.com/mangakakalot/a1/aishiteru_uso_dakedo/chapter_2/1.jpg' -H 'Referer: https://manganelo.com' > /dev/null
```

**Comment by 27136773** [comment]
I recommend using `MangaNel` / `MangaKakalot` as workaround for these cross-referencing chapters.

We need to discuss if a specific hack should be added to `WordPressZbulu` (`HolyManga` / `HeavenManga`) or not.

**Comment by MikeZeDev** [comment]
Damn cross references not done properly byt the website itself. Yup i saw some Mangakalot CDN requests, some blogpost requests, and some Google proxy calls too that got me blocked because of heavy traffic (btw i dont use vpn ). Weird thing i dont see any setting about that in dev build (there was one before am i right? ).

And i must add that i can reproduce the same thing on Koomanga. I mean, take my screenshot, replace the Holymanga picture with a Koomanga one, same typo, same color, same everyting. On ANY manga, like on HolyManga.

Thanks anyway, i'll stick to other connectors then  :D

**Comment by MikeZeDev** [comment]
Holymanga seems to be dead, its redirecting to Amazon S3. Time to close this ticket i guess :p 
And KooManga redirect to google.

**Comment by 27136773** [comment]
Website is quite alive for me https://holymanga.net, just need to do manual website interaction first before using it.
The problem still persist for https://holymanga.net/aishiteru-uso-dakedo/

**Comment by MikeZeDev** [comment]
Weird. I was redirected on hakuneko and inside my browser a couple of hours ago. Now website is up again. Sorry about that i wanted to help you close some ticket :/
