### ISSUE TITLE
[Feature]Copy all Image source or html link in every manga chapters

### ISSUE THREAD

**Issue by abyssusagi** [manga-download/hakuneko#2807]
Hi, I want to suggest this idea, maybe this feature can help many others for their needs.

for example I attach it to the image below
https://ibb.co/nLQX8Kj

I hope this idea is accepted. but if not, it's okay. 

all of features right now i like it all. thanks

**Comment by 27136773** [comment]
I don't really see the point in copying the direct image links from HakuNeko, since some of them may also expire or are protected by a token based on the user agent / session cookie...

May be there would be a better solution to the problem, but to understand this the use case is required

**Comment by abyssusagi** [comment]
The use is to make it easier to create manga post on my own website. without having to host all my downloaded images to the hosting.

yeah you right, one of the issue is that not all images have active links or maybe its expired.

ok, i am just conveying my ideas which are obtained from my own issue. It's okay if this idea is not accepted. For the all I love Hakuneko. It makes me easy to collect manga.

**Comment by Sheepux** [comment]
If i understand well... You want hakuneko to help you feed your website with hotlinked content from another website ?

**Comment by abyssusagi** [comment]
No, I only suggest this features because of the problem of my needs, I think this is also can help other people of their needs.

therefore the idea arose to suggest this feature.

if this idea turns out to be unsuitable for most people, then it is not necessary. 

well known, the idea arises from several obstacles encountered, if the idea is needed by many people to increase their needs then the idea is successful, but if the idea is not needed by many people then the idea fails and is not feasible to run.

I just a users who like Hakuneko. let's think of another great idea that is more useful to many people and make hakuneko be the best application.

**Comment by Sheepux** [comment]
I mean... I dont understand your "idea" at all or what problem this is supposed to solve. As Ronny said unless you explain the use case we'll close the request because we dont understand

**Comment by abyssusagi** [comment]
it's okay,  make this issue solve,. thanks for hearing this unclear idea. heheh 


because I think, I have clearly explain the idea of the features and the uses.


I explain again, that the feature allows the user to copy the file link from each chapter of the image.

the goal is to make it easier for users who have a manga website to make posts without having to upload manga images that have been downloaded from Hakuneko into their own hosting.

So, they only need to make a post with the link of the image that has been taken in Hakuneko without making full of their hosting disk space because they upload all the manga images on their own hosting.

For the display maybe you can see the image at link above. You can see the example of copy image link box in the top right.

But it's okay, just make this issue solved, maybe I have wrong put this unclear and useless idea on here 😅 I'm sorry

**Comment by Sheepux** [comment]
This looks like exactly what's described as 'hotlinking' in my comment : https://github.com/manga-download/hakuneko/issues/2807#issuecomment-751348035 (embeding external content without hosting it).
HakuNeko will/should not help such use case as there is no value for HN users as described in 'what is hakuneko'.
Closing.
