### ISSUE TITLE
https://mangakakalot.com/

### ISSUE THREAD

**Issue by boruto211** [manga-download/hakuneko#2810]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://mangakakalot.com/
https://mangakakalot.com/manga_list?type=newest&category=all&state=Completed&page=1
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by vinh2201** [comment]
This website is already supported.

**Comment by Robonau** [comment]
^
