### ISSUE TITLE
[Site Request] Read Manga

### ISSUE THREAD

**Issue by ounsen** [manga-download/hakuneko#2811]
Read Manga
https://ww3.readopm.com/read-manga/

** https://ww3.readopm.com/read-manga/ **
- Site:       https://ww3.readopm.com/read-manga/
- Manga List:      https://ww3.readopm.com/read-manga/
- Manga example:      https://ww1.readjujutsukaisen.com/
- https://ww2.readkingdom.com/
- https://ww3.readopm.com/
- https://ww6.readmha.com/
- https://ww3.readdrstone.com/
- https://ww1.readchainsawman.com/      and many others

- Chapter online viewer example:    https://ww1.readjujutsukaisen.com/chapter/jujutsu-kaisen-chapter-0.1/

**Languages**
english 
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
The quality is very good and i think i never saw a team tag on panels

**Comment by 27136773** [comment]
This is part of MangaCruzers affiliates and already supported...

![image](https://user-images.githubusercontent.com/27136773/103015478-ca593700-4540-11eb-87fa-8fb2ce74f210.png)

**Comment by ounsen** [comment]
Ok thanks i was looking for it

**Comment by 27136773** [comment]
For Reference: https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/MangaCruzers.mjs#L13-L40
