### ISSUE TITLE
[Site Request] Le Cercle du Scan

### ISSUE THREAD

**Issue by Yunaxigf** [manga-download/hakuneko#2817]
**Name of the website**
Le Cercle du Scan

**Website urls (examples below)**
- Site: https: http://www.lecercleduscan.com/sorties/
- Manga List: https: http://www.lecercleduscan.com/projets/manga/
- Manga example: http://www.lecercleduscan.com/manga/31/
- Chapter online viewer example: https://lel.lecercleduscan.com/read/fff-class-trashero/fr/0/1/page/1

**Languages**
French

**Comment by MikeZeDev** [comment]
dead
