### ISSUE TITLE
[Mangadex] Slow / neverending list update

### ISSUE THREAD

**Issue by AnirudhKanaparthy** [manga-download/hakuneko#2818]
The **_Mangadex_** connector seems to be taking a very very long time to load, even if I leave it for hours it's still loading. All the other websites seem to be working very well, they load in a few minutes. I am using the macOS version of HakuNeko. I will thankful if you look into the matter. 

I am a very beginner in programming (I can understand c/cpp/js/py but cannot write "applicable" code). So please take in account my lack of experience in these matter and please be kind.

**Comment by Robonau** [comment]
Mangadex has one of the largest libraries of manga on HN, it also has one of the longest throttles (be default it can only get 1 page every 2.5 seconds) , you can check if it is still working by pressing f12 and going to the network tab (check console tab for any errors)

**Comment by Sheepux** [comment]
Usually it's 30mins for me with mangadex.

**Comment by JojiiOfficial** [comment]
Isn't there a way to run this requests concurrently with like 10 requests at the same time? I think this would drastically decrease the time for it to finish.

**Comment by Sheepux** [comment]
Without throttling the request, mangadex will then respond in error with 'too many reqquests'. So no it canot be improved because of the website itself. 

Did you finally retrieve the list  ?

**Comment by Sheepux** [comment]
No further response closing.
