### ISSUE TITLE
[tapas.io] Connector not working

### ISSUE THREAD

**Issue by Holydragoness** [manga-download/hakuneko#2820]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
[Yes]/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
[Yes]/No

**Describe the bug**

**To Reproduce**
1. Name of connector: https://tapas.io/
2. Name of manga (if connector update is working): After School Special
3. Name of chapter (if manga update is working): Chapter 6 onwards 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)- I think it's not relevant. 
Note: I have unlocked all the chapters using the ink so yeah. I have no clue what's going on and it's it on all comics/ manga found on the site. 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Chapter 7](https://user-images.githubusercontent.com/71577019/103154123-8003d000-4763-11eb-9539-6e5bbfe9a196.PNG)
![Chapter 6](https://user-images.githubusercontent.com/71577019/103154124-809c6680-4763-11eb-901e-dec30ba9850c.PNG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Did you log in via manual website interaction ?

**Comment by Holydragoness** [comment]
I use Facebook to log into my account on chrome.  
![Unable to use facebook to log in](https://user-images.githubusercontent.com/71577019/103234253-2fc87180-490d-11eb-9c93-88db6f715347.PNG)
Do you have a solution?

**Comment by Sheepux** [comment]
Oh, looks like some extra work for such case.
You could as a temporary solution copy your session cookies into hakuneko (in both Chrome & Hakuneko : F12 > Application > Cookies > the domain > copy the cookie values).
but that's kinda hacky

**Comment by Holydragoness** [comment]
So not recommended to copy session cookies and any alternative to copying cookie alternatives, ie make a new account or use Gmail to create ect

**Comment by Holydragoness** [comment]
I tried copying cookies with not much success. I might add I am literally very bad at mathematics so all the tech program stuff is going over my head sorry

**Comment by 27136773** [comment]
Standard popups are kind of disabled by using a HakuNeko specific implementations to prevent injection of malicious code into the electron framework (non-closing dialogs, repeated popups, ...)

Just login to tapas and add/set a password, then use E-Mail based login with your facebook mail and the password configured in tapas.
