### ISSUE TITLE
[Neox Scanlator] Connector not working

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#2821]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes and no

**Describe the bug**
.net works, but its not updated.
And if you try to download the latest chapter that is on `.com` but not in `.net` its returns all the chapters in .bin (html saying 404~).

**Screenshots**
![chrome_tzw6JfHSSI](https://user-images.githubusercontent.com/46169656/103158513-7303d280-479d-11eb-9ba5-7259398e1fe7.png)
![tfTAgwKkY6](https://user-images.githubusercontent.com/46169656/103158514-75662c80-479d-11eb-80b3-be7176c6fd88.png)
![3ybNQz66uy](https://user-images.githubusercontent.com/46169656/103158516-78f9b380-479d-11eb-99c0-f63ca7b04c79.png)
![hLiELUjMCs](https://user-images.githubusercontent.com/46169656/103158520-7bf4a400-479d-11eb-876f-f4aef9a2d5d9.png)
![notepad++_rrXXCs5FGm](https://user-images.githubusercontent.com/46169656/103158521-7eef9480-479d-11eb-89fb-37b613d90b70.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Sheepux** [comment]
Checked their discord, new domain .com is confirmed as main website.
