### ISSUE TITLE
[Site Request] NiAddES

### ISSUE THREAD

**Issue by djgerman10** [manga-download/hakuneko#2822]
**NiAddES**
es.niadd.com

**Website urls (examples below)**
- Site: https://es.niadd.com/
- Manga List: https://https://es.niadd.com/category/
- Manga example: https://es.niadd.com/original/10015857.html
- Chapter online viewer example: https://https://es.niadd.com/chapter/237/100227004/

**Languages**
Spanish

**Comment by 27136773** [comment]
See #816
