### ISSUE TITLE
[Mangaxin] domain change "Manga Boruto"

### ISSUE THREAD

**Issue by Monolity** [manga-download/hakuneko#2825]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Fill the form

**Comment by Monolity** [comment]
Did you read the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
No, in the Hakuneko browser it doesn't open, but when it is opened in mozilla firefox, mangaxin.com changes its name to pweination.org and can be seen

Describe the bug
The Mangaxin connector can not open

To Reproduce
Steps to reproduce the behavior:

Name of connector (Mangaxin)
Name of manga (if connector update is working)
Name of chapter (if manga update is working)
Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Screenshots
If complex to describe, add screenshots to help explain your problem.

![error mangaxin](https://user-images.githubusercontent.com/40449522/103194426-39080d00-4912-11eb-9588-48c9c7996823.jpg)

HakuNeko:

Version 6.17

**Comment by Sheepux** [comment]
Ok, this is not a simple domain change, looks like the new connector would be called "Manga Boruto" and needs a rewrite.
Wordpress Madara template (should be done  in a few days. Edit: done!)
