### ISSUE TITLE
Error when download

### ISSUE THREAD

**Issue by devilchild123456789** [manga-download/hakuneko#283]
Hi,

When I download on website http://www.nettruyen.com/, in the same manga, there are chapters that can be downloaded, but there are chapters that have errors.

![67433753_2402411603199543_758241244492070912_o](https://user-images.githubusercontent.com/50281682/61722285-36f06500-ad94-11e9-98ab-43712f1b185d.jpg)

**Comment by 27136773** [comment]
Which manga/chapters?
Are the same chapters working on their website in browser?

**Comment by devilchild123456789** [comment]
I don't understand what you mean.
I can read the error chapters when downloading with Hakuneko normally in the browser.
Now I will send you some manga with error chapters, you can check them yourself.

http://www.nettruyen.com/truyen-tranh/nong-nu-thu-sac (error 403: chap 4, chap 8-10, chap 15-16, chap 29-33)

http://www.nettruyen.com/truyen-tranh/ac-ma-dung-hon-toi (chap 10 error 403)

http://www.nettruyen.com/truyen-tranh/ngao-kieu-quy-vuong-yeu-ta/ (chap 33, 21 error 404)

http://www.nettruyen.com/truyen-tranh/ong-xa-thu-tinh-dem-dem-goi-tinh (chap 86 error 403)

**Comment by 27136773** [comment]
It was possible to reproduce the issue.
Proposed fix is to add the correct referer when HakuNeko requests the image (at least the origin url)
`curl 'https://proxy.truyen.cloud/?url=https://www.inithtml.com/img/wp-content/uploads/2019/06/0-13.jpg&hash=13afb5221e0b0f4b5f14135111ec0951' -H 'Referer: http://www.nettruyen.com/truyen-tranh/nong-nu-thu-sac/chap-4/476865'`

**Comment by devilchild123456789** [comment]
Please tell me how can I add the correct referer when HakuNeko requests the image to HakuNeko?

**Comment by 27136773** [comment]
"Proposed fix" means it needs to be done in source code (in contrast to a workaround which may be done on user side).
You need to wait until it gets implemented...

**Comment by 27136773** [comment]
The fix has been made for the next version (which is currently in public testing), but will not be merged into the current version 0.4.0
