### ISSUE TITLE
[Feature] Alternative titles

### ISSUE THREAD

**Issue by MarqFJA87** [manga-download/hakuneko#2830]
I've been reorganizing some of my folders now that I've replaced one of my almost full external hard drives with a much bigger one; this reorganization included moving both the HakuNeko manga directory and my main directory for all things manga to the new drive, now that I have enough space for both. Unfortunately, this ran into a serious problem: several of the downloaded manga have such long titles that they exceed the 256 character limit on folder/file paths, forcing me to repeatedly move the HakuNeko directory one level at a time, until I finally managed to stay within the limit by putting at the very top level (i.e. it's now "G:\HakuNeko"). Most of the problematic manga only required a single level rise to fix the problem, but one manga had an especially long title that forced the repeated moves: _[Even Though I'm a Former Noble and a Single Mother, My Daughters Are Too Cute and Working as an Adventurer Isn’t Too Much of a Hassle](https://mangadex.org/title/40978/)_, commonly shortened to _MotoMusu_. And yes, there are other manga with similarly super-long titles; I can dig them up if so desired.

The solution to the problem IMO seems fairly simple: have HakuNeko be able to detect the existence of alternative titles, and allow the user to pick one of them to use instead of the main title. An alternative solution would be to allow the user to change a bookmarked manga's title. HakuNeko already has a similar phenomenon where even when a manga's title on a site is changed, HakuNeko still retains the old title in its database and continues to operate as normal; it's only if the user for some reason unbookmarks and then rebookmarks the manga in question that the title is changed, and that the old folder has to be renamed accordingly in order for HakuNeko to detect any previously downloaded chapters.

My current HakuNeko Version is 6.17. The OS is Windows 10.

**Comment by Sheepux** [comment]
Something like right click > custom name > text input

**Comment by Robonau** [comment]
suggested alt names might be a good idea (mangaupdates would probably be the best source of alt names)

**Comment by MarqFJA87** [comment]
> suggested alt names might be a good idea (mangaupdates would probably be the best source of alt names)

MangaDex commonly provides alternative titles as well, though not everybody can **add** them. AFAIK only the staff, uploaders, and those with the "contributor" role could do it.

**Comment by 27136773** [comment]
HakuNeko is folder/file based, it cannot remember when a user select a different name for a manga and therefore it will not appear in the list anymore, the original being seen as not downloaded.

A fix can be added to the `sanitize` method, but i think this is a problem with windows itself and there is a registry hack to enable unlimited path length support
https://github.com/manga-download/hakuneko/blob/fb28c8efecbf32fc47388b054730ddb8132562a3/src/web/mjs/engine/Storage.mjs#L780

**Comment by MarqFJA87** [comment]
> HakuNeko is folder/file based, it cannot remember when a user select a different name for a manga and therefore it will not appear in the list anymore, the original being seen as not downloaded.

You mean if a manga's title was changed on MangaDex after I downloaded chapters from it, and then I checked MangaDex's list on HakuNeko, I'd see the new title and the old one as separate entries? Yet HakuNeko clearly uses the base URL (i.e. without tacking on the title, as MD links often get formatted), because even after a title change it can detect additions, removals and renamings of the manga's chapters.

> A fix can be added to the `sanitize` method, but i think this is a problem with windows itself and there is a registry hack to enable unlimited path length support
> https://github.com/manga-download/hakuneko/blob/fb28c8efecbf32fc47388b054730ddb8132562a3/src/web/mjs/engine/Storage.mjs#L780

What does this fix do, exactly? I don't mean in **technical** terms, just so we're clear.

**Comment by 27136773** [comment]
Requires to much effort => rejected
