### ISSUE TITLE
[SmackJeeves] Website is closing

### ISSUE THREAD

**Issue by Sheepux** [manga-download/hakuneko#2831]
"Earlier this year the admin sold it to Comico which is a webtoons site and they announced smackjeeves will be shutting down at the end of 2020"
The website will probably shut down in 3 days. This issue is to track and plan the removal of the connector

https://www.smackjeeves.com/notice/36

**Comment by MikeZeDev** [comment]
Remove this connector maybe? :)

**Comment by MikeZeDev** [comment]
Website removed in haru.
