### ISSUE TITLE
[MangaDropOut] no chapter appears

### ISSUE THREAD

**Issue by Monolity** [manga-download/hakuneko#2837]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**

**Is the website of the connector working properly / are you able to see the manga within your browser**
**No, Changed the address to https://manhwa.komiktap.co/**

**Describe the bug**
**no chapter appears, all empty chapters**

**To Reproduce**
1. Name of connector 
2. Name of manga (**MangaDropOut**) 
3. Name of chapter (if manga update is working), **no chapter appears, all empty chapters**
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/40449522/103331436-831afb00-4a98-11eb-8ad6-c1d75034c2e1.png)

**HakuNeko (please complete the following information):**
 - **Version 6.17**

**Comment by Sheepux** [comment]
Tried the domain change and it's ok, but the site name changed to "komiktap". I think that we should create a new connector.

Edit: There is already a komiktap connector with https://komiktap.in with the same content (as far as i can see)
What's the relationship with https://manhwa.komiktap.co/ ?
Edit2: probably the same migration as https://github.com/manga-download/hakuneko/issues/237#issuecomment-507784614
