### ISSUE TITLE
[Site Request] Mint Wood

### ISSUE THREAD

**Issue by HoneyBo** [manga-download/hakuneko#2838]
**Name of the website**
Mint Wood

**Website urls (examples below)**
- Site: https://www.mintwood.top/
- Manga List: https://www.mintwood.top/p/manga-eng.html
- Manga example: https://www.mintwood.top/2020/05/ad-lib-no-koi.html?m=1
- Chapter online viewer example: 
https://www.mintwood.top/2020/05/a-lib-no-koi-1.html?m=1
**Languages**
English, Indonesian

**Website relationship*
-/-

**Additional details**
-/-

**Comment by MikeZeDev** [comment]
Dead Website
