### ISSUE TITLE
[Site Request] Otakudesu

### ISSUE THREAD

**Issue by MoonLGH** [manga-download/hakuneko#2840]
**Name of the website**
Otakudesu

**Website urls**
- Site: https://otakudesu.tv/
- Anime List: https://otakudesu.tv/anime-list/
- Anime Web example: https://otakudesu.tv/anime/isekai-smartphone-sub-indo/
- Anime Online viewer example: https://otakudesu.tv/isepone-episode-1-sub-indo/

**Comment by manh21** [comment]
Reference: 

- [https://github.com/Kaede-No-Ki/otakudesu-rest-api](https://github.com/Kaede-No-Ki/otakudesu-rest-api)
- [https://github.com/YuuDrive](https://github.com/YuuDrive)

**Comment by Robonau** [comment]
![](https://i.imgur.com/zoIaXgD.png)
lel

**Comment by 27136773** [comment]
Region locked, Singapore works

**Comment by 27136773** [comment]
I just started to add the website, when i noticed there are direct download links for each anime episode.
So should we really add support for this in HakuNeko?

----

Current Status
```javascript
import WordPressMangastream from './templates/WordPressMangastream.mjs';
import Manga from '../engine/Manga.mjs';

export default class OtakuDesu extends WordPressMangastream {

    constructor() {
        super();
        super.id = 'otakudesu';
        super.label = 'Otaku Desu';
        this.tags = [ 'anime', 'indonesian' ];
        this.url = 'https://otakudesu.tv';
        this.path = '/anime-list/';

        this.querMangaTitleFromURI = 'div.infozin div.infozingle p span';
        this.queryMangas = 'div.venser div.daftarkartun div.jdlbar ul li a.hodebgst';
        this.queryChapters = 'div.episodelist ul li span a';
        this.queryChaptersTitle = undefined;
    }

    async _getMangaFromURI(uri) {
        const request = new Request(new URL(uri), this.requestOptions);
        const data = await this.fetchDOM(request, this.querMangaTitleFromURI);
        const title = data[0].textContent.replace(/judul\s*:/i, '').trim();
        return new Manga(this, uri, title);
    }

    async _getPages(chapter) {
        throw new Error('Not Implemented');
    }
}
```

**Comment by MoonLGH** [comment]
> I just started to add the website, when i noticed there are direct download links for each anime episode.
> So should we really add support for this in HakuNeko?
> 
> Current Status
> 
> ```js
> import WordPressMangastream from './templates/WordPressMangastream.mjs';
> import Manga from '../engine/Manga.mjs';
> 
> export default class OtakuDesu extends WordPressMangastream {
> 
>     constructor() {
>         super();
>         super.id = 'otakudesu';
>         super.label = 'Otaku Desu';
>         this.tags = [ 'anime', 'indonesian' ];
>         this.url = 'https://otakudesu.tv';
>         this.path = '/anime-list/';
> 
>         this.querMangaTitleFromURI = 'div.infozin div.infozingle p span';
>         this.queryMangas = 'div.venser div.daftarkartun div.jdlbar ul li a.hodebgst';
>         this.queryChapters = 'div.episodelist ul li span a';
>         this.queryChaptersTitle = undefined;
>     }
> 
>     async _getMangaFromURI(uri) {
>         const request = new Request(new URL(uri), this.requestOptions);
>         const data = await this.fetchDOM(request, this.querMangaTitleFromURI);
>         const title = data[0].textContent.replace(/judul\s*:/i, '').trim();
>         return new Manga(this, uri, title);
>     }
> 
>     async _getPages(chapter) {
>         throw new Error('Not Implemented');
>     }
> }
> ```

Y E S PLEASE

**Comment by MoonLGH** [comment]
gonna up this web on a new pr, imma close this one first
