### ISSUE TITLE
[Bug] Images not being sorted correctly, or in wrong order

### ISSUE THREAD

**Issue by iCreatedAnAccountForThis** [manga-download/hakuneko#2841]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When I download a manga to read later the images are saved correctly (ex. 01.jpg, 02.jpg, ... 23.jpg etc.) and this is how they appear in my file folders , but when I open to read them in the Haku viewer the images are out of order, page 0 is usually correct, but rarely it isn't, about 1/3 to 1/2 of the way through a manga the order becomes scrambled.

01, 02, 03, 04, 07, 06, 05, 08, 10, 09, 11, 12 sometimes it will be similar to this, but it has also happened around the end of a manga as well.

**To Reproduce**
1. download any manga that has more than 2 or 3 pages
2. scroll through downloaded manga pages
3. See error

**Expected behavior**
Pages to be ordered by file name instead of randomly assorted.

**Screenshots**
This is the explorer folder and it displays the manga pages in the correct (alphanumerical) order.
![explorer_iJ0o4NzpWb](https://user-images.githubusercontent.com/76821208/103431050-4df5d200-4b98-11eb-9f31-d409c4727698.png)
This one shows how the manga displays in Haku.
![hakuneko_fvvRgtZEql](https://user-images.githubusercontent.com/76821208/103431072-a036f300-4b98-11eb-9785-b043a2bd34cc.png)

**Context (please complete the following information):**
 - OS: Windows10 pro (64bit)
 - HakuNeko Version 6.17@c16c32
 - I have also tried the portable version (64bit), 32bit, 64bit, and a nightbuild version.

**Additional context**
This only happens when opening images locally (downloaded).

**Comment by Robonau** [comment]
can't reproduce

**Comment by 27136773** [comment]
Same for me, unable to reproduce ...

**Comment by DivineDelorog** [comment]
I have the same bug, Went to correct the file names, assumed the site had them wrong when I realized the names were in the correct order the reader was just displaying the images out of order.

Edit - I see that you are using a usb to store the data, I am doing the same..... I wonder if that's related somehow?
