### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by Artemis2017** [manga-download/hakuneko#2842]
**Name of the website**
readonepiece

**Website urls (examples below)**
- Site: https://ww8.readonepiece.com
- Manga List: 
- Manga example: https://ww8.readonepiece.com/manga/one-piece-digital-colored-comics/
- Chapter online viewer example: https://ww8.readonepiece.com/chapter/one-piece-digital-colored-comics-chapter-931/

**Languages**
List of languages supported by the website
- English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by vinh2201** [comment]
This website is already supported.

**Comment by manh21** [comment]
Rejected. See #2381
