### ISSUE TITLE
[AllHentai] Connector not working

### ISSUE THREAD

**Issue by kifat** [manga-download/hakuneko#2845]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't update manga lists and can't get the chapter lists
F12 - Network - maximum range is 11100 of 12960, hakuneko_6.1.7\userdata\hakuneko.mangas.allhentai is empty

**To Reproduce**
1. Name of connector - allhentai.ru
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
1 error and 4 warnings on start, no new errors when connector checking

**Screenshots**
[Screenshot](https://i.imgur.com/BoFntiR.png)

**HakuNeko (please complete the following information):**
 - Version 6.17-x64-portable

**Comment by Sheepux** [comment]
Able to reproduce the issue. List fetch was successfull until offset 11100 but no result. Investigating further ...
