### ISSUE TITLE
[Site Request] readcomiconline.to

### ISSUE THREAD

**Issue by xXSiLeNtScReAmXx** [manga-download/hakuneko#2851]
**Name of the website**
readcomiconline.to

**Website urls (examples below)**
- Site: https://readcomiconline.to/
- Manga List: https://readcomiconline.to/ComicList
- Manga example: https://readcomiconline.to/Comic/Dark-Tower-The-Battle-of-Jericho-Hill
- Chapter online viewer example: https://readcomiconline.to/Comic/Dark-Tower-The-Battle-of-Jericho-Hill/Issue-1?id=163865

**Languages**
English

**Website relationship*
expanded version of readcomicsonline.ru 

**Additional details**
edit-- i see the website is listed but gives an error that the website does not provide a comic list i have added the link to the comic list in the ticket

**Comment by 27136773** [comment]
Use copy & paste as stated in the popup message
https://hakuneko.download/docs/FAQ/#copy-and-paste
