### ISSUE TITLE
[Site Request] webtoon.xyz

### ISSUE THREAD

**Issue by Ta8Success** [manga-download/hakuneko#2866]
**Name of the website**
Webtoon.xyz

**Website urls (examples below)**
- Site: https://www.webtoon.xyz/
- Manga List: https://www.webtoon.xyz/webtoons/
- Manga example: https://www.webtoon.xyz/read/seeing-her-panties-lets-me-stick-in/
- Chapter online viewer example: https://www.webtoon.xyz/read/seeing-her-panties-lets-me-stick-in/chapter-31/

**Languages**
List of languages supported by the website

English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See: #1539

**Comment by Abhishek7779** [comment]
I also Cover the Topic in This Application because it's an amazing Application please everyone visits this ******** Application and download Latest Comics.

----

EDIT:
Wrong location for advertisement
Please suggest alternative applications in the corresponding ticket #2602
