### ISSUE TITLE
[Site Request] Lovehug

### ISSUE THREAD

**Issue by VetoDayDream7** [manga-download/hakuneko#2867]
**Website Name:**
Lovehug

**Website Url:**
https://Lovehug.net

**Manga list link:**
https://lovehug.net/manga-list.html

**Manga Example:**
https://lovehug.net/299/

**Chapter online viewer example:**
https://lovehug.net/299/11488/

**Languages:**
Website is in English, the manga in Japanese

**Website relationship:**
Loveheaven.net transferred to Lovehug.net, so loveheaven.net is not working anymore

**Comment by 27136773** [comment]
See #2864
