### ISSUE TITLE
[CentralDeMangas] Connector not working

### ISSUE THREAD

**Issue by eacj** [manga-download/hakuneko#2868]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When i try to load the manga list i get an popup error that says: "Failed to Update mangalist for CentralDeMangas.

**To Reproduce**
1. Select CentralDeMangas as connector
2. Click the synchronize button to load mangalist

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
The connector's code is actually epic !
`    _getMangaList( callback ) {
        callback( new Error( 'Please report this broken website on HakuNeko\'s GitHub project page.' ), undefined );
    }
    _getChapterList( manga, callback ) {
        callback( new Error( 'Please report this broken website on HakuNeko\'s GitHub project page.' ), undefined );
    }
    _getPageList( manga, chapter, callback ) {
        callback( new Error( 'Please report this broken website on HakuNeko\'s GitHub project page.' ), undefined );
    }`
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/CentralDeMangas.mjs
Ronny, wtf did you do years go ? :D
I guess we'll have to change this issue to a website request.
Also, domain changed https://centraldemangas.online/

**Comment by Robonau** [comment]
there is quite a few connectors that look like that

![](https://i.imgur.com/GMUwUJg.png)
