### ISSUE TITLE
[KomikCast] Connector not working

### ISSUE THREAD

**Issue by abyssusagi** [manga-download/hakuneko#2869]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When i try to load the manga list i get an popup error that says: "Failed to Update mangalist for KomikCast.

**To Reproduce**
1. Select KomikCast as connector
2. Click the synchronize button to load mangalist

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end, list is loading fine

**Comment by Sheepux** [comment]
Same message as here https://github.com/manga-download/hakuneko/issues/2840#issuecomment-753682642 when trying to browse website: 
Probably geoloc as well.
But i don't get any error when refreshing (the list is just empty)

**Comment by Robonau** [comment]
fine in UK, as sheep says probably a geolock
(does what sheep says when using a eu vpn)

**Comment by 27136773** [comment]
Try to use a Proxy or VPN
