### ISSUE TITLE
can't run hakuneko in Ubuntu 19.04

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#287]
i tried hakuneko in Ubuntu 19.04. with this version "hakuneko-desktop_0.4.0_linux_amd64.deb"
"[https://github.com/manga-download/hakuneko/releases/download/v0.4.0/hakuneko-desktop_0.4.0_linux_amd64.deb](url)". i instal and success but when i tried to run, nothing happen.
so can anyone help me?

**Comment by 27136773** [comment]
See #51
