### ISSUE TITLE
[Site Request] mangakane

### ISSUE THREAD

**Issue by fajri411** [manga-download/hakuneko#2875]
**Name of the website**
Mangakane

**Website urls (examples below)**
- Site: https://mangakane.com/
- Manga List: https://mangakane.com/daftar-komik/
- Manga example: https://mangakane.com/series/hiratsu-kawaii-shizu-kawaii/
- Chapter online viewer example: https://mangakane.com/hiratsu-kawaii-shizu-kawaii-chapter-1/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Theme: WordPressMangastream
