### ISSUE TITLE
[LELScan] Connector not working

### ISSUE THREAD

**Issue by lemssu** [manga-download/hakuneko#2877]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
All the manga of the connector "LELScan" have an empty manga list

**To Reproduce**
1. Name of connector : LELScan
2. Name of manga (if connector update is working) : All of them
3. Name of chapter (if manga update is working) : not working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : 

TypeError: Failed to fetch 
EventTarget {connector: LELScan, id: "https://lelscans.net/lecture-en-ligne-toriko.php", title: "Toriko", status: "available", chapterCache: Array(0), …}
Manga.mjs:153 _getUpdatedChaptersFromWebsite TypeError: Failed to fetch

**Screenshots**
![ptit problem](https://user-images.githubusercontent.com/77124202/103941283-ea871980-512e-11eb-99cc-36ef419412d6.PNG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by lemssu** [comment]
still not working btw chapters of Scan FR dont appear either

**Comment by Sheepux** [comment]
Are you using the nightly ?

**Comment by lemssu** [comment]
Nope

**Comment by lemssu** [comment]
ok its working now thanks there's the same problem of empty chapter's list on Scan FR, and it says nothing on the console about that i think

**Comment by Sheepux** [comment]
Make sure to open a dedicated issue for that.
