### ISSUE TITLE
Missing sites

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#288]
I'm sorry if this is a stupid question. so in 'Closed issues' there are sites that have been added in hakuneko example: 'KomikAV', 'KomBatch' but not in my software.
can anyone handle it?
![Capture](https://user-images.githubusercontent.com/45929526/61778745-89c82c00-ae29-11e9-9ef1-d63d80870bef.PNG)
In Picture is nothing KomikAV and KomBatch sites

**Comment by 27136773** [comment]
As announced on discord the current version 0.4.0 is feature frozen, only important bug fixes will be done.
All other changes are made to the next version, so either wait for its release or participate in canary testing #266.
