### ISSUE TITLE
Aloalivn, Manhuaus, 

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#2886]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I'm a Mac userTitles and chapters show but the pages are blank on preview and downloads as .bin file

**To Reproduce**
1. Aloalivn, Manhua Us, Manhuas
2. all titles and chapter have this issue (except Manhuas has a couple of titles still work while the rest do not.)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
    no error messages.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

<img width="1098" alt="Screen Shot 2021-01-08 at 3 20 01 PM" src="https://user-images.githubusercontent.com/70929406/104074533-3edcd880-51c5-11eb-9f2d-9cccf7e370d4.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by tsentered** [comment]
ManhuaEs is having this issue as well. Not sure if this is related to #2725 (fixed image extraction)

**Comment by 27136773** [comment]
Websites may change regularly to protect against HakuNeko, so the fix could already be outdated again

**Comment by tsentered** [comment]
Thanks

**Comment by tsentered** [comment]
Manga357 is doing it too

**Comment by 27136773** [comment]
Cannot be reproduced on my end. All websites are working fine for me with random manga (some are a little slow to load the images).

Testet:
- Aloalivn
- Manhua US
- ManhuaEs
- Manga357

**Comment by tsentered** [comment]
That’s strange, It’s definitely not importing images for me. I’ve checked on everything on my side including rebooting a few times.  All of these sites worked day before yesterday. I sent the snapshot so you can see that it’s real. So I’m not sure why you can’t duplicate the results other than if using Mac other than windows may be the key difference.

What I’m seeing from the issues page that there is a rash others are having similar problems with other connectors. Weird stuff.

**Comment by hesoyamma785** [comment]
i can't either download or read from those sites that were mentioned.
when i download a chapter there are some .bin files and nothing more

**Comment by Robonau** [comment]
Aloalivn
Manhua US
ManhuaEs
Manga347
are all having an issue
some more info for a dev 
https://github.com/manga-download/hakuneko/issues/2925#issuecomment-760201931
that comment sows why the images are failing, but i have no idea how to fix it

**Comment by Robonau** [comment]
nvm i can fix it

**Comment by tsentered** [comment]
Awesome! Thanks.
