### ISSUE TITLE
[Site Request] randomtranslations

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#2889]
**Name of the website**
randomtranslations

**Website urls (examples below)**
- Site: https://randomtranslations.com/
- Manga List: https://randomtranslations.com/manga/
- Manga example: https://randomtranslations.com/manga/the-future-i-want-is-not-ashes/
- Chapter online viewer example: https://randomtranslations.com/manga/the-future-i-want-is-not-ashes/chapter-13/

**Languages**
List of languages supported by the website
Eng

**Additional details**
Add any other context details that you may have found (like template to reuse)
Madara

**Comment by 27136773** [comment]
Theme: WordPressMadara
