### ISSUE TITLE
add support for https://m.manmanga.com/

### ISSUE THREAD

**Issue by paranoid73** [manga-download/hakuneko#289]
https://m.manmanga.com/

**Comment by paranoid73** [comment]
forgot ?

**Comment by 27136773** [comment]
There are currently 115 open issues that needs to be solved, this is one of them.
It may happen tomorrow or never, depending on the developers.
You will know this is done when the status is set to resolved/closed.

**Comment by Robonau** [comment]
dead site?

**Comment by MikeZeDev** [comment]
Dead site, can be closed i guess.

**Comment by MikeZeDev** [comment]
Dead website, no alternative link found. @Sheepux pls <3
