### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by valclmb** [manga-download/hakuneko#2890]
**Name of the website**
Littlexgarden 

**Website urls (examples below)**
- Site: https://littlexgarden.com/
- Manga List: https://littlexgarden.com/mangas
- Manga example:https://littlexgarden.com/one-piece
- Chapter online viewer example: https://littlexgarden.com/one-piece/1000/1

**Languages**
French

**Website relationship*
--

**Additional details**
Sorry I don't have anything, I ask this website because there is a french version of colorfull one piece

**Comment by 27136773** [comment]
#2794
