### ISSUE TITLE
[IMHentai] support for downloading GIF image format

### ISSUE THREAD

**Issue by ProbexVector** [manga-download/hakuneko#2894]
some Doujin now features animated pages (ex : Imhentai) which is a .gif files, but when downloading the page result 404 file not found because the program finding the pages of chapter files with JPEG or PNG and the actually files on server is GIF. making the chapter cannot be finished to download

**Comment by 27136773** [comment]
GIF is supported, provide sample website/manga/chapter for reproduction

**Comment by ProbexVector** [comment]
for example https://imhentai.com/gallery/597438/

![gambar](https://user-images.githubusercontent.com/43844629/104107904-c2481800-52f2-11eb-9d90-ddfd589f385d.png)

the last page is actually gif files but not downloaded, so the problem is from connector?

**Comment by ProbexVector** [comment]
i found new bug again for this web (imhentai.com). When downloading some manga/doujin that more than 1000 pages in 1 chapter (because it's batch).

after download finished, the program only download pages/chapter max to 1000 or (0~999.jpg) in download folder. above 1000 pages are not downloaded

**Comment by 27136773** [comment]
Yo may create a new Issue for this, page numbering is from `001` to `999`, so everything after `999` will start from the beginning and overwrite pictures from `001`
Also add link to the doujin that has more then 1000 pages...
