### ISSUE TITLE
[ReadKomik] Connector not working

### ISSUE THREAD

**Issue by mwehehehe** [manga-download/hakuneko#2895]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
readkomik site won't load on the app by copy paste the manga link / update the manga list, but can load fine on my google chrome

**To Reproduce**
1. ReadKomik
2. All manga
3. Name of chapter (if manga update is working)
4. Nothing show

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version6.17

**Comment by 27136773** [comment]
Website changed template to WordPressMangastream

**Comment by mwehehehe** [comment]
thanks! now it works
