### ISSUE TITLE
Add Dong ManManHua

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#29]
https://www.dongmanmanhua.cn/

**Comment by su0su0** [comment]
This is the official Simplified Chinese version of Line Webtoon

 The site structure is the same as ID linewebtoon-en & linewebtoon-zh (already working sources in HakuNeko).

 [DongmanManhua](https://www.dongmanmanhua.cn/) vs "[Line Webtoon (Chinese)](https://www.webtoons.com/zh-hant/)" source (linewebtoon-zh):
+ Different writing scripts: The existing linewebtoon-zh is in Traditional Chinese, aimed at readers from Taiwan, HK, etc. DongmanManhua uses Simplified Chinese, aimed at readers in Mainland China.
+ The same manga have different translations
+ 2 sites have different selection of manga and update schedules (DongmanManhua seems to have more new titles)
+ Both offer free manga without the need to log in.

**Comment by su0su0** [comment]
@ronny1982 I tested this source just now and it works perfectly (both list loading and directly pasting individual links). Thank you Ronny, you're the best!! tusen tack!

**Comment by su0su0** [comment]
I tested this source just now and it works perfectly (both list loading and directly pasting individual links). Thank you Ronny, you're the best!!
