### ISSUE TITLE
Manga Rock API

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#291]
> **From:** HakuNeko User

Most of the manga websites are blcoked in my country and currently I can't afford to by a vpn and needless to sat free ones arent really considered options. the current vpn I'm using is windscribe which has a low speed.
Out of this problems, Manga Rock's API wasn't blocked and I had downloaded gigs of bytes with it. But since HakuNeko have changed Manga Rock's downloading method from it's API to website itself, my days of using HakuNeko have been doomed. I wanted to ask if it's possible, consider bringing back the API option, if not as main, but as a seconday option.
Thanks for your time and effort.

**Comment by 27136773** [comment]
On Windows try [Psiphon3](https://www.psiphon3.com/en/download.html) set to `L2TP/IPSec` transportation mode

**Comment by 27136773** [comment]
Related: #258, #184

**Comment by 27136773** [comment]
No further response => closed
