### ISSUE TITLE
[Site Request] 3Friends Scans

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#2910]
**Name of the website**
3Friends Scans

**Website urls**
- Site: https://3friendscan.com/
- Manga List: https://3friendscan.com/manga/
- Manga example: https://3friendscan.com/manga/isekai-cheat-survival-meshi/
- Chapter online viewer example: https://3friendscan.com/2020/11/isekai-cheat-survival-meshi-capitulo-1/

**Languages**
Portuguese

**Template**
EastManga

**Comment by MikeZeDev** [comment]
Site is dead no alternative found.
