### ISSUE TITLE
[Enhancement] Incorrect NicoNico Seiga download notification

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#2918]
If you're not logged into your NicoNico account and attempt to download a chapter from a NicoNico Seiga manga, HakuNeko will fail to download it (it will create the folder for the chapter, but it will be empty), yet it will mark the chapter as successfully downloaded.

Please fix this so that it correctly labels it with the DOWNLOAD FAILED icon when this happens. I've missed some chapters because HakuNeko got logged out my account without me knowing, and it incorrectly told me that the chapters were downloaded.

**Comment by 27136773** [comment]
It is technically correct, when opening the chapter without being logged in, it is a chapter containing 0 pages.
What you are asking for is that a chapter with 0 pages should be treated as error instead of success.
This behavior is the same for any website, not just NicoNico Seiga.
