### ISSUE TITLE
[mangalek] Connector not working

### ISSUE THREAD

**Issue by satyogi** [manga-download/hakuneko#2919]
https://mangalek.com stop working please fix

**Comment by Robonau** [comment]
possibly same as #2929
timing out during initialize connector

**Comment by Bmswad1** [comment]
I am a user of tachiyomi and this site sometimes doesn't work for a day or a week
And eventually it returns to normal

**Comment by satyogi** [comment]
is there is a way to make it work?

**Comment by satyogi** [comment]
i cant Load the mangalek.com webpage from the connector list
or any other manga

**Comment by Robonau** [comment]
Handled by #2933

**Comment by satyogi** [comment]
can you show me video how to do it please

**Comment by 27136773** [comment]
There is nothing you can do except waiting for #2933 to be fixed
