### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#292]
> **From:** HakuNeko User

no anime is downloading

**Comment by 27136773** [comment]
Which website/anime/episode?
Is it working on the website?
Have you tried [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?
Have you tried [Manual Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection)?
What is shown in the [error console](https://github.com/manga-download/hakuneko/wiki/Troubleshooting#making-an-informative-help-request)?

**Comment by 27136773** [comment]
No response => closed
