### ISSUE TITLE
[loveheaven] Website changed to lovehug

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#2920]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I think the website loveheaven.net changed to weloma.net since that is what it get's redirected to whenever I got to loveheaven

**Comment by Robonau** [comment]
it changed to lovehug, which we already support
![](https://i.imgur.com/DdvEDbE.jpg)

**Comment by Sheepux** [comment]
will PR to remove loveheaven
