### ISSUE TITLE
[mundowuxia] Connector not working

### ISSUE THREAD

**Issue by devildonovash** [manga-download/hakuneko#2923]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
https://mundowuxia.com/
The images are not downloaded properly, it has the following format ".bin" Example 012.bin

Whats your operating system?
	--> Windows 10 64 bits

Which desktop client version are you using?
	--> rev 6.17

What is the rev. number?
	--> @17a6fb
	
Which settings have you set in HakuNeko?
	--> Default

**Comment by Robonau** [comment]
same as #2930
images hosted on imgur
