### ISSUE TITLE
[hentainexus] Connector not working 

### ISSUE THREAD

**Issue by ozmoz94** [manga-download/hakuneko#2924]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes and No 

the connector is working, we can see and download the mangas before the update, but we dont see the updated ones.

**Describe the bug**

updated mangas arent showing in the list.

-----

thank you for this program, i really like it.

**Comment by Robonau** [comment]
can't reproduce / don't really understand what you are saying
hit this button
![](https://i.imgur.com/tvrRBgj.png)
and it will update the list

if there are manga that dosn't appear on that list you can use the clipboard method (see [wiki](https://hakuneko.download/docs/FAQ/#copy-and-paste) for how) to view it in HN

**Comment by ozmoz94** [comment]
yeah i hit that button and the newer chapters were not showing on the list, but it was fixed somehow yesterday i could see all the new chapters, so you can close this thread i think, and thanks for responding :)
