### ISSUE TITLE
[Site Request] Hentai's Club

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#2927]
**Name of the website**
Hentai's Club

**Website urls**
- Site: https://hentaisclub.com/
- Manga List: https://hentaisclub.com/manga/
- Manga example: https://hentaisclub.com/manga/a-perverts-daily-life/
- Chapter online viewer example: https://hentaisclub.com/manga/a-perverts-daily-life/01/

**Languages**
Portuguese

**Comment by manh21** [comment]
Template: WordpressMadara

**Comment by XenonR** [comment]
Website seems dead. "Internal Server Error". Unlikely, but eventually geo-blocked? Please verify.

**Comment by 27136773** [comment]
Cannot be reached from Brasil or Portugal
