### ISSUE TITLE
[Mangahasu] Website not working

### ISSUE THREAD

**Issue by xrfc0** [manga-download/hakuneko#2928]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Manga list is loading but if you click on a title it loads for a minute or so and then it shows a red symbol or noting on the right window. If I update the manga list I get an error after 60 seconds  

**To Reproduce**
1. Mangahasu.se
2. Doesn't work with any manga on mangahasu
4. Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "http://mangahasu.se/0/0.html?ts=1610574252640&rd=0.09973418201264006" within the given timeout of 60 seconds!
    at Request.mjs:363

**HakuNeko (please complete the following information):**
 - Version 6.1.7@17a6fb

**Comment by Robonau** [comment]
similar to #2929 though only for the pages where the images are
![](https://i.imgur.com/AVzRMym.png)

**Comment by 27136773** [comment]
Handled by #2933
