### ISSUE TITLE
[MyReadingManga] Connector not working

### ISSUE THREAD

**Issue by luic-c** [manga-download/hakuneko#2929]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Copy and pasting links of manga from myreadingmanga.info does not work. If I tried to open the website from the connector list the page will fail to load.

**To Reproduce**
1. Load the MyReadingManga webpage from the connector list
2. The page shows the redirection loading screen, but after a few seconds it turns blank
3. The F12 screen shows the Dev tools being detached or sth like that.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17 stable on Windows

**Comment by Robonau** [comment]
might be a Js and cookies thing
![](https://i.imgur.com/ek6PnL6.png)

fetchUI times out, failing _initializeConnector, so it doesn't even get to the connector part

**Comment by 27136773** [comment]
As described in https://github.com/manga-download/hakuneko/issues/2885#issuecomment-757030395, electron currently cannot load the new CloudFlare challenge and ends up in a redirect loop...
Reasons are not clear right now, but probably something that needs to be fixed in electron itself

**Comment by 27136773** [comment]
Handled by #2933
