### ISSUE TITLE
[Site Request] turktoon

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#2931]
**turktoon**

- Site: https://turktoon.com/
- Manga List: https://turktoon.com/manga/
- Manga example: https://turktoon.com/manga/anecdotes-about-spirits-and-immortals/
- Chapter online viewer example: https://turktoon.com/anecdotes-about-spirits-and-immortals-0/

**Languages**   Turkish

**Comment by manh21** [comment]
Template: WordpressMangaStream
