### ISSUE TITLE
[WAKASCAN] Connector not working

### ISSUE THREAD

**Issue by sebastien-de-saint-florent** [manga-download/hakuneko#2932]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Timeout error on Wakascan when trying to sync managa list or when trying to access a chapter list of a bookmarked manga

**To Reproduce**
1. Open Wakascan connector
2. Try loading manga list
3. Error message is displayed:
![Capture-hakuneko-wakascan](https://user-images.githubusercontent.com/2699108/104735606-13686980-5742-11eb-8246-47e625db9a64.PNG)

**HakuNeko:**
 - Version 6.1.7

**Comment by 27136773** [comment]
Handled by #2933
