### ISSUE TITLE
[Site Request] Masterkomik

### ISSUE THREAD

**Issue by Sekiryute** [manga-download/hakuneko#2937]
**Name of the website**
Masterkomik

**Website**
- Site: https://masterkomik.com/
- Manga List: https://masterkomik.com/manga/
- Manga example: https://masterkomik.com/manga/the-life-after-god-of-martial-lived-in-seclusion/
- Chapter online viewer example: https://masterkomik.com/the-life-after-god-of-martial-lived-in-seclusion-chapter-01-bahasa-indonesia/

**Languages**
Indonesia

**Additional details**
Themesia Template

**Comment by 27136773** [comment]
Theme: WordPressMangastream
