### ISSUE TITLE
[Feature] MultiSelect Chapters

### ISSUE THREAD

**Issue by CrownCrafter** [manga-download/hakuneko#2938]
**Is your feature request related to a problem? Please describe.**
I send manga to my Kindle in MOBI files of about 350MB, so I download 90-100 chapters of a manga and convert it.
At the moment, I have to click download for each chapter

**Describe the solution you'd like**
A way to select more than one chapter and download all of the selected chapters

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Comment by Robonau** [comment]
you can filter the list with regex though i do agree shift and ctrl click should be an option (most ppl don't know how to use regex)

**Comment by 27136773** [comment]
What is the use case of multi selecting?

**Comment by CrownCrafter** [comment]
It would be good for a person who sends books to his ereader to 
read(like me). I don't download all the manga at once and instead, 
download about 400MB worth at once(because of size limitations of 
ebooks)
ronny1982 writes:

> What is the use case of multi selecting?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


--
Ayush M

**Comment by 27136773** [comment]
For chunked downloads `RegEx` seems to be sufficient enough since it is not difficult to filter chapter ranges 001 - 099, 100 - 199, 200 - 299, ...
For further information a sample website and manga with chapters is required

**Comment by sangorys** [comment]
Hello,

the filtering function is really great. The support of regex is incredible also.


In the same time, I share the improvement idea of CrownCrafter : selecting chapter with the mouse with ctrl and shift function would be perfect.

Eg. In 2 clicks I can select Chapter 33 to chapter 47 :

- I click on chapter 33
- I press shift and I click to chapter 47

With the filtering I need to define 15 filter : chapter 33 then chapter 34 then chapter 35, ...
Or maybe a regex can help but I am not skilled enough for that.

Do you think it is feasible to implement a selection ?

**Comment by sangorys** [comment]
This request is redundant with https://github.com/manga-download/hakuneko/issues/382

**Comment by 27136773** [comment]
See #382
