### ISSUE TITLE
[Site Request] http://mangazuki

### ISSUE THREAD

**Issue by thor171** [manga-download/hakuneko#2940]
**Name of the website**
mangazuki

**Website urls (examples below)**
- Site: http://mangazuki.cc
- Manga List: http://mangazuki.cc/
- Manga example: http://mangazuki.cc/manga/dr-stone
- Chapter online viewer example: http://mangazuki.cc/dr-stone-chapter-149#1

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: AnyACG (same as http://manganelos.com)

**Comment by XenonR** [comment]
Site response is only adverts. Site dead?

**Comment by 27136773** [comment]
Can confirm there is no content and domain is redirecting to empty response...
