### ISSUE TITLE
[Azoramanga] Connector not working

### ISSUE THREAD

**Issue by amrsabry** [manga-download/hakuneko#2942]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
 yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
yes
**Describe the bug**
The manga list is not showing any mangas
**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

oading Frontend: frontend@classic-dark
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
loadClassicPolymer @ index.html:76
VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
Settings.mjs:371 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
(anonymous) @ Settings.mjs:371
BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
(anonymous) @ BookmarkManager.mjs:137
azoramanga.com/wp-admin/admin-ajax.php:1 Failed to load resource: the server responded with a status of 400 ()
Connector.mjs:440 GET https://azoramanga.com/wp-admin/admin-ajax.php 400
fetchDOM @ Connector.mjs:440
_getMangasFromPage @ WordPressMadara.mjs:50
_getMangas @ WordPressMadara.mjs:42
_getMangaList @ Connector.mjs:582
(anonymous) @ Connector.mjs:105
Promise.then (async)
updateMangas @ Connector.mjs:104
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/49689918/104852245-756fcd00-5902-11eb-9c89-f9ffec9855eb.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Brief Investigation Result: https://github.com/manga-download/hakuneko/issues/2939#issuecomment-761837029

**Comment by Robonau** [comment]
not a "Too many consecutive Requests" issue 

https://www.azoramanga.com/wp-admin/admin-ajax.php
redirects to 
http://azoramanga.com/wp-admin/admin-ajax.php
and that redirects to 
https://azoramanga.com/wp-admin/admin-ajax.php
which has Status Code 400
(cause it lost its Search Params)

simple url change
