### ISSUE TITLE
[Queensmanga] Connector not working

### ISSUE THREAD

**Issue by amrsabry** [manga-download/hakuneko#2943]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
yes

**Describe the bug**
I can't download the images
**To Reproduce**
1. Name of connector Queensmanga
2. Name of manga (if connector update is working) all
3. Name of chapter (if manga update is working) all
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
DownloadJob.mjs:118 GET connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhOmltYWdlL2pwZztiYXNlNjQsLzlqLzRBQVFTa1pKUmdBQkFRRUFZQUJnQUFELy9nQTdRMUpGUVZSUFVqb2daMlF0YW5CbFp5QjJNUzR3SUNoMWMybHVaeUJKU2tjZ1NsQkZSeUIyTmpJcExDQnhkV0ZzYVhSNUlEMGdPVGtLLzlzQVF3QUJBUUVCQVFFQkFRRUJBUUVCQVFFQkFRRUJBUUVCQVFFQkFRRUJBUUVCQVFFQkFRRUNBZ0VCQWdFQkFRSUNBZ0lDQWdJQ0FnRUNBZ0lDQWdJQ0FnSUMvOXNBUXdFQkFRRUJBUUVCQVFFQkFnRUJBUUlDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQy84QUFFUWdPaWdMUUF3RWlBQUlSQVFNUkFmL0VBQjhBQUFFRkFRRUJBUUVCQUFBQUFBQUFBQUFCQWdNRUJRWUhDQWtLQy8vRUFMVVFBQUlCQXdNQ0JBTUZCUVFFQUFBQmZRRUNBd0FFRVFVU0lURkJCaE5SWVFjaWNSUXlnWkdoQ0NOQ3NjRVZVdEh3SkROaWNvSUpDaFlYR0JrYUpTWW5LQ2txTkRVMk56ZzVPa05FUlVaSFNFbEtVMVJWVmxkWVdWcGpaR1ZtWjJocGFuTjBkWFozZUhsNmc0U0Zob2VJaVlxU2s1U1ZscGVZbVpxaW82U2xwcWVvcWFxeXM3UzF0cmU0dWJyQ3c4VEZ4c2ZJeWNyUzA5VFYxdGZZMmRyaDR1UGs1ZWJuNk9ucThmTHo5UFgyOS9qNSt2L0VBQjhCQUFNQkFRRUJBUUVCQVFFQUFBQUFBQUFCQWdNRUJRWUhDQWtLQy8vRUFMVVJBQUlCQWdRRUF3UUhCUVFFQUFFQ2R3QUJBZ01SQkFVaE1RWVNRVkVIWVhFVElqS0JDQlJDa2FHeHdRa2pNMUx3RldKeTBRb1dKRFRoSmZFWEdCa2FKaWNvS1NvMU5qYzRPVHBEUkVWR1IwaEpTbE5VVlZaWFdGbGFZMlJsWm1kb2FXcHpkSFYyZDNoNWVvS0RoSVdHaDRpSmlwS1RsSldXbDVpWm1xS2pwS1dtcDZpcHFyS3p0TFcydDdpNXVzTER4TVhHeDhqSnl0TFQxTlhXMTlqWjJ1TGo1T1htNStqcDZ2THo5UFgyOS9qNSt2L2FBQXdEQVFBQ0VRTVJBRDhBL3Y0b29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29BS0tLS0FDaWlpZ0Fvb29vQUtLS0tBQ2lpaWdBb29vb0FLS0tLQUNpaWlnQW9vb29
(anonymous) @ DownloadJob.mjs:118
Promise.then (async)
(anonymous) @ DownloadJob.mjs:118
_downloadPages @ DownloadJob.mjs:116
(anonymous) @ DownloadJob.mjs:76
(anonymous) @ Chapter.mjs:116
_getPageList @ Connector.mjs:622
async function (async)
_getPageList @ Connector.mjs:621
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
DownloadJob.mjs:145 TypeError: Failed to fetch (22) ["connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…m9yLXRob3NlLWJyb3RoZXJzLzU1Lz9zdHlsZT1saXN0In0%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…m9yLXRob3NlLWJyb3RoZXJzLzU1Lz9zdHlsZT1saXN0In0%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…tdGhvc2UtYnJvdGhlcnMvNTUvP3N0eWxlPWxpc3QifQ%3D%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…tdGhvc2UtYnJvdGhlcnMvNTUvP3N0eWxlPWxpc3QifQ%3D%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…m9yLXRob3NlLWJyb3RoZXJzLzU1Lz9zdHlsZT1saXN0In0%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…tdGhvc2UtYnJvdGhlcnMvNTUvP3N0eWxlPWxpc3QifQ%3D%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…tdGhvc2UtYnJvdGhlcnMvNTUvP3N0eWxlPWxpc3QifQ%3D%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…tdGhvc2UtYnJvdGhlcnMvNTUvP3N0eWxlPWxpc3QifQ%3D%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…tdGhvc2UtYnJvdGhlcnMvNTUvP3N0eWxlPWxpc3QifQ%3D%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…m9yLXRob3NlLWJyb3RoZXJzLzU1Lz9zdHlsZT1saXN0In0%3D", "connector://queensmanga/?payload=eyJ1cmwiOiJkYXRhO…WZvci10aG9zZS1icm90aGVycy81NS8%2Fc3R5bGU9bGlzdCJ9"]
(anonymous) @ DownloadJob.mjs:145
Promise.catch (async)
_downloadPages @ DownloadJob.mjs:139
(anonymous) @ DownloadJob.mjs:76
(anonymous) @ Chapter.mjs:116
_getPageList @ Connector.mjs:622
async function (async)
_getPageList @ Connector.mjs:621
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
21Connector.mjs:723 Provided mime type "image/jpg" does not match the file signature and was replaced by "image/jpeg"!
_applyRealMime @ Connector.mjs:723
_handleConnectorURI @ Connector.mjs:686
async function (async)
_handleConnectorURI @ Connector.mjs:683
_handleConnectorURI @ WordPressMadara.mjs:105
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/49689918/104852307-e8794380-5902-11eb-8bed-79eeba8e39f5.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Brief Investigation Result: https://github.com/manga-download/hakuneko/issues/2939#issuecomment-761837029
