### ISSUE TITLE
[Mangalek] Connector not working

### ISSUE THREAD

**Issue by amrsabry** [manga-download/hakuneko#2944]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
yes
**Describe the bug**
Time out before loading all the mangas
**To Reproduce**
1. Name of connector Mangalek
2. Name of manga (if connector update is working) All of them
3. Name of chapter (if manga update is working) All of them
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Connector.mjs:723 Provided mime type "image/jpg" does not match the file signature and was replaced by "image/jpeg"!
_applyRealMime @ Connector.mjs:723
_handleConnectorURI @ Connector.mjs:686
async function (async)
_handleConnectorURI @ Connector.mjs:683
_handleConnectorURI @ WordPressMadara.mjs:105
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "https://mangalek.com/?ts=1610908537453&rd=0.9400800734720529" within the given timeout of 60 seconds!
    at Request.mjs:363
**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/49689918/104852446-c502c880-5903-11eb-8b7a-b6eadcb8b094.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Bmswad1** [comment]
Duplicate of #2919
