### ISSUE TITLE
[Site Request] AnimesHouse

### ISSUE THREAD

**Issue by MomonSam** [manga-download/hakuneko#2949]
**Name of the website**
AnimesHouse

**Website urls**

- Site: https://animeshouse.net/
- Animes List: https://animeshouse.net/anime/
- Anime example: https://animeshouse.net/episodio/kumo-desu-ga-nani-ka-episodio-1-legendado-hd/

**Languages**
Portuguese

**Additional details**
...

**Comment by 27136773** [comment]
Server Error from my End

**Comment by XenonR** [comment]
Server Error also for me. Considering site dead.  Closing issue since no further comment was made by author.
