### ISSUE TITLE
Add anime Sites H

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#295]
https://hentaiyosh.com/
this site is an Indonesian subtitles hentai anime site. and without proxy or vpn.
hope you can add the site
Thanks

**Comment by 27136773** [comment]
- Page Links are pointing to an Ad page with a redirect link.
- The redirect link can be found in `div#wpsafe-link a`
- After redirection to the real page, he video is embedded in an iframe `div.chapter-video-frame iframe`
- The iframe content contains the mp4 video source in plain javascript

**Comment by MIRVOUS** [comment]
This site changed the domain from "https://hentaiyosh.com/" to "https://hentaiyosh.xyz/"

**Comment by XenonR** [comment]
Website is suspended. Supposedly dead.

**Comment by XenonR** [comment]
Still suspended, also with VPN. Considering site dead.
