### ISSUE TITLE
[Lezhin Korean] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#2950]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The whole site works. Just specifically for this one manga, paid chapters don't work.

**To Reproduce**
1. Lezhin Korean
2. 딸도둑이 될래!
3. chapter 24
<img width="1120" alt="Screen Shot 2021-01-18 at 3 07 38 PM" src="https://user-images.githubusercontent.com/70831806/104958896-ed8bd080-599e-11eb-9931-262db7d37737.png">

4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Press F12 to open developer tools and check for error message in console tab. Also check network tab for failed image requests and provide what you see there

**Comment by jstefansson6** [comment]
![Screen Shot 2021-01-18 at 5 16 57 PM](https://user-images.githubusercontent.com/70831806/104967315-11581200-59b1-11eb-943d-566300876365.png)
You mean like this?

**Comment by 27136773** [comment]
Probably regression of #1955

**Comment by MikeZeDev** [comment]
Manga.mjs:153 _getUpdatedChaptersFromWebsite ReferenceError: __LZ_PRODUCT__ is not defined

Connector.mjs:618 TypeError: Cannot read property 'd2' of undefined
    at <anonymous>:10:67 EventTarget {manga: EventTarget, id: "10", title: "10 - 10 화", file: {…}, language: "ko-KR", …}
