### ISSUE TITLE
[Site Request] Minda Fansub

### ISSUE THREAD

**Issue by t432aa** [manga-download/hakuneko#2951]
**Name of the website**
Minda Fansub

**Website urls (examples below)**

- Site: https://www.mindafansub.com/
- Manga List: https://www.mindafansub.com/search/label/seri?&max-results=5
- Manga example: https://www.mindafansub.com/2021/01/i-tamed-tyrant-and-ran-away.html
- Chapter online viewer example: https://www.mindafansub.com/2021/01/i-tamed-tyrant-and-run-away-1-bolum.html

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
dead website. @Sheepux please? :p

**Comment by Sheepux** [comment]
alternative domain found: https://mindafansub.me/

**Comment by MikeZeDev** [comment]
This connector exists, and works. Can be closed @Sheepux pls.

**Comment by Sheepux** [comment]
Indeed, added Dec 31, 2021
