### ISSUE TITLE
[Site Request] Sakura Fansub

### ISSUE THREAD

**Issue by t432aa** [manga-download/hakuneko#2952]
**Name of the website**
Sakura Fansub

**Website urls (examples below)**
- Site: https://sakurafansub.com/
- Manga List: https://sakurafansub.com/manga/
- Manga example: https://sakurafansub.com/manga/i-raised-the-beast-well/
- Chapter online viewer example: https://sakurafansub.com/manga/i-raised-the-beast-well/bolum-1/

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Madara Theme

**Comment by 27136773** [comment]
See: #2343
