### ISSUE TITLE
[Site Request] Rocket Toon

### ISSUE THREAD

**Issue by dmr111** [manga-download/hakuneko#2953]
**Name of the website**
Rocket Toon

**Website urls (examples below)**
- Site: https://rktoon4.com/
- Manga List: https://rktoon4.com/?view=all
- Manga example: https://rktoon4.com/bbs/content.php?co_id=webtoon_gate&gate=toon1951
- Chapter online viewer example: https://rktoon4.com/bbs/board.php?bo_table=webtoon&wr_id=146751

**Languages**
Korean

**Comment by MikeZeDev** [comment]
Dead website. Parking page. 

@Sheepux please?  <3

**Comment by Sheepux** [comment]
no alternative domain found
