### ISSUE TITLE
[Scan FR] Connector not working

### ISSUE THREAD

**Issue by lemssu** [manga-download/hakuneko#2954]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The chapter's list is empty for any manga

**To Reproduce**
1. Name of connector : Scan FR
2. Name of manga (if connector update is working) : any manga
3. Name of chapter (if manga update is working) : not working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![github](https://user-images.githubusercontent.com/77124202/105093607-4fcdf980-5aa3-11eb-9b05-a1ffe038b33b.PNG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by lemssu** [comment]
the chapter list still empty

**Comment by 27136773** [comment]
Which manga?
From which country is connection made?
What is shown in the error console?

**Comment by 27136773** [comment]
Use nightly build or wait until merged into stable 6.1.7
