### ISSUE TITLE
Error message in console on startup

### ISSUE THREAD

**Issue by hesoyamma785** [manga-download/hakuneko#2960]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I just installed hakuneko 6.17 stable and when I pressed F12 and go to console tab , I saw this error : 

**Expected behavior**
index.html:46 Loading Engine: HakuNeko
hakuneko://plugins/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
Settings.mjs:300 Failed to load HakuNeko settings! Error: ENOENT: no such file or directory, open 'C:\Users\Hooman\AppData\Roaming\hakuneko-desktop\hakuneko.settings'
load @ Settings.mjs:300
index.html:61 Loading Frontend: frontend@classic-light
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
loadClassicPolymer @ index.html:76
Connector.mjs:221 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\Hooman\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.manhuaes'
(anonymous) @ Connector.mjs:221
VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (VRV.mjs:303)
    at EventTarget.save (Settings.mjs:322)
(anonymous) @ VRV.mjs:305
Promise.catch (async)
_onSettingsChanged @ VRV.mjs:304
save @ Settings.mjs:322
async function (async)
save @ Settings.mjs:321
closeSaveChanges @ menu.html:254
handler @ template-stamp.html:96
VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (VRV.mjs:303)
    at EventTarget.save (Settings.mjs:322)
(anonymous) @ VRV.mjs:305
Promise.catch (async)
_onSettingsChanged @ VRV.mjs:304
save @ Settings.mjs:322
async function (async)
save @ Settings.mjs:321
closeSaveChanges @ menu.html:254
handler @ template-stamp.html:96
VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (VRV.mjs:303)
    at EventTarget.save (Settings.mjs:322)
(anonymous) @ VRV.mjs:305
Promise.catch (async)
_onSettingsChanged @ VRV.mjs:304
save @ Settings.mjs:322
async function (async)
save @ Settings.mjs:321
closeSaveChanges @ menu.html:254
handler @ template-stamp.html:96
Connector.mjs:221 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\Hooman\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.manganel'.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/77359705/105218882-fb8e4c80-5b6a-11eb-9180-afda712220d8.png)
**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by Sheepux** [comment]
What is not working ?

**Comment by hesoyamma785** [comment]
I don't khow exactly why?
i uninstall and reinstall it for several times but this message shows every time.
And one more thing , it works perfectly until I change my windows and after that i got this problem.

**Comment by Sheepux** [comment]
It's just a message (usefull for devs in some cases). As long as everything is working that's not a problem.
The message "settings file missing" might be cause you didn't save any setting for now.

Closing this issue as there is no issue.
