### ISSUE TITLE
[GoldenManga] Connector not working

### ISSUE THREAD

**Issue by MomonSam** [manga-download/hakuneko#2961]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the website in the normal browser like chrome opens normal, already in HakuNeko it is in an infinite loop in the cloudflare.

**To Reproduce**
1. GoldenManga.top

**Screenshots**
![image](https://user-images.githubusercontent.com/77288905/105232149-ba844100-5b46-11eb-94a6-063291b4984d.png)

**HakuNeko (please complete the following information):**
 - Version [6.1.7@17a6fb]

**Comment by Robonau** [comment]
handled by #2933
