### ISSUE TITLE
[Site Request] Wolfdotcom

### ISSUE THREAD

**Issue by Shinrol** [manga-download/hakuneko#2963]
**Name of the website**
늑대닷컴 aka wolfdotcom 
**Website urls (examples below)**
- Site: https://wfwf130.com/ing
- Manga List: https://wfwf130.com/ing
- Manga example: https://wfwf130.com/list?toon=4876&title=%B0%ED%B1%B3%C8%A3%B1%B8%BF%D5
- Chapter online viewer example: https://wfwf130.com/view?toon=4876&num=49&title=%B0%ED%B1%B3%C8%A3%B1%B8%BF%D549%C8%AD

**Languages**
List of languages supported by the website - Korean

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Looks like Toonkor, they also change their domain regulary...
https://wfwf131.com

**Comment by MikeZeDev** [comment]
Dead?
