### ISSUE TITLE
[Site Request] Yaoibar

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2965]
Name of the website:
Yaoibar
•	Site:  https://www.yaoibar.com
•	Manga List: https://www.yaoibar.com/dizi-kategori/yaoi/
•	Manga example:  https://www.yaoibar.com/dizi/path-to-you/
•	Chapter online viewer example: https://www.yaoibar.com/bolum/path-to-you-1-sezon-1-bolum/
Language: Turkish
Site… I’m not sure but, I think it looks like this site: WEBMANGATR
https://webmangatr.com

**Comment by 27136773** [comment]
WordPress: https://en.keremiya.com/product/movifox/
