### ISSUE TITLE
[ Opiatoon&Shipperland ] Connector not working

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2969]
*Did you read [the troubleshooting guide?
Yes

*Is the website of the connector working properly / are you able to see the manga within your browser?
Yes

*Describe the bug*
Site is working. But usually says access security and wants captcha (verify: I’m a human) 
But in Hakuneko nothing changed. It just looks like in this picture.
And manga list not visible.

*To Reproduce*
1. Opiatoon&Shipperland    

![1](https://user-images.githubusercontent.com/65365181/105395211-8b95ca00-5c2f-11eb-84c2-e9c05b5e6c1f.png)

![1a](https://user-images.githubusercontent.com/65365181/105395304-a2d4b780-5c2f-11eb-972b-c5a4d24d2371.jpg)

**HakuNeko 
 - Version [6.1.7@17a6fb]

**Comment by Robonau** [comment]
handled by #2933
