### ISSUE TITLE
Please add h5.mangatoon.mobi

### ISSUE THREAD

**Issue by xerzo** [manga-download/hakuneko#297]
Hello can please add h5.mangatoon.mobi since some comic in https://mangatoon.mobi are locked
but not lock in h5.mangatoon.mobi example: god of martial arts Ch.140 its locked here https://mangatoon.mobi/en/watch/1816/25703 and but its unlocked here https://h5.mangatoon.mobi/cartoons/watch/1816/25703

**Comment by 27136773** [comment]
Proposed ID: MangaToonMobile

**Comment by XenonR** [comment]
Can't read the chapter on any of the links. Also it appears to be already implemented as `mangatoon-en`
