### ISSUE TITLE
[hayalistic] Connector not working

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#2970]
*Did you read [the troubleshooting guide?
Yes

*Is the website of the connector working properly / are you able to see the manga within your browser?
Yes

*Describe the bug*
Site is working. But usually says access security and wants captcha (verify: I’m a human) 
But in Hakuneko nothing changed. It just looks like in this picture.
And manga list not visible.

1.	Hayalistic
2.	Can't download any manga

![2](https://user-images.githubusercontent.com/65365181/105395905-563dac00-5c30-11eb-844a-a76553c9e750.jpg)

![2a](https://user-images.githubusercontent.com/65365181/105395941-5fc71400-5c30-11eb-8eb4-3406b0f75b42.jpg)

**HakuNeko (please complete the following information):**
 - Version [6.1.7@17a6fb]

**Comment by Robonau** [comment]
handled by #2933
