### ISSUE TITLE
[Manhua us] Connector not working

### ISSUE THREAD

**Issue by joebid** [manga-download/hakuneko#2971]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes, tried deleting cache and restarting, problem persists.

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes (please see attached screenshot of chapter 263 from manhuaus below)

![Image 3](https://user-images.githubusercontent.com/77820263/105443946-d81cec00-5ca7-11eb-882e-3344b5b6b2b4.png)

**Describe the bug**
Previously, working. Manga list updates successfully but only empty pages in several manga. Downloaded tiny empty 001.bin files. Other connectors/sites used do not have this problem.

**To Reproduce**
1. Name of connector: Manhua us
2. Name of manga (connector update is working): Against the Gods
3. Name of chapter (manga update is working): 262-267, different number of empty pages for each chapter in preview
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): no messages

**Screenshots**
![Image 1](https://user-images.githubusercontent.com/77820263/105443612-1960cc00-5ca7-11eb-9e00-b178f3157918.png)
![Image 2](https://user-images.githubusercontent.com/77820263/105443616-1a91f900-5ca7-11eb-9c3c-4b190809fc3f.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@17a6fb

**Comment by Robonau** [comment]
same as #2925
