### ISSUE TITLE
[NineMangaEn] Connector not working

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#2976]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hakuneko web open gardenmanage.com and not en.ninemanga.com

**To Reproduce**
1. NineMangaEn
2. All not working
3. All not working
4. When i open through firefox "en.ninemanga.com" Is working. When i open via hakuneko web, it open gardenmanage.com

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by Sheepux** [comment]
Can you do a screenshot on how/where you're seeing gardenmanage ?
The connector is working fine on my side.

**Comment by samanta-widjaja** [comment]
![IMG_20210125_083435.jpg](https://user-images.githubusercontent.com/53214405/105651000-2c161380-5ee8-11eb-8912-9d73590c299f.jpg)

**Comment by Sheepux** [comment]
Looks like an ad to me. Doesn't seem to be triggered on my side.
Maybe something that should be blacklisted, needs further investigation.

**Comment by 27136773** [comment]
Cannot be reproduced on my end, which country/region is used for HakuNeko when accessing the website?

![image](https://user-images.githubusercontent.com/27136773/108097770-e1209380-7082-11eb-8a9f-9c7e8f60e01d.png)

**Comment by samanta-widjaja** [comment]
I'm from Indonesia

**Comment by XenonR** [comment]
Confirmed, geoblocked from asia.
```json
{
  "ip": "45.133.181.42",
  "city": "Singapore",
  "region": "Singapore",
  "country": "SG",
  "loc": "1.2897,103.8501",
  "org": "AS9009 M247 Ltd",
  "postal": "048508",
  "timezone": "Asia/Singapore",
  "readme": "https://ipinfo.io/missingauth"
}
```
Response Headers:
```
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
cf-cache-status: DYNAMIC
cf-ray: 63825e562c9f1a11-SIN
cf-request-id: 09255949dd00001a11f417a000000001
content-type: text/html
date: Tue, 30 Mar 2021 15:28:34 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 19 Nov 1981 08:52:00 GMT
location: https://www.gardenmanage.com/
pragma: no-cache
server: cloudflare
set-cookie: __cfduid=d14808a0dde1bd2324ee3426d0fcd53861617118114; expires=Thu, 29-Apr-21 15:28:34 GMT; path=/; domain=.ninemanga.com; HttpOnly; SameSite=Lax; Secure
status: 302
x-powered-by: PHP/5.3.8
```
Unfortunately there is nothing we can do about that. Please use a VPN.
