### ISSUE TITLE
[mangarawclub] Connector not working

### ISSUE THREAD

**Issue by ExoAnime** [manga-download/hakuneko#2979]
Site; manga-raw.club
Manga; Forced to Become the Villain’s Son-in-law

Issue; Downloading the wrong file. 
;;; is downloading "gif".

İmage; 
![Ekran Alıntısı](https://user-images.githubusercontent.com/30474170/105577134-da0aac00-5d88-11eb-94a1-d30292beaa2a.JPG)
-https://ibb.co/rFj3Y84

![Ekran Alıntısı2](https://user-images.githubusercontent.com/30474170/105577219-29e97300-5d89-11eb-8567-7de0c6e9347e.JPG)
-https://ibb.co/sw9PPLf
5-15 seconds later
![Ekran Alıntısı3](https://user-images.githubusercontent.com/30474170/105577220-2d7cfa00-5d89-11eb-8917-387790d49d5d.JPG)
-https://ibb.co/ZxDR6KW

**Comment by Robonau** [comment]
i can't reproduce (no loading img for me)

**Comment by ExoAnime** [comment]
> i can't reproduce (no loading img for me)

There is no problem for now. But sometimes it downloads the file in the picture. I think the **site owner** is following here. 

downloaded file example ".gif" ; https://ibb.co/2NXFR8H
