### ISSUE TITLE
[ManhuaPlus] Issue on 1 title

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#2985]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
2 problems: 
1. for some reason in order to successfully download a chapter first you must hit the preview on the chapter before        downloading or you get .bin blanks.
2. Soul Land IV is producing and error. 
<img width="1258" alt="Screen Shot 2021-01-23 at 3 12 00 PM" src="https://user-images.githubusercontent.com/70929406/105617322-843b0180-5d92-11eb-815b-85bc164d961b.png">

It's a new title added to connector site and the only title having this issue. The site is working perfectly fine and I've tried a few tricks including rebooting, but no luck. BTW there is no logins or anything of the sort.

Thanks.

**To Reproduce**
1. Name of connector-  ManhuaPlus
2. Name of manga (if connector update is working)- Soul Land IV
3. Name of chapter (if manga update is working)- All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)- See above

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Can confirm, all chapters of this title are different than the rest of the site.
Seems to be related to the Server selector that is only seen on this title: https://manhuaplus.com/manga/soul-land-iv/chapter-160-5/

**Comment by Robonau** [comment]
one of the sites in something i jus did had this too

**Comment by Robonau** [comment]
https://github.com/manga-download/hakuneko/pull/2973/files#diff-dff5663c78c5561172e44666bb1624f6c9e7016c57df415bae5a2eba09810b51

**Comment by Robonau** [comment]
images not loading will be fixed by that pr as well so il do this in the same pr #2973

**Comment by tsentered** [comment]
Thank you.
