### ISSUE TITLE
Add support for website [AnimePahe]

### ISSUE THREAD

**Issue by Ziy5** [manga-download/hakuneko#299]
AnimePahe is an english website (like some of the ones already supported), but its file sizes are much smaller than the other websites.

Website link: animepahe.com

**Comment by 27136773** [comment]
Looks good
Technology: HLS hosted on kwik CDN

**Comment by newaccforhc** [comment]
@ronny1982 This site is good as it has Low-size High Quality encoded Anime... 
Please add support... Thanks!

**Comment by newaccforhc** [comment]
@ronny1982 You can get some hints here: 
1. https://github.com/vn-ki/anime-downloader 
(https://github.com/vn-ki/anime-downloader/blob/master/anime_downloader/sites/animepahe.py)

2. https://gitlab.com/apmariano/animepahe-scraper/blob/master/anime.py
