### ISSUE TITLE
golden manga المانجا الذهبية

### ISSUE THREAD

**Issue by mohamed12101** [manga-download/hakuneko#2990]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
no images after download
**To Reproduce**
1. golden manga
2. all mangas not working
3. nothing works
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #2961
