### ISSUE TITLE
[Site Request] Comic Space

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#2991]
**Name of the website**
Comic Space

**Website urls**
- Site: https://www.acomic.space/
- Manga List: https://www.acomic.space/manga-list
- Manga example: https://www.acomic.space/manga/4-cut-hero
- Chapter online viewer example: https://www.acomic.space/manga/4-cut-hero/1

**Languages**
Portuguese

**Comment by MikeZeDev** [comment]
dead website?
