### ISSUE TITLE
[MangaFreak] Connector not working

### ISSUE THREAD

**Issue by ibrahimovsergei** [manga-download/hakuneko#2993]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Cannot fetch manga database from MangaFreak

**To Reproduce**
1. MangaFreak
2. All manga in its database
3. All manga in its database
4. Refer https://i.imgur.com/SDkW7I9.png , I suspect you need to change its url as the old .mjs is https://mangafreak.net and the new one is https://w11.mangafreak.net/

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Robonau** [comment]
cloudflare issue #2989

**Comment by 27136773** [comment]
Handled by #2933
