### ISSUE TITLE
[Japanread] Connector not working

### ISSUE THREAD

**Issue by zazouze** [manga-download/hakuneko#2995]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
La protection cloudflare bloque le chargement du connecteur 

**To Reproduce**
1. Name of connector : Japanread
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/62121714/105895665-143cad80-6016-11eb-8299-aea48e953c5a.png)
![image](https://user-images.githubusercontent.com/62121714/105895769-359d9980-6016-11eb-9e92-fc2cac397870.png)

**HakuNeko (please complete the following information):**
 - Version [6.1.7@HEAD]

**Comment by zazouze** [comment]
![image](https://user-images.githubusercontent.com/62121714/105897763-e3aa4300-6018-11eb-8164-c6cf5bb37519.png)

**Comment by Sheepux** [comment]
Will be fixed by #2989

**Comment by 27136773** [comment]
See: #2933
