### ISSUE TITLE
[Site Request] wbnovel

### ISSUE THREAD

**Issue by zenkijoe** [manga-download/hakuneko#2996]
**Wbnovel**
thewebsitename

**Website urls (examples below)**
- Site: https://wbnovel.com/
- Manga List: https://wbnovel.com/novel/
- Manga example: https://wbnovel.com/novel/reverend-insanity/
- Chapter online viewer example: https://wbnovel.com/novel/reverend-insanity/chapter-432/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Template: WordpressMadaraNovel

**Comment by 27136773** [comment]
See: #2796
