### ISSUE TITLE
[Scan FR] Connector not working

### ISSUE THREAD

**Issue by Eswann-G** [manga-download/hakuneko#2997]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The list of chapters is empty while the website is accessible and working, even from the HakuNeko window.

**To Reproduce**
1. Name of connector : Scan FR
2. Name of manga (if connector update is working) : Ryushika but also many others.
3. Name of chapter (if manga update is working) : nothing
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : nothing

Whats your operating system?
Windows 10

Which desktop client version are you using (e.g. 0.3.1)?
Windows 64-Bit Setup
version 6.1.7 

What is the rev. number (e.g. 0c3bac, shown at the top right of HakuNeko’s settings menu)?
rev 6.1.7@17a6fb

Which website / manga / chapter did not work (only if applicable)?
The site is scan fr and the manga is ryushika, even if it is very frequent that other manga don't work on this website.

Which settings have you set in HakuNeko (especially Chapter Naming Format, Host Connections and Output File Format)
I didn't change anything.

What is shown in the error log after the problem occurs (press F12 key and select the console tab)?
There is no error message.

**Comment by 27136773** [comment]
Cannot be reproduced on my end (but image download from their server is extremely slow...)

![image](https://user-images.githubusercontent.com/27136773/106393360-f2b53a80-63f6-11eb-80d6-8ee19dbae9a9.png)

**Comment by 27136773** [comment]
See: #2954
