### ISSUE TITLE
[Skymanga] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#2999]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Fails to connect.

**To Reproduce**
1. Skymanga

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
will be fixed by #2989 see #2933
