### ISSUE TITLE
webp

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#300]
> **From:** HakuNeko User

All the sudden when downloading in folder format from mangarock it is only downloading it in webp format.

**Comment by 27136773** [comment]
This is expected behavior, because the images hosted through MangaRock are in `webp` format.

![image](https://user-images.githubusercontent.com/27136773/62421879-9b22fb00-b6a9-11e9-84ee-731bd5fbd7fa.png)
