### ISSUE TITLE
[Site Request] Hodu235

### ISSUE THREAD

**Issue by ExoAnime** [manga-download/hakuneko#3000]
**Name of the website**
Hodu235

**Website urls (examples below)**
- Site: https://hodu235.com/
- Manga List: https://hodu235.com/
- Manga example: https://hodu235.com/%EC%9B%B9%ED%88%B0/%EB%B3%84%EC%9D%B4%EC%82%BC%EC%83%B5
- Chapter online viewer example: https://hodu235.com/%EB%B3%84%EC%9D%B4%EC%82%BC%EC%83%B5-1%ED%99%94-%EB%91%90%EB%B2%88%EC%A7%B8-%EC%B2%AB%EC%82%AC%EB%9E%91.hodu

**Languages**
Korean

**Comment by 27136773** [comment]
Same Layout as Toonkor (probably also domain changing strategy 233, 234, 235, ...)

**Comment by MikeZeDev** [comment]
SSl errors

**Comment by MikeZeDev** [comment]
Dead?
