### ISSUE TITLE
[11toon ] waiting for details ...

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#3001]
Found some bugs.
1. What appears to be a typical website search, but not a program search.

2. The phenomenon of not bringing in all table of contents
ex. There should be up to episode 30, but there are parts that are missing.

3. The phenomenon of not downloading even if you find the table of contents.

**Comment by Sheepux** [comment]
When creating an issue please use the template  or give the adequate details as we're not able to guess were is your issue exactly.
https://github.com/manga-download/hakuneko/issues/new?assignees=&labels=Website+Change&template=1-connector-website-not-working.md&title=%5BNameOfConnector%5D+Connector+not+working

1) what does that mean ?
2) what does that mean, what manga are you talking about
3) what does that mean ?

**Comment by ghost** [comment]
1. website search(chrome, IE, firefox, edge and etc.) -> all title search able / hakuneko program search -> some title not search
2. website search -> all episode 1 - 30 found -> / hakuneko program search -> not all episode 11 - 30 found
3. If there's a single picture in the post that's damaged -> not working download

**Comment by Sheepux** [comment]
As i asked, please give the manga name having issue. 
We're not all-knowing gods that can guess wich one is bugged within the 11358 titles.

for 3) that's a normal behavior. There is currently no feature to handle such case

**Comment by Robonau** [comment]
11toon shouldn't work at all right now, the cloudflare issue should break it 

#2962 will fix any other issues

**Comment by Sheepux** [comment]
It's working fine for me.

**Comment by Robonau** [comment]
i just get 
![](https://i.imgur.com/AuvCOog.png)
though it does seem to be working somehow, idk

**Comment by 27136773** [comment]
No further response which manga does not list all chapters
=> closed
