### ISSUE TITLE
[Site Request] Kakaopage ID

### ISSUE THREAD

**Issue by gilangsatria09** [manga-download/hakuneko#3004]
**Name of the website**
Kakaopage ID

**Website urls (examples below)**
- Site: https:https://kakaopage.co.id/
- Manga List: No manga list, similiar to webtoon
- Manga example: https://kakaopage.co.id/content/Virtue-of-the-Villainess/3344
- Chapter online viewer example: https://kakaopage.co.id/viewer/Virtue-of-the-Villainess-Prolog/154698

**Languages**
Only Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
I tried to reuse the tapas templete, and success to get the manga info, but when i want to get the list of chapters, i need to authtenticate. I don't know how to do that, so if you can add new kakaopage connector, i would be greatful

**Comment by Ever4engel** [comment]
related to [#200](https://github.com/manga-download/hakuneko/issues/200)
