### ISSUE TITLE
[MangaDex] Legacy Reader Discontinued

### ISSUE THREAD

**Issue by Lumiinon** [manga-download/hakuneko#3005]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

MangaDex just removed their Legacy Reader: https://mangadex.org/thread/409315.  Seems this has broken all MangaDex functionality.  Looks like they implemented a new API though which is probably all that needs to be updated.

**Comment by kgiroux** [comment]
Another problem on Mangadex, .bin files download instead of png file

**Comment by Lumiinon** [comment]
> 
> 
> Another problem on Mangadex, .bin files download instead of png file

Saw that as well.  I assume it's related.

**Comment by 27136773** [comment]
HakuNeko does not scrape from the reader, it uses the REST API, therefore this is probably an issue on MangaDex right now

**Comment by Lumiinon** [comment]
> 
> 
> HakuNeko does not scrape from the reader, it uses the REST API, therefore this is probably an issue on MangaDex right now

Previews don't even load in the reader either.  https://mangadex.org/thread/351011  As far as MangaDex is concerned, the v1 API is deprecated moving forward (even though I guess it's still technically around).  http://sizer99.com/pmd/  Polite MangaDex Reader had to make changes already surrounding the new API.  I can 100% tell you this is not an issue with MangaDex as I'm able to download using PMD (and other readers) no problem.

**Comment by kgiroux** [comment]
New API / `{
	"code": 200,
	"status": "OK",
	"data": {
		"information": "Authentication is achieved by the same means as logging in to the site (i.e. the mangadex_session, mangadex_rememberme_token cookies, correct User-Agent). Some chapters may require authenticated permissions to access. The Content-Type header for requests with bodies must be application\/json, and the content must be valid JSON. Boolean query values are evaluated 1\/true\/on\/yes for true, otherwise false.",
		"baseUrl": "https:\/\/api.mangadex.org\/v2\/",
		"resources": {
			"GET \/": {
				"description": "The current page, the API index.",
				"aliases": ["index"]
			},
			"GET \/manga\/{id}": {
				"description": "Get a manga.",
				"aliases": ["title"],
				"pathParameters": {
					"{id}": "The manga ID number."
				},
				"queryParameters": {
					"include": "(Optional) Possible values: chapters (Include partial chapter information)."
				},
				"subResources": {
					"GET \/manga\/{id}\/chapters": {
						"description": "Get partial information about the chapters belonging to a manga.",
						"queryParameters": {
							"p": "(Optional) The current page of the paginated results, starting from 1. Integer, default disables pagination.",
							"limit": "(Optional) The limit of the paginated results, allowed range 10 - 100. Integer, default 100.",
							"blockgroups": "(Optional) Do not include chapters by groups blocked by the user. Boolean, default true."
						}
					},
					"GET \/manga\/{id}\/covers": {
						"description": "Get a list of covers belonging to a manga."
					}
				}
			},
			"GET \/chapter\/{id|hash}": {
				"description": "Get a chapter. Possible error codes: 410 (deleted), 403 (restricted), 451 (unavailable).",
				"pathParameters": {
					"{id|hash}": "The chapter ID number, or the chapter hash."
				},
				"queryParameters": {
					"server": "(Optional) Use to override location-based server assignment. Possible values: na, na2.",
					"saver": "(Optional) Use low quality images (data saver). Boolean, default false.",
					"mark_read": "(Optional) Mark the chapter as read. Boolean, default true."
				}
			},
			"GET \/group\/{id}": {
				"description": "Get a group.",
				"pathParameters": {
					"{id}": "The group ID number."
				},
				"queryParameters": {
					"include": "(Optional) Possible values: chapters (Include partial chapter information)."
				},
				"subResources": {
					"GET \/group\/{id}\/chapters": {
						"description": "Get partial information about the chapters belonging to the group.",
						"queryParameters": {
							"p": "(Optional) The current page of the paginated results, starting from 1. Integer, default disables pagination.",
							"limit": "(Optional) The limit of the paginated results, allowed range 10 - 100. Integer, default 100.",
							"blockgroups": "(Optional) Do not include chapters by groups blocked by the user. Boolean, default true."
						}
					}
				}
			},
			"GET \/user\/{id}": {
				"description": "Get a user.",
				"pathParameters": {
					"{id}": "The user ID number, or the string 'me' as an alias for the current cookie-authenticated user."
				},
				"queryParameters": {
					"include": "(Optional) Possible values: chapters (Include partial chapter information)."
				},
				"subResources": {
					"GET \/user\/{id}\/chapters": {
						"description": "Get partial information about the chapters uploaded by the user.",
						"queryParameters": {
							"p": "(Optional) The current page of the paginated results, starting from 1. Integer, default disables pagination.",
							"limit": "(Optional) The limit of the paginated results, allowed range 10 - 100. Integer, default 100.",
							"blockgroups": "(Optional) Do not include chapters by groups blocked by the user. Boolean, default true."
						}
					},
					"GET \/user\/{id}\/settings": {
						"description": "(Authorization required) Get a user's website settings."
					},
					"GET \/user\/{id}\/followed-manga": {
						"description": "(Authorization required) Get a user's followed manga and personal data for them. The target user's MDList privacy setting is taken into account when determining authorization.",
						"queryParameters": {
							"type": "(Optional) Filter the results by the follow type ID (i.e. 1 = Reading, 2 = Completed etc). Use 0 to remove filtering. Integer, default 0.",
							"hentai": "(Optional) Filter results based on whether the titles are marked as hentai. 0 = Hide H, 1 = Show all, 2 = Show H only. Integer, default 0."
						}
					},
					"GET \/user\/{id}\/followed-updates": {
						"description": "(Authorization required) Get the latest uploaded chapters for the manga that the user has followed, as well as basic related manga information. Ordered by timestamp descending (the datetime when the chapter is available). Limit 100 chapters per page. Note that the results are automatically filtered by the authorized user's chapter language filter setting.",
						"queryParameters": {
							"p": "(Optional) The current page of the paginated results. Integer, default 1.",
							"type": "(Optional) Filter the results by the follow type ID (i.e. 1 = Reading, 2 = Completed etc). Use 0 to remove filtering. Integer, default 0.",
							"hentai": "(Optional) Filter results based on whether the titles are marked as hentai. 0 = Hide H, 1 = Show all, 2 = Show H only. Integer, default 0.",
							"delayed": "(Optional) Include delayed chapters in the results. Boolean, default false.",
							"blockgroups": "(Optional) Do not include chapters by groups blocked by the user. Boolean, default true."
						}
					},
					"GET \/user\/{id}\/ratings": {
						"description": "(Authorization required) Get a user's manga ratings."
					},
					"GET \/user\/{id}\/manga\/{mangaId}": {
						"description": "(Authorization required) Get a user's personal data for any given manga.",
						"pathParameters": {
							"{mangaId}": "The manga ID number."
						}
					}
				}
			},
			"POST \/user\/{id}\/marker": {
				"description": "(Authorization required) Set or unset chapter read markers.",
				"pathParameters": {
					"{id}": "The user ID number, or the string 'me' as an alias for the current cookie-authenticated user."
				},
				"jsonBodyParameters": {
					"chapters": "(Required) Array[Integer]. List of chapter IDs to set or unset. Max 100 items.",
					"read": "(Required) Boolean. Set or unset the chapter as read."
				}
			},
			"GET \/tag": {
				"description": "Get all tags."
			},
			"GET \/tag\/{id}": {
				"description": "Get a tag."
			},
			"GET \/relations": {
				"description": "Get all manga relation types."
			},
			"GET \/follows": {
				"description": "Get all follow types."
			}
		}
	}
}`

**Comment by 27136773** [comment]
I don't have any issues with random manga from MangaDex in HakuNeko 6.1.7, so if there is a manga not working, please provide more details such as manga / chapter / error console output / ...

![image](https://user-images.githubusercontent.com/27136773/106386142-e4095c00-63d3-11eb-81e7-0b5aca5006e2.png)

**Comment by Robonau** [comment]
no issues either, but it seems the mangadex api has been having issues over the last week or so 
its on mangadex's side though, nothing to do with HN

**Comment by Sheepux** [comment]
I'm getting http 502 on every image (tried S2, S3, S5 and many many titles). I'll retry at the end of the week.

**Comment by 27136773** [comment]
Confirmed, seems to be a problem with their backend servers.
When using `Random Mirror` aka MangaDex@Home distributed nodes, it works...

**Comment by doppler56** [comment]
There maybe multiple issues here.  I can confirm what kgiroux said about bin files generated.
If you view: https://mangadex.org/title/47371/a-breakthrough-brought-by-forbidden-master-and-disciple
Chapter 9 is fine, it's new content since the problem started.  but:!
If you download chapter 8, just 1 month older you get ###.bin files that all have the content of...

502 Bad Gateway
------------------------------------
openresty

Using random mirror may only pull the latest chapter not the oldest.  Old one's get a bin file.  BTW, I am not using the hakuneko viewer/read.  I just download them.
BTW, all new content is fine (haku is good even with legacy turned off).  Only problem if you want to start a new manga and view the older stuff.
edit: Bold text is not my doing, I just pasted the bin contents.

**Comment by doppler56** [comment]
@ronny1982 @kgiroux @Sheepux  This maybe fixed now.  Or I found an accidental fix.  I enabled the reader.  Read a former non working chapter, "Worked".  Disabled Neko reader.  Still worked.  I really don't thing the reader was involved.  I really think it's fixed now.

**Comment by Sheepux** [comment]
S2 & S3 servers have been fixed yesterday on mangadex side (we discussed about it on the discord).
Lots of people confirmed it's now working fine. I'm closing this issue (we didn't change anything in HN).
