### ISSUE TITLE
[Toonily.com] Connector not working

### ISSUE THREAD

**Issue by Aaveparthe** [manga-download/hakuneko#3006]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Message: Failed to update manga list for Toonily, failed to load within the given timeout of 60 seconds!

**To Reproduce**
1. Pick Toonily from connectors
2. Refreshing/synchronize local manga list with online list from <Toonily>
Pop-up error appears.

**HakuNeko (please complete the following information):**
 - Version nightly 8.3.4 amd64, rev. master@41af97
 - Version stable 6.1.7 amd64

**Comment by 27136773** [comment]
See: #2933
