### ISSUE TITLE
[Site Request] Manga Tepesi

### ISSUE THREAD

**Issue by RoyalHatB** [manga-download/hakuneko#3008]
Mangatepesi.com
Manga Tepesi

- Site: https://mangatepesi.com
- Manga List: https://mangatepesi.com/mangalistesi
- Manga example: https://mangatepesi.com/manga/strongest-anti-meta/4
- Chapter online viewer example: https://mangatepesi.com/manga/strongest-anti-meta/bolum-206/1278

**Languages**
Turkish

**Website relationship*
None

**Additional details**
You should add this website, it has webtoons which other websites not

**Comment by 27136773** [comment]
See: #1725
