### ISSUE TITLE
[Comic Trail] Connector not working

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#3009]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Comic Trail connector no longer works, as they just changed its system to the one used by 少年ジャンプ＋ (Shonen Jump +) (and many others).

**To Reproduce**
Just try to download any manga from it, like this one:
https://comic-trail.com/episode/13933686331767005994

**HakuNeko (please complete the following information):**
 - Version: master@41af97

**Comment by Ever4engel** [comment]
already available. please make sure see if the site is currently available in the tool before reporting it in github.

PS: i tried it, there in no syncing, something changed on css queries

**Comment by Redyn** [comment]
That's because they recently changed the system, switching the the one used by Shonen Jump +.

I just edited the issue to change it into a "Connector not working" type.
