### ISSUE TITLE
5.0.8 not downloading and showing no files in 508 folder

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#301]
> **From:** HakuNeko User

It confirms the download request, I hit it but nothing happens

**Comment by 27136773** [comment]
Which package are you trying to download?
I tested each [download link](https://github.com/manga-download/hakuneko/releases/tag/v5.0.8) and all of them are working for me.

If the buttons are not working for you, scroll down a bit and try to download from the attached asset section instead (see screenshot below):

<details>
<summary>Screenshot Download Page (click to show)</summary>

![image](https://user-images.githubusercontent.com/27136773/62439881-f60e2e00-b74d-11e9-82ac-ce910bbedf11.png)

</details>

**Comment by 27136773** [comment]
See #302 => closed
