### ISSUE TITLE
[MangaKawaii] Connector not working

### ISSUE THREAD

**Issue by Tawagot0** [manga-download/hakuneko#3010]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
Folder empty (0 download)

**To Reproduce**
1. MangaKawaii
2. Any manga
3. Any chapter

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Robonau** [comment]
i can't test cause hcaptcha

**Comment by 27136773** [comment]
See: #3038
