### ISSUE TITLE
[Site Request] SSS Manga

### ISSUE THREAD

**Issue by baro0ok** [manga-download/hakuneko#3011]
**Name of the website**
SSS Manga

**Website urls (examples below)**
- Site: https://sssmanga.com/
- Manga List: https://sssmanga.com/mangas
- Manga example: https://sssmanga.com/manga_page?mgsh=1
- Chapter online viewer example: https://sssmanga.com/read?mgsh-sc=851&mn=One%20Piece&idm=1

**Languages**
English

**Additional details**
The Manga List is divided into 4 categories 
- Shounen
- Seinen
- Shojo
- Adult

**Comment by FinnRG** [comment]
Website is dead
