### ISSUE TITLE
[Toonily] Empty Chapter List and Updating the Manga list Doesn't Work.

### ISSUE THREAD

**Issue by Mkjafu** [manga-download/hakuneko#3012]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The manga list shows the normal list, but every manga I choose has no chapter in it, and refreshing the manga list shows "Failed to update the manga list for Toonily"

**To Reproduce**
1. Select toonily
2. Select any manga.
3. No chapters in the chapter list
4. Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "https://toonily.com/?ts=1612207678254&rd=0.7809591558416098" within the given timeout of 60 seconds!
    at Request.mjs:363
(anonymous) @ Manga.mjs:153
Promise.catch (async)
_getUpdatedChaptersFromWebsite @ Manga.mjs:151
(anonymous) @ Manga.mjs:98
Promise.then (async)
getChapters @ Manga.mjs:94
onSelectedMangaChanged @ chapters.html:244
runObserverEffect @ property-effects.html:217
runEffectsForProperty @ property-effects.html:162
runEffects @ property-effects.html:128
_propertiesChanged @ property-effects.html:1662
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
__enableOrFlushClients @ property-effects.html:1555
_flushClients @ property-effects.html:1530
_propertiesChanged @ property-effects.html:1658
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
runNotifyEffects @ property-effects.html:261
_propertiesChanged @ property-effects.html:1665
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
set @ property-effects.html:1817
onMangaClicked @ mangas.html:263
handler @ template-stamp.html:96
(anonymous) @ templatize.html:149
Connector.mjs:221 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\HP\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.toonilynet'
(anonymous) @ Connector.mjs:221
Promise.catch (async)
_getUpdatedMangasFromFile @ Connector.mjs:219
(anonymous) @ Connector.mjs:156
Promise.then (async)
getMangas @ Connector.mjs:153
onSelectedConnectorChanged @ mangas.html:215
runObserverEffect @ property-effects.html:217
runEffectsForProperty @ property-effects.html:162
runEffects @ property-effects.html:128
_propertiesChanged @ property-effects.html:1662
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
runNotifyEffects @ property-effects.html:261
_propertiesChanged @ property-effects.html:1665
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
set @ property-effects.html:1817
selectConnector @ connectors.html:303
handler @ template-stamp.html:96
(anonymous) @ templatize.html:149
Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "https://toonily.com/?ts=1612207933630&rd=0.2715288524672328" within the given timeout of 60 seconds!
    at Request.mjs:363
(anonymous) @ Manga.mjs:153
Promise.catch (async)
_getUpdatedChaptersFromWebsite @ Manga.mjs:151
(anonymous) @ Manga.mjs:98
Promise.then (async)
getChapters @ Manga.mjs:94
onSelectedMangaChanged @ chapters.html:244
runObserverEffect @ property-effects.html:217
runEffectsForProperty @ property-effects.html:162
runEffects @ property-effects.html:128
_propertiesChanged @ property-effects.html:1662
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
__enableOrFlushClients @ property-effects.html:1555
_flushClients @ property-effects.html:1530
_propertiesChanged @ property-effects.html:1658
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
runNotifyEffects @ property-effects.html:261
_propertiesChanged @ property-effects.html:1665
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
set @ property-effects.html:1817
onMangaClicked @ mangas.html:263
handler @ template-stamp.html:96
(anonymous) @ templatize.html:149
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-brands-400.woff2?v=5.8.2
Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "https://toonily.com/?ts=1612208231888&rd=0.7214481118751281" within the given timeout of 60 seconds!
    at Request.mjs:363
5. Try to update the manga list. get "Failed to update manga list of Toonily, Failed to load "https://toonily.com/?ts=1612208228678" " within the given timeout of 60 secs.

**HakuNeko (please complete the following information):**
 - Version  6.17

**Comment by Ever4engel** [comment]
will be fixed by #2989 see #2933
