### ISSUE TITLE
[NicoNico Seiga] Connector not working

### ISSUE THREAD

**Issue by vsatyamesc** [manga-download/hakuneko#3014]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
I'm not able to see Free Manga chapters. Also, it is showing downloaded but the Image files aren't in the download folder (made by Hakuneko for that manga) . When I press the "Download" button again, it is saying "Re-download the existing chapter". I have tested it with other manga from the same connector, it is not working there too.

**To Reproduce**
1. Nico Nico Seiga
2. Not a single manga is downloadable
3. Name of chapter (if manga update is working)
4. No error message

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 
 - 6.1.7@17a6fb

**Comment by 27136773** [comment]
It is working on my end with random manga/chapter, please provide sample manga/chapter for reproduction.
You said the manga is not working on the website within your browser either, please note that HakuNeko can only download mangas if they are also accessible from your browser.

NOTE: Nico Seiga requires to be logged in to access its content (if i remember correctly), but there was no info if you are logged in from HakuNeko or not.

----

![image](https://user-images.githubusercontent.com/27136773/106610049-8ce7c080-6566-11eb-8cec-bcc8ef13896f.png)

**Comment by vsatyamesc** [comment]
Wait, I thought you said the in-built Hakuneko browser. I'm able to see
manga and it's Chapter on my Google Chrome browser, but not on Hakuneko.
Hakuneko was able to view images before without logging in and download
them perfectly, but not now. I posted new issue because beofre I used an
extension to download image from google chrome but that has also stopped
downloading from seiga nico nico

**Comment by 27136773** [comment]
I was not aware that there are any mangas/chapters that work without login.
Please provide sample manga/chapter that works without login from google chrome browser

**Comment by vsatyamesc** [comment]
Well now that you say it, Yes, Nico Nico doesn't let me open Manga chapters
without Logging in,
But Haku Neko was able to download it perfectly without logging in. And
Also, I don't see a "Login" for NicoNico seiga in the settings of Hakuneko.

**Comment by 27136773** [comment]
You have to login manually
https://hakuneko.download/docs/manual-website-interaction/#account-login
