### ISSUE TITLE
[MangaRawClub] Connector not working

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#3016]
Site; https://www.manga-raw.club/
Manga; https://www.manga-raw.club/manga/forced-to-become-the-villains-son-in-law/
CH; https://www.manga-raw.club/reader/en/forced-to-become-the-villains-son-in-law-chapter-59-eng-li/
CH; https://www.manga-raw.club/reader/en/forced-to-become-the-villains-son-in-law-chapter-60-eng-li/

Prob;
The content of the manga is not coming. Doesn't show pictures.

**Screenshots**

![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/106640817-8f164300-6597-11eb-8c9d-c1678862b592.JPG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/10929481/106640823-90e00680-6597-11eb-8ad0-860f910af38d.JPG)
![Ekran Alıntısı3](https://user-images.githubusercontent.com/10929481/106640828-92a9ca00-6597-11eb-8bb8-302f2a5f615e.JPG)

**Comment by Sheepux** [comment]
Are you using the nightly ? It was fixed 7 hours ago https://github.com/manga-download/hakuneko/pull/3013

**Comment by areglos** [comment]
> Are you using the nightly ? It was fixed 7 hours ago #3013

i use nightly.

**Comment by Sheepux** [comment]
They changed it in between (could they be watching HN?) .... fix incoming !
If they change again after this fix, simply reply here (or ping me on discord) and i'll reopen the issue.

**Comment by areglos** [comment]
> They changed it in between (could they be watching HN?) .... fix incoming !
> If they change again after this fix, simply reply here (or ping me on discord) and i'll reopen the issue.

It gives old mistakes again.

![Ekran Alıntısı](https://user-images.githubusercontent.com/10929481/107219732-8ce23780-6a22-11eb-891e-12a6ee9867dd.JPG)

**Comment by Sheepux** [comment]
Thanks for tracking those changes.
The change might take a while before getting merged as Ronny is quite occupied.
You can check the fix and apply it directly in your local cache here:
%USERPROFILE%\AppData\Local\hakuneko-desktop\cache\mjs\connectors
