### ISSUE TITLE
[Site Request] Manga tepesi

### ISSUE THREAD

**Issue by RoyalHatB** [manga-download/hakuneko#3019]
mangatepesi
mangatepesi.com

**Website urls )**
- Site: https://mangatepesi.com
- Manga List: https://mangatepesi.com/mangalistesi
- Manga example: https://mangatepesi.com/manga/strongest-anti-meta/4
- Chapter online viewer example: https://mangatepesi.com/manga/strongest-anti-meta/bolum-1/23

**Languages**
Turkish

**Website relationship*
Nowhere

**Additional details**
This website has cool mangas if you can add this website i will appreciate it :)

**Comment by 27136773** [comment]
See #1725

**Comment by 27136773** [comment]
Please do not create additional duplicates (=> #3008), it has no effect except putting additional workload on ticket assessment...
