### ISSUE TITLE
#301 5.0.8 not downloading

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#302]
> **From:** HakuNeko User

I'm trying to download 5.0.8 for MacOS. I click it. I get a confirm request to download to download folder and I hit yes. Nothing happens.

I also tried doing it from website with same results. Download latest version
hakuneko-desktop_0.4.0_macosx_amd64.dmg(49.0MB) is what shows up.

**Comment by Albirew** [comment]
you can find latest version on this webpage: https://github.com/manga-download/hakuneko/releases/latest
and the latest version specifically for maque OS here: https://github.com/manga-download/hakuneko/releases/download/v5.0.8/hakuneko-desktop_5.0.8_macos_amd64.dmg

**Comment by Iloveboobs84** [comment]
Having Issues with the latest Update. My previous version of HakuNeko worked fine until today when it popped up with a Newer Version was available to download. after downloading v5.0.8 program will not load up or respond correctly just keeps telling me the new desktop client is available for update. I downloaded the Windows 64bit ver setup. Fix please or solution to my issue to get it working again. I just uninstalled the updated version 5.0.8 from my PC and waiting for further help.

**Comment by 27136773** [comment]
> Having Issues with the latest Update. My previous version of HakuNeko worked fine until today when it popped up with a Newer Version was available to download. after downloading v5.0.8 program will not load up or respond correctly just keeps telling me the new desktop client is available for update. I downloaded the Windows 64bit ver setup. Fix please or solution to my issue to get it working again. I just uninstalled the updated version 5.0.8 from my PC and waiting for further help.

Sounds like the cache cannot be updated.
Delete all files in the [Cache Directory](https://github.com/manga-download/hakuneko/wiki/User-Manual#23-cache) and start HakuNeko again.

**Comment by 27136773** [comment]
There are more than just one issues discussed in this ticket => closed
If the problem persist, please create a new ticket for that.
