### ISSUE TITLE
manga azora

### ISSUE THREAD

**Issue by achraft2** [manga-download/hakuneko#3022]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Bmswad1** [comment]
If the site you are requesting is https://azoramanga.com/
Then it already exists

**Comment by Robonau** [comment]
azoramanga would be my bet but given they didn't fill out any of the issue its invalid regardless

**Comment by 27136773** [comment]
Our mind-reading abilities are a bit rusty, so tickets without sufficient information will be rejected
