### ISSUE TITLE
[WAKASCAN] Connector not working

### ISSUE THREAD

**Issue by Luvoli** [manga-download/hakuneko#3026]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I've tried for 3 days to use WAKASCAN on hakuneko but it always shows the same thing.

**HakuNeko (please complete the following information):**
 - Version 6.17
![haku neko](https://user-images.githubusercontent.com/78498459/106786229-9a787580-664e-11eb-90c2-6919c17b0a19.PNG)

**Comment by Ever4engel** [comment]
will be fixed by #2989 see #2933
