### ISSUE TITLE
[lelscanvf] Connector not working

### ISSUE THREAD

**Issue by goldraftel** [manga-download/hakuneko#3029]
hello sir i used to donwload manga ith hakuneko from ''https://www.japanread.cc/'' &  ''https://lelscan-vf.co/'' 
but they are not working anymore, please check it out,
thank you

**Comment by Sheepux** [comment]
Template are provided when opening an issue, they are not here to be ignored:

Japan read : will be fixed by #2989 see #2933
Lelscan: domain change (me -> co)

**Comment by goldraftel** [comment]
helli sir, still same problem japanread is not working again? what shall i
do?

**Comment by Sheepux** [comment]
Japan read : will be fixed by #2989 see #2933

**Comment by goldraftel** [comment]
Got it, thanks!
