### ISSUE TITLE
bookmark is lost if naming change or provider down

### ISSUE THREAD

**Issue by Albirew** [manga-download/hakuneko#303]
bookmark is lost if naming change or provider down, hence my suggestion:
Is it possible to, when bookmarked chapter is not in list anymore, to still show it?
Maybe the same way that shows folders that doesn't match list retrieved from server?
![Untitled](https://user-images.githubusercontent.com/2805161/62472690-917bbf00-b79f-11e9-85a5-08aad88fb081.png)

**Comment by 27136773** [comment]
Covered by #81 => closed

**Comment by 27136773** [comment]
It seems this cannot be covered simply by #81
It is way more complex to support this since the chaptermark itself cannot be converted to a valid chapter yet...

**Comment by 27136773** [comment]
Chapters that have been marked as "recently read ", but are no longer available in the online chapter list or as local files are now shown in red on the top of the list.
This notification will disappear as soon as the unmark button to remove the "recently read" flag from the chapter is clicked, or another chapter is marked as recently read.
Tooltips for the unmark button and the chapter title will show the corresponding information.
Chapters that has been marked before the update will show the pseudo title "Chapter Title Unavailable".

![image](https://user-images.githubusercontent.com/27136773/62835113-e2cef700-bc54-11e9-9516-3ae14bb582fc.png)
