### ISSUE TITLE
[Site Request] Tsuki Mangás

### ISSUE THREAD

**Issue by gfabao** [manga-download/hakuneko#3032]
**Name of the website**
Tsukimangas

**Website urls (examples below)**
- Site: https://tsukimangas.com/
- Manga List: https://tsukimangas.com/lista-completa
- Manga example: https://tsukimangas.com/obra/1353/the-girl-from-random-chatting
- Chapter online viewer example: https://tsukimangas.com/leitor/1353/70846/the-girl-from-random-chatting/01#1

**Languages**
Portuguese

**Comment by Slowftw** [comment]
pogn't

**Comment by MikeZeDev** [comment]
Website under maintenance?
