### ISSUE TITLE
[LoveHug] Connector not working

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#3035]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloading the chapter doesn't download any images

**To Reproduce**
1. https://lovehug.net/
2. Soukyuu no Ariande (In this example) (if connector update is working)
3. Chapter 140 (if manga update is working)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Ever4engel** [comment]
#3020 pr already merged the website just work fine on my side.

i'f you have an error in a manga/chapter, mention it here.

**Comment by PerseusRex** [comment]
was there anything you changed or updated? I'm not really getting an error message. It's just when I download a new chapter the folder is empty and when I preview a chapter nothing shows up. I've tried this with multiple random manga chapters and they're all the same.

**Comment by PerseusRex** [comment]
> #3020 pr already merged the website just work fine on my side.
> 
> i'f you have an error in a manga/chapter, mention it here.

was there anything you changed or updated? I'm not really getting an error message. It's just when I download a new chapter the folder is empty and when I preview a chapter nothing shows up. I've tried this with multiple random manga chapters and they're all the same. But as an example I'm trying to download Soukyuu no Ariande Ch 140, the preview is blank and there's nothing in the folder created for that chapter.

**Comment by Robonau** [comment]
chapter extraction was fixed by that previous PR but img extraction is now broken
(imma work on it)

**Comment by PerseusRex** [comment]
I just checked again, now a different thing is happening, it now a bunch of gif loading 
files 
![Screenshot (306)](https://user-images.githubusercontent.com/51503984/107602843-b85e5100-6bdf-11eb-9ce6-5a20e094b0fa.png)
