### ISSUE TITLE
[Site Request] 8muses.io

### ISSUE THREAD

**Issue by velteyn** [manga-download/hakuneko#3037]
**Name of the website**
8muses.io

**Website urls (examples below)**
- Site: https://8muses.io/
- Manga List: https://8muses.io/
- Manga example: https://8muses.io/valentines-day/
- Chapter online viewer example: https://8muses.io/valentines-day/#1

**Languages**
English

**Website relationship*
alternative of 8muses.com

**Additional details**
8muses.com  is heavily encrypted urls and well defended, this mirror is very user frendly instead, but have less updates..

**Comment by 27136773** [comment]
Already exist, please check before creating a request.
If the website is broken create a `Website Changed` ticket.

![image](https://user-images.githubusercontent.com/27136773/108122411-8861f280-70a4-11eb-94c7-fbf748a2199f.png)
