### ISSUE TITLE
[My connectors arent working] Connector not working

### ISSUE THREAD

**Issue by NazariiPace** [manga-download/hakuneko#3039]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
None of the connecters are working the only one that dose work is MANGALIFE but none of the others work I want to use mangafreak and other stuff but they dont work 

**To Reproduce**
1. ALL dont work but mangalife works well
2. Name of manga (if connector update is working)

3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screenshot (4)](https://user-images.githubusercontent.com/64541168/107072694-43a1a600-67de-11eb-8c05-930931b7c124.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
will be fixed by #2989 see #2933
