### ISSUE TITLE
[Viz - Shonen Jump] Connector not working

### ISSUE THREAD

**Issue by perrinaz** [manga-download/hakuneko#3041]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
TypeError: Failed to Fetch

**To Reproduce**
1. Viz - Shonen Jump
2. Blue Flag
3. Chapters 29, 31, and 33.  Other chapters worked.
4. There is a "403 - Forbidden" error message and then:
InterProcessCommunication.mjs:13 Error: Failed to retrieve image data. Please report at https://github.com/manga-download/hakuneko/issues
    at VizShonenJump._handleConnectorURI (VizShonenJump.mjs:192)

**HakuNeko (please complete the following information):**
 - Nightly Build

**Comment by 27136773** [comment]
This is not an issue with HakuNeko, they do not work on the website either.
You need to report the broken chapters/pages directly to VIZ (without mentioning HakuNeko of course)...

![image](https://user-images.githubusercontent.com/27136773/108106865-cd7b2a00-708e-11eb-85a1-3a5fecb194a8.png)
