### ISSUE TITLE
[Site Request] kakaopage.co.id

### ISSUE THREAD

**Issue by sashakeista** [manga-download/hakuneko#3047]
**Kakaopage Indonesia**

**Website urls (examples below)**
- Site: https://kakaopage.co.id/
- Manga List: https://kakaopage.co.id/webtoon?tab=31&day=TUE&sort=POPULAR
- Manga example: https://kakaopage.co.id/content/Space-Sweepers/3435
- Chapter online viewer example: https://kakaopage.co.id/viewer/Space-Sweepers-EP14/164403

**Languages**
Indonesia

**Website relationship*
Backup of Kakaopage ID android based app, Indonesian translated version of Kakaopage Korean (Not all comic is translated by Kakaopage Indonesia)

**Additional details**
Sorry if there any misplace or something... I don't really know much about computer things...

**Comment by 27136773** [comment]
See #200
