### ISSUE TITLE
#301 downloaded 5.0.8 but sixiang and ninja scans still not working. Problems from 4.0

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#305]
> **From:** HakuNeko User

ninjascans downloads empty folders and preview doesn't respond and shows nothing. sixiang processes with extreme slowness and downloads incomprehensible .bin files and shows blank pages in the preview. 

But Tritinia is working now, so thank you.

**Comment by 27136773** [comment]
**Sixiang:**
Please check the chapters on the website, if the website itself is slow and provides broken images there is nothing HakuNeko can do... (e.g. [Supreme Demon Chapter 14](http://www.sixiangscans.com/manga/supreme-demon/chapter-14/?style=list))
If there is a chapter that works on the website but not in HakuNeko than it is probably a bug, in this case post tha manga and chapter name.

**Comment by 27136773** [comment]
No feedback => Closed
If it is reported that there are chapters that work on the website but not in HakuNeko the issue may be re-opened
