### ISSUE TITLE
[Hikari Scan] Connector not working

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#3050]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
theme has been changed to MangaStream [?]

**Screenshots**
![style_from_src](https://cdn.discordapp.com/attachments/604805967657435195/808753681888575518/unknown.png)
![hakuneko_request](https://user-images.githubusercontent.com/46169656/107404291-e6ab3600-6ae4-11eb-9ef1-e2b78e86b3cd.png)

**HakuNeko:**
 - Version 6.1.7

**Comment by manh21** [comment]
Can't access probably geo lock
