### ISSUE TITLE
[Mangas For You] Dead Scan

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#3051]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
"END OF AN ERA! WITH THIS I OFFICIALLY DECREE THE END OF THE SCAN! THANKS TO EVERYONE WHO READ AND SEE YOU SOON!" [...]
<https://www.facebook.com/mangasforyou/posts/3565802763477573>

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Sheepux** [comment]
website now redirects to http://lazycat.com.br/ with only 4 titles, i don't see the point of implementing a connector that himself redirects to mangahostz.
You could create a request for mangahostz that seems to be the new domain of https://mangahosted.com (that has already a connector)
I'll consider this as a removal request.

**Comment by Slowftw** [comment]
Yes, was a removal request.
