### ISSUE TITLE
[Feature] Way to Bookmark Connectors

### ISSUE THREAD

**Issue by curtcolt** [manga-download/hakuneko#3052]
**Is your feature request related to a problem? Please describe.**
Been finding lately that I'm consistently jumping between multiple connectors when looking for things and figured it would be a nice feature to have a sort of bookmarks bar for them, sort of like we can bookmark manga names currently.

**Describe the solution you'd like**
Ideally a way to bookmark connectors to where they could show off on the side without having to search the name, the blank space to the right of where they currently show up would be perfect:
![image](https://user-images.githubusercontent.com/54252052/107467367-dd958580-6b33-11eb-8d7e-5733883d44e3.png)
For example in that image, there could be another column for bookmarked connectors where the red circle is.

**Describe alternatives you've considered**
Not many alternatives that I can think of beyond just remembering the names of the connectors you like and searching them every time.

**Context (please complete the following information):**
 Currently on HakuNeko rev. 6.17@17a6fb

**Comment by Sheepux** [comment]
Well, for such case i usually bookmark the website directly in my normal browser and use the copy/paste feature (that's how i got 350+ bookmarks from mangahere), it's truly easier to discover mangas as HakuNeko is not meant to be a manga discovering tool.

Edit: I though the default view was supposed to be on 2 columns, could be usefull to resize the window (or check what happened). could be related to my "welcome screen" feature.

**Comment by Robonau** [comment]
duplicate of #535

**Comment by Robonau** [comment]
> Edit: I though the default view was supposed to be on 2 columns, could be usefull to resize the window (or check what happened). could be related to my "welcome screen" feature.

the amount of columns is based on the amount of space
3 columns for instance
![](https://i.imgur.com/lCIJ9mo.png)

**Comment by 27136773** [comment]
See #535
