### ISSUE TITLE
[Site Request] flamescans.org

### ISSUE THREAD

**Issue by somegoodshet** [manga-download/hakuneko#3057]
**Name of the website**
flame scans

**Website urls (examples below)**
- Site: https://flamescans.org/
- Manga List: https://flamescans.org/manga/
- Manga example: https://flamescans.org/manga/skeleton-soldier-couldnt-protect-the-dungeon/
- Chapter online viewer example: http://flamescans.org/1231412-skeleton-soldier-couldnt-protect-the-dungeon-chapter-131/

**Languages**
English

**Website relationship**
same as flame-scans.com but with more chapters and series.

**Additional details**
hakuneko already have flame-scans.com as a supported website, but not flamescans.org that has more chapters and series.

**Comment by manh21** [comment]
Template: WordpressMangaStream

**Comment by manh21** [comment]
[flame-scans.com](https://www.flame-scans.com) probably migrating to [flamescans.org](https://flamescans.org)
