### ISSUE TITLE
[Site Request] Turktoon

### ISSUE THREAD

**Issue by t432aa** [manga-download/hakuneko#3059]
**Name of the website**
Turktoon

**Website urls (examples below)**
- Site: https://turktoon.com/
- Manga List: https://turktoon.com/manga/
- Manga example: https://turktoon.com/manga/above-all-gods/
- Chapter online viewer example: https://turktoon.com/above-all-gods-1/

**Languages**
Turkish

**Comment by manh21** [comment]
Duplicate of #2931

**Comment by t432aa** [comment]
> Duplicate of #2931

Why can't Hakuneko find Turktoon?
![Screenshot_15](https://user-images.githubusercontent.com/77677055/107648771-c2d72400-6c8d-11eb-89ea-73c7fe006d47.jpg)

**Comment by Sheepux** [comment]
because someone mistyped "Truktoon" :D (PR incoming)
