### ISSUE TITLE
Manga list Updates

### ISSUE THREAD

**Issue by Iloveboobs84** [manga-download/hakuneko#306]
Curious to know if when you update the client you also update the manga directory as well because clicking the Update button in the Client manually doesn't work to update with new Manga.

Been to a few manga sites that have manga I'm interested in downloading but when I search in the client there nowhere to be found even after trying the Update button for those site in the list.

**Comment by ronny1982** [comment]
Which website?
As workaround you can use the [clipboard button ①](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list)

**Comment by Iloveboobs84** [comment]
MangaRock, MangaDex and the Mostly used one I got to MangaKakalot. By the way from my earlier problem deleting the cache files fixed the issue thanks. Couldn't reply back since you closed the Ticket.

**Comment by ronny1982** [comment]
**MangaRock**
Cannot be reproduced, list has 18941 entries and i could not spot a manga that is on the website but not in the list. Can you provide sample mangas which are missing?

**MangaDex**
Cannot be reproduced, list has 34840 entries (while website shows only 28996) and i could not spot a manga that is on the website but not in the list. Can you provide sample mangas which are missing?

**MangaKakalot**
Same for this one, list has 23565 entries and randomly checked new mangas are all in the list. Can you provide sample mangas which are missing?

**Comment by ronny1982** [comment]
No more feedback => closed
