### ISSUE TITLE
I want to know how to fix aloalivn manhuaes manhuaus counters?

### ISSUE THREAD

**Issue by hesoyamma785** [manga-download/hakuneko#3060]
Hello
i want to know how to fix aloalivn manhuaes manhuaus counter?
i saw in the issues that s.o mentioned that they were fixed but i dont know how to apply those into my software!

**Comment by Sheepux** [comment]
You can still comment on closed issues:
https://github.com/manga-download/hakuneko/issues/2925
Use hakuneko nightly to get the fix when they are merged (we only put fixs in hakuneko stable when we have time).
