### ISSUE TITLE
[MangaRAW] Connector not working

### ISSUE THREAD

**Issue by Henshinx** [manga-download/hakuneko#3061]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No
**Describe the bug**
Can't Load Manga List when i click reload manga list.
It display popup
"Failed to update manga list for MangaRaw (Manga RAW Club)
Cannot read property 'href' of undefined"

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by Sheepux** [comment]
Is the website of the connector working properly / are you able to see the manga within your browser
No

If the website is not working in your browser, it won't work within hakuneko, and therefore it's not related to HakuNeko (working fine on my side) 
Make sure you use the nightly as there was some recent fix on chapter view for mangarawclub
-> Closing (you can still comment if this needs to be reopened)
