### ISSUE TITLE
[Site Request] Manhwaland

### ISSUE THREAD

**Issue by SokKeras** [manga-download/hakuneko#3064]
**Name of the website**
Manhwaland

**Website urls (examples below)**
- Site: https://manhwaland.xyz
- Manga List: https://manhwaland.xyz/manhwa-list/
- Manga example:https://manhwaland.xyz/series/is-there-an-empty-room/
- Chapter online viewer example: https://manhwaland.xyz/daughter-in-law-chapter-02-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
Nothing

**Additional details**
Using Theme ZManga Author Sofyan R.

**Comment by 27136773** [comment]
See #3003
