### ISSUE TITLE
[KissAway] Connector not working

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#3066]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
https://kissaway.net changed something. now when you want to preview a chapter you will get gifs files instead of real images

**Comment by Muzzie3** [comment]
does anyone have a work around?

**Comment by 27136773** [comment]
Handled by #3035
