### ISSUE TITLE
[LibraryZ (Mangaz)] Connector not working

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#3067]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
https://www.mangaz.com/ work well when you want to grab last mangalist also preview just work well, but when you want to download chapters it grab bin files

**Comment by Robonau** [comment]
the bin files are just named wrong fsr
renaming them .jpg will open them as an img
