### ISSUE TITLE
Add feature to show url

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#307]
I think it would be nice if Hakuneko had the feature to display and input the url for the comic.
maybe like this :
![this](https://user-images.githubusercontent.com/45929526/62545271-99189200-b88b-11e9-843c-defc253806d5.png)

**Comment by Ever4engel** [comment]
excellent idea IMHO

**Comment by 27136773** [comment]
What would this be used for?
Input is already supported for one or more links in the clipboard (either by clicking the button or using CTRL+V).
Would double clicking a manga and open it in a window be a a good alternative?

**Comment by MIRVOUS** [comment]
no, i think it not will be a good alternative.
maybe it would be great if, if this feature :
![Capture3](https://user-images.githubusercontent.com/45929526/62561110-b0b24380-b8a8-11e9-95a1-96c717b9a266.PNG)
 were combined with what I requested.
so, when focusing on the text box you can paste it or type it manually and hit enter.
And when clicking on the manga, the url appears.

**Comment by 27136773** [comment]
I still don't see why this should be useful and what benefit this would bring to the user.
Copy & Paste from Browser to HakuNeko is already supported.
Why should a user wants to Copy & Paste from HakuNeko to Browser?

**Comment by MIRVOUS** [comment]
okay maybe you're right. I just thought maybe it would be good for the layout

**Comment by 27136773** [comment]
Will not be implemented yet, maybe re-thinking this when this is in need
