### ISSUE TITLE
[japanread] Connector not working

### ISSUE THREAD

**Issue by goldraftel** [manga-download/hakuneko#3070]
hello sir; i tried to connecte japanread.cc to hakuneko but its not working anymore!!
can you fix it please.
thank you sir.

**Comment by Sheepux** [comment]
Japan read : will be fixed by #2989 see #2933

**Comment by goldraftel** [comment]
hello sir, it the same thing, japanread is not working, what shall i  do?!

**Comment by Sheepux** [comment]
Wait for the issue mentionned ( #2933 ) to be fixed

**Comment by goldraftel** [comment]
@Sheepux  ok thank you
