### ISSUE TITLE
[Site Request] Fuyoshi Scan

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#3075]
**Name of the website**
Fuyoshi Scan

**Website urls**
- Site: https://fuyoshiscan.com.br/
- Manga List:
- - https://fuyoshiscan.com.br/category/mangas/
- - https://fuyoshiscan.com.br/category/doujinshis/
- - https://fuyoshiscan.com.br/category/manhwas/
- Manga example: https://fuyoshiscan.com.br/serpens/
- Chapter online viewer example: https://fuyoshiscan.com.br/serpens-0/

**Languages**
Portuguese

**Additional details**
Hello Elementor Theme

**Comment by MikeZeDev** [comment]
Website is empty
