### ISSUE TITLE
[Site Request] https://manhuas.net/

### ISSUE THREAD

**Issue by Monolity** [manga-download/hakuneko#3078]
**Name of the website**
Manhuas.net

**Website urls (examples below)**
- Site: https://manhuas.net/
- Manga List: https://manhuas.net/manhua-tag/manhua/
- Manga example: https://manhuas.net/manhua/doupo-cangqiong-manhua/
- Chapter online viewer example: https://manhuas.net/manhua/doupo-cangqiong-manhua/doupo-cangqiong-chapter-322/

**Languages**
List of languages supported by the website
English

**Website relationship*

**Additional details**

**Comment by Ever4engel** [comment]
already supported. please check the website (in the tool) before you open a new ticket.
