### ISSUE TITLE
Pasting manga URL should only work when search input has focus

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#308]
Currently when using `CTRL+V` to paste a manga URL this triggers the `Paste from Clipboard` event from any source. This means when pasting something in the settings, the clipboard event for the manga list is fired and logs a warning that the pasted link is not a valid website. 

Suggestion: The clipboard event shall only be triggered when pasting links in the (active) manga search input field.

**Comment by MIRVOUS** [comment]
this problem is same like me
