### ISSUE TITLE
[lovehug.net] Connector not working

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#3080]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The images that show up and are downloaded are all a loading gif

**To Reproduce**
1. lovehug.net
2. Any manga (ex: shangrila frontier)
3. Chapter 28

**Screenshots**
![107602843-b85e5100-6bdf-11eb-9ce6-5a20e094b0fa](https://user-images.githubusercontent.com/51503984/107987143-59ebf680-6f82-11eb-84bc-d5c81bf25ab3.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Ever4engel** [comment]
wait for #3044 PR fix

**Comment by Sheepux** [comment]
Duplicate #3035
