### ISSUE TITLE
[https://westmanga.info/] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3085]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![Screenshot_5](https://user-images.githubusercontent.com/79199707/108196287-8737d080-714b-11eb-9cb9-1b34f0c7d9f6.png)

**Comment by Sheepux** [comment]
If the website is not working in your browser then it won't work magically via hakuneko.
