### ISSUE TITLE
[Site Request] masterkomik

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3086]
masterkomik.com

Site: https://masterkomik.com/
Manga List: https://masterkomik.com/manga/
Manga example: https://masterkomik.com/manga/cultivation-through-science/
Chapter online viewer example: https://masterkomik.com/cultivation-through-science-chapter-3-bahasa-indonesia/

Languages
Indonesia

**Comment by Ever4engel** [comment]
already available. please check the website in the tool before suggesting it in github.

PS: i done some tests, can't preview nor download webtoons/mangas.

**Comment by 27136773** [comment]
Use nightly build, or wait for changes to be merged into 6.1.7
See: #2937
