### ISSUE TITLE
[Site Request] comicfx

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3087]
comicfx.net

Site: https://comicfx.net/
Manga List: https://comicfx.net/komik-list
Manga example: https://comicfx.net/komik/the-nine-heaven-of-martial-arts
Chapter online viewer example: https://comicfx.net/komik/the-nine-heaven-of-martial-arts/Chapter-151/1

Languages
Indonesia

**Comment by 27136773** [comment]
Template: MangaReaderCMS
