### ISSUE TITLE
[myreadingmanga] Connector not working

### ISSUE THREAD

**Issue by Holydragoness** [manga-download/hakuneko#3090]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

It has to do more with the connector timed out. Just wondering if its just my computer or something else. 

![image](https://user-images.githubusercontent.com/71577019/108227828-48cef100-710c-11eb-85cc-395bc9b21034.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Ever4engel** [comment]
will be fixed by #2989 see #2933
