### ISSUE TITLE
[Manga Livre] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#3092]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Manga Livre connector is not working either by updating the catalog or by the copy and paste method.

When trying to update the manga catalog, he will request all the pages in the list, however, after finishing the valid pages, he will continue to make infinite requests for non-existent pages (error 404).

And when trying the copy and paste method, it identifies the link as invalid.

**OBS: This Connector in particular is a Brazilian server with Region Lock, you may need a proxy or a vpn.**

**To Reproduce**
Steps to reproduce Catalog Error behavior:
1. Select Manga Livre Connector
2. Update the connector
3. Press F12
4. After 380 pages of valid list, it will make infinite request for non-existent pages (**Screenshot Available**)

**To Reproduce**
Steps to reproduce the Copy and Paste Error behavior:
1. Go to the Site of [Connector](https://mangalivre.net/)
2. Select a random Manga. _Example:_ https://mangalivre.net/manga/beastars/6531
3. Copy and paste on Hakuneko
4. Press F12
5. CLIPBOARD: https://mangalivre.net/manga/beastars/6531 Error: No matching connector found (**Screenshot Available**)

**Screenshots**
**Catalog Error**
![Screenshot at 2021-02-18 08-42-30](https://user-images.githubusercontent.com/46279686/108354292-02d76300-71c8-11eb-9f0c-282b19fe8e65.png)
![Screenshot at 2021-02-18 08-42-44](https://user-images.githubusercontent.com/46279686/108354310-08cd4400-71c8-11eb-94cf-d12751ae4998.png)

**Copy and Paste Error**
![Screenshot at 2021-02-18 08-32-13](https://user-images.githubusercontent.com/46279686/108354445-374b1f00-71c8-11eb-9c37-bd5e57c9d081.png)

**HakuNeko:**
 - Version v6.1.7

**Comment by 27136773** [comment]
Looks like a simple domain change from `https://mangalivre.com` to `https://mangalivre.net`

**Comment by Ever4engel** [comment]
![image](https://user-images.githubusercontent.com/47645041/108388992-7f416480-720f-11eb-836f-d088a2eef218.png)

right now on .com and .net domains

**Comment by Robonau** [comment]
same, but he did say it was geolocked 
so maybe `https://mangalivre.com` to `https://mangalivre.net` will work

**Comment by 27136773** [comment]
Any idea to which country this is region locked?
I tried some random Portuguese speaking countries, but all of them did not work

**Comment by Slowftw** [comment]
> Any idea to which country this is region locked?
> I tried some random Portuguese speaking countries, but all of them did not work

Only Brazil

**Comment by Slowftw** [comment]
> Any idea to which country this is region locked?
> I tried some random Portuguese speaking countries, but all of them did not work

@ronny1982 Only works for Brazil, they blocked any other country

**Comment by 27136773** [comment]
Non of my VPNs in brazil works for this website, so i hope someone else with access from brazil can fix this...

**Comment by Ever4engel** [comment]
@ronny1982 should close this ticket. we can do nothing right now.

**Comment by 27136773** [comment]
Can someone with access to MangaLivre confirm that it still looks the same as https://leitor.net/home?
