### ISSUE TITLE
[Site Request] Yaoiflix

### ISSUE THREAD

**Issue by komarna** [manga-download/hakuneko#3093]
Name of the website:
Yaoiflix

•	Site:  https://www.yaoiflix.com
•	Manga List: -
•	Manga example:  https://www.yaoiflix.com/dizi/moonlight-garden/
•	Chapter online viewer example: https://www.yaoiflix.com/bolum/moonlight-garden-1-sezon-1-bolum/

Language: Turkish
I think same as webmangatr

**Comment by XenonR** [comment]
It is based on webmangatr, but `getPages` needs to be modified.
