### ISSUE TITLE
[Site Request] Komiraw

### ISSUE THREAD

**Issue by fachrinoor** [manga-download/hakuneko#3097]
**Name of the website**
Komiraw

**Website urls (examples below)**
- Site: https://komiraw.com/
- Manga List: https://komiraw.com/
- Manga example: https://komiraw.com/jujutsu-kaisen-raw
- Chapter online viewer example: https://komiraw.com/jujutsu-kaisen-raw/chapter-138-54?i=117423

**Languages**
Japanese

**Comment by 27136773** [comment]
Looks inspired by `FlatManga` template, maybe it can be used as base

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by MikeZeDev** [comment]
Its dead jim
