### ISSUE TITLE
[Site Request] ComicK

### ISSUE THREAD

**Issue by thesleepingsage** [manga-download/hakuneko#3105]
Name of the website
ComicK

Website urls:

Site: https://comick.fun/
Manga example: https://comick.fun/comic/magi
Chapter online viewer example: https://comick.fun/comic/magi/68mYO-chapter-2-en

*Website relationship
none

**Comment by Sheepux** [comment]
MangaList  possibly via search https://comick.fun/search 50 titles per page
42461 Titles listed
Using API https://comick.fun/api/get_comics_by_ranking?limit=50&page=201


RelationShip with https://animek.fun/

**Comment by Robonau** [comment]
it hotlinks the images from mangadex
not worth the time i already spent
someone else can finish the connector if they want to
https://github.com/Robonau/hakuneko/commit/5c84d5254e84fde3e6a73cc8101c8352e10261b3

**Comment by blaxcky** [comment]
Would like to see this site for hakuneko.
I don't think it only hotlinks the images from mangadex, there are some things that weren't on mangadex (maybe only now since mangadex is "down")
