### ISSUE TITLE
[Site Request] mangaweebs

### ISSUE THREAD

**Issue by Ayush62** [manga-download/hakuneko#3106]
mangaweebs

**Website urls (examples below)**
- Site: https://mangaweebs.in/

- Manga List: https://mangaweebs.in/manga/the-second-coming-of-gluttony/

- Chapter online viewer example: https://mangaweebs.in/manga/the-second-coming-of-gluttony/chapter-1/

**Languages**
Engelish

**Website relationship*
none

**Comment by 27136773** [comment]
Template: WordPressMadara
