### ISSUE TITLE
Mangadex website change connector now broken

### ISSUE THREAD

**Issue by doppler56** [manga-download/hakuneko#3107]
Using 8.3.4 win 10 64bit.
Mangadex is now storing content on the md@home network, not locally to them.
No longer s2.mangadex or s5.mangadex (or others prob) is the location to download.
Any attempt results in 404 not found.  Verified with F12 monitoring.
Using mangadex reader, the content location is from the md@home network.

I don't use discord, you maybe already working on it.
Thank you.

**Comment by 27136773** [comment]
Older images seems still to be available (as of the time of writing)
https://s2.mangadex.org/data/a082dac8d720fbb0cc5f631f13b98625/1-dd9193a480e74af3767eab2248c1c25a5944210596817e416631a3ab9e297218.jpg

One of the MangaDex@Home node ([478](https://mangadex.network/d/NDGiF3mGz/overview?var-client_id=478)) became the new seed for new chapters/images and seems to replace s2/s5.
Currently the node is available under the hostname:
https://d156gdtycsqca.xnvda7fch4zhr.mangadex.network/data/a082dac8d720fbb0cc5f631f13b98625/1-dd9193a480e74af3767eab2248c1c25a5944210596817e416631a3ab9e297218.jpg

**Comment by doppler56** [comment]
@ronny1982 Not surprised by that.  The md@home network does not contain the full library.  I think only the new stuff is being clouded.  Which if you are just following your likes.  Kinda sucks.  Other down loaders like tachiyomi and a FF addon I use (when things are bad) can follow out to the cloud for content.
I know you guys are working on the next generation of Haukneko.  I hope you can fold in a fix for this generation easily.

Just saw a real time update to your message, nice github can do that.  Node 478 is part of the md@home cloud.  It may not be the new seeder.  By usage any node can server the mangadex reader for content.  Node 478 must be the most stable one.

**Comment by 27136773** [comment]
The workaround is to select `Random Mirror` for MangaDex in HakuNeko settings

**Comment by doppler56** [comment]
@ronny1982 I will try that.  Knowing my luck the random mirror selected sometimes will be s2 and s5.mangadex

Thanks for the quicky.  Since closed issues stay up for others will close this.

**Comment by 27136773** [comment]
You will get a random node from the 250 private mangadex@home nodes, s2 and s5 are not part of md@h

**Comment by tsentered** [comment]
This was good stuff. Thank you to both.
