### ISSUE TITLE
[Site Request] 123hon

### ISSUE THREAD

**Issue by dzung1506** [manga-download/hakuneko#3108]
**Name of the website**
123hon

**Website urls (examples below)**
- Site: https://polca.123hon.com/
- Manga List: https://polca.123hon.com/series_list/
- Manga example: https://polca.123hon.com/book_series/bartlett/
- Chapter online viewer example: https://polca.123hon.com/vw/btlt/sv_pt0006029d9567f397_01/index.html
**Languages**
Japanese

**Website relationship*
None

**Comment by Ever4engel** [comment]
use Speedbind template

**Comment by dzung1506** [comment]
> Speedbind template

How to use Speedbind template?
Can you guide me with this?

**Comment by 27136773** [comment]
This was a note for developers
