### ISSUE TITLE
[MangaGecesi] Removal

### ISSUE THREAD

**Issue by coderbromanga** [manga-download/hakuneko#3125]
Site url : mangagecesi.com

Why should this website be removed from HakuNeko?
the removal of the content from hakuneko to avoid making money by copying it by others.

In case of Traffic
we don't have any information about the traffic we measure hakuneko

Have you also requested takedown on other tools such as Tachiyomi or FMD2?
All necessary removal requests were made and removed

the site was made as an example for ownership verification...
https://mangagecesi.com/hakuneko/

**Comment by Ever4engel** [comment]
same as said in #3124 discussion.

**Comment by 27136773** [comment]
Handled by #3124 (rejected)
