### ISSUE TITLE
[Yayutoon] Removal

### ISSUE THREAD

**Issue by coderbromanga** [manga-download/hakuneko#3127]
Site url : yayutoon.fun

Why should this website be removed from HakuNeko?
the removal of the content from hakuneko to avoid making money by copying it by others.

In case of Traffic
we don't have any information about the traffic we measure hakuneko

Have you also requested takedown on other tools such as Tachiyomi or FMD2?
All necessary removal requests were made and removed

the site was made as an example for ownership verification...
https://yayutoon.fun/hakuneko/

**Comment by Bmswad1** [comment]
I will say one thing
What's the use of removing your site from hakuneko or any other app
If someone wants to really steal your content he will do anything to steal it
One example is that one site I know put many efforts to stop aggregation of content and the one who was stealing when he couldn't download the comics on the site he took long screenshots of the whole chapter
So in my opinion there is no use removing your site from any app

**Comment by coderbromanga** [comment]
It is ridiculous to offer services so that you can steal the content from those who play the content, we will block as many apps as possible so that our site is left alone ...
You can manually download one by one, you are right, at least it takes 10 minutes to download 10000 episodes, while 10000 episodes will hardly download for 2 months.

**Comment by Sheepux** [comment]
Why are you using HN to get the raws then ?

**Comment by jowangsh1n** [comment]
I don't get original content through HN. So this request seems perfectly normal.

**Comment by Sheepux** [comment]
> I don't get original content through HN. So this request seems perfectly normal.

See the debate here: https://github.com/manga-download/hakuneko/issues

**Comment by Robonau** [comment]
he means here
https://github.com/manga-download/hakuneko/issues/3124

**Comment by 27136773** [comment]
Basically your leaving your door open and are asking a certain group of people not to enter

**Comment by 27136773** [comment]
Handled by #3124 (rejected)
