### ISSUE TITLE
[Feature] Please add inlauncher hotkeys like F to fullscreen (sorry for pull )

### ISSUE THREAD

**Issue by tescker** [manga-download/hakuneko#3134]

**Comment by 27136773** [comment]
Specifications are insufficient.
What is inlauncher?
What actions, which keys for which page views?
Fullscreen with `F` where, in reader in normal downloader, ...?

Sample:
As a user i would like to press `F` key to toggle between fullscreen when reading a manga

**Comment by Sheepux** [comment]
Press F11 for fullscreen ?
