### ISSUE TITLE
[MangaDex] Connector working, but images cannot viewed/downloaded

### ISSUE THREAD

**Issue by psduraes** [manga-download/hakuneko#3135]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The image server address has changed. I tested with all the addresses listed in the hakuneko and the error 404 appears.

**Screenshots**
Hakuneko screenshot

![image](https://user-images.githubusercontent.com/79729455/109368797-14c89e00-7879-11eb-8b60-67dcd561ec56.png)

Image server address screenshot

![image](https://user-images.githubusercontent.com/79729455/109368838-388be400-7879-11eb-8d47-c68495abca21.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3107
