### ISSUE TITLE
[Turktoon] Connector not working

### ISSUE THREAD

**Issue by t432aa** [manga-download/hakuneko#3136]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Only 1 chapter can be downloaded from the manga on this site, others cannot be downloaded.

**To Reproduce**
1. Name of connector: Turktoon
2. Name of manga: Rebirth of the Urban Immortal Cultivator and all mangas
3. Name of chapter: all chapters
4. Copy any relevant error message: Cannot read property 'pop' of undefined.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screenshot_15](https://user-images.githubusercontent.com/77677055/109384314-07ed8e00-78fd-11eb-8261-2fbadfc07dfc.jpg)
![Screenshot_18](https://user-images.githubusercontent.com/77677055/109384410-97933c80-78fd-11eb-8661-b7f71c57062b.jpg)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![Screenshot_16](https://user-images.githubusercontent.com/77677055/109384329-22c00280-78fd-11eb-9f8f-6c9eb4118354.jpg)

**Comment by 27136773** [comment]
Website is randomly crashing in browser for me (blank content), so it seems a problem with their website and not with HakuNeko

**Comment by 27136773** [comment]
They removed the text based manga list, therefore HakuNeko cannot acquire the list right now.
Copy & Paste still works...

**Comment by XenonR** [comment]
Working flawlessly for me.
![image](https://user-images.githubusercontent.com/18627623/113016935-3f12c180-917f-11eb-91dd-e3ea8a2ec89f.png)
Seems the website fixed the issue. Closed.
