### ISSUE TITLE
[Hiperdex] Connector not working

### ISSUE THREAD

**Issue by iamarvii** [manga-download/hakuneko#3137]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot synchronize with the website and when using web view its not loading.

**To Reproduce**
1. Name of connector: Hiperdex
2. Name of manga: All
3. Name of chapter: All
4. Copy any relevant error message: Failed to update manga list for Hiperdex

**Screenshots**
![h](https://user-images.githubusercontent.com/25127519/109385101-59f9d800-792c-11eb-8448-8e31713f3e69.PNG)
![h1](https://user-images.githubusercontent.com/25127519/109385103-5bc39b80-792c-11eb-9150-1d76e8a6a02a.PNG)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@1967c

**Comment by 27136773** [comment]
See #3042

**Comment by iamarvii** [comment]
Hello, Thanks for your response. I only have a question: do I need to use
the nightly instead of the stable version?

**Comment by 27136773** [comment]
In case it will be fixed eventually, the fix will only be available in the nightly version (due to technical reasons)

**Comment by iamarvii** [comment]
Thank you very much for your help.
