### ISSUE TITLE
[Site Request] MANGAGREAT

### ISSUE THREAD

**Issue by hesoyamma785** [manga-download/hakuneko#3140]
**Name of the website**
MANGAGREAT

**Website urls **
- Site: https://mangagreat.com/
- Manga List: https://mangagreat.com/manga/
- Manga example: https://mangagreat.com/manga/return-of-the-reborn-god-emperor/
- Chapter online viewer example: https://mangagreat.com/manga/return-of-the-reborn-god-emperor/chapter-14/

**Languages**
English
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See: #3104
Use nightly or wait until merged in 6.1.7
