### ISSUE TITLE
[Site Request] yanmaga.jp

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#3144]
**Name of the website**
yanmaga.jp

**Website urls (examples below)**
- Site: https://yanmaga.jp/
- Manga List: https://yanmaga.jp/comics/%E6%81%A5%E3%81%98%E3%82%89%E3%81%86%E5%90%9B%E3%81%8C%E8%A6%8B%E3%81%9F%E3%81%84%E3%82%93%E3%81%A0
- Manga example: https://yanmaga.jp/comics/%E6%81%A5%E3%81%98%E3%82%89%E3%81%86%E5%90%9B%E3%81%8C%E8%A6%8B%E3%81%9F%E3%81%84%E3%82%93%E3%81%A0/d768df8c5fc15ebf6a9e5a1155cf4729

**Languages**
japanese

**Comment by Ever4engel** [comment]
use comici viewer. see this for [references](https://github.com/shoushouminami/modelpress-downloader/blob/789ec3753c0118ae9ed84d0529e28f0993ea4b66/src/inject/yanmaga.jp.js) line [77](https://github.com/shoushouminami/modelpress-downloader/blob/789ec3753c0118ae9ed84d0529e28f0993ea4b66/src/inject/yanmaga.jp.js#L77)
