### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by Twilight-Hacker** [manga-download/hakuneko#3146]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When trying to download anything from Mangadex, it downloads a very small bin file instead of an image.

**To Reproduce**
1. Name of connector: Mangadex
2. Any manga eg Witch Craft Works 
3. Any recent chapter in English E.g.  c93 (some of the older ones download normally)

The console gives the following messages (or similar): (essentially it appears to give a 504 error)

Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/1-4dab27fd4b69490b890320596854dec4bc9ec1323c797d4af989403c2d514852.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/2-97988509852fa6aa8b7a2b6c58fb75bbb4e8ddc7d3d246ff1617c8392dc28352.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/3-e4fcae59675a86d210e746dadd7ad192290566cc2f874630e1d529975a24343e.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/5-e6863f9f3d628e430fe8457cd6bb6ad69ea4d07aab4e3207466a5168ed75d44d.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/6-bdfc9f9fe8fce350bf44b28e811aa51846e5aedfae705966510773e368bb88fd.jpeg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/4-9fb97c2c70eb29f72118300ebe39cda2afb7c889f7d9f817782ee0ac62115205.jpg 502
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/7-99ea5ace773b955c0c5131dd34f1bb54e291ce354250951dc188f3386afb2ab1.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/8-8701b4bc458d3e3574289b20530887e426ff9f49259518419692fab5c7b748f4.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/9-f842437b8faf0f840aa470918c6ab19975b0b5284055606f01ae0189e9701939.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/10-0ae95228bf602a6e0ac5811a4e5b9b8e18e8492f2bbeee589beeae1073910383.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/11-1fe22beac5a5a17a4c88ebe29f1a1e2e1fec086a565281e65753c6a4a671673c.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/12-5ff51b6796ded04c3e8bed79dddc6a08f3d18bb1e9d8354a4ddd3e5741e9d015.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/13-9bd736a5fccd46f92b27a90c357c2a4452e4b168aff57c55824c7d8db0aefc99.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/14-c2ccbacf4fa65d3296ab31a10554adf448606cbcd03f972e6f930a35c9aed741.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/15-ac9cc113801072d102d87095b51ebf9d1a147df384b22d208c894aab77142f6f.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/16-6856283aa6c680c927095691593427698c800deb39f39223a1c126e7b3a78e1d.jpeg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/17-3f07fd72eab8aa10928261f027b6b11e8e6a77a8cfd63ec4229dc256486cdb13.jpeg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/18-aa8d5f0d0b0e3470ae2c716f41d0703f7ec36b3150f259ee97c69c436742bf5c.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/19-47308f8e2ef44aae3d6f44bcf3e055de55cff159022939d09a0a2ea37def3b9d.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42
Connector.mjs:683 GET https://s2.mangadex.org/data/3c92f01f36d0ae135d0f2387fdd3c19c/20-6dd7dafcbf976b48d55552532a931b40cffae8633aa2e2d194e2cb2e2580ea95.jpg 504
_handleConnectorURI @ Connector.mjs:683
handleConnectorURI @ Connector.mjs:670
_protocolHandler @ Connectors.mjs:62
apply @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:281
(anonymous) @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\remote.js:271
emit @ events.js:200
onMessage @ C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version  6.17 @ a1967c

**Comment by 27136773** [comment]
See #3107
