### ISSUE TITLE
[Bug] using 9Anime opens Popup Windows with Advertisements

### ISSUE THREAD

**Issue by Maxwell12347842** [manga-download/hakuneko#3147]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Everytime you click on a Anime in the List, a new popup opens that leads to 9anime. Also this opens new Popups with advertisements.

**To Reproduce**
1. Go to 9Anime as the Connector
2. Click on a Anime in the List
3. New Popup to 9Anime opens & often Advertisement Popups additonal

**Expected behavior**
No Popup opening. It worked before in previous versions, but now it is acting strange and weird and the user is at risk by Advertising Popups opening that could lead to driveby downloads by malware campaigns.

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version: 6.17

**Comment by 27136773** [comment]
Cannot be reproduced on my end, there is no popup for me when loading episodes

![image](https://user-images.githubusercontent.com/27136773/109631937-c4866000-7b46-11eb-8f8c-09f2733b9250.png)

**Comment by Maxwell12347842** [comment]
i just tried it now again and wanted to record a video to show it.. and now it's not happening anymore. Weird. Usually, everytime when i clicked on the Name of an Anime, it did start load the Episodes and 1-2 Seconds later it did open a new popup with the 9anime website for the specific anime i clicked. then it opened 2-3 seconds later another popup from the 9anime website with advertisements for browser games. in the background it did load the Episode list and then showed it on the right sidebar.

could it be that 9anime from their server codeside opened this popup over javascript or something? because it really happend everytime and now suddenly isn't anymore.

**Comment by 27136773** [comment]
Could it be you are confusing the captcha dialog with an unwanted popup?.
HakuNeko will show a captcha dialog when the user have to solve a captcha to access the content.

HakuNeko's blacklist is not working, because of a conflict with JapScan connector and therefore ads cannot be blocked.

**Comment by Maxwell12347842** [comment]
There wasn't a captcha dialog, nope. It did open the specific Anime Directlink of 9anime. Like when you visit 9anime in a browser and click on a specific anime. I already have seen the captcha dialog and it looks different than what i had.

**Comment by 27136773** [comment]
The captcha is directly shown on the 9anime page which streams the video, but instead of the episodes there is a small captcha box.
So again, are you really sure it was not the captcha that was shown?

![image](https://user-images.githubusercontent.com/27136773/109647128-41223a00-7b59-11eb-8778-8b0a7ededeec.png)

**Comment by Maxwell12347842** [comment]
i did look more deeper on the site  that did open, and there wasn't a captcha. i could watch without input any captcha or similiar on this site. it did open the site, then i had the 1. epsiode auto starting. no captcha or anything. i often use 9anime in my firefox browser so i know how it looks like.. and there wasn't the captcha field. if there would be, i would have guessed thats why it did open.

anyway.. if it happens again, i try to make a video / screenshot of it so i can show it. till then it makes no sense to write more about it since it didn't happen again when i tried it again. thanks for the quick help!
