### ISSUE TITLE
[NameOfConnector] Sky Manga

### ISSUE THREAD

**Issue by howlersting** [manga-download/hakuneko#3149]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes, I can access the site in a normal desktop browser. But it doesn't work as a connector neither in the internal Haku Neko Browser.

**Describe the bug**
Unable to access any manhwa on connector. The site link is https://skymanga.co/. I can access the site in a normal desktop browser. But it doesn't work as a connector neither in the internal Haku Neko browse
.

**To Reproduce**
1. Skymanga
2. Try to update manga list or try accessing chapters for any manhwa name
3. Failed to update mangalist for Skymanga.  Failed to load site within given timeout of 60 seconds
4. Screenshots added

**HakuNeko (please complete the following information):**
 - Version 6.17

![Error](https://user-images.githubusercontent.com/79855279/109514351-f3132500-7acb-11eb-9965-00a692c01a8e.PNG)

**Comment by howlersting** [comment]
Duplicate issue found raised by another user. Closing for now

**Comment by 27136773** [comment]
Please link duplicates #2999

**Comment by howlersting** [comment]
Hi Ronny

Do, I have to link the issue? Looks like it is already done.

Regards

**Comment by 27136773** [comment]
I've done it for you

**Comment by howlersting** [comment]
Thank you sir
