### ISSUE TITLE
[Manhuaes] Connector not working

### ISSUE THREAD

**Issue by hesoyamma785** [manga-download/hakuneko#3151]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it doesn't show anything

**To Reproduce**
1. manhuaes
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/77359705/109617677-eb936080-7b4b-11eb-824b-04fcf1c2b21f.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Press the synchronize button as stated in the text on the screen...

**Comment by hesoyamma785** [comment]
> Press the synchronize button as stated in the text on the screen...

i did that and nothing happened
the picture is after pressing the button.

**Comment by tsentered** [comment]
Me too since yesterday. When trying to synchronize, it removes all titles even though the site is working.

**Comment by 27136773** [comment]
Please provide more detailed steps to reproduce next time

**Comment by tsentered** [comment]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The titles show zero chapters. When synchronize the connector all titles disappear. I exit Haku then restart all titles show again and same problem persists. I think some change has been made to website causing the issue. With my know how the best I can do is to make this likely guess.


**To Reproduce**
Steps to reproduce the behavior:
1. Name of connector - ManhuaES
2. Name of manga (if connector update is working) All titles
3. Name of chapter (if manga update is working).    All chapters
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) None

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

Titles show no chapters and pre-synched



Post synch



Re-opened


Website



**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by tsentered** [comment]
Thank you.
