### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by zenkijoe** [manga-download/hakuneko#3157]
**Name of the website**
WBNovel

**Website urls (examples below)**
- Site: https://wbnovel.com/
- Manga List: https://wbnovel.com/novel/
- Manga example: https://wbnovel.com/novel/martial-god-asura/
- Chapter online viewer example: https://wbnovel.com/novel/martial-god-asura/1/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by zenkijoe** [comment]
bro please add this new website novel. I have request this several time..Pleasss

**Comment by 27136773** [comment]
See: #2796

**Comment by 27136773** [comment]
Its done when some contributor feels like doing it, adding multiple issues has no effect except increasing time spent on administrating issues instead of developing...

**Comment by 27136773** [comment]
If the site is that important, consider placing a bounty on it to attract contributors
e.g. via [Bountysource](https://www.bountysource.com), [Gitpay](https://gitpay.me) or [IssueHunt](https://issuehunt.io)
