### ISSUE TITLE
[Site Request] Jiangzaitoon

### ISSUE THREAD

**Issue by crackmono** [manga-download/hakuneko#3159]
**Name of the website**
Jiangzaitoon

**Website urls (examples below)**
- Site: https://www.jiangzaitoon.com/
- Manga List: https://www.jiangzaitoon.com/manga/
- Manga example: https://www.jiangzaitoon.com/manga/chess-pieces/
- Chapter online viewer example: https://www.jiangzaitoon.com/manga/chess-pieces/bolum-2/

**Languages**
turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**

**Comment by 27136773** [comment]
Template: WordPressMadara

**Comment by 27136773** [comment]
Already supported, please check before making a request
