### ISSUE TITLE
[Site Request] Mangagenki

### ISSUE THREAD

**Issue by crackmono** [manga-download/hakuneko#3160]
**Name of the website**
Mangagenki

**Website urls (examples below)**
- Site: https://mangagenki.com/
- Manga List: https://mangagenki.com/manga/?list
- Manga example: https://mangagenki.com/manga/hardcore-leveling-warrior/
- Chapter online viewer example: https://mangagenki.com/hardcore-leveling-warrior-chapter-6/

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**

**Comment by 27136773** [comment]
Template: WordPressMangastream
