### ISSUE TITLE
[Site Request] comic-brise

### ISSUE THREAD

**Issue by RenoKL** [manga-download/hakuneko#3163]
**Name of the website**
comic-briseコミックブリーゼ

**Website urls (examples below)**
- Site: https://comic-brise.com
- Manga List: https://comic-brise.com/contents/
- Manga example: https://comic-brise.com/contents/changeup/
- Chapter online viewer example: https://comic-brise.com/comic_ep/changeup_ep1/

**Languages**
Japanese

**Website relationship*
Most mangas can also be read through a link to ニコニコ漫画: https://seiga.nicovideo.jp/

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment]
Resolved by #4255

**Comment by MikeZeDev** [comment]
Website is supported. @Sheepux please <3
