### ISSUE TITLE
[Site Request] Hanime

### ISSUE THREAD

**Issue by Testacda** [manga-download/hakuneko#3166]
**Name of the website**
Hanime

**Website urls (examples below)**
- Site: https://hanime.tv
- Anime List: https://members.hanime.tv/search
- Anime example: https://members.hanime.tv/videos/hentai/toilet-no-hanako-san-vs-kukkyou-taimashi-1

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
For playlists that people create the link is members.hanime.tv with the id of playlist at the end ex: https://**members.**hanime.tv/videos/hentai/toilet-no-hanako-san-vs-kukkyou-taimashi-1**?playlist_id=macmszeld6xhyhljxx0u**

**Comment by 27136773** [comment]
See: #2136
