### ISSUE TITLE
[Site Request] Freetime Scanlator

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#3170]
**Name of the website**
Freetime Scanlator

**Website urls**
- Site: https://www.ftmangas.top/
- Manga List: https://www.ftmangas.top/projetos/
- Manga example: https://www.ftmangas.top/projetos/sousei-no-onmyouji/
- Chapter online viewer example: https://www.ftmangas.top/projetos/sousei-no-onmyouji/2085/85

**Languages**
Portuguese

**Comment by sisco0** [comment]
Looks very similar to _WordPressZbulu_.
```
WordPressZbulu https://ww3.bulumanga.net 0.0 0.03753351206434316 0.01876675603217158
WordPressZbulu https://mytoon.net 0.0 0.0408673894912427 0.02043369474562135
WordPressZbulu https://koomanga.com 0.0 0.04554226167502894 0.02277113083751447
WordPressZbulu https://holymanga.net 0.0 0.01335559265442404 0.00667779632721202
WordPressZbulu http://mangatown.online 0.0 0.02111024237685692 0.01055512118842846
WordPressZbulu http://manganelo.me 0.0 0.019538882375928098 0.009769441187964049
```

![image](https://user-images.githubusercontent.com/25695302/113521319-55919200-955e-11eb-82d4-e0d2a3592040.png)

**Comment by MikeZeDev** [comment]
dead website.
