### ISSUE TITLE
[Bug] Unable to login to Tapas using social media with the manual website interaction

### ISSUE THREAD

**Issue by nostxlgiaa** [manga-download/hakuneko#3172]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I am unable to login to tapas with the manual website interaction when I use a social media to sign in (Google). When I click on it, it redirects me to a blank page.

**Screenshots**
<img width="1234" alt="Screenshot 2021-03-08 at 09 51 30" src="https://user-images.githubusercontent.com/80251183/110305060-330a6880-7ff4-11eb-9e6f-9bfc78071795.png">
<img width="912" alt="Screenshot 2021-03-08 at 09 53 11" src="https://user-images.githubusercontent.com/80251183/110305068-36055900-7ff4-11eb-835a-6da91981ac85.png">

**Context (please complete the following information):**
 - OS: macOS Big Sur v11.2.2
 - HakuNeko v6.1.7

**Comment by 27136773** [comment]
See: #2820
Social media sites are blacklisted in HakuNeko
