### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by danialhaz** [manga-download/hakuneko#3175]
**Name of the website**
imhentai

**Website urls (examples below)**
https://imhentai.xxx

**Languages**
List of languages supported by the website
English, Korea, Japanese, Spanish, Russia, and other

**Website relationship*
Related to imhentai.com

**Additional details**
imhentai website recently change their domain so the old imhentai in hakuneko do not work anymore, can you pls update it?

**Comment by 27136773** [comment]
Already fixed in PR #3143
Use nightly or wait for merge into 6.1.7
