### ISSUE TITLE
[IMHentai] Site changes to "IMHentai.xxx", download result error 403

### ISSUE THREAD

**Issue by ProbexVector** [manga-download/hakuneko#3181]
IMHentai changes their website from "IMHentai.com" to "IMHentai.xxx" 

i tried to change the code in .mjs file about IMHentai just to changes domain,

but after run and try to download files from website, return to error 403 (Forbidden)

![gambar](https://user-images.githubusercontent.com/43844629/110758821-85ab8500-827f-11eb-87f3-fc68651f4385.png)

the code : 
![gambar](https://user-images.githubusercontent.com/43844629/110758874-95c36480-827f-11eb-8eaf-984dc195e11f.png)

**Comment by 27136773** [comment]
Already changed in #3143
Use nightly or wait for changes to be merged into 6.1.7
