### ISSUE TITLE
download fails for JapScan marc 2021

### ISSUE THREAD

**Issue by kurtkristensen** [manga-download/hakuneko#3183]
Hello good evening, I always follow you.

I have problems with downloads from the japscan site
I downloaded both version V6.17 (stable and portable version)
I work from a dell 17 7778 with windows 10 prof.

It does not report an error, but when I choose a manga (eg sainte seiya deluxe) it gives me the list of volumes, then I download it, but shortly after it freezes, crashes and closes.

Can you help me?

**Comment by 27136773** [comment]
HakuNeko opens a new invisible browser window for each image when downloading from JapScan.
Saint Saya has hundreds of images and therefore the system will be pushed to its limits with hundreds of browsers opening.
Increase throttling in settings, use a RAM cleaner during download.

This topic was discussed quite often in discord, you should ask there how users handle this...
