### ISSUE TITLE
[Feature] Setting to disable auto update

### ISSUE THREAD

**Issue by TennyC** [manga-download/hakuneko#3188]
Currently, upon execution of Hakuneko opens an interface "Checking for updates" and I assume installing those updates if new ones found. A lot of times, I'm outside and trying to conserve data or just plan to use Hakuneko as a reader. Is there an option to disable auto updates that I'm not seeing? And if it's not there, would you consider making one?

**Comment by 27136773** [comment]
Turn off the network which forces HakuNeko to offline mode, or start HakuNeko with `--update-url=DISABLED` option (e.g. from terminal or create a shortcut)
