### ISSUE TITLE
[MangaSee] Connector not working

### ISSUE THREAD

**Issue by potato899** [manga-download/hakuneko#3189]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The downloads fail, but the site seems to work fine.

**To Reproduce**
1. MangaSee
2. Any manga.
3. Any chapter.
4. Fail to fetch.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
Already fixed.
Use nightly build or wait for fix to be merged into 6.1.7
