### ISSUE TITLE
[Site Request] 6parkbbs

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#3191]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2415%20Funded-%2300A156.svg" />](https://issuehunt.io/r/manga-download/hakuneko/issues/3191)

**Name of the website**
6park

- Site: https://web.6parkbbs.com
- Manga List: 
- Manga example: https://web.6parkbbs.com/index.php?act=bbs&bbsid=2032
- Chapter online viewer example: https://web.6parkbbs.com/index.php?app=forum&act=view&bbsid=2032&tid=1085778

**Languages**
Chinese

**Website relationship*

**Additional details**

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $15.00)

- [<img src='https://avatars.githubusercontent.com/u/27136773?v=4' alt='ronny1982' width=24 height=24> ronny1982](https://issuehunt.io/u/ronny1982) ($5.00)
- [<img src='https://avatars.githubusercontent.com/u/60792860?v=4' alt='suikodoen13' width=24 height=24> suikodoen13](https://issuehunt.io/u/suikodoen13) ($10.00)

### Submitted pull Requests
- [#3300 [6parkbbs] added website support (#3191)](https://issuehunt.io/r/manga-download/hakuneko/pull/3300)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/manga-download/hakuneko/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by sisco0** [comment]
I could see there are many subforums at that BBS. Are you interested in one in specific? (Ex: https://club.6parkbbs.com/enter6/)

**Comment by 27136773** [comment]
Looks like cross-linking between the sub-domains as well.
I would start with only one for now and then see how it works.
It may already work for both since the page layout seems exact the same for the sub-domians.

**Comment by dodieboy** [comment]
From https://web.6parkbbs.com/index.php?act=bbs&bbsid=2032 subforums, I found that other than manga, it also have [audio ](https://web.6parkbbs.com/index.php?app=forum&act=view&tid=1112847)and [video](https://web.6parkbbs.com/index.php?app=forum&act=view&tid=1116379).
So only manga is needed to be implement right? (i take it as a yes)

**Comment by dodieboy** [comment]
@ronny1982 i think can close this issues alr
