### ISSUE TITLE
[Site Request] Mangaowl

### ISSUE THREAD

**Issue by melai8** [manga-download/hakuneko#3194]
**Name of the website**
MangaOwl

**Website urls (examples below)**
- Site: https://mangaowl.net/
- Manga List: https://mangaowl.net/search
- Manga example: https://mangaowl.net/single/57188/love-is-an-illusion
- Chapter online viewer example: https://chessmoba.us/team/Mjg5LjA=?utm_source=google&utm_medium=organic

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website 
i think its like mangago?

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See: #2335
