### ISSUE TITLE
[MangaLife] Connector not working

### ISSUE THREAD

**Issue by hentaikamen1** [manga-download/hakuneko#3198]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Almost all notable manga site doesnt work on hakuneko like (mangalife and mangafreak) all the pages are blank or they dont reload anymore

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![160617078_771901946774486_9182832712211786964_n](https://user-images.githubusercontent.com/80653179/111113802-45107c00-859d-11eb-96da-52de7d4b264c.jpg)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
MangaLife is working fine here, mangafreak: read the pinned issue.
Unless more details is given, this issue will be closed.

**Comment by hentaikamen1** [comment]
> MangaLife is working fine here, mangafreak: read the pinned issue.
> Unless more details is given, this issue will be closed.

I mean the chapter don’t show anything it is all white

**Comment by hmsong01** [comment]
Huh?  Manga LIfe works?  Here's what happens:
https://i.ibb.co/ZfbdxNP/01.png

**Comment by hentaikamen1** [comment]
> Huh? Manga LIfe works? Here's what happens:
> https://i.ibb.co/ZfbdxNP/01.png
> 
> The chapter shows, but once you initiate the download, it just gets error and fails.

for me the chapter aren't showing also unable to dl it and one i look for the source of error i see this 
![160654566_444483656878278_9119222219721308016_n](https://user-images.githubusercontent.com/80653179/111115321-64a8a400-859f-11eb-9042-479e64214bfd.jpg) this is what it's saying about mangalife - Failed to load resource: net::ERR_NOT_IMPLEMENTED then to the chapters - Failed to load resource: net::ERR_NAME_NOT_RESOLVED

**Comment by Sheepux** [comment]
Did you try the nightly ?
![MangaLife](https://user-images.githubusercontent.com/19878135/111117439-cfd68400-8567-11eb-83d4-d348e4dd470a.png)

**Comment by hentaikamen1** [comment]
> Did you try the nightly ?
> ![MangaLife](https://user-images.githubusercontent.com/19878135/111117439-cfd68400-8567-11eb-83d4-d348e4dd470a.png)

how?

**Comment by Sheepux** [comment]
The download buttons on the front pages ....

**Comment by hentaikamen1** [comment]
> The download buttons on the front pages ....

nope doesn't either

**Comment by Sheepux** [comment]
Then, please give a manga name (as asked in the issue template) because i'm unable tor reproduce the issue.

**Comment by hentaikamen1** [comment]
> Then, please give a manga name (as asked in the issue template) because i'm unable tor reproduce the issue.

all manga in mangalife doesn't show any picture like this
![160617078_771901946774486_9182832712211786964_n](https://user-images.githubusercontent.com/80653179/111118651-05995e00-85a4-11eb-9e86-c27cb7e217b1.jpg) they stay up white

**Comment by Sheepux** [comment]
Click the menu icon in the topleft. What is the revision displayed ("rev")

**Comment by hentaikamen1** [comment]
> Click the menu icon in the topleft. What is the revision displayed ("rev")

6.1.7

**Comment by Sheepux** [comment]
Then ... again. Try the Nightly

**Comment by hentaikamen1** [comment]
> Then ... again. Try the Nightly

if i try the nightly do i have to remove the hakuneko?

**Comment by hentaikamen1** [comment]
> Then ... again. Try the Nightly

how do you use the nightly i dont understand it when i click the nighly it shows a lot of nighly(master) how or what do i do?

**Comment by ronny1982** [comment]
Same issue: #3189

**Comment by hmsong01** [comment]
When you say "Nightly", are you talking about the 2020-07-05 version?  Because that's the most recent version that I'm seeing on https://github.com/manga-download/hakuneko/releases

**Comment by hentaikamen1** [comment]
Who ever developer that fix this thank you because i just woke and tried to open it and it work thx

**Comment by hmsong01** [comment]
Ohh, you're right.  It's fixed.  Consider this subject resolved.  Thanks!
