### ISSUE TITLE
[Manga Life] Connector not working

### ISSUE THREAD

**Issue by hmsong01** [manga-download/hakuneko#3199]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can see the list of the Manga Life downloads, but for whatever reason, the downloads all fail from that site.

**To Reproduce**
1. Manga Life
2. (any manga, but let's just say Release That Witch)
3. (any chapter, but let's just say ch.240)
4. The download simply fails.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - 6.1.7

**Comment by 27136773** [comment]
Same as #3189
