### ISSUE TITLE
[Bug] Kakao page

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#3208]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
YES

**Describe the bug**
can't get list of available chapters for some webtoons (i found one). and, can't login in hakuneko in kakao's connector.

**To Reproduce**
1. copy this link : https://page.kakao.com/home/%EC%B2%9C%EC%9E%AC-%EC%9D%98%EC%82%AC-%EC%9D%B4%EB%AC%B4%EC%A7%84/56329995
2. use clipboard 
3. click on the webtoon to get chapterlist
4. no chapters (in the browser there is 28 chapters)

**Expected behavior**
i get chapterlist for the first bug. second bug i can't login.

**Context (please complete the following information):**
 - OS: windows 10 20H2
 - HakuNeko Version 8.3.4/6.1.7

**Comment by ap-sensei** [comment]
I am having the same problem too
I can see the webpage in my browser, however, in HakuNeko, it says
"Connection Timed Out"

**Comment by XenonR** [comment]
Closed by merging #3239

**Comment by Ever4engel** [comment]
@XenonR you done an error about this ticket. he's related about other bugs (the login bug)

**Comment by MikeZeDev** [comment]
Tested, fixed
