### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by shohibi** [manga-download/hakuneko#3209]
![image](https://user-images.githubusercontent.com/80662489/111757110-8d95a580-88cd-11eb-9d36-8628b9f92fa6.png)
How to fix website: mangaku.pro

**Comment by 27136773** [comment]
MangaKu is frequently fighting against HakuNeko.
Right now there is no time for their cat and mouse game, so currently nothing will be done...

**Comment by 27136773** [comment]
See: #2977
