### ISSUE TITLE
[Feature] Allow saving the chapters as zip, or at least recognize zip files as downloaded chapters

### ISSUE THREAD

**Issue by hikigaya-haru** [manga-download/hakuneko#3210]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like that the UI recognized .zip files with the same name as the chapter folder as a chapter. I don't like the cbz/epub formats, and would like to save my downloads as zip files of each chapter to allow for faster file transfers. If it is not possible to add an option to download directly to zip, at least some file name parsing to allow the UI to recognize $chapter_name (the folder) and $chapter_name.zip as equal and mark it as downloaded.

**Context (please complete the following information):**
HakuNeko Version 6.17

**Comment by manh21** [comment]
cbz is a zip

**Comment by 27136773** [comment]
In settings use `Post Command` to rename `.cbz` to `.zip`
For more details check the docs or ask in discord
