### ISSUE TITLE
myreadingmanga.info

### ISSUE THREAD

**Issue by babytoaster** [manga-download/hakuneko#3218]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes i am able to see the website without issues on my browser.

**Describe the bug**
when i click on the mangalist to update the site, it gives me an error failed to update manga list for myreadingmanga failed to load within the given timeout of60 seconds!

**To Reproduce**
1. Name of connector myreadingmanga.info
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17@beb46f

**Comment by 27136773** [comment]
Handled by #2933
