### ISSUE TITLE
[Site Request] chibimanga

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#3220]
**Name of the website**
chibimanga

**Website urls (examples below)**
- Site: https://www.cmreader.info/
- Manga List: https://www.cmreader.info/?s&post_type=wp-manga&m_orderby=alphabet
- Manga example: https://www.cmreader.info/manga/rere-hello/
- Chapter online viewer example: https://www.cmreader.info/manga/rere-hello/volume-11/chapter-43/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
A scanlator website

**Comment by 27136773** [comment]
Already supported
