### ISSUE TITLE
[Site Request] MangaOwl

### ISSUE THREAD

**Issue by GGFreak77** [manga-download/hakuneko#3222]
**Name of the website**
MangaOwl

**Website urls (examples below)**
- Site: https://mangaowls.com
- Manga List: https://mangaowls.com/shared_list
- Manga example: https://mangaowls.com/single/46812/walk-on-water
- Chapter online viewer example: https://mostraveller.com/what-to-do-and-what-to-see-in-quy-nhon-vietnam?utm_source=google&utm_medium=organic

**Languages**
I think English only.

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
Not sure but I think Animeow: https://animeow.me

**Additional details**
Add any other context details that you may have found (like template to reuse)
Not sure too.

**Comment by 27136773** [comment]
See: #2335
