### ISSUE TITLE
[Toonily] Connector not working

### ISSUE THREAD

**Issue by ratchet3131** [manga-download/hakuneko#3223]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
After trying to connect to Toonily, a 60 second timeout error is produced.

**To Reproduce**
1. Toonily

**Screenshots**
![image](https://user-images.githubusercontent.com/81117143/111921398-8eefdb00-8a51-11eb-941e-e87c0e342249.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
Handled by #2933
