### ISSUE TITLE
Download Skip Button

### ISSUE THREAD

**Issue by MadaHaz** [manga-download/hakuneko#3226]
**Is your feature request related to a problem? Please describe.**
Sometimes a download will become stuck because the images are not viewable on the website where it is being downloaded from. If other downloads are queued from various different mangas then the stuck download will hold up the other downloads.

**Describe the solution you'd like**
I would like there to be a button which when pressed can skip the current download.

**Describe alternatives you've considered**
An alternative way to do this is to close and reopen HakuNeko but it will result in the loss of other downloads.

**Context (please complete the following information):**
 My current HakuNeko version is rev. 6.1.7@beb46f.

**Comment by 27136773** [comment]
This will not be addressed in the current version of HakuNeko
Kind of related: #8
