### ISSUE TITLE
[TurkToon] Connector not working

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#3228]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
episodes are not downloaded.
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Please provide manga and chapter which does not work.

**Comment by MikeZeDev** [comment]
Works on nightly. Mangalist, preview and download.

Can be closed i guess . @Sheepux please <3
