### ISSUE TITLE
[Site Request] comica

### ISSUE THREAD

**Issue by jonjhmoon** [manga-download/hakuneko#3230]
**Name of the website**
Comica

**Website urls (examples below)**
- Site: https://www.comica.com/
- Manga List: https://www.comica.com/
- Manga example: https://www.comica.com/webtoon/episode/103956/
- Chapter online viewer example: https://www.comica.com/webtoon/episode/view/1000078950/

**Languages**
Korean

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
dead website?
