### ISSUE TITLE
[Japanread] Connector not working

### ISSUE THREAD

**Issue by zazouze** [manga-download/hakuneko#3236]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
download does not work

**To Reproduce**
1. Name of connector : Japanread
2. Name of manga (if connector update is working) : "Mi" Seijuku
3. Name of chapter (if manga update is working) : tous
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 404 ()
mjs/engine/Connector.mjs:624 Error: Failed to receive content from "https://www.japanread.cc/api/?type=chapter&id=125119" (status: 404) - 
    at mjs/engine/Connector.mjs:475
    at async JapanRead._getPages (mjs/connectors/JapanRead.mjs:56)
    at async JapanRead._getPageList (mjs/engine/Connector.mjs:621) EventTarget
**Screenshots**
![Capture](https://user-images.githubusercontent.com/62121714/112469558-e8198080-8d69-11eb-9c48-33dcc1fa73b2.PNG)

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by Robonau** [comment]
needs header `x-requested-with": "XMLHttpRequest`
cba to do it myself

**Comment by zazouze** [comment]
what is cba? I don't know the computer language

already present
![image](https://user-images.githubusercontent.com/62121714/112722268-ca365200-8f08-11eb-9507-611fd2e0acb4.png)
