### ISSUE TITLE
[Japanread] Connector not working

### ISSUE THREAD

**Issue by Dani97411** [manga-download/hakuneko#3237]
Hello when i try to download or read a chapter on the japanread site from HakuNeko i get this error. But on the site its function correctly. I only have problem for japanread
 
1. Japanread
2. I have the problem with all mangas
3. I have the problem with all chapter
4. ![error msg](https://user-images.githubusercontent.com/81385489/112534952-255f2c00-8dc5-11eb-8d03-4ee2739fc6e6.PNG)

**Comment by 27136773** [comment]
See #3236
