### ISSUE TITLE
[mangalek.com] Connector not working

### ISSUE THREAD

**Issue by crown869** [manga-download/hakuneko#3238]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
yes.
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
its working perfectly, and yes i can see the manga with the normal browser.
**Describe the bug**
it was working normally untill like 2 months where it stoped working and when i try to refresh the manga list or download any manga it says: failed to load within the given time of 60 sec.
![haku](https://user-images.githubusercontent.com/81412203/112609866-59b20700-8e1c-11eb-97ac-5bfbfef6417a.png)

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Bmswad1** [comment]
See #2933
