### ISSUE TITLE
[Site Request]    Piccoma    https://piccoma.com/web/

### ISSUE THREAD

**Issue by CN2025** [manga-download/hakuneko#3244]
**Name of the website**
Piccoma  
**Website urls (examples below)**
- Site: https://piccoma.com/web/
- Manga List: https://piccoma.com/web/category/product/list/2/N   (webtoon list)
- Manga example: https://piccoma.com/web/product/5523?etype=episode          (webtoon)
- Chapter online viewer example: https://piccoma.com/web/viewer/5523/321910     (webtoon)

**Languages**
Japanese

**Comment by sisco0** [comment]
I think this is not similar to any webpage we have at our database, could this be a new template?

**Comment by 27136773** [comment]
Probably individual website with individual reader

**Comment by CN2025** [comment]
their website is really bad for reading manga: like this one https://piccoma.com/web/viewer/3718/211938
I wanted to save some manga i bought from there

**Comment by 0xh3LL0** [comment]
this may help @ronny1982 
https://github.com/Elastic1/piccoma-downloader
