### ISSUE TITLE
[Site Request] mangapark v3 / mangapark dev

### ISSUE THREAD

**Issue by mangatabar** [manga-download/hakuneko#3246]
**Name of the website**
mangapark v3

**Website urls (examples below)**
- Site: https://v3.mangapark.net/
- Manga List: https://v3.mangapark.net/browse
- Manga example: https://v3.mangapark.net/comic/77581/i-got-a-cheat-ability-in-a-different-world-and-became-extraordinary-even-in-the-real-world
- Chapter online viewer example: https://v3.mangapark.net/chapter/2618992

**Languages**
English

**Website relationship*
mangapark.net

**Additional details**
since some manga / uploader sometime only post on this dev site instead mangapark.net

**Comment by 27136773** [comment]
Should we add support for a version of the website that is in development right now, or wait until it is finished?

**Comment by mangatabar** [comment]
on the website 
![image](https://user-images.githubusercontent.com/46851278/113404760-e20f4980-93d2-11eb-90bb-546e59d8c236.png) but from few weeks ago maybe 1-2 month? the update on actual web/non dev version start to decrease and only upload on this dev site

**Comment by 27136773** [comment]
=> Replacing the current MangaPark.net connector website with the v3 version.
