### ISSUE TITLE
[Site Request] Comic Bushiroad

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#3249]
**Name of the website**
ComicBushiroadWeb

**Website urls (examples below)**
- Site: comicbushi-web.com
- Manga List: https://comicbushi-web.com/#lineup
- Manga example: https://comicbushi-web.com/episode/3269632237268235921
- Chapter online viewer example: https://comicbushi-web.com/episode/3269632237268235921

**Languages**
Japanese

**Comment by sisco0** [comment]
Similar to _CoreView_
```
WordPressMadara https://yuri.live 1.0 1.0 1.0
WordPressMadara https://hentairead.com 1.0 1.0 1.0
CoreView https://viewer.heros-web.com 1.0 1.0 1.0
CoreView https://tonarinoyj.jp 1.0 1.0 1.0
CoreView https://shonenmagazine.com 1.0 1.0 1.0
CoreView https://shonenjumpplus.com 1.0 1.0 1.0
CoreView https://pocket.shonenmagazine.com 1.0 1.0 1.0
CoreView https://magcomi.com 1.0 1.0 1.0
CoreView https://kuragebunch.com 1.0 1.0 1.0
CoreView https://comic-zenon.com 1.0 1.0 1.0
CoreView https://comic-gardo.com 1.0 1.0 1.0
CoreView https://comic-days.com 1.0 1.0 1.0
CoreView https://comicborder.com 1.0 1.0 1.0
CoreView https://comic-action.com 1.0 1.0 1.0
```
![image](https://user-images.githubusercontent.com/25695302/113520716-c59e1900-955a-11eb-901c-152afcb02f27.png)
