### ISSUE TITLE
Add Hoshinoromi

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#325]
https://hoshinoromi.org/

**Comment by 27136773** [comment]
Website cannot be reached, may this be region locked?

**Comment by Ever4engel** [comment]
it work on my side ![image](https://user-images.githubusercontent.com/47645041/62627208-3b3a8780-b929-11e9-8341-cdf3eac1edfe.png)
But ya, maybe for your region it could use Ip restrictions

**Comment by hypoflex** [comment]
tried all kinds of VPN servers. seems pretty down to me @Ever4engel still working for you?

**Comment by Ever4engel** [comment]
No, dowm antil 2 months

**Comment by hypoflex** [comment]
Topic closed for down webpage
