### ISSUE TITLE
Manga1001 Referer Protection Issue (One Piece)

### ISSUE THREAD

**Issue by Shoxx98** [manga-download/hakuneko#3251]
https://cdn.discordapp.com/attachments/581630792120401922/826198178973614160/unknown.png
as seen in picture: One Piece (ワンピース) chapter 99x failed to download
link: https://manga1001.com/%e3%83%af%e3%83%b3%e3%83%94%e3%83%bc%e3%82%b9-raw-free1/

**Comment by XenonR** [comment]
Works fine for me. Is it possible you downloaded too much in a short period of time?
![image](https://user-images.githubusercontent.com/18627623/113132460-c5caab80-921e-11eb-81f2-b5d4e8e6d2db.png)

**Comment by 27136773** [comment]
Confirmed failure some days ago

![image](https://user-images.githubusercontent.com/27136773/113413924-0a3f7e00-93bc-11eb-91f3-9aba193ba5fa.png)

**Comment by ronny1982** [comment]
Ok it seems for some reason i forgot to merge the current `Manga1001` into 6.1.7, because Nightly already has referer protection bypass implemented...

**Comment by 27136773** [comment]
See #3219
