### ISSUE TITLE
[Site Request] meionovel

### ISSUE THREAD

**Issue by MoonLGH** [manga-download/hakuneko#3253]
**Name of the website**
meionovel

**Website urls (examples below)**
- Site: https://meionovel.id/
- Manga List: https://meionovel.id/novel-tag/htl
- Manga example: https://meionovel.id/novel/maou-gakuin-no-futekigousha/
- Chapter online viewer example: https://meionovel.id/novel/maou-gakuin-no-futekigousha/mtl/chapter-122/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Tags**
Manga,Novel,Indonesia,

**Additional details**
there is sometimes 2 option on manga example page. mtl and htl

**Comment by 27136773** [comment]
Template: WordPressMadara(Novel)
