### ISSUE TITLE
[Site Request] wbnovel

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#3257]
**Name of the website**
WBNOVEL

**Website urls (examples below)**
- Site: https://wbnovel.com/
- Manga List: https://wbnovel.com/novel/
- Manga example: https://wbnovel.com/novel/the-fantastic-super-vision/
- Chapter online viewer example: https://wbnovel.com/novel/the-fantastic-super-vision/chapter-796/

**Languages**
INDONESIA

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
WordpressMadaraNovel
![mna](https://user-images.githubusercontent.com/81703465/113179162-8aa99600-9279-11eb-90a5-3a8914c0bde8.png)

**Comment by 27136773** [comment]
See: #2796
