### ISSUE TITLE
[Site Request] lianscans

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3258]
**Name of the website**
lianscans

- Site: https://www.lianscans.my.id/
- Manga List: https://www.lianscans.my.id/manga-list/
- Manga example: https://www.lianscans.my.id/series/watashi-no-tomodachi-ga-sekaiichi-kawaii/
- Chapter online viewer example: https://www.lianscans.my.id/watashi-no-tomodachi-ga-sekaiichi-kawaii-chapter-08-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Could be WordPressMangastream template
