### ISSUE TITLE
[Site Request] kumamanga

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3259]
**Name of the website**
kumamanga

- Site: https://kumamanga.my.id/
- Manga List: https://kumamanga.my.id/project-kuma/
- Manga example: https://kumamanga.my.id/series/made-in-abyss/
- Chapter online viewer example: https://kumamanga.my.id/made-in-abyss-chapter-50-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Could be WordPressMangastream template
