### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by dervdinditii** [manga-download/hakuneko#3261]
**It's a hassle when you accidentally click a chapter and redoing the process just to stop it.**

**If you can, please add 'pause' feature in downloading.*

**Aside from .cbz, can you please add .cb7? And another, can you make the interface cleaner?**

**HakuNeko Version 6.1.7**

**Comment by 27136773** [comment]
First is duplicate of #8
Each user has a different opinion of `Clean UI`. Make detailed descriptions of what exactly should be changed. Try to disable preview in settings.

Only one request per ticket => Closed
