### ISSUE TITLE
[Tritinia Scans] Connector not working

### ISSUE THREAD

**Issue by hesoyamma785** [manga-download/hakuneko#3263]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector Tritinia Scans
2. Name of manga (if connector update is working) Doesn't show anything
3. Name of chapter (if manga update is working) Doesn't show anything
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![Untitled111111](https://user-images.githubusercontent.com/77359705/113245858-100a6600-92cd-11eb-9769-22ddfcd5b105.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Developers Note:
- Need to update domain
- Need to remove customized implemented `_getMangas()` method

**Comment by hesoyamma785** [comment]
> Developers Note:
> 
> * Need to update domain
> * Need to remove customized implemented `_getMangas()` method

is there any tutorial for this method?

**Comment by 27136773** [comment]
If you are not a developer/contributor there is nothing you can do and you have to wait for someone fixing this

**Comment by sisco0** [comment]
The new website uses _AJAX_ lazy loading so this may difficult the task of getting the complete list of the mangas. Hopefully something could be done basing us in JSON parsing.

**Comment by 27136773** [comment]
If we are lucky, we may re-use the base method from `WordPressMadara` template
