### ISSUE TITLE
[Site Request] Penlab

### ISSUE THREAD

**Issue by dervdinditii** [manga-download/hakuneko#3267]
**Name of the website**
Penlab - Pinoy komiks in one page

**Website urls (examples below)**
- Site: http://penlab.ink/
- Manga example: http://penlab.ink/titles/katipunera-warrior-kalabaw-kolektib/
- Chapter online viewer example: http://penlab.ink/titles/katipunera-warrior-kalabaw-kolektib/pitik-bulag-part-1/

**Languages**
English and Filipino

**Comment by sisco0** [comment]
Very similar to _FlatManga_.

```
FlatManga https://truyentranhlh.net 0.07207207207207207 0.014806980433632998 0.04343952625285254
FlatManga https://www.epikmanga.com 0.07017543859649122 0.033608116677235254 0.05189177763686324
WordPressMadara https://einherjarscans.space 0.056451612903225805 0.10526315789473684 0.08085738539898132
MangaReaderCMS https://leomanga.me 0.055 0.04452054794520548 0.04976027397260274
MangaReaderCMS https://ninemanga.net 0.05472636815920398 0.04452054794520548 0.04962345805220473
FlatManga https://kissaway.net 0.05241935483870968 0.030598052851182198 0.04150870384494594
WordPressMadara https://martialscans.com 0.05 0.03121951219512195 0.04060975609756098
MangaReaderCMS https://animaregia.net 0.04938271604938271 0.045941807044410414 0.04766226154689657
MangaReaderCMS https://trwebtoon.com 0.04830917874396135 0.024029574861367836 0.03616937680266459
FlatManga https://lovehug.net 0.047244094488188976 0.03555104113763331 0.041397567812911144
```

![image](https://user-images.githubusercontent.com/25695302/113520386-54f5fd00-9558-11eb-9836-125e9d42dab9.png)
![image](https://user-images.githubusercontent.com/25695302/113520390-5f17fb80-9558-11eb-9d27-b46ef61c2caf.png)
