### ISSUE TITLE
[Ngomik] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3269]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector Ngomik
2. A Returner’s Magic Should Be Special (if connector update is working) but only alphabet a which work, the rest of it not working
3. A Returner’s Magic Should Be Special Chapter 141 (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/79199707/113466038-df5c3500-9462-11eb-8702-85d94d5d9721.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
The description in the ticket does not state what exactly is the problem
