### ISSUE TITLE
[lezhin korea] Connector not working

### ISSUE THREAD

**Issue by brmqtr** [manga-download/hakuneko#3271]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

I bought chapters of this manhwa on lezhin
https://www.lezhin.com/ko/comic/walk_night

But when I try to download it, the download keeps failing. 

I bought some manhwa from lezhin about a month ago, and they downloaded fine a month ago. But it's not downloading now.

I also tried to download some manhwa I bought from lezhin againn, but the download of anotheor manhwa also failed. I think lezhin is blocking download from Hakuneko

Could you fix the download problem please?

**To Reproduce**
1. Name of connector - lezihn
2. Name of manga (if connector update is working)  밤을 걷는 선비/Scholar Who Walks the Night
3. Name of chapter (if manga update is working) chapter 60 - 113
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

https://i.imgur.com/O9ITtBF.png

https://i.imgur.com/FpDPpBd.png

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
Version 6.17

**Comment by 27136773** [comment]
Your automatic login probably failed.
Try [manual login](https://hakuneko.download/docs/manual-website-interaction/#account-login) before accessing anything from Lezhin, or try reloading/restarting HakuNeko in hope the automatic login may work after that.

**Comment by brmqtr** [comment]
Hi

But the chapters which I bought on lezhin is all showing up as available to
download.

https://i.imgur.com/FpDPpBd.png

You see, if  I am not logged in, then I won't be able to  view the list of
the chapters which I bought

On this screenshot, you can see that free chapters (Chapter 1 -3) is
showing and there are chapters which starts from chapter 60

I bought from chapter 60, so chapter 59 58 is not shown on this chapter
list.

**Comment by 27136773** [comment]
I can download the purchased test chapters just fine on my end.

What is shown in the tooltip of the failed download icon in the job list?
What is shown in error console and network connections (F12)?

**Comment by brmqtr** [comment]
Hi

I don't know how to see job list. What do I have to click on to see job
list?

I uninstalled the Hakuneko program and reinstalled it, but I still can't
download from lezhin.

I can download well from naver.

**Comment by brmqtr** [comment]
I forgot to say, I don't know how to view error console and network
connections. If I press F12 I just get a menu to adjust brightness of the
screen.

**Comment by 27136773** [comment]
https://hakuneko.download/docs/interface/#download-queue

**Comment by brmqtr** [comment]
[image: Hakuneko3.png]

The error looks like this.

**Comment by brmqtr** [comment]
https://i.imgur.com/CVm2BYZ.png

Here is a image link of the error.

**Comment by 27136773** [comment]
If manual website login did not solve the problem, i'm afraid i cannot help with that...

**Comment by brmqtr** [comment]
Manual login worked!
Though sometimes there is download error, but if I click on the file and
try to download it again, I can download it.

It's weird because I never got download error a month ago.

Thank you so much for all your help.

**Comment by 27136773** [comment]
Seems to be solved => closed
