### ISSUE TITLE
[Site Request] Fukushuu no Yuusha

### ISSUE THREAD

**Issue by notoraptor** [manga-download/hakuneko#3272]
**Name of the website**
Fukushuu no Yuusha

**Website urls (examples below)**
- Site: https://fny-scantrad.com/
- Manga List: https://fny-scantrad.com/manga/
- Manga example: https://fny-scantrad.com/manga/fate-strange-fake-vf/
- Chapter online viewer example: https://fny-scantrad.com/manga/fate-strange-fake-vf/chapitre-26/

**Languages**
French

**Additional details**
Website seems to be built with Wordpress.

**Comment by 27136773** [comment]
Template: WordPressMadara
