### ISSUE TITLE
[Site Request] manhwaindo

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3273]
**Name of the website**
manhwaindo

**Website urls (examples below)**
- Site: https://manhwaindo.com/
- Manga List: https://manhwaindo.com/daftar-manhwa/
- Manga example: https://manhwaindo.com/series/peerless-dad/
- Chapter online viewer example: https://manhwaindo.com/peerless-dad-chapter-164-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Template: WordPressMangastream

**Comment by XenonR** [comment]
Already merged.
