### ISSUE TITLE
[Site Request] nekomik

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3274]
**Name of the website**
nekomik

**Website urls (examples below)**
- Site: https://nekomik.com/
- Manga List: https://nekomik.com/manga/
- Manga example: https://nekomik.com/manga/sanzennenme-no-kamitaiou/
- Chapter online viewer example: https://nekomik.com/sanzennenme-no-kamitaiou-chapter-7-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Template: WordPressMangastream
