### ISSUE TITLE
[Mangaku] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3276]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
i can't download anything from mangaku

**To Reproduce**
1. Name of connector - Mangaku
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/79199707/113494016-d032c100-950e-11eb-8d9e-5178c896d8ab.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See: #2977
