### ISSUE TITLE
[Site Request] mangadisk

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3277]
**Name of the website**
mangadisk

**Website urls (examples below)**
- Site: https://mangadisk.web.id/
- Manga List: https://mangadisk.web.id/manga-lists/
- Manga example: https://mangadisk.web.id/manga/haite-kudasai-takamine-san/
- Chapter online viewer example: https://mangadisk.web.id/haite-kudasai-takamine-san-ch-26-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Template: WordPressMangastream
