### ISSUE TITLE
[NameOfConnector] sheamanga

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3278]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When i download from sheamanga, there lack of format image from sheamanga were webp not jpg

**To Reproduce**
1. Name of connector - Sheamanga
2. Name of manga (if connector update is working) - Strongest levelling
3. Name of chapter (if manga update is working) - Strongest levelling chapter 1-208
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/79199707/113494121-b0e86380-950f-11eb-84f7-7faf897b43ea.png)
![image](https://user-images.githubusercontent.com/79199707/113494130-b80f7180-950f-11eb-9e5b-312fc0201b9a.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Images are exactly downloaded as they are provided by the website. The mentioned `.webp` images are the credits and obviously by choice hosted as `.webp` by the website owner or scanlation group.

**Comment by 27136773** [comment]
There is even a FAQ about this...
https://hakuneko.download/docs/FAQ/#image-format
