### ISSUE TITLE
[NameOfConnector] boosei

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3279]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When i download from boosei, all format image from boosei were webp not jpg

**To Reproduce**
1. Name of connector - boosei
2. Name of manga (if connector update is working) - Isekai Cheat Magic Swordsman
3. Name of chapter (if manga update is working) - Isekai Cheat Magic Swordsman chapter 1-9
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/79199707/113494224-9bc00480-9510-11eb-9442-efaf23af6081.png)
![image](https://user-images.githubusercontent.com/79199707/113494227-a11d4f00-9510-11eb-90d1-29a863a71c77.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
If website hosts them as `.webp` they are downloaded as `.webp`. Read the documentation on possibilities to force a format conversion (and probably loose the original quality).

**Comment by 27136773** [comment]
There is even a FAQ about this...
https://hakuneko.download/docs/FAQ/#image-format
