### ISSUE TITLE
[Mangago] Connector not working

### ISSUE THREAD

**Issue by michelle912** [manga-download/hakuneko#3282]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When pasting the link to hakuneko, there are no results showing, even though the link works in the browser/ before mangago was down.

**To Reproduce**
1. Name of connector - Mangago
2. Name of manga (if connector update is working) - Fairy Tail
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
Copy & Paste is not working, but the website has tons of broken images not loading correctly.
e.g. http://www.mangago.me/read-manga/fairy_tail/mr/fairy-tail/544/pg-1/

Not sure if it is worth the time right now to fix this ...

**Comment by tori131** [comment]
> Copy & Paste is not working, but the website has tons of broken images not loading correctly.
> e.g. http://www.mangago.me/read-manga/fairy_tail/mr/fairy-tail/544/pg-1/
> 
> Not sure if it is worth the time right now to fix this ...

so will let you know as soon as they fix it???

**Comment by 27136773** [comment]
The PR #3319 will only fix the HakuNeko related errors, it cannot magically fix the download of images that are not even loading in [mangago.me](http://www.mangago.me) website...

![image](https://user-images.githubusercontent.com/27136773/114278279-57ac9280-9a2f-11eb-806b-80f841ea0d9f.png)

**Comment by tori131** [comment]
> The PR #3319 will only fix the HakuNeko related errors, it cannot magically fix the download of images that are not even loading in [mangago.me](http://www.mangago.me) website...
> 
> ![image](https://user-images.githubusercontent.com/27136773/114278279-57ac9280-9a2f-11eb-806b-80f841ea0d9f.png)

Yes, I know that you only fix that. What I wrote is if we have to notify you once mangago.me is recovered and working perfect again

**Comment by 27136773** [comment]
> > The PR #3319 will only fix the HakuNeko related errors, it cannot magically fix the download of images that are not even loading in [mangago.me](http://www.mangago.me) website...
> > ![image](https://user-images.githubusercontent.com/27136773/114278279-57ac9280-9a2f-11eb-806b-80f841ea0d9f.png)
> 
> Yes, I know that you only fix that. What I wrote is if we have to notify you once mangago.me is recovered and working perfect again

I was not replying to your message.
[This](#issuecomment-817171541) is a note for users that come in and complain that MangaGo is still not working, after this ticket is marked as fixed through the currently pending PR #3319.

This also answers your question, there is no further action required, since there is already a ready made fix pending for approval.

**Comment by tori131** [comment]
Now the website is working but i can't download any chapter from the site with hakuneko, every chaptes gives me an error

**Comment by 27136773** [comment]
> Now the website is working but i can't download any chapter from the site with hakuneko, every chaptes gives me an error

See #3351
