### ISSUE TITLE
[MangaGo] Connector not working

### ISSUE THREAD

**Issue by tori131** [manga-download/hakuneko#3283]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**
I try to load the mangago.me data and the hakuneko did not detect any link although I copy the link on my browser.
It worked until yesterday (04/04/2021) and this connector was down for 2 weeks aprox. so maybe there are some changes on it

**To Reproduce**
1. Name of connector: mangago.me
2. Name of manga (if connector update is working) : any
3. Name of chapter (if manga update is working) : any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3282
