### ISSUE TITLE
[mangago.me] Connector not working

### ISSUE THREAD

**Issue by heididoyoudo** [manga-download/hakuneko#3285]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
tried to use the clipboard to enter the url but its not accepting the link it just spins and doesn't pick it up, tried to go to the search,and it gives an error saying "failed to update managa list for mangago, this website does not provide a manga list, please copy and paste the URL containing the chapters directly from your browser into HakuNeko." Which, still doesn't work. Mangago.me was down for couple of weeks, when it came back up, it worked fine up until this morning when it doesn't pick it up anymore.

**To Reproduce**
1. Name of connector mangago.me
2. Name of manga any of them
3. Name of chapter doesn't pick up anything
4. Copy any relevant error message that appears in a popup or (advanced) "failed to update managa list for mangago, this website does not provide a manga list, please copy and paste the URL containing the chapters directly from your browser into HakuNeko."

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3282
