### ISSUE TITLE
[Site Request] Bakaman

### ISSUE THREAD

**Issue by SaiNls** [manga-download/hakuneko#3286]
**Bakaman**
Bakaman

**Website urls (examples below)**
- Site: https://bakaman.net/
- Manga List: https://bakaman.net/manga/
- Manga example: https://bakaman.net/manga/my-new-wife-is-forcing-herself-to-smile/%e0%b8%95%e0%b8%ad%e0%b8%99%e0%b8%97%e0%b8%b5%e0%b9%88-32/
- Chapter online viewer example: https://bakaman.net/manga/my-new-wife-is-forcing-herself-to-smile/%e0%b8%95%e0%b8%ad%e0%b8%99%e0%b8%97%e0%b8%b5%e0%b9%88-24/
- **Languages**
THAI

**Website relationship*

**Additional details**

**Comment by 27136773** [comment]
Template: WordPressMadara

**Comment by 27136773** [comment]
Alreasdy exist, please check before making a request ...
