### ISSUE TITLE
[Site Request] CAT-translator

### ISSUE THREAD

**Issue by SaiNls** [manga-download/hakuneko#3287]
**Name of the website**
CAT-translator

**Website urls (examples below)**
- Site: https://cat-translator.com/manga/
- Manga List: https://cat-translator.com/manga/manga-genre/comedy/
- Manga example: https://cat-translator.com/manga/manga/im-in-trouble-with-my-best-friends-daughter/%e0%b8%95%e0%b8%ad%e0%b8%99%e0%b8%97%e0%b8%b5%e0%b9%88-1/
- Chapter online viewer example: https://cat-translator.com/manga/manga/im-in-trouble-with-my-best-friends-daughter/%e0%b8%95%e0%b8%ad%e0%b8%99%e0%b8%97%e0%b8%b5%e0%b9%88-1/

**Languages**
THAI

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: WordPressMadara
Currently protected by CloudFlare, so it will not work anyway with HakuNeko

**Comment by 27136773** [comment]
Already exist, please check before making a request ...
