### ISSUE TITLE
[myreadingmanga.info] Connector not working

### ISSUE THREAD

**Issue by heididoyoudo** [manga-download/hakuneko#3289]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
its not picking up the connector, and it won't pick up via clipboard, and when you search for it , it won't pick up the manga lists.

**To Reproduce**
1. myreadingmanga.info
2. Name of manga none of them
3. Name of chapter all of them
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dodieboy** [comment]
Handled by #2933
