### ISSUE TITLE
mangago Connector not working

### ISSUE THREAD

**Issue by uuranor** [manga-download/hakuneko#3291]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The website appears offline when using hakuneko, but it's online
**To Reproduce**
1. Name of connector - mangago
2. Name of manga (if connector update is working) any manga
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
hakuneko://plugins/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:61 Loading Frontend: frontend@classic-dark
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version . 6.17

**Comment by 27136773** [comment]
See #3282
