### ISSUE TITLE
[Mangago & Mangahasu] Connector not working

### ISSUE THREAD

**Issue by ladymav** [manga-download/hakuneko#3292]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes to both

**Describe the bug**
For Mangago it fails to load manga list and times out after 25 seconds, for Mangahasu it fails to load manga list and times out after 60 seconds

**To Reproduce**
1. Mangago click the refresh button and it times out after 25 seconds.
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

1. Mangahasu click the refresh button and it times out after 60 seconds.
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Mangago: duplicate: #3282
Mangahasu Handled by #2933

**Comment by ladymav** [comment]
The issue for mangahasu was Not handled. the problem still remains

    On Tuesday, April 6, 2021, 12:17:23 PM CDT, Sheepux ***@***.***> wrote:  
 
 


Mangago: duplicate: #3282
Mangahasu Handled by #2933

**Comment by Sheepux** [comment]
The issue is not solved, it will be "handled" by the other issue.
