### ISSUE TITLE
[Hiperdex] Connector not working

### ISSUE THREAD

**Issue by KillerXSF** [manga-download/hakuneko#3293]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connector fails to update manga list. Error pops up as mentioned below with screenshot.

**To Reproduce**
1. Name of connector - Hiperdex
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message - Failed to update manga list for Hiperdex. Failed to load "https://hiperdex.com" within the given timeout of 60 seconds! 

**Screenshots**
![hiperdex error](https://user-images.githubusercontent.com/82061496/113779127-da410380-974a-11eb-975d-10ff09e16249.PNG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Handled by #2933
