### ISSUE TITLE
[Mangago] Connector not working

### ISSUE THREAD

**Issue by lacewing13** [manga-download/hakuneko#3295]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The manga all load fine in the manga list, but none of them show chapters when selected. It shows 0/0 chapters for all manga. The connector has been having issues with their site. The connector works ok in browser and worked normally for downloads as of this morning(no issues) ~12hours ago

**To Reproduce**
1. Name of connector- Mangago
2. Name of manga All
3. Name of chapter All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
N/A
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3282
