### ISSUE TITLE
[Site Request] https://animesuge.io/

### ISSUE THREAD

**Issue by windtucker** [manga-download/hakuneko#3296]
**Name of the website**
https://animesuge.io/

**Website urls (examples below)**
- Site: https://animesuge.io/
- Manga List: https://animesuge.io/anime/
- Manga example: https://animesuge.io/anime/black-clover-v2k6/ep-1
- Chapter online viewer example:  https://animesuge.io/anime/black-clover-v2k6/ep-1

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)
Anime!

**Comment by MikeZeDev** [comment]
Dead website.

**Comment by MikeZeDev** [comment]
https://animesuge.to/ ? 

related to Aniwave/Mangafire galaxy?

**Comment by MikeZeDev** [comment]
Website id dead as of today
