### ISSUE TITLE
[Lezhin] Connector not working (Free Chapters)

### ISSUE THREAD

**Issue by BaronKrause** [manga-download/hakuneko#3297]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Free chapters cannot be downloaded fir this title if logged in. If you log out they can be, as long as the free chapter doesn't require a login.

For example, the manga "The Love Doctor" has chapter 1 and 2 free, the first one is available to everyone without a login, but the second one requires you to be logged in to view even though its free.

If I'm logged into my account those 2 chapters will fail, but if I log out I can get the first one, but the second will still fail since it needs to be logged in.

Someone on another forum suggested that it is because Hakuneko uses "&purchased=true" for all non r18 chapters when logged in, and that throws an error on free chapters. When logged out it uses "&purchased=false" but then you run into the issue of not being able to download the free chapters that require logins.   `¯\_(ツ)_/¯`

**To Reproduce**
1. Lezhin (english)
2. The Love Doctor
3. 1, 2 and Epilogue (all 3 are free, the latter 2 require logins to access)
4. Error: Page "https://ccdn.lezhin.com/v2/comics/5043026657542144/episodes/5792558580236288/contents/scrolls/22?access_token=********-****-****-****-************&purchased=true&q=40" returned status: 403 -

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - nightly(master) • 2020-07-05T00:14:37UTC

EDIT:
Removed user's access token from link

**Comment by 27136773** [comment]
Maybe related #3413
Was this solved with #3419?

**Comment by 27136773** [comment]
Can no longer be reproduced on my end (2021-05-29)
Logged Out: Only chapter 1 can be read
Logged In: Chapter 1  + 2 can be read
