### ISSUE TITLE
[Asura Scans] Connector not working

### ISSUE THREAD

**Issue by M1A1H** [manga-download/hakuneko#3298]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
 Nothing is loading - It has been more than a week since this problem arose.

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![-](https://user-images.githubusercontent.com/82076862/113815040-3c196180-977b-11eb-9dfc-794c952ad4aa.PNG)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
Handled by #2933
