### ISSUE TITLE
Add Mangapo

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#330]
https://www.mangapo.net

**Comment by 27136773** [comment]
Website timed out for me, may this be region lock?

**Comment by Ever4engel** [comment]
Server problems
Privously it worked for me

**Comment by hypoflex** [comment]
after trying few times with VPN to japan it finally showed up
to be nothing
![image](https://user-images.githubusercontent.com/36196198/65739224-c5f76180-e0e4-11e9-902b-ecff561c88bb.png)
