### ISSUE TITLE
[https://toonily.com] Connector not working

### ISSUE THREAD

**Issue by yks111** [manga-download/hakuneko#3301]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Few days ago   https://toonily.com/  was working properly by  clipboard and bookmarks  but not now  its not working by anyway.  its can not connect to Toonliy by  clipboard and bookmarks .

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.1.7]

**Comment by Sheepux** [comment]
Cloudflare compatibility issue.
will be fixed by #2989 see #2933 (but will take a very long time before fixing)
