### ISSUE TITLE
[WebtoonXYZ] Connector not working

### ISSUE THREAD

**Issue by FajnB** [manga-download/hakuneko#3302]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
- When trying to update the list of available mangas on WebtoonXYZ by selecting the connector and updating the list a pop-up -shows up with unable to connect within 60 seconds.
- When trying to directly paste **working** website link the update starts automatically but after 60 seconds stops without any error.
- Saved bookmark has the same problem as direct link where it tries to update but fails without any error message and shows files stored on device where the gray folder icon after hovering over it shows text:

> OFFLINE     The chapter is only accessible from manga directory

**To Reproduce**

1. Click on WebtoonXYZ
2. Click to update manga list
2. _Result:_ Pop-up message about 60 sec timeout to website viz. screenshots

OR

1. Paste link from clipboard
2. _Result:_ Update button stops spinning and no manga or episodes is/are shown

**Screenshots**
![err_msg](https://user-images.githubusercontent.com/65245546/113867929-68e76c00-97af-11eb-908d-d0a361945ff4.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7
 - Revision 4c2d07

**Comment by Sheepux** [comment]
will be fixed by #2989 see #2933 (but will take a very long time before fixing)
