### ISSUE TITLE
[Mangafast] Connector not working

### ISSUE THREAD

**Issue by exedox** [manga-download/hakuneko#3305]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Getting error getUpdatedChaptersFromWebsite TypeError: Cannot read 

**To Reproduce**
1. Mangafast
2.  Seduce The Villain's Father
3. Missing chapter list
4. Connector.mjs:598 TypeError: Cannot read property 'textContent' of null
    at Mangafast.mjs:48
    at Array.map (<anonymous>)
    at Mangafast._getChapters (Mangafast.mjs:45)
    at async Mangafast._getChapterList (Connector.mjs:595) EventTarget
_getChapterList @ Connector.mjs:598
Manga.mjs:153 _getUpdatedChaptersFromWebsite TypeError: Cannot read property 'textContent' of null
    at Mangafast.mjs:48
    at Array.map (<anonymous>)
    at Mangafast._getChapters (Mangafast.mjs:45)
    at async Mangafast._getChapterList (Connector.mjs:595)le (press F12)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
Already fixed in #3266, use nightly or wait for merge into 6.1.7
