### ISSUE TITLE
MangaOwl

### ISSUE THREAD

**Issue by jcielfujiwara** [manga-download/hakuneko#3306]
MangaOwl

Site: https://www.mangaowl.net/view_category/2687

Manga List: https://www.mangaowl.net/search

Manga Example: https://www.mangaowl.net/single/57188/love-is-an-illusion

Chapter online viewer example: https://mangaowls.com/reader/50276/1103724/445215?s=aHR0cHM6Ly93d3cubWFuZ2Fvd2wubmV0

**Languages**
English

**Comment by 27136773** [comment]
See: #2335
