### ISSUE TITLE
manhuagui.com :FAILED TO UPDATE MANGA LIST

### ISSUE THREAD

**Issue by usafoi** [manga-download/hakuneko#3309]
1. https://www.manhuagui.com/
2. NONE
3. NONE
4. SCREENSHOT : https://imgur.com/a/mdJbiUO
**

**HakuNeko __
 - Version [e.g. 6.17@4c2d07]

**Comment by 27136773** [comment]
Use copy & paste feature as shown in the message / described in the documentation
