### ISSUE TITLE
[Site Request] nekopost.net

### ISSUE THREAD

**Issue by thitikorn123** [manga-download/hakuneko#3311]
**Name of the website**
nekopost.net

**Website urls (examples below)**
- Site: https://www.nekopost.net/
- Manga List: https://www.nekopost.net/manga
- Manga example: https://www.nekopost.net/manga/6842
- Chapter online viewer example: https://www.nekopost.net/manga/6842/20

**Languages**
THAI

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #3288
