### ISSUE TITLE
[Site Request] RoozFun

### ISSUE THREAD

**Issue by roshel188** [manga-download/hakuneko#3312]
RoozFun

**Website urls (examples below)**
- Site: https://www.roozfun.com/
- Manga List: https://www.roozfun.com/booklist/
- Manga example: https://www.roozfun.com/book/3256
- Chapter online viewer example: https://www.roozfun.com/chapter/206030

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `MH`
