### ISSUE TITLE
Can't download and not show preview on [MangaToonIndonesian]

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#333]
I tried the others but the results is same.
![3](https://user-images.githubusercontent.com/45929526/62631510-10692700-b95b-11e9-890d-e4ec8e3d2c3e.png)

**Comment by 27136773** [comment]
Is it working on the website?
You probably need a subscription to read those.

**Comment by MIRVOUS** [comment]
sorry, after I checked it was a novel not a comic
