### ISSUE TITLE
[Sekaikomik] Connector not working

### ISSUE THREAD

**Issue by manhwalover** [manga-download/hakuneko#3330]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**
Chapter list is empty. Because Cloudflare not success clear captcha

**To Reproduce**
1. Name of connector: Sekaikomik 
2. Name of manga: All
3. Name of chapter: All

**Screenshots**
![image](https://user-images.githubusercontent.com/79884368/114360772-97928780-9b9f-11eb-8919-d86b34ecd17f.png)

**HakuNeko (please complete the following information):**
 - Version 6.17 stable

**Comment by 27136773** [comment]
Handled by #2933
