### ISSUE TITLE
[Site Request] Mangahua

### ISSUE THREAD

**Issue by perrinaz** [manga-download/hakuneko#3334]
**Name of the website**
MangaHua

**Website urls (examples below)**
- Site: https://mangahua.com/
- Manga List: (maybe) https://mangahua.com/genres
- Manga example: https://mangahua.com/manga/parallel-paradise-raw-22718
- Chapter online viewer example: https://mangahua.com/manga/parallel-paradise-raw/chapter-151/879473
- 
**Languages**
The site is in English

**Website relationship*
No known

**Additional details**
No known

**Comment by 27136773** [comment]
Template: MojoPortalComic ([nettruyen](http://www.nettruyen.com/))
