### ISSUE TITLE
[MangaKawaii](french) Connector not working

### ISSUE THREAD

**Issue by ShiroiOukami** [manga-download/hakuneko#3336]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector is not working, List of mangas appears but chapters doesn't appear in the list, the connector seems to be dead.
Original website : https://www.mangakawaii.com/
see more in screenshots.

**To Reproduce**
1. MangaKawaii
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
No error message.

**Screenshots**
https://zupimages.net/viewer.php?id=21/15/2m6o.jpg
https://zupimages.net/viewer.php?id=21/15/u2u0.jpg

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
 - My HakuNeko version : 2021 HakuNeko rev 6.1.7@845bf9

**Comment by dodieboy** [comment]
Believe issues is cause by cloudflare timeout
