### ISSUE TITLE
[mangapark] Connector not working

### ISSUE THREAD

**Issue by BereBereBeer** [manga-download/hakuneko#3337]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
finds the manga but the chapters aren't showing up. the chapter list stays empty only for manga from this site

**To Reproduce**
1. Name of connector - mangapark.net
2. Name of manga (if connector update is working) -any/all
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
- HakuNeko version : 2021 HakuNeko rev 6.1.7@845bf9

**Comment by 27136773** [comment]
See also #3348 for additional information
