### ISSUE TITLE
[Scan VF] Connector not working

### ISSUE THREAD

**Issue by ByZorks** [manga-download/hakuneko#3339]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The site has a new url (from https://www.scan-vf.co to https://www.scan-vf.net)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.1.7]

**Comment by deceitful33** [comment]
Duplicate : https://github.com/manga-download/hakuneko/pull/3345
