### ISSUE TITLE
[Site Request] nyanfm

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3340]
nyanfm

**Website urls (examples below)**
- Site: https://nyanfm.com/
- Manga List: https://nyanfm.com/scanlation/
- Manga example: https://nyanfm.com/mushoku-tensei-roxy-datte-honki-desu/
- Chapter online viewer example: https://nyanfm.com/mushoku-tensei-roxy-datte-honki-desu-chapter-4/

**Languages**
Indonesia

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by manh21** [comment]
dead site

**Comment by MikeZeDev** [comment]
No alternative found
