### ISSUE TITLE
[Site Request] gabutscans

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3341]
gabutscans

**Website urls (examples below)**
- Site: https://gabutscans.com/
- Manga List: https://gabutscans.com/manga/
- Manga example: https://gabutscans.com/manga/saving-80000-gold-coins-in-the-different-world-for-my-old-age/
- Chapter online viewer example: https://gabutscans.com/saving-80000-gold-coins-in-the-different-world-for-my-old-age-chapter-1-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Theme: WordPressMangastream

**Comment by XenonR** [comment]
`[an error occurred while processing this directive] `
Website dead?

**Comment by 27136773** [comment]
Website is region locked (Indonesia).
Website has CloudFlare JavaScript challenge enabled (#2933)

**Comment by l0ok-man** [comment]
Website gabutscans.com udh hilang apa gimana tuh?

**Comment by hassiramasimoto-prog** [comment]
> Website gabutscans.com udh hilang apa gimana tuh?

Ya intinya websitenya udah ditutup
