### ISSUE TITLE
[Site Request] wrt

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3342]
wrt

Website urls (examples below)

Site: https://wrt.my.id/
Manga List: https://wrt.my.id/manga/
Manga example: https://wrt.my.id/manga/alya-who-sits-next-to-me-sometimes-whispers-sweet-nothings-in-russian/
Chapter online viewer example: https://wrt.my.id/alya-who-sits-next-to-me-sometimes-whispers-sweet-nothings-in-russian-chapter-0-berwarna/

Languages
Indonesia

**Comment by FinnRG** [comment]
This site already has a connector. Please search for World Romance Translation.
