### ISSUE TITLE
[mangapark] Connector not working

### ISSUE THREAD

**Issue by mangatabar** [manga-download/hakuneko#3343]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**
the link work but the chapther wont show up

**To Reproduce**
1. mangapark 
2. https://v3.mangapark.net/comic/67194/tenshoku-no-shinden-wo-hirakimashita (if connector update is working)
3. https://v3.mangapark.net/chapter/2455548 (if manga update is working)
4. ![image](https://user-images.githubusercontent.com/46851278/114662871-9e4a0780-9d23-11eb-8972-75e0988b359b.png)
**Screenshots**
mangalist work but chapther not work 
![image](https://user-images.githubusercontent.com/46851278/114662934-bb7ed600-9d23-11eb-952e-d3755018f1cf.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3337
