### ISSUE TITLE
[Site Request] katakomik

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3344]
katakomik

Website urls (examples below)

Site: https://www.katakomik.my.id/
Manga List: https://www.katakomik.my.id/project/
Manga example: https://www.katakomik.my.id/manga/trigger/
Chapter online viewer example: https://www.katakomik.my.id/trigger-chapter-64/

Languages
Indonesia

**Comment by 27136773** [comment]
Template: WordPressMangastream

**Comment by XenonR** [comment]
Website is already supported. Closed.
