### ISSUE TITLE
[MangaPark] Connector not working (regression)

### ISSUE THREAD

**Issue by Sheepux** [manga-download/hakuneko#3348]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Reported by user on discord.
Copy/pasting is not retrieving 

Seems to be regression from #3246 as it is working with previous version.

**To Reproduce**
1. MangaparkEN
2. Copy Paste https://mangapark.net/manga/ten-no-haoh-hokuto-no-ken-raoh-gaiden
3. Chapters are empty (error after clicking the manga)

`GET https://v3.mangapark.net/manga/ten-no-haoh-hokuto-no-ken-raoh-gaiden 404`

2'. No error message (but still not working) with https://v3.mangapark.net/comic/108443/ten-no-haoh-hokuto-no-ken-raoh-gaiden

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] master

**Comment by 27136773** [comment]
Handled by: #3337
