### ISSUE TITLE
[Site Request] manhua123

### ISSUE THREAD

**Issue by dodieboy** [manga-download/hakuneko#3349]
**Name of the website**
manhua123

**Website urls (examples below)**
- Site: https://m.manhua123.net/page/new.html
- Manga List: https://m.manhua123.net/page/hot.html
- Manga example: https://m.manhua123.net/comic/10037.html
- Chapter online viewer example: https://m.manhua123.net/comic/28532/1822819.html

**Languages**
Chinese

**Comment by MikeZeDev** [comment]
Dead website, parking page. @Sheepux please :)

**Comment by Sheepux** [comment]
no alternative domain found
