### ISSUE TITLE
Tumangaonline.con Not Working

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#335]
![ad](https://user-images.githubusercontent.com/53885246/62669259-99c92b00-b954-11e9-8ac5-9fd3f027757d.jpg)

**Comment by 27136773** [comment]
Probably a new protection to prevent to many consecutive requests...
Can be reproduced by opening a [library page](https://tmofans.com/library?page=2) in the browser and refreshing it repeatedly (15~20 times) until the `429 To Many Requests` page appears.

![image](https://user-images.githubusercontent.com/27136773/62682132-afbe0680-b9bb-11e9-98bc-7c6210aaea24.png)

**Suggested programming task:**

Maybe add a new delay setting for TuMangaOnline when fetching the manga list or completely move the work to HakuNeko's CDN server and get the manga list from there.

**Comment by 27136773** [comment]
Suggested workaround until this issue is fixed:

- Do not perform an update of the manga list
- Use the [copy/paste functionality](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list) to access the chapters of a manga

**Comment by 27136773** [comment]
Works now with list from CDN

**Comment by DarkBlooDStone** [comment]
The program works but the new series added are not updated. I must use the copy and paste function to see them.

**Comment by 27136773** [comment]
List of mangas is provided by HakuNeko's CDN, which is currently updated manually and therefore the manga lists for affected websites may be outdated...

**Comment by DarkBlooDStone** [comment]
Good afternoon / nights / days, I tried to run the application using the code you put before I don't know anything about programming so I guess I do it wrong because the program doesn't work for me anymore and I have to download again. I don't know if you could pass me the updated file or tell me how it should look. Thank you.
