### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by minhngoc25a** [manga-download/hakuneko#3350]
**Name of the website**
comick

**Website urls (examples below)**
- Site: https://comick.fun
- Manga List: https://comick.fun/list (log in required)
- Manga example: https://comick.fun/comic/fumetsu-no-anata-e
- Chapter online viewer example: https://comick.fun/comic/fumetsu-no-anata-e/QnRwl-chapter-20-en

**Languages**
Various

**Additional details**
The site itself is a progressive web app and it doesn't have any advertisements.

**Comment by 27136773** [comment]
See: #3105
