### ISSUE TITLE
[Mangago] Connector not working

### ISSUE THREAD

**Issue by uuranor** [manga-download/hakuneko#3351]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The manga all load fine in the manga list, showing the new chapters but when trying to download it ends with an error. It worked fine till 5 hours ago.

**To Reproduce**
1. Name of connector mangago
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version  6.17
![Immagine](https://user-images.githubusercontent.com/57646579/115048501-ec087080-9ed9-11eb-9c82-c22fa5230290.jpg)

**Comment by 27136773** [comment]
Their [JavaScript is now encrypted](https://www.mnggo.net/mobi/js/chapter.js?891), probably need to decrypt the script before it can be evaluated

**Comment by Holydragoness** [comment]
odd question if their java script is encrypted then who has to decrypt it? And that link about the java script that you pasted where do you place it?

**Comment by 27136773** [comment]
Needs to be implemented by developer

**Comment by Sheepux** [comment]
_DevNote_ : JS obfuscation seems to be sojson v4 : functions & variable name aren't obfuscated (such poor protection)

**Comment by suikodoen13** [comment]
hi

Still unable to load the images.
![mangago](https://user-images.githubusercontent.com/60792860/115866982-0bb90f00-a46d-11eb-9423-f08d347c53c4.PNG)

**Comment by Sheepux** [comment]
Use the nightly version of hakuneko

**Comment by suikodoen13** [comment]
ok. thanks for the advice.

**Comment by alexanderoe69** [comment]
Mangago still not working for me. What do i need to to? I can't read nor download any comics

**Comment by 27136773** [comment]
Create a new ticket and describe steps to reproduce, especially manga/chapter.
Also check for CloudFlare protection #2933 ...
