### ISSUE TITLE
[Site Request] Dellitoon

### ISSUE THREAD

**Issue by zazouze** [manga-download/hakuneko#3353]
Hello, I am attaching the website logo as well as the Delitoon connector code.
It works well for me in France.
The manga list is by default on the romance genre but the copy paste of the url of manga not present in the list works.
To download the episodes, even the free ones, you have to manually log in to your username.
Cordially.
[Delitoon.zip](https://github.com/manga-download/hakuneko/files/6329422/Delitoon.zip)

**Comment by dodieboy** [comment]
Look good, I updated your code to support all genre

**Comment by zazouze** [comment]
Oh good! Thank you
