### ISSUE TITLE
[mangaworld] Connector not working

### ISSUE THREAD

**Issue by bubba11985** [manga-download/hakuneko#3355]
Did you read the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
mangaworld.cc changed to mangaworld.io

To Reproduce

    Name of connector: Manga World
    Name of manga (if connector update is working)
    Name of chapter (if manga update is working)
    Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): Failed to load resource: the server responded with a status of 404

Screenshots
If complex to describe, add screenshots to help explain your problem.

HakuNeko (please complete the following information):

    Version 6.1.7 desktop 2021

**Comment by 27136773** [comment]
See #3346
