### ISSUE TITLE
[Site Request] Toptoon Plus

### ISSUE THREAD

**Issue by howlersting** [manga-download/hakuneko#3359]
**Name of the website**
TOPTOON PLUS

**Website urls (examples below)**
- Site: https://toptoonplus.com/
- Manga List: https://toptoonplus.com/daily/?weekly=0 (not sure)
- Manga example: https://toptoonplus.com/comic/100016/
- Chapter online viewer example: https://toptoonplus.com/comic/100016/100318/

**Languages**
English

**Website relationship*
English domain of Toptoon korean

**Additional details**
NA

**Comment by MikeZeDev** [comment]
Its now global.toptoon and there is a more recent request for it
