### ISSUE TITLE
[MangaWorld] Connector not working

### ISSUE THREAD

**Issue by uuranor** [manga-download/hakuneko#3360]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The website is working but there are no manga in the archive of HakuNeko. Am I just unlucky, first mangago and now mangaworld?
![Immagine](https://user-images.githubusercontent.com/57646579/115272967-448c7780-a13f-11eb-8e76-2693cafa038d.jpg)

**To Reproduce**
1. Name of connector mangaworld
2. Name of manga (if connector update is working) Every manga
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
You need to sync the list as described in the red box

**Comment by 27136773** [comment]
References: #3346
