### ISSUE TITLE
[Japscan] Connector not working

### ISSUE THREAD

**Issue by Klibiz** [manga-download/hakuneko#3361]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hello ! First of all thank you for your work.
I wanted to read Jojo's Bizarre Adventure a while ago and downloaded volumes 64 and 65 with Japscan's connector. It worked just fine.
But now I'd like to DL the next volumes and I keep having the same issue : the process takes forever and makes my computer super slow. Whenever the DL is near completion, it suddenly says "Failed to fetch". If I try to dowload the same volume again, HakuNeko crashes.

What can I do ? I've seen several threads about Japscan but the solutions given do not work. Throttling was already set at 7500, I tried a lower and higher number but it didn't change anything. I did update the manga list just in case, but it did not solve my problem either.
(FYI I use Haku Neko v6.1.7 and I can't see the volumes' preview, it shows blank images)

**To Reproduce**
1. Name of connector -> Japscan
2. Name of manga (if connector update is working) -> Jojo's Bizarre Adventure
3. Name of chapter (if manga update is working) -> Volume 66 to 80, maybe more
4. Copy any relevant error message that appears in a popup -> It just says "Error: Failed to fetch"

**Comment by 27136773** [comment]
If this is not one of these unsupported [multi-image chapter](https://github.com/manga-download/hakuneko/issues/2378) and nothing from [1451](https://github.com/manga-download/hakuneko/issues/1451#issuecomment-619609627) helped, then there is nothing that can be done...
