### ISSUE TITLE
[MangaHost] Connector not working

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#3362]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Only works if I use the clipboard with the "this.url" (https://mangahostz.com/)
https://github.com/manga-download/hakuneko/blob/da8856ac6b76fd93ffc44762065c9c798fea9bd7/src/web/mjs/connectors/MangaHost.mjs#L52

**Screenshots**
![image](https://user-images.githubusercontent.com/46169656/115293191-65e46800-a12d-11eb-82bd-3cfe2c62527c.png)

**HakuNeko (please complete the following information):**
 - Version Nightly

**Comment by dodieboy** [comment]
Cause by outdated domain

**Comment by dodieboy** [comment]
BTW MangaHost is also affected by cloudflare too
Handled by #2933
