### ISSUE TITLE
[Japanread] Connector not working

### ISSUE THREAD

**Issue by courli79** [manga-download/hakuneko#3367]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**The download does not work.
download does not work

**To Reproduce**
1. Name of connector : Japanread
2. Name of manga (if connector update is working) : A Way To Protect You, Sweetheart
3. Name of chapter (if manga update is working) : all
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 404 ()
mjs/engine/Connector.mjs:618 Error: Failed to receive content from "https://www.japanread.cc/api/?type=chapter&id=138242" (status: 404) - 
    at mjs/engine/Connector.mjs:469
    at async JapanRead._getPages (mjs/connectors/JapanRead.mjs:70)
    at async JapanRead._getPageList (mjs/engine/Connector.mjs:615) EventTarget

**Screenshots**
![image](https://user-images.githubusercontent.com/82915245/115476152-8d2c5980-a241-11eb-82bb-29373a607596.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dodieboy** [comment]
Cause by Cloudflare block
![image](https://user-images.githubusercontent.com/9015764/116047695-f2030c00-a6a6-11eb-9d74-5cab4a82fc51.png)
May be handled by #2933
@ronny1982 can close this issue

**Comment by zazouze** [comment]
Hello, this doesn't seem to be cloudfare bug because I can access japanread right now through hakuneko's browser.
Japanread does not always have cloudfare protection active.

![image](https://user-images.githubusercontent.com/62121714/116119282-8cbb1500-a6be-11eb-9d7e-574751c50292.png)

**Comment by courli79** [comment]
Hello, this doesn't seem to be cloudfare bug because I can access japanread right now through hakuneko's browser.
Japanread does not always have cloudfare protection active.

![026](https://user-images.githubusercontent.com/82915245/116120183-9002d080-a6bf-11eb-995f-9500cf9db759.jpg)

**Comment by 27136773** [comment]
They enabled reCaptcha protection for their chapters.

I will add support for reCaptcha recognition to HakuNeko, however it will still be required to solve a Captcha (for any arbitrary chapter) with [manual website interaction](https://hakuneko.download/docs/manual-website-interaction/) before any other chapter can be downloaded with HakuNeko.

![image](https://user-images.githubusercontent.com/27136773/119234454-4d9da980-bb2e-11eb-9ff6-b98dbb8e9231.png)

**Comment by courli79** [comment]
Okay. Thank you so much.
