### ISSUE TITLE
[Kakaopage] Connector not working

### ISSUE THREAD

**Issue by courli79** [manga-download/hakuneko#3368]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Manual login of the kakaopage user account does not work.
To manually connect with hakuneko, I open the kakaopage web page on hakuneko, I click on connection (present at the top right), the kakao account web page opens, I enter my email and my password and click on log in, the window disappears, but the kakaopage home web page does not connect.
There is no error message on the console as if the hakuneko web page did not receive the connection info.
So, I can't download the chapters that require a connection.

**To Reproduce**
1. Name of connector : Kakaopage
2. Name of manga (if connector update is working) : 악녀 는 마리오네트

3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : There is no error message on the console

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3252
