### ISSUE TITLE
[Site Request] readonepiece

### ISSUE THREAD

**Issue by NicolleenHaldemann** [manga-download/hakuneko#3372]
**Name of the website**
readonepiece

**Website urls (examples below)**
- Site: https://ww8.readonepiece.com/
- Manga List: https://ww8.readonepiece.com/
- Manga example: https://ww8.readonepiece.com/manga/one-piece-digital-colored-comics/
- Chapter online viewer example: https://ww8.readonepiece.com/chapter/one-piece-digital-colored-comics-chapter-922/

**Languages**
English

**Comment by 27136773** [comment]
This website is already supported as part of `MangaCruzers`
