### ISSUE TITLE
[Question] what hakuneko stored in hakuneko\userdata\cache ?

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#3374]
is it same as browser cache? mine took almost 500mb, i assume it safe to delete it?

**Comment by Sheepux** [comment]
Everything is described here: https://hakuneko.download/docs/install/#directories

> This directory contains the pure web application and will be updated automatically whenever a new version of the web application is available on the server.

Mine is around 300M. I don't know how big it should be, Ronny will probably have more insight.

**Comment by 27136773** [comment]
The directory corresponds to the same as it is in Chrome browser.
It does not contain data that is relevant for HakuNeko.
It is safe to delete, but you may need to re-login on certain websites.
