### ISSUE TITLE
[Manga World ] Connector not working

### ISSUE THREAD

**Issue by bubba11985** [manga-download/hakuneko#3375]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I choose manga world connector but does not load mangas list. It continues to load without any list 

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] desktop Windows 32 bit portable

**Comment by dodieboy** [comment]
The connector work fine for me, how long did you wait? The mange list for this connector is big, took me 4min to load

**Comment by dodieboy** [comment]
Can you try the nightly version, i fix the manga list take forever to load a few day ago

**Comment by bubba11985** [comment]
I will try stable version and not portable

**Comment by bubba11985** [comment]
Im trying nightly version portable Windows desktop and mangaworld now works 
Thanks 
PS 
What is the difference between nightly and stable version?

**Comment by dodieboy** [comment]
I believe the different is the lib use on the client

**Comment by dodieboy** [comment]
@ronny1982 issues solved, can close this issues alr

**Comment by 27136773** [comment]
See #3346
