### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by MarcusMorter** [manga-download/hakuneko#338]
Version: 5.0.8
Type: Windows 64bit client (non-portable)

After instalation, I'm having two problems
1, not being able to sync local manga list, it just plainly does nothing and there is zero comunication going to/from the program
2, "a new version is avaialbe" dialog shows up even though I installed the latest release from github

I'd like to know I just accidentally skiped a part, or the app is in fact not working.

ad, can't close the window through normal means, have to force close it from task manager

Edit
tried to download the portable version and it is working as intended

**Comment by 27136773** [comment]
See: https://github.com/manga-download/hakuneko/issues/302#issuecomment-518323279
