### ISSUE TITLE
[ScanTrad] Connector not working

### ISSUE THREAD

**Issue by Zarh** [manga-download/hakuneko#3380]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
They updated the website. The error occurs when we load the list of chapter and list of manga.

**To Reproduce**
1. Name of connector 
          - scantrad
2. Name of manga (if connector update is working) 
          - connector update doesn't work
3. Name of chapter (if manga update is working) 
          - manga update doesn't work
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
          - "TypeError: Cannot read property 'textContent' of null  at ScanTrad.mjs:33"
          
**HakuNeko (please complete the following information):**
 - Version 6.1.7 @845bf9

**Comment by Zarh** [comment]
I tried with nighlty version master@04aa09. I can load the manga and chapter list but I can't download the chapter. It returns the error 403 when it try to download the first picture. Can you re-open it, please ? or I must open another issue ?

**Comment by Ben93160** [comment]
hello,

Thanks for issue, +1 for this connector working again :-)

Did we have to open a new issue ?

Regards

Benoit

**Comment by 27136773** [comment]
Yes open a new issue and provide sample manga/chapter that is not working
