### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by janjanly** [manga-download/hakuneko#3383]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
the site mangago and myreadingmanga works totally fine and their issue on images are solved but i still cant download my bookmarked chapters. even when i copy paste the link itself,the chapters still shows up (even the undownloaded ones),but its keeps on showing up that it couldnt download the chapter when i tried to download them.

**To Reproduce**
1. Go to 'bookmarks'
2. Click on 'preffered manga (specifically mangago and myreadingmanga as well)'
3. click on the updated chapter that can be downloaded
4. its shows the red warning sign no matter how many times i do it

**Expected behavior**
it would download the chapter as it did before

**Screenshots**

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [e.g. 6.1.7 c2021]

**Additional context**

**Comment by 27136773** [comment]
Which manga?
What is shown in the tooltip for the error icon in the job list?
What is shown in the error log (F12 => Console)?
what is shown in the network tab (F12 => Network)?

**Comment by janjanly** [comment]
On Sat, Apr 24, 2021 at 10:16 PM Ronny ***@***.***> wrote:

> Which manga?
>
actually any manga coming from Mangago and Myreadingmanga,even if theyre
from bookmarks or i copy-pasted the link itself. it loads up fine but when
i try to download them,it didnt want to.

> What is shown in the tooltip for the error icon in the job list?
>
  Error: Failed to load "
http://www.mangago.me/read-manga/19_days/bt/ibx_chapter-354/pg-1/" within
the given timeout of 60 seconds!

> What is shown in the error log (F12 => Console)?
>

Connector.mjs:618 Error: Failed to load "
http://www.mangago.me/read-manga/19_days/bt/ibx_chapter-354/pg-1/" within
the given timeout of 60 seconds! at Request.mjs:371

   1. EventTarget {manga: EventTarget, id:
   "/read-manga/19_days/bt/ibx_chapter-354/pg-1/", title: "Ch.354", file:
   {…}, language: "en", …}

what is shown in the network tab (F12 => Network)?
>
Failed to load resource: net::ERR_FILE_NOT_FOUND  i dont know if i found
the right one on network

**Comment by 27136773** [comment]
MangaGo: See #3351 => Use Nightly or wait until fix is merged into 6.1.7
MyReadingManga: See #2929/#2933

**Comment by janjanly** [comment]
Ohhh thank you so much :D
