### ISSUE TITLE
[Manga Al-arab] Connector not working

### ISSUE THREAD

**Issue by Morinkashisan** [manga-download/hakuneko#3384]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector website is wrong.
must be mangaar.com instead of mngaar.com

**To Reproduce**
1. Manga Al-arab
![Untitlemmd](https://user-images.githubusercontent.com/83146297/115977181-34243480-a565-11eb-8834-087d09a5cff0.png)

2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dodieboy** [comment]
No error, it should be mngaar.com. But the website cdn is down, so you are unable to download any image from the site
![image](https://user-images.githubusercontent.com/9015764/116045045-36d97380-a6a4-11eb-9df9-f04b8b44dfa4.png)

@ronny1982 can close this issue

**Comment by Morinkashisan** [comment]
It turns out there's two domains mngaar.com and manga.ae.
Now the website is working.
Thank you.

**Comment by a7mad74** [comment]
How did you fix it

**Comment by Morinkashisan** [comment]
I didn't fix it 
The website cdn was down. 
But everything is working now
