### ISSUE TITLE
Selecting chapter range

### ISSUE THREAD

**Issue by Simon677-lab** [manga-download/hakuneko#3387]
**Is your feature request related to a problem? Please describe.**
[ Its irritating having to manually select manga chapters to download. ]

**Describe the solution you'd like**
[ Add chapter range selecting, It would be very helpful being able to select any number of chapters then hitting download. ]

**Describe alternatives you've considered**
[ None so far ]

**Context (please complete the following information):**
 [ Hakuneko v6.1.7 ]

**Additional context**
[ None ]

**Comment by Sheepux** [comment]
Currently, this feature is covered by the filter with regexp (hover your mouse over the button).
A generic feature cannot be adressed as all connector don't follow the same pattern for chapter names

**Comment by Simon677-lab** [comment]
Hadn't realized that. Its ok, using regular expressions works well. tnx👍
