### ISSUE TITLE
[Site Request] Catmanga

### ISSUE THREAD

**Issue by heydoyouknowme0** [manga-download/hakuneko#3389]
**Name of the website**
Catmanga

**Website urls (examples below)**
- Site: https://catmanga.org/
- Manga List: https://catmanga.org/
- Manga example: https://catmanga.org/series/kanokari
- Chapter online viewer example: https://catmanga.org/series/kanokari/185

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #3308
