### ISSUE TITLE
[Site Request] Happy Manhua

### ISSUE THREAD

**Issue by westward-MARTIAN** [manga-download/hakuneko#3390]
**Name of the website**
嗨皮漫画 (happy manhua)

**Website urls (examples below)**
- Site: https://m.happymh.com/
- Manga List: https://m.happymh.com/cate (https://m.happymh.com/apis/c/index?pn=1&)
- Manga example: https://m.happymh.com/manga/jizhufudao
- Chapter online viewer example: https://m.happymh.com/manga/read/jizhufudao/1405216?__cf_chl_jschl_tk__=63ded4023fb1176f63b506865d49b5da49789512-1619494118-0-AXJMQhNXgbe-kUz-yb5Qyko89MX2S1s0mlDLJCmpQ4lz3dLlZ9rbQyAtEIew6h918SlJD_X6fiGOsxIeR2ZEhqGJ0_kRobqPa_IzyrKcFDCyG6XEP-AKOOI2irAQ0_owsBAY95cPT9TQ2BRlO1uOCsivxW5TrdOzudfCTQYEUDCJcOd1VlAFr6XKxmfPCEw6AkNt62ll5Tm_Vznz8dKzRysXYjipkmHN92pWT9qGqbTRvVEFcb5OPzOHoSgNrAgqXwrX23iTTHAOieVdXqHiC_Jes7KIwIPV9ah-bFBz1nm0ioVMgf9decnVBlUZWmeSx6vRrSEyzPSCuMaqwCchkXOsTPkKuV_FzVFFV8TVi4xMVflAl_Nf1vYdOy-e0xnxW0WgMuNgOUgrTMk6UmszIuNvCwJozgO2-u3volcUE3UTj6tIjdTSB4D4uZCh5_RAgA

**Languages**
Chinese

**Website relationship*
N/A
**Additional details**
It works like an app and the html starts with "<html mip>"

**Comment by MikeZeDev** [comment]
Cant pass cloudflare checking on real browser.

**Comment by MikeZeDev** [comment]
Geoblocked

**Comment by MikeZeDev** [comment]
redirect to qq
