### ISSUE TITLE
[MangaFast & ManhuasWorld] Connector not working

### ISSUE THREAD

**Issue by MAmrollahi** [manga-download/hakuneko#3395]
Did you read the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
https://user-images.githubusercontent.com/80641031/116259962-85157200-a78b-11eb-8c49-21a513b9b8f7.png
https://user-images.githubusercontent.com/80641031/116260694-27cdf080-a78c-11eb-8a8f-26ac79ad0c2b.png

Screenshots
https://user-images.githubusercontent.com/80641031/116261103-927f2c00-a78c-11eb-95c8-0c00dbd11958.png
https://user-images.githubusercontent.com/80641031/116262364-b7c06a00-a78d-11eb-9635-747370c7b31b.png

 - Version  6.17  desktop Windows 64-bit setup

**Comment by dodieboy** [comment]
Look like ManhuasWorld close down alr

**Comment by MAmrollahi** [comment]
what about manga fast? 
is it because they update the site?

**Comment by 27136773** [comment]
Please describe the problem, the screenshots only imply that you need to synchronize the manga lists, otherwise they will be empty

**Comment by Amir-m-a** [comment]
same here with mangafast. website and network is fine yet list doesn't get synchronized.
![image](https://user-images.githubusercontent.com/33460495/116818113-e7e97d80-ab7e-11eb-82a5-0922b10b70a7.png)
