### ISSUE TITLE
[NameOfConnector] Copy Paste Not Working

### ISSUE THREAD

**Issue by jc1917** [manga-download/hakuneko#3396]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I tried following the instructions to copy the link and press the paste button at the top of the menu but it wasn't doing anything. 
I'm completely new to both the HakuNeko server and have no experience with coding... I had used the mangahere and mangafox connectors just fine. Just can't use the copy paste link. 

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Please provide explicit manga links which you are trying to paste

**Comment by jc1917** [comment]
I was trying to use it for kissmanga 
http://kissmanga.pw/manga/goong 
but I realized that the site is changed from before (?)

**Comment by 27136773** [comment]
`kissmanga.pw` is not supported.
Create a new website request ticket or use any other affiliate website.
manganelo, mangakakalot, mangabat, ...

**Comment by jc1917** [comment]
when I try the manganelo/mangakakalot sites it shows up as "Manga #53A" in the chapter list and doesn't show any chapters
