### ISSUE TITLE
[Kanjiku.net] Connector not working

### ISSUE THREAD

**Issue by tobiasfrck** [manga-download/hakuneko#3397]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Manga List does not show any of the mangas that are listed on the website.
The network tab in the inspector says that it tried loading `https://kanjiku.net/wp-admin/admin-ajax.php` and the page itself says:

> The page you were looking for doesn't exist.

and the console gives a 404 response.

**To Reproduce**
1. Loading manga from https://kanjiku.net/

**HakuNeko (please complete the following information):**
 - Version 6.1.7@845bf9

**Comment by 27136773** [comment]
Website has changed template, seems now custom instead of WordPressMadara

**Comment by Shirobaka** [comment]
I created a pull request with a fix for that.
