### ISSUE TITLE
[mangago] Connector not working

### ISSUE THREAD

**Issue by BereBereBeer** [manga-download/hakuneko#3398]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
preview of chapter's pages don't show up, can't download chapters, both give the error message 'failed to load within the given timeout of 60 seconds'

**To Reproduce**
1. Name of connector - mangago.me
2. Name of manga (if connector update is working) - any/all. example http://www.mangago.me/read-manga/jujutsu_kaisen/
3. Name of chapter (if manga update is working) 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by BereBereBeer** [comment]
it works fine with the nightly version

**Comment by 27136773** [comment]
Already resolved by #3386
Use nightly or wait for fix to be merged into 6.1.7
