### ISSUE TITLE
MangaKatana Links

### ISSUE THREAD

**Issue by LunerRaies** [manga-download/hakuneko#3399]
https://mangakatana.com/manga/theres-no-way-a-side-character-like-me-could-be-popular-right.25811
https://mangakatana.com/manga/amagami-san-chi-no-enmusubi.25810
https://mangakatana.com/manga/i-was-summoned-by-the-demon-lord-but-i-cant-understand-her-language.25809
https://mangakatana.com/manga/im-the-stepmother-but-my-daughter-is-too-cute.25808
https://mangakatana.com/manga/blue-box.25807
https://mangakatana.com/manga/updater.25806
https://mangakatana.com/manga/mookhyang-the-origin.25805
https://mangakatana.com/manga/you-at-first-sight.25804
https://mangakatana.com/manga/the-constellation-that-returned-from-hell.25803
https://mangakatana.com/manga/jujutsu-kaisen-0.25802
https://mangakatana.com/manga/getsuyoubi-no-tawawa-serialization.25801
https://mangakatana.com/manga/isekai-saikyou-no-daimaou-tensei-shi-boukensha-ni-naru.25800
https://mangakatana.com/manga/dungeons-artifacts.25799
https://mangakatana.com/manga/life-completely-ruined.25798
https://mangakatana.com/manga/incompetent-villain.25797
https://mangakatana.com/manga/whats-wrong-with-secretary-kim.25796
https://mangakatana.com/manga/the-elusive-samurai.25795
https://mangakatana.com/manga/seven-day-alternating-personality-syndrome.25794
https://mangakatana.com/manga/the-wanderer.25793
https://mangakatana.com/manga/return-of-the-female-knight.25792
https://mangakatana.com/manga/shotgun-boy.25791
https://mangakatana.com/manga/an-hour-of-romance.25790
https://mangakatana.com/manga/sentimental-kiss.25789
https://mangakatana.com/manga/herscherik-the-epic-of-the-reincarnated-prince.25788
https://mangakatana.com/manga/build-king.25787

**Comment by 27136773** [comment]
Missing context
