### ISSUE TITLE
1 speciffic manga not loding list?

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#340]
> **From:** Patchi

A speciffic manga is showing on left list of all of them but when I click on it to load chapters it just shows 0/0, it's weird, honesly I have no idea why is that.

29-sai Dokushin wa Isekai de Jiyuu ni Ikita……katta.
https://kissmanga.com/Manga/29-sai-Dokushin-wa-Isekai-de-Jiyuu-ni-Ikita……katta

**Comment by 27136773** [comment]
Some mangas from KissManga have broken links in their list.
This is a problem with the website and cannot be fixed in HakuNeko.

Workaround:
Use copy and paste the manga URL directly in HakuNeko to get the chapter list.
