### ISSUE TITLE
[Line Webtoon (English)] Connector not working

### ISSUE THREAD

**Issue by MAmrollahi** [manga-download/hakuneko#3400]
Did you read [the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
when you go to webtoon site, the site ask your age but the app can't fill it so it couldn't access the manga 
and i didn't find the place to paste the URL containing the chapters from my browser

Screenshots:
https://user-images.githubusercontent.com/80641031/116417333-66c57a00-a850-11eb-8a50-c6c5a8a0b352.png

 - Version :
nightly(master) • 2020-07-05T00:14:37UTC :
hakuneko-desktop_8.3.4_windows-setup_amd64.exe

**Comment by 27136773** [comment]
Read the error, the website is limited to copy & paste manga links only, there is no list.
