### ISSUE TITLE
[Site Request] bilibilicomics

### ISSUE THREAD

**Issue by inboot** [manga-download/hakuneko#3402]
**Name of the website**
bilibilicomics

**Website urls (examples below)**
- Site: https://www.bilibilicomics.com/
- Manga List: https://www.bilibilicomics.com/?from=manga_detail
- Manga example: https://www.bilibilicomics.com/detail/mc55?from=manga_index 
- Chapter online viewer example: https://www.bilibilicomics.com/mc55/321?from=manga_detail

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Affiliate: https://manga.bilibili.com (probably same layout)

**Comment by dodieboy** [comment]
yup, same layout. but need to change the connector abit, the getpage code giving error 403
