### ISSUE TITLE
[Mangago] Connector not working

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#3403]
Unable to load screen/images again. I am using the nightly version of hakuneko. 

![Capture](https://user-images.githubusercontent.com/60792860/116496659-26a9da00-a8d8-11eb-883f-f92497e255bd.PNG)

**Comment by 27136773** [comment]
It seems some chapters are still using the old [chapter.js?891](https://www.mnggo.net/mobi/js/chapter.js?891) script, the latest HakuNeko build was adapted to support [chapter.js?895](https://www.mnggo.net/mobi/js/chapter.js?895).

Not sure if this is intentional by MangaGo to prevent downloaders by using different versions, or if these chapters will be migrated to the newer version soon...

**Comment by tori131** [comment]
> It seems some chapters are still using the old [chapter.js?891](https://www.mnggo.net/mobi/js/chapter.js?891) script, the latest HakuNeko build was adapted to support [chapter.js?895](https://www.mnggo.net/mobi/js/chapter.js?895).
> 
> Not sure if this is intentional by MangaGo to prevent downloaders by using different versions, or if these chapters will be migrated to the newer version soon...

but the newest chapters (that they are uploading these days) aren't working too

**Comment by 27136773** [comment]
> > It seems some chapters are still using the old [chapter.js?891](https://www.mnggo.net/mobi/js/chapter.js?891) script, the latest HakuNeko build was adapted to support [chapter.js?895](https://www.mnggo.net/mobi/js/chapter.js?895).
> > Not sure if this is intentional by MangaGo to prevent downloaders by using different versions, or if these chapters will be migrated to the newer version soon...
> 
> but the newest chapters (that they are uploading these days) aren't working too

In that case, they are probably doing it by intention to make it harder for HakuNeko grabbing the images.
However a PR with support for backward compatibility is ready for review...

**Comment by tori131** [comment]
> > > It seems some chapters are still using the old [chapter.js?891](https://www.mnggo.net/mobi/js/chapter.js?891) script, the latest HakuNeko build was adapted to support [chapter.js?895](https://www.mnggo.net/mobi/js/chapter.js?895).
> > > Not sure if this is intentional by MangaGo to prevent downloaders by using different versions, or if these chapters will be migrated to the newer version soon...
> > 
> > 
> > but the newest chapters (that they are uploading these days) aren't working too
> 
> In that case, they are probably doing it by intention to make it harder for HakuNeko grabbing the images.
> However a PR with support for backward compatibility is ready for review...

I'm so noob on this... in that case what should I do? wait for another update in nightly version? use the nightly that I have now in a few days? use the not-nightly one? Sorry for bothering you

**Comment by 27136773** [comment]
Use nightly or wait for fix being merged into 6.1.7
