### ISSUE TITLE
[AsuraScans and Toonily.com] Connector not working

### ISSUE THREAD

**Issue by Mammad211** [manga-download/hakuneko#3405]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
it wont download Manga List For This Sites
it's Protected by cloudflare i tried to use this guide but it show an Empty Page after cloudflare Page
https://hakuneko.download/docs/manual-website-interaction/#cloudflare-bypass
**To Reproduce**
1. https://www.asurascans.com and https://toonily.com

**Screenshots**
![ScreenShot_20210429124742](https://user-images.githubusercontent.com/49652717/116522033-f0755600-a8e9-11eb-90ab-2869a47d1cec.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #2933
