### ISSUE TITLE
[Site Request] 極速漫畫

### ISSUE THREAD

**Issue by ardithho** [manga-download/hakuneko#3410]
**Name of the website**
極速漫畫

**Website urls (examples below)**
-Site: http://www.js518.net/
-Manga List: http://www.js518.net/all/
-Manga example: http://www.js518.net/zhentanmanhua/6577/
-Chapter online viewer example: http://www.js518.net/zhentanmanhua/6577/175557.html

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by dodieboy** [comment]
Duplicate of #162
