### ISSUE TITLE
[ManhuaScan] Connector not working

### ISSUE THREAD

**Issue by alexanderoe69** [manga-download/hakuneko#3412]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Furthermore there is not even a single clue about the problem in this ticket => closed

----
![image](https://user-images.githubusercontent.com/27136773/116864994-1449dc00-ac09-11eb-8c52-b3e613295360.png)
