### ISSUE TITLE
[Lezhin] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#3413]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Fail to connect.

**To Reproduce**
1. Lezhin

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
The domain update may solve the issue.
If still facing problems, try manual website interaction for Lezhin by opening and read a chapter with HakuNeko's internal browser.

**Comment by jstefansson6** [comment]
That did the trick. Thanks
