### ISSUE TITLE
[Site Request] litenovel

### ISSUE THREAD

**Issue by LunerRaies** [manga-download/hakuneko#3414]
**Name of the website**
litenovel

**Website urls (examples below)**
- https://www.litenovel.com/
- Manga List: https://www.litenovel.com/home/novel-list
- Manga example: https://www.litenovel.com/infinite-dendrogram
- Chapter online viewer example: https://www.litenovel.com/infinite-dendrogram/v0c0

**Languages**
english

**Website relationship*
n/a

**Additional details**
the meaning of “In�nite Tree Diagram” by its producers, was a Full Dive
looks likes is when downloaded

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by MikeZeDev** [comment]
Yes, parking page
