### ISSUE TITLE
[Asura Scans] Connector not working

### ISSUE THREAD

**Issue by OCKEYaNTO** [manga-download/hakuneko#3415]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Manga list not loading for Asura Scans. They had changed to the new enhanced cloud flare protection similar to Reaper Scans, maybe connector is not taking that into account?

**To Reproduce**
1. Name of connector **Asura Scans**
2. Name of manga (if connector update is working) **NA**
3. Name of chapter (if manga update is working) **NA**
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
60s timeout, screenshot attached

**Screenshots**
![image](https://user-images.githubusercontent.com/75157616/116798425-4cdc9f00-aabd-11eb-9e7e-cb73ca42ab46.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7 @845bf9539c088350011387a4d0102144a9d3e895

**Comment by dodieboy** [comment]
Handled by #2933
