### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#342]
> **From:** HakuNeko User

i can't download or read from (gmanga.com) ..why?

**Comment by ronny1982** [comment]
Which manga chapter?
Have you tried [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?
Have you performed [Manual Website Interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction)?

**Comment by 27136773** [comment]
Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by 27136773** [comment]
No further response => closed
