### ISSUE TITLE
[ReadMangaToday] Connector not working

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#3420]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The website is down.

**To Reproduce**
1. ReadMangaToday

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![ReadMangaToday](https://user-images.githubusercontent.com/71948230/116888357-a8c53600-ac2b-11eb-9a2c-d15ab725e100.jpg)

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by 27136773** [comment]
When the website is down, HakuNeko can nothing do about
