### ISSUE TITLE
[Site Request] HolyManga

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#3421]
**Name of the website**
HolyManga

**Website urls (examples below)**
- Site: https://w26.holymanga.net/
- Manga List: https://w26.holymanga.net/manga-list/
- Manga example: https://w26.holymanga.net/jujutsu-kaisen/
- Chapter online viewer example: https://w26.holymanga.net/jujutsu-kaisen-chap-1/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Already supported, please check before creating tickets
