### ISSUE TITLE
[MangaDoom] Connector not working

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#3422]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**

**To Reproduce**
1. MangaDoom

**Screenshots**
![Mangadoom](https://user-images.githubusercontent.com/71948230/116895890-ee85fc80-ac33-11eb-92b0-495adedd1ce7.jpg)

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by 27136773** [comment]
If the website is not working, then there is nothing that can be done in HakuNeko
