### ISSUE TITLE
[HolyManga] Connector not working

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#3423]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
There is no manga appearing in Hakuneko.
New url for website : https://w26.holymanga.net/

**To Reproduce**
1. Holy Manga

**Screenshots**
![HolyManga](https://user-images.githubusercontent.com/71948230/116902063-fe550f00-ac3a-11eb-9ca1-52f0551a99c7.jpg)
![HolyManga Website](https://user-images.githubusercontent.com/71948230/116902281-3c523300-ac3b-11eb-902d-0e209bbbd574.jpg)

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
HakuNeko uses https://holymanga.net (because domain changes frequently) and this is correctly forwarded to https://w26.holymanga.net

Could be a regional lock on holymanga's end ...

**Comment by dodieboy** [comment]
Cannot be reproduced on my end too

**Comment by moostalo** [comment]
![Defaul holy manga](https://user-images.githubusercontent.com/71948230/116973557-06559300-acbd-11eb-9bd3-d98532d6e4ef.jpg)
Apparently it is fixed now.
