### ISSUE TITLE
[GManga] Connector not working

### ISSUE THREAD

**Issue by mjeed02** [manga-download/hakuneko#3426]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
today i was going to download (Sweet Home)
from (GManga) but i can't open or download it and it is saying (cannot read property 'textContent' of undefined)

**To Reproduce**
1. GManga
2. Sweet Home
3. Sweet Home all chapters
4. cannot read property 'textContent' of undefined

**HakuNeko (please complete the following information):**
 - Version 6.1.7@845bf9

**Comment by dodieboy** [comment]
It look like that the chapter list api change, causing it to give the wrong page url

**Comment by mjeed02** [comment]
so will you fix it

**Comment by dodieboy** [comment]
Im not good with api, need wait for ronny or sheepux to fix

**Comment by mjeed02** [comment]
oh ok

**Comment by mohamed12101** [comment]
please fix the issues related to gmanga

**Comment by 4gattsu** [comment]
Facing the same problem here. Would appreciate fixing it.

**Comment by Bmswad1** [comment]
Don't spam and wait
Eventually someone interested will pick it
And use another source if it's that urgent

**Comment by mohamed12101** [comment]
not working yet

**Comment by 27136773** [comment]
Use nightly or wait for fix being merged into 6.1.7

**Comment by mohamed12101** [comment]
one small problem just tested with nightly
chapters is not arranged in alphabetical order as before 
fix please 
thanks
