### ISSUE TITLE
KissComic Connector not working

### ISSUE THREAD

**Issue by compulshun** [manga-download/hakuneko#3428]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Unable to download any issues from KissComic. Every attempt gives the error "ReferenceError: 1stImages not defined". It gives the same error when clicking the "Show preview of chapter's pages" button.

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

From the console:
Connector.mjs:618 ReferenceError: lstImages is not defined
    at <anonymous>:2:44
    at new Promise (<anonymous>)
    at <anonymous>:2:13
    at WebFrame.<computed> (C:\Program Files\Hak…api\web-frame.js:64)
    at WebFrame.executeJavaScript (C:\Program Files\Hak…pi\deprecate.js:114)
    at C:\Program Files\Hak…eb-frame-init.js:11
    at C:\Program Files\Hak…internal-utils.js:7
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (C:\Program Files\Hak…internal-utils.js:7)
    at EventEmitter.emit (events.js:200) 
EventTarget {manga: EventTarget, id: "/Comic/Fantastic-Four-1961/Issue-76?id=27172", title: "Issue #76", file: {…}, language: "en", …}

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
6.17

**Comment by 27136773** [comment]
See #3235
Use nightly or wait for fix being merged to 6.1.7

**Comment by DorkN313** [comment]
the bug is most definitely not fixed as of yet. I'm using the latest nightly build that I have just downloaded and the problem is still there
