### ISSUE TITLE
[MangaPark] Connector not working

### ISSUE THREAD

**Issue by maisonmains** [manga-download/hakuneko#3433]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Upon selecting the MangaPark site from the list of connectors, I then attempt to refresh the manga list and recieve this error message whether I serach for a manga or not.  
When I try to copy the website address link directly from my browser, there is no manga presented when the refresh button is pressed. 
It seems the website may have received an update and is in a beta state.

**To Reproduce**
1. MangaPark
2. Any manga will suffice
3. Any chapter will suffice
4. Error Messsage: [ Failed to update manga list for MangaPark
 Failed to receive content from "https://v3.MangaPark.net/ajax.reader.home.release" (status: 405) -

 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3337
Use nightly or wait for fix being merged to 6.1.7
