### ISSUE TITLE
[Site Request] MangaMelon

### ISSUE THREAD

**Issue by maisonmains** [manga-download/hakuneko#3434]
**Name of the website**
MangaMelon

**Website urls (examples below)**
- Site: https://mangamelon.com
- Manga List: https://mangamelon.com/list?order=date
- Manga example: https://mangamelon.com/manga/dandadan
- Chapter online viewer example: https://mangamelon.com/chapter/dandadan/chapter-1

**Languages**
English

**Website relationship*
None

**Additional details**
None

**Comment by XenonR** [comment]
Site looks broken, is it it already dead?

**Comment by maisonmains** [comment]
Your right, im not sure what exactly is wrong here. Its not essential to add this one though, since most of the manga here seems to be available elsewhere. Thanks for confirming that.
