### ISSUE TITLE
[Feature] Ability to set custom Font and Font size

### ISSUE THREAD

**Issue by hex007** [manga-download/hakuneko#3435]
**Is your feature request related to a problem? Please describe.**
Font is too small to read on Linux desktop with Text Magnification Accessibility enabled

**Describe the solution you'd like**
An option to set custom Font and Font Size for better readability

**Describe alternatives you've considered**
Use a magnifying lens, not that practical when the monitor is far away.

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7

**Additional context**
N/A

**Comment by 27136773** [comment]
The user interface will be revised in the HaruNeko prototype.
Efforts for UI updates are no put into 6.1.7 and Nightly version of HakuNeko.

Workaround:
- Open Developer Tools with F12
- Switch to `Console` tab
- Inject the following JavaScript commands to increase font size for manga and chapter list (125%)
```javascript
document.querySelector('hakuneko-app').shadowRoot.querySelector('hakuneko-mangas').shadowRoot.querySelector('ul.list').style.fontSize = '1.25em';
document.querySelector('hakuneko-app').shadowRoot.querySelector('hakuneko-chapters').shadowRoot.querySelector('ul.list').style.fontSize = '1.25em';
```
