### ISSUE TITLE
[Feature] Add more hosts to the blacklist (from Japscan)

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/hakuneko#3436]
Just tried Japscan on nightly because someone was saying it doesnt work. 

Its working but i got fucking spammed by ESET antiviruses alerts (165 !) .

I filtered all the addresses, here they are.

https://graveuniversalapologies.com
https://hunchmotherhooddefine.com
https://immunepine.com
https://jigsawthirsty.com
https://mineralscreamrobes.com
https://pianistrefutationgoose.com
https://prowlenthusiasticcongest.com
https://radarconsultation.com
https://sharpconnatechamber.com
https://sweaterwarmly.com
https://utmostsecond.com

Would you consider adding them to HN blacklist? Thanks a lot :)

**Comment by 27136773** [comment]
They can be added, but would have no effect for JapScan, because due to technical reasons the blacklist is disabled when using JapScan.
