### ISSUE TITLE
[Site Request] http://www.mangasusu.co.in/

### ISSUE THREAD

**Issue by Monolity** [manga-download/hakuneko#3438]
**Name of the website**
http://www.mangasusu.co.in/

**Website urls (examples below)**
- Site: http://www.mangasusu.co.in/
- Manga List: https://mangasusu.co.in/az-list/
- Manga example: https://mangasusu.co.in/komik/boarding-diary/
- Chapter online viewer example: https://mangasusu.co.in/boarding-diary-chapter-38/

**Languages**
Indonesian

**Website relationship*
before it: mangasusu reborn

**Additional details**

**Comment by 27136773** [comment]
Website is already supported, please check before creating a website request.
