### ISSUE TITLE
[Site Request] Animes Vision

### ISSUE THREAD

**Issue by Giovani-SantAna-Pedroso** [manga-download/hakuneko#3439]
**Name of the website**
Animes Vision

**Website urls (examples below)**
- Site: https://animesvision.biz/
- Manga List: https://animesvision.biz/pesquisa?genero=sci-fi
- Manga example: https://animesvision.biz/animes/ijiranaide-nagatoro-san
- Chapter online viewer example: https://animesvision.biz/animes/ijiranaide-nagatoro-san/episodio-05/legendado

**Languages**
Portuguese

**Comment by XenonR** [comment]
Cloudflare Error 1020 - Possibly geoblocked

**Comment by MikeZeDev** [comment]
dead
