### ISSUE TITLE
[Bug] HakuNeko doesn't launch on Chrome OS when using the Linux environment

### ISSUE THREAD

**Issue by AbhiMayadam** [manga-download/hakuneko#3440]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
Yes
**Describe the bug**
I am trying to run HakuNeko on Chrome OS using the Linux functionality of Chrome OS. It will install, but refuse to launch. It will show up in the task bar with a little loading circle on it.
**To Reproduce**
1. Install the amd64 HakuNeko.deb file
2. Restart Chrome OS
3. Run sudo apt-get upgrade
4. Click on HakuNeko
5. Watch the thing load forever.

**Expected behavior**
I expected the software to launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/39038515/117556750-304ee280-b03a-11eb-8178-917a002db407.png)
It just does this forever
**Context (please complete the following information):**
 - OS: Neverware CloudReady v89.3.3 Beta
 - HakuNeko Version 6.1.7 amd64 deb package

**Additional context**

**Comment by 27136773** [comment]
Chrome OS is not supported by HakuNeko, there is no compatible package for Chrome OS.

**Comment by AbhiMayadam** [comment]
It actually works on Chrome OS if you use the Debian VM built into it. It was missing a dependency for some reason.  Sent from Mail for Windows 10 From: RonnySent: Saturday, May 8, 2021 9:33 PMTo: manga-download/hakunekoCc: AbhiMayadam; AuthorSubject: Re: [manga-download/hakuneko] [Bug] HakuNeko doesn't launch on Chrome OS when using the Linux environment (#3440) Closed #3440.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
