### ISSUE TITLE
[animepahe] Connector not working

### ISSUE THREAD

**Issue by voidwalkerKek** [manga-download/hakuneko#3441]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
failed to update manga list for animepahe.

**To Reproduce**
1. animepahe
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
If the website isn't working in your browser then the website is probably geolocked.
Working fine here (France)

**Comment by 27136773** [comment]
Also check your `Animepahe` settings and make sure resolution and throttling is appropriate to prevent downloads from failing

**Comment by voidwalkerKek** [comment]
> Also check your `Animepahe` settings and make sure resolution and throttling is appropriate to prevent downloads from failing

ok lemme see

**Comment by voidwalkerKek** [comment]
> Also check your `Animepahe` settings and make sure resolution and throttling is appropriate to prevent downloads from failing

![Capture](https://user-images.githubusercontent.com/70213122/119950227-47894c00-bfb8-11eb-8a33-3742b532f379.PNG)

**Comment by 27136773** [comment]
I only made an additional comment, please check Sheep's comment first:
If you cannot even use animepahe in your browser (you said it did not working in your browser right?), then it cannot be used with HakuNeko.

----

![image](https://user-images.githubusercontent.com/27136773/120011635-d14c1000-bfde-11eb-88d2-8ddb0a72e4e1.png)
