### ISSUE TITLE
[Lezhin] Connector not working, website url changed

### ISSUE THREAD

**Issue by dmr111** [manga-download/hakuneko#3442]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I was able to download webtoons from www.lezhin.com that were offered for free about a month ago, but after the url change to www.lezhinus.com, I get two errors from hakuneko. The first error is 404, which I guess is because "www.lezhin.com" no longer exists.

**To Reproduce**
1. Name of connector: www.lezhin.com in connector list, the actual website changed to www.lezhinus.com recently.
2. Name of manga (if connector update is working) 
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://user-images.githubusercontent.com/57851738/117750423-fec04d80-b1d8-11eb-97e5-8cd2c6d565d0.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@845bf9

**Comment by dodieboy** [comment]
Change have been make on #3419
