### ISSUE TITLE
[Ichirin No Hana Yuri] Connector not working

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#3443]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The requests works, hakuneko receive the responses but I can't download, view or load the list of mangas on UI
- (Only clipboard show me the manga name in the manga list)

**Screenshots**
![R3zLHsZsfb](https://user-images.githubusercontent.com/46169656/117758136-cd0aaf00-b1f7-11eb-9124-04aeae608c79.gif)

**HakuNeko (please complete the following information):**
 - Version Nightly

**Comment by 27136773** [comment]
The website is protected by CloudFlare for me, so from my point of view it is #2933
