### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by rRoler** [manga-download/hakuneko#3444]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
While the frontend on [mangadex.org](https://mangadex.org) is not up yet, the backend and v5 API on [api.mangadex.org](https://api.mangadex.org) is up.

**Describe the bug**
If you are using the old Mangadex API, you can now upgrade to the new one [api.mangadex.org/docs.html](https://api.mangadex.org/docs.html).

**To Reproduce**
1. Select the Mangadex connector
2. Search for any manga

**Screenshots**
![Screenshot 2021-05-11 115428](https://user-images.githubusercontent.com/60528736/117800704-b3975080-b253-11eb-89ee-ea13a151af70.png)

**HakuNeko (please complete the following information):**
 - Version [v6.1.7 and Nightly]

**Comment by 27136773** [comment]
API is not stable yet, waiting for FrontEnd to be released before adapting the new API in HakuNeko
