### ISSUE TITLE
[manhwatop] Connector not working

### ISSUE THREAD

**Issue by mangatabar** [manga-download/hakuneko#3445]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Ye

**Describe the bug**
when i try to donwload/load new chapter not all image is loaded instead got broken image tried to open via website but there is no problem, also try to redownload previous chapter but got same problem

**To Reproduce**
1. just download from manhwatop.com any title u will get the error

**Expected behavior**
"A clear and concise description of what you expected to happen."?
i can't explain this but hope there is option to manually reload the image

**Screenshots**
![image](https://user-images.githubusercontent.com/46851278/117812337-e1988700-b28b-11eb-91e9-0427bd19733a.png)

**Context (please complete the following information):**
 - OS:  Windows10]
 - HakuNeko Version [ 6.17]

**Additional context**

**Comment by Sheepux** [comment]
Do not use the BUG issue template, this is a connector related issue.

Make sure to provide a manga & chapter name as i didn't get any issue. Connector is working fine here.
