### ISSUE TITLE
[manhuascan.com] Connector not working

### ISSUE THREAD

**Issue by itiswhatitseems** [manga-download/hakuneko#3446]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
when i try to download anything from the website it comes up as a red error in a triangle. i've tried a couple different sources, same thing happens

**To Reproduce**
1. Name of connector manhuascan.com
2. Name of manga (if connector update is working) nothing is worknig
3. Name of chapter (if manga update is working) nothing
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dodieboy** [comment]
![image](https://user-images.githubusercontent.com/9015764/118429778-06b24d00-b705-11eb-9aaa-5891feadf733.png)
