### ISSUE TITLE
[mangago.me] Connector not working

### ISSUE THREAD

**Issue by itiswhatitseems** [manga-download/hakuneko#3447]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
A clear and concise description of what the bug is. when trying to download from mangago it just spins and then comes up with a red triangle saying the chapters cannot be downloaded

**To Reproduce**
1. Name of connector mangago.me
2. Name of manga (if connector update is working) nothing
3. Name of chapter (if manga update is working) none of them
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
devNote: refer to #3403

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random manga/chapters.
Please provide sample manga and chapter.
Make sure you are testing with the nightly build as mentioned by Sheepux to ensure it was tested with the latest MangaGo updates.

**Comment by 27136773** [comment]
Furthermore, one of their fake reader domains (`www.fashionlib.net`) is currently not working (even on their website itself it does not work).
In this case just try re-downloading until the chapter is downloaded from one of their other fake domains...

**Comment by 27136773** [comment]
No further response with requested sample manga/chapter => closed
