### ISSUE TITLE
[[Site Request]] buzztoon97

### ISSUE THREAD

**Issue by itiswhatitseems** [manga-download/hakuneko#3448]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site:  https://buzztoon97.com
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://buzztoon97.com/bbs/board.php?bo_table=webtoon&wr_id=203387
- Chapter online viewer example: https://buzztoon97.com/bbs/board.php?bo_table=webtoon&wr_id=203387

**Languages**
List of languages supported by the website
korean

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ..."). n/a

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by dodieboy** [comment]
Site url change to: https://buzztoon98.com/

**Comment by MikeZeDev** [comment]
New url is dead too . @Sheepux pls :)

**Comment by Sheepux** [comment]
website with dynamic domain, unable to find the source to find the "current" one.
reopen if you know it
