### ISSUE TITLE
[MangaHost] Outdated domain

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#3449]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
```diff
- mangahosted.com
+ mangahostz.com
```

**HakuNeko (please complete the following information):**
 - Version Nightly

**Comment by Sheepux** [comment]
Changed domain, but still behind cloudflare, meaning it won't work. Will close in favor of #2933
