### ISSUE TITLE
[Bug] Png images downloaded as jpg

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [manga-download/hakuneko#3450]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
[Yes]/No

**Describe the bug**
Sometimes, png images are downloaded with the jpg extension despite maintaining the png internal format. This means that I cannot open them with some software unless I painstakingly changing the extensions one by one.

**To Reproduce**
The issue seems to be on the site's end, since it seems that browsers don't check the file extension, so the images are mislabeled in the servers.

**Expected behavior**
I would like for Hakuneko to check the file headers before saving the files, so that if a file starts with ‰PNG it gets saved as a png, and if it starts by ÿØÿà JFIF or ÿØÿáExif (I suppose just ÿØÿ is enough) it gets saved as a jpg, notwithstanding the original file extension.

**Comment by 27136773** [comment]
This is already supported, but for efficiency reasons only enabled for websites that knowingly providing the wrong mime-type. Please list the website(s) and sample image URLs that have the issue so it can be enabled for them.

**Comment by 27136773** [comment]
No further response => closed
