### ISSUE TITLE
[Copytoon] Connector not working

### ISSUE THREAD

**Issue by howlersting** [manga-download/hakuneko#3452]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The connector is unable to connect to the site and update the series list

**To Reproduce**
Steps to reproduce the behavior: Try to update filter on the site. Copytoon 142 seems to be the new site https://copytoon142.com/웹툰
1. Name of connector Copytoon
2. NA
3. NA
4. Unable to connect , err_name_resolution - unable to resolve domain dns i believe

**Screenshots**
![image](https://user-images.githubusercontent.com/79855279/118363014-ffc5f600-b5af-11eb-865f-c27279da9aef.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Domain doesn't exists anymore. No idea what the new domain is.
Connector will be deleted if nobody knows.

**Comment by Ever4engel** [comment]
https://copytoon142.com/

**Comment by howlersting** [comment]
Hi Sheepux

The new domain is https://copytoon142.com/ and the series are acccessible at https://copytoon142.com/%EC%9B%B9%ED%88%B0

Regards

**Comment by Sheepux** [comment]
PR will update the default value. 
Meanwhile you can change it in Hakuneko menu.

**Comment by howlersting** [comment]
Hi Sheepux

Can users change the domain in the HakuNeko menu. If yes, can you please tell me the steps. I cannot find any settings that allows users to change domains of existing connectors. 
If I misunderstood and the message wasn't for me. Apologies

Thanks and Regards

**Comment by Sheepux** [comment]
Open the menu in top left and change the Copytoon value

**Comment by howlersting** [comment]
Hi Sheepux

Please find the attached screenshots. I can only see options to change image quality, image format, throttle threshold and userids for websites. Is there a different UI or menu I need to check,

Regards

![image](https://user-images.githubusercontent.com/79855279/118405997-13e52280-b698-11eb-81b6-53c2e702ad09.png)
![image](https://user-images.githubusercontent.com/79855279/118406008-22333e80-b698-11eb-9a20-c67c4cd9ea5d.png)
![image](https://user-images.githubusercontent.com/79855279/118406058-61fa2600-b698-11eb-8cd2-2bc510f2ba20.png)

**Comment by Sheepux** [comment]
scroll more in the main menu there are options per connector in the menu

**Comment by howlersting** [comment]
No, I have reached the end of the line. Either my UI is dated or I'm missing something.

![image](https://user-images.githubusercontent.com/79855279/118406198-c2896300-b698-11eb-8b50-66d485dc8e65.png)

**Comment by Sheepux** [comment]
![copytoon](https://user-images.githubusercontent.com/19878135/118406285-b2af5600-b67b-11eb-840c-8baa9a02734f.jpg)

**Comment by howlersting** [comment]
Hi Sheepux

Got it. Sorry for the trouble and thanks for the help

Regards
