### ISSUE TITLE
TMOHentai

### ISSUE THREAD

**Issue by 741596357qpwo789512357** [manga-download/hakuneko#3454]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
In the TMOHentai connector, when I try to update the connector I immediately get this message: "FAILED TO UPDATE MANGA LIST FOR TMOHENTAI
CANNOT READ PROPERTY "TEXT" OF UNDEFINED"

**Screenshots**
![image](https://user-images.githubusercontent.com/71287475/118384438-cf378980-b5ba-11eb-9ade-0f19f21e6f57.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Sheepux** [comment]
DevNote: TMO removed the page count that HN was using. Fixing by chaning to hasNext pattern.
