### ISSUE TITLE
GNTAI

### ISSUE THREAD

**Issue by 741596357qpwo789512357** [manga-download/hakuneko#3455]
**Name of the website**
GNTAI

**Website urls (examples below)**
- Site: http://www.gntai.net/
- Manga List: http://www.gntai.net/?s=
- Manga example: http://www.gntai.net/mangas-hentai/curame-elfa-oscura-chan
- Chapter online viewer example: http://www.gntai.net/mangas-hentai/curame-elfa-oscura-chan
It is somewhat complicated to add the URLs of the website as they ask me

**Languages**
Spanish

**Additional details**
Nothing for the moment

**Comment by 27136773** [comment]
Already supported, please check before making a website suggestion
