### ISSUE TITLE
[Site Request] Patatescan

### ISSUE THREAD

**Issue by Bertrand6969** [manga-download/hakuneko#3456]
Name of the website
Patatescan

Website urls (examples below)

Site: https://patatescan.com/
Manga List: https://patatescan.com/manga/
Manga example: https://patatescan.com/manga/call-me-the-goddess-of-vengeance/
Chapter online viewer example: https://patatescan.com/call-me-the-goddess-of-vengeance-1/
Languages
French

*Website relationship
None

Additional details
None

**Comment by 27136773** [comment]
Template: WordPressMangastream
