### ISSUE TITLE
[Site Request] Japanime

### ISSUE THREAD

**Issue by Bertrand6969** [manga-download/hakuneko#3457]
**Name of the website**
Japanime

**Website urls (examples below)**
- Site: https://japanime.ch/
- Manga List: https://japanime.ch/manga/
- Manga example: https://japanime.ch/manga/matchless-emperor/
- Chapter online viewer example: https://japanime.ch/manga/matchless-emperor/chap-1/

**Languages**
French

**Website relationship*
None

**Additional details**
None

**Comment by 27136773** [comment]
Template: WordPressMadara
