### ISSUE TITLE
[Central de Mangas] website is probably dead

### ISSUE THREAD

**Issue by lucas3820** [manga-download/hakuneko#3459]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

![Captura de tela 2021-05-17 000616](https://user-images.githubusercontent.com/17399715/118427501-b951c380-b6a3-11eb-96c3-b783bd93b8b8.png)

**Comment by dodieboy** [comment]
look like Central de mangas website is down, no problem with the connector

**Comment by lucas3820** [comment]
something else, you know why only 120 sleeves appear? I believe that the site has much more than that.
![Captura de tela 2021-05-17 003445](https://user-images.githubusercontent.com/17399715/118429274-b2c54b00-b6a7-11eb-9597-d32bec19ad7b.png)

**Comment by dodieboy** [comment]
sorry, but i do not have the answer for that. Maybe you can ask in the discord group

**Comment by 27136773** [comment]
[Website](http://centraldemangas.online) is probably dead, regarding facebook the current URL is http://www.centraldemangas.com.br, but it is not loading for me (maybe region locked)...

**Comment by M4lho** [comment]
Well, looking at the [Central de Mangás group](https://www.facebook.com/groups/cdm.centraldemangas/), it looks like the site was removed by copyright, but that's just rumors. Their [Facebook page](https://www.facebook.com/CentralDeMangas) with around [~270.000 likes](https://web.archive.org/web/20200103022212/https://www.facebook.com/CentralDeMangas/) was suddenly erased too, I believe the Central de Mangás is over.
