### ISSUE TITLE
[Sektekomik] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3461]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
I'm failed continously when i download comics at sekte komik from hakuneko.

**To Reproduce**
1. Sektekomik
2. Name of manga (if connector update is working) --> Not working from hakuneko
3. Name of chapter (if manga update is working) --> Not working from hakuneko
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![Screenshot_2](https://user-images.githubusercontent.com/79199707/118650291-77915c00-b80e-11eb-8588-badb377daf2e.png)
![Screenshot_1](https://user-images.githubusercontent.com/79199707/118650300-78c28900-b80e-11eb-8bb1-774871e29eeb.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
References: dazedcat19/FMD2#540
