### ISSUE TITLE
[Site Request] Kiryuu

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3462]
**Name of the website**
Kiryuu

**Website urls (examples below)**
- Site: https://kiryuu.id/
- Manga List: https://kiryuu.id/manga/
- Manga example: https://kiryuu.id/manga/survive-romance/
- Chapter online viewer example: https://kiryuu.id/survive-romance-chapter-4-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Already supported, please check before making a suggestion
