### ISSUE TITLE
[Site Request] manga-zip.net

### ISSUE THREAD

**Issue by ProPooB** [manga-download/hakuneko#3464]
**Name of the website**
Manga-Zip
**Website urls (examples below)**
- Site: https://manga-zip.net/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://manga-zip.net/archives/277620.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
Japanese

**Website relationship*

**Additional details**

**Comment by 27136773** [comment]
Websaite has no ads and all chapters can be directly downloaded as ZIP (no images / online reader).
HakuNeko is for websites hiding behind an ad wall / have no convenient download option.
=> rejected
