### ISSUE TITLE
[Mangago] Connector not working

### ISSUE THREAD

**Issue by uuranor** [manga-download/hakuneko#3466]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
![mangago](https://user-images.githubusercontent.com/57646579/118701283-d3121880-b813-11eb-811e-589633d7eb95.jpg)

**Describe the bug**
I can access the chapter list but when I try to download it says cannot read property 'src' of null.

**To Reproduce**
1. Name of connector: Mangago
2. Name of manga (if connector update is working): Every manga I tried to download
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version e.g. 6.17 night version

**Comment by 27136773** [comment]
See #3447
