### ISSUE TITLE
[Manago] Connector not working

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#3468]
Error in loading images for this website. Using Nightly version.  Seem as mention before that the website is making it harder for HakuNeko to grab the images. Do we continue to use nightly or wait for fix to merge into 6.1.7?

<img width="841" alt="Capture" src="https://user-images.githubusercontent.com/60792860/118782476-b7188080-b8c0-11eb-9ecd-74e1dbf736ac.PNG">

**Comment by 27136773** [comment]
See #3447
