### ISSUE TITLE
[Site Request] Genshin Impact

### ISSUE THREAD

**Issue by SarkerNabil** [manga-download/hakuneko#3469]
**Name of the website**
Genshin Impact

**Website urls (examples below)**
- Site: https://genshin.mihoyo.com/en/manga
- Manga example: https://genshin.mihoyo.com/en/manga/detail/71?mute=1

**Languages**
English

**Additional details**
Mainly a website for a game, it issues manga once in a while related to the game.

**Comment by 27136773** [comment]
Website only provides a single webtoon => rejected
Use a browser extension or one of the scraper websites to download this webtoon
