### ISSUE TITLE
[Site Request] Book Walker

### ISSUE THREAD

**Issue by soliemad** [manga-download/hakuneko#3471]
**Name of the website**
Book Walker

**Website urls (examples below)**
- Site: https://bookwalker.jp/ 
- Manga List (need account): https://bookwalker.jp/holdBooks/
- Manga example:
    - Purchased example, no access
      https://viewer.bookwalker.jp/03/14/viewer.html?cid=c733f070-b495-4d56-b3fa-d79b713865d3&cty=1
    - Trial. Pages not scrambled: 
      https://viewer-trial.bookwalker.jp/03/9/viewer.html?cid=c733f070-b495-4d56-b3fa-d79b713865d3&cty=1
    - Free book but viewer is same as purchased. The access will be lost if the book stops being free. Pages scrambled: https://viewer.bookwalker.jp/03/14/viewer.html?cid=5d11d38e-d4c9-4da5-9a5a-699da379910a&cty=1

**Languages**
JP

**Website relationship**
also has global site but I don't know how it differs from the jp site
https://global.bookwalker.jp/

**Additional details**
More free books can be used in the site to test the viewer for purchased books.
https://bookwalker.jp/free/
Pages for non trial books are scrambled

**Comment by 27136773** [comment]
See: #809
