### ISSUE TITLE
[Site Request] MavAnime

### ISSUE THREAD

**Issue by zazouze** [manga-download/hakuneko#3472]
**Name of the website**
MavAnime

**Website urls (examples below)**
- Site: http://www.mavanimes.co/
- Manga List: http://www.mavanimes.co/tous-les-animes-en-vf/
- Manga List: http://www.mavanimes.co/tous-les-animes-en-vostfr-fullhd-2/
- Manga example: http://www.mavanimes.co/naruto-shippuden-vf/
- Chapter online viewer example: http://www.mavanimes.co/naruto-shippuden-1-vf/

**Languages**
french

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website is a mess to add
