### ISSUE TITLE
[Site Request] KissAnime

### ISSUE THREAD

**Issue by Fortune-dev** [manga-download/hakuneko#3475]
**Name of the website**
KissAnime

**Website urls (examples below)**
- Site: https://www9.kissanime.so/
- Manga List: https://www9.kissanime.so/anime-list.html
- Manga example: https://www9.kissanime.so/info/hunter-x-hunter-2011

**Languages**
English

**Comment by 27136773** [comment]
This could be a mirror of the [anime piracy website](https://piracy.moe) `KissAnimeX`, so maybe it would be better to add [KissAnimeX](https://kissanimex.com/)

**Comment by MikeZeDev** [comment]
Url is https://www2.kissanime.pe/ now.

**Comment by MikeZeDev** [comment]
dead
