### ISSUE TITLE
[Site Request] MangaMutiny

### ISSUE THREAD

**Issue by sohyuung** [manga-download/hakuneko#3480]
**Name of the website**
MangaMutiny

**Website urls (examples below)**
- Site: https://mangamutiny.org/
- Manga List: https://mangamutiny.org/titles
- Manga example: https://mangamutiny.org/title/CJHRuCXu
- Chapter online viewer example: https://mangamutiny.org/chapter/CJHRuCXu/vol-1-chap-0

**Languages**
English

**Comment by 27136773** [comment]
See #3290

**Comment by sohyuung** [comment]
> See #3290

oh, thank you, I'll wait then.

**Comment by MikeZeDev** [comment]
Website is dead for a while now.
