### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by sohyuung** [manga-download/hakuneko#3481]
**Is your feature request related to a problem? Please describe.**
Basically I hate how it is hard for me to get the updates of any manga because I do not read from a single site nor a single language.

**Describe the solution you'd like**
A button -beside the one you can from it download the whole manga- that if you press it you will get the new updates -chapters- of this page via email.

**Describe alternatives you've considered**
Without this button? I just go to every single site to check myself and it is flustering to know that your manga has not been updated. It annoying to sign up to every site and go to the setting or to the manga's page or whatever--- and imagine something like what happened to our dear MangaDex happening with this specific site... or even not having this feature.

It will be really great with the simple yet clear and clean design of HakuNeko (not like some of the complicated sites)

**Context (please complete the following information):**
 - My current HakuNeko Version is 6.17

**Additional context**
There should be a bar where you can put your email to get the notifications.

ــــــــــــــThank you.

**Comment by 27136773** [comment]
Automatic downloads are against HakuNeko's philosophy.
A manual check to detect new chapters is already covered by #653
