### ISSUE TITLE
[Site Request] 3asq

### ISSUE THREAD

**Issue by sohyuung** [manga-download/hakuneko#3482]
**Name of the website**
3asq

**Website urls (examples below)**
- Site: https://3asq.org/
- Manga List: https://3asq.org/manga/
- Manga example: https://3asq.org/manga/omniscient-readers-viewpoint/
- Chapter online viewer example: https://3asq.org/manga/omniscient-readers-viewpoint/n-a/

**Languages**
Arabic

**Comment by 27136773** [comment]
Website already supported.
Please check before making a new website request.

**Comment by sohyuung** [comment]
> Website already supported.
> Please check before making a new website request.

They do not share the same list, there are two sites called "3asq"

**Comment by 27136773** [comment]
I don't see any difference...

![image](https://user-images.githubusercontent.com/27136773/119184288-7ada5100-ba75-11eb-8415-44d8017bf503.png)

**Comment by sohyuung** [comment]
my bad, sorry, guess i haven't check it very well recently since they have the same old logo, thanks, and sorry again for the trouble
