### ISSUE TITLE
A website changed their url, can you update it on hakuneko please?

### ISSUE THREAD

**Issue by northernblade** [manga-download/hakuneko#3484]
**Name of the website**
Manga Diyarı

**Website urls**
- Site: https://manga-diyari.com/
- Manga List: https://manga-diyari.com/manga/
- Manga example: https://manga-diyari.com/manga/volcanic-age/
- Chapter online viewer example: https://manga-diyari.com/manga/volcanic-age/bolum-1/

**Languages**
Turkish

**Additional details**
This sites ex url is https://mangadiyari.com and it is already on Hakuneko.

**Comment by dodieboy** [comment]
Which version of Hakuneko you using? because i have make the change on #3373 already

**Comment by 27136773** [comment]
See #3347
Use nightly or wait for fix being merged into 6.1.7

**Comment by northernblade** [comment]
I am sorry for late return and yes i am using 6.1.7

**Comment by northernblade** [comment]
oh i see its fixed thank you
