### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by devem-software** [manga-download/hakuneko#3485]
I was banned from discord for publishing a group where the author can help us with information for nwjs in addition to the libraries that he develops.

I request that I be allowed to enter the server again

Thank you

My user is _//d3b31009_

**Comment by Sheepux** [comment]
done
the ban cause was annoted with "self advertisement"
i guess that it was that day where we were under spam and I didn't understand who this account was (didn't you have another account that was simple to identify you  ?)
