### ISSUE TITLE
[japanread] Connector not working

### ISSUE THREAD

**Issue by courli79** [manga-download/hakuneko#3488]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The download does not work

**To Reproduce**
1. Name of connector = Japanread
2. Name of manga (if connector update is working) = https://www.japanread.cc/manga/mi-seijuku
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
TypeError: Cannot read property 'dataset' of undefined
    at JapanRead._getPages (JapanRead.mjs:64)
    at async JapanRead._getPageList (Connector.mjs:615) EventTarget {manga: EventTarget, id: "/manga/mi-seijuku/8", title: "Vol.3 Ch.8", file: {…}, language: undefined, …}

**Screenshots**
![image](https://user-images.githubusercontent.com/82915245/119231629-2214c200-bb22-11eb-8fe0-51cf03878065.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by ronny1982** [comment]
They enabled reCaptcha protection for their chapters.

I will add support for reCaptcha recognition to HakuNeko, however it will still be required to solve a Captcha (for any arbitrary chapter) with [manual website interaction](https://hakuneko.download/docs/manual-website-interaction/) before any other chapter can be downloaded with HakuNeko.

![image](https://user-images.githubusercontent.com/27136773/119234454-4d9da980-bb2e-11eb-9ff6-b98dbb8e9231.png)

**Comment by 27136773** [comment]
See #3367
