### ISSUE TITLE
[Site Request] MangaOwl

### ISSUE THREAD

**Issue by milkNpudding** [manga-download/hakuneko#3490]
**Name of the website**
MangaOwl

**Website urls (examples below)**
- Site: https://Mangaowl.net
- Manga List:
- Manga example: https://mangaowl.net/single/68995/me-an-evil-god-and-wizard-girls
- Chapter online viewer example:

**Languages**
List of languages supported by the website 
English
...

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #2335
