### ISSUE TITLE
[manga18.club] Connector not working

### ISSUE THREAD

**Issue by user375s** [manga-download/hakuneko#3495]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
manga18.club manga list empty. Probably because of some website changes.

**To Reproduce**
Click the synchronize button for manga18.club list

**HakuNeko (please complete the following information):**
 - Version 8.3.4 nightly

Thanks

**Comment by M4lho** [comment]
**Cloudflare Loop** #2933

**Comment by user375s** [comment]
Ok thanks
