### ISSUE TITLE
[UnionMangas] list don't connect

### ISSUE THREAD

**Issue by Peixepeixe** [manga-download/hakuneko#3498]
The Unionmangas list does not connect with hakuneko, it loads, but no manga appears. 
I tried to use the MangaLivre and it worked correctly.
The site works perfectly in my browser.
I am using linux.
![Captura de tela_2021-05-24_06-01-34](https://user-images.githubusercontent.com/84708359/119325655-7a011500-bc57-11eb-915a-e37da7aae38e.png)
![Captura de tela_2021-05-24_06-14-00](https://user-images.githubusercontent.com/84708359/119325675-7ff6f600-bc57-11eb-93c1-1b912bb78838.png)

**Comment by M4lho** [comment]
It's okay here, I believe that as the Union is slow and falls all the time is one of the reasons for not having been able to load the list, I recommend using the clipboard.
![image](https://user-images.githubusercontent.com/84632071/119331044-488b4800-bc5d-11eb-89b7-e7f1065e11f4.png)

**Comment by 27136773** [comment]
Works fine on my end, adding 3 retries in case of a failure may or may not help to improve success of manga list scraping ...
