### ISSUE TITLE
[Site Request] SuperMangas

### ISSUE THREAD

**Issue by Peixepeixe** [manga-download/hakuneko#3499]
SuperMangas
- Site: https://www.supermangas.site/
- Manga List: https://www.supermangas.site/manhwa
- Manga example: https://www.supermangas.site/manhwa/solo-leveling
- Chapter online viewer example: https://www.supermangas.site/manhwa/solo-leveling/7859957

**Languages**
Mostly Portuguese but there are some manga with the English translation

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by Peixepeixe** [comment]
Sadly yes

Em ter, 4 de out de 2022 08:18, MikeZeDev ***@***.***>
escreveu:

**Comment by MikeZeDev** [comment]
Then @Sheepux pls :)
