### ISSUE TITLE
[Lezhinus] Connector not working

### ISSUE THREAD

**Issue by dmr111** [manga-download/hakuneko#3503]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I noticed the recent HakuNeko update that updated website links, I went to test www.lezhinus.com (formerly www.lezhin.com) since the update included that change. However, I still cannot read or download free chapters, and this time the second error changed to "Cannot read property 'd2' of undefined" in addition to the 404 error. 

I'm not sure if this helps, but Google Chrome extensions like Simple mass downloader or the Firefox page info could detect the image links to download (and the image links could be viewed in a new tab), but the images has to be loaded on the page via scrolling to them first. 

The links are numerical by page ( [page number].webp?q= ) in the episode and looks something like:

https://cdn.lezhin.com/v2/comics/6057692740255744/episodes/5556923846950912/contents/scrolls/18.webp?q=30&updated=1591859122140

https://cdn.lezhin.com/v2/comics/6057692740255744/episodes/5556923846950912/contents/scrolls/19.webp?q=30&updated=1591859122140

etc.

A page link example from a different free comic: https://cdn.lezhin.com/v2/comics/4817947542159360/episodes/5755841295417344/contents/scrolls/2.webp?q=30&updated=1496764657270

For later chapters released weekly for free, the link changes to something like (but could still be copy-and-pasted and viewed in incognito window):

https://cdn.lezhin.com/v2/comics/6057692740255744/episodes/5090628646273024/contents/scrolls/2.webp?access_token=d78a9545-9c31-4312-a6df-d537c74ac7d4&purchased=false&q=30&updated=1613716885376

Hmm, looking at those image links, they appear to use lezhin.com as a host while the reader uses lezhinus.com. Not sure if that detail is relevant, though.

**To Reproduce**
1. Name of connector www.lezhinus.com
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

![image](https://user-images.githubusercontent.com/57851738/119549504-e7e33480-bd5c-11eb-9ea5-3dd655cc3e70.png)

![image](https://user-images.githubusercontent.com/57851738/119549570-f6c9e700-bd5c-11eb-9a42-38ef8f02a5a2.png)

**HakuNeko (please complete the following information):**
 - Version 6.17@41c9fc

**Comment by dodieboy** [comment]
The issue is fix on the nightly vision 
#3419

**Comment by 27136773** [comment]
Cannot be reproduced in `6.1.7` or `nightly`, it works for me with random manga.
Please provide a sample manga.
Try performing manual website interaction before accessing lezhin inHakuNeko.

**Comment by dmr111** [comment]
The manga I was trying is Regnal Trigger: https://www.lezhinus.com/en/comic/regnal_trigger_en 

I still get the same errors in Version 6.1.7@311a31

**Comment by 27136773** [comment]
Still not reproducible for me.
Use manual website interaction to verify that you are correctly logged into your account with HakuNeko...

----

![image](https://user-images.githubusercontent.com/27136773/120383503-3e381080-c325-11eb-8436-1d4f4b4b139b.png)

**Comment by dmr111** [comment]
Tried manual website interaction, now I get 403 error.

![image](https://user-images.githubusercontent.com/57851738/120407698-4be49a80-c313-11eb-81a2-cca85890a04b.png)


![image](https://user-images.githubusercontent.com/57851738/120407718-53a43f00-c313-11eb-8464-48426d37409d.png)


![image](https://user-images.githubusercontent.com/57851738/120407683-4424f600-c313-11eb-80e2-184939f98970.png)

**Comment by 27136773** [comment]
Make sure you entered correct username and password for lezhin in settings

**Comment by dodieboy** [comment]
Don't know is it the same problem but having this error when running on nightly
![image](https://user-images.githubusercontent.com/9015764/120432016-e2649a80-c3ab-11eb-8fc1-960a8f683bd6.png)

**Comment by 27136773** [comment]
When `d2` is not accessible this could be caused by the website [not finished loading](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/Lezhin.mjs#L211) within the given [timeout](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/Lezhin.mjs#L224).
Increasing the timeout may help, but is not guaranteed.

**Comment by dodieboy** [comment]
i change the timeout from 2500 to 25000. still have the same error

**Comment by 27136773** [comment]
In that case i'm afraid only someone who can reproduce the issue may be able to debug and fix this

**Comment by dmr111** [comment]
I made sure my username and password is correct in both settings and manual website interaction.

Looking at the F12 Console, the link address HakuNeko tried to reach appears to be different to the actual link:

![image](https://user-images.githubusercontent.com/57851738/120535979-3a4dd200-c3a9-11eb-95f7-34da69c67bee.png)

https://ccdn.lezhin.com/v2/comics/6057692740255744/episodes/5090628646273024/contents/scrolls/43.webp?access_token=d78a9545-9c31-4312-a6df-d537c74ac7d4&purchased=true&q=40

Going to that link shows a "This site can’t be reached" page.

While the actual (working) image link uses purchased=false instead of purchased=true:

https://ccdn.lezhin.com/v2/comics/6057692740255744/episodes/5090628646273024/contents/scrolls/43.webp?access_token=d78a9545-9c31-4312-a6df-d537c74ac7d4&purchased=false&q=40

Identical urls save for the part with with purchased=false instead of purchased=true.

Does HakuNeko think my account purchased the episode (purchased=true) when I did not and I accessed it for free (purchased=false)? 

Is there a way to fix this?

**Comment by dmr111** [comment]
I managed to get past the problem for now by making a new account on Lezhin and switched to that one on HakuNeko.

**Comment by Leguu** [comment]
I was having the same problem (d2 and 403). I thought that HakuNeko was figuring out the purchased flag based on subscription, so I tried unsubscribing from the comic (from within the program), which fixed the issue.

@dmr111 can you check if unsubscribing works?

**Comment by dmr111** [comment]
@Leguu I have not subscribed to any comic on Lezhin and HakuNeko, so subscription did not cause my problem. I fixed my issue by making a new account for Lezhin and switched to the new one on HakuNeko.

**Comment by 27136773** [comment]
Handled by #2950
