### ISSUE TITLE
[mangapark] Connector not working

### ISSUE THREAD

**Issue by kinglessy** [manga-download/hakuneko#3505]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by kinglessy** [comment]
the chapters of the manga doesnt appear + tried to copy the manga url and paste it in the clipboard but it wont appear+when you  select the connector and the manags shows up on the manga list i cliocked on a random manga any manga it wont show the chapters
![Screenshot (25)](https://user-images.githubusercontent.com/84690859/119594749-ab571d80-bddc-11eb-9c71-1c38eed49b52.png)

**Comment by 27136773** [comment]
Cannot be reproduced on my end: mangas, chapters, images as well as copy & paste works as expected.
The sample manga shown in the screenshot does not exist on the website (outdated manga list?), so HakuNeko showing 0 chapters is correct.

Please provide existing sample manga for reproduction.
Make sure your version of HakuNeko is up to date.

![image](https://user-images.githubusercontent.com/27136773/119639171-a3689f00-be17-11eb-8103-c2a6a07d9cf1.png)

**Comment by 27136773** [comment]
No further response => closed
