### ISSUE TITLE
[manganelo] 520, 524 and 500 issues

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#3508]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
manganelo seems to be having error 520, 524 and 500 issues (only in HN) on mangalist refresh

**To Reproduce**
1. manganelo
2. on manga list refresh
3. ton of 520, 524 and 500 errors

doing the same (ish)(i used no request Options on the fetch) on chrome gets me 2 524 errors in the same amount of pages
Im not totally sure what is going on but I guess nelo/cloudflare don't like something in the request Options

adding retries on to the fetchdom doesn't work as those errors don't get retried

**Screenshots**
![](https://i.vgy.me/ifUAbr.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Probably caused by their recent domain change to `manganato` (which is now blazing fast for me)

**Comment by Rhisk** [comment]
> 
> 
> Probably caused by their recent domain change to `manganato` (which is now blazing fast for me)

Not only manganato, is `manganato` and `readmanganato`.

**Comment by 27136773** [comment]
Updated PR to support `copy & paste` links from both domains

**Comment by Rhisk** [comment]
https://manganato.com/
example: https://readmanganato.com/manga-bf979214 `readmanganato` only work for mangas, if u try to go at https://readmanganato.com/ u are redirect to https://manganato.com/
