### ISSUE TITLE
[BookLive] Purchased comics do not have any chapters

### ISSUE THREAD

**Issue by kuchenmitsahne** [manga-download/hakuneko#351]
When logged in via Manual Website Interaction, purchased books show up as having 0 chapters and therefore cannot be downloaded, whereas the samples for non-purchased books appear as having 1 chapter as usual. I think the issue is with `_getChapterList`.

https://github.com/manga-download/hakuneko/blob/c92ec7b0173dca368c12d839a3640779bb7dc91b/web/lib/hakuneko/engine/base/connectors/booklive.html#L47-L65

The problem seems to arise because `_getChapterList` is looking for `a.bl-bviewer` under an element (` ul.sub_actions`) that does not appear on the pages of purchased items when logged in.

<details>
  <summary><code>product_actions</code> HTML (logged in, purchased)</summary>

```html
<div class="product_actions">
    <ul class="main_actions">
        <li>
            <a class="btn_m read_action bl-bviewer sl-bread_b" href="javascript:return false;" data-title="424350" data-vol="001">
                <i class="btn_icon read_browser" deluminate_imagetype="png"></i>ブラウザで読む
            </a>
        </li>
        <li>
            <a href="#" onclick="return false;" class="btn_m read_action dt_origin bl-browse sl-aread_b" data-title="424350" data-vol="001" data-popup="1">
                <i class="btn_icon read_app" deluminate_imagetype="png"></i>アプリで読む
            </a>
        </li>
        <li class="app_login_get_point_2">
            <img src="//res.booklive.jp/resources/a/sp/common/images/app_login_get_point_2.png" alt="アプリログインで100ポイントGET！">
        </li>
        <li>
            <a class="btn_m keep_action" href="/follow/title-list">
                <i class="btn_icon keep_view" deluminate_imagetype="png"></i>フォロー中
            </a>
        </li>
    </ul>
</div>
```
</details>

<details>
  <summary><code>product_actions</code> HTML (logged out)</summary>

```html
<div class="product_actions">
    <ul class="main_actions">
        <li>
            <a class="btn_l buy_action" href="/purchase/product/title_id/424350/vol_no/001" id="product_button_1" onmousedown="window._gaq.push(['_trackEvent', 'bl_productParchase', 'Click', 'add']);">
                <i class="btn_icon dl_icon" deluminate_imagetype="png"></i>
                <span>今すぐ購入</span>
            </a>
        </li>
        <li>
            <a href="#" onclick="return false;" class="btn_m cart_action cart_in bl-cart bl-cart-url" data-title="424350" data-vol="001" id="product_button_2">
                <i class="btn_icon cart_icon" deluminate_imagetype="png"></i>
                <span class="btn_txt bl-cart-text">カートに入れる</span>
            </a>
        </li>
    </ul>
    <ul class="sub_actions clearfix">
        <li>
            無料サンプル
        </li>
        <li class="browser_reader">
            <a href="javascript:return false;" onclick="window._gaq.push(['_trackEvent', 'sample_btn_binb', 'Click', 'マンガ']);" class="btn_m bl-bviewer bl-tachiyomi_action sl-bstand_b" data-title="424350" data-vol="001">
                <i class="btn_icon tachiyomi_browser" deluminate_imagetype="png"></i>
                <span class="btn_txt">ブラウザ試し読み</span>
            </a>
        </li>
        <li class="app_reader">
            <a href="#" onclick="return false;" onmousedown="window._gaq.push(['_trackEvent', 'sample_btn_app', 'Click', 'マンガ']);" class="btn_m bl-browse sl-astand_b" id="open_dialog" data-title="424350" data-vol="001" data-sample="1" data-popup="1">
                <i class="btn_icon tachiyomi_app" deluminate_imagetype="png"></i>
                <span class="btn_txt">アプリ試し読み</span>
            </a>
        </li>
    </ul>
    <p class="mt10 link_right">
        <a href="/page/index/guide/read/index#tachiyomi" class="or_trilink" deluminate_imagetype="png">試し読みの方法はこちら</a>
    </p>
</div>
```
</details>

As for the reader itself, I compared the HTML source when logged in vs. logged out and found no significant differences (slightly different tracking elements, basically). In addition, the URL is exactly the same whether viewing a sample or a purchased book.

---

Update: Once I realized I could just edit the HTML file directly without having to recompile or anything, I tested it with `ul.sub_actions` removed from the method. As far as I can tell, it's not strictly necessary for the sample/logged-out case, and making the code more general allows it to also work for the logged in case. I was able to successfully load chapters for purchased and non-purchased items when logged in, and for non-purchased items when logged out. That very simple change should do the trick!

The only thing I thought was a little odd was that the volume number is used as a chapter number (so volume 1 contains only chapter 1, volume 2 contains only chapter 2, etc.), but seeing as there's no way to get actual chapter info and some sort of placeholder value is required, it doesn't particularly matter.

**Comment by 27136773** [comment]
Good find.

Unfortunately your local changes will be overwritten every time an auto-update is published, so it would be nice to solve this in the master code base as well.
Does the HTML when logged-in does not provide the list with `sub_actions`, because it seems to be missing in your post?

```html
<ul class="sub_actions clearfix">
    <!-- other li elements ... -->
</ul>
```

----

<details><summary>Here some tips when trying to finding a CSS selector:</summary>
<p>

1. Head over to the website that contains the chapters
2. Open the developer tools (F12)
3. In the developer tools switch to the _Elements_ tab
4. Toggle the element selector button (Fig. 01) and then click a chapter element in the website
5. Note the suggested CSS selector in the status bar of the _Elements_ tab
6. Switch to the _Console_ tab (Fig. 02)
7. Test a CSS selector by entering the JavaScript command, e.g.:
    ```javascript
    document.querySelectorAll('div#product_detail_area div.product_actions ul.sub_actions a.bl-bviewer')
    ```

----
![image](https://user-images.githubusercontent.com/27136773/62831326-784e9480-bc1d-11e9-886c-05724958887d.png)
**Fig. 01: Get suggested CSS selector for website elements**

![image](https://user-images.githubusercontent.com/27136773/62831289-bdbe9200-bc1c-11e9-83df-2e782664c33b.png)
**Fig. 02: Test a CSS selector with JavaScript**

</p>
</details>

**Comment by 27136773** [comment]
Based on the presented HTML source i would suggest the following CSS selector:
```
div#product_detail_area div.product_actions ul[class*="_actions"] a.bl-bviewer
```
Could you verify if this works in all the mentioned use cases?

**Comment by kuchenmitsahne** [comment]
>Does the HTML when logged-in does not provide the list with `sub_actions`, because it seems to be missing in your post?

Nope, it doesn't! The layout is a bit different when you're looking at a purchased item--that secondary box which is specified by `sub_actions` simply doesn't exist, which is why the HTML in the purchased case is so much shorter.

<details>
  <summary>Here are some screenshots:</summary>
  <p>

  ![purchased](https://user-images.githubusercontent.com/25233413/62836113-ee5af780-bc2d-11e9-8421-53b876bc5394.png)
  **Logged in, purchased**
  </p>
  <p>

  ![sample](https://user-images.githubusercontent.com/25233413/62836114-ee5af780-bc2d-11e9-8470-3b5498071f8b.png)
  **Logged out**
  </p>
</details>

I just tested your selector suggestion and it works for all cases, whether logged out or logged in. Thank you for the swift response!
