### ISSUE TITLE
[Site Request] Tappytoon Comics

### ISSUE THREAD

**Issue by slythrclw** [manga-download/hakuneko#3518]
**Name of the website**
Tappytoon Comics

**Website urls (examples below)**
- Site: https://www.tappytoon.com/en/
- Manga List: https://www.tappytoon.com/en/genres?alias=gl
- Manga example: https://www.tappytoon.com/en/comics/foxsaym
- Chapter online viewer example: https://www.tappytoon.com/en/chapters/813606143?

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #1824
