### ISSUE TITLE
[少年ジャンプ＋ (Shonen Jump +)] Connector not working

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#3521]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector for Shonen Jump Plus stopped working. New chapters no longer show up in my bookmarked SJP mangas, and Clipboard won't detect new mangas from that site.

**To Reproduce**
1. 少年ジャンプ＋ (Shonen Jump +) (shonenjumpplus)
2. Series and chapter to test: https://shonenjumpplus.com/episode/10834108156717915645
3. See 2

**HakuNeko (please complete the following information):**
 - Version: master@0e3b48

**Comment by 27136773** [comment]
Seems to be a regression caused by #3516, it still works in `6.1.7`
