### ISSUE TITLE
[Site Request] https://manganato.com/

### ISSUE THREAD

**Issue by whinee** [manga-download/hakuneko#3523]
**Name of the website**
https://manganato.com/

**Website urls (examples below)**
- Site: https://manganato.com/
- Manga List: https://manganato.com/
- Manga example: https://manganato.com/manga-fs982475
- Chapter online viewer example: https://readmanganato.com/manga-fs982475/chapter-7

**Languages**
English

**Website relationship*
Redirecting https://manganelo.com to https://manganato.com/, similar UI, similar XPaths, different url subdirectories.

**Additional details**
modifying https://manganelo.com connector to work with this site might work. The two sites have similar UI and XPaths, but the url subdirectories and the request header are different.

**Comment by 27136773** [comment]
See: #3511
