### ISSUE TITLE
[Site Request] YugenAnime

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#3528]
**Name of the website**
YugenAnime

**Website urls (examples below)**
- Site: https://yugenani.me
- Series List: https://yugenani.me/discover/
- Series example: https://yugenani.me/anime/1747/07-ghost/watch/
- Episode online viewer example: https://yugenani.me/watch/1747/07-ghost/1/

**Languages**
english, sub

**Comment by MikeZeDev** [comment]
Dead website ?
