### ISSUE TITLE
[Site Request] Gogo Play

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#3529]
**Name of the website**
Gogo Anime

**Website urls (examples below)**
- Site: https://streamani.net/
- Series List:
https://streamani.net/?page=1 - https://streamani.net/?page=212 (sub)
https://streamani.net/recently-added-raw?page=1 - https://streamani.net/recently-added-raw?page=2
https://streamani.net/recently-added-dub?page=1 - https://streamani.net/recently-added-dub?page=87
- Series example: https://streamani.net/videos/07-ghost-episode-1
- Episode online viewer example: https://streamani.net/videos/07-ghost-episode-1

**Languages**
sub, english, raw

**Comment by MikeZeDev** [comment]
dead
