### ISSUE TITLE
[Site Request] Aniorb

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#3530]
**Name of the website**
Aniorb (high quality streaming)

**Website urls (examples below)**
- Site: https://aniorb.me
- Series List: https://aniorb.me/recentlyadded/1 - https://aniorb.me/recentlyadded/305
- Series example: https://aniorb.me/details/pokemon-2019
- Episode online viewer example: https://aniorb.me/watching/pokemon-2019/1

**Languages**
sub

**Website relationship*
[ComicK](https://comick.fun)

**Comment by MikeZeDev** [comment]
"DNS points to prohibited IP".

Dead website?

**Comment by MikeZeDev** [comment]
Inactive Twitter account too. Closing.
