### ISSUE TITLE
Caisemh - Connector not working

### ISSUE THREAD

**Issue by howlersting** [manga-download/hakuneko#3539]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
The series gets updated on the conenctor. But I cannot download or view them in Haku Neko. Website is visible on the internal browser but chapters cannot be read. Seems there's a message on translating which says only readable on mobile.

To Reproduce
1. Caisemh (https://www.caisemh.com/)
2. All series
3. All chaps
4. Type Error: Failed to fetch

HakuNeko
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
It will be fixed with the PR, however even in the browser i can only see placeholder images pointing to `www.kelemh.com`

**Comment by howlersting** [comment]
I understand. Maybe they have changed somthing on their side
