### ISSUE TITLE
Webtoon Translate

### ISSUE THREAD

**Issue by jrdp18** [manga-download/hakuneko#354]
Is Webtoon Translate supported? Tried this [URL](https://translate.webtoons.com/webtoonVersion?webtoonNo=690&language=ENG&teamVersion=0), it loaded on the manga list but no chapters showing.

**Comment by 27136773** [comment]
Its broken right now and needs to be fixed

**Comment by 27136773** [comment]
This one is a little bit tricky.
The images are cleaned without any text and then overlayed with multiple text images.
e.g. [Noblesse Ep. 3](https://translate-phinf.pstatic.net/20141215_96/1418643758672GXSx5_JPEG/lW6kURvHPUhe9ZbWbZKr.jpg)

**Comment by vic1707** [comment]
Are you planning to get this website working soon for your awesome soft?
I know it's not the right place but i want to thanks you for Hakuneko it's fantastic !

**Comment by 27136773** [comment]
I doubt it will be done this year, focus is client, engine and UI improvement for the December release

**Comment by vic1707** [comment]
ok thanks you for the reply, look forward to seeing this new update!

**Comment by 27136773** [comment]
Similar to #367 the layers are merged down into a single image.
Therefore, the image format and quality is used from the settings (descrambling settings).
