### ISSUE TITLE
[Site Request] www.m-iq.me

### ISSUE THREAD

**Issue by AliFouad1** [manga-download/hakuneko#3540]
**Name of the website**
www.m-iq.me

**Website urls (examples below)**
- Site: https://www.m-iq.me/
- Manga List: https://www.m-iq.me/search/label/%D9%82%D8%A7%D8%A6%D9%85%D8%A9%20%D8%A7%D9%84%D9%85%D8%A7%D9%86%D8%AC%D8%A7

**Languages**
arabic

**Website relationship*
none

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dead website. Parking page. @Sheepux  please :p

**Comment by Sheepux** [comment]
no alternative domain found
