### ISSUE TITLE
Manga-Scantrad ( fix connector last don't work )

### ISSUE THREAD

**Issue by Bertrand6969** [manga-download/hakuneko#3544]
**Name of the website**
Manga-Scantrad

**Website urls (examples below)**
- Site: https://manga-scantrad.net/
- Manga List: https://manga-scantrad.net/manga/
- Manga example: https://manga-scantrad.net/manga/adabana-miyuki/
- Chapter online viewer example: https://manga-scantrad.net/manga/adabana-miyuki/ch-20/

**Languages**
French

**Website relationship*
None

**Additional details**
Madara template

**Comment by 27136773** [comment]
See #2933
