### ISSUE TITLE
failed to update mangalist for [site]

### ISSUE THREAD

**Issue by bingball** [manga-download/hakuneko#3547]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

i tried to refresh myreadingmanga but got a "failed to update manga list within the given timeout of 60 seconds" error  message, but the website is working

**Comment by dodieboy** [comment]
Error cause by cloudflare
hanlded by #2933
