### ISSUE TITLE
Webtoonily Connector not working

### ISSUE THREAD

**Issue by theduck749** [manga-download/hakuneko#3549]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
everything failed to download 

**To Reproduce**
1. Go to webtoonily or webtoonupdates
2. every manga
3. all of the chapters
4. "there was no content found in chapter *insert chapter number here*
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Please provide sample manga and chapter that did not work.
Also make sure that the manga and chapter are available on the website itself.

----

![image](https://user-images.githubusercontent.com/27136773/122464435-1e584c00-cfb7-11eb-8aa3-42495f0288d1.png)

**Comment by theduck749** [comment]
![image](https://user-images.githubusercontent.com/65233085/122465451-07622b80-cfb0-11eb-9f93-ad1b5d5a8de0.png)
no content was found

**Comment by 27136773** [comment]
This is not WebToonily, this is a complete different website...

**Comment by theduck749** [comment]
I thought I put in 2 different websites in total

**Comment by 27136773** [comment]
As it can bee seen it is too confusing handling multiple problems within a single ticket.
Please make a new ticket for `WebtoonUpdates` if the problem persist, this is now dedicated to `WebToonily`...

**Comment by MikeZeDev** [comment]
Can be closed, download is working. @Sheepux please.
