### ISSUE TITLE
[Bato.to] Connector not working

### ISSUE THREAD

**Issue by noering** [manga-download/hakuneko#3552]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot synchronize local manga list with online manga list from Bato.to
All the folder have grey colors, no blue folders for newest chapter.

**To Reproduce**
1. Connector : Batoto
2. Manga : Every manga, cannot refresh/update manga to the latest chapters
3. Chapter : Every chapter
4. Error message : 
Failed to update manga list for Batoto
Err_connection_refused https://bato.to/

**Screenshots**
Attached

**HakuNeko (please complete the following information):**
 - Version 6.17@311a31
 
![01](https://user-images.githubusercontent.com/3715548/121455039-076d9480-c9ce-11eb-902d-cfb8478b334c.JPG)

![Capture](https://user-images.githubusercontent.com/3715548/121049172-ae410d80-c7e1-11eb-9d96-2f847efaff07.JPG)

![01](https://user-images.githubusercontent.com/3715548/121051202-7935ba80-c7e3-11eb-840b-e11597ae3cb4.JPG)

**Comment by noering** [comment]
Sorry forget to fill 'Describe the bug'. 
Has been added it and also added 1 more screenshot (1st picture) about all local folder become grey.

**Comment by 27136773** [comment]
Cannot be reproduced on my end, could it be they activated CloudFlare protection for a certain period of time?

**Comment by noering** [comment]
I don't know, maybe so.
I tried with Isekaiscan and no problem, the link can be captured and the bookmark list synchronized.

**Comment by 27136773** [comment]
Yes it is CloudFlare protection, which kicks in whenever CloudFlare thinks the requests are suspicious
See #2933
