### ISSUE TITLE
[Site Request] Luminous Scans

### ISSUE THREAD

**Issue by Coravon** [manga-download/hakuneko#3556]
**Name of the website**
Luminous Scans

**Website urls (examples below)**
- Site: https://www.luminousscans.com/
- Manga List: https://www.luminousscans.com/series/
- Manga example: https://www.luminousscans.com/series/former-life-in-mount-hwa-volcanic-age/
- Chapter online viewer example: https://www.luminousscans.com/former-life-in-mount-hwa-chapter-169/

**Languages**
- English

**Comment by 27136773** [comment]
Template: WordPressMangastream
