### ISSUE TITLE
[question] how to convert downloaded manga into images to epub?

### ISSUE THREAD

**Issue by MakuSensei** [manga-download/hakuneko#3557]
Hello, I would like to know how I can use the hakuneko format converter to convert the manga that I have downloaded in image format to epub

**Comment by 27136773** [comment]
HakuNeko only supports downloading in a certain format, you cannot use HakuNeko to convert images afterwards.
You need a separate tool such as `kindlegen` (bundled with HakuNeko) or  `Kindle Comic Converter`

**Comment by MakuSensei** [comment]
thanks
