### ISSUE TITLE
[Site Request] Tsuki Mangás

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#3559]
**Name of the website**
Tsuki Mnagás 

**Website urls (examples below)**
- Site: https://tsukimangas.com
- Manga List: https://tsukimangas.com/lista-completa
- Manga example: https://tsukimangas.com/obra/30/tokyo-ghoul-re
- Chapter online viewer example: https://tsukimangas.com/leitor/30/28718/tokyo-ghoul-re/179#1

**Languages**
Portugues (BR)

**Comment by 27136773** [comment]
See #3032
