### ISSUE TITLE
[Site Request] SetsuScans

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#3563]
**Name of the website**
SetsuScans

**Website urls (examples below)**
- Site: https://setsuscans.com/
- Manga List: https://setsuscans.com/
- Manga example: https://setsuscans.com/manga/how-not-to-summon-a-demon-lord/
- Chapter online viewer example: https://setsuscans.com/manga/how-not-to-summon-a-demon-lord/chapter-68-1/

**Languages**
English

**Comment by 27136773** [comment]
Template: WordPRessMadara
