### ISSUE TITLE
[Site Request] ImperfectComic

### ISSUE THREAD

**Issue by mwehehehe** [manga-download/hakuneko#3564]
Name of the website
Imperfectcomic

Website urls (examples below)

- Site: imperfectcomic.com
- Manga List: imperfectcomic.com
- Manga example: https://imperfectcomic.com/comic/rooftop-sword-master
- Chapter online viewer example: https://imperfectcomic.com/comic/rooftop-sword-master/chapter-74/

Languages

- English

**Comment by 27136773** [comment]
Template: WordPressMadara

**Comment by 27136773** [comment]
Was added a month ago, please check if website already exist before making a new ticket

**Comment by mwehehehe** [comment]
sorry i don't know whats happen right now
but is it solved or what ?

**Comment by 27136773** [comment]
![image](https://user-images.githubusercontent.com/27136773/123041888-46501100-d3f6-11eb-8c7f-9131959e6590.png)

**Comment by mwehehehe** [comment]
just now try to update the list but got timeout and clipboard nothing happen just loading but not show the manga name

**Comment by 27136773** [comment]
If the website is broken create a new ticket with the corresponding template and information
