### ISSUE TITLE
[Site Request] truyenvn

### ISSUE THREAD

**Issue by cuonghapvn** [manga-download/hakuneko#3567]
**Name of the website**
truyenvn

**Website urls (examples below)**
- Site: https://truyenvn.com/
- Manga List: https://truyenvn.com/danh-sach-truyen
- Manga example: https://truyenvn.com/mairimashita-iruma-kun
- Chapter online viewer example: https://truyenvn.com/mairimashita-iruma-kun-chuong-206.html

**Languages**
Vietnamese

**Comment by 27136773** [comment]
Region Locked: Vietnam

**Comment by cuonghapvn** [comment]
@ronny1982 Is it mean that this site isn't supported?

**Comment by 27136773** [comment]
That means the one implementing this should keep in mind to use a VPN if required

**Comment by MikeZeDev** [comment]
Not anymore apparently.

**Comment by MikeZeDev** [comment]
dead
