### ISSUE TITLE
[Site Request] deliscan.xyz

### ISSUE THREAD

**Issue by Cheng145** [manga-download/hakuneko#3570]
Site: 
deliscan

Website urls (examples below)

Site:  [https://deliscan.xyz/]

Manga List: [https://deliscan.xyz/manga/]

Manga example: [https://deliscan.xyz/manga/painkiller/]

Chapter online viewer example: [https://deliscan.xyz/manga/painkiller/chapitre-60/]

Languages

French

**Comment by dodieboy** [comment]
Template: WordPressMadara
