### ISSUE TITLE
[asurascans] Connector not working

### ISSUE THREAD

**Issue by Odaxis** [manga-download/hakuneko#3571]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
https://www.asurascans.com/ manga list cannot be synchronized, Any attempt to load a manga from that site through Hakuneko fails. Error reported via F12/Network 

"_getUpdatedChaptersFromWebsite Error: Failed to load "https://asurascans.com/" within the given timeout of 60 seconds!"

**To Reproduce**
1. Name of connector is Asura Scans
2. Name of manga (if connector update is working) All manga, Connector seems to time out.
3. Name of chapter (if manga update is working). Not applicable. 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Error from F12
Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "https://asurascans.com/" within the given timeout of 60 seconds!
    at Request.mjs:371

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko Version [6.17]

**Comment by dodieboy** [comment]
Cloudflare loop error
handed by #2933
