### ISSUE TITLE
[SekteKomik] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3576]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**

**To Reproduce**
1. Name of connector --> SekteKomik
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/79199707/121825441-8fa8ae00-ccdc-11eb-827d-ce7be6e9f6f4.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
The URL https://sektekomik.com/manga/list-mode/ seems to be blocked by CloudFlare for various regions (even in browser), there is nothing that can be done in HakuNeko
