### ISSUE TITLE
[Site Request] Wib

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3577]
**Name of the website**
Wib

**Website urls (examples below)**
- Site: https://www.wib.my.id/
- Manga List: https://www.wib.my.id/p/project_10.html
- Manga example: https://www.wib.my.id/2021/06/isekai-man-chikin-hp-1-no-mama-de.html
- Chapter online viewer example: https://www.wib.my.id/2021/02/chapter-35_45.html

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: probably WordPressMangastream
