### ISSUE TITLE
[WorldRomanceTranslation] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3578]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
A clear and concise description of what the bug is the chapter didn't appear from hakuneko

**To Reproduce**
1. Name of connector --> https://wrt.my.id/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/79199707/121825516-16f62180-ccdd-11eb-9b9c-c158d6424a91.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Template: WordPressMangastream
