### ISSUE TITLE
[Site Request] Gabutscans

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3579]
**Name of the website**
Gabutscans

**Website urls (examples below)**
- Site: https://gabutscans.com/
- Manga List: https://gabutscans.com/manga/
- Manga example: https://gabutscans.com/manga/a-breakthrough-brought-by-forbidden-master-and-disciple/
- Chapter online viewer example: https://gabutscans.com/a-breakthrough-brought-by-forbidden-master-and-disciple-chapter-10-5/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: WordPressMangastream
Region Locked: Indonesia
Protected by CloudFlare it will not work in HakuNeko

**Comment by 27136773** [comment]
You only need to create one ticket, otherwise this behavior could be considered as impatient and unfair.
See #3341
