### ISSUE TITLE
Mangadex has no english(en) option

### ISSUE THREAD

**Issue by atomicfrenchfry** [manga-download/hakuneko#358]
When selecting mangadex as the primary website for your manga list, any manga chosen shows varying languages to choose from in chapter list, but for some reason, English is not one of them.
Example-Berserk:
![Screen Shot 2019-08-16 at 09 56 40](https://user-images.githubusercontent.com/54177803/63169096-533a9700-c00c-11e9-8ade-d132518da570.jpg)

**Comment by 27136773** [comment]
I think `gb` is mangadex' flag for english

**Comment by atomicfrenchfry** [comment]
> I think `gb` is mangadex' flag for english

I'm so stupid. Thanks man!
