### ISSUE TITLE
[Site Request] Katakomik

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3580]
**Name of the website**
Katakomik

**Website urls (examples below)**
- Site: https://www.katakomik.my.id/
- Manga List: https://www.katakomik.my.id/project/
- Manga example: https://www.katakomik.my.id/manga/the-villain/
- Chapter online viewer example: https://www.katakomik.my.id/the-villain-chapter-109/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: WordPressMangastream
