### ISSUE TITLE
[ManhuaID] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3582]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
A clear and concise description of what the bug is almost all of image where i download from hakuneko was html not jpg.

**To Reproduce**
1. Name of connector --> ManhuaID
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/79199707/121825859-e31bfb80-ccde-11eb-8d40-0aae431f3c2a.png)
![image](https://user-images.githubusercontent.com/79199707/121825864-e7e0af80-ccde-11eb-9960-d836b574a4a0.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
I don't see the problem, seems download work as expected

**Comment by Sheepux** [comment]
Same comment as #3583
webp is not html, it's an image format and it's the format that the website is providing. Nothing hakuneko can do. Closing.
