### ISSUE TITLE
[MGKomik] Connector not working

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3583]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
A clear and concise description of what the bug is all of image where i download from hakuneko was html not jpg.

**To Reproduce**
1. Name of connector MGKomik
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/79199707/121826404-aa315600-cce1-11eb-9ecf-bd5b5b3e279f.png)
![image](https://user-images.githubusercontent.com/79199707/121826407-ae5d7380-cce1-11eb-9921-f0f44cec1635.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
I don't see the problem, seems download work as expected

**Comment by Sheepux** [comment]
webp is not html, it's an image format and it's the format that the website is providing. Nothing hakuneko can do. Closing.
