### ISSUE TITLE
[ManHuaGui] Connector not working well in some comics

### ISSUE THREAD

**Issue by asd8299128** [manga-download/hakuneko#3590]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I found that some comics cannot get the chapters in hakuneko

**To Reproduce**
1. Select a comic like "High School DxD" with this problem, and copy its link "https://www.manhuagui.com/comic/1152/" to the clipboard. 
2. Paste it to hakuneko, then press the refresh icon. 
3. Ok, we get the manga, then select the only result to see the chapters. 
4. Then, we get 0 / 0 chapters in return. 
5. No message or error post, it just cannot get anything, but I can see it all in the brower. 

**Screenshots**
https://i.imgur.com/nLsxWQv.jpg

**HakuNeko (please complete the following information):**
 - rev 6.1.7@f5e130

**Comment by XenonR** [comment]
Works as designed. Webpage blocks access:
![image](https://user-images.githubusercontent.com/18627623/123626816-886fbd00-d811-11eb-99bb-e1810d224040.png)

Other mangas work just fine. Eg: https://www.manhuagui.com/comic/2703/

Closed.
