### ISSUE TITLE
[Manga Host] Connector not working

### ISSUE THREAD

**Issue by Greed4183** [manga-download/hakuneko#3596]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not exactly a bug, the website address has changed.
New link is: https://mangahost4.com/

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko 6.17
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See: #2933
