### ISSUE TITLE
[Manga18 Fx] Connector not working

### ISSUE THREAD

**Issue by howlersting** [manga-download/hakuneko#3598]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloading chaps gives 500 server error

**To Reproduce**
1. Manga18 Fx
2. All the series
3. Any chap from any series
4. Error : Page : https://xyz... returned status 500 ..

**Screenshots**
![image](https://user-images.githubusercontent.com/79855279/122654405-cbbe9180-d168-11eb-918e-e8b1a2796799.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #2933
