### ISSUE TITLE
[Site Request] komikindo

### ISSUE THREAD

**Issue by akn19** [manga-download/hakuneko#3599]
**Name of the website**
KomikindoId

**Website urls (examples below)**
- Site: https://komikindo.id/
- Manga List: https://komikindo.id/daftar-komik/?list
- Manga example: https://komikindo.id/komik/sousou-no-frieren/
- Chapter online viewer example: https://komikindo.id/sousou-no-frieren-chapter-48/

**Languages**
- indonesia

**Comment by manh21** [comment]
Templare: wordpress mangastream
