### ISSUE TITLE
Fails to load chapter - 404

### ISSUE THREAD

**Issue by cesiarath** [manga-download/hakuneko#360]
I'm running version rev.e53f6a. Manga is Liebling! on Mangago. All chapters are able to be viewed and downloaded except for chapter 45.  I am able to load and view the chapter in my browser just fine.

![hakuneko_error01](https://user-images.githubusercontent.com/41811640/63232741-63ab6700-c1f0-11e9-816f-0e2dd4a01401.jpg)

**Comment by 27136773** [comment]
Fixed in master 8a7a45f0
Needs to be merged into 5.0.8

**Comment by 27136773** [comment]
Resolved in 55ba9e4b
