### ISSUE TITLE
[MangaGo] Connector not working

### ISSUE THREAD

**Issue by bingball** [manga-download/hakuneko#3604]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Hakuneko error](https://user-images.githubusercontent.com/85443271/122803593-16562000-d2c7-11eb-85b4-b0396f3fb695.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
 i tried with all the mangas but got this error message, im not sure why. Thank you in advance

**Comment by Sheepux** [comment]
894 ? We're supposed to be at 895
894, looks the same as 891

However, if you do not give the name/url of the chapter as REQUESTED IN THE ISSUIE TEMPLATE, we cannot test it.
Website is working for me, and it's 895

**Comment by bingball** [comment]
I tried again after one day and now got this error message instead. I wonder if it's only on my side.
![image](https://user-images.githubusercontent.com/85443271/122969109-92ff0200-d38c-11eb-83c8-775b975b9d4d.png)

**Comment by uuranor** [comment]
I don't know if it can help, This is what happens when I tried to download any manga's chapter
![Immagine](https://user-images.githubusercontent.com/57646579/122975553-bf6a4c80-d393-11eb-9a0f-deea4955b470.jpg)

**Comment by 27136773** [comment]
Maybe they randomize which script is received. In the error it is clearly visible that the URL was not correctly decoded.

**Comment by Endareth** [comment]
Confirming I get the identical error described by @bingball. Apparently the site was offline for some reconstruction until recently, maybe they're still tweaking things?
