### ISSUE TITLE
[hiperdex] website not working (website not working)

### ISSUE THREAD

**Issue by codexhouse** [manga-download/hakuneko#3605]
the problem is the website not working in hakuneko
not being able to view the list and giving me this error 
also not being able to view it from hakuneko 
meanwhile the website works on my browser 
https://hiperdex.com/

 - Version [e.g. 6.17]
![image](https://user-images.githubusercontent.com/71021362/122845095-d7da5880-d2fa-11eb-97ec-a456eb0459ec.png)

**Comment by 27136773** [comment]
See #2933
