### ISSUE TITLE
patatescans

### ISSUE THREAD

**Issue by Bertrand6969** [manga-download/hakuneko#3607]
**Name of the website**
patatescans

**Website urls (examples below)**
- Site: https://patatescans.com/
- Manga List: https://patatescans.com/mangas/
- Manga example: https://patatescans.com/manga/dont-be-like-this-son-in-law/
- Chapter online viewer example: https://patatescans.com/dont-be-like-this-son-in-law-chapitre-1/

**Languages**
french

**Website relationship*
new domain to 
https://patatescan.com/

Thème : WordPressMangastream

**Comment by 27136773** [comment]
Website already exist, please check before requesting a website
