### ISSUE TITLE
[Site Request] mangapl

### ISSUE THREAD

**Issue by annewbies** [manga-download/hakuneko#3609]
**Name of the website**
mangapl

**Website urls (examples below)**
- Site: https://mangapl.com/
- Manga List: https://mangapl.com/?s&post_type=wp-manga&adult=1&m_orderby=new-manga
- Manga example: https://mangapl.com/manga/fitness-uncensored/
- Chapter online viewer example: https://mangapl.com/manga/fitness-uncensored/chapter-10/

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
This Website Had Uncensored Version of Manga

**Comment by 27136773** [comment]
Template: WordPressMadara
