### ISSUE TITLE
Update toonkor's url to toonkor.guru

### ISSUE THREAD

**Issue by su0su0** [manga-download/hakuneko#361]
Hello Ronny, when you have the time please change [toonkor](https://toonkor.guru/)'s url to toonkor.**guru** (previously toonkor.rip). Thank you!! 💖💖💖

**Comment by 27136773** [comment]
Done in 1336dd1a

**Comment by su0su0** [comment]
> Done in [1336dd1](https://github.com/manga-download/hakuneko/commit/1336dd1a30e8e66b046bece2a337e8b9255fc3ad)

thanks, Ronny, you're the best 🥰
