### ISSUE TITLE
[Question] Availability/Possibility of Adding Sources Myself

### ISSUE THREAD

**Issue by korewatori** [manga-download/hakuneko#3610]
General question, is there any way I can add a site to be supported by Hakuneko myself? I'd like to add a site that has a similar frontend to https://9anime.to/ - would there be any way someone could manually add support themselves or would this have to be done on your end?

Cheers,
Tori

**Comment by 27136773** [comment]
You have to [write a plugin and place it into the plugin directory](https://hakuneko.download/docs/install/#user-plugins)
