### ISSUE TITLE
[Site Request] manhwamanga.net

### ISSUE THREAD

**Issue by IsekaiMaou** [manga-download/hakuneko#3611]
manhwamanga

- Site: https://manhwamanga.net/
- Manga List: https://manhwamanga.net/latest-updates
- Manga example: https://manhwamanga.net/secret-class-01.html
- Chapter online viewer example: https://manhwamanga.net/secret-class-01/chapter-86.html

**Languages**
english
korea

**Comment by MikeZeDev** [comment]
Website has nothing to do with mangas anymore
