### ISSUE TITLE
mangapark

### ISSUE THREAD

**Issue by bakamarimo** [manga-download/hakuneko#3615]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
yes
**Describe the bug**
The manhwa(in this case) is loading in the browser and i am able to read it there as well. But upon finding it in hakuneko using the said connector "MANGAPARK" which has a huge number (56k) of entries, the app isnt able to download or let me preview any chapter. 
**To Reproduce**
1. Name of connector: MANGAPARK
2. Name of manga (if connector update is working): My stepmom/this doesn't feel like me 
![Screenshot (622)](https://user-images.githubusercontent.com/86364806/123115002-623acd80-d45d-11eb-8b7e-610e5ea5563d.png)

3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Robonau** [comment]
get pages times out (not cloudflare)

![](https://cdn.discordapp.com/attachments/581629183159959584/857235597122601020/unknown.png)

**Comment by 27136773** [comment]
See #2933
