### ISSUE TITLE
HakuNeko - saving a list of manga sites

### ISSUE THREAD

**Issue by Vancouverron** [manga-download/hakuneko#3616]
Aloha, 
HakuNeko is an outstanding program for downloading manga from various sites. 
As a newbie, the question I have concerns the Website / manga list. I have only a few favorite sites. For example, lets use two sites, Mangalife, and Mangadex. 
Every time I start HakuNeko, I have to click on [Clipboard], which gives me the entire list of all available sites, and find Mangalife. It then loads the manga list, and I can search for a title. 
Is there a shortcut for HakuNeko to remember the last site I used?
However, even if not, this is a great application - I love it. 
Mahalo, 
Ron

**Comment by 27136773** [comment]
There is already a feature request for this in #535

**Comment by Vancouverron** [comment]
Mahalo for the heads-up Ronnie.
