### ISSUE TITLE
[Site Request] pairof2+

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#3617]
**Name of the website**
pairof2+

**Website urls (examples below)**
- Site: https://pairof2.com/
- Manga List: https://pairof2.com/project/
- Manga example: https://pairof2.com/manga/mushoku-tensei-isekai-ittara-honki-dasu/
- Chapter online viewer example: https://pairof2.com/mushoku-tensei-jobless-reincarnation-chapter-72/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: WordPressMangastream
