### ISSUE TITLE
[Site Request] mangayabu

### ISSUE THREAD

**Issue by legendarysnake0** [manga-download/hakuneko#3618]
**Name of the website**
mangayabu

**Website urls (examples below)**
- Site: https://mangayabu.top
- Manga List: https://mangayabu.top/lista-de-mangas/
- Manga example: https://mangayabu.top/manga/fullmetal-alchemist
- Chapter online viewer example: https://mangayabu.top/ler/fullmetal-alchemist-capitulo-01-my21187/
**Languages**
portuguese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
The mangas chapters loads all at once. Like if you open a random manga chapter 3- all pages will load in one single page vertically.

**Comment by 27136773** [comment]
Cannot be reached from my end, could this be region locked?

**Comment by legendarysnake0** [comment]
> Cannot be reached from my end, could this be region locked?

i really dont know, try to use a Brazil vpn and see if it will work for you.

**Comment by 27136773** [comment]
Site can be successfully accessed from brazil

**Comment by RenanMenck** [comment]
**Website relationship**
https://yabutoons.com/ (same group webtoons site)

**Additional details**
a site with a good manga and webtoons collection to facilitate searching, and quick update of them, since there are few Brazilian sites with a larger manga collection..

**Comment by MikeZeDev** [comment]
dead
