### ISSUE TITLE
[Site Request]acggd

### ISSUE THREAD

**Issue by voltes2** [manga-download/hakuneko#3620]
**Name of the website**
http://www.acggd.com/

**Website urls (examples below)**
- Site: http://www.acggd.com/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Empty website? dead?

**Comment by MikeZeDev** [comment]
Dead no alternative found
