### ISSUE TITLE
[Site Request] brmangas

### ISSUE THREAD

**Issue by legendarysnake0** [manga-download/hakuneko#3621]
**Name of the website**
brmangas

**Website urls (examples below)**
- Site: https://www.brmangas.com/
- Manga List: https://www.brmangas.com/category/mangas/
- Manga example: https://www.brmangas.com/manga/kakegurui-online/
- Chapter online viewer example: https://www.brmangas.com/ler/kakegurui-1-online/

**Languages**
portuguese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
dead
