### ISSUE TITLE
[Site Request] YesMangas

### ISSUE THREAD

**Issue by legendarysnake0** [manga-download/hakuneko#3622]
**Name of the website**
yesmangas

**Website urls (examples below)**
- Site: https://yesmangas1.com/
- Manga List: https://yesmangas1.com/mangas
- Manga example: https://yesmangas1.com/manga/dragon-ball-ym34584
- Chapter online viewer example: https://yesmangas1.com/manga/dragon-ball-ym34584/194#2

**Languages**
portuguese
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
the site name is yesmangas1 on the url, but the actual name is just yesmangas

**Comment by MikeZeDev** [comment]
Cloudflare access denied. Geoblocked?

**Comment by MikeZeDev** [comment]
dead?

**Comment by legendarysnake0** [comment]
Site is dead, never mind
