### ISSUE TITLE
[Enhancement] Add terminal variant

### ISSUE THREAD

**Issue by divergnight** [manga-download/hakuneko#3628]
I would like you to add a variant with access only through the terminal. I don't know JavaScript at all, but it would be nice to be able to access the application without the interface. And thus launch requests / downloads automatically from a bash command.

**Comment by 27136773** [comment]
Rejected:
- against HakuNeko's philosophy (see documentation)
- technically not possible, UI is required to bypass certain protections such as JS challenges, CAPTCHAs, ...
