### ISSUE TITLE
[Site Request] MangaYabu

### ISSUE THREAD

**Issue by enzo40** [manga-download/hakuneko#3636]
**Name of the website**
MangaYabu

**Website urls (examples below)**
- Site: https://mangayabu.top/
- Manga List: https://mangayabu.top/lista-de-mangas/
- Manga example: https://mangayabu.top/manga/god-retreat/
- Chapter online viewer example: https://mangayabu.top/ler/god-retreat-capitulo-26-my634564/

**Languages**
Portugues (BR)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Cloudflare problem, geoblocked?

**Comment by MikeZeDev** [comment]
twitter redirect.

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/3618
