### ISSUE TITLE
Add support for website [kakaopage.co.id]

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#364]
https://www.webcomics.co.id/

**Comment by XenonR** [comment]
Redirects to https://kakaopage.co.id/

**Comment by MikeZeDev** [comment]
dont mind me i was wrong.

**Comment by Sheepux** [comment]
I don't know if it's the same as https://page.kakao.com/

**Comment by MikeZeDev** [comment]
Oh apparently not, one is id while the other is korean. Sorry i am dumb.

**Comment by MikeZeDev** [comment]
closed as dead
