### ISSUE TITLE
Missing Pages

### ISSUE THREAD

**Issue by Zeonymous** [manga-download/hakuneko#365]
Pages total: 20
Pages downloaded: 1-16 & 20
Pages not downloaded: 17, 18, 19

Issue is with The Promised Neverland, Mangastream.
Persists through all ~150 chapters, all chapters it seems.
Can confirm, all chapthers have only 17 pages total, the pages listed above are the only ones missing across all chapters.

Not sure if I'd messed something up, these are the setting I've changed;
Directory: Changed to preference locale
Sub Directories: On
File Format: (*.cbz)

**Comment by Zeonymous** [comment]
Seems this is indeed MangaStream specific. KissManga looks to be working correctly.
I did also confirm the pages missing in the application are not missing on MangaStream.

(This is also the case for the the missing pages when using the preview function)

As well, disabling the preview function show the same results.

I'm not tech savvy, so I'm not sure how I'd assist. However, I'd like to say this is an amazing program, and I'd like to show my appreciation by helping any way I can.

**Comment by 27136773** [comment]
Reason is the pages are not listed on page 1, seems a limitation og how much pages are available in the dropdown...
Need to implement an alternative solution to solve this issue

![image](https://user-images.githubusercontent.com/27136773/63294701-43040f80-c2cb-11e9-829a-cef5b5ee59f9.png)

**Comment by Zeonymous** [comment]
Ohhhh, I see, I see. That's a strange situation. So it's on the page itself's end. I wonder if this could be bypassed using the url, as it uses basic numerals as it's indexing. Rather than using it's own built-in "skip to" using with this method, the first, and last ~ filling in the numbers in-between. In this case, 2-19, finding a full 20 value, and then just using the URL itself in order to source from.

I told ya I wasn't tech savvy. I'm sure it's something way over my head.

Appreciate the quick resolution!!

**Comment by 27136773** [comment]
This was already fixed, but migrating to 5.0.8 introduced this regression bug. However it shall work again now.
