### ISSUE TITLE
Nettruyen not working

### ISSUE THREAD

**Issue by dragon031288** [manga-download/hakuneko#3651]
the Nettruyen website is not working now.
the website nettruyen has changed to new domaim: http://www.nettruyenvip.com/ 
hakuneko software can't detect any manga now. Please check the issue. Thank you

**Comment by XenonR** [comment]
Where do you get the new address from after a change?

**Comment by dragon031288** [comment]
when I typed the old website http://nettruyen.com/ to check if the website is still working , the website address automatic changed to http://www.nettruyenvip.com/
