### ISSUE TITLE
[Mangago.me] Connector not working

### ISSUE THREAD

**Issue by mpolintan** [manga-download/hakuneko#3654]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Tried more than 10 links from Mangago.me but it doesnt download properly. it says "DOWNLAOD FAILED"

**To Reproduce**
1. Name of connector: Mangago.me
2&3. Sample of the manges:
https://www.mangago.me/read-manga/national_high_school_of_economic_freedom_saesil_high/
https://www.mangago.me/read-manga/i_just_want_to_walk_on_the_flower_road_promo/
https://www.mangago.me/read-manga/snack_don_t_run_away/
https://www.mangago.me/read-manga/foxy_boy/
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate see #3646
