### ISSUE TITLE
[Site Request] comick.fun

### ISSUE THREAD

**Issue by RespectfulManga** [manga-download/hakuneko#3655]
**comick.fun**
thewebsitename

**Website urls (examples below)**
- Site: https://comick.fun/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Already supported, please check in HakuNeko before creating a website request

**Comment by RespectfulManga** [comment]
but all manga ae not there

**Comment by 27136773** [comment]
Then create a ticket to report broken website
