### ISSUE TITLE
[Site Request] morenovel

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#3658]
**Name of the website**
MORENOVEL

**Website urls (examples below)**
- Site: https://morenovel.net
- Manga List: https://morenovel.net/novel/?m_orderby=alphabet
- Manga example: https://morenovel.net/novel/to-be-a-power-in-the-shadows/
- Chapter online viewer example: https://morenovel.net/novel/to-be-a-power-in-the-shadows/chapter-203/

**Languages**
Indonesian

**Comment by 27136773** [comment]
Template: `WordPressMadaraNovel`
