### ISSUE TITLE
Chapter download Failed Line Webtoon (Indonesian)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#367]
i tried to download a manga in webtoon. but the download is fail. this result:
![Capture](https://user-images.githubusercontent.com/45929526/63334673-15b86f80-c366-11e9-95d9-e6d2598f9d09.PNG)
in picture is not show the failed download. But when i check the folder.The folder is empty :
![Capture2](https://user-images.githubusercontent.com/45929526/63334877-8bbcd680-c366-11e9-952d-c02ff6f4c872.PNG)
i tried on browser and it work.
![Capture4](https://user-images.githubusercontent.com/45929526/63334265-4350e900-c365-11e9-881c-a190fc4660b2.PNG)

**Comment by 27136773** [comment]
This [specific webtoon](https://www.webtoons.com/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1) is a motion webtoon using the oz-reader.
Images may consist of multiple image layers.
I'll leave this issue open for now, but i doubt support will be added...

**Comment by 27136773** [comment]
Basic support for motion webtoons has been added.
Animated layers are merged into a single image.
The image format and quality is used from the settings (descrambling settings).
Visual effects and sound effects are not supported.

----

I would appreciate if someone could compare some more samples from HakuNeno with the website to confirm it is working as expected (only tested with [Ghost Path - 01 Prolog](https://www.webtoons.com/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1) so far).

**Comment by MIRVOUS** [comment]
nice work
