### ISSUE TITLE
[Naver Webtoon] Connector failed to update manga

### ISSUE THREAD

**Issue by K-uro** [manga-download/hakuneko#3674]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Every time I refresh the connector it always fail to load manga lists, informing the user that the website does not provide a manga list and that instead copy and paste the URL containing the chapters which doesn't work as well.

**To Reproduce**
1. Naver Webtoon
2. The connector update is not working
3. The connector update is not working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
N/A

If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by FinnRG** [comment]
Naver Webtoon doesn't provide a manga list. Therefore please use the clipboard connector and click on the copy paste button on the top right of the manga list UI element (As described in the FAQ: https://hakuneko.download/docs/FAQ/#copy-and-paste ). If this still doesn't work, please provide the manga that you're trying to read.

![image](https://user-images.githubusercontent.com/65015656/125092484-aff83c80-e0d1-11eb-99d7-4d78a7892197.png)
