### ISSUE TITLE
[ManhuaScan] Connector not working

### ISSUE THREAD

**Issue by howlersting** [manga-download/hakuneko#3675]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Unable to update manhwas or download the chapters

**To Reproduce**
1. Manhuascan (https://manhuascan.com/)
2. Hajimete Ageru (https://manhuascan.com/manga-quothajimetequot-ageru.html )
3. Chapter 0 (https://manhuascan.com/read-quothajimetequot-ageru-chapter-0.html)
4. 403 error in download tab

**Screenshots**
![image](https://user-images.githubusercontent.com/79855279/124643861-37b23100-deaf-11eb-92ae-863ac74412b2.png)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
Provide sample manga and chapter, otherwise it cannot be reproduced

**Comment by howlersting** [comment]
Done,

Sample series with relevant chapter links added
A screenshot of the error is added as well (Apologies couldn't snip the error message)

**Comment by 27136773** [comment]
Seems like referer needs to be added to image links, e.g.
```bash
curl  -H 'Referer: https://manhuascan.com/' 'https://qq4.mhscdnv4.xyz/go/yumh.mhscdnv3.club/images/2020/05/31/d55be54f2f593cc6e37e7e976a1c279d4ddd96ac_447988_600_450.jpg'
```

**Comment by syleniaa** [comment]
is the problem solved?? it doesn't work for me either

**Comment by 27136773** [comment]
As long as the ticket is open, the issue is not solved

**Comment by nimra63626626** [comment]
![Screenshot_20220903_014414_com android chrome](https://user-images.githubusercontent.com/112720268/188232734-fadbf5db-818d-41f2-a08b-38e3cef46e18.jpg)
I did everything but now it can't open.. Kindly tell me what can i do...ERR_SSL_PROTOCOL_ERROR this error occur again and again but now it can't open ... Its been a 3 month, i do all the procedures but now it cant open.
