### ISSUE TITLE
[9Anime] Connector not working

### ISSUE THREAD

**Issue by korewatori** [manga-download/hakuneko#3678]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Up until two days ago, the MyCloud and VidStream mirrors to episodes on 9anime (regardless of what anime) worked perfectly. They would download, most of the time with no errors but sometimes, when I had an error I could just redownload it and it'd be fine. Both MyCloud and Vidstream do not work anymore, it instantly fails. I tried grabbing the direct m3u8 link to the episode files and I couldn't visit them in my browser. I don't know what happened all of a sudden, maybe they changed something that broke functionality within Hakuneko? Streamtape mirror still works fine, as that is an MP4 file and the issue only happens with m3u8/ts files. Weirdly enough when I visit the website in a browser the streaming works fine, but when I try to visit the m3u8 url in a browser that gives a 404.
This is weird. The issue seems to be temperamental, I got it working without doing something yesterday, and now it stopped working again.

**To Reproduce**
1. Name of connector - 9Anime
2. Name of manga (if connector update is working) - Don't Toy With Me, Miss Nagatoro (this applies to more than just this anime)
3. Name of chapter (if manga update is working) - Multiple
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - 

`DownloadJob.mjs:295 TypeError: playlist.match is not a function
    at DownloadJob.mjs:187 {hash: "id,language,resolution", mirrors: Array(1), subtitles: Array(0)}`

**Screenshots**
![image](https://user-images.githubusercontent.com/76889884/124912249-a1ccf200-dfe5-11eb-8463-ac2bb7722da0.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@f5e130

**Comment by 27136773** [comment]
Seems to me like recently the website has some problems. Browser sometimes also cannot correctly stream episodes.

**Comment by korewatori** [comment]
Oh right... I was worried whether this was a problem with Hakuneko in itself but it doesn't look like it then

**Comment by 27136773** [comment]
Just switch series/episodes in HakuNeko until it works, thats what i do when something in `9ANIME` did not load correctly on the first or second attempt...
