### ISSUE TITLE
[Site Request] Novel Ringan

### ISSUE THREAD

**Issue by zenkijoe** [manga-download/hakuneko#3679]
**Name of the website**
Novel Ringan

**Website urls (examples below)**
- Site: https://novelringan.com/
- Manga List: https://novelringan.com/daftar-novel/
- Manga example: https://novelringan.com/series/dungeon-predator/
- Chapter online viewer example: https://novelringan.com/dungeon-predator-chapter-555/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by FinnRG** [comment]
This site is already supported. Please check if you are using the latest version.

**Comment by zenkijoe** [comment]
no sir i have check it. but still no. and i am using the latest version hakuneko 6.1.7

**Comment by Pyther99** [comment]
Could you send a screenshot of the connector search site?

![image](https://user-images.githubusercontent.com/65015656/124963090-ae6e3c00-e01f-11eb-9640-a2e16174f9dd.png)

**Comment by FinnRG** [comment]
It seems that the distributed version isn't up to date with the version here on Github. This issue can be closed because it is a duplicate of #3588.

**Comment by zenkijoe** [comment]
![hakuneko2](https://user-images.githubusercontent.com/71316571/125080364-ebedca80-e0ee-11eb-98c5-8ecc2c5be27e.png)
![hakuneko](https://user-images.githubusercontent.com/71316571/125080417-f9a35000-e0ee-11eb-95eb-80f53fb466b3.png)

**Comment by zenkijoe** [comment]
this sir
can you give me the new link hakuneko. if there any new version

**Comment by Sheepux** [comment]
get the nightly on the website
