### ISSUE TITLE
[Site Request] Mangatigre

### ISSUE THREAD

**Issue by kamitsukai** [manga-download/hakuneko#3681]
**Name of the website**
Mangatigre

**Website urls (examples below)**
- Site: https://www.mangatigre.com/
- Manga List: https://www.mangatigre.com/mangas
- Manga example: https://www.mangatigre.com/manhwa/solo-leveling
- Chapter online viewer example: https://www.mangatigre.com/manhwa/solo-leveling/158

**Languages**
Spanish

**Comment by MikeZeDev** [comment]
dead?
