### ISSUE TITLE
[Site Request] es.NiAdd

### ISSUE THREAD

**Issue by kamitsukai** [manga-download/hakuneko#3682]
**Name of the website**
es.NiAdd

**Website urls (examples below)**
- Site: https://es.niadd.com/
- Manga List: https://es.niadd.com/category/
- Manga example: https://es.niadd.com/original/10036078.html
- Chapter online viewer example: https://es.niadd.com/chapter/Capitulo_22/100314206/

**Languages**
Spanish

**Comment by 27136773** [comment]
See #816
