### ISSUE TITLE
[ComicWalker] Connector not working

### ISSUE THREAD

**Issue by shionsaionji** [manga-download/hakuneko#3687]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error message says "Failed to fetch" when trying to download or preview

**To Reproduce**
1. Name of connector: ComicWalker
2. Name of manga (if connector update is working): 異世界もふもふカフェ https://comic-walker.com/contents/detail/KDCW_EB03202195010000_68/
3. Name of chapter (if manga update is working): 1
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

`Connector.mjs:460 GET hakuneko://cache/undefined/api/v1/comicwalker/episodes/KDCW_EB03202195010001_68/frames net::ERR_FILE_NOT_FOUND
fetchJSON @ Connector.mjs:460
(anonymous) @ ComicWalker.mjs:80
Promise.then (async)
_getPageList @ ComicWalker.mjs:77
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
onSelectedChapterChanged @ pages.html:269
runObserverEffect @ property-effects.html:217
runEffectsForProperty @ property-effects.html:162
runEffects @ property-effects.html:128
_propertiesChanged @ property-effects.html:1662
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
__enableOrFlushClients @ property-effects.html:1555
_flushClients @ property-effects.html:1530
_propertiesChanged @ property-effects.html:1658
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
runNotifyEffects @ property-effects.html:261
_propertiesChanged @ property-effects.html:1665
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
set @ property-effects.html:1817
onSelectChapterClick @ chapters.html:438
handler @ template-stamp.html:96
(anonymous) @ templatize.html:149
ComicWalker.mjs:87 TypeError: Failed to fetch EventTarget {manga: EventTarget, id: "/viewer/?tw=2&dlcl=ja&cid=KDCW_EB03202195010001_68&bs=1", title: "第1話", file: {…}, language: "", …}file: {name: "第1話", extension: "", full: "第1話"}id: "/viewer/?tw=2&dlcl=ja&cid=KDCW_EB03202195010001_68&bs=1"language: ""manga: EventTarget {connector: ComicWalker, id: "/contents/detail/KDCW_EB03202195010000_68/", title: "異世界もふもふカフェ", status: "available", chapterCache: Array(9), …}pageCache: []pageProcess: falsestatus: "failed"title: "第1話"__proto__: EventTarget
(anonymous) @ ComicWalker.mjs:87
Promise.catch (async)
_getPageList @ ComicWalker.mjs:86
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
onSelectedChapterChanged @ pages.html:269
runObserverEffect @ property-effects.html:217
runEffectsForProperty @ property-effects.html:162
runEffects @ property-effects.html:128
_propertiesChanged @ property-effects.html:1662
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
__enableOrFlushClients @ property-effects.html:1555
_flushClients @ property-effects.html:1530
_propertiesChanged @ property-effects.html:1658
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
runNotifyEffects @ property-effects.html:261
_propertiesChanged @ property-effects.html:1665
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
set @ property-effects.html:1817
onSelectChapterClick @ chapters.html:438
handler @ template-stamp.html:96
(anonymous) @ templatize.html:149
Connector.mjs:460 GET hakuneko://cache/undefined/api/v1/comicwalker/episodes/KDCW_EB03202195010001_68/frames net::ERR_FILE_NOT_FOUND
fetchJSON @ Connector.mjs:460
(anonymous) @ ComicWalker.mjs:80
Promise.then (async)
_getPageList @ ComicWalker.mjs:77
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
ComicWalker.mjs:87 TypeError: Failed to fetch EventTarget {manga: EventTarget, id: "/viewer/?tw=2&dlcl=ja&cid=KDCW_EB03202195010001_68&bs=1", title: "第1話", file: {…}, language: "", …}file: {name: "第1話", extension: "", full: "第1話"}id: "/viewer/?tw=2&dlcl=ja&cid=KDCW_EB03202195010001_68&bs=1"language: ""manga: EventTarget {connector: ComicWalker, id: "/contents/detail/KDCW_EB03202195010000_68/", title: "異世界もふもふカフェ", status: "available", chapterCache: Array(9), …}pageCache: []pageProcess: falsestatus: "failed"title: "第1話"__proto__: EventTarget
(anonymous) @ ComicWalker.mjs:87
Promise.catch (async)
_getPageList @ ComicWalker.mjs:86
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49`
**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![hakuneko_2021-07-09_23-17-02_HakuNeko](https://user-images.githubusercontent.com/87216256/125150188-f9fe1400-e10b-11eb-89e5-d491d2800826.png)

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by Ninoo-chan** [comment]
it doesn't work for me either

**Comment by ghost** [comment]
it doesn't work for me too
![image](https://user-images.githubusercontent.com/77142145/125889039-8d225a5b-40bf-466e-81d3-b6263b28c2b9.png)
