### ISSUE TITLE
Comparison of supported pages with other applications

### ISSUE THREAD

**Issue by DonaldTsang** [manga-download/hakuneko#369]
Note on this list of applications:
1. They are mostly in C#, Python or JS
2. They all have at least 5 supported sites

Large List:
- http://manga-py.yuru-yuri.sttv.me/#resources-list (Python)
- https://github.com/eight04/ComicCrawler#supported-domains (Python)

Smaller List:
- https://github.com/Xonshiz/comic-dl/blob/master/Supported_Sites.md (Python)
- https://github.com/NguyenDanPhuong/MangaRipper#supported-sites (C#)
- https://github.com/blacker-cz/MangaScraper#description (C#)
- https://github.com/andy29485/Manga#websites-that-work (Python)
- https://github.com/MonkAlex/MangaReader#mangareader (C#)
- https://github.com/jneidel/mangareader-dl#supported-sites (JS)
- https://github.com/poketo/poketo#supported-sites (JS)
- https://github.com/Hamuko/cum/wiki/Supported-sites (Python)

**Comment by 27136773** [comment]
The comparison in the wiki has two purposes:

- Show the websites supported in HakuNeko
- Show for which websites favorites can be imported from FMD

I see no need to compare the supported websites with other manga downloaders, especially if they are:

- console applications (probably to run them headless on a scraping server)
- not actively developed
- unpopular

That said, i will gladly accept and publish a comparison with other manga tools if anyone is going to contribute them. A brief comment on how to extract the list of websites in JSON fomat from HakuNeko can be found in [this post](https://github.com/manga-download/hakuneko/issues/370#issuecomment-523477114).

**Comment by 27136773** [comment]
Re-opened so possible contributors can find this issue...

**Comment by DonaldTsang** [comment]
@ronny1982 It would be good to consider adding sites that are on some of "the long list" onto Hakuneko, IF it was not in Hakuneko previously, which is why I provided the list for completeness sake.

If anyone in the comunity would like to add websites to the repo, please consider reading this issue.

**Comment by peylux** [comment]
https://trendmyhome.com/
https://peymanemlak.com/
https://raimand.com/

**Comment by peylux** [comment]
http://peylux.com/
https://edahukuk.com/

**Comment by peylux** [comment]
https://talarweb.net/

**Comment by DonaldTsang** [comment]
@peylux could you explain to me what are you referring to?

**Comment by 27136773** [comment]
No contributor was interested within the last 5 month => closed
