### ISSUE TITLE
[Site Request] novel Ringan

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#3692]
**Name of the website**
Novel Ringan

**Website urls (examples below)**
- Site: https://novelringan.com/
- Manga List: https://novelringan.com/daftar-novel/
- Manga example: https://novelringan.com/series/age-of-adepts/
- Chapter online viewer example: https://novelringan.com/age-of-adepts-chapter-1150/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #3588

**Comment by andillk** [comment]
but sir in my hakuneko they didn't have novelringan yet?
i am using hakuneko lates version for windows. can you please give me a new link or sofware hakuneko

**Comment by andillk** [comment]
![hakuneko](https://user-images.githubusercontent.com/81703465/125196600-b4188b80-e284-11eb-90d9-56e537869045.png)
![hakuneko2](https://user-images.githubusercontent.com/81703465/125196602-b549b880-e284-11eb-98c2-4e9d5344a9e9.png)

**Comment by 27136773** [comment]
Use nightly or wait for changes to be integrated into 6.1.7
