### ISSUE TITLE
[Flame Scans] Connector not working

### ISSUE THREAD

**Issue by korason7117** [manga-download/hakuneko#3693]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the connector seems to be simply outdated

**To Reproduce**
try to load the manga list or copy the manga link/chapter link.

1. Flame Scans
    ID: flamescans-org
    URL: https://flamescans.org

4. reciving an error: Failed to load "https://flamescans.org/" within the given timeout of 60 seconds

 - Version  6.1.7
 - I want to download Peerless Dad D:

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Probably CloudFlare protection due to bad IP/ISP reputation.
Maybe related to #2933

**Comment by Sheepux** [comment]
Cannot be reproduced as well.
Please provide a manga & chapter.

**Comment by korason7117** [comment]
Dunno why, but it is now properly working loading the manga list, chapter list and downloading works as expected
