### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by Albirew** [manga-download/hakuneko#3694]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
 the connector is simply outdated (mangadex reopened since few days with new API is out. see https://api.mangadex.org )

**To Reproduce**
1. Name of connector: MangaDex
~~2. Name of manga (if connector update is working)~~
~~3. Name of chapter (if manga update is working)~~
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
```
Connector.mjs:460 GET https://api.mangadex.org/chapter?limit=100&offset=0&manga=41744 400
fetchJSON @ Connector.mjs:460
[...]
Connector.mjs:598 Error: Failed to receive content from "https://api.mangadex.org/chapter?limit=100&offset=0&manga=41744" (status: 400) - 
    at Connector.mjs:469
    at async MangaDex._getChaptersFromPage (MangaDex.mjs:125)
    at async MangaDex._getChapters (MangaDex.mjs:112)
[...]
Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to receive content from "https://api.mangadex.org/chapter?limit=100&offset=0&manga=41744" (status: 400) - 
    at Connector.mjs:469
    at async MangaDex._getChaptersFromPage (MangaDex.mjs:125)
    at async MangaDex._getChapters (MangaDex.mjs:112)
    at async MangaDex._getChapterList (Connector.mjs:595)
[...]
Connector.mjs:460 Fetch failed loading: GET "https://api.mangadex.org/chapter?limit=100&offset=0&manga=41744".
```

~~**Screenshots**~~
~~If complex to describe, add screenshots to help explain your problem.~~

**HakuNeko (please complete the following information):**
 - Version 6.17

**Misc**
I believe you already know it and may even be already working on it. An issue for this is still fine, tho. =)
@everyone: Following this issue using notification subscription and seeing when it gets closed is a fine way to know when mangadex connector will be fixed.

**Comment by 27136773** [comment]
Since there are basically no steps to reproduce, i assume this was a request from a bookmarked manga.
Re-add your bookmarks or [migrate](https://github.com/manga-download/hakuneko-userland) them.

**Comment by Albirew** [comment]
oh, my bad. Thanks you!
if more idiots like me create useless issues like this, maybe you should consider making a pinned issue "concerning mangadex v5" or something...
