### ISSUE TITLE
[TruyenChon] Connector not working

### ISSUE THREAD

**Issue by thiennhing** [manga-download/hakuneko#3696]
Did you read the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
The connector http://truyenchon.com/ is not working anymore.
Can you fix this? 
Thank you <3

Version 6.1.7.

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Provide sample manga / chapter.
Provide detailed steps to reproduce.
If possible provide error/network output from developer tools (F12).

**Comment by MikeZeDev** [comment]
Dead website i guess.
