### ISSUE TITLE
Reaper Scans

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#3697]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

The site just merged with another site, so the problem is most likely tied to the site reformatting. Refreshing the connector empties out existing titles so zero titles and chapters. The site, itself works properly.

**To Reproduce**
1. Name of connector.   Reaper Scan
2. Name of manga (if connector update is working).   All
3. Name of chapter (if manga update is working).       All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

<img width="1124" alt="Screen Shot 2021-07-12 at 12 30 52 PM" src="https://user-images.githubusercontent.com/70929406/125345202-19b05a80-e30d-11eb-8e06-bc43201ddd07.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by tsentered** [comment]
A little update. As of today the site is having issues. I'll make another update when things change.

**Comment by tsentered** [comment]
Sorry, accidentally closed but the site as of today is having issues.

**Comment by 27136773** [comment]
Website changed template from `Genkan` to `WordPressMadara`

**Comment by tsentered** [comment]
Site is up and running again.

**Comment by tsentered** [comment]
Thank you.
