### ISSUE TITLE
Seperation between manga and anime in Wiki

### ISSUE THREAD

**Issue by DonaldTsang** [manga-download/hakuneko#370]
See https://github.com/manga-download/hakuneko/wiki/Comparison
(the mixing between anime and manga would lead to confusion for those that implement similar apps)

**Comment by 27136773** [comment]
The purpose of this (automatic generated) comparison is to simply list all websites that are supported in HakuNeko and which of them can be imported from FMD favorites. The type (anime, manga, webtoon, hentai, ...) is not taken into consideration and i would like to avoid spending much time to develope the auto generator for this document any further.

HakuNeko itself already provides a list of all supported websites and a sophisticated search to filter the list.

It is also possible to dump the list from within HakuNeko's developer tools console by running a script such as:

```javascript
let dump = Engine.Connectors.map( c => {
    return {
        id: c.id,
        label: c.label,
        website: c.url,
        tags: c.tags
    };
} )
.filter( c => c.website )
.sort( ( a, b ) => {
    return ( a.website.toLowerCase() < b.website.toLowerCase() ? -1 : 1 );
} );
JSON.stringify( dump, null, 2 );
```
Source: [wiki/comparison/README.txt](https://raw.githubusercontent.com/wiki/manga-download/hakuneko/comparison/README.txt)

**Comment by 27136773** [comment]
Re-opened in case a possible contributor would take the time and provide such a list...

**Comment by DonaldTsang** [comment]
The table would be used in https://github.com/yuru-yuri/manga-py/issues/211 and https://github.com/eight04/ComicCrawler/issues/217 to cover more websites

**Comment by s510** [comment]
Duplicate of #

**Comment by 27136773** [comment]
No contributor was interested within the last 5 month => closed

**Comment by s510** [comment]
Vào 20:14, CN, 2 thg 2, 2020 ronny1982 <notifications@github.com> đã viết:

**Comment by s510** [comment]
Vào 20:14, CN, 2 thg 2, 2020 ronny1982 <notifications@github.com> đã viết:
