### ISSUE TITLE
[UnionMangas] Ghost chapters

### ISSUE THREAD

**Issue by TrickOC** [manga-download/hakuneko#3700]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Duplicate ghost chapters in all mangas.

**To Reproduce**
1. UnionMangas
2. In any manga
3. Ghost chapter
4. There was no content found for ", make sure it is accessible (login, purchase, ...)!

**Screenshots**
![image](https://user-images.githubusercontent.com/32719215/125523935-7459b2e4-c99a-4aef-b930-539615eb7398.png)
![image](https://user-images.githubusercontent.com/32719215/125524145-3cb54a2e-0999-4c25-b1ff-edb7f513fd28.png)

**HakuNeko (please complete the following information):**
 - Version 8.3.4 windows / master@0f805b

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
All chapters shown correctly for `One Piece`.
Chapters that cannot show images in HakuNeko, also fail on the website itself.

If there is a chapter that correctly shows images on the website but not in HakuNeko, please provide manga / chapter.

**Comment by Sheepux** [comment]
Cannot be reproduced as well for one piece.

**Comment by 27136773** [comment]
Not reproducible => closed
