### ISSUE TITLE
[Site Request] Mangakakalot

### ISSUE THREAD

**Issue by Yato-o** [manga-download/hakuneko#3701]
Mangakakalot

- Site: https://mangakakalot.com/
- Manga List: https://mangakakalot.com/manga_list?type=latest&category=all&state=all&page=1
- Manga example: https://mangakakalot.com/search/story/one_piece
- Chapter online viewer example: https://readmanganato.com/manga-jn986670/chapter-763

English, Japanese

Why You Should Read Manga Online at Mangakakalot.com ?

There are many reasons you should read Manga online, and if you are a fan of this unique storytelling style then learning about them is a must. One of the biggest reasons why you should read Manga online is the money it can save you. While there's nothing like actually holding a book in your hands, there's also no denying that the cost of those books can add up quickly. So why not join the digital age and read Manga online? Another big reason to read Manga online is the huge amount of material that is available. When you go to a comic store or other book store their shelves are limited by the space that they have. When you go to an online site to read Manga those limitations don't exist. So if you want the best selection and you also want to save money then reading Manga online should be an obvious choice for you

©2016 Mangakakalot.com, all rights reserved. Top speed, completely free.

**Comment by 27136773** [comment]
Already supported, please check before requesting websites
