### ISSUE TITLE
[Site Request] 8MUSES

### ISSUE THREAD

**Issue by zasfan** [manga-download/hakuneko#3702]
**Name of the website**
8MUSES

**Website urls (examples below)**
- Site: https://8muses.net/
- Manga List: https://8muses.net/
- Manga example: https://8muses.net/album/MilfToon-Comics/The-Milftoons
- Chapter online viewer example: https://8muses.net/picture/MilfToon-Comics/The-Milftoons/Issue-1/1
**Languages**
ENGLISH

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Already supported as `comics.8muses.com`
