### ISSUE TITLE
[Feature] There should be options to pause, resume and cancel the downloading chapters and also there should also be an option to manually choose the number of chapters to be downloaded. 

### ISSUE THREAD

**Issue by eldoeta** [manga-download/hakuneko#3703]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
See #8
