### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by denisbrunom** [manga-download/hakuneko#3704]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site changed url from .net to .com. Manga list appears, but not the chapters.

**To Reproduce**
1. Neox Scanlator
2. any manga
3. chapter no appears
4. Failed to load resource: the server responded with a status of 403 ()

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Domain changed from `.net` to `.com`
