### ISSUE TITLE
[Bug] Feiled to update manga list for [Gmanga]

### ISSUE THREAD

**Issue by Dr-Shiro** [manga-download/hakuneko#3705]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When I update the manga list I get this error "feiled to update manga list for Gmanga"

**To Reproduce**
1. Go to 'Gmanga'
2. Click on 'synchronize local manga list'
3. See error

**Screenshots**
![](https://i.imgur.com/O9GThIc.png)

**Context (please complete the following information):**
windows server 2019

**Comment by 27136773** [comment]
Caused by #2933
