### ISSUE TITLE
[Site Request] mangas.io

### ISSUE THREAD

**Issue by ounsen** [manga-download/hakuneko#3707]
**Name of the website**

mangas.io

**Website urls (examples below)**
- Site: https://www.mangas.io/
- Manga List: https://www.mangas.io/manga-en-ligne
- Manga example: https://www.mangas.io/lire/old-boy
- Chapter online viewer example: https://www.mangas.io/lire/old-boy/1/1

**Languages**
French

**Website relationship*
No

**Additional details**
Site is growing

**Comment by Ever4engel** [comment]
duplicate #4344

**Comment by ounsen** [comment]
? je l'ai posté avant

**Comment by MikeZeDev** [comment]
I am closing this one and leave the other opened, because the duplicate message will make it pop if i look for "duplicate" ;D
