### ISSUE TITLE
[Site Request] otakuscan.net

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#3708]
**Name of the website**
otakuscan

**Website urls (examples below)**
- Site: https://otakuscan.net/
- 
- Comic List= https://otakuscan.net/Manga
- Manga List= https://otakuscan.net/Manga/Manga
- Manhwa List= https://otakuscan.net/Manga/Manhwa
- Manhua List= https://otakusan.net/Manga/Manhua

**Languages**
JP / RAW  / EN

**Comment by MikeZeDev** [comment]
404 not found. @Sheepux pls

**Comment by Sheepux** [comment]
website probably dead
