### ISSUE TITLE
[All Website Novel] Connector not working

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#3710]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't download and preview in novel website.

**To Reproduce**
All website for novel

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17 and 8.3.4

**Comment by 27136773** [comment]
Rejected, there isn't any information to locate the problem...
- website?
- manga/novel?
- chapter?
