### ISSUE TITLE
[Site Request] KakaoPage

### ISSUE THREAD

**Issue by itsgraxiabibi** [manga-download/hakuneko#3711]
**Name of the website**
KAKAO PAGE

**Website urls (examples below)**
- Site: https://page.kakao.com
- Manga List: https://page.kakao.com/main?categoryUid=11&subCategoryUid=1101
- Manga example: https://page.kakao.com/home?seriesId=57438962
- Chapter online viewer example: https://page.kakao.com/viewer?productId=57474624

**Languages**
KR

**Website relationship*
NA

**Additional details**
NA

**Comment by 27136773** [comment]
Already supported. Check before making a website request.
