### ISSUE TITLE
[NEOXSCANLATOR] Connector not working

### ISSUE THREAD

**Issue by PaulWalker1457** [manga-download/hakuneko#3713]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't download and preview in neoscanlator. problably because of the domain change in the site.

**To Reproduce**
1. Name of connector neoxscans.net

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See: #3704
