### ISSUE TITLE
[Site Request] Mangasee

### ISSUE THREAD

**Issue by randoomdude** [manga-download/hakuneko#3724]
**Name of the website**
Mangasee

- Site: https://mangasee123.com/
- Manga List: https://mangasee123.com/directory/
- Manga example: https://mangasee123.com/manga/Dragon-Ball-Super
- Chapter online viewer example: https://mangasee123.com/read-online/Dragon-Ball-Super-chapter-42-page-1.html

**Languages**
English

**Website relationship*
None

**Additional details**
None

**Comment by 27136773** [comment]
Already supported, please check before creating ticket
