### ISSUE TITLE
[Site Request] dynasty-scans

### ISSUE THREAD

**Issue by randoomdude** [manga-download/hakuneko#3725]
**Name of the website**
dynasty-scans

**Website urls (examples below)**
- Site: https://dynasty-scans.com/
- Manga List: https://dynasty-scans.com/series
- Manga example: https://dynasty-scans.com/series/yuri_sm_de_futari_no_kimochi_wa_tsunagarimasu_ka
- Chapter online viewer example: https://dynasty-scans.com/chapters/yuri_sm_de_futari_no_kimochi_wa_tsunagarimasu_ka_ch01#1

**Languages**
English

**Website relationship*
None

**Additional details**
None

**Comment by 27136773** [comment]
Already supported, please check before creating ticket
