### ISSUE TITLE
[Site Request] mangaowl

### ISSUE THREAD

**Issue by Jenniees** [manga-download/hakuneko#3732]
**Name of the website**
mangaowl

**Website urls (examples below)**
- Site: https://www.mangaowl.net/
- Manga List: https://www.mangaowl.net/shared_list
- Manga example: https://www.mangaowl.net/single/70605/this-witch-of-mine
- Chapter online viewer example: https://mostraveller.com/what-to-do-in-ninh-binh-near-hanoi-vietnam?utm_source=google&utm_medium=organic

**Languages**
ENG

**Website relationship*
No

**Additional details**
Thanks !

**Comment by 27136773** [comment]
See #2335
