### ISSUE TITLE
[Kakaopage] Connector not working

### ISSUE THREAD

**Issue by Pierre-Monier** [manga-download/hakuneko#3733]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

Someone points out this bug on discord. The connector isn't able to fetch manga. I'm working on it in my spare time, but I wanted to make an issue out of this.

**A clear and concise description of what the bug is.**

The connector can't get manga because we are getting the title with a CSS selector, which isn't the correct one anymore. I change the CSS selector for `let data = await this.fetchDOM(request, 'h2.text-ellipsis', 3);` before it was `let data = await this.fetchDOM(request, 'h2.text-ellipsis'.web-font, 3);`. 

But now for some webtoon we have this response when fetching images
![image](https://user-images.githubusercontent.com/65488471/126072166-1fb0e769-ce09-4d81-bbf2-b55af16c4872.png)
 The Korean message says ~ 'Need to purchase'

This [webtoon](https://page.kakao.com/home?seriesId=54727849) for example is having this issue 
But it's working fine with [this one,](https://page.kakao.com/home?seriesId=57268828) for example.

**To Reproduce**

1. Change the CSS selector
As I show before.
2. Name of connector
Kakaopage
3. Name of manga (if connector update is working)
Doesn't work with [this one,](https://page.kakao.com/home?seriesId=54727849) for example (there are others...)
Works with [this one](https://page.kakao.com/home?seriesId=54727849)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://user-images.githubusercontent.com/65488471/126072166-1fb0e769-ce09-4d81-bbf2-b55af16c4872.png)

**HakuNeko (please complete the following information):**
I'm in dev mode, running the app with `npm start:dev`, the version is `matser@HEAD`

**Comment by 27136773** [comment]
From a WIP stash of my fork:
It's probably incomplete, but i don't remember where i was going to continue work.

----
![image](https://user-images.githubusercontent.com/27136773/126074476-1ae2cdf3-9dde-467c-adb3-db62d9d470b7.png)

----

![image](https://user-images.githubusercontent.com/27136773/126074506-2dc7ec24-263f-4eaa-b1ff-02d9ebf2a2cf.png)

**Comment by Pierre-Monier** [comment]
I can start a PR with these changes if you want, but there is more work to do

**Comment by 27136773** [comment]
No need to make a PR if not complete, but feel free to continue working on this

**Comment by MikeZeDev** [comment]
I updated the thing for the new api but i dont know how to handle not purchased stuff properly. At least it works
