### ISSUE TITLE
[vizshonenjump] Connector not working

### ISSUE THREAD

**Issue by ccx2** [manga-download/hakuneko#3737]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapter 3 of the series Choujin X can not be downloaded. Checking the chapter in the Hakuneko viewer shows the last page as blank. Checking the chapter in the browser, it shows 403 errors for page 34. The chapter itself ends on page 33.
Please note that the chapter will be available to people without an account for two or three more weeks.

**To Reproduce**
1. Name of connector: vizshonenjump
2. Name of manga: Choujin X
3. Name of chapter: Ch. 3
4. Error 1 (Ids removed because I'm paranoid and doubt they're relevant):
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>Id1</RequestId><HostId>Id2</HostId></Error>`

Error 2:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>Id3</RequestId><HostId>Id4</HostId></Error>`

Error 3:
`<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access denied</Message></Error>`

**HakuNeko (please complete the following information):**
 - Version: 6.17@cad181

**Comment by 27136773** [comment]
This is a server side problem, i recommend to report it to the website admin.
HakuNeko cannot download images that don't even work in the browser.
Ignoring failed image downloads may result in incomplete chapters.

You may grab the image links manually from the network tab and download them with a downloader or one by one, skipping the broken ones.
