### ISSUE TITLE
[Site Request] MangaLandia (Spanish)

### ISSUE THREAD

**Issue by Britooo09** [manga-download/hakuneko#3738]
**Name of the website**
MangaLandia

**Website URLs**
- Site: https://mangalandia.com/
- Manga List: https://mangalandia.com/explorar
- Manga example: https://mangalandia.com/manga/23719
- Chapter online viewer example: https://mangalandia.com/capitulo/568056

**Languages**
Spanish (Español).

**Website relationship**
None.

**Comment by MikeZeDev** [comment]
Recaptcha bot verification :/

**Comment by Lenoyr** [comment]
Website is dead
