### ISSUE TITLE
[Site Request] TuMangaNet (Spanish)

### ISSUE THREAD

**Issue by Britooo09** [manga-download/hakuneko#3739]
**Name of the website**
TuMangaNet

**Website URLs**
- Site: https://tumanga.net/
- Manga List: https://tumanga.net/?s=&post_type=wp-manga
- Manga example: https://tumanga.net/manga/jujutsu-kaisen/
- Chapter online viewer example: https://tumanga.net/manga/jujutsu-kaisen/capitulo-151-00-totalmente-preparada-parte-4-el-club-de-askin/

**Languages**
Spanish (Español).

**Website relationship**
None.

**Additional details**
In the web, the top search button doesn't work. The search must be performed with the icon on the right side.

**Comment by 27136773** [comment]
Already supported, please check before making a new request

**Comment by Britooo09** [comment]
Oh! I'm so sorry. I thought I posted this on FMD2 😫
