### ISSUE TITLE
Comick.fun

### ISSUE THREAD

**Issue by RespectfulManga** [manga-download/hakuneko#3742]
All the manga available on the website are not available on hakuneko..please look into the issue

**Comment by Sheepux** [comment]
The connector is using the "lastest updates" api of the website to find titles, there is probably a limitation where some mangas don't appear (very old ones?).
Would you be so kind as to mention the desired titles as requested in the issue template ?

Dev note: could use the  search api with genres filtering ?
https://comick.fun/api/search?genres=&excludes=&tags=&demographic=&limit=50&page=8&country=&sort=follow

**Comment by 27136773** [comment]
Cannot be reproduced, website shows [2450 entries](https://comick.fun/search?q=) and HakuNeko shows 2527.

Since there was no further response what is missing, it is unreasonable to let the maintainers search for the needle in the haystack => closed
