### ISSUE TITLE
[comick.fun] Connector not working

### ISSUE THREAD

**Issue by RespectfulManga** [manga-download/hakuneko#3744]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**All the manga available on comick.fun is not available in the hakuneko comick.fun manga list**

**To Reproduce**
1. comick.fun
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
No reason to create multiple tickets #3742

**Comment by RespectfulManga** [comment]
i created multiple tickets because you guys did not even respond to the
first ticket

**Comment by Sheepux** [comment]
Your ticket was created less than 1 day ago, you'll get a response when someone will take care of it.
This is community support, there is no guaranted delay.

**Comment by RespectfulManga** [comment]
Thank you!
