### ISSUE TITLE
[Site Request] KomikSpot

### ISSUE THREAD

**Issue by MarqFJA87** [manga-download/hakuneko#3748]
**Name of the website**
KomikSpot

**Website urls (examples below)**
- Site: https://komikspot.com/
- Manga List: https://komikspot.com/komiks
- Manga example: https://komikspot.com/komiks/quantum-festival/
- Chapter online viewer example: https://komikspot.com/episode/18076/

**Languages**
English

**Website relationship**
N/A

**Additional details**
N/A

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by MarqFJA87** [comment]
Yeah. I don't know what exactly led to it dying off, but I guess that saves the effort of doing this task.
