### ISSUE TITLE
[Site Request] hentailib.me

### ISSUE THREAD

**Issue by imKota** [manga-download/hakuneko#3755]
**Name of the website**
hentailib

**Website urls (examples below)**
- Site: https://hentailib.me/
- Manga List: https://hentailib.me/manga-list?types[]=1
- Manga example: https://hentailib.me/kimi-wa-midara-na-boku-no-joou?section=chapters
- Chapter online viewer example: https://hentailib.me/kimi-wa-midara-na-boku-no-joou/v1/c1?page=1

**Languages**
Russian

**Website relationship**
mangalib.me

**Additional details**
N/A

**Comment by 27136773** [comment]
Since they are using CloudFlare right now which is bugged #2933 , there is not much motivation to add support right now...

**Comment by MikeZeDev** [comment]
On real browser cloudflare check passed BUT it lead to a 404 page anyway. Dead website . @Sheepux please.

**Comment by Sheepux** [comment]
same
