### ISSUE TITLE
[Bug] MangaJar

### ISSUE THREAD

**Issue by mwehehehe** [manga-download/hakuneko#3758]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
https://mangajar.com/manga/clover-hirakawa-tetsuhiro

the website has from chapter 1 to 400 but you have to scroll down so you got full chapters from 400 to 1
but in the app it won't load full chapter and it's only has 352 to 400

**Context (please complete the following information):**
 - OS: W10
 - HakuNeko Version [6.17]

**Comment by Sheepux** [comment]
Introduced chapter pagination (PR review within the week)
