### ISSUE TITLE
[Bug] Cannot view/download a particular chapter from CatManga

### ISSUE THREAD

**Issue by MarqFJA87** [manga-download/hakuneko#3759]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I am unable to view or download Chapter 23 of Getsuyoubi no Tawawa (Blue) from CatManga.org; I keep getting the error message "TypeError: Cannot read property 'length' of undefined". The chapter and others from the same manga and other ones can be viewed without problems on the site, and I've downloaded another chapter from the site shortly beforehand without incident.

**To Reproduce**
1. Start HakuNeko.
2. Choose CatManga from the Manga List.
3. Choose Getsuyoubi no Tawawa (Blue).
4. View/Download Ch. 23 from the chapter list.

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 6.1.7

EDIT: Okay, just now I tried again, and whatever it is that was causing the problem mysteriously vanished. I still want to understand what the error message that I got means, though.

**Comment by Sheepux** [comment]
Cannot be reproduced as well (was probably a temporary issue on the website/internet acess). Closing (user request)

The message just meant that the code wasn't able to acess a property it was looking for, probably the length of an array that was the expected pagelist.
