### ISSUE TITLE
[Lezhin (English)] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#3760]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Fails to download paid chapters 

**To Reproduce**
1. Lezhin (english)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Handled by #2950
