### ISSUE TITLE
[Site Request] Meganebuk

### ISSUE THREAD

**Issue by kari-basi** [manga-download/hakuneko#3761]
**Meganebuk**
Meganebuk

**Website urls**
- Site: https://www.meganebuk.net/
- Manga List: https://www.meganebuk.net/daftar-komik/
- Manga example: https://www.meganebuk.net/edens-zero-bahasa-indonesia/

**Languages**
Indonesian

**Comment by 27136773** [comment]
Website has no online reader, only download links of `zip` archives.
HakuNeko is not implemented to support chapters in archive formats.
