### ISSUE TITLE
[MangaSehri] Connector not working

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#3763]
it gives 1 page 404 in every chapter of all manga...
that's why hakuneko can't download episodes.
I have attached the gif and the image, can you please fix the error thanks I love you: offline reading ♥

https://prnt.sc/1h0r2cr    // gif
https://prnt.sc/1h0r4ky   // png

**Comment by Sheepux** [comment]
Cannot access the website. It probably requires a VPN to solve this. I'll let the other contributors on this case.
Thanks for the details it helps a lot.
