### ISSUE TITLE
[Site Request] CrunchyScan

### ISSUE THREAD

**Issue by NameLess0974** [manga-download/hakuneko#3766]
**Name of the website**
CrunchyScan

**Website urls (examples below)**
- Site: https://crunchyscan.fr/
- Manga List: https://crunchyscan.fr/liste-manga
- Manga example: https://crunchyscan.fr/liste-manga/tomb-raider-king
- Chapter online viewer example: https://crunchyscan.fr/liste-manga/tomb-raider-king/chapitre-115 or https://crunchyscan.fr/liste-manga/the-descent-of-the-demonic-master/chapitre-62?style=paged

**Languages**
French

**Website relationship*
N/A

**Additional details**
N/A

**Comment by 27136773** [comment]
Template: WordPressMadara

**Comment by V0IDgit** [comment]
Here is the basic code, since it's madara-based:

```mjs
import WordPressMadara from './templates/WordPressMadara.mjs';

export default class Crunchyscan extends WordPressMadara {

    constructor() {
        super();
        super.id = 'crunchyscan';
        super.label = 'Crunchyscan';
        this.tags = [ 'manga', 'webtoons', 'french' ];
        this.url = 'https://crunchyscan.fr';

    }

}

```

But, after doing this, everything works fine, except the file downloading.
I think the captcha on the website before __**every**__ chapter is blocking downloads.
We discussed about it on the discord.
