### ISSUE TITLE
[CocoManhua] image not load

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#3768]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't load the image

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![1](https://user-images.githubusercontent.com/77179150/127757521-19d18cc8-c82f-46be-872a-29142888e332.jpg)
![2](https://user-images.githubusercontent.com/77179150/127757524-c584ff71-a93e-41a5-80fe-5d3a818ad0f0.jpg)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Yusei-StarDust** [comment]
the website address switched to https://www.cocomanga.com/ now...

**Comment by 27136773** [comment]
> the website address switched to https://www.cocomanga.com/ now...

This ticket is closed, you have to create a new one
