### ISSUE TITLE
[Feature]: readme in folders

### ISSUE THREAD

**Issue by kate14black** [manga-download/hakuneko#3774]
**Describe the solution you'd like**
I'd like a readme inside the folder so on hakuneko I can select folders that hakuneko already downloaded so I can check new chapter really fast.
For example, the url is inside the read me and if I select the folder, it check the url inside the read me so I can download new chapter If I see them.

**Describe alternatives you've considered**
If doing the folder selection is difficult, then just the url in the readme so I can copy paste it in the clipboard connector.

**Context (please complete the following information):**
 - HakuNeko 2021 rev. 6.1.7@cad181

**Comment by 27136773** [comment]
Could be an alternative approach to implement #653
Handled by #653
