### ISSUE TITLE
Cmoa.jp

### ISSUE THREAD

**Issue by YuzzuUzzzu** [manga-download/hakuneko#3776]
**Name of the website**
Cmoa.jp

**Website urls (examples below)**
- Site: https://www.cmoa.jp/
- Manga List: I would like to get my library in there using a username and password.

**Languages**
Japanese

**Website relationship*
I'm not sure. I don't think they have one. 

**Additional details**
Na.

**Comment by manh21** [comment]
Duplicate
see: #2307
