### ISSUE TITLE
[CocoManhua] Connector not working

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#3777]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloading from the connector returns a 403

**To Reproduce**
1. cocomanhua.com
2. 虎x鹤 妖师录
3. 第411话 湮灭
4. DownloadJob.mjs:145 Error: Page "https://img.cocomanhua.com/comic/12586/Tys0WnF0d2lJZWF5NkRhRVdtZ3grQlRiZzlzR1hyL3ZuS1lCMnhWRStzRT0=/0001.jpg" returned status: 403 - 
    at DownloadJob.mjs:121
    at async Promise.all (index 0) 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate, see #3768
