### ISSUE TITLE
[Site Request] niadd

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#3781]
**Name of the website**
niadd

**Website urls (examples below)**
- Site: https://es.niadd.com/
- Manga List: https: https://es.niadd.com/category/
- Manga example: https://es.niadd.com/original/10027709/chapters.html
- Chapter online viewer example: https://es.niadd.com/chapter/Capitulo_1/100221633/

**Languages**
Spanish, English.

**Website relationship*
-

**Additional details**
-

**Comment by 27136773** [comment]
See #816
