### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by Zehra** [manga-download/hakuneko#3783]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapters unable to be downloaded, manga list does not update.  Manga may be partially previewed. Items which load appear to be from cache, as image links appear to be `blob:` objects when viewed in the web browser. (Browser used in test is Firefox.)

**To Reproduce**
1.  **MangaDex** is selected as connector.
2. Any manga series. (Selected/added by copy paste.) **N/A**
3. Any chapter, amount in preview varies.(Seems to do with cache.) **N/A**
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Error messages are mostly within the following format:
`Failed to load resource: net::ERR_CONNECTION_RESET` on connections to `s2.mangadex`. (Probably applies or will soon apply to all items in `this.serverNetwork` within `MangaDex.mjs`)
`Failed to load resource: net::ERR_NOT_IMPLEMENTED` on `connector://mangadex`
`TypeError: Failed to fetch` on `mjs/engine/DownloadJob.mjs`

**Screenshots**
If complex to describe, add screenshots to help explain your problem. **N/A**

**HakuNeko (please complete the following information):**
 - Version [6.17@cad1.8.1]

**Comment by 27136773** [comment]
Hardly reproducible, it seems the `HTTP2_PROTOCOL_ERROR` is not correctly caught with fetch API and responds with status `200 OK`. Added some checks, but not sure if they will do the trick ...

Workaround: retry the downloads that failed

**Comment by potato899** [comment]
I have issues too with Mangadex. Of all the bookmarks I have only one works, all the others fail to download anything.
 
![01](https://user-images.githubusercontent.com/80602782/128692956-04822ce9-e6a8-4593-9e68-a64b495a42c6.jpg)
