### ISSUE TITLE
[IsekaiScan] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#3785]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Don´t load any chapters of this conector

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
> **Is the website of the connector working properly / are you able to see the manga within your browser**
> Yes

This is not true from my end. The website is completely broken and returns an rss feed (mime type: `application/rss+xml`)

**Comment by rausina** [comment]
> > **Is the website of the connector working properly / are you able to see the manga within your browser**
> > Yes
> 
> This is not true from my end. The website is completely broken and returns an rss feed (mime type: `application/rss+xml`)

When I wrote the ticked the web was working perfectly, but since yesterday it was giving problems and today they are under maintenance. Sorry for the inconvenience.

**Comment by 27136773** [comment]
Can be fixed by updating the WordPressMadara template, however they enabled CloudFlare protection and therefore it will not work with HakuNeko anyways
