### ISSUE TITLE
Removal Request for [WEBSITE]

### ISSUE THREAD

**Issue by bruuhh69** [manga-download/hakuneko#3786]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Which website should be removed?
mangalandarabic.com
Why should this website be removed from HakuNeko?
the cpu usage of the server is going crazy for no reason and i think its related to this?

#### In case of Traffic
1. How much traffic is caused by HakuNeko?
i dont know
2. How much is it compared to overall traffic (percentage)?
idk too..
3. How did you measure those analytics (framework)?
bruh... wth
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
long story short im not an expert but haku is the only possible cuz of the high cpu usage i think
5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
yes

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
[YOUR ANSWER HERE]
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
[YOUR ANSWER HERE]
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
[YOUR ANSWER HERE]

#### In case of Monetization
1. Are you using Donations?
[YOUR ANSWER HERE]
2. Are you using Advertisements?
[YOUR ANSWER HERE]

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
Please check your server for potentially viruses or other processes that may consume too much processing power (try e.g. `top` or `htop`).

HakuNeko technically makes the same requests as a web browser, therefore it is affecting the hardware capabilities in the same way no less no more.

=> Rejected as invalid for now, as there is no proof of HakuNeko causing high CPU usage on the target system
