### ISSUE TITLE
[Toonkor] Connector not working

### ISSUE THREAD

**Issue by jollycooperation33** [manga-download/hakuneko#3796]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**

Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**

Yes - the site URL in HakuNeko is tkor.zone, but I believe the site changes it's domain regularly and usually HakuNeko does not seem to have issues with rerouting and connecting successfully. Right now the domain is tkor.green, but HakuNeko is unable to connect. The same behavior is occurring with Chrome browser - usually when typing tkor.zone or tkor.tel or some other domain, it is able to reroute to the new, updated domain (currently tkor.green). But now, the browser does not reroute to the updated domain and times out, and I need to directly type in tkor.green to access the website. 

**Describe the bug**

Click the field under Manga List and search for and select Toonkor. The titles in the site will display below, but when you select any title, the chapters will not display. The icon next to "Chapters:" will spin and then stop, but nothing will have changed. If you then hit the refresh icon next to the website field, the below error will display:

"Failed to update manga list for Toonkor

Failed to load "https://tkor.zone/" within the given timeout of 60 seconds!"

The error message in the console log was:

"mjs/connectors/templates/GnuBoard5BootstrapBasic2.mjs:53 Failed to retrieve data from Twitter API! TypeError: Cannot read property 'entities' of undefined
    at TwitterAPI.getProfileURL (mjs/connectors/templates/GnuBoard5BootstrapBasic2.mjs:38)
    at async Toonkor._initializeConnector (mjs/connectors/Toonkor.mjs:18)
    at async Toonkor.initialize (mjs/engine/Connector.mjs:65)
getProfileURL @ mjs/connectors/templates/GnuBoard5BootstrapBasic2.mjs:53"

I believe HakuNeko is experiencing the same issue of being unable to reroute to the new domain that I observed with my browser. I tried inputting the new URL using the Clipboard function and it didn't seem to work. The error message in the console log was: 

"ClipboardConnector.mjs:66 CLIPBOARD: https://tkor.green/ Error: Failed to load "https://tkor.zone/" within the given timeout of 60 seconds!
    at Request.mjs:371"

**To Reproduce**
1. Name of connector: Toonkor (tkor.zone)
2. Name of manga (if connector update is working): None of the titles will display chapters when clicking on them
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
I am using version 6.1.7. Thank you.

**Comment by MikeZeDev** [comment]
Dead website. parking page. @Sheepux please.

**Comment by Sheepux** [comment]
dynamic domain can possibly be found via https://t.me/s/new_toonkor

**Comment by MikeZeDev** [comment]
We get url from telegram now, shoudl be fixed
