### ISSUE TITLE
[ComicK] Connector not working

### ISSUE THREAD

**Issue by ToManyTickets** [manga-download/hakuneko#3799]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapter list is loading fine, but chapters themselves are unable to be downloaded / previewed. 

**To Reproduce**
1. ComicK
2. Chainsaw Man
3. All chapters
4. F12 gives `TypeError: Cannot read property 'md_images' of undefined`
 `at ComicK._getPages (mjs/connectors/ComicK.mjs:86)`
 `at async ComicK._getPageList (mjs/engine/Connector.mjs:615) EventTarget`

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Nightly build rev. master@59ea94

**Comment by MikeZeDev** [comment]
Tried a random Chainsawman chapter, preview and download works. Nightly.

can be closed maybe? @Sheepux pls

**Comment by Sheepux** [comment]
same
