### ISSUE TITLE
[komiktap.in] Connector not working

### ISSUE THREAD

**Issue by dengole899** [manga-download/hakuneko#3802]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
can't update the manga list, only the old ones. 

**To Reproduce**
1. KomikTap

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced, list updates correctly on my end.
Please provide more detail / samples...

**Comment by MikeZeDev** [comment]
Cannot reproduce too. Update manga list works fine. I got a "must be purchased" message on a manga, another preview and download fine.

Can be closed i guess @Sheepux please (and we have a pr anyway)
