### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by Satougg4** [manga-download/hakuneko#3805]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapter Download fails

**To Reproduce**
1. Mangadex
2. Download manga chapter from list (click cloud in results)
TypeError: failed to fetch
Console log attached. [cache-1628657837807.log](https://github.com/manga-download/hakuneko/files/6966019/cache-1628657837807.log)

**~~Screenshots~~**

**HakuNeko (please complete the following information):**
 - 6.1.7@cad181

**Other**
OS: Win 10 Home-1909 build 18363.1198
HakuNeko Client Version: 6.1.7@cad181
Rev number: see above
Not working: Mangadex.org
Settings related to issue: ? Chapter File Format = Folder with Images...
What's not working: Download manga chapter from list (click cloud in results)

**Comment by Zehra** [comment]
It probably should be fixed in the next update. #3783 
(Although I'm not sure, just FYI for anyone who is reading this.)

**Comment by 27136773** [comment]
Your MangaDex bookmarks are pre v5, so they using an outdated ID.
[Migrate your bookmarks](https://github.com/manga-download/hakuneko-userland/tree/master/bookmark-migration-mangadex-v5) and then try again, if the problem persist create a new ticket

**Comment by Satougg4** [comment]
No they aren't.
