### ISSUE TITLE
Not connecting to HeavenManga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#381]
> **From:** legion1978

It wont load any manga from HeavenManga, but it does from others. site is active and manga can be read over there.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Can be reproduced.
It seems the page links are no longer int he options, but available as array variable in the page.
e.g. view-source:http://heavenmanga.com/s/dragon-slayer-scans/game-obu-familia-family-senki/13/1
