### ISSUE TITLE
[Mangalib] Connector not working

### ISSUE THREAD

**Issue by panchenko9b** [manga-download/hakuneko#3812]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can not download manga from Mangalib. I got error (Error: Page "here I have pretty long URL address" returned status: 404 -)

**To Reproduce**
1. Mangalib.me
2. I have tried some mangas - all with the same error

**HakuNeko (please complete the following information):**
 - Version [6.1.7]

**Comment by 27136773** [comment]
See #2933
