### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by Satougg4** [manga-download/hakuneko#3813]
**Did you migrate to MangaDex v5?**
Yes

**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
In the previous ticket, I had some old pre v5 mangadex links. However, the issue was related to the new v5 api chapter links. This issue persists after migrating the links to v5 api.
Chapter Download fails (sometimes), but succeeds other times.

**To Reproduce**
1. Mangadex v5 link
2. Download manga chapter from list (click cloud in results)
TypeError: failed to fetch
Console log attached. [cache-1628807757887.log](https://github.com/manga-download/hakuneko/files/6978889/cache-1628807757887.log)

**~~Screenshots~~**

**HakuNeko (please complete the following information):**
 - 6.1.7@cad181

**Other**
OS: Win 10 Home-1909 build 18363.1198

**Comment by Satougg4** [comment]
The connector seems to be working now. The download doesn't always work, but it works about 60% of the time. Since it isn't reproducible every time, I'll mark this as fixed, though it is still inconvenient and confusing when it doesn't work.

**Comment by 27136773** [comment]
Use nightly or wait for fix to be merged into 6.1.7
