### ISSUE TITLE
[LineWebtoon] Chapter download Failed (English)

### ISSUE THREAD

**Issue by relenayui** [manga-download/hakuneko#3814]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I tried to download a manga in webtoon but the download is fail.

**To Reproduce**
1. https://www.webtoons.com/ 
2. I have tried some mangas - all with the same error

**Screenshots**
![ERROR](https://user-images.githubusercontent.com/69942645/129284045-c287427e-9f81-4e66-a7b9-b8324b2be7a4.jpg)

**HakuNeko (please complete the following information):**
 - Version [ 6.1.7]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
`SPDY` errors are related to the chrome engine and i have no idea what cause them nor how to fix them...

![image](https://user-images.githubusercontent.com/27136773/130667342-ab8808dd-cf5a-4d0f-af53-b17198a410f7.png)

**Comment by 27136773** [comment]
It was possible to reproduce this problem by reducing `Network Throttling` in the `Network Conditions` from `Developer Tools` to `3G`. It seems there are just too many concurrent requests for slow internet connections.
