### ISSUE TITLE
Removal Request for Gourmet Scans

### ISSUE THREAD

**Issue by EuGenesisR** [manga-download/hakuneko#3815]
Hiya, I'm Eugene acting as a representative for Gourmet Scans, and we're requesting removal of our site from HakuNeko.
https://gourmetscans.net/

----

### QUESTIONAIRE

Which website should be removed?
https://gourmetscans.net/

Why should this website be removed from HakuNeko?
We're requesting removal of our website so as to prevent the usage of our scans group's work without permission! 

#### In case of Traffic
We don't measure analytics on our site, this is a content protection claim

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
Yes, but HakuNeko is a well-known and popular RPing site, so our goal is to minimize damage.
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
I have not been able to find our site on FMD2 or Tachiyomi.
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
We have cloudflare and login redirect.

#### In case of Monetization
1. Are you using Donations?
We use donations strictly to fund the site and purchase of raws.
2. Are you using Advertisements?
Yes, to fund the site and purchase of our raws.

**Comment by 27136773** [comment]
Unfortunately your website does not meet the removal conditions. However it may qualify for a donation link within HakuNeko after removing the blocking popup advertisement.

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
No further response => rejected
