### ISSUE TITLE
[Site Request] MangaPark v2

### ISSUE THREAD

**Issue by BereBereBeer** [manga-download/hakuneko#3817]
**Name of the website**
MangaPark

**Website urls (examples below)**
- Site: https://v2.mangapark.net/
- Manga List: https://v2.mangapark.net/genre?a-z
- Manga example: https://v2.mangapark.net/manga/jujutsu-kaisen
- Chapter online viewer example: https://v2.mangapark.net/manga/jujutsu-kaisen/i2243991

**Languages**
English

**Website relationship**
old version of MangaPark v3 https://mangapark.net/

**Additional details**
MangaPark v3 is missing stuff while MangaPark v2 also comprises multiple versions of the same manga

**Comment by 27136773** [comment]
I don't think going back again to the old layout is a solution.
I suggest to contact the website owner and mention that mangas from `v2` are missing in `v3`.

**Comment by BereBereBeer** [comment]
I'll give it a try thanks. sorry I don't know how this works, I've got to ask though since you used to have the older version (v2), is it impossible or a lot of work to have both?

**Comment by Jaxk69** [comment]
@GorgoIlCane why don't you close this issue ?
