### ISSUE TITLE
 Connector not working

### ISSUE THREAD

**Issue by chan10njunjunie** [manga-download/hakuneko#3818]
**Did you read [the troubleshooting guide](![hakuneko mangago error](https://user-images.githubusercontent.com/88962904/129471178-815f3452-c296-4842-9405-6e49bf00b899.JPG))**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Please see the picture

**To Reproduce**
1. mangago

**HakuNeko
 - Version 6.17
![hakuneko mangago error]

 - -windows 10

**Comment by Sheepux** [comment]
read the message ?
