### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by RubySkyler** [manga-download/hakuneko#3819]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't load the manga list

**To Reproduce**
1. Webtoonxyz.com

**Screenshots**
![image](https://user-images.githubusercontent.com/88963189/129471857-c82a7048-dc8f-4143-95df-c6e731b9b17a.png)

**HakuNeko (please complete the following information):**
 - Version 6.17
 - window 10

**Comment by 27136773** [comment]
See #2933
