### ISSUE TITLE
[Site Request] Mangakio

### ISSUE THREAD

**Issue by tori131** [manga-download/hakuneko#3820]
**Name of the website**
Mangakio

**Website urls (examples below)**
- Site: https://mangakio.com/
- Manga List: https://mangakio.com/manga/?m_orderby=latest
- Manga example: https://mangakio.com/manga/red-candy1/
- Chapter online viewer example: https://mangakio.com/manga/red-candy1/chapter-65-maximizing-profit/

**Languages**
English

**Website relationship*
not that I know

**Additional details**
-----

**Comment by 27136773** [comment]
Template: WordPress Madara
