### ISSUE TITLE
[IsekaiScan] Connector not working

### ISSUE THREAD

**Issue by Odaxis** [manga-download/hakuneko#3821]
**Did you read [the troubleshooting guide]**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can connect to Isekaiscan from the list, I can refresh (successfully) the Manga List but I cannot access any Chapter Lists

**To Reproduce**
1. Name of connector - IsekaiScan / https://isekaiscan.com/
2. Name of manga (All Manga)
3. Name of chapter (No chapters load in the Chapter List)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

Some of the errors from Console
"Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!"
ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''

**Screenshots**
![ss](https://user-images.githubusercontent.com/18354599/129488636-f87d2b2e-405e-4214-92f8-71fdcf6abeb0.JPG)

**HakuNeko (please complete the following information):**  - Version 6.17

**Comment by 27136773** [comment]
See #3785
