### ISSUE TITLE
[9anime.to] Connector not working

### ISSUE THREAD

**Issue by SSpiegel07** [manga-download/hakuneko#3824]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**To Reproduce**
1. 9anime.to
2. Azumanga Daioh
3. 1 to 26, all servers
4. Error: Malformed UTF-8 data
    at Object.stringify (crypto-js.min.js:1)
    at i.init.toString (crypto-js.min.js:1)
    at NineAnime._getPages (mjs/connectors/NineAnime.mjs:142)
    at async NineAnime._getPageList (Connector.mjs:615) EventTarget
**Screenshots**
![image](https://user-images.githubusercontent.com/88986865/129491389-44949386-b946-49b8-88e4-0fa050690d9c.png).

**HakuNeko (please complete the following information):**
 - Version 6.17@cad1816

**Comment by 27136773** [comment]
See #3806
