### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by FernandezR** [manga-download/hakuneko#3826]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I believe the connector has not been updated to the new API.

**To Reproduce**
1. MangaDex
2. All manga
3. All chapters

**HakuNeko (please complete the following information):**
 - Version 6.1.7 and 8.3.4

**Comment by 27136773** [comment]
Cannot be reproduced, provide sample manga/chapter (not from old bookmarks).

**Comment by 27136773** [comment]
No further response => closed
