### ISSUE TITLE
[Site Request] TCB Scans

### ISSUE THREAD

**Issue by YorozuyaForever** [manga-download/hakuneko#3827]
**Name of The Website**
TCB Scans

**Website urls (examples below)**
- Site: https://onepiecechapters.com//
- Manga List: https://onepiecechapters.com/projects/
- Manga example: https://onepiecechapters.com/one-piece/
- Chapter online viewer example: https://onepiecechapters.com/manga/one-piece-chapter-1021/

**Languages**
English

**Comment by icpryde** [comment]
I know this has been here for over a year but this one would be really great to be able to download from!

Oh I also want to add, the above links will be dead because they only keep the latest chapters of the manga so you'd have to just simply go to the website to grab the latest every week.
