### ISSUE TITLE
[9Anime] Connector not working

### ISSUE THREAD

**Issue by Obamium69** [manga-download/hakuneko#3828]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't watch or download from 9anime. If I try i get the error Malformed UTF-8 data

**To Reproduce**
1. 9anime
2. Life Lessons with Uramichi-Oniisan
3. All chapters
4. Malformed UTF-8 data

**HakuNeko (please complete the following information):**
 - Version: 6.1.7
 - OS: Ubuntu 21.04

**Comment by 27136773** [comment]
See #3806
