### ISSUE TITLE
[Isekaiscan.com] Connector not working

### ISSUE THREAD

**Issue by Mrbones2121** [manga-download/hakuneko#3829]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I'm able to read what the manga's name is however the chapters no longer appear. This is likely due to isekaiscan coming out of maintenance. 

**To Reproduce**
1. Isekaiscan.com
2. Any manga
3. Manga update not working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3785
