### ISSUE TITLE
[nhentai.net] Connector not working

### ISSUE THREAD

**Issue by refinedchunk** [manga-download/hakuneko#3830]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector is not working and saying to copy directly the url, how can i do that

**To Reproduce**
1. nhentai.net
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Error: This website does not provide a manga list, please copy and paste the URL containing the images directly from your browser into HakuNeko.
    at NHentai._getMangas (NHentai.mjs:27)
    at NHentai._getMangaList (Connector.mjs:576)
    at Connector.mjs:99 NHentai

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
https://hakuneko.download/docs/FAQ/#copy-and-paste

**Comment by azmirido29ai** [comment]
/503604

**Comment by sle77694-droid** [comment]
https://nhentai.net

**Comment by kingdyrrot2011-hub** [comment]
.github

**Comment by kingdyrrot2011-hub** [comment]
510203

**Comment by adisanjaya23776-art** [comment]
6748663

**Comment by limalvaro75-spec** [comment]
333709

**Comment by HeaTTap** [comment]
Hehe
