### ISSUE TITLE
Hakuneko Redirects

### ISSUE THREAD

**Issue by Iloveboobs84** [manga-download/hakuneko#3833]
Hi, when trying to locate a manga to download this Program is redirecting to other sites within the APP. I find the manga but it pops up about it manga has been hotlinked by another site.  When going to the other site it will not load manga and the little icon that indicates the page is loading continues on 4ever.  The site that will not load is Manganelo.  My Anit-virus might be the issue but other links work just fine. How do I check if my Hakuneko app is up to date and where to download the latest version. I believe the last time I updated mine was in April of this year.

**Comment by ronny1982** [comment]
You should provide more details, such as which manga/chapter and what websites are involved...
