### ISSUE TITLE
[Site Request] https://yanmaga.jp

### ISSUE THREAD

**Issue by AetherniR** [manga-download/hakuneko#3834]
**Name of the website**
Yanmanga

**Website urls (examples below)**
- Site: https://yanmaga.jp
- Manga List: https://yanmaga.jp/comics/
- Manga example: https://yanmaga.jp/comics/異世界帰りの大賢者様はそれでもこっそり暮らしているつもりです 
- Chapter online viewer example: https://yanmaga.jp/comics/異世界帰りの大賢者様はそれでもこっそり暮らしているつもりです/c45739fa1110d84725c54625f992ad84

**Languages**
Japanese

**Website relationship*
Looklike:
- https://magcomi.com
- https://comic-polaris.jp / https://comic-meteor.jp/
- etc same sites...

**Additional details**
NA.

**Comment by Sheepux** [comment]
duplicate #3144
