### ISSUE TITLE
[IsekaiScan] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#3835]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Dont load chapters

**To Reproduce**
1. IsekaiScan
2. Any
3. Any
4. POST https://isekaiscan.com/wp-admin/admin-ajax.php 400 Connector.mjs:434

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by tsentered** [comment]
I've got the same problem. Same exact issue as #3852.

**Comment by 27136773** [comment]
See #3785
