### ISSUE TITLE
[Site Request] hentaiwebtoon

### ISSUE THREAD

**Issue by scepticweeb** [manga-download/hakuneko#3838]
**Name of the website**
Hentaiwebtoon

**Website urls (examples below)**
- Site: https://hentaiwebtoon.com/
- Manga List: https://hentaiwebtoon.com/manga/?m_orderby=views
- Manga example: https://hentaiwebtoon.com/manga/a-perverts-daily-life/
- Chapter online viewer example: https://hentaiwebtoon.com/manga/a-perverts-daily-life/chapter-01/

**Languages**
English

**Comment by 27136773** [comment]
Template: WordPressMadara
