### ISSUE TITLE
[Site Request] gabutscans

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3840]
**Name of the website**
gabutscans

**Website urls (examples below)**
- Site: https://gabutscans.com/
- Manga List: https://gabutscans.com/manga/
- Manga example: https://gabutscans.com/manga/bonkotsu-shinpei-no-monster-life/
- Chapter online viewer example: https://gabutscans.com/bonkotsu-shinpei-no-monster-life-chapter-1-bahasa-indonesia/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Template: WordPressMangastream
Region Lock: Indonesia

**Comment by 27136773** [comment]
Already supported, please check before open a request
