### ISSUE TITLE
[Site Request] Komikplay

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3841]
**Name of the website**
Komikplay

**Website urls (examples below)**
- Site: https://komikplay.com/
- Manga List: https://komikplay.com/daftar-komik/
- Manga example: https://komikplay.com/series/against-the-gods/
- Chapter online viewer example: https://komikplay.com/against-the-gods-chapter-378/

**Languages**
Indonesia

**Comment by 27136773** [comment]
Template: WordPressMangastream
