### ISSUE TITLE
[Site Request] Wib

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3842]
**Name of the website**
Wib

**Website urls (examples below)**
- Site: https://www.wib.my.id/
- Manga List: https://www.wib.my.id/p/project_10.html
- Manga example: https://www.wib.my.id/2021/06/990k-ex-life-hunter.html
- Chapter online viewer example: https://www.wib.my.id/2021/01/chapter-5_75.html

**Languages**
Indonesia

**Comment by 27136773** [comment]
Template: WordPressMangastream

**Comment by 27136773** [comment]
Already supported, please check before open a request
