### ISSUE TITLE
[Comic-Days] Connector not working for Magazines or Volumes

### ISSUE THREAD

**Issue by devmatcha** [manga-download/hakuneko#3845]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes for chapters [free and paid]
No for magazines [in subscription] or volumes [paid]

**Describe the bug**
A subscription to comic-days gives a list of magazines to read, but none of them show on the list of the connector and can't be downloaded. Any volumes of a series don't show up either. 

1. The connector doesn't show volumes of a series as an option to download [even when purchased] 
Even if I try with the volume link on the clipboard, it just shows the chapters of the series, not the whole volume option.

2. The connector doesn't show magazines titles as an option to download [even when a paid subscription is present]

**To Reproduce**
1. Name of connector : comic-days, with login information through manual website interaction
2. Name of manga: any magazine 
3. Name of chapter : issues / or magazine wont show up on the list to download

**HakuNeko (please complete the following information):**
 - Version 6.1.7@0084ac

**Comment by 27136773** [comment]
Please provide sample manga/chapter, developers don't have time to search hours to reproduce problems

**Comment by devmatcha** [comment]
Apologies for the oversight.

Volume link for アオの死、僕の後悔（１）: https://comic-days.com/volume/3269754496325252330
Magazine link for イブニング ２０２１年１８号: https://comic-days.com/magazine/13933686331696517405
Magazine link for デザート２０２１年１０月号 : https://comic-days.com/magazine/13933686331696526323


Trying to paste use the URL directly for the magazines shows a list of chapters completely unrelated to the magazine. (In fact, it shows the same list for any magazine, as shown in the screenshots below)

![Screen Shot 2021-08-23 at 2 50 27 PM](https://user-images.githubusercontent.com/81999844/130510561-f4c5d860-0f5b-4923-bc23-ab74cb84a625.png)
![Screen Shot 2021-08-23 at 2 48 48 PM](https://user-images.githubusercontent.com/81999844/130510564-9001d829-eb12-4c36-80b5-fd2c0600e0ca.png)

**Comment by 27136773** [comment]
Someone with a subscription need to adapt support for full volumes/magazines.
All i can do without an account is to ensure that pasted magazine links only list the magazine itself instead of the whole RSS feed...

**Comment by Ever4engel** [comment]
if @devmatcha give you his account for some tests would be great.

**Comment by MikeZeDev** [comment]
Closed as we lack means to test properly (paid account)
