### ISSUE TITLE
[Kiryuu] Connector not working 

### ISSUE THREAD

**Issue by famousfreak05** [manga-download/hakuneko#3846]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**

**To Reproduce**
1. Name of connector --> https://kiryuu.id/
2. Name of manga (if connector update is working) --> https://kiryuu.id/manga/my-girlfriend-is-a-villain/
3. Name of chapter (if manga update is working) --> https://kiryuu.id/my-girlfriend-is-a-villain-chapter-66/
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/79199707/130228587-26d16764-b66a-48fa-b25f-070359da5759.png)
![image](https://user-images.githubusercontent.com/79199707/130228170-d0b413d1-2ea6-4e71-9731-c8e9b7a4040f.png)

**Comment by 27136773** [comment]
Cannot be reproduced.
HakuNeko may cache the chapter list, so it might not be updated if HakuNeko runs for several days => restart HakuNeko from time to time...
