### ISSUE TITLE
[ManhuaPlus] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#3851]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
All new chapters are not downloading and when hitting preview, error message pops up. Older chapters work fine.
**To Reproduce**
1. Name of connector - ManhuaPlus
2. Name of manga (All)
3. Name of chapter (New chapters only)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

<img width="1090" alt="Screen Shot 2021-08-20 at 11 49 59 AM" src="https://user-images.githubusercontent.com/70929406/130281439-c51a5a49-714e-4ed1-b8ab-e3ff006da7cb.png">

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by EaZyStudiio** [comment]
Same Issue Here

**Comment by Sup3RNovaX** [comment]
Same problem !!

![hakine](https://user-images.githubusercontent.com/59704095/130629618-d9040df8-3b8a-48f9-8473-cd29a747adca.png)

**Comment by tsentered** [comment]
Most of the chapters are working now, except for a couple titles:
- Return of the Immortal Emperor - Ch. 225
- The Great Ruler - Ch. 253
- Versatile Mage - Ch. 745 -748
- Global Martial Arts - Ch. 102 (UPDATED)

The others are working great, though. These are the only ones that I notices which still don't. Thanks.
