### ISSUE TITLE
[ManhuaES] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#3852]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It seems that the site has changed format. No titles or chapters are working and when hitting refresh removes all title.

**To Reproduce**
1. Name of connector - ManhuaES
2. Name of manga (All)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

<img width="548" alt="Screen Shot 2021-08-20 at 12 05 34 PM" src="https://user-images.githubusercontent.com/70929406/130281947-f0f6a431-b361-4cf5-ad1e-a1a898ad411d.png">
<img width="547" alt="Screen Shot 2021-08-20 at 12 07 08 PM" src="https://user-images.githubusercontent.com/70929406/130282081-0d06abef-f1d3-438a-9020-70ec48f0c496.png">

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end, manga list loads, chapter lists loads, images are not shown (they are also not shown on the website)

**Comment by MikeZeDev** [comment]
Maybe they updated the manga list and the url scheme changed. So your old list and bookmarks are invalid.

Tested download and preview, it works. Nightly.

Can be closed i guess. @Sheepux  pls.
