### ISSUE TITLE
[Reset Scans] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#3853]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No chapters showing but update works fine. 
<img width="535" alt="Screen Shot 2021-08-20 at 12 34 23 PM" src="https://user-images.githubusercontent.com/70929406/130284876-413d6371-ef12-419d-b7af-ebea23c9c5dc.png">

**To Reproduce**
1. Name of connector - Reset Scan
2. Name of manga (All)
3. Name of chapter (if manga update is working)-All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
It is possible that they updated to the new `WordPressMadara` template (which is not yet supported by HakuNeko) and  then reverted it back...

**Comment by tsentered** [comment]
It seems to be working now. Thank you.
