### ISSUE TITLE
[Manytoon.com] Connector not working

### ISSUE THREAD

**Issue by Chitrarthrai** [manga-download/hakuneko#3854]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
i can get the list of manhwa but when i  click on required manhwa it shows chapter list 0

**To Reproduce**
1. manytoon.com
2. this problem is with all manhwa
3. Name of chapter (if manga update is working)
4. C0
5. fetch("https://manytoon.com/wp-admin/admin-ajax.php", {"credentials":"omit","headers":{"content-type":"application/x-www-form-urlencoded","sec-ch-ua":"","sec-fetch-dest":"empty","sec-fetch-mode":"cors","x-referer":"https://manytoon.com"},"referrerPolicy":"no-referrer-when-downgrade","body":"action=manga_get_chapters&manga=182610","method":"POST","mode":"cors"});

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![Screenshot (20)](https://user-images.githubusercontent.com/85828776/130308923-3e4ea7f7-e1bf-416c-b5a0-f5a818c52cbc.png)
![Screenshot (21)](https://user-images.githubusercontent.com/85828776/130308924-2c920f98-ba4a-44d2-9b3e-065c73323e1f.png)

**Comment by supes80** [comment]
Can someone please fix the issue with Manytoon.com? please???

**Comment by Sheepux** [comment]
It's already fixed. Use hakuneko nightly until it's released to the stable version.
