### ISSUE TITLE
[IsekaiScan] Connector not working

### ISSUE THREAD

**Issue by eblankgg** [manga-download/hakuneko#3855]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When any manga is selected it doesn't load any chapters 

**To Reproduce**
1. Isekaiscan 
2. Anyone can be selected 
3. No chapters are shown when any manga is selected 
4. Connector.mjs:434 GET https://isekaiscan.com/manga/a-bittersweet-couple/ 503

**HakuNeko (please complete the following information):**
 - rev. master@48f0a7

**Comment by tsentered** [comment]
I've got the same problem. Same exact issue as #3852.

**Comment by 27136773** [comment]
See #3785

**Comment by tsentered** [comment]
At the time I wrote this, the site was working perfectly for me, as well.  I checked right now, again the site is working perfectly. I read chapters on the site but no chapters showing on Haku.
