### ISSUE TITLE
[readmanhwa.com, manytoon.com, manytoon.me] Connector not working

### ISSUE THREAD

**Issue by supes80** [manga-download/hakuneko#3856]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not updating the directory and with the preloaded directory it does not pull anything from the library

**To Reproduce**
1. Name of connector: readmanhwa.com, manytoon.com, manytoon.me
2. Name of manga (if connector update is working) - not working
3. Name of chapter (if manga update is working) - not working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - None

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] Yes

**Comment by Sheepux** [comment]
Please ... 1 issue per connector
manytoon > duplicate
readmanhwa > connector update is working fine . Connector refresh took more than 20mins to load ( quite normal for 70K titless). Use copy paste if you don't want to wait.
However, images get HTTP 521, but it seems the same as the website.
https://readmanhwa.com/en/webtoon/two-wives

So... nothing we can do ? Will probably close

**Comment by supes80** [comment]
Thanks, I did not know that you could not refer to other connectors in the same ticket, but anyways what about Manytoon.com? this is the one that interests me the most since it has the largest library, I click on anything on their library and it gives me 0 chapters and I go into the website and the chapters are working fine



Thank you
Julio Bermudez

________________________________

**Comment by Sheepux** [comment]
Manytoon will be handled by https://github.com/manga-download/hakuneko/issues/3854
There is something that must be fixed. Someone will take care of it.
(closing this one)
