### ISSUE TITLE
[Crunchyscan] Connector not working

### ISSUE THREAD

**Issue by demaZelle** [manga-download/hakuneko#3858]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When any manga is selected it doesn't load any chapters

**To Reproduce**
1. Crunchyscan
2. All
3. No chapters are shown when any manga is selected
4. i think is : Failed to load resource: net::ERR_FILE_NOT_FOUND

**Screenshots**
![Capture](https://user-images.githubusercontent.com/89340845/130352836-8dfa1820-b91a-4b04-a4a5-686716a1e4b7.PNG)
this loads what i already downloaded, but nothing more Last night there was no problem, but now I can't download any more they are all like this or empty (sorry for my english)
I tried to refresh the page again but : 
![Capture](https://user-images.githubusercontent.com/89340845/130358096-af3b317e-3196-4dae-8453-cc7fd7754b40.PNG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
They enabled CloudFlare, see #2933

**Comment by demaZelle** [comment]
> They enabled CloudFlare, see #2933

I'm sorry, I don't understand the manipulation
What do I need to do to be able to download again?
thank you so much
(Sorry for my english again)

**Comment by 27136773** [comment]
You cannot do anything, use a different website
