### ISSUE TITLE
[Site Request] Mangatoon FR

### ISSUE THREAD

**Issue by demaZelle** [manga-download/hakuneko#3859]
**Name of the website**
Mangatoon FR

**Website urls (examples below)**
- Site: https://mangatoon.mobi/fr
- Manga List: https://mangatoon.mobi/fr/genre/tags/84?type=1
- Manga example: https://mangatoon.mobi/fr/detail/450918
- Chapter online viewer example: https://mangatoon.mobi/fr/watch/450918/6966

**Languages**
![Capture](https://user-images.githubusercontent.com/89340845/130352962-fe26775b-df85-4e19-9c32-4ce0a04fcfdb.PNG)

**Comment by demaZelle** [comment]
Hello, please add autentification as for delitoon (screen bellow)
![image](https://user-images.githubusercontent.com/89340845/137029105-e53d383c-4009-4fb4-a7ea-51cbcf56164a.png)

**Comment by 27136773** [comment]
Create a new issue and request to add login URL: https://h5.mangatoon.mobi/users/login
Or add the corresponding code from [Delitoon.mjs](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/Delitoon.mjs#L12-L14) to [MangaToon.mjs](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/MangaToon.mjs#L14) and create a pull request with the change.
