### ISSUE TITLE
Can't find manga title with special case ("...") in mangahere

### ISSUE THREAD

**Issue by jengky05** [manga-download/hakuneko#386]
Can't find manga title with special case ("...") in mangahere.
Like "This **"**Summon Kitchen**"** Skill is Amazing! ~Amassing Points By Cooking in Another World~"
Please make it work, so we can download manga that use special case :D

**Comment by 27136773** [comment]
Probably caused by invalid escaped double quotes on the website.

Current workaround:
Use copy & paste feature to get the manga's chapters

----

![DeepinScreenshot_dde-desktop_20190828200647](https://user-images.githubusercontent.com/27136773/63881133-72073900-c9cf-11e9-84c5-ae00f55e7631.png)

**Comment by 27136773** [comment]
Using quotes within an attribute value is invalid HTML syntax. Fixing this would be to costly since only a single title is affected. I suggest using the workaround suggested above and add this manga to your favorites.
