### ISSUE TITLE
[Site Request] Ganma!

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#3865]
**Name of the website**
Ganma! (To be more precise, if there's a possible way to download from the app, since the rest of the chapters are on it.)

**Website urls (examples below)**
- Site: https://ganma.jp
- Manga List: https://ganma.jp/list/complete
- Manga example: https://ganma.jp/kamuraitribe
- Chapter online viewer example: https://ganma.jp/kamuraitribe/3f6fda70-7273-11e7-97b2-06e4e79605e7/0

**Languages**
Japanese

**Website relationship*

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Already supported, please check before making a new website request...
