### ISSUE TITLE
[Clover Manga] Connector not working

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#3866]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
chapters list not listed

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dodieboy** [comment]
Cannot be reproduced on my end.
![image](https://user-images.githubusercontent.com/9015764/132085620-a7f1dedb-78d4-4110-a7c5-376154005a27.png)

**Comment by 27136773** [comment]
No further response => closed
