### ISSUE TITLE
[Site Request] Tsuki Mangás

### ISSUE THREAD

**Issue by gutolimeira** [manga-download/hakuneko#3869]
**Name of the website**
Tsuki Mangás

**Website urls (examples below)**
- Site: https://tsukimangas.com/
- Manga List: https://tsukimangas.com/lista-completa
- Manga example: https://tsukimangas.com/obra/7/goblin-slayer
- Chapter online viewer: https://tsukimangas.com/leitor/7/237970/goblin-slayer/62#1

**Languages**
Brazilian Portuguese

**Comment by 27136773** [comment]
See #3032
