### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by poudink** [manga-download/hakuneko#387]
I'd like sub folders to be supported. Currently in the folder viewer, when you click on a folder, it seems treats all the folders inside of it as images, which doesn't work. Instead, clicking on a folder with sub folders should display all of the subfolders and allow you to choose one.

**Comment by 27136773** [comment]
This would be a massive amount of work with various challenges and therefore this request will be rejected.

Reasons:
Chapters could consist of folders with images, archives, video files, pdf, ..., therefore it is quite difficult to determine if a given folder is a chapter or not. The fixed structure help to solve this issue, it is assumed that a manga folder always contains chapters and no nested folders. So by defining that the root level contains mangas it is quite easy to detect and distinguish mangas and their corresponding chapters. Breaking this core concept and allowing variable depth levels of nested mangas will lead to problems of detecting manga directories and chapters. Furthermore the UI needs to support complex navigation into nested folders in both, the manga list and the chapter list.

Note:
I recommend to use a third party software to manage and organize nested directory structures of mangas, maybe someone can recommend some...
