### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by randoomdude** [manga-download/hakuneko#3871]
**Name of the website**
Niadd

**Website urls (examples below)**
- Site: https://www.niadd.com/
- Manga List: https://www.niadd.com/category.html
- Manga example: https://es.niadd.com/original/10037633.html
- Chapter online viewer example: https://www.niadd.com/chapter/Cap_189/100308194/

**Languages**
English, Spanish, Italian, Russian, Portuguese, German, French

**Website relationship*
Seems to also host manga on https://www.gardenmanage.com/statuses/5624371.html for Spanish (?? not sure of relation if not just a mirror)

**Additional details**
Seems to be a good updated site as a lot of older manga i'm following is no longer available on older sites

**Comment by 27136773** [comment]
See #816
