### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by randoomdude** [manga-download/hakuneko#3872]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
Mangadex seems to have changed and trying to view on Hakuneko no longer works, series instead will have up to 30 variations of a title in the manga list that will all be blank
https://mangadex.org/chapter/d05277cb-170f-4f95-8be2-35181b8d1fa1/1
https://mangadex.org/group/12af330f-a9e0-48fb-bd19-894f0db44699
Website itself seems different from before but has working pages

**To Reproduce**
1. Mangadex
2. Watashi ga Motenai (Watamote)
3. Chapter 189-194 (since June 2021)
4. Video of console: https://files.catbox.moe/j4zznv.webm

**Screenshots**
![Image 126](https://user-images.githubusercontent.com/6027132/130536152-415e43d7-622a-4a82-9e08-432440f3431a.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Make sure the manga/chapter is working in your browser and your network is configured properly (proxy, vpn, ...).

![image](https://user-images.githubusercontent.com/27136773/130586709-30813468-84c4-4d2c-8b72-b2ac7ceb3836.png)

**Comment by randoomdude** [comment]
I'm not sure why it doesn't work for me, I was able to open the website itself in mangadex and see the chapters but it doesn't show up in the list, i've reinstalled it a couple times trying different releases/32 bit version and it seems the same every time. Also I don't know how to get rid of the tutorial thing on the right like you have in your picture either
![image](https://user-images.githubusercontent.com/6027132/131204001-491dcc0e-a91c-4f40-8efa-165a6b7aef9c.png)

**Comment by Zehra** [comment]
Chapters do not load from bookmarked series, despite being viewable in the external web view.

**Comment by MediLasso** [comment]
Chapters from the connector and bookmarked series do not and if I synchronize, the list becomes empty.

**Comment by 27136773** [comment]
[Update your bookmarks](https://github.com/manga-download/hakuneko-userland/tree/master/bookmark-migration-mangadex-v5) and use the `nightly build` or wait for update to be merged into `6.1.7`

**Comment by Ever4engel** [comment]
duplicate #4003

**Comment by 27136773** [comment]
The problem was reported before MangaDex changed their API, so it cannot be treated as duplicate of #3959
However, the comments from September 16th about chapters not being loaded are not related to the problem, as these comments were made after MangaDex changed their API...

**Comment by MikeZeDev** [comment]
Works on nightly. Tested chapter 189 preview and download. 

Can be closed i guess @Sheepux (but who knows with mangadex :D)
