### ISSUE TITLE
[Bug]Showing up "Streaming from this mirror is not implemented" messeage from 9anime site.

### ISSUE THREAD

**Issue by kgr44217** [manga-download/hakuneko#3877]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Ye
![err](https://user-images.githubusercontent.com/89502592/130726477-1cc4c124-90fb-4fc2-aeaf-0c37d6563b54.JPG)
s/No

**Describe the bug**

**To Reproduce**

**Expected behavior**
This problem is showing up in 9anime. I was able to watch from there previously,but the problem strted to show up from today.

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by Nunu27** [comment]
9anime seems to be updating their encryption again
