### ISSUE TITLE
Add new and website update

### ISSUE THREAD

**Issue by jrdp18** [manga-download/hakuneko#388]
Update:
- NetEase Comics URL is now https://163.bilibili.com (old: https://manhua.163.com)
- Some chapter titles don't load [pic](https://imgur.com/jffcNzz), so those chapters end up having no folder (and images overwriting each other)
  - Load NetEase comics manga list
  - Search 我所向往的她

New website:
- Bilibili Comics https://manga.bilibili.com/
- Manman Comic 漫漫漫画 https://www.manmanapp.com

**Comment by 27136773** [comment]
I need to know for which manga(s) the issue with the chapters occurs

**Comment by jrdp18** [comment]
- 我所向往的她
- 我家有个传送阵
- 公交男女爆笑漫画
