### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by mwehehehe** [manga-download/hakuneko#3880]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
https://mangadex.org/title/1d9fad4e-b81a-4498-8cce-e5ddfb1e4f03/moriarty-the-patriot
I can read the manga on the website but in the app download always fail

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/54024596/130865281-65ba2453-7a57-4c7d-bcd1-498c21ea258c.png)

![Screenshot_2](https://user-images.githubusercontent.com/54024596/130865393-08963924-f816-4cb0-91aa-ba90eec6bd6b.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Darkmaster006** [comment]
I second this. I've been trying to download some manga and most of them have failed. Currently, for example: https://mangadex.org/title/2b37189e-0bb2-4586-9757-b3fe6acd77b3
And this happens:
![image](https://user-images.githubusercontent.com/21136515/130992984-19886fed-166a-4b4e-9ab8-802af5664cd7.png)
(If anything, is there no way to automatically start download again if it fails?)

**Comment by Zehra** [comment]
It's possible to download chapters from MangaDex by repeatedly triggering restarts/refreshes upon each failure, but that is non-ideal nor a viable option when chapters may be 30-50 pages long. (Seems to need a refresh on every page or two.)

**Comment by 27136773** [comment]
Use workaround as described above.

Problem right now are `SPDY_PROTOCOL_ERRORS`, which for some reason did not throw an exception and therefore HakuNeko assumes they were successful. Otherwise HakuNeko would retry downloading the failed images from a different server...

**Comment by Darkmaster006** [comment]
> 
> 
> Use workaround as described above.
> 
> Problem right now are `SPDY_PROTOCOL_ERRORS`, which for some reason did not throw an exception and therefore HakuNeko assumes they were successful. Otherwise HakuNeko would retry downloading the failed images from a different server...

Clicking re-try on all episodes one at a time, five times or more, is not sustainable, as also outlined above.
