### ISSUE TITLE
[Langage Request] for Manga plus

### ISSUE THREAD

**Issue by ounsen** [manga-download/hakuneko#3881]
**Name of the website**
manga plus

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://mangaplus.shueisha.co.jp/updates
- Manga example: https://mangaplus.shueisha.co.jp/titles/100020
- Chapter online viewer example: https://mangaplus.shueisha.co.jp/viewer/1000486

**Languages**
thai ; russian ; Portuguese ; Indonesian ; spanich and english ( the last two are already on hakuneko)

I just wanted to request to add the the following languages for the connector Manga Plus already on hakuneko :
thai, russian, Portuguese, Indonesian.

**Comment by 27136773** [comment]
It already supports other languages, just copy & paste the correct manga link (the one you posted is english).
Only problem i see is that HakuNeko adds wrong language tag to the title...

![image](https://user-images.githubusercontent.com/27136773/131216741-69351054-4037-4a7f-bbed-c2388d785a21.png)

**Comment by ounsen** [comment]
I didn’t know, thank you and sorry for wasting you time!
