### ISSUE TITLE
[Hoc vien truyen tranh] Connector not working - 400 - Bad Request

### ISSUE THREAD

**Issue by vudoanbinhminh** [manga-download/hakuneko#3882]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No ( i can read chapter-list but can't read inside chapter )

**Describe the bug**
When i downloading , it gives error 400 - bad request

**To Reproduce**
1. Name of connector : Hoc vien truyen tranh
2. Name of manga (if connector update is working) : YuGi-Oh! Full Màu
3. Name of chapter (if manga update is working) : Every chapters
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : Failed to load resource: the server responded with a status of 400 (Bad Request)

**Screenshots**
![image](https://user-images.githubusercontent.com/33306530/130923339-a69c5d74-621e-48bb-9c6b-83bff05cfb55.png)

**HakuNeko (please complete the following information):**
 - Version : 6.1.7@0084ac

**Comment by 27136773** [comment]
If images are missing on the website, there is nothing that can be done in HakuNeko.
Report the problem to the website owner / use a different website to read the chapters.

**Comment by vudoanbinhminh** [comment]
oh so sorry , looks like my description is misleading you . I mean ,  the image is not missing , simply hakuneko can't view or download it with 400 error ( i tried load it inside hakuneko's browser , it's work normally )
