### ISSUE TITLE
[Site Request] Instamanhwa

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#3886]
**Name of the website**
instamanhwa

**Website urls (examples below)**
- Site: https://www.instamanhwa.com/
- Manga List: https://www.instamanhwa.com/latest
- Manga example: https://www.instamanhwa.com/manga/toshishita-no-senpai
- Chapter online viewer example: https://www.instamanhwa.com/manga/toshishita-no-senpai/chapter-1

**Languages**
English.

**Website relationship*
-

**Additional details**
-

**Comment by 27136773** [comment]
Theme: WordPressMadara
