### ISSUE TITLE
[Site Request] Toonlatinoapp

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#3887]
**Name of the website**
toonlatino

**Website urls (examples below)**
- Site: https://toonlatinoapp.com/
- Manga List: https://toonlatinoapp.com/manga/
- Manga example: https://toonlatinoapp.com/manga/rapocalips/
- Chapter online viewer example: https://toonlatinoapp.com/manga/rapocalips/01/

**Languages**
Spanish.

**Website relationship*
-

**Additional details**
-

**Comment by 27136773** [comment]
Theme: WordPressMadara
