### ISSUE TITLE
[Site Request] TsukiMangás

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#3889]
**Name of the website**
TsukiMangás

**Website urls (examples below)**
- Site: https://tsukimangas.com/
- Manga List: https://tsukimangas.com/obra/5225/the-book-eating-magician
- Manga example: https://tsukimangas.com/leitor/7030/249870/monster-pet-evolution/06#1
- Chapter online viewer example: https://tsukimangas.com/leitor/7030/249870/monster-pet-evolution/06#1

**Languages**
Portuguese Brazil

**Website relationship*
None

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Slowftw** [comment]
cala boca srwonka
also #3032

**Comment by MikeZeDev** [comment]
Close as duplicate?  @Sheepux  please <3
