### ISSUE TITLE
[Site Request] hentaizone

### ISSUE THREAD

**Issue by camisole26** [manga-download/hakuneko#3892]
**Name of the website**
hentaizone

**Website urls (examples below)**
- Site: https://hentaizone.xyz/
- Manga List: https://hentaizone.xyz/tous-les-mangas/
- Manga example: https://hentaizone.xyz/manga/close-as-neighbors/
- Chapter online viewer example: https://hentaizone.xyz/manga/close-as-neighbors/chapitre-1/

**Languages**
French

**Website relationship*
No

**Additional details**
No

**Comment by 27136773** [comment]
Template: WordPressMadara
