### ISSUE TITLE
[Site Request] Comikey

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#3894]
**Name of the website**
Comikey

**Website urls (examples below)**
- Site: https://comikey.com/
- Manga List: https://comikey.com/comics/
- Manga example: https://comikey.com/comics/battle-in-5-seconds-manga/33/
- Chapter online viewer example: https://comikey.com/read/battle-in-5-seconds-manga/yk70gD/chapter-1/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Comment by lord-ne** [comment]
I accidentally made  a duplicate request of this (#4045). I had some additional information in it, so I'll include it here:

> **Website urls (examples below)**
> - Site: https://comikey.com/
> - Manga List: https://comikey.com/comics/ (UI) or https://comikey.com/sapi/comics (API)
> - Manga example: https://comikey.com/comics/cursed-sword-manga/35/ (UI) or https://comikey.com/sapi/comics/35 (API)
> - Chapter online viewer example: https://comikey.com/read/cursed-sword-manga/qD0ZEo/chapter-1/ (UI) or https://comikey.com/sapi/comics/35/read?format=json&content=EPI-qD0ZEo (API)

>**Additional details**
>Official manga translations. Has some free chapters and some paid chapters. Has Clouflare protection. There is a [Tachiyomi extension](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/27a785e15e4a427ee8cd52b47ec1b91403d27257/src/en/comikey/src/eu/kanade/tachiyomi/extension/en/comikey/Comikey.kt), but it's currently not working because of the Cloudflare protection.
