### ISSUE TITLE
[Site Request] Manga Tepesi

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#3895]
**Name of the website**
Manga Tepesi

**Website urls (examples below)**
- Site: https://mangatepesi.com/
- Manga List: https://mangatepesi.com/mangalistesi
- Manga example: https://mangatepesi.com/manga/starting-from-today-i-ll-work-as-a-city-lord/7
- Chapter online viewer example: https://mangatepesi.com/manga/starting-from-today-i-ll-work-as-a-city-lord/238-bolum/1720

**Languages**
Turkish

**Comment by 27136773** [comment]
Search for existing tickets before creating a new one...
See #1725
