### ISSUE TITLE
[[Hoc vien truyen tranh]] Connector not working - Repost due to misunderstanding

### ISSUE THREAD

**Issue by vudoanbinhminh** [manga-download/hakuneko#3896]
i'm sorry for post this issue again , but the connector is really having problems . And it seems that my description has misinterpreted you guy. The image is not losing , but it cannot be downloaded (I have included an example video below) . There are some manga that only available here, so I hope it will be check again and fixed

**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes , but can't see them on hakuneko

**Describe the bug**
simply hakuneko can't download the manga from this website, even though i can watch it directly with hakuneko, it shows error 400 every time i download

**To Reproduce**
1. Name of connector : Hoc vien truyen tranh
2. Name of manga (if connector update is working) : every manga
3. Name of chapter (if manga update is working) : Every chapters
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : Failed to load resource: the server responded with a status of 400 (Bad Request)

**Screenshots**
![image](https://user-images.githubusercontent.com/33306530/131211662-5dd7a8d0-b79c-4ba1-83c0-827b1404fb8f.png)
Video example : [https://www.youtube.com/watch?v=LTpIAsuC8NQ](https://www.youtube.com/watch?v=LTpIAsuC8NQ)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@0084ac

**Comment by Sheepux** [comment]
Isn't it already fixed by https://github.com/manga-download/hakuneko/pull/3884 ?
Did you try hakuneko nightly ?

**Comment by vudoanbinhminh** [comment]
> Isn't it already fixed by #3884 ?
> Did you try hakuneko nightly ?

oh, I just tried it this afternoon , it didn't work. But it's ok now

**Comment by 27136773** [comment]
Chapter 343 contains a broken image, report it to the website owner or use a different website for download
