### ISSUE TITLE
[Feature]CHAPTER SELECTION RANGE

### ISSUE THREAD

**Issue by damare01** [manga-download/hakuneko#3902]
**Is your feature request related to a problem? Please describe.**
I get frustrated when I have to download all the chapters of a manga 

**Describe the solution you'd like**
make a feature where users can choose which chapter of a manga to start downloading and to stop downloading

**Comment by Sheepux** [comment]
Use chapter filter regex ?

**Comment by 27136773** [comment]
Pause/Resume/Stop downloads already covered by #8

**Comment by 27136773** [comment]
See #382
