### ISSUE TITLE
[Site Request] Günahkar Manga

### ISSUE THREAD

**Issue by Veysinator** [manga-download/hakuneko#3908]
**Name of the website**
Günahkar Manga

**Website urls (examples below)**
- Site: https://gunahkarmanga.com/
- Manga List: https://gunahkarmanga.com/manga/
- Manga example: https://gunahkarmanga.com/manga/dragon-son-in-law-god-of-war/
- Chapter online viewer example: https://gunahkarmanga.com/manga/dragon-son-in-law-god-of-war/bolum-46/

**Languages**
Turkish

**Additional details**
Site Template: WordPressMadara

**Comment by MikeZeDev** [comment]
Dead website?
