### ISSUE TITLE
error gmanga

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#391]
Please correct the error
![hbhb](https://user-images.githubusercontent.com/47768610/64046651-b8de6580-cb6c-11e9-8d73-4ad2310dc7e4.png)

**Comment by 27136773** [comment]
Cannot be reproduced, it works on my end.
Does it work on the website?
Do you have the latest HakuNeko update?
![image](https://user-images.githubusercontent.com/27136773/64048083-fa710f80-cb70-11e9-972a-20ff741ceee6.png)

**Comment by ghost** [comment]
![fgd](https://user-images.githubusercontent.com/47768610/64068991-f9a7ae80-cc40-11e9-9d5a-3e1932714343.png)

**Comment by 27136773** [comment]
OK, so you have the latest version.
It is still unknown if the chapter is working for you on the website.
Furthermore the output from console in developer tools (F12) may help.
Also make sure you are not using any proxy or VPN that might be blocked for image downloads.

**Comment by ghost** [comment]
The site stopped working in the program for more than a month
Now it works but does not show pictures

**Comment by 27136773** [comment]
I'm afraid i cannot help, since it just works fine on my end and the current amount of provided information is not enough to come to any conclusions for the problem.

----

![image](https://user-images.githubusercontent.com/27136773/64078304-53f44e00-ccd9-11e9-94a8-34cf963bc3a5.png)

**Comment by ghost** [comment]
When I login to browse this is the result
![cvc](https://user-images.githubusercontent.com/47768610/64081888-72713e00-cd07-11e9-997a-ba35807632c8.png)

**Comment by ghost** [comment]
Do I have to uninstall and reinstall it?
Thanks in advance

**Comment by 27136773** [comment]
Reinstalling will not help.
Try Proxy Server or VPN, it seems to be a regional issue.

**Comment by ghost** [comment]
thanks

**Comment by 27136773** [comment]
Cannot provide any further help => closed
