### ISSUE TITLE
[Site Request] Qmanga

### ISSUE THREAD

**Issue by yuukiasuna0000** [manga-download/hakuneko#3913]
**Name of the website**
Qmanga

**Website urls (examples below)**
- Site: https://qmanga.net/
- Manga List: https://qmanga.net/danh-muc/bl-yaoi
- Manga example: https://qmanga.net/than-tuong-den-roi.html
- Chapter online viewer example: https://qmanga.net/than-tuong-den-roi/chapter-19_510557.html

**Languages**
Vietnamese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
SSL error

dead?  or website juste change url often?
