### ISSUE TITLE
[Mangasee] May need throttling? 

### ISSUE THREAD

**Issue by Pirate-Hunter** [manga-download/hakuneko#3914]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I am unable to download manga in batch.. It just get stuck in middle of downloading after 2 - 5 chapters... I had to close and open again to download another 2 - 5 chapters everytime... I thought its connector problem which I usually use Mangasee.... But didn't work in mangalife either.. Also Mangasee one of the best connector in my opinion.. so do help making it work.. Thanks.

**To Reproduce**

**Expected behavior**
I want to download all chapters in a manga just by clicking that top download button.. which now getting stuck in between.

**Screenshots**
![Reporting Download Bug - 1](https://user-images.githubusercontent.com/73102278/131800117-dadda1ca-5a66-4268-bdec-8aaae9d1d935.png)
![Reporting Download Bug - 2](https://user-images.githubusercontent.com/73102278/131800126-edde348a-847d-4ae1-94cb-2aa896d0fbde.png)

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 6.17

**Additional context**

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Open developer tools (`F12`) and check for errors in the `Console` and `Network` tab...

**Comment by Pirate-Hunter** [comment]
> Cannot be reproduced on my end.
> Open developer tools (`F12`) and check for errors in the `Console` and `Network` tab...

![Screenshot 2021-09-02 181839](https://user-images.githubusercontent.com/73102278/131846931-6e0aa9a5-aba7-47bd-8bdd-cf34cc8abfc8.png)
What is the error here

**Comment by SaqinNoor** [comment]
This happens on my hakuneko too. It's really annoying. It doesn't happen if you download chapters one by one so i have to download EACH AND EVERY CHAPTER ONE BY ONE.

**Comment by Sheepux** [comment]
Probably website related: temp ip banning, need throttling.

**Comment by Pirate-Hunter** [comment]
They have to add Throttling for Mangasee then..

**Comment by MikeZeDev** [comment]
Do we have throttling?
