### ISSUE TITLE
"Update All Databases" Button[Feature]

### ISSUE THREAD

**Issue by Dividedby0KSJ** [manga-download/hakuneko#3915]
## **Is your feature request related to a problem? Please describe.**
When you select which website you want to search for your manga (or anime) you also have the option to search for the manga itself. but this only works if/when you have refreshed the database of a website that has that manga.

### for example.
I was searching for a manga called "Little Devils" and used the search MANGA option in the CONNECTORS screen, nothing showed up.
I then look around online and found it on "MangaSee".
'MangaSee' is available on HakuNeko but the manga didn't show up because I have never updated/refreshed the database for the 'MangaSee' connector.
once I did, it THEN showed up on the MANGA search in the CONNECTORS screen.

## **Describe the solution you'd like**
A button/option on the CONNECTORS screen or in the options menu to refresh all / selected website databases to allow for searching manga in the CONNECTORS screen.

I am aware that refreshing all websites will take a long time, so I thought if you give the user the ability to select which website to refresh in bulk or to simply say "This will take a while".

And I am also aware that some websites DO NOT have a database for HakuNeko to scan, as such another message will tell the user that some websites cannot be refreshed and have to be manually serched.

## **Describe alternatives you've considered**
Going into every connector and manually refresh the database. It works but can be tedious and confusing. plus there are a lot of websites.

## **Context (please complete the following information):**
 My current HakuNeko Version 6.1.7@c86d92

## **Additional context**
![image](https://user-images.githubusercontent.com/44017376/131837342-82f842f2-3454-45e0-bb56-fa1e6a609ebf.png)

**Comment by 27136773** [comment]
See #152
