### ISSUE TITLE
[Site Request] mangatuli

### ISSUE THREAD

**Issue by aquarius-771** [manga-download/hakuneko#3916]
**Name of the website**
mangatuli

**Website urls (examples below)**
- Site: https://mangatuli.com/
- Manga List: https://mangatuli.com/manga-genre/yaoi/
- Manga example: https://mangatuli.com/manga/pearl-boy/
- Chapter online viewer example: https://mangatuli.com/manga/pearl-boy/chapter-7/

**Languages**
english
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website doesnt answer. Dead? 

@Sheepux pls

**Comment by Sheepux** [comment]
no alternative domain found
