### ISSUE TITLE
[Site Request] mangarise

### ISSUE THREAD

**Issue by aquarius-771** [manga-download/hakuneko#3917]
**Name of the website**
mangarise

**Website urls (examples below)**
- Site: https://mangarise.com/
- Manga List: https://mangarise.com/genres
- Manga example: https://mangarise.com/manga/totally-captivated
- Chapter online viewer example: https://mangarise.com/manga/totally-captivated/chapter-71-12232

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Site is totally broken

**Comment by MikeZeDev** [comment]
Dead
