### ISSUE TITLE
Add support for tapread

### ISSUE THREAD

**Issue by hemantkgurjar** [manga-download/hakuneko#392]
please add support of tapread comics

link -->  http://www.tapread.com/comic/more

Thanks

**Comment by 27136773** [comment]
Seems to be an easy one, everything is available through REST:

- Webtoon List: https://www.tapread.com/comic/moredetail
- Chapter List: https://www.tapread.com/comic/contents?comicId=209
- Page List: https://www.tapread.com/comic/chapter?comicId=209&chapterId=15622

**Comment by hemantkgurjar** [comment]
Please add it ;-;

**Comment by 27136773** [comment]
Currently there are 86 website requests in queue.
Since this is a simple one, chances are high that it will be added to [version 6.0](https://github.com/manga-download/hakuneko/milestone/2) which will be released in December.

**Comment by 27136773** [comment]
Added to master.
Will not be merged to 5.0.8
