### ISSUE TITLE
[Site Request] doujin69.com

### ISSUE THREAD

**Issue by Firstzhiro** [manga-download/hakuneko#3921]
doujin69.com

Website urls

- Site: https://doujin69.com/
- Manga List: https://doujin69.com/doujin/
- Manga example: https://doujin69.com/doujin/17-sex-fantasies/
- Chapter online viewer example: https://doujin69.com/17-sex-fantasies-%e0%b8%95%e0%b8%ad%e0%b8%99%e0%b8%97%e0%b8%b5%e0%b9%881/

Languages
Thai

MangaReader WordPress Theme

**Comment by 27136773** [comment]
Template: `WordPressMangastream`
