### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by Rvisre** [manga-download/hakuneko#3923]
**Name of the website**
coloredcouncil

**Website urls (examples below)**
- Site: https://coloredcouncil.moe
- Manga List: https://coloredcouncil.moe/series/
- Manga example: https://coloredcouncil.moe/read/manga/Bleach/
- Chapter online viewer example: https://coloredcouncil.moe/read/manga/Bleach/675/1/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #3747
