### ISSUE TITLE
[Site Request] Azora

### ISSUE THREAD

**Issue by Ego-Kha** [manga-download/hakuneko#3925]
**Name of the website**
 Azora

**Website urls (examples below)**
- Site: https://azoraworld.com
- Manga List: https://azoraworld.com/series/
- Manga example: https://azoraworld.com/series/the-descent-of-the-demonic-masters/
- Chapter online viewer example: https://azoraworld.com/series/the-descent-of-the-demonic-masters/100/

**Languages**
Arabic

**Website relationship*
https://team1x1.com
**Additional details**
this website old url azoramanga.com and this is the new one.

**Comment by MikeZeDev** [comment]
Website is supported.

@Sheepux pls <3
