### ISSUE TITLE
[readmanga and mintmanga] Connector not working

### ISSUE THREAD

**Issue by wizarvamp** [manga-download/hakuneko#3929]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
nothing does not download 

**Screenshots**
![001](https://user-images.githubusercontent.com/90101234/132098317-fd2fe8b7-ccb4-4bff-a2d8-b7cd5f6846b5.png)

**HakuNeko 
Version 6.1.7@c86d92

**Comment by NiackZ** [comment]
The pages don't display because JS is disabled, according to the message on the page.
"You have disabled JavaScript. Reading manga is not possible."

![2021-09-07_01-15-57](https://user-images.githubusercontent.com/14057913/132258500-0c4e5b30-2d38-4482-a66e-fa263fd9c78c.png)
