### ISSUE TITLE
[SekaiKomik] Connector not working

### ISSUE THREAD

**Issue by powu01** [manga-download/hakuneko#3936]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Website has changed the manga list url from [https://www.sekaikomik.xyz] to [https://www.sekaikomik.biz]

**Comment by manh21** [comment]
Duplicate
see: #3803
