### ISSUE TITLE
[Feature] More options for Bilibili Comics

### ISSUE THREAD

**Issue by rg-4re** [manga-download/hakuneko#3937]
**Is your feature request related to a problem? Please describe.**
- Downloads always end with jpg format when the website provides webp with less artifacts. Tried changing de-scrambling format but it doesn't work. They also offer different resolutions (raw, hd, sd) but unable to choose which to get even when changing them in hakuneko browser.

**Describe the solution you'd like**
- Options to be added in settings. An image format and image quality dropdown are enough.

**Describe alternatives you've considered**
- Have a force webp toggle and Image quality would depend on browser instead. 

**Context (please complete the following information):**
- Version [6.1.7]

**Additional context**
- While some images looks almost the same, the difference could also be plain to see. I found the webp format from network monitor. The link looks like this ".../bfs/comic/xxxxxx.png@2000w.webp?token=xxxxxxx.."

**Comment by MikeZeDev** [comment]
I think its already fixed.
