### ISSUE TITLE
[1st Kiss Manga] Connector not working

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#3938]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When i refresh manga list to make it show new title, it show empty manga, but download is fine

**Comment by samanta-widjaja** [comment]
From network tab, it said failed to load resource: the 1stkissmanga.io/wp-a_in/admin-ajax.php:1 server responded with a status of 400 ()

**Comment by 27136773** [comment]
See: #3785
Make sure your version of HakuNeko is up to date

**Comment by 27136773** [comment]
Domain changed to https://1stkissmanga.io
