### ISSUE TITLE
[Feature] can choose muti Manga list+ get rib of confirm window 

### ISSUE THREAD

**Issue by bloodsucker3011** [manga-download/hakuneko#3939]
**Is your feature request related to a problem? Please describe.**
it pains to deal with some big company artists who have a huge collection of different comics with only 1 chapter. And it's frustrating to hit confirm on everytime i press download all (what the point to ask ?)

**Describe the solution you'd like**
1. make manga list panel is able to download without showing how many chapters (my previous manga downloader make it such easy to deal with artists with a huge collection. Too bad the owner not support the app)

2. get rib of pannel asking to confirm if I want to get an all chapter. I really don't see the point of that panel. it not like a doom day if I hit wrong.

**Describe alternatives you've considered**
1. make a small download icon for the Manga list like you did with the chapter list

**Context (please complete the following information):**
 - HakuNeko Version 6.17

**Comment by Sheepux** [comment]
From https://hakuneko.download/
`HakuNeko was made to help users who download media for circumstances that requires offline usage. The philosophy is ad-hoc consumption, get it when you want to read/watch it. It is not meant to be a mass downloader to stock up thousands of chapters that are just collected and will probably never be read.`

Such request fits the "stock up" description

**Comment by 27136773** [comment]
Rejected:
It is very close to the `sort` button and there is no way to stop or remove pending downloads despite restarting the program after accidentally clicking it.
If it is just one chapter, then simply click the download button of the chapter instead download all.
