### ISSUE TITLE
Downloading from HolyManga and Lezhin

### ISSUE THREAD

**Issue by MarqFJA87** [manga-download/hakuneko#394]
Several manga are undownloadable from HolyManga (I haven't gone through the whole list, but then much of the site's list on HakuNeko doesn't even return any chapters to begin with). In some cases, the download option is available but any attempt immediately suffers a "failed to fetch" error (example: [Dr. Hitomi's Infirmary](http://ww4.holymanga.net/hitomi-sensei-no-hokenshitsu/)), while in some cases the option is disabled outright (example: [A Pervert's Daily Life](http://ww4.holymanga.net/a-perverts-daily-life/)). The latter also holds true for Lezhin as well.

In HolyManga's case, I suspect it might have something to do with how HakuNeko appears to be looking for http://ww**3**.holymanga.net links when the site's domain is http://ww**4**.holymanga.net.

**Comment by 27136773** [comment]
Are the mangas on Lezhin you try to access free?
Are the mangas on Lezhin you try to access R-rated?
Are the mangas on Lezhin you try to access fully available on the website?
Are you logged in with your Lezhin in HakuNeko?

**Comment by MarqFJA87** [comment]
> Are you logged in with your Lezhin in HakuNeko?

... I wasn't because I didn't have an account (didn't think of doing so to begin with; I'm used to sites like MangaDex, didn't expect HakuNeko to access pay-to-read sites), but I made one and the problem is still persistent.

> Are the mangas on Lezhin you try to access fully available on the website?

If by "fully available" you mean "chapters have been already uploaded", then yes.

> Are the mangas on Lezhin you try to access free?

... Now that I look at the page, no. Only the first chapter and some notices are free access.

> Are the mangas on Lezhin you try to access R-rated?

Yes.

**Comment by 27136773** [comment]
R-rated mangas require a login, even if they are free.
After login to Lezhin from within HakuNeko, i can access **A Pervert's Daily Life** without any issues.

If you still got problems to access them please post the manga/chapter and if possible the console output from the developer tools (F12).

----
![image](https://user-images.githubusercontent.com/27136773/64066486-930f9a00-cc1a-11e9-947e-aef806bd2aa7.png)

**Comment by MarqFJA87** [comment]
Well, that's pretty much the same view I'm getting, but only if I picked "en-US" as the language of choice; [this](https://i.imgur.com/vYTptlz.jpg) is how the screen looks on my end when I pick "*" instead, showing all the paywall-locked chapters.

I guess that settles the Lezhin angle of this issue, then.

**Comment by 27136773** [comment]
These chapters are not the locked chapters from Lezhin, these are offline chapters. **Chap XX** is anything that does not exist on Lezhin, but is sitting in the same directory where you store the chapters from Lezhin (probably downloaded from another website which uses the exactly same manga name).

----
![image](https://user-images.githubusercontent.com/27136773/64066872-935e6400-cc1f-11e9-93aa-e24e38442219.png)

**Comment by 27136773** [comment]
Regarding issue #70 it is assumed that HakuNeko only lists the chapters that were free to access or purchased by the user. This is in contradiction to the website where locked chapters are listed, even if they have not been purchased yet.

**Comment by 27136773** [comment]
HolyManga fix is now published.
Additional information about Lezhin has been added in case someone will run into the same problem/question.
