### ISSUE TITLE
[Site Request] mangazure

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#3940]
**Name of the website** : mangazure
**Website urls ** : - Site: https://www.mangazure.com
- Manga List: https://www.mangazure.com/search/label/Tümü
- Manga example: https://www.mangazure.com/2020/11/solo-leveling.html
- Chapter online viewer example: https://www.mangazure.com/2021/09/solo-leveling-bolum-165.html

**Languages** : Turkish

**Comment by Jaxk69** [comment]
Duplicate #3376

**Comment by MikeZeDev** [comment]
Can be closed as duplicate, my dear @Sheepux <3
