### ISSUE TITLE
[Site Request] hentaizone Madara Template

### ISSUE THREAD

**Issue by Bertrand6969** [manga-download/hakuneko#3941]
**Name of the website**
HentaiZone

**Website urls (examples below)**
- Site: https://hentaizone.xyz/
- Manga List: https://hentaizone.xyz/tous-les-mangas/
- Manga example: https://hentaizone.xyz/manga/the-desire-to-kill/
- Chapter online viewer example: https://hentaizone.xyz/manga/the-desire-to-kill/chapitre-14/

**Languages**
French

**Website relationship*
/

**Additional details**
Template madara

**Comment by 27136773** [comment]
Already added, please check before making a website request
https://github.com/manga-download/hakuneko/search?q=hentaizone&type=issues
