### ISSUE TITLE
[Site Request] Toonily.com

### ISSUE THREAD

**Issue by Darthagnon** [manga-download/hakuneko#3944]
**Name of the website**
Toonily.com

**Website urls (examples below)**
- Site: https://toonily.com/
- Manga List: https://toonily.com/webtoons/
- Manga example: https://toonily.com/webtoon/nano-machine/
- Chapter online viewer example: https://toonily.com/webtoon/nano-machine/chapter-1/

**Languages**
List of languages supported by the website

**Website relationship*
Unknown; site seems unrelated to other sites called "Toonily"; this one has a Discord.

**Additional details**
Site has mostly adult manga/manhwa

**Comment by 27136773** [comment]
Already supported. Please check before making a website request.
