### ISSUE TITLE
[Site Request] mangaowl

### ISSUE THREAD

**Issue by RomanNumeraXIII** [manga-download/hakuneko#3946]
**Name of the website**
mangaowl
**Website urls (examples below)**
- Site: https://www.mangaowl.net/
- Manga List: https://www.mangaowl.net/new_release
- Manga example: https://www.mangaowl.net/single/55651/light-and-shadow
- Chapter online viewer example: https://chessmoba.us/team/MTI1Ni4w?utm_source=google&utm_medium=organic

**Languages**
List of languages supported by the website
English
Chinese
Traditional Chinese 
Japanese 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment]
Duplicate
see: #2335
