### ISSUE TITLE
Synchronize not work for (KlikManga)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#395]
the website is still work.
![Klikmanga](https://user-images.githubusercontent.com/45929526/64065369-f27ba300-cc36-11e9-80cc-ca98ef32fd47.png)

**Comment by 27136773** [comment]
Related: #384

**Comment by MIRVOUS** [comment]
when I try to update the list. hakuneko just rotates the icon without any result

**Comment by 27136773** [comment]
The ticket is still open because the fix has not been merged into 5.0.8 yet and is not published
