### ISSUE TITLE
[Site Request] kuaikanmanhua

### ISSUE THREAD

**Issue by spicablock** [manga-download/hakuneko#3950]
**Name of the website**
Kuaikan Manhua ( 快看漫画 )

**Website urls (examples below)**
- Site: https://www.kuaikanmanhua.com/
- Manga List: https://www.kuaikanmanhua.com/tag/0
- Manga example: https://www.kuaikanmanhua.com/web/topic/8499/
- Chapter online viewer example: https://www.kuaikanmanhua.com/web/comic/414186/

**Languages**
Chinese

**Comment by rs3mk** [comment]
![existe](https://user-images.githubusercontent.com/19628943/132915090-1db17889-b464-4435-b972-7213d7bf1b52.jpg)

**Comment by spicablock** [comment]
Oh, thank you so much, but it's not japanese, it's chinese. Could you change?
Thanks for the reply.
