### ISSUE TITLE
[Site Request] SadScans

### ISSUE THREAD

**Issue by vgrkaya** [manga-download/hakuneko#3952]
**SadScans**
thewebsitename

**Website urls (examples below)**
- Site: https://sadscans.com/
- Manga List: https://sadscans.com/series/
- Manga example: https://sadscans.com/series/one-piece
- Chapter online viewer example: https://sadscans.com/reader/613b351954b1b

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MrsLucifer** [comment]
+1
