### ISSUE TITLE
[3asq] Connector not working

### ISSUE THREAD

**Issue by RUGGEDMAN122** [manga-download/hakuneko#3956]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
yes

![bandicam 2021-09-12 18-44-02-932](https://user-images.githubusercontent.com/90565822/132994083-02eb91f2-5799-49bc-98a7-6028ac392e23.jpg)
**Describe the bug**
all the chapters stop failed to download and then go to the another chapter and do the same

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Open developer tools (F12) and check the console tab / network tab for errors...

**Comment by MikeZeDev** [comment]
Cant reproduce too. Nightly. @Sheepux pls?

**Comment by Sheepux** [comment]
working fine too
