### ISSUE TITLE
[Site Request] MangaOwl

### ISSUE THREAD

**Issue by noviemamalateo05** [manga-download/hakuneko#3957]
Name of the website
MangaOwl

Website urls (examples below)
- Site: https://mangaowl.net/
- Manga List: https://mangaowl.net/list
- Manga example: hhttps://mangaowl.net/single/57262/bj-alex
- Chapter online viewer example: https://mostraveller.com/how-to-get-to-chiang-mai-from-ayutthaya?utm_source=google&utm_medium=organic

Languages
English

Website relationship
Unknown

Additional details
Unknown

**Comment by 27136773** [comment]
See: #2335

**Comment by noviemamalateo05** [comment]
@ronny1982 oh thanks. i was rushing to suggest a site. forgot to check. **has it been included then?**
