### ISSUE TITLE
[Site Request] Mundo Webtoon

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#3963]
**Website**
Mundo Webtoon

**Website urls (examples below)**
- Site: https://mundowebtoon.com/
- Manga List: https://mundowebtoon.com/mangas
- Manga example: https://mundowebtoon.com/mangabr/100-man-no-inochi-no-ue-ni-ore-wa-tatteiru-gm
- Chapter online viewer example: https://mundowebtoon.com/mangabr/100-man-no-inochi-no-ue-ni-ore-wa-tatteiru-gm/55

**Languages**
Portuguese

**Website relationship*
https://goldenmangas.top/ (partner site)

**Additional details**
a site with a good manga and webtoons collection to facilitate searching, and quick update of them, since there are few Brazilian sites with a larger manga collection..

**Comment by MikeZeDev** [comment]
dead?
