### ISSUE TITLE
[Site Request] Manga Vibe

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#3964]
**Name of the website**
Manga Vibe

**Website urls (examples below)**
- Site: https://mangavibe.top
- Manga List: https://mangavibe.top/mangas
- Manga example: https://mangavibe.top/manga/12020/tsuyokute-new-saga
- Chapter online viewer example: https://mangavibe.top/chapter/12020/tsuyokute-new-saga/16

**Languages**
Portuguese

**Website relationship**
https://animevibe.top (same group anime site)
https://hentaivibe.top (same group hentai site)

**Additional details**
another site with a good collection of mangas, as there are few like that in Portuguese ..

**Comment by 27136773** [comment]
Region Locked

**Comment by MikeZeDev** [comment]
dead
