### ISSUE TITLE
[Site Request] Muito Manga

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#3965]
**Name of the website**
Muito Manga

**Website urls (examples below)**
- Site: https://muitomanga.com/
- Manga List: hhttps://muitomanga.com/lista-de-mangas
- Manga example: https://muitomanga.com/manga/shuumatsu-no-harem
- Chapter online viewer example: https://muitomanga.com/ler/shuumatsu-no-harem/capitulo-85

**Languages**
Portuguese

**Website relationship*

**Additional details**
another site with a collection of mangas and webtoons, as there are few like that in Portuguese, and time or another many are failing ..

**Comment by 27136773** [comment]
Region Locked: Brazil

**Comment by MikeZeDev** [comment]
dead
