### ISSUE TITLE
[animepahe.com] Connector not working

### ISSUE THREAD

**Issue by randomcloudswings** [manga-download/hakuneko#3967]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The website https://animepahe.com/ is no longer working for me , its alternate domain is https://animepahe.ru , which is working perfectly.

**To Reproduce**
1. https://animepahe.com/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. ERR_CONNECTION_RESET https://animepahe.com/

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/90744124/133371723-d0cc919f-3fcf-42d1-8563-0655f52295c1.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end, everything works as expected...

**Comment by 27136773** [comment]
No further response => closed
