### ISSUE TITLE
[Crunchyroll] Connector not working

### ISSUE THREAD

**Issue by Anim3y2j** [manga-download/hakuneko#3970]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No - Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No - No

**Describe the bug**
A clear and concise description of what the bug is. - I'm not sure

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
 - Version 8.4

**Comment by 27136773** [comment]
See #2416 or #2998
