### ISSUE TITLE
[Webcomics] Connector not working. Can't login and download paid chapters

### ISSUE THREAD

**Issue by jojokira** [manga-download/hakuneko#3971]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Can't login and download paid chapters on site. is there a way to login on site?

**To Reproduce**
1. Webcomics
2. Hottest Topics (if connector update is working)
3. 20-32 (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
If the chapters are not working on the website itself, then there is nothing that can be done in HakuNeko
