### ISSUE TITLE
[9anime] Connector not working

### ISSUE THREAD

**Issue by randomcloudswings** [manga-download/hakuneko#3975]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The connector https://9anime.to is not working, but it's alternative website https://9anime.ws is working fine.

**To Reproduce**
1. https://9anime.to
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. ERR_CONNECTION_RESET https://9anime.to/

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/90744124/133878477-15b5e629-d571-4ae0-ad22-a2947c8c426c.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3960
