### ISSUE TITLE
Doujindesu changed domain

### ISSUE THREAD

**Issue by FransARV** [manga-download/hakuneko#3976]
**Doujindesu**

- Site: https://doujindesu.id/
- Manga List: https://doujindesu.id/komik-list/
- Manga example: https://doujindesu.id/manga/sisuana-sister-hole/
- Chapter online viewer example: https://doujindesu.id/2021/09/17/the-owner-of-a-building-chapter-13/

**Languages**
Indonesia

**Website relationship*
the domain has changed from info to id

**Additional details**

**Comment by 27136773** [comment]
Already supported, but they changed domain from `doujindesu.info` to `doujindesu.id`

**Comment by FransARV** [comment]
> Already supported, but they changed domain from `doujindesu.info` to `doujindesu.id`
Still not able
![1](https://user-images.githubusercontent.com/90978065/133926355-186effa1-2af6-47fc-9180-164be9914d7c.png)

**Comment by 27136773** [comment]
You have to wait until the ticket is closed...
If the ticket is still open, it means it is not fixed yet

**Comment by 27136773** [comment]
Seems they now also updated the WordPress template to the latest version ...
