### ISSUE TITLE
[Site Request] Actvid

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#3977]
**Name of the website**
Actvid

**Website urls (examples below)**
- Site: https://www.actvid.com/
- Manga List: https://www.actvid.com/filter?type=tv&quality=HD&release_year=all&genre=3&country=173
- Manga example: https://www.actvid.com/tv/watch-record-of-ragnarok-full-70324
- Chapter online viewer example: https://www.actvid.com/watch-tv/watch-record-of-ragnarok-full-70324.4235757

**Languages**
English

**Comment by MikeZeDev** [comment]
Its a general streaming website, should HN include those or be limited to anime? I guess we should stick to manga and anime websites.
