### ISSUE TITLE
add support Mangairo & Mangaromance

### ISSUE THREAD

**Issue by FAReaper1** [manga-download/hakuneko#398]
http://mangairo.com

http://mangaromance.eu

**Comment by FAReaper1** [comment]
I found something in Mangairo, when I opened the chapter, the website changed.
http://manganelo.com


![1](https://user-images.githubusercontent.com/54781955/64304941-f3566100-cfb7-11e9-9084-998421483f77.png)
![2](https://user-images.githubusercontent.com/54781955/64305231-da01e480-cfb8-11e9-9eb3-3a660814634e.png)

**Comment by 27136773** [comment]
added in master.
Will not be merged into 5.0.8
Mangas  whih are cross referencing to affiliate sites such as MangaNEL will not be shown in the manga list (use the corresponding website for those).
