### ISSUE TITLE
Mangapark & Mangadex issues

### ISSUE THREAD

**Issue by HighArbiter** [manga-download/hakuneko#3981]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The chapter list of both Mangapark and Mangadex are empty, with exception of already downloaded manga.
They both work fine in the actual site, however - and I can find the manga in the list, it simply says "chapters 0/0" in both MangaPark.org and MangaDex

**Screenshots**
![If no downloads](https://user-images.githubusercontent.com/90999767/133916344-2d661ebe-e562-4cc1-954e-555f745be750.jpg)

![If downloaded](https://user-images.githubusercontent.com/90999767/133916338-a249be2b-64cb-48df-90dd-fac2bfb5cc01.jpg)
**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by psduraes** [comment]
Good night,
Complementing the error on the Mangadex website, when listing the chapters of a manga
![image](https://user-images.githubusercontent.com/79729455/134266414-bb6cad26-5691-4598-8fcc-a6c7d16c6f72.png)

HakuNeko version: **rev. 6.1.7@c86d92**

**Comment by Druzai** [comment]
For Mangadex website the error occurs because they changed key `results` to `data`.
It was fixed in #3958 but not released yet.

**Comment by lockemx** [comment]
`MangaParkEN.mjs`
Line 55: `const lang = element.getAttribute("@click").match(/\((\w+)\)/)[1];`
Line 62: `this.url + "/ajax.reader.subject.episodes.by.serial",`

I didn't look at the test cases, but they don't fail so they would have to be improved to cover this failure in retrieving chapters.

**Comment by lockemx** [comment]
[MangeParkEN.patch](https://gist.github.com/lockemx/e8ebe89c290153495cf67d4c370cdf94)

It doesn't have multi-lingual support, but the original didn't seem to have it either. It showed a selection for each mirror rather than each language.
