### ISSUE TITLE
[Comick.fun] Connector not working

### ISSUE THREAD

**Issue by redfox367** [manga-download/hakuneko#3983]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Just to get it out of the way first, I don't know much about coding, I was told this was a connector error by Sheep#6615 in the help section of the discord. I just started with hakuneko today because I im going to be out of cell service for a few days next week so i wanted to download some manga as entertainment. If I go to the websites in my browser they work and i can read it but in hakuneko when i try and download anything it comes up with an error that says-

Click to re-download 
TypeError: Cannot read properly 'md_images' of undefined 

When I press it again to try and re-download it, it instantly comes up with the same error. And it wont let me preview the manga because it comes up with the same error as before. If you have anymore questions my discord is benjamin toelong#2963 and im free all day today

**To Reproduce**
1. Name of connector: md_images 
2. Name of manga (if connector update is working) one punch man chapter 1 English 
3. Name of chapter (if manga update is working) chapter 1
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

Click to re-download 
TypeError: Cannot read properly 'md_images' of undefined 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/63875483/133934116-df38e7a9-778f-45d4-86c2-d47031f8691b.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot help without name of website...

**Comment by redfox367** [comment]
> Cannot help without name of website...
Comick.fun

**Comment by 27136773** [comment]
See #3799
