### ISSUE TITLE
[Feature] request for a easy way to download new content

### ISSUE THREAD

**Issue by Mrbones2121** [manga-download/hakuneko#3984]
Could we get a download all button for the bookmarked pages? I have a lot of regularly updated content and going through each one is quite tiresome.

Having a way to select ether a group or all of the bookmarked content to download new or undownload content in mass would be awesome.

Alternatively having a system or notification that shows if content has not been downloaded or has  been updated could show besides the bookmarked content would be nice.  Adding a Toogle button for turning off the notification for undownloaded content for those who read instead of download. So they aren't stuck with constant notifications.

**Comment by 27136773** [comment]
Notification system is tracked by #653
Download all is a leeching feature and therefore against the philosophy of HakuNeko, use another tool (e.g. FMD2)
