### ISSUE TITLE
[1stkissmanga] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#3985]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The only site that does not respond is the one with the .com domain when I make the request in my browser. no son los dominios .io y .love espejos del .com

**To Reproduce**
1. 1stkissmanga
2. Any
3. Any
4. ERR_NAME_NOT_RESOLVED https://1stkissmanga.com/
    

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #3938
