### ISSUE TITLE
[Site Request] XXX Yaoi

### ISSUE THREAD

**Issue by nonlexy** [manga-download/hakuneko#3987]
**Name of the website**
xxxyaoi.com

**Website urls (examples below)**
- Site: https://xxxyaoi.com/
- Manga List: https://xxxyaoi.com/xxx/
- Manga example: https://xxxyaoi.com/bl/love-me-doctor/
- Chapter online viewer example: https://xxxyaoi.com/bl/love-me-doctor/capitulo-01/

**Languages**
Portuguese

**Website relationship*
maybe https://www.yaoitoshokan.net/

**Additional details**
Brazilian sites with a larger yaoi manga collection, we can either read in the format of chapters

**Comment by 27136773** [comment]
Looks like template `WordPressMadara`

**Comment by Jaxk69** [comment]
Duplicate #3911

**Comment by MikeZeDev** [comment]
Can be closed as duplicate @Sheepux pls <3
