### ISSUE TITLE
[Lezhin] Connector not working

### ISSUE THREAD

**Issue by jojokira** [manga-download/hakuneko#3989]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
New manhwas are not shown in the lezhin list and isn’t taken up even after copying the url.

**To Reproduce**
1. Lezhinus 
2. No kidding
3. All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
References: #2950

**Comment by 27136773** [comment]
Cannot be reproduced on my end, all 2 (free) chapters of the webtoon working as expected

----

![image](https://user-images.githubusercontent.com/27136773/134018309-145a6250-4f11-4cc8-a6ad-cbd050ee3a23.png)

**Comment by 27136773** [comment]
Make sure you setup correct login information for lezhin

**Comment by jojokira** [comment]
> Cannot be reproduced on my end, all 2 (free) chapters of the webtoon working as expected
> 
> ![image](https://user-images.githubusercontent.com/27136773/134018309-145a6250-4f11-4cc8-a6ad-cbd050ee3a23.png)

![image](https://user-images.githubusercontent.com/88510800/134018555-1e9e275d-9ff3-4f2d-915a-e919e5f53c6c.jpg) on my end I can’t access the new titles on lezhin idk why. Even by using the actual url it doesn’t show anything

**Comment by 27136773** [comment]
Just to be sure, you clicked the button to update the manga list?

**Comment by jojokira** [comment]
> Just to be sure, you clicked the button to update the manga list?

Yes thank you so much! Just had to update it again.
