### ISSUE TITLE
Can't download (Mangashiro)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#399]
i don't now why. but when i try to download ch. 40 - 44 from manga "Akaaka to Shita Chi no Monogatari" cannot be downloaded.
![capture](https://user-images.githubusercontent.com/45929526/64119546-52ec1b00-cdc4-11e9-8291-cdf889d489d4.PNG)

**Comment by MIRVOUS** [comment]
but when i try to preview the manga it works

**Comment by 27136773** [comment]
I cannot download, preview or even see the images on the website.
To me this looks like server issue...

----

![image](https://user-images.githubusercontent.com/27136773/64126139-f2051880-cdac-11e9-8406-3d2b8d042cb2.png)

**Comment by MIRVOUS** [comment]
no. in my browser is work when i see the website
![fmd2](https://user-images.githubusercontent.com/45929526/64251882-bbadd180-cf43-11e9-8dab-552100728d17.png)

**Comment by 27136773** [comment]
Was able to reproduce the issue with SG proxy server (no idea why this does not work without proxy, since images are stored on google...).
=> seems googleusercontent has some kind of region block

**Comment by 27136773** [comment]
Fixed for master
Will not be merged into 5.0.8
