### ISSUE TITLE
[MyReadingManga] Connector not working

### ISSUE THREAD

**Issue by SilverAsh4158** [manga-download/hakuneko#3990]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Doesn't load website in connector nor in update list.

**To Reproduce**
1)  In connector > MyReadingManga > open website in new window > "checking your browser before accessing..." > blank > F12 > "DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect"
2)  Copied specific manga link from website > HakuNeko clipboard > F12 > (screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/68351191/134373264-d5c676a0-e3d2-473b-841a-63fc5bd04310.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@c86d92

**Comment by 27136773** [comment]
See #2933
