### ISSUE TITLE
[Site Request] ComicBushi

### ISSUE THREAD

**Issue by tsenglol** [manga-download/hakuneko#3993]
**Name of the website**
Comic Bushiroad Web

**Website urls (examples below)**
- Site: https://comicbushi-web.com/
- Manga List: https://comicbushi-web.com/#lineup
- Manga example: https://comicbushi-web.com/episode/3269754496311077772
- Chapter online viewer example: https://comicbushi-web.com/episode/3269754496311077772

**Languages**
Japanese

**Website relationship*
Site reader same as tonari no young jump or magcomi

**Comment by Ever4engel** [comment]
use coreview template
