### ISSUE TITLE
[yugenmangas] Connector does not work by web update

### ISSUE THREAD

**Issue by kuvoid** [manga-download/hakuneko#3997]
hello,

hakuneko has stopped working on yugenmangas.com as it has changed its design.

**Comment by SaitoGlutton** [comment]
Disculpe Sr.Daniel pero le puedo decir unos errores de unas cuantas páginas.. es que no se muy bien el mandar mi problema ya que aun que lo mande creo que lo hago mal.( menos mal que reporto ese problema creía que ya no descargaría mas en esa pagina xd)
