### ISSUE TITLE
[Site Request] Cmoa

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#3999]
**Name of the website**
    cmoa

**Website urls (examples below)**
- Site: https://www.cmoa.jp/
- Manga List: https://www.cmoa.jp/genre/20/
                      https://www.cmoa.jp/genre/2/
- Manga example: https://www.cmoa.jp/title/115225/
- Chapter online viewer example: https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000115225_jp_0001&u0=1&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Ftitle%2F115225%2F

**Languages**
   Japanese

**Comment by Ever4engel** [comment]
Duplicate #2307
