### ISSUE TITLE
two manga sites will not work any more in Hakuneko

### ISSUE THREAD

**Issue by maryann411** [manga-download/hakuneko#400]
the web site are Zinmanga.com, and 1stkissmanga.com, first they work great, but when i try to up date them in web site client on the Hakuneko display box, they disappeared client  for display box .
My system is Acer 64 Operating,Window 10 Pro, client is 507 Hakuneko upgrade, 2019 HakuNeko rev.f9ad59.
and yes they  both show up in my browser, but i real would like them  to show up back in the replay box on the Hakuneko please,then it would be much more easier to download for there.

**Comment by 27136773** [comment]
Solved with 57ecda18
Will not be merged into 5.0.8
