### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by whghjyh** [manga-download/hakuneko#4000]
I found this quite useful item by searching.I think this software can solve my needs and many people's needs.However, This software seems to be only in English.I think such excellent software can help more people not just English speakers..Could you publish the translation file and let us help translate it?Thank you a lot.

**Comment by 27136773** [comment]
Software was not designed to be localized
=> won't implement since this is a massive amount of work

**Comment by whghjyh** [comment]
Okay, I can understand.:ok_hand:
