### ISSUE TITLE
[MangaPlus] Connector not working

### ISSUE THREAD

**Issue by moostalo** [manga-download/hakuneko#4002]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The language displayed in the title is not correct can be confusing. For this example it is indicated in spanish however based on the title is written in french. 

**To Reproduce**
1. Mangaplus

**Screenshots**
![Mangaplus language](https://user-images.githubusercontent.com/71948230/134815352-8a85f407-6fe5-4af0-85f6-21f805f14160.png)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by Ever4engel** [comment]
They added French language today.
wait for a fix

**Comment by Ever4engel** [comment]
@ronny1982 and the language tag isn't correct 
![image](https://user-images.githubusercontent.com/47645041/135126276-14a2c831-c278-4bb4-bf60-595d0aeec191.png)
all those are available languages worldwide: French, english, Spanish, Portuguese, Russian and indian.  (don't need a vpn)

**Comment by Zarh** [comment]
Could it be possible to use the combo box for languages like it's done for mangadex ?
Also, it doesn't detect the chapter number, %CH% doesn't work.

**Comment by Zarh** [comment]
It might helps you.
The website is using a new version to grab the list of mangas : https://jumpg-webapi.tokyo-cdn.com/api/title_list/allV2
The protocole buffer probably need to be updated too : https://mangaplus.shueisha.co.jp/js/app.a4c690d6.js

**Comment by Ever4engel** [comment]
https://github.com/manga-download/hakuneko/pull/4358

**Comment by MikeZeDev** [comment]
PR fixed the problem? This can be closed?
