### ISSUE TITLE
[Site Request] realmscans

### ISSUE THREAD

**Issue by Mammad211** [manga-download/hakuneko#4005]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://realmscans.xyz
- Manga List: https://realmscans.xyz/series
- Manga example: https://realmscans.xyz/series/it-starts-with-a-mountain/
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
En

**Comment by 27136773** [comment]
Template: `WordPressMadara`

**Comment by MikeZeDev** [comment]
Redirect to https://realmscans.com/
Website is supported

@Sheepux pls <3
