### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Akhilkrishnauk** [manga-download/hakuneko#4006]
The program is completely broken or something, nothing loads. Its stuck on a white screen on launch. 
 
Installed the macapp from the github releases and also tried the one in the AUR on my arch system, both have the exact same problem.

just a white screen and nothing else.

Program doesnt even quit normally, i have to force quit it to even close.

Attaching an image rn of the issue. the one on the left is hakuneko

![pic-full-210927-2206-25](https://user-images.githubusercontent.com/48402475/134949855-f2a9afe1-2566-4291-956b-8884b3cd1f08.png)

**Comment by Sheepux** [comment]
https://hakuneko.download/docs/troubleshoot/#is-the-screen-blankblack-when-starting-hakuneko
+ refer #13
