### ISSUE TITLE
[https://lectortmo.com/] Connector not working https://lectortmo.com/

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#4008]
After a few minutes of being used it becomes like this and does not load any series or chapter.

And it also presents continuous errors during downloads 

![Sin título](https://user-images.githubusercontent.com/53885246/135388876-cbcf3dcc-c168-4286-9997-650f6e1878f3.jpg)

**Comment by Sheepux** [comment]
duplicates closing in favor of #4622
