### ISSUE TITLE
Preview manga not work (BacaManga)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#401]
![1](https://user-images.githubusercontent.com/45929526/64251143-f7e03280-cf41-11e9-995b-eafc7994eefa.PNG)
![2](https://user-images.githubusercontent.com/45929526/64251145-f878c900-cf41-11e9-9f12-88fa90ae9fa6.png)
![3](https://user-images.githubusercontent.com/45929526/64251147-f878c900-cf41-11e9-984f-756d306909c7.PNG)

**Comment by MIRVOUS** [comment]
I tried to preview the manga and it didn't work, so I tried to download it and the folder was empty.
and i tried the other but result is same

**Comment by 27136773** [comment]
Fixed for master
Will not be merged into 5.0.8
