### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wedgingt** [manga-download/hakuneko#4010]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**

When starting hakuneko, there is an error, sometimes repeated more than once:
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

This does not appear to affect things later but it's hard to be sure.  It did update once on its own and I tried reinstalling from the existing *.deb file after upgrading to Ubuntu 20.04.3, but the error still appears.

**Expected behavior**
No error message.

**Context (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS - the error was not there with Ubuntu 18.04.
 - HakuNeko Version: 6.1.7

**Comment by 27136773** [comment]
HakuNeko is probably run on a system with incompatible `glibc`.
The electron version of HakuNeko will not be updated anymore, therefore this cannot be fixed.
Try using the nightly version which is build on electron 8.

References:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1025739
- https://github.com/electron/electron/issues/22291
