### ISSUE TITLE
[Manga World] Connector not working

### ISSUE THREAD

**Issue by soymuchocalor** [manga-download/hakuneko#4012]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I choose manga world connector but does not load mangas list. It continues to load without any list. They changed their domain again.

**To Reproduce**
1. Name of connector Manga world
2. Name of manga any
3. Name of chapter 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by bubba11985** [comment]
Is it possible to update hakuneko nightly version ? Thanks

**Comment by terluc** [comment]
> **Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)** Yes
> 
> **Is the website of the connector working properly / are you able to see the manga within your browser** Yes
> 
> **Describe the bug** I choose manga world connector but does not load mangas list. It continues to load without any list. They changed their domain again.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Name of connector Manga world
> 2. Name of manga any
> 3. Name of chapter
> 4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
> 
> **Screenshots** If complex to describe, add screenshots to help explain your problem.
> 
> **HakuNeko (please complete the following information):**
> 
> * Version [e.g. 6.17]

Hi, to make it work, as wrokaround, open with any editor the file "cache/mjs/connectors/MangaWorld.mjs" (on windows "cache\mjs\connectors\MangaWorld.mjs" ), and modify the line n.11 (in this way -->  this.url = 'https://www.mangaworld.in';  <--) . Put the file in read-only mode after saving it. Remember to put it in R/W before the next update :)
