### ISSUE TITLE
Narrow and long image downloads

### ISSUE THREAD

**Issue by animeandme** [manga-download/hakuneko#4013]
Hello, I just want to ask why my downloads look very narrow and long? When I convert it to epub it looks like that. 
![456C4E26-DBD4-4228-90EA-65C8C2FE9F37](https://user-images.githubusercontent.com/91728207/135598632-9a199874-e25e-4e02-9ae6-b2d59eb1d24a.png)

**Comment by l-l-l-l-l-l** [comment]
That's a single-strip webcomic. It comes like that from the source.

**Comment by animeandme** [comment]
> That's a single-strip webcomic. It comes like that from the source.

What can I do to fix this? Is it possible? If not, can you recommend a site where I can download with good image size and quality? Thank you very much!

**Comment by 27136773** [comment]
Post-processing (crop/split) with corresponding image editing tools.
You have to search on your own which other websites fit your desires.
