### ISSUE TITLE
[Mangaworld] Connector not working

### ISSUE THREAD

**Issue by bubba11985** [manga-download/hakuneko#4014]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Mangaworld.io changed to mangaworld.in

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version nightly 8.3.4

**Comment by 27136773** [comment]
See #4012
