### ISSUE TITLE
[Mangafreak] Connector not working

### ISSUE THREAD

**Issue by Asia81** [manga-download/hakuneko#4015]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error timout when trying to load-update the list of manga.

**To Reproduce**
1. Mangafreak
2. -
3. -
4. Can't open error console while error pop-up is shwon (f12 doesn't work)

**Screenshots**
Screen : https://zupimages.net/up/21/39/mjax.png

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See #2933
