### ISSUE TITLE
How to fix extenson %CH% for ac.qq.com

### ISSUE THREAD

**Issue by kbnduy12** [manga-download/hakuneko#402]
Hi everyone, I want to change the chapter name to chapter 1,2,3 or whatever, extenson like above does not work, so is there any way, please help me?

**Comment by 27136773** [comment]
It seems to me like the chapters don't have a number at all.
HakuNeko cannot provide a chapter number if there is none.

----

![image](https://user-images.githubusercontent.com/27136773/64276111-6c69a000-cf47-11e9-94a8-324f150c1c09.png)

**Comment by 27136773** [comment]
Seems this cannot be achieved=> closed

**Comment by kbnduy12** [comment]
You can set it to add an extenson which is download from start to finish
and then you can follow it by marking the number of chapters?

Vào Th 3, 10 thg 9, 2019 vào lúc 03:50 ronny1982 <notifications@github.com>
đã viết:

**Comment by 27136773** [comment]
Using the index as chapter number is to error prone.
The website just needs to insert a new chapter in between the list, and all downloaded chapters can no longer be linked to their related online chapter, in worst case they are linked to the wrong chapter.
