### ISSUE TITLE
[Readm.org] Connector not working

### ISSUE THREAD

**Issue by jhung0301** [manga-download/hakuneko#4022]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not able to fetch the chapter list even though the website is accessible and can read.

**To Reproduce**
1. https://readm.org/
2. A Capable Maid
4. Failed to load resource: net::ERR_FILE_NOT_FOUND

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end, chapters are loading fine.
The `resource: net::ERR_FILE_NOT_FOUND` is probably shown because you have no custom plugins installed for HakuNeko.

**Comment by MikeZeDev** [comment]
Cant reproduce too. Worth closing?

**Comment by MikeZeDev** [comment]
@Sheepux pls <3
