### ISSUE TITLE
page error [TuMangaOnline]

### ISSUE THREAD

**Issue by djgerman10** [manga-download/hakuneko#403]
page error does not go

![1](https://user-images.githubusercontent.com/48584512/64363082-1c8de600-cfe6-11e9-964a-c51fcbd57a95.png)

![2](https://user-images.githubusercontent.com/48584512/64363218-755d7e80-cfe6-11e9-89e1-034fa4fa7c5a.png)

**Comment by 27136773** [comment]
See: #335
