### ISSUE TITLE
[Bug] Number is not changing in bookmark section when new chapters are updated              Steps to reproduce: 1. Go to 'webtoon.xyz' 2. Sign in 3. click on bookmark section 4. see the number doesnot change when new chapters are updated             Expected behaviour - When new chapters are updated numbers indicating unread chapters in bookmark section should change           Context: OS -Windows 10

### ISSUE THREAD

**Issue by Dark8203** [manga-download/hakuneko#4030]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Please create tickets by editing the template and not writing hundreds of words into the title
