### ISSUE TITLE
[Bug] Handling manga between Windows and Linux in dual boot system

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4031]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I have dual boot system Windows and Ubuntu and (I have an app on Windows that can read ext4 partition) stored all the manga on Linux directory and also connect the downloaded manga directory of hakuneko Windows to Linux. Good news is Hakuneko for Linux can read all the manga chapters. But, Hakuneko Windows claim the chapters are missing. 

**To Reproduce**
1. on hakuneko Windows, I click to three lines on the top left and 
2. change the manga directory to E:/home/user/Documents/Mangas
3. Scroll down to selected manga
4. many chapters are gone

**Expected behavior**
I expect hakuneko for Windows can read the Linux directory

**Screenshots**
![2021-10-09_00-04](https://user-images.githubusercontent.com/29157187/136581547-861ef91c-f061-488e-91b6-039be6992690.png)
(This is Linux directory)

![2021-10-09_00-04_1](https://user-images.githubusercontent.com/29157187/136581616-fa4cb571-0722-4e7f-a4b9-4054e435958d.png)
The mangas on Linux directory are completely downloaded 

<img width="348" alt="Screenshot_2021-10-09_00-01-24" src="https://user-images.githubusercontent.com/29157187/136581781-55386a6b-d325-41d6-8d40-caf76f6e4b26.png">
I connect the directory of hakuneko Windows to Linux

<img width="390" alt="Screenshot_2021-10-09_00-01-08" src="https://user-images.githubusercontent.com/29157187/136581895-b1519491-b9fc-4c4f-b912-a41111e01292.png">
Hakuneko for Windows claim that the chapters are missing

**Context (please complete the following information):**
 - OS: Windows 10 and Ubuntu 
 - HakuNeko 6.1.7

**Additional context**
Is this related to the ntfs partition cannot handle ext4 partition, despite I have an app that can read and write ext4 partition on Windows?

**Comment by spyoff** [comment]
I believe this is not a bug, this is the expected behaviour of ext4 partition on windows.
Hakuneko is a web-app packaged by electron, thus it utilise the chromium engine to do things.
The easiest comparison is with google chrome, if your windows 10 google chrome can download files (save files) directly to the ubuntu ext4 partition, but Hakuneko not able to do that, than it's a bug.
If windows 10 google chrome exhibit the same behaviour, then it's not a bug.

**Comment by dnet890** [comment]
the strange thing is I can download my files (mp3,jpeg, zip etc) from Edge browser (Win10) and set the download directory to the Linux partition without any data loss issues. But, hakuneko behave differently with some of my manga chapters are gone. Honestly, I never did it in reverse (set the manga directory to Win10 and Hakuneko Win10/Linux can access the manga directory) which can cause similar effect. any thoughts about this?

**Comment by 27136773** [comment]
Even with the portable version there would be limitations, as `windows` has a different set of forbidden characters that can be used in the file path than `linux`.

**Comment by dnet890** [comment]
@ronny1982  to sum up that means, dual booting and use manga directory between OS is impossible. Is that so?

**Comment by spyoff** [comment]
it is possible, but need to have common filesystem that can be accessed natively by both OS, e.g: you have FAT32 partitions to store your manga, then it can be read by windows and linux natively.

**Comment by dnet890** [comment]
I have external hdd in exfat (better and newer than fat32) partition. But, hakuneko cannot detected it. I suppose hakuneko cannot detect external hdd. Is that so?

**Comment by spyoff** [comment]
Can you try to download a file using google chrome (must google chrome, no firefox or edge or etc) in both OS, and save file to that partition?

**Comment by dnet890** [comment]
Yes, I can download files using Google chrome and save to ext4 partition without issues.

**Comment by spyoff** [comment]
After looking at your screenshot, I think the issues is not the partitions itself, but rather on how windows vs linux handles the filename. On your example (in the screenshot), the filename that cannot be read in windows is the filename that contains `:` character in it.

**Comment by dnet890** [comment]
if this is part of a technical limitation. I think it is fine. But, I might try to connect the manga directory to other internal HDD with blank NTFS/exfat partition. it might create interesting result
