### ISSUE TITLE
[Site Request] NetTruyen

### ISSUE THREAD

**Issue by thiennhing** [manga-download/hakuneko#4032]
**Name of the website**
Nettruyen

**Website urls (examples below)**
- Site: http://www.nettruyenpro.com/
- Manga List: http://www.nettruyenpro.com/tim-truyen
- Manga example: http://www.nettruyenpro.com/truyen-tranh/dao-hai-tac-9169
- Chapter online viewer example: http://www.nettruyenpro.com/truyen-tranh/dao-hai-tac/chap-1027/771035

**Languages**
Vietnamese

**Comment by 27136773** [comment]
Already supported, but changed domain

**Comment by thiennhing** [comment]
@ronny1982 yes, it changed to http://www.nettruyenpro.com/ 
So... can't fix it right? Sorry if it's a stupid question but I don't understand clearly.
