### ISSUE TITLE
[Ganma] Connector not working

### ISSUE THREAD

**Issue by Niko200104** [manga-download/hakuneko#4033]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Some mangas i need to download (双無しの人形 and others) are not listed in the ganma connector, and copying the link (https://ganma.jp/theoriginaldoll) also doesn't work.
Other problems: the last chapters that you can read ahead of time with the subscription aren't listed either, and when i download a chapter it doesn't download the afterword image, which thends to be a part of the chapter

**To Reproduce**
1. Ganma
2. Open page and log in
3. 双無しの人形

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
Due to lack of account and subscription i cannot help with this.

You may try to run the following JavaScript on page https://ganma.jp/theoriginaldoll while logged in.
Without login/subscription it only shows 5 chapters, no idea what will be shown with valid login/subscription...
```javascript
(async function() {
    const response = await fetch('https://ganma.jp/api/1.0/magazines/web/theoriginaldoll', { headers: { 'x-from': 'https://ganma.jp/' } });
    const data = await response.json();
    const chapters = data.root.items.map(item => {
        return {
            id: item.id,
            kind: item.kind,
            title: `${item.title} - ${item.subtitle}`,
            images: item.page.files
        };
    });
    console.log('CHAPTERS:', chapters);
})();
```

Furthermore, HakuNeko is currently set to [only show free chapters](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/Ganma.mjs#L49) and ignores anything else.

**Comment by Niko200104** [comment]
Okay, I understood the "only free chapters" issue, and was actually able to disable it locally, but i still don't understand why many mangas are not listed.

When i ran the JavaScript, it showed a list of 83 chapters (the total number of chapters), so i guess it works, but the issue is the manga not being showed on the list (left box in the hakuneko interface)
![Captura](https://user-images.githubusercontent.com/88807932/136673979-15ebeae4-746c-45b6-bb23-fd9b336fe9de.PNG)

**Comment by Niko200104** [comment]
Nevermind, it worked, i just hadn't see the fixes because i'm not familiar with github. big thanks.
