### ISSUE TITLE
[https://mangagecesi.com/] Connector not working

### ISSUE THREAD

**Issue by By-PorfecTo** [manga-download/hakuneko#4041]
Unable to access manga list.
![ScreenShot_20211009232256](https://user-images.githubusercontent.com/92230690/136672933-04902b02-370e-45fa-bdde-1ba3b3d8d17c.png)
new website..
![ScreenShot_20211009232335](https://user-images.githubusercontent.com/92230690/136672949-b7a9aff7-9650-430f-ad32-ab94310ec56a.png)mangagecesi.mjs çalışmıyor..
mangagecesi.mjs is not working..
![ScreenShot_20211009232658](https://user-images.githubusercontent.com/92230690/136672985-79e5e58e-dd82-42ae-9ecf-89a1d67c6f43.png)
 Hoping to fix it as soon as possible...

**Comment by Sterbenm** [comment]
> manga listesine erişilemiyor.. ![ScreenShot_20211009232256](https://user-images.githubusercontent.com/92230690/136672933-04902b02-370e-45fa-bdde-1ba3b3d8d17c.png) yeni site.. ![ScreenShot_20211009232335](https://user-images.githubusercontent.com/92230690/136672949-b7a9aff7-9650-430f-ad32-ab94310ec56a.png) mangagecesi.mjs çalışmıyor.. ![ScreenShot_20211009232658](https://user-images.githubusercontent.com/92230690/136672985-79e5e58e-dd82-42ae-9ecf-89a1d67c6f43.png) En kısa sürede düzeltmeniz dileği ile...

Write it in English pls

**Comment by By-PorfecTo** [comment]
The site is logged out of wordpress scripts so it doesn't work

**Comment by ghost** [comment]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
When I click the update button, icon spin. When icon stop spinning, nothing happen, Manga List is still empety. (Note: Clipboard is not working too.)
The website is switched to the new scripts. So WordPress Madara scripts not working.

**New website urls**
- Site: https://mangagecesi.com
- Manga List: https://mangagecesi.com/cizgi-romanlar
- Manga example: https://mangagecesi.com/cizgi-romanlar/ofis-oykumuz
- Chapter online viewer example: https://mangagecesi.com/cizgi-romanlar/ofis-oykumuz/bolum-1

**To Reproduce**
Steps to reproduce the behavior:
1. Manga Gecesi
2. Click update button
3. Connector update isn't working

**Screenshots**
![resim](https://user-images.githubusercontent.com/59330357/146513368-569a8bdd-2a0c-4f2d-a228-b5c496167420.png)

**HakuNeko (please complete the following information):**
 - Version Version 6.17@9436d8 and master@e334bc

**Comment by MikeZeDev** [comment]
Cloudflare :/

**Comment by MikeZeDev** [comment]
They closed the website.
