### ISSUE TITLE
[MangaGecesi] Connector not working

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#4043]
they switched to the new script, it doesn't download,  they are doesn't using madara now..

**Comment by 27136773** [comment]
See #4041

**Comment by canlost** [comment]
Both tickets were closed without a problem.
please update hakuneko

**Comment by canlost** [comment]
@ronny1982

**Comment by 27136773** [comment]
#4041 is not `Closed`, it is still `Open`
