### ISSUE TITLE
[KissMangaWebsite] Connector not working

### ISSUE THREAD

**Issue by MpVrooyeN** [manga-download/hakuneko#4044]
As title shows the KissMangaWebsite connector isnt working. No chapters of anything is being shown however names of mangas are. Keep getting the error "cannot read property href or undefined" when trying to synchronize.

**Comment by 27136773** [comment]
Is the website working for you?
I cannot reach the domain...
https://kissmanga.website

**Comment by MpVrooyeN** [comment]
No it's not working. They seem to have changed it. The kissmanga that I can
use on my browser is kissmanga.nl. They have a lot of the stuff I'm looking
for.

**Comment by 27136773** [comment]
The website http://kissmanga.nl is just one of the `AnyACG` mirrors, such as [manganelos](http://manganelos.com), create a new ticket if this should be added...

Regarding this ticket, `KissMangaWebsite` shall be removed from HakuNeko as the website seems to be dead.
