### ISSUE TITLE
[Site Request] Comikey.com

### ISSUE THREAD

**Issue by lord-ne** [manga-download/hakuneko#4045]
**Name of the website**
Comikey

**Website urls (examples below)**
- Site: https://comikey.com/
- Manga List: https://comikey.com/comics/ (UI) or https://comikey.com/sapi/comics (API)
- Manga example: https://comikey.com/comics/cursed-sword-manga/35/ (UI) or https://comikey.com/sapi/comics/35 (API)
- Chapter online viewer example: https://comikey.com/read/cursed-sword-manga/qD0ZEo/chapter-1/ (UI) or https://comikey.com/sapi/comics/35/read?format=json&content=EPI-qD0ZEo (API)

**Languages**
English

**Additional details**
Official manga translations. Has some free chapters and some paid chapters. Has Clouflare protection. There is a [Tachiyomi extension](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/27a785e15e4a427ee8cd52b47ec1b91403d27257/src/en/comikey/src/eu/kanade/tachiyomi/extension/en/comikey/Comikey.kt), but it's currently not working because of the Cloudflare protection.

**Comment by 27136773** [comment]
See: #3894
