### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by noviemamalateo05** [manga-download/hakuneko#4049]
**Is your feature request related to a problem? Please describe.**
I want to hide the window for HakuNeko when being used while I'm doing something else.

**Describe the solution you'd like**
I suggest that minimizing the app will minimize it to tray like uTorrent, telegram, zoom or similar desktop apps.

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - HakuNeko verion 6.1.7

**Additional context**
Courtesy: uTorrent [https://www.utorrent.com/]
Image 1: Windows tray icon
![image](https://user-images.githubusercontent.com/62878983/136847254-c9ec1ae6-e4d1-4634-aa8c-07b35f4b3949.png)

Image 2: Right-clicked tray icon
![image](https://user-images.githubusercontent.com/62878983/136847397-1eb3f8be-ffb8-42e4-9991-e9f55cec3350.png)

Image 3: System tray settings inside the software
![image](https://user-images.githubusercontent.com/62878983/136847654-7891a4cd-01e9-4f95-b3f8-6d7e9b6a8661.png)

**Comment by 27136773** [comment]
See: #412
