### ISSUE TITLE
need help with 400 issues please help

### ISSUE THREAD

**Issue by maryann411** [manga-download/hakuneko#405]
hakuneko, were do i get this up date code or how do i add this code in to client hakuneko 508 it has no were to add code and I'm a newbie to this. please help me fix this.

**Comment by 27136773** [comment]
You cannot add it to 5.0.8, it can only be updated by a developer.
I cannot do it, there is to much maintenance work to do.

Either use the nightly build at your own risk, or wait for release 6.x.x

**Comment by 27136773** [comment]
I think this question should be answered => closed

**Comment by maryann411** [comment]
thank i will wait for up date thank
