### ISSUE TITLE
Cocomanga Connector not working

### ISSUE THREAD

**Issue by mancancry** [manga-download/hakuneko#4050]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can see manga's name but after click download give a error

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random manga.
Please provide sample manga and chapter.

**Comment by MikeZeDev** [comment]
Problem is cloudflare, we got 403 error in console while updating manga list. Curl confirm its cloudflare.

**Comment by MikeZeDev** [comment]
base64 not found. i guess they changed the protection again.

**Comment by MikeZeDev** [comment]
Fixed
