### ISSUE TITLE
[Site Request] MangaDig

### ISSUE THREAD

**Issue by NhimxuCR** [manga-download/hakuneko#4053]
**Name of the website**
MangaDig

**Website urls (examples below)**
- Site: https://mangadig.com/
- Manga List: https://mangadig.com/show
- Manga example: https://mangadig.com/10445/
- Chapter online viewer example: https://mangadig.com/10445/1/261.html

**Languages**
English

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/3731
