### ISSUE TITLE
[Site Request] MangaOwl

### ISSUE THREAD

**Issue by NhimxuCR** [manga-download/hakuneko#4054]
**Name of the website**
Mangaowls

**Website urls (examples below)**
- Site: https://mangaowls.com/
- Manga List: https://mangaowls.com/popular
- Manga example: https://mangaowls.com/single/48021/the-beginning-after-the-end
- Chapter online viewer example: https://mangaowls.com/reader/48021/1441550/0?tr=oOjIYBTzxRTXyFzQvQk%2Bcw%3D%3D&s=aHR0cHM6Ly9tYW5nYW93bHMuY29t

**Languages**
English

**Comment by 27136773** [comment]
Same website as #2335, but under a different domain
