### ISSUE TITLE
[Site Request] Manga Chill

### ISSUE THREAD

**Issue by Silo-K** [manga-download/hakuneko#4055]
**Manga Chill**
Manga Chill

**Website urls (examples below)**
- Site: https://mangachill.com/
- Manga List: https://mangachill.com/manga-genre/fantasy/
- Manga example: https://mangachill.com/manga/true-beauty-all-chapterss/
- Chapter online viewer example: https://mangachill.com/manga/true-beauty-all-chapterss/chapter-165/

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `WordPressMadara`
