### ISSUE TITLE
[Site Request] Madaradex

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4057]
**Madaradex**
MadaraDex

**Website urls (examples below)**
- Site: https://madaradex.org/
- Manga List: https://madaradex.org/tags/manga/
- Manga example: https://madaradex.org/title/tokyo-revengers/
- Chapter online viewer example: https://madaradex.org/title/tokyo-revengers/chapter-225/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `WordPressMadara`
