### ISSUE TITLE
[Site Request] mangafoxfull

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4058]
**Mangafoxfull**
Mangafoxfull

**Website urls (examples below)**
- Site: https://mangafoxfull.com/
- Manga List: https://mangafoxfull.com/manga/
- Manga example: https://mangafoxfull.com/manga/mairimashita-iruma-kun/
- Chapter online viewer example: https://mangafoxfull.com/manga/mairimashita-iruma-kun/chapter-223/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `WordPressMadara`
