### ISSUE TITLE
[Site Request] mangahere.today

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4059]
**mangahere.today**
mangahere.today

**Website urls (examples below)**
- Site: http://mangahere.today/
- Manga List: http://mangahere.today/latest-manga
- Manga example: http://mangahere.today/manga/kimetsu-no-yaiba
- Chapter online viewer example: http://mangahere.today/kimetsu-no-yaiba-chapter-205.5#1

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `AnyACG`
