### ISSUE TITLE
[Site Request] mangame

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4060]
**mangame**
mangame

**Website urls (examples below)**
- Site: https://mangame.org/
- Manga List: https://mangame.org/manga/?m_orderby=rating
- Manga example: https://mangame.org/manga/fairy-tail-100-years-quest/
- Chapter online viewer example: https://mangame.org/manga/fairy-tail-100-years-quest/chapter-92/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `WordPressMadara`
