### ISSUE TITLE
[MangaLivre] Connector not working

### ISSUE THREAD

**Issue by felipe-negri** [manga-download/hakuneko#4061]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
error to download list chapters from manga and open a download file name download

**To Reproduce**

1. List a chapters with url https://mangalivre.net/manga/boku-no-hero-academia/1319

**Screenshots**
![image](https://user-images.githubusercontent.com/27769172/137233503-0d76a6a1-30a9-45a5-aa43-bd4a44083ca5.png)

**HakuNeko**
 - Version [e.g. 6.17@0084ac]

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Try to open a chapter of the corresponding manga with [manual website interaction](https://hakuneko.download/docs/manual-website-interaction/) before downloading.

**Comment by felipe-negri** [comment]
on manual website interaction occurs the log is like this and the download page opens.
![image](https://user-images.githubusercontent.com/27769172/140098891-e8c79176-2bdd-4570-8161-be0cbbc2dd31.png)
![image](https://user-images.githubusercontent.com/27769172/140098927-e6752618-341a-4f56-a6ef-8c50e8ac8927.png)

on linux download i found this issues
![Screenshot_20211103_132834](https://user-images.githubusercontent.com/27769172/140102131-fe5693d1-622d-4fd9-acd0-02b5c4608d86.png)

the chapter list and request to get images of chapter works fine but this error appears on the console

![Screenshot_20211103_132938](https://user-images.githubusercontent.com/27769172/140102185-08870e47-f8ad-4600-b08b-811ca5750ca2.png)
this is the version of hakuneko, fresh install
![Screenshot_20211103_133420](https://user-images.githubusercontent.com/27769172/140103053-5b62c73f-832d-478a-8d1b-50fd59628b74.png)

**Comment by felipe-negri** [comment]
on linux download i found this issues
![Screenshot_20211103_132834](https://user-images.githubusercontent.com/27769172/140102131-fe5693d1-622d-4fd9-acd0-02b5c4608d86.png)

the chapter list and request to get images of chapter works fine but this error appears on the console

![Screenshot_20211103_132938](https://user-images.githubusercontent.com/27769172/140102185-08870e47-f8ad-4600-b08b-811ca5750ca2.png)
this is the version of hakuneko, fresh install
![Screenshot_20211103_133420](https://user-images.githubusercontent.com/27769172/140103053-5b62c73f-832d-478a-8d1b-50fd59628b74.png)

**Comment by marcosbenevides** [comment]
Guys, i found the solution to download via Manga Livre.

This code is trying to do a replace on a object, on Chapter.js::115
`this.pageCache = Array.isArray(pages) ? pages.map(page => page.replace(/\/i\d+\.wp\.com/, '')) : pages;`

On my machine i change to:
`this.pageCache = Array.isArray(pages) ? pages.map(page => page.legacy.replace(/\/i\d+\.wp\.com/, '')) : pages;`

And it worked, I was able to download the episodes.

**Comment by felipe-negri** [comment]
I just downloaded the github project and put it to download without changing any code and it worked normally.
may be a problem with the executable in production.

**Comment by MikeZeDev** [comment]
Cloudflare acces crap. Doesnt work in my browser, geoblocked?

**Comment by Feliposo21** [comment]
still not working  
![image](https://user-images.githubusercontent.com/83885392/197337101-eccebf12-a15f-440f-a5a0-39b8a58e594e.png)

**Comment by MikeZeDev** [comment]
I didnt say the issue mentioned would help. I mentioned it because its same site, and a possible duplicate

Anyway, there is this damn Cloudflare crap that prevent dev to debug that unless they test with a VPN with PT ip address.
OR may totally block them because HN cant deal with Cloudflare when the security is set too high.

Either way, the problem is accessing the website in the first place :/ .

**Comment by Rodrigo-017** [comment]
Apparently, the connector doesn't work at all here. I fixed the errors myself but the connector said it can't find images for the pages. The connector needs a update on the code.
![error](https://github.com/manga-download/hakuneko/assets/137452679/81affbe4-eef9-4879-bce0-f849a4077bbf)

**Comment by MikeZeDev** [comment]
Sadly you are on you own. Cant check because i cant access the website.

**Comment by Rodrigo-017** [comment]
> Sadly you are on you own. Cant check because i cant access the website.

Use a Brazil VPN.

**Comment by MikeZeDev** [comment]
IKR .I have 2 vpn none of them gimme brazilian IP and in dont want to screw my windows with another vpn.

**Comment by Rodrigo-017** [comment]
If only someone have access to this site and figure out what's causing this error on the code... I guess this is not the only connector that doesn't work properly I guess, there are plenty of others.


> IKR .I have 2 vpn none of them gimme brazilian IP and in dont want to screw my windows with another vpn.

Why don't try UrbanVPN? They have Brazil for free.

**Comment by MikeZeDev** [comment]
Website is useless, there is no content
