### ISSUE TITLE
[Mangas Origines] Connector not working

### ISSUE THREAD

**Issue by ShiroiOukami** [manga-download/hakuneko#4067]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I click on the title I want, a download window asks me to download a file called "download" and nothing happens. And the chapters of a manga do not appear.

**To Reproduce**
1. Mangas Origines
2. Name of manga (takes randomly)
3. Name of chapter (chapters doesn't appear)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\callbacks-registry.js:41 Uncaught (in promise) Error: ERR_FAILED (-2) loading 'https://mangas-origines.fr/'
    at rejectAndCleanup (C:\Program Files\HakuNeko Desktop\resources\electron.asar\browser\navigation-controller.js:67:29)
    at WebContents.stopLoadingListener (C:\Program Files\HakuNeko Desktop\resources\electron.asar\browser\navigation-controller.js:107:17)
    at WebContents.emit (events.js:200:13)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end with random manga.
Please provide sample manga / chapter ...

**Comment by ShiroiOukami** [comment]
> Cannot be reproduced on my end with random manga. Please provide sample manga / chapter ...

This for example : Edens Zero, chapter 1

**Comment by MikeZeDev** [comment]
Update the manga list > test Eden Zero chapter 1, working. tested other manga, works too.  Using nightly .

**Comment by MikeZeDev** [comment]
Cloudflare issue.
Websites doesnt even load in browser now. Geoblocked? But its a freaking french website and i use a french ip, thats ridiculous.

**Comment by MikeZeDev** [comment]
Updating manga list preview and download (Zero game) works fine. 

Can be closed?

**Comment by MikeZeDev** [comment]
Closed as Cloudflare is removed
