### ISSUE TITLE
[9ANIME] Connector not working

### ISSUE THREAD

**Issue by RvBCHURCH6669** [manga-download/hakuneko#4068]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can download Manga but I can't download the Anime and I have no idea why

**To Reproduce**

1. 9Amine
2. Is It Wrong to Try to Pick Up Girls in a Dungeon?
3. Is It Wrong to Try to Pick Up Girls in a Dungeon?
4. DownloadJob.mjs:223 GET https://pro5.vidstream.pro/1126/stream1/EqPFI_kQBAro1HhYl67rC8EurFwU5LizFAV7rqk+wIMmUtcbRWEl/br/hls/720/0460.ts 404
(anonymous) @ DownloadJob.mjs:223
Promise.then (async)
(anonymous) @ DownloadJob.mjs:218
(anonymous) @ DownloadJob.mjs:216
Promise.then (async)
_downloadPlaylistHLS @ DownloadJob.mjs:215
(anonymous) @ DownloadJob.mjs:81
(anonymous) @ Chapter.mjs:120
_getPageList @ Connector.mjs:616
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
DownloadJob.mjs:223 GET https://pro5.vidstream.pro/1126/stream1/EqPFI_kQBAro1HhYl67rC8EurFwU5LizFAV7rqk+wIMmUtcbRWEl/br/hls/720/0461.ts 404
(anonymous) @ DownloadJob.mjs:223
Promise.then (async)
(anonymous) @ DownloadJob.mjs:218
(anonymous) @ DownloadJob.mjs:216
Promise.then (async)
_downloadPlaylistHLS @ DownloadJob.mjs:215
(anonymous) @ DownloadJob.mjs:81
(anonymous) @ Chapter.mjs:120
_getPageList @ Connector.mjs:616
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
DownloadJob.mjs:223 GET https://pro5.vidstream.pro/1126/stream1/EqPFI_kQBAro1HhYl67rC8EurFwU5LizFAV7rqk+wIMmUtcbRWEl/br/hls/720/0462.ts 404
(anonymous) @ DownloadJob.mjs:223
Promise.then (async)
(anonymous) @ DownloadJob.mjs:218
(anonymous) @ DownloadJob.mjs:216
Promise.then (async)
_downloadPlaylistHLS @ DownloadJob.mjs:215
(anonymous) @ DownloadJob.mjs:81
(anonymous) @ Chapter.mjs:120
_getPageList @ Connector.mjs:616
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
DownloadJob.mjs:223 GET https://pro5.vidstream.pro/1126/stream1/EqPFI_kQBAro1HhYl67rC8EurFwU5LizFAV7rqk+wIMmUtcbRWEl/br/hls/720/0463.ts 404
(anonymous) @ DownloadJob.mjs:223
Promise.then (async)
(anonymous) @ DownloadJob.mjs:218
(anonymous) @ DownloadJob.mjs:216
Promise.then (async)
_downloadPlaylistHLS @ DownloadJob.mjs:215
(anonymous) @ DownloadJob.mjs:81
(anonymous) @ Chapter.mjs:120
_getPageList @ Connector.mjs:616
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-brands-400.woff2?v=5.8.2
Settings.mjs:371 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
(anonymous) @ Settings.mjs:371
Promise.catch (async)
_getValidValue @ Settings.mjs:368
load @ Settings.mjs:294
async function (async)
load @ Settings.mjs:272
closeDiscardChanges @ menu.html:248
handler @ template-stamp.html:96
DownloadJob.mjs:168 GET https://jrpkz.vidstream.pro/EqPVJPsPW1322yVezviuGdNz9wsVp_2xSlow5Od52MBlQ9QQSn4l9aIzxgLjDfyI+tzdG4991OvS7PNrAyWqkmeZRvMLH71dRJiivXxFIkYyM4M0Fgwwkc+ct1uf8SKSfUD0SVhntgLv5DdKs0JLmvx6lKMqTArvmcDaBpzip7ToINA32wzYzdtVO9fPSJIWJ4s/br/hls/720/720.m3u8 404
(anonymous) @ DownloadJob.mjs:168
_downloadPlaylistHLS @ DownloadJob.mjs:163
(anonymous) @ DownloadJob.mjs:81
(anonymous) @ Chapter.mjs:120
_getPageList @ Connector.mjs:616
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
DownloadJob.mjs:295 TypeError: playlist.match is not a function
    at DownloadJob.mjs:187 {hash: "id,language,resolution", mirrors: Array(1), subtitles: Array(0)}
(anonymous) @ DownloadJob.mjs:295
Promise.catch (async)
_downloadPlaylistHLS @ DownloadJob.mjs:289
(anonymous) @ DownloadJob.mjs:81
(anonymous) @ Chapter.mjs:120
_getPageList @ Connector.mjs:616
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
DownloadJob.mjs:168 GET https://jrpkz.vidstream.pro/EqPVJPsPW1322yVezviuGdNz9wsVp_2xSlow5Od52MBlQ9QQSn4l9aIzxgLjDfyI+tzdG4991OvS7PNrACenkmeZRvMLH71dRJiivXxFIkYyM4M0Fgwwkc+ct1uf8SKSfUD0SVhntgLv5DdKs0JLmvx6lKMqTArvmcDaBpzip7ToINA32wzYzdtVO9fPSJIWJ4s/br/hls/1080/1080.m3u8 404
(anonymous) @ DownloadJob.mjs:168
_downloadPlaylistHLS @ DownloadJob.mjs:163
(anonymous) @ DownloadJob.mjs:81
(anonymous) @ Chapter.mjs:120
_getPageList @ Connector.mjs:616
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:110
Promise.then (async)
getPages @ Chapter.mjs:108
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
DownloadJob.mjs:295 TypeError: playlist.match is not a function
    at DownloadJob.mjs:187 {hash: "id,language,resolution", mirrors: Array(1), subtitles: Array(0)}

**Screenshots**
![Screenshot (43)](https://user-images.githubusercontent.com/92655536/137606622-8f021176-9a7f-4670-b4d0-e367b3563105.png)
]

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17

**Comment by 27136773** [comment]
It seems only `MP4` streams from VidStream are affected, the `HLS` streams are still working (e.g. episodes of Bai Yao Pu 2nd Season)
