### ISSUE TITLE
Ninjascans update is not updating

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#407]
> **From:** HakuNeko User

updating list ended removing whole list. website is working properly.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Cannot be reproduced, manga list is updated correctly on my end.
However it seems images are no longer loaded...

----

![image](https://user-images.githubusercontent.com/27136773/64552857-740ab980-d338-11e9-9ffa-d7d312816561.png)

**Comment by 27136773** [comment]
It seems the chapters with missing images are also not working on the website, so everyhing seems fine from my end.

Are you using stable client 5.0.8 or any of the nightly builds?
Have you ensured network settings such as proxy/VPN are correct?

**Comment by 27136773** [comment]
Merged wordpress madare fix to 5.0.8
All Wordpress Madara based websites should now work again.
