### ISSUE TITLE
[1stkiss Manga] Connector not working

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#4072]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
download chapter error

**To Reproduce**
1. 1stkiss Manga
2. 101 Ways to Win Her Heart
3. chapter 37
4. err_spdy_protocol_error

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by 27136773** [comment]
The `SPDY_PROTOCOL_ERROR` is not related to a single website, this is an issue between client and server communication.
Try to start HakuNeko with command-line arg `--disable-http2` and see if this improves connections...

It is possible that the server cannot cope with the amount of requests and therefore some of the connections are failing.

**Comment by 27136773** [comment]
See also: #3814

**Comment by 27136773** [comment]
Possible causes: https://stackoverflow.com/questions/33867014/what-does-err-spdy-protocol-error-mean-in-nginx
