### ISSUE TITLE
[Site Request] MangaReader

### ISSUE THREAD

**Issue by Kastlet** [manga-download/hakuneko#4073]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://mangareader.to/
- Manga List: https://mangareader.to/type/manga
- Manga example: https://mangareader.to/naruto-567
- Chapter online viewer example: https://mangareader.to/read/naruto-567/en/chapter-1

**Languages**
List of languages supported by the website
English, Japanese
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #3979
