### ISSUE TITLE
[Bug] bugs in website manga livre

### ISSUE THREAD

**Issue by Paquitosz** [manga-download/hakuneko#4075]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
today the site manga livre doesn't show the chapters and every time I press something it asks to install a file called "download". And yesterday this error appeared when it was possible to download a chapter: TypeError: page.replace is not a function.

**To Reproduce**
1. access the extension of manga livre
2. press to see a chapter of any manga

**Expected behavior**
that I can see and download the available chapters and that it no longer appears asking to download a file called "download"

**Screenshots**
asking to download a file called "download": https://prnt.sc/1ww4r5i
the chapters not appearing: https://prnt.sc/1ww4zid
message that appeared when I try to download a chapter yesterday: https://prnt.sc/1ww5343

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
See #4061
