### ISSUE TITLE
[Question] Mangadex issue or just me?

### ISSUE THREAD

**Issue by ShadowEaglz** [manga-download/hakuneko#4079]
Anyone else finding they have to retry a download from mangadex multiple times lately?

I keep getting 

```
connector://mangadex/?payload=eyJuZXR3b3JrTm9kZSI6Imh0dHBzOi8vdXBsb2Fkcy5tY…NjM2ZDVjMzI5OGNlMDY2ZmQ3M2ExNzlmMDQyMGI0NjBlZjA4NDMzYThiYjVjMGMuanBnIn0%3D net::ERR_NOT_IMPLEMENTED

  | (anonymous) | @ | DownloadJob.mjs:118
-- | -- | -- | --
  | Promise.then (async) |   |  
  | (anonymous) | @ | DownloadJob.mjs:118
  | _downloadPages | @ | DownloadJob.mjs:116
  | (anonymous) | @ | DownloadJob.mjs:76
  | getPages | @ | Chapter.mjs:105
  | downloadPages | @ | DownloadJob.mjs:72
  | processQueue | @ | DownloadManager.mjs:49
```

and/or 
`TypeError: Failed to fetch`

But eventually after numerous retries (many more if multiple downloads at once) it does complete. 

Is this just me?

Hakuneko nightly-20200705.1 rev. Master@bd6623

would have added the question label, but that wasn't an option in the new issue menu.

**Comment by 27136773** [comment]
See: #4121

**Comment by 27136773** [comment]
No further response => closed
