### ISSUE TITLE
407

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#408]
> **From:** HakuNeko User

Previously bookmarked ninjascan titles still work and show images properly, but updating list directly from ninjascan removed all titles (again, ninjascan bookmarks still work regardless). I run off of Mac and have the latest haku version.

That might account for the different result when updating list (green circular arrows).

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
#407
