### ISSUE TITLE
LilyManga sometimes have incorrect page orders

### ISSUE THREAD

**Issue by Nivyan** [manga-download/hakuneko#4080]
This is pretty hard to give specific details for, as it doesn't apply to all chapters of a given manga - especially because the pages on LilyManga are ordered correctly.

For an example, in [this chapter](https://lilymanga.com/ys/bocchi-kaibutsu-to-moumoku-shoujo/chapter-15/), page 7 and 8 are correct on the site, but swapped in HakuNeko. 

Redownloading the chapter does not fix the issue.

LilyManga has an alternative, page view - rather than list view, which could be iterated through to retrieve the pages in the correct order - but would probably slow down the download considerably. Personally, I'd be more than happy with such and alternative, at least in the options.

**Comment by 27136773** [comment]
Cannot find any special code on the website itself that may try to shuffle the image order as protection against scrapers. It is just plain and structured HTML which is expected to be extracted by HakuNeko in the exact same order as presented in the browser...

![image](https://user-images.githubusercontent.com/27136773/139600776-a9505f1b-5bfe-4500-9731-dcdfd0b02749.png)

**Comment by Nivyan** [comment]
Exactly. That's why I was unable to provide additional information 🙁
Not sure what could be causing it, I'd assume images downloaded in the 'wrong order' because of some random circumstances - and order them based off the images names.

**Comment by 27136773** [comment]
I cannot see any related programmatic issue in HakuNeko. There is a chance that the server side `PHP` that renders the page messed up sometimes (maybe page is generated async on the server?). Therefore there is nothing that can be done now in HakuNeko.
