### ISSUE TITLE
[Site Request] iimanga

### ISSUE THREAD

**Issue by P2B3** [manga-download/hakuneko#4081]
**iimanga**
iimanga

**Website urls (examples below)**
- Site: https://iimanga.com/
- Manga List: https://iimanga.com/manga/
- Manga example: https://iimanga.com/manga/martial-god-asura/
- Chapter online viewer example: https://iimanga.com/martial-god-asura-chapter-222/

**Languages**
Arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dead website. @Sheepux pls.

**Comment by Sheepux** [comment]
they've probably changed to https://aresmanga.com (found via https://iimangaprev.blogspot.com/ )
wich is already implemented :)
