### ISSUE TITLE
[Site Request] FireCross

### ISSUE THREAD

**Issue by Neutronoid** [manga-download/hakuneko#4083]
**Name of the website**
FireCross

**Website urls (examples below)**
- Site: https://firecross.jp
- Manga List: https://firecross.jp/ebook/comics
- Manga example: https://firecross.jp/ebook/series/235
- Chapter online viewer example: https://firecross.jp/reader/3055?trial=0&token=6aa8b999-99c0-44e9-8683-117c8995d9e2

**Languages**
Japanese

**Website relationship*
Seperated from Hobby Japan

**Comment by Ever4engel** [comment]
Duplicate from #3978
