### ISSUE TITLE
[Site Request] animepahe.org because animepahe.com doesn't seem to work

### ISSUE THREAD

**Issue by v09j** [manga-download/hakuneko#4084]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Related: #3967

**Comment by 27136773** [comment]
Maybe add an option to setup the preferred domain for animepahe in settings.
- animepahe.com
- animepahe.org
- animepahe.ru

**Comment by v09j** [comment]
> Maybe add an option to setup the preferred domain for animepahe in settings.
> 
> * animepahe.com
> * animepahe.org
> * animepahe.ru

you could use a vpn or 1.1.1.1 warp by cloudfare(free), but downloads gets cancelled pretty often maybe it was an issue with the anime i was trying to download but you could give it a try(might work)
