### ISSUE TITLE
Removal Request for [teamxmanga]

### ISSUE THREAD

**Issue by Mahox1** [manga-download/hakuneko#4086]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Which website should be removed?
[https://teamxmanga.com/]

Why should this website be removed from HakuNeko?
[It helped onther websites stealing our chapters and harm our vists]

#### In case of Traffic
1. How much traffic is caused by HakuNeko?
[YOUR ANSWER HERE]
2. How much is it compared to overall traffic (percentage)?
[YOUR ANSWER HERE]
3. How did you measure those analytics (framework)?
[YOUR ANSWER HERE]
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
[YOUR ANSWER HERE]
5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
[YOUR ANSWER HERE]

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
[Yes]
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
[Yes we removed it from tachiyomi]
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
[Yes]

#### In case of Monetization
1. Are you using Donations?
[Yes]
2. Are you using Advertisements?
[Yes]

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
Please make sure the removal conditions are met:
- there is at least one overlay ad and one popup ad which must be removed
- download links for chapters could not be found

Let me know when the changes are done

**Comment by 27136773** [comment]
No further response => rejected for now
Feel free to re-open the request when you think the conditions are fulfilled.
