### ISSUE TITLE
[Site Request] manga1st

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4089]
**Name of the website**
manga1st

**Website urls (examples below)**
- Site: https://manga1st.com/
- Manga List: https://manga1st.com/manga/
- Manga example: https://manga1st.com/manga/divine-heros-skyfall-system/
- Chapter online viewer example: https://manga1st.com/manga/divine-heros-skyfall-system/chapter-283/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `WordPressMadara`
