### ISSUE TITLE
[Manga-TR] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4091]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I click the update button, icon spin. When icon stop spinning, nothing happen, Manga List is still empety.
Note: Clipboard is working.

**To Reproduce**
1. Manga-TR
2. Bypass CloudFlare-like DDOS-protection
3. Click update button
4. Connector update isn't working

**HakuNeko (please complete the following information):**
 - Version 6.17@a8e80e and master@2653c

**Comment by 27136773** [comment]
See #4042
