### ISSUE TITLE
[Site Request] Shimada Scans

### ISSUE THREAD

**Issue by Coravon** [manga-download/hakuneko#4092]
**Name of the website**
Shimada Scans

**Website urls (examples below)**
- Site: https://shimadascans.com/
- Manga List: https://shimadascans.com/manga/
- Manga example: https://shimadascans.com/manga/imprisoned-one-million-years-my-disciples-are-all-over-the-world/
- Chapter online viewer example: https://shimadascans.com/imprisoned-one-million-years-my-disciples-are-all-over-the-world-chapter-1/

**Languages**
English

**Comment by 27136773** [comment]
Template: `WordPressMangastream`
