### ISSUE TITLE
Removal Request for [yaoifanclube.com.br]

### ISSUE THREAD

**Issue by tiauva** [manga-download/hakuneko#4095]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Which website should be removed?
[yaoifanclube.com.br]

Why should this website be removed from HakuNeko?
[We are not a manga aggregator site, we are just a fansub (scanlator) and all the projects we have on our site we worked on them, in addition, the ads on the site (only 4 poup) are to sponsor artists who have authorized us to do so your own projects. We sponsor some artists and also buy original chapters to help others, and we also have to pay for hosting and other site expenses. Most of the expenses come from fansub(scanlator) participants' pockets, and precisely because we have authorization for the projects of some artists, we don't put them for download. And we only put padlocked chapters because they are very explicit and it was just some authors who came up with the idea (We don't charge "nothing" for readers to read on our site).]

#### In case of Traffic
1. How much traffic is caused by HakuNeko?
[YOUR ANSWER HERE]
2. How much is it compared to overall traffic (percentage)?
[YOUR ANSWER HERE]
3. How did you measure those analytics (framework)?
[YOUR ANSWER HERE]
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
[YOUR ANSWER HERE]
5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
[YOUR ANSWER HERE]

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
[Yes, we will try to work on it]
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
[Yes, we placed the order for Tachiyomi and they have already removed our site from their extender and on FMD2 we were not added.]
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
[We didn't just because we're just a fansub (fan site for fans) and we never imagined that would happen. But, now because of this occurrence, we will work on it.]

#### In case of Monetization
1. Are you using Donations?
[YOUR ANSWER HERE]
2. Are you using Advertisements?
[YOUR ANSWER HERE]

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by Sheepux** [comment]
Case is about monetization not content protection, please check those specific parts.

Removal conditions are probably not met : 
- AMP ad standard are probably not met (website cannot be joined atm)
- Are download links provided so that users can read offline ? (website cannot be joined atm)

**Comment by tiauva** [comment]
It's not a matter of monetization, not least because we ARE NOT AN AGGREGATE SITE. We are just a fansub. And if the person has the internet to download chapters, they can easily read them online. The other question is. If the official sites don't download the chapters why would we, who are a fansub, do it???? Putting the site in your extender should be an option for the OWNER of the site and not for anyone who has a link, after all, in the end, who pays the site's bills and works with the translations "it's me".

**Comment by Sheepux** [comment]
You are complaining about bills, so your issue is about monetization.
The site, in view of the volume, costs almost nothing. If you're using donation it should largely cover the hosting cost.

But that's not the debate. Removal conditions are stated and not met.
Let us know when you'll plan to set user-respectfull ads and download options for offline reading.

**Comment by tiauva** [comment]
Well, since you refuse to remove my site from your extender, I will have to notify the authors of the works I sponsor for what happened, and with that they will notify the official websites about you. And I will also take further steps.

**Comment by Sheepux** [comment]
Well ... hakuneko is not hosting anything. You are ... and publicly (it's called internet). If you don't want your images to be public you can protect them by hiding them from the public access.

You can also report Google for developping Chrome and allowing it to display your images.

**Comment by 27136773** [comment]
No further intention by the opener to fulfil the removal requirements => rejected
Feel free to reopen the ticket when the removal requirements are met.
