### ISSUE TITLE
[Site Request] Animixplay

### ISSUE THREAD

**Issue by kgr44217** [manga-download/hakuneko#4098]
**Name of the website**
Animixplay

**Website urls (examples below)**
- Site: https://animixplay.to/
- Manga List: https://animixplay.to/list
- Manga example: https://animixplay.to/v1/aho-girl
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Jaxk69** [comment]
Duplicate #3919
