### ISSUE TITLE
[Site Request] MerakiScan

### ISSUE THREAD

**Issue by Zahyra16** [manga-download/hakuneko#4099]
**Name of the website**
Meraki Scan
**Website urls (examples below)**
- Site: https://meraki801.com/
- Manga List: https://meraki801.com/lista/
- Manga example: https://meraki801.com/manga/tercer-final/
- Chapter online viewer example: https://meraki801.com/manga/tercer-final/capitulo-17/

**Languages**
List of languages supported by the website
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by SofiAr16** [comment]
@ronny1982 Can you do a connector from this? Please

**Comment by MikeZeDev** [comment]
I need a password to see the website. Therefore HN devs cant do anything without it. Also, better not giving it in the open.

**Comment by Zahyra16** [comment]
@MikeZeDev I have an account that I do not use. Where do I write to give you the username and password. to make a connector of this

**Comment by MikeZeDev** [comment]
I am not a HN dev. Ask them :)

**Comment by MikeZeDev** [comment]
Dead website @Sheepux pls.

**Comment by Sheepux** [comment]
their websites https://merakiscans.com  redirects to https://azuremanga.com/
wich is already implemented.
