### ISSUE TITLE
407

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#410]
> **From:** HakuNeko User

redownloaded 5.0.8 but still nothing.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See #407

**Comment by 27136773** [comment]
Please perform the following tasks first and let us know if the problem still exist:
- [ ] Are there any errors shown in the developer tools console and network tab (F12)
- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_
