### ISSUE TITLE
[Site Request] Ikifeng

### ISSUE THREAD

**Issue by Zahyra16** [manga-download/hakuneko#4100]
**Name of the website**
Ikifeng

**Website urls (examples below)**
- Site: https://ikifeng.com
- Manga List: https://ikifeng.com/
- Manga example: https://ikifeng.com/manga/lazos_de_sangre/
- Chapter online viewer example: https://ikifeng.com/manga/lazos_de_sangre/capitulo-76/

**Languages**
List of languages supported by the website
Spanish
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #4112
