### ISSUE TITLE
[ReadM] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#4102]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapters not showing up and refresh doesn't work

**To Reproduce**
1. Name of connector - ReadM
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working) - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="580" alt="Screen Shot 2021-10-29 at 11 57 25 AM" src="https://user-images.githubusercontent.com/70929406/139488029-533094e2-d29b-499f-b20c-2fe12b1ecce1.png">

<img width="1117" alt="Screen Shot 2021-10-29 at 11 55 15 AM" src="https://user-images.githubusercontent.com/70929406/139488043-eb50bbe2-6f0e-4aae-ae3c-454511511893.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by ICyperior** [comment]
It is working. You just need to open the site and bypass CloudFlare Protection.

**Comment by tsentered** [comment]
Thank you for checking but when I checked to make sure the site was operational, worked fine and there was no CloudFlare popups. But whatever the case, it is working now.

**Comment by ICyperior** [comment]
Yeah, It was there for a moment. Maybe they were trying something.
