### ISSUE TITLE
mangareader.to

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4106]
**Name of the website**
mangareader.to

**Website urls (examples below)**
- Site: https://mangareader.to/
- Manga List: https://mangareader.to/az-list
- Manga example:
   https://mangareader.to/solo-leveling-21?ref=search
- Chapter online viewer example: https://mangareader.to/read/solo-leveling-21/en/chapter-171

**Languages**
english

**Comment by 27136773** [comment]
See #3979
