### ISSUE TITLE
[Site Request] Eternal Scans

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4107]
**Name of the website**
Eternal Scans

**Website urls (examples below)**
- Site: https://eternalscans.com/
- Manga List: https://eternalscans.com/series/
- Manga example: https://eternalscans.com/series/the-dragons-brave-love/
- Chapter online viewer example: https://eternalscans.com/series/the-dragons-brave-love/chapter-5/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by onelots** [comment]
Done, I'll put it in my next PR !
