### ISSUE TITLE
[Site Request] mangaboss

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4108]
**Name of the website**
mangaboss

**Website urls (examples below)**
- Site: https://mangaboss.org/
- Manga List: https://mangaboss.org/manga/
- Manga example: https://mangaboss.org/manga/rebirth-of-god-level-prodigal-son/
- Chapter online viewer example: https://mangaboss.org/manga/rebirth-of-god-level-prodigal-son/chapter-12/

**Languages**
Ebglish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by onelots** [comment]
Done, I'll put it in my next pr ;)
