### ISSUE TITLE
[Ikifang ] Connector changed website to ikifeng.com

### ISSUE THREAD

**Issue by Zahyra16** [manga-download/hakuneko#4112]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**
Connector changed website to ikifeng.com
**To Reproduce**
1. Name of connector Ikifang
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Zahyra16** [comment]
@ronny1982 Can you fix this?

**Comment by Pierre-Monier** [comment]
I have checked that, it's more complicated because it looks like the website has done some major change. There is no more list url and the clipboard method is broke. So it might take some time but I will take a closer look pretty soon ;)

**Comment by Zahyra16** [comment]
Thanks :)

**Comment by Zahyra16** [comment]
@Pierre-Monier You should close this #4100 
I think is same

**Comment by Pierre-Monier** [comment]
I can't work on that before next week :'(

**Comment by Pierre-Monier** [comment]
This is fixed
