### ISSUE TITLE
[Manhuas] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#4114]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

titles shows no chapters and when updated all titles disappear. I think a change was made to the format of the site. No cloudfare issues.

**To Reproduce**
1. Name of connector - Manhuas
2. Name of manga (if connector update is working) - N/A
3. Name of chapter (if manga update is working) - N/A
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - None

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**

<img width="562" alt="Screen Shot 2021-11-02 at 11 31 08 AM" src="https://user-images.githubusercontent.com/70929406/139924909-91dc56d9-849b-4b3d-affa-d3f06ee8da74.png">

 - Version [e.g. 6.17]

**Comment by ICyperior** [comment]
Click on the green round icon. It's after the Site name in the above picture.

**Comment by MikeZeDev** [comment]
It works you just have to read the damn manual and follow instruction  :D

@ronny1982 this can be closed its working for me on nighlty at least.

**Comment by tsentered** [comment]
If you read "describe the bug" section up at the top of the thread, you will see that I mentioned that updating connector ( or "click on the green round icon" made all titles disappear.  I also took the time to show the screenshot which shows this after updating connector.

If you read the top of the thread, you will see that I followed the instructions but also provided answers to every step.

**Comment by tsentered** [comment]
Updating the connector is working now though very slow.

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Was maybe temporary/regional server issue?

**Comment by 27136773** [comment]
No further problem reports => closed
