### ISSUE TITLE
manhwa18.net not working

### ISSUE THREAD

**Issue by darkflee** [manga-download/hakuneko#4116]
manhwa18.net not working, i think maybe bcs of cloud, n need user agent n cookies from browser, or maybe the format of the site changes idk
i'm trying using diff proxy n vpn still cant attach 
![Screenshot 2021-11-03 040446](https://user-images.githubusercontent.com/89280778/139951490-f30c3d3a-8f34-4886-aa83-85ffc7d8cd97.jpg)

**Comment by 27136773** [comment]
See #2933

**Comment by darkflee** [comment]
> See #2933

ahhhh i see, so this issues alrd noticed, it's ok i think i'll be waiting for the fix patiently, actually i try using the other software such fmd2 but still had the issues n that looping i bealive it's the same happened.
i try using cookies n user-agent from diff browser but it's failed attach, without it, that will be infinite loop bcs failed solve the cloud challange ald post that issues on them as well
