### ISSUE TITLE
[Site Request] painful nightz

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4117]
**Name of the website**
painfulnightz

**Website urls (examples below)**
- Site: https://painfulnightz.com/
- Manga List: https://painfulnightz.com/manga/
- Manga example: https://painfulnightz.com/manga/the-goddess-consort-reigns-supreme/
- Chapter online viewer example: https://painfulnightz.com/manga/the-goddess-consort-reigns-supreme/chapter-12/
- 
**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Cloudflare check.
