### ISSUE TITLE
Yaoi Haven [Bug]

### ISSUE THREAD

**Issue by billsargent** [manga-download/hakuneko#4119]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

Yes

**Describe the bug**
Yaoi Haven Connector doesn't list titles beginning with a bracket. Most items on their site begin with that. [author name] Title. 

**To Reproduce**
1. Go to search 
2. Try to find any manga title with a bracket

**Expected behavior**
A list of titles that include [Author name] Title

**Context (please complete the following information):**
 - OS:  Windows 11
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Please provide a link to a manga that is listed on https://www.yaoihavenreborn.com/doujinshi/all-doujinshi, but not shown in HakuNeko

**Comment by billsargent** [comment]
This one: https://p.yaoihavenreborn.com/doujinshi/satsuki-fumi-ultra-happy-egoist-eng/

However, the brackets seem to only appear on the main page. Not in the title itself. I must be losing my mind. But this one still doesn't show up.

**Comment by billsargent** [comment]
![image](https://user-images.githubusercontent.com/32219940/140304136-928eacef-2374-4c1b-bdb4-ada7e9fbc8d9.png)

**Comment by 27136773** [comment]
> This one: https://p.yaoihavenreborn.com/doujinshi/satsuki-fumi-ultra-happy-egoist-eng/
> 
> However, the brackets seem to only appear on the main page. Not in the title itself. I must be losing my mind. But this one still doesn't show up.

How do you get this link?
It is on the subdomain `p.yaoihavenreborn.com`, i cannot find it on [www.yaoihavenreborn.com](https://www.yaoihavenreborn.com/doujinshi/all-doujinshi?colour=all&lang=all&sort=all&search=egoist)

**Comment by billsargent** [comment]
Ok, after I sign in, I get taken to the p subdomain. I initially thought p was their CDN but maybe its not. I can find it after signing in, but it is not limited to registered users as you could see it.

**Comment by 27136773** [comment]
Seems they are currently testing their new layout on subdomain https://p.yaoihavenreborn.com, it is. ot yet known if this is permanent or if they will move the new website to https://www.yaoihavenreborn.com soon

![image](https://user-images.githubusercontent.com/27136773/140699744-a4855f8b-8d62-4c5a-9ad1-62f7edfa4ee0.png)

**Comment by billsargent** [comment]
Ok that makes more sense then. I guess we'll have to wait until they get it sorted. :)

**Comment by billsargent** [comment]
The site has now migrated to their new layout.
