### ISSUE TITLE
MangaDex Connector not working

### ISSUE THREAD

**Issue by Zeonymous** [manga-download/hakuneko#4121]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
MangaDex is not allowing for consecutive downloads within a certain time limit. They all fail unless left inactive, and manually attempting again after X min of inactivity.

**To Reproduce**
Hit this button, and off to the races: 
![image](https://user-images.githubusercontent.com/20764838/140181913-7d361fea-e7e2-4bbb-ba43-12e259ae9f82.png)

1. Name of connector: MangaDex
2. Name of manga: "Kumo Desu ga, Nani ka?"
3. Name of chapter: Many of them.
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://user-images.githubusercontent.com/20764838/140181685-1e7cd476-1508-482c-ad38-6b92a2f59394.png)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7@a8e80e

**Comment by 27136773** [comment]
See: #4082 for new setting, use nightly build or wait for update to be merged into `6.1.7`
