### ISSUE TITLE
[Site Request] manhuaga

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4123]
**Name of the website**
manhuaga

**Website urls (examples below)**
- Site: https://manhuaga.com/
- Manga List: https://manhuaga.com/manga/
- Manga example: https://manhuaga.com/manga/keep-a-low-profile-sect-leader/
- Chapter online viewer example: https://manhuaga.com/manga/keep-a-low-profile-sect-leader/chapter-18/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website is covered by https://github.com/manga-download/hakuneko/commit/c21d7b94dcc96a10469a86533da3133a2acd063b

Can be closed @Sheepux pls <3
