### ISSUE TITLE
[Comikey] Connector not working

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#4125]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Final Chapter response seems to be providing a Obsfucated response instead of a plain JSON response. THe onnector is now not working.

**To Reproduce**
1. Comikey
2. Any Manga
3. Any Chapter

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Synthlight** [comment]
For more details on the json returned, the type (from Chrome inspector) is listed as "divina+json+vnd.ep4.drm".
And it looks something like this:
![image](https://user-images.githubusercontent.com/1075166/140469005-ee58b56e-cd46-45cc-9c5e-d15ac05fee6c.png)
So.... yea. I'm sure this will be rather obnoxious to break.

**Comment by Sheepux** [comment]
divina seems to be a new DRMised format for ebooks  developped by https://www.edrlab.org/ (2020)

**Comment by Ever4engel** [comment]
if the drm is cracked by ronny this connector need to be obfuscated.

**Comment by Sheepux** [comment]
I don't see the need for that.
