### ISSUE TITLE
[.asurascans.com] Connector not working

### ISSUE THREAD

**Issue by Kyuusei000** [manga-download/hakuneko#4126]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
allows you to download, but the files are "corrupted" they add an image that says that I stole the manga from their site, and they put webp files that the cbz reader does not read, if you want to use it you have to unzip file by file and delete the image , and change the ones that were converted to webp, and redo the cbz

**To Reproduce**
1. .asurascans.com
2. The Dark Magician Transmigrates After 66666 Years and SSS-Class Gacha Hunter
3. It was tested with chapters from 1 to 10 and they all did the same (tested with both completely and does the same I will keep trying and adding but the problem seems to be general)

**HakuNeko 6.17]

**Comment by 27136773** [comment]
Images are downloaded as is.
If your reading software does not support `CBZ` with `.webp` images, than this is a limitation of your reader. There are no official specifications about the `CBZ` format that forbids `.webp`.

You may setup HakuNeko to download images directly and then use a `Post Command` to convert and zip the images.

**Comment by 27136773** [comment]
I cannot find corrupted images in "Dark Magician [...]" chapters 1-10, only an additional cover image that says the files were stolen.
Please provide a sample manga/chapter that contains images which works on their website, but were corrupted in HakuNeko.

**Comment by Kyuusei000** [comment]
![Error01](https://user-images.githubusercontent.com/93754396/140471437-5a67d1cb-7674-4425-8e71-f4b3432fc4a7.jpg)
here I leave an image with the files if you occupy a copy of the file tell me to upload it to dropbox or another , and I am doing tests with the post commands, to see if that corrects it and thanks for answering soon the truth I have little using the program

**Comment by Kyuusei000** [comment]
![Error02](https://user-images.githubusercontent.com/93754396/140472017-23c51f17-ec7b-4a3d-bd3c-e0f8e98fb7db.jpg)
![Error03](https://user-images.githubusercontent.com/93754396/140472033-629c9091-d0d7-41c3-8942-36170ced50f8.jpg)
and this is what I commented that they are corrupted, maybe you are right and it is my cbz reader

**Comment by MikeZeDev** [comment]
@ronny1982 i checked this manga. If i visit the same chapter directly on the website there is no "stolen" page  thing. In HN preview pane there is one. Try chapter 1. So i guess its a countermeasure against robots and crawlers.

https://i.imgur.com/tJCNb7B.png
https://i.imgur.com/Wm7tqy2.png

The image is not corrupted by itself it just broke his reader. Thats asura goal maybe. You may want to get rid of garbage introduced by website to mess with non-regular browser users maybe? :D

**Comment by mooglestiltzkin** [comment]
is there a solution to this?

i noticed that when using cdexdisplay, it will have this faulty broken image as mentioned in this thread, basically broken and images while trying to view.

but when doing the same using sumatra pdf to view the same zip/rar/7zip, it worked fine? i also tried using YACReader, and that managed to view it fine, whereas Cdexdisplay couldn't.

In summary, i think why some of u are getting this broken/missing image to display in your comic reader, is becauz some sort of support issue for your reader app. Try using YACReader or Sumatra PDF, because those 2 worked fine for me (though i'd probly recommend YACReader as the better app for viewing manga).
