### ISSUE TITLE
[Site Request] Tappytoon FR

### ISSUE THREAD

**Issue by Cheng145** [manga-download/hakuneko#4129]
**Tappytoon **

- Site: hhttps://www.tappytoon.com/
- Manga List: https://www.tappytoon.com/fr/genres/
- Manga example: tappytoon.com/fr/comics/i-became-villains-mother-fr
- Chapter online viewer example: https://www.tappytoon.com/fr/comics/i-became-villains-mother-fr

**Languages**
French

**Comment by Jaxk69** [comment]
Duplicate #4062
