### ISSUE TITLE
407 ninjascan list emptied when updated list

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#413]
> **From:** HakuNeko User

I re-downloaded 5.0.8 (mac 64 bit) three times with no results. Preexisting ninjascan bookmarks still works. I know the drill and gone through the due dilegence. Website works fine, but updating list still emptied out the mangalist, though bookmarks still works. I've never seen an issue like this one.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See: #407
