### ISSUE TITLE
[Site Request] https://r.mangaowls.com/

### ISSUE THREAD

**Issue by paopaoluna** [manga-download/hakuneko#4131]
**Name of the website**
MangaOwl

**Website urls (examples below)**
- Site: https://r.mangaowls.com/
- Manga List: https://mangaowl.net/list
- Manga example: https://mangaowl.net/single/4472/pita-ten
- Chapter online viewer example: https://r.mangaowls.com/reader/4472/791525?tr=uO8Zi2MBH4H0o6n6G57Dsw%3D%3D&s=aHR0cHM6Ly9tYW5nYW93bC5uZXQ%3D

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #2335
