### ISSUE TITLE
[Comikey] Connector not working

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#4136]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloading any free chapter doesnt work. Keeps throwing error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14815570/140727173-98d448ea-a5de-4bbc-8693-bc0631a9c682.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Synthlight** [comment]
It looks like they saw the PR to use `addEventListener("e4p_web_readyDRM"` and just went to fuck with the event name:
![image](https://user-images.githubusercontent.com/1075166/140762964-7df9a8db-114b-4f06-b0e8-64795524e70b.png)

_Currently_, `addEventListener(atob(atob("WlRSd1gzZGxZbDl5WldGa2VVUlNUVEJpWVRjMVpEVmpabUl6T1RFMVltRTBObVZrWW0=") + "VkNzE1ZjBjOWEy")` will work, but probably not long term. They will probably just change it again.

**Comment by Sheepux** [comment]
OK, so they're really starting a connector war :) code obfuscation incoming

**Comment by 27136773** [comment]
Already started on this
