### ISSUE TITLE
[DragonTranslation] Connector not working

### ISSUE THREAD

**Issue by Sanedrac1** [manga-download/hakuneko#4137]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

I think a change was made to the format of the site. No cloudfare issues.
They change the wordpress theme. Now they use WordPressMadara
![solucion 2](https://user-images.githubusercontent.com/91925379/142911068-f9c547f0-4f2f-49aa-8b9c-0196c0751a66.png)

**To Reproduce**
1. Name of connector - DragonTranslation
2. Name of manga (if connector update is working) - N/A
3. Name of chapter (if manga update is working) - N/A
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - N/A

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7
![issue](https://user-images.githubusercontent.com/91925379/141035242-d67c35bd-1b8e-470a-8ea1-ae4d016863ae.png)

**Comment by SaitoGlutton** [comment]
no hay una opción para decir que también notifico el cambio de sitio web¡?

**Comment by Sanedrac23** [comment]
![image](https://user-images.githubusercontent.com/91925379/141125570-e427db54-2951-4769-8cc4-3f81c7e1aa6c.png)
The new manga list url: https://dragontranslation.com/manga/

**Comment by SaitoGlutton** [comment]
Como que Arreglaran este problema después de año, Por lo que veo :,v.,..

**Comment by Sanedrac1** [comment]
> Como que Arreglaran este problema después de año, Por lo que veo :,v.,..

Te recomiendo que descargues el proyecto de github y modifiques el código por tu propia cuenta haciendo los cambios que he puesto en la captura de pantalla. No creo que arreglen los conectores para web en español y si hay nuevos cambios, lo reportaré aquí

**Comment by SaitoGlutton** [comment]
Okey Tratare de Hacer Algo, Aunque No Soy Programador pero Igual Gracias
d(U^)

**Comment by Sanedrac1** [comment]
> Okey Tratare de Hacer Algo, Aunque No Soy Programador pero Igual Gracias d(U^) 

No es necesario ser programador. Yo no lo soy, apenas se un poco de css y html5

**Comment by SaitoGlutton** [comment]
SI Tengo Cualquier duda Puedo Aclararme Con Vos¿?

**Comment by onelots** [comment]
there is nothing at all on this website 🤨
