### ISSUE TITLE
[Sunday-webry.com] Connector not working

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#4139]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
yes

**Describe the bug**
the connector is **broken** (**no mangalist, previews, dl...**) it changed **it's own reader to Coreview.**

**HakuNeko (please complete the following information):**
 - **stable and nightly versions**

**Comment by onelots** [comment]
<img width="1277" alt="Capture d’écran 2021-12-28 à 23 44 51" src="https://user-images.githubusercontent.com/54822802/147612543-49b23f0d-b806-4109-b515-b84004f4acad.png">
Okay I've found the bug :joy: the website seems to be dead X)

**Comment by Ever4engel** [comment]
> <img alt="Capture d’écran 2021-12-28 à 23 44 51" width="1277" src="https://user-images.githubusercontent.com/54822802/147612543-49b23f0d-b806-4109-b515-b84004f4acad.png">
> Okay I've found the bug 😂 the website seems to be dead X)

Nope, this connector isn't dead ^^

it work well

**Comment by onelots** [comment]
Uh yeah it's up

**Comment by MikeZeDev** [comment]
It works fine. @Sheepux pls?
