### ISSUE TITLE
407 cancel

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#414]
> **From:** HakuNeko User

Soon as I sent the last message 2 seconds ago, I tried updating list one last time and it updated! Weird stuff.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See #407

**Comment by 27136773** [comment]
I fixed it, there was a merge error in the previous commit

**Comment by 27136773** [comment]
Also, please do not open a new ticket to answer an existing ticket, this will become confusing
