### ISSUE TITLE
[Site Request]  https://mangaowl.net/

### ISSUE THREAD

**Issue by Tanya077crow** [manga-download/hakuneko#4140]
**Name of the website**
[thewebsitename](https://mangaowl.net/)

**Website urls (examples below)**
- Site:  https://mangaowl.net/
- Manga List:  https://mangaowl.net/list
- Manga example: https://mangaowl.net/single/878/my-beautiful-world
- Chapter online viewer example: https://r.mangaowls.com/reader/878/124623/0?tr=HLDrR2vIwpopyOuNLHv0Yw%3D%3D&s=aHR0cHM6Ly9tYW5nYW93bC5uZXQ%3D

**Languages**
English

**Website relationship*
It's like mangakakalot but with a different logo etc. (eg : " https://mangakakalot.com/  ...").

**Additional details**
None (like template to reuse)

**Comment by 27136773** [comment]
See #2335
