### ISSUE TITLE
[manhwatop] Connector not working

### ISSUE THREAD

**Issue by jishnu4496** [manga-download/hakuneko#4147]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
when clicking on the files downloaded from manhwatop on bookmark, a new window is appearing and asking to download it again and it is same for the connector website also. their is no problem for files of other sites
![2021-11-13 (3)](https://user-images.githubusercontent.com/94229904/141646685-aee9339e-7a56-4bcb-b55a-44f28b125794.png)

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Works fine on my end. Your bookmark is probably outdated and needs to be re-added...
