### ISSUE TITLE
https://mangaalarab.com/[Site Request] thewebsitename

### ISSUE THREAD

**Issue by faris-lofi** [manga-download/hakuneko#4148]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Rejected: Please fill the form properly

If the users don't take the time to fill the form, the developers don't bother to implement...

**Comment by 27136773** [comment]
See: #4149
