### ISSUE TITLE
[Site Request] thewebsitenamehttps://mangaalarab.com/

### ISSUE THREAD

**Issue by faris-lofi** [manga-download/hakuneko#4149]
mangaalarab **Name of the website**
thewebsitename

**Website urls (examp*
- Site: https://mangaalarab/
- Manga List: https://mangaalarab/mangalist.html
- Manga example: https://mangaalarab/manga/themanganame.html
- Chapter online viewer example: https://mangaalarab/manga/0012/view.html
les below)**
- Site: https://mangaalarab/
- Manga List: https://mangaalarab/mangalist.html
- Manga example: https://mangaalarab/manga/themanganame.html
- Chapter online viewer example: https://mangaalarab/manga/0012/view.html

**Languages**
List of languages supported by the website
Arabic 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dead website. @Sheepux pls <3

**Comment by Sheepux** [comment]
no alternative domain found
