### ISSUE TITLE
407 Thank you (forgot my manners)

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#415]
> **From:** HakuNeko User

Forgot to say thanks.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See: #407
