### ISSUE TITLE
[manhwa18] Connector not working

### ISSUE THREAD

**Issue by zjhl214** [manga-download/hakuneko#4151]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapter lists all display 0/0

**To Reproduce**
1. manhwa18.com
2. Any
3. Any
4. _getUpdatedChaptersFromWebsite Error: Failed to receive chapter list (status: 404) - at Manhwa18._getChapters (FlatManga.mjs:49) at aysnc Manhwa18._getChapterList (Connector.mjs:595)

**HakuNeko (please complete the following information):**
 - 6.17

**Comment by 27136773** [comment]
No longer `FlatManga` template, seems to be completely new layout.

**Comment by MikeZeDev** [comment]
Everything works. Nightly. Can be closed?

**Comment by MikeZeDev** [comment]
Cant repro.
