### ISSUE TITLE
[Site Request] MangaReader

### ISSUE THREAD

**Issue by subZER002** [manga-download/hakuneko#4152]
**MangaReader**

**Website urls (examples below)**
- Site: https://mangareader.to/
- Manga List: https://mangareader.to/az-list
- Manga example: https://mangareader.to/read/25d-seduction-9844/en/volume-1
- Chapter online viewer example: https://mangareader.to/read/25d-seduction-9844/en/chapter-1

**Languages**
List of languages supported by the website
English
Japanese
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
See #3979
