### ISSUE TITLE
[Site Request] 9anime

### ISSUE THREAD

**Issue by scepticweeb** [manga-download/hakuneko#4156]
**Name of the website**
9anime

**Website urls (examples below)**
- Site: https://9anime.gg/
- Anime List: https://9anime.gg/az-list/
- Anime example: https://9anime.gg/watch/one-piece-episode-of-merry-mou-hitori-no-nakama-no-monogatari.qnir9LU455/

**Languages**
English

**Comment by Pierre-Monier** [comment]
Is the content different to  [this 9anime website](https://9anime.to/home) ?

**Comment by scepticweeb** [comment]
> Is the content different to [this 9anime website](https://9anime.to/home) ?

No but the (9anime.to) is banned in some countries (including mine) so vpn is required to download in hakuneko thats all.

**Comment by Pierre-Monier** [comment]
I don't think we will implement this website because we don't add duplicates, sorry :/
