### ISSUE TITLE
[Site Request] Comico Vietnam

### ISSUE THREAD

**Issue by minhngoc25a** [manga-download/hakuneko#4158]
**Name of the website**
Comico Vietnam

**Website urls (examples below)**
- Site: https://www.comico.vn/
- Manga List: https://www.comico.vn/comic/weekly
- Manga example: https://www.comico.vn/title/70
- Chapter online viewer example: https://www.comico.vn/chapter/70/2910

**Languages**
Vietnamese

**Website relationship**
Additional Vietnamese language version of Comico Japan

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by minhngoc25a** [comment]
> Dead website?

Yeah. Comico recently seized operations in Vietnam.
