### ISSUE TITLE
[Feature] Rename image files in a chapter

### ISSUE THREAD

**Issue by JoGaTo** [manga-download/hakuneko#4160]
_**Is your feature request related to a problem? Please describe.**_
Everytime I download a chapter of a manga, I opened its' files and they're all in two/three-digit numbers. In order to move all the images from every chapter into just one folder so that I won't have to waste time clicking on folders, I would have to MANUALLY re-name EVERY image files from EVERY chapter folder except the first, and then move them.

_**Describe the solution you'd like**_
Have whatever you posted in the chapter title format not only be the same for the chapter's folder/.cbz file, but for the images inside the archive, or whatever volume/chapter numbers extracted from the original name be used as part of the image's name [example: Ch. 1 - 01.jpg, 0000 - 05.png]

_**Describe alternatives you've considered**_
Besides manually re-naming which is a pain in the ass

_**Context (please complete the following information):**_
HakuNeko V6.17, latest nightly build

_**Additional context**_
None

**Comment by 27136773** [comment]
Alternative:
- Write a script for rnaming files and set it in `Post Command`
- On windows use PowerToys to rename multiple files

This has been discussed previously and there are some specific problems why this will not be implemented:
- extracting the chapter number is not reliable and may fail
- The sort order of the images is not guaranteed if the chapter names are inconsistent (e.g. `Ch. 03 - 001.png` may be listed before `Ch. 1 - 001.png`)
- Longer image file names increase the risk of hitting the path name length on windows systems

=> rejected
