### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by concord72** [manga-download/hakuneko#4161]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When pressing the refresh button for website MangaDex, I get the error "Failed to upload manga list for MangaDex. Failed to receive content from ...://api.mangadex.org/manga?limit=100&offset=2900&publicationDemographic%5B%5D=... (Status: 404) - 

**To Reproduce**
1. Name of connector - MangaDex
2. Name of manga (if connector update is working) Update not working

**HakuNeko (please complete the following information):**
 - Version 6.1.7@9436d8

**Comment by Albirew** [comment]
I can confirm, having the same output.
![Sans titre](https://user-images.githubusercontent.com/2805161/142463850-30503694-63a9-46d8-bfa3-d0ad5864ab73.png)
still working if you have series in your manga list, but refreshing mangadex connector leads to this error.

**Comment by Robonau** [comment]
![image](https://user-images.githubusercontent.com/30987265/142658541-0607a969-1971-4120-99dd-47b2e0e15d6e.png)
for some more info
it redirects to a captcha
and that 404s so it dosnt retry like it usually would

**Comment by Albirew** [comment]
captcha-v3 seems related to ddos-guard service
![Sans titre](https://user-images.githubusercontent.com/2805161/142699950-2ad163f6-8ac6-44df-8448-6d74d02463df.png)

**Comment by luvsick** [comment]
Also having hits issue, list won:t refresh but you can still download stuff that:s already pre-loaded.

**Comment by Albirew** [comment]
if the problem is the number of requests, is it possible to get partial update based on search (like, if we search for foo before updating, it will return everything that start by "foo" like foobar, foobaz, etc., and partially update list with results)?

**Comment by KunalG-Zol** [comment]
**Try using a VPN**. If it works then that means **the site might have blocked your real IP**. To prevent this try **disabling concurrent downloads**. I don't see a captcha when I go to the site so probably using a VPN might fix the problem.
(If you don't know which VPN to use, I recommend ProtonVPN.)

**Comment by concord72** [comment]
Already tried using a VPN, didn't work.

**Comment by Albirew** [comment]
disabling concurrent downloads gets to fetch up to offset=3200 before hitting the captcha (aka "*same-as-before*-kun"). may be a hard limit on number of requests per minute or per 30s (witch would be around 30~35 requests)

**Comment by nugstar** [comment]
Disabled concurrent downloads + a Network Throttling Profile with a latency of 2000ms worked for me to download the manga list. A 1000ms latency stopped at 30 requests. It's very slow, but at least seems to work.

Downloading manga works fine without the additional latency throttle - though issues pop up if enabling concurrent downloads.

**Comment by Albirew** [comment]
what version of Hakuneko do you use?
latest release (6.1.7) or latest nightly?

In latest release, there is no option to configure mangadex and neither there is an overall throttle.
tried to manually put `"mangadex": { "throttle": 2500 },` in `hakuneko.settings` but it doesn't looks like it's taken into account.

**Comment by nugstar** [comment]
Using latest release (6.1.7@9436d8

Added the Throttle as below:
1. F12
2. Network
3. Click on the Down arrow next to "Online"
4. "Add..."
5. Add Custom Profile

![Screenshot 2021-12-01 041853](https://user-images.githubusercontent.com/95298534/144095956-07699f89-7a05-497a-aa4e-70e010933b38.png)
![Screenshot 2021-12-01 041915](https://user-images.githubusercontent.com/95298534/144095960-30b9dac1-e853-4198-b467-04226aae319c.png)

Hope this helps

**Comment by Albirew** [comment]
yes! looks like it's working, at  least, it fetchs over 50 and counting. Thanks!
edit: forgot to say fetch completed without issue =)

**Comment by tsentered** [comment]
> 

Same issue with MacOS

**Comment by Sheepux** [comment]
> Added the Throttle as below:
> 
> Hope this helps

yup it points to the same as i commented in the PR: https://github.com/manga-download/hakuneko/pull/4167#issuecomment-981094359
