### ISSUE TITLE
[Site Request] Minda Fansub

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4162]
**Name of the website**
Minda Fansub

**Website urls**
- Site: https://mindafansub.me/
- Manga List: https://mindafansub.me/manga/list-mode/
- Manga example: https://mindafansub.me/manga/demons-sweetheart/
- Chapter online viewer example: https://mindafansub.me/demons-sweetheart-1-bolum/

**Languages**
Turkish

**Website relationship**
No

**Additional details**
No

**Comment by onelots** [comment]
Done, it will be in my next pr !
