### ISSUE TITLE
[Comikey] Not working - timed out

### ISSUE THREAD

**Issue by lord-ne** [manga-download/hakuneko#4164]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapters fail to download with the error "failed to load [the url of the chapter] within the given timeout of 10 seconds"

**To Reproduce**
1. Go to any manga on comikey (for example, "A Cursed Sword's Daily Life"
2. Try to download any free chapter (for example, Chapter 1)
3. After several seconds, download fails. Mousing over the exclamation mark in the download list shows `Error: Failed to load "https://comikey.com/read/cursed-sword-manga/qD0ZEo/chapter-1/" within the given timeout of 10 seconds!"` 

**HakuNeko (please complete the following information):**
 - Version: master@32c048 (notably, this already includes #4142 which fixed an issue with Comikey)

**Comment by amit34521** [comment]
Comikey guys are keeping a look here. As soon as Ronny makes a commit, they change the event names

**Comment by Sheepux** [comment]
It's called a "connector war". It lasts a few weeks. 
I Think that we should let a single issue open (not close it each time with solve the issue) .
