### ISSUE TITLE
[WeLoveManga] Connector not working

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#4165]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector is broken (mangalist, preview and download).

**HakuNeko (please complete the following information):**
 - nightly and stable

**Comment by Sheepux** [comment]
MangaList is disabled
https://welovemanga.net/manga-list.html

Website itself is not working (i don't see any chapter content).
Not something we can fix


Second weloma changed list-manga.html -> fixed
I'll let the issue open
