### ISSUE TITLE
[Site Request] muctau

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4168]
**Name of the website**
muctau

**Website urls (examples below)**
- Site: https://muctau.com/
- Manga List: https://muctau.com/manga/
- Manga example: https://muctau.com/manga/a-love-you-cant-escape/
- Chapter online viewer example: https://muctau.com/manga/a-love-you-cant-escape/chapter-12/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 27136773** [comment]
Template: `WordPressMadara`

**Comment by onelots** [comment]
Done, It will take place in my next pr !
