### ISSUE TITLE
is this doable through post command?

### ISSUE THREAD

**Issue by gitfirl** [manga-download/hakuneko#4169]
i want to replace every character in the folder name (manga title) and file name (chapter title) that isn't a letter, number, space, underscore, or dash with underscore. i'm using windows.

**Comment by Robonau** [comment]
it is doable yes

**Comment by gitfirl** [comment]
@Robonau if you don't mind, can you tell me how?

**Comment by 27136773** [comment]
Renaming folders in windows with a batch script to remove unwanted characters is something you should search in the web or ask in appropriate forums, as this is not really related to HakuNeko.

You can call any commandline tool with the `Post Command`, so thats just the caller to your batch script (see tooltip for supported parameters)
