### ISSUE TITLE
[Site Request] Legacy-Scans

### ISSUE THREAD

**Issue by Bertrand6969** [manga-download/hakuneko#4170]
**Name of the website**
Legacy-Scans

**Website urls (examples below)**
- Site: https://legacy-scans.com/
- Manga List: https://legacy-scans.com/series/
- Manga example: https://legacy-scans.com/manga/solo-necromancy/
- Chapter online viewer example: https://legacy-scans.com/solo-necromancy-1/

**Languages**
French

**Website relationship*
idk

**Additional details**
template themesia

**Comment by 27136773** [comment]
Template: seems to be `WordPressMangastream`

**Comment by onelots** [comment]
@ronny1982 I've made the code yesterday (and it works).
Here it is : 

```mjs
import WordPressMangastream from './templates/WordPressMangastream.mjs';

export default class LegacyScans extends WordPressMangastream {

    constructor() {
        super();
        super.id = 'legacyscans';
        super.label = 'Legacy-Scans';
        this.tags = ['webtoon', 'french'];
        this.url = 'https://legacy-scans.com/';
        this.path = '/manga/list-mode/';
    }
}

```
