### ISSUE TITLE
mangarawclub

### ISSUE THREAD

**Issue by hboy44** [manga-download/hakuneko#4171]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
None of the chapters are downloading

**To Reproduce**
1. mangarawclub
2. Click on any one
3. try to download any one
4. Download Failed

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Unable to reproduce, connector is working fine.
Please give a manga name & chapter that is failing for you as we cannot test the thousands titles.

**Comment by MikeZeDev** [comment]
Cant update manga list on manhwas (not men) anyway.

https://manhwas.net/manga-list/?list is error 404.

**Comment by MikeZeDev** [comment]
Website works flawlessly. 

@Sheepux pls <3
