### ISSUE TITLE
[Manhwas] Connector not working

### ISSUE THREAD

**Issue by Sanedrac1** [manga-download/hakuneko#4172]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
They changed the property to show chapters on their website so when pasting a link the chapters are not displayed.
To solve the problem I change **queryChapters** and **queryPages**
![solucion](https://user-images.githubusercontent.com/91925379/142906626-19ddbc69-7416-449b-9e0d-95c7d8ad9aff.png)

**To Reproduce**
1. Name of connector - Manhwas

2. Name of manga (if connector update is working) - N/A
3. Name of chapter (if manga update is working) - N/A
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![error manhwasnet](https://user-images.githubusercontent.com/91925379/142893937-94451f14-e858-462d-9b08-8c0d6fae39c1.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Sheepux** [comment]
Connector is working fine here.
the code you're showing doesn't belong to ManhwasMen

**Comment by Sanedrac1** [comment]
> Connector is working fine here. the code you're showing doesn't belong to ManhwasMen

I got confused. Both sites are similar and only differ in .net and .men. Sorry about that

**Comment by MikeZeDev** [comment]
https://manhwas.net/manga-list/?list is 404 error, cant update list anyway.

**Comment by MikeZeDev** [comment]
This has been fixed apparently. Can be closed @Sheepux pls?

**Comment by MikeZeDev** [comment]
Reopened because the problem arise again and it clearly website changes. Will be closed when fix is merged.
