### ISSUE TITLE
[Site Request] Kings Of Darkness Fansub

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4174]
**Name of the website**
Kings Of Darkness Fansub

**Website urls (examples below)**
- Site: https://kings-of-darkness.wixsite.com/
- Manga List: https://kings-of-darkness.wixsite.com/0000/proyectos
- Manga example: https://kings-of-darkness.wixsite.com/pod005
- Chapter online viewer example: https://kings-of-darkness.wixsite.com/pod005/copia-de-pod-00

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by onelots** [comment]
Website dead, can close this issue.

**Comment by Lenoyr** [comment]
The website has been reactivated.
