### ISSUE TITLE
[Asura Scans] Connector not working

### ISSUE THREAD

**Issue by Odaxis** [manga-download/hakuneko#4176]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error when trying to download, Error message "There was no content found for "Chapter ##"  Make sure it's accessible"

**To Reproduce**
1. Asura Scans (Others work)
2. Doctor's Rebirth (Or any other)
3. Chapter 62 (Or any other)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
  "There was no content found for "Chapter ##"  Make sure it's accessible"

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by ToiYeuTien** [comment]
I'm having the same problem, did you fix it?

**Comment by Sheepux** [comment]
This issue is from 2021, do not comment in a closed issue.
The issue is fixed, use the "nightly" version
