### ISSUE TITLE
[Site Request] unemployed scans

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4178]
**Name of the website**
unemployed scans

**Website urls (examples below)**
- Site: https://unemployedscans.com/
- Manga List: https://unemployedscans.com/manga/
- Manga example: https://unemployedscans.com/manga/brother-is-not-a-villain/
- Chapter online viewer example: https://unemployedscans.com/manga/brother-is-not-a-villain/chapter-16/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by onelots** [comment]
Website added, it will be on my next pr.
