### ISSUE TITLE
[Site Request] Sakuranovel

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#4185]
**Name of the website**
Sakuranovel

**Website urls (examples below)**
- Site: https://sakuranovel.id/
- Manga List: https://sakuranovel.id/daftar-novel/
- Manga example: https://sakuranovel.id/series/overlimit-skill-holder/
- Chapter online viewer example: https://sakuranovel.id/fake-saint-of-the-year-side-story-2b-bahasa-indonesia/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Little cloudflare check
