### ISSUE TITLE
[Site Request] manga weeaboo

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4189]
**Name of the website**
manga weeaboo

**Website urls (examples below)**
- Site: https://mangaweeaboo.com/
- Manga List: https://mangaweeaboo.com/manga
- Manga example: https://mangaweeaboo.com/manga/all-hail-the-sect-leader/
- Chapter online viewer example: https://mangaweeaboo.com/manga/all-hail-the-sect-leader/chapter-90/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dead website?

**Comment by Lenoyr** [comment]
> Dead website?

Yeah
