### ISSUE TITLE
[Manga-Scantrad] Connector not working

### ISSUE THREAD

**Issue by Vatox-G** [manga-download/hakuneko#4190]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
nothing is displayed when i press the button to synchronize

**To Reproduce**
1. Manga-Scantrad
4.  _getUpdatedMangasFromFile Error: ENOENT: no such file or directory
<html>
<body>

(anonymous) | @ | Connector.mjs:215
-- | -- | --
  | Promise.catch (async) |   |  
  | _getUpdatedMangasFromFile | @ | Connector.mjs:213
  | (anonymous) | @ | Connector.mjs:150
  | Promise.then (async) |   |  
  | getMangas | @ | Connector.mjs:147
  | onSelectedConnectorChanged | @ | mangas.html:215
  | runObserverEffect | @ | property-effects.html:217
  | runEffectsForProperty | @ | property-effects.html:162
  | runEffects | @ | property-effects.html:128
  | _propertiesChanged | @ | property-effects.html:1662
  | _flushProperties | @ | properties-changed.html:341
  | _flushProperties | @ | property-effects.html:1510
  | _invalidateProperties | @ | property-effects.html:1482
  | runNotifyEffects | @ | property-effects.html:261
  | _propertiesChanged | @ | property-effects.html:1665
  | _flushProperties | @ | properties-changed.html:341
  | _flushProperties | @ | property-effects.html:1510
  | _invalidateProperties | @ | property-effects.html:1482
  | set | @ | property-effects.html:1817
  | selectConnector | @ | connectors.html:303
  | handler | @ | template-stamp.html:96
  | (anonymous) | @ | templatize.html:149

</body>
</html>

POST https://manga-scantrad.net/wp-admin/admin-ajax.php 503 Connector.mjs:434
fetchDOM @ Connector.mjs:434
_getMangasFromPage @ WordPressMadara.mjs:50
_getMangas @ WordPressMadara.mjs:42
_getMangaList @ Connector.mjs:576
(anonymous) @ Connector.mjs:99
Promise.then (async)
updateMangas @ Connector.mjs:98
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Robonau** [comment]
no issues here

**Comment by Sheepux** [comment]
works fine as well
