### ISSUE TITLE
[Site Request] X Mangas Origines

### ISSUE THREAD

**Issue by xavimaa** [manga-download/hakuneko#4194]
**Name of the website**
x mangas origines

**Website urls (examples below)**
- Site: https://x.mangas-origines.fr/
- Manga List: https://x.mangas-origines.fr/catalogue/
- Manga example: https://x.mangas-origines.fr/catalogue/young-boss/
- Chapter online viewer example: https://x.mangas-origines.fr/catalogue/young-boss/chapitre-1/

**Languages**
French

**Website relationship*
This site is the new section x of the site https://mangas-origines.fr/

**Additional details**
There is already an extension for the https://mangas-origines.fr/ website but it does not take into account the new chapters on the https://x.mangas-origines.fr/ website

**Comment by MikeZeDev** [comment]
Cloudflare...
