### ISSUE TITLE
[Reaper Scans] Connector not working

### ISSUE THREAD

**Issue by Trinthakis** [manga-download/hakuneko#4200]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can only view the chapter list for 4 of the 65 mangas in the manga list, the rest are blank.

**To Reproduce**
1. Reaper Scans
2. These mangas work:
    21st Century Archmage
    Kill the Hero
    SSS-Class Suicide Hunter
    The Great Mage Returns After 4000 Years
3. The rest show 0/0

**HakuNeko (please complete the following information):**
 - Version 6.17@9436d8

**Comment by JerichoZ99** [comment]
Same for me although only this novel (not manga) appears in the list: _21st Century Archmage_.
Clicking on a chapter gives the message:
![Capture](https://user-images.githubusercontent.com/75426262/145211960-4ab4decb-b5a5-4936-acaa-b690a0e92407.JPG)
"

**Comment by Robonau** [comment]
everything works that should work for me

21st Century Archmage wont cause of the different chapter structure (and its a novel)

**Comment by M1A1H** [comment]
When will the problem be fixed?

**Comment by Kyuusei000** [comment]
I doubt it according to the comments there are no problems although I also have that problem ...

![image](https://user-images.githubusercontent.com/93754396/147811891-e90bf87c-6446-4642-97b5-96aa6366ca17.png)

**Comment by Sheepux** [comment]
connector is working fine.
Make sure you refresh the list (they changed the manga IDs). The total of titles should be 79
Also... remove your old bookmarks in red.
Let me know if it's working so that i close it.

**Comment by M1A1H** [comment]
yes it started working two weeks ago, thanks
