### ISSUE TITLE
[Bilibili] Connector not working properly

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#4201]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Only two pages showing per chapter

**To Reproduce**
1. Name of connector - Bilibili Comics
2. Name of manga (Tales of Demons and Gods)
3. Name of chapter (if manga update is working) - Chapters 35 and onward
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - I couldn't find anything but just in case, I screen shotted it.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="1099" alt="Screen Shot 2021-12-06 at 6 23 50 PM" src="https://user-images.githubusercontent.com/70929406/144954919-f23e4914-dd69-46bc-8891-fc694b5b85d9.png">
<img width="557" alt="Screen Shot 2021-12-06 at 6 26 06 PM" src="https://user-images.githubusercontent.com/70929406/144954923-c8fbab63-4a3e-497a-a14f-68edf6602f82.png">
<img width="580" alt="Screen Shot 2021-12-06 at 6 26 16 PM" src="https://user-images.githubusercontent.com/70929406/144954925-86cacdc0-9ffc-41d4-8b2d-db72418918f9.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
Cannot be reproduced on my end, there are only two pages on the website. It also clearly states you need to login to get bonus episodes.

**Comment by tsentered** [comment]
When this ticket was set up logins were not required (clear or otherwise) but the issue was there. But thanks regardless.
