### ISSUE TITLE
[Site Request] Online Ichijinsha

### ISSUE THREAD

**Issue by HaniToyoda** [manga-download/hakuneko#4202]
**Name of the website**
Online Ichijinsha

**Website urls (examples below)**
- Site: https://online.ichijinsha.co.jp/zerosum
- Manga List: https://online.ichijinsha.co.jp/zerosum/works
- Manga example: https://online.ichijinsha.co.jp/zerosum/comic/mobuoshi
- Chapter online viewer example: https://static.ichijinsha.co.jp/online/u/book/zerosum/mobuoshi/e2c3a355d8ff8838a31bf6ea93bbda6b/index.html

**Languages**
Japanese

**Website relationship*
The online reader of Zerosum

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Ever4engel** [comment]
Already added. Please check in the program before opening a new issue here next time.

**Comment by MikeZeDev** [comment]
Can be closde @Sheepux pls.
