### ISSUE TITLE
[Site Request] coloredmanga

### ISSUE THREAD

**Issue by nowusee911** [manga-download/hakuneko#4203]
**Name of the website**
coloredmanga

**Website urls (examples below)**
- Site: https://coloredmanga.com/
- Manga List: https://coloredmanga.com/manga/
- Manga example: https://coloredmanga.com/manga/one-piece/
- Chapter online viewer example: https://coloredmanga.com/manga/one-piece/volume-1/chapter-1/

**Languages**
List of languages supported by the website
English

**Website relationship*
none

**Comment by Ever4engel** [comment]
Already added. Please check in the program before opening a new issue here next time

**Comment by nowusee911** [comment]
I just check again and no the program does not have this connection **colored manga** . The one it currently has is called **true colored scan** which is not the same one. This one (**colored manga** )  in particular has some official releases and many other colored manga.

**Comment by Robonau** [comment]
> I just check again and no the program does not have this connection **colored manga** . The one it currently has is called **true colored scan** which is not the same one. This one (**colored manga** ) in particular has some official releases and many other colored manga.

no, this was already added
![image](https://user-images.githubusercontent.com/30987265/145383286-334e6828-eee1-4608-a4af-fa331258dbca.png)

**Comment by somegoodshet** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/78900371/145521724-3e0d8f76-0fac-4787-b452-c0d30119d26b.PNG)
I cant find it either.
And when i try using the clipboard, it does not update

**Comment by Ever4engel** [comment]
> ![Skjermbilde](https://user-images.githubusercontent.com/78900371/145521724-3e0d8f76-0fac-4787-b452-c0d30119d26b.PNG) I cant find it either. And when i try using the clipboard, it does not update

right now, available in the nightly version, wait until merged to the stable version or use the nightly version.

**Comment by 27136773** [comment]
See: #4124
