### ISSUE TITLE
[https://www.baozimh.com/] Baozimh

### ISSUE THREAD

**Issue by Knan2039** [manga-download/hakuneko#4206]
**Name of the website**
Baozimh

**Website urls (examples below)**
- Site: https://www.baozimh.com/
- Manga List: https://www.baozimh.com/classify
- Manga example: https://www.baozimh.com/comic/huidaolimingqian-wenyuan
- Chapter online viewer example: https://www.webmota.com/comic/chapter/huidaolimingqian-wenyuan/0_3.html

**Languages**
Chinese

**Website relationship*

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
implemented in 02/2022
https://github.com/manga-download/hakuneko/commits/master/src/web/mjs/connectors/Baozimh.mjs
