### ISSUE TITLE
[Site Request] Nonstopscans.com

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#4207]
**Name of the website**
(https://www.nonstopscans.com/)

**Website urls (examples below)**
- Site: https://www.nonstopscans.com/
- Manga List: https://www.nonstopscans.com/series/
- Manga example: https://www.nonstopscans.com/manga/reborn-80000-years/
- Chapter online viewer example: https://www.nonstopscans.com/1-reborn-80000-years/

**Languages**
English

**Website relationship*
-

**Additional details**
-

**Comment by MikeZeDev** [comment]
Dead website . @Sheepux pls <3
