### ISSUE TITLE
[Kuman57] Connector not working

### ISSUE THREAD

**Issue by Enbekkor** [manga-download/hakuneko#4208]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No (I tried, so first 2 minutes nothing happens, and after this browser sends me to www.kmwu6.com, screenshots of the console are given below)

**Describe the bug**
Infinite loading without any result

**To Reproduce**
1. Website - Kuman57
2. Namo of the comic - 绝世战魂 (if connector update is working)
3. Chapters - All chapters (if manga update is working)
4. Problem - Just infinite loading screen

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![image](https://user-images.githubusercontent.com/95868882/145422459-666d0cb4-1ded-4aae-9a47-5bcebbfd4ac9.png)
![image](https://user-images.githubusercontent.com/95868882/145422502-b026dd2b-1077-4dbb-8b30-500489b75e63.png)

**Comment by Robonau** [comment]
website no longer exists
