### ISSUE TITLE
[Site Request] kuman56

### ISSUE THREAD

**Issue by Enbekkor** [manga-download/hakuneko#4209]
**Name of the website**
[thewebsitename](kuman56)

**Website urls (examples below)**
- Site: http://kuman56.com/
- Manga List: http://kuman56.com/sort/1-1.html
- Manga example: http://kuman56.com/12478/
- Chapter online viewer example: http://kuman56.com/12478/1308429.html

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dead?
