### ISSUE TITLE
UnionMangás pt-br (not loading chapters)

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#421]
Good afternoon, after changing the site address I can not load the chapters of UnionMangás, only appear the chapters that I had already downloaded, I tested the program I was using, downloaded the portable version and had the same problem, so I installed the program on another computer and again couldn't load the chapters

The chapters on Union that were in the [bookmarks] are updated and show the chapters, but it is not possible to download, displaying the message: 'failed to fetch'
I use v5.0.8 and rev.65cd84, windows 10 64bits

Thanks if you can help ..
<a href="https://imgur.com/NDsiiZe"><img src="https://i.imgur.com/NDsiiZe.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/gFk5bFR"><img src="https://i.imgur.com/gFk5bFR.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/etgtgAR"><img src="https://i.imgur.com/etgtgAR.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/2G5QlGR"><img src="https://i.imgur.com/2G5QlGR.png" title="source: imgur.com" /></a>

**Comment by 27136773** [comment]
Fixed in 44340af0
Duplicate: #420, #409

**Comment by 27136773** [comment]
5.0.8 is feature locked (only high severity bugs are fixed)
Made an exception since this was a simple one and merged the fix to 5.0.8
Restart to update then it should work
