### ISSUE TITLE
[Site Request] mangatigre

### ISSUE THREAD

**Issue by webrootpro** [manga-download/hakuneko#4210]
**Name of the website**
mangatigre

**Website urls (examples below)**
- Site: https://www.mangatigre.com/
- Manga List: https://www.mangatigre.com/mangas
- Manga example: https://www.mangatigre.com/manga/1-000-000-000-000-game
- Chapter online viewer example: https://www.mangatigre.com/manga/1-000-000-000-000-game/1

**Languages**
List of languages supported by the website :ES

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3681
