### ISSUE TITLE
[Site Request] mangadig

### ISSUE THREAD

**Issue by Mammad211** [manga-download/hakuneko#4211]
**Name of the website**
mangadig

**Website urls (examples below)**
- Site: https://mangadig.com
- Manga List: https://mangadig.com/show
- Manga example: https://mangadig.com/11843/
- Chapter online viewer example: https://mangadig.com/11843/1/95.html

**Languages**
English

**Website relationship*
like other website that will gather Manga Manhua and etc but have very good archive

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/3731
