### ISSUE TITLE
[Toonily] Connector not working

### ISSUE THREAD

**Issue by xavimaa** [manga-download/hakuneko#4212]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
"Failed to update manga list for Toonily : Cannot read property 'href' of undefined"

**To Reproduce**
1. Name of connector : Toonily
2. Name of manga : All
3. Name of chapter : All
4. Problem : Access to the site from the connector no longer works

**Screenshots**
![image](https://user-images.githubusercontent.com/82511742/145675446-dbd76bce-f3bf-401b-b00b-bca82cc1acf8.png)

**HakuNeko (please complete the following information):**
 - Version Nightly rev. master@0a7876

**Comment by Dark-Load** [comment]
Same issue. Maybe it has something to do with cloudfare. it doesn't read the hakuneko's inbuilt browser but reads other browsers(chrome,edge).

**Comment by Robonau** [comment]
cloudflare issue #2933, wont be fixed

**Comment by Dark-Load** [comment]
Issue now fixed in nightly version 👍

**Comment by ResidualValue** [comment]
I have the same issue here. I tested both stable and nightly version (master@92824b).

**Comment by jstefansson6** [comment]
It worked yesterday but not anymore again today

**Comment by Dark-Load** [comment]
ya its not working now

**Comment by Dark-Load** [comment]
Toonily is back again Download anything you want asap in case it goes offline again
