### ISSUE TITLE
[manga livre] Connector not working

### ISSUE THREAD

**Issue by tailalima** [manga-download/hakuneko#4217]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
not working, no download

**To Reproduce**
1. manga livre
**Screenshots**
![image](https://user-images.githubusercontent.com/88906108/146093763-ea7eaa6d-95d3-439f-ae47-4b254fa797b9.png)
![image](https://user-images.githubusercontent.com/88906108/146093785-021604b7-21c7-4181-8e2b-8b014c614ea6.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Geoblocked

**Comment by MikeZeDev** [comment]
Duplicated https://github.com/manga-download/hakuneko/issues/4061
