### ISSUE TITLE
[Site Request] TumangaOnline

### ISSUE THREAD

**Issue by potato899** [manga-download/hakuneko#4218]
**Name of the website**
TuMangaOnline

**Website urls (examples below)**
- Site: https://lectortmo.com/
- Manga List: https://lectortmo.com/library/manhwa/54527/the-max-leveled-hero-will-return
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://cook2love.com/news/295d4751f09a596244efa9584abd19d7/cascade

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by diegowrhasta** [comment]
There's support for this site already

**Comment by onelots** [comment]
as diegowhrasta said, the connector still exists 🤨
