### ISSUE TITLE
Unable to load chapters from MangaRock

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#422]
Since 3 days, Hakuneko is unable to load manga's chapters form MangaRock.com 
![Capture d’écran (37)](https://user-images.githubusercontent.com/11735800/64899588-b35c4180-d67b-11e9-840a-94d8a859cbf5.png)

**Comment by 27136773** [comment]
Does it work on the website?

**Comment by Ever4engel** [comment]
mangarock will shut down.
