### ISSUE TITLE
[IsekaiScans] Connector not working

### ISSUE THREAD

**Issue by HishaamDeVries** [manga-download/hakuneko#4224]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
On the Isekaiscan connector it won't show the manga chapters for any manga and when I try to synchronize the connector it gives a CloudFlare Error 522

**To Reproduce**
1. Enter IsekaiScan connector 
2. Click on any Manga in said Connector
3. After loading for a while it will stop and show no chapters
4. CloudFlare Error 522

**HakuNeko
 - Version nightly(master) • 2020-07-05T00:14:37UTC

**Comment by Robonau** [comment]
IsekaiScans is doing maintenance right now, there is nothing HN can do about that

this issue should be closed

**Comment by Sheepux** [comment]
website seems more likely dead.

I propose to delete it.

**Comment by HishaamDeVries** [comment]
its not dead they have been having issue since they data base went down a few months ago but are fixing it and more manga are being updated daily, so I say keep it

**Comment by MikeZeDev** [comment]
Cant bypass Cloudflare  "verify you are human".

**Comment by Sheepux** [comment]
it's not the (infinite reload) cloudflare issue, it's probably a missing header triggering the protection

**Comment by Druzai** [comment]
> Cant bypass Cloudflare "verify you are human".

Strange. I don't have this Cloudflare issue.
Connector works on nightly.
![image](https://user-images.githubusercontent.com/70586473/189769228-099ec5e3-c071-405e-add2-ab58f587b27a.png)

**Comment by MikeZeDev** [comment]
Just tested now, its working. Well its not the first time i got CF issues with IsekaiScan and they suddenly vanishes.
"Fixed", i guess?

**Comment by MikeZeDev** [comment]
Still working. @Sheepux pls <3

**Comment by Sheepux** [comment]
seems fine, they probably reduced the cloudflare sensitivity
