### ISSUE TITLE
[Site Request] Azora World

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#4225]
**Name of the website**
Azora World

**Website urls**
- Site: https://azoraworld.com/
- Manga List: https://azoraworld.com/series/
- Manga example: https://azoraworld.com/series/slave-b/
- Chapter online viewer example: https://azoraworld.com/series/slave-b/44/

**Languages**
Arabic

**Additional details**
Provide: Manga - Manhua - Manhwa

**Comment by onelots** [comment]
Done, it will be in my next pr.
