### ISSUE TITLE
Toonily https://toonily.com/ not working anymore

### ISSUE THREAD

**Issue by jimiz88** [manga-download/hakuneko#4226]
![image](https://user-images.githubusercontent.com/96447061/146832739-bb97b639-294e-4681-8608-4d7d39a8aa75.png)

**Comment by Dark-Load** [comment]
Issue now fixed in nightly version 👍

**Comment by jstefansson6** [comment]
It worked yesterday but not anymore again today

**Comment by Dark-Load** [comment]
aaahhhhh shit you're right its not working again

**Comment by Dark-Load** [comment]
Toonily is back again Download anything you want asap in case it goes offline again

**Comment by Dark-Load** [comment]
it's offine now
