### ISSUE TITLE
manga18.club not working manga18.club

### ISSUE THREAD

**Issue by jimiz88** [manga-download/hakuneko#4227]
![image](https://user-images.githubusercontent.com/96447061/146833658-dcf9bfd9-1bf1-40f3-b363-4bfc5fd41a0d.png)

**Comment by jimiz88** [comment]
please

**Comment by Destiny-o24** [comment]
> ![image](https://user-images.githubusercontent.com/96447061/146833658-dcf9bfd9-1bf1-40f3-b363-4bfc5fd41a0d.png)

<img width="1762" height="988" alt="Image" src="https://github.com/user-attachments/assets/91ad3544-9ffa-4946-a9fc-8b13695562cd" />

I have same problem how can I solve this?


<img width="1398" height="858" alt="Image" src="https://github.com/user-attachments/assets/96f7da17-ab95-4075-9342-d0bc3aa672dd" />
I'm opening Toongod site mangas but it doesn't opening.
