### ISSUE TITLE
[Opiatoon] Connector not working

### ISSUE THREAD

**Issue by spicablock** [manga-download/hakuneko#4229]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Website is changed.

**To Reproduce**
1. https://opiatoon.net/ (old one https://opiatoon.com)
2. https://opiatoon.net/manga/beware-of-demons
3. https://opiatoon.net/manga/beware-of-demons/bolum-0/

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by onelots** [comment]
done, I'll put it in my next pr
