### ISSUE TITLE
Probleme avec japscan.to

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#423]
> **From:** HakuNeko User

je veux tetecharger manga "Sprite" sur japscan.to mais ça marche pas svp régler ce probleme le vite possible
merci

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Astoria951** [comment]
Bonjour J'utilise HakuNeko

Je ne peux plus télécharger sur japscan.lol ni sur bento manga. Y a t il possibilité de résoudre sur ce problème svp ? merci d'avance.
