### ISSUE TITLE
[Site Request] Yaoiflix

### ISSUE THREAD

**Issue by spicablock** [manga-download/hakuneko#4230]
**Name of the website**
Yaoiflix

**Website urls (examples below)**
- Site: https://www.yaoiflix.org/
- Manga List: https://www.yaoiflix.org/
- Manga example: https://www.yaoiflix.org/dizi/painter-of-the-night-turkce-oku/
- Chapter online viewer example: https://www.yaoiflix.org/bolum/gece-ressami-bolum-1/

**Languages**
Turkish

**Website relationship**
https://www.yaoiflix.fun/ 
https://www.yaoiflix.com/ 
https://www.yaoiflix.me/ 
https://www.yaoiflix.com/

**Additional details**
Wordpress Movifox theme 
Yaoi Webtoon Hentai

**Comment by MikeZeDev** [comment]
It load an interactive world map for me wtf? 

dead website? @Sheepux pls ?

**Comment by spicablock** [comment]
> Benim için interaktif bir dünya haritası yüklüyor wtf?
> 
> ölü web sitesi?@Sheepuxlütfen ?

it's https://www.yaoiflix.be/ now

**Comment by spicablock** [comment]
> It load an interactive world map for me wtf?
> 
> dead website? @Sheepux pls ?

it's https://www.yaoiflix.be/ now

**Comment by MikeZeDev** [comment]
404not found
