### ISSUE TITLE
[Site Request] https://ww2.mangakakalots.com/

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4233]
**Name of the website**
(https://ww2.mangakakalots.com/)

**Website urls (examples below)**
- Site: https://ww2.mangakakalots.com/
- Manga List: https://ww2.mangakakalots.com/manga_list/?type=latest&category=all&state=all&page=1
- Manga example: https://ww2.mangakakalots.com/manga/manga-qm951521
- Chapter online viewer example: https://ww2.mangakakalots.com/chapter/manga-qm951521/chapter-70

**Languages**
English

**Website relationship*
Alternative of the mangakakalots.com

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by onelots** [comment]
Mangakakalot connector already exists 🤨

**Comment by dnet890** [comment]
same name. But, the domain is different

**Comment by onelots** [comment]
I'm pretty sure that it's [that connector](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/MangaKakalots.mjs)

**Comment by dnet890** [comment]
but, the url is totally different and I got this url from tachiyomi. You can check it

**Comment by Jaxk69** [comment]
4 0 3 
Forbidden

**Comment by Jaxk69** [comment]
It's a mirror website and there's already a connector for mangakakalot.
So, they won't make a connector .

**Comment by dnet890** [comment]
I got this url from tachiyomi and tachiyomi treat this url as a separate entity called mangakakalots unoriginal. So, I think it is good because if there is something bad  happened with mangakakalots. we can still access its content. Why not do the same? 
PS: Hakuneko already did the same with kissmanga and manganelo
![image](https://user-images.githubusercontent.com/29157187/150908050-dba908a8-d03f-4e88-8dc8-e44b07ee8b0c.png)

![image](https://user-images.githubusercontent.com/29157187/150907874-2c1f6ed9-abbc-4733-b461-dbe4ce0912fe.png)

**Comment by MikeZeDev** [comment]
It seems dead, Jim.
