### ISSUE TITLE
[Site Request] mangahere.today

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4234]
**Name of the website**
mangahere.today

**Website urls (examples below)**
- Site: http://mangahere.today/
- Manga List: http://mangahere.today/latest-manga
- Manga example: http://mangahere.today/manga/the-four-knights-of-the-apocalypse
- Chapter online viewer example: http://mangahere.today/the-four-knights-of-the-apocalypse-chapter-44#1

**Languages**
English

**Website relationship*
alternative of mangahere.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4059 . Can be closed @Sheepux
