### ISSUE TITLE
[Site Request] Aqua Manga

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4235]
**Name of the website**
Aqua Manga

**Website urls (examples below)**
- Site: https://aquamanga.com/
- Manga List: https://aquamanga.com/manga/
- Manga example: https://aquamanga.com/read/black-clover/
- Chapter online viewer example: https://aquamanga.com/read/black-clover/chapter-317/

**Languages**
English

**Website relationship*
independent

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by onelots** [comment]
Done, I'll put it in my next PR.

**Comment by MikeZeDev** [comment]
Added to Haruneko https://github.com/manga-download/haruneko/pull/344
