### ISSUE TITLE
[Site Request] Koomanga

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4238]
**Name of the website**
KooManga

**Website urls (examples below)**
- Site: https://w10.koomanga.com/
- Manga List: https://w10.koomanga.com/manga-list/
- Manga example: https://w10.koomanga.com/mahou-tsukai-no-yome/
- Chapter online viewer example: https://w10.koomanga.com/mahou-tsukai-no-yome-chap-80-5/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website supported.

@Sheepux pls <3
