### ISSUE TITLE
[Site Request] manganelos

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4239]
**Name of the website**
manganelos

**Website urls (examples below)**
- Site: http://manganelos.com/
- Manga List: http://manganelos.com/latest-manga
- Manga example: http://manganelos.com/manga/boku-no-hero-academia
- Chapter online viewer example: http://manganelos.com/chapter/boku-no-hero-academia-chapter-338#1

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by onelots** [comment]
It's a Laravel CMS, not a wordpress or anything.

**Comment by Sheepux** [comment]
Already implemented. Please check the list first.
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/Manganelos.mjs

**Comment by dnet890** [comment]
I cannot find it when I search manga through this connector
