### ISSUE TITLE
[WeLoveManga] Connector not working

### ISSUE THREAD

**Issue by diegowrhasta** [manga-download/hakuneko#4243]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The site can no longer be fetched through the connector, nor chapters using the Clipboard module

**To Reproduce**
1. Access WeLoveManga connector
2. Try to retrieve list

**Screenshots**
![imagen](https://user-images.githubusercontent.com/26168851/147396214-0f55a012-c5d5-4e71-a798-d984853c2f7c.png)
![imagen](https://user-images.githubusercontent.com/26168851/147396216-16cd9cf6-7853-4849-be88-837b488180c5.png)

It used to work by just parsing a manga entry to retrieve its chapters, but that's no longer the case, the request is done correctly (at least the HTTP Status Code is 200), but the interface doesn't show anything.
![imagen](https://user-images.githubusercontent.com/26168851/147396234-6806a04a-419e-42ad-be3b-aa4185ca07d1.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Robonau** [comment]
the 404 is caused by welomas ddos protection
you can use manual website interaction to "prove you are human" then it should work fine

**Comment by diegowrhasta** [comment]
I did enter through the manual website interaction:

![imagen](https://user-images.githubusercontent.com/26168851/147805260-51bc6218-39f0-4555-868c-05a7154789d3.png)

![imagen](https://user-images.githubusercontent.com/26168851/147805265-b8d2c341-7d12-4e76-833c-d712aa1098df.png)

After doing that, if I press the refresh button:

![imagen](https://user-images.githubusercontent.com/26168851/147805272-c53b2786-5792-4248-beb5-61b966ed5e9e.png)

That's when I get the "cannot read property"

![imagen](https://user-images.githubusercontent.com/26168851/147805279-b6c8340c-17cb-4147-a273-7126dd58919e.png)

Taking a look at the request it is trying to make I can get this endpoint:

![imagen](https://user-images.githubusercontent.com/26168851/147805303-2fdddb87-14a4-458f-b134-ce14b6aac5fd.png)

Trying to get it through a browser it shows this:

![imagen](https://user-images.githubusercontent.com/26168851/147805309-970b6149-1034-42c9-92cc-feb001eed42c.png)

Which leads me to believe that the old manga list that used to be there is no longer available, (at least through that specific endpoint).

**Comment by MikeZeDev** [comment]
Nevermind, Url changed, issue already opened.

**Comment by MikeZeDev** [comment]
Website doesnt answer

**Comment by MikeZeDev** [comment]
Tested : Works .
