### ISSUE TITLE
[Site Request] mangagohan

### ISSUE THREAD

**Issue by HillLiVys** [manga-download/hakuneko#4249]
**Name of the website**
mangagohan

**Website urls (examples below)**
- Site: https://mangagohan.com/
- Manga List: https://mangagohan.com/
- Manga example: https://mangagohan.com/manga/ochikobore-oujo-to-kuro-no-banken/
- Chapter online viewer example: https://mangagohan.com/manga/ochikobore-oujo-to-kuro-no-banken/%e7%ac%ac1-1%e8%a9%b1/

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment]
Template: wordpress madara
