### ISSUE TITLE
[Site Request] pocket shonenmagazine

### ISSUE THREAD

**Issue by HillLiVys** [manga-download/hakuneko#4251]
**Name of the website**
pocket shonenmagazine

**Website urls (examples below)**
- Site: https://pocket.shonenmagazine.com/
- Manga List: https://pocket.shonenmagazine.com/genre/3
- Manga example: https://pocket.shonenmagazine.com/episode/3269754496432809060
- Chapter online viewer example: https://pocket.shonenmagazine.com/episode/3269754496432809060

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Ever4engel** [comment]
Already in the program, please check supported connectors before opening a new request.
