### ISSUE TITLE
[Site Request] 包子漫画 webmota

### ISSUE THREAD

**Issue by engkhsky** [manga-download/hakuneko#4252]
**Name of the website**
包子漫画 webmota

**Website urls **
- Site: https://www.webmota.com/
- Manga List: https://www.webmota.com/classify
- Manga example: https://www.webmota.com/comic/feirenzai-fenzihudong
- Chapter online viewer example: https://www.webmota.com/comic/chapter/feirenzai-fenzihudong/0_758.html

**Languages**
List of languages supported by the website
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
alternative Sites:
https://www.baozimh.com/

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Added as Baozimanhua i guess.

@Sheepux pls <3

**Comment by Sheepux** [comment]
could be added as an option to set favorite altdomain

**Comment by MikeZeDev** [comment]
redirect to baozimh
