### ISSUE TITLE
[Site Request] Firecross

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4254]
**Name of the website**
Firecross

**Website urls (examples below)**
- Site: https://firecross.jp/
- Manga List: https://firecross.jp/ebook
- Manga example: https://firecross.jp/ebook/series/448
- Chapter online viewer example: https://firecross.jp/reader/3499?trial=0&token=0b7631a8-533b-4e36-8909-f7d2dfb21704

**Languages**
Japan

**Website relationship*

**Additional details**

**Comment by Ever4engel** [comment]
Duplicate from #3978
