### ISSUE TITLE
[olympusscanlation.com] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#4257]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/N

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error 404
**To Reproduce**
1. olympusscanlation.com
2. Any
3. Any
4. Error 404 and CLIPBOARD: https://olympusscanlation.com/manga/el-hombre-fuerte-del-manicomio/ TypeError: Cannot read property 'textContent' of undefined
    at OlympusScanlation._getMangaFromURI (mjs/connectors/templates/WordPressMangastream.mjs:81)
    at async hakuneko:/cache/mjs/connectors/system/ClipboardConnector.mjs:64
    at async Promise.all (index 0)
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Robonau** [comment]
seems to have changed template to madara

**Comment by onelots** [comment]
Okay, I'll do that tonight and it'll be in my next pr.

**Comment by rausina** [comment]
Thanks for your hard work. Regards
