### ISSUE TITLE
[Site Request] Fire Cross

### ISSUE THREAD

**Issue by Mrsimple8375** [manga-download/hakuneko#4261]
**Name of the website**
ファイアCROSS (Fire Cross)

**Website urls (examples below)**
- Site: https://firecross.jp/
- Manga List: https://firecross.jp/comic
- Manga example: https://firecross.jp/ebook/series/281
- Chapter online viewer example: https://firecross.jp/reader/3439?trial=0&token=ea1764e4-23e8-41b5-b963-d57e61f2fa03

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Ever4engel** [comment]
Duplicate from #3978
