### ISSUE TITLE
Manhwaid

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#4264]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Website Domain change to https://manhwaid.org/.

**To Reproduce**
1. Manhwaid

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by manh21** [comment]
Template: Wordpress madara
