### ISSUE TITLE
[MangaLife] Connector not working

### ISSUE THREAD

**Issue by kabul369** [manga-download/hakuneko#4267]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
i want to open "MagaLife" library but when i click to update the library appear the following message: "Failed to update manga list for MagaLife. ERR_CONNECTION_REFUSED https://manga4life.com/

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [6.1.7]

**Comment by Dark-Load** [comment]
try the nightly version for now until they solve the issue for the stable version(it works fine here)
https://github.com/manga-download/hakuneko/releases

**Comment by MikeZeDev** [comment]
Working as intended. @Sheepux pls?
