### ISSUE TITLE
[Site Request] Mangaroshi

### ISSUE THREAD

**Issue by blizzardnana** [manga-download/hakuneko#4269]
**Name of the website**
Mangaroshi

**Website urls (examples below)**
- Site: https://mangaroshionline.blogspot.com/
- Manga List: https://mangaroshionline.blogspot.com/search/label/Series?&max-results=20
- Manga example: https://mangaroshionline.blogspot.com/2021/11/everything-is-agreed-english.html
- Chapter online viewer example: https://mangaroshionline.blogspot.com/2022/01/chapter-101-109.html

**Languages**
List of languages supported by the website 
English, Chinese, Spanish 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dead without alternative
