### ISSUE TITLE
[olympusscanlation] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#4270]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
404

**To Reproduce**
1. olympusscanlation.com
2. Any
3. Any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
[olympus.log](https://github.com/manga-download/hakuneko/files/7799448/olympus.log)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Website works on nightly. Can be closed @Sheepux pls.
