### ISSUE TITLE
[doujindesu] Connector not working

### ISSUE THREAD

**Issue by akn19** [manga-download/hakuneko#4272]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
domain changed (doujindesu.xxx)

**To Reproduce**
1. doujindesu
2. https://doujindesu.xxx/manga/h-a-life/
3. https://doujindesu.xxx/2022/01/03/h-a-life/
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by manh21** [comment]
Template: wordpress mangastream

**Comment by amir32** [comment]
I have same website which is [paklix.com](https://www.paklix.com) and its not working connector stop working.
