### ISSUE TITLE
[Feature] MAL list sync

### ISSUE THREAD

**Issue by Sergiogd112** [manga-download/hakuneko#4273]
Add the possibility to sync one's list with MAL.
Doing so would require checking wether two series are the same since they may not share the title between MAL and the connector. I think that to start off, it could be done by the user in a similar manner as to add a phone number to a contact list(add to new or to an existing one). This would allow the implementation of similar features to the ones in MAL(sort by different parameters or filters).

**Comment by Sheepux** [comment]
duplicate see #3699 
but probably a more specific use case, i'd suggest commenting there
