### ISSUE TITLE
[Site Request] bacakomikid

### ISSUE THREAD

**Issue by reivi27** [manga-download/hakuneko#4283]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by reivi27** [comment]
Site: https://bacakomikid.com/
Manga List: https://bacakomikid.com/manga/list-mode/
Manga example: https://bacakomikid.com/manga/ima-made-ichido-mo-onna-atsukaisareta-koto-ga-nai-onna-kishi-wo-onna-atsukai-suru/
Chapter online viewer example: https://bacakomikid.com/toukyourevengers-chapter-01/

**Comment by reivi27** [comment]
Languages
List of languages supported by the website:

Indonesia

**Comment by manh21** [comment]
Template: wordpress mangastream
