### ISSUE TITLE
[Site Request] Lower World

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4285]
**Name of the website**
Lower World

**Website urls (examples below)**
- Site: https://www.lowerworld.fun
- Manga List: https://www.lowerworld.fun/search/label/Manga OR https://www.lowerworld.fun/search/
- Manga example: https://www.lowerworld.fun/2021/08/dating-with-tail.html
- Chapter online viewer example: https://www.lowerworld.fun/2022/01/dating-with-tail-bolum-18.html

**Languages**
Turkish

**Website relationship*
N/A

**Additional details**
N/A

**Comment by MikeZeDev** [comment]
dead
