### ISSUE TITLE
[Site Request] Bun Comics

### ISSUE THREAD

**Issue by AzureDragon101** [manga-download/hakuneko#4286]
**Bun Comics**
Bun Comics (baozimh)

**Website URLS:**
- Site: https: https://www.baozimh.com/
- Manga List: https://www.baozimh.com/classify
- Manga Example: https://www.baozimh.com/comic/bailianchengshen-fengxingzhe
- Chapter Online Viewer Example: https://www.webmota.com/comic/chapter/bailianchengshen-fengxingzhe/0_878.html

**Languages**
Chinese

**Website relationship*
(alternative for: https://www.kuaikanmanhua.com/)

**Additional details**
It has some manga, but they're all in Chinese. (Pretty irrelevant, I know.)

**Comment by MikeZeDev** [comment]
Website is supported..

@Sheepux pls <3
