### ISSUE TITLE
[Kuman57] Connector not working

### ISSUE THREAD

**Issue by AzureDragon101** [manga-download/hakuneko#4287]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
It is not able to download any chapters when prompted to.

**To Reproduce**
1. Name of connector: Kuman57
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message: 
[Failed to update Manga List for Kuman57]
[ERR_CONNECTION_TIMED_OUT http://kmwu6.com/]

**Screenshots**
![image](https://user-images.githubusercontent.com/97290422/148542656-2258ef05-d36d-4ac1-ac7e-ba79a31df61e.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.1.7]

**Comment by Sheepux** [comment]
Fill the form when it exists... especially step2 ... no the website doesn't work at all. Nothing hakuneko can fix.
