### ISSUE TITLE
[Site Request] Colored Manga

### ISSUE THREAD

**Issue by Fishbaitbait** [manga-download/hakuneko#4289]
**Name of the website**
Colored Manga

**Website urls (examples below)**
Website- https://coloredmanga.com/
Manga List- https://coloredmanga.com/?s=&post_type=wp-manga
Manga Example- https://coloredmanga.com/manga/chainsaw-man/
Chapter Online Example- https://coloredmanga.com/manga/chainsaw-man/volume-1-dog-chainsaw/chapter-1/

**Languages**
Some in english, some in french.

**Additional details**
It has all of Chainsaw man in colour and in english, so thats a plus.

**Comment by manh21** [comment]
Template: wordpress madara

**Comment by manh21** [comment]
Already added
See #4124

**Comment by MikeZeDev** [comment]
Already added. @Sheepux pls.
