### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by ggtylerr** [manga-download/hakuneko#4290]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The manga list is unable to update. It fetches ~100k entries, then resets to 0.

**To Reproduce**
1. Select Mangadex and refresh
2. Open F12
3. Wait till offset gets to 9900, then to 0.

**Screenshots**
![Screenshot of Console](https://user-images.githubusercontent.com/28498877/148642094-5b2478aa-c8b7-4141-aab9-8447c40b4c14.png)

**HakuNeko (please complete the following information):**
 - Nightly, revision [master@e69858](https://github.com/manga-download/hakuneko/commit/e698588355efa8b1e5d4d71cd64fa68d6f3edf3e)

**Comment by ggtylerr** [comment]
Nevermind, I underestimated how much manga there was. It just took ~30 minutes to get the list and looked like there was an error.

For those curious, there's 56k.

**Comment by sebbu2** [comment]
I have the same issue with the last nightly (2020-07-05T00:14:37UTC)
