### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by enricguasch** [manga-download/hakuneko#4298]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I access a manga through my bookmarks or I set MangaDex as my connector and select a manga, all the chapters appear but I can't download any of them, the error seen in the image below happens.

**To Reproduce**
1. MangaDex
2. Any manga
3. Any chapter
4. TypeError: Cannot read property 'map' of undefined
    at MangaDex._getPages (MangaDex.mjs:165)
    at async MangaDex._getPageList (Connector.mjs:615) 

**Screenshots**
![image](https://user-images.githubusercontent.com/91875383/148703012-3c8c6702-ff1f-464c-b558-565dacdfbdc2.png)

**HakuNeko (please complete the following information):**
 - Version  6.1.7@9436d8

**Comment by enricguasch** [comment]
Fixed by downloading nightly

**Comment by MarqFJA87** [comment]
> Fixed by downloading nightly

What do you mean by "downloading nightly"?

**Comment by enricguasch** [comment]
I was using the stable version of Hakuneko, but I read from other comments that there is another version of Hakuneko called "nightly" that is more updated but isn't as stable and so sometimes if there is a problem with a connector in the stable version it might work in the nightly.
