### ISSUE TITLE
[Site Request] bacamanga.org

### ISSUE THREAD

**Issue by akn19** [manga-download/hakuneko#4299]
**Name of the website**
BacamangaOrg

**Website urls (examples below)**
- Site: https://bacamanga.org/
- Manga List: https://bacamanga.org/manga/list-mode/
- Manga example: https://bacamanga.org/manga/arafoo-kenja-no-isekai-seikatsu-nikki/
- Chapter online viewer example: https://bacamanga.org/arafoo-kenja-no-isekai-seikatsu-nikki-chapter-29/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment]
Template: WordPress MangaStream
