### ISSUE TITLE
Some sources on NSFW manga doesn't work

### ISSUE THREAD

**Issue by VideoLikePro** [manga-download/hakuneko#430]
Me and 3 of my friends who are good followers of HakuNeko started to realize that some of the manga from some NSFW website/sources doesn't work. We tried many attempts even pasting the link to the downloader however we experienced with freezes and no manga list/chapters.

This works on some (not all) NSFW websites. Please fix this.

**Comment by hypoflex** [comment]
The source he's talking about is KissDoujin. they seem to have redirected their page to 9hentai which is going through cloudflare and ends up on the main page of 9hentai (see images)
![kissDoijin request 9hentai](https://i.gyazo.com/d1c9617970232a614dddac67f1c6eb03.png)
![kissDoijin request 9hentai](https://i.gyazo.com/7e48bd6a3ab93746f8f5950e32923ff2.png)

9hentai itself cant update the mangalist in HakuNeko
![image](https://user-images.githubusercontent.com/36196198/65042606-78972980-d959-11e9-804f-81058ad47fb1.png)

**Comment by 27136773** [comment]
Fixed:

- 9hentai b5e543f7
- AllHentai 7dec369d
- ASMHentai 9261077b

KissDoujin will be kept as is until it is confirmed that the website really went down / merged into 9hentai.

----

Also, please make a dedicated ticket for each website you want to have fixed.

- It is difficult for the developers to guess which websites are not working for the user
- The developers may spend precious time on fixing websites which are not requested (and therefore will not be used by anyone)
