### ISSUE TITLE
[Site Request]  Realm Scans 

### ISSUE THREAD

**Issue by rRoler** [manga-download/hakuneko#4302]
**Name of the website**
 Realm Scans 

**Website urls**
- Site: https://realmscans.com/
- Manga List: https://realmscans.com/series/
- Manga example: https://realmscans.com/series/mononogatari/
- Chapter online viewer example: https://realmscans.com/mononogatari-chapter-1/

**Languages**
English and Arabic on https://ar.realmscans.com/

**Website relationship**
Arabic version on: https://ar.realmscans.com/

**Additional details**
No.

**Comment by manh21** [comment]
Template: wordpress mangastream
