### ISSUE TITLE
[hiperdex] Connector not working

### ISSUE THREAD

**Issue by Odaxis** [manga-download/hakuneko#4304]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Console returns error "Failed to load resource: the server responded with a status of 503 ()"

**To Reproduce**
1. https://hiperdex.com
2. Manga list is loading or empty, (Icon not spinning)
3. n/a
4. Failed to load resource: the server responded with a status of 503 ()

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by Sheepux** [comment]
Cloudflare issue, unfixed. See #2933
