### ISSUE TITLE
[Team X] Connector not working - Site domain has changed

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#4305]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**

Please update the connector Team X , because the site has been changed

old one : https://www.team1x1.com/

new domain site : https://teamxmanga.com/

**Comment by Sheepux** [comment]
That's already the case (fixed 1 month ago).
