### ISSUE TITLE
text list of manga of website

### ISSUE THREAD

**Issue by notgoodperson** [manga-download/hakuneko#4306]
I hope to you make the possibility of export the following list of manga after scan the website

**Comment by Robonau** [comment]
all of the data is already exported and saved in json format in the userdata folder

**Comment by Sheepux** [comment]
There is no value for HN in adding such extra options. I'll close this issue in a few days unless there is more details on the use case.

**Comment by Sheepux** [comment]
no further details, closing. Feel free to give more info to reopen this issue.
