### ISSUE TITLE
[Site Request] Mangareader.to

### ISSUE THREAD

**Issue by Jaxk69** [manga-download/hakuneko#4308]
**Name of the website**
Mangareader

**Website urls (examples below)**
- Site: https://mangareader.to/
- Manga List: https://mangareader.to/az-list
- Manga example: https://mangareader.to/demon-slayer-kimetsu-no-yaiba-296
- Chapter online viewer example: https://mangareader.to/read/demon-slayer-kimetsu-no-yaiba-296/en/chapter-1

**Languages**
English And Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
When you read the manga there are three types of image quality - High, Medium and Low .
Also when you click on a manga there are two types of list Chapter and Volume .

**Comment by Ever4engel** [comment]
Duplicate #3979
