### ISSUE TITLE
install in Fedora

### ISSUE THREAD

**Issue by sunnlife1978** [manga-download/hakuneko#431]
Hi, 
i have some issue to install Hakuneko in Fedora:
hakuneko-desktop: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
i check that i have NSS and NSS-devel already installed
Could you help me please
Thanks

Alex

**Comment by 27136773** [comment]
Are you using the desktop client 5.0.8 or higher?

**Comment by 27136773** [comment]
See also #298

**Comment by sunnlife1978** [comment]
> Are you using the desktop client 5.0.8 or higher?

Yes I wanted use the last version of client desktop

**Comment by sunnlife1978** [comment]
and I have with fedora 28 not 30

**Comment by sunnlife1978** [comment]
Finalyy I did it, I use the wrong rpm (i386 instead of amd64) and now it's OK 
Thanks for the app
