### ISSUE TITLE
[Site Request] ACE SCANS

### ISSUE THREAD

**Issue by rRoler** [manga-download/hakuneko#4312]
**Name of the website**
ACE SCANS

**Website urls (examples below)**
- Site: https://acescans.xyz/
- Manga List: https://acescans.xyz/manga/
- Manga example: https://acescans.xyz/manga/home-cabaret-operation-making-a-cabaret-club-at-home-so-nii-chan-can-get-used-to-girls/
- Chapter online viewer example: https://acescans.xyz/home-cabaret-operation-making-a-cabaret-club-at-home-so-nii-chan-can-get-used-to-girls-chapter-1/

**Languages**
English

**Website relationship**
Early access site: https://s.acescans.xyz/

**Additional details**
No.

**Comment by manh21** [comment]
Template: wordpress mangastream
