### ISSUE TITLE
[Site Request] ZINNOVEL

### ISSUE THREAD

**Issue by Kiriri01** [manga-download/hakuneko#4313]
**Name of the website**
ZINNOVEL

**Website urls (examples below)**
- Site: https://zinnovel.com/
- Manga List: https://zinnovel.com/manga-genre/fantasy/
- Manga example: https://zinnovel.com/manga/becoming-the-villains-family/
- Chapter online viewer example: https://zinnovel.com/manga/becoming-the-villains-family/1/

**Languages**
ENGLISH

**Additional details**
NO

**Comment by manh21** [comment]
Template: wordpress madara
