### ISSUE TITLE
[Site Request] AnitationArts.org

### ISSUE THREAD

**Issue by Dpavlakis** [manga-download/hakuneko#4316]
**Name of the website**
Anitation Arts

**Website urls (examples below)**
- Site: https://anitationarts.org/
- Manga List: https://anitationarts.org/project/
- Manga example: https://anitationarts.org/manga/the-first-sequence/
- Chapter online viewer example: https://anitationarts.org/the-first-sequence-chapter-1/

**Languages**
English

**Website relationship*
N/A

**Additional details**
N/A

**Comment by manh21** [comment]
Template: wordpress mangastream
