### ISSUE TITLE
[Site Request] Comic Bushiroad

### ISSUE THREAD

**Issue by kid1485** [manga-download/hakuneko#4318]
**Name of the website**
ComicBushiroadWeb

**Website urls (examples below)**
- Site: https://comicbushi-web.com/
- Manga List: https://comicbushi-web.com/#lineup
- Manga example: https://comicbushi-web.com/episode/3269754496647728590
- Chapter online viewer example: https://comicbushi-web.com/episode/3269754496647728590

**Languages**
Japanese

**Comment by Jaxk69** [comment]
Duplicate #3993
