### ISSUE TITLE
[manhwa18.com] Connector not working

### ISSUE THREAD

**Issue by xlunarwastakenx** [manga-download/hakuneko#4320]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I go to the connector and click the green button to reload, no mangas popup. Ex:
![image](https://user-images.githubusercontent.com/98142191/150468650-f42b4b4a-b136-42fd-b32f-29df0deaccd3.png)
I have repeatedly clicked the button but no manga show up. 

**To Reproduce**
1.  manhwa 18: the site has visible chapters, but someone reason they don't load.

![image](https://user-images.githubusercontent.com/98142191/150468546-fdf56730-6f23-4865-ae53-966ae34fe570.png)
Thanks so much for you help

**Comment by MikeZeDev** [comment]
Preview and download works fine on nightly. @Sheepux ?

**Comment by Sheepux** [comment]
can confirm
