### ISSUE TITLE
[Comikey] Connector not working

### ISSUE THREAD

**Issue by lavavex** [manga-download/hakuneko#4321]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Unable to download owned chapters even if logged in, gives this error
SyntaxError: Unexpected token < in JSON at position ()

**To Reproduce**
1. comikey
2. Killer Vamp
3. Chapter 6 - I'm Not Afraid of You, Either (as well as 7,8,9,10 as those are the ones i own right now)
4. title="Click to re-download
SyntaxError: Unexpected token < in JSON at position 0"

**Screenshots**
![image](https://user-images.githubusercontent.com/27239435/150557203-f2abe531-c1ec-4dfb-8738-cfb44ba5ff7d.png)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by lavavex** [comment]
![image](https://user-images.githubusercontent.com/27239435/150558110-55e2ec45-6f99-446c-bf7b-91b3f74e7af6.png)
This is what i get if i try loading chapter in built in browser while logged in

**Comment by 27136773** [comment]
Ask in discord channel, certain `Comikey` related problems are not discussed on GitHub
