### ISSUE TITLE
[Site Request] Niadd IT

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4322]
Hi,

The only Italian manga site missing from HakuNeko that is available on FMD2 is Niadd IT. It would be nice to have it added on HakuNeko :)

Thank you

**Name of the website**
Niadd IT

**Website urls (examples below)**
- Site: https://it.niadd.com/
- Chapter list of manga example: https://it.niadd.com/manga/Noragami/chapters.html
- Manga example: https://it.ninemanga.com/chapter/Episodi-98/903593.html

**Languages**
Italian

**Website relationship**
I am a user of the website.

**Comment by manh21** [comment]
See #816
