### ISSUE TITLE
[1stkissmanga.io] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#4323]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
Error 403

**To Reproduce**
1. 1stkissmanga
2. Any
3. Any
4. 
[cache-1642810923842.log](https://github.com/manga-download/hakuneko/files/7917266/cache-1642810923842.log)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17].

**Comment by Sildran** [comment]
Same here. When clicking on a kissmanga bookmark, Hakuneko closes itself after 1 or 2 seconds.

**Comment by manh21** [comment]
![image](https://user-images.githubusercontent.com/31276236/150644808-f19a88e5-0812-4630-8ff4-8b44aa29feca.png)
Cloudflare issues see #2933

**Comment by rausina** [comment]
> ![image](https://user-images.githubusercontent.com/31276236/150644808-f19a88e5-0812-4630-8ff4-8b44aa29feca.png) Cloudflare issues see #2933

thanks for your time. Regards

**Comment by Sildran** [comment]
Issue was solved, but is now starting again : clicking on a kissmanga bookmark immediately closes Hakuneko

**Comment by Sheepux** [comment]
Issue found, there is cloudflare that triggers on some conditions.
Adding referer makes it that it doesn't trigger cldouflare  (PR incoming)
