### ISSUE TITLE
Is it possible to add TXT format for https://kolnovel.com/ And other novel sites[Bug]

### ISSUE THREAD

**Issue by nouroth** [manga-download/hakuneko#4329]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
No it is not implemented.

**Comment by 27136773** [comment]
To much effort to convert HTML to TXT
