### ISSUE TITLE
Mangapark long request time

### ISSUE THREAD

**Issue by hypoflex** [manga-download/hakuneko#433]
## Website Change
MangaPark takes about 5 minutes to pull all data, may be worth reviewing for improvement?
![image](https://user-images.githubusercontent.com/36196198/65083124-fb46d580-d9a7-11e9-9003-aefdad08ea38.png)

## Enhacement
Provide a combined download for these larger scrapers
(just a brainstorm)

**Comment by 27136773** [comment]
Previously suggested solutions:

**Always download the full manga list (used for almost any website)**
⊕ most up to date
⊖ may take long download time

**Only download new mangas not yet downloaded (not used)**
⊕ fast download
⊖ may miss updates (e.g. manga deleted or renamed)
⊖ existing manga links will no longer work when changed on the server side

**Use HakuNeko CDN (used for certain websites, e.g. KissManga)**
⊕ fast download
⊖ out of date for up to 14 days (manual CDN updates)
⊖ additional cost for implementation on CDN backend

**Comment by XenonR** [comment]
My personal suggestions are:
1. Use an _old_ locally cached manga list (there is no need to always refresh) or
2. Use clipboard import

In my opinion it can simply not be the aim for hakuneko to implement features that a website is lacking (eg. download a list of all mangas at once). Additionally i would refrain from parallel website request out of respect of the people maintaining these sites. And also it is more likely to get banned when hammering a server.
