### ISSUE TITLE
[Site Request] MangaReader.to

### ISSUE THREAD

**Issue by Weebster69** [manga-download/hakuneko#4332]
**Name of the website**
MangaReader

**Website urls (examples below)**
- Site: https://mangareader.to/
- Manga List: https://mangareader.to/type/manga
https://mangareader.to/type/manhwa
https://mangareader.to/type/manhua
 
- Manga example: https://mangareader.to/boruto-naruto-next-generation-8419
- Chapter online viewer example: https://mangareader.to/read/boruto-naruto-next-generation-8419/en/chapter-66

**Languages**
List of languages supported by the website : English, Japanese, Korean, Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment]
Duplicate of #3979
