### ISSUE TITLE
[Site Request] MangaReader.to

### ISSUE THREAD

**Issue by stellam-a** [manga-download/hakuneko#4339]
**Wesbite Name**
- MangaReader

**Website urls**
- Site: https://mangareader.to/
- Manga List: https://mangareader.to/az-list
- Manga example: https://mangareader.to/one-piece-3
- Chapter online viewer example: https://mangareader.to/read/one-piece-3/en/chapter-1037

**Languages**
- English
- Japenese

**Website relationship**
If applicable, describe the relation with any other website (e.g., "Sister site of [Zoro Anime](https://zoro.to/home) and [Sflix](https://sflix.to/home)".

**Comment by manh21** [comment]
Duplicate of #3979

**Comment by stellam-a** [comment]
Ohh, okay

**Comment by Jaxk69** [comment]
wtf? dude close this issue there's already an issue

**Comment by Ever4engel** [comment]
#4336
