### ISSUE TITLE
[Site Request] Infernal Void Scans

### ISSUE THREAD

**Issue by ElectroShade** [manga-download/hakuneko#4341]
**Name of the website**
Infernal Void Scans

**Website urls (examples below)**
- Site: https://infernalvoidscans.com/
- Manga List: https://infernalvoidscans.com/projects/
- Manga example: https://infernalvoidscans.com/manga/blue-flame-dot_jung_/
- Chapter online viewer example: https://infernalvoidscans.com/blue-flame-dot_jung_1/

**Languages**
English

**Comment by manh21** [comment]
Template: `WordPress MangaStream`
