### ISSUE TITLE
[Site Request] Wicked Dragon Scans

### ISSUE THREAD

**Issue by ElectroShade** [manga-download/hakuneko#4342]
**Name of the website**
Wicked Dragon Scans

**Website urls (examples below)**
- Site: https://wdscans.com/
- Manga List: https://wdscans.com/manga/
- Manga example: https://wdscans.com/manga/ryuu-kusari-no-ori-kokoro-no-uchi-no-kokoro/
- Chapter online viewer example: https://wdscans.com/manga/ryuu-kusari-no-ori-kokoro-no-uchi-no-kokoro/chapter-7/

**Languages**
English

**Comment by manh21** [comment]
Template: `Wordpress Madara`

**Comment by bhalalansh** [comment]
The site is being compromised.

**Comment by MikeZeDev** [comment]
Website doesnt answer

Dead? 

@Sheepux  pls?  <3
