### ISSUE TITLE
[Site Request] Mangas.io

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#4344]
**Name of the website**
Mangas io

**Website urls (examples below)**
- Site: https://www.mangas.io
- Manga List: https://www.mangas.io/manga-en-ligne
- Manga example: https://www.mangas.io/lire/17-ans
- Chapter online viewer example: https://www.mangas.io/lire/17-ans/1/1  (there is a parameter to put optimized content or **high quality image files**)

**Languages**
French

**Website relationship*
nothing to say.

**Additional details**
it's a french official digital publisher, he serve it's content as chapterlists. by default the reader serve webp files, but there is jpg/png files, so for the best possible experience, it need to grab jpg/png files instead of webp images. 

PS: all mangas have a free chapter (first chapter to read).

**Comment by MikeZeDev** [comment]
Can be closed as duplicate i guess @Sheepux pls
