### ISSUE TITLE
[Site Request] Mangago

### ISSUE THREAD

**Issue by luluchan93** [manga-download/hakuneko#4345]
**Mangago**

- Site:  https://mangago.me
- Manga List: https://www.mangago.me/list/directory/all/1/
- Manga example: https://www.mangago.me/read-manga/exotic_love/
- Chapter online viewer : https://www.mangago.me/read-manga/exotic_love/uu/mpn_chapter-2430606/pg-1/
**Languages**
English

**Comment by MikeZeDev** [comment]
Website is supported.

@Sheepux pls <3
