### ISSUE TITLE
[Site Request] Mangabuddy

### ISSUE THREAD

**Issue by Iloveboobs84** [manga-download/hakuneko#4346]
**Name of the website**

Mangabuddy.com

- Site: https://mangabuddy.com/
- Manga List: https://mangabuddy.com/popular
- Manga example: https://mangabuddy.com/maou-to-ore-no-hangyakuki
- Chapter online viewer example: https://mangabuddy.com/maou-to-ore-no-hangyakuki/chapter-1-1

**Languages**
English translated from Raws

**Website relationship*
https://manga-zip.info/dl/%E9%AD%94%E7%8E%8B%E3%81%A8%E4%BF%BA%E3%81%AE%E5%8F%9B%E9%80%86%E8%A8%98/

Raw manga directory has up to Volume 8 and Ongoing.

**Comment by MikeZeDev** [comment]
Similar to Toonily : MadTheme theme. On madara maybe?
