### ISSUE TITLE
[Site Request] https://manga-zip.info/home/

### ISSUE THREAD

**Issue by Iloveboobs84** [manga-download/hakuneko#4347]
**Name of the website**
https://manga-zip.info/home/

**Website urls (examples below)**
- Site: https://manga-zip.info/home/
- Manga List: https://manga-zip.info/a-z/
- Manga example: https://manga-zip.info/dl/%E3%81%82%E3%82%8A%E3%81%B5%E3%82%8C%E3%81%9F%E8%81%B7%E6%A5%AD%E3%81%A7%E4%B8%96%E7%95%8C%E6%9C%80%E5%BC%B7/

**Languages*
   Raw 

**Additional details**
Manga volume download site

**Comment by MikeZeDev** [comment]
This website doesnt have manga reader, only zip download. Its not fit for Hakuneko.
