### ISSUE TITLE
[Feature] Volume List Option 

### ISSUE THREAD

**Issue by Jaxk69** [manga-download/hakuneko#4349]
**Is your feature request related to a problem? Please describe.**
So, i have seen many sites which also have a volumes list other than the chapter list but there is no volume option in Hakuneko.

**Describe the solution you'd like**
Add a volume option for available sites and if there are no volumes leave it empty or NONE

**Describe alternatives you've considered**
I have suggested some methods below :-
 1)  I think there should a small button at the side of CHAPTER LIST so whenever we click on it, it changes from Chapter List to Volume list and Volumes are shown by the given name.  
2)  We can also change from Chapter List to Volume List just by click on Chapter List and it shows Volume list . It can revert back clicking on Volume List . (but it think this would be confusing for many people)
3)  Change the title from Chapter List to Chapter/Volume List and when we click on  (for e.g. Volumes) it would get highlighted with a blue colour and the list appear.    

**Context (please complete the following information):**
 - Current HakuNeko Stable v.6.1.7

**Additional context**
None

**Comment by Sheepux** [comment]
Not sure if someone will have time to implement but if you already know sites that behaves like that you should state them to help the dev process ;)

**Comment by Jaxk69** [comment]
Websites -
https://mangareader.to/    [FREE]
https://global.bookwalker.jp/   [PAID]

There were more of them but they got shut down

**Comment by Ever4engel** [comment]
> Websites - https://mangareader.to/ [FREE] https://global.bookwalker.jp/ [PAID]
> 
> There were more of them but they got shut down

Well it seems didn't understood what he meant... and even you did not get the difference between an aggregator website and an official Japanese digital book store...

all what you need to understand is, he said that too few people gonna use this if supported + 90% use chapters when they read on line. his second statement were just mandatory because there is no English aggregator website who use volume list. (Well... except this website.)

**Comment by Jaxk69** [comment]
> > Websites - https://mangareader.to/ [FREE] https://global.bookwalker.jp/ [PAID]
> > There were more of them but they got shut down
> 
> Well it seems didn't understood what he meant... and even you did not get the difference between an aggregator website and an official Japanese digital book store...
> 
> all what you need to understand is, he said that too few people gonna use this if supported + 90% use chapters when they read on line. his second statement were just mandatory because there is no English aggregator website who use volume list. (Well... except this website.)

So like should i close this issue ? 
They did say you can modify the already existing .mjs to receive volumes instead of chapters and use it as a User Plugin.
I tried doing that but it didn't work. Here's the pastebin link if you or anyone wanna try - https://pastebin.com/GaRyg28i 
The end-point link is correct btw.
