### ISSUE TITLE
SakuraManga failed image preview

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#435]
Some chapters does not show images, seems image link extraction fails
e.g. Attack on Titan => Chapter 110

----

![image](https://user-images.githubusercontent.com/27136773/65173982-487e8200-da50-11e9-80ab-c30593d7a096.png)

**Comment by hypoflex** [comment]
Website pulling the wrong URL/manga
given link for chapter 110:
https://sakuramanga.net/japanese-manga/attack-on-titan/shingeki-no-kyojin-110/

given link for chapter 111:
https://sakuramanga.net/japanese-manga/attack-on-titan/shingeki-no-kyojin-%e9%80%b2%e6%92%83%e3%81%ae%e5%b7%a8%e4%ba%ba-chap-111/

![image](https://user-images.githubusercontent.com/36196198/65174318-f5f19580-da50-11e9-8548-dba2dfc0935a.png)

**Comment by hypoflex** [comment]
HTTP seems to be working
http://fiona.epizy.com/wp-content/uploads/comic6/201812/0342.jpg?i=1
HTTPS giving a certificate error
https://fiona.epizy.com/wp-content/uploads/comic6/201812/0342.jpg?i=1

actual hakuneko image link
![image](https://user-images.githubusercontent.com/36196198/65174793-da3abf00-da51-11e9-90b9-fa701d1239e7.png)

**Comment by hypoflex** [comment]
all chapters without japanese text fail on the website itself and return a boku no hero alt title
running the given url of the image in HTTP works, and does actually return a AOT
```Shingeki no Kyojin 進撃の巨人 chap 111    04/2019
Shingeki no Kyojin 110    12/2018
Shingeki no Kyojin 109    12/2018
Shingeki no Kyojin 108    12/2018
Shingeki no Kyojin 107 – vol 27    12/2018
Attack on Titan 進撃の巨人 chap 106    08/2018```

**Comment by hypoflex** [comment]
reported the issue to the site owner.
