### ISSUE TITLE
[Site Request] manga-nato

### ISSUE THREAD

**Issue by giaez** [manga-download/hakuneko#4351]
**Name of the website**
manga nato

**Website urls (examples below)**
- Site: https://www.manga-nato.com/ not to be confused with the other manganato (https://manganato.com/) which is already available in Hakuneko
- Manga List: https://www.manga-nato.com/manga/
- Manga example: https://www.manga-nato.com/manga/i-m-the-only-one-loved-by-the-constellations/
- Chapter online viewer example: https://www.manga-nato.com/manga/i-m-the-only-one-loved-by-the-constellations/chapter-1/

**Languages**
English

**Additional details**
Template is exactly like Manga Kio (https://mangakio.com/) which is already available in Hakuneko

**Reason for suggesting**
Unlike other aggregate websites, this particular site has consistent source of their titles. In other connectors, some manhwa actually have different sources in each of their chapters (e.g. chapter 1 is taken from Asura scans, chapter 2 is from Shimada scans, chapter 3 is Reaper scans). In Manga Nato each of their title is taken from the same source instead.

**Comment by Jaxk69** [comment]
see #3511
