### ISSUE TITLE
[zeroscans.com] Connector not working

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#4352]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When updating the connector everything disappears; and when clicking on the manga the chapter doesn't appear.

**To Reproduce**
1. zeroscans
2. click on the updating button or on any manga
3. no chapter appears

**Screenshots**

![Screenshot (47)](https://user-images.githubusercontent.com/95138799/151385246-ef3a6ce6-175a-48f5-a32b-be2124011552.png)
![Screenshot (48)](https://user-images.githubusercontent.com/95138799/151385267-2bd354e9-983b-441b-bba7-bc6fe3245c20.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by manh21** [comment]
Cloudflare issues
![image](https://user-images.githubusercontent.com/31276236/151492407-08f27508-c7d2-47a0-9162-a18e26c673e7.png)

**Comment by Sheepux** [comment]
(that's not how you find out it's the cloudflare issue because hakuneko is working in some cloudflare case)
connector is working fine here

**Comment by Murshid7absi** [comment]
resolved
