### ISSUE TITLE
[NineMangaEs] Connector not working (Chapters with files .bin)

### ISSUE THREAD

**Issue by KasukeLp23** [manga-download/hakuneko#4353]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When downloading chapters (Of any title) of the extension "NinemangaEs" some files are downloaded in format **.bin** and not in **.jpg/.png** , etc.)

**To Reproduce**
1. NinemangaEs
2. Wotaku ni Koi wa Muzukashii (Happens with all titles)
3. Chapter. 72 ,ect (Happens with all chapters)

**Screenshots**
Used connector:
![image](https://user-images.githubusercontent.com/70596255/151418164-cfa30421-791f-42fc-821b-18875fb6d431.png)
Chapter 72 downloaded from"Wotaku ni Koi wa Muzukashii" **[**In the page "**02**" rename the file to .jpg and no image appears**]**
![image](https://user-images.githubusercontent.com/70596255/151418587-4f376832-b5ce-4c34-87b0-1603499220b8.png)
Chapter 01 downloaded from"Shikisaki Shimai wa Abakaretai"
![image](https://user-images.githubusercontent.com/70596255/151418843-45e84558-9b91-4d9e-88d0-78a2b97025dc.png)

**Note:
This only happens to me with this connector, I downloaded with others and it works perfectly**

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by doppler56** [comment]
If you have concurrent download turned on.  Turn it off.  The problem might go away.

**Comment by kuvoid** [comment]
> If you have concurrent download turned on. Turn it off. The problem might go away.

dont work

**Comment by KasukeLp23** [comment]
@doppler56 Does not work
