### ISSUE TITLE
[Site Request] MangaBuddy

### ISSUE THREAD

**Issue by AndyKills457** [manga-download/hakuneko#4357]
**Name of the website**
MangaBuddy

**Website urls (examples below)**
- Site: https://mangabuddy.com/
- Manga List: https://mangabuddy.com/az-list
- Manga example: https://mangabuddy.com/kimetsu-no-yaiba
- Chapter online viewer example: https://mangabuddy.com/kimetsu-no-yaiba/chapter-26-bare-handed-fight

**Languages**
English

**Website relationship**
None as far as I know.

**Additional details**
~

**Comment by Sheepux** [comment]
duplicate #4346
