### ISSUE TITLE
Show the Connector for a Bookmark

### ISSUE THREAD

**Issue by anders-eriksson** [manga-download/hakuneko#4359]
My memory is short, so I don't recall which connector a specific bookmark is using.

Is there someway of showing this in the program?

My problem is that some connectors are not working any more (the folder icon is grayed) and I don't know which...

**Comment by Sheepux** [comment]
Put your mouse over the bookmark ?

**Comment by anders-eriksson** [comment]
To quote a popular figure: D'oh!

I tried everything else, but this was to simple ;-)

Thanks
