### ISSUE TITLE
[Site Request] Haikyu!! - Read Haikyuu Manga Online in High Quality

### ISSUE THREAD

**Issue by miaomia0** [manga-download/hakuneko#4365]
**Website Name**
[Haikyu!! - Read Haikyuu Manga Online in High Quality]

**Website urls (examples below)**
- Site: https://haikyuumanga.org/
- Manga List: https://haikyuumanga.org/mangalist.html
- Manga example: https://haikyuumanga.org
- Chapter online viewer example: https://haikyuumanga.org/manga/haikyuu/haikyuu-chapter-0-one-shot/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
HN doest not accept one-manga websites
