### ISSUE TITLE
[DynastyScans] Connector working, but not updating manga list

### ISSUE THREAD

**Issue by psduraes** [manga-download/hakuneko#4367]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When clicking to update manga list, the below error occurs. It's OK to download any chapter.

**Screenshots**
![image](https://user-images.githubusercontent.com/79729455/152625573-8ccc1faf-cab9-4060-b423-f12f265a740a.png)

**HakuNeko (please complete the following information):**
 - Version 6.17@fc96b6

**Comment by Darkmaster006** [comment]
This is still happening. You can't even get a list if you didn't have one from before.
