### ISSUE TITLE
Fetching volumes from mangareader.to [Feature]

### ISSUE THREAD

**Issue by Jaxk69** [manga-download/hakuneko#4368]
**Is your feature request related to a problem? Please describe.**
I want to fetch volumes from mangareader.to

**Describe the solution you'd like**
Modify .mjs file mangareader.to fetch volumes instead of chapters .

**Describe alternatives you've considered**
 1. Make it a different connector to only fetch volumes for hakuneko .
 2.  Add a checkbox option to switch between the two options (chapters and volumes) 

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7

**Additional context**
Site - https://mangareader.to/
Manga Page (It has a list for chapters as well as volumes) - https://mangareader.to/jujutsu-kaisen-168

**Comment by Jaxk69** [comment]
`import Connector from '../engine/Connector.mjs';
import Manga from '../engine/Manga.mjs';
 
export default class MangaReaderTo extends Connector {
 
    constructor() {
        super();
        super.id = 'mangareaderto';
        super.label = 'MangaReader.to';
        this.tags = ['manga', 'webtoon', 'japanese', 'korean', 'english', 'chinese'];
        this.url = 'https://mangareader.to';
        this.path = '/az-list?page=';
 
        this.querMangaTitleFromURI = 'div#ani_detail div.anisc-detail h2.manga-name';
        this.queryMangas = '#main-content div.manga-detail h3 a';
        this.queryChapters = 'div.chapters-list-ul ul li a';
        this.queryPages = 'div#wrapper';
    }
 
    async _getMangaFromURI(uri) {
        const request = new Request(new URL(uri), this.requestOptions);
        const data = await this.fetchDOM(request, this.queryMangaTitleFromURI);
 
        const id = uri.pathname;
        const title = data[0].textContent.trim();
 
        return new Manga(this, id, title);
    }
 
    async _getMangas() {
        const mangaList = [];
        for(let page = 1, run = true; run; page++) {
            const mangas = await this._getMangasFromPage(page);
            mangas.length ? mangaList.push(...mangas) : run = false;
        }
        return mangaList;
    }
 
    async _getMangasFromPage(page) {
        const uri = new URL(this.path + page, this.url);
        const request = new Request(uri, this.requestOptions);
        const data = await this.fetchDOM(request, this.queryMangas);
        return data.map(element => {
            return {
                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
                title: element.title.trim()
            };
        });
    }
 
    async _getChapters(manga) {
        let uri = new URL(manga.id, this.url);
        let request = new Request(uri, this.requestOptions);
        let data = await this.fetchDOM(request, this.queryChapters);
        return data.map(element => {
            const link = this.getRootRelativeOrAbsoluteLink(element, this.url);
            const title = element.title.replace(/:(.*)/gi, '');
            const lang = link.match(/(\/en\/)|(\/ja\/)|(\/ko\/)|(\/zh\/)/gi);
            const language = lang ? lang[0].replace(/\//gm, '').toUpperCase() : '';
            return {
                id: link,
                title: title.replace(manga.title, '').trim() + ` ${language}` || manga.title,
                language
            };
        });
    }
 
    async _getPages(chapter) {
        const uri = new URL(chapter.id, this.url);
        const request = new Request(uri, this.requestOptions);
        const data = await this.fetchDOM(request, this.queryPages);
        const readingId = data[0].dataset.readingId;
 
        return this._getImages(request, readingId);
    }
 
    async _getImages(requestChapter, readingId) {
        // https://mangareader.to/ajax/image/list/vol/26684?mode=vertical&quality=high&hozPageSize=1
        const uri = new URL(`ajax/image/list/chap/${readingId}`, this.url);
        uri.searchParams.set('quality', 'high');
        const request = new Request(uri, this.requestOptions);
        const data = await this.fetchJSON(request, 3);
 
        const dom = this.createDOM(data.html);
        const imagesArr = Array.from(dom.querySelectorAll('.iv-card'));
 
        // Example: https://c-1.mreadercdn.ru/_v2/1/0dcb8f9eaacfd940603bd75c7c152919c72e45517dcfb1087df215e3be94206cfdf45f64815888ea0749af4c0ae5636fabea0abab8c2e938ab3ad7367e9bfa52/9d/32/9d32bd84883afc41e54348e396c2f99a/9d32bd84883afc41e54348e396c2f99a_1200.jpeg?t=4b419e2c814268686ff05d2c25965be9&amp;ttl=1642926021
        const imageData = JSON.stringify(imagesArr.map(image => image.dataset.url));
 
        const type = Engine.Settings.recompressionFormat.value;
        const quality = parseFloat(Engine.Settings.recompressionQuality.value)/100;
        const script = `
            new Promise(async (resolve, reject) => {
                try {
                    let images = [];
                    const data = ${imageData};
                    for(const d of data) {
                        const canvas = await imgReverser(d);
                        const uri = canvas.toDataURL('${type}', ${quality})
                        images.push(uri);
                    }
                    resolve(images);
                } catch(error) {
                    reject(error);
                }
            });
        `;
 
        return Engine.Request.fetchUI(requestChapter, script, 60000, true);
    }
}`

**Comment by Jaxk69** [comment]
` import Connector from '../engine/Connector.mjs';
import Manga from '../engine/Manga.mjs';
 
export default class MangaReaderTo extends Connector {
 
    constructor() {
        super();
        super.id = 'mangareaderto';
        super.label = 'MangaReader.to';
        this.tags = ['manga', 'webtoon', 'japanese', 'korean', 'english', 'chinese'];
        this.url = 'https://mangareader.to';
        this.path = '/az-list?page=';
 
        this.querMangaTitleFromURI = 'div#ani_detail div.anisc-detail h2.manga-name';
        this.queryMangas = '#main-content div.manga-detail h3 a';
        this.queryChapters = 'div.chapters-list-ul ul li a';
        this.queryPages = 'div#wrapper';
    }
 
    async _getMangaFromURI(uri) {
        const request = new Request(new URL(uri), this.requestOptions);
        const data = await this.fetchDOM(request, this.queryMangaTitleFromURI);
 
        const id = uri.pathname;
        const title = data[0].textContent.trim();
 
        return new Manga(this, id, title);
    }
 
    async _getMangas() {
        const mangaList = [];
        for(let page = 1, run = true; run; page++) {
            const mangas = await this._getMangasFromPage(page);
            mangas.length ? mangaList.push(...mangas) : run = false;
        }
        return mangaList;
    }
 
    async _getMangasFromPage(page) {
        const uri = new URL(this.path + page, this.url);
        const request = new Request(uri, this.requestOptions);
        const data = await this.fetchDOM(request, this.queryMangas);
        return data.map(element => {
            return {
                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
                title: element.title.trim()
            };
        });
    }
 
    async _getChapters(manga) {
        let uri = new URL(manga.id, this.url);
        let request = new Request(uri, this.requestOptions);
        let data = await this.fetchDOM(request, this.queryChapters);
        return data.map(element => {
            const link = this.getRootRelativeOrAbsoluteLink(element, this.url);
            const title = element.title.replace(/:(.*)/gi, '');
            const lang = link.match(/(\/en\/)|(\/ja\/)|(\/ko\/)|(\/zh\/)/gi);
            const language = lang ? lang[0].replace(/\//gm, '').toUpperCase() : '';
            return {
                id: link,
                title: title.replace(manga.title, '').trim() + ` ${language}` || manga.title,
                language
            };
        });
    }
 
    async _getPages(chapter) {
        const uri = new URL(chapter.id, this.url);
        const request = new Request(uri, this.requestOptions);
        const data = await this.fetchDOM(request, this.queryPages);
        const readingId = data[0].dataset.readingId;
 
        return this._getImages(request, readingId);
    }
 
    async _getImages(requestChapter, readingId) {
        // https://mangareader.to/ajax/image/list/vol/26684?mode=vertical&quality=high&hozPageSize=1
        const uri = new URL(`ajax/image/list/chap/${readingId}`, this.url);
        uri.searchParams.set('quality', 'high');
        const request = new Request(uri, this.requestOptions);
        const data = await this.fetchJSON(request, 3);
 
        const dom = this.createDOM(data.html);
        const imagesArr = Array.from(dom.querySelectorAll('.iv-card'));
 
        // Example: https://c-1.mreadercdn.ru/_v2/1/0dcb8f9eaacfd940603bd75c7c152919c72e45517dcfb1087df215e3be94206cfdf45f64815888ea0749af4c0ae5636fabea0abab8c2e938ab3ad7367e9bfa52/9d/32/9d32bd84883afc41e54348e396c2f99a/9d32bd84883afc41e54348e396c2f99a_1200.jpeg?t=4b419e2c814268686ff05d2c25965be9&amp;ttl=1642926021
        const imageData = JSON.stringify(imagesArr.map(image => image.dataset.url));
 
        const type = Engine.Settings.recompressionFormat.value;
        const quality = parseFloat(Engine.Settings.recompressionQuality.value)/100;
        const script = `
            new Promise(async (resolve, reject) => {
                try {
                    let images = [];
                    const data = ${imageData};
                    for(const d of data) {
                        const canvas = await imgReverser(d);
                        const uri = canvas.toDataURL('${type}', ${quality})
                        images.push(uri);
                    }
                    resolve(images);
                } catch(error) {
                    reject(error);
                }
            });
        `;
 
        return Engine.Request.fetchUI(requestChapter, script, 60000, true);
    }
} `

**Comment by Jaxk69** [comment]
Paste Bin - https://pastebin.com/GaRyg28i
I have only changed the end-point and nothing else with the help of manh21

**Comment by CeRenard** [comment]
If this is working well and with it I could use Mangareader.to to download the volumes.
Would you mind briefly explain how or where should I put this to make it work.
Thanks.

**Comment by sud0x00** [comment]
The above pastebin has expired , kindly post it again

**Comment by Druzai** [comment]
Fetching list of volumes together with list of chapters was added in #4908
So you may close this issue
