### ISSUE TITLE
[https://webtoon-tr.com] Webtoon TR

### ISSUE THREAD

**Issue by northernblade** [manga-download/hakuneko#4369]
**Name of the website**
Webtoon TR

**Website urls (examples below)**
- Site: https://webtoon-tr.com
- Manga List: https://webtoon-tr.com/webtoon/
- Manga example: https://webtoon-tr.com/webtoon/legend-of-the-northern-blade1/
- Chapter online viewer example: https://webtoon-tr.com/webtoon/legend-of-the-northern-blade1/bolum-117/

**Languages**
Turkish

**Website relationship**
In Haku Neko, Webtoon TR already exists but it is not the same. Maybe this can help.

**Additional details**
None.

**Comment by Sterbenm** [comment]
It probably won't be added. because they are stealing content from other manga sites.

**Comment by Sterbenm** [comment]
that would be nice.
