### ISSUE TITLE
[https://mangagecesi.com] Connector not working

### ISSUE THREAD

**Issue by northernblade** [manga-download/hakuneko#4370]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
This website is not working since they upgrade the website. I can open the website within the Haku Neko but Haku Neko can't retrive the manga list. 

**To Reproduce**
1. Manga Gecesi
2. Legend of the northern blade (Kuzeyin Kılıcı)
3. Bölüm 91
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![image](https://user-images.githubusercontent.com/84595947/152658346-292bb5c1-dc39-439b-8fb3-fbb884266700.png)

**HakuNeko (please complete the following information):**
 - Version [6.1.7]

**Comment by ghost** [comment]
**Describe the bug**
The website is switched to the new scripts, they not use Madara. So WordPress Madara scripts not working.

**New website urls**
    Site: https://mangagecesi.com/
    Manga List: https://mangagecesi.com/cizgi-romanlar
    Manga example: https://mangagecesi.com/cizgi-romanlar/ofis-oykumuz
    Chapter online viewer example: https://mangagecesi.com/cizgi-romanlar/ofis-oykumuz/bolum-1

**Comment by Druzai** [comment]
I tried to fix connector, but the site can't load due to Cloudflare protection in Hakuneko, so without fixing Cloudflare issue, this connector won't work anyway.
If someone want to work on it further, here is my edited connector -[MangaGecesi.zip](https://github.com/manga-download/hakuneko/files/9339721/MangaGecesi.zip)

**Comment by MikeZeDev** [comment]
Old issue  ; https://github.com/manga-download/hakuneko/issues/4041
