### ISSUE TITLE
MMScans

### ISSUE THREAD

**Issue by kishan97** [manga-download/hakuneko#4371]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Website url for mmscans has been changed and hakuneko is routing it to .com.
New website is : https://mm-scans.org/

**To Reproduce**
**Screenshots**
Screenshot attached

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![Screenshot_1](https://user-images.githubusercontent.com/26489535/152673206-3ecba279-d813-46ef-876f-498b8d677732.jpg)

**Comment by Veysinator** [comment]
@Sheepux This seems to be fixed, can you close the issue
