### ISSUE TITLE
[Site Request] https://highschooldxd.online

### ISSUE THREAD

**Issue by FunkeJupiter007** [manga-download/hakuneko#4372]
**Name of the website**

highschooldxd.online

**Website urls (examples below)**

- Site: https://highschooldxd.online/
- Manga List: https://highschooldxd.online/manga/
- Chapter online viewer example: https://highschooldxd.online/manga/high-school-dxd-chapter-33/

**Languages**

English

**Comment by MikeZeDev** [comment]
Any point adding single manga website?
