### ISSUE TITLE
An external repository to download each platform's updated database

### ISSUE THREAD

**Issue by dothackjhe** [manga-download/hakuneko#4373]
I am requesting a repository of all of the supported platforms that can be used as a supplement to the app. I'm asking this specifically as, having used this amazing app some years before, downloading any particular platform's index list takes some time (e.g. Batoto), even with fast internet. So, what if there is a faster way about it, which I am thinking is feasible if done externally from the app, where we can just copy-and-paste said databases into the app's folder? I believe this will be a major boon to anyone who's seeking to get quick access to their favorite manga from their most preferred platform, especially from scratch.

**Comment by Sheepux** [comment]
This is how it worked in the past. Users were complaining tthat "title xyz is missing" causing too much questions and therefore the feature was removed.
the "database" file for each connecot is available here: https://hakuneko.download/docs/install/#user-data 

If they want quick access. Using the copy paste feature is faster.
