### ISSUE TITLE
[Site Request] Realm Scans

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4376]
**Name of the website**
Realm Scans

**Website urls**
- Site: https://realmscans.com/
- Manga List: https://realmscans.com/series/
- Manga example: https://realmscans.com/series/infinite-level-up-in-murim/
- Chapter online viewer example: https://realmscans.com/infinite-level-up-in-murim-chapter-82/

**Languages**
English

**Comment by manh21** [comment]
Duplicate of #4005
