### ISSUE TITLE
[Site Request] RESET SCANS

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4377]
Name of the website
RESET SCANS

Website urls (examples below)
- Site: https://reset-scans.com/
- Manga List: https://reset-scans.com/manga/
- Manga example: https://reset-scans.com/manga/book-eater/
- Chapter online viewer example: https://reset-scans.com/manga/book-eater/chapter-42/

Languages
English

**Comment by Veysinator** [comment]
@Sheepux It has been added
