### ISSUE TITLE
[DynastyScans] Failed to update manga list

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#4379]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When I try to update the manga list, this message appears:
Failed to update manga list for DynastyScans, cannot read property 'trim' of undefined

**To Reproduce**
1. Choose Dynasty-Scans as connector.
2. Update manga list.
3. Won't update.

**Expected behavior**
For the manga list to update itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/21136515/152883767-49ae12bf-bbd3-426b-93df-d678cc15b24c.png)

**Context (please complete the following information):**
 - OS: Linux Mint 20.2 Uma (happened on Windows 10 too)
 - HakuNeko rev. master@7ca17a

**Seemingly related issue:**
When using 'clipboard' for a manga in Dynasty-Scans, you get this:
![image](https://user-images.githubusercontent.com/21136515/152884264-82d7546d-0401-4efe-9a61-2c97b56412f5.png)
A 'random name'.
![image](https://user-images.githubusercontent.com/21136515/152884285-faf4bc54-069b-4359-96c1-66fb9a4c3c01.png)
This one's Swallow Tail: https://dynasty-scans.com/series/swallow_tail

**Comment by Sheepux** [comment]
duplicate #4367
