### ISSUE TITLE
[Toonily] Connector not working

### ISSUE THREAD

**Issue by Dark-Load** [manga-download/hakuneko#4382]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connector it not working and showing error
"Failed to update manga list for Toonily
Cannot read propery 'href' of undefined"

**To Reproduce**
1. Name of connector:Toonily
2. Name of manga : All
3. Name of chapter : All
4. Error
"Failed to update manga list for Toonily
Cannot read propery 'href' of undefined"

**Screenshots**
![Toonily Issue](https://user-images.githubusercontent.com/64626124/153101669-153e588b-5821-43b2-bfe7-8ccaf715227d.JPG)

**HakuNeko (please complete the following information):**
 - Version [master@7ca17a]

**Comment by MikeZeDev** [comment]
Works for me, update, preview and download . Nightly.

@Sheepux  pls? <3

**Comment by Sheepux** [comment]
works fine as well
