### ISSUE TITLE
[Site Request] Toptoon+

### ISSUE THREAD

**Issue by YokoKitsune** [manga-download/hakuneko#4384]
**Name of the website**
Toptoon+

**Website urls (examples below)**
- Site: https://toptoonplus.com/
- Manga https://toptoonplus.com/
- Manga example: https://toptoonplus.com/comic/100306
- Chapter online viewer example: https://toptoonplus.com/comic/100306/100235

**Languages**
English

**Website relationship*
English domain of https://toptoon.com/ and https://toptoon.net/

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3359
