### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by Cheng145** [manga-download/hakuneko#4386]
Verytoon

https://www.verytoon.com/
- Site: https://www.verytoon.com/
- Manga List: https://www.verytoon.com/genres
- Manga example: https://www.verytoon.com/serie/solo-leveling
- Chapter online viewer example: https://www.verytoon.com/serie/solo-leveling/episode/2644

French

the site uses a login system

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4051

@Sheepux  pls <3
