### ISSUE TITLE
[Site Request] mangahost4

### ISSUE THREAD

**Issue by Zenitchuu** [manga-download/hakuneko#4387]
**MangaHost**

- Site: https://mangahost4.com/
- Manga List: https://mangahost4.com/mangas
- Manga example: https://mangahost4.com/manga/spy-x-family-mh38173
- Chapter online viewer example: https://mangahost4.com/manga/spy-x-family-mh38173/1#1

**Languages**
Portuguese

**Comment by MikeZeDev** [comment]
Geoblocked

**Comment by MikeZeDev** [comment]
Dead
