### ISSUE TITLE
Remove menubar icon on macOS

### ISSUE THREAD

**Issue by pickx** [manga-download/hakuneko#439]
It's unnecessary (does not add any features except show/hide the window) and does not conform to UI guidelines. Thanks.

**Comment by 27136773** [comment]
Are you referring to the tray icon?
Please provide a screenshot.
Please provide a reference to the UI guidelines, so it can be adjusted according to them.

Probably related #412

**Comment by hypoflex** [comment]
he's indeed refering to the tray icon. which on OSX is massive and pretty useless
see video example:
https://i.gyazo.com/9c5ccd740f775d2fadd3bdc0ac86f39b.mp4

OSX 10.14.5

**Comment by 27136773** [comment]
As discussed on discord some contributes have ideas to put HakuNeko in the background (to tray) and still getting notifications. Furthermore there might be upcoming features, e.g. drop manga links on the tray icon.

I think it should be consistent on all operating systems.
The icon design may be fixed to integrate better into the UI, but we are still missing the link to the UI design guidelines that were mentioned by the opener.

**Comment by pickx** [comment]
> As discussed on discord some contributes have ideas to put HakuNeko in the background (to tray) and still getting notifications. Furthermore there might be upcoming features, e.g. drop manga links on the tray icon.
> 
> I think it should be consistent on all operating systems.
> The icon design may be fixed to integrate better into the UI, but we are still missing the link to the UI design guidelines that were mentioned by the opener.

These certainly are welcome features, except in OS X it is the Dock icon that is used for these features. The Dock icon functions exactly like the menubar icon in that it hides/shows the app, and stuff can be dragged into it. The Menubar icon in OS X (mostly) serves for apps that don't have Dock presence.

**Comment by 27136773** [comment]
As mentioned in #412 the tray icon has been disabled for now
