### ISSUE TITLE
[Leitor] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4391]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I'm able to see the tile by website but not via Hakuneko

**To Reproduce**
1. Leitor
2. Monster (https://leitor.net/manga/monster/1335)
3. Seach for "Monster" into hakuneko
4. No match found

**Screenshots**
![image](https://user-images.githubusercontent.com/76596575/153708609-45279879-bf84-4a18-a148-73d966601986.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Geoblocked

**Comment by MikeZeDev** [comment]
Gone, Same as mangalivre
