### ISSUE TITLE
[???] unspecified issue

### ISSUE THREAD

**Issue by ORPisNoob** [manga-download/hakuneko#4394]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**
I can see a big problem. Whenever I try to download animes, they don't download the video files. Instead they just download the photos taken from the video. Please help me what to do now. Try to add a feature where I can download mangas as well as anime episodes

**Comment by Sheepux** [comment]
How about you fill the form ? It's not here just for fun...

give the context/connector/title

**Comment by Sheepux** [comment]
no reponse -->  closing
