### ISSUE TITLE
[Manga PLUS by Shueisha] Connector not working (0/0 Chapters)

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#4396]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot update manga list. And all chapters of all series show 0/0.

**To Reproduce**
1. Manga PLUS by Shueisha
2. Red Hood (es) but none is working.
3. 0/0 Chapters show.
4. If you try to update the manga list, this appears:
![image](https://user-images.githubusercontent.com/21136515/153991982-8034eef1-1867-473d-bb62-07ad76d9e271.png)
5. Furthermore, if I try to use 'Clipboard', for example with https://mangaplus.shueisha.co.jp/titles/200088 it won't show anything either.

**Screenshots**
![image](https://user-images.githubusercontent.com/21136515/153991951-23d2a061-8972-4238-831b-bf673db48aaa.png)

**HakuNeko (please complete the following information):**
 - Version master@7ca17a

**Comment by MikeZeDev** [comment]
Works without problems. Nightly.
