### ISSUE TITLE
[Bug] Program not starting

### ISSUE THREAD

**Issue by theNEOkun** [manga-download/hakuneko#4397]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Program does not start, either through the launcher, nor through command-line, though through command-line I get the information:
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[34590:0215/063647.791516:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
/usr/bin/hakuneko-desktop: line 3: 34590 Trace/breakpoint trap   (core dumped) /usr/lib/hakuneko-desktop/hakuneko

**To Reproduce**
1. Open the application

**Expected behavior**
I expected the program to open, but it simply failed to load at all

**Screenshots**

**Context (please complete the following information):**
 - OS: EndevourOS
 - HakuNeko Version 6.17

**Additional context**

**Comment by Sheepux** [comment]
There are no releases of hakuneko for arch (you won't probably get support for that). Did you try to run it from code ?

**Comment by theNEOkun** [comment]
There was a version on the AUR that I used. I am currently trying to run it from code, and it at least is getting into a window, though it is taking an awful time Checking for an update.

**Comment by theNEOkun** [comment]
After some testing:
If locally building 6.1.7, the app just continues to say "Checking for an update" and does not seem to do anything else.
If locally building nightly, then the app gets past that, but only a white window shows up, with nothing showing for it.

Trying to install the .deb-package downloaded from the site gives the same error as getting the package from the AUR

**Comment by theNEOkun** [comment]
After some more testing, running the app with --no-sandbox makes it work again, for some reason.

**Comment by Sheepux** [comment]
that's probably not related to nosandbox.
The white screen happens when internet connectivity issues occurs (can be seen with the F12 network console) when hakuneko is trying to selfupdate.
I guess it just finally worked somehow. I'll close this issue as we don't have much official support for arch systems, but thanks for sharing the details.

**Comment by aradkdj** [comment]
I can reproduce it in Fedora 37 installed from the RPM. I get the same fontconfig error and it won't run unless I pass `--no-sandbox`.
