### ISSUE TITLE
[Feature] A badge for "New Chapter" on bookmarked mangas/manhwas

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#4399]
**Is your feature request related to a problem? Please describe.**
I have a big list of +100 mangas/manhwas bookmarked on the app. Therefore, I have to go through all of them daily to check for new chapters because I don't know when all of them are released. some scanlators have a release date and some don't and it's tiring because some mangas need to time to load the available chapters.

**Describe the solution you'd like**
A badge that shows up beside the name of the bookmarked manga that indicate that there's a new chapter for this manga. This badge can only be showed for recently uploaded chapters and not for un-downloaded old chapters.

**Describe alternatives you've considered**
-

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Additional context**
The below screenshot is an example of the feature (Photoshoped)
![Screenshot (49)](https://user-images.githubusercontent.com/95138799/154141456-e3fac871-7896-42bb-bed6-2298b801f2eb.jpg)

**Comment by Sheepux** [comment]
duplicate #653
