### ISSUE TITLE
Lezhin (English) and (Korean) not working

### ISSUE THREAD

**Issue by themysciraa** [manga-download/hakuneko#4400]
Lezhin (English) and (Korean) stopped working for both Free and Paid chapters. Was working fine couple days ago.

`Failed to load resource: the server responded with a status of 404 () www.lezhin.com/ko/404?path=&sw=all:1`

`TypeError: Cannot read property 'd2' of undefined
    at <anonymous>:10:67  `

I think Lezhin turned off `https://cdn.lezhin.com/v2/comics/*` I used to be able to manually see it. And I can't change to higher resolution `q=40` for the new rcdn server `https://rcdn.lezhin.com/v2/comics/*` because the access key wouldn't match.

I'm using the latest version of HakuNeko on MacOS

**Comment by Robonau** [comment]
#2950
