### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by rathneshh** [manga-download/hakuneko#4401]
**Name of the website**
kanojo-okarishimasu.com

**Website urls (examples below)**
- Site: https://kanojo-okarishimasu.com/
- Manga example: https://kanojo-okarishimasu.com/manga/rent-a-girlfriend-chapter-1/

**Languages**
List of languages supported by the website : English

**Comment by Robonau** [comment]
single manga sites wont be added by devs
though if you want to do it yourself and make a PR it will probably be merged

**Comment by Sheepux** [comment]
Closing. The title can be retrieve on many other connectors. No extra value +see  Robo's comment

**Comment by rathneshh** [comment]
> 

how can i add the site manually 
a brief tutorial would be of literally GREAT help 
thanks in advance

**Comment by Sheepux** [comment]
read the wiki. no it's not brief
