### ISSUE TITLE
[isekaiscan] Connector not working

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#4403]
Site; https://isekaiscan.com/

It keeps doing the same thing. There is probably a problem with admin_ajax.php.

**Screenshots**
![Ekran görüntüsü 2022-02-17 195847](https://user-images.githubusercontent.com/10929481/154532184-b1dafccb-08e5-4c5d-a62f-acc8d38f1399.png)

**Comment by Sheepux** [comment]
duplicate #4224
