### ISSUE TITLE
[Website Change] [Site Request] REALM SCANS

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4406]
**Name of the website**
Realm Scans

**Website urls (examples below)**
- Site: https://realmscans.com/
- Manga List: https://realmscans.com/series/
- Manga example: https://realmscans.com/series/eternal-club/
- Chapter online viewer example: https://realmscans.com/eternal-club-chapter-62/

**Languages**
ENGLISH

**Website relationship**
Previously known as Realmscans.xyz.

**Additional details**
Changed from realmscans.xyz to realmscans.com

**Comment by alen098** [comment]
It works.

**Comment by MohamedMaherAhmed** [comment]
Website relationship
Previously known as Realmscans.xyz.

Additional details
Changed from realmscans.xyz to realmscans.com

New Details
The current website URL is realmscans.xyz

Proof
![image](https://github.com/manga-download/hakuneko/assets/57438243/877b192d-5c7e-4694-8cbf-1ed2dcc96302)

so I will do the form again to make it work for realmscans.xyz

Name of the website
Realm Scans

Website URLs (examples below)

    Site: https://realmscans.xyz/
    Manga List: https://realmscans.xyz/series
    Manga example: https://realmscans.xyz/m050523/series/eternal-club
    Chapter online viewer example: https://realmscans.xyz/m050523/eternal-club-chapter-199

Languages
ENGLISH
