### ISSUE TITLE
[Site Request] Sushi scan

### ISSUE THREAD

**Issue by Glm34** [manga-download/hakuneko#4407]
**Name of the website**
Sushi scan

**Website urls (examples below)**
- Site: https://sushi-scan.su/
- Manga List: https://sushi-scan.su/manga/
- Manga example: https://sushi-scan.su/manga/attache-moi/
- Chapter online viewer example: https://sushi-scan.su/attache-moi-volume-1/#

**Languages**
French

**Comment by MikeZeDev** [comment]
Website is added and works . @Sheepux pls <3
