### ISSUE TITLE
The search box can be typed just once per run

### ISSUE THREAD

**Issue by thugdang** [manga-download/hakuneko#441]
i can't download any of my favorite manga by this app
i've gathered (all of) Vietnamese sources to see if any of these works. and suprise? only one source is working
AcademyVN (not working)
BlogTruyen (not working)
HamTruyen (not working)
MangaToon Vietnamese (works)
TruyenTranhTuan (not working)
VNSharing (not working)
NetTruyen (not working)
TruyenChon (not working)
and another problem is the search box can be typed just once per run. seems like it's frozen on the next time i type into. i have to start the app once again to use the search box
i deleted my user data and reinstall the app but nothing changed. please fix

**Comment by 27136773** [comment]
Which search box are you referring to?
Please open a ticket for each website that is not working and that you intend to use, this will save time to fix websites which are not going to be used at all.

**Comment by thugdang** [comment]
i meant the website search box
and i can't find any manga in Vietnamese sources. are those sources usable?

**Comment by 27136773** [comment]
Cannot be reproduced, the search box works for me as expected.
Please provide detailed steps how to reproduce the issue.

No those websites are probably incomplete and therefore not usable.
Please open **a new ticket for each broken website** that you wanna use.
One problem => one ticket, otherwise the discussion and development get way to confusing.
There is already a list of all incomplete websites, but as long as no user needs any of them, there is no reason to fix them.
See #124

**Comment by hypoflex** [comment]
# reproduce steps
- Search for the `BookLive` connector
- Refresh the manga list
- Error of failed to update will be shown.
- Go back to connectors

- Cant search for different connector
- Cant paste manga link
- Backspace does remove the `BookLive` connector search
- Click Bookmarks
- Not able to filter bookmarks

**Comment by 27136773** [comment]
Could be reproduced.
All input fields stop working after the error popup is closed.

**Comment by 27136773** [comment]
I can no longer reproduce this with the latest nightly builds.
Anyone still got this problem?

**Comment by hypoflex** [comment]
https://i.gyazo.com/80c02ebc6c4e197c19d90a5019a6f0a1.mp4

**Comment by 27136773** [comment]
Maybe this issue is operating system specific, will test other systems later.

**Comment by hypoflex** [comment]
indeed seems to be platform specific
https://i.gyazo.com/388736a1339e06d740b2d9126637eb65.mp4

**Comment by 27136773** [comment]
Related:
https://stackoverflow.com/questions/56805920/cant-edit-input-text-field-after-window-alert

**Comment by 27136773** [comment]
Unfortunately it seems all `alert()` and `confirm()` calls must be gradually removed...
