### ISSUE TITLE
[Site Request] ArcaneScans

### ISSUE THREAD

**Issue by NameLess0974** [manga-download/hakuneko#4410]
**Name of the website**
ArcaneScans

**Website urls (examples below)**
- Site: https://arcanescan.fr/
- Manga List: https://arcanescan.fr/manga/
- Manga example: https://arcanescan.fr/manga/i-am-the-sorcerer-king/
- Chapter online viewer example: https://arcanescan.fr/i-am-the-sorcerer-king-86/

**Languages**
French

**Comment by MikeZeDev** [comment]
Website doesnt answer.

**Comment by MikeZeDev** [comment]
Website is dead domain is available
