### ISSUE TITLE
[Site Request] Anubis Scans

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4413]
**Name of the website**
Anubis Scans

**Website urls (examples below)**
- Site: https://anubisscans.com
- Manga List: https://anubisscans.com/manga/
- Manga example: https://anubisscans.com/manga/onizuka-chan-and-sawarida-kun/
- Chapter online viewer example: https://anubisscans.com/manga/onizuka-chan-and-sawarida-kun/bolum-1/

**Languages**
Turkish

**Website relationship*

**Additional details**

**Comment by ghost** [comment]
As Anubis Scans management, we do not want our site to be added to Hakuneko. Last time you opened a topic for our site to be added to Tachiyomi's, but your request was not valid as I requested that it be removed from the authorities. The same request goes for Hakuneko.
We do not and will not want content from our own site to be embedded into another application without our consent.

Application you previously opened: [#10835](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10835)
Please do not apply on behalf of us, the Anubis Scans management team! We do not and will not want content from our site to be embedded in other application without our consent.

**Comment by ghost** [comment]
I reply @Kaeinzhu in our native language because it isn't necessarily in English.
* * *
Merhaba,

Sitenizin WP Madara tabanlı olduğunu görüyorum. Bu sayede biz arşivciler hiçbir çaba göstermeksizin [Manga Downloader](https://redsquirrel87.altervista.org/doku.php/manga-downloader) ile tüm mangaları indirebiliyor zaten. Sitenizin HakuNeko'ya eklenip eklenmemesi sizin için çok da önemli olmamalı. Eğer sitenizin HakuNeko'dan kaldırılmasını istiyorsanız, kaldırma talebinde bulunabilirsiniz ama zaten gördüğünüz gibi HakuNeko açık kaynak kodlu bir yazılım ve geliştirmelere de çok açık yani isteyen herkes kolaylık (hem yerel hem de herkese açık olarak) istediği siteyi ekleyebilir[*](https://github.com/manga-download/hakuneko/wiki/Developer-Website-Tutorial#31-website-scraper-plugin-module). Yani kaldırma talebinizin pek de bir anlamı yok. Gerçekten böyle şeylerin olmasını istemiyorsanız [Manga Gecesi](https://mangagecesi.com) gibi sitenizi kendiniz yazabilir ve indirmeleri elinizden geldiğince engellersiniz. Ama bu gibi eylemler kendisini saygılı okuyucu olarak görüp elinden geldiğince çeviri gruplarının sitelerine girip reklamlara tıklayan, okurken olmasa da okuduktan sonra teşekkür mesajı yazan kişileri kıracak, belki küstürecektir. Bunun yanında serilerinizi çalıp kendi sitelerinde yükleyenleri de engellemeyecektir.

Uzun süreler emek vererek çevirdiğiniz serilerin, izniniz olmadan, başka sitelere yüklenmesini hoş karşılamamanız hatta sinirlenmezin çok doğal olduğunu anlıyorum ama lütfen siz de biz çevrimdışı okuyan okuyucuları anlayın. Zaten dediğim gibi bu siteleri engellemek, en azından bu yolla, mümkün değil.

Bir diğer husus, lütfen çoktan kapanmış sorunlara(issue) bu şekilde yorum yazarak olağan akışı bozmayın.

İyi çalışmalar.
> Tüm çeviri gruplarının Tachiyomi ve HakuNeko nefretinin bitmesi, en azından azalması, temennisi ile...

**Comment by MrsLucifer** [comment]
@matmakif 
As I understand it, the website is down because of you. Please don't belittle anyone when opening a request.
they won't be scanning anymore because of you. (that's how I understood)

![image](https://user-images.githubusercontent.com/89423242/155985562-2a21d87b-331e-47e2-9eb6-d92fe8053bd8.png)
