### ISSUE TITLE
[Cutie Pie] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4415]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Site URL and Theme changed.

**Website urls (examples below)**
- Site: https://cutiepie.moe/
- Manga List: https://cutiepie.moe/seriler
- Manga example: https://cutiepie.moe/seri/moscow-s-dawn-16
- Chapter online viewer example: https://cutiepie.moe/seri/moscow-s-dawn-16/1-bolum

**Comment by MikeZeDev** [comment]
Url changed to cutiepie.moe, and is probably geoblocked (cloudflare)

**Comment by MikeZeDev** [comment]
redirect to manga_ay which is already supported
