### ISSUE TITLE
ReadRawManga changed Template

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#442]
> **From:** HakuNeko User

Mangaromance would be a great add. readrawmanga.com seems to has changed to mangaromance.eu. If you get the chance to add mangaromance then please also remove readrawmanga.

Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Mangaromance was added in #398 
ReadRawManga probably changed domain to https://readrawmanga.info (but logo is different)
readrawmanga.info also changed from SoraOne template to WordPressJarida template

**Comment by 27136773** [comment]
https://www.readrawmanga.com is back online and therefore will not be removed
