### ISSUE TITLE
[GManga] Connector not working

### ISSUE THREAD

**Issue by CherryPie94** [manga-download/hakuneko#4421]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When adding GManga and trying to get the manga list, I get:
"Failed to update manga list for GManga
Failed to receive content from "hhtps://gmanga.me/api/mangas/search" (status: 400)-"

**To Reproduce**
1. GManga
2. "Failed to update manga list for GManga
Failed to receive content from "hhtps://gmanga.me/api/mangas/search" (status: 400)-"

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4420
