### ISSUE TITLE
[Site Request] Muamh

### ISSUE THREAD

**Issue by Natoram** [manga-download/hakuneko#4426]
Site 
https://www.muamh.com/
 
It is a Chinese mobile website

**Comment by Sheepux** [comment]
Website doesn't work for me.
Also use the template when requesting a website:
https://github.com/manga-download/hakuneko/issues/new?assignees=&labels=Website+Suggestion&template=2-suggest-a-new-connector-website.md&title=%5BSite+Request%5D+thewebsitename
lots of question helps the contributors

**Comment by MikeZeDev** [comment]
Doesnt work for me too. Geoblocked?

**Comment by Sheepux** [comment]
no response from user, closing
