### ISSUE TITLE
[Site Request] Krhentai

### ISSUE THREAD

**Issue by Natoram** [manga-download/hakuneko#4427]
https://krhentai.com

It is a Chinese site please add it

**Comment by Sheepux** [comment]
Use the template when requesting a website:
https://github.com/manga-download/hakuneko/issues/new?assignees=&labels=Website+Suggestion&template=2-suggest-a-new-connector-website.md&title=%5BSite+Request%5D+thewebsitename
lots of question helps the contributors

**Comment by MikeZeDev** [comment]
error 403
