### ISSUE TITLE
[ReaperScan.FR] Connector not working

### ISSUE THREAD

**Issue by IKaynI** [manga-download/hakuneko#4431]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
We can't see the manga list, after the button is loaded nothing appears

**To Reproduce**
1. Name of connector / ReaperScan FR(https://reaperscans.fr/)
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 404 ()
GET https://reaperscans.fr/list/ 404
Failed to load bookmarks: Invalid bookmark list!
**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/96729560/155214706-3f5e6ad4-db56-4045-ac43-c3ba3deb0b5a.png)

**HakuNeko (please complete the following information):**
 -hakuneko-desktop_6.1.7_windows-portable_amd64

**Comment by Sheepux** [comment]
don't report again, it was fixed a few minutes ago. Use nightly
