### ISSUE TITLE
[Kissmanga.in] Application crash

### ISSUE THREAD

**Issue by Nitro963** [manga-download/hakuneko#4432]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When you try to update manga list the application crash while loading, and it seems like the same problem happens when you update chapter list of a bookmarked manga from the connector.

**To Reproduce**
1. KissManga.in
2. The application crash before any log captured in the console

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by Sheepux** [comment]
Unable to reproduce, connector is working fine. But  someone reported it on discord as well.

**Comment by Nitro963** [comment]
Neither do I, hopefully it were solved by recent commits.

**Comment by Sheepux** [comment]
Someone mentionned that using hakuneko nightly fixes the issue
