### ISSUE TITLE
[Lezhin US] Connector not working

### ISSUE THREAD

**Issue by chuntaazu** [manga-download/hakuneko#4433]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can't access chapters beyond episodes 1 and special episodes. Only the free ones are viewable, is there any way for me to use my purchased chapters in hakuneko?

**To Reproduce**
1. Lezhin US
2. Mad Place (if connector update is working)
3. All of them minus the free ones (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![image](https://user-images.githubusercontent.com/87785723/155283041-b8406037-1a55-427a-b3b2-abeb76b67490.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
did you fill your user credentials in the configuration menu ?
HN will not bypass paywalls

**Comment by chuntaazu** [comment]
yes, i did, it still doesn't work. it says "Cannot read property 'd2' of undefined"

**Comment by BereBereBeer** [comment]
same, from the console i get errors 403

**Comment by BereBereBeer** [comment]
i solved it by installing nightly

---

I want to add a little weird observation if it can help anybody, at times I had problems with free chapters too but apparently by unsubscribing from the series I could download them just fine

**Comment by Sheepux** [comment]
@chuntaazu can you try the nightly release ?

**Comment by ghost** [comment]
Temporary solution is to use HDoujin. 

This is not going to be fixed anytime soon. 🙄 

I've tried downloading on both Windows & Mac with both Hakuneko versions (stable & nightly) & I had opened the first initial "Duplicate" issue 12 days ago.

It used to work until today. First it was Hiatus chapters not working & now you can't download anything.

**Comment by BereBereBeer** [comment]
I'm back to say that it doesn't work at all, free chapters or otherwise, even with nightly. I'm logged in correctly on both the menu and browser, yesterday was fine, but now I again get this error message 

> Failed to load resource: the server responded with a status of 403

**Comment by MikeZeDev** [comment]
d2 value doesnt exist anymore. Even if we fix that, the promise doesnt resolve __LZ_DATA__.episode, but after debugging i see its still populated with episodes.. no clues why promise doesnt work.
