### ISSUE TITLE
[HentaiZone] Connector not working

### ISSUE THREAD

**Issue by xavimaa** [manga-download/hakuneko#4438]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
We can't see the manga list, after the button is loaded nothing appears

**To Reproduce**
1. Name of connector : HentaiZone
2. Name of manga : All
3. Name of chapter : All
4. Problem : Access to the site from the connector no longer works

**Screenshots**
![image](https://user-images.githubusercontent.com/82511742/155391653-8d559680-670d-4cd7-9ece-fb8a5520b07f.png)

**HakuNeko (please complete the following information):**
 - Version Nightly rev. master@c0cb8b

**Comment by Veysinator** [comment]
![image](https://user-images.githubusercontent.com/71281955/155399346-237ef747-91f7-409c-b9d5-2b01e3632329.png)
Seems like it's a server-side problem

**Comment by xavimaa** [comment]
![image](https://user-images.githubusercontent.com/82511742/155502720-756e37eb-d13c-42fc-9f0d-f3f727302adc.png)

The connection to the site works for me, obviously it's cloudflare that is the problem for hakuneko

**Comment by Sheepux** [comment]
cloudflare issue, cannot be fixed atm: see #2933
