### ISSUE TITLE
[Feature] Add CLI usage 

### ISSUE THREAD

**Issue by Q300Z** [manga-download/hakuneko#4439]
**English**
Allow the use of hakuneko in CLI for an automation of it.

Example of use:

Search:
haku search (-s) <target site>
--> Lists the manga on the site or returns the site

haku search (-s) <target site> <target manga>
--> Lists the chapters of the target manga or returns the manga

haku search (-s) <target manga>
--> Lists sites that include the manga

Update caches: 

haku update (-u) <target site>
--> Updates the list of manga on the target site

Chapter download:

haku download (-d) <target site> <target manga> <target chapter>/--all (-a) #To download all chapters <output download>
--> Chapter *Chapter number* of *manga* #You customize it as you want ;)

Here's overall how I see the thing, chances are I forgot some things but I wanted to express my idea.

Translated with www.DeepL.com/Translator (free version)

**French**
Permettre l'utilisation d'hakuneko en CLI pour une automatisation de celui-ci.

Exemple d'utilisation :

La recherche :
haku search (-s) <site cible>
--> Liste les mangas du site ou retourne le site

haku search (-s) <site cible> <manga cible>
--> Liste les chapitres du manga cible ou retourne le manga

haku search (-s) <manga cible>
--> Liste les sites comprennent le manga

Mise à jour des caches : 

haku update (-u) <site cible>
--> Mets à jour la liste des mangas du site cible

Téléchargement des chapitres :

haku download (-d) <site cible> <manga cible> <chapitre cible>/--all (-a) #Pour télécharger tout les chapitres <sortie téléchargement>
--> Chapitre *Numéro chap* de *manga* #Vous la personnalisez comme vous voulez ;)

Voila globalement comment je vois le truc, il y a des chances que j'ai oublié des choses mais je voulais exprimer mon idée.

**Comment by Sheepux** [comment]
Do not write in French, the community support is done in english.

Use the TEMPLATES available when creating an issue.
the main information "what's this request is supposed to solve?" is missing

CLI would be mostly used for automatic downloading and thus contradicts hakuneko's phylosophy.
https://github.com/manga-download/hakuneko/issues/4440
I'm not favorable.

**Comment by Sheepux** [comment]
Negative answer already covered by https://github.com/manga-download/hakuneko/issues/3628#issue-930735167
