### ISSUE TITLE
ref#398 readrawmanga.info

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#444]
> **From:** HakuNeko User

Got it! Thank you.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Duplicate #442
