### ISSUE TITLE
[Hiperdex] Connector not working

### ISSUE THREAD

**Issue by leopradipta** [manga-download/hakuneko#4447]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Seem Hiperdex using DDoS protections. so I no longer can download from here anymore.

**To Reproduce**
1. Hiperdex
2. Any title (if connector update is working)
3. always 0/0 (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
https://hiperdex.com/manga/circles-231121 -> error 503 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/100523264/155886591-3d40a52b-2ead-43a4-a7f1-70c6352415de.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
cloudflare issue, cannot be fixed atm: see #2933
