### ISSUE TITLE
[Bug] Hekuneko does not start

### ISSUE THREAD

**Issue by Q300Z** [manga-download/hakuneko#4449]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When I launch the application nothing happens, so I decided to launch it via cli, this returns me the screen below

**To Reproduce**
1. Open your terminal
2. Type in: " hakuneko-desktop " 
3. Watch the error

**Expected behavior**
Launching the hakuneko

**Screenshots**
![Capture d’écran_2022-02-28_20-59-13](https://user-images.githubusercontent.com/34000576/156050934-6c65ec30-fbba-474c-a184-177457a8bf35.png)

**Context (please complete the following information):**
 - OS: Manjaro Linux: 21.2.4, Kernel: Linux 5.15.25-1-MANJARO, XFCE: 4.16
 - HakuNeko Version : 6.1.7-1 AUR

**Additional context**
Nop

**Comment by Sheepux** [comment]
Arch is not a supported distribution by the repo maintainers.
Refer to other issues for possible solutions

**Comment by pr3martins** [comment]
I'm using Arch Linux as well and this comment helped me. It's unfortunate that hakuneko doesn't support Arch.

After some more testing, running the app with --no-sandbox makes it work again, for some reason.

_Originally posted by @theNEOkun in https://github.com/manga-download/hakuneko/issues/4397#issuecomment-1041172454_

**Comment by Sheepux** [comment]
People are free to contribute to the open source project to make a build for arch

**Comment by WittyNameHere** [comment]
I'm not on Arch and I believe I'm on a supported distro (Fedora 35) and the same error is happening when launching from terminal. Using --no-sandbox to workaround it for now. Using nightly build installed from RPM.

**Comment by Sheepux** [comment]
This issue will probably not be fixed soon as we're rewriting hakuneko frrom scratch (project haruneko https://github.com/manga-download/haruneko).
The sandbox seems to be an electron issue/feature on those systems as it requires more permissions.
We'll do haruneko distro testing later and might consider adding arch as more and more people have been asking for it.
