### ISSUE TITLE
[Manga Livre] Connector not working

### ISSUE THREAD

**Issue by Holisses-Sol** [manga-download/hakuneko#4450]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can't download/view the manga, but I can see the list of titles and their chapters.

**To Reproduce**
1. Name of connector: Manga Livre (mangalivre.net)
2. Name of manga (if connector update is working): Any title
3. Name of chapter (if manga update is working): Any chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12):
I will use as an example 1 title and 2 chapters

`Connector.mjs:460 GET https://mangalivre.net/leitor/pages/316481.json?key=y96Bf5inTfIolO9iVO29D84…22x6R91zaum0WeJrjX6ey7Hf7pDP93Y4S2YxFL66c6Td4b0Jdynux1Mdti9bb8TfC3ei9sP2e5 500`

`Connector.mjs:618 Error: Failed to receive content from "https://mangalivre.net/leitor/pages/316481.json?key=y96Bf5inTfIolO9iVO29D84…22x6R91zaum0WeJrjX6ey7Hf7pDP93Y4S2YxFL66c6Td4b0Jdynux1Mdti9bb8TfC3ei9sP2e5" (status: 500) - 
    at Connector.mjs:469
    at async MangaLivre._getImageLinks (Leitor.mjs:98) 
EventTarget {manga: EventTarget, id: "/ler/kikan-shita-yuusha-no-gojitsudan/online/316481/capitulo-13", title: "13 - Outra Visita Na Casa Do Herói [Late Scan]", file: {…}, language: undefined, …}`

**Screenshots**
If complex to describe, add screenshots to help explain your problem.:
print1
![Captura de tela 01](https://user-images.githubusercontent.com/8585141/156432393-1a9dc903-9d89-451f-a9a2-cc89f731a46c.png)

print2
![Captura de tela 02](https://user-images.githubusercontent.com/8585141/156432429-8a7f5a5d-98ca-4158-8d4e-8c5d15476a0b.png)

**HakuNeko (please complete the following information):**
 - Version: 2022 HakuNeko rev. 6.1.7@cf569b

**Comment by Sheepux** [comment]
duplicate #4061
