### ISSUE TITLE
[Site Request] Bomtoon

### ISSUE THREAD

**Issue by xingie** [manga-download/hakuneko#4451]
**Name of the website**
Bomtoon 

**Website urls (examples below)**
- Site: https://bomtoon.com/comic
- Manga List: https://www.bomtoon.com/main/comics
- Manga example: https://bomtoon.com/comic/ep_list/Prof_2ing
- Chapter online viewer example: https://bomtoon.com/comic/ep_view/Prof_2ing/pp0

**Languages**
Korean

**Website relationship*
If applicable describe the relation with any other website:  Raw Korean manhwas

**Additional details**
NA

**Comment by Sheepux** [comment]
duplicate #2701
