### ISSUE TITLE
[Remangas] Connector not working

### ISSUE THREAD

**Issue by Holisses-Sol** [manga-download/hakuneko#4454]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Does not sync manga list. Maybe it's because it changed the connector from _.top_ to _.net_

**To Reproduce**
1. Name of connector: **Remangas** (current website: **remangas.net**; Registered in the Connectors list: remangas.top)
2. Name of manga (if connector update is working): Any title
3. Name of chapter (if manga update is working): Any title
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12):

`Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\Emanno\Downloads\HakuNeko 6.1.7 64-Bit Portable\userdata\hakuneko.mangas.remangas'
(anonymous)	@	Connector.mjs:215
Promise.catch (async)		
_getUpdatedMangasFromFile	@	Connector.mjs:213
(anonymous)	@	Connector.mjs:150
Promise.then (async)		
getMangas	@	Connector.mjs:147
onSelectedConnectorChanged	@	mangas.html:215
runObserverEffect	@	property-effects.html:217
runEffectsForProperty	@	property-effects.html:162
runEffects	@	property-effects.html:128
_propertiesChanged	@	property-effects.html:1662
_flushProperties	@	properties-changed.html:341
_flushProperties	@	property-effects.html:1510
_invalidateProperties	@	property-effects.html:1482
runNotifyEffects	@	property-effects.html:261
_propertiesChanged	@	property-effects.html:1665
_flushProperties	@	properties-changed.html:341
_flushProperties	@	property-effects.html:1510
_invalidateProperties	@	property-effects.html:1482
set	@	property-effects.html:1817
selectConnector	@	connectors.html:303
handler	@	template-stamp.html:96
(anonymous)	@	templatize.html:149`

**Screenshots**
If complex to describe, add screenshots to help explain your problem:

![Captura de tela 2022-03-03 remangas](https://user-images.githubusercontent.com/8585141/156618517-fb04aa5f-fa8c-4d83-8527-de720a9caae7.png)

**HakuNeko (please complete the following information):**
 - Version: 2022 HakuNeko rev. 6.1.7@cf569b

**Comment by Sheepux** [comment]
Cloudflare issue cannot be fixed yet. See #2933
