### ISSUE TITLE
[Morpheus Manga] Website url changed

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4456]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site name and URL changed.

New name: Manga Bilgini

Website URLs (examples below):
Site: https://mangabilgini.com/
Manga List: https://mangabilgini.com/manga/
Manga example: https://mangabilgini.com/manga/the-emperor-is-a-woman/
Chapter online viewer example: https://mangabilgini.com/manga/the-emperor-is-a-woman/bolum-1/

**Comment by MikeZeDev** [comment]
Can you please change the title to [Morpheus Manga] Website url changed?
