### ISSUE TITLE
[Team X] Connector not working

### ISSUE THREAD

**Issue by kira-4** [manga-download/hakuneko#4457]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The website domain was changed so now we cant view anything

**To Reproduce**
1. Name of connector : Team X 
2. It shows this in the console GET https://www.teamxmanga.com/manga/page/1/ 404

**Website new urls**
- Site: https://teamx.fun/
- Manga List: https://teamx.fun/manga/
- Manga example: https://teamx.fun/manga/solo_max_level_newbie/
- Chapter online viewer example: https://teamx.fun/57bzax/

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by Sheepux** [comment]
Just change the domain in the settings. They change it so often that it's now an option. (but I'll PR to change the current default value)
