### ISSUE TITLE
Cross platform bookmarks / chaptermarkers

### ISSUE THREAD

**Issue by hypoflex** [manga-download/hakuneko#447]
would love to sync bookmarks and chapters between my laptop and desktop

one way of achieving this relative easily (since hakuneko cant provide a cloud save) being able to set the location of bookmarks and chaptermarkers file.

so this can be set to a external drive / cloud folder (dropbox/Gdrive) / NAS / SMB server

**Comment by 27136773** [comment]
Path of the [User Data](https://github.com/manga-download/hakuneko/wiki/User-Manual#22-user-data) directory can be changed via command line arguments (e.g. by creating a shortcut to HakuNeko's executable containing this argument)

`hakuneko.exe --user-directory='D:\...'`

**Comment by hypoflex** [comment]
but that would covert the hole directory, 
meaning all files would be synced. now from windows to windows that wouldn't be a problem
but windows to OSX (which i use) the settings file would not like that.

of course this could be manipulated by only syncing the bookmarks and chapter file.
but a dedicated check button + directory location in the settings would be more user friendly.

**Comment by hypoflex** [comment]
Feature was added, Bookmark file and Chaptermarker can be transfered to different folder for sync with a cloud option
