### ISSUE TITLE
[mangadex.org] Connector not working

### ISSUE THREAD

**Issue by sakunakai** [manga-download/hakuneko#4472]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The synchronization went for few minutes then there was a message that 'Hakuneko failed to fetch the manga"

**To Reproduce**
1. mangadex.org

4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
 "Failed to update manga list from mangadex
   Failed to fetch"

**Comment by MikeZeDev** [comment]
Well it works. @Sheepux pls
