### ISSUE TITLE
[Feature] to be enable to download webnovel

### ISSUE THREAD

**Issue by MAmrollahi** [manga-download/hakuneko#4477]
**Is your feature request related to a problem? Please describe.**
nope  I want to ask for a new feature to be able to download novels as well

**Describe the solution you'd like**
to be able to download web novels

**Describe alternatives you've considered**
https://github.com/Flameish/Novel-Grabber
something like this

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.17 nightly

**Additional context**
if you want to add this feature please check out  Novel-Grabber there is a good manual mode that is very helpful even if  Novel-Grabber doesn't support the sites you can do it on your own (but with little more work to do )

**Comment by Sheepux** [comment]
Hakuneko already support novels. Use the novel filter to find the connectors supported
