### ISSUE TITLE
[Feature] Login Support for Bilibili Comics

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4481]
**Is your feature request related to a problem? Please describe.**

- [Bilibili comics](https://www.bilibilicomics.com/) put up a paywall for comics. After paying coins or waiting for certain time the episodes will unlock. I tried to download the unlocked episodes with hakuneko and the downloaded folder shows only the first two images.

- Many comics on this site are inaccessible without an account.

**Describe the solution you'd like**

- Add login support for [bilibili comics](https://www.bilibilicomics.com/).

**Describe alternatives you've considered**

- I did not consider any other alternatives.

**Context (please complete the following information):**
 - HakuNeko Version 6.1.7

**Comment by Sheepux** [comment]
did you try the manual website interraction feature ?

**Comment by ghost** [comment]
![Untitled](https://user-images.githubusercontent.com/99159926/158300833-266ca447-aa6e-4e23-8022-da3a3f0a9233.png)
If this is the manual website interraction feature, then I have tried it and the downloaded folder shows only two images.

**Comment by Owyn** [comment]
>  I tried to download the unlocked episodes with hakuneko and the downloaded folder shows only the first two images.

It's actually 1st and the last image from the chapter

still waiting for login support btw, cuz else can't really download anything from BilibiliComics

and manually logging in doesn't change the situation anyhow, - still just 2 pages gets downloaded

**Comment by Darkmaster006** [comment]
This would be a very nice feature to have. Hopefully it can be implemented.
