### ISSUE TITLE
[Asura Scans] Connector not working

### ISSUE THREAD

**Issue by zrx47** [manga-download/hakuneko#4487]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the chapters are shown, but downloading fails 

**To Reproduce**
1. Asura Scans (Others work)
2. Update (or any other work)
3. Chapters 68, 69 (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
"There was no content found for "Chapter 68" Make sure it's accessible"

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Asura Scans](https://user-images.githubusercontent.com/77073976/158266307-2165926d-d666-45f5-9f8a-0aa6e094a783.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by tsentered** [comment]
Same problem. Website working but not connecting to Haku. Refresh doesn't work.

**Comment by kira-4** [comment]
It shows me a msgbox that says:
There was no content found for 'Chapter 26', make sure it is accessible (login, purchase, ...)!

**Comment by Odaxis** [comment]
Same issue here, Content not found in app, works fine online

**Comment by kira-4** [comment]
Sorry if this is obvious but I don't know this.
How long will it take until it's fixed in the app, or should I do something to make it work?

**Comment by Sheepux** [comment]
use hakuneko nightly
