### ISSUE TITLE
[Site Request] MangaToon

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4488]
Name of the website
h5.MangaToon

Website urls (examples below)

Site: https://h5.mangatoon.mobi/
Manga List: https://h5.mangatoon.mobi/
Manga example: https://h5.mangatoon.mobi/contents/detail/5
Chapter online viewer example: https://h5.mangatoon.mobi/cartoons/watch/5/108302

Languages
English

Website relationship
Alternative domain of [Manga Toon](https://mangatoon.mobi/).

**Comment by Sheepux** [comment]
DO NOT PING ME

**Comment by Sheepux** [comment]
duplicate #4378
