### ISSUE TITLE
Support for 1stkissmanga

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#449]
Would you please add support for 1stkissmanga.com?

**Comment by 27136773** [comment]
FirstKiss is already implemented

**Comment by siennk** [comment]
It has? I don’t see it on the list of sources.

**Comment by hypoflex** [comment]
![image](https://user-images.githubusercontent.com/36196198/65824007-011e9f80-e261-11e9-87b5-2747421e9b79.png)
https://github.com/manga-download/hakuneko/commit/4d0af6153b291747f862b9833b2ce09e6c91ed40 Added August 23rd

**Comment by siennk** [comment]
Huh that’s weird. It doesn’t show up in mine.

Does it make a difference if I am using the version I got from Sourceforge originally? Would I have to download the github version?

**Comment by hypoflex** [comment]
Yea, you're probably running a older version.
Your current version can be found top left of settings:
![image](https://user-images.githubusercontent.com/36196198/65824149-4e504080-e264-11e9-994d-3079a6d78993.png)

Here's a link to the latest github releases with installer. the app auto updates now so no need to worry about future updates
https://github.com/manga-download/hakuneko/releases/tag/v5.0.8

**Comment by siennk** [comment]
Thank you so much!
