### ISSUE TITLE
[Mangahost] Não consigo fazer download dos capitulos

### ISSUE THREAD

**Issue by Delcio235** [manga-download/hakuneko#4491]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Whenever I try to download a chapter from mangahost it fails but the manga are listed without problem and on other sites in other languages it works

**To Reproduce**
1. Mangahost

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 8.3.4]
 - when down from another connector works
![Screenshot_26](https://user-images.githubusercontent.com/98470492/158357874-ae618757-4335-44f2-a24f-f8b5b8656d5a.png)
- by the amount of sleeves available on mangahost and indispensable
![Screenshot_27](https://user-images.githubusercontent.com/98470492/158358054-77587923-b49a-405a-be73-462959b17bbb.png)
![Screenshot_28](https://user-images.githubusercontent.com/98470492/158359039-5c579169-deed-4295-9495-604d338a63d0.png)

**Comment by Sheepux** [comment]
Use hakuneko nightly, it was fixed last week (they've implemented a throttling protection)
