### ISSUE TITLE
[manga-raw.club] Connector not working

### ISSUE THREAD

**Issue by lit377** [manga-download/hakuneko#4492]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by lit377** [comment]
i have read the guide 

the websites are working fine on my browser

mangalist is not updating, showing this error, Connector.mjs:579 TypeError: Cannot read property 'textContent' of undefined
    at MangaRaw._getMangas (MangaRaw.mjs:26)
    at async MangaRaw._getMangaList (Connector.mjs:576) MangaRaw
    
    
  and with another connector, the mangalist is just not loading, the update button spins for a few seconds but it won't load the list and not showing any pop up error box.
  
  i have attached a screen shot for better understanding of the issue 
  
    
![Screenshot 2022-03-15 211032](https://user-images.githubusercontent.com/101654265/158417134-34347dbd-1439-42c4-9ac4-0e4ec0683349.png)

**Comment by Sheepux** [comment]
duplicate #4489
