### ISSUE TITLE
[manga-1001] domain change

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#4494]
**Name of the website**
manga-1001

**Website urls (examples below)**
- Site:  https://doki1001.com/

- Manga List: https://doki1001.com/manga-genre/%e3%82%a2%e3%82%af%e3%82%b7%e3%83%a7%e3%83%b3/3/

- Manga example: https://doki1001.com/manga/367426247747/

- Chapter online viewer example: https://doki1001.com/manga/367426247747/%e7%ac%ac292%e8%a9%b1/

**Languages**
Japanese

**Website relationship*
It is most likely an alternative or copy of manga1001.com, but it looks like manga1001 is offline.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Juboha** [comment]
> but it looks like manga1001 is offline.

I believe manga1001.com is now manga-1001.com.
However, the connector for manga1001 does not appear to work anymore.

**Comment by PerseusRex** [comment]
Oh, I didn't know that. I'll edit it then

**Comment by Juboha** [comment]
And now the website is called doki1001.com.

This site seems to works by extending the template connector WordPressMandara.mjs.

**Comment by PerseusRex** [comment]
> And now the website is called doki1001.com.
> 
> This site seems to works by extending the template connector WordPressMandara.mjs.

I tried messing around with it, but I don't know what I'm doing. How do you extend the template connector?

**Comment by Juboha** [comment]
[doki1001.zip](https://github.com/manga-download/hakuneko/files/8659037/doki1001.zip)

Here's one I prepared earlier. Just unzip it to the following folder:
`%appdata%/hakuneko-desktop/hakuneko.plugins/`

When choosing Connectors, choose "Doki1001" instead of "Manga 1001".
I have not fully tested it yet, so please take it as is.

**Comment by MikeZeDev** [comment]
Parking page, dead website
