### ISSUE TITLE
Impossible to connect to mangadex (add option to use a different DNS)

### ISSUE THREAD

**Issue by Wip-Sama** [manga-download/hakuneko#4495]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hakuneko can't connect to mangadex, to connect you need to change DNS from the default to 8.8.8.8 (google public dns or another)

**To Reproduce**
This is quite hard...
1. Being in Italy
2. Searching mangadex in hakuneko

**Screenshots**
[Error](https://imgur.com/3jscybI)

**HakuNeko:**
 - Version 6.17

**Comment by Sheepux** [comment]
Configuring your system dns resolver is not related to hakuneko
