### ISSUE TITLE
Novel japanread

### ISSUE THREAD

**Issue by Sulphura** [manga-download/hakuneko#4496]
Hello, I see more and more novel posted on japanread (translation of Asian novel). But hakuneko software doesn't allow to get the text. Instead it creates a .bin file, openable with a notepad. In this file there is htlm code but not the text of the novels. Do you plan to make an update to be able to download these texts? Or is this not an option at all?
I have tried novel grabber but it does not work. I have heard about filter but I can't find more information. Could you help me?
Thanks

**Comment by TristanWasTaken** [comment]
**Context**
[Japanread](https://japanread.cc) is now [BentoManga](https://bentomanga.com)

**Comment by metoobz** [comment]
![hakunekoissue2BINfile](https://github.com/manga-download/hakuneko/assets/154104140/2be0b159-790f-408d-b574-7870436c41cb)
here's a pic incase that helps
