### ISSUE TITLE
[Site Request] mangatepesi

### ISSUE THREAD

**Issue by ardainanir** [manga-download/hakuneko#4497]
Manga Tepesi

- Site: https://mangatepesi.com
- Manga List: https://mangatepesi.com/mangalistesi
- Manga example: https://mangatepesi.com/manga/starting-from-today-i-ll-work-as-a-city-lord/7
- Chapter online viewer example: https://mangatepesi.com/manga/starting-from-today-i-ll-work-as-a-city-lord/263-bolum/1928

Turkish

Reader

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/1725
