### ISSUE TITLE
[Feature] be able to save and view favorite websites

### ISSUE THREAD

**Issue by tripnikk** [manga-download/hakuneko#4500]
Hello, 
I'd love to be able to save a list of favorite or commonly used websites for quick and easy access. This would either help with remembering that I want to look through more of their selection in the future, or even just make it faster to navigate to a commonly used site instead of having to click on the website button, search for the site, etc. 
Interface-wise it would be great to either click a star next to the website name to save/unsave it to favorites, or perhaps have a contextual menu that pops up when you right click it.

**Comment by Sheepux** [comment]
duplicate #535

Also being implemented in haruneko as part of the experimental zone
https://github.com/manga-download/haruneko/issues/40
![harufavs](https://user-images.githubusercontent.com/19878135/159078285-eb274f88-237e-4778-b900-40fcdd654a21.png)
