### ISSUE TITLE
[manga1001] Connector not working

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#4506]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
I opened up a new connector issue previously, but was told that the domain of the website changed from manga1001.com to manga-1001.com

**To Reproduce**
1. manga1001
2. domain changed to manga-1001.com

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Juboha** [comment]
Here's one I knocked up - "Manga-1001 TempFix".
[Manga1001Temp.zip](https://github.com/manga-download/hakuneko/files/8333129/Manga1001Temp.zip)
There is 4400 mangas on the site, so listing all of them for the first time may take up to 10 minutes to load.

Unzip attachment to the plugin folder (on Windows it is %USERPROFILE%\AppData\Roaming\hakuneko-desktop\hakuneko.plugins). This folder doesn't exist by default so you may have to create it.

Note that the site manga-1001.com has issues where:
- Title of manga and the actual manga pages under it does not match  
- Older chapters are listed, but does not contain the correct manga pages.

And also attached is the connector for website manga1000.top. The site is called "MangaBank", and so I used this name in the website list within Hakuneko.
[MangaBank.zip](https://github.com/manga-download/hakuneko/files/8333128/MangaBank.zip)

***Neither have been fully tested so please expect some errors.***

**Comment by Sheepux** [comment]
duplicate #4494
