### ISSUE TITLE
[immortalupdates] Connector not working

### ISSUE THREAD

**Issue by inheritno** [manga-download/hakuneko#4509]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

https://github.com/dazedcat19/FMD2/issues/942#issue-1176620449

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
https://immortalupdates.com/manga/empresss-harem/chapter-282/ url changed. Tried downloading in HN, nothing is scrambled. Fixed i guess, at least on nightly. @Sheepux pls?

**Comment by Sheepux** [comment]
works fine on nightly too
