### ISSUE TITLE
[ReadComicOnline.li] Connector not working

### ISSUE THREAD

**Issue by m-darweesh** [manga-download/hakuneko#4510]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connecter was working fine for months, now chapters don't show (0/0) and list would not update (Error 503 in console)

1. Name of connector ReadComicOnline.li

![image](https://user-images.githubusercontent.com/102323776/159993837-c8debca1-db6b-4d86-8944-39b8fd7a8e04.png)

Hakuneko Version 6.1.7

**Comment by Blipbliptoryah** [comment]
Hi, I've got this exact issue! I feel that the cloudflare on this page is getting a bit nasty as it was down on tachiyomi as well

**Comment by MikeZeDev** [comment]
Can confirm the bug.
