### ISSUE TITLE
[readkomik.com] Connector not working

### ISSUE THREAD

**Issue by nirolfa** [manga-download/hakuneko#4511]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connector.mjs:434 GET https://readkomik.com  error 503
	fetchDOM	@	Connector.mjs:434
_getChapters	@	WordPressMangastream.mjs:36
_getChapterList	@	Connector.mjs:595

**HakuNeko (please complete the following information):**
 - Version [master 1c6d00]

**Comment by MikeZeDev** [comment]
Cant reproduce. Works as intended. Nightly. @Sheepux maybe?

**Comment by Sheepux** [comment]
works fine too on nightly
