### ISSUE TITLE
[japanread.cc/] Connector not working  the name change to .bentomanga.com

### ISSUE THREAD

**Issue by gouki44** [manga-download/hakuneko#4513]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
It's not really a bug, it's just the site that changed its name before it was japanread now it's https://www.bentomanga.com/.

Site: https://bentomanga.com/
Manga List: https://bentomanga.com/manga_list
Manga example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead
Chapter online viewer example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead/chapter/30
Novel example: https://bentomanga.com/manga/who-made-me-a-princess-1
Chapter Novel online viewer example: https://bentomanga.com/manga/who-made-me-a-princess-1/chapter/01

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by courli79** [comment]
**Website urls (examples below)**
- Site: https://bentomanga.com/
- Manga List: https://bentomanga.com/manga_list
- Manga example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead
- Chapter online viewer example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead/chapter/30
- Novel example: https://bentomanga.com/manga/who-made-me-a-princess-1
- Chapter Novel online viewer example: https://bentomanga.com/manga/who-made-me-a-princess-1/chapter/01

**Comment by gouki44** [comment]
> **Website urls (examples below)**
> 
> * Site: https://bentomanga.com/
> * Manga List: https://bentomanga.com/manga_list
> * Manga example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead
> * Chapter online viewer example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead/chapter/30
> * Novel example: https://bentomanga.com/manga/who-made-me-a-princess-1
> * Chapter Novel online viewer example: https://bentomanga.com/manga/who-made-me-a-princess-1/chapter/01

Merci Courli79, j'ai édite le poste avec ce que tu as fais proprement! Bien vu.

**Comment by hisoka-07** [comment]
Site: https://bentomanga.com/
Manga List: https://bentomanga.com/manga_list
Manga example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead
Chapter online viewer example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead/chapter/30
Novel example: https://bentomanga.com/manga/who-made-me-a-princess-1
Chapter Novel online viewer example: https://bentomanga.com/manga/who-made-me-a-princess-1/chapter/01

**Comment by courli79** [comment]
Hello, I have prepared a code for BentoManga which I am attaching. It works but we only see the first chapters of the manga because I miss the code to unlock the 'load more' button for the chapters and the Manga List. If anyone can help me with this code. thank you

![image](https://user-images.githubusercontent.com/82915245/161388195-19ad6660-a1bd-4030-a1a9-def1f3b1e45f.png)
![image](https://user-images.githubusercontent.com/82915245/161388908-a67db676-182c-4290-a50a-79a6de9df2a2.png)


[BentoManga.zip](https://github.com/manga-download/hakuneko/files/8402747/BentoManga.zip)

**Comment by gouki44** [comment]
Merci Courli79.

**Comment by xavimaa** [comment]
Hello,

The japanread connector is not working anymore.
The manga list update is working correctly.
The manga retrieval does not work, there seems to be a 403 error.

Version : master@1aa377
![image](https://user-images.githubusercontent.com/82511742/173200259-0bb31e31-e01d-4829-833e-90bcee204475.png)

**Comment by MikeZeDev** [comment]
Its Cloudflare. Not sure it can be fixed right now.

https://i.imgur.com/YhaSJvn.png

#4776

**Comment by MikeZeDev** [comment]
There is still a Japanread.cc website. Whats going on ?

**Comment by onelots** [comment]
many things to say.

First, Japanread became definitely bentomanga.com, their website japanread.cc will be shut down soon; 
Then, chapters are available on boths websites because their db is shared, which makes that mangas are available at the same time on both the websites.
So, forget Japscan, it's now bentomanga.

**Comment by Ever4engel** [comment]
japscan isn't dead.

**Comment by MikeZeDev** [comment]
There is a classical Cloudflare check for accessing to any manga, but even on my browser i got "Bot Detection error" and if i reload the page it goes 404 :D.

https://cdn.discordapp.com/attachments/581629183159959584/1030063869026119730/unknown.png

(My FF browser is hardened tho, a naked firefox works fine)

If you insist they force you to fill a Hcaptcha.

And  i am banned https://cdn.discordapp.com/attachments/581629183159959584/1030069207892775003/unknown.png
