### ISSUE TITLE
https://www.bentomanga.com/

### ISSUE THREAD

**Issue by hisoka-07** [manga-download/hakuneko#4514]

**Comment by gouki44** [comment]
https://github.com/manga-download/hakuneko/issues/4513  Viens voté chez moi , comme ca on s entraide et avec de la chance ca montera plus vite!  On a le même désire ;)

**Comment by bensoc1** [comment]
this website was known before as https://japanread.cc but they switched today their domain name to https://bentomanga.com i'd +1 on this please add it to the supported websites

**Comment by gouki44** [comment]
Site: https://bentomanga.com/
Manga List: https://bentomanga.com/manga_list
Manga example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead
Chapter online viewer example: https://bentomanga.com/manga/i-didnt-mean-to-seduce-the-male-lead/chapter/30
Novel example: https://bentomanga.com/manga/who-made-me-a-princess-1
Chapter Novel online viewer example: https://bentomanga.com/manga/who-made-me-a-princess-1/chapter/01

**Comment by Sheepux** [comment]
duplicate #4513
