### ISSUE TITLE
[mangadex] connector not working on a reload loop

### ISSUE THREAD

**Issue by Deltapl7s** [manga-download/hakuneko#4515]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
Yes

**Describe the bug**
The mangadex reload is on Infinite loop manga names not showing even after 10 to 20 min wait

**To Reproduce**
1. Name of connector mangadex 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Errr .... The mangadex refresh is usually longer than that.
