### ISSUE TITLE
[Asura scan] Connector not working in stable version

### ISSUE THREAD

**Issue by Deltapl7s** [manga-download/hakuneko#4516]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
Yes
**Describe the bug**
When I click reload, reload stops and at left corner manga 0/ this shows up

**To Reproduce**
1. Name of connector asura scans
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
use nightly. stable will be released soon

**Comment by Deltapl7s** [comment]
> 

Thanks and mangadex is still loading around 20 min still not got manga list
