### ISSUE TITLE
[Bug]https://sushi-scan.su/

### ISSUE THREAD

**Issue by loopingvvv** [manga-download/hakuneko#4517]
Hello,
For a few days now, a problem persists on the Sushi Scan website.
It is now impossible to download or even watch the chapters or tome.
The app only shows me the front cover.

Thank you for your attention to my message.

**Comment by Sheepux** [comment]
Fill the template when reporting a broken connector
https://github.com/manga-download/hakuneko/issues/new?assignees=&labels=Website+Change&template=1-connector-website-not-working.md&title=%5BNameOfConnector%5D+Connector+not+working
