### ISSUE TITLE
[Bug] manual website sign in error

### ISSUE THREAD

**Issue by kimhomo** [manga-download/hakuneko#4518]
Hi! I am unable to login to toptoon with the manual website interaction using a social media sign in (google). 

 [This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.]

OS: [Windows10]
HakuNeko Version 6.17

**Comment by MikeZeDev** [comment]
Sadly is because the "social media website auth mechanism" does not recognize hakuneko as a recent browser and it cant be fixed. Use a normal account
