### ISSUE TITLE
[Sushi-scan] Connector not working

### ISSUE THREAD

**Issue by loopingvvv** [manga-download/hakuneko#4519]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It is now impossible to download or even watch the chapters or tome.
The app only shows me the front cover.

**To Reproduce**
1. sushi-scan

**Screenshots**
Example
2. [](https://sushi-scan.su/)
![bug02](https://user-images.githubusercontent.com/102437488/160280029-c783bd3e-29ca-4947-85af-fca154d62ddc.PNG)

![bug](https://user-images.githubusercontent.com/102437488/160279919-3ba92398-27f5-4b23-94bc-c49b53d882be.PNG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by hisoka-07** [comment]
we hope they can fix the problem ASAP

**Comment by Shirozaond** [comment]
This bug has occurred once again
