### ISSUE TITLE
[Bug] [E-hentai.org] PROTOCOL_ERROR

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#4523]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**

The files are only partially or erroneously downloaded 

**To Reproduce**

**Expected behavior**

**Screenshots**

![Sin título](https://user-images.githubusercontent.com/53885246/160514460-654ab719-37bc-410a-96cc-d117c04f19d2.jpg)
 25mb archive.

![Sin título](https://user-images.githubusercontent.com/53885246/160514566-b670ffae-8533-49a4-8408-e7d3f3025958.jpg)

1.816kb Download.

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by RandomGOTI** [comment]
I tried it today and it downloaded a cbz with .bin files , the bin files where html login page

pasting the url in hakuneko browser can view gallery just fine without having to login

I am using 
Windows 7 Ultimate SP1 x64
hakuneko [nightly](https://github.com/manga-download/hakuneko/releases/tag/nightly-20200705.1)

**Comment by MikeZeDev** [comment]
The problem arise when we try to download the "fullimage" using the php link. We download instead the login page (as bin file).
Adding a fallback to the displayed image doesnt work, we get PROTOCOL ERROR

![image](https://user-images.githubusercontent.com/10671518/204834000-e0bb4519-ed99-4ba2-b75f-f2778c68b39a.png)

The link is weird but still...
