### ISSUE TITLE
access to https://significantoperativeclearance.com ?

### ISSUE THREAD

**Issue by camisole26** [manga-download/hakuneko#4525]
Hello,

Bitdefender Total Security 26.0.14.62 tells me that Hakuneko is trying to access the page https://significantoperativeclearance.com.
Message in french sorry:
![image](https://user-images.githubusercontent.com/66274638/160684947-0b56f3bc-56ee-4cb7-9792-70f314ce7b54.png)

Is this normal?

Best regards 
Jérémie

**Comment by gouki44** [comment]
Tu as dl ou hakuneko ?

**Comment by camisole26** [comment]
Version stable ici : https://github.com/manga-download/hakuneko#download

Cordialement
Jérémie

**Comment by Sheepux** [comment]
was it when using a connector ? it could be that specific website doing so

**Comment by camisole26** [comment]
I have to apologize.
I forgot I was using the portable version.
I installed the classic version and I always launched the portable version via my shortcut.
So it was the presence of the classic version that was to cause conflicts with the portable version.

Best regards
Jérémie

**Comment by Sheepux** [comment]
on peut fermer du coup ?

**Comment by camisole26** [comment]
Bien entendu, encore désolé.
