### ISSUE TITLE
[Leitor.net] Connector not working

### ISSUE THREAD

**Issue by Alucardpsa12** [manga-download/hakuneko#4526]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
 
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
 
Yes
**Describe the bug**
I can't download/view the manga, but I can see the list of titles and their chapters.

**To Reproduce**
1. Name of connector ( Leitor.net )
2. Name of manga (if connector update is working) any title
3. Name of chapter (if manga update is working) any chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Connector.mjs:618 TypeError: Cannot read property 'src' of undefined
    at Leitor._getPages (Leitor.mjs:87)
    at async Leitor._getPageList (Connector.mjs:615) 
EventTarget {manga: EventTarget, id: "/manga/abnormal-hunting/242368/0", title: "0 [Vapo Scan]", file: {…}, language: undefined, …}
Connector.mjs:618 TypeError: Cannot read property 'src' of undefined
    at Leitor._getPages (Leitor.mjs:87)
    at async Leitor._getPageList (Connector.mjs:615) 
EventTarget {manga: EventTarget, id: "/manga/abnormal-hunting/242658/1", title: "1 [Vapo Scan]", file: {…}, language: undefined, …}
﻿
​
﻿
​
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![1](https://user-images.githubusercontent.com/102625840/160715146-43201ae3-2237-401f-abfb-949b11237c99.png)
![2](https://user-images.githubusercontent.com/102625840/160715194-472058de-70fb-4454-bc1b-1d4d998a506c.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4391
