### ISSUE TITLE
[Site Request] readcomiconline.li

### ISSUE THREAD

**Issue by Brem-Stoker** [manga-download/hakuneko#4529]
**Name of the website**
readcomiconline.li

**Website urls (examples below)**
- Site: https://readcomiconline.li/
- Manga List: https://readcomiconline.li/ComicList
- Manga example: https://readcomiconline.li/Comic/Out-of-Control-Starring-Superman
- Chapter online viewer example: https://readcomiconline.li/Comic/Out-of-Control-Starring-Superman/Full?id=174437&readType=1

**Languages**
English

**Website relationship*
-

**Additional details**
-

**Comment by MikeZeDev** [comment]
Website is supported. @Sheepux
