### ISSUE TITLE
[Bilibili] now downloads files at a HUGE size (before, 20-50 MB, now 100-200 MB)

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#4530]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Basically, before, with Bilibili, you'd download a manhua and it'd be around 20 MB, now the same file, and subsequent chapters, are about 100 or even 200 MB in size! This is... a very big file. I thought it could be the quality, but I've compared a chapter I had with a new one I downloaded, and the pictures are the same.

**To Reproduce**
1. Go to Bilibili connector.
2. Download a chapter. Examples of the ones that I've had it happen to are: https://www.bilibilicomics.com/detail/mc16 and https://www.bilibilicomics.com/detail/mc124
3. Size is just... huge.

**Expected behavior**
For chapters to be smaller, even more when the quality isn't changing.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/21136515/160974792-d95d45b3-0239-4ff4-9ebb-b8abb77f01d4.png)

**Context (please complete the following information):**
 - OS: Windows 8, Windows 10, Linux.
 - HakuNeko Version 1c6d00

**Additional context**

**Comment by Ever4engel** [comment]
![image](https://user-images.githubusercontent.com/47645041/161379355-f6a46502-b581-4992-851d-983f3a7c3612.png)
Change PNG to jpg or webp (to your convenience)

it's not a bug it's a **feature** . joke aside...

`For chapters to be smaller, even more when the quality isn't changing.`

Nah there is a difference in quality between served files by blibli (png is the highest quality, imo it's the best choice for scanlation, the website serves also jpg and webp files with less space).

**Comment by Darkmaster006** [comment]
> ![image](https://user-images.githubusercontent.com/47645041/161379355-f6a46502-b581-4992-851d-983f3a7c3612.png) Change PNG to jpg or webp (to your convenience)
> 
> it's not a bug it's a **feature** . joke aside...
> 
> `For chapters to be smaller, even more when the quality isn't changing.`
> 
> Nah there is a difference in quality between served files by blibli (png is the highest quality, imo it's the best choice for scanlation, the website serves also jpg and webp files with less space).

Thank you. Has it been changed by default? Or did Bilibili just now start serving PNGs? Either way, I don't think the PNG's and the JPG's are of different quality, compare:
5 MB PNG file: https://i.imgur.com/2yTQkc4.png
500 KB JPG file: https://i.imgur.com/8V3Eru1.jpg
Manga is 'The Incapable Married Princess', but others I've checked are the same.
So there might be something weird going on.

**Comment by Ever4engel** [comment]
> > ![image](https://user-images.githubusercontent.com/47645041/161379355-f6a46502-b581-4992-851d-983f3a7c3612.png) Change PNG to jpg or webp (to your convenience)
> > it's not a bug it's a **feature** . joke aside...
> > `For chapters to be smaller, even more when the quality isn't changing.`
> > Nah there is a difference in quality between served files by blibli (png is the highest quality, imo it's the best choice for scanlation, the website serves also jpg and webp files with less space).
> 
> Thank you. Has it been changed by default? Or did Bilibili just now start serving PNGs? Either way, I don't think the PNG's and the JPG's are of different quality, compare: 5 MB PNG file: https://i.imgur.com/2yTQkc4.png 500 KB JPG file: https://i.imgur.com/8V3Eru1.jpg Manga is 'The Incapable Married Princess', but others I've checked are the same. So there might be something weird going on.
Well Bilibli served png files from a long while, it's just that the connector got updated to support all image format that the website serve.
Well, there is a difference on colors and dark areas and little aliasting more noise, we already analysed that.

if you want to jpg use it, you have full choice on what file format you want to get for that connector.

**Comment by Ever4engel** [comment]
Well Bilibli served png files from a long while, it's just that the connector got updated to support all image format that the website serve.
Well, there is a difference on colors and dark areas and little aliasting more noise, we already analysed that.

if you want to jpg use it, you have full choice on what file format you want to get for that connector.

**Comment by Darkmaster006** [comment]
> Well Bilibli served png files from a long while, it's just that the connector got updated to support all image format that the website serve. Well, there is a difference on colors and dark areas and little aliasting more noise, we already analysed that.
> 
> if you want to jpg use it, you have full choice on what file format you want to get for that connector.

I see, for the life of me I couldn't see any difference, thought it'd be a starker one. I'll probably stay with the jpgs. Thanks!
