### ISSUE TITLE
[Manga 347] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#4532]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Titles and chapters not working. Refresh makes all titles disappear. I think site changed format.

**To Reproduce**
1. Name of connector - Manga 347
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) None.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="1117" alt="Screen Shot 2022-03-31 at 12 34 54 PM" src="https://user-images.githubusercontent.com/70929406/161135197-4b24a8b9-c32c-449f-8461-cd9fabfcf454.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Error 404

**Comment by tsentered** [comment]
same problem still. Regardless, Happy New Year!

**Comment by MikeZeDev** [comment]
wdy mean? 
![image](https://user-images.githubusercontent.com/10671518/210741619-0216d2f3-889b-4174-98c9-6b1bd409173c.png)

**Comment by tsentered** [comment]
I meant Reaper Scans still has the same problems, not Manga 347.Sent from my iPhoneOn Jan 5, 2023, at 1:02 AM, MikeZeDev ***@***.***> wrote:﻿
wdy mean?

**Comment by tsentered** [comment]
Apologies.Sent from my iPhoneOn Jan 5, 2023, at 1:02 AM, MikeZeDev ***@***.***> wrote:﻿
wdy mean?
