### ISSUE TITLE
[ストーリアダッシュ Storia Dash] Connector not working

### ISSUE THREAD

**Issue by tsenglol** [manga-download/hakuneko#4533]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes, https://storia.takeshobo.co.jp/

**Describe the bug**
April 1st, 12pm JST Website update messed up the chapters fetch, the manga list load, but no chapter is being displayed when you click on anything from the list
edit2: if you click synchronize now, the manga list is completely gone unless you open the connector again, manga list show up again, but no chapter list is displayed anyway, so the connector is broken due to the website update, manga list https://storia.takeshobo.co.jp/manga/

**To Reproduce**
1. ストーリアダッシュ Storia Dash
2. Click Synchronize or not
3. The manga list is gone when clicking synchronize, if you don't, the manga list show up, but no new chapter is being fetch when clicking on any manga

**Screenshots**
https://i.imgur.com/2qrwIKU.png
https://i.imgur.com/VGIMmxy.png
https://i.imgur.com/xZPHgO7.png

**HakuNeko (please complete the following information):**
 - Version 6.1.7@cf569b

**Comment by MikeZeDev** [comment]
I ma able to get the manga list, the chapters BUUUUUT Cloudflare block the picture download in preview.

**Comment by MikeZeDev** [comment]
All seems to work : manga list chapters preview and download. @Sheepux
