### ISSUE TITLE
[x.mangas-origines.fr] Connector not working

### ISSUE THREAD

**Issue by camisole26** [manga-download/hakuneko#4534]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes : https://x.mangas-origines.fr/catalogue/a-twisted-day/

**Describe the bug**
When I try to update the manga list of x.mangas-origines.fr, Hakuneko offers me to download the file named "download".

**To Reproduce**
1. Name of connector : Mangas Origines
2. Connector update is not working
3. See screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/66274638/161351488-63456e4a-eaa3-44aa-9de2-4545e8041129.png)

**HakuNeko (please complete the following information):**
 - Version : 6.17cf569b

**Comment by MikeZeDev** [comment]
Cloudflare issue.

**Comment by MikeZeDev** [comment]
Redirect to discord
