### ISSUE TITLE
[Gmanga] Connector not working

### ISSUE THREAD

**Issue by mujtaba1moawia** [manga-download/hakuneko#4535]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the app is failed to receive content from the connector, the connector did some update and change the URL or some of that . 
https://gmanga.org/mangas

**To Reproduce**
1. Gmanga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4.Failed to load resource: net::ERR_NAME_NOT_RESOLVED

**Screenshots**

![Screenshot 2022-04-02 004221](https://user-images.githubusercontent.com/102835633/161351635-7f31d213-df62-4fe8-9c6b-137695dd91b4.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Qsoomi** [comment]
I Don't understand, why this issue is not fixed yet?

**Comment by MikeZeDev** [comment]
Its working . @Sheepux
