### ISSUE TITLE
[Site Request] Toon123

### ISSUE THREAD

**Issue by AzureDragon101** [manga-download/hakuneko#4537]
**Name of the website**
Toon123

**Website urls (examples below)**
- Site: http://www.toon123.com/
- Manga List: http://www.toon123.com/bbs/board.php?bo_table=toon_c&sca=001
- Manga example: http://www.toon123.com/bbs/board.php?bo_table=toons&is=9528
- Chapter online viewer example: http://www.toon123.com/bbs/board.php?bo_table=toons&wr_id=1119742&is=a947991d23af59abc35a00435be53b2f&cid=9528

**Languages**
Korean

**Website relationship*
An aggregator for Korean Manhwas, just like Toonkor, but however, toonkor has some errors in some of their raws so it's a bit irritatiing.

**Additional details**
Less ads than you'd see in Newtoki

**Comment by MikeZeDev** [comment]
Is it still alive?

**Comment by MikeZeDev** [comment]
dead?
