### ISSUE TITLE
[1st Kiss Manga] Connector not working

### ISSUE THREAD

**Issue by wedgingt** [manga-download/hakuneko#4539]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
My browser says page not found.

**Describe the bug**
Running hakuneko-desktop on Ubuntu 20.04.4 LTS trying to download from several known sites, notably 1st Kiss Manga.

**To Reproduce**
1. Go to 1st Kiss Manga with 'play' as a search term for manga
2. Download most any manga
3. See error/complaint:  
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

After trying more manga, eventually the following complaint will repeat endlessly without other progress until exiting:
(node:3306087) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.

**Expected behavior**
The manga is downloaded.

**Context (please complete the following information):**
 - OS: Linux Ubuntu 20.04.4 LTS
 - --------------
Framework Info
--------------
Electron : 8.3.4
Chrome   : 80.0.3987.165
Node     : 12.13.0

**Comment by Sheepux** [comment]
Connector working fine here. Unable to reproduce.

Use the "connector issue template", not the "client bug".
Don't use the error message as title. the message mentionned is not related to your issue.

**Comment by MikeZeDev** [comment]
Working fine too. Nightly. Can be close i guess @Sheepux
