### ISSUE TITLE
[Hiperdex] Connector not working

### ISSUE THREAD

**Issue by popogod** [manga-download/hakuneko#4540]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I think it's a problem with Cloudflare

**To Reproduce**
1. Hiperdex
2. Please turn JavaScript on and reload the page.
DDoS protection by [Cloudflare]

 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4507
