### ISSUE TITLE
[Site Request] HVNC

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#4542]
**Name of the website**
HVNC - Free Fakku Manga

**Website urls (examples below)**
- Site: https://fakku.cc
- Manga List: 
- Manga example: 
- Chapter online viewer example: https://fakku.cc/reader?id=645fea086fe9d02835eac5dbc6beb49656241fde

**Languages**
English

**Website relationship*

**Additional details**
LANraragi (edited version) (?)

A site with a wide variety of uncensored hentai, that can hardly be found anywhere else for free.

**Comment by MikeZeDev** [comment]
"Seized website ".

There are also issues  opened for fakku.net. Probably not alternative url but other website.

@Sheepux pls

**Comment by Sheepux** [comment]
looks like they moved to telegram https://www.reddit.com/r/hvnc/
