### ISSUE TITLE
[Site Request] Pocket Comics

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#4543]
**Name of the website**
Pocket Comics

**Website urls (examples below)**
- Site:  https://www.pocketcomics.com/
- Manga example: 
- https://www.pocketcomics.com/comic/7841
- Chapter online viewer example: https://www.pocketcomics.com/comic/7841/chapter/1/product

**Languages**
English

**Comment by Sheepux** [comment]
duplicate #4222
