### ISSUE TITLE
[Site Request] INKR

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#4544]
**Name of the website**
INKR

**Website urls (examples below)**
- Site: https://inkr.com/
- Manga List: https://inkr.com/browse/manga
- https://inkr.com/browse/manhua
- https://inkr.com/browse/webtoon
- https://inkr.com/browse/comics
- https://inkr.com/browse/free
- Manga example: https://inkr.com/title/1170-did-you-reject-mr-lu-today
- Chapter online viewer example: https://inkr.com/title/1170-did-you-reject-mr-lu-today/chapter/69295-chapter-1

**Languages**
English

**Comment by Leifman35** [comment]
I wish this was supported :'(

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3782
