### ISSUE TITLE
[Site Request] doki1001.com

### ISSUE THREAD

**Issue by siak123** [manga-download/hakuneko#4545]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://doki1001.com
- Manga List: https://doki1001.com/?s=&post_type=wp-manga
- Manga example: https://doki1001.com/manga/%e5%bf%8c%e3%81%bf%e5%ad%90%e3%81%a8%e5%91%bc%e3%81%b0%e3%82%8c%e3%81%9f%e5%8f%ac%e5%96%9a%e5%a3%ab-raw-free/
- Chapter online viewer example: https://doki1001.com/manga/%e5%bf%8c%e3%81%bf%e5%ad%90%e3%81%a8%e5%91%bc%e3%81%b0%e3%82%8c%e3%81%9f%e5%8f%ac%e5%96%9a%e5%a3%ab-raw-free/%e7%ac%ac231%e8%a9%b1/

**Languages**
Raw Japanese

**Website relationship*
before his domain was https://manga-1001.com  , it is a backup site manga1001.com

**Additional details**
your template is similar to this site  mangagohan.com  change site to gokumanga.com

**Comment by MikeZeDev** [comment]
Website is dead
