### ISSUE TITLE
[Kiss Manga] Connector not working

### ISSUE THREAD

**Issue by Odaxis** [manga-download/hakuneko#4546]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Nothing will load through the app. website works fine.

**To Reproduce**
1. Kissmanga (https://kissmanga.in/)
2. All
3. All
4. Failed to load resource: the server responded with a status of 503 ()

**HakuNeko (please complete the following information):**
 - Version [Latest Nightly]

**Comment by MikeZeDev** [comment]
Checking if the site connection is secure Cloudflare shit.

**Comment by MikeZeDev** [comment]
Works on nightly as of 11 December 2022. Feel free to reopen if you got the problem
