### ISSUE TITLE
[Gmanga] Connector not working

### ISSUE THREAD

**Issue by Dr-Shiro** [manga-download/hakuneko#4548]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I am unable to refresh the manga list. the app is failed to receive content from the connector, the connector did some update and change the URL or some of that .
https://gmanga.me/mangas

**To Reproduce**

1. GManga
2. connector update not working

Failed to update manga list for GManga
Failed to receive content from "https://gmanga.me/api/mangas/search" (status: 400) - 

**Screenshots**
![image](https://user-images.githubusercontent.com/57459656/162343816-8dc0f39f-863c-4e15-afa1-e28fd46d4eb0.png)

HakuNeko (please complete the following information):

Version [e.g. 6.17]: 6.1.7

**Comment by 27136773** [comment]
See: #4535
