### ISSUE TITLE
[Lily Manga] Connector not working (Timeouts)

### ISSUE THREAD

**Issue by Nivyan** [manga-download/hakuneko#4550]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The getUpdatedChaptersFromWebsite function timeouts from www.lilymanga.com

**To Reproduce**
1. Name of connector
Lily Manga
`_getUpdatedChaptersFromWebsite Error: Failed to load "https://lilymanga.com/" within the given timeout of 60 seconds!
    at Request.mjs:380`

**Screenshots**
[Screenshot](https://i.imgur.com/LCIqL06.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@cf569b

**Comment by MikeZeDev** [comment]
Working on nightly. Can be closed i guess @Sheepux
