### ISSUE TITLE
[CocoManga (Coco漫画)] Connector not working

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#4558]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update manga list for Cocomanga cannot read property 'href' or undefined

**To Reproduce**
1. CocoManga
2. 
3. 
4. Connector.mjs:579 TypeError: Cannot read property 'href' of undefined
    at CocoManHua._getMangas (ZYMK.mjs:66)
    at async CocoManHua._getMangaList (Connector.mjs:576) CocoManHua {id: "cocomanhua", label: "Coco漫画", tags: Array(2), isLocked: false, initialized: true, …}

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by X0Zeon** [comment]
![image](https://user-images.githubusercontent.com/28489226/170816995-ddb44c22-b3ad-4491-a756-17ace4d26864.png)
i have 403 problem i need clear cookie than i can fix it but i open another cocomanga web again 403  just can use one time clear cookie I can't after that i use andorid no have this problem just in computer have this, i cant watch manga 😭

**Comment by engkhsky** [comment]
Is this connector resolved? I also unable to download manga from this website

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/4802
https://github.com/manga-download/hakuneko/issues/4725

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/4050
