### ISSUE TITLE
[Manhwaindo] Connector not working

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#4563]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
cannot load image on some chapter (not all but most of chapter). when i opened manually the image link its say forbidden http referer blocked, and i see the link is use cdn statically, when i use the original link of the image is loaded well but i dont know how to do that on hakuneko

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cant reproduce, on nightly. Any manga/chapter so we can test ?
