### ISSUE TITLE
[Site Request] Uzay Manga

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4567]
**Name of the website**
Uzay Manga

**Website urls (examples below)**
- Site: https://uzaymanga.com/
- Manga List: https://uzaymanga.com/manga/
- Manga example: https://uzaymanga.com/manga/my-new-wife-is-forcing-herself-to-smile/
- Chapter online viewer example: https://uzaymanga.com/manga/my-new-wife-is-forcing-herself-to-smile/bolum-1/

**Languages**
Turkish

**Website relationship*

**Additional details**

**Comment by NekoManga** [comment]
Hello, the episodes are not downloading
