### ISSUE TITLE
xianman123

### ISSUE THREAD

**Issue by maksumnik** [manga-download/hakuneko#4571]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I cant download or read manga

![Screenshot_76](https://user-images.githubusercontent.com/103852539/163687904-2e27df89-725c-4009-9724-3aadb82f69e0.png)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Unexpected end of json input. Website may have changed something
