### ISSUE TITLE
[Site Request] asurascans

### ISSUE THREAD

**Issue by apt42541** [manga-download/hakuneko#4572]
**Name of the website**
asurascans

**Website urls (examples below)**
- Site: https://www.asurascans.com
- Manga List: https://www.asurascans.com/manga/?page=1&order=update
- Manga example: https://www.asurascans.com/comics/super-evolution/
- Chapter online viewer example: https://www.asurascans.com/super-evolution-chapter-48/

**Languages**
List of languages supported by the website
English , Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)
it's wordpress theme but other make setting not same.

**Comment by amit34521** [comment]
Connector for Asura Scans is already available.

**Comment by Sterbenm** [comment]
resolve

**Comment by MikeZeDev** [comment]
can be closed @Sheepux
