### ISSUE TITLE
[DM5.com] Connector not working

### ISSUE THREAD

**Issue by tamster94** [manga-download/hakuneko#4574]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't download any chapter for this connector

**To Reproduce**
1. Name of connector - dm5.com
2. Name of manga (if connector update is working) - guimiezhiren / https://www.dm5.com/manhua-guimiezhiren/
3. Name of chapter (if manga update is working) - ch 152-ch 205
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 403 ()
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open '/Users/tamster/Library/Application Support/hakuneko-desktop/hakuneko.mangas.11toon'

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![Screen Shot 2022-04-17 at 8 11 06 PM](https://user-images.githubusercontent.com/103913867/163748608-ec2b64fb-52e5-4d94-a34e-cbfa3f9ce069.png)

**Comment by Sheepux** [comment]
duplicate #4536
