### ISSUE TITLE
[Site Request] manga4life

### ISSUE THREAD

**Issue by Alverik** [manga-download/hakuneko#4575]
**Name of the website**
manga4life

**Website urls (examples below)**
- Site: **https://manga4life.com/**
- Manga List: https://manga4life.com/search/
- Manga example: https://manga4life.com/manga/Ore-Monogatari
- Chapter online viewer example: https://manga4life.com/read-online/Ore-Monogatari-chapter-24.html

**Languages**
English

**Comment by starring94** [comment]
The connector for this website is already available with the name MangaLife.

**Comment by HorrorBest** [comment]
Hey could you please Close this issue.... ?? @Alverik with the button at the bottom

**Comment by MikeZeDev** [comment]
Can be closed @Sheepux
