### ISSUE TITLE
[Lezhin (english) ] Connector not working

### ISSUE THREAD

**Issue by HorrorBest** [manga-download/hakuneko#4577]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Webtoon ain't showing any chapters.

**To Reproduce**
1. Lezhin (english)
2. Payback / Walk On Water (I think all
3. "Not Showing any chapter"
4. ReferenceError: __LZ_PRODUCT__ is not defined (in th console) [ERROR]

**HakuNeko (please complete the following information):**
 - Version 6.1.7@cf569b

**Comment by Sheepux** [comment]
possible duplicate of #4433 
possibly fixed in hakuneko nightly, can you give a try ?
