### ISSUE TITLE
mangahere cant download

### ISSUE THREAD

**Issue by mangatabar** [manga-download/hakuneko#4584]
get this error  i can view/read via web but got this error when try to download

![image](https://user-images.githubusercontent.com/46851278/164161610-ebb337e7-e1a1-4e5d-bea0-0d37774ee2d7.png)

**Comment by Sheepux** [comment]
Saw that this morning (i'm a mangahere user). I'll fix it this evening as soon as my working hours are over.

**Comment by OutcastSlayer** [comment]
MangaHere still isnt working, I've even reinstalled the client but to no avail.

**Comment by Sheepux** [comment]
merge request is not merged, issue is still open. wait for it to be closed
