### ISSUE TITLE
[TraducionesAmistosas][nartag] Connector not working 

### ISSUE THREAD

**Issue by horacio881** [manga-download/hakuneko#4589]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**

The connector is not working, I can't download anything or view the manga list.

**Screenshots**

![Sin título](https://user-images.githubusercontent.com/24598871/164376343-1817eed2-7a4f-419c-9a93-978286a62801.jpg)

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 6.17

**Comment by MikeZeDev** [comment]
Cloudflare check :/

**Comment by MikeZeDev** [comment]
Works now
