### ISSUE TITLE
[cocomanga] Connector not working

### ISSUE THREAD

**Issue by apt42541** [manga-download/hakuneko#4595]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector cocomanga
2. Name of manga (if connector update is working) 从渡劫开始
3. Name of chapter (if manga update is working) [第29话 无妄之灾](https://www.cocomanga.com/17226/1/29.html)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
ClipboardConnector.mjs:66 CLIPBOARD: https://www.cocomanga.com/17226/ 
     TypeError: Cannot read property 'textContent' of undefined
**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/12625408/164884098-3cff3d60-cf59-4c5c-a135-9d85eebcb061.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
rev. master@822a64

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4050
