### ISSUE TITLE
[Site Request] cocomanga

### ISSUE THREAD

**Issue by HMZ67993** [manga-download/hakuneko#4596]
cocomanga

- Site: https://www.cocomanga.com
- Manga List: https://www.cocomanga.com/show
- Manga example: https://www.cocomanga.com/15204/
- Chapter online viewer example: https://www.cocomanga.com/13112/1/272.html

Languages: Chinese

Site was working fine but it doesn't now

**Comment by MikeZeDev** [comment]
Website is added

@Sheepux pls <3
