### ISSUE TITLE
[DOUJINDESU] Connector not working

### ISSUE THREAD

**Issue by amzz888** [manga-download/hakuneko#4600]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector https://212.32.226.234/ (DOUJINDESU) and https://194.233.66.232/ (Komiktap.in)
2. Name of manga A Knowing Sister
3. Name of chapter not working download
4. the connector still works but the chapter download error in doujindesu, Please help

**Screenshots**
![image](https://user-images.githubusercontent.com/104286800/164953865-062e0185-80d1-460b-af15-f394a79bc267.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
create an issue for each separate connector
Edit: Komiktap duplicate #3802

**Comment by MikeZeDev** [comment]
Preview works fine, downloading gives 404 errors.

**Comment by Anitab212** [comment]
Hi @ [small world cup](https://asmallworldcup.com) thanks for your share.

**Comment by styfox123** [comment]
Wit

**Comment by FazzD** [comment]
DoujinDesu Cannot be opened on the proxy site

**Comment by Sheepux** [comment]
open a new issue, this one is closed from 2022.
Also, use "hakuneko nightly" version, it's been fixed

**Comment by Arhan235** [comment]
V
