### ISSUE TITLE
Tsumino Connector not working

### ISSUE THREAD

**Issue by Danyoooo** [manga-download/hakuneko#4601]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can not connect to Tsumino as connetor. Also Cloudflare loads indefinitely or just shows a blank page when I try to use the app's browser.

**To Reproduce**
1. Choose Tsumino as connector
2. Press the button to synchronize

**Screenshots**
![image](https://user-images.githubusercontent.com/104294157/164960662-fd8fb9ce-13c1-4ada-8dee-fccf2772d42c.png)

**HakuNeko :**
 - Version 6.17

**Comment by MikeZeDev** [comment]
Nightly. Working as intended.

**Comment by MikeZeDev** [comment]
Can be closed @Sheepux  <6
