### ISSUE TITLE
[MangaHere] Connector not working

### ISSUE THREAD

**Issue by Romangelo** [manga-download/hakuneko#4603]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Unable to download any chapter of any manga.

**To Reproduce**
1. Mangahere
2. Any of them.
3. All.
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

DownloadJob.mjs:115 Error: Page " https://zjcdn.mangahere.org/store/manga/28927/044.1/compressed/e001.jpg" returned status: 403 - 
    at DownloadJob.mjs:143
    at async Promise.all (index 0)
    at async EventTarget._downloadPages (DownloadJob.mjs:108) Array(21)
_downloadPages @ DownloadJob.mjs:115
zjcdn.mangahere.org/store/manga/28927/044.1/compressed/e002.jpg:1 Failed to load resource: the server responded with a status of 403 ()

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
6.17

**Comment by Sheepux** [comment]
Already fixed, use hakuneko nightly
