### ISSUE TITLE
[MangaKyo] Connector not working

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#4608]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Website changed the domain from "https://www.mangakyo.me" to "https://mangakyo.me"

**To Reproduce**
1. Name of connector mangakyo
2. Name of manga (if connector update is working) not work
3. Name of chapter (if manga update is working) not work

**Comment by MikeZeDev** [comment]
Can you please change the issue title so it reflect that the Website url changed? Changing url in connectors is faster than correcting bugs so it may get more attention from devs 🍡 .
