### ISSUE TITLE
please add this website serimanga.com

### ISSUE THREAD

**Issue by zasfan** [manga-download/hakuneko#461]
https://serimanga.com/?a=a
ı hope you add this website for turkey
thanks for read

**Comment by ercanakcay** [comment]
♥

**Comment by komarna** [comment]
https://github.com/manga-download/hakuneko/issues/461
Adonis Fansub
https://manga.adonisfansub.com 
This site added. Ok this. And thank you for this site. 
BUT…
https://github.com/manga-download/hakuneko/issues/1510
https://github.com/manga-download/hakuneko/issues/1606
This topics say duplicate adonis fansub and seri manga. But they are not.
Seri manga
https://serimanga.com/?a=a
This site is not add. For request always say 461, 1510 or 1606. 

These are DIFFERENT sites.  
Please Seri manga add too. 
https://serimanga.com/?a=a
Thank you.

**Comment by 27136773** [comment]
I re-checked #1510 and #1606, both issues are referencing the exact same site https://serimanga.com/?a=a which is already tracked here in this ticket #461 which is still open.

As long as the ticket is open, the site has not been added...
