### ISSUE TITLE
[Site Request] Sugar Babies

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#4615]
**Name of the website**
Sugar Babies

**Website urls (examples below)**
- Site: https://sugarbbscan.com/
- Manga List: https://sugarbbscan.com/series/
- Manga example: https://sugarbbscan.com/series/my-family-is-obsessed-with-me/
- Chapter online viewer example: https://sugarbbscan.com/series/my-family-is-obsessed-with-me/chapter-1/

**Languages**
English

**Comment by starring94** [comment]
HakuNeko nightly already added this connector.
