### ISSUE TITLE
[Feature] YAOI tag

### ISSUE THREAD

**Issue by HorrorBest** [manga-download/hakuneko#4618]
**Is your feature request related to a problem? Please describe.**
I like reading a lot of webtoons, and this program is really good but whenever I wanna search for "YAOI" manga/webtoon...
I cant find a tag for it so I have to go search from a website name.... but I'm sure there websites that don't have YAOI in their name that also have YAOI content

**Describe the solution you'd like**
It would be a good idea to add a YAOI tag.

**Describe alternatives you've considered**
you can allow users to add or vote for a tag that can be added to a website EX: this example.com website is tagged with (Manga, hentai) but it does have webtoons In it.... users can add tags to websites so people can find more website for the content they want _(Please Make this happen as It came to my head when I was writing this request)_

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7@cf569b

**Comment by Sheepux** [comment]
hakuneko is not a manga search engine.
Tags are for connector, yaoi is not related to a connector but to a manga title.
Your request is out of topic for hakuneko
