### ISSUE TITLE
[Read M] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#4619]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

Refresh isn't working and there are no error messages. I believe they have changed the website format.

**To Reproduce**
1. Name of connector. - Read M
2. Name of manga (if connector update is working). - NA
3. Name of chapter (if manga update is working).  - NA
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

<img width="1125" alt="Screen Shot 2022-04-26 at 5 41 23 PM" src="https://user-images.githubusercontent.com/70929406/165415626-8a6c8da5-a4e0-4318-9e81-49baf523725f.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Works on nightly, can be closed @Sheepux pls <3
