### ISSUE TITLE
Chapter List Bug

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#462]
> **From:** HakuNeko User

Hi, I tried several time to reinstall Hakuneko to fix my issue, I have the latest version and the 64bit. The first time I used Hakuneko was for download Berserk. I downloaded only the first 10 books on Japscan. Now, when I want download the others books, the chapter list only shows the books that I Have already download. I have this issues for all sites and all mangas that I try. Thanks for helping me and sorry for my not so well english (I'm French).

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by hypoflex** [comment]
Your sure you're using the connector and not folder view?
as can be seen in the image below, folder view (which is also shown as connector in top left)
only shows the items it knowns from your manga directory
![image](https://user-images.githubusercontent.com/36196198/65836024-d29ad600-e2ed-11e9-8773-50249f8f8efa.png)

**Comment by 27136773** [comment]
Please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by 27136773** [comment]
No further response => closed
