### ISSUE TITLE
Animixplay.to

### ISSUE THREAD

**Issue by AdriBD83** [manga-download/hakuneko#4624]
Animixplay

- Site: https://animixplay.to/
- Manga List: https://animixplay.to/list
- Manga example: https://animixplay.to/v1/boruto-naruto-next-generations
- Chapter online viewer example: https://animixplay.to/v1/boruto-naruto-next-generations

**Languages**
English.
**Website relationship*
Uses https://gogoplay5.com/   and some other websites.

**Additional details**
uses vidstream, mycloud, stream sb etc.

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/3919
