### ISSUE TITLE
Zoro.to

### ISSUE THREAD

**Issue by AdriBD83** [manga-download/hakuneko#4625]
Zoro

**Website urls **
- Site: https://zoto.to/
- Manga List: https://zoro.to/az-list
- Manga example: https://zoro.to/one-piece-100
- Chapter online viewer example: https://zoro.to/watch/one-piece-100?ep=2142

**Languages**
English

**Additional details**
uses vidstream, vidcloud etc.

**Comment by MikeZeDev** [comment]
dead website.

**Comment by MikeZeDev** [comment]
dead

**Comment by beedell-roke** [comment]
> https://github.com/manga-download/hakuneko/issues/4625#issuecomment-1722540131

What does that mean, @MikeZeDev?

**Comment by MikeZeDev** [comment]
Website is dead

**Comment by beedell-roke** [comment]
@MikeZeDev, are you aware that the site owners have moved the website to a new domain – HTTPS://AniWatch.to?

**Comment by MikeZeDev** [comment]
> @MikeZeDev, are you aware that the site owners have moved the website to a new domain – [HTTPS://AniWatch.to](HTTPS://AniWatch.to)?

I forgot that, thanks

**Comment by beedell-roke** [comment]
@MikeZeDev, why https://github.com/manga-download/hakuneko/issues/4625#event-12087031665?

**Comment by beedell-roke** [comment]
> https://github.com/manga-download/hakuneko/issues/4625#issuecomment-1991839599

@MikeZeDev, https://github.com/manga-download/hakuneko/issues/6878#issue-2181831304
