### ISSUE TITLE
Issue with loading list from MangaPark

### ISSUE THREAD

**Issue by MT135** [manga-download/hakuneko#463]
Manga list loads to up to letter D and stops. Refreshing and restart doesn't help. Other manga sites load the whole list from A to Z.

**Comment by hypoflex** [comment]
Confirmed,
Mangapark (`super.id = 'mangapark-en';`) does indeed only grab till letter D
(result: 10.000 mangas. desired result: 58490 mangas)
Mangapark (2018) (`super.id = 'mangapark';`) does download from A-Z

switching to that will resolve the issue. 2018 version is multi language so expect some manga's being a different language.

ticket will stay open for further investigation.

**Comment by hypoflex** [comment]
according to the website there are 1950 pages of manga's 
Hakuneko does indeed pull 1950 pages.
but going onto the website to page 1950 it giving `No match found. Try a different search...`

looking through it page 334 seems to be the last page it can properly pull
https://mangapark.net/search?orderby=a-z&page=334
page 335 returns the error, so this is not HakuNeko related

**Comment by hypoflex** [comment]
send an email to report the bug

**Comment by 27136773** [comment]
Use the [copy & paste](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list) feature as a workaround

**Comment by MT135** [comment]
Thanks, copy and paste worked

**Comment by 27136773** [comment]
I think this is not going to be fixed in HakuNeko
