### ISSUE TITLE
[Storia Dash] Connector not working

### ISSUE THREAD

**Issue by pazergithub** [manga-download/hakuneko#4630]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes (https://storia.takeshobo.co.jp/manga/)

**Describe the bug**
HakuNeko will no longer load chapter lists for any Storia Dash series. Previously downloaded chapters cannot be redownloaded. New series (added to Storia Dash within the past 4-6 weeks) cannot be viewed and direct links to the series page will not be parsed if copied to the clipboard.

**HakuNeko (please complete the following information):**
 - Version: 6.17@cf569b

**Comment by MikeZeDev** [comment]
Tested on nightly, saw no problems. Please name a non working manga.

**Comment by MikeZeDev** [comment]
template was changed to takeshobonew in the meantime, so its fixed.
