### ISSUE TITLE
[bato.to] Connector not working

### ISSUE THREAD

**Issue by fatezuru** [manga-download/hakuneko#4631]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

The connector won't update and can't download chapters. Whenever I click a title, it will just notify that it is offline and is only accessible in the manga directory. Copying and pasting the link is not working too.

**Comment by MikeZeDev** [comment]
Duplicate of https://github.com/manga-download/hakuneko/issues/4632
