### ISSUE TITLE
Batoto Connector not working

### ISSUE THREAD

**Issue by receh16** [manga-download/hakuneko#4632]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I see in F12 there a text Failed to load resource: the server responded with a status of 403 ()

**To Reproduce**
1. Name of connector Batoto
2. Name of manga (if connector update is working) I Raised Cinderella Preciously
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : 
![Screenshot_1](https://user-images.githubusercontent.com/104669304/166094533-d716aead-9dd1-4cd9-821b-d48758a55af0.png)
![Screenshot_1](https://user-images.githubusercontent.com/104669304/166094539-8ed38ef4-11f6-42ee-b23a-b5fd7fc877c9.png)
Failed to load resource: the server responded with a status of 403 ()

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4631
