### ISSUE TITLE
[Feature] Wallpaper

### ISSUE THREAD

**Issue by 0adri3n** [manga-download/hakuneko#4633]
Hi !
First, I love hakuneko ! I suggest the following feature : wallpaper.
The menu at the right could be removed if a cross is clicked, and manga list etc hidden to see our wallpaper.

**Comment by Sheepux** [comment]
?? If you're hiding everything what's the point of using hakuneko ? I don't get it

**Comment by MikeZeDev** [comment]
Maybe he wants a panic button? I can understand the use tho.

**Comment by Sheepux** [comment]
For such case there is the "reduce to taskbar" button isn't it ?

**Comment by MikeZeDev** [comment]
A hotkey is easier :D .
Anyway after re-reading carefully,  i guess he wants to hide some part of the interface.

"The menu at the right could be removed if a cross is clicked,"
"and manga list etc hidden "
"to see our wallpaper." > goal? 

Its either a hide to tray thing, or a hide element of the interface but i dont get why its entitled "wallpaper" 😓

**Comment by 0adri3n** [comment]
At least Mike u understand
Its entitled wallpaper bcause maybe we can set a wallpaper for hakuneko's background. A wallpp that we can see with hiding some part of the UI.
Or replace this by a phone wallpaper or something else idk
![image](https://user-images.githubusercontent.com/62818208/167123880-9eb0ef4c-3362-4d9b-a72c-42f26addd3dd.png)

**Comment by Sheepux** [comment]
if you want to disable the right side, then use the settings to disable it (enable reader)
And if you want to disable the left side, what's the point of using hakuneko ? :)
