### ISSUE TITLE
[Feature] Faster Manga Load From Huge Connectors

### ISSUE THREAD

**Issue by HorrorBest** [manga-download/hakuneko#4635]
**Is your feature request related to a problem? Please describe.**
I don't like it when I the manga list takes ages to lead while the server of the manga is good and I have a good internet connect, The website got 7000+ "Manga-list" pages and that's gonna take a long time to load

**Describe the solution you'd like**
If You could at least show the Mangas while they are loading... (well I want them just to load faster) or you could maybe allow the user to specify which page/list of pages to load from the connector

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7@cf569b

**Additional context**
EXAMPLE CONNECTOR: _**manhuascan**_

**Comment by Sheepux** [comment]
When you need it to be faster, use the URL copy paste feature.
Even if you have a good connexion, we try to not abuse the targeted website as it is not "ours".

**Comment by HorrorBest** [comment]
> When you need it to be faster, use the URL copy paste feature. Even if you have a good connexion, we try to not abuse the targeted website as it is not "ours".

If You have a wiki page that shows how to use COPY PASTE then please link it here <3... also Do I need the Chapter link or the "Manga-List" page link....

**Comment by Sheepux** [comment]
Simply google "hakuneko copy paste" or read the documentation https://hakuneko.download/docs/FAQ/#copy-and-paste

**Comment by HorrorBest** [comment]
> Simply google "hakuneko copy paste" or read the documentation https://hakuneko.download/docs/FAQ/#copy-and-paste

Problem Solved, Will it work on connectors that aren't on Heku ??

**Comment by Sheepux** [comment]
no, it's just a way to bypass the refresh list process, but it still require the connector to be coded
