### ISSUE TITLE
[mangareader.to] Scrambled Page Content

### ISSUE THREAD

**Issue by riizii05** [manga-download/hakuneko#4636]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Basically, the manga “Kotaro Lives Alone” pages content is scrambled.

**To Reproduce**
1. Go to mangareader.to connector 
2. Click on Kotaro Lives Alone
3. Scroll down to Chapters 26-Ongoing
and look through any of those chapters 
4. You’ll then see the scrambled panels/content on every page in each chapter 

**Expected behavior**
I expected the pages to be normal, and not disoriented and scrambled.

**Screenshots**

![E02BB1A9-593E-4747-A7D7-6DD0B696A15F](https://user-images.githubusercontent.com/104748835/166184431-1ace5011-2af2-4e5f-ad64-d238396f2b65.png)

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 6.17

**Additional context**
Only chapters 26-present are affected, the chapters before 26 are all normal.

**Comment by Ninjaracc00n** [comment]
I can add this issue applies to more than just Kotaro Lives Alone. It seems to be every newly added chapter of any manga as of a couple of weeks ago.
