### ISSUE TITLE
[Site Request] TMO Manga - Mangas online en español

### ISSUE THREAD

**Issue by KaiserSKL** [manga-download/hakuneko#4637]
**TMO Manga - Mangas online en español**
thewebsitename

**Website urls (examples below)**
- Site: https://tmomanga.com/
- Manga List: https://tmomanga.com/biblioteca
- Manga example: https://tmomanga.com/manga/spy-x-family
- Chapter online viewer example: https://tmomanga.com/capitulo/spy-x-family-62.50

**Languages**
Spanish

**Website relationship*
Tu manga online

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara without admin-ajax.
