### ISSUE TITLE
[http://tumangasonline.com/] tumangasonline.com leer mangas en español

### ISSUE THREAD

**Issue by KaiserSKL** [manga-download/hakuneko#4638]
**tumangasonline.com leer mangas en español**
thewebsitename

**Website urls (examples below)**
- Site: http://tumangasonline.com/
- Manga List: http://tumangasonline.com/manga-list
- Manga example: http://tumangasonline.com/manga/spy-x-family
- Chapter online viewer example: http://tumangasonline.com/manga/spy-x-family/62.50-fc01/1

**Languages**
Spanish

**Website relationship*
tu manga online

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Its redirecting to Mangadoor, which is supported but need fixes
