### ISSUE TITLE
Comic Walker not able to download some manga

### ISSUE THREAD

**Issue by jrdp18** [manga-download/hakuneko#464]
I can download [this](https://comic-walker.com/contents/detail/KDCW_MF00000180010000_68/) but not [this](https://comic-walker.com/contents/detail/KDCW_MF00000063010000_68/)

**Comment by hypoflex** [comment]
last images seems to be causing the issue, further inspection needed
![image](https://user-images.githubusercontent.com/36196198/65897720-3be31d80-e3b0-11e9-8091-b90b17d5a650.png)
