### ISSUE TITLE
[Site Request] Getcomics

### ISSUE THREAD

**Issue by Irithind** [manga-download/hakuneko#4641]
**Name of the website**
Getcomics

**Website urls (examples below)**
- Site: https://getcomics.info
- Manga List: https://getcomics.info/sitemap/
- Manga example: https://getcomics.info/other-comics/empowered-special-1-7-2009-2015/

**Languages**
As far as I know, only English.

**Comment by MikeZeDev** [comment]
This website does no always provide ways to read comics online. Most of the time it give external links on file hosters like Mega and its crb/cbz anyway. Not sure its relevant in Hakuneko.
