### ISSUE TITLE
[Tumangaonline] Connector not working

### ISSUE THREAD

**Issue by Uc690** [manga-download/hakuneko#4642]
Hi, for a few days I can not download anything from Tumanga, the page works well and I can read the manga without problems, but when I want to download them from hakuneko it doesn't let me and I get errors. 
I tried reinstalling hakuneko but it doesn't work, and when i try to update the connector i get an error that tells me to wait while it connects to the server and nothing happens from there (it doesn't matter how long I wait)

I attached screenshots showing the problem
![1](https://user-images.githubusercontent.com/53823367/166610458-e6585dd9-4fdf-4742-bdb9-91f137b0d408.png)
![2](https://user-images.githubusercontent.com/53823367/166610462-045c09d4-5694-4de8-bd33-37177fe0a382.png)
![3](https://user-images.githubusercontent.com/53823367/166610463-cbed2187-569d-4ce8-a058-b8492413f980.png)

**To Reproduce**
1. Name of connector: Tumangaonline
2. Name of manga (if connector update is working): all the mangas
3. Name of chapter (if manga update is working): all chapters

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by kuvoid** [comment]
I add information for devs,

The problem is related to getting the reader pics.

![Screenshot_39](https://user-images.githubusercontent.com/44142877/167253582-2120bef5-2b59-4ca1-a445-6eb2b6cec5ca.png)
![Screenshot_40](https://user-images.githubusercontent.com/44142877/167253610-4bad941d-3697-4873-acf7-927e4130ba4a.png)

**Comment by Chomping** [comment]
any update?

**Comment by kuvoid** [comment]
Nope.

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4622
