### ISSUE TITLE
[https://www.readmng.com] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#4643]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes , (issues shows one open case but all cases are really old)

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapters not showing. Refresh disappears all titles. No errors. I believe problem caused by redesigned  cite.

**To Reproduce**
1. Name of connector - (https://www.readmng.com)
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

<img width="1118" alt="Screen Shot 2022-05-04 at 12 13 02 PM" src="https://user-images.githubusercontent.com/70929406/166809010-54942fe3-be37-496d-adc6-ffa608c4cdca.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
I can confirm this on nightly. Nothing works because they revamped their website. Its also broken on tachiyomi for the same reason.
