### ISSUE TITLE
[mangahere.cc] Returned Status: 403

### ISSUE THREAD

**Issue by JakaiMandrake** [manga-download/hakuneko#4645]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it says https://zjcdn.mangahere.org/store/manga (the next part is different depending on the manga then) returned status: 403
I've refreshed the list, checked in the browser, checked my version (6.1.7), and waited a few day to see if it was a temp problem
but no matter the manga on the site it still says the same

**To Reproduce**
1. Name of connector - Label: MangaHere ID: mangahere URL: https://mangahere.cc
2. Name of manga - Any
3. Name of chapter - Any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) it seems long but here (it was too long had to cut the last half)
index.html:46 Loading Engine: HakuNeko
hakuneko://plugins/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
Connectors.mjs:49 Failed to load connector "hakuneko://cache/mjs/connectors/Comikey.mjs" TypeError: Cannot read property 'isDevToolsOpened' of null
    at Comikey.mjs:4
    at Comikey.mjs:4
    at Comikey.mjs:4
    at Comikey.mjs:4
register @ Connectors.mjs:49
index.html:61 Loading Frontend: frontend@classic-light
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
loadClassicPolymer @ index.html:76
mjs/connectors/templates/VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (Settings.mjs:305)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ mjs/connectors/templates/VRV.mjs:305
mjs/connectors/templates/VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (Settings.mjs:305)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ mjs/connectors/templates/VRV.mjs:305
mjs/connectors/templates/VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (Settings.mjs:305)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ mjs/connectors/templates/VRV.mjs:305
Settings.mjs:378 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
(anonymous) @ Settings.mjs:378
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\LENOVO\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.tenmanga'
(anonymous) @ Connector.mjs:215
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\LENOVO\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.mangafox'
(anonymous) @ Connector.mjs:215
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\LENOVO\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.mangatownonline'
(anonymous) @ Connector.mjs:215
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\LENOVO\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.tenmanga'
(anonymous) @ Connector.mjs:215
f72_1.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f01.jpg:1 Failed to load resource: the server responded with a status of 403 ()
DownloadJob.mjs:115 Error: Page " https://zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f01.jpg" returned status: 403 - 
    at DownloadJob.mjs:143
    at async Promise.all (index 0)
    at async EventTarget._downloadPages (DownloadJob.mjs:108) Array(73)
_downloadPages @ DownloadJob.mjs:115
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f02.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f03.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f04.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f05.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f06.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f07.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f08.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f09.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f10.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f11.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f12.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f13.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f14.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f15.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f16.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f17.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f18.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f19.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f20.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f21.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f22.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f23.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f24.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f25.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f26.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f27.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f28.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f30.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f31.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f32.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f33.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f34.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f35.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f36.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f37.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f38.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f39.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f40.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f41.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f42.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f43.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f44.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f45.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f46.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f47.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f48.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f49.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f50.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f51.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f52.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f53.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f54.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f55.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f56.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f57.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f58.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f59.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f60.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f61.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f62.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f63.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f64.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f65.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f66.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f67.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f68.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f69.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f70.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f71.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f72.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f73.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f72_1.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f04.jpg:1 Failed to load resource: the server responded with a status of 403 ()
DownloadJob.mjs:115 Error: Page " https://zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f04.jpg" returned status: 403 - 
    at DownloadJob.mjs:143
    at async Promise.all (index 3)
    at async EventTarget._downloadPages (DownloadJob.mjs:108) Array(73)
_downloadPages @ DownloadJob.mjs:115
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f01.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f50.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f58.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f56.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f67.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f54.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f66.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f52.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f57.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f60.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f68.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f59.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f51.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f63.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f53.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f65.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f69.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f62.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f72.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f49.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f61.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f70.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f64.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f73.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f55.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f04.jpg:1 Failed to load resource: the server responded with a status of 403 ()
DownloadJob.mjs:115 Error: Page " https://zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f04.jpg" returned status: 403 - 
    at DownloadJob.mjs:143
    at async Promise.all (index 3)
    at async EventTarget._downloadPages (DownloadJob.mjs:108) Array(73)
_downloadPages @ DownloadJob.mjs:115
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f42.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f71.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f37.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f39.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f48.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f46.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f72_1.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f41.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f38.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f36.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f40.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f43.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f35.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f34.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f44.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f47.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f45.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f21.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f11.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f26.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f27.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f02.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f28.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f22.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f09.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f31.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f25.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f07.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f20.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f08.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f14.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f06.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f12.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f17.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f33.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f16.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f19.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f10.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f30.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f13.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f23.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f05.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f58.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f32.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f01.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f66.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f50.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f54.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f03.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f56.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f15.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f24.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f18.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f67.jpg:1 Failed to load resource: the server responded with a status of 403 ()
f52.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f60.jpg:1 Failed to load resource: the server responded with a status of 403 ()
zjcdn.mangahere.org/store/manga/1484/01-001.0/compressed/f57.jpg:1 Failed to load resource: the server responded with a status of 403 ()

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
use hakuneko nightly, it's already fixed here
