### ISSUE TITLE
[https://skymanga.xyz/] thewebsitename

### ISSUE THREAD

**Issue by tuvinh0106** [manga-download/hakuneko#4647]
**Name of the website**
skymanga.xyz

**Website urls (examples below)**
- Site: https://skymanga.xyz/
- Manga List: https://skymanga.xyz/read/?m_orderby=latest
- Manga example: https://skymanga.xyz/read/escort-warrior/
- Chapter online viewer example: https://skymanga.xyz/read/escort-warrior/chapter-133/

**Languages**
english, korean, chinese

**Website relationship*
Skymanga.xyz is the alternate domain name of Skymanga.co

**Additional details**
Manhwa/Manhua

**Comment by MikeZeDev** [comment]
Duplicate
