### ISSUE TITLE
[Site Request] https://manhwafreak.com/

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#4649]
**Name of the website**
[thewebsitename](https://manhwafreak.com/)

**Website urls (examples below)**
- Site: https://manhwafreak.com/
- Manga List: https://manhwafreak.com/manga/
- Manga example: https://manhwafreak.com/manga/dimensional-mercenary-other-world-warrior/
- Chapter online viewer example: https://manhwafreak.com/dimensional-mercenary-other-world-warrior-ch-198/

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Murshid7absi** [comment]
@Sheepux Please update

**Comment by Sheepux** [comment]
Contributors will work on it when they can/want. Dont ping, it wont get things faster.

**Comment by MikeZeDev** [comment]
Duplicate of https://github.com/manga-download/hakuneko/issues/4649
