### ISSUE TITLE
[ReadManga] Connector not working (Website changed readmanga.io)

### ISSUE THREAD

**Issue by atas1234** [manga-download/hakuneko#4651]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Website changed name on readmanga.io. Not search any chapters

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] rev.master@e53409

**Comment by MikeZeDev** [comment]
ReadManga the russian one is readmanga.live, and it works. Seems the "io" redirect to "live" i assume those are the same.

**Comment by atas1234** [comment]
Yeah they changed again. All good now. I'm sorry
