### ISSUE TITLE
[Hunterscan] Website URL changed

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#4652]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No / yes [https://huntersscan.xyz/series/my-neighborhoods-female-teacher/]

**Describe the bug**
The webpage location changed... now it is https://huntersscan.xyz/

**To Reproduce**
1. Name of connecto
Hunterscan.

**HakuNeko (please complete the following information):**
 - Version [latest stable version of 06/05/22]

**Comment by MikeZeDev** [comment]
Can you please change the title to "[Hunterscan] Website URL changed" ?
