### ISSUE TITLE
[Site Request] https://hentai20.com/

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#4654]
**Name of the website**
hentai20

**Website urls (examples below)**
- Site: https://hentai20.com/

- Manga List: 
 https://hentai20.com/
https://hentai20.com/manga-genre/manhwa-hentai-17/
https://hentai20.com/manga-genre/manga-hentai/

- Manga example: https://hentai20.com/manga/my-high-school-bully-50/

- Chapter online viewer example: https://hentai20.com/manga/my-high-school-bully-50/chapter-106/

**Languages**
portuguese

**Comment by Sheepux** [comment]
duplicate #4241
