### ISSUE TITLE
[Site Request] mangatoto

### ISSUE THREAD

**Issue by AshadaDhistar** [manga-download/hakuneko#4655]
**Name of the website**
mangatoto

**Website urls (examples below)**
- Site: https://mangatoto.com/
- Manga List: https://mangatoto.com/browse
- Manga example: https://mangatoto.com/series/82299
- Chapter online viewer example: https://mangatoto.com/chapter/1588655

**Languages**
English
etc

**Comment by MikeZeDev** [comment]
I dont think we need another batoto mirror :/
