### ISSUE TITLE
[KomikCast] Connector not working and a bug occurs

### ISSUE THREAD

**Issue by rizukurizu** [manga-download/hakuneko#4658]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/Done

**Is the website of the connector working properly / are you able to see the manga within your browser**
**Yes**/ i see manga with my browser

**Describe the bug**
when downloading more than one or two chapters the connector suddenly disconnects and has to refresh the Hakuneko page (ctrl + r ), and if you don't restart or refresh the page on hakuneko (f12, then press crtl + r or close and then reopen hakuneko) the connector will always be disconnected even though you have pressed the manga default refresh button (which is next to the connector name), please fix it immediately
![image](https://user-images.githubusercontent.com/79633934/167303851-9474ed1a-a367-47d3-8e2b-8aebef5ba461.png)

I really beg you, because I'm having trouble downloading many chapters at once, because if I've downloaded 1 or 2 chapters, after that the connector always disconnects by itself and takes a long time to close and then reopen the hakuneko

**To Reproduce**
1. Name of connector: **KomikCast**
2. Name of manga (if connector update is working): **all manga in KomikCast connector**
3. Name of chapter (if manga update is working): **all chapter in KomikCast connector**
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/79633934/167303922-9c638f89-bd8f-4381-a12d-f56251a32db6.png)
![image](https://user-images.githubusercontent.com/79633934/167303958-db510cc4-995f-4fcd-8a4f-e24c780cf5df.png)
when downloading more than one or two chapters the connector suddenly disconnects and has to refresh the Hakuneko page (ctrl + r ), and if you don't restart or refresh the page on hakuneko (f12, then press crtl + r or close and then reopen hakuneko) the connector will always be disconnected even though you have pressed the manga default refresh button (which is next to the connector name)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
 
![image](https://user-images.githubusercontent.com/79633934/167304033-974f6d85-5373-4d26-a0eb-00b8c5bfcb90.png)

**Comment by MikeZeDev** [comment]
It would have been useful to see the errors messages in console. Maybe the website has a cooldown on download? 
What about waiting a few minutes and retrying the failing chapters ? 

Unrelated notes : "please fix it immediately" would rather prevent quick updates, devs are not your slaves, please refrain asking like that in the future. Its quite rude :)

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/commit/318423c2ecab7077393caf022d6ea9445bb0e86f#diff-296d90c0d8d86b6679773c07cfc3468ad03a0dba2155f92e1b4eff08d5b04c7d
