### ISSUE TITLE
cannot access manga directory

### ISSUE THREAD

**Issue by suri-z-n** [manga-download/hakuneko#4660]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
warning:cannot access the directory for 'Manga Directory' from "General' setting

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![image](https://user-images.githubusercontent.com/105288515/167623594-32a92512-402b-4747-b452-3ee4e5aac7ea.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
read the message ? Create the folder ?

**Comment by suri-z-n** [comment]
i cannot create the folder. this happened after i update to windows 11

**Comment by suri-z-n** [comment]
it was ok when i use windows 7 but after update to windows 11 this error appeared

**Comment by suri-z-n** [comment]
it was ok when i use windows 7 but after update to windows 11 this error appeared

**Comment by Sheepux** [comment]
Then change the folder in hakuneko's settings to one you can use. This is not a hakuneko issue

**Comment by MikeZeDev** [comment]
If you cannot create the folder inside your Documents folder i suggest you to turn off WIndows Defender "anti ransomware protection" because it often causes access problems within personal folders. Maybe it will fix your problem.

**Comment by Sheepux** [comment]
no feedback since may, closing
