### ISSUE TITLE
[MangaFox] Connector not working

### ISSUE THREAD

**Issue by CHRIS-HENRY-M** [manga-download/hakuneko#4662]
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
Yes

Describe the bug
Error: Page " https://zjcdn.mangafox.me/store/manga/26297/232.0/compressed/o000.jpg?token=999e113e32c68dc8f887285fa5a61f6402619383&ttl=1652284800" returned status: 403 

To Reproduce

    Go to Connectors
    Select "MangaFox"
    Click on any manga from the manga list
    Click on download or show preview button on any chapter

Expected behavior
The manga should be downloaded or previewed without any errors showing up. I am using rev. 6.1.7@cf569b.

Screenshot
![Screenshot1 (2)](https://user-images.githubusercontent.com/57654587/167806695-305c0377-5292-4ed2-9557-384ee7c316ae.png)
s

**Comment by Eltik** [comment]
The issue with this is that MangaFox recently updated their website. Direct links to images are now locked behind a firewall or something. This also happens with ReaperScans, so maybe there's a way to replicate how requests are made for MangaFox...? I go more into depth here on this issue [here](https://github.com/manga-download/hakuneko/issues/4684).

**Comment by firestorms321** [comment]
Might help as a workaround and for debugging but mangafox download still work without issue using rev. master@1aa377
(rev. 6.1.7@cf569b. also dont work for me )

**Comment by MikeZeDev** [comment]
Can be closed i guess, i have no problem. Maybe also #4676

@Sheepux pls <3
