### ISSUE TITLE
[Site Request] Bato.to (battwo.com, comiko.net, mangatoto.com, mto.to, batotoo.com, batotwo.com)

### ISSUE THREAD

**Issue by wrccher** [manga-download/hakuneko#4669]
**Battwo**
Battwo.com

**Website urls**
- Site: https://battwo.com/
- Manga List: https://battwo.com/browse
- Manga example: https://battwo.com/series/93662/honey-i-m-going-on-a-strike
- Chapter online viewer example: https://battwo.com/chapter/1775578

**Languages**
Cambodian, Danish, Filipino, Hindi, Korean, Persian, Russian, Thai, Arabic, Chinese, Dutch, Finnish, Hungarian, Malay, Polish, Serbian, Turkish, Basque, Chinese, English, French, Indonesian, Malaysian, Portuguese, Spanish, Ukranian, German, Italian, Mongolian, Portuguese (BR), Spanish (LA), Vietnamese, Bulgarian, Croatian, Esperanto, Greek, Japanese, Nepali, Portuese (PT), Tamil, Zulu, Burmese, Czech, Hebrew, Kazakh, Norwegian, Romanian, Telugu

**Website relationship*
I've saw many people recommended this website since it's the new batoto. I found that this website gives more language option and has close to none watermark on the pages. If it can be added to the connectors, it would be great.

**Additional details**
it's batoto with new url
![Screenshot 2022-05-14 151832](https://user-images.githubusercontent.com/105538132/168417486-08a4b31a-c1da-4b73-8ad4-281ff4e93369.png)

**Comment by wrccher** [comment]
i have found out that batoto has many mirror sites [https://bato.to/](https://bato.to/ "https://bato.to/") [https://mto.to/](https://mto.to/ "https://mto.to/") [https://batotoo.com/](https://batotoo.com/ "https://batotoo.com/") [https://batotwo.com/](https://batotwo.com/ "https://batotwo.com/") [https://battwo.com/](https://battwo.com/ "https://battwo.com/") [https://comiko.net/](https://comiko.net/ "https://comiko.net/") [https://mangatoto.com/](https://mangatoto.com/ "https://mangatoto.com/")

i know that there's the Batoto (by AnyACG), but it usually show this error
![batoto error](https://user-images.githubusercontent.com/105538132/168420780-884cbe42-d94a-430e-91bf-041959b4f171.png)

**Comment by hujahraina-cyber** [comment]
Bl
