### ISSUE TITLE
Can't download anymore from japscan

### ISSUE THREAD

**Issue by benoittachet** [manga-download/hakuneko#467]
Hello,

It seems that Japscan changed its path to the mangas, all we get from Hakuneko now is 404 errors.
I've seen that it looks at path https://japscan.co/lecture-en-ligne/[manga name], but now, the correct path is https://www.japscan.co/manga/[manga name]/

**Comment by 27136773** [comment]
Cannot be reproduced, everything works as expected on my end.
Make sure you have HakuNeko 5.0.8 or above.
You may synchronize your manga list, maybe the links in your local list are outdated.

**Comment by benoittachet** [comment]
I have downloaded the latest version just before sending this issue. I didn't try to update the database, thought it was only from online, and it works now. Thanks.
