### ISSUE TITLE
[teamx.fun] Connector not working

### ISSUE THREAD

**Issue by majdtqe** [manga-download/hakuneko#4671]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
team x connector not working please fix him

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Bmswad1** [comment]
New domain: teamx.fun

**Comment by Bmswad1** [comment]
New domain: teamx.fun

**Comment by Bmswad1** [comment]
New domain: teamx.fun

**Comment by majdtqe** [comment]
I can change team x domin from setting but it doesn't work because they are
update the website
In the past it was wordpress
Now i dont what is it
