### ISSUE TITLE
[MangaFox] Connector not working

### ISSUE THREAD

**Issue by pammseyy** [manga-download/hakuneko#4676]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I want to download from MangaFox, I am able to open and read the manga in my browser, but I can't open in on HakuNeko and download always fail.

**To Reproduce**

**Expected behavior**
Since I can read it on my browser, I expected it to be able to be downloaded in HakuNeko

**Screenshots**
![Screen Shot 2022-05-17 at 19 15 20](https://user-images.githubusercontent.com/78685704/168809053-8da09fec-4e4f-444c-bce7-a25eab601842.png)
![Screen Shot 2022-05-17 at 19 15 09](https://user-images.githubusercontent.com/78685704/168809068-5e040658-9d1a-433d-977e-6cfdcd4eca34.png)
![Screen Shot 2022-05-17 at 19 14 57](https://user-images.githubusercontent.com/78685704/168809071-9cb6db70-8ecb-43df-84fa-0e13e3d832c8.png)

**Context (please complete the following information):**
 - OS: ios
 - HakuNeko Version 6.17

**Additional context**

**Comment by Eltik** [comment]
Same issue as mentioned [here](https://github.com/manga-download/hakuneko/issues/4684). MangaFox updated their website. Hopefully we'll get a fix soon. Although MangaFox might have to be removed entirely since this is a security issue.

**Comment by dodieboy** [comment]
Fixed on #4594, pls use nightly version to get the update

**Comment by MikeZeDev** [comment]
Can be closed i guess, i have no problem. Maybe also https://github.com/manga-download/hakuneko/issues/4662

**Comment by MikeZeDev** [comment]
@Sheepux pls <3
