### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by ElijahS9** [manga-download/hakuneko#4677]
**AnzManga**

**(https://www.anzmangashd.com/)**
- Site: https://www.anzmangashd.com/
- Manga List: https://www.anzmangashd.com/manga-list
- Manga example: https://www.anzmangashd.com/manga/mashle
- Chapter online viewer example: https://www.anzmangashd.com/manga/mashle/90/1

**Languages**
Spanish

**Comment by MikeZeDev** [comment]
Added to Haruneko https://github.com/manga-download/haruneko/pull/344
