### ISSUE TITLE
[GMMANGA] Connector not working

### ISSUE THREAD

**Issue by faris-lofi** [manga-download/hakuneko#4678]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector / gmmanga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4.  Failed to update manga list for GManga - Failed to receive content from "https://gmanga.me/api/mangas/search" (status: 400)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

 - Version [6.17]
![2022-05-18_103034](https://user-images.githubusercontent.com/94230658/169118343-b02a6e5d-7e8a-4b7b-9285-9cb3359fab94.png)

**Comment by MikeZeDev** [comment]
Seems to work on nightly. Can be closed?
