### ISSUE TITLE
[Site Request] BOOK☆WALKER

### ISSUE THREAD

**Issue by BBLOVERl** [manga-download/hakuneko#4680]
**Name of the website**
BOOK☆WALKER Global Store

**Website urls (examples below)**
- Site: https://global.bookwalker.jp/
- Manga List: https://global.bookwalker.jp/categories/2/manga/
- Manga example: https://global.bookwalker.jp/de5b6b8d5c-c13f-4b54-ac0f-593ed5fe3983/im-quitting-heroing%E3%80%80chapter-1-my-next-gig-is-at-the-demon-queens-castle/
- Chapter online viewer example: https://viewer.bookwalker.jp/03/19/viewer.html?cid=5b6b8d5c-c13f-4b54-ac0f-593ed5fe3983&cty=1

**Languages**
English

**Website relationship**
Alternative domain, copy of book walker app

**Additional details**
Just like viz you must purchase the mangas before downloading, so add where you can log into your account. Hope you consider!

**Comment by MikeZeDev** [comment]
A bit late maybe. I am afraid my code is working on free content and there is a problem with paid content, and its not ez to fix.
Eventually this could be handled properly in Haruneko

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/809
