### ISSUE TITLE
[Viz] Log in Difficulties with 

### ISSUE THREAD

**Issue by BBLOVERl** [manga-download/hakuneko#4681]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes.

**Describe the bug**
Whenever I go into viz (the website on app) it shows all the manga, like how it always does. But when I go to log into my account on the connector, it won't let me login. At first I thought it was my account so I pulled up the site on a different tab and it logged me in perfectly fine. I sat here waiting 3 hours and still nothing. 

**To Reproduce**

**Expected behavior**
I expected it to show me all the manga I bought but inside it didn't show anything. 

**Screenshots**
I did my best screenshot wise;
![2
![2022-05-18 (1)](https://user-images.githubusercontent.com/105815870/169128356-5adadc40-54c9-4744-97cf-641e52da8d94.png)
022-05-18](https://user-images.githubusercontent.com/105815870/169128226-e8f600ed-e383-4965-8787-f457ada6bbed.png)
![Uploading 2022-05-18 (2).png…]()
![2022-05-18 (3)](https://user-images.githubusercontent.com/105815870/169128640-1e403a58-e3fb-41a9-b85f-3190c31ebcd1.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows11]
 - HakuNeko Version [e.g. 6.17]

**Additional context**
It's been like this for the last few days

**Comment by michaeljohnm** [comment]
Hi, having the same issue as well, for more context, here's what the Developer Console is telling us when we attempt to login:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/30578980/169630646-3c13af04-22cc-45d5-b786-71770e1047b5.png">

**Comment by Eltik** [comment]
Most likely a site change. `$(...).serialize(...)` leads me to believe this is an issue with Cheerio not loading the HTML properly. Or a DOM issue.

**Comment by north93** [comment]
This is still happening to me too.
![image](https://user-images.githubusercontent.com/25226796/172921417-c0620da0-1d8c-405c-aa87-370e3b0af948.png)
