### ISSUE TITLE
[Site Request] mangaalarab

### ISSUE THREAD

**Issue by faris-lofi** [manga-download/hakuneko#4682]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://mangaalarab.com/
- Manga List: https://mangaalarab.com/manga
- Manga example: https://mangaalarab.com/manga/%D8%B3%D9%88%D9%84%D9%88-%D9%84%D9%8A%D9%81%D9%84%D9%8A%D9%86%D8%AC
- Chapter online viewer example: https://mangaalarab.com/manga/%D8%B3%D9%88%D9%84%D9%88-%D9%84%D9%8A%D9%81%D9%84%D9%8A%D9%86%D8%AC/chapters/0

**Languages**
Arabic

**Website relationship*
Like mangalink but better than him

**Additional details**
I hope to add the site, I will be very thankful to you

**Comment by MikeZeDev** [comment]
Dead website?
