### ISSUE TITLE
[Sushi Scan] Connector not working

### ISSUE THREAD

**Issue by berbasan** [manga-download/hakuneko#4683]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's impossible to read or download any chapter from the Sushi Scan website

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sakuships** [comment]
for me it does work, but it's only showing and downloading the first page.

**Comment by MikeZeDev** [comment]
Cant reproduce. Updated manga list, tried a few manga, i see every images. Can you name a manga causing problem?

**Comment by MikeZeDev** [comment]
Working, can be closed @Sheepux pls <3
