### ISSUE TITLE
[MangaFox] Connector not working

### ISSUE THREAD

**Issue by Eltik** [manga-download/hakuneko#4684]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloading manga from MangaFox seems to not work. I downloaded the source code for Hakuneko and re-coded the process in NodeJS and noticed that the website now denies access when fetching files externally (see images below). Unfortunately, I can't seem to find anything in the website source that sends request headers besides `isAdmin` and `isLoggedIn`. I doubt that would change anything, however. Also, the chapter url's on the website end in `.htm`, but when fetching the page links, the URL ends in `.html`, but based on what I've inspected that doesn't seem to be the main cause of the issue.

**To Reproduce**
1. Name of connector: MangaFox
2. Name of manga: Tenseishichatta yo (iya gomen) [random manga I found, shouldn't work with any however]
3. Name of chapter (if manga update is working): N/A
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): 

```
DownloadJob.mjs:141 GET https://zjcdn.mangafox.me/store/manga/19969/01-001.0/compressed/k035.jpg?token=3e687f964b5af98ccd50f9b8b8f404c82f5bef83&ttl=1653062400 403
```

**Screenshots**
![image](https://user-images.githubusercontent.com/76538547/169376037-c3c3d42d-59f1-484b-8d8f-7659e67feb11.png)
![image](https://user-images.githubusercontent.com/76538547/169376474-5af19139-01ea-4075-9622-dea87552d9f0.png)

**HakuNeko (please complete the following information):**
 - Version 6.17.

**Comment by Sheepux** [comment]
duplicate #4684
