### ISSUE TITLE
[Site Request] LELMANGA

### ISSUE THREAD

**Issue by MrNelio** [manga-download/hakuneko#4685]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://www.lelmanga.com
- Manga List: https://www.lelmanga.com/manga
- Manga example: https://www.lelmanga.com/manga/wind-breaker
- Chapter online viewer example: https://www.lelmanga.com/wind-breaker-1

**Languages**
French

**Website relationship*
N/A : maining website

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by ImNelio** [comment]
Hello,

I can't find lelmanga on the connector
