### ISSUE TITLE
[bato.to] Connector not working

### ISSUE THREAD

**Issue by BereBereBeer** [manga-download/hakuneko#4686]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
not sure if it's a bug or was intended, but it disappeared from the list of websites. the bookmarks I had show up "batoto (unavailable)" under the manga name.
I get that some [changes](https://github.com/manga-download/hakuneko/commit/688f83c20c1035144ba5866e1d6c83741b4c1884#diff-9a8699912fb270ec2d8b2e5201bafc0e6fc8e40d45a3581de3948a5d4cd85cb4) have been made, but I don't understand what I'm supposed to do or what it means at all

**To Reproduce**
1. Name of connector Batoto (by AnyACG) https://bato.to/

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by RedwanRabbiHoque** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/48180076/170677517-b1638669-9408-4aa6-a8df-81f2d7d3f7e8.jpg)

Hello, I kept getting issues when I tried to load the available chapter lists in 'Bato.to'
The image at the top shows that it won't load whenever I try to update the list.

**Comment by Holydragoness** [comment]
This is my problem
![image](https://user-images.githubusercontent.com/71577019/170900322-6d9e9fd8-886f-4ad6-944a-d8d70b1b6bcd.png)
 
This is the manga: https://bato.to/series/80637

**Comment by Tattoo20** [comment]
Same problem....my bookmarks from bato.to don't work anymore and if i want to paste a new series nothing works.... that's really frustating as there are some webtoons scans only on this site

**Comment by thundrglaive** [comment]
Hello, just wanted to chip in that i'm running into the same issue. Since yesterday Batoto (by AnyACG) does not seem to work at all anymore. 

Connector: Batoto (by AnyACG)
ReferenceError: Server is not defined.

If there is anything i can help with to provide more information, let me know. :)
Thank you.

**Comment by Xitain** [comment]
RefrenceError: CryptoJS is not defined

![Untitled](https://user-images.githubusercontent.com/13646929/171757673-a50cd31c-27a2-4fa9-be1b-dfd6917442fd.png)

**Comment by DeniablePlausibility** [comment]
ReferenceError:  server is not defined (sounds like a node.js error?)

![crop](https://user-images.githubusercontent.com/107167254/172765789-3f172155-0fdb-4e09-abc8-d2648f31ae0f.png)

**Comment by buratsy** [comment]
> ReferenceError: server is not defined (sounds like a node.js error?)
> 
> ![crop](https://user-images.githubusercontent.com/107167254/172765789-3f172155-0fdb-4e09-abc8-d2648f31ae0f.png)

I'm getting the same error in the stable version. This is the error I get when I try to download chapters but I can still bookmark mangas from bato.to. In the nightly version, I can't bookmark new mangas at all and my existing bookmarks from bato.to just say "Offline".
