### ISSUE TITLE
[Bug] .exe stuck on "Virus Downloading"

### ISSUE THREAD

**Issue by henry-cotton** [manga-download/hakuneko#4688]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Trying to get the Windows x64 exe to run, it only brings up a window that shows a looping .gif claiming to be installing a virus

**To Reproduce**
1. Download setup .exe from downloads page.
2. Run setup, installing HakuNeki program
3. Run hakuneko.exe

**Expected behavior**
I expected to see the normal downloads UI, as shown in the README

**Screenshots**
![exeissue](https://user-images.githubusercontent.com/72087779/169565687-ab2d067e-6fff-47ae-a106-31433e120063.png)

**Context (please complete the following information):**
 - OS: Windows 10, version 21H2
 - HakuNeko Version 6.1.7

**Comment by 27136773** [comment]
This is by intention, ask in discord for solution
