### ISSUE TITLE
[Site Request] 漫画猫

### ISSUE THREAD

**Issue by wezsew** [manga-download/hakuneko#4694]
**Name of the website**
漫画猫

**Website urls (examples below)**
- Site: https://www.maofly.com/
- Manga List: https://www.maofly.com/list.html
- Manga example: https://www.maofly.com/manga/25819.html
- Chapter online viewer example: https://www.maofly.com/manga/25819/500456.html

**Languages**
Chinese

**Comment by MikeZeDev** [comment]
Similar to ManhuaDB

**Comment by MikeZeDev** [comment]
dead
