### ISSUE TITLE
[MangarawClub] Url change https://mcreader.net/

### ISSUE THREAD

**Issue by Reiva24** [manga-download/hakuneko#4695]
**Name of the website**
Mc reader o Manga raw club.

**Website urls (examples below)**
- Site: https://mcreader.net/
- Manga List: https://www.manga-raw.club/listt/manga/

**Language**
English

**Comment by MikeZeDev** [comment]
MangarawClub connector changed its url for this.one, and now its www.mreader.co. I just need to update it :)
