### ISSUE TITLE
[Site Request] TCB Scans

### ISSUE THREAD

**Issue by PheaDiel** [manga-download/hakuneko#4697]
**Name of the website**
TCB Scans

- Site: https: https://onepiecechapters.com/
- Manga List: https://onepiecechapters.com/projects
- Manga example: https://onepiecechapters.com/mangas/5/one-piece
- Chapter online viewer example: https://onepiecechapters.com/chapters/2293/one-piece-chapter-1050

**Languages**
-english

**Comment by Murshid7absi** [comment]
TCB Scans have been added already!
https://github.com/manga-download/hakuneko/commit/dd59107eb47e5c0b6a2a4211e231def4cd6ebde8

![Screenshot (28)](https://user-images.githubusercontent.com/95138799/170675379-9ea7f2af-b89b-4924-b9ba-86027214bde4.png)

**Comment by PheaDiel** [comment]
Then help, it's not showing whenever I look for it.
![image](https://user-images.githubusercontent.com/93088592/170816951-cc6649ad-2088-43ea-a54a-b8b17287d88b.png)
![image](https://user-images.githubusercontent.com/93088592/170816972-37e74995-559f-40fd-b0e9-e344f481fce2.png)

**Comment by korason7117** [comment]
You need to use the **Nightly Version**, or else wait for it to be merged into the stable branch

**Comment by PheaDiel** [comment]
oh thanks!
