### ISSUE TITLE
[Bilibili ] Unlocked Chapters through wait-time cannot be downloaded

### ISSUE THREAD

**Issue by Lyreen** [manga-download/hakuneko#4698]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Bilibili comics time-gated chapters that have been unlocked remained un-downloadable.

**To Reproduce**
Logged in as usual through the web-reader. Full Chapter can be viewed from web-reader, going back to hakuneko, it's locked.

**Expected behavior**
Should be able to download if chapter is already unlocked on reader, regardless of whether it's paid or time-unlocked.

![image](https://user-images.githubusercontent.com/96034443/170659653-ca48ef9e-b85e-4132-b5ad-2c54161aa00b.png)

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version 6.1.7 @cf569b

**Comment by Darkmaster006** [comment]
Agreed, this cannot be done even though the chapters can be seen. It may be that Hakuneko is grabbing from the app or mobile website? Since I can see them from the webpage.

**Comment by watatomo** [comment]
Same issue here. Looking at devtools, it says that I need to unlock the chapter. However, I already logged into my account and paid for all of the chapters.

![image](https://user-images.githubusercontent.com/23179278/209040872-3f4b4727-0cbb-4e8e-bcf7-4fa8c2c7070b.png)

**Comment by MikeZeDev** [comment]
Can someone check with nightly if its always the case?
