### ISSUE TITLE
Multiple chapter downloads at once (Simultaneously) [Feature] 

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#4699]
**Is your feature request related to a problem? Please describe.**
Sometimes/ when I download a new manga that has 200+ or 300+ chapters from 1 connector, I get tired of waiting as I have a fast download speed.

**Describe the solution you'd like**
an option in the settings to choose how many multiple chapters download simultaneously ( like 3, 5, or 7 ..., etc. chapters download at once) for people with fast download speed. 

You can see this feature in the uTorrent app below.
![Screenshot (27)](https://user-images.githubusercontent.com/95138799/170674514-29e099b9-ac8a-4e86-bf33-79c41819d915.png)

THANK YOU!!

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Hakuneko's community policy is not to overload the targeted website and therefore will not handle parallel downloads for the same connector. If the website is slow at downloading a single chapter, it will stay slow.
