### ISSUE TITLE
App crashes on download

### ISSUE THREAD

**Issue by Yutsano0** [manga-download/hakuneko#4704]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When i click the download button then hakuneko will automatically close (crash). 
I think its the website (9anime) is the problem. 
I can download manhwas and mangas on other connectors but 9anime makes my hakuneko crash.

**To Reproduce**
1. Go to '9anime'
2. Click on 'download'
4. See error 'CRASH'

**Expected behavior**
i want it to not crash and download the thingy. I even reinstalled hakuneko for 3 times now and still crash 

**Screenshots**
heres a video sorry if the quality is low. github says i can only upload 10 mb
https://user-images.githubusercontent.com/102207694/170908566-929c4be5-ee06-4a07-9f9c-207fa7d23267.mp4

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version 6.17

**Additional context**
Please help me asap im really itching to watch some animes bec ive been reading alot of manhwas

**Comment by Sheepux** [comment]
Read the troubleshooting guide as requested, and fill the form: it's here for reasons.
Try to reinstall

**Comment by Yutsano0** [comment]
> Read the troubleshooting guide as requested, and fill the form: it's here for reasons. Try to reinstall

i filled the form and i uploaded a video about the crash

**Comment by Yutsano0** [comment]
> Read the troubleshooting guide as requested, and fill the form: it's here for reasons. Try to reinstall

i reinstalled it 3 times still doesn't work

**Comment by Sheepux** [comment]
can you try hakuneko nightly ?

**Comment by Yutsano0** [comment]
> can you try hakuneko nightly ?

i can click the download button and it doesn't crash but can't download it says "Error Failed to Load (website) within the given time out of 30 seconds
![Screenshot (248)](https://user-images.githubusercontent.com/102207694/171364795-a1a74408-d5b8-42c1-be68-9d3b4573717a.png)

**Comment by Sheepux** [comment]
Glad it worked for the crash. I will close this issue related to the crash.
For the 9anime connector failure, there are reported issues already. Yes 9anime has quite some broken things.
https://github.com/manga-download/hakuneko/issues?q=is%3Aissue+is%3Aopen+9anime
