### ISSUE TITLE
[Site Request] Mangareader.to

### ISSUE THREAD

**Issue by DrunkCommunist** [manga-download/hakuneko#4705]
**Name of the website**
Mangareader.to

**Website urls (examples below)**
- Site: https://mangareader.to
- Manga List: https://mangareader.to/az-list
- Manga example: https://mangareader.to/yakumo-san-wa-edzuke-ga-shitai-2945?ref=search
- Chapter online viewer example: https://mangareader.to/read/yakumo-san-wa-edzuke-ga-shitai-2945/en/volume-1

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
already implemented, try the progbram first ....
