### ISSUE TITLE
[Sushi-scan] Connector not working

### ISSUE THREAD

**Issue by Shirozaond** [manga-download/hakuneko#4711]
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
It is now impossible to download or even watch the chapters or tome.
The app only shows me the front cover.

To Reproduce

sushi-scan
Screenshots
Example
![160279919-3ba92398-27f5-4b23-94bc-c49b53d882be](https://user-images.githubusercontent.com/106657359/171400637-d5204e43-e36f-4d0d-9f0d-4ed486ecba23.PNG)

**Comment by berbasan** [comment]
Hey,

It's impossible to download or watch the chapters...

Thank you !

**Comment by starring94** [comment]
Use nightly, it should work.
