### ISSUE TITLE
[Daum] Connector not working

### ISSUE THREAD

**Issue by themysciraa** [manga-download/hakuneko#4712]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly /
No

are you able to see the manga within your browser**
Yes

**Describe the bug**
webtoon.daum.net is redirected to webtoon.kakao.com when viewing through browser.
Is it possible to change the connector to tap on 'webtoon.kakao.com' instead?

**To Reproduce**
1. Daum
2. 
3. 
4. Failed to update manga list for Daum 웹툰
 Failed to receive content from "http://webtoon.daum.net/data/pc/webtoon/list_serialized/mon" (status: 403) - 

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Its redirecting to https://webtoon.kakao.com/. Website is dead.
