### ISSUE TITLE
[Site Request] https://hajime-noippo.com/

### ISSUE THREAD

**Issue by term88nator** [manga-download/hakuneko#4719]
**Name of the website**
Hajime No Ippo Manga Online

**Website urls**
- Site: https://hajime-noippo.com/
- Manga example: https://hajime-noippo.com/manga/hajime-no-ippo-chapter-556-reverberating-victory/

**Languages**
English

**Comment by MikeZeDev** [comment]
I dont think devs will add a single manga website.
