### ISSUE TITLE
[Feature] Is it possible to download monthly paid member chapters from to-corona-ex.com?

### ISSUE THREAD

**Issue by lasthm** [manga-download/hakuneko#4720]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I hope it possible to download monthly paid member chapters from to-corona-ex.com.

**Describe alternatives you've considered**
The connector of To-Corona-Ex is work, but it can't download monthly paid member chapters.

**Context (please complete the following information):**
 - v6.1.7

**Additional context**
Connector: To-Corona-Ex

**Comment by Sheepux** [comment]
did you try to log in with manual website interraction

**Comment by lasthm** [comment]
> did you try to log in with manual website interraction

Yes, I tried. But it can't get list with monthly paid member chapters.

**Comment by lasthm** [comment]
The url of list with subscription chapters is like:
https://api.to-corona-ex.com/episodes?comic_id=20000000055111&episode_status=free_viewing%2Conly_for_subscription&order=asc&sort=episode_order

But the connector seem to use:
https://api.to-corona-ex.com/episodes?comic_id=20000000055111&episode_status=free_viewing&order=asc&sort=episode_order

I don't how to revise the connector to make it possible to get subscription chapters

**Comment by MikeZeDev** [comment]
It seems the connector is able to handle subscription (cant test tho).
```
        if (hasSubscription) {
            extraparameters += "&episode_status=free_viewing%2Conly_for_subscription";
        }
```

That said, it need a little fix (need the api key)

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/commit/9f21ea3b236651539d4221530255bed024b6094f
