### ISSUE TITLE
[HELP].bin from ManhuaScan and cannot connect other sites.

### ISSUE THREAD

**Issue by Nyangomaru** [manga-download/hakuneko#4724]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I have multiple problems...
1) Since yesterday I only get .bin files at manhuascan.io, before I had no problems downloading there..
I think the it changed from .com to .io but I autodirect to the new and the mangalist updates normal.

2) When I want to load the Mangalist from Bato.to I get "Failed to update manga list for... Cannot read property "text" of undefined"
One time I could update the manga list but the chapters are empty.

**To Reproduce**
1. Go to 'Manga List "ManhuaScan'
2. Click on 'the Manga I have chosen and download the chapters'
3. go to the folder

**Expected behavior**
pat
**Screenshots**

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 6.17

**Additional context**

**Comment by Nyangomaru** [comment]
Connector.mjs:579 TypeError: Cannot read property 'text' of undefined
    at Batoto._getMangas (AnyACG.mjs:43)
    at async Batoto._getMangaList (Connector.mjs:576) 
Batoto {id: "batoto", label: "Batoto (by AnyACG)", tags: Array(2), isLocked: false, initialized: true, …}

What do I have to do to fix that?

**Comment by Sheepux** [comment]
bin files are usually related to bad internet connexion and/or website not sending adequate headers on image.
Can you try to rename the images to jpeg and see if they work fine or are corrupted ?

For batoto, it's a separate issue: https://github.com/manga-download/hakuneko/issues/4686

**Comment by Sheepux** [comment]
manhuascan also has an already existing issue #4628 , will close to clean up duplicates:
