### ISSUE TITLE
[CocoManhua] Connector not working

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#4725]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Cannot Download and when klik preview error base64 is not identified

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/77179150/172038616-a5f362e7-c5a5-4d74-8220-099e2112ee75.JPG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/4558
https://github.com/manga-download/hakuneko/issues/4802
