### ISSUE TITLE
[Site Request] Muitomanga

### ISSUE THREAD

**Issue by mynamex1** [manga-download/hakuneko#4735]
**Name of the website**    
     Muito Mangá

**Website urls (examples below)**
- Site: https://muitomanga.com/
- Manga List: https://muitomanga.com/lista-de-mangas
- Manga example: https://muitomanga.com/manga/the-tyrants-beloved-doll-novel
- Chapter online viewer example: https://muitomanga.com/ler/the-tyrants-beloved-doll-novel/capitulo-1

**Languages**
portuguese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Can you please rename the issue properly with the website name? :)

**Comment by MikeZeDev** [comment]
Geoblocked.

**Comment by MikeZeDev** [comment]
dead
