### ISSUE TITLE
[ScanTrad] Connector not working

### ISSUE THREAD

**Issue by Fred-Vatin** [manga-download/hakuneko#4737]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

# Describe the bug
Until recently when selecting a manga in the list (2 weeks ago ?), its chapters were listed. For instance [One Punch-Man](https://scantrad.net/one-punch-man). Now, its broken. List of chapters for all mangas is empty. All errors are 403 type. See screenshot below.

# To Reproduce
1. ScanTrad
2. All mangas (if connector update is working)
3. Chapters list is empty
4. Error 403 in console when clicking any mangas

# Screenshots

Error when clicking manga
![image](https://user-images.githubusercontent.com/22337329/172981767-67c7e791-f970-4aa2-988a-fa0567e6a32e.png)

Error when clicking the synchronize (update) button
![image](https://user-images.githubusercontent.com/22337329/172982767-51333d7c-01a7-474d-84c7-e87d34149deb.png)

# HakuNeko (please complete the following information):
 - Version 6.1.7 rev cf569b
 - Windows 10 21H1

**Comment by MikeZeDev** [comment]
Cant reproduce. I updated the list successfully then i was able to read One punch man (chapter 164 was no more).

**Comment by Fred-Vatin** [comment]
Yes. It seems solved now.

**Comment by MikeZeDev** [comment]
Can be closed @Sheepux pls
