### ISSUE TITLE
[Site Request] Manga Scan

### ISSUE THREAD

**Issue by jspkoim** [manga-download/hakuneko#4740]
**Name of the website**
Manga scan

**Website urls (examples below)**
- Site: https://mangascan.cc
- Manga List: https://mangascan.cc/index.php/manga-list
- Manga example: https://mangascan.cc/index.php/manga/parasite
- Chapter online viewer example: https://mangascan.cc/index.php/manga/parasite/1

**Languages**
French

**Comment by MikeZeDev** [comment]
Takes pictures from ScansMangas.me, already supported.
