### ISSUE TITLE
[Batoto] Connector not working

### ISSUE THREAD

**Issue by SakuraPSP** [manga-download/hakuneko#4744]
I tried downloading from manga website "Bato.to" using Hakuneko, but continue to result in "download failed" with all chapters. I attempted other manga titles ("This Villainess Wants a Divorce","Ani-tachi no Aisarete, Korosarete","Akuyaku Reijou wa Ichizuni Dekiaisarete") and have seen the same result. 
The website is currently working on my browser. Please assist with problem.
![16550685795892579517654967425067](https://user-images.githubusercontent.com/107370466/173253921-7e4279c1-b29c-4b74-861c-65f5f79fce2b.jpg)

*Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4686
