### ISSUE TITLE
[Animepahe] no episodes are showing on all animes.

### ISSUE THREAD

**Issue by Wonderweiss21** [manga-download/hakuneko#4745]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Chapters/episodes are not showing on any anime.

**To Reproduce**
1. Go to animepahe directory
2. Click on any anime titles
3. No chapters/episodes are showing

**Expected behavior**
For episodes to show up.

**Screenshots**
![2022-06-13 (1)](https://user-images.githubusercontent.com/107377549/173266866-2b7b1123-f12c-4b3e-9390-b430f2052d79.png)
![2022-06-13 (2)](https://user-images.githubusercontent.com/107377549/173266920-3ff5f35e-b23b-447e-95b3-a3453bec1c0d.png)
![2022-06-13 (3)](https://user-images.githubusercontent.com/107377549/173266944-6367b9eb-33a7-40a1-9037-23d18888969a.png)
![2022-06-13](https://user-images.githubusercontent.com/107377549/173266956-5c4a99fd-15bb-4883-bbb0-74b07121220b.png)

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version 6.17 (64-bit)

**Additional context**
 - reinstalled hakuneko
 - animepahe.com is online and active.

**Comment by HeyEyh** [comment]
i have the same issue, using a proxy doesnt work
