### ISSUE TITLE
[Site Request] comicastle

### ISSUE THREAD

**Issue by Alpha0Raptor** [manga-download/hakuneko#4747]
**Name of the website**
Comicastle

**Website urls (examples below)**
- Site: https:https://comicastle.org/home
- Manga List: https://comicastle.org/library/postdate/desc
- Manga example: https://comicastle.org/home/detail/3478/grimm-spotlight-zodiac
- Chapter online viewer example: https://comicastle.org/read/pbp/28681/3478/grimm-spotlight-zodiac/1

**Languages**
-English

**Website relationship*
No alternate domain (eg : "alternative domain, copy of ...").

**Additional details**
Comicastle is a website which has many comics (eg. Marvel,DC,etc) and has a nice library

**Comment by MikeZeDev** [comment]
dead
