### ISSUE TITLE
[Batoscan] Connector not working

### ISSUE THREAD

**Issue by Deltapl7s** [manga-download/hakuneko#4750]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
When connected to the connector the names of the mangas not showing and when refreshing it still the same after few times and even manga0/ showing in the left down corner.

**Comment by azariie** [comment]
I am experiencing a similar issue. The manga list loads fine, but it's impossible to download any file. The error I get when trying to visualize the previews is "server not defined". Maybe it would be best to switch to Bato more stable mirror mangatoto.com?

**Comment by MikeZeDev** [comment]
Dead website? Its an ad page blocked by ublock origin right now?.
