### ISSUE TITLE
[Site Request] anime-sama

### ISSUE THREAD

**Issue by Cheng145** [manga-download/hakuneko#4751]
**Anime Sama**

URL : https://anime-sama.fr/
Mangas List : https://anime-sama.fr/scan/
Mangas Exemple : https://anime-sama.fr/scan/all-you-need-is-kill/
-Chapter online viewer example : https://s44.anime-sama.org/s1/scans/All%20You%20Need%20Is%20Kill/1/1.jpg

**Languages**
French

**Comment by MikeZeDev** [comment]
Site is too broken (very slow, many errors 404 and 522, got infinite redirection on bleach in HN) and inconsistent (some "manga pages" are just pages with links to other manga pages not listed on manga list) to be added IMHO.
