### ISSUE TITLE
[Feature] double page mode for the inbuilt reader

### ISSUE THREAD

**Issue by HeyEyh** [manga-download/hakuneko#4752]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A world in which the inbuilt reader of HakuNeko has a two page view

**Describe alternatives you've considered**
using an external reader

**Context (please complete the following information):**
 - HakuNeko Version [e.g. 6.17]

**Additional context**
no

**Comment by Sheepux** [comment]
done in haruneko (hakuneko v10 WIP)

**Comment by heelee912** [comment]
How does this work? There is no option for a double-page mode.

**Comment by heelee912** [comment]
How does this work? There is no option for a double-page mode.
