### ISSUE TITLE
[Site Request] Mangascantrad

### ISSUE THREAD

**Issue by Ozhael** [manga-download/hakuneko#4753]
**Name of the website**
Mangascantrad

- Site: https://www.mangascantrad.fr
- Manga List: https://www.mangascantrad.fr/manga/
- Manga example: https://www.mangascantrad.fr/manga/tokyo-revengers/
- Chapter online viewer example: https://www.mangascantrad.fr/manga/tokyo-revengers/chapitre-256/

**Languages**
French

**Website relationship**
no alternative domain

**Additional details**
mangascantrad has a good library and some mangas that i cant find on other website

**Comment by MikeZeDev** [comment]
https://github.com/MikeZeDev/hakuneko/commit/dc43a08141ffb2d2489d55150698d6146b5b9330

**Comment by MikeZeDev** [comment]
Website is dead :/

**Comment by MikeZeDev** [comment]
dead
