### ISSUE TITLE
[Site Request] fbsquadz

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#4755]
Name of the website
Fbsquadz

Website urls (examples below)

Site: https://fbsquadz.com/
Manga List:https://fbsquadz.com/manga/
Manga example: https://fbsquadz.com/manga/dark-fall/
Chapter online viewer example: https://fbsquadz.com/manga/dark-fall/1-temporada/capitulo-2/

Languages
Portuguese

Additional details
MadaraWordPress

**Comment by MikeZeDev** [comment]
IS that https://fbsquads.com/ ?

**Comment by mangareader4** [comment]
No, still works. Just changed the domain to

Fbsquads.com

Em dom., 13 de nov. de 2022 1:44 PM, MikeZeDev ***@***.***>
escreveu:

**Comment by mangareader4** [comment]
> IS that https://fbsquads.com/ ?

yes!

**Comment by MikeZeDev** [comment]
Doesnt answer today.
