### ISSUE TITLE
[Alpha Scans] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#4756]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No - within the HakuNeko browser
Yes - for desktop browser

**Describe the bug**
No works are listing.

**To Reproduce**
For some reason the site won't load within HakuNeko but will load for my desktop and phone browsers.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Site loads fine.
Demonic emperor chapter 286 loads (randomly choosen)
I got a no content make sure its accessible message on [lightnovel] star instructor... but it can be normal i guess.

I use nightly.
