### ISSUE TITLE
[Flame Scans] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#4757]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
No works are listing. And when I try to bring up the site within the HakuNeko browser, the "Just a moment.." screen keeps just refreshing in a neverending cycle.

**To Reproduce**

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cant reproduce. Tried a random manga, updating list, it works. Nightly. No 'Just a moment" in HN browser that would suggest Cloudflare.
