### ISSUE TITLE
[Bato.to] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#4758]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The works and their chapters are listing, but you try to preview the images, a "server is not defined" box pops up and no downloading is possible.

**To Reproduce**

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4686
