### ISSUE TITLE
Crunchyroll manga - Failed to fetch

### ISSUE THREAD

**Issue by cyatek** [manga-download/hakuneko#476]
Windows 7
5.0.8
rev.27f24e
Stock settings
[error log
](https://i.gyazo.com/9936d3fc233f1fa796afd26922c2844d.png)

Happens on a single chapter (Silver Nina ch.105) while others download fine.
Picture viewing is also working fine, it just doesn't want to download.
![69977b77bddf756dead71b1dcb956d23](https://user-images.githubusercontent.com/19691333/66089727-67b0ff80-e578-11e9-98e8-6f74f9f6dcfe.png)

**Comment by 27136773** [comment]
The last page of [this chapter](https://www.crunchyroll.com/comics_read/manga?volume_id=607&chapter_num=105.00) is broken on the CrunchyRoll server, there is nothing that can be done in HakuNeko. You may contact the support of CrunchyRoll...

----

![image](https://user-images.githubusercontent.com/27136773/66168607-f6d41b00-e63d-11e9-9c76-4d15b5bb2034.png)

**Comment by cyatek** [comment]
Hm you're right, but the chapter is there in it's entirety, that last page shouldn't even exist. Would there be some way to force the download of the pages that do work?

**Comment by 27136773** [comment]
No there is no such mechanism implemented.
You can open developer tools switch to network tab and save the images one by one...

![image](https://user-images.githubusercontent.com/27136773/66169662-744d5a80-e641-11e9-9faf-e01a14f69830.png)

**Comment by cyatek** [comment]
That'll do it lol, thanks for the help!

**Comment by annieonmymay** [comment]
Hi, I think I'm having the exact same issue, but I can't figure out how to open developer tools for HakuNeko? When I open it in Chrome, it seems to only register the stuff going on in Chrome itself, rather than on the rest of the computer (e.g. it doesn't log anything from HakuNeko). Is there some way to open developer tools for HakuNeko directly?
