### ISSUE TITLE
[Site Request] Manhwax

### ISSUE THREAD

**Issue by MzMinaRi** [manga-download/hakuneko#4765]
**Name of the website**
[Manhwax]

**Website urls (examples below)**
- Site: https://manhwax.com/
- Manga List: https://manhwax.com/manga/list-mode/
- Manga example: https://manhwax.com/manga/a-lucky-man/
- Chapter online viewer example: https://manhwax.com/a-lucky-man-chapter-1-english/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Deleted some messages on a couple of issues. Enjoy your report for spamming, moron.
