### ISSUE TITLE
[KLManga] Connector not working

### ISSUE THREAD

**Issue by Floritaner** [manga-download/hakuneko#4766]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Website changed from klmag.com to klmanga.com

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Seems fixed on nightly .

**Comment by MikeZeDev** [comment]
URL fixed BUT there is a particular manga i cant get. 

Connector.mjs:598 SyntaxError: Invalid regular expression: /+ TIC NEE-SAN/: Nothing to repeat

The + in the manga name fuck the Regex :D

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5246
