### ISSUE TITLE
[Site Request] comicdrive.jp

### ISSUE THREAD

**Issue by vleaf0210** [manga-download/hakuneko#4767]
**Name of the website**
comicdrive.jp

**Website urls (examples below)**
- Site: Site: https://pages.comicdrive.jp/
- Manga List: https://ciao.shogakukan.co.jp/webwork/
- Manga example: https://ciao.shogakukan.co.jp/webwork/16563/
- Chapter online viewer example: http://sgk.comicdrive.jp/?p=f3612a

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Closing as duplicate https://github.com/manga-download/hakuneko/issues/7129 (7129 is fullfilled in haruneko)
