### ISSUE TITLE
[swatmanga] Connector not working

### ISSUE THREAD

**Issue by rovina20** [manga-download/hakuneko#4769]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The website has moved to a new address and can't be reached by Honoka at the moment
https://swatmanga.co/

**To Reproduce**
1. swatmanga(https://swatmanga.co/)
2. does not work
3. does not work
4. does not work
**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/96107418/174789189-ba392b13-a344-4fca-8945-df545aff4fa9.png)

**HakuNeko (please complete the following information):**

[v6.1.7]

**Comment by Sheepux** [comment]
already fixed, use hakuneko nightly

**Comment by rovina20** [comment]
Don't do try it yourself the site in Honoka does not work and does not show the mango list

**Comment by Sheepux** [comment]
I already did so .... why do you think i say it's fixed ?
![swatmanga](https://user-images.githubusercontent.com/19878135/175113065-410261df-c6d4-4258-99fb-a8ba84546494.png)
