### ISSUE TITLE
[swatmanga] thewebsitename

### ISSUE THREAD

**Issue by rovina20** [manga-download/hakuneko#4771]
**swatmanga**
thewebsitename

**Website urls (examples below)**
- Site: https://swatmanga.co/
- Manga List: https://swatmanga.co/manga/
- Manga example: https://swatmanga.co/manga/fff-class-trashero/
- Chapter online viewer example: https://swatmanga.co/fff-class-trashero-120/1317605/

**Languages**
Arabic

https://swatmanga.co/

**Comment by Sheepux** [comment]
connector already exists

**Comment by rovina20** [comment]
He doesn't work.

**Comment by Sheepux** [comment]
Use issues, not connector requests.
Also, use hakuneko nightly, it's fixed
