### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by rovina20** [manga-download/hakuneko#4775]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**

Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The site has moved to a new address other than the one in Honoka

**To Reproduce**
1. Name of connector( swatmanga)
2. Name of manga (connector not working)
3. Name of chapter (connector not working)
4. connector not working

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/96107418/174943557-12889fb3-a286-4eb5-956b-17fbf3b4a7e0.png)

**HakuNeko (please complete the following information):**
6.17

**Comment by Sheepux** [comment]
use hakuneko nightly, it's fixed
and stop creating dozens of issues
