### ISSUE TITLE
[Japanread] Chapters of all manga are not available in Hakuneko

### ISSUE THREAD

**Issue by Lanfeust84** [manga-download/hakuneko#4776]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hi.
The mangas with "japanread" are not available to download anymore.
I read this page "https://hakuneko.download/docs/manual-website-interaction/#source-selection" but it doesn't work.

For exemple you can try in Japanread in Hakuneko like the screenshot "otomege sekai...". The software see the title, but don't see any
chapters. And it's the case with all manga in "Japanread".
It appears it because now the website put a captcha system.

Please can you help me ?

Thanks in advance

HakuNeko- Version [e.g. 6.17]
![hakuneko japanread otomege](https://user-images.githubusercontent.com/108029751/175133480-a18a7e50-b740-4715-bfde-a248b4b3510c.png)

**Comment by MikeZeDev** [comment]
Its Cloudflare. Not sure it can be fixed right now.

https://i.imgur.com/YhaSJvn.png

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/4513

**Comment by MikeZeDev** [comment]
Weesite doesnt exist anymore
