### ISSUE TITLE
[Toonily] Connector not working

### ISSUE THREAD

**Issue by jstefansson6** [manga-download/hakuneko#4779]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot connect. "Failed to update manga list for Toonily. Cannot read property 'href' of undefined"

**To Reproduce**
1. Toonily

**Screenshots**
<img width="1121" alt="Screen Shot 2022-06-24 at 12 21 28 PM" src="https://user-images.githubusercontent.com/70831806/175576672-0c2b5090-ac9e-4ccc-8f8b-327f0611aef9.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Just tried on nightly, it works.

**Comment by MikeZeDev** [comment]
Still working
