### ISSUE TITLE
[serimanga] Connector not working

### ISSUE THREAD

**Issue by MrsLucifer** [manga-download/hakuneko#4780]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
not working. sections are not downloading.

 - HakuNeko Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Website is protected by DDoss-guard. I opened the website with manual interaction, i let it load. It allowed me to update manga list and then download chapters flawlessly. I downloaded "My princess you must die" said the female knight chapter 1.

I think there is nothing to fix?

**Comment by MikeZeDev** [comment]
Tested, works, without manipulations. Nightly.
