### ISSUE TITLE
[Site Request] mangaforest

### ISSUE THREAD

**Issue by scallywag** [manga-download/hakuneko#4784]
Name of the website:
mangaforest

• Site: https://mangaforest.com
• Manga List: https://mangaforest.com/latest
• Manga example: https://mangaforest.com/sword-empire
• Chapter online viewer example: https://mangaforest.com/sword-empire/chapter-10-9

Language: english

**Comment by MikeZeDev** [comment]
Template : MadTheme theme.(mangabuddy, toonily.me)
