### ISSUE TITLE
[LectorTMO] Connector not working

### ISSUE THREAD

**Issue by iDorito** [manga-download/hakuneko#4785]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
ReferenceError: $ is not defined. (When trying to download)

**To Reproduce**
1. LectorTMO
2. Ultimate Scheming System (link: https://lectormanga.com/library/manhua/40936/ultimate-scheming-system )
3. Chapter 1
4. Console errors: 
//
BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
(anonymous) @ BookmarkManager.mjs:137
Connector.mjs:618 ReferenceError: $ is not defined
    at <anonymous>:5:36 EventTarget
_getPageList @ Connector.mjs:618
Connector.mjs:618 ReferenceError: $ is not defined
    at <anonymous>:5:36 EventTarget
_getPageList @ Connector.mjs:618
Connector.mjs:618 ReferenceError: $ is not defined
    at <anonymous>:5:36 EventTarget 
    
    //

**Screenshots**
![image](https://user-images.githubusercontent.com/108236985/175829884-46214c05-e91f-4366-b3cf-ea65ed0a1e26.png)

HakuNeko:
 - Version [6.17]

**Comment by Sheepux** [comment]
duplicate #4622
