### ISSUE TITLE
Please allow modification of the Wiki.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [manga-download/hakuneko#4786]
**Is your feature request related to a problem? Please describe.**
I am unable to commit nor duplicate the content of the Wiki of this project.

**Describe the solution you'd like**
Perform what "https://stackoverflow.com/a/58692638/9731176" states.

**Describe alternatives you've considered**
Store and provide your documentation via somewhere alternative.

**Additional context**
This problem is caused by GitHub.

**Comment by Sheepux** [comment]
what do you want to add to the dev wiki ?
The user documentation is already externalised https://github.com/manga-download/manga-download.github.io/tree/master/_docs
Also, yes you can duplicate the wiki content by using it was git source https://github.com/manga-download/hakuneko.wiki.git

**Comment by beedell-roke** [comment]
@Sheepux, I wanted to commit [this](http://github.com/manga-download/manga-download.github.io/pull/1). I am thankful for your assistance.
