### ISSUE TITLE
[Comic Ribo Maga] Connector missing

### ISSUE THREAD

**Issue by pattyyyyy** [manga-download/hakuneko#4787]
I saw that Ribo Maga was added as a connector based from here https://github.com/manga-download/hakuneko/issues/4193 but I can't seem to find it. 

![image](https://user-images.githubusercontent.com/108323737/176109550-d748857d-23df-4a10-b789-92b08b569263.png)

**Comment by MikeZeDev** [comment]
You are wrong, it was closed as "Not planned".
