### ISSUE TITLE
[Mangadex manga list fails to fetch]

### ISSUE THREAD

**Issue by TheLejen** [manga-download/hakuneko#4788]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Mangadex has trouble with loading manga chapters within it. I have tried both Nightly and Stable versions of HakuNeko.
The website opens without any problems with both my own browser (brave) and Hakuneku's built-in browser

**To Reproduce**

**Expected behavior**
It's expected for Mangadex's mangalist to work like other sites like Mangasee.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/108355804/176224981-2b9b1c68-7d24-4435-9c57-4287a0ff04c3.png)

It's opened and logged in with Hakuneko's built-in browser:
![image](https://user-images.githubusercontent.com/108355804/176226355-7ba5ee9c-3fca-4f57-a4d2-b079acc056d3.png)

Console: 
![image](https://user-images.githubusercontent.com/108355804/176225346-bab0fbe6-51f7-4e9c-9be8-fe883b5bb484.png)

My Mangadex settings in Hakuneku: 
![image](https://user-images.githubusercontent.com/108355804/176225913-2a367254-782d-40e7-a9ff-1aba6ae33873.png)

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [Nightly - 6e421b] (The stable one with 6.17 was the same)

**Additional context**
When I use the clipboard method from the link of an individual manga page from mangadex, the chapters appear without problem.
Not to mention that mangasee or any other manga website I've tested works fine.

**Comment by Infernotez** [comment]
Issue exclusive to this hakuneko, other downloaders can still download from dex.

**Comment by TheLejen** [comment]
> Issue exclusive to this hakuneko, other downloaders can still download from dex.

By "**this** hakuneko" do you mean the nightly version? I've also tried the main version but that was still the case.

**Comment by TheLejen** [comment]
A

**Comment by Infernotez** [comment]
This is fixed on the nightly builds.

**Comment by TheLejen** [comment]
>  You mean on the newest version? Cause the last time I tried it didn't work.

**Comment by MikeZeDev** [comment]
reported as fixed

**Comment by joshuchiha4** [comment]
![Screenshot (23)](https://github.com/manga-download/hakuneko/assets/155190756/9e0385fd-5f79-432d-835d-c85fceaa7d34)


I am having this same issue please help i downloaded hakuneku nightly master and made my Mangadex setting the same as the image above and it still can not receive content. IDk what to do

**Comment by MikeZeDev** [comment]
No matter how much people complain about it, there is NOTHING to do, its mangadex servers.
Properly use throttling settings on nightly. If that doesnt work for you , use Copy Paste method for individual manga, or change website. 🤷

**Comment by joshuchiha4** [comment]
ok thanks for letting me know iv been using mangasee and its pretty good
