### ISSUE TITLE
[Site Request] 嗨皮漫画 (happymh)

### ISSUE THREAD

**Issue by mnioq** [manga-download/hakuneko#4790]
**Name of the website**
嗨皮漫画 (happymh)

**Website urls (examples below)**
- Site: https://m.happymh.com/
- Manga List: 
https://m.happymh.com/latest (not sure if this counts) 
- Manga example: https://m.happymh.com/manga/lunpanshijie
- Chapter online viewer example: https://m.happymh.com/reads/lunpanshijie/2736463

**Languages**
chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3390
