### ISSUE TITLE
[Site Request] Mangapro

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#4794]
**Name of the website**
Mangapro

**Website urls (examples below)**
- Site: https://mangapro.top/
- Manga List: https://mangapro.top/list/
- Manga example: https://mangapro.top/%e4%b9%99%e5%a5%b3%e3%82%b2%e3%83%bc%e8%bb%a2%e9%80%81%e3%80%81%e4%bf%ba%e3%81%8c%e3%83%92%e3%83%ad%e3%82%a4%e3%83%b3%e3%81%a7%e6%95%91%e4%b8%96%e4%b8%bb-raw-free/

- Chapter online viewer example: https://mangapro.top/chapters/%e3%80%90%e7%ac%ac1%e8%a9%b1%e3%80%91%e4%b9%99%e5%a5%b3%e3%82%b2%e3%83%bc%e8%bb%a2%e9%80%81%e3%80%81%e4%bf%ba%e3%81%8c%e3%83%92%e3%83%ad%e3%82%a4%e3%83%b3%e3%81%a7%e6%95%91%e4%b8%96%e4%b8%bb-raw/

**Languages**
Japanese

Just a side note, if anyone knows, what's the new url (if there is one) for doki1001.com. Since it looks like it's offline

**Comment by Juboha** [comment]
[MangaProTop.zip](https://github.com/manga-download/hakuneko/files/9039597/MangaProTop.zip)

For anyone who doesn't want to wait for an official update, the above attachment adds mangapro.top to Hakuneko.

Unzip the attachment content into:
`%appdata%\hakuneko-desktop\hakuneko.plugins\`

**Comment by PerseusRex** [comment]
Thank you! The url changed so I edited that into the new one, but I realized some mangas aren't showing up right in HakuNeko.

For example this one: https://manga9.co/S%e3%83%a9%e3%83%b3%e3%82%af%e3%83%91%e3%83%bc%e3%83%86-raw-free/

Wondering if you know how to fix it. Thanks
![Capture](https://user-images.githubusercontent.com/51503984/179459627-00a6cfdc-063f-46f6-9af0-01060bcd09f7.PNG)

**Comment by Juboha** [comment]
[Manga9Co.zip](https://github.com/manga-download/hakuneko/files/9131816/Manga9Co.zip)

Fixed. The brackets "【】" is used as a delimiter to locate the chapter number, but unfortunately this manga also uses them in the title.
Update now ensures that brackets in the title are skipped.
