### ISSUE TITLE
[Site/ClipboardConnector Request] manhwa68.com

### ISSUE THREAD

**Issue by RandomGOTI** [manga-download/hakuneko#4795]
**Name of the website**
manhwa68.com

**Website urls (examples below)**
- Site: https://manhwa68.com/
- Manga List: https://manhwa68.com/manga/
- Manga example: https://manhwa68.com//manga/themanganame
- Chapter online viewer example: https://manhwa68.com/manga/themanganame/chapter-1/

**Languages**
English

**Comment by MikeZeDev** [comment]
madara.
