### ISSUE TITLE
[Site Request] Mangabuddy

### ISSUE THREAD

**Issue by animeearth** [manga-download/hakuneko#4796]
**Name of the website**
Mangabuddy

**Website urls (examples below)**
- Site: https://mangabuddy.com/
- Manga List: https://mangabuddy.com/latest
- Manga example: https://mangabuddy.com/yumis-cells
- Chapter online viewer example: https://mangabuddy.com/yumis-cells/chapter-510-ep-510-ending

**Languages**
English

**Website relationship*
Normal reader

**Comment by Sheepux** [comment]
duplicate #4346
