### ISSUE TITLE
[DM5] Connector not working

### ISSUE THREAD

**Issue by sheuher** [manga-download/hakuneko#4804]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

No pages were loaded, all blank.

**To Reproduce**
Steps to reproduce the behavior: click on 猎人, open first chapter, nothing will appear
1. Name of connector: DM5 漫画
2. Name of manga (if connector update is working)： 猎人
3. Name of chapter (if manga update is working)：all chapters
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

Failed to load resources: net::ERR_SPDY_PROTOCOL_ERROR

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4536
