### ISSUE TITLE
[Site Request] Drake Scans

### ISSUE THREAD

**Issue by Coravon** [manga-download/hakuneko#4820]
**Name of the website**
Drake Scans

**Website urls (examples below)**
- Site: https://drakescans.com/
- Manga List: https://drakescans.com/comics/
- Manga example: https://drakescans.com/series/martial-god-chat-group/
- Chapter online viewer example: https://drakescans.com/series/martial-god-chat-group/chapter-01/

**Languages**
List of languages supported by the website
- English

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5138
