### ISSUE TITLE
[Site Request] ZORO.to

### ISSUE THREAD

**Issue by 99keyz** [manga-download/hakuneko#4827]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by 99keyz** [comment]
Name of the website
ZORO.to

    Site: https://zoro.to/
    Manga List: https://zoro.to/dubbed-anime
    Manga example: https://zoro.to/my-dress-up-darling-17930
    Chapter online viewer example: https://zoro.to/watch/my-dress-up-darling-17930?ep=85827

**Comment by Sheepux** [comment]
duplicate #4625
