### ISSUE TITLE
[Feature] DNS

### ISSUE THREAD

**Issue by rabilbudiman** [manga-download/hakuneko#4828]
can you add DNS options inside HakuNeko? Like the one on google chrome.

because the problem I'm facing is because of the government's blocking of websites for adult content in indonesian

we can use vpn, but it doesn't really support it because it takes a long time to load/download

 - im using HakuNeko Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Why don't you change it at your OS level ?
