### ISSUE TITLE
MangaFreak Connector not working

### ISSUE THREAD

**Issue by jhoee7** [manga-download/hakuneko#4833]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I tried adding MangaFreak, a dialouge box appeared, it says, "Failed to update manga list for mangafreak, Cannot read property 'href' of undefined" 

**To Reproduce**
1. Manga Freak
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. "Failed to update manga list for mangafreak, Cannot read property 'href' of undefined"

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4292
