### ISSUE TITLE
[manhuascan] Connector not working

### ISSUE THREAD

**Issue by HorrorBest** [manga-download/hakuneko#4838]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I download any Manhua it does download but its empty (the files are like 1kb) **PDF form** and **Comic Book form** Both didn't work, But In other websites/connectors it does work fine

**To Reproduce**
1. manhuascan
2. Any manga/Manhua (if connector update is working)
3. Any chapter (if manga update is working)
4. "server responded with a status of 403 ()","GET https://my2.1stmggv3.xyz/go/fankyj.mhscdnv5.club/images/2020/12/31/3155502_1080_526_51043.jpg 403"

**HakuNeko (please complete the following information):**
 - Version 6.1.7@66ea4f

**Comment by Sheepux** [comment]
duplicate #4628

**Comment by HorrorBest** [comment]
> duplicate #4628

I don't think this is a duplication, This is not about the connector loading its about well the download/viewing of the mangas/manhua, and even today I checked and Its still not working

**Comment by Sheepux** [comment]
It was the same issue. Use "hakuneko nightly"
