### ISSUE TITLE
[Site Request] webnovel 

### ISSUE THREAD

**Issue by johnny200313** [manga-download/hakuneko#4840]
**Name of the website**
webnovel
**Website urls (examples below)**
- Site: https://webnovel.com
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
English, Spanish, Vietnamese, Hindi, Bahasa Melayu, Behasa Indonesian 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by amit34521** [comment]
already added to HN.

**Comment by MikeZeDev** [comment]
Already added and works fine.
