### ISSUE TITLE
[MangaKik] Url change

### ISSUE THREAD

**Issue by Narutofox** [manga-download/hakuneko#4843]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector url has changed.

**To Reproduce**
1. Name of connector -  MangaKik
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working) - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![Screenshot 2022-07-19 171945](https://user-images.githubusercontent.com/6874139/179787331-e7be05d8-e5ab-444e-b151-595064e3869f.jpg)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment]
> the url has changed

Can you please provide the new url and change the issue title to let people know its just an url change? thanks

Nevermind, Its mangakik.net now? or topmangas.net ?

**Comment by Narutofox** [comment]
The new URL should be https://mangakik.net.
Thank you
