### ISSUE TITLE
[Site Request] zoro.to

### ISSUE THREAD

**Issue by maxtheproblemsolver** [manga-download/hakuneko#4847]
Name of the website
Zoro
Website urls (examples below)

Site: https://zoro.to/
Anime List: https://zoro.to/az-list
Anime example: https://zoro.to/rent-a-girlfriend-2nd-season-15758
Episode online viewer example: https://zoro.to/watch/rent-a-girlfriend-2nd-season-15758?ep=92798
Languages
English, Arabic, French, German, Italian, Portuguese, Russian, Spanish, Thai

*Website relationship
I know that 9anime often uses videos with zoro.to watermarks on them, meaning they originaly come from zoro.to

**Comment by Sheepux** [comment]
Duplicate #4625
