### ISSUE TITLE
包子漫書 (baozimh)]Connector not working

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#4848]
1. Name of connector 
   包子漫書 (baozimh)
2. Name of manga (if connector update is working)
  童養夫想幹掉我怎麼辦
https://www.baozimh.com/comic/tongyangfuxianggandiaowozenyaoban-shanchuanwannan

3. Name of chapter (if manga update is working)
eg. 第六十七章 情逾骨肉 (Chapter 67)

7. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
The software is not able to show the full chapter. There is another section of the chapter which the software cannot display.

<img width="958" alt="Capture1" src="https://user-images.githubusercontent.com/60792860/180213686-198b6d64-5d00-40e6-b289-1bbce5afd43f.PNG">

This is the website of the manga which show that you need to click inorder to display the next sections of the chapters

<img width="465" alt="Capture2" src="https://user-images.githubusercontent.com/60792860/180214816-a3ea9da8-5b84-44aa-aec9-fd30eddf064c.PNG">

This is the website displaying another section of the chapters after clicking it. These are the parts where the software cannot display. This happen on the other chapters and other mangas too.
<img width="556" alt="Capture3" src="https://user-images.githubusercontent.com/60792860/180215350-44bd5db8-f8c4-405d-8f2a-c5c5da590c60.PNG">

Is there any way to set in hakuneko app to capture the full chapter?
Some of the mangas in this website also cannot display the full chapters because of this feature in the website.

**HakuNeko (please complete the following information):**
 - Version [rev. master@6c2a52)

**Comment by Sheepux** [comment]
did you try "hakuneko nightly"  (it's probably already fixed)

**Comment by suikodoen13** [comment]
yes currently i am using hakuenko nightly
The software is only able to load 50 frames from that website. If it is more than 50 frames...not able to load the rest.

**Comment by suikodoen13** [comment]
Problem is still not fixed....any updates on this?

**Comment by Sheepux** [comment]
it's not fixed because no contributor were interested in working on it. 
Here comes the update.

**Comment by suikodoen13** [comment]
thanks for the update. Guess have to wait for contributor to pick up on this.
