### ISSUE TITLE
[Site Request] cmoa.jp

### ISSUE THREAD

**Issue by kirbyreadsmanga** [manga-download/hakuneko#4850]
**Name of the website**
cmoa.jp

**Website urls (examples below)**
- Site: https://www.cmoa.jp/
- Manga example: https://www.cmoa.jp/title/241530/
- Chapter online viewer example: https://www.cmoa.jp/bib/speedreader/?cid=0000241530_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Ftitle%2F241530%2F&rb=1

**Languages**
Japanese.

**Comment by Ever4engel** [comment]
already supported, please check in the tool before opening any new ticket, thanks.

**Comment by MikeZeDev** [comment]
Already supported
