### ISSUE TITLE
[Site Request] Manhwa Freak

### ISSUE THREAD

**Issue by Infernotez** [manga-download/hakuneko#4854]
**Name of the website**
Manhwa Freak

**Website urls (examples below)**
- Site: https://manhwafreak.com/
- Manga example: https://manhwafreak.com/manga/i-was-born-as-the-seventh-prince-what-should-i-do/
- Chapter online viewer example: https://manhwafreak.com/i-was-born-as-the-seventh-prince-what-should-i-do-ch-01/
- 
**Languages**
English

**Comment by MikeZeDev** [comment]
Duplicate of https://github.com/manga-download/hakuneko/issues/4649
