### ISSUE TITLE
[Site Request] manhatic

### ISSUE THREAD

**Issue by thezero2000** [manga-download/hakuneko#4856]
**Name of the website**
[مانهاتك](https://manhatic.com/)

**Website urls (examples below)**
- Site: https://manhatic.com/
- Manga List: https://manhatic.com/manga/
- Manga example: https://manhatic.com/manga/fitness/
- Chapter online viewer example: https://manhatic.com/manga/fitness/21/

**Languages**
Arabic

**Comment by MikeZeDev** [comment]
Added by https://github.com/manga-download/hakuneko/pull/5138
