### ISSUE TITLE
[Site Request] Mangasol

### ISSUE THREAD

**Issue by Ghilas951** [manga-download/hakuneko#4857]
**Name of the website**
Mangasol

**Website urls (examples below)**
- Site: https://www.mangasol.com/
- Manga List: https://www.mangasol.com/manga/
- Manga example: https://www.mangasol.com/manga/im-a-villainess-can-i-die/
- Chapter online viewer example: 
https://www.mangasol.com/the-tax-reaper-25/
**Languages**
Arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Site redirect to a hotel industry job school?  Alternative not found. Can be closed i guess @Sheepux pls :D

**Comment by Ghilas951** [comment]
Yes the site closed 😩
