### ISSUE TITLE
[WeLoveManga] Website url change

### ISSUE THREAD

**Issue by lunarian793** [manga-download/hakuneko#4859]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector url has changed from weloma.net to weloma.art

**To Reproduce**
1. Name of connector - WeLoveManga
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working) - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/110048124/181047760-61d51af2-39dc-477c-ace3-61c712596da6.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] - 6.1.7

**Comment by MikeZeDev** [comment]
If you can please change your issue title to "[WeLoveManga] Website url change" :)

**Comment by MikeZeDev** [comment]
Maybe this can be closed?  https://github.com/manga-download/hakuneko/issues/4243
