### ISSUE TITLE
[Feature] Hakuneko Nightly in Flathub-Beta

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#4863]
**Is your feature request related to a problem? Please describe.**
I know there is a Hakuneko Stable for Flatpak. But, the update cycle is quite slow and we cannot get the latest feature on time

**Describe the solution you'd like**
To ensure we can get the latest update. I think Hakuneko Nightly should be available on Flathub Beta

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7

**Additional context**

**Comment by Sheepux** [comment]
Flatpak isn't maintained by the team
