### ISSUE TITLE
[Site Request] cubari.moe

### ISSUE THREAD

**Issue by CultZone99** [manga-download/hakuneko#4864]
**Name of the website**
cubari.moe

**Website urls (examples below)**
- Site: https://cubari.moe/
- Manga List: https://cubari.moe/read/gist/OPM/l
- Manga example: https://cubari.moe/read/gist/OPM/
- Chapter online viewer example: https://cubari.moe/read/gist/OPM/168/1/

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by knst0** [comment]
#4882
If you need, I rework connector to plugin: https://github.com/sekiju/hakuneko-plugins

**Comment by Sheepux** [comment]
refer to the comment as linked by sekiju
https://github.com/manga-download/hakuneko/pull/4882#issuecomment-1204350164
