### ISSUE TITLE
[WebComicsApp] Connector not working

### ISSUE THREAD

**Issue by makerkym** [manga-download/hakuneko#4866]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Won't load any of the chapters

**To Reproduce**
1. Name of connector: Webcomicsapp
2. Name of manga: All
3. Name of chapter: All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [nightly(master) • 2020-07-05T00:14:37UTC]

**Comment by MikeZeDev** [comment]
Website change. Endpoints are not the same.

* Manga page (list of chapters) went from reader.html? to stuff like https://www.webcomicsapp.com/comic/Nabe-Universe/623f26b062661d29d46cbb54

* A chapter page is now like this : https://www.webcomicsapp.com/view/Nabe-Universe/1/623f26b062661d29d46cbb54-The-Encounter-Part-1-
