### ISSUE TITLE
[webmota ] connector limited to 50 images

### ISSUE THREAD

**Issue by apt42541** [manga-download/hakuneko#4868]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**
i found problem about webmota, it slice 50 image per page and hakuneko only first page so it can download only 50 image per chapters by now 
**To Reproduce**
1. Go to ' man site of manga '
2. Click on 'single chapter'
3. Scroll down to 'bottom click next  you will get 0_15_2 , 0_15_3 or 0_15_4 '
5. 
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12625408/181670124-9590a23f-26fd-4fe9-920a-fa46f6a251e4.png)
like screenshot it still not ending.
**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by Druzai** [comment]
@apt42541 I guess it's related to this connector `baozimh` and this issue #4848?
Cause this site `https://www.baozimh.com` uses `https://www.webmota.com` to view chapters.
Or are there other connectors/sites that use `https://www.webmota.com`?

**Comment by apt42541** [comment]
> `https://www.webmota.com`

yes it same issue

**Comment by Druzai** [comment]
Ok, thanks.
I have a fix for this issue, but it will be included in a PR that updates/fixes several connectors.
So this will be fixed soon.
