### ISSUE TITLE
Issue with loading list from WuxiaWorld

### ISSUE THREAD

**Issue by FAReaper1** [manga-download/hakuneko#487]
https://wuxiaworld.site/tag/comics/

2 days ago the website still works

**Comment by 27136773** [comment]
Probably disabled ajax.
Use copy/paste for manga url until this get fixed.

**Comment by 27136773** [comment]
Problem seems to no longer exist / can no longer be reproduced.

**Comment by FAReaper1** [comment]
I realized something interesting, the web tag is always changing

https://wuxiaworld.site/tag/webcomic/
https://wuxiaworld.site/tag/comic/
https://wuxiaworld.site/tag/webcomics/
https://wuxiaworld.site/tag/comics/

interesting right?

**Comment by 27136773** [comment]
Shouldn't matter, HakuNeko now uses the list from the front page
