### ISSUE TITLE
[toonily.com] Connector not working

### ISSUE THREAD

**Issue by Dark-Load** [manga-download/hakuneko#4871]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
THe Family mode is blocking from getting all the manhwas downloaded

**To Reproduce**
1. Toonily.com
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by paulphyo** [comment]
Yeah, one of the request cookie headers that's responsible for enabling/disabling family safe got renamed.
Im kinda new to github and pull requests and stuff so for future peeps who wanna solve this, just replace the 
```js
this.requestOptions.headers.set('x-cookie', 'wpmanga-adault=1');
```
in the Toonily.mjs file to
```js
this.requestOptions.headers.set('x-cookie', 'toonily-mature=1');
```
Similar to commit [4cf8fbf](https://github.com/manga-download/hakuneko/commit/4cf8fbf2814eaf6cb4112e6c9bf3e4c08d1df900)

**Comment by Sheepux** [comment]
As requested in the issue form, provide  the informations that will allow testing (eg: title)
