### ISSUE TITLE
[Site Request] hentai20

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#4872]
**Name of the website**
hentai20

**Website urls (examples below)**
- Site: https://hentai20.com

- Manga List: 
https://hentai20.com/
https://hentai20.com/manga-genre/manhwa-hentai-19/

- Manga example: https://hentai20.com/manga/touching-my-older-sister-under-the-table/

- Chapter online viewer example: https://hentai20.com/manga/touching-my-older-sister-under-the-table/chapter-19/

**Languages**
english

**Comment by Sheepux** [comment]
duplicate #4241
