### ISSUE TITLE
[Site Request] mcreader

### ISSUE THREAD

**Issue by T0PMAX** [manga-download/hakuneko#4873]
**Name of the website**
mcreader

**Website urls (examples below)**
- Site: https://www.mcreader.net/
- Manga List: https://www.mcreader.net/browse-comics/
- Manga example: https://www.mcreader.net/manga/trapped-in-a-webnovel-as-a-good-for-not/
- Chapter online viewer example: https://www.mcreader.net/reader/en/trapped-in-a-webnovel-as-a-good-for-nothing-chapter-1-eng-li/

**Languages**
English

**Website relationship*
copy of: isekaiscan

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
duplicate #4695
