### ISSUE TITLE
[Site Request] animixplay

### ISSUE THREAD

**Issue by zo-xoxo** [manga-download/hakuneko#4875]
animixplay

- Site: https://animixplay.to/
- anime example: https://animixplay.to/anime/11617/High_School_DxD
- Chapter online viewer example: https://animixplay.to/v1/high-school-dxd

Languagues supported: english(sub&dub)

(plz consider it there's no english anime connector that works)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/3919
