### ISSUE TITLE
[TuMangaOnline & LectorManga] Connector not working

### ISSUE THREAD

**Issue by Yoanlle** [manga-download/hakuneko#4879]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Detected mangas only by links, but don't download or show anything

**To Reproduce**
1. Connectors: TuMangaOnline, LectorManga
2. PopUp says: **$ is not defined.**
3. After a while, Cloudflare start working

**Screenshots**
![image](https://user-images.githubusercontent.com/105180340/182262535-8db6201d-7449-439a-b391-0f0865e34738.png)
**HakuNeko (please complete the following information):**
![image](https://user-images.githubusercontent.com/105180340/182262576-c2dd9161-c9b9-457c-adc4-d830205935dd.png)
![image](https://user-images.githubusercontent.com/105180340/182262801-9e143948-b45d-443f-8a03-a92ece608cba.png)

 - Version [6.1]

**Comment by MikeZeDev** [comment]
Cloudflare error strikes again.

**Comment by Sheepux** [comment]
Error message: read the message ....
Clip board infinite loop = cloudflare : unsolved issue #2933
