### ISSUE TITLE
Fire Cross - Connector not working

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#4880]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
HN doesn't detect the site from the clipboard

**To Reproduce**
Manga: https://firecross.jp/ebook/series/387
Chapter: https://firecross.jp/reader/1409?trial=0&token=a31890a7-d545-4bc4-adb4-7e6bbed8bf60&vertical=0

**HakuNeko:**
 - Version master@4b7a83

**Comment by knst0** [comment]
@Redyn, because HN doesn't support this site, I don't found Connector for this site in source code

**Comment by Sheepux** [comment]
Please, create a connector request using the adequate template.

**Comment by Redyn** [comment]
My bad. The site request for Fire Cross was marked as "completed", which I took to mean it had been implemented:
https://github.com/manga-download/hakuneko/issues/4261

What did that mean then?

**Comment by Sheepux** [comment]
it was a duplicate, see #3978 the request is still open.
"completed" was known as "closed" before 2022
