### ISSUE TITLE
[Hiperdex] Connector not working

### ISSUE THREAD

**Issue by TheRebel03** [manga-download/hakuneko#4884]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
Yes
**Describe the bug**
The website can't open in hakuneko.

**To Reproduce**
hiperdex.com	

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [All Version ]

**Comment by MikeZeDev** [comment]
It is working. On Nightly at least.

https://i.imgur.com/6qA7xxz.png

**Comment by Sheepux** [comment]
Cannot reproduce using nightly, please reopen and give errors details from the console if the issue persists
