### ISSUE TITLE
[NHentai] Connector not working

### ISSUE THREAD

**Issue by Ace733** [manga-download/hakuneko#4887]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hakuneko cannot use the site

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
https://i.imgur.com/wnEyTnm.png

Cloudflare. There are chances it cant be fixed.

**Comment by Sheepux** [comment]
Cloudflare issue, unsolved for now: #2933
