### ISSUE TITLE
[Site Request] Manga1001.in and Comick.top

### ISSUE THREAD

**Issue by kamikaze00007** [manga-download/hakuneko#4898]
**Name of the website**
Manga1001.in

**Website urls (examples below)**
- Site: https://manga1001.in
- Manga List: https://manga1001.in/list/
- Manga example: https://manga1001.in/%e9%ad%94%e5%8a%9b0%e3%81%a7%e6%9c%80%e5%bc%b7%e3%81%ae%e5%a4%a7%e8%b3%a2%e8%80%85%ef%bd%9e%e3%81%9d%e3%82%8c%e3%81%af%e9%ad%94%e6%b3%95%e3%81%a7%e3%81%af%e3%81%aa%e3%81%84%e3%80%81%e7%89%a9%e7%90%86%e3%81%a0%ef%bc%81%ef%bd%9e-raw-free/
- Chapter online viewer example: https://manga1001.in/chapters/%e3%80%90%e7%ac%ac20.2%e8%a9%b1%e3%80%91%e9%ad%94%e5%8a%9b0%e3%81%a7%e6%9c%80%e5%bc%b7%e3%81%ae%e5%a4%a7%e8%b3%a2%e8%80%85%ef%bd%9e%e3%81%9d%e3%82%8c%e3%81%af%e9%ad%94%e6%b3%95%e3%81%a7%e3%81%af%e3%81%aa%e3%81%84%e3%80%81%e7%89%a9%e7%90%86%e3%81%a0%ef%bc%81%ef%bd%9e-raw/

**Languages**
Japanese

**Website relationship*
Manga1001.in might possibly be a variation of Manga1001 that got taken down some time ago. It has manga with chapters not readily available on other popular raw sites.

**Additional details**
Manga1001.in has a simple layout where the specific manga page has a list of available chapters that serve as links to reading them. The sample manga I linked have pages watermarked as "mangaraw.co".

**Name of the website**
Comick.top

**Website urls (examples below)**
- Site: https://comick.top
- Manga List: https://comick.top/genre/harem **(NOTE: each genre is a list)**
- Manga example: https://comick.top/eigo-sensei-raw
- Chapter online viewer example: https://comick.top/eigo-sensei-raw/chapter-21-937

**Languages**
Japanese

**Website relationship*
Comick.top shows the name "MangaBank"(漫画ばんく) in Japanese on the homepage. The mobile version uses a small icon of the initials "CK" in red. It has manga with chapters not readily available on other popular raw sites.

**Additional details**
Comick.top seems to have a system where it loads pages slowly while displaying "Please turn off your ad-blocker. Comick.top" or something similar. I don't know if it's specific to the site or not. Just waiting for the page to load makes the pages load just fine though.

**Comment by MikeZeDev** [comment]
Both are down
