### ISSUE TITLE
[Bug] Can't Load Website Mangatoon

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#4901]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Can't load the list of manga/website.

**To Reproduce**

**Expected behavior**

**Screenshots**
![haku](https://user-images.githubusercontent.com/81703465/185096567-43565891-6f48-4270-98ab-5c8973dffc30.PNG)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [ 8.3.4 ]

**Additional context**

**Comment by Sheepux** [comment]
duplicate #4609
