### ISSUE TITLE
[Feature] BilibiliComics Login

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4903]
**Is your feature request related to a problem? Please describe.**

I tried downloading paid comics (that I paid for) from [Bilibilicomics](https://www.bilibilicomics.com/) but I could not.
Only the starting two images are being downloaded for comics behind a paywall.

For free chapters, all images are being downloaded.

**Describe the solution you'd like**
If possible a site login feature for [bilibili](https://www.bilibilicomics.com).

**Describe alternatives you've considered**
I have not thought of any alternatives. I also used the manual website interaction feature and it did not work.

**Context (please complete the following information):**
 - HakuNeko rev. 6.1.7@7ed275

**Additional context**
I uploaded a screenshot below, left is the original and right is the requested feature.

![Bilibili](https://user-images.githubusercontent.com/111482404/185443206-124f3835-3589-4c3e-8b8c-9a64b9f7c8fb.png).

**Comment by Sheepux** [comment]
did you try to log in using manual website interraction ?

**Comment by Sheepux** [comment]
duplicate #4481
