### ISSUE TITLE
[Mangakatana] Connector not working, only downloads first page

### ISSUE THREAD

**Issue by thevladsoft** [manga-download/hakuneko#4904]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When downloading from mangakatana, it will only download the first page. It doesn't seems to happen with every manga, so could be a recent change on their part.

**To Reproduce**
Try to download, for example, any chapter of this manga: https://mangakatana.com/manga/school-doodles-festival-2017.24105. Only the first page is downloaded. Hakuneko does not reports an error.

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by thevladsoft** [comment]
Correction, it's happening with all mangas.

**Comment by MikeZeDev** [comment]
Mentioned here https://github.com/manga-download/hakuneko/issues/4905
