### ISSUE TITLE
[Tappytoon (English)] Only free chapters are displayed despite login

### ISSUE THREAD

**Issue by SpottyMcBumbleFuck** [manga-download/hakuneko#4906]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Through Tappytoon english, only the freely available chapters are listed, despite most series containing more than those freely available chapters and despite logging into an account that has those paid chapters unlocked already.

**To Reproduce**
1. Tappytoon (English)
2. Any series that does not fully contain chapters labelled as FREE
3. Comparing the chapter list produced by HakuNeko vs total available chapters

**Screenshots**
Chapter list by HakuNeko: https://i.imgur.com/khjGSCB.png
Sample Chapter list: https://i.imgur.com/r1WQGYx.png
>Chapters marked Free and those with a checkmark (Paid chapters that were unlocked)
>>Having the chapter unlocked changes nothing vs locked

**HakuNeko (please complete the following information):**
 - Version [6.1.7@7ed275]

**Comment by ghost** [comment]
a few months later & this still isn't fixed... I'm having the same issue too... 😞

**Comment by BereBereBeer** [comment]
I can't even download the free ones anymore 
![Screenshot_2022-10-12_06-15-38](https://user-images.githubusercontent.com/52054446/195248967-b5c9432c-76eb-47ff-8bac-d2a4f6caa2de.png)

**Comment by ghost** [comment]
> I can't even download the free ones anymore ![Screenshot_2022-10-12_06-15-38](https://user-images.githubusercontent.com/52054446/195248967-b5c9432c-76eb-47ff-8bac-d2a4f6caa2de.png)

I'm on mac and it works but only for the free ones. :( - you signed in to your tappytoon account? idk how it works on windows.

**Comment by BereBereBeer** [comment]
> > I can't even download the free ones anymore ![Screenshot_2022-10-12_06-15-38](https://user-images.githubusercontent.com/52054446/195248967-b5c9432c-76eb-47ff-8bac-d2a4f6caa2de.png)
> 
> I'm on mac and it works but only for the free ones. :( - you signed in to your tappytoon account? idk how it works on windows.

I have linux, but that was an issue on my part. I hadn't noticed that it kept signing me off. so yes, free chapters are available unless they are free through "Time Till Free"
