### ISSUE TITLE
[MangaToon (English)] Connector not working

### ISSUE THREAD

**Issue by makerkym** [manga-download/hakuneko#4909]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The MangaToon Connector won't even load the list of comics. Even using the clipboard for a specific comic, it won't load.

**To Reproduce**
1. MangaToon (English)
2. All Mangas
3. All Chapters
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - nightly master

**Comment by MikeZeDev** [comment]
Novel are now available on Noveltoons so you have to specify a genre in the request, hence https://mangatoon.mobi/en/genre/comic. 

Pasting doesnt work anymore too, tried with https://mangatoon.mobi/en/my-underworld-boyfriend?content_id=7
