### ISSUE TITLE
[DoujinDesu] Connector not working

### ISSUE THREAD

**Issue by 181011** [manga-download/hakuneko#4910]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
DoujinDesu is changing their website to Doujinesia, that's why the connector won't work, I've tried to copy the new url and tried the clipboard method but still not working

**To Reproduce**
1. DoujinDesu
2. All Mangas
3. All Chapters
4. Failed to load resource: the server responded with a status of 404 ()

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - 6.1.7

**Comment by Sheepux** [comment]
duplicate #4600
