### ISSUE TITLE
[Site Request] Manga Fox Full

### ISSUE THREAD

**Issue by zasfan** [manga-download/hakuneko#4912]
**Name of the website**
Manga Fox Full

**Website urls (examples below)**
- Site: https://mangafoxfull.com
- Manga List: https://mangafoxfull.com/manga/
- Manga example: https://mangafoxfull.com/manga/the-law-of-love-in-the-last-of-our-days/
- Chapter online viewer example: https://mangafoxfull.com/manga/the-law-of-love-in-the-last-of-our-days/chapter-52/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4058
