### ISSUE TITLE
[Site Request] inarimanga

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#4917]
**Name of the website**
inarimanga

**Website urls (examples below)**
- Site: https://inarimanga.com/
- Manga List: https://inarimanga.com/manga/
- Manga example: https://inarimanga.com/manga/la-hermana-del-villano-sufre-hoy/
- Chapter online viewer example: https://inarimanga.com/manga/la-hermana-del-villano-sufre-hoy/capitulo-1/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
"Coming soon on website

**Comment by MikeZeDev** [comment]
Dead?

**Comment by Lenoyr** [comment]
> Dead?

"Inari Manga is Under Maintenance"
The site is under maintenance for several days, that's what they said on their Discord.

**Comment by MikeZeDev** [comment]
Website doesnt host content
