### ISSUE TITLE
[Mangakatana] Connector not working

### ISSUE THREAD

**Issue by thevladsoft** [manga-download/hakuneko#4918]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When trying to download, it fails with error "ReferenceError: htnc is not defined"

**To Reproduce**
Try to download anything from Mangakatana. It happens with any chapter, recent or old.

**HakuNeko (please complete the following information):**
 - Version 8.3.4, Linux

**Comment by DarkDiRaiZeL** [comment]
yeah.i face the same problem
btw, im using window version
![image](https://user-images.githubusercontent.com/76126487/187055190-0e8cf5c2-1279-4269-b06b-48451fb989cf.png)

**Comment by DarkDiRaiZeL** [comment]
its fixed!!
thank you so much!!!
