### ISSUE TITLE
[Manga Livre] Connector not working

### ISSUE THREAD

**Issue by Agnaldo-Carmo** [manga-download/hakuneko#4924]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot Download any chapter from mangas on Manga livre

**To Reproduce**
1. Manga Livre
2.Yu-Gi-Oh! 
3. 103 - Aguente Firme [One Man Army Scans]
4. TypeError: Cannot read property 'src' of null
    at MangaLivre._getPages (MangaLivre.mjs:18)
    at async MangaLivre._getPageList (Connector.mjs:615) EventTarget {manga: EventTarget, id: "/ler/yugioh/online/386669/103", title: "103 - Aguente Firme [One Man Army Scans]", file: {…}, language: undefined, …}

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Access denied Error code 1020. Cloudflare strikes gain. Is that website geoblocking people? Anyone with a vpn?

**Comment by Agnaldo-Carmo** [comment]
Yes it is, tested with ProtonVpn

**Comment by Sheepux** [comment]
duplicate #4061
