### ISSUE TITLE
[NEWTOKI] Connector not working correctly

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#4925]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
for some reason, there are some manhwas that newtoki doesnt show chapters and others that it does.
시크릿 오피스  <== this is an example
https://newtoki151.com/webtoon/22839579/시크릿오피스

슈가대디  <=== this is another example
https://newtoki151.com/webtoon/8734941/슈가대디

the toons are on the list that the conector got from the site, but the chapters aren't being shown on hakuneko

**To Reproduce**
1. Name of connector
newtoki
2. Name of manga (if connector update is working)
시크릿 오피스   <= manga 1
슈가대디  <= manga 2
3. Name of chapter (if manga update is working)
none are being shown

 - Version
 newest one, I am using nightly version

**Comment by MikeZeDev** [comment]
I got error where HN cant even connect to this website when its works in browser. Preview gives a blank page.
ERR_CONNECTION_CLOSED. Wtf
