### ISSUE TITLE
[blacktoon] blacktoon

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#4926]
**Name of the website**
BLACK TOON

**Website urls (examples below)**
- Site: http://blacktoon.link/   [the number XXX on  blacktoonXXX.com keeps changing but this site redirects to the correct site number]
- Manga List: http://blacktoon.link/
- Manga example: https://blacktoon195.com/webtoon/8979.html 
- Chapter online viewer example: https://blacktoon195.com/webtoons/8979/1091539.html

**Languages**
korean

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3453
