### ISSUE TITLE
[WebtoonXYZ] Connector not working 

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#4931]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
not retrieving manga list, clipboard not working

**To Reproduce**
1. webtoonxyz
2. Name of manga : my-first-time-is-with-my-little-sister
3. Name of chapter : Chapter 78 

**HakuNeko (please complete the following information):**
 - I am using nightly version

**Comment by MikeZeDev** [comment]
Cloudlfare "Checking if the site connection is secure". Cant bypass using manual interaction.

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4281
