### ISSUE TITLE
[Mangahub.io] Connector not working mangahub.io

### ISSUE THREAD

**Issue by ramana3797** [manga-download/hakuneko#4933]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
failed to update manga list.
**To Reproduce**
1. mangahub.io
2. Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 403)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7@7ed275
<img width="380" alt="Screenshot 2022-09-01 015545" src="https://user-images.githubusercontent.com/112585806/187776482-aea865e2-9225-4eb1-b6ec-8d62e18c7a0b.png">

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/4939
