### ISSUE TITLE
[Manga Pro z] Connector not working

### ISSUE THREAD

**Issue by MahmoudRaafatCod** [manga-download/hakuneko#4934]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector url has changed

**To Reproduce**
1. Name of connector (Manga Pro z)
2. Name of manga (if connector update is working) all
3. Name of chapter (if manga update is working) all
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

" Website urls (examples below) 

• Site: https://mangaprotm.com/ 

• Manga List: https://mangaprotm.com/manga/

• Manga example: https://mangaprotm.com/manga/tensei-goblin-dakedo-shitsumon-aru/

• Chapter online viewer example: https://mangaprotm.com/dfg654df654gdf/
"

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MahmoudRaafatCod** [comment]
The link has not been modified yet

**Comment by MikeZeDev** [comment]
If you want faster updates use nightly and dont repost another issue.

**Comment by Druzai** [comment]
@Jack-0009 Since you fixed this issue in #4982. Can you close it?

**Comment by MikeZeDev** [comment]
Fixed with #4982
