### ISSUE TITLE
[Site Request] asuralightnovel

### ISSUE THREAD

**Issue by makerkym** [manga-download/hakuneko#4936]
**Name of the website**
asuralightnovel

**Website urls (examples below)**
- Site: https://asuralightnovel.com
- Manga List: https://asuralightnovel.com/novels/
- Manga example: https://asuralightnovel.com/novel/solo-max-level-newbie-novel/
- Chapter online viewer example: https://asuralightnovel.com/novel/solo-max-level-newbie-novel/chapter-407/

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Template : WordPressMadaraNovel. EZ
