### ISSUE TITLE
[MangaFox.Fun] Connector not working

### ISSUE THREAD

**Issue by HighArbiter** [manga-download/hakuneko#4941]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
All chapters missing in the desktop application
All previously downloaded chapters from the site are greyed out.

**To Reproduce**
1. Name of connector - [MangaFoxFun](https://mangafox.fun)

**HakuNeko (please complete the following information):**
 - Version - 6.1.7

**Comment by manikkuge-saumyadasa** [comment]
Update the title to the name of the connector

**Comment by HighArbiter** [comment]
Sorry, missed that one

**Comment by MikeZeDev** [comment]
Its tied to Mangahub, which was fixed and this one work too now, i tested.
