### ISSUE TITLE
[Manga Gecesi] Connector not working

### ISSUE THREAD

**Issue by FortisBey** [manga-download/hakuneko#4943]
Manga Gecesi website is not connecting
![image](https://user-images.githubusercontent.com/112723443/188212419-248137cd-d9cf-4ed3-9dcf-022f7af3ea43.png)
pls repair

**Comment by MikeZeDev** [comment]
Cloudflare "check if connection is secure". Cant bypass using manual interaction.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4041
