### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by Sarwar23** [manga-download/hakuneko#4953]
**Name of the website**
Mangabuddy

**Website urls (examples below)**
- Site:https://mangabuddy.com/
- Manga List: https://mangabuddy.com/manga-list
- Manga example: https://mangabuddy.com/vermeil-in-gold-a-magician-pushes-through-the-magical-world-with-the-strongest-disaster- Chapter online viewer example:https://mangabuddy.com/vermeil-in-gold-a-magician-pushes-through-the-magical-world-with-the-strongest-disaster/chapter-19

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
duplicate #4346
