### ISSUE TITLE
[Manganelos (by AnyACG)] (second one) Connector not fully working

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [manga-download/hakuneko#4956]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes, Through the programs site link window. didn't try in external browser because I don't know the link to get to it myself.

**Describe the bug**
"Vermeil in Gold" title is not downloading, says something about "can not read properly 'textcontent' " when I look at log/F12 screen

**To Reproduce**

If you search by manga and type in "vermeil" the only result is the below mentioned "connector", if you search by connector then type in "Manganel" and there's Manganelo (ironman image) and Manganelos (Luffy/One Piece image), The Ironman one doesn't work at all and the Luffy one is the one I'm attempting to use. when doing the connector method most of the results either didn't work (errored out) or didn't load any results without any filters applied.

1. Name of connector Manganelos (by AnyACG) the second one, the other one didn't work at all.
2. Name of manga (if connector update is working) Vermeil In Gold
3. Name of chapter (if manga update is working) Tried 15.2 and 15.3, both errored out, Tried other titles and they worked.
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
FolderConnector.mjs:69 Error: ENOENT: no such file or directory, scandir '' 
FolderConnector
Connector.mjs:618 TypeError: Cannot read property 'textContent' of undefined
    at Manganelos._getPages (AnyACG.mjs:80)
    at async Manganelos._getPageList (Connector.mjs:615) 
EventTarget
Connector.mjs:618 TypeError: Cannot read property 'textContent' of undefined
    at Manganelos._getPages (AnyACG.mjs:80)
    at async Manganelos._getPageList (Connector.mjs:615) 
EventTarget
Connector.mjs:618 TypeError: Cannot read property 'textContent' of undefined
    at Manganelos._getPages (AnyACG.mjs:80)
    at async Manganelos._getPageList (Connector.mjs:615) 
EventTarget
Connector.mjs:618 TypeError: Cannot read property 'textContent' of undefined
    at Manganelos._getPages (AnyACG.mjs:80)
    at async Manganelos._getPageList (Connector.mjs:615) 
EventTarget {manga: EventTarget, id: "/vermeil-in-gold-a-magician-pushes-through-the-mag…al-world-with-the-strongest-disaster-chapter-15.3", title: "Chapter 15.3", file: {…}, language: "", …}

5. 
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7@7ed275 (I don't see an "Check for updates" button but it did one upon opening (fresh install after deleting several months ago, settings remained from previous install apparently).

**Comment by MikeZeDev** [comment]
Can confirm on Nightly. Its weird its only on some manga . See those two : https://i.imgur.com/VBjBUDz.png
One is working, i got the error with the other.

Now there is something strange about the network request : 

http://manganelos.com/quotnobukuni-san-quot-does-she-like-me-chapter-1
http://manganelos.com/nobukuni-san-does-she-like-me-chapter-1

Notice the "quot". Like what, "quote"? Quotation mark? 

Fist bookmark works and load a Manganelos page (in console preview)
Second doesnt work and load a MangaNATO page (always according to console preview)

Gotta update my manga list just in case.

Vermeil in Gold indeed load a manganato webpage, not a manganelos one

**Comment by GeneralUser-NonDev** [comment]
Druzai, sorry but I'm new to this, How would I apply this pull request? Running a windows version of the program, is it automatic when opened and update checked, or does it take config on my part? will the "@[code]" change or how would I tell if I have that patch?

Thanks.

**Comment by MikeZeDev** [comment]
> Druzai, sorry but I'm new to this, How would I apply this pull request? Running a windows version of the program, is it automatic when opened and update checked, or does it take config on my part? will the "@[code]" change or how would I tell if I have that patch?
> 
> Thanks.

You dont have to do anything but wait.

**Comment by Druzai** [comment]
@GeneralUser-NonDev Sorry for replying late.
This PR isn't merged yet so you have to wait for it to be merged and then you can test my changes with nightly build of HakuNeko.
