### ISSUE TITLE
[Mangapill] Connector not working

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/hakuneko#4957]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
*  Cant update manga list.  Clicking on the button clear the current list as if there was nothing.
*  Pasting a manga page doesnt work : Test with https://mangapill.com/manga/6650/planet-with
*  Viewing old manga from old manga list seems to work, oddly.

Ofc i use nightly.

**Comment by ach4ndi** [comment]
is seems mangapill limited 1000 record per query, so current implementation is not fetch all mangas. So i just modified mangapill connector to fetch per genre.
