### ISSUE TITLE
[MangaSee] Hellsing is not downloading 

### ISSUE THREAD

**Issue by fazzefazze** [manga-download/hakuneko#4962]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

Hellsing is giving me error, "Failed to fetch". Any other manga I try to download from MangaSee works fine, and I can read Hellsing on their site, so I don't know what issue it is.

1. MangaSee
2. Hellsing
3. Any volume
4. Failed to fetch

**HakuNeko (please complete the following information):**
 - 6.17

**Comment by MikeZeDev** [comment]
Cant reproduce. Tried volume 1.  Nightly.
