### ISSUE TITLE
[MangaRaw (Manga Raw Club)] Connector not working

### ISSUE THREAD

**Issue by StarOcean3** [manga-download/hakuneko#4966]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
-hakuneko able to detect new chapter..but everytime I tried to download..always give error
F12 shows "Failed to load resource: the server responded with a status of 503 ()"
-Ive tried to view the chapter through hakuneko but will give error "there was no content found.make sure it is accessible" 
-I tried to login to the actual website too but it's not working..

-I Ve make sure the chapter is available too by going to actual website..but mangaraw club always redirect it's chapter to mcreader dot net..I'm wondering if that's the problem

**To Reproduce**
1. Name of connector : MangaRaw (Manga Raw Club)
2. Name of manga (if connector update is working) :Living In This World With Cut & Paste
3. Name of chapter (if manga update is working) : 31-44
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 503 ()

**HakuNeko (please complete the following information):**
 - Nightly version, rev number master@512058
![error1](https://user-images.githubusercontent.com/113383727/189734260-e15725e4-b43e-45f1-beca-7949a0593d0c.png)

**Comment by MikeZeDev** [comment]
Cloudflare :/

**Comment by MikeZeDev** [comment]
No more problems after https://github.com/manga-download/hakuneko/pull/5239
