### ISSUE TITLE
[MangaTown] Connector not working

### ISSUE THREAD

**Issue by CidSilverwing** [manga-download/hakuneko#4968]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes. Running Windows 10 64-bit, if relevant.

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
MangaTown keeps downloading files as as 5 KB .bin files.

**To Reproduce**
1. MangaTown.
2. Any.
3. Any.
4. mjs/engine/Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\Cid Silverwing\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.mangatownonline'
(anonymous) @ mjs/engine/Connector.mjs:215
mjs/engine/Connector.mjs:579 TypeError: Cannot read property 'href' of undefined
    at MangaTownOnline._getMangas (mjs/connectors/templates/WordPressZbulu.mjs:38)
    at async MangaTownOnline._getMangaList (mjs/engine/Connector.mjs:576) MangaTownOnline
_getMangaList @ mjs/engine/Connector.mjs:579
Connector.mjs:677 GET https://zjcdn.mangahere.org/store/manga/26603/001.0/compressed/gpage_002.jpg 403
[last error repeats with every chapter]

**HakuNeko (please complete the following information):**
 - Version 6.1.7@a8da6a
![Error](https://user-images.githubusercontent.com/113474014/190003523-210e0841-6adf-4bc2-be76-5923329f4169.png)

**Comment by MikeZeDev** [comment]
Mangatown uses Mangahere CDN for some reason.

Cloudflare blocks access to images because it needs a referer to mangahere.

I can confirm that

`curl https://zjcdn.mangahere.org/store/manga/11533/001.0/compressed/j009.jpg -e http://mangahere.org `

works.

**Comment by Sheepux** [comment]
will not fix hotlinkers, use mangahere directly
