### ISSUE TITLE
[MangaKomi] Website url changed

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/hakuneko#4971]
Updating manga list doesnt work. Old mangalist still working. Preview and download still works.

I used nightly.

Error 400 on admin ajax. Maybe adding Origing and Referrer will work like for LeviatanScans ? 

https://github.com/manga-download/hakuneko/issues/4954

**Comment by Druzai** [comment]
They just changed url from `https://mangakomi.com` to `https://mangakomi.io`.

> Preview and download still works.

It works because they set up a redirect for now.
