### ISSUE TITLE
[mangaswat.co] Connector not working

### ISSUE THREAD

**Issue by NEUX1** [manga-download/hakuneko#4983]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Hi, the domain of mangaswat.co has been changed to swatmanga.me. Please change the domain of the site in the program, thank you..

**To Reproduce**
1.  swatmanga.me
2. (https://swatmanga.me/manga/urban-fairy-king/)
3. [Name of chapter (if manga update is working)](https://swatmanga.me/1397691/%d8%a7%d9%84%d9%81%d8%b5%d9%84-167-urban-fairy-king/)
4. error no manga website.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Manga list changed to https://swatmanga.me/az-list/

**Comment by TheRebel03** [comment]
Not resolved yet, right?

**Comment by MikeZeDev** [comment]
It is but you have to wait for the fix to come. Main dev are busy and have many previous changes to approve.

In the meantime you can change the url yourself by editing mangaswat.mjs with a text editor :D

**Comment by TheRebel03** [comment]
Thank you for your help, I will do it.
