### ISSUE TITLE
[ColoredManga] Connector not working

### ISSUE THREAD

**Issue by NarutoRudy** [manga-download/hakuneko#4986]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes in my personal browser, not in the HakuNeko browser, « checking if the connection is secure » https://coloredmanga.com/manga/naruto-full-colored-manga-english-digital-colored-comics-700-chapters-upscaled-version/

**Describe the bug**
Hi, no manga list in HakuNeko. Thank you.

**To Reproduce**
1. Colored Manga
2. Don’t working (if connector update is working)
3.  Don’t working (if manga update is working)
4. Manga list is loading or empty 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Can confirm. Good old Cloudflare check.

**Comment by MikeZeDev** [comment]
Apparently works on nightly now. Something changed?

**Comment by NarutoRudy** [comment]
Yes, work on nightly. I don’t know why but it’s good !
