### ISSUE TITLE
[Mangakatana] Connector not working

### ISSUE THREAD

**Issue by thevladsoft** [manga-download/hakuneko#4987]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Something changed on Mangakatana (again). Hakuneko can only download first page of any manga.

**To Reproduce**
Download any manga.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by MikeZeDev** [comment]
Relevant issue : https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13486

**Comment by DarkDiRaiZeL** [comment]
thank you so much!!!
