### ISSUE TITLE
[Site Request] comiko

### ISSUE THREAD

**Issue by suimin96** [manga-download/hakuneko#4990]
**Name of the website**
comiko

**Website urls (examples below)**
- Site: https://comiko.net/
- Manga List: https://comiko.net/browse
- Manga example: https://comiko.net/series/73496
- Chapter online viewer example: https://comiko.net/chapter/1570014

**Languages**
English

**Website relationship*
alternative (English version) of bato.to

**Comment by MikeZeDev** [comment]
No need for another batoto mirror. You can change the url to your favorite mirror in hakuneko settings.
