### ISSUE TITLE
[mangahubfr] Connector not working

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/hakuneko#4992]
I ran into 403 errors when loading chapter. Any manga.

Since i dont accept cookies on my browser, i can see the usual Cloudflare check, maybe we need more headers? 

Example : https://mangahub.fr/manga/bungaku-shoujo-to-ue-kawaku-yuurei/

**Comment by 27136773** [comment]
Related: #2933

**Comment by MikeZeDev** [comment]
No more CF
