### ISSUE TITLE
[Mangas.in] Connector problem

### ISSUE THREAD

**Issue by Heavyarms04** [manga-download/hakuneko#4993]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The list of chapters is not shown in its entirety, only the last chapters and the first

**To Reproduce**
1. MangAS.in
2. All
3. All
![16634957654581176696117384285106](https://user-images.githubusercontent.com/49253118/190896924-6ad1790a-6cbb-4a27-a845-ee5c652f9f87.jpg)

 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Its not surprising, as you need more clicks to load the rest of the chapters

https://i.imgur.com/wbKY0r8.png.

**Comment by Lenoyr** [comment]
> **Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)** Yes
> 
> **Is the website of the connector working properly / are you able to see the manga within your browser** Yes
> 
> **Describe the bug** The list of chapters is not shown in its entirety, only the last chapters and the first
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. MangAS.in
> 
>     2. All
> 
>     3. All
>        ![16634957654581176696117384285106](https://user-images.githubusercontent.com/49253118/190896924-6ad1790a-6cbb-4a27-a845-ee5c652f9f87.jpg)
> 
> 
>     * Version 6.1.7

Same problem lol

**Comment by Heavyarms04** [comment]
😢 Any solution?

**Comment by MikeZeDev** [comment]
> 😢 Any solution?

If think its fixable, but i must see with my fellow dev if i can get the source code  for it ^^
