### ISSUE TITLE
[muctau] Website Url changed

### ISSUE THREAD

**Issue by BereBereBeer** [manga-download/hakuneko#4994]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it works fine from the website/connectors list, but nothing happens after pasting the link

**To Reproduce**
1. Name of connector https://www.muctau.com/

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Url changed -> https://bibimanga.com/

@GorgoIlCane Can you please change the title to smg like [muctau] Website Url changed? Thanks
