### ISSUE TITLE
[Delitoon] Connector not working

### ISSUE THREAD

**Issue by onelots** [manga-download/hakuneko#4995]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Of course :)

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
really simple, they made an update. So far, I saw that they deleted tags (path /genre/XXXX) so hakuneko can't load anything since there is no list provided. But there are # now, maybe it could work with it ? (#comedie, #romance etc) 

**To Reproduce**
1. simply use to load manga list

**HakuNeko (please complete the following information):**
 - Version : hakuneko-dev@1.0.0

**Comment by Sheepux** [comment]
duplicate #4988
