### ISSUE TITLE
[Site Request] battwo.com

### ISSUE THREAD

**Issue by HeyyGoldfish** [manga-download/hakuneko#5000]
**Name of the website**
Bato.to

**Website urls (examples below)**
- Site: https://battwo.com/
- Manga List: https://battwo.com/browse?sort=title.az
- Manga example: https://battwo.com/series/80052
- Chapter online viewer example: https://battwo.com/chapter/1515603

**Languages**
English

**Website relationship*
alternative of bato.to 
has the same UI as bato.to
(eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by BereBereBeer** [comment]
it's included already but you have to go on the menu/settings and under BATOTO  (BY ANYCG) replace the url with your preferred one, https://battwo.com in your case

**Comment by MikeZeDev** [comment]
We dont need another Batoto Mirror, people can change the URL in settings.
