### ISSUE TITLE
[MangaKatana ] Connector not working

### ISSUE THREAD

**Issue by LunerRaies** [manga-download/hakuneko#5001]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
MangaKatana only shows 1 picture on all Chapters.

**To Reproduce**
1. Go to 'MangaKatana'
2. Click on 'any story'

**Expected behavior**
I expect to to see all picture in the chapter.

**Screenshots**
![Screenshot_2022-09-22_14-20-31](https://user-images.githubusercontent.com/83321540/191853601-de7bc152-823f-4105-9268-e9d747890a2b.png)
![Screenshot_2022-09-22_14-20-05](https://user-images.githubusercontent.com/83321540/191853597-c0728738-634d-417b-b8a8-85fbb60c931c.png)

**Context (please complete the following information):**
 - Linux Mint
 - HakuNeko Version v6.1.7

**Additional context**

**Comment by Sheepux** [comment]
duplicate #4987
