### ISSUE TITLE
[Site Request] read berserk manga online

### ISSUE THREAD

**Issue by Anak1nsama** [manga-download/hakuneko#5006]
**Name of the website**
read berserk manga online

**Website urls (examples below)**
- Site: https://readberserk.com/
- Manga List: https://ww3.readopm.com/read-manga/
l
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
single title website will not be implemented
