### ISSUE TITLE
[Site Request] Phoenixmanga

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5008]
**Name of the website**
Phoenixmanga

**Website urls (examples below)**
- Site: https://phoenixmanga.com/
- Manga List: https://phoenixmanga.com/mangas
- Manga example: https://phoenixmanga.com/manhwa/doctor-elise
- Chapter online viewer example: https://phoenixmanga.com/manhwa/doctor-elise/8

**Languages**
Spanish
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Errors 419 on manga list on firefox ..WTF

![image](https://user-images.githubusercontent.com/10671518/209122528-e277deec-cea5-46ad-a3f9-7b5f52c2147c.png)

**Comment by MikeZeDev** [comment]
Error 502, dead website?

**Comment by Lenoyr** [comment]
> Error 502, dead website?

Yes
