### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Newbei04** [manga-download/hakuneko#5009]
[**Did](url) you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**
Stuck on loading screen

**To Reproduce**

**Expected behavior**
Goto main UI

**Screenshots**
![Screenshot 2022-09-25 105244](https://user-images.githubusercontent.com/102936778/192126131-afb3963b-0044-4b13-adf8-815f5bfe5b3a.png)

**Context (please complete the following information):**
-Windows 11
 - HakuNeko Version  6.17

**Additional context**

**Comment by MikeZeDev** [comment]
Hello. If you had read the manual you would have know is a KNOWN PROBLEM and there are ways to fix that. No need to report a bug that has workarounds in the manual.

https://hakuneko.download/docs/troubleshoot/#is-the-screen-blankblack-when-starting-hakuneko

@Sheepux  pls

**Comment by Sheepux** [comment]
@MikeZeDev chill up a bit :) it happens from time to time that people are lazy/don't know how to use google when they have questions. 
Don't get to much angry, just say it's known (without caps) and that there is a guide about it.

duplicate #13

**Comment by MikeZeDev** [comment]
Well maybe caps was a bit much. I am not angry , just a bit disappointed. I was not intended to be rude. I am just too straight sometimes, my bad.
