### ISSUE TITLE
[Site Request] koushoku.org

### ISSUE THREAD

**Issue by scepticweeb** [manga-download/hakuneko#5011]
**Name of the website**
koushoku

**Website urls (examples below)**
- Site: https://koushoku.org/
- Manga List: https://koushoku.org/?order=asc&sort=id
- Manga example: https://koushoku.org/archive/9477/my-precious-girlfriend
- Chapter online viewer example: https://koushoku.org/archive/9477/my-precious-girlfriend/1

**Languages**
English

**Comment by MikeZeDev** [comment]
Duplicate : https://github.com/manga-download/hakuneko/issues/5483
