### ISSUE TITLE
[Site Request] nana.my.id

### ISSUE THREAD

**Issue by scepticweeb** [manga-download/hakuneko#5012]
**Name of the website**
nana.my.id

**Website urls (examples below)**
- Site: https://nana.my.id/
- Manga List: https://nana.my.id/
- Manga example: NONE (directly goes to reader from home page) 
- Chapter online viewer example: https://nana.my.id/reader/0bf4d82cd0ba5d8c7bd27d47d2257c3cd4577e8e

**Languages**
   English

**Comment by Pembokepp** [comment]
Has this site been permanently blocked or has the url changed please let me know

**Comment by scepticweeb** [comment]
> Has this site been permanently blocked or has the url changed please let me know

yes unfortunately the site is permanently down now, you can close this query but there is another website which is the parent of this website

issue link for that one is :

 https://github.com/manga-download/hakuneko/issues/5011#issue-1384918701  

edit: i closed this issue
