### ISSUE TITLE
[bilibili] Not downloading all pages

### ISSUE THREAD

**Issue by fatezuru** [manga-download/hakuneko#5013]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Whenever I try to download updates on Bilibili comics, the lastest chapters won't have the full images. It only downloads  two pages of the chapters.

**To Reproduce**

**Expected behavior**

**Screenshots**

![adfdff](https://user-images.githubusercontent.com/68878997/192442896-24dec96c-d05c-4c6b-871d-e37e6b29cfba.png)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by Owyn** [comment]
Same here, perhaps it's not related to login at all as ppl have been reporting in  https://github.com/manga-download/hakuneko/issues/4481

**Comment by MikeZeDev** [comment]
Can confirm the problem. But when i go to the website, only 2 pictures are fetched too. Then it keeps yelling "pls login".
Can someone confirm logging with a free account fix the problem? I mean at least on website. 

If it does i can try to fix that

**Comment by omodia** [comment]
> Can confirm the problem. But when i go to the website, only 2 pictures are fetched too. Then it keeps yelling "pls login". Can someone confirm logging with a free account fix the problem? I mean at least on website. 

Yes, it fixed the problem after logging in. The entire locked chapter is visible on the website only while logged in.

Reference #4481 and #5070.

**Comment by omodia** [comment]
Is it possible to resolve this login issue?

**Comment by MikeZeDev** [comment]
There has been a fix, use nightly.

**Comment by omodia** [comment]
### Some titles are missings
- I am using nightly, but the comics are not being downloaded even after signing in using the manual website interaction feature.
- Some titles do not appear in the list even after clicking on the refresh button.
- Example title - [Above Myriads](https://www.bilibilicomics.com/detail/mc1524). 

![1](https://user-images.githubusercontent.com/116664905/215301938-2f32fd30-3d0c-42fd-9c04-0a9fd12bfbed.png)

### This happens when trying to access a paid comic.
- When not logged in shows two pages, which is normal.
- When logged in and paid comic is unlocked, then this error pops-up while using the reader. Downloads are also not working.

![2](https://user-images.githubusercontent.com/116664905/215302353-a311e381-2f6a-4454-bd0a-d1ac7c073071.png)

**Comment by MikeZeDev** [comment]
> Some titles do not appear in the list even after clicking on the refresh button.

There is nothing i can do about that, use the clipboard feature. 

> Other problems

This is particular, for Bilibili there is automated login. Follow this exact procedure : Dont use manual interaction. **Logout**. Close hakuneko. Launch Hakuneko. Go to settings and enter you username and password under bilibili category. Chose you language too.. Get manga list and retry.

If that still doesn't work then you may come on discord, lend me your credentials so i can properly test.

**Comment by omodia** [comment]
There is no username and password column under bilibili category and I am using latest [nightly](https://github.com/manga-download/hakuneko/releases).


![1](https://user-images.githubusercontent.com/116664905/215320762-58fc0d71-b4b9-40b5-baa1-1d9e1e92b1df.png)

**Comment by MikeZeDev** [comment]
My bad then, i'll require your help for testing then.

**Comment by omodia** [comment]
> My bad then, i'll require your help for testing then.

?
I did not understand what you meant.

**Comment by MikeZeDev** [comment]
Cant test paid stuff without someone who paid. I need to use your account to make tests and fix the code. Come on discord if you want.

**Comment by Owyn** [comment]
but it's not paid tho? chapters are free if you just wait, also if you use their app

**Comment by omodia** [comment]
> Cant test paid stuff without someone who paid. I need to use your account to make tests and fix the code. Come on discord if you want.

You can also wait for free or pay for the chapters. So how to contact you on discord? Is it the same profile name - MikeZeDev.

**Comment by MikeZeDev** [comment]
I tested with free unlock chapters and it worked before :/
https://discord.com/invite/A5d3NDf there is a topic in help section

**Comment by Owyn** [comment]
It still downloads just two pages for app-only chapters, is this intended? you could at least mark those chapters differently so we don't expect it to work...

but unlocked chapters work fine now

**Comment by MikeZeDev** [comment]
Its intended, it working like the website. In the first place i didnt thought app only chapters would shown 2 images instead of nothing. No one is gonna rever engineer the app to fix that anyway.

You may open a feature request ticket for your other idea.
