### ISSUE TITLE
[LeviatanScans] Connector not working

### ISSUE THREAD

**Issue by UnusualCharge** [manga-download/hakuneko#5016]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hakuneko is unable to load any series or chapters from leviatanscans.com.  Even pasting the series URL into the clipboard gives no result.  Perhaps due to the site recently changing all the addresses from leviatanscans.com to en.leviatanscans.com.

**To Reproduce**
1. Leviatanscans
2. Any series
3. Any chapter
4. -Clicking on a bookmarked series: "getUpdatedChaptersFromWebsite Error: Failed to load "https://leviatanscans.com/" within the given timeout of 60 seconds!"
    -Clicking on the site from the connector list: "GET https://en.leviatanscans.com/wp-admin/admin-ajax.php 400
    -Pasting a series URL into the clipboard: "CLIPBOARD: https://en.leviatanscans.com/ha/manga/legend-of-the-northern-blade/ Error: No matching connector found for URL https://en.leviatanscans.com/ha/manga/legend-of-the-northern-blade/"

**HakuNeko (please complete the following information):**
 - 8.3.4

**Comment by MikeZeDev** [comment]
Duplicate of https://github.com/manga-download/hakuneko/issues/4954
