### ISSUE TITLE
[Site Request] Apolomanga

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5017]
**Name of the website**
apolomanga

**Website urls (examples below)**
- Site: https://apolomanga.com/
- Manga List: https://apolomanga.com/directorio/
- Manga example: https://apolomanga.com/ver/1
- Chapter online viewer example: https://apolomanga.com/ver/1/30

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website is dead
