### ISSUE TITLE
[Neoxscans] Connector not working

### ISSUE THREAD

**Issue by iriscelio** [manga-download/hakuneko#5021]
When I will download a chapter it gets red with exclamation, adjust this problem please!!!!
Site Name: https://neoxscans.net

**Comment by Sheepux** [comment]
do not remove templates when writing an issue.
As asked by the template give the title/chapter having the issue

**Comment by iriscelio** [comment]
Thanks Bro!!!!!

**Comment by Sheepux** [comment]
Tested with 2 titiles, working fine, user did not provide his test case. Closing
