### ISSUE TITLE
[Softkomik] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5022]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
![image](https://user-images.githubusercontent.com/112748173/192942990-f29f3630-af52-49ad-b1b3-f3b09285ca2c.png)

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Url changed to https://animeyusha.com/

**Comment by MikeZeDev** [comment]
Animeyusha is down?

**Comment by MikeZeDev** [comment]
Softkomik.com is geoblocked .

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4612
