### ISSUE TITLE
[Site Request] Drake Scans

### ISSUE THREAD

**Issue by alen098098** [manga-download/hakuneko#5026]
**Name of the website**
Drake Scans

**Website urls (examples below)**
- Site: https://drakescans.com/
- Manga List: https://drakescans.com/comics/
- Manga example: https://drakescans.com/series/without-a-daoist-partner-i-will-die/
- Chapter online viewer example: https://drakescans.com/series/without-a-daoist-partner-i-will-die/chapter-00/

**Languages**
English

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5138
