### ISSUE TITLE
[saikaiscan] Connector not working

### ISSUE THREAD

**Issue by iriscelio** [manga-download/hakuneko#5036]
The site does not connect anymore!!!!!

Site New: saikaiscan.com.br/home

**Comment by MikeZeDev** [comment]
To be precise,  cant update manga list nor use clipboard. "textcontent not fund in console", most likely a website change.
I ofc use nightly.

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/commit/f6d1d778b372d2cd7b791daa09074258c6d0d9b2
