### ISSUE TITLE
[Mangahub] Connector not working (Can't update API key error)

### ISSUE THREAD

**Issue by manikkuge-saumyadasa** [manga-download/hakuneko#5040]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)*
yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
After downloading around 10 chapters I get a error saying "MangaHub: Can't update the API KEY!"

**To Reproduce**
1. Name of connector = Mangahub
2. Name of manga (if connector update is working) = All

**Screenshots**
<img width="1839" alt="Screenshot 2022-10-03 at 21 46 28" src="https://user-images.githubusercontent.com/110282720/193632672-57418f78-16c9-4673-b895-0efff834c8e3.png">

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by MikeZeDev** [comment]
Did the same, There is a rate limit apparently.

**Comment by manikkuge-saumyadasa** [comment]
> Did the same, There is a rate limit apparently.

But like apparently after some you can download some chapters again

**Comment by MikeZeDev** [comment]
This is how rate limits works.  Not sure if throttling would help?
