### ISSUE TITLE
[少年ジャンプ＋ (Shonen Jump +)] Connector not working

### ISSUE THREAD

**Issue by nERD8932** [manga-download/hakuneko#5043]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector for Shonen Jump Plus is not displaying a particular manga

**To Reproduce**
Search for 僕のヒーローアカデミア on the 少年ジャンプ＋ (Shonen Jump +) connector.

Series and chapter to test: https://shonenjumpplus.com/episode/10833519556325021790

Version: master@faa335

**Comment by zerobkpro** [comment]
you can use copy and paste link. :)

**Comment by MikeZeDev** [comment]
It works, 🤷 
![image](https://github.com/manga-download/hakuneko/assets/10671518/eb26c8f7-99f5-472f-a19c-d497af0bc58a)
