### ISSUE TITLE
[Site Request] manhuadb

### ISSUE THREAD

**Issue by DittoJy** [manga-download/hakuneko#5045]
**Name of the website**
漫画DB

**Website urls (examples below)**
- Site: https://www.manhuadb.com
- Manga List: https://www.manhuadb.com/manhua/list.html
- Manga example: https://www.manhuadb.com/manhua/25931
- Chapter online viewer example: https://www.manhuadb.com/manhua/25931/31275_312674.html

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
duplicate #3477
