### ISSUE TITLE
[週刊ヤングジャンプ] Weekly Young Jump 

### ISSUE THREAD

**Issue by zerobkpro** [manga-download/hakuneko#5047]
**Name of the website**
Weekly Young Jump (週刊ヤングジャンプ)
**Website urls (examples below)**
- Site: https://ynjn.jp/
- Manga List: https://ynjn.jp/titles/label?d=268
                     https://ynjn.jp/titles/label?d=253
                     https://ynjn.jp/titles/label?d=27
                     https://ynjn.jp/titles/label?d=254
                     https://ynjn.jp/titles/label?d=161
                    https://ynjn.jp/titles/label?d=31
- Manga example: https://ynjn.jp/title/109
- Chapter online viewer example: https://ynjn.jp/viewer/109/13670?cid=13670

**Languages**
Japan

**Comment by Elastic1** [comment]
Template >> SpeedBinb

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5146
