### ISSUE TITLE
[https://reaperscans.com/] Connector not working/ Site is changed

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#5048]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
They changed their website with the same domain name.

**To Reproduce**
1. Reaper Scans
2. Update connector (not working)

New Website Links:
Website: https://reaperscans.com/

Manga Section: https://reaperscans.com/comics
Manga Page: https://reaperscans.com/comics/5984-absolute-sword-sense
Manga Chapter: https://reaperscans.com/comics/5984-absolute-sword-sense/chapters/43757903-chapter-1

Novels Section: https://reaperscans.com/novels
Novel Page: https://reaperscans.com/novels/7019-21st-century-archmage
Novel Chapter: https://reaperscans.com/novels/7019-21st-century-archmage/chapters/51546995-chapter-190

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Website changed. All reaperscans languages connectors doesnt work anymore: English, french, portuguese, etc....

https://reaperscans.com/wp-admin/admin-ajax.php gives a 405 error.

Edit :  Cloudflare on admin ajax.

**Comment by MikeZeDev** [comment]
See also https://github.com/manga-download/hakuneko/issues/5032

**Comment by MikeZeDev** [comment]
You can easily fetch all mangas. /comics?page=1.

You **cant** use the same method to get chapters as for some reasons the last page will always be empty of chapters (you'll miss first chapters basically).

Digging further : 

They changed their stuff and use Livewire.js as a way to dynamically display manga list and chapters lists. 
Basically, you POST json to the dynamic endpoint (end of url change for every session) and it return the html with what we need.

Model of the JSON to be posted is in the webpage as <div wire;id="garbage" wire:initial-data:"thejson". I assume you can mess with it to get next pages. Its full of hashes, checksums and stuff tho. The end of the url to use can be seen in the JSON.
`        uri = new URL('/livewire/message/frontend.'+ body.fingerprint.name, this.url)` (body being the json object)

I was fiddling with request parameters then i was stopped by Cloudflare. Now i get 403 everywhere.

What an interesting website.

**Comment by MikeZeDev** [comment]
Other reapers website use Madara or custom stuff, they not longer depends on the main reaperscans.

**Comment by MrsLucifer** [comment]
For hakuneko, .msj needs to be made from scratch. reminder...

**Comment by tsentered** [comment]
Reaper Scans still not working. No chapters and When hitting update/refresh  the titles disappear.

**Comment by MikeZeDev** [comment]
I fixed it but they added cloudflare now :/

**Comment by MikeZeDev** [comment]
Website works again
