### ISSUE TITLE
[Pixiv] Connector not working

### ISSUE THREAD

**Issue by HillLiVys** [manga-download/hakuneko#5049]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I copied the link of a manga to clipboard but it didn't show me any chapters  (another mangas also had this trouble). I loaded pixiv in system but it just gave me a list and didn't show any chapters too

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
For example: https://comic.pixiv.net/works/7500
**Screenshots**
![image](https://user-images.githubusercontent.com/96725388/194684204-6113c3ef-d0d8-4b9d-a0e2-f6ec8c33b3eb.png)
![image](https://user-images.githubusercontent.com/96725388/194684277-b8bff83c-b243-42dc-8114-0a0e9cc030bf.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
You said you copied a link but i dont see any link in your issue, therefore no one can test it :)

**Comment by HillLiVys** [comment]
> You said you copied a link but i dont see any link in your issue, therefore no one can test it :)

I just gave the example link up there. Besides, from the picture I sent, I copied a link of a random manga and it even didn't load that link

**Comment by junk-labs** [comment]
API changed from v4 to v5.
_getChapters needs to be reworked.
