### ISSUE TITLE
[TuMangaOnline] Connector not working, please try to fix it 

### ISSUE THREAD

**Issue by JonZotto** [manga-download/hakuneko#5050]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

https://lectortmo.com (TuMangaOnline)

The problem is related to getting the reader pics.

The connector is not working. The problem started several months ago, sometimes I could download sometimes not. After those months I have not been able to download or even preview the chapter pages.

Initially, HN was capable to read list of chapters of titles (NOW NOT ANYMORE), but when try to "preview" or "download" a chapter, will appear text like:
ReferenceError: $ is not defined
at :5:36

Now if you load the website in hakuneko, you will see a "cloudflare's compatibility browser check" page. If you try solve the gacha, it only gets in a loop of "gacha solve" page.
They also were using something like "concurrent and sequential downloads" check.

**Screenshots**
![166610463-cbed2187-569d-4ce8-a058-b8492413f980](https://user-images.githubusercontent.com/76739108/194684946-e1eeddfc-f69e-47c5-947e-4345b3e0f7a4.png)

![165631570-cd4f8179-14ed-463a-8072-d877bba008ce](https://user-images.githubusercontent.com/76739108/194684949-acc02b05-a592-4fd4-9abd-d5eab77ef044.png)

![165880017-26e76326-fe93-45aa-a342-33dbe9fb90c5](https://user-images.githubusercontent.com/76739108/194685405-20e529c3-23eb-4141-8301-e5128458679b.png)

![167253582-2120bef5-2b59-4ca1-a445-6eb2b6cec5ca](https://user-images.githubusercontent.com/76739108/194685415-d5811c69-a42b-4e87-8b84-d552b9b2cf0d.png)

![167253610-4bad941d-3697-4873-acf7-927e4130ba4a](https://user-images.githubusercontent.com/76739108/194685420-536da6fa-8bc3-41b0-84bf-11c1c85feb21.png)

**HakuNeko (please complete the following information):**

- OS: Windows 10
- HakuNeko Version 6.1.7

**Comment by MikeZeDev** [comment]
1) Duplicate https://github.com/manga-download/hakuneko/issues/4622. No need to open another issue :)
2) This cloudflare issue, with captcha, is a well known issue due to an Electron bug and cant be fixed by HN dev. This is one of the main reason they work on Haruneko, HN successor.
