### ISSUE TITLE
[Piccoma FR] Connector not working

### ISSUE THREAD

**Issue by Blackfairie** [manga-download/hakuneko#5052]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Doesn't work

**To Reproduce**
1. Piccoma France
2. All manga
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Describe the bug
> Doesn't work

Thats not very helpfull. What did you do? :D

**Comment by MikeZeDev** [comment]
Tried pasting this https://fr.piccoma.com/fr/product/437. Chapter 7 isnt paid so i cant download, Chapter 1 works 

https://i.imgur.com/JN2LQXV.png

Everything seems to work as intended. I can't test paid chapters obviously :D

For reference i use Nightly build.

**Comment by Blackfairie** [comment]
Can we talk on discord it will be more easy for me. This is my id:
Blackfairies#7951

**Comment by MikeZeDev** [comment]
Feel free to come on HN discord .

**Comment by Blackfairie** [comment]
![image](https://user-images.githubusercontent.com/115415720/194783016-7ecc63b7-3886-45ce-b2e0-c9871f25f851.png)

I don't see chapters

**Comment by Ever4engel** [comment]
![image](https://user-images.githubusercontent.com/47645041/194784405-a5e8087f-619b-4f9c-a091-455941e54c75.png)
Wrong place

**Comment by Blackfairie** [comment]
where then

**Comment by MikeZeDev** [comment]
https://hakuneko.download/docs/FAQ/#copy-and-paste

Straight from the manual ^^

**Comment by Blackfairie** [comment]
Thank you, it was working on nightly and I was doing it wrong, thank you for your help.

**Comment by Blackfairie** [comment]
I'm already on your discord, but i wanna talk with you directly in private
chat. It's better than gmail.
