### ISSUE TITLE
Request for Happymh 

### ISSUE THREAD

**Issue by Machochita** [manga-download/hakuneko#5053]
**Name of the website**
Happymh

**Website urls (examples below)**
- Site: https://m.happymh.com
- Manga List: https://m.happymh.com/latest
- Manga example: https://m.happymh.com/manga/cangfeng
- Chapter online viewer example: https://m.happymh.com/reads/cangfeng/2944127

**Languages**
Chinise

**Website relationship*
sometimes, with the new chapters, they reupload cocomanga and baizimh chapters, although after a while they update them and upload the original raws.

**Additional details**
It is a Chinese web page, where you can extract free raw without watermark, although some chapters are extracted from other pages such as cocomanga or baozimh

**Comment by MikeZeDev** [comment]
It is already requested two times :)
Duplicate https://github.com/manga-download/hakuneko/issues/3390
