### ISSUE TITLE
[mangareader.to] Volume download doest work

### ISSUE THREAD

**Issue by Chiefbrake** [manga-download/hakuneko#5054]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I can't download manga in Volumes from mangareader.to connector. It's all good on site's side, but when i try to download volume, it always times out. Chapters on other hand are downloading easier

**To Reproduce**
1. Go to mangareader.to connector (i'm not sure if there are any other connector with volumes to download)
2. Click on Naruto (that's where i encountered a problem, but i think it works with everything else too)
3. Try to download VOL 1 (EN)
4. It will timeout, but if you try to download any chapter, it will download correctly

My guess that it's something with the timeout feature and increased size of volumes, compared to chapters. Is there any way to increase time for timeout manually?

**Context:**
 - OS: Windows 7
 - HakuNeko Version 6.17

**Comment by MikeZeDev** [comment]
Confirmed on nightly too. Preview doesnt work either.
