### ISSUE TITLE
[Site Request] Bilibili Comics France

### ISSUE THREAD

**Issue by Blackfairie** [manga-download/hakuneko#5055]
**Name of the website**
Bilibili Comics France

**Website urls (examples below)**
- Site: https://www.bilibilicomics.com/
- Manga List: /
- Manga example: https://www.bilibilicomics.com/detail/mc2007?from=manga_search
- Chapter online viewer example: https://www.bilibilicomics.com/mc2007/185357?from=manga_detail

**Languages**
French (available in other language)

**Website relationship*
Website have diffrent language in the same website.

**Additional details**
/

**Comment by Darkmaster006** [comment]
You can get them with the Clipboard function. But only the ones freely available without clicking, it seems. That is, from that one, you can get til c12, sadly.
