### ISSUE TITLE
[Piccoma FRANCE] Connector not working

### ISSUE THREAD

**Issue by Blackfairie** [manga-download/hakuneko#5056]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The login doesn't work for paid chapter.

**To Reproduce**
1. Piccoma FR
2. Name of manga All
3. Name of chapter /
4. Error: The chapter '#4 Ce genre d'ambiance…' is neither public, nor purchased!
    at PiccomaFR._getPages (PiccomaFR.mjs:42)
    at async PiccomaFR._getPageList (Connector.mjs:615) EventTarget {manga: EventTarget, id: "424/26191", title: "#4 Ce genre d'ambiance…", file: {…}, language: undefined, …}manga: EventTarget {connector: PiccomaFR, id: "424", title: "Oups, j'ai séduit le héros !", status: "available", chapterCache: Array(21), …}id: "424/26191"title: "#4 Ce genre d'ambiance…"file: {name: "#4 Ce genre d'ambiance…", extension: "", full: "#4 Ce genre d'ambiance…"}language: undefinedstatus: "failed"pageProcess: falsepageCache: []__proto__: EventTarget
_getPageList @ Connector.mjs:618
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:111
Promise.then (async)
getPages @ Chapter.mjs:109
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49

**Screenshots**
![image](https://user-images.githubusercontent.com/115415720/194946931-ae9a93a8-b2de-4516-b169-34b5df5c35f4.png)

**HakuNeko (please complete the following information):**
 - Version nightly [e.g. 6.17]

**Comment by MikeZeDev** [comment]
It has been reported today not working on paid chapters. And there are cases of scrambled pictures. The fix worked fine when i reviewed it, on free stuff ofc.

**Comment by Elastic1** [comment]
It is a problem of getting the volume list. (I forgot to test with volume URLs and volume-only manga🤦)

**Comment by MikeZeDev** [comment]
`line 50       const result = await this.fetchJSON(request);`

If i try to get a chapter i didnt pay for ("wait until free"), this line throw an error (the answer is not json). so we never reach the error handling
```
        if (images == null) {
            throw new Error(`The chapter '${chapter.title}' is neither public, nor purchased!`);
        }
```

You may want to properly handle it.

And just a detail : Hakuneko order chapters from the last to the first usually. You should put a reverse() in getchapters

```
        return episodes.map(ep => {
            return {
                id: `${nextData.buildId}/fr/viewer/${productId}/${ep.id}`,
                title: ep.title,
            };
        }).reverse();
```
I guess the scrambled picture was because the user tried chrome devtools, dont bother.

**Comment by Blackfairie** [comment]
Thank you very much it works well for Manga Volume ! 
![image](https://user-images.githubusercontent.com/115415720/205709776-1c2d87cc-65c3-4a07-b433-142d4adff793.png)
