### ISSUE TITLE
[Site Request] allanime.site

### ISSUE THREAD

**Issue by ulqi0rra** [manga-download/hakuneko#5058]
**Name of the website**
allanime.site

**Website urls (examples below)**
- Site: https://allanime.site/
- Manga List: https://allanime.site/manga or https://allanime.site/search-manga
- Manga example: https://allanime.site/manga/cjWQvrZpvRYekrCBJ/Maou_App_de_S_kyuu_Hunter_ni_Naremashita
- Chapter online viewer example: https://allanime.site/manga/cjWQvrZpvRYekrCBJ/Maou_App_de_S_kyuu_Hunter_ni_Naremashita/chapters/sub/27

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5058

**Comment by MikeZeDev** [comment]
You posted it twice in 5 minutes and the template is not even properly filled :D

**Comment by ulqi0rra** [comment]
> 

sorry,first time doing this

**Comment by ulqi0rra** [comment]
the website name is allanime.site 
the website url is https://allanime.site/manga

**Comment by Sheepux** [comment]
I've updated everything (i was in a good mood), please make sure  to take 2 minute to read what's written in the templates when creating issues.

**Comment by MikeZeDev** [comment]
There is a GraphQL api underneath. Not sure if directly accessible. All request comes with a sha256 hashMAC. We are to figure out what is the key and what is actually hashed. 

https://www.apollographql.com/docs/react/api/link/persisted-queries/

**Comment by MikeZeDev** [comment]
So, apparently the query is hashed but not the parameters, which means its usable.

**Comment by ulqi0rra** [comment]
So if its usable does that mean it can be made availale on hakuneko as an extension Sent from Mail for Windows From: MikeZeDevSent: Wednesday, November 23, 2022 1:10 PMTo: manga-download/hakunekoCc: ulqi0rra; AuthorSubject: Re: [manga-download/hakuneko] [Site Request] allanime.site (Issue #5058) So, apparently the query is hashed but not the parameters, which means its usable.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by MikeZeDev** [comment]
Yes. I am working on two connectors : one for animes and one for mangas. Do not expect much for the anime one. The site use multiple sources and depending on the source preview / download would not work.

**Comment by ulqi0rra** [comment]
Thank you Sent from Mail for Windows From: MikeZeDevSent: Wednesday, November 23, 2022 7:13 PMTo: manga-download/hakunekoCc: ulqi0rra; AuthorSubject: Re: [manga-download/hakuneko] [Site Request] allanime.site (Issue #5058) Yes. I am working on two connectors : one for animes and one for mangas. Do not expect much for the anime one. The site use multiple sources and depending on the source preview / download would not work.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
