### ISSUE TITLE
FIXED : App not working with latest version installed

### ISSUE THREAD

**Issue by makavli** [manga-download/hakuneko#5061]
Hey, 
This is my first time posting an issue, I hope I did it right. 

When I try to open the app, it looks for updates then it blocks on a blank page.

I tried launching it on terminal, this is the error I got. 

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default

--------------
Framework Info
--------------
Electron : 6.1.7
Chrome   : 76.0.3809.146
Node     : 12.4.0

-------------
Configuration
-------------
Update URL           : https://manga-download.github.io/hakuneko/6.1.7/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : C:\Users\MAKA\AppData\Local\hakuneko-desktop\cache
UserData Directory   : C:\Users\MAKA\AppData\Roaming\hakuneko-desktop

 2022-10-13T13:03:12.963Z <ERROR>    Update Failed! Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'

Thank you in advance.

Regards,

**Comment by Sheepux** [comment]
Try to use hakuneko nightly
try to browse the update url with your standard browser. It looks like your computer is rejecting the network connection to this url.

**Comment by makavli** [comment]
> Try to use hakuneko nightly try to browse the update url with your standard browser. It looks like your computer is rejecting the network connection to this url.

Thank you for your reply.

I already tried the nightly, same thing.I had also tried browsing the update url, it downloads smth called latest, but it doesnt have any extension.

**Comment by makavli** [comment]
Hey guys,

The problem is fixed. I executed the program with admin rights and it worked.

**Comment by Sheepux** [comment]
you probably have a firewall/antivirus that is blocking something. If you have one try to whitelist the executable. Runing it with administrators rights could be dangerous if a connector were to fail it's sandboxing.

**Comment by makavli** [comment]
> you probably have a firewall/antivirus that is blocking something. If you have one try to whitelist the executable. Runing it with administrators rights could be dangerous if a connector were to fail it's sandboxing.

Thank you for your help.
I just did it. It worked perfectly.
