### ISSUE TITLE
[ManhuaScan.io] Connector not working

### ISSUE THREAD

**Issue by BereBereBeer** [manga-download/hakuneko#5067]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
clipboard tries to load for a bit before giving up, but titles from the same site (or manhuascan.com) I had in my bookmarks work perfectly fine

**To Reproduce**
1. [manhuascan.io](https://manhuascan.io/)
2. all titles
3. /
4. ClipboardConnector.mjs:66 CLIPBOARD: https://manhuascan.io/manga-19-days.html TypeError: Cannot read property 'content' of undefined
    at ManhuaScan._getMangaFromURI (FlatManga.mjs:28)
    at async hakuneko:/cache/mjs/connectors/system/ClipboardConnector.mjs:64
    at async Promise.all (index 0)

**HakuNeko (please complete the following information):**
 - Version Nightly

**Comment by MikeZeDev** [comment]
Website changed layout, updating manga list doesnt work anymore too.
