### ISSUE TITLE
[Pixiv] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#5069]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No chapters are listed no matter which manga you pick. Even copy and pasting URLs doesn't work.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.1.7]

**Comment by MikeZeDev** [comment]
Just tested on nightly, it works. Can you please link a manga that doesnt work?

**Comment by Druzai** [comment]
This can happen with some works if you're not logged in to pixiv in HakuNeko. Maybe that's the case?
Also which connector? `Pixiv Comics` or `Pixiv (Artwork)`

**Comment by Druzai** [comment]
I seem to have found a problem with the `Pixiv (Artwork)` connector.
If manga has less than 5 chapters, no chapters will be found.
For example this works: https://www.pixiv.net/user/46393/series/166519
But this doesn't work: https://www.pixiv.net/user/46393/series/183896

I've made a PR (#5433) to fix it. Maybe it can resolve this issue.
