### ISSUE TITLE
[Feature] Bilibili unlocked chapters

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#5070]
**Is your feature request related to a problem? Please describe.**
A way to download the "blocked" chapters in Bilibili.
For example: https://www.bilibilicomics.com/detail/mc1678
With Hakuneko, one can only download until chapter 16, normally. Then, chapter 17 onwards, you have to click (on the website) "continue" so that it unlocks a chapter (and you have waiting times to unlock more and more chapters, and so on). Is there any way to unlock these chapters inside Hakuneko (or somehow login to Bili with an account with the unlocked chapters) and get them?

**Describe the solution you'd like**
Be able to login or somehow make Hakuneko login into an account with chapters unlocked or to unlock chapters.

**Context (please complete the following information):**
Hakuneko rev. master@9f21ea

**Comment by Sheepux** [comment]
duplicate #4481
