### ISSUE TITLE
[Manganato] Connector not working/ Url changed for some titles

### ISSUE THREAD

**Issue by BereBereBeer** [manga-download/hakuneko#5072]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
to be precise mangakakalot redirected me to manganato.
some manga still have the original working urls others changed to chapmanganato.com

**To Reproduce**
1. [Manganato](https://manganato.com/)
2. https://chapmanganato.com/manga-ba979135

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
perhaps all chapters are available on the new domain ?

**Comment by BereBereBeer** [comment]
I just tried changing a manganato url, I think you are right, it turns back to say manganato but at least works, the other way around gives me a 404

**Comment by MikeZeDev** [comment]
Not sure why you mentioned mangakakalot but its still mangakakalot.com. 

Manganato **chapters** are now on chapmanganato.com, but everything works on nightly. I just updated manga list an i am able to preview stuff.

**Comment by UnknownLink** [comment]
> Not sure why you mentioned mangakakalot but its still mangakakalot.com.

Mangakakalot also redirects to chapmanganato, for example just as linked in the steps to reproduce but for that domain.

1. [mangakakalot.com](https://mangakakalot.com) Same search for JJK
2. [https://readmanganato.com/manga-ba979135](https://readmanganato.com/manga-ba979135) Redirects to readmanganato (Can be used in hakuneko)
3. [https://chapmanganato.com/manga-ba979135](https://chapmanganato.com/manga-ba979135) Then redirects to the same as linked above (Cannot/No matching connector found for url)

- Version 6.17

**Comment by MikeZeDev** [comment]
JJK on Kakalot send you to manganato, indeed. While other on front page still on mangakalot like https://mangakakalot.com/manga/xj929592.

What a dirty mess.

**Comment by Sheepux** [comment]
in such case if the domain is different we could add a warning saying "This title is hosted in another domain <domain> you will have to use the adequate connector"

**Comment by MikeZeDev** [comment]
Yet, JJK works on nightly on Mangakakalot.com. I updated the manga list to make sure.

https://i.imgur.com/366NiD4.jpeg

Tried first chapter, second, last one, it works.
