### ISSUE TITLE
Animixplay

### ISSUE THREAD

**Issue by Abrahamcrewz** [manga-download/hakuneko#5077]
**Animixplay**

- Site: https://animixplay.to/
- Manga List: https://animixplay.to/list
- Manga example: https://animixplay.to/v1/muv-luv-alternative-2nd-season/ep3
- Chapter online viewer : https://animixplay.to/anime/50638

**Languages**
List of languages supported by the website
multi language
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/3919
