### ISSUE TITLE
[Site Request] siyahmelek.net

### ISSUE THREAD

**Issue by nacht3k** [manga-download/hakuneko#5078]
**Name of the website**
siyahmelek.net

**Website urls**
- Site: https://siyahmelek.net/
- Manga List: https://siyahmelek.net/seri/
- Manga example: https://siyahmelek.net/seri/madam/
- Chapter online viewer example: https://siyahmelek.net/seri/madam/bolum-1/

**Languages**
Turkish

**Comment by MikeZeDev** [comment]
Site is already supported, url need to be changed to .net
