### ISSUE TITLE
[Mangaworld] Connector not working

### ISSUE THREAD

**Issue by soymuchocalor** [manga-download/hakuneko#5080]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
mangaworld changed domine www.mangaworld.in to www.mangaworld.so

**To Reproduce**
It is just a change of domine

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5135
