### ISSUE TITLE
[Site Request] Muslosnosekai

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5082]
**Name of the website**
Muslosnosekai

**Website urls (examples below)**
- Site: https://muslosnosekai.blogspot.com/
- Manga List: https://muslosnosekai.blogspot.com/search/label/Update
- Manga example: https://muslosnosekai.blogspot.com/2022/09/una-historia-sobre-un-dragon-y-el.html
- Chapter online viewer example: https://muslosnosekai.blogspot.com/2022/09/cap-10_29.html

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
dead
