### ISSUE TITLE
[lezhinus.com] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5084]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
A new chapter (Hiatus) notice is not displaying on Hakuneko for a Lezhin Series.

**To Reproduce**
1. Open Hakuneko 
2. Load 'The Pawn's Revenge' from your Bookmarks - https://www.lezhinus.com/en/comic/pawn
3. The chapter, Notice: Hiatus is missing in Hakuneko to download.

**Screenshots**
This chapter is missing from Hakuneko
<img width="742" alt="Screen Shot 2022-10-24 at 2 23 43 pm" src="https://user-images.githubusercontent.com/114213739/197442553-898c0634-e804-4ae4-bda3-10d4d0591958.png">

**HakuNeko (please complete the following information):**
 - Version 6.1.7

I'm hoping this only effects this chapter & not future downloads for this series.

**Comment by ghost** [comment]
Okay, it isn't just this series but Lezhin has been so annoying with Hakuneko. Some series take ages to update the chapter listings & I have to keep re-opening hakuneko. Takes me about 20 minutes now for doing 7 series.

**Comment by Sheepux** [comment]
duplicate #4433
