### ISSUE TITLE
[kuaikanmanhua] Connector not working

### ISSUE THREAD

**Issue by deyvisgt93** [manga-download/hakuneko#5086]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The last chapters published in kuaikanmanhua.com are not updated in HakuNeko, to avoid errors enter both in my browser and in the internal browser of HakuNeko and in both if the published chapters are seen, but when I put it to download, no update is displayed so I can not download it, and that applies to all series within kuaikanmanhua.com, I hope you can repair this error, I appreciate your attention and work.

**To Reproduce**
1. kuaikanmanhua
2. 从大树开始的进化
3. 15, 16
4. 

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**¿Ha leído [la guía de solución de problemas](https://hakuneko.download/docs/troubleshoot/)**
Sí

**¿Funciona bien la página web del conector / puedes ver el manga en tu navegador**?
Sí

**Describa el fallo
Los últimos capítulos publicados en kuaikanmanhua.com no se actualizan en HakuNeko, para evitar errores entra tanto en mi navegador como en el navegador interno de HakuNeko y en ambos si se ven los capítulos publicados, pero cuando lo pongo a descargar, no aparece ninguna actualización por lo que no puedo descargarlo, y eso se aplica a todas las series dentro de kuaikanmanhua.com, espero que puedan reparar este error, agradezco su atención y trabajo.

**Reproducir**
Pasos para reproducir el comportamiento:
1. kuaikanmanhua
2. 从大树开始的进化
3. 15, 16
4. 

**HakuNeko (por favor, complete la siguiente información):**
 - Versión [por ejemplo, 6.17]

**Comment by MikeZeDev** [comment]
Hum, all i can get is this https://i.imgur.com/CE5DgNE.png, anyone knows what it means? 

I bet its something to do with referer, i see a referer mention in cookies

**Comment by kiryuxD** [comment]
it seems that the connector for kuaikanmanhua has been removed, so it does not find the link to the website and therefore can not be downloaded, I do not know if it was removed by mistake, if so, you can upload it again?

**Comment by MikeZeDev** [comment]
> kuaikanmanhua

Its still here on Nightly at least.

**Comment by kiryuxD** [comment]
> > kuaikanmanhua
> 
> Its still here on Nightly at least.

if it is on localhost but apparently, the app does not recognize it or is scraping it from the github server, I don't know how the app really works but it is my guess.
![haku](https://user-images.githubusercontent.com/10092594/199560433-f4f0f203-eeae-4b61-9445-418a8245a418.png)
