### ISSUE TITLE
proxy in hakuneku

### ISSUE THREAD

**Issue by hellojonas** [manga-download/hakuneko#509]
how to use porxy in hakuneku? i very confused with this.
I dont understand what proxy rules is and how to use it in hakuneku,
the only thing i know about proxy is domain and ports

**Comment by 27136773** [comment]
The tooltip gave some examples.
Proxy rules are not a concept of HakuNeko, the tooltip provides an URL with further information.

**Comment by hellojonas** [comment]
thanks, huge help
