### ISSUE TITLE
[Site Request] Raikiscan

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5091]
**Name of the website**
Raikiscan

**Website urls (examples below)**
- Site: https://raikiscan.com/
- Manga List: https://raikiscan.com/manga/
- Manga example: https://raikiscan.com/manga/el-mayordomo-mas-fuerte-del-mundo/
- Chapter online viewer example: https://raikiscan.com/el-mayordomo-mas-fuerte-del-mundo-capitulo-6/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already added . @Sheepux  pls
