### ISSUE TITLE
[Site Request] Kawascans.com

### ISSUE THREAD

**Issue by TKCeegit** [manga-download/hakuneko#5094]
**Name of the website**
Kawa Scans

**Website urls (examples below)**
- Site: https://kawascans.com/
- Manga List: https://kawascans.com/manga/
- Manga example: https://kawascans.com/manga/king-golf/
- Chapter online viewer example: https://kawascans.com/manga/king-golf/16/154/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Wordpress Mangastream, but since website seems broken itself, i cant try further than listing chapters.

**Comment by MikeZeDev** [comment]
Added by https://github.com/manga-download/hakuneko/pull/5138
