### ISSUE TITLE
[Site Request] Chapmanganato

### ISSUE THREAD

**Issue by hind-sagar-biswas** [manga-download/hakuneko#5095]
**Chapmanganato**
chapmanganato

**Website urls**
- Site: https://chapmanganato.com/
- Manga example: https://chapmanganato.com/manga-pm992369
- Chapter online viewer example: https://chapmanganato.com/manga-pm992369/chapter-24

**Languages**
Dont know

**Website relationship**
related to manganato.com and mangakakalot.com

**Comment by MikeZeDev** [comment]
Manganato chapters now are on chapmanganato.com but its still manganato.com (for manga lists)

Better opening an issue "Manganato : not working" and fix manganato to handle the chapters url.

Or i am wrong again. What a mess.

Edit : Use manganato, its working on nightly build. Can be closed @Sheepux  <3

**Comment by hind-sagar-biswas** [comment]
> 

@MikeZeDev but when i tried to copy chapmanganato link and tried clipboard option, it didn't work
