### ISSUE TITLE
[Site Request] Legion scans

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5096]
**Name of the website**
Legion scans

**Website urls (examples below)**
- Site: https://legionscans.com/
- Manga List: https://legionscans.com/manga/
- Manga example: https://legionscans.com/manga/el-domador-de-cargas-de-un-grupo-de-rango-s-desperte-mi-verdadero-poder-al-hacer-que-mataran-a-mi-familiar/
- Chapter online viewer example: https://legionscans.com/manga/el-domador-de-cargas-de-un-grupo-de-rango-s-desperte-mi-verdadero-poder-al-hacer-que-mataran-a-mi-familiar/capitulo-12/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Added by https://github.com/manga-download/hakuneko/pull/5138
