### ISSUE TITLE
[Site Request] LegionAsia

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5097]
**Name of the website**
LegionAsia

**Website urls (examples below)**
- Site: https://legionasia.com
- Manga List: https://legionasia.com/manga/
- Manga example: https://legionasia.com/manga/la-verdadera-hija-ha-vuelto/
- Chapter online viewer example: https://legionasia.com/capitulo-30-107/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Exist and works. Can be closed @Sheepux pls <3
