### ISSUE TITLE
[Early Manga] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#5099]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes but a bit slow

**Describe the bug**
Update not working and chapters not populating.

**To Reproduce**
1. Name of connector - Early Manga
2. Name of manga (if connector update is working) - NA
3. Name of chapter (if manga update is working) - NA
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - Screenshot easier.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

<img width="1124" alt="Screen Shot 2022-10-28 at 10 14 44 AM" src="https://user-images.githubusercontent.com/70929406/198696684-bb035c14-e832-402e-ad4f-8b68007d1660.png">
<img width="1391" alt="Screen Shot 2022-10-28 at 10 18 22 AM" src="https://user-images.githubusercontent.com/70929406/198696799-e3251c8b-a98a-4ba9-b089-cd23f78397b9.png">
**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by tsentered** [comment]
The site has a new version and I also noticed that the earlymng.org is being redirected to earlym.org./home. Hope this helps.

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/commit/f3a1289213fd9c92cb1d04606957d2fc20bd1c16
