### ISSUE TITLE
[Site Request] Scan Hentai.Menu

### ISSUE THREAD

**Issue by Franck3173** [manga-download/hakuneko#5100]
**Name of the website**
Scan Hentai.Menu

**Website urls (examples below)**
- Site: https://scan.hentai.menu
- Manga List: https://scan.hentai.menu/manga/
- Manga example: https://scan.hentai.menu/manga/maitresse/
- Chapter online viewer example: https://scan.hentai.menu/manga/maitresse/maitresse/chapitre-35/

**Languages**
French

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
WordPress Madara with a referer check. But i still have problems i cant get images.

**Comment by Kiwi-ma** [comment]
Bonjour, Serait-il possible de configurer ce site en FR car il ne fonctionne pas sur Haku-Neko ?

https://scan.hentai.menu/manga/

Merci d'avance,
Cordialement.

**Comment by Sheepux** [comment]
Pour signaler une anomalie il faut créer une "issue" et non commenter la demande de quelqu'un d'autre.
Et dans notre cas le site est protégé par cloudflare pour lequel la version actuelle ne fonctionne plus, il n'y a donc pas de solution actuellement.
