### ISSUE TITLE
[Saikai Scan] Connector not working

### ISSUE THREAD

**Issue by ArTaRki** [manga-download/hakuneko#5101]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://saikaiscan.com.br/comics
- Manga List: https://saikaiscan.com.br/historias
- Manga example: https://saikaiscan.com.br/comics/5-elementos-5e?tab=capitulos
- Chapter online viewer example: https://saikaiscan.com.br/ler/comics/5-elementos-5e/28988/capitulo-01-eu-elemental

**Languages**
Portugues

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website is supported but support is broken. Plus, there is no support for novels, as the website provide both mangas and novels.

**Comment by MikeZeDev** [comment]
https://github.com/MikeZeDev/hakuneko/commit/134fcaae3d3f04bc91b353ba028cea445077930c
