### ISSUE TITLE
[Site Request] Omega Scans

### ISSUE THREAD

**Issue by NaruHinaDis** [manga-download/hakuneko#5102]
**Name of the website**
Omega Scans

**Website urls (examples below)**
- Site: https://omegascans.org
- Manga List: https://omegascans.org/manga/
- Manga example: https://omegascans.org/manga/lady-elishas-diary-of-debauchery/
- Chapter online viewer example: https://omegascans.org/lady-elishas-diary-of-debauchery-chapter-1/

**Languages**
English

**Website relationship*
NSFW site of Omega Scans, a sister nsfw group of scylla scans

**Additional details**
None

**Comment by MikeZeDev** [comment]
template : Mangastream

Added by https://github.com/manga-download/hakuneko/pull/5138
