### ISSUE TITLE
[Japscan] Connector not working

### ISSUE THREAD

**Issue by drl77** [manga-download/hakuneko#5105]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Change Website Japscan.ws to Japscan.me

**To Reproduce**
1. japscan
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
NIghtly. Freshly updated List. When i click on a chapter, any chapter, i got a "failed to determine page type" error.

**Comment by Sheepux** [comment]
duplicate #4657

**Comment by heif-3** [comment]
I can access the japscan site, for example, within the software. But when I start loading mangas, it works for several minutes and then stops without displaying anything. How can we solve this problem?

**Comment by MikeZeDev** [comment]
Dont ask on a closed ticket 😭
