### ISSUE TITLE
Kindly Add Indian Comics Online

### ISSUE THREAD

**Issue by 7bajwa** [manga-download/hakuneko#511]
Hello,

Kindly add http://www.indiancomicsonline.com/ in the source list. 
It have great collection of Indian comics. it will be pain to download page by page.
I wanted to translate them to English as well. Just to support the community.
I will really appreciate the support if you add this. 

Thanks

**Comment by 7bajwa** [comment]
Wow that was fast. Thanks!  When will I be able to see it in the app?

**Comment by 27136773** [comment]
Use the nightly build or wait for stable release in december

**Comment by 7bajwa** [comment]
Thank you for the latest build. Works like a charm. Thanks again. 😄

**Comment by maybesmart** [comment]
Not working anymore remove it.
