### ISSUE TITLE
[Comic FX] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5112]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**
5. 
![image](https://user-images.githubusercontent.com/112748173/199520072-c81b7f89-a0db-4269-9024-27baf1ffab33.png)
just 3 image without comic

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by MikeZeDev** [comment]
Can confirm the bug on nightly. Request preview from console works we can see all image in the page. HN only shows the last picture in the page, which is one on the posted ones.

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5138
