### ISSUE TITLE
[Site Request] MangaKakalot

### ISSUE THREAD

**Issue by Booblover22** [manga-download/hakuneko#5116]
**Name of the website**
MangaKakalot.is

**Website urls (examples below)**
- Site: https://mangakakalot.is/
- Manga List: https://mangakakalot.is/browse
- Manga example: https://mangakakalot.is/worlds-end-harem-after-world-56190
- Chapter online viewer example: https://mangakakalot.is/worlds-end-harem-after-world-56190/ja/chapter-1

**Languages**
Japanese Raw

**Website relationship*
N/A

**Additional details**
Its a Raw Jp site.

**Comment by Sheepux** [comment]
duplicate #4914
