### ISSUE TITLE
[Lezhinus.com] Connector not working / I cannot download anything !

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5117]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I cannot download any series now from Lezhin US.

**To Reproduce**
1. Login to Lezhin website via Hakuneko.
2. Enter credentials into Hakuneko Application.
3. Any purchased series will be fine to use.
4. Console error messages are in photos below.
<img width="1436" alt="Screenshot 2022-11-05 at 12 24 14 am" src="https://user-images.githubusercontent.com/114213739/199983397-9bc03660-0ce7-47d5-a450-95775bcf5100.png">

<img width="1432" alt="Screenshot 2022-11-05 at 12 24 31 am" src="https://user-images.githubusercontent.com/114213739/199983423-21e11afd-2487-433d-b2c6-b3146cf50dc1.png">

**HakuNeko (please complete the following information):**
 - Version 6.1.7@a8da6a - Mac OS

**Comment by ghost** [comment]
Can we please have this looked into??? 😭

**Comment by Sheepux** [comment]
stop opening the same issue multiple times ...

**Comment by ghost** [comment]
> stop opening the same issue multiple times ...

The first issue was about Hiatus Chapters not showing but now the new issue is nothing is downloading. You didnt even respond to the first one 12 days ago & now you've closed both of them. 🙄

**Comment by Sheepux** [comment]
simply leave a comment in an existing issue
