### ISSUE TITLE
[Japscan] Connector not working

### ISSUE THREAD

**Issue by Flokeshi** [manga-download/hakuneko#5119]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
When I want to download mangas on JapScan, I have the following error : Failed to detect page type.
In Hakuneko the connector is japscan.ws but the website has changed: now it's japscan.me

**To Reproduce**
1. JapScan
2. Arifureta
3. Chapter 1
4. error : Failed to detect page type

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4657
