### ISSUE TITLE
[MangaLife] Connector not working

### ISSUE THREAD

**Issue by sonvsvswv** [manga-download/hakuneko#5121]
on the laptop app when i went to open up manga life the chapters didnt load even after refreshing. i tired switching interents and using a vpn but nothing worked. occasionally the app would give an error meesage that the maga list failed to update and i dont know what to do only the manga life apk shows any manags on it but donesnt load them while the other dont even show the manga list and then give the error message i told you about above

**Comment by Sheepux** [comment]
You know ... there are templates for people like you that writes horrible single-lines that gives you headaches

https://github.com/manga-download/hakuneko/issues/new/choose (option 1)

step1, is the website working in your browwer? https://manga4life.com/ ? not on my side --> nothing hakuneko can solve

**Comment by sonvsvswv** [comment]
> You know ... there are templates for people like you that writes horrible single-lines that gives you headaches
> 
> https://github.com/manga-download/hakuneko/issues/new/choose (option 1)
> 
> step1, is the website working in your browwer? https://manga4life.com/ ? not on my side --> nothing hakuneko can solve

i apologies for inconviencing you i am new to all this and didnt really know what i am doing so again sorry causing you any unessary trouble 
and yes it isnt opening on my browser so what do i do next

**Comment by Sheepux** [comment]
You just wait until the website works and then you try again in hakuneko.
The website is now working and it's working in HN, i'm closing the issue.

**Comment by sonvsvswv** [comment]
> You just wait until the website works and then you try again in hakuneko. The website is now working and it's working in HN, i'm closing the issue.

ok please just one more question i am still getting the failed to update manga list on other ports like on manga cat and what not what do i for them ??

**Comment by Sheepux** [comment]
if it's not working, look for existing issues and if nothing simply create a new one

**Comment by sonvsvswv** [comment]
i dont understand could you explain

**Comment by Sheepux** [comment]
github, create, new, issue

**Comment by sonvsvswv** [comment]
i still dont understand i am user of hakuneko just to be clear so i dont get what you mean

**Comment by Sheepux** [comment]
you have an issue with mangacat ? Create an issue about mangacat:
https://github.com/manga-download/hakuneko/issues/new/choose

**Comment by sonvsvswv** [comment]
no you dont understand my issue is with all of the ports none of them are working on my end they call keep giving the same issue of failed to load manga list

**Comment by Sheepux** [comment]
what does "all of the ports" means ?

**Comment by sonvsvswv** [comment]
i mean when you go to the website section and type in any kind of website like manga life or manga mitsu or any other the open up but then when i refresh the list to see the manga list it keeps giving me the same failed to load manga list error

**Comment by Sheepux** [comment]
mangalife is working fine here. Is the website working in your browser https://manga4life.com/ ? if it's not working then it's nothing hakuneko can solve

**Comment by sonvsvswv** [comment]
ok its started working some how i still dont understand why it wasnt working in the first place thank you for your time and again i apologize for causing you so much trouble
