### ISSUE TITLE
Dev new connector : fetch issues

### ISSUE THREAD

**Issue by apt42541** [manga-download/hakuneko#5122]
they allow to fetch data only to same domain? 

how can i fix this problem ?

![image](https://user-images.githubusercontent.com/12625408/200120896-5cb0e7f7-8152-4c6a-b3ca-dc76a9471789.png)

**Comment by Sheepux** [comment]
how about using the issue template to give the connector name? We aren't all knowing wizards you know.
If you checked the domain directly you would see that it's rejecting connection > domain was changed to https://manga169.com/

**Comment by apt42541** [comment]
manga168 connector use WordPressMangastream but has problem about cors about same-origin

**Comment by Sheepux** [comment]
give
the
connector
name

**Comment by apt42541** [comment]
it not by hakuneko by current update i just add it by myself 

![image](https://user-images.githubusercontent.com/12625408/200124866-f4d8f703-cff4-4732-a3cf-88d233934d64.png)

**Comment by Sheepux** [comment]
as i stated earlier did you try with  https://manga169.com/ ?

**Comment by apt42541** [comment]
> as i stated earlier did you try with https://manga169.com/ ?

yeah this site , hakuneko can grab manga and chapter but no image. and manga168.com is currently update than manga169.com
![image](https://user-images.githubusercontent.com/12625408/200125645-23431518-8338-42b1-8704-9c8aa2fbb6b2.png)
