### ISSUE TITLE
[Error 403] Can't download some Chapters from Lezhin, while others work.

### ISSUE THREAD

**Issue by Tanja-sama** [manga-download/hakuneko#5123]
As said in the Title, I can't download some Chapters from the NSFW Manhwa I'm reading, while others work and can be downloaded. The one's that aren't working throw the Error 403 at me.
The F12 Error console says:
"DevTools failed to parse SourceMap: protobuf.min.js.map , hls.light.min.js.map and 4f4f849....map"

And then it's just a constant error of GET >link< 403
I'm logged in and purchased the chapters just so that's out of the way.

**Comment by Sheepux** [comment]
duplicate #4433

**Comment by lord-ne** [comment]
If these issues are really the same issue as that one from 9 months ago, why did this only just now stop working for so many people?
