### ISSUE TITLE
Client crash after Jammy update: gpu error

### ISSUE THREAD

**Issue by Eidonko** [manga-download/hakuneko#5124]
Hello, I have recently updated my laptop distribution to Jammy (22.04.01), and now Hakuneko fails to start
The error message I get is 
[31393:1106/003353.499895:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
Any idea of what goes wrong and how I could solve this?
Thanks a lot!

$ hakuneko-desktop 

Usage:
  /usr/lib/hakuneko-desktop/hakuneko [OPTIONS]

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default

--------------
Framework Info
--------------
Electron : 6.1.7
Chrome   : 76.0.3809.146
Node     : 12.4.0

-------------
Configuration
-------------
Update URL           : https://manga-download.github.io/hakuneko/6.1.7/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : /home/e/.cache/hakuneko-desktop
UserData Directory   : /home/e/.config/hakuneko-desktop

[31845:1106/004020.153911:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)

**Comment by Sheepux** [comment]
sounds like electron/chrome gpu hardware acceleration issue.
can you try to run it with --no-sandbox ?

dev-note: https://www.electronjs.org/docs/latest/tutorial/sandbox

**Comment by Eidonko** [comment]
Hello, thanks for your help. A window now appears, though it is empty. I waited for about 15' minutes -- no change. Any idea of the reason and possible remedy? Thanks again.

- Eidon.


Nov 6, 2022, 03:14 by ***@***.***:

**Comment by Sheepux** [comment]
White screen issue is another one
https://hakuneko.download/docs/troubleshoot/#is-the-screen-blankblack-when-starting-hakuneko
https://github.com/manga-download/hakuneko/issues/13
There are various reasons, checking the console (F12) will reveal some of those. You could try to start it ONCE with sudo to see if it allows the update to work, but don't do it after that.

**Comment by Eidonko** [comment]
Hello, I tried but nothing seemed to work. Then I made a clean reinstall with the latest nightly release, and it works! Thanks a lot
Best,
Eidon

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Nov 6, 2022, 13:54 by ***@***.***:
