### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by GoranXXV** [manga-download/hakuneko#5132]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
MangaDex doesn't load at all 

**To Reproduce**
1. Name of connector MangaDex
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![Immagine 2022-11-09 181116](https://user-images.githubusercontent.com/101893515/200896264-fed9ba3f-3649-4620-ba19-ccad10d87927.jpg)

**Comment by MikeZeDev** [comment]
You got a CONNECTION REFUSED (explicit name) for some reason, but it works. I use nightly .

I think the problem is not from Hakuneko.

**Comment by GoranXXV** [comment]
> You got a CONNECTION REFUSED (explicit name) for some reason, but it works for me, and the website itself is alive. I use nightly .
> 
> I think the problem is not from Hakuneko but on your end.

I can go to mangadex within my browser and my wifi connection is good so I can't understand why on hakuneko I can use mangadex

**Comment by Sheepux** [comment]
Try to open mangadex using the internal browser ([manual website interraction](https://hakuneko.download/docs/manual-website-interaction/))

**Comment by GoranXXV** [comment]
> Try to open mangadex using the internal browser ([manual website interraction](https://hakuneko.download/docs/manual-website-interaction/))
How you can see I can go to MD with edge but If I use hakuneko internal browser MD doesn't load at all
![Immagine 2022-11-10 145052](https://user-images.githubusercontent.com/101893515/201109621-6b8c5b2a-bcb3-4dc4-bc97-1960976ffe6f.jpg)
![Immagine 2022-11-10 145151](https://user-images.githubusercontent.com/101893515/201109634-64b7bd30-c93a-4da6-aa60-dff5b82de476.jpg)

**Comment by Sheepux** [comment]
can you check the network tab in F12 (network tab) for detail on the failing request (and also when you see a red one: rightclick copy as fetch)

**Comment by Sheepux** [comment]
are you perhaps using an antivirus or antimalware ? That could explain the internet access behing blocked only for hakuneko (try to disable them or whitelist hakuneko)
