### ISSUE TITLE
[KomikCast] Connector not working

### ISSUE THREAD

**Issue by knapah** [manga-download/hakuneko#5140]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The site has changed its domain from [komikcast.me](https://komikcast.me/) to [komikcast.site](https://komikcast.site/)

**To Reproduce**
1. KomikCast
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/92723126/201218764-35e73147-315c-4fc8-8d43-7bb4619b3d72.png)

**HakuNeko (please complete the following information):**
 - Version 8.3.4 (Nightly)

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5138
