### ISSUE TITLE
[MangaKu] Connector not working

### ISSUE THREAD

**Issue by ilhamakbarsurya** [manga-download/hakuneko#5141]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
On Connectors I still see for the Mangaku website it is mangaku.in while the website has changed to mangaku.vip.

**To Reproduce**
1. MangaKu
2. -
3. -
4. 
![Screenshot_20221111_042816](https://user-images.githubusercontent.com/48595623/201309961-9a9c2ba1-9fe1-4f2a-ab57-4a9b0122e5fd.png)
![image](https://user-images.githubusercontent.com/48595623/201309860-aec8d309-5a0f-44f1-ac72-fff7c1409332.png)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Url chanded to mangaku.VIP. Loading manga listy works but
"Website has updated the redirection protection to prevent scraping" error when i want to see a chapter.

Website itself doesnt even load pictures on my own browser.

**Comment by ilhamakbarsurya** [comment]
> Url chanded to mangaku.VIP

How to fix it?

**Comment by MikeZeDev** [comment]
> > Url chanded to mangaku.VIP
> 
> How to fix it?

You cant. Connector code is restricted to a few users, because the website is one of those who fight against Hakuneko. I cant test myself :D

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/2977
