### ISSUE TITLE
[MangaFreak] Connector not working

### ISSUE THREAD

**Issue by ilhamakbarsurya** [manga-download/hakuneko#5142]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
I don't know for the specifics of this problem but it looks like it happened because of the wrong website link.

**To Reproduce**
1. MangaFreak
2. -
3. -
4. -

**Screenshots**
![image](https://user-images.githubusercontent.com/48595623/201310704-9804cf5b-6876-49ef-b73c-75276d6dd176.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Its the same on tachiyomi. I bet they reactivated cloudflare/changed CF level, not sure we can do anything.

**Comment by ilhamakbarsurya** [comment]
> Its the same on tachiyomi. I bet they reactivated cloudflare/changed CF level, not sure we can do anything.

I don't understand what's that mean, but the link moved to: https://w14.mangafreak.net/

**Comment by MikeZeDev** [comment]
ClouFlare is something websites use to protect them from "bots" (automated programs). From CF point of view, scrapers like HN can be detected as bots. Hakuneko has an unfixable bug when Clouflare is enforced to a certain level. Lower level may require tweaks and fixes.

When websites ask "Please wait , checking browser", and wants you to fill a Hcaptcha its most likely CF.

MangaFreak personalised they picture, but its still Cloudflare behind.
 ![image](https://user-images.githubusercontent.com/10671518/201320969-5862d136-4105-4573-ae5d-6dbc4995c514.png)

Tachiyomi (mobile app for manga) gives "cant pass cloudflare" errors on mangafreak for a week now.
Changing website url doesnt work, i tested.

**Comment by MikeZeDev** [comment]
Duplicate [4292](https://github.com/manga-download/hakuneko/issues/4292)
