### ISSUE TITLE
[Mangapark (AnyACG)] Connector not working

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/hakuneko#5143]
Nothing works, basically.

I fixed getting the manga list already but i am stuck getting the chapters properly : https://pastebin.com/87tGF9pH

**Comment by Druzai** [comment]
As far as I can tell, `mangapark.org` has become the mirror of `mangapark.net`.
And using [MangaParkEN](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/MangaParkEN.mjs) connector for `mangapark.org` works with added handling of that hostname:
```js
    canHandleURI(uri) {
        return /mangapark\.net|mangapark\.org/.test(uri.hostname);
    }
```
