### ISSUE TITLE
[Japscan] Connector not working

### ISSUE THREAD

**Issue by lbkev** [manga-download/hakuneko#5150]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can t download

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
duplicate #4657
