### ISSUE TITLE
[Plot Twist Scan not work] missing chapters

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5151]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Missing chapters

**To Reproduce**
1. Plot Twist no Fansub
2. Getsuyoubi no Tawawa
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![HakuNeko](https://user-images.githubusercontent.com/65477084/201636337-6ac4d957-4d8e-47c2-9213-a978d7024281.jpg)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Can reproduce. Its because HN read https://www.plot-twistnf-scans.com/plot/manga/getsuyoubi-no-tawawa/. Only 5 chapters are listed if you dont click on the button 
![image](https://user-images.githubusercontent.com/10671518/201742029-e2be0cb2-cc63-4e6c-9e62-9906f3a603e1.png)
