### ISSUE TITLE
[Union Mangás] Connectors not working

### ISSUE THREAD

**Issue by cj1051** [manga-download/hakuneko#5152]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Mangahost  and Union Mangás websites went down and now are up on new urls. Cuz of that I cant download their manga through the aplication :/
New urls are (https://mangahosted.com) and (https://orchidcommerce.com/home)

**To Reproduce**
1. Mangahost and Union Mangás

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by cj1051** [comment]
I changed some configs on my antivirus and Mangahost is actually working. Sorry for false alarm

Union Mangás is still not though

**Comment by MikeZeDev** [comment]
Changing the url for https://orchidcommerce.com works but the website is unstable. I always get 503 errors when getting chapter list. Also, Cloudflare.
