### ISSUE TITLE
[Kumanga] Connector not working

### ISSUE THREAD

**Issue by Ilyed** [manga-download/hakuneko#5153]
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
Kumanga connector does not work anymore. Connecting to their website and logging in did not change anything.

To Reproduce

![image](https://user-images.githubusercontent.com/22822021/201780623-d0e733cc-5b3a-49f8-81e5-fc62147e646d.png)

If complex to describe, add screenshots to help explain your problem.

HakuNeko (please complete the following information):

Version 6.1.7

**Comment by Sandlayth** [comment]
Congratulations on your first Github Issue!

**Comment by Ilyed** [comment]
> Congratulations on your first Github Issue!

Thanks, I was scared at first  ヽ༼ ಠ益ಠ ༽ﾉ
