### ISSUE TITLE
[Legionasia.com] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#5154]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error 403

**To Reproduce**
1. LegionAsia
2. Any manga
3. Any chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
[cache-1668493180572.log](https://github.com/manga-download/hakuneko/files/10009853/cache-1668493180572.log)

**Comment by MikeZeDev** [comment]
Tested Combat continent V : Chapter 1 load fine in browser, not on HN. On HN we bypass WP and then 403.
Its done in Chapter.mjs and in the template. Damn.

**Comment by MikeZeDev** [comment]
Its sometimes using a russian hoster for images, which is geoblocking some countries. No solution would be ideal : either we bypass WP to get high quality but get rekt by the russian website (no images), either we make a workaround for this website to get the pictures from WP like it should (but less quality)
