### ISSUE TITLE
[manga1001] change URL and template

### ISSUE THREAD

**Issue by PVPEugeo** [manga-download/hakuneko#5155]
**Name of the website**
manga1001

**Website urls (examples below)**
- Site: https://manga1001.club/
- Manga List: https://manga1001.club/latest
- Manga example: https://manga1001.club/%E3%83%8F%E3%82%99%E3%83%84%E3%83%8F%E3%83%AC-raw-free.7032
- Chapter online viewer example: https://manga1001.club/%E3%83%8F%E3%82%99%E3%83%84%E3%83%8F%E3%83%AC-raw-free.7032/%E7%AC%AC33%E8%A9%B1.273180

**Languages**
japanese, English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
new version of mgang1001 is dead
**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Template  : MadTheme (Mangabuddy, TrueManga, mangaforest). Template already coded.
