### ISSUE TITLE
[Mangahasu] Connector not working

### ISSUE THREAD

**Issue by chengsta** [manga-download/hakuneko#5158]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
manga not showing up on haruneko, showing error 'cannot read property href of undefined' when hitting refresh

**To Reproduce**
1. mangahasu
2. any manga
3. any chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
5. MangaHasu {id: "mangahasu", label: "MangaHasu", tags: Array(2), isLocked: false, initialized: true, …}
existingManga: [20 Years Old (Complete): true, 80% of the Swimming Club Girls Are Shaved (Complete): true, A Baby’s Nest (Complete): true, A Chaste Girl’s Climax at a Nudist Beach (Complete): true, A Different Class: true, …]
existingMangas: []
id: "mangahasu"
initialized: true
isLocked: false
isUpdating: false
label: "MangaHasu"
mangaCache: (1140) [EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, …]
requestOptions: {method: "GET", mode: "cors", redirect: "follow", credentials: "same-origin", headers: Headers}
tags: (2) ["manga", "english"]
url: "http://mangahasu.se"
icon: (...)
__proto__: Connector
constructor: class MangaHasu
icon: (...)
_getChapterList: _getChapterList( manga, callback ) { this.fetchDOM( this.url + manga.id, 'div.list-chapter table tr td.name a' ) .then( data => {…}
_getMangaList: _getMangaList( callback ) { this.fetchDOM( this.url + '/directory.html', 'div.pagination-ct a:last-of-type' ) .then( data => {…}
_getMangaListFromPages: _getMangaListFromPages( mangaPageLinks, index ) { if( index === undefined ) { index = 0; } return this.wait( 0 ) .then ( () => {…}
_getPageList: _getPageList( manga, chapter, callback ) { let request = new Request( this.url + chapter.id, this.requestOptions ); this.fetchDOM( request, 'div.img-chapter div.img source' ) .then( data => {…}
_handleConnectorURI: ƒ _handleConnectorURI( payload )
_initializeConnector: ƒ async _initializeConnector()
__proto__: Object

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [6.1.7]

**Comment by MikeZeDev** [comment]
Cloudflare. Mangahasu is even mentioned in the Cloudflare bug issue.

**Comment by chengsta** [comment]
but that was in 2021.  manga hasu was working for me until 2 months ago.  And to doublecheck, there is no fix, right?  I didn't see anything.

**Comment by MikeZeDev** [comment]
Websites sometimes changes the cloudflare level, and HN has unfixable bug with CF (blame Electron, not HN). This is why [Haruneko ](https://github.com/manga-download/haruneko) is developed, but its far from finished.

**Comment by MikeZeDev** [comment]
No more cloudflare
