### ISSUE TITLE
[Site Request] Simplyaweeb

### ISSUE THREAD

**Issue by AbsoluteZrro** [manga-download/hakuneko#5159]
**Name of the website**
Simplyaweeb

**Website urls (examples below)**
- Site: https://simplyaweeb.to/
- Manga List: https://simplyaweeb.to/anime/
- Manga example: https://simplyaweeb.to/anime/chainsaw-man-dub-episode-1/
- Chapter online viewer example: idk

**Languages**
English, Japanese

**Website relationship*
anime

**Additional details**
idk

**Comment by MikeZeDev** [comment]
Hello, can you please change the title so its easier to identify :) ?

**Comment by AbsoluteZrro** [comment]
What do you mean?  I put the name and everything, I mostly put the
suggestion so I can download anime.

**Comment by MikeZeDev** [comment]
> What do you mean? I put the name and everything, I mostly put the suggestion so I can download anime.

There are a lot of issues and having the website name in the title helps for triage.

**Comment by MikeZeDev** [comment]
"Goodbye" they say
