### ISSUE TITLE
[Site Request] LeerCapitulo

### ISSUE THREAD

**Issue by rodriguezrobinj** [manga-download/hakuneko#5160]
**Name of the website**
LeerCapitulo

**Website urls (examples below)**
- Site: https://www.leercapitulo.com/
- Manga List: https://www.leercapitulo.com/
- Manga example: https://www.leercapitulo.com/manga/the-dark-massacre-of-the-vengeful-hero/
- Chapter online viewer example: https://www.leercapitulo.com/read/the-dark-massacre-of-the-vengeful-hero/61/#1

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Hum, cant find a manga list :/
