### ISSUE TITLE
[Site Request] s-mangavf

### ISSUE THREAD

**Issue by Moustakym** [manga-download/hakuneko#5161]
**Name of the website**
s-mangavf

**Website urls (examples below)**
- Site: https://s-mangavf.ws/
- Manga List: https://s-mangavf.ws/manga-list
- Manga example: https://s-mangavf.ws/manga/sakamoto-days-scan
- Chapter online viewer example: https://s-mangavf.ws/manga/sakamoto-days-scan/1

**Languages**
French

**Website relationship*
none

**Additional details**
none

**Comment by MikeZeDev** [comment]
Template : MangaReaderCMS.

**Comment by Aura-anon** [comment]
Hello is it working ? I am also trying to use hakuneko on https://s-mangavf.ws/ but it cannot load.



> Template : MangaReaderCMS.

how to use it ?

**Comment by MikeZeDev** [comment]
Its an info which is useful for devs.  
It wont work until the fix come.  Its ready but need validation, among others.
