### ISSUE TITLE
[Site Request] manga-reader

### ISSUE THREAD

**Issue by Dkafetzis** [manga-download/hakuneko#5162]
**Name of the website**
manga-reader

**Website urls (examples below)**
- Site: https://manga-reader.org/
- Manga List: https://manga-reader.org/completed
- Manga example: https://manga-reader.org/black-jack-m-62070
- Chapter online viewer example: https://manga-reader.org/read/black-jack-m-62070/en/chapter-1

**Languages**
EN, JA

**Website relationship*
None that i know of

**Comment by MikeZeDev** [comment]
Seems a mirror of mangareader.to. Same design, same number of pages, and similar code. You should use connector "mangareader.to" then.

**Comment by MikeZeDev** [comment]
Website doesnt answer anymore.
