### ISSUE TITLE
[mnhaestate.com] Connector not working

### ISSUE THREAD

**Issue by TheRebel03** [manga-download/hakuneko#5165]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector url has changed.

To Reproduce

Name of connector - [TEAM X]
Name of manga (if connector update is working) - All
Name of chapter (if manga update is working) - All
Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
" Website urls (examples below)

Site: https://mnhaestate.com/
Manga List: https://mnhaestate.com/series
Manga example: https://mnhaestate.com/series/apotheosis
Chapter online viewer example: https://mnhaestate.com/series/apotheosis/1

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Default domain is already https://mnhaestate.com/ in code. You can change it manually in config

![image](https://user-images.githubusercontent.com/10671518/202861956-05948a30-2579-4b71-9232-1e3b8510a120.png)

Changing the domain in config works as intended. Nothing to see here, this can be closed i think.

**Comment by TheRebel03** [comment]
yes. thank you.
