### ISSUE TITLE
[Site Request] Cosmic Scans

### ISSUE THREAD

**Issue by Coravon** [manga-download/hakuneko#5168]
**Name of the website**
Cosmic Scans

**Website urls (examples below)**
- Site: https://cosmicscans.com/
- Manga List: https://cosmicscans.com/manga/
- Manga example: https://cosmicscans.com/manga/demonic-emperor/
- Chapter online viewer example: https://cosmicscans.com/demonic-emperor-chapter-338/

**Languages**
- English

**Website relationship*
Replacement of Alpha Scans (I think)

**Additional details**

**Comment by MikeZeDev** [comment]
Template : Mangastream.
