### ISSUE TITLE
[NewType] Connector not working

### ISSUE THREAD

**Issue by monnch** [manga-download/hakuneko#5170]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
List does not load properly

**To Reproduce**
1. NewType
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
5
**
![image](https://user-images.githubusercontent.com/103281934/203446963-0771b01b-384f-4ea3-9cc5-69b3c2632ce8.png)
**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Website change.

**Comment by MikeZeDev** [comment]
Kinda struggling to find proper exhaustive manga list cause i dont read japanese. Any help?

**Comment by Elastic1** [comment]
This is the new manga list's URL. https://comic.webnewtype.com/contents/?refind_search=all

**Comment by MikeZeDev** [comment]
Previous manga list used to have around 400 entries, now i get 149 using the provided page.
Hum, any way to get more?  I dont see a next button . Well there is still the clipboard button if a manga is missing

**Comment by Elastic1** [comment]
It seems that there is no way to get more. I tried crawling the URLs of the other manga listings and still found only 149.
