### ISSUE TITLE
There is a GraphQL api underneath. Not sure if directly accessible. All request comes with a sha256 hashMAC. We are to figure out what is the key and what is actually hashed.

### ISSUE THREAD

**Issue by ulqi0rra** [manga-download/hakuneko#5171]
There is a GraphQL api underneath. Not sure if directly accessible. All request comes with a sha256 hashMAC. We are to figure out what is the key and what is actually hashed. 

https://www.apollographql.com/docs/react/api/link/persisted-queries/

_Originally posted by @MikeZeDev in https://github.com/manga-download/hakuneko/issues/5058#issuecomment-1324329703_

**Comment by ulqi0rra** [comment]
unfortunately,i am technologically inept hence i do not understand any of this

**Comment by MikeZeDev** [comment]
Those things are developer notes, dont pay attention. And close this, this issue is useless, you can answer on the same issue already :D . Please close this issue and let the other open :)
