### ISSUE TITLE
[Manga World] Connector not working

### ISSUE THREAD

**Issue by ittobeadg** [manga-download/hakuneko#5173]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The "click to paste" option doesn't work because the domine change from www.mangaworld.in to www.mangaworld.so

**To Reproduce**
1. Name of connector [Manga World] 
2. Name of manga [All mangas]
3. Name of chapter [All chapters]
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12).

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [Nightly]

**Comment by MikeZeDev** [comment]
Noted. You can change the url yourself by modifying Mangaworld.mjs using notepad in the meantime. Thanks for reporting.

**Comment by ittobeadg** [comment]
> Noted. You can change the url yourself by modifying Mangaworld.mjs using notepad in the meantime. Thanks for reporting.

Thanks, it works. you saved me from next site changes.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5080
