### ISSUE TITLE
Removal Request for GlobalComix

### ISSUE THREAD

**Issue by ChristopherGC** [manga-download/hakuneko#5176]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

**Which website should be removed?**
GlobalComix

**Why should this website be removed from HakuNeko?**
As the creator, owner, and lead engineer of GlobalComix, I am formally requesting that GlobalComix not be listed in this app. The thousands of creators who upload to GC receive no benefit (followers, comments, reactions, etc) from readership happening outside of our context.

#### In case of Traffic
**1. How much traffic is caused by HakuNeko?**
N/A - not merged to live yet.
**2. How much is it compared to overall traffic (percentage)?**
N/A
**3. How did you measure those analytics (framework)?**
N/A
**4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?**
N/A
**5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?**
N/A

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
Sure.
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
We request removal wherever we see it added.
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
Sure.

#### In case of Monetization
1. Are you using Donations?
Yes - but not to us. To each creator owner of each series (Self publishing).
2. Are you using Advertisements?
No.

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
We don't use ads at all.

- must provide direct download links for all chapters
This is not an option - this is a self-publishing platform for creators and it's their choice how they publish.

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

This is not applicable.

**Comment by Sheepux** [comment]
HakuNeko is indeed of no value for the content creators (feature wise) but it's for the end users that desires offline reading.

The website is well done and user respectfull (from the ad point of view). It doesn't seem to be an aggregator.
It seems to offer digital download, but only for paid chapter ?
Is such feature also available for free titles/chapters ? (i think that would be the only thing blocking the removal). I was not able to see a download button on free ones (maybe I need an account?)

Internal note: hey, if there is a website fullfilling all conditions what should we do ? Add the connector but only so that it tells the user that the download/offline option is directly available on the website ? (so that users don't request it again)

**Comment by ChristopherGC** [comment]
`Is such feature also available for free titles/chapters ? (i think that would be the only thing blocking the removal). I was not able to see a download button on free ones (maybe I need an account?) `

it is up to individual creators to offer downloads. Some do, some don’t.

for reference, I built this platform and it’s not an aggregator. It’s a legit official platform that creators and publishers publish in legally- there is exactly zero pirated or scanlated comics on it.

I’d like to ask people to respect that and not try to rip the content off (even for offline reading). Our native apps comic early next year will also have offline support fwiw.
