### ISSUE TITLE
[Feature] Discord rich presence would be cool

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5177]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Discord rich presence for the app to show which manga we are reading

**Describe alternatives you've considered**
None.

**Context (please complete the following information):**
 - Latest version

**Comment by Sheepux** [comment]
Already implemented, use the nightly version

**Comment by ghost** [comment]
ok thanks
