### ISSUE TITLE
[manganato.com] Connector not working

### ISSUE THREAD

**Issue by DgBeast** [manga-download/hakuneko#5178]
website changed, older bookmarks displayed. some remain blank 
here is a example of a "working" bookmark,
https://manganato.com/manga-nt990654

This is a non working one. 
https://chapmanganato.com/manga-de980539

**Comment by MikeZeDev** [comment]
Tested nightly. Updating list works, preview and download too.

Unfortunately, there is no way to update bookmarks automatically in Hakuneko when such changes appears. You'll have either to recreate them, or manually modify the hakuneko.bookmarks file with notepad.

**Comment by Sheepux** [comment]
Just changing the domain in the connector to the new domain will get the bookmarks working (when bookmarks are stored as relative URL)

**Comment by MikeZeDev** [comment]
But manganato bookmarks are stored with full url. At least i got some old ones like that

`    "title": {
      "connector": "Manganato",
      "manga": "Soul Land"
    },
    "key": {
      "connector": "manganel",
      "manga": "https://readmanganato.com/manga-hg952215"
    }`

I think its precisely because they used many urls in the past that we use full url. :/

**Comment by DgBeast** [comment]
> Just changing the domain in the connector to the new domain will get the bookmarks working (when bookmarks are stored as relative URL)

but what if the connector / domain is not listed / available?? i have just been using copy / paste link.

**Comment by Sheepux** [comment]
that was a discussion between devs, don't mind it

**Comment by DgBeast** [comment]
> Tested nightly. Updating list works, preview and download too.
> 
> Unfortunately, there is no way to update bookmarks automatically in Hakuneko when such changes appears. You'll have either to recreate them, or manually modify the hakuneko.bookmarks file with notepad.

i have only been using the latest stable build. also that non working link one has not yet been bookmarked, as it does not appear on the connector tab upon copy / pasting the link.

**Comment by MikeZeDev** [comment]
I am afraid testing nightly wont help you with your bookmark issue. 
As for the copy paste issue, there has been recent fixes for manganato, available on nightly for the moment. Give it a try :)

**Comment by DgBeast** [comment]
just installed nightly version, pasting from the clipboard still doesn't work ( on said link ). tried searching it thru the manganato connector, no results. the page works fine on browsers though. 
https://chapmanganato.com/manga-de980539
 
![The Eminence In Shadow Manga Online Free - Manganato](https://user-images.githubusercontent.com/119042824/204114457-30e7528f-96e1-41f5-83fd-28de839fac61.png)

**Comment by MikeZeDev** [comment]
I guess we could update the Regex for paste feature to 
`/(m\.|chap)?(read)?manganato\.com/`

Waiting for other devs suggestions.

**Comment by DgBeast** [comment]
> I guess we could update the Regex for paste feature to `/(m\.|chap)?(read)?manganato\.com/`
> 
> Waiting for other devs suggestions.

hope it works, i tested other newer manga links on the same site. same issue. that chap url really is something @_@ , older links that only have the manganato.com on the link seem to still work. On a totally different note, the https://e-hentai.org website seems to have some issues on some link pages not appearing on preview mode then upon downloading the pages, all the files are .bin .

**Comment by MikeZeDev** [comment]
> > I guess we could update the Regex for paste feature to `/(m\.|chap)?(read)?manganato\.com/`
> > Waiting for other devs suggestions.
> 
> hope it works, i tested other newer manga links on the same site. same issue. that chap url really is something @_@ , older links that only have the manganato.com on the link seem to still work. On a totally different note, the https://e-hentai.org website seems to have some issues on some link pages not appearing on preview mode then upon downloading the pages, all the files are .bin .

1) Manganato/nelo whatever is always messy
2) If you want to mention problem with another website make another issue
3) E-hentai problem is known, no need to open another issue
