### ISSUE TITLE
[Site Request] global toptoon [former toptoonplus]

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#5180]
**Name of the website**
globaltoptoon [former toptoonplus]

**Website urls (examples below)**
- Site: https://global.toptoon.com
- Manga List: https://global.toptoon.com/genres
- Manga example: https://global.toptoon.com/content/Fitness/100548
- Chapter online viewer example: https://global.toptoon.com/content/Fitness/100548/103534

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Got to work a bit on it, i still cant get the pages, and i am out of ideas. Someone may help? 

https://github.com/MikeZeDev/hakuneko/commit/08bdea02d3d965953e558b3b584b278f9f4b72a7

**Comment by EvilKing3** [comment]
I would be nice if the support for toptoon was added, I have done a python script for siteripping the entire website and keep it updated 1 month ago, unfortunately I couldn't finish the download, and I don't have the time to review to update it, it was done for the previous version but it could help, if they didn't change too much stuff:
[toptoonplus.txt](https://github.com/manga-download/hakuneko/files/10175611/toptoonplus.txt)
Let me know if it can help figure it out a solution for the new toptoon @MikeZeDev

**Comment by MikeZeDev** [comment]
Now Daycomics https://github.com/manga-download/hakuneko/issues/5802
