### ISSUE TITLE
[Komiktap] Connector not working

### ISSUE THREAD

**Issue by Emely028** [manga-download/hakuneko#5181]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
can't connect, can't update manga list, can't copy clipboard and etc

**To Reproduce**
Site: https://92.87.6.124/
Manga List: https://92.87.6.124/
Manga example: https://92.87.6.124/manga/dosukebe-sauna-e-youkoso/
Chapter online viewer example: https://92.87.6.124/dosukebe-sauna-e-youkoso-chapter-1/

**Screenshots**
![Screenshot_105](https://user-images.githubusercontent.com/119110022/204090393-76a103b8-eb1a-4ead-af76-150d76556f32.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
https://github.com/MikeZeDev/hakuneko/commit/5a8fbd3c58ddc1f7b7c722f73a0ddf1eafc53415
