### ISSUE TITLE
[Site Request] manhwa18.cc

### ISSUE THREAD

**Issue by WikiMike69** [manga-download/hakuneko#5183]
**Name of the website**
manhwa18

**Website urls**
- Site: https://manhwa18.cc/
- Manga List: https://manhwa18.cc/webtoons
- Manga example: https://manhwa18.cc/webtoon/the-beginning-after-the-end
- Chapter online viewer example: https://manhwa18.cc/webtoon/the-beginning-after-the-end/chapter-3

**Languages**
English - Korean

**Website relationship**
Nothing

**Additional details**
manhwa18.cc is quite different from manhwa18.net & manhwa18.com , are not relevant to each other.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4016
