### ISSUE TITLE
[Site Request] mangabuddy

### ISSUE THREAD

**Issue by WikiMike69** [manga-download/hakuneko#5184]
**Name of the website**
mangabuddy

**Website urls**
- Site: https://mangabuddy.com/
- Manga List: https://mangabuddy.com/latest
- Manga example: https://mangabuddy.com/kimetsu-no-yaiba
- Chapter online viewer example: https://mangabuddy.com/kimetsu-no-yaiba/chapter-114-wanting-to-be-accepted

**Languages**
English

**Website relationship**
alternative domain : https://mangamirror.com/

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4346
