### ISSUE TITLE
[Site Request] Manga Planet

### ISSUE THREAD

**Issue by mslmn** [manga-download/hakuneko#5185]
**Name of the website**
Manga Planet

**Website urls (examples below)**
- Site: https://read.mangaplanet.com/
- Manga List: https://read.mangaplanet.com/browse
- Manga example: https://read.mangaplanet.com/comic/61726768bedee
- Chapter online viewer example: https://read.mangaplanet.com/reader?cid=62a80c58c209e&sk=1

**Languages**
English

**Website relationship*
Is a sister site to https://read.futekiya.com/, which is available as a connector in Hakuneko.

**Comment by MikeZeDev** [comment]
Exactly. Its exactly the same. Thanks for the hint it was easy to do.

**Comment by mslmn** [comment]
Thank you. Is the connector available in the app?

**Comment by MikeZeDev** [comment]
No. Its ready but many things need validation before.

**Comment by mslmn** [comment]
Ah ok. Thank you for your help.
