### ISSUE TITLE
[Site Request] Yuri Neko

### ISSUE THREAD

**Issue by Khangry** [manga-download/hakuneko#5189]
**Name of the website**
https://yurineko.net/

**Website urls (examples below)**
- Site: https://yurineko.net/
- Manga List: https://yurineko.net/
- Manga example: https://yurineko.net/manga/1599
- Chapter online viewer example: https://yurineko.net/read/1599/8663

**Languages**
Vietnamese

**Comment by Khangry** [comment]
r18 page didn't work :( can you fix that

**Comment by MikeZeDev** [comment]
r18? All i see is a login page. Didnt knew there was a r18 list, i am a bit lost in foreign language websites, sorry.
Come on discord

**Comment by Khangry** [comment]
> r18? All i see is a login page. Didnt knew there was a r18 list, i am a bit lost in foreign language websites, sorry. Come on discord

it's same as api.yurineko.net api using /r18Lastest?page=1 slug to query r18 content (require login or bearer token). I'm working on this stuff but idk how to get pageCount to get all of that list :(

**Comment by MikeZeDev** [comment]
why bother with pagecount if there is not? make api calls until 
1) results are empty 
or
2) Server throw and http error 
or

3) last result from api is the same that the last manga in the manga list (meaning its looping)

Look at many connectors that have for loop with run = true and run = false

**Comment by Khangry** [comment]
> why bother with pagecount if there is not? make api calls until
> 
> 1. results are empty
>    or
> 2. Server throw and http error
>    or
> 3. last result from api is the same that the last manga in the manga list (meaning its looping)
> 
> Look at many connectors that have for loop with run = true and run = false

Can you give me some ref commit using loop with api?

**Comment by MikeZeDev** [comment]
Api or not its just a request. Look into @sample.js. Look for connectors with getmangasfrompages
