### ISSUE TITLE
[A Pair of 2+] Connector not working

### ISSUE THREAD

**Issue by MiniZaki** [manga-download/hakuneko#5191]
**Name of the website**
A Pair of 2+

**Website urls (examples below)**
- Site: https://po2scans.com/
- Manga List: https://po2scans.com/manga/?m_orderby=alphabet
- Manga example: https://po2scans.com/manga/be-blues-ao-ni-nare/
- Chapter online viewer example: https://po2scans.com/manga/be-blues-ao-ni-nare/chapter-482/

**Languages**
English

**Additional details**
Their is a Pair of 2+ website (https://pairof2.com/) on HakuNeko, but it has a different website and it doesn't work.

**Comment by MikeZeDev** [comment]
then its probably just an url change . Or not, they switched to madara.
