### ISSUE TITLE
[Komiku] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5197]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Cant find some comic

**To Reproduce**
1. Komiku
2. Martial Peak 2 (https://komiku.id/manga/martial-peak-part-2/)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/112748173/205439815-0164b153-eb43-476f-9c6e-3e4372e437f9.png)
![image](https://user-images.githubusercontent.com/112748173/205439824-23014a19-f4ee-4783-89c7-1a39c8f528ca.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 8.3.4]

**Comment by MikeZeDev** [comment]
HN gather the manga list from here : https://komiku.id/daftar-komik/. Martial peak isnt on it. That list even stops at the letter 'F'.
Martial peak is indeed in the manhua list. As a workaround maybe we should read the 3 filtered list instead.

For now, use the clipboard feature with the manga page, it works.
