### ISSUE TITLE
[MangaHub] Connector not working

### ISSUE THREAD

**Issue by tryguy** [manga-download/hakuneko#5199]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
When attempting to get the manga list from the site, hakuneko comes up with an error, something about "Can't initialize the API key!"

This site used to work well, but stopped working maybe a few days ago.

**To Reproduce**
1. MangaHub

**HakuNeko (please complete the following information):**
master@9cc6f1

**Comment by MikeZeDev** [comment]
Nightly got the bug too. They got rid of their api key and use cloudflare?
