### ISSUE TITLE
[JapScan] Connector not working

### ISSUE THREAD

**Issue by minibombardo** [manga-download/hakuneko#5202]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No 

In the developer tools, the site points to https://www.japscan.ws while there is a redirect to https://www.japscan.me/. I can't seem to find in the configuration files to change it.

the download works a month ago. now any manga shows this error

**Describe the bug**

**To Reproduce**
1. JapScan
2. Blue Lock
3. 190
4.
Connector.mjs:618 Error: Failed to detect page type!
    at JapScan._getPagesType (JapScan.mjs:4)
    at async JapScan._getPages (JapScan.mjs:4)
    at async JapScan._getPageList (Connector.mjs:615) EventTarget {manga: EventTarget, id: "/lecture-en-ligne/blue-lock/191/", title: "Blue Lock 0191", file: {…}, language: "", …}
_getPageList @ Connector.mjs:618
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:111
Promise.then (async)
getPages @ Chapter.mjs:109
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49

**HakuNeko (please complete the following information):**
 - Version master@9b4a33

**Comment by MikeZeDev** [comment]
Yeah we know. JS is a pain.

**Comment by Sheepux** [comment]
duplicate #4657
