### ISSUE TITLE
[NeoxScanlator] Connector not working

### ISSUE THREAD

**Issue by MaxColen** [manga-download/hakuneko#5203]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It does not load any manga from the website. https://neoxscans.net/

**To Reproduce**
1. Neox Scanlator
2. Update not working
3. Update not working
4. Failed to load resource: the server responded with a status of 403 ()

**Screenshots**
[Capturar](https://user-images.githubusercontent.com/25783797/205849371-870a3e17-8809-4480-a892-b69281eff560.PNG)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]!

**Comment by MikeZeDev** [comment]
Cant reproduce on nightly. Manga update works fine. Preview and download too.
