### ISSUE TITLE
[Toomics (English)] Add log-in feature to download from subscription

### ISSUE THREAD

**Issue by EvilKing3** [manga-download/hakuneko#5205]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Missing log-in option for Toomics.
With a premium account you can view any manhwa on the website if you have a sub, if someone can code I'm offerring my premium account to check the website, it has the sub active.

**To Reproduce**
There's no log-in option.

**Screenshots**
![toomics](https://user-images.githubusercontent.com/5150545/205988351-67065a5b-3c04-43a8-95fb-46107561c1b7.PNG)

**HakuNeko (please complete the following information):**
 - Version 6.17 stable.

**Comment by MikeZeDev** [comment]
Afaik there is no "login page", its a popup on the main page. So there is no"login link" to add.

Did you try the button on the right to open the page and click on sign-in? 
![image](https://user-images.githubusercontent.com/10671518/206154918-a2dacaa5-1058-4f52-b666-a663ecacea1e.png)

**Comment by EvilKing3** [comment]
You were correct, I didn't know you could access that way, I can confirm with a subscription you can download everything from Toomics by sign in that way.
Thanks!
