### ISSUE TITLE
[Site Request] mangascan.ws

### ISSUE THREAD

**Issue by Aura-anon** [manga-download/hakuneko#5206]
**Name of the website**
[mangascan.ws](https://mangascan.ws)

**Website urls (examples below)**
- Site: https://mangascan.ws
- Manga List: https://mangascan.ws/manga-list
- Manga example: https://mangascan.ws/manga/chainsaw-man
- Chapter online viewer example: https://mangascan.ws/manga/chainsaw-man/1

**Languages**
french

**Website relationship*
unknown

**Additional details**
unknown

**Comment by MikeZeDev** [comment]
Duplicate of https://github.com/manga-download/hakuneko/issues/4740

**Comment by MikeZeDev** [comment]
I'd swear its a template, but which one?

**Comment by Aura-anon** [comment]
> Duplicate of #4740

not exacly the same adress
I dunno

**Comment by MikeZeDev** [comment]
It is. cc redirect to ws :D
