### ISSUE TITLE
[NeuManga] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5211]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. NeuManga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/112748173/206415950-5f3a3d97-30e4-4ab9-8904-254af76fc380.png)
![image](https://user-images.githubusercontent.com/112748173/206415989-02c9ecb8-3988-48ef-987e-d2a9f67c2710.png)
![image](https://user-images.githubusercontent.com/112748173/206416075-c81be7a2-38c5-409b-9fd5-8a6089922e93.png)
![image](https://user-images.githubusercontent.com/112748173/206416218-c6aadb08-975e-42d7-9a95-795340c9a770.png)
Cant refresh manga list

**HakuNeko (please complete the following information):**
 - Version [e.g. 8.3.4]

**Comment by MikeZeDev** [comment]
Url change i guess => neumanga.net. And new wordpress theme : Zmanga.
