### ISSUE TITLE
Viz Connector not working

### ISSUE THREAD

**Issue by qchrisd** [manga-download/hakuneko#5215]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Not all manga series are being found in the manga list. Additionally, only free chapters are available, not member chapters even when you have logged in through the portal. After logging in and refreshing the list the network monitor shows a "session expired" page. Lastly, adding a series through the clipboard connector shows the series name but fails to load any chapters with an error stating `TypeError: manga.id.startsWith is not a function`

**To Reproduce**
1. Log into Viz connector
2. Select Chainsaw Man
3. Console shows https://www.viz.com/account/refresh_login_links page before loading series page.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by shiplin** [comment]
Are you using [the nightly version of hakuneko](https://github.com/manga-download/hakuneko/releases)? I was running into similar issues with not being able to see member chapters and #5145 fixed it for me, but that fix isn't in stable yet. I'm able to use the viz connector, access all manga and membership chapters without any issues in nightly. (Not sure about the clipboard connector though)

**Comment by qchrisd** [comment]
I just tried the nightly and it does appear to list all series titles and chapters appropriately. I'll use this build for now and switch back to stable when these fixes are merged. Thanks for the help!
