### ISSUE TITLE
Bilibili Connector not working

### ISSUE THREAD

**Issue by Blackfairie** [manga-download/hakuneko#5224]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The first chapters works well but at a certain chapter (12-13) the connector doesn't detect the images.

**To Reproduce**
1. Bilibili Comics
2. All
3. Higher than 11-12-13
4. No error

**Screenshots** 
![image](https://user-images.githubusercontent.com/115415720/206905875-a068222f-931b-4d05-9a38-4ff391495b8c.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Blackfairie** [comment]
![image](https://user-images.githubusercontent.com/115415720/206905916-c533fcf9-f1cd-480d-8f25-78fb1c4568b8.png)

Chapter 1 to 13 are detected but not more than 14.

**Comment by Sheepux** [comment]
duplicate #4673
