### ISSUE TITLE
[Site Request] cuutruyen

### ISSUE THREAD

**Issue by Khangry** [manga-download/hakuneko#5226]
**Name of the website**
cuutruyen.net

**Website urls (examples below)**
- Site: https://cuutruyen.net/
- Manga List: https://cuutruyen.net/newest?page=
- Manga example: https://cuutruyen.net/mangas/204
- Chapter online viewer example: https://cuutruyen.net/mangas/204/chapters/1686

**Languages**
Vietnamese

**Comment by MikeZeDev** [comment]
Scrambled pictures. They are descrambled and drawn on page canvas through a Webassembly. 
First part of the work is in my experimental branch fi you want to deal with unscrambling

**Comment by Khangry** [comment]
> Scrambled pictures. They are descrambled and drawn on page canvas through a Webassembly. First part of the work is in my experimental branch fi you want to deal with unscrambling

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/vi/cuutruyen/src/eu/kanade/tachiyomi/extension/vi/cuutruyen/CuuTruyenImageInterceptor.kt
Can you checkout this, I'm too noob to know what they code inside

**Comment by MikeZeDev** [comment]
wasm to js :D Thats cute.

**Comment by Khangry** [comment]
> wasm to js :D Thats cute.

https://github.com/Darkrai9x/vbook-extensions/tree/master/cuutruyen/src

I found this reference

**Comment by MikeZeDev** [comment]
Dont close it, i linked it in your PR. Merging the PR will close the issue automatically ;)
