### ISSUE TITLE
[komiktap] Domain website has been change

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#5230]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the domain website has change

**To Reproduce**
1. komiktap
2. New Domain https://92.87.6.124/

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Already done . https://github.com/MikeZeDev/hakuneko/commit/5a8fbd3c58ddc1f7b7c722f73a0ddf1eafc53415

**Comment by amir32** [comment]
I wanted to drop a quick comment to let everyone know that our website, FusionCalculator.com, has undergone an exciting domain change! 🌟 We're thrilled to share that we've expanded and improved our Pokémon Fusion Calculator to provide an even more fun and interactive experience for all Pokémon fans.

Now, you can visit us at our new domain: [FusionCalculator.com](https://fusioncalculator.com/) to explore the latest fusion combinations, create your unique Pokémon fusions, and discover the endless possibilities of Pokémon fusion.

We appreciate your continued support, and we can't wait to have you explore our enhanced fusion calculator. Feel free to reach out if you have any questions or if you want to share your fusion creations with the Pokémon community. Thanks again, [Komiktap] community, and happy fusing!

**Comment by MikeZeDev** [comment]
Damn bloody spammers
