### ISSUE TITLE
[LELSCAN-VF] Connector not working

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/hakuneko#5232]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

The website changed its address.

**To Reproduce**
1. LELSCAN-VF
2. All mangas

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by didierGuieu** [comment]
New address : lelscanvf.com

**Comment by MikeZeDev** [comment]
url changed and a lil fix needed :)
