### ISSUE TITLE
[Site Request] Constellarscans

### ISSUE THREAD

**Issue by hesoyamma785** [manga-download/hakuneko#5238]
**Name of the website**
constellarscans

**Website urls *
- Site: https://constellarscans.com/
- Manga List: https://constellarscans.com/manga/
- Manga example: https://constellarscans.com/manga/grand-disciple/
- Chapter online viewer example: https://constellarscans.com/grand-disciple-chapter-1/
**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Source says "Mangareader' but its a bona fide MangaStream. Wait i am dumb,  those two are identical.
