### ISSUE TITLE
[Site Request] mangamirror

### ISSUE THREAD

**Issue by johninaba** [manga-download/hakuneko#5245]
**Name of the website**
mangamirror

**Website urls (examples below)**
- Site: mangamirror.com
- Manga List: https://mangamirror.com/home-page
- Manga example: https://mangamirror.com/manga/43312-dont-fall-in-love-with-the-villainess
- Chapter online viewer example: https://mangabuddy.com/dont-fall-in-love-with-the-villainess/chapter-17

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Yeah another MadTheme website. Just when i refined the template.

**Comment by MikeZeDev** [comment]
Chapters are hosted on Mangabuddy, which is already done and will be added in a future PR . No need for this website.
![image](https://user-images.githubusercontent.com/10671518/208253530-cce34b31-9bf5-4bda-98c0-d4175d5fc31a.png)
