### ISSUE TITLE
[Site Request] manganelo

### ISSUE THREAD

**Issue by Kenny-Stilyan** [manga-download/hakuneko#5249]
**Name of the website**
manganelo

**Website urls (examples below)**
- Site: https://m.manganelo.com/wwww
          https://manganato.com/
- Manga List: https://m.manganelo.com/wwww
- Manga example: https://m.manganelo.com/manga-ul98457
- Chapter online viewer example: https://chapmanganelo.com/manga-ul98457/chapter-1

**Languages**
ENG

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4955
