### ISSUE TITLE
[RealmScans] Connector not working

### ISSUE THREAD

**Issue by omodia** [manga-download/hakuneko#5251]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The manga list of the connector is updating and refreshing properly, but downloading of chapters is not working for every manga of this connector.

**To Reproduce**
1. Realm Scans
2. EVery Manga
3. Every Chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**

**HakuNeko (please complete the following information):**
 -

**Comment by omodia** [comment]
@MikeZeDev 

The issue is still present and downloads are not working for this connector.

**Comment by MikeZeDev** [comment]
![image](https://user-images.githubusercontent.com/10671518/210134630-efe815a7-62a3-48b9-9745-757824496efe.png)

The fix has not been pushed on stable version yet. It works on nightly, use nightly.

**Comment by omodia** [comment]
Still not working on stable.

**Comment by MikeZeDev** [comment]
Stable wont be updated for a while. We are busy working in Haku successor. Nightly got the update, **Read what i've said**
