### ISSUE TITLE
[Mangakatana] Connector not working

### ISSUE THREAD

**Issue by Overlord008** [manga-download/hakuneko#5257]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When downloding manga or even previewing only cover image (jpg) is shown or downloaded ,It doesn't download the complete manga but rather it downloads only the cover.
![Screenshot (10)](https://user-images.githubusercontent.com/121127624/208981843-290292f7-1c87-4e87-b5fd-46390ee04b10.png)
![Screenshot (11)](https://user-images.githubusercontent.com/121127624/208981856-d687d7b7-ac5a-4545-a960-f85966822bd6.png)

**To Reproduce**
Mangakatana
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
1) Invalid ticket, fill the form properly.
2) Mangakatana works for me. Give more infos

**Comment by MikeZeDev** [comment]
That is way better. See, ticket filled properly? Solution ! It was fixed by https://github.com/manga-download/hakuneko/pull/5020, and its still working. Download Nightly version of Hakuneko , the fix is already inside..
