### ISSUE TITLE
[Ichijin-plus] Connector not working

### ISSUE THREAD

**Issue by Hatshuharu** [manga-download/hakuneko#5260]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update manga list for the website. Copy-paste doesn't work either.

**To Reproduce**
1. Select the Ichijin-plus connector.
2. Click the refresh icon to update manga list.
3. Error shows up.
4. F12 panel screenshot is attached. The same error occurs in both nightly and stable version.
5. Tried copy-paste the link and click refresh button, nothing happens.

**Screenshots**
![1](https://user-images.githubusercontent.com/121182829/208944674-890f9dbc-7c34-40a7-accd-84b4477b18a6.png)
![2](https://user-images.githubusercontent.com/121182829/208944689-44ab1460-d380-46ba-ad8f-f3091216351d.png)

**HakuNeko (please complete the following information):**
 - Version 6.17 (stable)
 - Version 8.3.4 (nightly)

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/pull/5259
