### ISSUE TITLE
[MangaFreak] Connector not working

### ISSUE THREAD

**Issue by Kapovski** [manga-download/hakuneko#5261]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
when i want to do the update list , an error shows up

**To Reproduce**
1. MangaFreak
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Connector.mjs:579 TypeError: Cannot read property 'href' of undefined
    at MangaFreak._getMangas (MangaFreak.mjs:38)
    at async MangaFreak._getMangaList (Connector.mjs:576) MangaFreak {id: "mangafreak", label: "MangaFreak", tags: Array(2), isLocked: false, initialized: true, …}
_getMangaList @ Connector.mjs:579
async function (async)
_getMangaList @ Connector.mjs:576
(anonymous) @ Connector.mjs:99
Promise.then (async)
updateMangas @ Connector.mjs:98
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96

**Screenshots**
![image](https://user-images.githubusercontent.com/121189021/208991348-880c023a-27d1-48ae-85ae-2ae2ede98a0a.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4292

**Comment by Kapovski** [comment]
> Duplicate #4

> Duplicate #4292

![image](https://user-images.githubusercontent.com/121189021/208995145-87112e7c-c82d-403b-92dc-1c78a1259533.png)
should i past this [raws.mangazuki.co] on the search bar in mangafreak from hakuneko or past it on google=\     cause none of them shows up with a response

**Comment by MikeZeDev** [comment]
I dont quite understand what you say but the Cloudflare Loop of death cant be passed or patched. Choose another website. Its old dev tool fault, not HN :/
