### ISSUE TITLE
[Comico (コミコ)] Connector not working

### ISSUE THREAD

**Issue by AkatsukiKawa** [manga-download/hakuneko#5263]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot update and synchronize local manga list with online list from Comico (コミコ)

**To Reproduce**
1. Name of connector: Comico.jp
2. Name of manga: Any
3. Name of chapter: Any 
4. Copy any relevant error message that appears in a popup: Unexpected token < in JSON at position 0

**Screenshots**

![haku](https://user-images.githubusercontent.com/121239973/209149074-91921a66-742f-4513-879c-aa0cc1aa82b9.PNG)

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by MikeZeDev** [comment]
They changed their api. Bunch of added headers in request and a comico-check-sum we have to compute. Prob some SHA, have to dig, this website is a mess.

**Comment by lunataruf** [comment]
I still got the same issue
![image](https://user-images.githubusercontent.com/80588550/214827192-2606a5f9-7ccf-4da5-9e37-69570fedb7ba.png)

**Comment by MikeZeDev** [comment]
Tried nightly ?

**Comment by AkatsukiKawa** [comment]
I also still have the same issue with Hakuneko nightly.

Probably it is the update because my Hakuneko is still rev. 6.1.7@554b0c, which according to revision history only has update until "Commits on Dec 23, 2022". The Comico fix was commited after that (IIRC Jan 1st 2023).

Is there a way to update manually?

**Comment by MikeZeDev** [comment]
>  my Hakuneko is still rev. **6.1.7@554b0c,**

It seems you didnt use nightly judging by this number. Or i misunderstood..

I have no json error on nightly. Well most chapters are not shown since you need to buy them but free stuff works.

![image](https://user-images.githubusercontent.com/10671518/215052827-d06b7454-9151-4962-b56e-02b1041c1198.png)

**Comment by AkatsukiKawa** [comment]
By Nightly, you mean Nightly build in the Hakuneko download page, didn't you? This is how my Hakuneko looks like when I tried to access Comico JP:   

![Picture1](https://user-images.githubusercontent.com/121239973/215054539-77e4b669-b560-4a76-a357-45fd06416dc0.png)

ETA: My Hakuneko always check for updates whenever I open it. But the rev. version doesn't change.

**Comment by MikeZeDev** [comment]
This is what nightly show in about 

![image](https://user-images.githubusercontent.com/10671518/215060162-88fcfe92-5730-4605-9c01-d93910ceb11a.png)

Nightly and stable sure autoupdate but those are different branches and updates are available earlier on nightly.

**Comment by AkatsukiKawa** [comment]
I reinstalled Hakuneko and now it works :D !  
  
Another question though, I bought some manga in Comico.JP. Is there a way to download it? 

I am wondering because I could not find the manga name in the list although it has free chapters ("転生した異世界で家政婦になりました！" The webpage is https://www.comico.jp/comic/424). And I also didn't find a place to fill in login information for Comico.JP in Hakuneko Setting page.

**Comment by MikeZeDev** [comment]
https://hakuneko.download/docs/manual-website-interaction/

Close HN. Launch HN. Login inside HN and see if downloading works. its 50/50. May require additional coding.
Its important NOT to check for chapters before login because HN use cache for chapters and for now you cant refresh chapter list without closing HN.

**Comment by AkatsukiKawa** [comment]
I logged in but the manga name still doesn't appear on the Comico.JP in Hakuneko. Probably cannot be done now.

Anyway, thank you very much! You are really helpful!

**Comment by AkatsukiKawa** [comment]
Just want to report. I successfully downloaded the manga from ComicoJP although it doesn't appear in the list after refreshing. It's just I must use Clipboard after login in
