### ISSUE TITLE
[ScansMangas (XYZ)] Connector not working

### ISSUE THREAD

**Issue by Andflowan** [manga-download/hakuneko#5277]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not a bug , the site have a new adress, it was before scansmangas.xyz and it's now scansmangas.ws. When we enter old adress, it redirect to the new website and on the app , it shows every mangas but when we use download button , it don't work.

Site: https://scansmangas.ws/
Manga List: https://scansmangas.ws/tous-nos-mangas/
Manga example: https://scansmangas.ws/manga/battle-royale-perfect-edition/
Chapter online viewer example: https://scansmangas.ws/scan-battle-royale-perfect-edition-5/

**Screenshots**

![Capture d’écran (216)](https://user-images.githubusercontent.com/117603445/209486194-2fc1db1c-f802-4f02-bd23-b28bc2049d7b.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
This has nothing to do with address change, but it doesnt work yeah gotta fix it asap
