### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by yukinolapatate** [manga-download/hakuneko#5278]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapter isnt visible, the list is empty !

**To Reproduce**
1. Japanread
2. All mangas
3. All chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Fill the template properly :/..

Duplicate #[4776](https://github.com/manga-download/hakuneko/issues/4776)
