### ISSUE TITLE
[Futabanet Monster] Connector not working

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#5280]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to download some chapter on this site, look like they change URL for reader.

**To Reproduce**
1. Select Futabanet Monster (Gaugau Monster).
2. Select some manga (Ex. 姉の身代わりで婚約したら何故か辺境の聖女と呼ばれるようになりました).
3. Select new chapter.
4. Download failed and appear 404 on bibGetCntntInfo.php at dev tool.

**Screenshots**
![image](https://user-images.githubusercontent.com/2475440/209589256-94cdda73-988e-4ba9-8e70-50684b509f46.png)
![image](https://user-images.githubusercontent.com/2475440/209589687-812c17d1-0fc1-4ada-9417-dcd5b9ac1061.png)

**HakuNeko (please complete the following information):**
 - Version master@21931e

**Comment by MikeZeDev** [comment]
Its seems they use 2 different Speedbind versions , for reader.futabanet.jp  and gaugau.futabanet.jp

**Comment by siennk** [comment]
Is there a workaround to get the connector to work?

**Comment by MikeZeDev** [comment]
Nope. Speedbind is messy for me and they use 2 different one i dont know how to start.
