### ISSUE TITLE
[https://www.ainzscans.my.id/] Ainz Scans ID

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5281]
**Name of the website**
Ainz Scans ID

**Website urls (examples below)**
- Site: https://www.ainzscans.my.id/
- Manga List: https://www.ainzscans.my.id/p/manga-list.html
- Manga example: https://www.ainzscans.my.id/2022/12/i-copied-peerless-divine-art-in-another.html
- Chapter online viewer example: https://www.ainzscans.my.id/2022/12/chapter-00.html

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Added in Haruneko https://github.com/manga-download/haruneko/pull/344
