### ISSUE TITLE
[ComicExtra] Url Change

### ISSUE THREAD

**Issue by ToManyTickets** [manga-download/hakuneko#5285]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hakuneko is unable to fetch list from ComicExtra connection or download chapters contained in bookmarks.

**To Reproduce**
1. ComicExtra
2. Select any comic (tested using Batman Gotham Knights Gilded City)
3. Select any chapter (tested chapter 1)
4. `ClipboardConnector.mjs:66 CLIPBOARD: https://ww1.comicextra.com/comic/batman-gotham-knights-gilded-city Error: No matching connector found for URL https://ww1.comicextra.com/comic/batman-gotham-knights-gilded-city
    at ClipboardConnector.mjs:59
    at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28)
    at HTMLElement.onUpdateMangaListClick (mangas.html:233)
    at HTMLElement.onPasteClick (mangas.html:340)
    at HTMLElement.handler (template-stamp.html:96)
`
`_getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open '/home/user/.config/hakuneko-desktop/hakuneko.mangas.comicextra`

**HakuNeko (please complete the following information):**
 - Version master@ce23356

**Comment by MikeZeDev** [comment]
Url changed
