### ISSUE TITLE
[Sushiscan] New URL

### ISSUE THREAD

**Issue by ballhardy95** [manga-download/hakuneko#5291]
The URL has changed 
The new URL is -> https://sushiscan.ru/

**Comment by MikeZeDev** [comment]
Cloudflare, changing url is useless :/

**Comment by didierGuieu** [comment]
even if we use the integrated browser to initiate the first connection?

**Comment by MikeZeDev** [comment]
> even if we use the integrated browser to initiate the first connection?

you'll get infinite loop.

**Comment by ballhardy95** [comment]
Hi there is the same issu with the website sushiscan again

**Comment by MikeZeDev** [comment]
Another isssue has been opened already
