### ISSUE TITLE
[Site Request] Adult Painful Nightz

### ISSUE THREAD

**Issue by infyProductions** [manga-download/hakuneko#5294]
**Name of the website**
Adult Painful Nightz

**Website urls (examples below)**
- Site: https://adults.painfulnightz.com/
- Manga List: https://adults.painfulnightz.com/manga/
- Manga example: https://adults.painfulnightz.com/manga/jiokima-2/
- Chapter online viewer example: https://adults.painfulnightz.com/manga/jiokima-2/chapter-1/

**Languages**
List of languages supported by the website
- English
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
- NSFW site version of Painful Nightz (https://painfulnightz.com/)
**Additional details**
Add any other context details that you may have found (like template to reuse)
- Mostly identical with their SFW site (https://painfulnightz.com/) (refer to #4117 for their SFW version)

**Comment by MikeZeDev** [comment]
Its pointless. Main site and adult website doesnt work because of Cloudflare.

**Comment by MikeZeDev** [comment]
Website is now empty. Feel free to reopen this issue in case there is content.
