### ISSUE TITLE
Delitoon Connector not working

### ISSUE THREAD

**Issue by Pipixel** [manga-download/hakuneko#5305]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I try to download a chapter I buy, it required me to login, but I already done it, but it works only with the free chapters

**To Reproduce**
1. Select the Delitoon plugin
2. Login to an account
3. Search a chapter already buy
4. Download it

**Screenshots**

![hakuneko_hcbOcx52gE](https://user-images.githubusercontent.com/66361896/210136867-818c3a35-6503-48b0-a477-ef1667353385.png)

**HakuNeko (please complete the following information):**
 - Version Nightly 8.3.4

**Comment by MikeZeDev** [comment]
I updated this but obviously i couldnt test paid chapters. Well, unless you lend to me your account credentials i cant fix it i guess.
I made sure this message was displayed only when we receive a NOT_LOGIN_USER error btw so there is something wrong.

**Comment by Pipixel** [comment]
You are ArseneLapin on Discord didn't you? For being sure I send my user credentials to the good person
