### ISSUE TITLE
[Team x] Connector not working

### ISSUE THREAD

**Issue by Dr-Shiro** [manga-download/hakuneko#5317]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The website domain was changed so now we cant view anything

**To Reproduce**
1. Name of connector Team X
Failed to update manga list for team x
ERR_NAME_NOT_RESOLVED https://www.teamxmanga.com

**Website new urls**
Site: https://team1x1.fun/
Manga List: https://team1x1.fun/series
Manga example: https://team1x1.fun/series/tales-of-demons-and-gods
Chapter online viewer example: https://team1x1.fun/series/tales-of-demons-and-gods/412

**Screenshots**
[![Screen-Shot-2023-01-02-at-19-49-10.png](https://i.postimg.cc/P5MGGLL4/Screen-Shot-2023-01-02-at-19-49-10.png)](https://postimg.cc/DSmpLwPJ)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Just change URL in hakuneko config. And it works :)
![image](https://user-images.githubusercontent.com/10671518/210272156-132bf2bb-20d2-4a5d-b51d-a58b0e10ec64.png)
