### ISSUE TITLE
[Site Request] Yanp Fansub

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#5320]
Name of the website
**Yanp Fansub**

Website urls 

Site: **http://yanpfansub.com/**
Manga List: https://yanpfansub.com/manga/
Manga example: https://yanpfansub.com/manga/hero-vs-villain/
Chapter online viewer example: https://yanpfansub.com/manga/hero-vs-villain/capitulo-11/

Languages
Portuguese

Additional details
MadaraWordPress

**Comment by MikeZeDev** [comment]
They went password protected today. Nothing to see.

**Comment by mangareader4** [comment]
> They went password protected today. Nothing to see.

Website open now

**Comment by Smaly25** [comment]
Como faz pra entrar?
