### ISSUE TITLE
[Site Request] Animated Glitched Scans

### ISSUE THREAD

**Issue by abhishek-exists** [manga-download/hakuneko#5327]
**Name of the website**
Animated Glitched Scans

**Website urls (examples below)**
- Site: https://anigliscans.com/
- Manga List: https://anigliscans.com/series/
- Manga example: https://anigliscans.com/series/monsters/
- Chapter online viewer example: https://anigliscans.com/monsters-chapter-14/

**Languages**
English
List of languages supported by the website

**Additional details**
Similar to Realm Scans. Can use similar connector :)
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Done. Will come eventually. Be patient

**Comment by abhishek-exists** [comment]
@MikeZeDev Hey, I have successfully added this connector. Can I create a pull request ?
Find ss for your reference :)
![image](https://user-images.githubusercontent.com/62441572/210761886-57b9b2ac-e6d7-4409-81ef-a947ebe054fb.png)
![image](https://user-images.githubusercontent.com/62441572/210761892-6973df79-38ba-4181-8358-9879a97ad59f.png)

**Comment by MikeZeDev** [comment]
Sure feel free to submit a PR.
