### ISSUE TITLE
[Mangapill] Missing manga from list

### ISSUE THREAD

**Issue by namel3ssguy** [manga-download/hakuneko#5329]
I see there are many mangas on the Manga Pill website which the app could not fetch.

Can you guys update the Manga Pill script?

**Comment by MikeZeDev** [comment]
Can you name a manga pls? 

So i tested : no matter what we do, they limited search results to 1k, and this is what we use to gather manga list. The only list we can get is through search apparently.

 You can use the copy paste feature in case one is not found.

**Comment by namel3ssguy** [comment]
Hi @MikeZeDev,

Demon Slayer (or Kimetsu no Yaiba) is an example.

**Comment by MikeZeDev** [comment]
Yup, its working with copy paste manga url. https://mangapill.com/manga/2285/kimetsu-no-yaiba

![image](https://user-images.githubusercontent.com/10671518/210750955-f90aedfe-298a-40eb-8255-50998af357cd.png)


There is nothing we can do.  Its limited on their end.

**Comment by namel3ssguy** [comment]
How can we paste the url like above? I'm using HakuNeko on macOS.

**Comment by namel3ssguy** [comment]
I found it. It's the [paste] icon above the textbox. Thanks a lot. I really appreciate it.

**Comment by MikeZeDev** [comment]
Wont fix
