### ISSUE TITLE
[https://manhwalist.in/] ManhwaL ist

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5336]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://manhwalist.in/
- Manga List: https://manhwalist.in/az-lists/
- Manga example: https://manhwalist.in/manga/bad-guy/
- Chapter online viewer example: https://manhwalist.in/bad-guy-chapter-117/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by abhishek-exists** [comment]
@MikeZeDev should I go with this one? As this is similar to the Realmscans and Anigliscans

**Comment by MikeZeDev** [comment]
Its another mangastream, sure, do it, dont ask :p

Also a tip : connector icons can be easily fetched from website sometimes, look in your browser network inspector for favicon stuff, its usually a suitable png file, big enough to be cropped to 96x96px.

![image](https://user-images.githubusercontent.com/10671518/211084819-f35c5041-8861-4c5c-8138-a35115b6db83.png)
