### ISSUE TITLE
[AsuraScans] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5337]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
AsuraScans no longer connects, most likely due to a Website Change. Manual Website opening does not work. The connector now shows the error ERR_TOO_MANY_REDIRECTS upon trying to refresh the list.

**To Reproduce**
1. Select AsuraScans (English)
2. Refresh Site
3. Shows in F12 Console:
Uncaught (in promise) Error: ERR_TOO_MANY_REDIRECTS (-310) loading 'https://asurascans.com/'
    at rejectAndCleanup (C:\Program Files\HakuNeko Desktop\resources\electron.asar\browser\navigation-controller.js:67:29)
    at WebContents.failListener (C:\Program Files\HakuNeko Desktop\resources\electron.asar\browser\navigation-controller.js:77:21)
    at WebContents.emit (events.js:205:15)

**HakuNeko (please complete the following information):**
 - Version 6.17 @554b0c

**Comment by MikeZeDev** [comment]
Cant reproduce on nightly. Moreover, last change to AsuraScans was in March 2022, so nightly version is same as stable ( the one you are using). Turkish ones works too.

![image](https://user-images.githubusercontent.com/10671518/211039993-938fb73f-092f-4163-8f67-9b11b9de56b1.png)

**Comment by ghost** [comment]
It also happened on Version master@4aeb50. I'm using the windows i386 version. I dunno what else to tell you that's specific to my system that could help in reproducing the bug

**Comment by MikeZeDev** [comment]
Too many redirect is unusual error. Whats happening in your browser? Is there any AV interfering? Idk.

**Comment by ghost** [comment]
The network tab doesn't even show an attempt to connect online, so it isn't getting that far. Also, no AV interference, I disabled it to test. But the nighly gave a more detailed error report so there's a little more info if it helps. It showed:
![ErrorSnip](https://user-images.githubusercontent.com/122104594/211098287-7f555374-d2c2-4fb3-a5bc-00f900f6d997.PNG)

I dunno what it means, so I appreciate the help.

**Comment by Pipixel** [comment]
I think I know the problem, few manhwas are transferred to there new site in alpha and might cause problems. It's the only reason comes to my mind

**Comment by MikeZeDev** [comment]
> I think I know the problem, few manhwas are transferred to there new site in alpha and might cause problems. It's the only reason comes to my mind

Well there is clearly a cloudflare check; no need to dig further.

**Comment by ghost** [comment]
What does that mean? The FAQ doesn't explain cloudflare or if there's a fix or any plans for workaround. Am I just out of luck? Is the thread closed?

**Comment by MikeZeDev** [comment]
Anti bot / DDoS/ automation mechanism some websites uses. And we cant fix it ftm.

When i checked yesterday there was a Cloudflare check now there is not. Look like they removed it / lowered CF level, it works again. I am closing this since it works again. Feel free to reopen it in case it doesnt work again.
