### ISSUE TITLE
[KomikIndo] Connector not working

### ISSUE THREAD

**Issue by abhishek-exists** [manga-download/hakuneko#5338]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I reviewed the code for the connector and It seems that they changed their theme from Madara to MangaReader. 
This needs a quick fix. 

**To Reproduce**
1. Name of connector: **KomikIndo**
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
`Failed to load resource: the server responded with a status of 403 ()`

**Screenshots**
![image](https://user-images.githubusercontent.com/62441572/211088194-ff86ead5-8058-4aa4-a72b-b205246605b9.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by abhishek-exists** [comment]
Update: They are using Cloud flare, Is there any alternative to this problem?

**Comment by MikeZeDev** [comment]
Depends on Cloudflare level. Idk the specifics. Assume its a no.

**Comment by MikeZeDev** [comment]
Fixed itself
