### ISSUE TITLE
[包子漫書 (baozimh)] redirect or replace image real with fake image

### ISSUE THREAD

**Issue by apt42541** [manga-download/hakuneko#5340]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
yes
**Describe the bug**
redirect or replace image real with fake image 
![image](https://user-images.githubusercontent.com/12625408/211132037-a996f80c-aad2-430c-9bf0-b97f868b2ab7.png)
![image](https://user-images.githubusercontent.com/12625408/211132045-94860354-d8a6-4023-96aa-fceb88450f37.png)
https://s2.baozimh.com/scomic/dushijipinyishen-yuewenmanhua/0/33-cbe1/4.jpg
**To Reproduce**
1. Name of connector
baozimh
2. Name of manga (if connector update is working)
都市極品醫神
3. Name of chapter (if manga update is working)
033
https://www.webmota.com/comic/chapter/dushijipinyishen-yuewenmanhua/0_33.html
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
-
**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/12625408/211132082-e7ad378f-f8a1-445e-8804-7306dadb8feb.png)

**HakuNeko (please complete the following information):**
 - Version 
 - latest version by auto update

**Comment by MikeZeDev** [comment]
Need referer on pictures ..

```curl https://s2.baozimh.com/scomic/dushijipinyishen-yuewenmanhua/0/33-cbe1/4.jpg```

![x](https://user-images.githubusercontent.com/10671518/211152450-72b2fef5-c121-421b-bb70-da96b360ed9d.jpg)

```curl https://s2.baozimh.com/scomic/dushijipinyishen-yuewenmanhua/0/33-cbe1/4.jpg -e baozimh.com```

![image](https://user-images.githubusercontent.com/10671518/211152488-56f8f5cf-efa8-4aa9-b8d6-fa33e868b00c.png)
