### ISSUE TITLE
[9Anime] Connector not working

### ISSUE THREAD

**Issue by MohammedHamza0631** [manga-download/hakuneko#5343]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The website of the connector is changed. In the hakuneko app it is displayed as https://9anime.to but the website domain is changed to https://9anime.vc .
![issue](https://user-images.githubusercontent.com/91896151/211153860-d4ef0319-b50f-461c-8c3d-d74d124acda8.png)
![issue-2](https://user-images.githubusercontent.com/91896151/211153964-f9f567ad-6519-4e83-9a6a-e55983f38a24.png)

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
9anime.to website is still ok. Now, as for HN support, yeah, its not working.

**Comment by Sheepux** [comment]
duplicate #4561
