### ISSUE TITLE
[Site Request] ComicId

### ISSUE THREAD

**Issue by mkrisskarr** [manga-download/hakuneko#5346]
**Name of the website**
ComicId

**Website urls (examples below)**
- Site: http://comicsid.com/inicio
- Manga List: http://comicsid.com/categorias/dc-A
- Manga example: http://www.comicsid.com/serie/651-90-serie
- Chapter online viewer example: http://www.comicsid.com/co/BatmanV3-131/

**Languages**
Spanish

**Additional details**
It's a comic page and include a differente editorials, the list of all comics it's divide in different category, to inclued all the comics of the site for example for the Marvel Comics:

http://comicsid.com/categorias/marvel-A

**Comment by MikeZeDev** [comment]
I may be blind but where are the readers links (/co/comicname/) on the chapters list page? All i see is direct download links.

Furthermore http://www.comicsid.com/co/BatmanV3-131/ works so i could think about a pattern. So i tried http://www.comicsid.com/co/BatmanV3-112/ but its not available.

Without links we cant do anything.
