### ISSUE TITLE
[Site Request] Tenshi.moe

### ISSUE THREAD

**Issue by shekoo193** [manga-download/hakuneko#5347]
**Name of the website**
(https://tenshi.moe/)

**Website urls (examples below)**
- Site: https://tenshi.moe/
- Manga List: https://tenshi.moe/anime
- Manga example: https://tenshi.moe/anime/dcrer4o9
- Chapter online viewer example: https://tenshi.moe/anime/dcrer4o9/1

**Comment by MikeZeDev** [comment]
Ddoss Guard but its ok :p
