### ISSUE TITLE
[ReadManga] Connector not working

### ISSUE THREAD

**Issue by Rad-Fore** [manga-download/hakuneko#5348]
Capture from https://readmanga.live/ has stopped working again.

1. Readmanga
2. https://readmanga.live/liubov_na_rasstoianii_v_8_metrov
3. All chapters
4. Can't load any pictures even after logging in to the site

Version 6.1.7

**Comment by MikeZeDev** [comment]
Works on nightly. Use nightly 
![image](https://user-images.githubusercontent.com/10671518/211409221-4dcd2093-6570-43e3-950a-ce63ac9e38b6.png)
