### ISSUE TITLE
[TOONILY] Connector not working

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#5349]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it cant get new mangas nor update the manga list

**To Reproduce**
1. toonily
2. update isnt working

4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
=>>> cannot read property 'href' of undefined

**Screenshots**
![image](https://user-images.githubusercontent.com/6580326/211437968-da602578-3ec1-4690-92ac-d75f85289850.png)

**HakuNeko (please complete the following information):**
i use the nightly build, so, latest version

**Comment by MikeZeDev** [comment]
https://cdn.discordapp.com/attachments/581630792120401922/1062309243937640509/image.png

Cant fix

**Comment by MikeZeDev** [comment]
No more cloudflare
