### ISSUE TITLE
Timeout too fast for larger files

### ISSUE THREAD

**Issue by Amarok682** [manga-download/hakuneko#5350]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Using the connector for MangaReader.to to save the full volume versions of a manga.  "Bloom into you" is an example but not the only one this happens with.  It will timeout before it downloads or shows the reader preview.  Individual chapters work fine but just not volumes.

**Screenshots**
![image](https://user-images.githubusercontent.com/122336503/211462139-b0a59c67-432b-4947-b96c-a08476204098.png)

![image](https://user-images.githubusercontent.com/122336503/211462973-5fb832b7-29a4-40df-8af2-d766a24bcf07.png)

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 6.1.7

**Additional context**
It is just my guess that it is takinging too long to load the larger libraries and thus timing out.  Being able to increase the timeout time may solve the problem

**Comment by MikeZeDev** [comment]
Known problem. Mentioned many time. You got it right. Just use chapters for now.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5054
