### ISSUE TITLE
[HIPERDEX] Connector not working

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#5354]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
YES

**Is the website of the connector working properly / are you able to see the manga within your browser**
YES

**Describe the bug**
update not getting new list of manga nor download from the old list

**To Reproduce**
1. HIPERDEX

4. Nothing appears, it just doesnt update the list... when i tried to use a backup list of manga and download a chapter, it didnt even found it...

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
NIGHTLY BUILD.

**Comment by MikeZeDev** [comment]
They activated cloudflare again

**Comment by MikeZeDev** [comment]
Fixed by itself
