### ISSUE TITLE
[Hentai-Chan] Connector not working

### ISSUE THREAD

**Issue by Rad-Fore** [manga-download/hakuneko#5357]
Hentai-Chan is now located at the following addresses:
https://y.hentaichan.live/
https://xxxxx.hentaichan.live/

1. Connector: Hentai-Chan
2. Manga: Any
3. Chapter: Any
4. Any manga doesn't load

Version Nightly

**Comment by MikeZeDev** [comment]
Which one do you suggest we use? We cant use two.

**Comment by Rad-Fore** [comment]
Please use https://y.hentaichan.live/

**Comment by MikeZeDev** [comment]
No need for the y apparently, oh well.
