### ISSUE TITLE
Show chapters/size next to titles - Feature request

### ISSUE THREAD

**Issue by Darkrift411** [manga-download/hakuneko#536]
When I am browsing for something new the lists can be overwhelming, especially since lots of the results are very small (just a few pages for some, 1-2 chapters for others). I prefer longer stories, so if the results could show the number of items it would be easier to see at a glance which ones I would like to look into.

ex:
MangaName1 (1 item (chapter/volume))
MangaName2 (72 items (chapter/volume))
MangaName3 (17 items (chapter/volume))

**Comment by 27136773** [comment]
This is not possible, because for each manga a request to the server must be made to get the number of chapters. For a website with thousands of mangas this would result in thousands of requests and the time to load a manga list would explode from some minutes to several hours.
