### ISSUE TITLE
[Site Request] Saikai Scan

### ISSUE THREAD

**Issue by Akarin2** [manga-download/hakuneko#5360]
**Name of the website**
Saikai Scan

**Website urls**
- Site: https://saikaiscan.com.br/home
- Manga List: https://saikaiscan.com.br/comics
- Manga example: https://saikaiscan.com.br/comics/light-and-shadow-ls
- Chapter online viewer example: https://saikaiscan.com.br/ler/comics/light-and-shadow-ls/29296/capitulo-01

**Languages**
Portuguese

**Comment by MikeZeDev** [comment]
Duplicate and already done. 

![image](https://user-images.githubusercontent.com/10671518/211771327-5eb704e7-c479-46f1-ad54-af42eea25c7f.png)

Use nightly if you cant see it in stable.
