### ISSUE TITLE
Reader Background[Feature]

### ISSUE THREAD

**Issue by acebed** [manga-download/hakuneko#5363]
![image](https://user-images.githubusercontent.com/66884552/212055720-14bb4bbf-d27c-4b78-a388-e0e16fa78d85.png)

Hello
first i want to tell u that i love HakuNeku
its the best app for me 
the thing i want to ask is wether its possible to remove the lady on the background while reading mangas 
i really want to turn it into full black, i think its better for a reading experience
otherwise its perfect 
thanks

**Comment by Murshid7absi** [comment]
go to the hakuneko folder where you installed it and go to this path \HakuNeko\cache\img... there you will find it and you can just delete it

**Comment by acebed** [comment]
> go to the hakuneko folder where you installed it and go to this path \HakuNeko\cache\img... there you will find it and you can just delete it

thanks alot

**Comment by Sheepux** [comment]
I don't think that i'll bring back such background in Haruneko (future HakuNeko version).
Closing as this won't be done in HakuNeko
