### ISSUE TITLE
[Toonily] Connector not working

### ISSUE THREAD

**Issue by lambdareader** [manga-download/hakuneko#5364]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connector is unable to parse the name correctly. Name shown in hakuneko has 'HOT', 'NEW', 'END' in the end. Example: '(SERIESNAME) HOT' 
Problematic because status of the series changes over time so hakuneko creates a new folder.

**To Reproduce**
1. toonily
2. all manga which have the status HOT, NEW or END

**HakuNeko (please complete the following information):**
 - Version 6.17

Edit: Only does not work when copying from clipboard.

**Comment by MikeZeDev** [comment]
i dont see any problem right now .

![image](https://user-images.githubusercontent.com/10671518/212120815-02b61401-3445-4046-a9c3-b4dc1764383b.png)

![image](https://user-images.githubusercontent.com/10671518/212120950-4619dbbb-8186-44b1-b3fb-1026f2d2d6ec.png)

Can you precisely name a manga?

**Comment by lambdareader** [comment]
Sorry, I should have clarified that it happens when copying from clipboard.
Just tried normal list and it works.
Up until recently clipboard also worked just fine.

Brave New World for example:
<img width="188" alt="hakuneko" src="https://user-images.githubusercontent.com/120762220/212166341-955a1578-ca1f-4f1f-a8b2-8db3b1e05292.PNG">

**Comment by lambdareader** [comment]
The patch is not working for me on nightly rev 23fcb9 (which should have the patch)
It only scans the link in the clipboard for 2 seconds and is not displaying anything.
Other connectors work fine with clipboard.
And toonily connector without clipboard also works.
