### ISSUE TITLE
[Neumanga] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5366]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Neumanga (https://neumanga.net/)
2. all Project Update web
3. Cultivation Return on Campus
4. 
![image](https://user-images.githubusercontent.com/112748173/212292467-e5a9a142-6532-4780-abf6-17781064c06a.png)
![image](https://user-images.githubusercontent.com/112748173/212292504-46c445f1-c2d4-4647-babf-8042ed9321be.png)
![image](https://user-images.githubusercontent.com/112748173/212292540-80bfc1d0-ead4-43e6-8191-2ed4d0827d5a.png)

**Screenshots**
Cant detect manga/manhua/manhwa project
![image](https://user-images.githubusercontent.com/112748173/212293147-71d00754-129d-4cb8-993d-0508cb948f73.png)
![image](https://user-images.githubusercontent.com/112748173/212293239-eff89bcb-3bd6-453c-ad69-5308eb9c7d9e.png)
![image](https://user-images.githubusercontent.com/112748173/212293313-e78692e8-282a-4e50-89b1-370d5a6cc5f0.png)
but if not projact can detect
![image](https://user-images.githubusercontent.com/112748173/212293492-07429ebc-3d9d-4f8c-b035-e177ca36448b.png)
or tag manga and manhua cant detect

**HakuNeko (please complete the following information):**
 - Version [e.g. 8.3.4]

**Comment by MikeZeDev** [comment]
I see, There are links for Manwha and Manga, filter miss mangas
