### ISSUE TITLE
[Site Request] COLAMANHUA

### ISSUE THREAD

**Issue by gembikong** [manga-download/hakuneko#5368]
**Name of the website**
COLAMANHUA

**Website urls (examples below)**
- Site: https://www.colamanhua.com/16918/
- Manga List: https://www.colamanhua.com/show?orderBy=update
- Manga example: https://www.colamanhua.com/16918/
- Chapter online viewer example: https://www.colamanhua.com/16918/1/148.html

**Languages**
Chinese

**Website relationship*
copy of the english website http://mangadig.com/

**Comment by MikeZeDev** [comment]
Already supported please check before making issues. If website needs update make an appropriate issue.

**Comment by flysk1** [comment]
Website not working when reading chapter or download on app sir! @MikeZeDev

**Comment by MikeZeDev** [comment]
>  If website needs update make an appropriate issue.

What i wrote still applies. Moreover, its not fixed on stable but it was on nightly build please try nightly.
