### ISSUE TITLE
Not able to synchronize with Tsuminos's manga database

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#537]
> **From:** HakuNeko User

I am unable to synchronize with Tsumino's manga database. I am using Debian 10 on amd64. I have tried interacting with the website, then trying again, but to no avail.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
From time to time a captcha may popup to continue using the website.
To proceed just solve the captcha, press the continue button and then close the popup.

----

<img width="590" alt="tsumino-captcha" src="https://user-images.githubusercontent.com/27136773/67144949-0e85e300-f27d-11e9-8407-431c614e871b.png">
