### ISSUE TITLE
[Komikav] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5372]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
![image](https://user-images.githubusercontent.com/112748173/212462031-76395034-04a1-4b89-ba1c-a80895277941.png)
![image](https://user-images.githubusercontent.com/112748173/212462068-cd7e38a1-1be9-46e6-a150-828d2a7c3224.png)
![image](https://user-images.githubusercontent.com/112748173/212462045-219687a5-c5e9-4ec8-bb81-6230d28d05c0.png)
https://komikav.com/manga/  (mangalist)

**To Reproduce**
1. Komikav
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version e.g. 8.3.4

**Comment by MikeZeDev** [comment]
No offense, but its kinda useless to report every website that came to activate Cloudflare from time to time. 

If it looks like this
![image](https://user-images.githubusercontent.com/10671518/212467444-edd721cb-7933-4862-93b1-850305ff6d84.png)

its CF and we cant do anything (at least, for now ;) )
