### ISSUE TITLE
Run hakuneko in a headless machine

### ISSUE THREAD

**Issue by maipley** [manga-download/hakuneko#5373]
Is there a way to run hakuneko just from the command line?
I'm trying to install hakuneko on a headless machine, and to use it by ssh-ing into the machine, but i can't find any documentation on that topic. Or if it is even possible.
(I'm trying to run it in a headless debian based machine)

**Comment by MikeZeDev** [comment]
I am talking in my name only. I think not only this is not planned but its not planned on purpose.
Hakuneko is not intended to be a mass downloading tool, and headless use is making it close to that.

Again, i may be wrong.

**Comment by Sheepux** [comment]
hakuneko has no command line options and never will

**Comment by 27136773** [comment]
See #2602 for alternatives
