### ISSUE TITLE
[MangaHub.FR] Connector not working

### ISSUE THREAD

**Issue by Andflowan** [manga-download/hakuneko#5376]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When we click on a manga section in the app, in mangahub connector, chapters don't load but on the mangahub.fr website there is a manga list that work and load manga without issues.

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![HakuNeko 16_01_2023 00_35_55](https://user-images.githubusercontent.com/117603445/212573732-cd1fd21f-3e32-408f-bb9a-69b77bef3df7.png)
![Mozilla Firefox 16_01_2023 00_37_24](https://user-images.githubusercontent.com/117603445/212573738-519a1bac-65c1-4196-a92c-2f86cef1ef9c.png)
![Mozilla Firefox 16_01_2023 00_37_55](https://user-images.githubusercontent.com/117603445/212573741-0ecb0a99-29fb-4edd-a15b-75b1dea9b821.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4992
