### ISSUE TITLE
[Lezhin] Can't download

### ISSUE THREAD

**Issue by brmqtr** [manga-download/hakuneko#5377]
Hi, I can't download from Korean lezhin.

This is the error that I get

[..redacted to remove identifying parts...]

A:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED TypeError: Failed to construct 'URL': Invalid URL
    at ClipboardConnector.mjs:50
    at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28)
    at HTMLElement.onUpdateMangaListClick (mangas.html:233)
    at HTMLElement.onPasteClick (mangas.html:340)
    at HTMLElement.handler (template-stamp.html:96)
(anonymous) @ ClipboardConnector.mjs:66
_getMangaList @ ClipboardConnector.mjs:48
updateMangas @ ClipboardConnector.mjs:28
onUpdateMangaListClick @ mangas.html:233
onPasteClick @ mangas.html:340
handler @ template-stamp.html:96
ClipboardConnector.mjs:66 CLIPBOARD: InterProcessCommunication.mjs:13 TypeError: Failed to fetch Error: No matching connector found for URL interprocesscommunication.mjs:13 TypeError: Failed to fetch
    at ClipboardConnector.mjs:59
    at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28)
    at HTMLElement.onUpdateMangaListClick (mangas.html:233)
    at HTMLElement.onPasteClick (mangas.html:340)
    at HTMLElement.handler (template-stamp.html:96)
(anonymous) @ ClipboardConnector.mjs:66
_getMangaList @ ClipboardConnector.mjs:48
updateMangas @ ClipboardConnector.mjs:28
onUpdateMangaListClick @ mangas.html:233
onPasteClick @ mangas.html:340
handler @ template-stamp.html:96
ClipboardConnector.mjs:66 CLIPBOARD: (anonymous) @ InterProcessCommunication.mjs:13 TypeError: Failed to construct 'URL': Invalid URL
    at ClipboardConnector.mjs:50
    at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28)
    at HTMLElement.onUpdateMangaListClick (mangas.html:233)
    at HTMLElement.onPasteClick (mangas.html:340)
    at HTMLElement.handler (template-stamp.html:96)
(anonymous) @ ClipboardConnector.mjs:66
_getMangaList @ ClipboardConnector.mjs:48
updateMangas @ ClipboardConnector.mjs:28
onUpdateMangaListClick @ mangas.html:233
onPasteClick @ mangas.html:340
handler @ template-stamp.html:96

**Comment by MikeZeDev** [comment]
What version of hakuneko are you using, nightly or stable ? Were you logged, and how? What was the manga and the chapter ? Is the chapter paid or unlocked by other means? I am really interested because i was not able to test paid chapters when i fixed
 Lezhin code. With your help i may correct that bug.

**Comment by brmqtr** [comment]
Hi, I am using nightly. I was logged in. I was first logged out and could only see free chapters, but after I logged in, I could see the two chapters I paid for on Hakuneko. 

https://www.lezhin.com/ko/comic/broken_wings

This was manhwa and I tried to download the first three chapters. Most of the chapters on this manhwa are free now, and only the last two chapters have to be paid to be viewed and I bought those two chapters.

**Comment by MikeZeDev** [comment]
How did you logged in precisely?

**Comment by brmqtr** [comment]
https://i.imgur.com/klk5eFP.png

Here is the screenshot of the error.

**Comment by brmqtr** [comment]
I logged in like the Hakuneko guide said. 

Open the [website selection list](https://hakuneko.download/docs/manual-website-interaction/Quick-Reference#3-source-selection)
Click on the link in the top right corner of the website that requires manual interaction (e.g. Toomics)
Now wait until the website has been loaded
Login with your credentials through the website
Close the window

I used this way.

**Comment by MikeZeDev** [comment]
Logout and put your credentials in settings window, under LEZHIN Korea iirc. Restart Hakuneko. And retry.

**Comment by MikeZeDev** [comment]
If you are ok with helping me fixing downloading content can you come on Hakuneko Discord pls? There is something id better check with someone who paid for content.

**Comment by brmqtr** [comment]
Thank you for your help! The free chapters are downloading okay, but the paid chapters are downloading like this.

https://i.imgur.com/ngcJWJj.png

It is saved as bin files and it's blank empty files. 

I left a message at Hakuneko discord help chatroom.

**Comment by MikeZeDev** [comment]
I think i got it.
