### ISSUE TITLE
[Bug] PDF Export soft locked when at least 1 image on source fails to download

### ISSUE THREAD

**Issue by himdo** [manga-download/hakuneko#5380]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When downloading certain mangas the download queue gets stuck at 100% forever. This is easily reproduceable bellow.

**To Reproduce**
1. Set the "Chapter File Format" in the settings to "Portable Document (*.pdf)"
2. Go to the Connector "WebToonily"
3. Search for the manga "Leveling Up, By Only Eating!"
4. Attempt to download any of the following chapters: 2, 3 , 4, 5, 6, 9, 10, 11, 12, 14, 16, 23, 25, 26, 27, 28, ... 76, I first observed this on chapter 76.
5. Observe that the download never finishes, in addition, if you are watching the network traffic you should observe that some of the images are broken

**Expected behavior**
The app throws an error on broken images and moves on to the next download

**Screenshots**
N/A

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version: 6.17@554b0c

**Additional context**
In addition to this I've pulled the current master branch and have fixed the issue locally, however when attempting to push my branch I am getting a 403.

To fix this the following code needs to be adding to "web/mhs/engine/Storage.mjs":
"_saveChapterPagesPDF"
Encapsulate the entire function in a try catch block, with a throw statement in the catch part.

"_addImageToPDF"
Encapsulate the entire function in a try catch block, with a throw statement in the catch part. As well as for the bitmap promise add: "resolve(img)" to the end of the promise.

That is all that is needed.

**Comment by MikeZeDev** [comment]
Fork HN, make changes on a branch of your fork (cause its cleaner) and make a PR :)
