### ISSUE TITLE
[Frscan] Connector not working

### ISSUE THREAD

**Issue by ReivenIV** [manga-download/hakuneko#5386]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The conector is loging the information but the images or the posibility to download the chapter is not possible.
I double check the website and the chapters there are working just fine. 
https://frscan.ws/manga/dr-stone

**To Reproduce**
1. Name of connector: 
    - Frscan
2 Name of manga (if connector update is working) : 
    - Dr.stone
3. Name of chapter (if manga update is working) : 
    - none
4. Copy any relevant error message :
    - i don't know if its relevant. 
    - Here is the error log that appears when i click to download a chapter: <br>
![image](https://user-images.githubusercontent.com/94102249/213010369-1efc9e91-8179-403f-9ec7-a96fbdcbc2cc.png)

**HakuNeko (please complete the following information):**
 - Version : 6.1.7@554b0c

**Comment by MikeZeDev** [comment]
It works on nightly . Cant remember why.

![image](https://user-images.githubusercontent.com/10671518/213146145-b5eb2447-1d3d-42a3-9397-9c9a83ae06f1.png)
