### ISSUE TITLE
[Japanread] Connector still not working

### ISSUE THREAD

**Issue by ReivenIV** [manga-download/hakuneko#5388]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The conector is loging the information but the images or the posibility to download the chapter is not possible.
I double check the website and the chapters there are working just fine. 
https://www.japanread.cc/manga/demon-slayer-colored-edition-fr/143

**To Reproduce**
1. Name of connector: 
    - Japanread
2 Name of manga (if connector update is working) : 
    -  Devil slayer
3. Name of chapter (if manga update is working) : 
    - none
4. Copy any relevant error message :
    - Here is the error log that appears when i click to download a chapter: <br>
## F12 error log
![image](https://user-images.githubusercontent.com/94102249/213122215-388f556b-35e1-4664-84a5-b8535aad2107.png)
## On website
![image](https://user-images.githubusercontent.com/94102249/213122902-eb3f2e5a-6d7f-4771-b3e5-d36a922a9edf.png)
## What UI show in hakuneko 
![image](https://user-images.githubusercontent.com/94102249/213123289-9389663f-a62b-4c5e-ba9f-ac0f400c5537.png)

**HakuNeko (please complete the following information):**
 - Version : 6.1.7@554b0c
 - Os: Windows 10
 - Brave 1.41.171

**Comment by MikeZeDev** [comment]
No need to open another issue.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4513
