### ISSUE TITLE
[mangadex] Manga list synchronization not working

### ISSUE THREAD

**Issue by Garakusi** [manga-download/hakuneko#5390]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Manga list update fails with the error: 
Failed to update manga list for MangaDex

Failed to receive content from "https://api.mangadex.org/manga?limit=100&offest=3300&order%5BcreatedAt%5D=asc&contentRating%5B%5D=safe&contentRating%5B%5D=suggestive&contentRating%5B%5D=erotica&contentRating%5B%5D=pornographic" (status: 400) -

**To Reproduce**
0. Fresh install hakuneko-desktop from AUR (Arch Linux)
1. Sync mangadex manga list
2. Wait for the pop up previously described appear

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5258
