### ISSUE TITLE
{comicブースト] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5391]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I tried refreshing after picking the comicブースト in the connector, but it didn't work.

**To Reproduce**
1. comicブースト
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/78268518/213291057-618f8cd8-2c23-4b5d-a0fc-d11ee217aa13.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7@554b0c

**Comment by MikeZeDev** [comment]
Hum, manga list not available anymore. Would https://comic-boost.com/genre/ be an acceptable (exhaustive) replacement?

**Comment by MikeZeDev** [comment]
Dev note : Configuration file is encrypted.

**Comment by arifsyahbani** [comment]
I'm sorry, I want to make the same issues with Comic Boost. After pasting (https://comic-boost.com/content/01100001), then this appeared in the dev console
![image](https://user-images.githubusercontent.com/45502806/235564752-585bc3d0-950c-4f42-9b7d-8e8b0197f093.png)
Is this the same issue with "Corona EX" connector? https://github.com/manga-download/hakuneko/issues/5733.

**Comment by MikeZeDev** [comment]
Completely unrelated.
