### ISSUE TITLE
[Site Request] Magbz

### ISSUE THREAD

**Issue by TenshiHunter** [manga-download/hakuneko#5393]
Manhwa/magbz

- Site: https://magbz.ir/
- Manga List: https://magbz.ir/category/manga/

**Languages**
Persian

**Comment by MikeZeDev** [comment]
dead or geoblocked?

**Comment by TenshiHunter** [comment]
> dead or geoblocked?
ig it's geoblocked. https://webmanga.ir/

**Comment by MikeZeDev** [comment]
What is this url? And why posting it? All i see is direct download links, there is nothing for Hakukneko here. Dont forget not everyone can understand Arabic  so excuse me if i miss something.
