### ISSUE TITLE
[Site Request] Hentaivn

### ISSUE THREAD

**Issue by mrchanqing01** [manga-download/hakuneko#5394]
**Name of the website**
Hentaivn

**Website urls (examples below)**
- Site: https://hentaivn.de/
- Manga List: https://hentaivn.de/danh-sach.html
- Manga example: https://hentaivn.de/32841-doc-truyen-illya-chan-da-san-sang-de-lam-me.html
- Chapter online viewer example: https://hentaivn.de/32841-60558-xem-truyen-illya-chan-da-san-sang-de-lam-me-oneshot-no-cac.html

**Languages**
vietnamese

**Comment by MikeZeDev** [comment]
Cloudflare

**Comment by egnaro1007** [comment]
They changed the url from hentaivn.de to hentaivn.tv

**Comment by MikeZeDev** [comment]
doesnt matter, cant do it, CloudFlare

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4798

**Comment by saigonacademi** [comment]
Name of the website: Hentaivn

Website urls (examples below)

Site: https://hentaivn.asia/
Manga List: https://hentaivn.asia/manga/
Manga example: https://hentaivn.asia/manga/chi-giup-viec/
Chapter online viewer example: https://hentaivn.asia/manga/chi-giup-viec/chap-19/

Used RESERVE PROXY deny DMCA

**Comment by MikeZeDev** [comment]
dont hijack an issue for a website (hentaivn.bio) with another totally unrelated website (hentaivn.asia). Make a proper issue.
