### ISSUE TITLE
Select the chapters to download[Feature]

### ISSUE THREAD

**Issue by acebed** [manga-download/hakuneko#5397]
Hello,
first i want to tell u that i enjoy reading mangas in hakuneku,
as for me its the best app i ever tried.
the only issue im facing is while downloading manga chapter with big quantity but not all chapters
as it takes some time to download the chapters one by one,
i tried as far as i know to select the chapets but i couldnt, i hope u will give me some tip want aware about or adding this feature for next update
Thanks

**Comment by MikeZeDev** [comment]
You can use regexp but that a bit complicated. That thing is planned in Haruneko obviously.

**Comment by Sheepux** [comment]
duplicate #382
Multi chapter selection is implemented in haruneko (Triggering the download isn't :D)
![multiselect](https://user-images.githubusercontent.com/19878135/213949966-bf1b021c-f04d-4a46-8088-bfcf08c1bc21.gif)
