### ISSUE TITLE
[Tappytoon (English)] Some manga titles are not in the search result

### ISSUE THREAD

**Issue by DragonWhisperer** [manga-download/hakuneko#5398]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Some manga titles are not in the search result, like:
* [The Villainess Behind the Mask](https://www.tappytoon.com/en/book/the-villainess-behind-the-mask)
* [The Legendary Fossil](https://www.tappytoon.com/en/book/the-legendary-fossil)

But I can view and download other titles from Tappytoon (like [It Was All a Mistake](https://www.tappytoon.com/en/book/it-was-all-mistake)), including paid chapters.

**To Reproduce**
1. Tappytoon (English)
2. Name of manga: The Villainess Behind the Mask
3. No manga result
4. No popup error message, but 2 errors within the console (I don't think it's related to the problem):
   ```
   hakuneko://plugins/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
   ```

   ```
   Settings.mjs:307 Failed to load HakuNeko settings! Error: ENOENT: no such file or directory, open 
   'C:\Users\DragonWhisperer\AppData\Roaming\hakuneko-desktop\hakuneko.settings'
   ```

**Screenshots**
![Tappytoon-1](https://user-images.githubusercontent.com/50916459/213703347-ede9ee45-bd1a-4d47-9f88-cb608de3346b.png)

![Tappytoon-2](https://user-images.githubusercontent.com/50916459/213703442-5675425b-d956-4f61-a3da-5ff1d92ea3b4.png)

**HakuNeko:**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Tappytoon seems to limit results to 100 manga.  We cant change that, so it misses somes.. But you can always paste the manga url it should work.

![image](https://user-images.githubusercontent.com/10671518/213719281-39185c5c-8ee6-4c7d-919c-5f35f8398034.png)

**Comment by DragonWhisperer** [comment]
@MikeZeDev 
The limit should not affect the search result like this, this is definitely a bug.
And thanks, it works with manga url 👍

**Comment by MikeZeDev** [comment]
> @MikeZeDev The limit should not affect the search result like this, this is definitely a bug. And thanks, it works with manga url 👍

Maybe i wasnt clear enough : Its ENFORCED by the website there is nothing we can do :D. As you found a solution i am closing this.

**Comment by 27136773** [comment]
HakuNeko does not perform the search on the website itself.
HakuNeko downloads a local list and perform the search within the list.
If the website only provides a limited list, some manga will be missing.
