### ISSUE TITLE
[Baozimh] Connector not working

### ISSUE THREAD

**Issue by tenchipuu** [manga-download/hakuneko#5408]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Random images are downloaded as the website logo .webp
![hakuneko](https://user-images.githubusercontent.com/123152059/213899152-11b671b0-85a1-491d-b530-f1e7780d7b8f.png)
![Untitled](https://user-images.githubusercontent.com/123152059/213899190-8efee738-47ba-4ca4-8167-2406f58c72d0.png)

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7@554b0c

**Comment by MikeZeDev** [comment]
Use nightly is has been fixed already
