### ISSUE TITLE
[Hiperdex] Connector not working

### ISSUE THREAD

**Issue by FalconLoss** [manga-download/hakuneko#5409]
Hiperdex is now changed to following address:
https://1sthiperdex.com/ [New address]
https://hiperdex.com/ [Old address]

**To Reproduce**
1. Connect to Hiperdex
2. Search any manga
3. Select any chapter
4. Nothing will load

 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Use nightly its updated

**Comment by FalconLoss** [comment]
> Use nightly its updated

website changed again 😔

**Comment by MikeZeDev** [comment]
Thats becoming ridiculous ;/

**Comment by FalconLoss** [comment]
I know
and I feel like it's going to change back again in 2-3 weeks 😒

**Comment by MikeZeDev** [comment]
hum... gotta put url as a setting :shrug:
