### ISSUE TITLE
[Site Request] manhwa18.cc

### ISSUE THREAD

**Issue by FalconLoss** [manga-download/hakuneko#5410]
**Name of the website**
Manhwa18.cc

**Website urls (examples below)**
- Site: https://manhwa18.cc/
- Manga List: https://manhwa18.cc/webtoons
- Manga example: https://manhwa18.cc/webtoon/worn-and-torn-newbie
- Chapter online viewer example: https://manhwa18.cc/webtoon/worn-and-torn-newbie/chapter-127

**Languages**
English

**Additional details**
Manhwa Manga Webtoon

**Comment by MikeZeDev** [comment]
Already supported. https://github.com/manga-download/hakuneko/blob/1e5953e4d189ded736a50d8bf9b96520aa4c3d6b/src/web/mjs/connectors/Manhwa18cc.mjs

**Comment by MikeZeDev** [comment]
No advertising, no recommendations. locking
