### ISSUE TITLE
Verytoon Connector not working

### ISSUE THREAD

**Issue by Pipixel** [manga-download/hakuneko#5411]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I want to download a chapter I buy, it shows an error like if the links are invalid, even if I am login. Even the free links doesn't work either.

**To Reproduce**
1. Select Verytoon plugin.
2. Login to Verytoon
3. Past the link from Verytoon (because there's no manga list).
4. Select the series purchase.
5. And try to download.

**Screenshots**

![VO877Luh9M](https://user-images.githubusercontent.com/66361896/213918990-02d55ace-9a5d-4146-b633-2e6ff3a99206.png)

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by MikeZeDev** [comment]
Just to be clear, its a purchased serie? 

If its the case,  it may require additional coding, and an account who paid for something for testing. Cant test paid content without paying first :D

**Comment by MikeZeDev** [comment]
Stupid bug, my fault
