### ISSUE TITLE
[Site Request] mangago

### ISSUE THREAD

**Issue by HorrorBest** [manga-download/hakuneko#5414]
**Name of the website**
mangago

**Website urls (examples below)**
- Site: https://www.mangago.me/
- Manga List: https://www.mangago.me/list/directory/all/1/
- Manga example: https://www.mangago.me/read-manga/090_eko_to_issho/
- Chapter online viewer example: https://www.lady-first.me/article/the-malabar-coat-the-super-star-coat-of-winter,866.html

**Languages**

- English

**Website relationship*
No idea

**Additional details**
This doesn't look like any other website that I know of but, The Online reader Is not a scroll based reader (to move between pages you have to click a button) also you get redirected to another domain to use the reader

**Comment by MikeZeDev** [comment]
Mangago is supported. Please look before posting issues.

**Comment by HorrorBest** [comment]
> Mangago is supported. Please look before posting issues.

its not... I didn't find it in the app...

I swear I searched from Mangago and didn't find it now its there

**Comment by MikeZeDev** [comment]
![image](https://user-images.githubusercontent.com/10671518/214247268-dd2721e1-0327-4192-868f-fdf202dc5881.png)
