### ISSUE TITLE
impossible to display the mangas

### ISSUE THREAD

**Issue by Onyx46** [manga-download/hakuneko#5417]
Hello, 
I use HakuNeko on windows 11 on version 6.1.7 in 64 bits. 
The rev number is 554b0c. 
I have not changed any of the default settings of the software. 

When I try to use the software, no manga is displayed in the list. I have tried different sites and it is always the same result. I tried to refresh the page for each one but nothing works. 

Moreover for the Japscan.me site, when I try to update, it displays an error message: 
"Failed to update manga list for Japscan 
Cannot read property "text" of undefined" 

Can you help me to solve this problem so I can use HakuNeko.

**Comment by MikeZeDev** [comment]
So basically, its a problem with japscan? In this case problem is know and not fixed

**Comment by Onyx46** [comment]
no, it's not just with Japscan. No matter what I use nothing works I don't have access to any manga from any platform.

**Comment by MikeZeDev** [comment]
That doesnt help much. Name the one you tested

**Comment by MikeZeDev** [comment]
Duplicate issue + lack of informations.
