### ISSUE TITLE
[Mangareaderto] failed to load within the given timeout of sixty seconds when downloading volumes.

### ISSUE THREAD

**Issue by Dingo536** [manga-download/hakuneko#5418]
The Bug
I downloaded Hakuneko to download mange. I got it working and then found out I could also download in volumes, but when I click download after a minute it says that it failed to load whitin the given timeout of sixty seconds. I also can't view the manga as it gives me the same error. It is not a connector issue, because the chapters do work. I think it is because the volumes are to big to load within sixty seconds. Is there a way to change the sixty second time period or maybe something else?

To Reproduce
1. Load a connector that has volumes( i tried mangareader as i couldn't find a other one that could).
2. earch for a manga ( I tried The quintessential quintuplets, my hero academia, fire force and ayakashi triangle).
3. Click download and after sixty seconds it gives a error.

Additional context
My os is windows 10 and I run version 6.1.7 of hakuneko

Thanks in advance.

**Comment by MikeZeDev** [comment]
I am reluctant to increase the timeout but i everyone keep asking, that so annoying . Well i'll make a PR and i see what other devs say.
