### ISSUE TITLE
[Site Request] JuinJutsuTeam

### ISSUE THREAD

**Issue by forzaportante** [manga-download/hakuneko#5420]
**Name of the website**
JuinJutsuTeam

**Website urls (examples below)**
- Site: https://www.juinjutsureader.ovh/
- Manga List: https://www.juinjutsureader.ovh/directory/
- Manga example: https://www.juinjutsureader.ovh/series/shy/
- Chapter online viewer example: https://www.juinjutsureader.ovh/read/shy/it/0/1/page/1

**Languages**
Italiano

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/2728
