### ISSUE TITLE
[Site Request] Mangastk.xyz

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5425]
**Name of the website**
Mangastk.xyz

**Website urls (examples below)**
- Site: https://mangastk.xyz/
- Manga List: https://mangastk.xyz/serie/
- Manga example: https://mangastk.xyz/serie/revelacion-de-la-juventud/
- Chapter online viewer example: https://mangastk.xyz/serie/revelacion-de-la-juventud/1/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
What the relation with https://mangastk.net/ (already requested) btw?

**Comment by Lenoyr** [comment]
Dead Site
"Good evening/good day/good afternoon, please receive a warm greeting everyone. This message is to inform you that 'MANGASTK' is permanently closed. We reserve our privacy policy. Thank you and goodbye." 
It is a message from your Telegram.

![imagen](https://github.com/dazedcat19/FMD2/assets/65477084/c6c338c7-8632-4fd7-bc99-f80a5d24e0f3)
