### ISSUE TITLE
[Site Request] Rightdark-scan

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5426]
**Name of the website**
Rightdark-scan

**Website urls (examples below)**
- Site: https://rightdark-scan.com/
- Manga List: https://rightdark-scan.com/manga/
- Manga example: https://rightdark-scan.com/manga/maou-to-seijo-ga-michibiku-boukensha-life-mahou-tekisei-dakedo-kyokudai-maryoku-ni-kakusei-shimashita/
- Chapter online viewer example: https://rightdark-scan.com/manga/maou-to-seijo-ga-michibiku-boukensha-life-mahou-tekisei-dakedo-kyokudai-maryoku-ni-kakusei-shimashita/capitulo-1/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara
