### ISSUE TITLE
[Gammaplus] Connector not working

### ISSUE THREAD

**Issue by vsatyamesc** [manga-download/hakuneko#5427]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Gammaplus is not loading again on Hakuneko. I can load the website properly on the Hakuneko client. It loads all the manga but not the chapter.

**To Reproduce**
1. Name of connector - Gammplus
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working) - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![image](https://user-images.githubusercontent.com/60954779/215085918-09f8f407-56f6-43b1-a103-3446866e5980.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.1.7@554b0c]

**Comment by vsatyamesc** [comment]
Currently, I'm using my own python script to fetch images, but they are changing the image res or something I guess I don't wanna bother. You might wanna fix that too if you de-puzzle the image with your own algorithms.

**Comment by MikeZeDev** [comment]
Cant reproduce, please name a manga and a chapter where you get the problem.

![image](https://user-images.githubusercontent.com/10671518/215108942-1523c807-2406-4003-bc71-bb6190b466c2.png)

I use nightly build ofc.

**Comment by vsatyamesc** [comment]
> Cant reproduce, please name a manga and a chapter where you get the problem.
> 
> ![image](https://user-images.githubusercontent.com/10671518/215108942-1523c807-2406-4003-bc71-bb6190b466c2.png)
> 
> I use nightly build ofc.

https://gammaplus.takeshobo.co.jp/manga/imaizuminchiha/

I used the latest build idk? I always checks for the updates right?

**Comment by MikeZeDev** [comment]
>I used the latest build idk? I always checks for the updates right?

Stable version and nightly version are auto updated on launch. But it can takes months before stable get available updates that are instantly here in nightly.  Your version number tells me you are using stable, not nightly. Use nightly.

![image](https://user-images.githubusercontent.com/10671518/216125877-d45e9141-79b8-4085-aa4b-21534035c492.png)

**Comment by vsatyamesc** [comment]
alright.
