### ISSUE TITLE
[Site Request] Raijin Scans

### ISSUE THREAD

**Issue by learner01x** [manga-download/hakuneko#5429]
**Name of the website**
Raijin Scans

**Website urls (examples below)**
- Site: https://raijinscans.com/
- Manga List: https://raijinscans.com/manga/?m_orderby=alphabet
- Manga example: https://raijinscans.com/manga/i-am-the-fated-villain/
- Chapter online viewer example: https://raijinscans.com/manga/i-am-the-fated-villain/chapitre-59/

**Languages**
french

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by TristanWasTaken** [comment]
**Additional details**
Is geoblocked with cloudflare and can only be accessed from France. Using a vpn works.

**Comment by learner01x** [comment]
Thanks for your answer

Envoyé depuis Proton Mail mobile

-------- Message d'origine --------

**Comment by MikeZeDev** [comment]
Madara template
