### ISSUE TITLE
[MangaKawaii] Connector not working

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/hakuneko#5435]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes. The web site changed its layout.

**Describe the bug**
TypeError when trying to download chapter : Cannot read property '1' of null

**To Reproduce**
1. MangaKawaii
2. Martial Peak
3. last one for example
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
5. 
Connector.mjs:618 TypeError: Cannot read property '1' of null
    at MangaKawaii._getPages (MangaKawaii.mjs:63)
    at async MangaKawaii._getPageList (Connector.mjs:615) EventTarget

**HakuNeko (please complete the following information):**
 - Version : latest

**Comment by MikeZeDev** [comment]
hum, they changed the website.

**Comment by didierGuieu** [comment]
Thanks a lot for this update !
