### ISSUE TITLE
Removal Request for JPMANGAS

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/hakuneko#5436]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Which website should be removed?
jpmangas

Why should this website be removed from HakuNeko?
The site does not longer exist.

**Comment by MikeZeDev** [comment]
Removal Requests are for people waiting their own website removed from Hakuneko. Thats true a cleaning is needed tho.
