### ISSUE TITLE
[Feature Request] BilibiliComics Image Resolution

### ISSUE THREAD

**Issue by omodia** [manga-download/hakuneko#5439]
**Is your feature request related to a problem? Please describe.**

Currently Hakuneko downloads images in their Original Resolution/Raw+ (2400px) by default which is very good.
But there is no reader that has smooth scrolling with this resolution in long strip mode in PC. Mobile supports it.

**Describe the solution you'd like**
So can you add support for the remaining resolutions by creating a column under or above preferred image format in hakuneko's bilibilicomics settings namely,
- Raw+ / Original (2400px)
- Raw (1600px)
- HD (1000px)
- SD (800px)

**Describe alternatives you've considered**
None.

**Context (please complete the following information):**

**Additional context**

**Comment by MikeZeDev** [comment]
I tried changing random manga resolution on the website : from HD to SD, its still downloading the same pictures. It just change a value in browser storage but i see no effects.

**Comment by omodia** [comment]
The tabs are Raw, HD, SD. The image dimensions appear in the pop-up.

**Comment by MikeZeDev** [comment]
Gotta look into how they cook the url before requesting /Imagetoken. Need to separate image format (currently called quality in hn) and quality( sd, hd, raw). Incorrect combination of format and quality may prevent downloading :/

**Comment by omodia** [comment]
### A suggestion for adding image resolutions.
- Total four resolutions. Raw+, Raw, HD, SD.
- Since you said that Raw+ is currently called quality in hakuneko, rename it as Raw+.
- You only need to look into Raw, HD URL's.
- Only Raw+, Raw, HD are important.

**Comment by MikeZeDev** [comment]
Website JSON only mention 3 resolutions

**Comment by omodia** [comment]
In the above video, you can see 4 resolutions.

**Comment by MikeZeDev** [comment]
Its written RAW HD and SD

**Comment by omodia** [comment]
Use hakuneko to download. It downloads 2400w file (Raw+/Original).
These three can be seen in video.
- RAW (1600w)
- HD (1000w)
- SD (800w)

**Comment by MikeZeDev** [comment]
You are mistaken there is not raw+.  Listen : 

Website gives us file links with file dimensions. The value we got depends on the quality choosed ; RAW, HD, SD.

Website use a formula to reduce the size asked according to quality (2400 is then reduced to 2000) then request the file. Its the "RAW" they serve, 2000px.

Hakuneko use the file dimension provided directly without the formula, so it request 2400 and you got a 2400 px file. Its still the same damn "raw" setting

![image](https://user-images.githubusercontent.com/10671518/219362803-bd09b733-fdd6-4ad0-971b-5fad734bfe83.png)

Bypassing their restriction on quality (like its done for now) may lead to problems. I'll stick to 3 qualities to ensure it will work and maybe put a checkbox to unrestrict raw quality for adventurous people.

**Comment by omodia** [comment]
Thanks for the explanation and your hard work. I now understand how images here work. Looking forward to it.

**Comment by omodia** [comment]
- Hey, I think you can close this issue.
- **I mean, It's best to always download / view the highest possible image quality the website can provide.**
- I don't even know why I asked for the low and mid image quality. Maybe, just for settings sake.
- **I apologize for the inconvenience it caused to you.**
- Hence, I am closing this issue as completed.

**Comment by MikeZeDev** [comment]
Website needed a fix, and that fix was related to quality, so i coded the feature at the same time. No need to close this, especially "as completed" for now . It will be closed in due time when feature is merged.

We are busy now, really busy, thats all.

**Comment by omodia** [comment]
- I mean, It's best to always download / view the highest possible image quality the website can provide.
- You previously added the login feature and everything was working, so, I thought the low, mid resolution image quality feature is unnecessary and closed this.
- My bad, sorry.
