### ISSUE TITLE
[Comic Brise] Connector not working

### ISSUE THREAD

**Issue by arifsyahbani** [manga-download/hakuneko#5440]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't get the images.

**To Reproduce**
1. Comicブリーセ (Comic Brise)
2. https://www.comic-brise.com/contents/tenfollo/
3. 第 8 話 (chapter 8)
4. DownloadJob.mjs:115 TypeError: Failed to fetch (29) ["connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDEucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDIucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDMucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDQucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDUucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDYucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDcucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDgucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMDkucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTAucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTEucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTIucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTMucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTQucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTUucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTYucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTcucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTgucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMTkucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjAucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjEucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjIucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjMucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjQucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjUucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjYucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjcucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjgucHRpbWcuanNvbiI%3D", "connector://comicbrise/?payload=Imh0dHBzOi8vd3d3Lm…C90ZW5mb2xsby9lcC9kYXRhLzAwMjkucHRpbWcuanNvbiI%3D"]

DownloadJob.mjs:141 GET connector://comicbrise/?payload=Imh0dHBzOi8vd3d3LmNvbWljLWJyaXNlLmNvbS9jb21pY19lcC90ZW5mb2xsby9lcC9kYXRhLzAwMDUucHRpbWcuanNvbiI%3D net::ERR_NOT_IMPLEMENTED

**Screenshots**
![erro comic brise jan 30 23](https://user-images.githubusercontent.com/45502806/215469810-7ccaa3e4-35ff-4b35-9a0a-36fd1694debb.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7@554b0c

**Comment by MikeZeDev** [comment]
SyntaxError: Unexpected token < in JSON at position 0

Speedbind?
