### ISSUE TITLE
[Site Request] INKR Comics

### ISSUE THREAD

**Issue by omodia** [manga-download/hakuneko#5442]
**Name of the website**
INKR

**Website urls (examples below)**
- Site: https://comics.inkr.com/
- Manga List: https://comics.inkr.com/
- Manga example: https://comics.inkr.com/title/1075-apocalypse-online
- Chapter online viewer example: https://comics.inkr.com/title/1075-apocalypse-online/chapter/65028-chapter-1-apocalypse-reborn

**Languages**
English

**Paid Content**
Account is required to access paid content.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3782

**Comment by MikeZeDev** [comment]
> You need to close the other ones and not this, as the links are old, the site has changed their links to the above mentioned ones.

Newest is the duplicate no matter what you say so i'll close it. It's not like we cant use google to find a link .
