### ISSUE TITLE
[Site Request] Reaper Scans [French]

### ISSUE THREAD

**Issue by LiliThEvil** [manga-download/hakuneko#5447]
**Name of the website**
Reaper Scans

**Website urls (examples below)**
- Site: https://reaperscans.fr
- Manga List: https://reaperscans.fr/webtoon/
- Manga example: https://reaperscans.fr/serie/it-all-starts-with-playing-game-seriously/
- Chapter online viewer example: https://reaperscans.fr/serie/it-all-starts-with-playing-game-seriously/chapitre-1/

**Languages**
French

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
![image](https://user-images.githubusercontent.com/10671518/216080403-e90395d9-d82c-45dd-a896-fbd166d60046.png)

Please do not request already supported websites
