### ISSUE TITLE
[linewebtoon-translate] Chapter's number

### ISSUE THREAD

**Issue by vic1707** [manga-download/hakuneko#545]
First of all, thank you for adding support to this site a few hours ago. 
You may already know this: chapters do not get their number and are called "c0000" depending on what makes them impossible to download (the images of the chapter being downloaded replace those of the previous chapter).

**Comment by 27136773** [comment]
Cannot be reproduced, please provide manga/chapter sample.

**Comment by vic1707** [comment]
I tried with linewebtoon-translate with the two following series in their french translation :  "the gamer" and "the god of highschool"

**Comment by 27136773** [comment]
Works fine for me, could it be you are using the experimental chapter format setting?

**Comment by vic1707** [comment]
it maybe that, i was using this set "%M% c%CH%" I'll try a reset to default

**Comment by 27136773** [comment]
Fixed in aaca48d1

**Comment by vic1707** [comment]
works when the chapter format is disable, thanks!

**Comment by 27136773** [comment]
Problem has been fixed to extract chapter number correctly.
