### ISSUE TITLE
[MangaSail] Connector not working

### ISSUE THREAD

**Issue by DGee3** [manga-download/hakuneko#5451]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Each time I press the refresh while MangaSail is the connector, the error "failed to update manga list" appears with "Cannot read property 'text of undefined" right below it
 
**To Reproduce**
1. MangaSail
2. Name of manga (if connector update is working) - Any
3. Name of chapter (if manga update is working) - Any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://user-images.githubusercontent.com/58882968/216749892-75fd44da-1c2b-4503-bbf8-fbdd9c4336c0.png)
![image](https://user-images.githubusercontent.com/58882968/216749728-3a8ebe66-b11f-483c-9ab2-77ae172618e5.png)

**HakuNeko (please complete the following information):**
 - Version 1.6.7@554b0c

**Comment by MikeZeDev** [comment]
Url changed
