### ISSUE TITLE
[Site Request] summanga.com

### ISSUE THREAD

**Issue by Zelloss010** [manga-download/hakuneko#5454]
summanga

https://summanga.com
- Site: https://summanga.com
- Manga List: https://summanga.com/manga/
- Manga example: https://summanga.com/manga/when-beauty-meets-beasts/
- Chapter online viewer example: https://summanga.com/manga/when-beauty-meets-beasts/chapter-1/

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara
