### ISSUE TITLE
[Site Request] h5 MangaToon

### ISSUE THREAD

**Issue by omodia** [manga-download/hakuneko#5456]
**Name of the website**
h5.MangaToon

**Website urls (examples below)**
- Site: https://h5.mangatoon.mobi/
- Manga List: Not Applicable
- Manga example: https://h5.mangatoon.mobi/contents/detail/5
- Chapter online viewer https://h5.mangatoon.mobi/cartoons/watch/5/2921

**Languages**
English

**Website relationship*
Alternate domain of [MangaToon](https://mangatoon.mobi/)

**Comment by MikeZeDev** [comment]
> Alternate domain of [MangaToon](https://mangatoon.mobi/)

Ok but any reason we should support it? Different mangas?

**Comment by omodia** [comment]
Some mangas/manhuas of MangaToon are unlocked here. It is their official site. Other than this, no other reason.

**Comment by omodia** [comment]
Are you going to add this site?
If possible, please support it.

**Comment by MikeZeDev** [comment]
We will consider it. I cant make promises tho.

* There are older request they take priority. Some were here for years before i came to help you know.
* We are focusing on Haruneko and fixing Hakuneko. New websites comes after.
* We are not fond of adding mirrors clones and alternates. It's still possible but I'd like to ask the team their opinion but they are busy.

**Comment by omodia** [comment]
Thank you for replying and also for considering this.

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4378
