### ISSUE TITLE
[Legacy-Scans] Connector not working

### ISSUE THREAD

**Issue by LiliThEvil** [manga-download/hakuneko#5457]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**
when i chose this connector No mangas list appeared & no chapters list too, it's simply a blank list. when refresh nothing change, no bug or error message idk what's wrong with this connector.

**To Reproduce**
1. Legacy-Scans
2. Name of manga (if connector update is working) - any
3. Name of chapter (if manga update is working) - any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - no error message

**Screenshots**
![test1](https://user-images.githubusercontent.com/75996528/216975666-2a4c524a-c4d4-43c4-8174-c632ca586bfb.png)
![test2](https://user-images.githubusercontent.com/75996528/216975700-7be6595f-fdba-42d9-9d21-3c3935bb0f46.png)

**HakuNeko (please complete the following information):**
 - Version HakuNeko 8.3.4 Nighty

**Comment by MikeZeDev** [comment]
Mangastream > Madara
