### ISSUE TITLE
manga not downloading at full resolution

### ISSUE THREAD

**Issue by TalPal** [manga-download/hakuneko#546]
I'm trying to get something from Lezhin.com. yes I have payed for the entire webtoon and yes I am logged in within HakuNeko. It downloads the webtoon perfectly but it's at a resolution of 720 x *whatever length* so for instance of one particular image, it's 720x1440 resolution whereas if I use HDoujin Downloader (which I don't like using for multipul reasons) it downloads at the full resolution which is 1024 x *whatever length* or in this case with the same image, 1024x2048. Is there anyway to get it to download at the full resolution or if not get it implemented?

**Comment by 27136773** [comment]
Use the nightly build or wait for release of v6 in December.

**Comment by 27136773** [comment]
Duplicate of #527
