### ISSUE TITLE
[lezhinus.com] Connector not working

### ISSUE THREAD

**Issue by YokoKitsune** [manga-download/hakuneko#5461]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The new chapters I just bought are no longer downloading, but the old chapters I downloaded 1 month ago can still be downloaded. 

**To Reproduce**
1. Lezhinus
2. Bad Thinking Diary
3. 32 and 33
4. /

**Screenshots**
<a href="https://zupimages.net/viewer.php?id=23/06/to2m.png"><img src="https://zupimages.net/up/23/06/to2m.png" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=23/06/rgs7.png"><img src="https://zupimages.net/up/23/06/rgs7.png" alt="" /></a>

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment]
* We know (https://github.com/manga-download/hakuneko/issues/5377) . Its The same error than the korean one but i'll let this issue open.
* A fix is already pending https://github.com/manga-download/hakuneko/pull/5378

When its merged make sure to use nightly build.

That said, its weird you were being able to download the others besides the first two.

Maybe its worth contacting us on discord.

**Comment by YokoKitsune** [comment]
![image](https://github.com/manga-download/hakuneko/assets/99326482/b8839519-f96f-4c43-ab8b-033eece42c21)
![image](https://github.com/manga-download/hakuneko/assets/99326482/a6dc0c09-5cec-41ac-8aae-28c56b33dc49)

Still having problems with lezhin.

**Comment by MikeZeDev** [comment]
Because fix is stil pending

**Comment by YokoKitsune** [comment]
Okay sorry
As the chapters were downloading, I thought it had been fixed
