### ISSUE TITLE
[Question] Questions related to connector dev

### ISSUE THREAD

**Issue by myocytebd** [manga-download/hakuneko#5462]
1. How to make the "menu" UI (=manga list + chapter list) draggable (drag to resize width) ?  
2. If ```_handleConnectorURI()``` is not implemented, is there any difference between ```return url``` and ```return createConnectorURI(url)``` for ```Connector._getPage()```?  
3. Lint problems:  
- Lint rule promoting ill format like: "Unnecessary parentheses around expression  no-extra-parens" for:  
```let index = pathSegs[2] === undefined ? 1 : (parseInt(pathSegs[2]) || -1);```
- Pointless Lint rule: "Unexpected constant condition  no-constant-condition" for ```while (true) {...}``` (with break in middle of loop)
- Failure to parse valid js: "Parsing error: Unexpected token"  
4. It seems that Hakuneko does not have a central place for collecting errors (and presenting to user or writing logs)?  
  What would be the intended way to report error? console.error?

**Comment by Sheepux** [comment]
We're moving to [HaruNeko](https://github.com/manga-download/haruneko) (WIP of next version of Hakuneko). I'd suggest investing time there
1. use css resize (i think i did a quick try last year but there were some issues)
2. default handleConnectorURI has some extra features
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/engine/Connector.mjs#L680
`this._applyRealMime(data);`  will fix some inconsistent mime headers sent by the website. If not used it leads to download/preview errors.
3. If you really need to use infinite loops (and most of the time that's not true) use `bool run=true and then run=false; continue; (or return)`. This lint rule covers some other cases.
However, I didn't check what lint rules we set in Haru
Also, there is probably something invalid in the js (but without it we can't guess)
4. If you need user interaction. Use standard [throw Error](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/Imgur.mjs#L24)
also if you need to log something in the console, yes use the console.

**Comment by myocytebd** [comment]
Thanks for the reply.  
It is unfortunate to see the project moves onto non-standard environment.

**Comment by Sheepux** [comment]
what do you mean by that ? That's the same stuff ...

**Comment by myocytebd** [comment]
> what do you mean by that ? That's the same stuff ...

I mean TypeScript (=> non-standard environment). (I know ts is "compiled" to js, and consider it awkward and counter-productive)

**Comment by Sheepux** [comment]
https://survey.stackoverflow.co/2022/#technology-most-popular-technologies

typescript is the third programming language
it's a standard

but whatever, think what you want.
