### ISSUE TITLE
[myanimelistmanga] Connector not working

### ISSUE THREAD

**Issue by stop5** [manga-download/hakuneko#5464]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Scraper is broken. I buyed a few mangas from the site any i read a few on the site, but the scraper can't detect even the individual volumes even when i point the page to the series or the volume

**To Reproduce**
1. myanimelistmanga, open the site inside hakuneko to log in
2. reload the connector (nothing happens)
3. open the site in hakuneko again, but this time to username -> bookshelf and copy the url
4. now one "manga" appears: "<username>'s Bookshelf - MyAnimeList.net"
Step 3+4 has the same effect if you choose the all manga page

**HakuNeko (please complete the following information):**
 6.1.7

**Comment by MikeZeDev** [comment]
OK lets say there is this serie : https://myanimelist.net/store/manga_volume/9298/That_Time_I_Got_Reincarnated_Again_as_a_Workaholic_Slime_Volume_2

which url should i chose for volume 1? 

```
viewer_url: "https://myanimelist.net/store/viewer/1/9298"
preview_url: "https://myanimelist.net/store/viewer/1/9298/preview"
```

I suppose the one where need login  (viewer_url) let you see the whole volume when purchased? What if you didnt? 
should i use the other if not purchased? 

So many questions

**Comment by MikeZeDev** [comment]
![image](https://user-images.githubusercontent.com/10671518/218272091-f4f235ce-5975-4d35-9e66-cadc93c147cf.png)

For purchased stuff i'd require your help. Come on HN discord.

**Comment by stop5** [comment]
how can i reach you on discord?

**Comment by MikeZeDev** [comment]
Hakuneko Discord. Look for the rabbit or open a subject in help section.

**Comment by stop5** [comment]
i opened a thread in #help-requests

**Comment by MikeZeDev** [comment]
Managed to make something working but the store also sells light novel, and for LN they use Publus.
Need slight modifications for it to work .
