### ISSUE TITLE
[Futabanet Monster] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#5465]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The titles load, but viewing the images or downloading them are not possible

**Screenshots**
<img width="1126" alt="Screenshot 2023-02-11 at 11 51 44 PM" src="https://user-images.githubusercontent.com/25418911/218293797-eda3531a-e1ab-4838-866b-5e6f14b52d1c.png">

**HakuNeko (please complete the following information):**
 - Version 6.1.7 @554b0c

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5280
