### ISSUE TITLE
[Site Request] Cocorip 

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5468]
**Name of the website**
Cocorip 

**Website urls (examples below)**
- Site: https://cocorip.net/
- Manga List: https://cocorip.net/manga/
- Manga example: https://cocorip.net/manga/selena-2/
- Chapter online viewer example: https://cocorip.net/manga/selena-2/capitulo-2/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara
