### ISSUE TITLE
[Kuaikan] Connector not working

### ISSUE THREAD

**Issue by nikkiwebsterrulz** [manga-download/hakuneko#5469]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
1. Can't download any manga - chapters all displayed as 0.
2. Can't find some manga for instance: 你却爱着一个他

**To Reproduce**
1. Name of connector: kuaikan
3. Name of manga: 你却爱着一个他 (https://www.kuaikanmanhua.com/web/topic/13464/)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
![image](https://user-images.githubusercontent.com/10671518/218518375-71cda441-545f-46e2-a865-7d6b7d20d408.png)

Download also worked. Use paste feature on Nightly build.

**Comment by nikkiwebsterrulz** [comment]
> ![image](https://user-images.githubusercontent.com/10671518/218518375-71cda441-545f-46e2-a865-7d6b7d20d408.png)
> 
> Download also worked. Use paste feature on Nightly build.

Thank you. It works! However it doesn't work with classic build. I have to download the nightly build to get it.

**Comment by MikeZeDev** [comment]
Fixes on Nightly will eventually reach stable, no need to reopen.

**Comment by hainguyenkutekute** [comment]
> Fixes on Nightly will eventually reach stable, no need to reopen.

help me. i can't download (https://www.kuaikanmanhua.com/web/topic/13464/)

**Comment by hainguyenkutekute** [comment]
> ![image](https://user-images.githubusercontent.com/10671518/218518375-71cda441-545f-46e2-a865-7d6b7d20d408.png)
> 
> Download also worked. Use paste feature on Nightly build.

help me. i can't download ( https://www.kuaikanmanhua.com/web/topic/13464/)

**Comment by MikeZeDev** [comment]
Open another ticket dont hijack a closed one. Btw, its because the page you linked is empty :D

![image](https://github.com/manga-download/hakuneko/assets/10671518/fa80c317-9142-4f3e-8564-099880842b47)
![image](https://github.com/manga-download/hakuneko/assets/10671518/a45092fa-3e7f-4eb2-8b78-c69af5e080c6)
