### ISSUE TITLE
20-10-2019 - Hakuneko not showing manga chapters at all!

### ISSUE THREAD

**Issue by yotsmungand90** [manga-download/hakuneko#547]
Hello.
I have updated the program to latest version.
Yesteday worked wonderful by using a slightly older version.
Today I pasted a list of mangas I like via clipboard, they were found but chapter list is not working.
I was using the slightly older version even today.
Updated to lastest.
Still not working.
Website is "Manganelo".
Used it yesterday worked like charm.
Please help.

**Comment by 27136773** [comment]
Some of the affiliates (e.g. MangaKakalot) uses a JavaScript based redirect to MangaNel for some mangas, based on using the `window.location` assignment. This script has been changed a little bit and therefore no longer works correctly with HakuNeko:

```javascript
window.location.assign("https://manganelo.com/manga/pn918005");
```

Furthermore MangaNel has added a new protection against MangaNel Unblocker, which also affects HakuNeko as it is falsely thinking it is following a redirect from MangaKakalot:

```javascript
if(REMOTE_HOST == 'https://manganelo.unblocker.cc/' || REMOTE_HOST == 'https://manganelo.unblocker.cc') {
    window.location = 'https://manganelo.net';
    window.stop();
}
```

**Comment by 27136773** [comment]
Fixed.
Use Nightly Build or wait for release of Version 6.x in December to use...
