### ISSUE TITLE
[Site Request] rawplus.co

### ISSUE THREAD

**Issue by Haozz200** [manga-download/hakuneko#5470]
**Name of the website**
rawplus.co

**Website urls (examples below)**
- Site: https://rawplus.co/manga-raw-online/
- Manga List: https://rawplus.co/%e3%83%9e%e3%83%b3%e3%82%ac%e7%94%9f%e4%b8%80%e8%a6%a7/?m_orderby=latest
- Manga example: https://rawplus.co/manga/%e6%88%a6%e9%87%8e%e3%81%ae%e4%b8%80%e6%9c%8d-raw-free/
- Chapter online viewer example: https://rawplus.co/manga/%e6%88%a6%e9%87%8e%e3%81%ae%e4%b8%80%e6%9c%8d-raw-free/chapter-8/

**Languages**
Japanese

**Comment by MikeZeDev** [comment]
rawplus.pro. Madara

**Comment by MikeZeDev** [comment]
No more madara  (and its rawplus.org now? )

**Comment by MikeZeDev** [comment]
Dead
