### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by letty25** [manga-download/hakuneko#5473]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
My downloaded jpg files cannot be open. The file created is something called a MacBinary Archive

**To Reproduce**
1. Selected my connector MangaHub
2. Searched for the manga Mangetsu no Ou
3. Downloaded Ch1 by clicking to cloud icon for ch 1 and waited for it to turn into a yellow folder
4. Opened the folder in my documents
5. Chapters are labeled 2.bin and 1.bin
6. Receive a message saying it can't be opened 
7. Tested if I could properly download an epub file and had no issue with that file format 

**Expected behavior**
I expect to see jpg files in the chapter folder 

**Screenshots**
<img width="1020" alt="Screenshot 2023-02-14 at 7 54 18 AM" src="https://user-images.githubusercontent.com/125332816/218814990-7a37d01a-4c5a-4e00-b527-5fd517aa06bf.png">

**Context (please complete the following information):**
 - OS: [MacBook Pro, 14 inch 2021, Ventura 13.0.1 ]
 - HakuNeko Version [e.g. 6.1.7@554b0c]

**Additional context**
This was my first time ever using HakuNeko so the issue could be with something simple I failed to understand with downloading manga

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5473

**Comment by letty25** [comment]
Why did you close this? Nothing was answered

**Comment by letty25** [comment]
> Duplicate #5473

why did you close this. Nothing has been fixed
