### ISSUE TITLE
[Site Request] Mangayaro

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5475]
**Name of the website**
Mangayaro

**Website urls (examples below)**
- Site: https://mangayaro.net/
- Manga List: https://mangayaro.net/manga/
- Manga example: https://mangayaro.net/manga/number-one-star-instructor-master-baek-one-hit-teacher-master-baek/
- Chapter online viewer example: https://mangayaro.net/number-one-star-instructor-master-baek-one-hit-teacher-master-baek-chapter-64-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4718

**Comment by Frezian** [comment]
the previous request didn't work, please help
