### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by ofenchuk** [manga-download/hakuneko#5476]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
MangaDex not working in app, manga list not loading "failed to receive content from... (status:400)", and site is not opening in app browser

**To Reproduce**
1. Name of connector
  MangaDex
2. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
  
  Uncaught SyntaxError: Unexpected token ?     entry.00187c8e.js:1 (Error i get wen  i try to open site in app browser)

**Screenshots**
-
![2023-02-15](https://user-images.githubusercontent.com/31511909/218963679-ea0b661e-a5fc-467e-9d8c-b1907180f7c6.png)

**HakuNeko (please complete the following information):**
 - Version [6.17@554b0c]

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5258. Cant do anything about that, its their server.
You can still  use paste feature to directly access to  the manga you want
