### ISSUE TITLE
[Site Request] MangaArabics

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#5477]
**Name of the website**
MangaArabics

**Website urls (examples below)**

- Site: https://mangaarabics.com
- Manga List: https://mangaarabics.com/manga/
- Manga example: https://mangaarabics.com/manga/the-book-eating-magician/
- Chapter online viewer example: https://mangaarabics.com/manga/the-book-eating-magician/77/
 
**Languages**
Arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
MAdara
