### ISSUE TITLE
[Swat Manga] Connector not working

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#5478]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
connect update not work and dont show any manga
![image](https://user-images.githubusercontent.com/65435897/218996900-b72f68f3-04b8-4e98-a733-23a9f82b9740.png)

my guess is the domain is changed from 
https://swatmanga.co || to || https://swatmanga.me

**To Reproduce**
1. Name of connector Swat Manga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment]
Url is already https://swatmanga.me/ in nightly version. Its working. Use nightly and if works please close this issue

**Comment by SatanHere** [comment]
its work ty
