### ISSUE TITLE
Removal Request for [akumanga.com]

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#5479]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Which website should be removed?
akumanga.com

Why should this website be removed from HakuNeko?
website is shut down for a long time 

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

**Comment by MikeZeDev** [comment]
Removal requests are for website owners who wants their website removed from hakuneko.

Many websites are dead, and its a hassle to check them all. We are rewriting Haku (Haruneko) and ofc we wont recode dead websites. Keeping them for now is not a problem .

**Comment by MikeZeDev** [comment]
If you want to report a dead website you may post in this issue i opened 
https://github.com/manga-download/hakuneko/issues/4972 :)
