### ISSUE TITLE
Request and problem

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#548]
https://epikmanga.com/  add...

and

MangaKakalot, > Solo Leveling > (Chapter List) > Blank....

Video; https://youtu.be/uVCFQiZE6uA

**Comment by 27136773** [comment]
EpikManga is already supported and currently available in latest nightly build...

**Comment by 27136773** [comment]
This issue is related to #547 and will automatically be solved by the proposed fix.

**Comment by areglos** [comment]
> EpikManga is already supported and currently available in latest nightly build...

hakuneko-desktop_6.0.12(nightly-20191014.1)  not working, Blank page comes out...

Video; https://youtu.be/KCYk0ZKsc7c

**Comment by 27136773** [comment]
What is the error output when you start `hakuneko.exe` from a terminal?

**Comment by areglos** [comment]
> What is the error output when you start `hakuneko.exe` from a terminal?

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://static.hakuneko.download/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default


--------------
Framework Info
--------------
Electron : 6.0.12
Chrome   : 76.0.3809.146
Node     : 12.4.0


-------------
Configuration
-------------
Update URL           : http://manga-download.github.io/hakuneko/6.0/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : C:\Users\EVA\Desktop\hakuneko-desktop_6.0.12_windows-portable_amd64\cache
UserData Directory   : C:\Users\EVA\Desktop\hakuneko-desktop_6.0.12_windows-portable_amd64\userdata

 2019-10-20T16:26:55.188Z <ERROR>    Update Failed! Error: Integrity check of update failed! The signature does not match the update package.
    at C:\Users\EVA\Desktop\hakuneko-desktop_6.0.12_windows-portable_amd64\resources\app.asar\UpdatePackageInfo.js:24:23    at new Promise (<anonymous>)
    at UpdatePackageInfo.validate (C:\Users\EVA\Desktop\hakuneko-desktop_6.0.12_windows-portable_amd64\resources\app.asar\UpdatePackageInfo.js:18:16)
    at Updater.updateCache (C:\Users\EVA\Desktop\hakuneko-desktop_6.0.12_windows-portable_amd64\resources\app.asar\Updater.js:30:34)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async App.run (C:\Users\EVA\Desktop\hakuneko-desktop_6.0.12_windows-portable_amd64\resources\app.asar\App.js:68:13)

**Comment by areglos** [comment]
![adwawdaw](https://user-images.githubusercontent.com/10929481/67162761-078bcd00-f370-11e9-948e-6c8b6cc5cd30.PNG)

**Comment by 27136773** [comment]
This looks not good and i have no idea why the update archive does not matches the signature on your system...

The only solution is to manually download and extract the update, but i'm pretty sure this will not solve the issue and you will be locked out from successive automatic updates

----

To perform a manual update download and extract the content of the [attached archive](https://github.com/manga-download/hakuneko/files/3748094/cache.zip) to HakuNeko's [Cache Directory](https://github.com/manga-download/hakuneko/wiki/User-Manual#24-cache).

[cache.zip](https://github.com/manga-download/hakuneko/files/3748094/cache.zip)

**Comment by areglos** [comment]
> This looks not good and i have no idea why the update archive does not matches the signature on your system...
> 
> The only solution is to manually download and extract the update, but i'm pretty sure this will not solve the issue and you will be locked out from successive automatic updates
> 
> To perform a manual update download and extract the content of the [attached archive](https://github.com/manga-download/hakuneko/files/3748094/cache.zip) to HakuNeko's [Cache Directory](https://github.com/manga-download/hakuneko/wiki/User-Manual#24-cache).
> 
> [cache.zip](https://github.com/manga-download/hakuneko/files/3748094/cache.zip)



Server problem? 

 2019-10-20T17:49:29.169Z <ERROR>    Update Failed! Error: connect ETIMEDOUT 185.199.111.153:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '185.199.111.153',
  port: 80
}

**Comment by areglos** [comment]
Mobile Data.  Logging In. There must be a server problem. Blocked.  
Another error started to emerge.  

^^Luck has left me.

![mobilveri](https://user-images.githubusercontent.com/10929481/67163864-e382b880-f37c-11e9-8517-e99c879b99de.PNG)
![mobilveri2](https://user-images.githubusercontent.com/10929481/67163865-e41b4f00-f37c-11e9-88f4-3002bcef23cc.PNG)

**Comment by 27136773** [comment]
This is just a warning meaning that a folder path is not correctly setup in the settings
