### ISSUE TITLE
[Ares Manga] Url change

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#5480]
**Name of the website**
Ares Manga

**Website urls (examples below)**
- Site: https://aresmanga.net/
- Manga List: https://aresmanga.net/series/
- Manga example: https://aresmanga.net/series/above-ten-thousand-people/
- Chapter online viewer example: https://aresmanga.net/above-ten-thousand-people-chapter-185/

**Languages**
Arabic

**Additional details**

![image](https://user-images.githubusercontent.com/65435897/219000381-7b0ca85c-4d2c-443f-ae32-13cf69f05596.png)

**OLD Domain is not working anymore** they are moving to a new domain that i mentioned above

**Comment by MikeZeDev** [comment]
Then its not a site request, its a Website change.
