### ISSUE TITLE
[Site Request] Shinigami.id

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5481]
**Name of the website**
Shinigami.id

**Website urls (examples below)**
- Site: https://shinigami.id/
- Manga https://shinigami.id/semua-series/
- Manga example: https://shinigami.id/series/the-dark-magician-transmigrates-after-66666-years/
- Chapter online viewer example: https://shinigami.id/series/the-dark-magician-transmigrates-after-66666-years/chapter-76/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Its reaperscansID , PR already ready

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/hakuneko/blob/1cc7c83f40f4ecc3efb19b6e950e0f146b6d2c2a/src/web/mjs/connectors/ReaperScansID.mjs
