### ISSUE TITLE
https://www1.gogoanime.bid/

### ISSUE THREAD

**Issue by michaelsiame** [manga-download/hakuneko#5487]
gogoanime
thewebsitename

**Website urls (examples below)**
- Site: https://www1.gogoanime.bid/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3677
