### ISSUE TITLE
[Reaper Scans] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#5488]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No chapters will load.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cloudflare, cant fix
