### ISSUE TITLE
[Site Request] AZORA MANGA

### ISSUE THREAD

**Issue by NaifES** [manga-download/hakuneko#5489]
**Name of the website**
AZORA MANGA

**Website urls (examples below)**
- Site: https://azoranov.com/
- Manga List: https://azoranov.com/series/
- Manga example: https://azoranov.com/series/the-tutorial-tower-of-the-advanced-player-22/
- Chapter online viewer example: https://azoranov.com/series/the-tutorial-tower-of-the-advanced-player-22/141/

**Languages**
List of languages supported by the website
arabic
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
the website address has been changed form "https://azoraworlds.net/" to "https://azoranov.com/"
**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by SatanHere** [comment]
@NaifES  if you can add me on discord 

Mh-Al3tebi#6355

**Comment by SatanHere** [comment]
Its already changed on the nightly version

![image](https://user-images.githubusercontent.com/65435897/219985326-c82ba63e-e157-42b6-a2fc-eac89c09a016.png)

![image](https://user-images.githubusercontent.com/65435897/219985357-8d60722f-83ec-4d5f-b696-23ef9bff1d32.png)

**Comment by MikeZeDev** [comment]
Yeah, not only its already done, but you should have made a website change resquest and not a Website suggestion request.
Closed as already done
