### ISSUE TITLE
[ManhuaScan] Connector not working

### ISSUE THREAD

**Issue by PeachNyaa** [manga-download/hakuneko#5490]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
**Yes**/No

**Describe the bug**
Cannot connect to ManhuaScan - error shows "Failed to update manga list for ManhuaScan. Cannot read property 'text' of undefined"

**To Reproduce**
1. ManhuaScan
2. Unable to connect
3. Unable to connect
4. "Failed to update manga list for ManhuaScan. Cannot read property 'text' of undefined"

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="253" alt="Screen Shot 2023-02-20 at 10 15 09 am" src="https://user-images.githubusercontent.com/125836546/219981594-21b05150-9c01-42d7-940b-d53c3c358de9.png">

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
[Fixed since december](https://github.com/manga-download/hakuneko/pull/5267). Use nightly version
