### ISSUE TITLE
[Hiperdex] Connector not working

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#5495]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
![haku](https://user-images.githubusercontent.com/81703465/220108281-4cda2bc6-ab9f-41eb-bd2e-c8277a5976e8.png)

**Describe the bug**
Can't load the list website but the url open is ok and work properly

**To Reproduce**
1. Hiperdex

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [8.3.4]

**Comment by MikeZeDev** [comment]
1 ) Use nightly version
2) Make sure url is set to 1sthiperdex
![image](https://user-images.githubusercontent.com/10671518/220116765-28e487ec-db37-42e4-a83b-0e307dd927a4.png)

Please close this issue if it works

**Comment by andillk** [comment]
done
