### ISSUE TITLE
[Bilibili Manhua] Connector not working for one particular manga

### ISSUE THREAD

**Issue by nube22** [manga-download/hakuneko#5497]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error when downloading any chapter from Full Metal Alchemist, both the free ones and paid ones (via login). No problem reading them in the browser. I have only been able to reproduce the error with this particular manga, the others I tried work fine. The "Show preview of chapter's pages" in the "Chapter List" doesn't work either.

**To Reproduce**
1. Name of connector: Bilibili Manhua (Chinese)
2. Name of manga: 钢之炼金术师 (https://manga.bilibili.com/detail/mc27362?)
3. Name of chapter: Any chapter (first 4 are free)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 400 ()

**HakuNeko (please complete the following information):**
 - Both in Version 6.17 and Nightly Version v8.3.4

**Comment by MikeZeDev** [comment]
For this manga, server doesnt send us correct image dimension (0 and 0). So we request invalid dimension. And it fails. Website use a workaround for that, Gotta implement getImageSizeByQuality to get a size that will be accepted .

It will be the first step to code quality selection, gotta code it whil we are at it.
