### ISSUE TITLE
[Scan-FR] Change URL

### ISSUE THREAD

**Issue by webrootpro** [manga-download/hakuneko#5499]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
website  👍 https://www.scan-fr.org/

description ;not able to load chapitres
![Uploading Capture.PNG…]()

**Comment by MikeZeDev** [comment]
Next time, take the time to put website name in title please.
Moreover, a simple url change is worth mentioning in title too as its easy fix. Developers loves easy fixes

**Comment by MikeZeDev** [comment]
Website doesnt load at all in haku, what is going on.
Edit : its working again. Well, it still need an url change
