### ISSUE TITLE
[COMIC FUZ] Connector not working

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#5502]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't download manga on this site even episode 1 is free.

**To Reproduce**
1. Select COMIC FUZ
2. Select some manga (ex. 魔女は満月に咲く https://comic-fuz.com/manga/3226)
3. Select some free episode
4. Download failed and appear (failed) net::ERR_NOT_IMPLEMENTED at dev tool

**Screenshots**
![2023-02-26_10-40-30](https://user-images.githubusercontent.com/2475440/221387942-faa05b1d-49c9-466c-90ed-d4eaa610c138.png)

![2023-02-26_10-51-19](https://user-images.githubusercontent.com/2475440/221388024-b503fa3e-dc41-4736-9001-2cdff6787464.png)

**HakuNeko (please complete the following information):**
 - Version master@23fcb9

**Comment by MikeZeDev** [comment]
Hum, for some reason, "crypto.subtle" is undefined

Was it working before? Because "crypto.subtle" is not supposed to be supported in our NodeJs version.

**Comment by sakuhanachan** [comment]
I not sure since this is first time for try to download from this site.

**Comment by MikeZeDev** [comment]
Gotta be technical sorry : it certainly can be fixed if someone is able to replace the use of "crypto.subtle" with Crypto.js that is included in Hakuneko. Tried a bit, went confused with input parameters encoding format (hex, utf8, arraybuffer, wordarray, UintArray8....) since both systems use different ones. 🤷‍♂️

**Comment by MikeZeDev** [comment]
Note for myself : CryptoJS needs Wordarray for input and has convenient methods to create them.
