### ISSUE TITLE
[Site Request] INKR

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5503]
**Name of the website**
INKR

**Website urls (examples below)**
- Site: https://comics.inkr.com/
- Manga List: None
- Manga example: https://comics.inkr.com/title/480-tales-of-demons-and-gods
- Chapter online viewer example: https://comics.inkr.com/title/480-tales-of-demons-and-gods/chapter/18143-chapter-1-rebirth

**Languages**
English

**Website relationship*
None

**Additional details**
None

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3782
