### ISSUE TITLE
[hiperdex.com Connector not working

### ISSUE THREAD

**Issue by codexhouse** [manga-download/hakuneko#5505]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
hiperdex.com
Warning iconYour browser is out of date!
Update your browser to view this website correctly. [More Information.](https://developers.cloudflare.com/fundamentals/get-started/concepts/cloudflare-challenges/#browser-support)

**To Reproduce**
1. hiperdex
2. the whole list/website cant be accessed through hakuneko

![image](https://user-images.githubusercontent.com/71021362/221444890-4bb6e205-a0d3-44ce-a9be-875d28c1600e.png)

Failed to load resource: the server responded with a status of 404 () this is the errror 
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cloudflare strikes again. Wait so they remove it.

**Comment by jeremieLyvoc** [comment]
Also happening for sushiscan.net

**Comment by MikeZeDev** [comment]
we know already . People keep complaining about it :D

**Comment by MikeZeDev** [comment]
Fixed itself
