### ISSUE TITLE
[Site Request] AlceaScan

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5506]
**Name of the website**
Alceascan

**Website urls (examples below)**
- Site: https://alceascan.my.id/
- Manga List: https://alceascan.my.id/manga/
- Manga example: https://alceascan.my.id/manga/18-year-old-spy/
- Chapter online viewer example:https://alceascan.my.id/18-year-old-spy-chapter-30/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangareader/stream
