### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by longIT0708** [manga-download/hakuneko#5510]
**Name of the website**
m.happymh

**Website urls (examples below)**
  https://m.happymh.com/
- Site: https://m.happymh.com/
- Manga List:  https://m.happymh.com/manga/zhanshennaiba
- Manga example:  https://m.happymh.com/manga/zhanshennaiba
- Chapter online viewer example: https://m.happymh.com/reads/zhanshennaiba/3255348

**Languages**
Chinese
List of languages supported by the website
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Sheepux** [comment]
duplicate #3390
