### ISSUE TITLE
[Site Request] miauscan

### ISSUE THREAD

**Issue by ErickShadow12** [manga-download/hakuneko#5512]
**Name of the website**
[thewebsitename]miauscan

**Website urls (examples below)**
- Site: https://miauscan.com/
- Manga List: https://miauscan.com/manga/
- Manga example: https://miauscan.com/manga/mi-patron-solo-tiene-cinco-anos/
- Chapter online viewer example: https://miauscan.com/mi-patron-solo-tiene-cinco-anos-capitulo-16/

**Languages**
-Español
-Portigues

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangareader/stream
