### ISSUE TITLE
[Comick] Change in Comick API

### ISSUE THREAD

**Issue by PhilippKammann** [manga-download/hakuneko#5514]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Hakuneko can't load the chapter list, beacuse it calls `https://api.comick.fun/comic/{id}/chapter` (deprecated) instead of the new API path `https://api.comick.fun/comic/{hid}/chapters`

**HakuNeko:**
 - Version 6.1.7@554b0c

**Comment by MikeZeDev** [comment]
Your url still got the .fun tld, when its .app in last commit.

https://github.com/manga-download/hakuneko/commit/5c35da7b25648b34cfca0228c42ba6ff56f61b95

"Comick.fun" tells me you dont have the updated version (nightly)

And loading chapters works fine at least in nightly.

**Comment by PhilippKammann** [comment]
It works again (still with 554b0c) so who knows.

Just found this issue https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14788 by one of the Comick people, which seemed connected
