### ISSUE TITLE
[Olympusscanlation] Connector not working

### ISSUE THREAD

**Issue by rausina** [manga-download/hakuneko#5517]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site has change his URL to https://olympusscans.com/

**To Reproduce**
1. Olympusscanlation
2. Any
3. Any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
They didnt only change url. This is not using Madara anymore. Gotta use their api
