### ISSUE TITLE
[Site Request] m.happmh

### ISSUE THREAD

**Issue by longIT0708** [manga-download/hakuneko#5518]
**Name of the website**
m.happmh

**Website urls (examples below)**
- Site: https://m.happymh.com/
- Manga List: https://m.happymh.com/manga/yirenzhixia
- Manga example: https://m.happymh.com/reads/yirenzhixia/3273014
- Chapter online viewer example: https://m.happymh.com/reads/yirenzhixia/3273014
**Languages**
Chiness

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
* Duplicate issue : https://github.com/manga-download/hakuneko/issues/3390
* Cant access website because its geoblocked 🤷
