### ISSUE TITLE
[Animepahe] Connector not working

### ISSUE THREAD

**Issue by Jman024** [manga-download/hakuneko#5519]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**
Whenever attempting to download anime from animepahe, the download fails and the reason for failing is 'Syntax Error: Unexpected token o in Position 1'

**To Reproduce**
1. animepahe
2. Any video
3. Any episode
4. Syntax Error: Unexpected token o in Position 1

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
[Fixed ](https://github.com/manga-download/hakuneko/pull/5507), use nightly
