### ISSUE TITLE
[Site Request] 123anime

### ISSUE THREAD

**Issue by Jman024** [manga-download/hakuneko#5520]
**Name of the website**
123anime

**Website urls (examples below)**
- Site: https://123anime.to/
- Manga List: https://123anime.to/anime
- Manga example: https://123anime.to/anime/sora-yori-mo-tooi-basho
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
English
Japanese

**Additional details**
Also carries a wide collection of cartoons as well as anime not found on more popular sites like watchcartoonsonline and animepahe

**Comment by MikeZeDev** [comment]
dead
