### ISSUE TITLE
Add 9anime.skin as a Connector

### ISSUE THREAD

**Issue by tonyevans75** [manga-download/hakuneko#5524]
Could you please add this as a Connector?:
https://9anime.skin/ 
and/or
https://9anime.skin/home

**Comment by MikeZeDev** [comment]
No need for 9anime clone when we already have 9 anime

**Comment by tonyevans75** [comment]
The current 9anime connector is broken because it's set to 9anime.to, which is dead.
Please update it to 9anime.skin

**Comment by MikeZeDev** [comment]
Nope.

![image](https://user-images.githubusercontent.com/10671518/224418599-e5e7dfdd-c311-4005-8638-8f12db3dc9ba.png)

Its not dead. Change your DNS maybe.

**Comment by tonyevans75** [comment]
This is what I get for 9anime.to. These even happens in a VM where almost the entire environment is different than on my main PC:
![Capture - Copy](https://user-images.githubusercontent.com/118947673/224503802-d9b9b3d1-f787-47ac-93d2-f75c3ff727fb.PNG)

This doesn't happen at all with other versions of 9anime, like .gs and .skin

**Comment by MikeZeDev** [comment]
* Developing a connector takes times
* Devs have limited time
* Therefore we have a policy where we avoid adding clones. 
* ...especially when they are a pain the a* like 9Anime (they hate scrapers like haku :)
* And anyway, 9anime is already only partially working as they use some video hosters we support and some we dont. No point in spending more time in something that already could be perfected on the original. 
 
Anime websites support is not hard to code by itself but they often use crapload of video hosters and THAT is painful.

If you have problem in real browser there is nothing we can do. Its your system problem, maybe your country is blocking the website idk in that case change your dns or use a VPN. I would have said SSL problems is antivirus meddling with SSL , disable SSL / TLS scanning maybe? 

Here, Issues or discord are technical support for Hakuneko, not computer support. I still gave you some advice on how to fix your problem but thats all i can and will do, i hope you understand :)
