### ISSUE TITLE
[Ichijin-plus] Connector not working

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#5526]
**Name of the website**
Ichijin-plus

**Website urls (examples below)**
- Site: https://ichijin-plus.com
- Manga example: https://ichijin-plus.com/comics/89324057887009
- Chapter online viewer example: https://ichijin-plus.com/episodes/89686464169323

**Languages**
Japanese

**Comment by Elastic1** [comment]
duplicate #4721

**Comment by Ever4engel** [comment]
in this case it's broken.

**Comment by MikeZeDev** [comment]
I changed title. Now you have to describe the issue ofc.

**Comment by MikeZeDev** [comment]
Apparently only clipboard pasting is broken
