### ISSUE TITLE
[Newtoki] Connector not working

### ISSUE THREAD

**Issue by libreidy** [manga-download/hakuneko#5529]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/
**Describe the bug**

Failed to update manga list for NewToki

Cannot read property 'href' of undefined

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [6.1.7@554b0c]

**Comment by MikeZeDev** [comment]
This website is changing its url way too often. No need to open an issue each time
 Change url in settings and close this issue if it works. 
![image](https://user-images.githubusercontent.com/10671518/222895670-ab2c1684-f1ee-47ab-801b-767354747d4c.png)

**Comment by libreidy** [comment]
Thank you.
