### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by BaNyarKyawKyaw** [manga-download/hakuneko#5532]
**Name of the website**
Manhwa18

**Website urls**
- Site: https://manhwa18.net/
- Manga List: https://manhwa18.net/genre/manhwa?sort=az
- Manga example: https://manhwa18.net/manga/100-perfect-girl
- Chapter online viewer example: https://manhwa18.net/manga/100-perfect-girl/chapter-1-138

**Languages**
English

**Website relationship*
-None

**Additional details**
-None

**Comment by MikeZeDev** [comment]
It is supported since june 2022 🤦 https://github.com/manga-download/hakuneko/blob/95e35adf9fd9bcde40ebf25fab45119b14b2a7ae/src/web/mjs/connectors/ManhwaEighteen.mjs
