### ISSUE TITLE
[Manhwa 18 (.net)] Connector not working

### ISSUE THREAD

**Issue by BaNyarKyawKyaw** [manga-download/hakuneko#5533]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I try to connect the connector, it starts loading normally but after sometimes, it stopped and show the error message as shown in the attached picture.

**To Reproduce**
1. Manhwa 18 (.net)
4. Error Message - Cannot read property 'text' of undefined

**Screenshots**
If complex to describe, add 
screenshots to help explain your problem.
![Hakuneko](https://user-images.githubusercontent.com/29281714/222977829-fefa1b8d-ff42-4c01-9042-8d0f372cd84e.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Website changed.
