### ISSUE TITLE
[Tritinia] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#5535]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I press the refresh button, this message comes up "Failed to update manga list for Tritinia Scans
Cannot read property 'includes' of null"

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Its not your first issue right? Did you try nightly? because there has been a fix the 8th of january.

Always try nightly before opening issues that may already been fixed pls.

Feel free to reopen if the problem persist.
