### ISSUE TITLE
[Reaper Scans] Connector not working

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#5536]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No titles of chapters will load.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
You already opened an issue 2 weeks ago, the problem is unfixable, you may open 50 more it wont change anything.

**Comment by MikeZeDev** [comment]
Its not your first issue right? Did you try nightly? because there has been a fix the 8th of january.

Always try nightly before opening issues that may already been fixed pls
