### ISSUE TITLE
[Naver Webtoon] Connector not working 

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5538]
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
I'm trying to download a chapter from the website, but when I paste the URL for the series into Hakuneko doesn't load the series (on the left box). I saw that someone else had the same issues and it was solved, but it doesn't seem to be working on my end.

To Reproduce

    Name of connector Naver Webtoon
    Name of manga (if connector update is working)
    Name of chapter (if manga update is working)
    Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
(anonymous) @ BookmarkManager.mjs:137
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-solid-900.woff2?v=5.8.2
ClipboardConnector.mjs:66 CLIPBOARD: https://comic.naver.com/webtoon/list?titleId=807170 TypeError: Cannot read property 'childNodes' of undefined
    at Naver._getMangaFromURI (Naver.mjs:22)
    at async hakuneko:/cache/mjs/connectors/system/ClipboardConnector.mjs:64
    at async Promise.all (index 0)
(anonymous) @ ClipboardConnector.mjs:66
ClipboardConnector.mjs:66 CLIPBOARD: https://comic.naver.com/webtoon/list?titleId=796062 TypeError: Cannot read property 'childNodes' of undefined
    at Naver._getMangaFromURI (Naver.mjs:22)
    at async hakuneko:/cache/mjs/connectors/system/ClipboardConnector.mjs:64
    at async Promise.all (index 0)
(anonymous) @ ClipboardConnector.mjs:66
3ClipboardConnector.mjs:66 CLIPBOARD: https://comic.naver.com/webtoon/list?titleId=796062 TypeError: Cannot read property 'childNodes' of undefined
    at Naver._getMangaFromURI (Naver.mjs:22)
(anonymous) @ ClipboardConnector.mjs:66
async function (async)
(anonymous) @ ClipboardConnector.mjs:64
_getMangaList @ ClipboardConnector.mjs:48
updateMangas @ ClipboardConnector.mjs:28
onUpdateMangaListClick @ mangas.html:233
onPasteClick @ mangas.html:339
handler @ template-stamp.html:96
ClipboardConnector.mjs:66 CLIPBOARD: https://comic.naver.com/webtoon/list?titleId=807170 TypeError: Cannot read property 'childNodes' of undefined
    at Naver._getMangaFromURI (Naver.mjs:22)

Manga.mjs:153 _getUpdatedChaptersFromWebsite TypeError: Cannot read property 'innerText' of undefined
at Naver.mjs:67
Screenshots
If complex to describe, add screenshots to help explain your problem.
[](https://files.catbox.moe/0caito.PNG)

HakuNeko (please complete the following information):

    Version 6.1.7

**Comment by MikeZeDev** [comment]
The guy on the other issue didnt wait for the fix to come in Hakuneko, he copied the code/file which is fine too

Download nightly version and wait because its not officially available. No need to open another issue.
