### ISSUE TITLE
[Site Request] Piscans

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5540]
**Name of the website**
Piscans

**Website urls (examples below)**
- Site: https://piscans.in/
- Manga List: https://piscans.in/manga/
- Manga example: https://piscans.in/manga/reincarnation-of-the-suicidal-battle-god/
- Chapter online viewer example: https://piscans.in/doom-breaker-reincarnation-of-the-suicidal-battle-god-chapter-66/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Wordpress: Mangareader (mangastream)

**Comment by Frezian** [comment]
What does it mean?

**Comment by MikeZeDev** [comment]
> What does it mean?

Developer comment to help issues triage. Don't mind it. It mean the website use a template we know well.  Coding should then be easy (there are TONS of mangastream like websites)
