### ISSUE TITLE
[Newtoki] Fake Images

### ISSUE THREAD

**Issue by watatomo** [manga-download/hakuneko#5543]
**Describe the bug**
"Fake" images are shown among the actual images of the manhwa. Not a huge deal, but it's rather annoying. It would be great if the URL could be blacklisted: `/^https:\/\/newtoki[0-9]+\.com\/tokinbtoki\/[0-9]+/`

**HakuNeko (please complete the following information):**
 - I'm running it from the master branch.

**Comment by MikeZeDev** [comment]
Not sure what you mean with this regex. Anyway, the fix works by whitelisting so it should be more efficient.
