### ISSUE TITLE
[Mangafox] Connector not working mangalist doesnt add some titles or outdated

### ISSUE THREAD

**Issue by kevin01523** [manga-download/hakuneko#5547]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
magalist seems to be stuck at 10008 and doesnt add anymore
**To Reproduce**
1. mangafox
2. [Name of manga](http://fanfox.net/manga/ooyukiumi_no_kaina/) (if connector update is working) cannot search for it as it isnt added

afterchecking  how the connector gets the mangalist 
i think part of the problem is some manga are not on the mangakist on mangafox website but can be searched

is there anyway to add missng manga into the list?

** Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 834]

**Comment by MikeZeDev** [comment]
If mangalist is missing manga, use clipboard feature. 

Close issue if this solution works

**Comment by kevin01523** [comment]
> If mangalist is missing manga, use clipboard feature.
> 
> Close issue if this solution works

oh thaks had to find how that feaure wotks but still thanks
