### ISSUE TITLE
[Site Request] summanga

### ISSUE THREAD

**Issue by Mammad211** [manga-download/hakuneko#5549]
**Name of the website**
summanga 

**Website urls (examples below)**
- Site: https://summanga.com
- Manga List: https://summanga.com/manga
- Manga example: https://summanga.com/manga/all-starts-with-ubume
- Chapter online viewer example: https://summanga.com/manga/all-starts-with-ubume/chapter-169/
- 
**Languages**
English

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5454
