### ISSUE TITLE
[YaoiIsLife] Connector not working, domain up for sale.

### ISSUE THREAD

**Issue by billsargent** [manga-download/hakuneko#5555]
You can remove this connector as the domain is up for sale and the site is completely gone. 
![image](https://user-images.githubusercontent.com/32219940/224322915-fe7267e1-7f76-4b7d-af7c-feb1e43c57f0.png)

**Comment by MikeZeDev** [comment]
OK. Modified https://github.com/manga-download/hakuneko/issues/4972. Thanks.
