### ISSUE TITLE
zoro.to

### ISSUE THREAD

**Issue by githubdebosmit** [manga-download/hakuneko#5560]
**Name of the website**
zoro.to

**Website urls (examples below)**
- Site: https://zoro.to/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4625 , and template not even filled properly
