### ISSUE TITLE
[Manga Gecesi] Connector not working

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#5561]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site is not opening on the HakuNeko but The site is working on the internet
**To Reproduce**
1. Name of connector https://mangagecesi.com/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7

**Comment by MikeZeDev** [comment]
Cloudflare, cant fix

**Comment by MikeZeDev** [comment]
Website is dead
