### ISSUE TITLE
[Site Request] Spartan Manga

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#5563]
**Name of the website**
thewebsitename Spartan Manga

**Website urls (examples below)**
- Site: https://spartanmanga.com.tr/
- Manga List: https://spartanmanga.com.tr/manga/
- Manga example: https://spartanmanga.com.tr/manga/the-worlds-best-engineer/
- Chapter online viewer example: https://spartanmanga.com.tr/the-worlds-best-engineer-bolum-76/

**Languages**
List of languages supported by the website
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dev notes : Mangastream template.
