### ISSUE TITLE
[Site Request] Titan Manga

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#5564]
**Name of the website**
thewebsitename Titan Manga

**Website urls (examples below)**
- Site: https://titanmanga.com/
- Manga List: https://titanmanga.com/manga/?m_orderby=alphabet
- Manga example: https://titanmanga.com/manga/ben-gercekten-seytanin-usagi-degilim/
- Chapter online viewer example: https://titanmanga.com/manga/ben-gercekten-seytanin-usagi-degilim/bolum-1/

**Languages**
List of languages supported by the website
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream template
