### ISSUE TITLE
[Rüya Manga] Connector not working

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#5565]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site is not opening on the HakuNeko but the site is working on the internet

**To Reproduce**
1. Name of connector Rüya Manga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7

**Comment by MikeZeDev** [comment]
Cloudflare cant fix 
![image](https://user-images.githubusercontent.com/10671518/224541916-2975efad-9234-406b-845a-d5290ebcbae8.png)

**Comment by Mehmet20032003** [comment]
A week ago this website was working in HakuNeko, but now it is not working. And I am not an expert but when I open the website in a normal browser, there is no cloudflare screen.
![Adsız2](https://github.com/manga-download/hakuneko/assets/127633031/c65ca477-b760-4b26-bd90-114f5f2c0a74)
