### ISSUE TITLE
[Site Request] Nirvana Manga

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#5566]
**Name of the website**
thewebsitename Nirvana Manga

**Website urls (examples below)**
- Site: https://nirvanamanga.com/
- Manga List: https://nirvanamanga.com/manga/
- Manga example: https://nirvanamanga.com/manga/akil-hastanesindeki-guclu-adam/
- Chapter online viewer example: https://nirvanamanga.com/the-strong-man-from-the-mental-hospital-bolum-1/

**Languages**
List of languages supported by the website
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream template
