### ISSUE TITLE
[Ayatoon] Connector not working

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#5567]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site is not opening on the HakuNeko but the site is working on the internet

**To Reproduce**
1. Name of connector Ayatoon
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7

**Comment by MikeZeDev** [comment]
They changed their website template, and i made a fix in January. Use Nightly version of Hakuneko.

Relevant commit : https://github.com/manga-download/hakuneko/commit/240d069f66d59e947e4630a5b49a71b2e7c75d56
