### ISSUE TITLE
Manganelo shows titles but not chapters and timesout when trying to update list

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#557]
> **From:** HakuNeko User

Site itself working properly

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
See #547
