### ISSUE TITLE
[Feature] Change downloaded chapter filename within the chapter list view

### ISSUE THREAD

**Issue by j-o-e-s** [manga-download/hakuneko#5570]
Is it possible to add a feature to change the downloaded chapter filename without breaking the link to the chapter from the parent website?

Sometimes the chapter naming pattern changes from Ch.000 to Vol.00 Ch.000 midway through the manga. It messes with the chapter list sort and when reading the chapters in the app. I have to back out and select the correct next chapter.

If the downloaded chapter filename is changed outside the app, the next time that manga is loaded in the app, the link is broken and the app says the chapter hasn't been downloaded.

If I can change the chapter title from within the app, then it could be coded so the link isn't broken.

**Comment by Sheepux** [comment]
did you try the "chapter title format" in the settings ?

**Comment by j-o-e-s** [comment]
I didn't realize it also affected the chapter list.  I see it adds an extra 0 in front of the VOL & CH numbers but it works.
I'll have to redownload the chapters, but thanks for the tip!
