### ISSUE TITLE
Isekaiscan moved?!?

### ISSUE THREAD

**Issue by Lord-Death** [manga-download/hakuneko#5574]
Isekaiscan.com no longer opens the website it appears to have changed to isekaiscan.to. 

Please verify and update.

Thank you.

**Comment by MikeZeDev** [comment]
I see but are we sure thats the same?  Apparently is gone for a few months. Hum, should we replace this or create another? 
See there is also http://isekaiscan.top :shrug:

**Comment by Lord-Death** [comment]
That's the question... If only there was a test that could verify if one of the sites is the same as the original one thus the bookmarks would remain and already downloaded files would not have to be downloaded again otherwise it is a process of "restarting" the favorites on another website.

**Comment by Lord-Death** [comment]
After spending time on both sites I believe that neither isekaiscan.to or isekaisan.top are the same group of people therefore they should be added as new sites...I wish we could find out what happened with the original group.

**Comment by MikeZeDev** [comment]
I'll refrain from adding an http website, its 2023 after all :D
