### ISSUE TITLE
[Mangahub.io] Connector not working

### ISSUE THREAD

**Issue by flysk1** [manga-download/hakuneko#5578]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't download, it saved .bin files

**To Reproduce**
1. Name of connector: Mangahub.io
2. Name of manga (if connector update is working): All
3. Name of chapter (if manga update is working): All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
It was fixed last month use nightly
