### ISSUE TITLE
New chapters not available to Hakuneko

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#558]
> **From:** HakuNeko User

Recently, I noticed that Hakuneko stopped listing the newest chapters to some of the mangas I was following.  In my browser, the manga has already reached chapter 34, but the Hakuneko chapter list stops at chaper 31.  (1st kissmanga.com-"My Apprentice: Game over Again!" (https://1stkissmanga.com/manga/my-apprentice-game-over-again/)  
I opened the site through Hakuneko and there, it also stopped listing the chapter at 31.  

This is also the case with 1stkiss.com's "A Star Reborn: The Queen’s Return"  (https://1stkissmanga.com/manga/a-star-reborn-the-queens-return/)

Why is this happening?

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by hypoflex** [comment]
Both manga's you listed and linked are up to date with the connector/source.
issue cant be reproduced.

please provide steps to reproduce issue

**Comment by 27136773** [comment]
Same for me

----

![image](https://user-images.githubusercontent.com/27136773/67244605-5d3ca400-f45a-11e9-812f-df546ee7cf7c.png)

**Comment by 27136773** [comment]
Are you using 5.0.8?
1st Kiss Manga is broken in 5.0.8, so you may only see the chapters you already downloaded.

**Comment by 27136773** [comment]
No further response => closed
