### ISSUE TITLE
[MangaBuddy] Can't Read or Download Chapter.

### ISSUE THREAD

**Issue by Lordsneak** [manga-download/hakuneko#5580]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I cant Download or Read Chapter in Mangabuddy

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
https://imgur.com/kZAbfIG

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
I see. easy fix.

**Comment by Lordsneak** [comment]
Thanks, it works.

**Comment by MikeZeDev** [comment]
Dont close the issue until changes are merged pls :)

**Comment by flysk1** [comment]
It's not working again @MikeZeDev

**Comment by Lordsneak** [comment]
> It's not working again @MikeZeDev

It's work for me!

**Comment by MikeZeDev** [comment]
Parrot dev said : use nightly it wont work otherwise
