### ISSUE TITLE
Yaoiscan[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by Jinyaaaa** [manga-download/hakuneko#5582]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
When you read a chapter It says timeout or http error

**To Reproduce**
1. Yaoiscan 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Timeout and Http error appears to every chapter 

**Screenshots**
![Screenshot_20230319_034754](https://user-images.githubusercontent.com/128232616/226134202-34fa0497-cda4-4a3b-9acd-68934f891bf5.jpg)

**HakuNeko (please complete the following information):**
 - Version [0.14.5]

**Comment by MikeZeDev** [comment]
Its a Tachiyomi screen, and you open an issue on Hakuneko github :D

I can confirm website works in Hakuneko. Closed as invalid request.
