### ISSUE TITLE
[ComicK] Connector not working

### ISSUE THREAD

**Issue by PhilippKammann** [manga-download/hakuneko#5587]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapter list doesn't load when selecting a series trough a bookmark or trough the Comick manga list.
Console shows 404 error on an api call (e.g. 'https://api.comick.app/comic/9873/chapter?page=1')

**To Reproduce**
1. ComicK
2. Any (example: "One Piece) 
3. ---
4. "Connector.mjs:460 GET https://api.comick.app/comic/30181/chapter?page=1 404"

**HakuNeko (please complete the following information):**
 - Version master@375d51

**Comment by MikeZeDev** [comment]
Api change i guess

**Comment by PhilippKammann** [comment]
Seems like it.
'https://api.comick.app/comic/CzcseUMi/chapters?page=1' works for One Piece with "CzcseUMi" being the `hid` while HakuNeko uses the `id` "112"

There is also a Tachiyomi issue about the api change
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14788

**Comment by MikeZeDev** [comment]
> 'https://api.comick.app/comic/CzcseUMi/chapters?page=1' works for One Piece with "CzcseUMi" being the `hid` while HakuNeko uses the `id` "112"

Figured it out before you posted ^^ thanks anyway.
