### ISSUE TITLE
[ReadManga] Connector not working 

### ISSUE THREAD

**Issue by IsakGairatov** [manga-download/hakuneko#5588]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I cannot download manga from https://readmanga.live .  It starts downloading chapter, but after filling dowloand  progress line, it stops. No errors, just downloading of chapter do not finish no matter how long I wait. 

**To Reproduce**
1. Readmanga.live
2. https://readmanga.live/atele_koldovskih_kolpakov__A5238
3. Any
4. No errors

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
[Probably Fixed 3 month ago. ](https://github.com/manga-download/hakuneko/blob/accce9d702c4d00e22c119c37c19278a91a8d9cd/src/web/mjs/connectors/ReadManga.mjs)

Use nightly version, if that works, close this issue as completed.
