### ISSUE TITLE
[Site Request] mangasee123

### ISSUE THREAD

**Issue by anodcire** [manga-download/hakuneko#5592]
**Name of the website**
[mangasee123](https://mangasee123.com/)

**Website urls (examples below)**
- Site: https://mangasee123.com/
- Manga List: https://mangasee123.com/directory/
- Manga example: https://mangasee123.com/manga/Darling-In-The-Franxx
- Chapter online viewer example: https://mangasee123.com/read-online/Darling-In-The-Franxx-chapter-1-page-1.html

**Languages**
English only (as far as I know)

**Website relationship*
Not sure

**Additional details**
N/A

**Comment by MikeZeDev** [comment]
Already supported. Please check before asking. 

https://github.com/manga-download/hakuneko/blob/ca077809b4870ee0dac552443fb251f098a019ae/src/web/mjs/connectors/MangaSee.mjs

If it doesnt works open a "Connector non working" ticket instead.

**Comment by anodcire** [comment]
Sorry - must have spelled incorrectly when checking.
