### ISSUE TITLE
[Mangachan] Connector not working

### ISSUE THREAD

**Issue by IsakGairatov** [manga-download/hakuneko#5593]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Starting today, some chapters of manga cannot be downloaded. I try to download it multiple times, but it gets red in seconds after start.

**To Reproduce**
1. Mangachan
2. https://manga-chan.me/manga/56835-karakuri-circus.html
3. Chapters 167, 157, 147, 137, 127, 117, 97, 87,  77, 67, 57, 27, 9, 8, 1
4. Error "Page "link of page png"  returned"

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] // I used both stable and nightly last versions

**Comment by MikeZeDev** [comment]
Preview got a missing picture in chapter 167. Error 404 not found. Url is correct and we dont get a 404 error in browser.
wtf

Then it works after some tries. It seems the server got hiccups. Not sure something can be done. Calm down on downloads maybe?
