### ISSUE TITLE
[Site Request] agit185

### ISSUE THREAD

**Issue by longIT0708** [manga-download/hakuneko#5596]
**Name of the website**
agit185

**Website urls (examples below)**
- Site: https://agit185.com/
- Manga List: https://agit185.com/azi_toon/11005.html
- Manga example: https://agit185.com/azi_toons/11005/1167925.html
- Chapter online viewer example: https://agit185.com/azi_toons/11005/1167925.html

**Languages**
List of languages supported by the website
Korea
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Is that one of those website whose address change constantly?
