### ISSUE TITLE
[Clipboard] Connector not working for Naver Comic

### ISSUE THREAD

**Issue by bndki** [manga-download/hakuneko#5602]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Everything worked okay until the recent update to Naver's site.
I believe they changed something that it breaks the script.
If I load the link into the clipboard (eg. https://comic.naver.com/webtoon/list?titleId=757904),
it does not populate any title/chapter, which used to work fine.

**To Reproduce**
First of all, clipboard connector worked great for Naver comic.
But now, using any link in the clipboard will throw the following error in the console:
```
ClipboardConnector.mjs:66 CLIPBOARD: https://comic.naver.com/webtoon/list?titleId=757904 TypeError: Cannot read property 'childNodes' of undefined at Naver._getMangaFromURI (Naver.mjs:22)
(anonymous)	@	ClipboardConnector.mjs:66
async function (async)		
(anonymous)	@	ClipboardConnector.mjs:64
_getMangaList	@	ClipboardConnector.mjs:48
updateMangas	@	ClipboardConnector.mjs:28
onUpdateMangaListClick	@	mangas.html:233
handler	@	template-stamp.html:96
```

**HakuNeko (please complete the following information):**
 - Version rev 6.1.7@554b0c
 - Windows 11

**Comment by MikeZeDev** [comment]
[Already fixed 2 weeks ago](https://github.com/manga-download/hakuneko/pull/5531/files), use nightly.
