### ISSUE TITLE
[Feature] Multi Manga selection

### ISSUE THREAD

**Issue by Ninofj** [manga-download/hakuneko#5603]
**Is your feature request related to a problem? Please describe.**
So it's possible to select all chapters for one Manga but is it possible to select multiple Mangas and all including chapters?

**Describe the solution you'd like**
Multi select for Manga and chapters.

**Context (please complete the following information):**
 - HakuNeko 6.1.7

**Comment by MikeZeDev** [comment]
Pretty sure you wont see that in Hakuneko. As far as Haruneko is concerned, i wonder 

1) What would be the use case? Mass download? Its already possible to do that for a whole manga, i think going multi manga will be against the program philosophy.

1) if its doable. I mean sure, but its more complex than you can imagine.

**Comment by Sheepux** [comment]
Multi manga goes against the ad-hoc consumption, I'm voting to reject this issue

> The philosophy is ad-hoc consumption, get it when you want to read/watch it. It is not meant to be a mass downloader to stock up thousands of chapters that are just collected and will probably never be read.

Multi chapter is already available via filter/download all button, and in haruneko via multi select
