### ISSUE TITLE
Japscan Connector not working

### ISSUE THREAD

**Issue by Maxitoll** [manga-download/hakuneko#5605]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes/

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Japscan URL have change : https://www.japscan.lol/mangas/

**To Reproduce**
1. Name of connector :Japscan
The new URL :https://www.japscan.lol/mangas/

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4657
