### ISSUE TITLE
[Cocomanhua/Colamanhua] Connector not working

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#5606]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
cannot download chapter, it download bin file 

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
* Cant reproduce error on nightly 
* Template not filled properly 

>     Name of connector
>     Name of manga (if connector update is working)
>     Name of chapter (if manga update is working)
>     Copy any relevant error message that appears in a popup or (advanced) within the console (press F12

Please provide required informations. Also you said you tried nightly but since you didnt fill the template properly and that bug should be fixed i have doubts about that.

**Comment by MikeZeDev** [comment]
Nevermind : Nothing can be done, they block ip for whatever reasons

![image](https://user-images.githubusercontent.com/10671518/227504057-99c36c0d-1e12-42f9-a208-61a958573f7f.png)

**Comment by ttasadasdw** [comment]
- the problem with coco : colamanhua 
-  Describe : 
1. see that the new comic is not loaded in tab Chapter. example the comic : example :大医凌然.
you can see , it have no chapter :
![image](https://github.com/manga-download/hakuneko/assets/125495298/91c2af7f-e7ca-4f64-aef2-41608e39e57b)
2. If i use link of comic : https://www.colamanhua.com/manga-wp49323/ 
It have success load the chapter but if click on chapter , it have error _cad is not defined !

![image](https://github.com/manga-download/hakuneko/assets/125495298/19ba9a14-5cd4-432f-96f7-17f9df6217a7)
3. If i use link of chapter 236 : https://www.colamanhua.com/manga-wp49323/1/237.html
![image](https://github.com/manga-download/hakuneko/assets/125495298/abe29df1-fe60-4409-bf25-5fcc75d3fef9)
