### ISSUE TITLE
[Site Request] newtoki

### ISSUE THREAD

**Issue by longIT0708** [manga-download/hakuneko#5607]
**Name of the website**
newtoki282

**Website urls (examples below)**
- Site: https://newtoki282.com/
- Manga List: https://newtoki282.com/webtoon?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
- Manga example: https://newtoki282.com/webtoon/11300191?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
- Chapter online viewer example: https://newtoki282.com/webtoon/27411465/%EC%96%BC%EC%96%B4%EB%B6%99%EC%9D%80-%ED%94%8C%EB%A0%88%EC%9D%B4%EC%96%B4%EC%9D%98-%EA%B7%80%ED%99%98-75%ED%99%94?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0&spage=1

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website is already supported  stop with useless issues
