### ISSUE TITLE
[Manga SY] Connector not working

### ISSUE THREAD

**Issue by ZeroMD** [manga-download/hakuneko#5609]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
None of the downloads seem to work.
The website is working.
I can retrieve a list of series, but downloading a chapter fails

**To Reproduce**
1. Manga SY
2. All manga have the same problem, but I'll pick the first as example, so select "7 Days Of Ecstatic Marriage"
3. Select "Chapter 1-Ecstatic"
4. Click the download button
  2 requests will be made:
  1 ?style=list
  2 chapter-1-ecstatic/
  It looks like something goes wrong here, it does not start downloading pictures
6. After a few seconds the download failed

**Screenshots**
These are the only errors I see in the console
![image](https://user-images.githubusercontent.com/39047641/227709643-c781e7ad-a1f9-4439-a63c-0e248cfb4b3c.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
1) Error is normal, we try to get chapters using different ways, first is failing.
2) Seems like they protect images now 

![image](https://user-images.githubusercontent.com/10671518/227710864-63c20056-249a-4217-99c1-ac26bb7ef149.png)

Its Wordpress Manga Protector
