### ISSUE TITLE
[GD Scans] URL change

### ISSUE THREAD

**Issue by Torablue** [manga-download/hakuneko#5610]
GD Scans changed their domain. From .xyz to .com
Btw, I tried to change it myself, but I can't push it. How to apply for permission??

**Comment by MikeZeDev** [comment]
Fork hakuneko, modify file, open a pull request, and ill validate the changes. Its gonna be approved faster this way :)
Mention this issue as "Fixes issueurl" in PR text for automatic closure.

**Comment by Torablue** [comment]
Fixes issueurl

**Comment by MikeZeDev** [comment]
Dont close it until its fixed ;)

**Comment by Torablue** [comment]
Oh I see. Sorry about that.
Btw, I already edit it.
