### ISSUE TITLE
[Site Request] Mangareaderpro

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5622]
**Name of the website**
Mangareaderpro

**Website urls (examples below)**
- Site:  https://mangareaderpro.com/
- Manga List: https://mangareaderpro.com/es/manga/
- Manga example: https://mangareaderpro.com/manga/un-ladron-borracho-que-compro-una-esclava/
- Chapter online viewer example: https://mangareaderpro.com/manga/un-ladron-borracho-que-compro-una-esclava/capitulo-9/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara
