### ISSUE TITLE
[MangaSee] Not working for specific manga/chapters but working just fine for everything else.

### ISSUE THREAD

**Issue by Jamerrone** [manga-download/hakuneko#5624]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Chapters 10-30 of the [The Magical Revolution of the Reincarnated Princess and the Genius Young Lady](https://mangasee123.com/manga/The-Magical-Revolution-of-the-Reincarnated-Princess-and-the-Genius-Young-Lady) manga are not being downloaded. I get the followwing error:
<img width="534" alt="Screenshot 2023-03-30 at 15 24 54" src="https://user-images.githubusercontent.com/16142485/228850650-1ec675de-ef83-4f74-84cb-3c2ff5d64733.png">
However, they work just fine when visiting the website.

**To Reproduce**
1. Name of connector: MangaSee
2. Name of manga (if connector update is working): The Magical Revolution of the Reincarnated Princess and the Genius Young Lady
3. Name of chapter (if manga update is working): 10-30
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): See bug description.

**HakuNeko (please complete the following information):**
 - Version: 6.1.7@debbcc

**Comment by MikeZeDev** [comment]
On a real browser when i load chapter 10 page, i have 50% chance that the page is fucked up, 50% chances that it works.

![image](https://user-images.githubusercontent.com/10671518/228910805-0aad4bc9-bab6-4630-b400-81569ce69975.png)

If website is fucked up, cant fix

**Comment by Jamerrone** [comment]
@MikeZeDev I see, I am not sure about the 50% chance, but once it breaks, it stays broken. Clearing the cache seems to fix it again, but only temporary. Closing this issue as it seems site related. Thanks for your response.
