### ISSUE TITLE
[myreadingmanga.info] Connector not working

### ISSUE THREAD

**Issue by billsargent** [manga-download/hakuneko#5625]
**Is the website of the connector working properly / are you able to see the manga within your browser**

Yes

**Describe the bug**

The connector does not work because it cannot get past cloudflare. When viewing the site in a normal browser it works, however the internal browser gives a hint at a possible cause. Cloudflare reports the browser is too old. Is it possible to update the GUI to use updated components or does this run a CLI behind the scenes?

**Screenshots**
![image](https://user-images.githubusercontent.com/32219940/229284399-b9b6eec9-8729-49f5-9a18-e372c0ec0206.png)
![image](https://user-images.githubusercontent.com/32219940/229284421-bab5347c-a124-4cf1-8f00-4063ed63d45b.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
6.1.7

**Comment by MikeZeDev** [comment]
There is no CLI. The Electron we use is outdated. There is nothing to do as changing the version is breaking stuff.
Choose another website or wait for Haruneko.

**Comment by MikeZeDev** [comment]
Btw, Duplicate https://github.com/manga-download/hakuneko/issues/4020

**Comment by billsargent** [comment]
Sorry about the duplicate part. -- Where is the client source? Your development wiki page says there should be a client directory for the Windows app but its just not there when I clone the repository.

**Comment by MikeZeDev** [comment]
Well, i guess the app appears when you build it. 

> npm run build
