### ISSUE TITLE
[Site Request] Arcane Scans

### ISSUE THREAD

**Issue by Coravon** [manga-download/hakuneko#5626]
**Name of the website**
Arcane Scans

**Website urls (examples below)**
- Site: https://arcanescans.com/
- Manga List: https://arcanescans.com/manga/
- Manga example: https://arcanescans.com/manga/i-spread-immortality-all-over-the-world/chapter-1/
- Chapter online viewer example: https://arcanescans.com/manga/i-spread-immortality-all-over-the-world/chapter-1/

**Languages**
- English

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
Added to Haruneko https://github.com/manga-download/haruneko/pull/344
