### ISSUE TITLE
[Mangafox] Can't Download Properly

### ISSUE THREAD

**Issue by firmanjawa** [manga-download/hakuneko#5627]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I am new so i don' know much, but i already search for the possible solution but not fixed yet. I try to download manga in mangafox, it progress to download, but it become error and the file that I download as pdf, can't opened or error to.

**To Reproduce**
1. Connector : Mangafox
2. Manga : Akame ga Kill
3. All chapter i think, trying download chap 69 to 75 still not working

Loading Engine: HakuNeko
hakuneko://plugins/:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
index.html:61 Loading Frontend: frontend@classic-dark
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
loadClassicPolymer @ index.html:76
VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:340)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:340)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:340)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
(anonymous) @ BookmarkManager.mjs:137
index.html:1 A cookie associated with a resource at http://vrv.co/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'D:\1. Manga - Manhwa\Hakuneko\Hakuneko 8.3.4 x64\userdata\hakuneko.mangas.mangabat'
(anonymous) @ Connector.mjs:215
index.html:1 A cookie associated with a resource at http://m.mangabat.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
index.html:1 A cookie associated with a resource at http://h.mangabat.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
index.html:1 A cookie associated with a resource at http://fanfox.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
index.html:1 A cookie associated with a cross-site resource at http://fanfox.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
DownloadJob.mjs:115 Error: Failed to load image!
    at Image.img.onerror (Storage.mjs:522) Array(60)
_downloadPages @ DownloadJob.mjs:115
DevTools failed to parse SourceMap: hakuneko://cache/js/protobuf.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/js/hls.light.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/sm/4f4f84956292156efc04b79e1131dc7c3a51794b7b3d62b43ed5eaca1b36d71e.map

**Screenshots**
![image](https://user-images.githubusercontent.com/76039896/229331272-4dbc048e-51f8-4bb0-a345-1cadcb0c1cb0.png)

**HakuNeko (please complete the following information):**
 - NIghtlyBuil 8.3.4 Portable x64

**Comment by MikeZeDev** [comment]
You could at least have set up a proper title for that issue, it help for triage you know :) Nevermind.

![image](https://user-images.githubusercontent.com/10671518/229343574-caea9628-3a59-4d4c-86c7-0cd518314eb5.png)

There are errors 403 but its "normal" and this doesnt prevent downloading.

I dont see why its not working.

Well i am gonna fix that 403 errors, who knows?

**Comment by firmanjawa** [comment]
Thank you very much for the respond and sorry for the inconvenience, I actually kinda new for github to, so didn't realize it. I hope the problem can solved easily. Once again thank you

**Comment by MikeZeDev** [comment]
@firmanjawa Any news?

**Comment by firmanjawa** [comment]
@MikeZeDev sorry, with how low my ability, I can only try som simple external trick, the last thing i try is using virtual box, but it just burdening my laptop, and it's still no use even I using VPN
