### ISSUE TITLE
[Site Request] https://hentai20.io/

### ISSUE THREAD

**Issue by Erest99** [manga-download/hakuneko#5628]
**Name of the website**
heantai20

**Website urls (examples below)**
- Site: https://hentai20.io/
- Manga List: https://hentai20.io/manga-genre/manhwa-hentai-24/
- Manga example: https://hentai20.io/manga/springtime-for-blossom-1000/
- Chapter online viewer example: https://hentai20.io/manga/springtime-for-blossom-1000/chapter-0/

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Asked many times, impossible . Cloudflare.
Duplicate https://github.com/manga-download/hakuneko/issues/4241
