### ISSUE TITLE
[Site Request] topmangas [Mangas/FR]

### ISSUE THREAD

**Issue by ReivenIV** [manga-download/hakuneko#5631]
**Name of the website**
topmangas

**Website urls (examples below)**
- Site: https://topmangas.fr/
- Manga List: https://topmangas.fr/
- Manga example:  https://demonslayervf.com/
- Chapter online viewer example: https://demonslayervf.com/manga/demon-slayer-scan-vf-chapitre-1/

**Languages**
French

**Comment by MikeZeDev** [comment]
A portal that just link to "one manga" websites. huh.

1) We do not support websites with only one manga. Its a waste of time.
2) Making a single webpage to link those kind of websites doesnt change anything. Different urls each time would be messy.

**Comment by MikeZeDev** [comment]
Reopened because there is a precedent : https://github.com/manga-download/hakuneko/blob/c81e82ae03f94e0cd64e760ee3ffcda3bb519cd8/src/web/mjs/connectors/MangaCruzers.mjs

**Comment by MikeZeDev** [comment]
As expected, websites are a mess. For the end user they seems identical but there are so many inconsistencies that you never know if a chapter will load or not. They love to use different CSS for pictures :D

 This will need heavy testing if someone is motivated.
