### ISSUE TITLE
[Site Request] vfscan

### ISSUE THREAD

**Issue by ReivenIV** [manga-download/hakuneko#5632]
**Name of the website**
vfscan

**Website urls (examples below)**
- Site: https://www.vfscan.com/
- Manga List: https://www.vfscan.com/manga/
- Manga example: https://www.vfscan.com/manga/valkyrie-apocalypse/
- Chapter online viewer example: https://www.vfscan.com/scan-valkyrie-apocalypse-1/

**Languages**
French

**Comment by MikeZeDev** [comment]
Useless. All their pictures comes from scansmanga.me, which is already supported.

![image](https://user-images.githubusercontent.com/10671518/229503632-6a787ccf-ba6a-4b36-a12d-4fa882c9c6ff.png)

![image](https://user-images.githubusercontent.com/10671518/229503735-5d090df0-7bbc-4be3-b67e-e95c5a3bc6c7.png)

**Comment by reivenIV** [comment]
Thanks for the effort !

**Comment by 1MarONE** [comment]
sorry, thanks
