### ISSUE TITLE
[OmegaScans] Connector not working

### ISSUE THREAD

**Issue by xavimaa** [manga-download/hakuneko#5633]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I want to refresh the list of manga or chapters of a manga, I get a 404 error.
The site seems to have been updated and no longer use WordPress Mangastream.

**To Reproduce**
1. Name of connector : OmegaScans
2. Name of manga (if connector update is working) : not working
3. Name of chapter (if manga update is working) : not working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : 

GET https://omegascans.org/manga/list-mode 404
fetchDOM	@	Connector.mjs:434
_getMangas	@	WordPressMangastream.mjs:25
_getMangaList	@	Connector.mjs:576
(anonymous)	@	Connector.mjs:99
Promise.then (async)		
updateMangas	@	Connector.mjs:98
onUpdateMangaListClick	@	mangas.html:233
handler	@	template-stamp.html:96

**HakuNeko (please complete the following information):**
 - Version [master@deed91]

**Comment by xavimaa** [comment]
Thank you for your work.
I just tried to refresh the manga list and I got an error message.
I have no information about this message in console.
I don't get a console request when I click on a manga too.

![image](https://user-images.githubusercontent.com/82511742/230641627-9f024251-7a7a-4dc6-9f1e-bbaad68ca387.png)

**Comment by MikeZeDev** [comment]
Oops, typo
