### ISSUE TITLE
[Site Request] scan-vf

### ISSUE THREAD

**Issue by ReivenIV** [manga-download/hakuneko#5634]
**Name of the website**
scan-vf

**Website urls (examples below)**
- Site: https://www.scan-vf.net/
- Manga List: https://www.scan-vf.net/manga-list
- Manga example: https://www.scan-vf.net/one_piece
- Chapter online viewer example: https://www.scan-vf.net/one_piece/chapitre-1/1

**Languages**
French

**Comment by MikeZeDev** [comment]
Dont request already supported websites.

![image](https://user-images.githubusercontent.com/10671518/229501274-a1555e75-b56e-42ff-bd46-535b9cb1f2a4.png)

**Comment by reivenIV** [comment]
Thanks a lot !! Sorry for the trouble
And awesome news <3
