### ISSUE TITLE
[Site Request] thewebsitename mangasee

### ISSUE THREAD

**Issue by u3k0wN** [manga-download/hakuneko#5636]
**Name of the website**
Mangasee
**Website urls (examples below)**
- Site: https://mangasee123.com
- Manga List: https://mangasee123.com/directory/
- Manga example: https://mangasee123.com/manga/Chainsaw-Man#unavailable
- Chapter online viewer example: https://mangasee123.com/read-online/Jujutsu-Kaisen-chapter-218-page-9.html

**Languages**
english

**Comment by MikeZeDev** [comment]
Already supported.

![image](https://user-images.githubusercontent.com/10671518/229515042-5d4f5757-c87d-4e83-88ea-6b3a771e0884.png)
