### ISSUE TITLE
[Hiperdex] Connector not working and domain change.

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#5638]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cloudflare

**To Reproduce**
1. hiperdex
2. hiperdex.com
![Screenshot_1](https://user-images.githubusercontent.com/81703465/229549598-2d9708a9-3123-4027-bd60-0ccc6dbca0b2.png)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version Nighly [8.3.4]

**Comment by andillk** [comment]
the domain back to old domain https://hiperdex.com/

**Comment by MikeZeDev** [comment]
1) There is a setting for the url
2) They turns on and off Cloudflare regularly, so Hakuneko cant access it and gives the kind of message you posted. This cant be fixed and its useless to report it :D

**Comment by andillk** [comment]
> 1. There is a setting for the url
> 2. They turns on and off Cloudflare regularly, so Hakuneko cant access it and gives the kind of message you posted. This cant be fixed and its useless to report it :D

The url is change back to https://hiperdex.com/
