### ISSUE TITLE
[Hiperdex] Domain Website Has Change

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#5639]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Domain website has change

**To Reproduce**
1. https://hiperdex.com/

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by andillk** [comment]
the domain is back to old url

**Comment by MikeZeDev** [comment]
If i closed the previous one , dont reopen one minutes later, and read what i WROTE.
