### ISSUE TITLE
Kissanime host not working

### ISSUE THREAD

**Issue by eggyrulz** [manga-download/hakuneko#564]
Recently I was trying to watch some anime on kissanime, and I discovered that none of the videos would load. They all seem to return the error message "Cannot read property '1' of null". I don't know anything about coding so I still have no idea what that error means, however, I did do some digging. Your program is set to use kissanime's Rapidvideo files, which they just mass deleted in favor of a less glitchy/virusy server. If this could be addressed I would be extremely greatful.

OS: windows 10 x64 Home edition 
build version: 5.0.8 and I tried both the windows setup version and windows portable, both 64-bit as that is what my OS is
Rev number is: 3a8a8f
Website: Kissanime, obvisously, and issue is with any and all Rapidvideo files from them.
Settings: all settings are at default
error log shows: 
TypeError: Cannot read property '1' of null
    at kissanime.html:96 Chapter
(anonymous) @ kissanime.html:108

**Comment by ms308680** [comment]
same here, I also read I believe on discord that there has been a big issue with RapidVideo.

**Comment by 27136773** [comment]
Currently there is ongoing integration to support their new HydraX media hosting mirror, but it is not going smoothly due to lag of time...

**Comment by eggyrulz** [comment]
Understood, just wanted to make sure y’all were aware of the issue, and now that I know a resolution is in the works I shall patiently await it’s arrival. Thank you.

**Comment by 27136773** [comment]
Reopened until fixed
