### ISSUE TITLE
[PojokManga] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5640]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. PojokManga
2. Name of manga (if connector update is working)
3. Cant open the chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/112748173/229750715-781cd219-f25d-460b-935c-95c9f90e7a53.png)
![image](https://user-images.githubusercontent.com/112748173/229750950-a9abda19-be7c-4e86-89b7-97ed0c94b419.png)
![image](https://user-images.githubusercontent.com/112748173/229751000-b2bf637a-23d3-4ac8-b01b-7437f5f46c78.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 8.3.4]

**Comment by MikeZeDev** [comment]
Website is geoblocked, cant do anything. If you have access tell me, maybe there is something to try.
