### ISSUE TITLE
[Sinenis Scan] Connector not working

### ISSUE THREAD

**Issue by Akarin2** [manga-download/hakuneko#5644]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No, but i think the problem is because the site changed in 2022. I don't know if it was the link, the host or whatever, but since then the look of the site is the same as CeriseScan which also changed the site in 2022 and the connector does not work anymore.

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
when I select the scan and click to update, the list of mangas does not appear. It stops updating, but none of the manga appear. I can't even access the chapters, because the list of manga doesn't appear.

**To Reproduce**
1. Name of connector [Sinenis Scan, but the correct is SinenSIS Scan]
2. Name of manga (not working)
3. Name of chapter (not working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
[none message. I think? I don't know if I did it right.]

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [Windows64. 6.17]

**Comment by MikeZeDev** [comment]
Website is just dead do you have another url? 

![image](https://user-images.githubusercontent.com/10671518/230348802-49a70e10-bf90-4538-93ee-025b9ba7af1c.png)

Before reporting please at least check if website is working :)
In case its dead report it to the pinned issue i made : https://github.com/manga-download/hakuneko/issues/4972

**Comment by MikeZeDev** [comment]
New url i guess  : [sinensisscans](https://sinensisscans.com/)
