### ISSUE TITLE
[Site Request] Yumekomik

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5649]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://yumekomik.com/
- Manga List: https://yumekomik.com/manga/
- Manga example: https://yumekomik.com/manga/invincible-after-a-hundred-years-of-seclusion/
- Chapter online viewer example: https://yumekomik.com/2023/04/06/invincible-after-a-hundred-years-of-seclusion-chapter-70-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Was added 2 days ago https://github.com/manga-download/hakuneko/blob/22bb211fbfb167ee338efded3f6be1d003e98609/src/web/mjs/connectors/YumeKomik.mjs.

Check before asking please ^^
