### ISSUE TITLE
[JayMana] Connector not working

### ISSUE THREAD

**Issue by mystacoda** [manga-download/hakuneko#5652]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Many of the manga available on the website are not showing up in Hakuneko
Including [원피스(ONE PIECE)](https://kr21.jmana.one/book?bookid=4681), and likely more (have not checked).

**To Reproduce**
1. Name of connector: JayMana (Jmana1)
2. Name of manga (if connector update is working): 원피스
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment]
Website address changed.

**Comment by MikeZeDev** [comment]
Also where did you get that link? 

Yours is /book?bookid=xxxx . 

The correct link i got for one piece is 

/comic_list_title?bookname=%EC%9B%90%ED%94%BC%EC%8A%A4%28ONE+PIECE%29

Pasting feature will work with mine, not with yours o_o
