### ISSUE TITLE
[Omegascans] site changed and not working anymore

### ISSUE THREAD

**Issue by Gwonhoozz** [manga-download/hakuneko#5656]
https://omegascans.org/

**Comment by MikeZeDev** [comment]
Use nightly

**Comment by MikeZeDev** [comment]
Feel free to reopen this issue in case nightlty doesnt work :)

**Comment by Gwonhoozz** [comment]
> Feel free to reopen this issue in case nightlty doesnt work :)

I was using nightly from start

**Comment by Gwonhoozz** [comment]
> Feel free to reopen this issue in case nightlty doesnt work :)

**Comment by Gwonhoozz** [comment]
> > Feel free to reopen this issue in case nightlty doesnt work :)

No it's working

**Comment by Gwonhoozz** [comment]
> Feel free to reopen this issue in case nightlty doesnt work :)

It gives me .IMG format i think there is something wrong with it i just downloaded Chapter 30 of where is my Hammer

**Comment by MikeZeDev** [comment]
Huh?  In case it works you should download png/jpg/webp. And if it doesnt work you will get BIN files. Where does that IMG come from? On it.

Edit  : i see. Their server send wrong file type.

**Comment by Gwonhoozz** [comment]
> Huh? In case it works you should download png/jpg/webp. And if it doesnt work you will get BIN files. Where does that IMG come from? On it.
> 
> Edit : i see. Their server send wrong file type.

So it can't be fixed?

**Comment by MikeZeDev** [comment]
haha it can, its easy, its a known problem with a known solution just wait

https://github.com/manga-download/hakuneko/pull/5659

**Comment by Gwonhoozz** [comment]
> haha it can, its easy, its a known problem with a known solution just wait
> 
> #5659

Hey this site add a new comic called world tree but it's not showing up in list i refreshed it a couple of times
Omegascans.

**Comment by MikeZeDev** [comment]
Wait for the PR to bemerged
