### ISSUE TITLE
[Bug] New chapters not appearing unless cache is manually cleared

### ISSUE THREAD

**Issue by Agnaldo-Carmo** [manga-download/hakuneko#5658]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When a new chapter is added to a website/connector , it does not appear in hakuneko until I manually wipe the cache folder.

**To Reproduce**
1. Go to (https://unionleitor.top/home)'
2. Choose any manga and see its current latest chapter
3. Open hakuneko , connect to UnionMangas , open the chosen manga and see if the latest chapter to appear in the list match the website`s.
4.When a new chapter is released in the website, open hakuneko again and see that the new chapter will not appear in the manga`s chapter list.
5.(On windows) wipe the cache folder content located in AppData\Roaming\hakuneko-desktop\Cache.
6.Open hakuneko again and the new chapter will appear in the list.

**Expected behavior**
After a new chapter is released in website it should automatically appear in hakuneko manga list.

**Context (please complete the following information):**
 - OS: [Windows11]
 - HakuNeko Version [ 6.17]

**Additional context**

**Comment by MikeZeDev** [comment]
There is no need to empty cache or whatever. This is not a bug. Its working as intended.
Chapters list are cached in memory the first time you click on a manga. It will stay until you close and launch Haku again.
It was done like that so its not hammering servers.

What we need is a way to force refresh chapters. IIRC its not planned in Hakuneko, but already implemented in Haruneko.

**Comment by Agnaldo-Carmo** [comment]
"There is no need to empty cache or whatever", but if i don`t the chapters never update, "Chapters list are cached in memory the first time you click on a manga. It will stay until you close and launch Haku again." no matter , even after relauching haku it`s still not update.

**Comment by MikeZeDev** [comment]
Exemple so i can reproduce the problem? Website manga and chapter?

**Comment by Agnaldo-Carmo** [comment]
I often download this one in union mangas : https://unionleitor.top/manga/yu-gi-oh

currently it`s chapter 190 , released yesterday, it should release another in 2 days , following their schedule of 3 days rate

**Comment by MikeZeDev** [comment]
Got it, we will see in a couple of days then

**Comment by MikeZeDev** [comment]
Chapters are shown, its now 193. I didnt empty anything. Idk what to say.

**Comment by Agnaldo-Carmo** [comment]
odd , Mines still 190, only thing i forgot to mention is that i bookmarked this manga, dunno if that has anything to do

**Comment by MikeZeDev** [comment]
Ah. Thats it. Someone said we were using the url of a copycat website instead of the good one. So we changed it to the real one,
Your bookmark may therefore be invalid (or point to old website).

https://github.com/manga-download/hakuneko/commit/5afcec5fae9c797433921f36aea961163843594a


Update your manga list and redo your bookmarks.
Unfortunately there is no easy way to update bookmarks when website changes url AND structure.

**Comment by MikeZeDev** [comment]
ON the copycat its 193 too, idk whats going on but in case of doubts, just ditch bookmark.

**Comment by Agnaldo-Carmo** [comment]
I don`t know what to do anymore, tha last thing that`s left for me to tryis completely uninstall and reinstall Haku
