### ISSUE TITLE
[ManhuaPlus] Connector not working : 403

### ISSUE THREAD

**Issue by Sildran** [manga-download/hakuneko#5660]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
When trying to open ManhuaPlus' manhwas from my manga list, I hear the start of a music for around 0,5sec and then nothing.
Can't get their manga list when trying to update.

**To Reproduce**
1. ManhuaPlus
2. Tales Of Demons And Gods
3. Any chapters
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) :

Connector.mjs:434 GET https://manhuaplus.com/manga/tales-of-demons-and-gods/ 403

Sorry, you have been blocked
You are unable to access manhuaplus.com
Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

 - Version : Nightly master@b9a2f8

**Comment by Sildran** [comment]
I forgot to mention the 403 is only with hakuneko. I can access their website without issue using my browser

**Comment by MikeZeDev** [comment]
> I forgot to mention the 403 is only with hakuneko. I can access their website without issue using my browser

Of course, that is called cloudflare and this particular warning can probably be solved.

Nevermind : i got that sh- on front page. :/

**Comment by Sildran** [comment]
Thanks for the explanation and the fix ;)

**Comment by MikeZeDev** [comment]
Feel free to reopen this issue in case fix doesnt work (we never know with cloudflare)
