### ISSUE TITLE
[Site Request] ebookjapan

### ISSUE THREAD

**Issue by Janime6** [manga-download/hakuneko#5663]
**Name of the website**
ebookjapan

**Website urls (examples below)**
- Site: https://ebookjapan.yahoo.co.jp/
- Manga List: https://ebookjapan.yahoo.co.jp/ranking/ (this is just their rankings page)
- Manga example: https://ebookjapan.yahoo.co.jp/books/382444/
- Chapter online viewer example (1): https://ebookjapan.yahoo.co.jp/viewer/trial/B00184016810/ (this is a viewer for the samples)
- Chapter online viewer example (2): https://ebookjapan.yahoo.co.jp/viewer/purchased/B00160684563/ (this is for a book that I bought, so probably useless to anyone who doesn't also own it)

**Languages**
Japanese

**Additional details**
[EbixExtract](https://github.com/y2361547758/EbixExtract) doesn't work with newer books anymore, so it'd be nice to have a way to get ebookjapan stuff again.

**Comment by Ever4engel** [comment]
duplicate #228

**Comment by Ever4engel** [comment]
side note for the guy who opened this ticked, use kubo.
