### ISSUE TITLE
[dm5.com] Connector not working completely

### ISSUE THREAD

**Issue by yaCoderIce** [manga-download/hakuneko#5665]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

Thanks for fixing this connector, however, it is not 100% working yet.

Eg: 
https://www.dm5.com/manhua-buguoshizhizhushenmede/

There are several tabs
[连载] [卷] [番外]

The connector now only reads from 连载 and not the other two. Making this 96 chapters only
![image](https://user-images.githubusercontent.com/36793934/230794291-c7183d4e-6cdb-4972-a159-bfc39e1cb87f.png)

**To Reproduce**
1. Name of connector
DM5.com
3. Name of manga (if connector update is working)
不过是蜘蛛什么的
4. Name of chapter (if manga update is working)
[卷] all 5 of them
5. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
No Error, but it is not displaying in the potential download list.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
I see. May i ask what are those tabs? What are their purpose/ meanings?
