### ISSUE TITLE
[Feature] Pause/Smart downloading

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#5670]
**Is your feature request related to a problem? Please describe.**
Not a problem perse.

**Describe the solution you'd like**
I don't know if it's actually called "smart" downloading, but basically what I am talking about is downloads being put on pause when you close or app and then restart when you start the app again.

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. master@1e5ef1]

**Comment by Sheepux** [comment]
duplicate #8 (yup yup, that's old)
