### ISSUE TITLE
[Site Request] Coffee Manga

### ISSUE THREAD

**Issue by hunght37** [manga-download/hakuneko#5672]
**Name of the website**
Coffee Manga

**Website urls (examples below)**
- Site: https://coffeemanga.io/
- Manga List: https://coffeemanga.io/
- Manga example: https://coffeemanga.io/manga/romantic-flow/
- Chapter online viewer example: https://coffeemanga.io/manga/romantic-flow/chapter-8/

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara
