### ISSUE TITLE
[Realmscans] Connector not working

### ISSUE THREAD

**Issue by zeoint** [manga-download/hakuneko#5676]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector is showing the manga list, but not downloading, red error symbol in chapter download.

**To Reproduce**
1. Realmscans
2. [Top Tier Providence ](https://realmscans.com/m270323/series/top-tier-providence/)(if connector update is working)
3. [From Chapter 21 Finally Against Zhou Fan ](https://realmscans.com/m270323/top-tier-providence-chapter-21/)(if manga update is working)
4. It might be because they renamed the empty chapters with titles. Ex. Chapter 21 to Chapter 21 Finally Against Zhou Fan.

**Screenshots**

![image](https://user-images.githubusercontent.com/127277950/231468397-2979c236-416e-4d63-9e8b-7b4f77a5aa05.png)

**HakuNeko (please complete the following information):**
 - rev. master@f1db6e

**Comment by MikeZeDev** [comment]
Cloudflare cant fix

![image](https://user-images.githubusercontent.com/10671518/231552192-278eb762-cf91-4f55-88c7-5b1a129b440d.png)

**Comment by zeoint** [comment]
It is working now.

**Comment by MikeZeDev** [comment]
Nope, still getting cloudflare errors

**Comment by zeoint** [comment]
I mean, after downloading about 10 chapters, it throws cloudflare error then.

**Comment by zeoint** [comment]
- See, it is working.
- But sometimes it throws cloudfare errors, when downloading chapters in bulk. But after 2 minutes of idle, again works.

https://user-images.githubusercontent.com/127277950/234335167-9ed00ea9-3642-404f-b8fc-cbfef653b3bd.mp4

**Comment by MikeZeDev** [comment]
They removed/lowered CF, we did nothing.
