### ISSUE TITLE
[Japscan] Connector not working : Failed to detect page type!

### ISSUE THREAD

**Issue by wazaki** [manga-download/hakuneko#5677]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I'm on on ios with version 6.1.7.
The problem is the following.
I can see the manga list from Japscan, when i click on a manga. The chapter list is shown but when i want to download a chapter a see it on the preview i have an error : "Failed to detect page type!". i have check directly on the website and everything is ok.

**To Reproduce**
1. Japscan
2. one piece
3. Chapitre 1080 : ...
4. Failed to detect page type!

**HakuNeko (please complete the following information):**
 - Apple M1 Max
 - Hakuneko version 6.1.7

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4657
