### ISSUE TITLE
manga freak 

### ISSUE THREAD

**Issue by zorotoisthebestanimesite** [manga-download/hakuneko#5679]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
when i try to search using this connector, the error "cannot read property "href" of undefined"

**To Reproduce**
1. mangafreak

**HakuNeko (please complete the following information):**
 - Version 6.17
 - 64 bit operating system

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4292 + cant fix

**Comment by zorotoisthebestanimesite** [comment]
Oh that sucks, well thanks for checking it out either way
