### ISSUE TITLE
[https://nonbiri.space/] Nonbiri Space

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5684]
**Name of the website**
Nonbiri Space

**Website urls (examples below)**
- Site: https://nonbiri.space/
- Manga List: https://nonbiri.space/manga/
- Manga example: https://nonbiri.space/manga/martial-peak/
- Chapter online viewer example: https://nonbiri.space/martial-peak-chapter-3030/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream template

**Comment by ClayzaAubert** [comment]
mangareader template
