### ISSUE TITLE
[ComicK.app] API Requests fails at page 101 

### ISSUE THREAD

**Issue by smol-loli** [manga-download/hakuneko#5688]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Syncing the Manga list from the comick.app connector fails at request of API page 101. According to HakuNeko 2965 Mangas are available but website says there are over 80.000.

**To Reproduce**
1. connector: ComicK
2. Manga: Kimi ga Shinu Made Koi Wo Shitai
3. chapter: all
4. Errors: Status 400 on FETCH https://api.comick.app/search?page=101

Opening the url in Firefox shows the following: {"statusCode":400,"message":"querystring/page must be <= 100"}

**Screenshots**
![Screenshot_20230417_214016](https://user-images.githubusercontent.com/118623325/232593232-05a1a610-08f4-4151-be3d-8ce215de1642.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.1.7@debbcc]

**Comment by smol-loli** [comment]
Using links and the clipboard connector is still working. I also noticed that the search bar on the website itself sents the searched text as API calls and gets back possible results. Maybe that can be taken into consideration when changing the connector.

**Comment by MikeZeDev** [comment]
Website stops at page 100 you know

https://cdn.discordapp.com/attachments/581630792120401922/1092710280129167381/image.png

Nothing can be done. Its for cases like that that there IS a clipboard feature.

**Comment by smol-loli** [comment]
I didn't know that. Sorry for the inconvenience!
