### ISSUE TITLE
[Site Request] Nonbiri

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5689]
**Name of the website**
Nonbiri

**Website urls (examples below)**
- Site: https://nonbiri.space/
- Manga List: https://nonbiri.space/manga/
- Manga example: https://nonbiri.space/manga/martial-peak/
- Chapter online viewer example: https://nonbiri.space/martial-peak-chapter-3041/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already added https://github.com/manga-download/hakuneko/pull/5687
