### ISSUE TITLE
[Site Request] Tukangkomik

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5691]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://tukangkomik.id/
- Manga List: https://tukangkomik.id/manga/
- Manga example: https://tukangkomik.id/manga/endless-devourer/
- Chapter online viewer example: https://tukangkomik.id/endless-devourer-88/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Its not your first issue, right? You know if its a website URL change, you have to make a "website url change" request, not "add this connector" request.
