### ISSUE TITLE
[Site Request] Cosmic Scan

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5694]
**Name of the website**
Cosmic Scan

**Website urls (examples below)**
- Site: https://cosmicscans.id/
- Manga List: https://cosmicscans.id/semua-komik/
- Manga example: https://cosmicscans.id/manga/questism/
- Chapter online viewer example: https://cosmicscans.id/questism-chapter-82/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Added last week, please search before asking.
https://github.com/manga-download/hakuneko/blob/1e5ef1ededc92cd1e816601837af76ae9a0e7d0e/src/web/mjs/connectors/CosmicScansID.mjs
