### ISSUE TITLE
[Site Request] Noromax

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5695]
**Name of the website**
Noromax

**Website urls (examples below)**
- Site: https://www.noromax.xyz/
- Manga List: https://www.noromax.xyz/p/daftar-komik.html
- Manga example: https://www.noromax.xyz/2022/07/sign-in-mystery-box-to-dominate-world_5.html
- Chapter online viewer example: https://www.noromax.xyz/2023/04/sign-in-mystery-box-to-dominate-world_12.html

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
KumaReader template

**Comment by Frezian** [comment]
when was it added?

**Comment by MikeZeDev** [comment]
it doesnt

**Comment by MikeZeDev** [comment]
Switched to Mangastream
