### ISSUE TITLE
[Bug] Facebook comments not linking right

### ISSUE THREAD

**Issue by zippydsmlee** [manga-download/hakuneko#5698]
As you can see in these examples, the links are not working.

https://manganato.com/chapter/ny922152/chapter_381?comment_id=1424147915021398&fbclid=IwAR13lK7NDSNq-exGMWf5AlmDx-SfifFoUvYNAEy-th2vOcXYih60mYd_ILw

https://manganato.com/chapter/the_other_world_doesnt_stand_a_chance_against_the_power_of_instant_death/chapter_15?comment_id=5583359045064690&reply_comment_id=2578130542327091&fbclid=IwAR0H19ytujpBcmbUKAWaMfKBtKvsUHaCFfT5BeXxoy_Vqxy44JUk89n2sGo

https://manganato.com/chapter/qx927591/chapter_57?comment_id=1002360220726214&fbclid=IwAR2kP3R8mfRuqrhH1DoU2exCAu4Ck3PqPz-396QaHZ5J67-9-kWJDloNv_E

I did read about it a bit, its a simple issue of formatting, thus when I get a notice the link it gives is not correctly formatted. but I have no idea how to test it.

Is there a way to find which manga these link was too? I assume this is most of the indenifiter, ny922152 and qx927591?

Man disqus really spoils you..

**Comment by MikeZeDev** [comment]
How? Website gives 404 errors. The second link got the manga name and chapter but thats all.
Nothing to fix here (and its not related to Hakuneko => closing)
