### ISSUE TITLE
[KSGroupScans] Connector not working

### ISSUE THREAD

**Issue by Torablue** [manga-download/hakuneko#5700]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Whenever I synchronize the manga list, I always got "Cannot read property 'href' of undefined". My list is still empty.

**To Reproduce**
1. Name of connector https://ksgroupscans.com/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) "Failed to update manga list for KS Group Scans. Cannot read property 'href' of undefined."

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
They switched to Madara,
