### ISSUE TITLE
Better reordering and resizing of the Downloads pane[Feature]

### ISSUE THREAD

**Issue by ghastlyyyy** [manga-download/hakuneko#5703]
Good day to the devs, I was wondering if it was possible to allow the Downloads pane to be freely resized on the UI, as well as the possibility of dynamically or statically changing the order of future downloads. 
I'm asking this due to a few problems regarding downloads from sources like Mangadex or Mangakakalot, which tend to fail several download requests in a row and pick up at arbitrarily chosen chapters. Currently, the only way to scroll through the download pane is rather frustrating, since one can only see about 5 results out of possibly hundreds for a given title. 
Thank you so much for the amazing tool though!

**Comment by MikeZeDev** [comment]
No download enhancements are scheduled for Hakuneko. For Haruneko it had chances to be done, put an issue here
https://github.com/manga-download/haruneko

**Comment by ghastlyyyy** [comment]
Sorry for replying so late, but thanks!
