### ISSUE TITLE
[Dragon Tea Scans] Connector not working

### ISSUE THREAD

**Issue by zeoint** [manga-download/hakuneko#5706]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

- When using manual interaction - Shows outdated browser message.
- Manga update - Connector update not working
- Manual copy paste is also not working.

**To Reproduce**

1. Dragon Tea Scans
2. connector update is not working
3. manga update is not working
4. Error - 403

**Screenshots**
### Outdated Browser
![Dragontea](https://user-images.githubusercontent.com/127277950/233667428-bde5f53b-2501-4e16-9bed-96b12dda2c51.png)
### Console
![Dragonteaconsole](https://user-images.githubusercontent.com/127277950/233667660-1998853f-d9a8-4caf-8fb2-9349cc50d945.png)

**HakuNeko (please complete the following information):**
 - Version rev.master@b60934

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4476, cant fix
