### ISSUE TITLE
[Site Request] Ler Yaoi

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#5708]
**Name of the website**
Ler Yaoi

**Website urls (examples below)**
- Site: https://leryaoi.com/
- Manga List: https://leryaoi.com/bl/
- Manga example: https://leryaoi.com/bl/restless/
- Chapter online viewer example: https://leryaoi.com/bl/restless/capitulo-10-fim/

**Languages**
Portuguese

**Additional details**
Madara Website

**Comment by MikeZeDev** [comment]
Madara. Since i am ready to push some madara website i'll do this one right now :D
