### ISSUE TITLE
Sanitize path in Ubuntu

### ISSUE THREAD

**Issue by enriqueism** [manga-download/hakuneko#571]
Hi! I have this error dowloading a chapter in Ubuntu with semicolon character in path "Error: EINVAL: invalid argument, open '/foo/bar/hakuneko/Black Clover/Black Clover Chapter 225: Heart Kingdom.cbz'" I'm running hukuneko from command line "npm start" in previos versions I'm used to change characters list in https://github.com/manga-download/hakuneko/blob/cda6c98afd07e8ac3017b848883ee9c60c400557/web/lib/hakuneko/engine/electron/storage.html#L760 but now I don't find where do You sanitize path. Could You help me ti find the method? Thanks.

**Comment by 27136773** [comment]
I guess you are looking for the `Storage.mjs` module
https://github.com/manga-download/hakuneko/blob/4e1ac9feb4bbb9533c7a980b40647cf509012ac0/src/web/mjs/engine/Storage.mjs#L801

**Comment by enriqueism** [comment]
This is exactly what I was looking for. Thanks for your help and for your work.
