### ISSUE TITLE
[Site Request] Night scans

### ISSUE THREAD

**Issue by zeoint** [manga-download/hakuneko#5710]
**Name of the website**
Night scans

**Website urls (examples below)**
- Site: https://nightscans.org/
- Manga List: https://nightscans.org/series/
- Manga example: https://nightscans.org/series/cong-da-shu-kaishi-de-jinhua__trashed/
- Chapter online viewer example: https://nightscans.org/evolution-from-a-tree-1/

**Languages**
English

**Comment by MikeZeDev** [comment]
Cant do it, CF

**Comment by zeoint** [comment]
- [Chapter downloads in realmscans ](https://github.com/manga-download/hakuneko/issues/5676#issuecomment-1522048732)work if they are not downloaded in bulk, if possible please add this site too.
- It might atleast work in the same way.

**Comment by MikeZeDev** [comment]
When i checked i had CF on homepage, meaning it was useless to try. If they lowered the CF level, who knows

**Comment by zeoint** [comment]
It is working, thank you.

**Comment by zeoint** [comment]
The reader is wokring, but when downloaded, it shows .bin file in folder.

**Comment by MikeZeDev** [comment]
Works for me. Image type returned by server is accurate (image/jpeg) and match filenames.

In this case, you probably were blocked by Cloudflare again and your bin are html files.

It may happend from time to time and there is nothing we can do, its useless to even mention it, sadly.

Which manga and chapter ?

**Comment by zeoint** [comment]
> Which manga and chapter ?

Evolution from a tree.
All 61 chapters.

**Comment by zeoint** [comment]
> In this case, you probably were blocked by Cloudflare again and your bin are html files.

For example chapter 1 of evolution from tree,
- The downloaded files are .bin.
- In the website they are .webp.
- So, I changed the extension from .bin to .webp and it worked. They became images.
- From chapter 56 / 59, they use .jpg images.

**Comment by MikeZeDev** [comment]
Ok server is shit and doesn't give a correct type for webp pictures. Not Hakuneko problem but gonna be fixed anyway.

**Comment by zeoint** [comment]
Thank you.

**Comment by zeoint** [comment]
> Ok server is shit and doesn't give a correct type for webp pictures. Not Hakuneko problem but gonna be fixed anyway.

- It is not downloading now. Can you please look into it / roll the changes back to the previous way it downloaded the .bin file.
- I can just rename the extensions.

https://user-images.githubusercontent.com/127277950/235573358-04595347-fa37-4c68-9059-b5179ee3be20.mp4

**Comment by MikeZeDev** [comment]
You didnt try nightly, did you? Fix landed on nightly, not stable.

**Comment by zeoint** [comment]
Nope, I am using nightly / master.

![image](https://user-images.githubusercontent.com/127277950/235684431-59930307-4262-41c2-919e-924216f2f25e.png)

**Comment by MikeZeDev** [comment]
Sorry i am dumb

**Comment by zeoint** [comment]
Thanks, It's working.
