### ISSUE TITLE
8Muses enhancement

### ISSUE THREAD

**Issue by subhajit-001** [manga-download/hakuneko#5712]
Hello developers,

I have added some enhancement for 8muses Website and it is working well. Since I am new to development, I don't know how to compile hakuneko source code to a **.exe** installer. Can you please help me?

**Comment by Sheepux** [comment]
did you read the wiki ?
https://github.com/manga-download/hakuneko/wiki/Developer-Manual

anyway, the' best way is to do a pull request so that it gets merged into the project.

**Comment by MikeZeDev** [comment]
Modify the file directly from github and them submit it as PR :)

**Comment by subhajit-001** [comment]
> did you read the wiki ? https://github.com/manga-download/hakuneko/wiki/Developer-Manual
> 
> anyway, the' best way is to do a pull request so that it gets merged into the project.

Hi Sheepux,

I have read the developer's manual. When I am trying **npm install** it is giving me error. Attaching the error. Also, I believe the command to build app is **npm run build:app**, it is also giving error. Though I have install innosetup compiler, still getting the error. Also attaching this error.

I'll explain what I did in the code changes.

Previously, we have to paste only the comics URL from 8muses which contain pictures. After my code changes. it is successfully, fetching all the comics from a album URL. Though I need to work more on it to make it perfect, it is working fine as of now. Don't know how much it will help others. But I'll do a pull request as per your suggestion.

[npm_install_error](https://drive.google.com/file/d/166WTn5S8ITbRHeUPnEv1VbwjegURErQF/view?usp=sharing) 
[npm_run_build_app_error](https://drive.google.com/file/d/1FaNLeLrCKkQudJQU4GQrT9VslMyUZLo-/view?usp=sharing)


> Modify the file directly from github and them submit it as PR :)

Hi MikeZeDev,

I'll do it, but if it affects any coding integrity of the main software please reject it, I don't wanna mess with it, as it is is one of the best comic downloader I've seen in my life. [](url)

**Comment by MikeZeDev** [comment]
> I'll do it, but if it affects any coding integrity of the main software please reject it, I don't wanna mess with it, as it is is one of the best comic downloader I've seen in my life.

Modifying a single MJS file from a connector shouldn't mess anything. We are here to make sure it doesnt anyway, and this is why Pull Requests and Reviews are for ^^

Its a safe process.

**Comment by subhajit-001** [comment]
> Previously, we have to paste only the comics URL from 8muses which contain pictures. After my code changes. it is successfully, fetching all the comics from a album URL.

Thanks for the info. I have done a pull request, please review and accepts changes when you have free time.

**Comment by subhajit-001** [comment]
Also, can you help me with how to create  hakuneko setup file from its source code, just to enrich my knowledge.

**Comment by Sheepux** [comment]
if you read trhe error messages carefully : install inosetup & vscode

**Comment by subhajit-001** [comment]
> if you read trhe error messages carefully : install inosetup & vscode

I've installed both. But still getting error. Don't know what I'm doing wrong.

**Comment by MikeZeDev** [comment]
Issues are not the appropriate place to discuss node, vscode, and trouble installing dev tools 📦 

You may ask on discord for that ^^
