### ISSUE TITLE
[toonily.com] Connector not working

### ISSUE THREAD

**Issue by Techzise** [manga-download/hakuneko#5713]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

toonily.com
Warning Your browser is out of date!
Update your browser to view this website correctly. [More Information.](https://developers.cloudflare.com/fundamentals/get-started/concepts/cloudflare-challenges/#browser-support)

**To Reproduce**
1. toonily.com
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. toonily.com
Warning Your browser is out of date!
Update your browser to view this website correctly. [More Information.](https://developers.cloudflare.com/fundamentals/get-started/concepts/cloudflare-challenges/#browser-support)
![zzzzz](https://user-images.githubusercontent.com/131561741/233811625-36763046-d7f5-4f68-80e4-272a088a5278.png)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cant fix

**Comment by MikeZeDev** [comment]
The cloudflare block was removed but to download picture we now need a referrer fix
