### ISSUE TITLE
[Sushi Scans] Connector not working

### ISSUE THREAD

**Issue by lulux82** [manga-download/hakuneko#5722]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the connector does not display the manga list, even after updating the connector

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.17
![Capture d’écran 2023-04-24 204408](https://user-images.githubusercontent.com/131707268/234087387-8cb7ce5f-394d-4a75-bc8b-bc2b9fcb00c6.jpg)
![Capture d’écran 2023-04-24 204536](https://user-images.githubusercontent.com/131707268/234087750-724ba0f2-16b7-4b1d-89b4-b6e2448932c4.jpg)

**Comment by MikeZeDev** [comment]
We know. Search before posting new issue pls.

https://github.com/manga-download/hakuneko/issues/5615
