### ISSUE TITLE
[Site Request] Siren Komik

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5724]
**Name of the website**
Siren Komik

**Website urls (examples below)**
- Site: https://sirenkomik.my.id/
- Manga List: https://sirenkomik.my.id/manga/
- Manga example: https://sirenkomik.my.id/manga/blend-s/
- Chapter online viewer example: https://sirenkomik.my.id/2023/04/20/blend-s-chapter-85/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Sweet another mangastream
