### ISSUE TITLE
[Site Request] Young Champion Web

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#5726]
**Name of the website**
Young Champion Web

**Website urls (examples below)**
- Site: https://youngchampion.jp/
- Manga List: https://youngchampion.jp/series/list
- Manga example: https://youngchampion.jp/series/d2adaa2d5246f
- Chapter online viewer example: https://youngchampion.jp/episodes/61694cd903f3d

**Languages**
Japanese

**Additional details**
This site use viewer same as Yanmaga (https://yanmaga.jp/) and Young Animal Web (https://younganimal.com/) (#5556 ).
Also have gravure idol photo gallery in list, if really need manga only list you can access via [here](https://youngchampion.jp/category/manga).

**Comment by MikeZeDev** [comment]
Thanks to the Yanmaga hint, its indeed similar ^^. I got it working BUT (mangas AND gravure) i suspect it will need some tweaks, because api need a user-id, set to 0 for now. I wonder if a logged user got a different one. Care to help with purchased content or that user thing? Come discord

**Comment by sakuhanachan** [comment]
> api need a user-id, set to 0 for now. I wonder if a logged user got a different one.

It's got different id as logged user.
![image](https://user-images.githubusercontent.com/2475440/234484525-22d57ceb-5ba4-4d80-a442-758e72888abb.png)

**Comment by MikeZeDev** [comment]
Can you try this one pls? https://github.com/manga-download/hakuneko/blob/YoungChampion/src/web/mjs/connectors/YoungChampion.mjs

**Comment by sakuhanachan** [comment]
Tested, it's work on both free and paid content (I test on [this](https://youngchampion.jp/episodes/f480a6dd73c49) and [this](https://youngchampion.jp/episodes/a24f70d38d543) for paid content).
