### ISSUE TITLE
Site Request] KissAnime

### ISSUE THREAD

**Issue by ketblue** [manga-download/hakuneko#5727]
Name of the website
KissAnime

Website urls (examples below)

Site: https://kissanime.com.ru/kissanime.html
Manga List: https://kissanime.com.ru/AnimeListOnline
Manga example: https://kissanime.com.ru/Anime/Maicching-Machiko-Sensei/

Languages
English

**Comment by MikeZeDev** [comment]
Duplicate( ? ) https://github.com/manga-download/hakuneko/issues/3475

**Comment by ketblue** [comment]
Possibly sorry I think they changed the address again, but it is probably just a clone fo
