### ISSUE TITLE
[Site Request] GoGoAnime

### ISSUE THREAD

**Issue by ketblue** [manga-download/hakuneko#5728]
Name of the website
GoGo Anime

Website urls (examples below)

Site: https://gogoanime.llc
Manga List: https://gogoanime.llc/anime-list.html
Manga example: https://gogoanime.llc/category/kamen-rider-den-o-imagin-anime

Languages
English

**Comment by MikeZeDev** [comment]
Was it not already requested? it feels like a clone of something to me.
Ah, a Kiss** clone, again :/

**Comment by ketblue** [comment]
Sorry probably is, just getting around to really digging in to new sites and the like, also absolutely new to HakuNeko no idea really how to work yet, used wfdownlader before but now it is no go.

**Comment by MikeZeDev** [comment]
dead?
