### ISSUE TITLE
[To enhance the ZOOM option]

### ISSUE THREAD

**Issue by manikkuge-saumyadasa** [manga-download/hakuneko#5729]
**Is your feature request related to a problem? Please describe.**
It get frustrated when adjusting the zoom. It's like this... there is a optimum zoom for manhuwa right? But the problem is I can't get that  exact value because I can only switch between the set amount of values. Like 45% 60% 75% etc.

**Describe the solution you'd like**
It vould be great to have an additional option to just type or adjust the zoom as the user wants. As an example lets say 72%.. 36%.. 71%...

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 8.3.4] (Nightly)

**Additional context**
<img width="202" alt="wv" src="https://user-images.githubusercontent.com/110282720/234497250-2086bab8-81a7-428b-b8a9-56aa9d8fe41f.png">

A button like this for minor changes would be great. As an example the change done by them should be set to 1%. So we can adjust major changes with the existing function and the minor changes with the newly added button.

**Comment by Sheepux** [comment]
Zoom scenario covered by  #1859 (closing in favor of)
I've plan for it in [haruneko](https://github.com/manga-download/haruneko)
