### ISSUE TITLE
[Feature] option to ignore 404 errors

### ISSUE THREAD

**Issue by TristanWasTaken** [manga-download/hakuneko#5731]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a single image like the credit page is missing and the whole chapter download fails. I will have to get the chapter manually anyways.

**Describe the solution you'd like**
An option in the settings to ignore 404 errors and save the chapter anyways.

**Describe alternatives you've considered**
An "ignore errors" option when you retry to download a failed chapter.

**Context (please complete the following information):**
 - Version: 6.1.7

**Additional context**

**Comment by Sheepux** [comment]
added to haruneko's features tracking
