### ISSUE TITLE
[Leviatan Scans] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#5739]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Not connecting, updating the refresh removes all titles. Might have changed site format.

**To Reproduce**
1. Name of connector. -  Leviatan Scans                                                                                                                       2. Name of manga (if connector update is working) - NA
3. Name of chapter (if manga update is working) - NA
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
       first gave message stating "unable to fetch". now it simply removes all title and when you reopen              HakuNeko the list is there but same thing happens when refreshing again.
<img width="1117" alt="Screenshot 2023-04-27 at 6 12 38 PM" src="https://user-images.githubusercontent.com/70929406/235277121-41378110-d7c6-40c2-919a-872c0a8fd4c2.png">
<img width="1400" alt="Screenshot 2023-04-27 at 6 13 42 PM" src="https://user-images.githubusercontent.com/70929406/235277125-cd70474f-79f7-40b0-a99f-75eb43c01eeb.png">

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]8.3.5

**Comment by MikeZeDev** [comment]
Ah, nothing works now, isee.

**Comment by tsentered** [comment]
Sorry.

**Comment by MikeZeDev** [comment]
Dont be sorry ;).
Patch note : I had to use /ranking/ for manga list. If you miss a manga, use clipboard feature.

**Comment by tsentered** [comment]
Thank you.
