### ISSUE TITLE
HakuNeko 5.0.8 cannot load chapter lists from Manganel (manganelo.com.)

### ISSUE THREAD

**Issue by theenemy9** [manga-download/hakuneko#574]
Hi, I am using HakuNeko 5.0.8 64-bit on Fedora 29 (64-bit). I cannot download any new chapters of all mangas from Manganel (manganelo.com.)

![HakuNeko 2019-10-23 15-00-49](https://user-images.githubusercontent.com/56912217/67371489-a8fc6400-f5a6-11e9-8f70-d433040d0b98.png)

I have included a screenshot. Please help.

Thanks.

**Comment by 27136773** [comment]
See: #547
