### ISSUE TITLE
[Feature] Possibility to add labels to bookmarked manga

### ISSUE THREAD

**Issue by forestpas3** [manga-download/hakuneko#5746]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Users can create and add labels to bookmarked manga to categorize them 
Ex.: NSFW and SFW labels

**Describe alternatives you've considered**
Maybe download from same _connector_ to different folders

**Context (please complete the following information):**
 - Hakuneku rev. 6.1.7@debbcc

**Additional context**
Not a big deal if not implemented, just a suggestion.

**Comment by Sheepux** [comment]
I'll close that one in favor of https://github.com/manga-download/hakuneko/issues/1912
issue is tracked in the current WIP (haruneko)
https://github.com/manga-download/haruneko/issues/40
