### ISSUE TITLE
[manhwas.men] Connector not working

### ISSUE THREAD

**Issue by AbdullahBM-1419** [manga-download/hakuneko#5751]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

The application does not download or display the chapters and title lists + the process of updating lists fails every time.

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
It works for me. Manga , chapter which fail maybe?

**Comment by AbdullahBM-1419** [comment]
I tried the application on two different computers (desktop + laptop) Windows 11 Version 22H2 Build 22621.1105
with and without VPN and problem is in both of them. 
And It includes all titles... not just osaka.

![لقطة الشاشة 2023-05-01 152508](https://user-images.githubusercontent.com/109600427/235452890-037ed683-d013-4998-81df-1489acd5ea93.png)
![لقطة الشاشة 2023-05-01 152542](https://user-images.githubusercontent.com/109600427/235452906-fa261c2c-7ba5-4fe9-b47f-281c5cf50b83.png)
![لقطة الشاشة 2023-05-01 152632](https://user-images.githubusercontent.com/109600427/235452929-8243d48f-a599-4314-8666-2d9524cd7c94.png)

**Comment by MikeZeDev** [comment]
Use nightly there was a fix 2 weeks ago

**Comment by AbdullahBM-1419** [comment]
Seems to be working now... Thanks.
