### ISSUE TITLE
[Viz] Purchased Volumes download not working

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#5755]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the volumes download is broken. the titles dont get detected and navigating to manga page doesnt show the volume.
using nightly version of hakuneko

**Comment by MikeZeDev** [comment]
Is that a duplicate of https://github.com/manga-download/hakuneko/issues/5583 ?

**Comment by amit34521** [comment]
> Is that a duplicate of #5583 ?

nope. that one is different. based on what i see, the references for this have changed entirely. the getMangas itself is itself failing to detect the purchases. then there are other changes at get chapters too

**Comment by MikeZeDev** [comment]
Obviously in need for help to handle paid content. Free seems to works fine.

**Comment by MikeZeDev** [comment]
Does is works on nightly now that https://github.com/manga-download/hakuneko/pull/5776 is merged?

**Comment by amit34521** [comment]
> Does is works on nightly now that #5776 is merged?

it does. me and another friend using it
