### ISSUE TITLE
Omegascans list

### ISSUE THREAD

**Issue by Gwonhoozz** [manga-download/hakuneko#5756]
https://omegascans.org/series/fucked-the-world-tree

New manhwa won't get add into list

**Comment by MikeZeDev** [comment]
A fix is pending no need to open another issue

**Comment by MikeZeDev** [comment]
Use Copy paste feature for now, it works

**Comment by MikeZeDev** [comment]
api is fucked up, sometimes i got 20 manga, sometimes 44, sometimes 48 just by changin DAMN ORDER.

Just use clipboard if manga is missing 🤷

**Comment by Gwonhoozz** [comment]
> api is fucked up, sometimes i got 20 manga, sometimes 44, sometimes 48 just by changin DAMN ORDER.
> 
> Just use clipboard if manga is missing 🤷

What's that?

**Comment by MikeZeDev** [comment]
I explained that the API from the website is giving weird results. We use that to gather manga list. It means we miss manga.
Not a big problem as pasting manga url works.
