### ISSUE TITLE
[Site Request] tempestscans

### ISSUE THREAD

**Issue by Samsara-byte** [manga-download/hakuneko#5759]
**Name of the website**
tempestscans.com

**Website urls (examples below)**
- Site: https://tempestscans.com/
- Manga List: https://tempestscans.com/manga/
- Manga example: https://tempestscans.com/manga/bleach/
- Chapter online viewer example: https://tempestscans.com/bleach-1/

**Languages**
Turkish
**Website relationship*

**Additional details**

**Comment by MikeZeDev** [comment]
Mangastream

**Comment by Samsara-byte** [comment]
ı dont understand. will be add? or ı gave missing info

**Comment by MikeZeDev** [comment]
Dev note, dont worry. It means code would probably just be copy pasting (and testing of course)
