### ISSUE TITLE
[Site Request] buondua

### ISSUE THREAD

**Issue by scepticweeb** [manga-download/hakuneko#5767]
**Name of the website**
buondua

**Website urls (examples below)**
- Site: https://buondua.com
- Photoset collection : https://buondua.com/collection
- Photoset online viewer example: https://buondua.com/artgravia-vol-268-kang-in-kyung-%EA%B0%95%EC%9D%B8%EA%B2%BD-94-photos-22279

**Additional details**
This is not a manga/anime website but i just wanted to recommend in case you guys can add it. This website offers photosets of models mostly based in korea. It would be nice if the content was downloadable.

**Comment by MikeZeDev** [comment]
Sorry its a bit off topic website.
