### ISSUE TITLE
[Site Request] manga-scan

### ISSUE THREAD

**Issue by ballhardy95** [manga-download/hakuneko#5768]
**Name of the website**
manga-scan

**Website urls (examples below)**
- Site: https://manga-scan.ws/
- Manga List: 
- Manga example: 
- Chapter online viewer example: 

**Languages**
French

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Useless : all pictures comes from ScansMangas.me, already supported

![image](https://user-images.githubusercontent.com/10671518/236898906-ae178c81-51f6-436c-b439-8dd0210edb69.png)

**Comment by Ryuujitoraz** [comment]
> Useless : all pictures comes from ScansMangas.me, already supported
> 
> ![image](https://user-images.githubusercontent.com/10671518/236898906-ae178c81-51f6-436c-b439-8dd0210edb69.png)

Not real, I checked but "scansmangas" doesn't work on HaruNeko and I was looking for a manga called "Gleipnir" it's available on manga-scan but not on "scansmangas"

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/3c3b982a-af14-4e3b-bef2-4395eae92ddb)

And same for gleipnir.

![image](https://github.com/manga-download/hakuneko/assets/10671518/ea78e3a0-ab9c-46de-a001-865ac61df858)

And Website works

![image](https://github.com/manga-download/hakuneko/assets/10671518/51d66d54-7362-4ccd-84c6-c8cf4f174e3f)

**Comment by webrootpro** [comment]
not working friends

**Comment by webrootpro** [comment]
please addd this site https://manga-scan.ws/

**Comment by MikeZeDev** [comment]
> not working friends

Name manga and chapter that doesnt work because on my end, it works

![image](https://github.com/manga-download/hakuneko/assets/10671518/4737fa81-6d14-4dcb-a0b2-b87d613c85c3)

**Comment by webrootpro** [comment]
CAN show me how can i added a new site to program u have some experience in
progrmation
