### ISSUE TITLE
[Site Request] Noromax.my.id

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5769]
**Name of the website**
Noromax

**Website urls (examples below)**
- Site: https://noromax.my.id/
- Manga List: https://noromax.my.id/Komik/
- Manga example: https://noromax.my.id/Komik/all-hail-the-sect-leader-bahasa-indonesia/
- Chapter online viewer example: https://noromax.my.id/all-hail-the-sect-leader-chapter-233-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5695, and PR already opened
