### ISSUE TITLE
[Sushi Scans] Connector not working

### ISSUE THREAD

**Issue by Ryuujitoraz** [manga-download/hakuneko#5771]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It doesn't show any manga in the list but the site works perfectly on my browser

**To Reproduce**
1. Name of connector : Sushi Scans

**Screenshots**
![01](https://user-images.githubusercontent.com/132905023/236816791-a31ea5e1-2af8-464b-8e41-5f2a6ef6784c.png)
![02](https://user-images.githubusercontent.com/132905023/236816812-16daf9f5-ed30-442a-8776-da8052290354.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] : 6.1.7@debbcc

**Comment by Sheepux** [comment]
duplicate #5615
