### ISSUE TITLE
[FR-SCAN] Connector not working

### ISSUE THREAD

**Issue by Ryuujitoraz** [manga-download/hakuneko#5773]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It works on my browser but not in HaruNeko, I have an error when I try to update the manga list (see the screen)

**Screenshots**
![image](https://user-images.githubusercontent.com/132905023/236853360-22aa6f60-3ee0-41d8-8146-6e41c9086f74.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@debbcc

**Comment by MikeZeDev** [comment]
> Is the website of the connector working properly / are you able to see the manga within your browser
> Yes

I wonder how it can work for you, since website is dead? 

![image](https://user-images.githubusercontent.com/10671518/236897378-6af25acf-a1e0-4311-8691-357e1e31cc33.png)

Cant fix what is dead 🤷
