### ISSUE TITLE
[Site Request] Komik Realm

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5777]
**Name of the website**
Komikrealm

**Website urls (examples below)**
- Site: https://www.komikrealm.my.id/
- Manga List: https://www.komikrealm.my.id/p/komik-list.html
- Manga example:  https://www.komikrealm.my.id/2023/05/way-to-heaven.html
- Chapter online viewer example: https://www.komikrealm.my.id/2023/05/way-to-heaven-chapter-83.html

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5696

**Comment by MikeZeDev** [comment]
And multiplying the issues is pointless, website wont come faster you know.
