### ISSUE TITLE
[Site Request] INKR

### ISSUE THREAD

**Issue by zeoint** [manga-download/hakuneko#5778]
**Name of the website**
INKR

**Website urls (examples below)**
- Site: https://comics.inkr.com/
- Manga List: N/A
- Manga example: https://comics.inkr.com/title/472-the-devil-butler
- Chapter online viewer example: https://comics.inkr.com/title/472-the-devil-butler/chapter/16013-season-1-chapter-0

**Languages**
English

**Website relationship*
N/A

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3782. Please search before asking.

**Comment by zeoint** [comment]
> Please search before asking.

I apologize.
