### ISSUE TITLE
[Cosmic Scans] Connector not working

### ISSUE THREAD

**Issue by Steven-OConnell** [manga-download/hakuneko#5780]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Manga list fails to synchronize. When opening the website directly in HakuNeko I am presented with a CloudFlare page saying "Your browser is out of date!"

**To Reproduce**
1. Connector: Cosmic Scans
2. Attempt to synchronize manga list.

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/54165616/3c7e6934-0ff6-47dc-9c3c-74dbc805a1bf)

**HakuNeko (please complete the following information):**
 - Version: rev.master@b58672

**Comment by MikeZeDev** [comment]
Great, cant fix :/

**Comment by Steven-OConnell** [comment]
I noticed a similar issue was opened with Toonily #5713, is this an issue that we can expect to see on other sites as well that use a similar setup?

**Comment by MikeZeDev** [comment]
Yeah. Toonily dropped the blocking one for a simple referrer control. Which is fixable.
The "older browser issue" isnt fixable on Hakuneko end without breaking Hakuneko.

So, we are working on [Haruneko](https://github.com/manga-download/haruneko/)

**Comment by MikeZeDev** [comment]
Fixed itself
