### ISSUE TITLE
[Reaper Scans] Connector not working

### ISSUE THREAD

**Issue by Steven-OConnell** [manga-download/hakuneko#5781]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
While the connector *mostly* works correctly any entry with a large amount of chapters (I don't know how many exactly) will fail to generate a Chapter List due to a HTTP 429 error.
Seems like they are rate limiting requests pretty heavily.

I ran into the same issue using "Manga Downloader" by Red Squirrel, you can see the issue here: [https://github.com/RedSquirrel87/manga-downloader/issues/768](https://github.com/RedSquirrel87/manga-downloader/issues/768)

**To Reproduce**
1. Connector: Reaper Scans
2. Name of manga: [Demonic Emperor](https://reaperscans.com/comics/4921-demonic-emperor)
3. Attempt to generate Chapter List

**HakuNeko (please complete the following information):**
 - Version: rev.master@b58672

**Comment by MikeZeDev** [comment]
Its a cloudflare problem 
![image](https://github.com/manga-download/hakuneko/assets/10671518/e8d60bcf-5dd6-43b9-8a18-2d631e997f6f)

As such, its a duplicate issue, and also cant be fixed.https://github.com/manga-download/hakuneko/issues/5488
