### ISSUE TITLE
[Hentaidexy] Domain change & no more madara

### ISSUE THREAD

**Issue by giaez** [manga-download/hakuneko#5783]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Domain of the website changed from hentaidexy.com to hentaidexy.net

**HakuNeko (please complete the following information):**
 - Nightly master@b58672

**Comment by MikeZeDev** [comment]
Okay, time to recode it all o_o
