### ISSUE TITLE
[Site Request] comic boost

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#5788]
**Name of the website**
comic boost

**Website urls (examples below)**
- Site: https://comic-boost.com/
- Manga List: https://comic-boost.com/genre/
- Manga example: https://comic-boost.com/content/01110001
- Chapter online viewer example: https://comic-boost.com/viewer/viewer.html?cid=1xyuZRBR4uNw%2F0g69pfNeAJyH8VW2GOmsQM6JnF81b3Gh5lGng0E9fuP6yn4JhJGsCbzLwBkphE%2FfJ4cPuG5m9%2BjDPCoI11%2F2TVwWaNSEl19svYl%2BivYgC5JBg4aWfPHs%2B%2FqEd5LHAopypZDswCTdQ%3D%3D&com-access-no-history

**Languages**
Japanese

**Website relationship*

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Its supported for 3 years already.

https://github.com/manga-download/hakuneko/blob/b586725306b68d26012e6a4bccd9163996256ea9/src/web/mjs/connectors/ComicBoost.mjs#L4
