### ISSUE TITLE
[ManHuaGui] Connector not working

### ISSUE THREAD

**Issue by linuxbelletian** [manga-download/hakuneko#5790]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
can't download specify chapter in the manga
**To Reproduce**
1. Name of connector: ManHuaGui
2. Name of manga (if connector update is working): 我的现实是恋爱游戏 link: https://www.manhuagui.com/comic/27586/
3. Name of chapter (if manga update is working): from "第12回"  to "第01回"
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)  : No Error Log

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="260" alt="Capture" src="https://github.com/manga-download/hakuneko/assets/8522288/0b34e2b3-7560-4a17-989a-e63101797b4e">
<img width="865" alt="Capture2" src="https://github.com/manga-download/hakuneko/assets/8522288/64036b13-8338-4e50-9a48-917d3be4fd49">

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by MikeZeDev** [comment]
Cant reproduce. As this site is known to ban ip (according to the code) maybe you are in this case.
