### ISSUE TITLE
[Feature] Option to view and download all chapters of titles marked as favorites

### ISSUE THREAD

**Issue by jhonatanDS** [manga-download/hakuneko#5793]
**Is your feature request related to a problem? Please describe.**
I have over 480 manga titles bookmarked and I find it time consuming to select one title at a time to check if new chapters are available and download.

**Describe the solution you'd like**
1 - Option to view which chapters have not yet been downloaded without having to select each title in the favorites;
2 - Allows you to download new chapters of all your favorites without having to keep selecting each title.

**Describe alternatives you've considered**
1 - Create a button that allows you to filter only the favorites that have new chapters (that have not yet been downloaded);
2 - Create a button that downloads the new chapters of all titles in the favorites.

**Context (please complete the following information):**
  6.1.7

**Comment by Sheepux** [comment]
New content detection is available in [haruneko ](https://github.com/manga-download/haruneko)(next HN version).
Mass download will not be implemented as it goes against hakuneko's policy.

>  The philosophy is ad-hoc consumption, get it when you want to read/watch it. It is not meant to be a mass downloader

I also have 500+ bookmarks, but i'm using the internal reader.
