### ISSUE TITLE
[yuri-ism] Connector not working

### ISSUE THREAD

**Issue by Pandacat-sudoer** [manga-download/hakuneko#5795]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No, I'm using the source code instead 

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
yuri-ism.net moved to yuri-ism.com

**To Reproduce**
1. Yuriism
2. It says connector not found when try to fetch, and then I check the web that it's moved
**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by Pandacat-sudoer** [comment]
Please change the hakuneko/web/mjs/connectors/YuriISM.mjs
By this line :
```javascript
this.url = 'https://www.yuri-ism.com';
```

**Comment by MikeZeDev** [comment]
Ok. Next time can you please mention in issue title that is a simple url change? Thanks :)

**Comment by MikeZeDev** [comment]
Ah. but "reader" is on Dynasty scan now, what a mess. Closing this issue, use "DynastyScans" instead
