### ISSUE TITLE
[MangaHub.io] Connector not working

### ISSUE THREAD

**Issue by manikkuge-saumyadasa** [manga-download/hakuneko#5805]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector : MangaHub.io
2. Name of manga (if connector update is working) : All Manga
3. Name of chapter (if manga update is working) : All Chapters
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : MangaHub errors: API rate limit excessed! Go to mangahub.io to continue reading!

**Screenshots**
<img width="1792" alt="Screenshot 2023-05-18 at 08 15 20" src="https://github.com/manga-download/hakuneko/assets/110282720/6aeba3d3-5b2d-46c6-8dee-ed69ed1cbfe2">

**HakuNeko (please complete the following information):**
 - Version [8.3.4]

**Comment by MikeZeDev** [comment]
Hu? wasn't it fixed by https://github.com/manga-download/hakuneko/pull/5791?

**Comment by manikkuge-saumyadasa** [comment]
> Hu? wasn't it fixed by #5791?

It was fixed very recently, But it came up again.
