### ISSUE TITLE
[Site request] Souls Scans

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5806]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
 https://soulscans.my.id/ new

**To Reproduce**
1. komiklab
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
You could have mentioned that in the already opened issue :)

**Comment by MikeZeDev** [comment]
Its a new website.

**Comment by Frezian** [comment]
when added?

**Comment by Frezian** [comment]
when will this site be added?

**Comment by MikeZeDev** [comment]
When someone wants to do it.
