### ISSUE TITLE
Know how many chapters you don't have read since last time 

### ISSUE THREAD

**Issue by Romain-12** [manga-download/hakuneko#5807]
**Is your feature request related to a problem? Please describe.**
Its really long when you have a lot to read to know what u need to read in the manga list

**Describe the solution you'd like**
what i suggest is to know how many chapiter we dont have read since the "recentely read"

i dev a little but i clearly dont have the patience to look how the app work to make it myself.

For the devs who know where you can fetch the chapter and the chapter with "recently read" in the app just look the diference between the recently read and the last if there is a difference u can display manga like this:

Solo Leveling (2).

that just a exemple to understand what i wanted to do, i hope u can understand how much that can improve the app.
Thanks a lot to the one who will make it.

If u want to talk about it im on discord Romain12#2748

**Comment by Sheepux** [comment]
duplicate #653 already implemented in haruneko https://github.com/manga-download/haruneko/issues/41
