### ISSUE TITLE
[https://manhuaplus.com/ Connector not working

### ISSUE THREAD

**Issue by bachdesign** [manga-download/hakuneko#5808]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by bachdesign** [comment]
many pages can't load
https://manhuaplus.com/

**Comment by MikeZeDev** [comment]
Errors not clear.
I see we cant fetch manga list but old list still work

**Comment by bachdesign** [comment]
I understand it's on the list, but it doesn't show the list of stories.  
![270](https://github.com/manga-download/hakuneko/assets/23213041/f73976d6-a801-4e7d-b131-dfaca171f63e)
