### ISSUE TITLE
[Site Request] Mangageko

### ISSUE THREAD

**Issue by thegoldenboy542** [manga-download/hakuneko#5809]
**Name of the website**
mangageko.com

**Website urls (examples below)**
- Site: https://www.mangageko.com
- Manga List: https://www.mangageko.com/browse-comics/
- Manga example: https://www.mangageko.com/manga/asura-s-wrath-kai/
- Chapter online viewer example: https://www.mangageko.com/reader/en/asura-s-wrath-chapter-1-eng-li/

**Languages**
English

**Comment by MikeZeDev** [comment]
Its supported but as "Mangarawclub". The url was mreader.co, and mreader.co redirect to mangageko.com.

gotta change url i guess

**Comment by thegoldenboy542** [comment]
Um I ran into another issue, when I use mangarawclub for some reason Asura's Wrath Kai doesn't show up in the search bar, copying the URL from the webpage doesn't work either, should I open another issue?

**Comment by MikeZeDev** [comment]
Manga url? Because website search doesnt show it too

![image](https://github.com/manga-download/hakuneko/assets/10671518/056f003d-c39d-42cf-9f26-5f5a674ef2dd)

**Comment by thegoldenboy542** [comment]
Here's the link: https://www.mangageko.com/manga/asura-s-wrath-kai/ 

Also your searching azura, their's no z its a s, that's why its not showing up...

**Comment by MikeZeDev** [comment]
You tested when the fix is not available yet, ofc it wont work 🤣 . It works for me.
Download Nightly version to get it faster and wait for it to be pushed.
