### ISSUE TITLE
mangaspark Connector not working

### ISSUE THREAD

**Issue by satyogi** [manga-download/hakuneko#5810]
https://mangaspark.com/5
stop working today

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/7e193fb0-e7aa-433b-bd7d-fa410e272b2d)
Cant fix

**Comment by satyogi** [comment]
but the website is working

**Comment by MikeZeDev** [comment]
There are ton of website with this problem, if we said we cant fix, we cant fix. Cf is a plague,

**Comment by MikeZeDev** [comment]
website down
