### ISSUE TITLE
[Site Request] Soul Scans

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5812]
**Name of the website**
Soul Scans

**Website urls (examples below)**
- Site: https://soulscans.my.id/
- Manga List: https://soulscans.my.id/manga/
- Manga example: https://soulscans.my.id/manga/since-the-red-moon-appeared/
- Chapter online viewer example: https://soulscans.my.id/since-the-red-moon-appeared-chapter-53/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Its komiklab who changed name . Issue is already opened and fix is already ready.  https://github.com/manga-download/hakuneko/pull/5801

**Comment by Frezian** [comment]
komiklab.com for english translation, soulscans.my.id for indonesian translation.. please help

**Comment by MikeZeDev** [comment]
crap, yesterday it was redirected

**Comment by MikeZeDev** [comment]
But we have komiklab.net, i am confused there is no mention of a soulscan website

![image](https://github.com/manga-download/hakuneko/assets/10671518/d05372ee-0cec-4f66-b99f-42100b712dc2)

**Comment by MikeZeDev** [comment]
Closed because its a duplicate, then :)

https://github.com/manga-download/hakuneko/issues/5806

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/5806 duplicate
