### ISSUE TITLE
[FusionScanlation] website is dead

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5813]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Screenshots**
![imagen](https://github.com/manga-download/hakuneko/assets/65477084/bb90fcfb-1ad8-4c6d-825e-9033d3fb77df)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Thanks a lot : Please report dead website in the pinned issue instead :) 
https://github.com/manga-download/hakuneko/issues/4972
