### ISSUE TITLE
[HFusionScanlation] website is dead

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5814]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Screenshots**
![imagen](https://github.com/manga-download/hakuneko/assets/65477084/d6d2f05f-a66f-4bab-bd76-9bca8e17c6a7)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Thanks a lot : Please report dead website in the pinned issue instead :) 
https://github.com/manga-download/hakuneko/issues/4972
