### ISSUE TITLE
[Site Request] Templescan

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5815]
**Name of the website**
Templescan

**Website urls (examples below)**
- Site: https://templescan.net/
- Manga List: https://templescan.net/comic/
- Manga example: https://templescan.net/comic/death-when-separated/
- Chapter online viewer example: https://templescan.net/comic/death-when-separated/chapter-1/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara
