### ISSUE TITLE
[Bilibili Comics] Connector not working

### ISSUE THREAD

**Issue by omodia** [manga-download/hakuneko#5816]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloads are not working.

**To Reproduce**
1. Bilibili Comics
2. Any manga.
3. Any Chapter.
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**

**HakuNeko (please complete the following information):**

**Comment by MikeZeDev** [comment]
Unfortunately, i think a protocol error is beyond what we can fix i think. At least beyond my understanding.

**Comment by omodia** [comment]
Okay. If you find a way in the future, then please do fix it.
Thank you.

**Comment by MikeZeDev** [comment]
If you look for this error on the internet, its very often a problem on server end. :/

**Comment by omodia** [comment]
I checked it again, now the downloads are working. As you said, the problem must be on their server end.

**Comment by omodia** [comment]
Thank you for searching a way to fix this.
