### ISSUE TITLE
[Site Request] Soul Scans

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5823]
**Name of the website**
SoulScans

**Website urls (examples below)**
- Site: https://soulscans.my.id/
- Manga List: https://soulscans.my.id/manga/
- Manga example: https://soulscans.my.id/manga/cultivation-return-on-campus/
- Chapter online viewer example:https://soulscans.my.id/cultivation-return-on-campus-chapter-439/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
It turns out that this is a new website, and the correct Komiklab site is Komiklab.net, I'm sorry

**Comment by Frezian** [comment]
It turns out that this is a new website, and the correct Komiklab site is Komiklab.net, I'm sorry

**Comment by MikeZeDev** [comment]
Duplicate  https://github.com/manga-download/hakuneko/issues/5806
