### ISSUE TITLE
[Painfulnightz] Connector not working

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5825]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
YES

**Describe the bug**
The episodes are not being displayed

**To Reproduce**
1. Painfulnightz
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Connector.mjs:434 POST https://painfulnightz.com/wp-admin/admin-ajax.php 403

**Screenshots**
![imagen](https://github.com/manga-download/hakuneko/assets/65477084/3e11a59b-a8ba-4665-8218-f1f4eb7d8c32)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
website down
