### ISSUE TITLE
[Muctau] Url change

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5826]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector url has changed.
The new URL should be "https://bibimanga.com/"

**To Reproduce**
1. Name of connector - Muctau
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Can you check before opening an issue please?  This has been fixed in january

https://github.com/manga-download/hakuneko/blob/88400ae5cdc3bac79af5e1e2af66ad97ca81fe06/src/web/mjs/connectors/muctau.mjs#L10
