### ISSUE TITLE
[Site Request] Readmangafree

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5828]
**Name of the website**
readmangafree

**Website urls (examples below)**
- Site: https://readmangafree.net/
- Manga List: https://readmangafree.net/manga/
- Manga example: https://readmangafree.net/manga/the-weight-of-our-sky/
- Chapter online viewer example: https://readmangafree.net/manga/the-weight-of-our-sky/ep-11/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara template.

**Comment by Lenoyr** [comment]
Website is dead
