### ISSUE TITLE
readmng.com not showing chapters of some titles

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#583]
> **From:** HakuNeko User

Site works and all chapters on site showing but not some don't show up on HakuNeko. Sometimes the problem use to resolve itself restarting Haku but more and more this is working less and less. I'm a mac user.

Thanks.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Please provide additional info such as which manga/chapter is affected.

If a website changes the URL path of certain mangas, the manga list needs to be updated to get the new paths. Furthermore, affected bookmarks will also stop working and needs to be re-added.

**Comment by 27136773** [comment]
There is nothing that can be done in HakuNeko to adapt manga links when a websites changes them...
