### ISSUE TITLE
[Cloudflare] Update Electron to fix Cloudflare

### ISSUE THREAD

**Issue by Euphillya** [manga-download/hakuneko#5832]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
There have been a lot of bug reports with Cloudflare that the browser is obsolete. The Electron v24.3.1 version allows to go on sites with Cloudflare, so it is necessary to update from the version 8 which is more than obsolete to this one.

**To Reproduce**
#5615 #4292 #5780 (all cloudflare...)

**Expected behavior**
Update Electron

**Screenshots**

**Context (please complete the following information):**
 - OS: Windows 11
![image](https://github.com/manga-download/hakuneko/assets/26461373/33f44d71-72bc-4634-82c2-c7a06191bc87)
![image](https://github.com/manga-download/hakuneko/assets/26461373/8131d701-5cc0-492b-863c-69ed8a0add8b)
![image](https://github.com/manga-download/hakuneko/assets/26461373/f5dfc980-7da7-433e-baed-a1affb173080)
![image](https://github.com/manga-download/hakuneko/assets/26461373/207aba53-efb3-493e-8ab2-a71430d27d6f)

**Comment by samanta-widjaja** [comment]
don't get your hope up though. there solution by isyfalana in https://github.com/manga-download/hakuneko/issues/2933. it's working though

**Comment by MikeZeDev** [comment]
This wont happend, as its breaking so much stuff in Hakuneko.  We keep working on HN successor for a while because of this now.
https://github.com/manga-download/haruneko/
