### ISSUE TITLE
[Site Request] inkr

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5834]
**Name of the website**
inkr

**Website urls (examples below)**
- Site: https://comics.inkr.com/
- Manga List: none
- Manga example: https://comics.inkr.com/title/478-the-boss-s-shotgun-wedding?ref=section_daily_updates_home
- Chapter online viewer example: https://comics.inkr.com/title/478-the-boss-s-shotgun-wedding/chapter/16045-chapter-1

**Languages**
engilsh

**Website relationship*
none

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3782

**Comment by ghost** [comment]
Apolpgies, i new here. Did not know there is request already.
