### ISSUE TITLE
[TruyenQQ] Connector not working

### ISSUE THREAD

**Issue by egnaro1007** [manga-download/hakuneko#5844]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Change URL of TruyenQQ

**To Reproduce**
TruyenQQ has change their url from truyenqqvip.com to truyenqqne.com

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Those damn VN websites that keep changing URL every week 😭 

I'll do it

**Comment by MikeZeDev** [comment]
Cloudflare
