### ISSUE TITLE
[Site Request] https://newtoki291.com/

### ISSUE THREAD

**Issue by holychristmas** [manga-download/hakuneko#5846]
**Name of the website**
newtoki291

**Website urls (examples below)**
- Site: https://newtoki291.com/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
korean

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already supported ![image](https://github.com/manga-download/hakuneko/assets/10671518/4177dd8c-9cde-42dd-83c6-d0dbed5cef77)
