### ISSUE TITLE
[Site Request] AinzScans

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5848]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://ainzscans.site/
- Manga List: https://ainzscans.site/series/
- Manga example: https://ainzscans.site/series/infinite-leveling-up-in-murim/
- Chapter online viewer example: https://ainzscans.site/infinite-level-up-in-murim-chapter-30-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already supported. https://github.com/manga-download/hakuneko/blob/199aef7ebd06909b09ce950d02005bdf63b11c98/src/web/mjs/connectors/Ainzscans.mjs#L4

Like you where already told many times, please, search before asking. Or maybe i am wrong and its different 🤷 

It may require updating but in this case feel free to open a "website change" issue and not a "website suggestion" issue.

Thanks, have a nice day.
