### ISSUE TITLE
[newtoki291.com] Connector not working

### ISSUE THREAD

**Issue by holychristmas** [manga-download/hakuneko#5851]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
II put in the url and nothing pops up for chapters

**To Reproduce**
1. Name of connector https://newtoki291.com/webtoon/47504/%EB%A1%AD%ED%94%8C%EB%A1%AD-Loplop?stx=%EB%A1%AD%ED%94%8C%EB%A1%AD
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cant reproduce . On nightly

![image](https://github.com/manga-download/hakuneko/assets/10671518/f466a173-fc4f-4d72-9fc2-80c7ad63de97)

**Comment by MikeZeDev** [comment]
Did you change newtoki domain in settings?

**Comment by MikeZeDev** [comment]
Using the good domain in Hakuneko settings and pasting your link i cant reproduce the error.
Please do the same and if the error persist feel free to reopen this ticket :)
