### ISSUE TITLE
[NameOfConnector] Change Domain Ainz Scans

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5860]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The "click to paste" option doesn't work because the domine change from [www.ainzscans.my.id](http://www.ainzscans.my.id/) to [www.ainzscans.site](https://www.ainzscans.site/)

**To Reproduce**
1. Name of connector [Ainz Scans]
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
They use Mangastream now <3
