### ISSUE TITLE
[Nettruyen] Connector not working

### ISSUE THREAD

**Issue by tuanhobbit123** [manga-download/hakuneko#5861]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connector change the domain

**To Reproduce**
1. Nettruyen
2. ONE PUNCH MAN
3. https://www.nettruyenplus.com/truyen-tranh/anh-hung-onepunch/chap-231/993540
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![Capture1](https://github.com/manga-download/hakuneko/assets/99427505/03421f8b-6a98-44c1-bfc5-02f059f64dc9)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Its already Nettruyenplus? 
![image](https://github.com/manga-download/hakuneko/assets/10671518/992630e5-6b7e-48c8-989b-e933bf97f98d)

Just use Nightly version
