### ISSUE TITLE
[Site Request] bigcomics.jp

### ISSUE THREAD

**Issue by AsHBySLd** [manga-download/hakuneko#5863]
**Name of the website**
BigComics

**Website urls (examples below)**
- Site: https://bigcomics.jp/
- Manga List: https://bigcomics.jp/series/list
- Manga example: https://bigcomics.jp/series/4a917e09503ce
- Chapter online viewer example: https://bigcomics.jp/episodes/5664113d6d6ea

**Languages**
Japanese

**Additional details**
The site has DRM protection.

**Comment by AsHBySLd** [comment]
Can this site appear in HakuNeko?

**Comment by MikeZeDev** [comment]
"comici" references like Yanmaga, YoungChampion if someone want to try, it could be similar.
Edit : in fact its identical lmao
