### ISSUE TITLE
[LilyManga.net] Connector not working

### ISSUE THREAD

**Issue by EldritchPandora** [manga-download/hakuneko#5868]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
the url https://lilymanga.net works

**Describe the bug**
Can't connect to the website LilyManga , load manga list or chapters since the website return online with a cloudflare captcha

**To Reproduce**

when trying to reaload the list i got the following:

POST http://lilymanga.net/wp-admin/admin-ajax.php 403 Connector.mjs:434
fetchDOM @ Connector.mjs:434
_getMangasFromPage  @ WordPressMadara.mjs:52
_getMangas  @ WordPressMadara.mjs:44
_getMangaList  @ Connector.mjs:576
(anonymous)  @ Connector.mjs:99
Promise.then (async)  
updateMangas  @ Connector.mjs:98
onUpdateMangaListClick  @ mangas.html:233
handler  @ template-stamp.html:96
![screen 1](https://github.com/manga-download/hakuneko/assets/135387194/eaa7343e-bf6a-4f7c-bfd7-5a7c69659c47)

when trying to access a manga of this website in my bookmarks i got the following:

GET https://lilimanga.net/ys/mage-demon-queen/ 403 Connector.mjs:434
fetchDOM  @ Connector.mjs:434
_getChapters  @ WordPressMadara.mjs:93
_getChapterList  @ Connector.mjs:595
(anonymous)  @ Manga.mjs:134
(anonymous)  @ Manga.mjs:133
Promise.then (async)
_getUpdatedChaptersFromWebsite  @ Manga.mjs:132
(anonymous) @ Manga.mjs:98
Promise.then (async)  
getChapters  @ Manga.mjs:94
onSelectedMangaChanged  @ chapters.html:244
runObserverEffect  @ property-effects.html:217
runEffectsForProperty  @ property-effects.html:162
runEffects  @ property-effects.html:128
_propertiesChanged  @ property-effects.html:1662
_flushProperties  @ properties-changed.html:341
_flushProperties  @ property-effects.html:1510
__enableOrFlushClients  @ property-effects.html:1555
_flushClients  @ property-effects.html:1530
_propertiesChanged  @ property-effects.html:1658
_flushProperties  @ properties-changed.html:341
_flushProperties  @ property-effects.html:1510
_invalidateProperties  @ property-effects.html:1482
runNotifyEffects  @ property-effects.html:261
_propertiesChanged  @ property-effects.html:1665
_flushProperties  @ properties-changed.html:341
_flushProperties  @ property-effects.html:1510
_invalidateProperties  @ property-effects.html:1482
set | @ | property-effects.html:1817
onMangaClicked  @ mangas.html:263
handler  @ template-stamp.html:96
(anonymous) @ templatize.html:149

![screen 2](https://github.com/manga-download/hakuneko/assets/135387194/cd919e10-4097-4944-acc3-6ddb100da914)

**HakuNeko (please complete the following information):**
 - tested on rev. master@e073a1 after installing the nightly build

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/d535bcd3-36cc-45ef-9fad-cdc4ff5b14c0)

Cant fix

**Comment by MikeZeDev** [comment]
No more CF
