### ISSUE TITLE
[Site Request] Worldmanhwas

### ISSUE THREAD

**Issue by enjoeid** [manga-download/hakuneko#5869]
**Name of the website**
worldmanhwas

**Website urls**
- Site: https://worldmanhwas.in
- Manga List: https://worldmanhwas.info/all-mangas
- Manga : https://worldmanhwas.in/komik/the-bathhouse/
- Chapter online viewer : https://worldmanhwas.in/komik/the-bathhouse/chapter-1/

**Languages**
Indonesian

**Website relationship*
Nothing

**Additional details**
Template : Madara

**Comment by MikeZeDev** [comment]
> worldmanhwas.bar, and website is so slow that its unbearable.

**Comment by MikeZeDev** [comment]
Worldmanhwas.zone atm

**Comment by MikeZeDev** [comment]
dead
