### ISSUE TITLE
[Aresmanga] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5870]
Browser update pls
 - OS: Windows11
 - HakuNeko Version 6.17
 
![Capture d’écran 2023-06-03 120537](https://github.com/manga-download/hakuneko/assets/47768610/b9eb152e-4fa8-4cb0-93c7-94aa491ddc4a)
![Capture d’écran 2023-06-03 121115](https://github.com/manga-download/hakuneko/assets/47768610/5a9d6f7b-2ca3-4baf-9e01-19cdf5b3e78e)
![Capture d’écran 2023-06-03 121829](https://github.com/manga-download/hakuneko/assets/47768610/96f416de-47f9-495c-ad7e-482cbe21ba0a)

**Comment by MikeZeDev** [comment]
Sorry, cant fix. Next time please put website name in title.

**Comment by ghost** [comment]
okay np

The problem is caused by deleting the dns cache

**Comment by MikeZeDev** [comment]
> The problem is caused by deleting the dns cache

Nope i can tell you it has nothing todo with that :D

**Comment by ghost** [comment]
Some websites stop the captcha and show the message browser is not up to date
eg: https://mangalek.com/
Oh it's fixed
good XD

**Comment by MikeZeDev** [comment]
Is useless to mention another site having the same cloudflare issue, it wont help, unfortunately.

**Comment by MikeZeDev** [comment]
Fixed by itself
