### ISSUE TITLE
[Site Request] getsuaku.com

### ISSUE THREAD

**Issue by monnch** [manga-download/hakuneko#5871]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: getsuaku.com
- Manga List: https://getsuaku.com/series
- Manga example: https://getsuaku.com/episode/053_gaw_kamoisan-1
- Chapter online viewer example: https://getsuaku.com/episode/001_gaw_tsugumomo

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Speedbind

**Comment by MikeZeDev** [comment]
Merged with ComicAction
