### ISSUE TITLE
[YoungChampion] Connector not working

### ISSUE THREAD

**Issue by sm1thchr1s** [manga-download/hakuneko#5872]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to load resource: the server responded with a status of 404 ()
https://youngchampion.jp/episodes/87f39f07bad7e/list

**To Reproduce**
1. Copied a Young Champion link. (e.g. https://youngchampion.jp/episodes/87f39f07bad7e)
2. Wait for load.
3. Result: Failed to load resource: the server responded with a status of 404 ()

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/135480959/21f6241a-34cd-4ddc-8c8f-6c3f6c13c5c3)
Take note that the website is not down:
![image](https://github.com/manga-download/hakuneko/assets/135480959/d6274cb7-eb37-4db4-8f42-8f1180d082e3)

**HakuNeko (please complete the following information):**
 - Version 8.3.4

**Comment by MikeZeDev** [comment]
FYI 404 means ressource not found, not website down :D. Anyway, gotta check tha

**Comment by MikeZeDev** [comment]
You pasted the link to a chapter . See there is a reader on it? 
You need to past a manga list not a chapter link.

Bad : h--ps://youngchampion.jp/episodes/87f39f07bad7e
Good : h--ps://youngchampion.jp/series/c01e4ebf86e9b

Manga list is here btw, its being added in next update /series/list
