### ISSUE TITLE
[ReaperScans] Connector not working

### ISSUE THREAD

**Issue by bboymo** [manga-download/hakuneko#5873]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Says the manga list is loading or empty. Icon did not spin at all after first initiation and said list is empty everytime.

**To Reproduce**
1. Reaper Scans
2. Overgeared (if connector update is working)
3. All of them (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5488. Please search before posting next time :)
