### ISSUE TITLE
[Site Request] HyoManga ID

### ISSUE THREAD

**Issue by Haiyoe** [manga-download/hakuneko#5879]
**Name of the website**
thewebsitename

**Website urls**
- Site: https://hyomanga.my.id/
- Manga List: https://hyomanga.my.id/search/label/Manga
- Manga example: https://hyomanga.my.id/2023/05/solo-leveling.html
- Chapter online viewer example: https://hyomanga.my.id/2023/03/chapter-1.html

**Languages**
Indonesian

**Additional details**
The site runs on blogger, and uses the ZeistManga V4 template by EmissionHex

**Comment by MikeZeDev** [comment]
Dev note : ZeistManga /Kumareader /Blogger. We already have websites using that, maybe its worth doing a template?

**Comment by MikeZeDev** [comment]
dead
