### ISSUE TITLE
[Newtoki] Not Working/Change Domain

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5880]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The "click to paste" option doesn't work because the domine change to [www.newtoki291.com](https://www.newtoki291.com/)
**To Reproduce**
1. Name of connector [Newtoki]
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
cant reproduce. Launched Haku, pasted https://newtoki291.com/webtoon/17652318/10%EB%A7%8C-%EB%85%84%EC%A7%B8-%EC%98%A4%EB%8A%98%EC%9D%84-%EC%82%B4%EB%8D%98-%EB%86%88 and it works.

![image](https://github.com/manga-download/hakuneko/assets/10671518/b56de8fb-3b62-49bb-9d2d-575dd8dc7712)

You can change NT domain settings.
![image](https://github.com/manga-download/hakuneko/assets/10671518/1ffbb8ac-b5b3-4694-874d-839eb242f13b)

**Comment by MikeZeDev** [comment]
Using the good domain in Hakuneko settings and pasting your link i cant reproduce the error.
Please do the same and if the error persist feel free to reopen this ticket :)

**Comment by GuPuSi7ff** [comment]
The old address doesn’t work now.
[newtoki.mom](https://newtoki.mom/) works.

**Comment by MikeZeDev** [comment]
1) Dont bump old closed issues 

2) > The old address doesn’t work now. [newtoki.mom](https://newtoki.mom/) works.

There is no manga here. So this is useless.

3) Stop losing your time => use Haruneko. Because this website got CLOUDFLARE and CAPTCHAS
