### ISSUE TITLE
[Feature] Pacstall package

### ISSUE THREAD

**Issue by Diegiwg** [manga-download/hakuneko#5881]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing pull request to add [hakuneko-deb](https://github.com/pacstall/pacstall-programs/pull/3657) to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for hakuneko-deb for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by MikeZeDev** [comment]
Hi, let me quote Ronny, the lead dev : 

> My opinion:
> If they want to work on support for other package repositories they are welcome.
> HakuNeko contributors probably don't have the resources to maintain all these packages out in the wild, so it will likely not receive support from dedicated HakuNeko contributors.
> => https://hub.docker.com/search?q=hakuneko
> => https://aur.archlinux.org/packages/hakuneko-desktop
> => https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HakuNeko/HakuNeko 
> It should not be listed on HakuNeko official websites as it could be mistaken that HakuNeko contributors are maintaining these packages.

From what he said i can infer there is no problem. :)

**Comment by Sheepux** [comment]
If we were to go to a more generic packaging, I'd invest time to work on flatpak
