### ISSUE TITLE
[Site Request] Suchi-scan

### ISSUE THREAD

**Issue by DrKami047** [manga-download/hakuneko#5883]
Name of the site : Sushi-scan

- Site: https://sushiscan.net/
- Manga List: https://sushiscan.net/manga/
- Manga example: https://sushiscan.net/manga/pandora-hearts/
- Chapter online viewer example: http:\/\/sushiscan.net\/wp-content\/uploads4\/PandoraHeartsTome5-007.jpg

Languages : French

**Comment by MikeZeDev** [comment]
What? Website is supported since January 2022, come on.

https://github.com/manga-download/hakuneko/commit/ae242b1183ae8549849f4b826af55130b1dc255a

**Comment by MikeZeDev** [comment]
That said, it wont work https://github.com/manga-download/hakuneko/issues/5615
