### ISSUE TITLE
[Olympusscans] Website Change

### ISSUE THREAD

**Issue by ElijahS9** [manga-download/hakuneko#5884]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
It's not an error, it's more of a site change, they created another page and left the old one, if they could update it to the new website that would be great.
this is the old website--https://olympusscanlation.com/

**To Reproduce**
1. https://olympusscans.com/
2. https://olympusscans.com/series/comic-maldita-reencarnacion
3. https://olympusscans.com/capitulo/65603/comic-maldita-reencarnacion
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5517.
Please search before opening an issue.
