### ISSUE TITLE
[hiperdex] Domain website Change

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#5885]
**Describe the bug**
The url is change

**To Reproduce**
1. hiperdex
2. The url is change from https://1sthiperdex.com/ To Old domain https://hiperdex.com/

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Use hakuneko settings for hiperdex to choose url
