### ISSUE TITLE
[Cosmic Scans ID] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5886]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Cosmic Scans ID
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/112748173/d4eb4c1e-3844-4d77-8ccc-53bd33bcf7cb)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Duplicate and not fixable. Please search before asking.
https://github.com/manga-download/hakuneko/issues/5780
