### ISSUE TITLE
[Young Animal] Connector not working

### ISSUE THREAD

**Issue by arifsyahbani** [manga-download/hakuneko#5889]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Clipboard feature didn't work.

**To Reproduce**
1. Young Animal Web (https://younganimal.com/category/manga or https://younganimal.com/)
2. CHILDEATH (connector update isn't working)
3. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Error Messages:
CLIPBOARD: https://younganimal.com/series/48a9766a429a7 Error: No matching connector found for URL https://younganimal.com/series/48a9766a429a7
    at ClipboardConnector.mjs:59
    at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28)
    at HTMLElement.onUpdateMangaListClick (mangas.html:233)
    at HTMLElement.onPasteClick (mangas.html:339)
    at HTMLElement.handler (template-stamp.html:96)

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/45502806/f1fe8a8d-58bb-46cb-a7cd-c0d87ea8c4bb)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment]
Of course it doesnt work, website isnt supported, nothing has been coded, no one requested it. It wont magically work by itself :D

![image](https://github.com/manga-download/hakuneko/assets/10671518/7b53e7f1-a02e-41eb-8d62-c5fad5a9280f)
