### ISSUE TITLE
[Coloredmanga] Connector not working

### ISSUE THREAD

**Issue by aihooo444** [manga-download/hakuneko#5890]
Can no longer refresh colored manga after pushing F12 to check what is going on this is the info that I get:

Fatal error: Uncaught TypeError: strlen(): Argument #1 ($string) must be of type string, array given in /home/coloredmanga/htdocs/coloredmanga.com/wp-content/plugins/madara-shortcodes/.50c5c42a.inc(63) : eval()'d code:4 Stack trace: #0 /home/coloredmanga/htdocs/coloredmanga.com/wp-content/plugins/madara-shortcodes/.50c5c42a.inc(63) : eval()'d code(4): xyxggy() #1 /home/coloredmanga/htdocs/coloredmanga.com/wp-content/plugins/madara-shortcodes/.50c5c42a.inc(63): eval() #2 /home/coloredmanga/htdocs/coloredmanga.com/wp-config.php(4): include('...') #3 /home/coloredmanga/htdocs/coloredmanga.com/wp-load.php(50): require_once('...') #4 /home/coloredmanga/htdocs/coloredmanga.com/wp-admin/admin-ajax.php(22): require_once('...') #5 {main} thrown in /home/coloredmanga/htdocs/coloredmanga.com/wp-content/plugins/madara-shortcodes/.50c5c42a.inc(63) : eval()'d code on line 4

**Comment by MikeZeDev** [comment]
Wordpress endoint is messed up. How weird :D

gotta list manga normally then
