### ISSUE TITLE
[Site Request] https://aniworld.to/

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5892]
**Name of the website**
[thewebsitename](https://aniworld.to/)

**Website urls (examples below)**
- Site: https://aniworld.to/
- Anime List: https://aniworld.to/animes
- Anime example: https://aniworld.to/anime/stream/100-sleeping-princes-the-kingdom-of-dreams

**Languages**
German, Subtitles German, Subtitle English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Links have same structure

https://aniworld.to/anime/stream/%NAME%/%STAFFEL%/%EPISODE%

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4984.

Please search before opening already existing issues.
