### ISSUE TITLE
new Chapter Notification [Feature]

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5893]
I often find it challenging to stay updated on the release of new chapters for my favorite manga or webcomics. It would be incredibly helpful to have a feature that notifies me whenever new chapters are available, ensuring that I never miss out on the latest content.

I would like to request the addition of a new feature in HakuNeko that provides notifications whenever new chapters are released for the manga or webcomics I follow. The feature should have the following functionality:

Automated Chapter Detection: The feature should automatically detect and monitor the bookmarked manga or webcomics for new chapter releases.

Notification System: Whenever a new chapter is released for a selected manga or webcomic, a notification should be displayed to the user.

Describe alternatives you've considered
One alternative solution would be manually checking for updates by regularly visiting each manga or webcomic's website or using external services. However, this approach can be time-consuming and cumbersome, especially when following multiple titles.

Additional context
I believe this new feature will greatly enhance the user experience of HakuNeko and make it easier for manga and webcomic enthusiasts like myself to stay updated on new chapters. Thank you for considering my feature request, and I'm available for any further clarification or information if needed.

**Comment by Sheepux** [comment]
duplicate,  see the pinned issue : #653
