### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by libreidy** [manga-download/hakuneko#5895]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Not all titles are showing in the list

**To Reproduce**
1. Name of connector -  Newtoki292.com or manatoki292.net
2. Name of manga (if connector update is working) - 장송의 프리렌
3. Name of chapter (if manga update is working) -  Title of manga is not showing
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)  - Not just this but a lot of titles of different manga are not showing

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version 6.1.7@513508

**Comment by MikeZeDev** [comment]
> Not all titles are showing in the list

Use Clipboard feature in this case. Its not our fault if the list we get from the website is inaccurate.
