### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by webrootpro** [manga-download/hakuneko#5898]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**

**To Reproduce**
1. [Name of connector](https://manga-scan.ws/)
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Can you at least describe the problem?

**Comment by MikeZeDev** [comment]
Website is not supported. Then there is no bug to report .
