### ISSUE TITLE
Multiple

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#59]
> **From:** HakuNeko User

-readrawmanga.com isn't showing any title.
-The help feature seems to have changed and doesn't show the "development and other categories any more.

Thank you

**Comment by 27136773** [comment]
HakuNeko now uses GitHub's ticket system for support instead of the [SourceForge forum](https://sourceforge.net/p/hakuneko/discussion/)

**Comment by 27136773** [comment]
Handled by #62
