### ISSUE TITLE
[NetTruyen] Connector not working

### ISSUE THREAD

**Issue by TeddyTruong** [manga-download/hakuneko#5905]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The site has changed its URL from [nettruyenplus](https://www.nettruyenplus.com/) to [nettruyenio](https://www.nettruyenio.com/)

New website URLs

Site: https://www.nettruyenio.com/
Manga list: https://www.nettruyenio.com/tim-truyen
Manga example: https://www.nettruyenio.com/truyen-tranh/gto-shonan-14-days-23860
Chapter online viewer example: https://www.nettruyenio.com/truyen-tranh/gto-great-teacher-onizuka/chap-199/495772
Languages
Vietnamese

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by MikeZeDev** [comment]
For me its nettruyenmax, what a mess
