### ISSUE TITLE
[Sushi Scans] Connector not working

### ISSUE THREAD

**Issue by dunkmask2407** [manga-download/hakuneko#5906]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not possible to acces manga on this connector. This connector not work.

**To Reproduce**
1. Sushi Scans

**Screenshots**
![bugs5](https://github.com/manga-download/hakuneko/assets/116431676/8c428d1b-292d-4fb2-b50c-1e1e08626ffd)
![bugs1](https://github.com/manga-download/hakuneko/assets/116431676/f800d20b-f7a7-478b-8b92-a34c40de61c0)
![bugs2](https://github.com/manga-download/hakuneko/assets/116431676/640b0a12-2e6e-447b-991a-c596455f82ed)
![bugs3](https://github.com/manga-download/hakuneko/assets/116431676/66d205b9-9486-4e43-b6a7-63da635376da)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Duplicate. please search before asking.
https://github.com/manga-download/hakuneko/issues/5615
