### ISSUE TITLE
[MangaHasu] Connector not working

### ISSUE THREAD

**Issue by dunkmask2407** [manga-download/hakuneko#5907]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not possible to acces manga on this connector. This connector not work.

**To Reproduce**
1. MangaHasu

**Screenshots**
![bugs6](https://github.com/manga-download/hakuneko/assets/116431676/8319d9bd-382c-4be2-914c-e888de863862)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dunkmask2407** [comment]
![bugs6](https://github.com/manga-download/hakuneko/assets/116431676/d4f2dd36-218c-4d68-88f5-da08075c7cce)

**Comment by MikeZeDev** [comment]
Please stop highlighting this "warning", it just means you dont have a cached manga list for this website yet and its normal.

**Comment by MikeZeDev** [comment]
Also, website now (finally ) uses HTTPS, i fixed that 2 weeks ago, use nightly.
