### ISSUE TITLE
[SenManga] Connector not working

### ISSUE THREAD

**Issue by dunkmask2407** [manga-download/hakuneko#5909]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It's not possible to acces manga on this connector. This connector not work.

**To Reproduce**
1. SenManga

**Screenshots**
![bugs8](https://github.com/manga-download/hakuneko/assets/116431676/821532ca-3fcd-4a3e-9976-99b878320590)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Hu? thats normal it means you have not fetched manga list yet.
