### ISSUE TITLE
[Site Request] inkr

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5910]
**Name of the website**
inkr

**Website urls (examples below)**
- Site: https://comics.inkr.com/
- Manga List: https://comics.inkr.com/
- Manga example: https://comics.inkr.com/title/428-embrace-my-shadow
- Chapter online viewer example: https://comics.inkr.com/title/428-embrace-my-shadow/chapter/14464-chapter-1

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/3782
