### ISSUE TITLE
[Bug] i just cant download the manga chapter or see the chapter preview on hakuneko

### ISSUE THREAD

**Issue by italocardoso** [manga-download/hakuneko#5914]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by MikeZeDev** [comment]
Closing that issue:.
Reason : Invalid issue. No information at all. Template not filled. Cant fix what we dont know. Waste of time.
