### ISSUE TITLE
[Site Request] SoulScans

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5915]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://soulscans.my.id/
- Manga List: https://soulscans.my.id/manga/?order=update
- Manga example: https://soulscans.my.id/manga/sekainohate-de-aimashou/
- Chapter online viewer example: https://soulscans.my.id/manga/sekainohate-de-aimashou/#/chapter-1

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
You dont even remember asking for it? 😞 
Duplicate https://github.com/manga-download/hakuneko/issues/5806

**Comment by Frezian** [comment]
when will this site be added?
