### ISSUE TITLE
[Site Request] Scanwaves

### ISSUE THREAD

**Issue by Algaiya** [manga-download/hakuneko#5916]
**Name of the website**
  - Scanwaves

**Website urls**
  - Site: http://www.scanwaves.fr/
  - Manga List: http://www.scanwaves.fr/bibliotheque
  - Manga example: http://www.scanwaves.fr/bibliotheque/fabricant-100
  - Chapter online viewer example: http://www.scanwaves.fr/lecteur/15

**Languages**
  - Only **french**.

**Additional details**
  - The site is built using the Symfony framework, with an **interactive reading system** developed entirely by me, the founder.

**Comment by MikeZeDev** [comment]
Nice reader but without a proper chapter list i dont think we should add it.
