### ISSUE TITLE
[AllAnimeSite] Connector not working

### ISSUE THREAD

**Issue by Pancake87** [manga-download/hakuneko#5917]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It is not possible to access any manga on AllAnimeSite connector.

**To Reproduce**
1. Open AllAnimeSite connector.
2. No content loads even if connector is refreshed.

**Screenshots**
![Screenshot (22815)](https://github.com/manga-download/hakuneko/assets/136653715/f403d8cc-cb8c-4952-a909-bd269f52c1e8)

**HakuNeko (please complete the following information):**
 - Version [6.1.7@513508]

**Comment by Pancake87** [comment]
I tried both nightly and stable versions but had no luck.

**Comment by MikeZeDev** [comment]
Error displayed are not for that site so that doesnt help :D
