### ISSUE TITLE
[Site Request] Hentaivn

### ISSUE THREAD

**Issue by Stragytek** [manga-download/hakuneko#5918]
**Name of the website**
Hentaivn

**Website urls (examples below)**
- Site: https://hentaivn.tv/
- Manga List: https://hentaivn.tv/danh-sach.html
- Manga example: https://hentaivn.tv/33979-doc-truyen-hatsukoi.html
- Chapter online viewer example: https://hentaivn.tv/33979-62864-xem-truyen-hatsukoi-chap-1.html

**Languages**
Vietnamese

**Website relationship*
alternative domain: https://hentaivn.autos/

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Not possible, and duplicate. Search before , issue already exists

https://github.com/manga-download/hakuneko/issues/5394
