### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by andib4** [manga-download/hakuneko#5921]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector suddenly not working on 6/19 at 8 PM (UTC+7), getting the error net::ERR_NOT_IMPLEMENTED, already tested using a different ISP or other internet connection, and the error still appeared.

**To Reproduce**
1. Open Mangadex connector.
2. Any manga titles.
3. Any manga chapters.
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![U4nXX4uRJf](https://github.com/manga-download/hakuneko/assets/117697540/79760848-c5e0-4718-91d1-0f93cc8d23f0)

**HakuNeko (please complete the following information):**
 - Version [6.1.7@513508]

**Comment by MikeZeDev** [comment]
Not implemented? WTF. Hum i dont have this manga in my list, so i tried clipboard. Same manga, same chapter. No problems.

Gotta test with the list, but refreshing list will take a while :D

I got an error but i waited a few minutes, then i retried and it worked..

![image](https://github.com/manga-download/hakuneko/assets/10671518/8bbb6acb-f92d-4830-869d-d1b8dd29736a)

Preview and download worked after retrying, i guess its mangadex server 🤷 .

**Comment by ach4ndi** [comment]
is seems mangadex server is limiting the connection on certain region, so got error when is meet the limit. And also caching the request is bad idea, no wonder I always got error on any titles. 

is possible to set number files of concurrent download? like limit to 5?

**Comment by MikeZeDev** [comment]
You can disable concurrent downloads in options. Not sure about a number tho
