### ISSUE TITLE
[Site Request] book.dmm

### ISSUE THREAD

**Issue by EinarGravity** [manga-download/hakuneko#5922]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://book.dmm.com/
- Manga List: https://book.dmm.com/schedule/?floor=Gcomic
- Manga example: https://book.dmm.com/product/4315117/b574acmin03126/?i3_ref=list&i3_ord=56&dmmref=g_List_commonList
- Chapter online viewer example: https://book.dmm.com/free_streaming/b574acmin02942/?cid=FglfSVtRA11XDh1IQVkCQgIRaV9UBAYMVVZWBV8MWQBXWAQLSlATV106QkxBUwdaCAtRCwEVEEsDDEQPRgxYXjoHXF5bBw__&lin=0&sd=1

**Languages**
Japones

**Comment by MikeZeDev** [comment]
Duplicat ehttps://github.com/manga-download/hakuneko/issues/4317
