### ISSUE TITLE
[Site Request] firecross

### ISSUE THREAD

**Issue by EinarGravity** [manga-download/hakuneko#5923]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://firecross.jp/
- Manga List: https://firecross.jp/hjbunko/series
- Manga example: https://firecross.jp/ebook/series/414
- Chapter online viewer example: https://firecross.jp/reader/1462?trial=0&token=82addaa6-cad3-44a7-9c2f-6f9864775fff&vertical=0

**Languages**
Japones

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3978
