### ISSUE TITLE
[Site Request] Zoro.to

### ISSUE THREAD

**Issue by Vara-3** [manga-download/hakuneko#5926]
**Name of the website**
Zoro.to

**Website urls (examples below)**
- Site: https://zoro.to/home
- Manga List: https://zoro.to/jojos-bizarre-adventure-part-4-diamond-is-unbreakable-uncensored-89
- Manga example: https://zoro.to/watch/jojos-bizarre-adventure-part-4-diamond-is-unbreakable-uncensored-89?ep=2001

**Languages**
Sub: Arabic, English, French, German, Italian, Portuguese - Brazilian Portuguese, Spanish - Spanish[ESP], Spanish - Spanish[LAT]
Dub: English

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4625
