### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by monke-society-dev** [manga-download/hakuneko#5928]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
won't download, error in joblist says "support for video stream from mirror [link] is not implemented"

**To Reproduce**
1. connect to 9anime
2.  search up garden of sinners/ steins gate 0
3. download first option

**Expected behavior**
it should create a new folder with file inside

**Screenshots**

**Context (please complete the following information):**
 - OS: windows 11
 - the newest one (hakuneko ver)
 

**Additional context**

**Comment by MikeZeDev** [comment]
Vidsteam Mycloud and Mp4Upload cant be fixed. However you have videos hosted on Filemoon. 

![image](https://github.com/manga-download/hakuneko/assets/10671518/faebd28c-7ed7-407c-b898-34b92a62e636)
