### ISSUE TITLE
[NameOfConnector] Readmanga and Mintmanga Connectors not working

### ISSUE THREAD

**Issue by IsakGairatov** [manga-download/hakuneko#5929]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
I choose any manga from these 2 connectors, but it has no chapters. It shows Chapters: 0/0 for any manga I want to download, despite there are chapters on these sites

**To Reproduce**
1. Readmanga, Mintmanga
2. gleipnir
3. any 
4. when I try to update connector it fail to fetch

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/97949548/549b7b27-f027-4937-9620-14c6d0ad2a09)

If complex to describe, add screenshots to help explain your problem.
![image](https://github.com/manga-download/hakuneko/assets/97949548/60533ce6-09d0-41d7-aa84-a5372a799ba5)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
And i bet its the same for mangachan, since those are using the same template. Ah, nope

**Comment by ignaciocastro** [comment]
Fix: #5931 
Mangachan issue unrelated
