### ISSUE TITLE
[Mangachan] Connector not working

### ISSUE THREAD

**Issue by IsakGairatov** [manga-download/hakuneko#5930]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I try to download chapters of manga, but it stops process immediately, and turn sign to red 

**To Reproduce**
1. Mangachan
2. Gleipnir 
3. any
4. no error shown

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![image](https://github.com/manga-download/hakuneko/assets/97949548/de399b62-6c47-4b82-a5de-4c9b04130537)

**Comment by MikeZeDev** [comment]
Of course : 

![image](https://github.com/manga-download/hakuneko/assets/10671518/01aa3da1-86d3-4302-b5d8-4001fd596262)

Files doesnt exists, hakuneko cant download them. Is that working on the website? 


I tried other mangas/chapters and it works fine.

**Comment by ignaciocastro** [comment]
`curl https://img2.manga-chan.me/manga/-7new/1/1682434370_14_88/0.jpeg` > 404 not found
`curl https://img2.manga-chan.me/manga/-7new/1/1682434370_14_88/0.jpeg -e https://manga-chan.me` > Downloads as intended

**Comment by MikeZeDev** [comment]
Meh. Why dont they return a real error like 5xx or 403 instead of fakeing a file not found? derp
Gotta fix that , ty
