### ISSUE TITLE
[Manga Livre] Can't download chapters "Cannot read property 'src' of null"

### ISSUE THREAD

**Issue by Rodrigo-017** [manga-download/hakuneko#5933]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes and No

**Describe the bug**
It gives me this error whenever I try to download a chapter.

**To Reproduce**
1. Name of connector: Manga Livre
3. Name of manga (if connector update is working): Everything
4. Name of chapter (if manga update is working): Everything
5. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12):

TypeError: Cannot read property 'src' of null
    at MangaLivre._getPages (mjs/connectors/MangaLivre.mjs:18)
    at async MangaLivre._getPageList (mjs/engine/Connector.mjs:615) 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version master@d45881

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4061
