### ISSUE TITLE
[AnimeUnity] Connector not working

### ISSUE THREAD

**Issue by marcostudios** [manga-download/hakuneko#5934]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The AnimeUnity connector shows the "Cannot read property 'map' of undefined error when refreshing the anime list

**To Reproduce**
1. Select AnimeUnity as the source
2. Press syncronize list with online list from AnimeUnity
3. The error appears

**Screenshots**
![immagine](https://github.com/manga-download/hakuneko/assets/5209299/d9355799-f58c-4d7f-9da8-bf208aca56a8)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
They changed URL, and redirection use GET and not POST, LMAO
