### ISSUE TITLE
[ScanTrad] It can be removed : the site closed.

### ISSUE THREAD

**Issue by Fred-Vatin** [manga-download/hakuneko#5935]
On March 1, the https://scantrad.net/ closed the site permanently.

source : https://www.konbini.com/popculture/apres-17-ans-a-traduire-des-scans-de-mangas-le-site-scantrad-tire-sa-reverence/

**Comment by MikeZeDev** [comment]
Merci pour l'information, nous le savions :)

https://github.com/manga-download/hakuneko/issues/4972
