### ISSUE TITLE
Problem with downloading

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#594]
> **From:** HakuNeko User

Can't download Jojo Volumes from volume 113-117 (japscan Source). I think the problem isn't from you since I try with Tachiyomi with my mobile and it's the same...

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Works for me as expected with the latest Nightly Build.

Have you tried with default settings?
Are you using any proxy or VPN?

**Comment by 27136773** [comment]
As mentioned in discord HakuNeko version was out of date
