### ISSUE TITLE
[Site Request] Manga Scan

### ISSUE THREAD

**Issue by webrootpro** [manga-download/hakuneko#5942]
Name of the website
Manga Scan

Website urls (examples below)

Site: https://manga-scan.ws/
Manga List: https://manga-scan.ws/manga-list
Manga example: https://manga-scan.ws/manga/mi-seijuku
Chapter online viewer example: https://manga-scan.ws/manga/mi-seijuku/10
Languages
fr

**Comment by MikeZeDev** [comment]
No. Same answer than https://github.com/manga-download/hakuneko/issues/5768. Duplicate
