### ISSUE TITLE
[mangalek.org] is not working because it change to [mangalek.com]

### ISSUE THREAD

**Issue by KoStranger** [manga-download/hakuneko#5943]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
https://ww.mangalek.org/ is still up for me. After a little fix it works properly.

![image](https://github.com/manga-download/hakuneko/assets/10671518/086aab7e-87ad-4725-8543-ef2bd9d0d70f)
