### ISSUE TITLE
[Site Request] Manga One

### ISSUE THREAD

**Issue by manti-X** [manga-download/hakuneko#5946]
**Name of the website**
Manga One

**Website urls (examples below)**
- Site: https://manga-one.com/
- Manga List: https://manga-one.com/title
- Manga example: https://manga-one.com/title/323
- Chapter online viewer example: https://manga-one.com/title/323/214557

**Languages**
Japanese

**Additional details**
You can read the series only in their app.

**Comment by MikeZeDev** [comment]
Rejected. Reason : we do not plan to support app-only websites because it means reversing the application.
