### ISSUE TITLE
[ReadComicOnline] Connector not working

### ISSUE THREAD

**Issue by DorkN313** [manga-download/hakuneko#5949]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When trying to download comics from KissCartoon, it gives you "1stImages is not defined" error. It sometimes works on a fresh launch, but only for some time and rarely.

**To Reproduce**
1. KissCartoon (ReadComicOnline)
2. Any
3. Any
4. 
```
    Connector.mjs:618 ReferenceError: lstImages is not defined
    at <anonymous>:2:44
    at new Promise (<anonymous>)
    at <anonymous>:2:13
    at WebFrame../lib/renderer/api/web-frame.ts.WebFrame.<computed> [as executeJavaScript] (web-frame.ts:64)
    at web-frame-init.ts:19
    at EventEmitter.<anonymous> (ipc-renderer-internal-utils.ts:10)
    at EventEmitter.emit (events.js:210)
    at Object.onMessage (init.ts:51) 
EventTarget
manga: EventTarget {connector: KissComic, id: "/Comic/More-Fun-Comics", title: "More Fun Comics", status: "available", chapterCache: Array(115), …}
id: "/Comic/More-Fun-Comics/Issue-73?id=64896"
title: "Issue #73"
file: {name: "Issue #73", extension: ".cbz", full: "Issue #73.cbz"}
language: "en"
status: "failed"
pageProcess: false
pageCache: []
__proto__: EventTarget
```

**HakuNeko (please complete the following information):**
 - Version master@480591

**Comment by MikeZeDev** [comment]
Cant reproduce. 🤷 

![image](https://github.com/manga-download/hakuneko/assets/10671518/d4d45f72-1fd1-4f60-bf7c-ed3245a0b0a5)

One reason could be : problem with slow internet / slow server / ip ban ? 

I know this website have problems from time to time. Were you mass downloading or something?

**Comment by MikeZeDev** [comment]
well, gotta add a delay, just in case 🤷

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/9bfc7710-6456-4385-8ac5-180359298335)

Captcha :/

**Comment by MikeZeDev** [comment]
Worst : Page doesnt fully "load". You have to close the ad. And you cant do that if you didnt trigger the captcha (because window wont open without captcha detected)
