### ISSUE TITLE
[Feature] Don't download duplicates

### ISSUE THREAD

**Issue by Username9980** [manga-download/hakuneko#5954]
**Describe the solution you'd like**
When a manga website has two of the same chapter but different scanlation groups, don't download that scanlation group and download the best version possible.

**Context (please complete the following information):**
Current Master version.

**Comment by 27136773** [comment]
Cannot be reproduced.
Sample website, manga and chapter are not provided.

**Comment by MikeZeDev** [comment]
> same chapter

How are we supposed to guess its the same chapter if they are named differently ? I mean, not empirically but realistically?  Its prone to errors.  Scanlator team is not an info available everywhere, and not even an info we fetch anyway.

> the best version possible.

Unless we have a magical crystal ball , how can we know "the best version possible"? I mean, Haku download the best image quality when possible but thats for websites offering different qualities. 

But you are talking about different scanlators."The best version possible" depends on each person own judgement. And if its about the quality, ahem.... they need to be downloaded to check.

Suggestion : use the scanlator website's connector. Feel free to request if it doesnt exists. Or choose a connector which doesnt add duplicates from the same chapter.
