### ISSUE TITLE
https://lectormanga.com/library/manhwa/65336/today-dinner

### ISSUE THREAD

**Issue by Gwonhoozz** [manga-download/hakuneko#5955]
https://lectormanga.com/library/manhwa/65336/today-dinner

Can't download chapter from this

**Comment by MikeZeDev** [comment]
Problem Known, CloudFlare cant fix

**Comment by Gwonhoozz** [comment]
> Problem Known, CloudFlare cant fix

But it's not on cloudflare anymore

**Comment by MikeZeDev** [comment]
> > Problem Known, CloudFlare cant fix
> 
> But it's not on cloudflare anymore

It is. I just tried 

![image](https://github.com/manga-download/hakuneko/assets/10671518/c2b04cdf-4502-440e-9596-3e0c4560df86)
