### ISSUE TITLE
[Site Request] Mangaraw

### ISSUE THREAD

**Issue by Poharan** [manga-download/hakuneko#5956]
**Name of the website**
mangaraw

**Website urls (examples below)**
- Site: https://mangaraw.org
- Manga List: https://mangaraw.org/directory
- Manga example: https://mangaraw.org/kanan-sama-wa-akumade-choroi
- Chapter online viewer example: https://mangaraw.org/kanan-sama-wa-akumade-choroi/001

**Languages**
Japanese

**Comment by MikeZeDev** [comment]
Cloudflare cant do
