### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by xavimaa** [manga-download/hakuneko#5963]
**Describe the bug**
MangaDex update not working there is error 400

**Screenshots**

![image](https://github.com/manga-download/hakuneko/assets/82511742/90828550-c529-4894-9698-db04e4cc795b)

**HakuNeko (please complete the following information):**
 - Nightly Build

**Comment by ghost** [comment]
same

**Comment by tizio04** [comment]
Hi, I have the same problem; I use the stable 6.1.7 version

**Comment by Vuragado** [comment]
Same here - I use the Stable 6.1.7 version as well.

**Comment by mabequinho** [comment]
Unable to refresh connector but saved mangadex bookmarks are working here. 6.17.

**Comment by ccx2** [comment]
Looks like the API throttling is not applied, leading to a temp ban:
![grafik](https://github.com/manga-download/hakuneko/assets/63751016/e820f9c5-b7c1-4863-91e0-f19abdffcf53)

**Comment by ccx2** [comment]
Will make a pull request if this works - will let it run throughout the night:
`        while(lastCreatedAt) {
            await throttle;
            throttle = new Promise(resolve => setTimeout(resolve, 250));`
==>
`        while(lastCreatedAt) {
            await throttle;
            throttle = new Promise(resolve => setTimeout(resolve, this.config.throttleRequests.value));`

**Comment by MikeZeDev** [comment]
Fixed , ty. 5 Seconds seems enough.
