### ISSUE TITLE
[Site Request] GregoryMangas 

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5966]
**Name of the website**
Gregory Mangas

**Website urls (examples below)**
- Site: https://gremorymangas.com/
- Manga List: https://gremorymangas.com/manga/
- Manga example: https://gremorymangas.com/manga/comenzando-con-la-cuenta-del-rey/
- Chapter online viewer example: https://gremorymangas.com/2023/06/30/comenzando-con-la-cuenta-del-rey-361/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream
