### ISSUE TITLE
[Site Request] Nora No Fansub

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5967]
**Name of the website**
Nora No Fansub

**Website urls (examples below)**
- Site: https://www.noranofansub.com/
- Manga List: https://www.noranofansub.com/lector/
- Manga example: https://www.noranofansub.com/lector/series/your-royal-highness-is-happy/
- Chapter online viewer example: https://www.noranofansub.com/lector/read/your-royal-highness-is-happy/es-cl/1/34/page/1

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Ahem https://github.com/manga-download/hakuneko/blob/54f80c398223b2333d5ac5160ad732be3686184b/src/web/mjs/connectors/NoraNoFansub.mjs#L6

In case it doesnt work, feel free to make a "not working "request" :)
