### ISSUE TITLE
[Site Request] Ridibooks

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5968]
**Name of the website**
Ridibooks

**Website urls (examples below)**
- Site: https://ridibooks.com/comics/bl

**Languages**
Korean

**Website relationship*
It's just like Lenzhin and Tapas, a Korean comic website.

**Additional details**
Was trying to locate this connector in HakuNeko but its not showing up. I'm a fan-scanlator and was trying to download raws which can only be found in this website. [RIDIBOOKS]

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5387
