### ISSUE TITLE
[Site Request] Add manhuabaiku.com

### ISSUE THREAD

**Issue by LazyScar** [manga-download/hakuneko#5970]
**Name of the website**
manhuabaiku

**Website urls (examples below)**
- Site: https://www.manhuabaiku.com/
- Manga List: https://www.manhuabaiku.com/category/
- Manga example: https://www.manhuabaiku.com/comic/10230.html
- Chapter online viewer example: https://www.manhuabaiku.com/chapter/10230_1010299.html

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
template : MH, maybe?

**Comment by WavaDev** [comment]
Using Same Theme as: http://www.6mh67.com

**Comment by MikeZeDev** [comment]
No matter which chapter i try its all garbage page

![image](https://github.com/manga-download/hakuneko/assets/10671518/b149c5a7-c174-4b95-9bc4-3d06d6e109c9)

**Comment by WavaDev** [comment]
it worked before tho, not anymore.

> No matter which chapter i try its all garbage page
> 
> ![image](https://private-user-images.githubusercontent.com/10671518/313721673-b149c5a7-c174-4b95-9bc4-3d06d6e109c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzYyMDksIm5iZiI6MTcxMTg3NTkwOSwicGF0aCI6Ii8xMDY3MTUxOC8zMTM3MjE2NzMtYjE0OWM1YTctYzE3NC00Yjk1LTliYzQtM2QwNmQ2ZTEwOWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA5MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDgwNTM0YWJkNGZiZThhYjE1ZjU3YzU0NmJjN2JjMDFiOWY2ZDU3MzEyZjdjYjRjYWYyYjFhNWI0NGMwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4cGTWzoawOcl8l5HdpTb4v5OcEtJkzJHklQHjH7ZbnY)

**Comment by MikeZeDev** [comment]
Sho
