### ISSUE TITLE
[Site Request] MangaStorm - مانجا ستورم

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#5971]
**Name of the website**
MangaStorm - مانجا ستورم

**Website urls (examples below)**
- Site: https://mangastorm.org/
- Manga List: https://mangastorm.org/mangas
- Manga example: https://mangastorm.org/mangas/18-solo-leveling
- Chapter online viewer example: https://mangastorm.org/mangas/18-solo-leveling/chapter/135

**Languages**
Arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
dead?

**Comment by SatanHere** [comment]
yes
