### ISSUE TITLE
[Dragon Translation] Connector not working

### ISSUE THREAD

**Issue by CloudBladed** [manga-download/hakuneko#5975]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can't access the manga site because I changed the domain from .com to .net

**To Reproduce**
1. Name of connector: Dragon Translation.
2. New site url: https://dragontranslation.net/
Cannot see or access the web from HaruNeko because the site changed domain.

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/70826672/960450df-13f0-4615-a39f-a3db5ae20828)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17@513508]

**Comment by MikeZeDev** [comment]
Not only that , stuff need to be recoded
