### ISSUE TITLE
[mangagg.com] Connector not working

### ISSUE THREAD

**Issue by 0Zzero** [manga-download/hakuneko#5983]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
no

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Your browser is out of date.

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cant fix

**Comment by MikeZeDev** [comment]
dont close unless issue is fixed?

**Comment by MikeZeDev** [comment]
Fixed itself
