### ISSUE TITLE
> https://swateam.me/

### ISSUE THREAD

**Issue by Oussjo7a** [manga-download/hakuneko#5984]
> https://swateam.me/

By all mean open an issue dont write on a PR

_Originally posted by @MikeZeDev in https://github.com/manga-download/hakuneko/issues/5859#issuecomment-1620178996_

**Comment by MikeZeDev** [comment]
https://www.google.com.

I can post urls too.

Can you please take the time to explain the problem by correctly filling the template provided, please?

**Comment by MikeZeDev** [comment]
And url changed again : https://swatop.club :D
