### ISSUE TITLE
[nhentai.net] Connector not working cloudflare

### ISSUE THREAD

**Issue by thegoldenboy542** [manga-download/hakuneko#5987]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
I am unable to access nhentai.net due to the cloudflare captcha page, on both ver 6.1.7 and the nightly build. On version 6.1.7 it says the browser in too old and incompatible. On the nightly build the captcha keeps resetting no matter how many times I press the verify button.

**HakuNeko (please complete the following information):**
 - Version  6.1.7
 - Nightly master@ecb835

**Comment by Aces-and-Jacks** [comment]
Since this is related to both nhentai and cloudflare would it be possible to make an option in settings that directs to browser cookies? Or imports them for specific websites?

**Comment by MikeZeDev** [comment]
No more cloudflare
