### ISSUE TITLE
[Feature] Is hakuneko support docker image base on KasmVNC

### ISSUE THREAD

**Issue by linuxbelletian** [manga-download/hakuneko#5989]
**Is your feature request related to a problem? Please describe.**

It would be great if hakuneko can be deployed in a container environment for NAS usage scenarios.

There is a base image: KasmVNC Base Images, I don't know if hakuneko is compatible with it
[kasmvnc](https://github.com/linuxserver/docker-baseimage-kasmvnc)

**Comment by MikeZeDev** [comment]
IIRC this was already asked. Since its a path leading to headless Haku and its a road we dont want to take this probably wont be implemented, but maybe i am wrong and someone will correct me.

See https://github.com/manga-download/hakuneko/issues/1384
