### ISSUE TITLE
[Site Request] AnimeDao

### ISSUE THREAD

**Issue by kazukeiixx** [manga-download/hakuneko#5990]
**AnimeDao**
https://animedao.to/

**Website urls (examples below)**
- Site: 
- Manga List: https://animedao.to/animelist/
- Manga example: https://animedao.to/anime/black-butler/
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website
English 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)
Anime website

**Comment by MikeZeDev** [comment]
Dead
