### ISSUE TITLE
[Site Request] webtoonevreni

### ISSUE THREAD

**Issue by NekoManga** [manga-download/hakuneko#5991]
**Name of the website**
webtoonevreni

- Site: webtoonevreni.net
- Manga List: https://webtoonevreni.net/manga/
- Manga example: https://webtoonevreni.net/manga/secilmis-kisi/
- Chapter online viewer example: https://webtoonevreni.net/manga/secilmis-kisi/bolum-253/

**Languages**
Turkish

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
They have Merlin scans icon, can someone explain?

**Comment by MikeZeDev** [comment]
dead
