### ISSUE TITLE
[Site Request] tarotscans

### ISSUE THREAD

**Issue by NekoManga** [manga-download/hakuneko#5992]
**Name of the website**
tarotscans

**Website urls (examples below)**
- Site: https://www.tarotscans.com/
- Manga List: https://www.tarotscans.com/manga/
- Manga example: https://www.tarotscans.com/manga/murim-login/
- Chapter online viewer example:https://www.tarotscans.com/murim-login-bolum-1/

**Languages**
Turkish

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
MangaStream

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5562
