### ISSUE TITLE
[Feature] A way to change folder name so duplicate names can be in separate folders

### ISSUE THREAD

**Issue by Elliander** [manga-download/hakuneko#5993]
**Is your feature request related to a problem? Please describe.**
For some Manga I attempt to obtain from multiple different sources whenever there is a problem with one or more chapters such as repeating images or excessive watermarks. Unfortunately, if more than one site uses the exact same name HakuNeko will use the exact same folder. This means that I cannot maintain separate download lists of the same series to compare quality later.

It's also possible that I may at some point in the future encounter two separate works with the same name. Some mangas have very simple names and there are already examples of name reuse in popular media so that seems like a problem to avoid ahead of time.

**Describe the solution you'd like**
I'd like to be able to select a series from my favorites and give it a new name. Doing so should create a new folder for that work and reset the list of downloaded chapters for that folder since it's now empty. It should also remember the new name from that source at least if it's in my favorites.

An alternative to this idea could be to have an option for a [tag] to be added to the end of the filename given the source, but this approach sounds messier since it might screw up existing download folders.

**Describe alternatives you've considered**
I could manually rename a folder before trying to download a new source, but if I do that for an ongoing series the overlap will still cause problems. It will become impossible for me to even tell which site a given file came from. 

**Context (please complete the following information):**
 - HakuNeko rev. 6.1.7@513508

**Comment by MikeZeDev** [comment]
Well, there is an option that could help you, since your problem is that you use different sources.

![image](https://github.com/manga-download/hakuneko/assets/10671518/ee6ebdb6-c158-4d27-998c-0fc739f19cb0)

**Comment by MikeZeDev** [comment]
I ma closing this as the option i mentioned could fix your problem, if you feel its not helping reopen this issue :)
