### ISSUE TITLE
[Site Request] Immortal Update ID

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5995]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://immortalupdates.id/
- Manga List: https://immortalupdates.id/manga/
- Manga example: https://immortalupdates.id/manga/evolution-frenzy/
- Chapter online viewer example: https://immortalupdates.id/manga/evolution-frenzy/chapter-104/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
template Madara

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
dead
