### ISSUE TITLE
[Site Request] voiranime.com

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#5999]
**Name of the website**
VoirAnime

**Website urls (examples below)**
- Site: www.voiranime.com

**Languages**
VO Sub in french
French

**Website relationship*
None.

**Additional details**
There is a Cloudflare first then a Recaptcha on the episode

Could be a great connector/Website to open Hakuneko to new countries (France) as just around 97.6 million people speak French as their mother tongue. French is also considered a world language and is therefore the official or common language in many countries. Thus, there are over 300 million speakers. 

France is also the 3rd with the highest demand of anime titles (after US and Indonesia)
(https://www.parrotanalytics.com/insights/the-global-content-marketplace-audience-demand-for-anime/)

**Comment by MikeZeDev** [comment]
Duplicate : https://github.com/manga-download/hakuneko/issues/250
