### ISSUE TITLE
[Site Request] voirdrama

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6000]
**Name of the website**
VoirDrama

**Website urls (examples below)**
- Site: www.voirdrama.com

**Languages**
VO sub in French
French

**Website relationship**
None

**Additional details**
Works exactly like voiranime.com (cloudflare + recaptcha every episode)

I think it could be interesting to add a drama source ???
Could be a great connector/Website to open Hakuneko to new countries (France) as just around 97.6 million people speak French as their mother tongue. French is also considered a world language and is therefore the official or common language in many countries. Thus, there are over 300 million speakers.

**Comment by MikeZeDev** [comment]
Despites having alternate DNS i cant open it. I got a .org working
Cloudflare is a no go at least for the moment

**Comment by I-JMC** [comment]
My bad it's .org, too bad Cloudflare protected website won't work 😥

**Comment by MikeZeDev** [comment]
Voirdama.org
