### ISSUE TITLE
[となりのヤングジャンプ (Tonari no Young Jump)] Connector not working

### ISSUE THREAD

**Issue by KatPonse** [manga-download/hakuneko#6001]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Doesn´t load the new manga and load only the last chapter in all the options to download

**To Reproduce**
1. となりのヤングジャンプ (Tonari no Young Jump)
2. One Punch man
3. 233
4. api.vrv.co/core/index:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![hakuneko error3](https://github.com/manga-download/hakuneko/assets/48859634/376903c7-ecd5-430b-80cf-bda7243aefb1)
![hakuneko error2](https://github.com/manga-download/hakuneko/assets/48859634/cf32d477-3fe6-4147-a3a4-108ed8bb20f6)
![hakuneko error](https://github.com/manga-download/hakuneko/assets/48859634/c787c356-01e8-4fd9-9185-df843b8ce490)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Could you please write the manga name as its displayed on the website please so i can copy paste it ? 
I cant write Japanese 🤷

**Comment by MikeZeDev** [comment]
Works for me. 

![image](https://github.com/manga-download/hakuneko/assets/10671518/64513dbd-223b-465c-87d0-7ff2b295a99d)

Refresh manga list, use nightly? 

Also 

> Is the website of the connector working properly / are you able to see the manga within your browser
> No

You said its not working in your browser ? In that case its not Hakuneko fault.

**Comment by KatPonse** [comment]
the name of the manga
ワンパンマン/One Punch man

**Comment by MikeZeDev** [comment]
Ii works 🤷

**Comment by MikeZeDev** [comment]
You tried nightly?

**Comment by KatPonse** [comment]
Not yet!

**Comment by MikeZeDev** [comment]
I doubt it will change anyrthing, and i cant fix what i cant reproduce

**Comment by kevin01523** [comment]
probably specific to his isp or location using a vpn might help
