### ISSUE TITLE
[leviatan scans] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#6006]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

Fail to download chapter and when I hit the preview button "cryptoJS is not defined" message pops up. refresh work fine but has no effect. As far as I can tell, this is the case for all titles and chapters.

**To Reproduce**
1. Name of connector - Leviatan.Scans
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
       
     "cryptoJS is not defined"

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="1110" alt="Screenshot 2023-07-13 at 4 38 08 PM" src="https://github.com/manga-download/hakuneko/assets/70929406/938f2dcd-af5a-41a2-ae93-901d3cdbb041">
<img width="1160" alt="Screenshot 2023-07-13 at 4 37 15 PM" src="https://github.com/manga-download/hakuneko/assets/70929406/c97c4914-e82f-43b4-be30-b71552b3c36e">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] - 8.3.4

**Comment by MikeZeDev** [comment]
Unrelated : You should use a good adblocker like ublock Origin :)

**Comment by tsentered** [comment]
Righteous
