### ISSUE TITLE
[Mangadex] Connector not working fully?!

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [manga-download/hakuneko#6007]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No, not fully. in app it mentioned refreshing the page but that didn't do anything

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No, not that i'm aware of. 

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes, https://mangadex.org/title/9e107c4a-ad46-4fcf-9ca1-98f21c6ec2a3/the-hero-took-everything-from-me-so-i-partied-with-the-hero-s-mother

**Describe the bug**
I was trying to locate a specific manga ("The Hero Took Everything from Me, So I Partied with the Hero’s Mother!") to download found it on MangaDex dot org but it's not showing up on here (anywhere). either English name or Japanese name.

**To Reproduce**
1. Name of connector **Mangadex and "connection search" window**
2. Name of manga (if connector update is working) **The Hero Took Everything from Me, So I Partied with the Hero’s Mother!**
3. Name of chapter (if manga update is working) **any /all**
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
I don't know if this means anything but.... also don't know if it's relevant but what does load for the connector takes a minute or two
.
api.mangadex.org/man…B%5D=pornographic:1 Failed to load resource: the server responded with a status of 400 ()
Connector.mjs:579 Error: Failed to receive content from "https://api.mangadex.org/manga?limit=100&order%5BcreatedAt%5D=asc&createdAt…5D=suggestive&contentRating%5B%5D=erotica&contentRating%5B%5D=pornographic" (status: 400) - 
    at Connector.mjs:469
    at async MangaDex._getMangas (MangaDex.mjs:94)
    at async MangaDex._getMangaList (Connector.mjs:576) 
MangaDex

**_Fresh open of app again, then load of a working title:_**
Loading Engine: HakuNeko
hakuneko://plugins/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
mjs/engine/Connectors.mjs:49 Failed to load connector "hakuneko://cache/mjs/connectors/Comikey.mjs" TypeError: Cannot read property 'isDevToolsOpened' of null
    at mjs/connectors/Comikey.mjs:4
    at mjs/connectors/Comikey.mjs:4
    at mjs/connectors/Comikey.mjs:4
    at mjs/connectors/Comikey.mjs:4
index.html:61 Loading Frontend: frontend@classic-light
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
mjs/connectors/templates/VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:305)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
mjs/connectors/templates/VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:305)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
mjs/connectors/templates/VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:305)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
mjs/engine/Settings.mjs:378 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-solid-900.woff2?v=5.8.2
3
api.vrv.co/core/index:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
mjs/connectors/templates/VRV.mjs:310 VRV (Crunchyroll) initialization failed! SyntaxError: Unexpected token < in JSON at position 0
mjs/connectors/templates/VRV.mjs:310 VRV (HiDive) initialization failed! SyntaxError: Unexpected token < in JSON at position 0
mjs/connectors/templates/VRV.mjs:310 VRV (Rooster Teeth) initialization failed! SyntaxError: Unexpected token < in JSON at position 0
Added Network Seeds '[ https://uploads.mangadex.org/data/, https://cache.ayaya.red/mdah/data/ ]' to MangaDex
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-regular-400.woff2?v=5.8.2

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
6.1.7@513508

**Comment by MikeZeDev** [comment]
Use nightly and increase throttling for mangadex in hakuneko options. Do exactly like that. I know it sounds a lot but with 5 seconds i got it working. Fetching list took a crapload of time but it worked. Maybe a bit less?

**Comment by GeneralUser-NonDev** [comment]
![hn_mangadex](https://github.com/manga-download/hakuneko/assets/96662916/07423499-1553-4747-903e-6e458bfc1b24)

How do I tell if I'm using  "Nightly" build? I think I may have went to it once before but i don't recall.

when you say increase throttling do you mean this "Throttle image requests" or the "Throttle API Requests"? or something else?

**Comment by MikeZeDev** [comment]
> How do I tell if I'm using "Nightly" build? I think I may have went to it once before but i don't recall.

https://hakuneko.download. BIG NIGHTLY BUTTON. And also, in the ticket you opened :)

**Comment by GeneralUser-NonDev** [comment]
> > How do I tell if I'm using "Nightly" build? I think I may have went to it once before but i don't recall.
> 
> https://hakuneko.download. BIG NIGHTLY BUTTON. And also, in the ticket you opened :)

OK, so there's no way to tell if the already installed version is the nightly or not, and as for the "Info entered on ticket" it says (I stated) that I don't know if it's nightly or not. 

Future readers (if any): I just installed the "Nightly" build and instead of the top right corner saying "rev. 6.1.7@xxxxxxx" it says "rev. master@xxxxx", Maybe that's the tell-tale of Stable build vs Nightly build. That alone didn't help find the title, the titles the "connector" finds work fine, I just can't find this particular title I'm looking for using this program (I can find the title on the connectors website though). I set the "Throttle API" field from 2000 to 5000 and hit the refresh button and it's taking FOREVER to finish refreshing, tried to change it back (mid-refresh, got tired of waiting, waited approximately 8-10 minutes) then the connector error-ed out (screen shot below) closed and reopened the program and same as prior to error, connector works but doesn't find the title I'm looking for, even by title search in connector screen same as with stable build.
![hn_mangadex_Nightly](https://github.com/manga-download/hakuneko/assets/96662916/5a288423-eeaf-4389-97ee-ef15fb21e17f)

**Comment by MikeZeDev** [comment]
1) You can check the version in settings but its a hassle for the user to identify "nightly". So i told you to download nightly on the website. Because its easier to do that. ^^. I told you to use nightly because throttling is no properly applied in stable and fix is available since a couple of days in nightly ^^

2) If you are impatient and change throttling in the middle ofc it f* up the process. We are sorry but since Mangadex is limiting requests this is something unavoidable. Its not like we did that on purpose :/

Considering Mangadex list i just got have 77302 mangas, you get 100 mangas for each request, you will need 774 requests. I tried with a 5 seconds delay. Suppose a request takes 1 second  it means you get one request each 6 seconds, meaning it will take 774*6 = 4644 seconds = 77 minutes = 1h17. Lets say i was generous and it really takes 2 or 3 hours. Thats not so so long considering you can let it run in the background.

If you are in a hurry there is a the Copy Paste aka Clipboard feature that will directly lead you to the manga you want. 
I didnt mentioned it since its written in the manual and your problem was with the manga list in the first place :/

Copy the manga url from your browser and past it inside haku, using the paste button on the interface.

**Comment by GeneralUser-NonDev** [comment]
> 1. You can check the version in settings but its a hassle for the user to identify "nightly". So i told you to download nightly on the website. Because its easier to do that. ^^. I told you to use nightly because throttling is no properly applied in stable and fix is available since a couple of days in nightly ^^

**Understandable, however like in my case I didn't know what I had (stable or Nightly) the form asks for the revision number anyway so if that's the identifier, then it shouldn't bee to hard to find out what you have installed already to be able to tell.**

> 2. If you are impatient and change throttling in the middle ofc it f* up the process. We are sorry but since Mangadex is limiting requests this is something unavoidable. Its not like we did that on purpose :/

**Yeah, I figured that's why it f-ed up, I was just stating that once it did I reset the program (closed and re-opened) for anyone who may read this in the future so they know it wasn't a lasting f- up.**


> Considering Mangadex list i just got have 77302 mangas, you get 100 mangas for each request, you will need 774 requests. I tried with a 5 seconds delay. Suppose a request takes 1 second it means you get one request each 6 seconds, meaning it will take 774*6 = 4644 seconds = 77 minutes = 1h17. Lets say i was generous and it really takes 2 or 3 hours. Thats not so so long considering you can let it run in the background.

**considering it can be left in the background yes, I agree time shouldn't be an issue, However I was trying to troubleshoot it not finding a specific manga and in the 30-60 sec it originally loads for me it finds some 62,xxx titles, I didn't expect it to take another 1.5+ hours (using your estimated math above) to find another 10,xxx or so. not to mention you didn't tell me which of the 2 "Throttle" options it was you changed or what you changed it to, I was just guessing and trying to see if it worked and with the INCREDIBLY long load time (compared to "out of the box") I didn't think it was.
I don't just leave this up all the time to fetch titles, I open it when I'm at the computer and actively looking for the title, when I find it I bookmark it so I can just click on it the next time I open the program in the future.**

> If you are in a hurry there is a the Copy Paste aka Clipboard feature that will directly lead you to the manga you want. I didnt mentioned it since its written in the manual and your problem was with the manga list in the first place :/

**Honestly, I didn't know there was a "Manual" for this so admittedly I guess I didn't read it. That being said I didn't know that this was a feature/function available to me. I wondered what that "[Clipboard]" option in the connector window was about, I suppose this answers that query.**

> Copy the manga url from your browser and past it inside haku, using the paste button on the interface.

**I did just that for this instance now that I know about it. Copied URL from web browser (Ctrl+C) then went into HN clicked into the connectors window "[Bookmarks]" spot and then clicked on "[Clipboard]", pressed enter on my keyboard and voila, There was the manga I was looking for.
apparently, I just read a couple links on the download website, all you have to do is press the 2 pages (paste) icon to the right of where it says "Manga List" and it'll go direct to your clipboard-ed link. Very Nice, Wish I knew about that prior.**

Thanks for your time and putting up with me. I learned a couple things about this program through this, but I'm still not to an "advanced user" status I'm sure.

**Comment by MikeZeDev** [comment]
Yeah no PB :)

I must admit  : maybe the settings are not clear enough 🤷 

![image](https://github.com/manga-download/hakuneko/assets/10671518/dd5a48c0-e0cf-43d4-94a8-3b31b97e2b00)

Users may not now what is the API, but could guess that "Image" one has nothing to do with getting manga list.
Oh well, glad you got it working 💪
