### ISSUE TITLE
[Site Request] ReadComicsOnline

### ISSUE THREAD

**Issue by kolbdog3333** [manga-download/hakuneko#6010]
**Name of the website**
Read Comics Online

**Website urls (examples below)**
- Site: https://readcomiconline.li
- Manga List: https://readcomiconline.li/ComicList
- Manga example: https://readcomiconline.li/Comic/Robyn-Hood-Annual-Invasion
- Chapter online viewer example: https://readcomiconline.li/Comic/Robyn-Hood-Annual-Invasion/Full?id=217099#1

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Invalid issue : 

* Use the bug report template or the connector not working template not "site request" next time.
* Usually i wouldnt care but i have nothing to look into. I dont know what going on you said nothing.

Feel free to reopen a proper ticket that explain your problem, it will be faster for you and me.
