### ISSUE TITLE
[JapScan] Failed to detect page type !

### ISSUE THREAD

**Issue by Fred-Vatin** [manga-download/hakuneko#6012]
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Recently, trying to see or download One Punch Man triggers the error
`Failed to detect page type !`

**To Reproduce**
1. JapScan
2. One Punch Man
3. All chapters
![image](https://github.com/manga-download/hakuneko/assets/22337329/b28a699d-8976-4049-9887-05f7b807e4d2)

**HakuNeko (please complete the following information):**
 - Version 6.1.7 (513508)

**Comment by MikeZeDev** [comment]
We know. Duplicate https://github.com/manga-download/hakuneko/issues/4657
