### ISSUE TITLE
[Site Request] Shirakami

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#6020]
**Name of the website**
Shirakami

**Website urls (examples below)**
- Site: https://shirakami.xyz/
- Manga List: https://shirakami.xyz/manga/
- Manga example: https://shirakami.xyz/manga/young-master-of-the-plutokart/
- Chapter online viewer example: https://shirakami.xyz/young-master-of-the-plutokart-chapter-15-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream
