### ISSUE TITLE
[LectorManga] Connector not working

### ISSUE THREAD

**Issue by Suwako-kero** [manga-download/hakuneko#6021]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Doesn't load the mangas

**To Reproduce**
1. Name of connector (LectorManga)
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Screenshot_1](https://github.com/manga-download/hakuneko/assets/42721382/acadda8a-b72e-4791-ab77-d1803c044d00)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Its not a bug. Just read what is written 🤦 . Some website does not provide accurate manga listing. You could have used Copy paste feature but this website wont work anyway, and cant fix because its Cloudflared

**Comment by Suwako-kero** [comment]
Oh... :[
