### ISSUE TITLE
ZINNOVEL Connector not working

### ISSUE THREAD

**Issue by Kiriri01** [manga-download/hakuneko#6024]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
**The connector not working properly. The app can't fetch new novel from the website.** 

**To Reproduce**
1. [zinnove](https://zinnovel.com/)
2. Failed to load resource: net::ERR_FILE_NOT_FOUND

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/97859566/5572de95-04d6-45f2-b7eb-318966b74685)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
> The connector not working properly. The app can't fetch new novel from the website.

but you answered

>Is the website of the connector working properly / are you able to see the manga **within your browser**
> No

If website doesnt work at all, hakuneko cant do anything :D

**Comment by Kiriri01** [comment]
ah, sorry, i mean, i can see the manga. there's update in the website. im sorry, i didn't read the question properly.
well, everytime i hit the reload button, those new novels didn't show up. but the old novels still uodating.
and the app stuck like this...

![image](https://github.com/manga-download/hakuneko/assets/97859566/76b7c9f9-d217-4031-a309-f35475d4437a)

**Comment by MikeZeDev** [comment]
In case you didnt saw, a fix in ready and just need approval :)
