### ISSUE TITLE
[Asura Scans] Connector not working

### ISSUE THREAD

**Issue by jhung0301** [manga-download/hakuneko#6025]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Connector doesn't show the chapter list or any of the new series when you try to refresh.

**To Reproduce**
1. Asura Scans
2. Name of manga - Click any
3. Name of chapter - Click any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
I think this connector isn't working because they changed their domain to https://asura.gg/

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Domains change, ok. Thanks <3

**Comment by ttasadasdw** [comment]
asura scan now not active, i can't download from this site

**Comment by Sheepux** [comment]
another domain change
Edit:  Use nightly version and change domain in program settings 😢
