### ISSUE TITLE
[Site Request]

### ISSUE THREAD

**Issue by noneplayers** [manga-download/hakuneko#6029]

**Comment by MikeZeDev** [comment]
o_o

1) no HTTPS in 2023? 
2) their so called "pictures" are PDF (despites being named jpeg)

I am afraid Hakuneko does not support pdf viewing :/

**Comment by noneplayers** [comment]
Thank you very much, if you want to do it later, please write to me (gta_yagame[at]hotmail.co.th), I'm willing to pay for this.

**Comment by MikeZeDev** [comment]
No money, no donations.

**Comment by noneplayers** [comment]
I understand, I just thought if you would do it. I just want to give you something for your time. Because I understand that this job is difficult.
