### ISSUE TITLE
[Flame Scan.fr] Connector not working

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6030]
**Describe the bug**
The website is dead

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://github.com/manga-download/hakuneko/assets/99205448/bf0f888d-f92a-496e-ba4d-d5d6d337f56d)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Thanks, next time try to use the pinned issue :)

**Comment by I-JMC** [comment]
Pinned issue ?

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/7f889015-2d3f-4754-8800-54607d2ea585)

The one on the right ^^

**Comment by I-JMC** [comment]
Oh ok thx
