### ISSUE TITLE
[KLManga] Connector not working

### ISSUE THREAD

**Issue by linuxbelletian** [manga-download/hakuneko#6032]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't get chapter list of manga

**To Reproduce**
1. select any manga of KLManga
2. load chapter list error
3. F12  to see http request . Here's a 301 redirect, then stuck at the new address

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
<img width="886" alt="Capture" src="https://github.com/manga-download/hakuneko/assets/8522288/c4687eac-c6c5-4655-80aa-3360cf709ed1">

**HakuNeko (please complete the following information):**
 - Version  6.17@513508

**Comment by MikeZeDev** [comment]
Ok i see
