### ISSUE TITLE
[Bug] Can't queue up anime for download

### ISSUE THREAD

**Issue by Xenabiliy** [manga-download/hakuneko#6033]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Description: When attempting to queue multiple anime for download, only one can be downloaded at a time. When queuing up the next anime, it appears with an exclamation mark and cannot be downloaded.

**To Reproduce**
1. Attempt to queue up multiple anime for download.
3. the first one works, but all the other queued one fails with the cloud icon replaced with an exclamation mark.

**Expected behavior**
I expect the app to download the queued-up anime one-by-one

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/139631182/de9d209e-4e88-460c-b1c3-4abb890e0873)

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version 6.1.7

**Additional context**
I can download them one by one, but queueing them won't work.

**Comment by MikeZeDev** [comment]
i just downloaded 2 in a row without problems 🤷 Idk what happened.

If you want to mass download anime by all means use torrents btw.

**Comment by Xenabiliy** [comment]
Thanks, but may I ask how can I use torrents to download?

**Comment by MikeZeDev** [comment]
Google
