### ISSUE TITLE
[Bug] Clipboard problem

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6034]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
The "open Clipboard website in new window" function doesn't work

**To Reproduce**
1. Go to 'Connectors'
2. Click on 'Clipboard'
3. Go to 'Connectors'
4. Click on 'Open link in a new window'
![image](https://github.com/manga-download/hakuneko/assets/99205448/79d35446-5b85-43ae-847c-e0ffd817dbc3)
6. See error: None (in F12)

**Expected behavior**
To open the link, I copied in the Clipboard (9anime.to which is already a working connector) in a new window 

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko 6.17 Stable Portable

**Additional context**
Doesn't work on both of my PCs.

**Comment by MikeZeDev** [comment]
Thats not how copy paste / clipboard function works. This button just does nothing on Clipboard "pseudo connector", its normal :)

**Comment by I-JMC** [comment]
Oh Ok, but the Clipboard connector still doesn't work for me though

**Comment by MikeZeDev** [comment]
This connector is a placeholder.  "the Clipboard connector doesn't work" doesnt make sense.
Just mention "clipboard doesnt work for this website."

**Comment by I-JMC** [comment]
I just don't understand the clipboard function in the connectors 😅

**Comment by MikeZeDev** [comment]
By all means, read the FAQ/doc 

https://hakuneko.download/docs/FAQ/

In case of doubt read manuals, they exists for a reason :D
https://hakuneko.download/docs/FAQ/#copy-and-paste

**Comment by I-JMC** [comment]
Ok thx
