### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6036]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
- Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
- No

**Is the website of the connector working properly / are you able to see the manga within your browser**
- Yes

**Describe the bug**
Idk tried to load Mangadex mangas

**To Reproduce**
1. Choose Mangadex as a connector
2. Click refresh

![image](https://github.com/manga-download/hakuneko/assets/99205448/97f23048-870f-4316-bdb6-176cf84debf0)
![image](https://github.com/manga-download/hakuneko/assets/99205448/7a14f1e5-b813-417c-810c-ed7706297eae)

**HakuNeko (please complete the following information):**
 - Version 6.17 Stable Portable

**Comment by MikeZeDev** [comment]
Use nightly , set an accurate "throttling delay" in settings for mangadex and wait. 

You could have searched recent closes issues btw. If mangadex got hiccups, you can be sure people will post an issue withing hours.

**Comment by I-JMC** [comment]
I can't use Nightly, it's not portable, or is it ?

**Comment by MikeZeDev** [comment]
yeah 
![image](https://github.com/manga-download/hakuneko/assets/10671518/2a1991b3-68d2-4b3d-ac91-cc26cabcb91d)

😉

**Comment by I-JMC** [comment]
GREAT, THX
Just a tiny problem, in Nightly, the close HakuNeko window is in the middle (which is not very intuitive) and it takes too much time to close HakuNeko in the parameters as the button is hidden by it 😅
![image](https://github.com/manga-download/hakuneko/assets/99205448/1067d743-472d-41a1-95b8-1858489814a3)

**Comment by MikeZeDev** [comment]
> GREAT, THX Just a tiny problem, in Nightly, the close HakuNeko window is in the middle (which is not very intuitive) and it takes too much time to close HakuNeko in the parameters as the button is hidden by it 😅

You'll get used to it ^^. Interface rework is present in next big version :p
