### ISSUE TITLE
[Feature] Lack of ideas ?

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6037]
**Miru**
I found out another anime downloader which is also based on electron n might give you some new great ideas
It also uses Electron !
https://github.com/ThaUnknown/miru

**Comment by MikeZeDev** [comment]
We already have some ideas for the upcoming version (2024?) but we are very busy right now, if you want a particular feature describe it in an issue :)

**Comment by I-JMC** [comment]
OK
