### ISSUE TITLE
[Site Request] Scan Hentai.Menu

### ISSUE THREAD

**Issue by Kiwi-ma** [manga-download/hakuneko#6039]
Name of the website
Scan Hentai.Menu

Website urls (examples below)

Site: https://scan.hentai.menu/
Manga List: https://scan.hentai.menu/manga/
Manga example: https://scan.hentai.menu/manga/maitresse/
Chapter online viewer example: https://scan.hentai.menu/manga/maitresse/maitresse/chapitre-35/
Languages
French

*Website relationship
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

Additional details
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Invalid request 
![image](https://github.com/manga-download/hakuneko/assets/10671518/79dce02e-ca47-481e-bb98-d87d89f2682a)
