### ISSUE TITLE
bookmarks gone

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#604]
> **From:** HakuNeko User

all my bookmarks disappeared

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Which version are you using?
Have you updated recently?
Have you checked the [User Data Directory](https://github.com/manga-download/hakuneko/wiki/User-Manual#22-user-data) for the file `hakuneko.bookmarks`?
Have you checked your HakuNeko settings for the path to the bookmark directory?

**Comment by 27136773** [comment]
No response => closed
