### ISSUE TITLE
[VRV (HiDive)] Connector not working

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6040]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
- Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
- No

**Is the website of the connector working properly / are you able to see the manga within your browser**
- IDK

**Describe the bug**
Wrong URL

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/99205448/4b452855-30f9-4f1e-8332-8f3298e90b8e)

**HakuNeko (please complete the following information):**
 - Version 6.17 Stable Portable

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/4980
