### ISSUE TITLE
[Site Request] www.comicsmode.com

### ISSUE THREAD

**Issue by Jchasa** [manga-download/hakuneko#6041]
**Name of the website**
www.comicsmode.com

**Website urls (examples below)**
- Site: https://www.comicsmode.com/
- Manga List: https://www.comicsmode.com/comics
- Manga example: https://www.comicsmode.com/comics/the-green-lantern-2018-chapters
- Chapter online viewer example: https://www.comicsmode.com/comics/the-green-lantern-2018-chapters/multi-page/1

**Languages**
English

**Website relationship*
NA

**Additional details**
NA

**Comment by MikeZeDev** [comment]
dead
