### ISSUE TITLE
[Site Request] readallcomics.com

### ISSUE THREAD

**Issue by Jchasa** [manga-download/hakuneko#6048]
**Name of the website**
readallcomics.com

**Website urls (examples below)**
- Site: https://readallcomics.com/
- Manga List: 
- Manga example: 
- Chapter online viewer example: https://readallcomics.com/frank-frazettas-death-dealer-14-2023/

**Languages**
English

**Website relationship*
[If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").]
(https://readallmanga.com/)

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Huh there is no grouping by issues (that would make a "manga") and mangalist would get 11k pages that is very bad.
Not sure its worth if you have to copy paste every chapter link but why not
