### ISSUE TITLE
[Feature] Select various mangas at same time

### ISSUE THREAD

**Issue by tester01101** [manga-download/hakuneko#6052]
I have a problem when I wanna download various mangas at same time, I can't select more than one manga, there is a button for download all chapters of one manga but the problem is when manga site don't organize mangas and every chapter seen like one different manga, is some frustrating when mangas have more than 30 chapters (a lot mangas I read have more than 150 chapters) and I need download one by one, so will be more easily if users could select all mangas they want and put them in queue with right click for download

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/382

Also its planned in haruneko, if not already done?

**Comment by Sheepux** [comment]
> Also its planned in haruneko, if not already done?

Already done indeed

**Comment by Anangaya** [comment]
How do I select a range of chapters without filtering with regex? Ctrl, shift keys doesn't do anything. It should be done like in WebToEpub where chapter selections work seamlessly.
I only found that hakuneko was capable of filtering with regex by going though these issues. For the moment using regex filtering is good enough for me.

**Comment by 27136773** [comment]
> How do I select a range of chapters without filtering with regex? Ctrl, shift keys doesn't do anything. It should be done like in WebToEpub where chapter selections work seamlessly. I only found that hakuneko was capable of filtering with regex by going though these issues. For the moment using regex filtering is good enough for me.

You don't, see #382
