### ISSUE TITLE
Hi how can i remove strip mode in pdf

### ISSUE THREAD

**Issue by Godfatherdeathlock** [manga-download/hakuneko#6055]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by Godfatherdeathlock** [comment]
![Screenshot_20230720_205723_OneDrive](https://github.com/manga-download/hakuneko/assets/140094191/8f77e492-18ab-412c-a860-ee251d63227b)
I downloaded chapter in form of pdf  from hakuneko but the problem is the images are appearing in strip mode and i want full screen image

**Comment by MikeZeDev** [comment]
Download as pictures, photoshop the images, create pdfs ? 

This question is outside what hakuneko can do i think

**Comment by Sheepux** [comment]
What is the actual expected behavior ? If it's to modify the actual image sent by the website it's not hakuneko related.

**Comment by Sheepux** [comment]
no response, closing
