### ISSUE TITLE
[Site Request] Futari

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#6056]
**Name of the website**
Futari

**Website urls (examples below)**
- Site: https://futari.info/
- Manga List: https://futari.info/manga/
- Manga example: https://futari.info/manga/saihate-ni-madou/
- Chapter online viewer example: https://futari.info/saihate-ni-madou-chapter-03/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream
