### ISSUE TITLE
[Feature] Resize parts in HakuNako

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6058]
### Is your feature request related to a problem? Please describe.
- No

### Describe the solution you'd like
- To resize parts in HakuNako

### Describe alternatives you've considered
- None

### Context (please complete the following information):
Your current HakuNeko Version 6.17 Stable Portable
Your current HakuNeko Version 8.3.4 Nightly Portable

### Additional context
![image](https://github.com/manga-download/hakuneko/assets/99205448/ff36f443-3bdd-42c8-a69e-b8ea93b1e100)

**Comment by Sheepux** [comment]
Already done in [haruneko](https://github.com/manga-download/haruneko) (next hakuneko version)
Interface preview here https://haruneko.pages.dev/
