### ISSUE TITLE
[Site Request] mangarawjp

### ISSUE THREAD

**Issue by jinto070** [manga-download/hakuneko#6061]
**Name of the website**
mangarawjp

**Website urls (examples below)**
- Site: https://mangarawjp.io/
- Manga List: https://mangarawjp.io/list/
- Manga example: https://mangarawjp.io/SPY%c3%97FAMILY-raw-free/
- Chapter online viewer example: 
- 
**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/0401a968-746b-4285-9b1d-03fb10584fd5)

Closing as dead
