### ISSUE TITLE
[Sushiscan] Connector not working

### ISSUE THREAD

**Issue by MarsouinVolant** [manga-download/hakuneko#6062]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the browser is obsolete.

**To Reproduce**
1. [https://sushiscan.net]
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
<img width="830" alt="2023-07-22_19h52_18" src="https://github.com/manga-download/hakuneko/assets/140271620/dee12722-528c-46c8-a5a3-b3c76b16e8a0">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]@513508

**Comment by MikeZeDev** [comment]
Duplicate, please search before next time

https://github.com/manga-download/hakuneko/issues/5615
