### ISSUE TITLE
[mangaraw] Downloaded pages not matching up with website 

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/hakuneko#6064]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Pages being shown and downloaded aren't matching up with the website order, for mangaraw.to. Also 

**To Reproduce**
1. Go to website `https://mangaraw.to/chapters/%e3%80%90%e7%ac%ac55.2%e8%a9%b1%e3%80%91%e3%82%be%e3%83%b3100%e3%80%9c%e3%82%be%e3%83%b3%e3%83%93%e3%81%ab%e3%81%aa%e3%82%8b%e3%81%be%e3%81%a7%e3%81%ab%e3%81%97%e3%81%9f%e3%81%84100%e3%81%ae%e3%81%93%e3%81%a8%e3%80%9c-raw/)` ([ゾン100 〜ゾンビになるまでにしたい100のこと〜 – Raw 【第55.2話】
2. Open same chapter in connector 
3. After first couple pages, the pages start to get mixed up

**Expected behavior**
Pages of both the connector and and actual website should be matching up

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 6.17

**Comment by MikeZeDev** [comment]
Please keep in mind that we are not japanese therefore its hard to find the manga you are referring just with the chapter url.

Regarding the issue : thats right, whats the hell is going on?  And we get Webp in the mix

**Comment by MikeZeDev** [comment]
Turns out using javascript allows us to get the good order 🤷

**Comment by PerseusRex** [comment]
> Turns out using javascript allows us to get the good order 🤷

**Comment by PerseusRex** [comment]
Just wanted to ask, the fix hasn't been merged yet right?

**Comment by MikeZeDev** [comment]
No. use nightly and wait please dont close issue until its merged.

**Comment by PerseusRex** [comment]
Got it, and yea sorry I accidently clicked the wrong one when asking that question.
