### ISSUE TITLE
[Bug] hobbyjapan.co.jp comic site changed

### ISSUE THREAD

**Issue by Yucie** [manga-download/hakuneko#6066]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Website changed

**To Reproduce**

**Expected behavior**
When open comic site https://firecross.jp/ebook/series/479
It cannot connect due to website changed.
When change the url to 
https://hobbyjapan.co.jp/ebook/series/479
It will show 404 Not found

**Screenshots**
![Clipboard01fdsafd](https://github.com/manga-download/hakuneko/assets/12384865/05d5dfe2-5f24-4a29-b684-513e99a6d4b2)

**Context (please complete the following information):**
OS: Windows 11
HakuNeko Version: 6.17@513508

**Additional context**

**Comment by MikeZeDev** [comment]
Website doesnt got mangas anymore. Lets consider it as dead.
 Idk why you talk about firecross .


* Marked website as dead in dead websites issues
*  Firecross is already requested anyway. Marked issue as duplicate and closed it

Duplicate https://github.com/manga-download/hakuneko/issues/3978
