### ISSUE TITLE
[alphapolis] Cannot download old comic

### ISSUE THREAD

**Issue by Yucie** [manga-download/hakuneko#6067]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Some old comic cannot download.

**To Reproduce**
When download from https://www.alphapolis.co.jp/manga/official/492000109
Except ep 8 and ep9 cannot download

**Expected behavior**
The image url show 403 but the comic can read from chrome.

**Screenshots**
![Clipboard02sfdsafds](https://github.com/manga-download/hakuneko/assets/12384865/5b5af6a3-ab63-4732-87c0-bd054c74b4dc)

![Clipboard03safdsdfsadf](https://github.com/manga-download/hakuneko/assets/12384865/991809d3-ec6c-4439-a128-919daed9344b)

**Context (please complete the following information):**
OS: Windows 11
HakuNeko Version: 6.17@513508

**Additional context**

**Comment by MikeZeDev** [comment]
interesting : turns out old comics dont have high resolution
