### ISSUE TITLE
[Coco漫画] Connector not working

### ISSUE THREAD

**Issue by Yucie** [manga-download/hakuneko#6068]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Paste the link to hakuneko will show 403

**To Reproduce**
1. Coco漫画
2. 如何隐藏皇帝的孩子  https://www.colamanhua.com/manga-al63814/
4. 403 (press F12)

**Screenshots**
![Clipboard02fsadfsda](https://github.com/manga-download/hakuneko/assets/12384865/36f444a3-6eba-4a1f-aa09-a6a6614191d8)

**HakuNeko (please complete the following information):**
OS: Windows 11
HakuNeko Version: 6.17@513508

**Comment by MikeZeDev** [comment]
Website is plagged by Cloudflare, bug is known, duplicate issue, cant fix
