### ISSUE TITLE
[Firecross] Connector not working

### ISSUE THREAD

**Issue by Yucie** [manga-download/hakuneko#6069]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
No matching connector found

**To Reproduce**
1. Firecross
2. Name of manga https://firecross.jp/ebook/series/479
3. 超!!! 天才発明令嬢のパワフル領地改革r (if manga update is working)
4. ClipboardConnector.mjs:66 CLIPBOARD: https://firecross.jp/ebook/series/479 Error: No matching connector found for URL https://firecross.jp/ebook/series/479
    at ClipboardConnector.mjs:59
    at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28)
    at HTMLElement.onUpdateMangaListClick (mangas.html:233)
    at HTMLElement.onPasteClick (mangas.html:339)
    at HTMLElement.handler (template-stamp.html:96)

**Screenshots**
![Clipboard01sdfdsfdsa](https://github.com/manga-download/hakuneko/assets/12384865/f97201a5-1d29-42a7-ab4c-5ad9c72d7f80)

**HakuNeko (please complete the following information):**
OS: Windows 11
HakuNeko Version: 6.17@513508

P.S I am so sorry for my wrong issue before.

**Comment by MikeZeDev** [comment]
Invalid issue. Website is not supported at all, why opening a bug issue for a website we dont support in the first place?
