### ISSUE TITLE
Download more than one manga at same time (Not chapters because this function already exists)

### ISSUE THREAD

**Issue by noobMob** [manga-download/hakuneko#6071]
Implement an option for download more than one manga at same time, when I use the program I can download all chapters of a specific manga of the section 2, but when I try to select other manga of this section with CTRL +click it doesn't work I think this option will very helpful when you wanna download various mangas, just selecting with CTRL + click or MAYUS + click and send them with all his chapters to the queue.
For example if I wanna download 3 AM Dangerous Zone, A Divine Love Alone, Anemone, Beaty Honey, Amazones Kiss and A Too Honest Guy if select one and another with CTRL+click until select all mangas I need and download with one button or with rigth click + download option something like this.
![image](https://github.com/manga-download/hakuneko/assets/140690470/321ce5cb-8521-41b8-ae0f-ef2fbca22ec5)

**Comment by MikeZeDev** [comment]
We wont do that. Its not meant to be a mass manga downloader
