### ISSUE TITLE
[bentomanga.com] Connector not working

### ISSUE THREAD

**Issue by labriochedu91** [manga-download/hakuneko#6073]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
CF ask upgrade browser

**To Reproduce**
1. CF
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![bm](https://github.com/manga-download/hakuneko/assets/72697881/b51d1edb-1416-43b1-881d-c708365b4eb6)

If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Duplicate issue
