### ISSUE TITLE
[YoungChampion.jp] Connector not working

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#6074]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
_GetChapter broken need to be fixed again.

**HakuNeko (please complete the following information):**
 - Nightly Version

**Comment by MikeZeDev** [comment]
Can you please link a non working manga?

**Comment by Ever4engel** [comment]
> Can you please link a non working manga?

https://youngchampion.jp/episodes/c8cc2e33cd67f

PS: hakuneko baited me 
![image](https://github.com/manga-download/hakuneko/assets/47645041/7cf24b04-bb54-4e82-a25b-1463261eeada)
