### ISSUE TITLE
[ManhuaPlus] Connector not working

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/hakuneko#6075]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector is not working for Martial Peak
Error : ERR_TOO_MANY_REDIRECT

It works well for the other manhua

**To Reproduce**
1. ManhuaPlus
2. Martial Peak

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Cant reproduce. Any particular chapter? 

Could be caused by shitty ads on the website 🤷, i got that right now in a naked browser. . Use a solution to block ads in host file on your computer, a vpn that blocks ads or change website.

**Comment by rs3mk** [comment]
Cloudflare is blocking him from entering any manhua from hakuneko's browser.

![cloud](https://github.com/manga-download/hakuneko/assets/19628943/ad5cb4d4-3d96-4232-8c02-948f8e6a761e)

**Comment by MikeZeDev** [comment]
Then you have tour answer :/ And please DONT CLOSE the issue as long as problem persist.

**Comment by tsentered** [comment]
For me ManhuaPlus stopped working yesterday. With a lot of titles (not just ManhuaPlus)I find that I have to click a title, nothing shows up, then click another title then the original title again and chapters would populate. Sometimes it would take multiple tries. This worked with Reaper Scan until about a month ago it stopped. This is now the case with Manhuaplus, as well.

**Comment by tsentered** [comment]
I worked just now. I took a screenshot of before and after download. That title is from Manhuaplus. Hope this helps.


<img width="694" alt="Screenshot 2023-10-09 at 3 26 25 PM" src="https://github.com/manga-download/hakuneko/assets/70929406/9967dd55-eb88-4a53-bd56-da3dd45f0ca9">
<img width="588" alt="Screenshot 2023-10-09 at 3 28 17 PM" src="https://github.com/manga-download/hakuneko/assets/70929406/e3f195a5-5664-4064-916b-e5e99eb04a10">

**Comment by MikeZeDev** [comment]
As long as the problem is Cloudflare its no use for everyone to tell "me too". You obviously can leave a message if it works again so the issue can be closed  :)

**Comment by didierGuieu** [comment]
Manhuaplus only used cloudflare when there is an issue on their website. Most of the time, it's temporary.
My issue was related to a cache corruption and it's solved now.
For my point of view, you can close this issue.
