### ISSUE TITLE
[AnimeUnity] Connector not working

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6079]
### **Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

### **Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

### **Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

### **To Reproduce**
1. AnimeUnity
2. Just reload the source

### **Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/99205448/33c967be-0cef-4317-ad15-4c32b1b927e7)
![image](https://github.com/manga-download/hakuneko/assets/99205448/35ea9b02-857b-4654-b1f0-4c83650e8a15)

### **HakuNeko (please complete the following information):**
 - Version 8.3.4 Nightly  Portable
 - Version 6.17 Stable Portable

**Comment by MikeZeDev** [comment]
AH. domain changed.
