### ISSUE TITLE
[9Anime] Connector not working

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6080]
### **Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

### **Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

### **Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

### **Describe the bug**
Anime list loads, but it doesn't matter what anime you click on it doesn't load the chapters, well at least it tries (same for source Animepahe)
New error (see screenshots)

### **To Reproduce**
1. 9Anime
2. Select an anime

### Screenshots
![image](https://github.com/manga-download/hakuneko/assets/99205448/06e91467-95f4-4a95-b405-0763aea0a681)

### **HakuNeko (please complete the following information):**
 - Version 6.17 Stable Portable
 - Version 8.3.4 Nightly Portable

**Comment by MikeZeDev** [comment]
I got chapters on AnimePahe, i dont know what going on for 9Anime.

Edit : Interesting changes. loving their CDN name <3

**Comment by MikeZeDev** [comment]
Also please dont talk about more than one website. Make a separate issue for each website :)

**Comment by I-JMC** [comment]
Ok sorry
