### ISSUE TITLE
[Site Request] Surya Scans

### ISSUE THREAD

**Issue by Coravon** [manga-download/hakuneko#6083]
**Name of the website**
Surya Scans

**Website urls (examples below)**
- Site: https://suryascans.com/
- Manga List: https://suryascans.com/manga/
- Manga example: https://suryascans.com/manga/the-miraculous-physical-therapist/
- Chapter online viewer example: https://suryascans.com/lord-of-money-chapter-113/

**Languages**
List of languages supported by the website
English

**Comment by MikeZeDev** [comment]
mangastream

**Comment by Murshid7absi** [comment]
@MikeZeDev website is a copy of asura scans

**Comment by MikeZeDev** [comment]
redirect to discord
