### ISSUE TITLE
https://www.anime-planet.com/manga/painter-of-the-night

### ISSUE THREAD

**Issue by dondiba** [manga-download/hakuneko#6085]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by dondiba** [comment]
https://www.anime-planet.com/manga/painter-of-the-night

**Comment by MikeZeDev** [comment]
Invalid request, template not filled, closing
