### ISSUE TITLE
[Site Request] ridibooks.com

### ISSUE THREAD

**Issue by EinarGravity** [manga-download/hakuneko#6087]
**Name of the website**
ridibooks.com

**Website urls (examples below)**
- Site: https://ridibooks.com/webtoon/recommendation
- Manga List: https://ridibooks.com/selection/1829
- Manga example: https://ridibooks.com/books/4883000611?_rdt_sid=webtoon_recommendation_ai_recommendation&_rdt_idx=4
- Chapter online viewer example: https://view.ridibooks.com/books/4883000611

**Languages**
Koreano

**Comment by MikeZeDev** [comment]
And duplicate again. Three in a row we have a winner 🎺 https://github.com/manga-download/hakuneko/issues/5387
