### ISSUE TITLE
[Site Request] pocketcomics.com

### ISSUE THREAD

**Issue by EinarGravity** [manga-download/hakuneko#6088]
**Name of the website**
pocketcomics.com

**Website urls (examples below)**
- Site: https://www.pocketcomics.com/
- Manga List: https://www.pocketcomics.com/menu/all_comic/read_for_free
- Manga example: https://www.pocketcomics.com/comic/9028
- Chapter online viewer example: https://www.pocketcomics.com/comic/9028/chapter/1/product

**Languages**
List of languages supported by the website

INGLES

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4222
