### ISSUE TITLE
[Site Request] manta.net

### ISSUE THREAD

**Issue by EinarGravity** [manga-download/hakuneko#6089]
**Name of the website**
manta.net

**Website urls (examples below)**
- Site: https://manta.net/en
- Manga List: https://manta.net/en/categories/Free%20Pass
- Manga example: https://manta.net/en/series/the-lady-alchemist?seriesId=2178
- Chapter online viewer example: https://manta.net/en/series/the-lady-alchemist/episodes/episode-1?episodeId=70721

**Languages**
List of languages supported by the website
ingles

**Comment by MikeZeDev** [comment]
Already rejected  https://github.com/manga-download/hakuneko/issues/5333
