### ISSUE TITLE
[nhentai.net] Connector not working

### ISSUE THREAD

**Issue by manikkuge-saumyadasa** [manga-download/hakuneko#6092]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Nhentai does not provide a manga list so the links are needed to be pasted manually, but when I do nothing comes up. However, I do still get some error messages. I will attach the screenshots below.

**To Reproduce**
1. Name of connector - nhentai.net
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working) - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) 

**Screenshots**
<img width="1415" alt="Screenshot 2023-08-01 at 07 38 46" src="https://github.com/manga-download/hakuneko/assets/110282720/8b582618-d526-4e21-8026-649d54f2dc74">

<img width="1415" alt="Screenshot 2023-08-01 at 07 39 01" src="https://github.com/manga-download/hakuneko/assets/110282720/82aa45e5-c281-4b10-b6fd-f1cbc806d1dc">

**HakuNeko (please complete the following information):**
 - Version [8.3.4]

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5987
