### ISSUE TITLE
[Feature] sort chapters by their number instead of their author

### ISSUE THREAD

**Issue by Aces-and-Jacks** [manga-download/hakuneko#6093]
**Is your feature request related to a problem? Please describe.**
when looking at the chapter list for series on magadex there can be two different uploaders and one can post a chapter the other did not do. And since it separates by uploader it makes it a little harder to find the other chapter. 

**Describe the solution you'd like**
Some sort of way to sort it different ways, for mangadex at least. I'm not sure how the other websites are. 

**Describe alternatives you've considered**
None

**Context (please complete the following information):**
 - Your current HakuNeko Version [6.1.7]

**Additional context**

**Comment by MikeZeDev** [comment]
Thats something tricky to do. How do you extract a chapter number without error? There is no fixed format, and we cant certainly code hacks for particular websites, especially when its prone to changes and errors.

Most of the time the naming scheme is not even coherent between chapters of the same manga on the same website.

Volume, Tome, Chapter, Bölüm, Epilogue, prologue, numbering mess..

That said, extracting a number from the title and use it to sort could be done, buts its just crappy.
Anyway, its a feature for HaRUneko.

**Comment by Aces-and-Jacks** [comment]
Well I was thinking more of just sorting by the name. So like if someone has `volume 1 chapter 3`, and `volume 1 chapter 7` then it could sort by that. It already does that...I think, but if the uploader is different then it separates it

**Comment by MikeZeDev** [comment]
If its just by name there is a button for that  🤦 

Read the docs :)

**Comment by Aces-and-Jacks** [comment]
oh...sorry
