### ISSUE TITLE
[Feature] Download with date created in file metadata (or whatever it's called)

### ISSUE THREAD

**Issue by Aces-and-Jacks** [manga-download/hakuneko#6094]
**Is your feature request related to a problem? Please describe.**
Not really a problem but an annoyance if certain chapters are named differently like epilogue instead of volume# chapter# 

**Describe the solution you'd like**
When a manga is downloaded if possible have the upload date of the chapter in the file data as date created.

**Describe alternatives you've considered**
N/A

**Context (please complete the following information):**
 - Your current HakuNeko Version [6.1.7]

**Additional context**
If it's only possible for singular websites, which sounds like it would be, instead of all as a whole then I mainly want it for mangadex since it's most used

**Comment by Aces-and-Jacks** [comment]
<img width="377" alt="Screen Shot 2023-08-01 at 2 39 25 AM" src="https://github.com/manga-download/hakuneko/assets/106651342/13beca51-eed7-4515-a7a4-00c1d297051b">

**Comment by MikeZeDev** [comment]
Most websites doesnt give the infos, and we dont extract it from the others. It would also require some engine modifications.
Huge work when you can just use another website with better naming convention :/

Wont Be done in Hakuneko, maybe haruneko idk.

**Comment by Sheepux** [comment]
Sorry, but that's not something we're going to extrract from the websites (too much extra work).
