### ISSUE TITLE
[Tappytoon (Frensh)] Connector not working

### ISSUE THREAD

**Issue by L0L01** [manga-download/hakuneko#6095]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Once i've clicked on Tappytoon (Frensh) site from HakuNeko, the site's home page opens with a loading loop in the middle. But it stays frozen and i can't connect to my account.

**To Reproduce**
1. Tappytoon (Frensh)
2. 
3. 
4. DevTools failed to parse SourceMap: https://www.tappytoon.com/fr/comics/web-frame.js.map
DevTools failed to parse SourceMap: https://www.tappytoon.com/fr/comics/window-setup.js.map
DevTools failed to parse SourceMap: https://www.tappytoon.com/fr/comics/reset-search-paths.js.map

**Screenshots**
![Sans titre](https://github.com/manga-download/hakuneko/assets/141184057/d23f16d0-1746-4a0a-a7eb-f3175303afa4)

**HakuNeko (please complete the following information):**
 - Version [6.1.7]

**Comment by MikeZeDev** [comment]
Why did you open the page? What were you trying to do?  🤔 

Manga listing works fine, chapters and page are loading fine too. 

And even opening the page like you did worked for me, no loading problem .

**Comment by L0L01** [comment]
> Pourquoi avez-vous ouvert la page ? Qu'est ce que tu essayais de faire? 🤔
> 
> La liste des mangas fonctionne bien, les chapitres et la page se chargent bien aussi.
> 
> Et même ouvrir la page comme vous l'avez fait a fonctionné pour moi, pas de problème de chargement.

Hi, i was told to come here to tell you about the problem i have with HakuNeko for Tappytoon (Frensh).
I asked a friend to try from her computer and it still doesn't work.
I find Tappytoon (Frensh) by searching in the connectors from HakuNeko but when i open it it freezes.
I don't know if the problem is with my computer or HakuNeko, but i don't think is with me

**Comment by L0L01** [comment]
![problem tappytoon frensh](https://github.com/manga-download/hakuneko/assets/141184057/b6d3c1ca-06eb-4259-b60c-0a7f3db962a8)
I get this when i click on f12, can anyone help me ?

**Comment by L0L01** [comment]
> ![problem tappytoon frensh](https://user-images.githubusercontent.com/141184057/257651865-b6d3c1ca-06eb-4259-b60c-0a7f3db962a8.png) I get this when i click on f12, can anyone help me ?


![problem tappytoon frensh from HN](https://github.com/manga-download/hakuneko/assets/141184057/5c9a0941-761b-448b-9b56-e8595f8990ac)

And this directly from HakuNeko

**Comment by MikeZeDev** [comment]
Pourquoi insistes-tu pour ouvrir le navigateur interne? 
Ce n'est pas comme cela que l'on utilise Hakuneko.
Lit le manuel avant d'ouvrir un ticket stp.

**Comment by MikeZeDev** [comment]
Désolé mais il n'y a rien que l'on puisse faire concernant le navigateur interne. On lui demande juste de charger le site, si il tourne en boucle cela n'est pas de notre ressort.  De mon côté en plus je n'ai pas ce problème :/

![image](https://github.com/manga-download/hakuneko/assets/10671518/dfdc6068-df34-459d-8682-8eefa16b925d)

**Comment by Sheepux** [comment]
Essaye avec la version "nightly"

**Comment by MikeZeDev** [comment]
Peut etre devrait tu essayer la version Nightly, mais si c'est pour se connecter avec un compte Google cela ne marchera pas de toute façon. 😢

**Comment by L0L01** [comment]
Ah i didn't know this version, thank you for your answers i'll try as you said so.

**Comment by L0L01** [comment]
It works ! Thanks a lot for your help. And sorry i'm new to this and haven't been using HakuNeko and Gitbug for long.
