### ISSUE TITLE
[Mangadex] Connector not working

### ISSUE THREAD

**Issue by thegoldenboy542** [manga-download/hakuneko#6096]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The browser for Mangadex is just a white screen

**To Reproduce**
1. Mangadex

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment]
>  The browser for Mangadex is just a white screen

Excuse me, but what? The browser? what browser?

**Comment by thegoldenboy542** [comment]
> > The browser for Mangadex is just a white screen
> 
> Excuse me, but what? The browser? what browser?

The in-built browser

**Comment by thegoldenboy542** [comment]
The site opens on my normal browser but when I try to open it in Hakuneko's in-built browser it doesn't work, I've also never had this bug up till now.

**Comment by thegoldenboy542** [comment]
It also seems to be only for mangadex, mangasee opens in the in-built browser

**Comment by MikeZeDev** [comment]
If you have any problem loading manga list, manga , chapter or picture on mangadex please state which one.

**Comment by thegoldenboy542** [comment]
> If you have any problem loading manga list, manga , chapter or picture on mangadex please state which one.

Yeah the manga list isn't working either, the connector itself doesn't seem to be working.

https://imgur.com/gallery/1uZfvgx

**Comment by MikeZeDev** [comment]
Ah i see, You should have explained that first ^^. 
And maybe looked for relevant issues, because it has been fixed last week ;). 

Use nightly, and increase throttling for mangadex in hakuneko settings.
Warning : fetching manga list will take some hours. Cant do better, MD is so popular, they must limit request to their servers.
