### ISSUE TITLE
[Kuaikan] Unable to find a manhua

### ISSUE THREAD

**Issue by 3O01** [manga-download/hakuneko#6097]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
The problem is here, it's only available on phone (But it works properly there).

**Describe the bug**
It's not loading a certain manhua only available on phone (link+name: [破云2：吞海](https://m.kuaikanmanhua.com/mobile/7121/list/))

**To Reproduce**
Just going for Kuaikan then searching the manhua in the list of manhua that appeared.

**HakuNeko (please complete the following information):**
 - I tried the last version of both...
 
 If u've any solutions or the possibility to add it, i'll be really grateful! (I'm translating it, and it's kind of an issue not to be able to get the raws.) Thanks in advance!
 Edit: just a little precision: I can open it in the in-built browser using the switching device in the dev tools and the copy/past thing. Tho, I don't know what else to do from there..

**Comment by MikeZeDev** [comment]
Your links lead to an empty page on PC. 
When you said on phone, is that through an app,  or does it works on the website? 

In case of an app-only manga, forget about it :/

**Comment by MikeZeDev** [comment]
Got it. After getting the fix when it lands on nightly,  make sure you are pasting the desktop link and not the mobile link :)
 
* https://www.kuaikanmanhua.com/web/topic/7121/  ✔️ 
* https://m.kuaikanmanhua.com/mobile/7121/list/ 🔴

**Comment by 3O01** [comment]
Oh thanks!, thought it'd not work since it's not showing on the browser. Tho now, there's no chapters on it

**Comment by MikeZeDev** [comment]
You just have to impersonate a mobile by changing user agent.
