### ISSUE TITLE
[Site Request] Kanzenin

### ISSUE THREAD

**Issue by Gisol789** [manga-download/hakuneko#6099]
**Name of the website**
Kanzenin

**Website urls (examples below)**
- Site: https://kanzenin.xyz/
- Manga List: https://kanzenin.xyz/a-z-list/
- Manga example: https://kanzenin.xyz/manga/asahina-ikka-netorareta-haha/
- Chapter online viewer example: https://kanzenin.xyz/asahina-ikka-netorareta-haha-chapter-3/

**Languages**
List of languages supported by the website
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream
