### ISSUE TITLE
mangahasu

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#61]
> **From:** user101

some of the manga in mangahasu is undownloadable. is there some explanation for this? also, i can't update the manga list for said site

**Comment by 27136773** [comment]
Are the mangas and chapters you are trying to download available via your web browser?
Please provide a sample manga and chapter to reproduce the issue.

**Comment by 27136773** [comment]
No additional data was provided and the problem could not be reproduced.
