### ISSUE TITLE
[Baozimh ] Connector not working

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#6107]
Hi,

Unable to load images for the above website.

https://www.baozimh.com/comic/manjiluchachuanchengxiaokelian-boyidongman_f

The browser is working fine but software not able to load/download the images.
<img width="1531" alt="Screenshot 2023-08-05 171148 p1" src="https://github.com/manga-download/hakuneko/assets/60792860/b1f08e02-2260-49c3-992a-67bbbb9f1af5">

<img width="954" alt="Screenshot 2023-08-05 171512 p2" src="https://github.com/manga-download/hakuneko/assets/60792860/58b88a85-acec-4300-a9e6-986d3d45eb68">

Anyone to help/solve this issue?

**Comment by MikeZeDev** [comment]
Like ive said, i got the same error on browser :/. Website doesnt display pages at all.

**Comment by suikodoen13** [comment]
For me...my browser is working fine. Website display the images....but this is not reflected in the software. Is the software not in sync with my brower??
<img width="956" alt="Screenshot 2023-08-06 002440 p1" src="https://github.com/manga-download/hakuneko/assets/60792860/c93fc5a7-c827-41ec-b05c-530b3fa072d8">
<img width="950" alt="Screenshot 2023-08-06 002550 p2" src="https://github.com/manga-download/hakuneko/assets/60792860/8fe4e967-c0bc-4add-b3bb-760439dd37cf">

**Comment by MikeZeDev** [comment]
Tried today, it fixed itself 🤷
