### ISSUE TITLE
[Feature Request] Enable/Disable toggle for Right side immovable panel and for auto-update of bookmarked titles

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [manga-download/hakuneko#6111]
**Is your feature request related to a problem? Please describe.**
**due to a connector taking FOREVER to update each title as I click on it I'd like to see a way to have it Auto-update anything that is bookmarked upon the program opening (and maybe a timed interval if the program is left open) so when I select a title it just opens up and is updated. I'm sure people on restricted connections wouldn't want this so make it toggle-able in the settings. Also the LARGE immovable panel on the right of the app that takes up too much space should also be on a toggle so I can get rid of it if so desired. I'd also like to see a way to have the language filer stay populated through title changes. say I am only looking for English translated content, It's annoying that I have to wait for the content to load THEN have to select the filter, Let the filter stay in place so I can have one less step.**

**Describe the solution you'd like**
**put toggles in settings menu to enable/Disable specified function/item. Make the language filter for content stick through title changes, possibly another settings entry "Default Content Language" or something like that.**

**Describe alternatives you've considered**
**Haven't really thought of "Plan B's" or how something would work since I don't know coding for what's doable or not.**

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]
 - **Current Nightly Build to my knowledge, as long as it auto-updates at program open like it says it does.**

**Additional context**
**none to add**

**Comment by Sheepux** [comment]
Right side pannel > open the settings disable reader
Auto updates, that's another request (do not request in same issues) ands the issue already exists (and it's a pinned one) https://github.com/manga-download/hakuneko/issues/653 also it's aready implemented in [haruneko ](https://github.com/manga-download/haruneko)(codename for next hakuneko version)

Regarding the filter, hakuneko isn't a search engine, usually people use a specific connector and just search by name. You can open a specific issue for that though.

(closing because duplicates)

**Comment by GeneralUser-NonDev** [comment]
> Right side pannel > open the settings disable reader 
**Thanks, that worked.**
>Auto updates, that's another request (do not request in same issues) ands the issue already exists (and it's a pinned one) #653 also it's aready implemented in [haruneko ](https://github.com/manga-download/haruneko)(codename for next hakuneko version)
**From reading that request I'm assuming the "Notification of changes" is the blue/grey text, However that is different from My idea of Loading the connectors titles, not quite downloading but having the Connector/Title ready for view/download, a sort of "Parse" if you will. Is this "Codename: Haruneko" and update to Hakuneko (if so idea of when implement-ed/-ing), or is that a separate program?**
> 
> Regarding the filter, hakuneko isn't a search engine, usually people use a specific connector and just search by name. You can open a specific issue for that though.
**Even if searching by connector titles can have multiple language translations in the filter field (Look at a bunch of MangaDex titles), I'm only looking for the English releases so I don't need a list of all the Portuguese, Russian, Spanish, etc languages the content is also translated in so a "lock in" of the language I'm looking for (Filter lock) would solve that. What is the point of the bookmark feature if "People load the full connector" instead of the titles they previously found and "Liked"? I still think this should be considered, but  I can't "Twist your arm" to make it happen.**
> 
> (closing because duplicates)

**Comment by Sheepux** [comment]
as i said you can open a dedicated feature request. Having a post with multiple topics is a nightmare to discusss
