### ISSUE TITLE
''failed dectect page type'' Connector not working

### ISSUE THREAD

**Issue by heif-3** [manga-download/hakuneko#6114]
![image](https://github.com/manga-download/hakuneko/assets/141563696/63a19683-5841-4169-91aa-2c25cbd8e7f4)
![Capture](https://github.com/manga-download/hakuneko/assets/141563696/f013f491-017c-4381-afdf-1ff7938e4d1b)

**HakuNeko (please complete the following information):**
 - Version lastest

**Comment by MikeZeDev** [comment]
We know for a while now and we cant do anything because of cloudflare, people keep reopening new tickets :/

**Comment by heif-3** [comment]
mes excuses! Mais est ce la fin de hakuneko ?
ce serait vraiment dommage si oui

**Comment by MikeZeDev** [comment]
Mais non c'est juste que la c'est pas corrigeable sans tout péter.
On travaille sur https://github.com/manga-download/hakuneko/ pour ca
