### ISSUE TITLE
[Site Request] manhwahentai.to

### ISSUE THREAD

**Issue by dbleach777** [manga-download/hakuneko#6115]
**Name of the website**
manhwahentai.to

**Website urls (examples below)**
- Site: https://manhwahentai.to/
- Manga List: https://manhwahentai.to/pornhwa/
- Manga example: https://manhwahentai.to/pornhwa/eleceed/
- Chapter online viewer example: https://manhwahentai.to/pornhwa/eleceed/chapter-1/

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Madara no Ajax

**Comment by tahzib1451** [comment]
would like this website added to the app as well...the included manhwahentai.me website has been down for quite some time

**Comment by MikeZeDev** [comment]
Normally, contributors would not have added it but since we have Manhwaclub that redirect to Manhwahentai.to, consider yourself lucky https://github.com/manga-download/hakuneko/pull/6865

**Comment by dbleach777** [comment]
Thank you I really appreciate it :) 
Btw I use portmaster (DNS changer) rather than VPN for bypass censorship & cloudfire (never encounter cloudfire page now) also it's faster than VPN & free to use for windows, linux &macOS. Just in case if you have problem with downloading in some website.

**Comment by dbleach777** [comment]
Thank you I really appreciate it :) 
Btw I use portmaster (DNS changer) rather than VPN for bypass censorship & cloudfire (never encounter cloudfire page now) also it's faster than VPN & free to use for windows, linux. Just in case if you have problem with downloading in some website.

**Comment by dbleach777** [comment]
> Normally, contributors would not have added it but since we have Manhwaclub that redirect to Manhwahentai.to, consider yourself lucky https://github.com/manga-download/hakuneko/pull/6865
> 
Thank you I really appreciate it :) 
Btw I use portmaster (DNS changer) rather than VPN for bypass censorship & cloudfire (never encounter cloudfire page now) also it's faster than VPN & free to use for windows, linux. Just in case if you have problem with downloading in some website.
