### ISSUE TITLE
https://baozimh.com/

### ISSUE THREAD

**Issue by RageMist** [manga-download/hakuneko#6117]
https://baozimh.com/ is not working for a few days for some reason, the comic list and chapters list is working fine but when I click on download or view. The images aren't showing up or being Downloaded. Can you Check it out please....
![image](https://github.com/manga-download/hakuneko/assets/69992781/90a1ac11-2dd9-4884-b30a-c7eaca0c103b)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6107

There is literally the same issue on the first page already its useless to open another :D

![image](https://github.com/manga-download/hakuneko/assets/10671518/6fb702bf-2a2a-43c2-a884-edbc92294a99)

Please look first
