### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by famouslybreak** [manga-download/hakuneko#6118]
Happymh

- Site: https://happymh.com/
- Manga List: https://m.happymh.com/latest
- Manga example: https://m.happymh.com/manga/manmenfanpaifengpiweiyoushimeidoubi
- Chapter online viewer example: https://m.happymh.com/reads/manmenfanpaifengpiweiyoushimeidoubi/3692453

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already requested, Please use the search feature

Duplicate https://github.com/manga-download/hakuneko/issues/3390
