### ISSUE TITLE
[asurascan.gg] Connector not working

### ISSUE THREAD

**Issue by Sleepless001** [manga-download/hakuneko#6120]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can enter in asurascan connector and find my manga but the chapter is not there but the manga name is avaiable I try to refresh it but doesnt work any manga in asurascan cant download no matter how many times I refresh close and open same result

**To Reproduce**
1. Name of connector asurascan https://asura.gg/
2. Name of manga (infinite mage)
3. Name of chapter ( chapter 1 to 44)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/141658081/86e00735-429e-4926-8af6-7bc8d7c271dd)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Use nightly, as suggested in the template
