### ISSUE TITLE
[fmteam] Connector not working

### ISSUE THREAD

**Issue by notoraptor** [manga-download/hakuneko#6122]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hello! It seems FMTeam website was updated with a new layout/CMS: https://fmteam.fr/

Since then, connector is not working.

### To Reproduce

Connector: fmteam

Manga list and chapter list are not working.

**Comment by MikeZeDev** [comment]
Oh boy, its that, pizza reader? 
Gotta check that, thanks
