### ISSUE TITLE
[Site Request] KomikRealm

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#6123]
**Name of the website**
KomikRealm

**Website urls (examples below)**
- Site: https://www.komikrealm.my.id/
- Manga List: https://www.komikrealm.my.id/p/project-list.html
- Manga example: https://www.komikrealm.my.id/2023/06/leveling-up-with-skills.html
- Chapter online viewer example: https://www.komikrealm.my.id/2023/08/leveling-up-with-skills-chapter-29.html

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
The more you open issues for the same website the less i want to add it we are not at your service stop being impatient its rude.
You already opened 3 issues, calm down.

Last warning.

Duplicate https://github.com/manga-download/hakuneko/issues/5696
