### ISSUE TITLE
[DouijinDesu] Domain Change

### ISSUE THREAD

**Issue by myth-riel** [manga-download/hakuneko#6125]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Chapter list isn't refreshing because domain change to https://doujindesu.tv

### To Reproduce

1. DoujinDesu
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by ryoiki-debug** [comment]
kenapa pas pencet link doujindesu nya ga bisa kebuka trus tulisan nya doujindesu menolak terhubung
