### ISSUE TITLE
[<Komikcast>] Domain Change, Connector not working

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#6132]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [x] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

domain change to komikcast.vip

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
new url doesnt load at all in haku

![image](https://github.com/manga-download/hakuneko/assets/10671518/9a2ab73d-a4a0-4cea-9347-071e4a21a5b9)

**Comment by MikeZeDev** [comment]
Cant even close the window, wtf with this website?

**Comment by black0888** [comment]
i dont know either, but in browser normal
