### ISSUE TITLE
[Site Request] happymh.com

### ISSUE THREAD

**Issue by AyanoKiru** [manga-download/hakuneko#6134]
**Name of the website**
m.happymh.com

**Website urls (examples below)**
- Site: https://m.happymh.com/
- Manga List: https://m.happymh.com/latest
- Manga example: https://m.happymh.com/manga/meizitaiduozhihaofeishengle
- Chapter online viewer example: https://m.happymh.com/reads/meizitaiduozhihaofeishengle/3214734

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate : https://github.com/manga-download/hakuneko/issues/3390
