### ISSUE TITLE
[Site Request] manhuatai.org

### ISSUE THREAD

**Issue by AyanoKiru** [manga-download/hakuneko#6136]
**Name of the website**
manhuatai.org

**Website urls (examples below)**
- Site: http://www.manhuatai.org/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: http://www.manhuatai.org/comics/10329.html
- Chapter online viewer example: http://www.manhuatai.org/manhua/10329/1061965.html

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Http only :/
