### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by Sildran** [manga-download/hakuneko#6140]
### Is there an existing issue for this connector?

- [x] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Can't update MangaDex's list after reaching a certain point.
![2023-08-13 09_10_02-HakuNeko](https://github.com/manga-download/hakuneko/assets/6168457/dc9b2f3b-4b6b-40a7-92f2-ff7688d9ad2f)

### To Reproduce

1. MangaDex
2. Try to update

**Comment by MikeZeDev** [comment]
> Is there an existing issue for this connector?

Indeed but the issue is CLOSED because its FIXED :)

Do what i said in this issue
https://github.com/manga-download/hakuneko/issues/6096

**Comment by Sildran** [comment]
Thank you Mike ;)  I didn't check the closed requests ; my bad :/

Increased the throttling from 3000 > 6000 and 1000 > 3000. It's updating without issue now :)

**Comment by MikeZeDev** [comment]
No problem that isnt necessarily intuitive :)
