### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by quinxo117** [manga-download/hakuneko#6141]
**Name of the website**
Mangatoto

**Website urls (examples below)**
- Site: https://mangatoto.com/
- Manga List: https://mangatoto.com/series/86975/berserk-official
- Manga example: https://mangatoto.com/chapter/2248232
- Chapter online viewer example: hhttps://mangatoto.com/chapter/2248232

**Languages**
English

**Website relationship*
N/A

**Additional details**
N/A

**Comment by MikeZeDev** [comment]
We obviously support BATOTO already
