### ISSUE TITLE
[Site Request] https://comikey.com/

### ISSUE THREAD

**Issue by EinarGravity** [manga-download/hakuneko#6145]
**Name of the website**
comikey

**Website urls (examples below)**
- Site: https://comikey.com/
- Manga List: https://comikey.com/comics/?order=name
- Manga example: https://comikey.com/comics/so-ill-fall-for-you-webtoon/622/
- Chapter online viewer example: https://comikey.com/read/so-ill-fall-for-you-webtoon/egOdne/episode-1/

**Languages**
Ingles

**Comment by MikeZeDev** [comment]
eeeeeeh did you even check before posting an issue? :D

![image](https://github.com/manga-download/hakuneko/assets/10671518/971e2538-7b46-4848-8bae-865b729ad360)
