### ISSUE TITLE
[1st Kiss Manga] Change url to https://likemanga.io

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#6149]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Announcement in their website
![Screenshot_2023-08-15-15-28-47-952_eu kanade tachiyomi](https://github.com/manga-download/hakuneko/assets/53214405/054014de-ffcc-41d8-bec6-d5e1365b2995)

### To Reproduce

1. 1st kiss manga is working but no new chapter update
2. There's announcement in their site that they gonna change to https;//likemanga.io
3. Likemanga.io is already running
![Screenshot_2023-08-15-15-28-47-952_eu kanade tachiyomi](https://github.com/manga-download/hakuneko/assets/53214405/5ad1d399-edab-466a-91fd-ce5380700d9e)

**Comment by MikeZeDev** [comment]
and they changed template too? meh ok
