### ISSUE TITLE
[Site Request] younganimal.com

### ISSUE THREAD

**Issue by dragows** [manga-download/hakuneko#6155]
Name of the website
younganimal

Website urls (examples below)
- Site: https://younganimal.com/
- Manga List: https://younganimal.com/series/list
- Manga example: https://younganimal.com/series/5d1e949cd0b52
- Chapter online viewer example: https://younganimal.com/episodes/b640d00b436a7

Languages
Japonese

Website relationship
same reader youngchampion and bigcomics

Additional details
Use comicihandler as reader

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/5556
