### ISSUE TITLE
[doujindesu] Domain change

### ISSUE THREAD

**Issue by kyoukun22** [manga-download/hakuneko#6156]
**Name of the website**
Doujindesu.tv

**Website urls (examples below)**
- Site: https://doujindesu.tv/
- Manga List: https://doujindesu.tv/manga/
- Manga example: https://doujindesu.tv/manga/missy-neighbors/
- Chapter online viewer example: https://doujindesu.tv/missy-neighbors-chapter-06/

**Languages**
Indonesian
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/blob/66877d7694cc8d2fc90271610ff2fafbf2d3553e/src/web/mjs/connectors/DoujinDesu.mjs#L4

Fixed last week already, search before please ;-;

**Comment by Sukrisima** [comment]
No problem link

**Comment by csdewa** [comment]
thanks for share 

Best Regard
[Dewa](https://dolarberaparupiah.id/author/dewapoker/)

**Comment by marthasimons8888** [comment]
Thanks for reporting this issue! I found this resource that might help: [Click here](https://rickycasino3.com/)
Hope it’s useful!
