### ISSUE TITLE
[MangaGreat] Domain changed

### ISSUE THREAD

**Issue by ignatiousb** [manga-download/hakuneko#6161]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list isn't refreshing. Existing bookmarks also isn't refreshing.

### To Reproduce

1. MangaGreat

4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

On refresh manga list, network log shows:
1. admin-ajax.php shows status 301 
2. followed by a fetch of admin-ajax.php that returned status 400

**Comment by MikeZeDev** [comment]
301 is redirect. Website changed url maybe. In that case you could have given the new url from the following fetch :) oh well no pb gotta check.

Edit : Its just domain change.
