### ISSUE TITLE
[Site Request] Tenshi.ID

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#6163]
**Name of the website**
Tenshi.ID

**Website urls (examples below)**
- Site: https://tenshi.id/
- Manga List: https://tenshi.id/komik/
- Manga example: https://tenshi.id/komik/worlds-apocalypse-online/
- Chapter online viewer example: https://tenshi.id/worlds-apocalypse-online-chapter-244-bahasa-indonesia/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream
