### ISSUE TITLE
[Site Request] Manga District

### ISSUE THREAD

**Issue by markace123** [manga-download/hakuneko#6164]
**Name of the website**
Manga District

**Website urls (examples below)**
- Site: https://mangadistrict.com/
- Manga List: https://mangadistrict.com/read-scan/
- Manga example: https://mangadistrict.com/read-scan/my-kingdom/
- Chapter online viewer example: https://mangadistrict.com/read-scan/my-kingdom/chapter-159/

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5515

**Comment by markace123** [comment]
ok. Thank you. Just want to ask what does "No more CF" means?
