### ISSUE TITLE
[<doujindesu.TV>] Connector not working

### ISSUE THREAD

**Issue by nopolare** [manga-download/hakuneko#6169]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

im already read and copy the connector form [[hakuneko/src/web/mjs/connectors/DoujinDesu.mjs](https://github.com/manga-download/hakuneko/blob/66877d7694cc8d2fc90271610ff2fafbf2d3553e/src/web/mjs/connectors/DoujinDesu.mjs#L4)](https://github.com/manga-download/hakuneko/issues/6156)
 but still not working
![asd](https://github.com/manga-download/hakuneko/assets/107017591/f507a3a9-69d1-4026-9ec6-01b2ec47b05a)
how to fix it thanks

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
>> im already read and copy the connector form

Copied? copied what? you dont need to copy anything :D Just use nightly .

I can confirm it works . I refreshed manga list. Please ignore the censorsheep.

![image](https://github.com/manga-download/hakuneko/assets/10671518/db378590-7b8f-4eb9-ad47-24bf5965f976)


And the screen you posted shows literally nothing. Are you able to see the website on your browser?

**Comment by nopolare** [comment]
> > > im already read and copy the connector form
> 
> Copied? copied what? you dont need to copy anything :D Just use nightly .
> 
> I can confirm it works . I refreshed manga list. Please ignore the censorsheep.
> 
> ![image](https://user-images.githubusercontent.com/10671518/262968279-db378590-7b8f-4eb9-ad47-24bf5965f976.png)
> 
> And the screen you posted shows literally nothing. Are you able to see the website on your browser?


Already using the copy connector method and reinstalling the latest version of Nightly or using the portable, the case is still the same. so where is the error? after refreshing it's always like that

**Comment by MikeZeDev** [comment]
> the copy connector method ? 

Excuse me but what is that? if you talk about clipboard method its working too i just tested. What are you pasting ?

**Comment by nopolare** [comment]
sorry beacuase im busy and cant replay asap, btw it turns out that the app has an IP block, but I open it with browser everything is ok. Is there any solution to set DNS in the app?

**Comment by MikeZeDev** [comment]
> sorry beacuase im busy and cant replay asap, btw it turns out that the app has an IP block, but I open it with browser everything is ok. Is there any solution to set DNS in the app?

Unfortunately, its not Hakuneko job to circumvent ip blocking. Use a VPN or change your DNS on your system.
Doing that will not only help, but overall you may have a better browsing experience.  

I am closing this now, sorry for not being helpful

**Comment by Putra-genk** [comment]
![Screenshot_2024-10-14-01-22-26-541_com android chrome](https://github.com/user-attachments/assets/69927550-e81e-4c71-a7d4-97bb6a6b49ce)
Ini kaya mna min

**Comment by MikeZeDev** [comment]
Dont spam old issues
