### ISSUE TITLE
[Site Request] Miauscans

### ISSUE THREAD

**Issue by cloudbladed1** [manga-download/hakuneko#6170]
**Name of the website**
miauscans

**Website urls (examples below)**
- Site: https://miauscans.com/
- Manga List: https://miauscans.com/manga/
- Manga example: https://miauscans.com/manga/la-era-de-oman/
- Chapter online viewer example: https://miauscans.com/la-era-de-oman-capitulo-5/
**Languages**
Spanish and Portuguese.

**Additional details**
Madara

**Comment by MikeZeDev** [comment]
Dev note : this one is NOT Miauscan but Miauscans, so no duplicate.
Just another Mangastream website.

**Comment by MikeZeDev** [comment]
Already supported, but need url change
