### ISSUE TITLE
[Site Request] MangaStic

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#6173]
**Name of the website**
MangaStic

**Website urls (examples below)**
- Site: mangastic7.com
- Manga List: https://mangastic7.com/?s=&post_type=wp-manga
- Manga example: https://mangastic7.com/manga/the-big-shots-darling-returns/
- Chapter online viewer example: https://mangastic7.com/manga/the-big-shots-darling-returns/chapter-0/

**Languages**
English

**Comment by MikeZeDev** [comment]
Madara again

**Comment by siennk** [comment]
Naruto??

**Comment by MikeZeDev** [comment]
dead
