### ISSUE TITLE
[MANHWA TOP] Connector not working 403

### ISSUE THREAD

**Issue by Xenos4th** [manga-download/hakuneko#6176]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

 Connector.mjs:434 POST https://manhwatop.com/wp-admin/admin-ajax.php 403

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
cant fix

**Comment by blueboned** [comment]
Mister what can be the Problem?

**Comment by Xenos4th** [comment]
In my case, my internet provider block it, so use vpn
