### ISSUE TITLE
[Site Request] READ COMICS PLUS

### ISSUE THREAD

**Issue by youssefadly237** [manga-download/hakuneko#6178]
**Name of the website**
Ream Comics +

**Website urls**
- Site: https://readcomicsplus.com
- Manga List: https://readcomicsplus.com/comic-list/alphabet
- Manga example: https://readcomicsplus.com/comic/spider-verse-unlimited-infinity-comic
- Chapter online viewer example: https://readcomicsplus.com/spider-verse-unlimited-infinity-comic/issue-9

**Languages**
- English

**Comment by MikeZeDev** [comment]
Probably similar to comic extra and others

**Comment by MikeZeDev** [comment]
dead website
