### ISSUE TITLE
[comic-days.com] Connector not working

### ISSUE THREAD

**Issue by zackultimate** [manga-download/hakuneko#6180]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

new monthly chapters don't appear 

### To Reproduce

1. Name of connector
https://comic-days.com
3. Name of manga (if connector update is working)
Any manga on the site
5. Name of chapter (if manga update is working)
7. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Please link a manga and name the chapter that should appear.

Is that paid chapter? Are you opening a magazine link? So many questions .
