### ISSUE TITLE
[Comic Fuz] Connector not working

### ISSUE THREAD

**Issue by Khangry** [manga-download/hakuneko#6184]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

I can't download any chapter.

### To Reproduce

1. Comic Fuz
2. After Kissing Many Girls, I Became A Yuri Kisser... (色んな女の子とキスをしていたら、百合キスに目覚めてしまいました…)
3. All chapter

**Comment by MikeZeDev** [comment]
server is a bit slow but it works :shrug:

![image](https://github.com/manga-download/hakuneko/assets/10671518/41fd861e-7f09-405b-9e8f-ad243b99c144)
