### ISSUE TITLE
[gooffansub] Site changed domain

### ISSUE THREAD

**Issue by Akimanga** [manga-download/hakuneko#6185]
**Goof Fansub**

- Site: https://gooffansub.com/

- Manga List: https://thewebsiteurl/mangalist.html

- Manga example:
https://gooffansub.com/manga/cry-me-a-river/

- Chapter online viewer example: 
https://gooffansub.com/manga/cry-me-a-river/capitulo-01/

**Languages**
Portuguese

**Website relationship*

**Additional details**

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
Btw @Akimanga you requested maaany websites . I am afraid we are very busy but the good news is you requested ez websites. They all use madara template. If you look in hakuneko source you see how you can easily add them yourself and submit the changes. Or maybe someone will do that.

**Comment by Akimanga** [comment]
Can you tell me how to include it? Can I help?

**Comment by MikeZeDev** [comment]
As for how to code a Madara plugin, you can look for an exemple file here : https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/AHStudios.mjs.

* Name the new file using website name : **GoofFansub.mjs**
* Make sure the class name match the file name (same case) : 

`export default class GoofFansub extends WordPressMadara {`

* Make sure the id is lowercase and doesnt already exists in hakuneko: 

`        super.id = 'gooffansub';`

* change website label : 

`        super.label = 'Goof Fansub ';`

* Fix tags for language and content type

`        this.tags = [ 'manga', 'webtoon', 'portuguese' ];`


* put the good website url without leading /

`        this.url = 'https://gooffansub.com';`


* Put the file in `C:\Users\<yourname>\AppData\Local\hakuneko-desktop\cache\mjs\connectors\`, and restart hakuneko. TEST IT.
(refresh manga list, get chapters, and pictures)

* Prepare a website icon. PNG file, max size 96x96, < 10kb, File name must match the id and CANT have any extension  
  GoofFansub.png ⛔ 
  gooffansub ✔️ 

* put that file inside `C:\Users\<yourname>\AppData\Local\hakuneko-desktop\cache\img\connectors`, restart hakuneko et check if gooffansub got a logo.

If you already do that, i'll explain how to submit it

**Comment by MikeZeDev** [comment]
Now to submit your first change : 

* Fork Hakuneko so you can work on your own copy 
![image](https://github.com/manga-download/hakuneko/assets/10671518/2e2c9a70-ebfb-401e-938e-671baff61ce5)

* Go to your fork, create a branch , so you will make specific change for a specific website on a specific branch 
 https://www.howtogeek.com/714112/how-to-create-a-new-branch-in-github/

* Make sure your new branch is selected, and upload your files in the good folder : 

MJS FILE
![image](https://github.com/manga-download/hakuneko/assets/10671518/f440faab-5d75-4fba-812b-5b260be8d5a4)

Icon file 

![image](https://github.com/manga-download/hakuneko/assets/10671518/c7f7168b-677f-4837-b1cc-2b713d00acf7)

* Then create a PR, aka "pull request" to apply your changes to the main hakuneko repository (ours)
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork


When you want to add support for another website, repeat 
* create branch
* upload files on branch
* submit a pull request

**Comment by MikeZeDev** [comment]
Renamed issue as the site was already supported but changed domain.
