### ISSUE TITLE
[Site Request] Mizu Mangás

### ISSUE THREAD

**Issue by Akimanga** [manga-download/hakuneko#6188]
**Name of the website**
Mizu Mangás

**Website urls (examples below)**
- Site: https://mizumangas.com.br/

- Manga example: https://mizumangas.com.br/manga/532/
- Chapter online viewer example: https://mizumangas.com.br/manga/reader/21487/

**Languages**
Portuguese

**Comment by MikeZeDev** [comment]
Cant do geoblocked

**Comment by MikeZeDev** [comment]
dead?
