### ISSUE TITLE
Hakuneko can't download some chapters

### ISSUE THREAD

**Issue by dragon031288** [manga-download/hakuneko#619]
Some chapters of the manga have 1 fail image and hakuneko refused to download the whole chapter. Is there any way if we can force hakuneko to download that chapter since it has only 1 fail image only and the rest still ok ?

**Comment by 27136773** [comment]
Need to update FAQ why HakuNeko will not download chapters which have broken images...

**Comment by 27136773** [comment]
See updated [FAQ](https://github.com/manga-download/hakuneko/wiki/FAQ)
