### ISSUE TITLE
[Site Request] Lumix Fansub

### ISSUE THREAD

**Issue by Akimanga** [manga-download/hakuneko#6195]
Name of the website
Lumix Fansub

Website urls (examples below)

Site: https://nixfansub.com.br/

Manga example: https://nixfansub.com.br/manga/order-of-salvation/

Chapter online viewer example: https://nixfansub.com.br/manga/order-of-salvation/capitulo-1/

Languages
Portuguese

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
passworded
