### ISSUE TITLE
[Site Request] Pink Sea Unicorn

### ISSUE THREAD

**Issue by Akimanga** [manga-download/hakuneko#6196]
Site: Name of the website
Pink Sea Unicorn

Website urls (examples below)

Site: https://psunicorn.com/ 

Manga example: https://psunicorn.com/manga/bye-bye/ 

Chapter online viewer example: https://psunicorn.com/manga/bye-bye/capitulo-42/ 

Languages
Portuguese

**Comment by MikeZeDev** [comment]
Duplicate #5705
