### ISSUE TITLE
[Manhwalist] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#6198]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

![image](https://github.com/manga-download/hakuneko/assets/112748173/6e1c7678-9d56-454c-8de4-588f3ae209bc)
![image](https://github.com/manga-download/hakuneko/assets/112748173/530c138f-9aca-4484-85f4-3c08db7df397)
![image](https://github.com/manga-download/hakuneko/assets/112748173/ddc3d5de-ff82-469b-8967-58de9f145c0a)
cant see new chapter

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
There is not logical reason for that. The only filter we apply on chapters are for site with paid chapters. i will check.

Edit : you are on https://manhwalist.com. Hakuneko use https://manhwalist.xyz which is still at chapter 17

![image](https://github.com/manga-download/hakuneko/assets/10671518/ce5e3e92-622f-497f-b138-70ee74103555)
![image](https://github.com/manga-download/hakuneko/assets/10671518/33ab3fd1-3e58-48ff-a09d-ba00526cf36f)

Website xyz redirect to com, but the xyz url of the manga is not redirecting., what a mess.
