### ISSUE TITLE
Readrawmanga.com & youbamangablog.ga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#62]
> **From:** HakuNeko User

Nothing showing on readrawmanga.com the site is working but has a new look

YouBa titles and chapters show but doesn't download and the site is working as normal

Thanks

**Comment by 27136773** [comment]
Related: #59

**Comment by 27136773** [comment]
Confirmed:
readrawmanga has updated that website layout and HakuNeko needs to adapt the new requests, pagination and CSS selectors.

**Comment by 27136773** [comment]
Problem with www.youbamanga.ga cannot be reproduced, it works as expected.
Please provide a sample manga and chapter that did not work.
