### ISSUE TITLE
Plot Twist Scan not work

### ISSUE THREAD

**Issue by rs3mk** [manga-download/hakuneko#620]
Hi.

Plot Twist Scan, not load chapters
Plot Twist No Fansub, not load manga (It only works when pasting direct link.).

![plot-twist](https://user-images.githubusercontent.com/19628943/68499198-99c41a00-0226-11ea-9d33-0f5db2242bff.png)

regards

**Comment by 27136773** [comment]
Have you tried re-syncing/updating the mangalist? The links might have changed...
