### ISSUE TITLE
[YugenMangas] Connector not working

### ISSUE THREAD

**Issue by Lyze03** [manga-download/hakuneko#6201]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [x] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Failed to receive content from " https://api.yugenmangas.com/series/querysearch " (status: 526) -

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Well they changed from .com to .net. Ofc it wont work anymore.

**Comment by MikeZeDev** [comment]
oops
