### ISSUE TITLE
[managfox] Connector not working but just on a single manga using clipboard

### ISSUE THREAD

**Issue by kevin01523** [manga-download/hakuneko#6204]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

i copy a manga then click the clipboard manga and its just load infinitely but it works on other manga

http://fanfox.net/manga/waga_gyouyuu_ni_furueyo_tenchi_arekushisu_teikoku_kouryuuki/

### To Reproduce

1. mangafox
2. [[Name of manga (if connector update is working)](http://fanfox.net/manga/waga_gyouyuu_ni_furueyo_tenchi_arekushisu_teikoku_kouryuuki/)]
3. any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/8380242/647e2f76-897d-4722-b4a2-f6545af7a05d)
but it loads fine on browser

after changing ip via vpn

![image](https://github.com/manga-download/hakuneko/assets/8380242/142e9eb0-cd5d-421e-ba32-9120d3783ee9)

EDIT: after a few tries it worked now but yeah it failed a last night and 30 minutes ago,,,,,,

just keeping it here for reference i guess if it stops working again

**Comment by MikeZeDev** [comment]
You have copied only the last part of the url, ofc if wont work its not a real url :). So we get an "invalid URL" error .

If i paste only "waga_gyouyuu_ni_furueyo_tenchi_arekushisu_teikoku_kouryuuki" i can reproduce your error.
![image](https://github.com/manga-download/hakuneko/assets/10671518/e039c2a5-05bc-467a-bc33-c1bc63ca14f9)

the full url works without problem
http://fanfox.net/manga/waga_gyouyuu_ni_furueyo_tenchi_arekushisu_teikoku_kouryuuki/

![image](https://github.com/manga-download/hakuneko/assets/10671518/5f55b84e-d609-46f0-988b-ff9a466e2ee9)
