### ISSUE TITLE
[<yanmaga.jp>] Connector not working

### ISSUE THREAD

**Issue by arifsyahbani** [manga-download/hakuneko#6207]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

After ctrl + V the yanmaga.jp link to the clipboard, nothing happens. 
![image](https://github.com/manga-download/hakuneko/assets/45502806/40d94039-619c-46d0-b9cb-9b5364d19924)

### To Reproduce

1. Name of connector : yanmaga.jp
2. Name of manga (すぐ泣く先輩 - https://yanmaga.jp/comics/%E3%81%99%E3%81%90%E6%B3%A3%E3%81%8F%E5%85%88%E8%BC%A9)
3. Name of chapter (not working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

```
ClipboardConnector.mjs:66 CLIPBOARD: https://yanmaga.jp/comics/%E3%81%99%E3%81%90%E6%B3%A3%E3%81%8F%E5%85%88%E8%BC%A9 TypeError: Cannot read property 'textContent' of undefined
    at Yanmaga._getMangaFromURI (Yanmaga.mjs:27)
    at async hakuneko:/cache/mjs/connectors/system/ClipboardConnector.mjs:64
    at async Promise.all (index 0)
(anonymous) @ ClipboardConnector.mjs:66
```

![image](https://github.com/manga-download/hakuneko/assets/45502806/681f8d8d-da9f-43ac-995d-dd6195e8bf29)

**Comment by MikeZeDev** [comment]
> Manga list isn't refreshing

It works for me.

> After ctrl + V 

Because CTRL+v i useless, ofc it wont work .

And paste feature worked for me, using the same link you posted in the issue.

Idk what to say

**Comment by arifsyahbani** [comment]
The manga was bookmarked, but after press it, chapters list didn't appear.

![image](https://github.com/manga-download/hakuneko/assets/45502806/379975d1-5484-4291-b7fd-7fb31ff0cbf6)
`TypeError: Cannot read property 'content' of null
    at Yanmaga._getChapters (Yanmaga.mjs:34)
    at async Yanmaga._getChapterList (Connector.mjs:595) EventTarget {connector: Yanmaga, id: "/comics/%E3%81%99%E3%81%90%E6%B3%A3%E3%81%8F%E5%85%88%E8%BC%A9", title: "すぐ泣く先輩", status: "available", chapterCache: Array(0), …}connector: Yanmaga {id: "yanmaga", label: "Yanmaga", tags: Array(2), isLocked: false, initialized: true, …}id: "/comics/%E3%81%99%E3%81%90%E6%B3%A3%E3%81%8F%E5%85%88%E8%BC%A9"title: "すぐ泣く先輩"status: "available"chapterCache: []existingChapters: []__proto__: EventTarget`

`_getUpdatedChaptersFromWebsite TypeError: Cannot read property 'content' of null
    at Yanmaga._getChapters (Yanmaga.mjs:34)
    at async Yanmaga._getChapterList (Connector.mjs:595)
(anonymous) @ Manga.mjs:153
Promise.catch (async)
_getUpdatedChaptersFromWebsite @ Manga.mjs:151
(anonymous) @ Manga.mjs:98
Promise.then (async)
getChapters @ Manga.mjs:94
onSelectedMangaChanged @ chapters.html:244
runObserverEffect @ property-effects.html:217
runEffectsForProperty @ property-effects.html:162
runEffects @ property-effects.html:128
_propertiesChanged @ property-effects.html:1662
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
__enableOrFlushClients @ property-effects.html:1555
_flushClients @ property-effects.html:1530
_propertiesChanged @ property-effects.html:1658
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
runNotifyEffects @ property-effects.html:261
_propertiesChanged @ property-effects.html:1665
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
set @ property-effects.html:1817
onMangaClicked @ mangas.html:263
handler @ template-stamp.html:96
(anonymous) @ templatize.html:149`

**Comment by MikeZeDev** [comment]
1) Mangalist can be outdated but you can update it. Bookmark can be outdated to but there is not way to update them . Idk when you created that bookmark but it could be the case. Please ignore that remark if you just created it right now.

2) I dont remember when last stable version was released but there have been fixes on Youngchampion/Yanmaga 3 months ago. Those fixes are available for sure on nightly version. In the issue you said you tried it but is that really the case? Because i use it and i cant reproduce your errors so thats disturbing. Did you REALLY TRY NIGHTLY?

**Comment by kanjieater** [comment]
I just confirmed it doesn't work on latest stable, but downloading the nightly version, did fix it for me.

**Comment by MikeZeDev** [comment]
Next time, dont check "i did it " when you clearly didnt do it, and please follow the instructions. It would have been solved faster for you and me :D

**Comment by arifsyahbani** [comment]
Hello Mike, I'm sorry for the trouble. So it turned out after using VPN, yanmaga seems back to normal. I think **yanmaga** have an **issue with my country IP things**.
