### ISSUE TITLE
Kissmanga doesn't download some chapters because of Captcha

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#621]
Kissmanga doesn't download some chapters because of Captcha.

**Comment by 27136773** [comment]
For now you can bypass captchas using [manual website interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection)

**Comment by 27136773** [comment]
Re-opened to implement automatically show the required captcha whenever needed (like in 9anime)

**Comment by MikeZeDev** [comment]
The kissmanga mentioned in the issue is dead.
Kissmanga.org does not have that problem.
The other one still need unrelated fixing (another issue is opened)

Closing this issue?

**Comment by MikeZeDev** [comment]
@Sheepux  pls?
