### ISSUE TITLE
[YumeKomik] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#6214]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

cant download chapter

### To Reproduce

1. YumeKomik
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

![image](https://github.com/manga-download/hakuneko/assets/112748173/659e40f8-f9c2-45dd-9a01-e36d1f343963)
![image](https://github.com/manga-download/hakuneko/assets/112748173/9cf0eacf-2c98-430b-9b62-b156f4382fd8)

**Comment by MikeZeDev** [comment]
they have hosting problems : 

![image](https://github.com/manga-download/hakuneko/assets/10671518/bc8541a4-ae23-4057-b1e9-d368fa3451a8)

cdn.yumekomik.com doesnt respond. 

As for your particular problem, messages doesnt help and idont know what going on.

**Comment by Shaft14** [comment]
thanks
