### ISSUE TITLE
[MgKomik] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#6216]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Change domain

### To Reproduce

1. Mgkomik
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

![image](https://github.com/manga-download/hakuneko/assets/112748173/01b185e5-ee8b-4fb6-b232-1f3219abafb5)

https://mgkomik.com/ to https://mgkomik.id/
thanks

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/6208

You clearly didnt search for already opened issues.
