### ISSUE TITLE
[request] New list for manga readers

### ISSUE THREAD

**Issue by Luke0094** [manga-download/hakuneko#622]
Hi, i would like to see these sites in the list:
https://hastareader.com/slide/
https://mangaworld.biz/
https://www.fansubitaliani.org/manga_reader/
http://www.agcscanlation.it/serie.php
https://hentai-ita.net/

All sites are italian.
Thank you for your work.

**Comment by 27136773** [comment]
Please make a single issue for each request, handling multiple requests in a single issue is inconveniemnt for developers and watchers
