### ISSUE TITLE
[mangafire.to] Connector not working

### ISSUE THREAD

**Issue by GalaxyAmbience** [manga-download/hakuneko#6220]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Although mangafire.to is included in the list as a connector, when I choose it, and then press refresh icon as guided by the instructions for a manga list, the refresh icon quickly stops spinning and there is no list of any type of mangas. Perhaps, it might be because the connector is outdated and a new version V2. of the website has been launched.

### To Reproduce

Name of connector: mangafire.to

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/pull/6217

They use the same protection than 9anime (Aniwave) and another website. How are they related? Its a mystery for me.

**Comment by TristanWasTaken** [comment]
> How are they related? Its a mystery for me.

@MikeZeDev 9anime was advertising mangafire for some time
so it's pretty likely the operators are the same, or are at least acquaintances

**Comment by GalaxyAmbience** [comment]
> #6217
> 
> They use the same protection than 9anime (Aniwave) and another website. How are they related? Its a mystery for me.

So, did the problem get fixed?

**Comment by MikeZeDev** [comment]
> > #6217
> > They use the same protection than 9anime (Aniwave) and another website. How are they related? Its a mystery for me.
> 
> So, did the problem get fixed?

Yes. Fix must be reviewed by a peer before being approved and available to the end user.

**Comment by GalaxyAmbience** [comment]
> > > #6217
> > > They use the same protection than 9anime (Aniwave) and another website. How are they related? Its a mystery for me.
> > 
> > 
> > So, did the problem get fixed?
> 
> Yes. Fix must be reviewed by a peer before being approved and available to the end user.

I see, thank you for your effort and how much time will it take before it gets reviewed by another peer?

**Comment by MikeZeDev** [comment]
> > > > #6217
> > > > They use the same protection than 9anime (Aniwave) and another website. How are they related? Its a mystery for me.
> > > 
> > > 
> > > So, did the problem get fixed?
> > 
> > 
> > Yes. Fix must be reviewed by a peer before being approved and available to the end user.
> 
> I see, thank you for your effort and how much time will it take before it gets reviewed by another peer?

Depends on one's free time.
