### ISSUE TITLE
[Comic ZEROSUM] website change

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6222]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga series and chapter list isn't refreshing

### Describe the bug

Comic ZEROSUM [has renewal their site](https://twitter.com/comic_zerosum/status/1702168052400603450). Hakuneko can't fetch any manga series and chapter list, also look like they change viewer to something.

### To Reproduce

1. Name of connector: Comic ZEROSUM
2. Name of manga (if connector update is working): All
3. Name of chapter (if manga update is working): All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): get 404 on manga series and chapter list.

### Screenshots

![image](https://github.com/manga-download/hakuneko/assets/2475440/a04c1599-5634-4b4d-96bf-1ee2c417c2f2)

**Comment by MikeZeDev** [comment]
Hum, ofc, url changed :D

Ohh crap, they use protobuff and no more speedbind. damn thats gonna be annoying
