### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by justanotherreder** [manga-download/hakuneko#6225]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

1stkissmanga.me and its sister 1stkissmanhua.com changed their webaddres to likemanga.io.  When opening the link by clicking on the arrow in the topright corner, likemanga automatically opens, but when i try to copy the url from there (even with refresthing etc.) it is unavailable  Also, when I load the connector's manga list, the manga names are listed, but when i click on a manga, no chapters are listed, due to the link being broken.

Can you do the necessary adjustments please.

1.  1stkissmanga.me and 1stkissmanhua.com
2.  Currently. nothing is working anymore
3.  Nothing listed due to address being broken
4.  No messages are displayed

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
* Make a proper issue, with a proper title please.

> . When opening the link by clicking on the arrow in the topright corner, likemanga automatically opens, but when i try to copy the url from there (even with refreshing etc.) it is unavailable

What a funny idea. Thats not how copy past feature work . There is a manual, read it before opening pointless issues.

https://hakuneko.download/docs/FAQ/#copy-and-paste

**Comment by justanotherreder** [comment]
Hi

Sorry, I sometimes find it hard to explain an issue.  I'll try again:

I have a lot of 1stKissmanga.com manga/manhuas marked as a favorite:
[image: image.png]

1stKissmanga.com has changed their address to Likemanga.io.  As you can
see, since this is still listed as a 1stKissmanga.com-manga, only the
already-downloaded chapters are listed.

But when I go to this page and click on the little arrow at the topright of
the site I want to open, like so
[image: image.png]

I get the following message
[image: image.png]
But last time Likemanga opened, allowing me to browse

Then, when I came accross a manga i liked, i went to Edit -- Copy URL
[image: image.png]

and then went to Hakuneko's Clipboard,  and pasted it , like so
[image: image.png]

Notice, that while nothing is listed, it still did find the manga.  So, I
simply clear out the address that was pasted and Voila:  there it is.

[image: image.png]

I could do this directly from a browser as well.  But now that 1stKissmanga
changed its address, this technique does not work anymore.


When I click on the 1stKissmanga.com it still lists all the mangas
[image: image.png]

But when you physically click on a manga,
[image: image.png]
no chapters are found,

This is my favorite site as it is userfriendly and basically immediately
uploads the latest chapters once uploaded, but now that the address has
been changed to Likemanga.io, I cannot view, nor download anything.

Likemanga.io isn't listed on the "connectors page" so i cannot download
from them directly either.

Could you please have 1stkissmanga.com's address redirected to Likemanga.io?

Please feel free to contact me if you have any further questions.

kind regards
Anja

**Comment by MikeZeDev** [comment]
* Your message doesnt have screenshot unfortunately
* If you use nightly build there is likemanga. 1stkissmanga has been renamed to that and url changed.
* Bookmarks can not work from one website to another you have to redo them for likemanga. Or maybe they work, it depends . Better deleting and redo them i think.
* if you miss a manga again copy paste feature is best.

**Comment by justanotherreder** [comment]
Ok, I will try that.

Strange that the screenshots i've sent does't work.

Thanks for your help, though.

The Likemanga you were referring to is Likemanga.io, right?  I noticed that
a few likemanga's were listed, but none of them had the .io extension.

Anyway, thanks for the help.

**Comment by justanotherreder** [comment]
Hi there

I tried doing as you suggested, but something is "buggy"

When clicking on "Likemanga.io" the Nightly Hakuneko loads all the manga,
but when I click on any of the mangas, no chapters are listed.

I tried the copy-paste feature as well, but it doesn't work either.

Am i missing something?

Hoping to hear from you soon.

**Comment by MikeZeDev** [comment]
Which manga, cause everything works.

![image](https://github.com/manga-download/hakuneko/assets/10671518/b6f257c8-d1a9-4f95-948f-3afdc263570a)

**Comment by justanotherreder** [comment]
Hi there

That is very odd.

All I get is:
[image: image.png]
We are using the same Connector, and yet mine does not work.

I don't get it?
