### ISSUE TITLE
[Site Request] mangarockteam

### ISSUE THREAD

**Issue by gorksharamchandra** [manga-download/hakuneko#6226]
mangarockteam

- Site: https://mangarockteam.com/
- Manga List: https://mangarockteam.com/manga/
- Manga example: https://mangarockteam.com/manga/boku_no_hero_academia/
- Chapter online viewer example: https://mangarockteam.com/manga/boku_no_hero_academia/chapter-399/

**Languages**
English

**Comment by MikeZeDev** [comment]
Already supported 🤦 since 4 years .
