### ISSUE TITLE
[123Hon] More manga sources

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6229]
**Name of the website**
Comic Nova

**Website urls (examples below)**
- Site: https://www.123hon.com/nova/
- Manga List: https://www.123hon.com/nova/web-comic/
- Manga example: https://www.123hon.com/nova/web-comic/lastboss/
- Chapter online viewer example: https://www.123hon.com/vw/lastboss/sv_pt000650693ab14424_01a_re

**Languages**
Japanese

**Website relationship**
[Comic Polca (123hon)](https://www.123hon.com/polca/)'s another manga label.

**Additional details**
Use speedbind for reader like Comic Polca.
Look like can't fetch url path correctly on some chapter of new release like ``https://www.123hon.com/vw/lastboss/*episode path*/data/*file*`` but hakuneko fetch as ``https://www.123hon.com/vw/lastboss/data/*file*`` (tested via 123hon (Comic Polca)'s connector).
Also clipboard from both site can't get manga name correctly like [yellatiam (天と地と狭間の世界イェラティアム)](https://www.123hon.com/nova/web-comic/yellatiam/) hakuneko get as Manga #B4C

**Comment by MikeZeDev** [comment]
At least Hakuneko is able to display chapters from clipboard link. Gotta first fix the title, then see if i can add another source.

And that path problem is annoying, Its retarded. 

For lastboss, the chapter path ends without '/'. So we end up making an URL without the last part and that remove the episode part. Thats nasty.

![image](https://github.com/manga-download/hakuneko/assets/10671518/423bfcf8-a390-4aa7-b5d6-73b2adc46227)
