### ISSUE TITLE
[Site Request]nyxmanga

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6231]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https:https://nyxmanga.com/
- Manga List: https://nyxmanga.com/manga/
- Manga example: https://nyxmanga.com/manga/10-yil-sonra-can-dusmanimla-evlenmisim/
- Chapter online viewer example: https://nyxmanga.com/10-yil-sonra-can-dusmanimla-evlenmisim-1/

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream

**Comment by MikeZeDev** [comment]
dead?

**Comment by Tianzhou2** [comment]
> dead?

The site is under maintenance
