### ISSUE TITLE
[Site Request] Mangacim

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6234]
**Name of the website**
Mangacim

**Website urls (examples below)**
- Site: https://mangacim.com/
- Manga List: https://mangacim.com/manga/
- Manga example: https://mangacim.com/manga/akrabalarim-bana-takintili/
- Chapter online viewer example: https://mangacim.com/takintiliakrabalarim1/

**Languages**
Turkish
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Supported since last year, again, SEARCH BEFORE ASKING. 🙏 

https://github.com/manga-download/hakuneko/blob/93c21813d872987128a7b3017073263e4e832b00/src/web/mjs/connectors/Mangacim.mjs#L4
