### ISSUE TITLE
[Asura Scans TR] Domain change

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6235]
**Name of the website**
ArmoniScans

**Website urls (examples below)**
- Site: https://armoniscans.com/
- Manga List: https://armoniscans.com/manga/
- Manga example: https://armoniscans.com/manga/a-business-proposal/
- Chapter online viewer example: https://armoniscans.com/a-business-proposal-bolum-1/

**Languages**
Turkish
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Waaaait , tr asura scans url changed?

**Comment by Tianzhou2** [comment]
> Waaaait, tr asura taramalarının URL'si değişti mi?

yes

**Comment by MikeZeDev** [comment]
So its NOT a site request, its a website change

**Comment by Mehmet20032003** [comment]
[Asura Scans TR] Domain change: The URL of Armoni Scans will change or has already changed. The new URL is again https://asurascans.com.tr/

Translation of the image: The Armoni Scans series is out now "asurascans.com.tr " it will continue at the address. We are waiting for you at our new address!
![Adsız](https://github.com/manga-download/hakuneko/assets/127633031/79e318f7-e16e-4156-ad98-e21d163f11ef)

**Comment by MikeZeDev** [comment]
Dont use closed issues for taht open another we dont look after closed issues
