### ISSUE TITLE
[Site Request]Mangazure

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6236]
**Name of the website**
Mangazure

**Website urls (examples below)**
- Site: https://www.mangazure.com/
- Manga List: https://www.mangazure.com/search/label/T%C3%BCm%C3%BC
- Manga example: https://www.mangazure.com/2023/09/the-reincarnated-assassin-is-genius.html
- Chapter online viewer example: https://www.mangazure.com/2023/09/the-reincarnated-assassin-is-genius_1.html

**Languages**
Turkish
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
already requested, check before asking pls 

Duplicate https://github.com/manga-download/hakuneko/issues/3376
