### ISSUE TITLE
[Site Request] Webtoon Evreni

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6240]
**Name of the website**
Webtoon Evreni

**Website urls (examples below)**
- Site: https://webtoonevreni.net/
- Manga List: https://webtoonevreni.net/manga/
- Manga example: https://webtoonevreni.net/manga/boruto-two-blue-vortex/
- Chapter online viewer example: https://webtoonevreni.net/manga/boruto-two-blue-vortex/bolum-1/

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/5991
