### ISSUE TITLE
[Site Request] ReadComicOnline

### ISSUE THREAD

**Issue by Gino-El-Renegado** [manga-download/hakuneko#6241]
**Name of the website**
ReadComicOnline

**Website urls (examples below)**
- Site: https://readcomiconline.li/
- Manga List: https://readcomiconline.li/ComicList
- Manga example: https://readcomiconline.li/Comic/Mighty-Morphin-Power-Rangers
- Chapter online viewer example: https://readcomiconline.li/Comic/Mighty-Morphin-Power-Rangers/Issue-24?id=130902#1

**Languages**
English

**Website relationship*
Unklnown

**Additional details**
N/A

**Comment by MikeZeDev** [comment]
Its already supported , check before asking 

https://github.com/manga-download/hakuneko/blob/93c21813d872987128a7b3017073263e4e832b00/src/web/mjs/connectors/KissComic.mjs#L11
