### ISSUE TITLE
[WebToonTRCOM] domain change

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6245]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Webtoon TR has renewal their site. Hakuneko can't fetch any manga series and chapter list,new adress https://webtoontr.net/

### To Reproduce

1. Name of connector Webtoon TR
2. Name of manga (if connector update is working) All
3. Name of chapter (if manga update is working)  All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Please put a proper title next time. Are people that lazy ? :/

**Comment by Tianzhou2** [comment]
> Please put a proper title next time. Are people that lazy ? :/

How are the settings made?

**Comment by MikeZeDev** [comment]
I fail to understand what you want to say. this is fixed, use nightly.

**Comment by Tianzhou2** [comment]
> I fail to understand what you want to say. this is fixed, use nightly.

How is it used?
