### ISSUE TITLE
[syalemlek] new domain

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6248]
**Name of the website**
Gri Melek
**Website urls (examples below)**
- Site: https://grimelek.net/
- Manga List: https://grimelek.net/seri/
- Manga example: https://grimelek.net/seri/please-go-home-akutsu-san-2/
- Chapter online viewer example: https://grimelek.net/seri/please-go-home-akutsu-san-2/bolum-84/

**Languages**
Turkish
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Its the new url of syalemlek . https://github.com/manga-download/hakuneko/blob/79fbc280a03f1980a2bcb59cddfedfaffdf664e8/src/web/mjs/connectors/Siyahmelek.mjs#L4

Gotta change the ticket for a website change.

Also , it need to be logged for getting chapters, that sucks.

**Comment by Tianzhou2** [comment]
> Bu syalemlek'in yeni URL'si.
> 
> https://github.com/manga-download/hakuneko/blob/79fbc280a03f1980a2bcb59cddfedfaffdf664e8/src/web/mjs/connectors/Siyahmelek.mjs#L4
> 
> Web sitesi değişikliği için bileti değiştirmem gerekiyor.
> 
> Ayrıca bölümleri alabilmek için oturum açmanız gerekiyor, bu berbat bir şey.

How are the settings made?
