### ISSUE TITLE
Problem updating Tmofans

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#626]
Good afternoon / nights / days, I tried to run the application using the code you put before I don't know anything about programming so I guess I do it wrong because the program doesn't work for me anymore and I have to download again. I don't know if you could pass me the updated file or tell me how it should look. Thank you.

**Comment by 27136773** [comment]
Just download the Nightly Build

**Comment by DarkBlooDStone** [comment]
Portable version 6.1.4 black screen not openned 
![aasd](https://user-images.githubusercontent.com/53885246/68557491-f9c3e780-0403-11ea-9351-12e1ae87b0a5.jpg)
Two hours.

**Comment by 27136773** [comment]
What is shown in the error console (F12)?
What is shown when you start HakuNeko in terminal?

**Comment by DarkBlooDStone** [comment]
Nothing after hours remains the same.

**Comment by 27136773** [comment]
Pressing F12 didn't work?
Starting HakuNeko from command line within a terminal also didn't show any output?

**Comment by DarkBlooDStone** [comment]
Did not show any results follow the black screen.

**Comment by 27136773** [comment]
Cannot be reproduced on macOS.
Cannot be analysed based on the provided information.

**Comment by DarkBlooDStone** [comment]
My computer uses windows seven.

**Comment by DarkBlooDStone** [comment]
Using the setup also presented the same problem.

**Comment by 27136773** [comment]
Issue cannot be reproduced.
The requested command-line output and console log was not provided.
Cannot help => closed

**Comment by DarkBlooDStone** [comment]
The program works only the screen does not clear up.
