### ISSUE TITLE
[<Animated Glitch Scans>] Connector not working

### ISSUE THREAD

**Issue by Infernotez** [manga-download/hakuneko#6260]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

If I try to reload the manga list for the site, it just empties it and the loading icon just goes back to normal, if I try to click any series to see a chapter list it does not load. The site loads perfectly fine and I can view chapters there. I can't remember if the site recently changed domains, I know many sites that host manhwas have been swapping domains a lot recently.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Fix was already pending . https://github.com/manga-download/hakuneko/pull/6253

**Comment by MikeZeDev** [comment]
Added to Haruneko https://github.com/manga-download/haruneko/pull/344
