### ISSUE TITLE
[<Asura Scans>] New Domain

### ISSUE THREAD

**Issue by mikeyblitz21** [manga-download/hakuneko#6261]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Request to change url to https://asuracomics.com/

Current URL in Hakuneko: https://asurascans.com

### To Reproduce

.

**Comment by MikeZeDev** [comment]
Useless ticket. Change domain in settings. Use nightly version to to that.
