### ISSUE TITLE
[<mangalek.org>] Connector not working

### ISSUE THREAD

**Issue by NEUX1** [manga-download/hakuneko#6263]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The "mangalek.org "website is not working because it has changed its domain to "manga-lek.net" and "manga-lek.org". Please change the links in the program and modify them for the new links. Thank you.

### To Reproduce

1. Name of connector https://manga-lek.org/ and https://manga-lek.net/
2. Name of manga manga-lek.org/manga/rebirth-i-am-the-king-of-entertainment/
3. Name of chapter manga-lek.org/manga/rebirth-i-am-the-king-of-entertainment-chapter-56/

**Comment by MikeZeDev** [comment]
Hum, how should we chose between https://manga-lek.org/ , https://manga-lek.net/ or https://mangaleku.com/ ? 

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18124

**Comment by NEUX1** [comment]
oh xD

idk but u can chose two of them or one that will be great

thx for ur effort btw

<3

**Comment by NEUX1** [comment]
anything new?

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/3ea88136-9d9f-4b6b-9c78-313fc49ad144)

Download nightly version, wait for fix validation.

**Comment by NEUX1** [comment]
but it did not  complete yet
