### ISSUE TITLE
[<majorscans>] Connector not working

### ISSUE THREAD

**Issue by NekoManga** [manga-download/hakuneko#6269]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

The chapters do not download completely. Corrupt gif file downloads instead of unopened images. The images below are not loading.

![image](https://github.com/manga-download/hakuneko/assets/131636429/6aa4a18a-fbad-409d-bb47-d597905e59d1)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Hu? There is no majorscan website supported ? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/03d50ee8-c0d2-403b-a949-1c55608bd020)

**Comment by MikeZeDev** [comment]
Unless i am wrong this website was never supported, so ofc course it doesnt work. I dont know where do you got your bookmarks.
Closing it as there is nothing to check.
