### ISSUE TITLE
[Novelcool (ES)] Connector not working - not showing manga with special character (') ?

### ISSUE THREAD

**Issue by CV-Carlos** [manga-download/hakuneko#6271]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

This specific manga, B'T X, is not showing in the search on HakuNeko. I tried manually looking for the manga on the list but had no luck.
I tried using multiple formats, but I found the manga on the novelcool page by using B'T X on the search bar and it works without issues.

### To Reproduce

1. novelcool (ES)
2. B'T X
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Then use copy paste feature, it works perfectly. I checked the website : i cant go past page ***, i get redirected to website homepage. They say 1519 pages but most are unreachable. 🤷

**Comment by CV-Carlos** [comment]
What do you mean by "copy-paste feature"? I am copying the name as it is on the website and no luck. I also got no idea what you mean by "i cant go past page ***".

**Comment by MikeZeDev** [comment]
https://hakuneko.download/docs/FAQ/#copy-and-paste

And website doesnt allow getting all manga list pages so we get incomplete list its simple.
