### ISSUE TITLE
[niconico seiga] Image not download correctly on some chapter

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6282]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Hakuneko download image on some chapter incorrectly by download another image instead expected to be of that page, but haven't any error message on dev tool.

### To Reproduce

1. select niconico seiga
2. select or clipboard paste [六姫は神護衛に恋をする　～最強の守護騎士、転生して魔法学園に行く～](https://seiga.nicovideo.jp/comic/49282)
3. download or read chapter 2 ([第2話　母の仕事](https://seiga.nicovideo.jp/watch/mg500887))

### Screenshots

![image](https://github.com/manga-download/hakuneko/assets/2475440/b9e14819-51e4-4459-9459-d6cd73dfaea2)

**Comment by MikeZeDev** [comment]
I see. We try to get better quality image, fails 99% of the time so the fallback works. When we hit a a "high quality image" it is totally irrelevant to the chapter.
