### ISSUE TITLE
[AsuraScans] Domain Change

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#6287]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The "click to paste" option doesn't work because the domine change from https://asuracomics.gg/ to https://asuratoon.com/

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Nightly > change url in settings.

Already said maaaaaaaaaaaany times. https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+asura&type=issues

[I even already gave the same answer to you 5 days ago,](https://github.com/manga-download/hakuneko/issues/6272) I wonder if you even read what i say. 

Please stop reopening the same issue each time when you have a solution.
