### ISSUE TITLE
[Coco漫画] Connector not working

### ISSUE THREAD

**Issue by RageMist** [manga-download/hakuneko#6288]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

"https://colamanhua.com" changed to "https://www.colamanga.com"
The connector can load the Manga List and Chapter List correctly. However, when trying to download a chapter, it is in a format that is not in image types like "jpg," "jpeg," or "webp." Instead, it is in some kind of video or ".bin" format, which is unreadable.

1. Manga List works fine.
![image](https://github.com/manga-download/hakuneko/assets/69992781/42f568e7-472f-4415-9c4b-98cceb143af1)

2. Chapter List works fine.
![image](https://github.com/manga-download/hakuneko/assets/69992781/27d19d27-0ac0-47f7-b9ea-1a24214f13cb)

3. Files do get Downloaded.
![image](https://github.com/manga-download/hakuneko/assets/69992781/13664e02-a34f-44e3-9b7e-24b82f724b1f)

4. Image files are Unreadable, they are in a format that's not Image type.
![image](https://github.com/manga-download/hakuneko/assets/69992781/a179c09e-19f1-41fb-9dba-007911d4fe96)
![image](https://github.com/manga-download/hakuneko/assets/69992781/ebfc89fa-757e-42fd-bec6-bad114e10567)

### To Reproduce

1. Coco漫画
2. 全球御鬼：我的体内有亿只鬼
3. Any
4. 
![image](https://github.com/manga-download/hakuneko/assets/69992781/65ea93dd-fee8-4514-83ab-4adf2096e211)

**Comment by MikeZeDev** [comment]
* Ok, gotta change url
* Bin is a generic extension, dont bother, content is probably just html.  Coco tends to use temporary ip blocking ant we cant do anything about that, it could the reason.

Anyway, i dont see any problem after changing url 

![image](https://github.com/manga-download/hakuneko/assets/10671518/1a118c94-53b4-49b5-bd88-18219e3ea733)

**Comment by RageMist** [comment]
It still doesn't work, I think the change were not made for some reason. Can you Check it again.....

**Comment by MikeZeDev** [comment]
I made a REQUEST for change. Ofc they need approval from my peers. Its how Github works.
Make sure you use nightly version and wait.
