### ISSUE TITLE
[Site Request] Lunar Scans

### ISSUE THREAD

**Issue by AzureLance24** [manga-download/hakuneko#6295]
**Name of the website**
Lunar Scans

**Website urls (examples below)**
- Site: https://lunarscan.org/
- Manga List: https://lunarscan.org/series/
- Manga example: https://lunarscan.org/series/my-sisters-friends/
- Chapter online viewer example: https://lunarscan.org/my-sisters-friends-chapter-1/

**Languages**
English

**Website relationship*
I'm not sure

**Additional details**
MangaStream Wordpress Theme

**Comment by Ishkei** [comment]
yes Ive been Wanting lunarscans to be added for some time now, they have many Novels on their website

**Comment by Sheepux** [comment]
> yes Ive been Wanting lunarscans to be added for some time now

well ...  when you don't request it (like here) you'd wait an eternity
