### ISSUE TITLE
[<Mangatoto>] Connector not working

### ISSUE THREAD

**Issue by Eurus17** [manga-download/hakuneko#6297]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

i can open mangatoto.com fine on my chrome
but i can't open on the apps
already change on setting from bato.to to mangatoto.com but both got the same error

![1](https://github.com/manga-download/hakuneko/assets/147233581/5429b097-3f5d-4a92-8ea0-2f0c17ca06c9)

### To Reproduce

1. Name of connector : Mangatoto.com
2. Name of manga (if connector update is working) : 
3. Name of chapter (if manga update is working) : - 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![2](https://github.com/manga-download/hakuneko/assets/147233581/1542f933-0fb0-46a2-94be-d3da53ba652e)
![3](https://github.com/manga-download/hakuneko/assets/147233581/fe3419e3-b0a5-4933-b220-42eaae200d37)
![4](https://github.com/manga-download/hakuneko/assets/147233581/97193dff-b985-4590-8811-1016c3a9d284)

**Comment by MikeZeDev** [comment]
I am afraid both works for me.

**Comment by Eurus17** [comment]
yeah, but i don't know why it's not working on my apps
i can open it on my chrome but not on apps :(

want to download manga from the apps

just to make sure
after download the app ( for me portable ver ) no need to add something else right ? to get the  " latest updated ver "

**Comment by MikeZeDev** [comment]
>yeah, but i don't know why it's not working on my apps

And i dont know either, its weird.

> after download the app ( for me portable ver ) no need to add something else right ? to get the " latest updated ver "
Nothing. It should work out of the box.

Maybe its a problem with your security suite SSL/TLS scanning? 🤷

**Comment by Eurus17** [comment]
is there a way to fix it ? my internet can't load the mangalist on most of the websites
