### ISSUE TITLE
[Feature] New release compilation

### ISSUE THREAD

**Issue by jhonatanDS** [manga-download/hakuneko#6304]
Would it be possible to compile/make available a new release of hakuneko for the Linux system using the .deb packaging?
The last version released was in 2020, and I believe there have been several improvements in the code from 2020 to 2023. 

 Thank you.

**Comment by 27136773** [comment]
<img width="932" alt="image" src="https://github.com/manga-download/hakuneko/assets/27136773/0dcf9196-a123-42b2-9843-d5abe9e6a392">
