### ISSUE TITLE
[MangaMX] Connector not working

### ISSUE THREAD

**Issue by nelvalderramaf** [manga-download/hakuneko#6308]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

the url of the site https://manga-mx.com/ changed to https://manga-oni.com/

### To Reproduce

1. Name of connector manga mx

**Comment by MikeZeDev** [comment]
Manga-mx still.com up. the the other url is Cloudflared
