### ISSUE TITLE
New mangas don't show up

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#631]
> **From:** HakuNeko User

Hi,
there are a lot of new mangas that are nowhere to be found using haruneko but they've been uploaded on the various websites. I know I've to wait a couple of days, but some of them have been uploaded longer than 7 days ago. Is it ok or there some issue?

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Which website(s)?
Does it work with Copy & Paste?

**Comment by uuranor** [comment]
Firstly on mangago, but I noticed the same issue on other website as mangabat, mangadex, myreadingmanga, mangarock and so on. You can find the new manga on the website, but you can't find it using hakuneko. It happens only on new manga, no issue whit mangas already uploaded and updated.
Copy/paste doesn't work too.

**Comment by 27136773** [comment]
For MangaGo see [FAQ](https://github.com/manga-download/hakuneko/wiki/FAQ).
I cannot reproduce the issue with any of the other websites using random recently added mangas.
Just to make sure, the manga lists have been regularly synced?

**Comment by uuranor** [comment]
Yes, and even using the Link Copy & Paste feature still not working on mangago, also with manga uploaded mounths ago.
Instead the Copy & Paste feature works just fine with all the other websites.
Thank you very much for your help, I'll wait for the mangas that are nowhere to be found but on mangago.

**Comment by uuranor** [comment]
Ok, now it's working on mangago too. I don't know if you just did something or whatever, but thank you very much!!!

**Comment by 27136773** [comment]
When copy & paste make sure to copy the correct link to the manga (where the chapters are listed).
Also press F12 and check the console output to spot warnings and errors.
