### ISSUE TITLE
[Asura Scans] Only Downloads/Loads First Page of Recent Uploads

### ISSUE THREAD

**Issue by Keyeson** [manga-download/hakuneko#6316]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

Only downloads/loads the first page of recent uploads. Tried updating the URL in the config, but still getting the issue. Only seems to affect the most recently uploaded stuff. Older chapters load fine, but any of the recently added chapters I only get the first page.

### To Reproduce

1. Asura Scans
2. Boundless Necromancer or any other recently updated series
3. Chapters 49-53
4. No errors appear.

**Comment by MikeZeDev** [comment]
Already done, use nightly build

**Comment by Keyeson** [comment]
Was using nightly build still didn't work guess the update hadn't gone through when I posted this. Also Githubs search sucks apparently because I searched Asura to see if there were any existing issues both closed and open, and it didn't show this one #6313 even though it shows other results with AsuraScans/Asurascans.
