### ISSUE TITLE
[Site Request] Shirakami

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#6317]
**Name of the website**
Shirakami

**Website urls (examples below)**
- Site: https://shirakami.xyz/
- Manga List: https://shirakami.xyz/manga/?order=update
- Manga example: https://shirakami.xyz/manga/please-dont-show-your-son/
- Chapter online viewer example: https://shirakami.xyz/please-dont-show-your-son-chapter-13-bahasa-indonesia/

**Languages**
List of languages supported by the website
 Indonesia
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already requested and already added. https://github.com/manga-download/hakuneko/issues/6020. https://github.com/manga-download/hakuneko/pull/6129. 

Please. Its not your first issue, you are like a veteran here. By the time, you should know than things comes first in nightly build, so use it and check if the website dont already exist in this build. Then no one will lose time. Its a bit irritating, i feel like talking to a deaf individual.

**Comment by Shaft14** [comment]
oh ok
