### ISSUE TITLE
Manga-like has updated its domain.

### ISSUE THREAD

**Issue by AissaUs** [manga-download/hakuneko#6319]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Manga-like has updated its domain to manga-like.net.  (can you please fix it?)

### To Reproduce

Manga-like has updated its domain to manga-like.net.  (can you please fix it?)

**Comment by MikeZeDev** [comment]
Mangalek mess, we chose mangaleku because its apparently updated faster. Dont know which one is a clone which one is the real, they all look the same to me
