### ISSUE TITLE
[Site Request] TempleScan

### ISSUE THREAD

**Issue by LightScans** [manga-download/hakuneko#6323]
**Name of the website**
TempleScan

**Website urls (examples below)**
- Site: https://templescan.net/
- Manga List: https://templescan.net/comics
- Manga example: https://templescan.net/comic/i-thought-its-a-common-possession
- Chapter online viewer example: https://templescan.net/comic/i-thought-its-a-common-possession/36

**Languages**
English

**Website relationship**
Haven't

**Additional details**
>>

**Comment by MikeZeDev** [comment]
No template afaik, should be coded from scratch.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5815
