### ISSUE TITLE
[Site Request] ReadOnePiece.com

### ISSUE THREAD

**Issue by SammBrooks** [manga-download/hakuneko#6325]
**Name of the website**
ReadOnePiece.com

**Website urls**
- Site: https://ww9.readonepiece.com/
- Manga List: (No Cohesive List Found. Each Available Is Linked At the Top of the Site.)
- Manga example: https://ww9.readonepiece.com/chapter/one-piece-digital-colored-comics-chapter-001/
- Chapter online viewer example: https://ww9.readonepiece.com/manga/one-piece-digital-colored-comics/

**Languages**
English

**Website relationship**
A bevvy of other sites that are "read(manganame).com"

**Additional details**
Not a helpful detail, but it's the only site I've found that carries the most color scans of OP, and I really want them.

**Comment by 27136773** [comment]
See #2381 and all the other related issues for ReadOnePiece

**Comment by SammBrooks** [comment]
Thanks a bunch for the insight.
