### ISSUE TITLE
[Site Request] Truyenqq

### ISSUE THREAD

**Issue by NQKFOX** [manga-download/hakuneko#6328]
Name of the website
Truyenqq

Website urls (examples below)

Site: https://truyenqqvn.com
Manga List: https://truyenqqvn.com/truyen-moi-cap-nhat/trang-1.html?country=4
Manga example: https://truyenqqvn.com/truyen-tranh/that-tinh-907
Chapter online viewer example: https://truyenqqvn.com/truyen-tranh/that-tinh-907-chap-1.html
Languages
Vietnamese

Additional details
None

**Comment by MikeZeDev** [comment]
Already supported 🤦 https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/TruyenQQ.mjs

Url may have changed but its no use updating it, Cloudflare
