### ISSUE TITLE
[Site Request] Blogtruyenmoi

### ISSUE THREAD

**Issue by NQKFOX** [manga-download/hakuneko#6329]
Name of the website
Blogtruyenmoi

Website urls (examples below)

Site: https://blogtruyenmoi.com
Manga List: https://blogtruyenmoi.com/theloai/manga
Manga example: https://blogtruyenmoi.com/30276/ryoushin-no-shakkin-wo-katagawari-shite-morau-jouken-wa-nihon-ichi
Chapter online viewer example: https://blogtruyenmoi.com/c839604/ryoushin-no-shakkin-wo-katagawari-shite-morau-jouken-wa-nihon-ichi-chap-16
Languages
Vietnamese

Additional details
None

**Comment by MikeZeDev** [comment]
Already supported, like your other request https://github.com/manga-download/hakuneko/blob/3ee31917c257397ddfa243d7128477b637b7bfcc/src/web/mjs/connectors/BlogTruyen.mjs#L11 .

Can you please look into the program before requesting sometign already done?
