### ISSUE TITLE
manhwa18 problem

### ISSUE THREAD

**Issue by FAReaper1** [manga-download/hakuneko#633]
![2](https://user-images.githubusercontent.com/54781955/68729427-9224bc80-05fc-11ea-968c-125a9d04e68e.png)
![1](https://user-images.githubusercontent.com/54781955/68729428-92bd5300-05fc-11ea-957e-1b288d903fa8.png)

**Comment by 27136773** [comment]
Error 503 is possible a CloudFlare issue, try to unlock the website through  [manual website interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#1-cloudflare-bypass)
