### ISSUE TITLE
[<Toonkor>] Connector not working

### ISSUE THREAD

**Issue by wamiscorner** [manga-download/hakuneko#6332]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

I noticed that Toonkor's URL is outdated. I was just wondering you guys could add the URL copy/paste, just like newtoki's. Thank you.

### To Reproduce

Currently, Toonkor is still active and I really wish to download the current new chapters and series that are there, thank you so much **_!_**

Toonkor is currently https://toonkor299.com

I would really like a feature like newtoki's where you can just copy/paste the URL.

Thanks _**!**_

**Comment by MikeZeDev** [comment]
Hum. Tricky one. Gotta use their telegram to get the URL :D

**Comment by wamiscorner** [comment]
> Hum. Tricky one. Gotta use their telegram to get the URL :D

I am aware. What I mean that is there a way to put the url in, like when you copy/paste the link url into the settings like newtoki?

**Comment by MikeZeDev** [comment]
> > Hum. Tricky one. Gotta use their telegram to get the URL :D
> 
> I am aware.

I meant programatically ;)
