### ISSUE TITLE
[Site Request] Taberu

### ISSUE THREAD

**Issue by brendonxv** [manga-download/hakuneko#6336]
**Website names**

Taberu Mangás

taberu.org

**Website urls**

- Site: https://taberu.org/

https://taberu.org/manga/

https://taberu.org/manga/kanojo-okarishimasu/

https://taberu.org/manga/kanojo-okarishimasu/cap-301/

**Languages**

Portuguese (Brazil)

**Website relationship*
-

**Additional details**
-

**Comment by MikeZeDev** [comment]
dead
