### ISSUE TITLE
[Bug] Download error, some episodes in the series can still be read but cannot be downloaded

### ISSUE THREAD

**Issue by ToiYeuTien** [manga-download/hakuneko#6337]
Hello !
I'm trying to download a manga collection from mangaraw.to
The story has 15 episodes, I have downloaded episodes 1 - 10, the remaining episodes show an error that they cannot be downloaded and cannot be read on Hakuneko.
But I can still read it in my browser.
Please help me fix it and download it!
Thank you!

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/6206
