### ISSUE TITLE
#621 Kissmanga stopped working completely

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#634]
> **From:** HakuNeko User

I passed the capchta at the site and am able to access the site without problems but cannot connect at all. I'm running off mac.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Try manual website interaction as described in #621

**Comment by 27136773** [comment]
No further response => closed
