### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by kanjieater** [manga-download/hakuneko#6340]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I'm trying to access DOGA from Web Action, but when i hit refresh on the latest nightly it still won't show.
https://comic-action.com/episode/14079602755328572625

### To Reproduce

1. Name of connector
 webアクション (Comic Action)
3. Name of manga (if connector update is working)
Doga
5. Name of chapter (if manga update is working)
1
6. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
No errors. 

It's not in this list:
![image](https://github.com/manga-download/hakuneko/assets/32607317/7cea5165-1c1f-40ab-a980-64ad1c6562f0)

**Comment by MikeZeDev** [comment]
Use copy paste feature in case a manga isnt in the list. Japanese websites are sometimes a mess.

![image](https://github.com/manga-download/hakuneko/assets/10671518/b910592a-123c-43c9-8f36-c0befdbba67c)
