### ISSUE TITLE
[<toongod.org>] Connector not working

### ISSUE THREAD

**Issue by dbleach777** [manga-download/hakuneko#6342]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Website works on browser & hakuneko (site preview only) but can't get manga list on sync even i try to get the manga by using clipboard connector link from browser/preview site
Maybe because the website URL is outdated?
![toongod website works](https://github.com/manga-download/hakuneko/assets/141564787/fea184f5-f703-4aeb-8fa6-18522cebde41)
![hakuneko nightly toongod](https://github.com/manga-download/hakuneko/assets/141564787/1cd22f9f-fe89-4b5f-8aed-be0047b3c085)

### To Reproduce

Change url website to https://www.toongod.org/  or (https://www.toongod.org/home/)?
Current url on hakuneko : https://www.toongod.com

That's the only solution that i can think of. This website is has good collection for all kinds of manhwa. Please make it works again.
:)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4507.

Chanding url is pointless is cloudflare

**Comment by dbleach777** [comment]
I use Proton vpn with free Japanese server and the cloudfire is gone! I can't get the list automaticly using sync on hakuneko but manually added the toongod manga URL and it works!

![Clipboard-20231020](https://github.com/manga-download/hakuneko/assets/141564787/778d685b-10ba-41ca-affe-716bc4e83fde)
![image](https://github.com/manga-download/hakuneko/assets/141564787/b58c38c0-b9ac-4012-9527-5eeeda2959c9)

**Comment by dbleach777** [comment]
> Duplicate #4507.
> 
> Chanding url is pointless is cloudflare

I use Proton vpn with free Japanese server and the cloudfire is gone! I can't get the list automaticly using sync on hakuneko but manually added the toongod manga URL and it works!

![Clipboard-20231020](https://github.com/manga-download/hakuneko/assets/141564787/778d685b-10ba-41ca-affe-716bc4e83fde)
![image](https://github.com/manga-download/hakuneko/assets/141564787/b58c38c0-b9ac-4012-9527-5eeeda2959c9)

but still without sync feature it's pain, i have to manually edit the bookmark every time i want to download the manga...
