### ISSUE TITLE
[<Cerise Scans>] Connector not working

### ISSUE THREAD

**Issue by Akarin2** [manga-download/hakuneko#6343]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

The chapters are not loading and several more recent manga are missing. In recent days there have been several attacks on online sites and scans (DMCA), some scans have made modifications to the site. Cerise announced that they would use a backup site, perhaps they changed the site. I also noticed that the link for some manga has changed.

This is the current website link: https://cerisescan.com/
And this is the link to a manga: https://cerisescan.com/manga/82/
And this is from one chapter: https://cerisescan.com/manga/82/cap-01/

### To Reproduce

1. Name of connector: Cerise Scans
2. Name of manga (if connector update is working): The name of the manga appears, but the new manga are missing
3. Name of chapter (if manga update is working): No chapter appears.
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/121842042/7bf29152-87a5-4684-bd07-bb5e45394c25)

**Comment by MikeZeDev** [comment]
There is a PR for that but PR opener doesnt answer.
