### ISSUE TITLE
[<FayScans>] Connector not working

### ISSUE THREAD

**Issue by Akarin2** [manga-download/hakuneko#6344]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

The chapters appear, but I can't download them. I tried several times, all downloads fail. I've tried downloading just one chapter and it also doesn't work. I tried to download it from another scan and I managed to do it, so I think it was an update from that scan/website.

### To Reproduce

1. Name of connector: Fay Scans
2. Name of manga (if connector update is working): How to Hide the Emperor’s Child 
3. Name of chapter (if manga update is working): 80 (All chapters appear, but the download fails for all)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/121842042/e93d1055-55db-4bea-872c-f4d4b8fb169f)

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/b4a119d8-cc5e-42ba-b064-290711dce726)

Really? This is what i got for the homepage.

![image](https://github.com/manga-download/hakuneko/assets/10671518/a24e435c-45b3-48bc-8eef-977f04e6d7cb)

If you are able to access to the site in your browser please ignore what i am about to say but : 

Please, DONT check a box saying it works in browser when it clearly doesnt. DONT just randomly check boxes because you are lazy those are important steps to diagnose a problem 😢 

Again, its a Portuguese website, i would not be surprised if it was another form of geoblocking. If thats the case, sorry for that rant. If the site is really dead thanks for reporting.

**Comment by MikeZeDev** [comment]
Turns out site is dead. Thanks for the information anyway.

**Comment by Akarin2** [comment]
The site is working normally for me.
Maybe it was down when you accessed it or it could be geoblocking, as you said
![image](https://github.com/manga-download/hakuneko/assets/121842042/5e54a393-2ac7-4e42-91d7-65a8fde73d59)
![image](https://github.com/manga-download/hakuneko/assets/121842042/6272afc1-d392-410f-b1a2-66ccb0ef64e5)

**Comment by MikeZeDev** [comment]
Nope, doesnt work. Well i can try something,

try replacing the content of FayScans.mjs with this 

```js
import WordPressMadara from './templates/WordPressMadara.mjs';

export default class FayScans extends WordPressMadara {

    constructor() {
        super();
        super.id = 'fayscans';
        super.label = 'Fay Scans';
        this.tags = [ 'manga', 'portuguese', 'scanlation' ];
        this.url = 'https://fayscans.com.br';
    }

    async _getPages(chapter) {
        const url = new URL(chapter.id, this.url);
        const request = new Request(url, this.requestOptions);
        const script = `
            new Promise((resolve, reject) => {
                var imgdata = JSON.parse(CryptoJS.AES.decrypt(chapter_data, wpmangaprotectornonce, {
                    format: CryptoJSAesJson
                }).toString(CryptoJS.enc.Utf8));
                resolve(JSON.parse(imgdata));
            });
        `;
        const data = await Engine.Request.fetchUI(request, script);
        return data.map(picture => this.createConnectorURI({url : picture, referer : url}));
    }
}


```

**Comment by MikeZeDev** [comment]
@Akarin2 I need your feedback

**Comment by Akarin2** [comment]
I'll try this weekend.

**Comment by Akarin2** [comment]
I'm sorry for the delay, but I couldn't do it.
The truth is that I have no experience in this type of thing, I even asked someone I knew for help and tried several times, but it didn't work. I tried installing with "npm install", but it didn't work. I can't say if this change solved the problem or not, because I couldn't make this change :(

**Comment by MikeZeDev** [comment]
You just had to open a file and copy paste tho. No  need to go further :/

**Comment by Akarin2** [comment]
It worked out. It was much easier. Sorry for the problems and thank you for your patience.
​

**Comment by MikeZeDev** [comment]
Thanks for your cooperation, but please dont close the issue until its fixed. Everyone need the fix :)
