### ISSUE TITLE
[Nightscans] Connector not working

### ISSUE THREAD

**Issue by zeoint** [manga-download/hakuneko#6349]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Wesbite changed to nightscans.net.

### To Reproduce

Wesbite changed to nightscans.net.

**Comment by MikeZeDev** [comment]
gotta change the url but it wont work , Cloudflare.

**Comment by zeoint** [comment]
Is it not possible to do the below method to bypass cloudflare,
1. Prompt user to solve captcha / cloudflare manually.
2. After solving it, close the prompt and download.
3. If clouldflare happens in between the downlad, auto-pause the download and loop steps 1 and 2.

[Reference link.](https://github.com/dteviot/WebToEpub/issues/991#issuecomment-1595573447)

**Comment by MikeZeDev** [comment]
Captcha wont resolve https://github.com/manga-download/hakuneko/issues/2933
