### ISSUE TITLE
[<Komiktap>] Connector not working

### ISSUE THREAD

**Issue by Emely028** [manga-download/hakuneko#6360]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list isn't refreshing, even manga chapter

### To Reproduce

1. Komiktap
2. I Meet You Again (if connector update is working)
3. All Chapter (if manga update is working)
![Screenshot_121](https://github.com/manga-download/hakuneko/assets/119110022/97103e22-7940-4a6e-a818-df73b6d08448)

**Comment by MikeZeDev** [comment]
Works for me. Can you close Hakuneko, start it, press F12, try refreshing the list and post screenshots please?

![image](https://github.com/manga-download/hakuneko/assets/10671518/7f57fa92-8168-4e05-b924-a159c01c7d68)

You could have been hijacked by a nasty ad :/
