### ISSUE TITLE
[Feature] Pre-parse and auto-update/refresh Bookmarks

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [manga-download/hakuneko#6366]
**Is your feature request related to a problem? Please describe.**

It takes too long for all my bookmarked manga titles to load 1 at a time as I select them. I'd like a way to pre-load (not download) all the titles in my Bookmark List, and reload an update maybe every hour or so (Possibly select-able in settings).

**Describe the solution you'd like**

A setting to pre-parse/load (not download) content (chapters) for the titles in my bookmark list upon program launch so when I click on the title it is ready for me to read or download right away instead of having to wait for the connector to load it as I select the titles, and with that a timed "Refresh" of the load that we can set for say every hour, 2 hours, 3 hours, 1 day, etc if the program is left open.

**Describe alternatives you've considered**

none really 

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]
 
Latest Nightly (master@4a29b4)

**Additional context**

**Comment by Sheepux** [comment]
Duplicate  https://github.com/manga-download/hakuneko/issues/653
Already done in haru https://github.com/manga-download/haruneko/issues/41

**Comment by GeneralUser-NonDev** [comment]
#41: This appears to be a bookmark (of sorts) of last chapter viewed per title, seems different from what I'm asking.

#653: This appears to be (from my reading of it) just a way for the program to "Notify" you of a new chapter (which would be nice), I assume that's the different color text on the title panel (white or grey) though I've yet to figure out whats what because I've got titles with new releases both colors when I check manually myself. again different from an "Auto-parse" feature.

In that case then I guess this becomes a  Broken report then, because when I click on a title (each one) it takes a minute or two to load the chapters, in my submission here it would do that automatically in the background at program start and when you click on a title it pops up instantly.
![Hakuneko Bookmarks](https://github.com/manga-download/hakuneko/assets/96662916/df52aaf1-b414-4b27-b668-cf62e965a1f1)

**Comment by Sheepux** [comment]
If you have the checkNewContent enabled > it will updates all bookmarks to check for items without flags (="new content") and therefore your bookmarks will be preloaded

Current Haru "classic" UI doesn't have the cache feature yet that exists in haku so when you click it will try to refresh. I'll work on that one this WE.

**Comment by GeneralUser-NonDev** [comment]
> If you have the checkNewContent enabled > it will updates all bookmarks to check for items without flags (="new content") and therefore your bookmarks will be preloaded
**Huh, I just went through the settings (Hamburger menu, Hakuneko) and don't see this option. Do I have to look in some advanced section somewhere else?**
> 
> Current Haru "classic" UI doesn't have the cache feature yet that exists in haku so when you click it will try to refresh. I'll work on that one this WE.
**I appreciate it, and sorry if I'm being a pain in the ---.**

**Comment by Sheepux** [comment]
I'm talking about haRuneko (notice the R). The next version of hakuneko under developpement https://github.com/manga-download/haruneko

**Comment by GeneralUser-NonDev** [comment]
> I'm talking about haRuneko (notice the R). The next version of hakuneko under developpement https://github.com/manga-download/haruneko

OK, I just found the download for that. After extracting and un-quarentine-ing the exe file from my norton I get 
"Hakuneko-app-nw.exe - Entry Point Not Found
The procedure entry point SetProcessMitigationPolicy could not be located in the dynamic link library KERNEL32.dll"

Do I have to put this in the original Hakuneku directory to work, or do I have to learn some kind of coding to get it? I see the main page is saying something about running a bunch of commands, do I have to do those if so where, Command prompt I assume?
If/when I do get HaRu working, will all my settings/bookmarks from HaKu port over, or will I have to look them up again?

Please don't take this the wrong way, but I did post this in the issues page for HaKu not knowing about the existence of (a new fork?) HaRu. I'm assuming the hakuneko project is dead and you're forking/continuing it to haruneko? As my screen name suggests, I don't know anything about codeing so I'm at your mercy with getting the program running and such. 

Again sorry for being a pain, and thanks for not only your patience with me, but also the program(s).

**Comment by Sheepux** [comment]
I'll make it simple : just wait until hakuneko v10 (codename haruneko)  is released (many months).
I'm closing this feature request as to clean the issue list from things that are already solved in the next version.
