### ISSUE TITLE
[<Neox Scanlator>] Connector not working

### ISSUE THREAD

**Issue by Akarin2** [manga-download/hakuneko#6367]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I click to load the manga list, but it ends without showing any manga. Maybe the site changed the link or made some modification to avoid DMCA issues, but the site it's working for me.

https://neoxscan.net/
https://neoxscan.net/manga/
https://neoxscan.net/manga/pre-37_57_46-548593-surpresa/
https://neoxscan.net/manga/pre-37_57_46-548593-surpresa/cap-124/

### To Reproduce

1. Name of connector: Neox Scanlator
2. Name of manga (if connector update is working) Not working
3. Name of chapter (if manga update is working) Not working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
considering the website is full of 
![image](https://github.com/manga-download/hakuneko/assets/10671518/e6dc45c5-5ca0-4dab-bded-cdf2449de8c4)

And chapters ends up like this

![image](https://github.com/manga-download/hakuneko/assets/10671518/7aca982c-361f-48dc-ae54-acaef2f6c437)

I wonder if i should bother fixing manga listing . Does the website works for you?

**Comment by MikeZeDev** [comment]
hum, just changed https://neoxscans.net for https://neoxscan.net and everything works, except getting pictures but i bet its again because of geoblocking.
