### ISSUE TITLE
[Site Request] BRMangás

### ISSUE THREAD

**Issue by Akarin2** [manga-download/hakuneko#6369]
**Name of the website**
BRMangás

**Website urls (examples below)**
- Site: https://www.brmangas.net/
- Manga List: https://www.brmangas.net/lista-de-manga/
- Manga example: https://www.brmangas.net/manga/daa-daa-daa-online/
- Chapter online viewer example: https://www.brmangas.net/ler/daa-daa-daa-1-online/#

**Languages**
Portuguese

**Website relationship*

**Additional details**

**Comment by MikeZeDev** [comment]
Cant access it unless from PT or BR IP i guess.

If its the same website than https://github.com/manga-download/hakuneko/issues/3621 please tell us and close this issue as duplicate.

**Comment by Akarin2** [comment]
Yes, it's the same. This site is older than I thought. Since it was a suggestion for a new website, I put it to search on hakuneko itself and not on github, my misteke. I'll try close.
