### ISSUE TITLE
[Site Request] blogtruyenmoi

### ISSUE THREAD

**Issue by minhprovip** [manga-download/hakuneko#6373]
**Name of the website**
blogtruyenmoi

**Website urls (examples below)**
- Site: https://blogtruyenmoi.com/
- Manga List: https://blogtruyenmoi.com/danhsach/tatca
- Manga example: https://blogtruyenmoi.com/13152/kanojo-to-kanojo-no-neko
- Chapter online viewer example: https://blogtruyenmoi.com/c208457/kanojo-to-kanojo-no-neko-chap-1

**Languages**
vietnamese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dont request already supported websites !

![image](https://github.com/manga-download/hakuneko/assets/10671518/7660b94d-6d7a-464a-aa73-120dcd047cf7)

**Comment by minhprovip** [comment]
This old website has been already sold for another company, the ex owner created a new website name blogtruyenmoi, "moi" is new in vietnamese. Thank u and sorry for my bad english.
![350841728_787478599581443_4885006997779401375_n](https://github.com/manga-download/hakuneko/assets/148124958/eaab35ec-7110-4c46-b1d9-ec1cec895ae3)
