### ISSUE TITLE
[Site Request] Cứu truyện

### ISSUE THREAD

**Issue by minhprovip** [manga-download/hakuneko#6374]
**Name of the website**
Cuu Truyen

**Website urls (examples below)**
- Site: https://hetcuutruyen.net/
- Manga List: https://hetcuutruyen.net/newest
- Manga example: https://hetcuutruyen.net/mangas/1628
- Chapter online viewer example: https://hetcuutruyen.net/mangas/1628/chapters/28067

**Languages**
vietnamese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5226
