### ISSUE TITLE
[<tcbscans>] Certain chapter downloads are not working.

### ISSUE THREAD

**Issue by gorksharamchandra** [manga-download/hakuneko#6375]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

1. Name of connector-https://tcbscans.com/
2. Name of manga My Hero Academia
3. Name of chapters- 264, 277,279,280,281,282,283,284,285
4. Error 404

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Pfff. Looks like they purposely put missing picture. And they cant be distinguished by name

![image](https://github.com/manga-download/hakuneko/assets/10671518/ac0e9588-fd96-45ef-bdc8-a303ed9565cd)

Thanks for reporting, idk what to do.
