### ISSUE TITLE
[Site Request] mangaland

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#6377]
**Name of the website**
mangaland

**Website urls (examples below)**
- Site: https://mangaland.net/
- Manga List: https://mangaland.net/biblioteca/
- Manga example: https://mangaland.net/manga/el-menu-secreto-de-la-entrega-especial/
- Chapter online viewer example: https://mangaland.net/manga/el-menu-secreto-de-la-entrega-especial/capitulo-1/

**Languages**
Spanish

**Comment by MikeZeDev** [comment]
Madara

**Comment by MikeZeDev** [comment]
dead
