### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by Lost8person** [manga-download/hakuneko#6378]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

![IMG20231031224353](https://github.com/manga-download/hakuneko/assets/149522216/54577c61-20b5-47ec-99f6-265f1c8f7dfc)
I don't know what to do 

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Not sure was going on here. Does the folder exists? Is it empty?  You have access rights?

**Comment by MikeZeDev** [comment]
Is your problem solved?
