### ISSUE TITLE
[Site Request] Hwago.id

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#6381]
**Name of the website**
Hwago.id

**Website urls (examples below)**
- Site: https://hwago.id/
- Manga List: https://hwago.id/komik/
- Manga example: https://hwago.id/komik/dreaming-freedom/
- Chapter online viewer example: https://hwago.id/komik/dreaming-freedom/chapter-113/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Using madara theme

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6259
