### ISSUE TITLE
[Kakaopage] Connector not working

### ISSUE THREAD

**Issue by vetp** [manga-download/hakuneko#6387]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

not working

**Comment by MikeZeDev** [comment]
> Manga list isn't refreshing

And is perfectly normal. Hakuneko is displaying this 

![image](https://github.com/manga-download/hakuneko/assets/10671518/18bb0abc-8046-417c-9071-f3465fb29974)

meaning you have to use the copy paste feature.  Its written right here.  Please refrain opening tickets without reading the error messages  or the manual

https://hakuneko.download/docs/FAQ/#copy-and-paste

Hum well you need to paste the MANGA link the message is a bit wrong :/

**Comment by MikeZeDev** [comment]
Ho and there has been a [fix ](https://github.com/manga-download/hakuneko/blob/4a29b4c79a7de11723fbf651e42055e765333933/src/web/mjs/connectors/kakaopage.mjs#L4)last month for chapters, make sure to use [hakuneko nightly build !](https://github.com/manga-download/hakuneko/releases)

**Comment by vetp** [comment]
> > A lista de mangás não é refrescante
> 
> E é perfeitamente normal. Hakuneko está exibindo isso
> 
> ![imagem](https://private-user-images.githubusercontent.com/10671518/280263086-18bb0abc-8046-417c-9071-f3465fb29974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDYzOTUsIm5iZiI6MTcwMTQ0NjA5NSwicGF0aCI6Ii8xMDY3MTUxOC8yODAyNjMwODYtMThiYjBhYmMtODA0Ni00MTdjLTkwNzEtZjM0NjVmYjI5OTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE1NTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MDU2YmE0NTRjMGVlN2M1OWMyZGE3ZGY2NTY5MmI3NDRkNzY2ZDhhNmI4MDU5NjFlZDk5MjlhYTBlZTU5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qAwIgtapvqENne4dL_C7IJAB5x0o4WPhCsVSLaSVutY)
> 
> o que significa que você deve usar o recurso de copiar e colar. Está escrito aqui. Evite abrir tickets sem ler as mensagens de erro ou o manual
> 
> https://hakuneko.download/docs/FAQ/#copy-and-paste
> 
> Hum, bem, você precisa colar o link do MANGA, a mensagem está um pouco errada :/

Eu estava tentando pelo metodo copiar e colar
