### ISSUE TITLE
webtoon.com cannot load old comic

### ISSUE THREAD

**Issue by n13oss** [manga-download/hakuneko#6390]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Hi , it's look like old comic from webtoon that link number below 1000 cannot load by software.

Example fail download
https://www.webtoons.com/th/action/lookism/list?title_no=576 - Cannot load chapter 01 - 70
https://www.webtoons.com/th/fantasy/hell-warden-roruv/list?title_no=746

Example success download
https://www.webtoons.com/th/romance/into-the-boundary-of-love/list?title_no=4794
https://www.webtoons.com/th/romance/i-need-a-bride/list?title_no=3630

Could you please fix these ?

Thanks in advance.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Downloaded a couple of chapters from mentioned "failing" webtoons, no pb .

Well there are random HTTP2 protocol not supported error but id number has nothing to do with them. And idk whats going on in those case.

If you followed the ticket correctly you should already be using nightly so try increasing throttling for LinewebtoonTH in Hakuneko settings, maybe. It wont work in stable version its important to use nightly.

**Comment by n13oss** [comment]
oh yes , you are right. I downloaded latest nightly version , install  and all chapters are load up.

I thought I install nightly version at that time but it's not , my mistake. I downloaded wrong link haha.
