### ISSUE TITLE
[<Nettruyen>] Connector not working

### ISSUE THREAD

**Issue by minhduc1212** [manga-download/hakuneko#6391]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Website has changed the domain to nettruyenus.com 
![image](https://github.com/manga-download/hakuneko/assets/108139083/2ab39b6e-607c-4e0d-ad82-244d71da7881)

### To Reproduce

1. NetTruyen
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. ERR_NAME_NOT_RESOLVED https://www.nettruyenplus.com. The domain of this website changed to nettruyenus.com

**Comment by MikeZeDev** [comment]
Change url in hakuneko settings.

**Comment by minhduc1212** [comment]
> Change url in hakuneko settings.

i can't see the settings of nettruyen

**Comment by minhduc1212** [comment]
> Change url in hakuneko settings.

I have found the mistake,, the url hasn't been update in NetTruyen.mjs it is still nettruyenplus.com

**Comment by minhduc1212** [comment]
> Change url in hakuneko settings.

![image](https://github.com/manga-download/hakuneko/assets/108139083/d40aeff8-5431-4be9-8f6a-69a0d0a711b5)

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/f3942311-d53f-4f08-8475-014bde8a6084)

You checked the box saying you tried nightly, so you should have nightly and there is a setting here. 

This website change url waaaaaaaaay to often, is annoying to maintain so url is a setting you can change.

**Comment by minhduc1212** [comment]
> ![image](https://user-images.githubusercontent.com/10671518/280472318-f3942311-d53f-4f08-8475-014bde8a6084.png)
> 
> You checked the box saying you tried nightly, so you should have nightly and there is a setting here.
> 
> This website change url waaaaaaaaay to often, is annoying to maintain so url is a setting you can change.

I'm so sorry as not to check carefully. Thank you so much for your support

**Comment by MikeZeDev** [comment]
Its ok, Url settings are not advertised enough, cant blame you :D
