### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by seankid1409** [manga-download/hakuneko#6397]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Hello !
With this website : https://mangaraw.to/ was update a new way to reading manga, so this tool can not download image anymore, can you help me to update it?
Chapter demo: https://mangaraw.to/chapters/%e3%80%90%e7%ac%ac12%e8%a9%b1%e3%80%91%e3%80%8c%e4%bb%95%e4%ba%8b%e4%b8%ad%e3%81%ab%e3%81%9d%e3%82%93%e3%81%aa%e5%a5%a5%e3%81%be%e3%81%a7%e3%81%a3%e2%80%a6%e3%83%80%e3%83%a1%e3%81%a3%ef%bc%81%e3%80%8d%ef%bd%9e%e4%b8%8a%e5%8f%b8%e3%81%ab%e3%83%92%e3%83%9f%e3%83%84%e3%81%ae%e5%af%86%e7%9d%80%e5%8f%96%e6%9d%90-raw/
Thanks

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/6206
