### ISSUE TITLE
[tempestfansub] fix manga listing

### ISSUE THREAD

**Issue by EmojiPati** [manga-download/hakuneko#6399]
**Name of the website**
tempestfansub

**Website urls (examples below)**
- Site: https://tempestfansub.com/
- Manga List: https://tempestfansub.com/manga
- Manga example: https://tempestfansub.com/manga/lanet-savaslari/
- Chapter online viewer example: https://tempestfansub.com/lanet-savaslari-1/

**Languages**
Turkish

**Website relationship*
Request to change the domain name manga.tempestfansub.com to tempestfansub.com.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
doesnt answer for me.

**Comment by EmojiPati** [comment]
> doesnt answer for me.

We're under a lot of attack these days. I'd appreciate it if you'd try again.

**Comment by MikeZeDev** [comment]
Domain doenst need to be changed, its already the good one lmao. I am gonna change manga listing to use single page, since its now possible.
