### ISSUE TITLE
[<phenixscans.fr>] Connector not working

### ISSUE THREAD

**Issue by dente** [manga-download/hakuneko#6400]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Hello,
I had posted a ticket for the download that didn't seem to work for the [phenixscan ](https://github.com/manga-download/hakuneko/issues/6385)site and the ticket seems to be closed. Unfortunately I don't know if this is the reason but now it's not even possible to list the chapters.

Thank you in advance for your work and your help !

### To Reproduce

1. Name of connector : phenixscans.fr
2. Name of manga (if connector update is working) : pick me up
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/6699441/aa7e119c-954c-45eb-b9b4-b2aa77fcb082)
![image](https://github.com/manga-download/hakuneko/assets/6699441/0d568202-f324-44f7-882c-e4242cc821c8)

**Comment by MikeZeDev** [comment]
Cant fix CF. Old ticket was closed because the issue was solved by a fix but its unrelated.

**Comment by MikeZeDev** [comment]
No more CF
