### ISSUE TITLE
[<ScanManga>] Connector not working

### ISSUE THREAD

**Issue by dente** [manga-download/hakuneko#6401]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hello,
I think the error speaks for itself, but I can't seem to download the list of mangas on ScanManga.com (French at least, but I don't know about other languages).

### To Reproduce

1. Name of connector : Scanmanga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/6699441/b88b3487-f32d-482a-984e-1de4f05e9b20)

**Comment by MikeZeDev** [comment]
Manga list wont work. if you try to open the JSON url its just empty. Its the same in my browser. It has been like that for a while, i dont know what they are doing.

**Comment by MikeZeDev** [comment]
Cloudflare

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3460
