### ISSUE TITLE
crunchyscan

### ISSUE THREAD

**Issue by tetem75015** [manga-download/hakuneko#6403]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

no possibility to donwload mangas

### To Reproduce

1. crunchyscan
2. maison ikkoku

**Comment by MikeZeDev** [comment]
1) Cloudflare cant fix
2) There is already an issue opened for that website stop spamming issues and use the search feature BEFORE
