### ISSUE TITLE
sushi scans

### ISSUE THREAD

**Issue by tetem75015** [manga-download/hakuneko#6405]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

none liste can be displayed

### To Reproduce

1. sushi scans

**Comment by MikeZeDev** [comment]
1) Cloudflare cant fix
2) There is already an issue opened for that website stop spamming issues and use the search feature BEFORE
