### ISSUE TITLE
https://www.scan-manga.com/

### ISSUE THREAD

**Issue by tetem75015** [manga-download/hakuneko#6406]
**Name of the website**
scan-manga

**Website urls (examples below)**
- Site: https://www.scan-manga.com/
- Manga List: https://www.scan-manga.com/TOP-Manga-Webtoon-24.html
- Manga example: https://www.scan-manga.com/5278/Martial-Peak.html
- Chapter online viewer example: https://www.scan-manga.com/lecture-en-ligne/Martial-Peak-Chapitre-1-FR_83800.html

**Languages**
french

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
There is a ticket opened for this website on the FIRST PAGE OF the issues. Please search before opening useless tickets.

![image](https://github.com/manga-download/hakuneko/assets/10671518/7ea64923-59d2-4851-822a-52301fc51417)

**Comment by tetem75015** [comment]
ok but have you ever fixed the issue ?
