### ISSUE TITLE
japscan.lol

### ISSUE THREAD

**Issue by tetem75015** [manga-download/hakuneko#6407]
**Name of the website**
japscan.lol

**Website urls (examples below)**
- Site: https://www.japscan.lol/
- Manga List: https://www.japscan.lol/
- Manga example: https://www.japscan.lol/manga/kingdom/
- Chapter online viewer example: https://www.japscan.lol/lecture-en-ligne/kingdom/777/

**Languages**
french

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Search before opening a request !https://github.com/manga-download/hakuneko/issues/4657
