### ISSUE TITLE
[Site Request] Qua anh dao cuteo

### ISSUE THREAD

**Issue by Froktime** [manga-download/hakuneko#6414]
**Name of the website**
Qua anh dao cuteo

**Website urls (examples below)**
- Site: https://quaanhdaocuteo.com/
- Manga List: https://quaanhdaocuteo.com/
- Manga example: https://quaanhdaocuteo.com/manga/lac-giua-nhung-tang-may-bl/
- Chapter online viewer example: https://quaanhdaocuteo.com/manga/lac-giua-nhung-tang-may-bl/chuong-1/

**Languages**
Vietnamese

**Website relationship*
Haven't

**Additional details**
This is a BL website.

**Comment by MikeZeDev** [comment]
Dev note; Madara

**Comment by MikeZeDev** [comment]
dead
