### ISSUE TITLE
[Site Request] Comic Zenon

### ISSUE THREAD

**Issue by Froktime** [manga-download/hakuneko#6416]
**Name of the website**
Comic Zenon

**Website urls (examples below)**
- Site: https://comic-zenon.com/
- Manga List: https://comic-zenon.com/comics
- Manga example: https://comic-zenon.com/episode/13933686331689929651
- Chapter online viewer example: https://comic-zenon.com/episode/13933686331689929651

**Languages**
Japanese

**Website relationship*
Haven't

**Additional details**

**Comment by MikeZeDev** [comment]
Please

![image](https://github.com/manga-download/hakuneko/assets/10671518/a21b5e39-85b1-41d1-82d0-e6a21516ebd2)

Check before requesting, its already supported .
