### ISSUE TITLE
[Batoto (by AnyACG)] Connector not working

### ISSUE THREAD

**Issue by Hans-2023** [manga-download/hakuneko#6419]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

It seems the website itself has changed domains (it was bath.to and now is dot.to), therefore the connection never loads or works. The refresh just keeps loading and loading and nothing else happens. 

### To Reproduce

1. Name of connector: Batoto (by AnyACG)
2. Name of manga (if connector update is working): N/A
3. Name of chapter (if manga update is working): N/A
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): N/A

**Comment by MikeZeDev** [comment]
use setting to change url

![image](https://github.com/manga-download/hakuneko/assets/10671518/8f647add-1870-4612-9036-2d804428f6eb)
