### ISSUE TITLE
[Site Request] Bata.to (dto.to)

### ISSUE THREAD

**Issue by Hans-2023** [manga-download/hakuneko#6420]
**Name of the website:**
Bata.to v3x

**Website urls (examples below)**
- Site: https://dto.to/v3x
- Manga List: https://dto.to/v3x-search?sort=field_name&page=1
- Manga example: https://dto.to/title/81514-solo-leveling-official
- Chapter online viewer example: https://dto.to/title/81514-solo-leveling-official/1559439-ch_1

**Languages**
Chinese, English, Japanese, Korean for the main original work languages. 

They support many other languages (see attached screenshot) 

<img width="1434" alt="Screenshot 2023-11-10 at 12 53 20" src="https://github.com/manga-download/hakuneko/assets/150474586/4d45fd63-68de-47aa-8300-fe88b36c1965">

**Website relationship**
You can find a list of their mirrors here: https://rentry.co/batoto

**Additional details**
There is a connector that no longer works, this site is the updated website for that connector: 
Batoto (by AnyACG)

**Comment by MikeZeDev** [comment]
no need use setting to change url 
![image](https://github.com/manga-download/hakuneko/assets/10671518/4bd9ab39-d5f3-4c93-a1c8-643833b42d36)
