### ISSUE TITLE
[<Lilymanga>] Connector not working

### ISSUE THREAD

**Issue by n13oss** [manga-download/hakuneko#6421]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

![Screenshot 2023-11-11 221058](https://github.com/manga-download/hakuneko/assets/21300857/e2528cf4-169f-4dd2-8868-455d830251b1)
https://lilymanga.net/
I can choose manga name but chapter are not load.

https://lilymanga.net/ys/misterioso/

For example link but it's happen to all manga.

### To Reproduce

1. Lilymanga
2. misterioso (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/5868
