### ISSUE TITLE
[AllHentai] Domain change

### ISSUE THREAD

**Issue by HaruKunOFF** [manga-download/hakuneko#6424]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

It is necessary to replace 24.allhen.online with 20.allhen.online. This is a more up-to-date site address, the first one does not work.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
You could at least have filled the template properly, you dont even mention the website NAME 😢 
Please.

**Comment by HaruKunOFF** [comment]
Sorry, English is not my native language. In the program ID of the allhentai website . URL: https://24.allhen.online at the moment, now relevant https://20.allhen.online /. It seems that at the moment they will not change it. As I understand it, they had difficulties with regulators, but it seems they have already agreed

**Comment by HaruKunOFF** [comment]
What I wrote above concerns the nightly version. in the stable version, the current URL https://2023.allhen.online/

**Comment by MikeZeDev** [comment]
Yeah i knew the website already, i mean in issue title. You see other issues? They all have website title ^^. Got it changed, wait for the fix.

**Comment by HaruKunOFF** [comment]
Thanks, you're better bro
