### ISSUE TITLE
Add support for Indonesian Novel Sites

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#643]
Thanks for supporting novel feature.

- https://indomtl.com/

- https://novelgo.id/

- https://novelringan.moe/ (this site must login to read more than 2 times) (can you make this to unlimited reads)

- https://isekaiwebnovel.com/

- https://mynovel.net/

- https://lfnovels.com/

- https://www.idqidian.us/

- https://overlordfree.web.id/

- https://lnindo.org/

- https://www.luinovel.xyz/

- https://www.worldnovel.online/

- https://wbnovel.com/

- https://4scanlation.com/

- https://www.aggsannovel.xyz/

Thanks Alot

**Comment by 27136773** [comment]
Please make a single ticket for each requested website, handling multiple issues in a single ticket is to confusing for the developers in case of discussion, feedback loops and status changes.
