### ISSUE TITLE
[Piccoma France] Connector not working

### ISSUE THREAD

**Issue by onelots** [manga-download/hakuneko#6430]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

@Elastic1 Hi dude, Piccoma changed their scrambeling method ig, here is an example of what I get rn : 

![image](https://github.com/manga-download/hakuneko/assets/54822802/abcd4d69-c254-45ae-bb60-77af736b5ea1)

If you could try to check this I would really appreciate 🙏 thx in advance
### To Reproduce

1. PiccomaFR
2. any manga

**Comment by Mahora2106** [comment]
Hello, this no longer works for piccoma, the images are new encrypted.
