### ISSUE TITLE
Removal Request for [https://manga-tr.com/]

### ISSUE THREAD

**Issue by McMaster68** [manga-download/hakuneko#6433]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Which website should be removed?
[https://manga-tr.com]

Why should this website be removed from HakuNeko?
[It was added unannounced as site management.]

#### In case of Traffic
1. How much traffic is caused by HakuNeko?
[It causes a lot of traffic.]
2. How much is it compared to overall traffic (percentage)?
[It causes an extreme slowdown in the server server.]
3. How did you measure those analytics (framework)?
[YOUR ANSWER HERE]
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
[There are certain slowdowns in the boat shots when entering and exiting.]
5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
[No, we don't. That's why it causes slowdowns.]

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
[Yes, we are aware. But we are still trying to reduce it.]
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
[Yes, of course.]
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
[Nope.]

#### In case of Monetization
1. Are you using Donations?
[YOUR ANSWER HERE]
2. Are you using Advertisements?
[YOUR ANSWER HERE]

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by Sheepux** [comment]
This connector has been there for years. I doubt the issue is suddenly about hakuneko's traffic as the replies to the questions "how do you know it's linked to hakuneko's traffic" are evasives.
User also requested connectors and his github history also shows he's been using alternatives such as FMD / Tachiyomi. There is some kind of hypocrisy in requesting removal.

Adding my vote to reject the request

**Comment by McMaster68** [comment]
> This connector has been there for years. I doubt the issue is suddenly about hakuneko's traffic as the replies to the questions "how do you know it's linked to hakuneko's traffic" are evasives. User also requested connectors and his github history also shows he's been using alternatives such as FMD / Tachiyomi. There is some kind of hypocrisy in requesting removal.
> 
> Adding my vote to reject the request

Good afternoon, I do not want to start a discussion, but we have stated that we do not want our site to be added to applications such as tachiyomi, fmd, hakuneko without our knowledge. Likewise, we even blocked it in tachiyomi. But they still do not respond to our deletion request. On FMD, I think I remember we opened it. I don't understand what it has to do with hypocrisy, thank you. We would be grateful if you can get back to us.

**Comment by 27136773** [comment]
> I do not want to start a discussion

This ticket would have been the perfect place for discussions, but fine with me as this saves time and stress.

Rejected, since the opener does not want to discuss further details about traffic measurement and the contradiction of requesting support for downloading from other TR websites, but want to remove the owned TR website.

**Comment by McMaster68** [comment]
> > I do not want to start a discussion
> 
> This ticket would have been the perfect place for discussions, but fine with me as this saves time and stress.
> 
> Rejected, since the opener does not want to discuss further details about traffic measurement and the contradiction of requesting support for downloading from other TR websites, but want to remove the owned TR website.

Ahaha, you're too funny. You don't care about sites for money.
