### ISSUE TITLE
 MangaStorm

### ISSUE THREAD

**Issue by ninayona** [manga-download/hakuneko#6434]
**Name of the website**
 MangaStorm

**Website urls (examples below)**
- Site: https://mangastorm.org/
- Manga List: https://mangastorm.org/mangas
- Manga example: https://mangastorm.org/mangas/18-solo-leveling
- Chapter online viewer example: [[https://thhttps://thewebsiteurlewebsiteurl/manga/0012/view.html](https://mangastorm.org/mangas/18-solo-leveling/chapter/200)
]
**Languages**
List of languages supported by the website 
 [Arabic]
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/6434
