### ISSUE TITLE
need new release tagged

### ISSUE THREAD

**Issue by tidux** [manga-download/hakuneko#6439]
The last tagged release is years old.  Can we get a new one so places like Flathub can update?

**Comment by 27136773** [comment]
<img width="906" alt="image" src="https://github.com/manga-download/hakuneko/assets/27136773/faccac49-da4b-42bd-8c6c-59f103a17be6">

**Comment by chenrui333** [comment]
@ronny1982 I dont quite understand the hassle of cutting a new release, so I filed [an new issue](https://github.com/manga-download/hakuneko/issues/6641) of asking for a new release from package management perspective. Let me know if that helps! (Happy new year!)
