### ISSUE TITLE
[mangadex] Connector not working

### ISSUE THREAD

**Issue by Certez1** [manga-download/hakuneko#6445]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

manga list isn't loading. Can't find api

### To Reproduce

1. mangadex

**Comment by MikeZeDev** [comment]
Did you try nightly build with increased throttle setting ? because the problem is known and the solution is slowing down like that
