### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6447]
**Name: Ler Mangá
thewebsitename: Ler mangá

- Site: https://lermanga.org
- Manga List: https://lermanga.org/mangas/
- Manga example: https://lermanga.org/mangas/barbarian-quest/
- Chapter online viewer example: https://lermanga.org/capitulos/barbarian-quest-capitulo-72/

**Languages**
Português Brazil. 

**Website relationship*
Hello. We use hakuneko a lot to upload manga on our website. I could add this site to Hakuneko.

**Comment by MikeZeDev** [comment]
Another day, another PT-br region locked website. 

* please fill the TITLE properly :/
* please search before, https://github.com/manga-download/hakuneko/issues/6347 its already requested.
