### ISSUE TITLE
[Manga-chan] Cant access

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6448]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Hello. Mangas chan (that's the name of the site) does not carry any manga.

The website is working normally, however, on Hakuneko it stopped working yesterday.

![imagem_2023-11-21_200620340](https://github.com/manga-download/hakuneko/assets/151384031/93d6dc2e-8a0e-4150-84c1-45884b1c0279)

![Captura de tela 2023-11-21 200353](https://github.com/manga-download/hakuneko/assets/151384031/b0f4f662-5094-4463-bbc5-bc950de61b34)

**Context (please complete the following information):**
  . Windows11
 - HakuNeko Version 8.3.4

**Comment by MikeZeDev** [comment]
Website is not working at all

![image](https://github.com/manga-download/hakuneko/assets/10671518/546507a8-82f9-41d3-9793-3ca6fce46c82)

**Comment by MikeZeDev** [comment]
Maybe you are referring to https://mangaschan.net/ and not https://manga-chan.me.  It doesnt matter as devs cant access to it

![image](https://github.com/manga-download/hakuneko/assets/10671518/8c3617c7-cc66-4471-821c-b664b204f585)

**Comment by MikeZeDev** [comment]
https://mangaschan.com/ is down .

![image](https://github.com/manga-download/hakuneko/assets/10671518/396751a8-58c7-4754-ab54-67fd5f2d6ff8)

I dont know where you saw it "working normally"

https://mangaschan.net/ is unreachable outside PT-BR ip.

**Comment by MikeZeDev** [comment]
And now the first is redirecting to the second.

**Comment by MikeZeDev** [comment]
@CristianoLBR Is the mangachan plugin working properly even if url changed? If yes just rename the issue using "domain changed"

**Comment by DartinSA** [comment]
@MikeZeDev for now its not working, The manga list script has the old domain in search
![image](https://github.com/manga-download/hakuneko/assets/97482945/66b8e9a4-9a44-49bf-8302-351c9fbe1f4a)

**Comment by MikeZeDev** [comment]
On phone now but perhaps its blocked for non pt br ip so idk i wont do anything if cant see it working ilsee tomorrow
