### ISSUE TITLE
Add file .mjs but I couldn't find the website

### ISSUE THREAD

**Issue by YainuWan11** [manga-download/hakuneko#6449]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**
I'am Add file OremangaNet.mjs in Manga Download (https://github.com/manga-download/hakuneko/pull/6443) complete. But I couldn't find the website oremanga on Hakuneko web app. In addition, I tried delete old cache on my computer, but still can't find.

**Expected behavior**
I want to find a website oremanga. net on Hakuneko web app and can download pictures.

**Context (please complete the following information):**
 - HakuNeko Version 6.17

**Comment by MikeZeDev** [comment]
Use nightly
