### ISSUE TITLE
[<Kuaikanmanhua>] Connector not working

### ISSUE THREAD

**Issue by Froktime** [manga-download/hakuneko#6450]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

The website is only available for viewing on mobile devices and cannot be used on computers/pc/macbook
<img width="900" alt="image" src="https://github.com/manga-download/hakuneko/assets/98095197/0befd2ba-36b5-4e29-9c52-dabec9c8d173">
<img width="800" alt="image" src="https://github.com/manga-download/hakuneko/assets/98095197/6697052e-6a6b-47d3-85b1-b1c1dfa345e7">
Sample link on mobile devices: https://m.kuaikanmanhua.com/mobile/15716/list/
Sample link on PC: https://www.kuaikanmanhua.com/web/topic/15716/

### To Reproduce

1. Kuaikanmanhua
2. Limited to many BL manhuas, some BG manhuas

**Comment by MikeZeDev** [comment]
They need mobile user agent AND login , what a pain
