### ISSUE TITLE
[Flame Scans] Connector not updated

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [manga-download/hakuneko#6452]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

This connector seems to have been fixed 3 weeks ago, but the connector in my system seems to be still the one from before, so no dice. It looks for updates and downloads the manga, but it doesn't update the connector.
Also, when I installed the nightly version, I lost the exit button.

### To Reproduce

1. Name of connector: Flame Scans
2. Name of manga (if connector update is working): <- this is the issue
3. Name of chapter (if manga update is working): <- any
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
```
hakuneko://plugins:1
Failed to load resource: net::ERR_NOT_IMPLEMENTED        


Settings.mjs:378 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
(anonymous) @ Settings.mjs:378


DevTools failed to parse SourceMap: hakuneko://cache/js/protobuf.min.js.map


DevTools failed to parse SourceMap: hakuneko://cache/js/hls.light.min.js.map


DevTools failed to parse SourceMap: hakuneko://cache/sm/4f4f84956292156efc04b79e1131dc7c3a51794b7b3d62b43ed5eaca1b36d71e.map


ClipboardConnector.mjs:66
CLIPBOARD: https://flamecomics.com/series/ Error: No matching connector found for URL  
https://flamecomics.com/series
    at ClipboardConnector.mjs:59 at Array.map (<anonymous>)
    at ClipboardConnector._getMangaList (ClipboardConnector.mjs:48)
    at ClipboardConnector.updateMangas (ClipboardConnector.mjs:28) 
    at HTMLElement.onUpdateMangaListClick (mangas.html:233) 
    at HTMLElement.onPasteClick (mangas.html:339) 
    at HTMLElement.handler (template-stamp.html:96)
 (anonymous)                  @  ClipboardConnector.mjs:66 
 _getMangaList                @  ClipboardConnector.mjs:48  
 updateMangas                 @  ClipboardConnector.mjs:28  
 onUpdateMangaListClick       @  mangas.html:233 
 onPasteClick                 @  mangas.html:339 
 handler                      @  template-stamp.html:96
```

EDIT: This message appears if I still try to use the connector:
![image](https://github.com/manga-download/hakuneko/assets/36646277/95bbfab8-a28f-4d02-adbc-9d751d168e18)

**Comment by l-l-l-l-l-l** [comment]
As a side note, I have the latest nightly installed (8.3.4.0) but the about screen shows "rev. 6.1.7@513208".

EDIT: the nightly build broke all compatibility; I reinstalled the stable build and turned the current FlameScans connector into a plugin with the needed tweaks and it seems to work that way. The true connector is still not updated, but the pluginone connects as it should.

**Comment by MikeZeDev** [comment]
HU? Compatibility ? The "true connector"? Broken? 

I dont understand anything. I just use Nightly and it works 

![image](https://github.com/manga-download/hakuneko/assets/10671518/988caa03-63bb-42ba-a10e-1cbeeb03b9f5)

**Comment by MikeZeDev** [comment]
Also you pasted ```https://flamecomics.com/series/``` Hakuneko expect a manga url, not a mangalist url .

Like this ```https://flamecomics.com/series/forty-eight-hours-a-day/```

![image](https://github.com/manga-download/hakuneko/assets/10671518/78c13925-156f-41fd-ae5b-3200ef325859)

**Comment by l-l-l-l-l-l** [comment]
> Also you pasted `https://flamecomics.com/series/` Hakuneko expect a manga url, not a mangalist url .
> 
> Like this `https://flamecomics.com/series/forty-eight-hours-a-day/`

I also tried with a manga link, but still the same. It's as if hakuneko refused to update. The conector as custom plugin seems to work mostly fine, though.

EDIT: this is what it does pasting that URL with the plugin disabled, which means relying on the inbuilt connector:
![image](https://github.com/manga-download/hakuneko/assets/36646277/ba382c81-9dd3-4e4a-90cf-7caed1f0d83f)


As evidence, when I try to use the "open website" option of the connector, what I get is this:
![image](https://github.com/manga-download/hakuneko/assets/36646277/effd4a21-a4fd-4acf-b116-f373cae36991)
... which means it's still pointing to https://flamescans.org

I've also tried downloading the portable version of the latest nightly, but that one gets stuck in a white screen forever.

**Comment by l-l-l-l-l-l** [comment]
Found a way to manually update all connectors, but someone should check if there are any circumstances where hakuneko doesn't update.

**Comment by MikeZeDev** [comment]
Are you sure you got nightly?

**Comment by l-l-l-l-l-l** [comment]
After whatever version I had failed to update the connector, I installed this latest version to overwrite it:
![image](https://github.com/manga-download/hakuneko/assets/36646277/e04c36ce-6e8d-4bd2-9af7-524f9cb691ed)

The weird thing is that now that I manually updated the cache folder at %USERDATA%\Local\hakuneko-desktop with the contents of the src/web folder from this repository, whenever I open hakuneko it first looks like this:
![image](https://github.com/manga-download/hakuneko/assets/36646277/8cfd2645-b8b8-4132-848f-7e639ac11fd4)

then like this once I close the window or wait about 5-10 seconds:
![image](https://github.com/manga-download/hakuneko/assets/36646277/9730a658-530a-4587-b05c-5f07a4d97bfd)

fixing once and for all the issue I previously had where I needed to close the Nightly version from the taskbar.

And now the version actually says this:
![image](https://github.com/manga-download/hakuneko/assets/36646277/233589ce-820e-4bfc-bd83-c52e175411f0)

instead of the rev. 6.1.7@513208 it said before (after running the installer)

**Comment by MikeZeDev** [comment]
nightly says 

![image](https://github.com/manga-download/hakuneko/assets/10671518/97120a53-7c5f-49ee-b889-6b3805e71468)

**Comment by MikeZeDev** [comment]
Nightly should be something about build version 
![image](https://github.com/manga-download/hakuneko/assets/10671518/12536b73-e2a9-4a81-b678-b362fd1c13e6)

Idk why you got HEAD.  Now that you messed with the folders yourself when its not needed idk whats going on.
Better nuke folders in appdata and launch program again.
