### ISSUE TITLE
[Bug] UI not usable/displayed on Wayland

### ISSUE THREAD

**Issue by Minecodes** [manga-download/hakuneko#6455]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Elements in the window are black or not there, or the window doesn't start at all.

**To Reproduce**
1. Install Linux with Gnome (for best reproduction with Arch Linux, linux-lqx kernel, and proprietary NVIDIA drivers)
2. Start `/usr/lib/hakuneko-desktop/hakuneko` via terminal
3. See error

**Expected behavior**
The window doesn't open and displays an error that says that the display composer crashed multiple times.

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/65566012/364566be-7468-4142-b7b5-1816c28fb41a)

**Context (please complete the following information):**
 - OS: Arch Linux (Gnome (Wayland) via desktop preset in `archinstall`, linux-lqx with proprietary NVIDIA drivers and RTX 3060 Ti)
 - HakuNeko Version: v6.1.7

**Additional context**
The application runs with XWayland (because it uses X11). I also tried to manually reset it by deleting the cache and tried workarounds.

**Comment by Sheepux** [comment]
Use --no-sandbox as workaround

**Comment by Minecodes** [comment]
I didn't know that one. Thanks! I think it would be practical to add it to the troubleshooting page.
