### ISSUE TITLE
[Site Request] TuMangaOnline

### ISSUE THREAD

**Issue by anndriu** [manga-download/hakuneko#6460]
**Name of the website**
TuMangaOnline

**Website urls (examples below)**
- Site: https://visortmo.com/
- Manga List: https://visortmo.com/library
- Manga example: https://visortmo.com/library/manga/44032/yamada-kun-to-lv999-no-koi-wo-suru
- Chapter online viewer example: https://visortmo.com/viewer/138a3fdc6445cf848bdb7d95f9e55690/cascade

**Languages**
Spanish

**Website relationship*
the website before was lectortmo.com but that's no longer working

**Comment by MikeZeDev** [comment]
PLEASE 
![image](https://github.com/manga-download/hakuneko/assets/10671518/edde6300-4052-462b-aa53-1caa1c9ee0e4)

https://github.com/manga-download/hakuneko/pull/6389

Dont open useless requests !
