### ISSUE TITLE
[ Coven Scan] domain changed

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#6463]
**Name of the website**
Coven Scan

**Website urls (examples below)**
- Site: https://cvnscan.com/
- Manga List: https://cvnscan.com/manga/
- Manga example: https://cvnscan.com/manga/love-history-caused-by-willful-negligence/
- Chapter online viewer example: https://cvnscan.com/manga/love-history-caused-by-willful-negligence/capitulo-60/

**Languages**
Português

**Additional details**
Madara Theme

**Comment by MikeZeDev** [comment]
Its already existing. You requested it yourself. https://github.com/manga-download/hakuneko/issues/5321.
If url changed do NOT make a "website suggestion" but open a "Connector not working" request

**Comment by mangareader4** [comment]
The domain is cvnscan.com and not cvEnscan.com as you changed
