### ISSUE TITLE
[Site Request] Algodão Doce 

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#6464]
**Name of the website**
Algodão Doce Scan

**Website urls (examples below)**
- Site: https://xn--mfiadoce-8ya.com.br/
- Manga List: https://xn--mfiadoce-8ya.com.br/manga/
- Manga example: https://xn--mfiadoce-8ya.com.br/manga/e-meu-bebe/
- Chapter online viewer example: https://xn--mfiadoce-8ya.com.br/manga/e-meu-bebe/1-temporada/capitulo-25/

**Languages**
Português

**Additional details**
Madara Theme

**Comment by MikeZeDev** [comment]
dead
