### ISSUE TITLE
[<Maga web site>] without connectors avaibles on the list

### ISSUE THREAD

**Issue by andrea-co-1** [manga-download/hakuneko#6466]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I need to add this url to the connetors list 
https://yugenmangas.lat/home
https://page.kakao.com/menu/10010
https://void-scans.com/
https://arvenscans.com/
https://templescan.net/
https://m.happymh.com/

### To Reproduce

Connectors don't exist

**Comment by MikeZeDev** [comment]
* Only one website per issue. 

* Use the "Website suggestion" template to request a website not the bug report one.

* Some of them are already requested. Search for the issue before even asking

* Some of them are already SUPPORTED. Look into the program first 😢 .

Invalid issue + too lazy to search before asking, i am closing this.
