### ISSUE TITLE
[Site Request] Portal Yaoi

### ISSUE THREAD

**Issue by NobodyIsBody** [manga-download/hakuneko#6467]
**Name of the website**
Portal Yaoi

**Website urls (examples below)**

- Site: https://portalyaoi.com/
- Manga List: hhttps://portalyaoi.com/manga/
- Manga example: https://portalyaoi.com/manga/the-origin-of-species/
- Chapter online viewer example: https://portalyaoi.com/manga/the-origin-of-species/capitulo-72/

**Languages**
Portuguese

**Additional details**
Madara Theme

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/6187
