### ISSUE TITLE
[<CocoManHua>] Connector not working

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#6468]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

Cannot preview/download chapter, the downloaded file is broken
![WM-Screenshots-20231129211656](https://github.com/manga-download/hakuneko/assets/77179150/75f0c6d1-1fe9-455d-9aae-bff02cd80d0b)
![WM-Screenshots-20231129211746](https://github.com/manga-download/hakuneko/assets/77179150/d36ea340-2f91-45ff-bfe2-6cf460c708e8)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Please give manga link . 

Anyway, those are probably html files, in that case you got ipblocked and nothing can be done.

THIS SITE IS A PAIN

Possible duplicate of [5606](https://github.com/manga-download/hakuneko/issues/5606)

**Comment by black0888** [comment]
manga link : https://www.colamanga.com/manga-xf36517/
chapter link : https://www.colamanga.com/manga-xf36517/1/311.html

**Comment by MikeZeDev** [comment]
It seems like they are playing again with encryption keys. Oh well, nothing complicated.
This time i wonder how they will counterattack.
