### ISSUE TITLE
[Site Request] Dianxia Traduções

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#6469]
**Name of the website**
Dianxia Traduções

**Website urls (examples below)**
- Site: https://dianxiatrads.com/
- Manga List: https://dianxiatrads.com/manga/
- Manga example: https://dianxiatrads.com/manga/heaven-officials-blessing-ptbr/
- Chapter online viewer example: https://dianxiatrads.com/manga/heaven-officials-blessing-ptbr/capitulo-1/

**Languages**
Português

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
MadaraTheme

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/6190
