### ISSUE TITLE
[Site Request] sonagi

### ISSUE THREAD

**Issue by StalkeRz2** [manga-download/hakuneko#6473]
s33.sonagi

- https://s33.sonagi.org/category/%EC%84%B1%EC%A2%8C%EB%93%A4%EC%9D%B4-%EB%82%B4-%EC%A0%9C%EC%9E%90/

korean

**Comment by MikeZeDev** [comment]
And i thought only thai/indo website were shining like lanterns, here is korean one :)

Does it regularly change url? I suspect its that kind of website.

**Comment by MikeZeDev** [comment]
Website is just leeching toonkor no need to add it

![image](https://github.com/manga-download/hakuneko/assets/10671518/48d76ee5-5a81-4a61-be32-78a56ccf3c6b)
