### ISSUE TITLE
[Site Request] thewebsitename

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6478]
thewebsitename: Nexo

**Website urls: https://nexoscans.com

- Manga List: https://nexoscans.com/manga/
- Manga example: https://nexoscans.com/manga/oe-065_32_1-comeco-de-um-noob/
- Chapter online viewer example: https://nexoscans.com/manga/oe-065_32_1-comeco-de-um-noob/cap-151/
- 

List of languages supported by the website: Português

Hello! This site was the old "Neox" He changed the name to try to avoid dmca. They ended up changing the website's IP.

**Comment by MikeZeDev** [comment]
> Hello! This site was the old "Neox" He changed the name to try to avoid dmca. They ended up changing the website's IP.

Then fill a "Website change" request not a new website request. 

Website is full of  crap tho

![image](https://github.com/manga-download/hakuneko/assets/10671518/3e247272-f181-42af-af3f-4cec8faadfdb)

Not sure its worth begin fixed.

**Comment by CristianoLBR** [comment]
The site appears this way to people outside Brazil. This way, this prevents Brazilian websites from crashing.

**Comment by MikeZeDev** [comment]
:D Really? oh, damn. How weird.

Well it doesnt change its not a new website, you should fill a website change request then .
I wonder if i can fix that if i see nothing :D
