### ISSUE TITLE
[Site Request] add  Ler manga

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6479]
thewebsitename: Ler manga 

**Website urls 
- Site: https://lermanga.org
- 
- Manga List: https://lermanga.org/mangas/
- Manga example: https://lermanga.org/mangas/damn-magic-swords/
- Chapter online viewer example: https://lermanga.org/capitulos/damn-magic-swords-capitulo-02/ 

List of languages supported by the website

Português

**Comment by MikeZeDev** [comment]
Already requested stop asking for already requested websites pls use the search engine. Also cant access website , region locked anyway

**Comment by CristianoLBR** [comment]
Can we in Brazil help in any way to add these sites that seem blocked to you?

**Comment by MikeZeDev** [comment]
> Can we in Brazil help in any way to add these sites that seem blocked to you?

Sure you can submit code , that what Github is for ;)
