### ISSUE TITLE
[Site Request] Lectorunitoon

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#6485]
**Name of the website**
Lectorunitoon

**Website urls (examples below)**
- Site: https://lectorunitoon.com/
- Manga List: https://lectorunitoon.com/manga
- Manga example: https://lectorunitoon.com/manga/me-vengare-de-mi-marido
- Chapter online viewer example: https://lectorunitoon.com/archivo/904

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
MangaStream

**Comment by MikeZeDev** [comment]
dead
