### ISSUE TITLE
ares manga

### ISSUE THREAD

**Issue by brincebebo** [manga-download/hakuneko#6487]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

ares manga is new source https://en-aresmanga.com/

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Aresnov.org is still alive why should we change? + ESET complains about adware javascript on the domain you mentioned

**Comment by brincebebo** [comment]
the two sites are different can you add them both

**Comment by MikeZeDev** [comment]
Both? First one is suported already why both? 

If you want the new one fill a proper request, not a bug request
