### ISSUE TITLE
goldragon

### ISSUE THREAD

**Issue by brincebebo** [manga-download/hakuneko#6490]
**Name of the website**
goldragon

**Website urls (examples below)**
- Site: https://goldragon.me/
- Manga List: https://goldragon.me/manga
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website
arabic
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dont open a NEW WEBSITE issue if you know that its the new url a website and you already opened an issue to fix the url 🤦
