### ISSUE TITLE
[<aresmanga.com>] Connector not working

### ISSUE THREAD

**Issue by Oussjo7a** [manga-download/hakuneko#6494]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

the website changes his domain to(https://en-aresmanga.com/) please fix the problem

### To Reproduce

1. aresmanga
2. the website changes his domain
3. need to change it
4.](https://en-aresmanga.com/)

**Comment by MikeZeDev** [comment]
Seriously? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/ec9e86bf-056c-48f0-8143-e1bc3caea062)
