### ISSUE TITLE
gateanimemanga

### ISSUE THREAD

**Issue by brincebebo** [manga-download/hakuneko#6496]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

manga list isn't refreshing

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Wont fix. gatemanga is broken, chapters dont load in browser (with a fresh profile), there is nothing we can do its their problem.

![image](https://github.com/manga-download/hakuneko/assets/10671518/045ce336-79ba-46a4-9373-7a68a5498530)
