### ISSUE TITLE
VexManga Scans

### ISSUE THREAD

**Issue by brincebebo** [manga-download/hakuneko#6499]
**Name of the website**
vexmanga

**Website urls (examples below)**
- Site: https://vexmanga.com/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website
arabic
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Mangastream

**Comment by MikeZeDev** [comment]
It was added to haruneko as "Vortex scans" as the url was redirecting to a "vortex scans" website but now there is VortexScans.org
and VexMangas .....

**Comment by MikeZeDev** [comment]
Now its broken with one manga and "test1" and 'test2"... Wont do. Feel free to reopen issue in caes its fixed.
