### ISSUE TITLE
YouBa Manga - Missing Chapters (#62)

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#65]
> **From:** HakuNeko User

YouBa isn't downloading more recent releases for an example "spirit sword sovereign 152 and up only downloads empty folders and when you hit the preview button it shows empty as well.

**Comment by 27136773** [comment]
#62

**Comment by 27136773** [comment]
This behavior is correct.
These chapters are published and just linked to the new website https://youbamanga.net.
Therefore you have to download them from `YouBa Manga (2019)` and not from `YouBa Manga`.
