### ISSUE TITLE
[Site Request] Webnovel.com Novels

### ISSUE THREAD

**Issue by amit34521** [manga-download/hakuneko#6511]
**Name of the website**
webnovel.com

**Website urls (examples below)**
- Site:https://www.webnovel.com/
- Novel List: Same As Manga API, just change comicId to BookId
- Chapter example: https://www.webnovel.com/book/25759730405792805/75371851454401932

Basically the novels from Webnovel. They changed the structure about 2 years ago where now the locked chapters are encrypted.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5958
