### ISSUE TITLE
[https://manhuaplus.org] manhuaplus

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#6515]
**Name of the website**
thewebsitename-----manhuaplus.org
**Website urls (examples below)**
- Site: https://thewebsiteurl/.   ---- (https://manhuaplus.org/home)- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website - English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").---manhuaplus.com

**Additional details**
Add any other context details that you may have found (like template to reuse)---

Wasn't sure if I should frame it as domain name change or new connector request. The site states that the new domain works better.

<img width="1399" alt="Screenshot 2023-12-07 at 9 42 26 AM" src="https://github.com/manga-download/hakuneko/assets/70929406/cba2bce1-ee3f-4df1-b2dd-b68567832d35">

**Comment by MikeZeDev** [comment]
I saw that while working on Haruneko. Idk if its worth it

**Comment by tsentered** [comment]
🥺

**Comment by tsentered** [comment]
I’m guessing that it wouldn’t have the issues that the current domain has. I could be wrong, of course.

Either way thanks for looking into it.

**Comment by MikeZeDev** [comment]
Using .org in Haruneko.

**Comment by tsentered** [comment]
In the interest of professionalism, I offer this response,

￼
