### ISSUE TITLE
[<Comick>] Missing mangas in list

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6516]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

I've noticed that the connector is functioning properly, and it successfully refreshes. However, I've encountered an issue where some titles and mangas are missing from the connector but can still be found on the original website.

### To Reproduce

1. Name of connector- Comick
2. Name of manga (if connector update is working)- I Am Really Not A Child Of Luck
3. Name of chapter (if manga update is working)- I Am Really Not A Child Of Luck
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): not found
![2](https://github.com/manga-download/hakuneko/assets/123682535/7e48da29-dc30-4036-b66e-53f890ba9ca5)
![1](https://github.com/manga-download/hakuneko/assets/123682535/6b8d7e69-3c0c-4770-8765-bbba67a75796)

**Comment by MikeZeDev** [comment]
If their API doesnt give the complete manga list there is nothing that can be done. 
If you scroll down their search page you will see errors after they load page 25.

This is why copy / paste feature exists no need to report a problem. Use copy paste feature.

**Comment by MikeZeDev** [comment]
Crap they changed domain so copy paste wont work
