### ISSUE TITLE
[<KomikTap>] Connector not working

### ISSUE THREAD

**Issue by itshyungnim** [manga-download/hakuneko#6522]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

please update KomikTAP connector here is the new link https://komiktap.me/

### To Reproduce

Name of the website
komiktap
https://komiktap.me/

Website urls (examples below)

Site: https://komiktap.me/
Manga list: https://komiktap.me/manga/
Manga example: https://komiktap.me/manga/benefactors-daughters/
Chapter online viewer example: https://komiktap.me/benefactors-daughters-chapter-7/

Languages
List of languages supported by the website
Indonesian

*Website relationship
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

Additional details
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Domain is good in nightly already. The problem is elswhere :)
