### ISSUE TITLE
[<Piccoma Fr>] Connector not working

### ISSUE THREAD

**Issue by Mahora2106** [manga-download/hakuneko#6523]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Hello, piccoma images are encrypted again.
![image](https://github.com/manga-download/hakuneko/assets/71670560/af9dd445-342a-4eec-ab26-9952bb5c8be0)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
we know already. A PR was on the way but they changed again
