### ISSUE TITLE
[<Reaper Scans>] Connector not working

### ISSUE THREAD

**Issue by uxnouri** [manga-download/hakuneko#6526]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Chapters not showing after URL change! you can see manhwa but you can't see chapters... idk why!
![Capture](https://github.com/manga-download/hakuneko/assets/153362818/d46e58b9-82fa-4dd5-8bc9-e5c1961a0763)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by uxnouri** [comment]
Still chapters not showing...

**Comment by MikeZeDev** [comment]
Please understand how github works : 

1) someone fill an issue
2) Problem is eventually solved by a dev, he submit a pull request
3) When  pull request is approved fix is available to the end user

its useless to said "still no work" where we are still at step 2.

**Comment by uxnouri** [comment]
Thank you for explaining!

**Comment by uxnouri** [comment]
![Capture](https://github.com/manga-download/hakuneko/assets/153362818/b4d7c68e-b035-487b-a9d9-3775616d1485)

**Comment by UnusualCharge** [comment]
They moved back to their original domain yesterday, and this fix stopped working (for me, at least).

**Comment by MikeZeDev** [comment]
> They moved back to their original domain yesterday, and this fix stopped working (for me, at least).

🤦 Godaaam and there is cloudflare now
