### ISSUE TITLE
[<GourmetScans.mjs>] Connector not working

### ISSUE THREAD

**Issue by BillyBob1354** [manga-download/hakuneko#6530]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

URL Changed to "https://gourmetsupremacy.com"
If I manually fix the URL I get "CryptoJS is not defined" If I try to preview any chapter.

### To Reproduce

1. GourmetScans.mjs (with URL manually fixed "https://gourmetscans.net" -> "https://gourmetsupremacy.com")
2. Any manga
3. Any chapter
4. "CryptoJS is not defined"

**Comment by MikeZeDev** [comment]
Script needs to be tweaked a bit :D
