### ISSUE TITLE
[Site Request] MangaGUN

### ISSUE THREAD

**Issue by KiRa937** [manga-download/hakuneko#6533]
**MangaGUN**
mangagun

**Website urls (examples below)**
- Site: https://mangagun.net/
- Manga List: https://mangagun.net/manga-list.html
- Manga example: https://mangagun.net/manga-tank-chair.html
- Chapter online viewer example: https://mangagun.net/read-tank-chair-chapter-1.html

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5550
