### ISSUE TITLE
[<Comick>] Connector Copy Paste Not Working

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6534]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

manga was not in the list tried the Copy & Paste Feature but that didn't work too.

### To Reproduce

1. Name of connector: comick
2. Name of manga (if connector update is working): This Martial Saint Is Way Too Generous
3. Name of chapter (if manga update is working):
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): https://comick.cc/comic/this-martial-saint-is-way-too-generous

**Comment by MikeZeDev** [comment]
Its because they keep changing domain we cant follow. We already changed it 3 days ago :/. If you use Nightly, replace .cc by .ink. If you use stable replace .cc by .app.
