### ISSUE TITLE
[Site Request] https://sushiscan.net/

### ISSUE THREAD

**Issue by Kirua-95** [manga-download/hakuneko#6535]
**Sushi Scan**
thewebsitename

**Website urls (examples below)**
- Site: https://sushiscan.net/
- Manga List: https://sushiscan.net/catalogue/
- Manga example: https://sushiscan.net/catalogue/slam-dunk-star-edition/
- Chapter online viewer example: https://sushiscan.net/slam-dunk-star-edition-volume-1/

**Languages**
French

**Website relationship*
No idea. Just the biggest french scan website

**Additional details**
none

**Comment by MikeZeDev** [comment]
Supported since 5 months already, come on. https://github.com/manga-download/hakuneko/blob/74cb06d816dbfcea0615770e1e43aaeddc3b8617/src/web/mjs/connectors/SushiScans.mjs

Oh and i am sorry but dont bother telling us it doesnt work, we know, that cant be fixed (Cloudflare) :/
