### ISSUE TITLE
[Comic Earth Star] website change

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6536]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Earth Star Ent. has renewal their site and change viewer to CoreView.

### To Reproduce

1. Name of connector: Comic Earth Star
2. Name of manga: All
3. Name of chapter: All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Got this error on Devtool.

```
Request.mjs:388 Uncaught (in promise) Error: Object has been destroyed
    at electron/js2c/browser_init.js:6863
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6706)
    at IpcMainImpl.emit (events.js:210)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930)
    at WebContents.emit (events.js:210)
```

**Comment by MikeZeDev** [comment]
Awesome. Coreview is way easier :)
