### ISSUE TITLE
manga-like

### ISSUE THREAD

**Issue by brincebebo** [manga-download/hakuneko#6546]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

manga list isn't refreshing and can't download

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Mangalike.org is dead (404)

Now, what to do? Use one of those? 

https://manga-like.net/
https://manga-like.org/ 

But d they are all named "Mangalek" which is a website we already have under the url mangaleku.com and the name Mangalek.

Its a mess . If someone can clarify things for me i'd really appreciate it.

related https://github.com/manga-download/hakuneko/issues/6495

**Comment by brincebebo** [comment]
can you update the connector
