### ISSUE TITLE
[Site Request] Comic Ride/RiComi

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6553]
**Name of the website**
Comic Ride/RiComi (ライコミ)

**Website urls (examples below)**
- Site: https://comicride.jp/
- Manga List: https://comicride.jp/series/list
- Manga example: https://comicride.jp/series/bcf8f99bbbbe3/
- Chapter online viewer example: https://comicride.jp/episodes/a20359bd53d46

**Languages**
Japanese

**Website relationship**
Micro Magazine's Manga portal site (renewal for merge other label site to 1 site).

**Additional details**
Use Comici platform for site and viewer, look like manga list can't get complete list on YoungChampion connector but still get complete chapter list and clipboard still working.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/321.
