### ISSUE TITLE
[Site Request] Asura Scans TR

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6554]
**Name of the website**
Asura Scans TR

**Website urls (examples below)**
- Site: https://asurascans.com.tr/
- Manga List: https://asurascans.com.tr/manga/
- Manga example: https://asurascans.com.tr/manga/oyuncunun-son-sansi/
- Chapter online viewer example: https://asurascans.com.tr/manga/oyuncunun-son-sansi/bolum-21/

**Languages**
Turkish (Türkçe)

**Website relationship*
Asura Scans (TR) is already in HakuNeko, but, it doesn't work. I think, the website changed its URL. Now the website has two different URL than the previous URL. One is https://asurascans.com.tr/ the other URL is https://armoniscans.com/ it's complicated to understand.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18051
