### ISSUE TITLE
[Site Request] Armoni Scans

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6555]
**Name of the website**
Armoni Scans

**Website urls (examples below)**
- Site: https://armoniscans.com/
- Manga List: https://armoniscans.com/manga/
- Manga example: https://armoniscans.com/manga/asagi-dunyanin-efendisi/
- Chapter online viewer example: https://armoniscans.com/asagi-dunyanin-efendisi-bolum-64/

**Languages**
Turkish (Türkçe)

**Website relationship*
In HakuNeko, Asura Scans (TR) is exist but, that site doesn't work. I think, the website changed its URL. Now the website has two different URL than the previous URL. One is https://armoniscans.com/ the other URL is https://asurascans.com.tr/ it's complicated to understand.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18051
