### ISSUE TITLE
[Site Request] Manga Gezgini

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6556]
**Name of the website**
Manga Gezgini

**Website urls (examples below)**
- Site: https://mangagezgini.com/
- Manga List: https://mangagezgini.com/project/
- Manga example: https://mangagezgini.com/manga/gecmise-donen-kahraman/
- Chapter online viewer example: https://mangagezgini.com/gecmise-donen-kahraman-1-1/

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already requested . Search engine, use it and stop spamming please 💢
