### ISSUE TITLE
[Site Request] Reaper Scans

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6557]
**Name of the website**
Reaper Scans

**Website urls (examples below)**
- Site: https://reaperscans.com.tr/
- Manga List: https://reaperscans.com.tr/manga/
- Manga example: https://reaperscans.com.tr/manga/this-is-the-law/
- Chapter online viewer example: https://reaperscans.com.tr/this-is-the-law-63-bolum/

**Languages**
Turkish (Türkçe)

**Website relationship*
Reaper Scans (Turkish) is already in HakuNeko, but, it doesn't work. The website changed its URL.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Url changed > report a website change, not a new website and stop spam.
