### ISSUE TITLE
[Site Request] Gölge Bahçesi

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6558]
**Name of the website**
Gölge Bahçesi

**Website urls (examples below)**
- Site: https://golgebahcesi.com/
- Manga List: https://golgebahcesi.com/manga/
- Manga example: https://golgebahcesi.com/manga/the-absolute-gods-game/
- Chapter online viewer example: https://golgebahcesi.com/the-absolute-gods-game-bolum-4/

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already requested . Search engine, use it and stop spamming please 💢
