### ISSUE TITLE
[<Güncel Manga>] Connector not working

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6560]
### Is there an existing issue for this connector?

- [ ] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [ ] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list is not loading in HakuNeko. However everything is fine when I use within a browser. The URL has changed.

Name of the website
Güncel Manga

Website urls (examples below)

Site: https://guncelmanga.net/
Manga List: https://guncelmanga.net/manga-oku/
Manga example: https://guncelmanga.net/manga/bug-player/
Chapter online viewer example: https://guncelmanga.net/manga/bug-player/bolum-119/

Languages
Turkish (Türkçe)

### To Reproduce

1. Name of connector Güncel Manga https://guncelmanga.net/ 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by Mehmet20032003** [comment]
![Adsız](https://github.com/manga-download/hakuneko/assets/127633031/bfe23c16-48f5-4337-8528-c47c22705403)

**Comment by Mehmet20032003** [comment]
![Adsız](https://github.com/manga-download/hakuneko/assets/127633031/5b22d317-a77d-44a2-a1a8-61a7dc109424)

**Comment by MikeZeDev** [comment]
No need for screenshots if url just changed you know :D
