### ISSUE TITLE
[Site Request] Manga Efendisi

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6561]
**Name of the website**
Manga Efendisi

**Website urls (examples below)**
- Site: https://mangaefendisi.net/
- Manga List: https://mangaefendisi.net/manga
- Manga example: https://mangaefendisi.net/manga/disastrous-necromancer/
- Chapter online viewer example: https://mangaefendisi.net/disastrous-necromancer-bolum-39/

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already requested . Search engine, use it and stop spamming please 💢
