### ISSUE TITLE
[Site Request] Mangazure

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6563]
**Name of the website**
Mangazure

**Website urls (examples below)**
- Site: https://www.mangazure.com/
- Manga List: https://www.mangazure.com/search/label/Tümü
- Manga example: https://www.mangazure.com/2023/11/everyone-regressed-except-me.html
- Chapter online viewer example: https://www.mangazure.com/2023/12/everyone-regressed-except-me-bolum-14.html

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already requested . Search engine, use it and stop spamming please 💢
