### ISSUE TITLE
[Site Request] Manwe

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6573]
**Name of the website**
ManWe

**Website urls (examples below)**
- Site: https://manwe.pro/
- Manga List: https://manwe.pro/manga/
- Manga example: https://manwe.pro/manga/a-useless-villain/
- Chapter online viewer example: https://manwe.pro/manga/a-useless-villain/bolum-52/

**Languages**
Turkish (Türkçe)

**Website relationship*
The old name of this website was EvaScans. Even EvaScans has a section in HakuNeko. Of course it's not working now.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Then open a "not working 'ticket to fix Evascans with this url
