### ISSUE TITLE
[<Manga Kitsu>] Connector not working

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6576]
### Is there an existing issue for this connector?

- [ ] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [ ] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list is not loading in HakuNeko. However everything is fine when I use within a browser. The URL has changed.

Name of the website
OLD NAME IS "Manga Kitsu"
NEW NAME IS "Kıtsu"

Website urls (examples below)

Site: https://kitsu.io/
Manga List: https://kitsu.io/manga
Manga example: https://kitsu.io/manga/trash-of-the-count-s-family
Chapter online viewer example: https://kitsu.io/manga/trash-of-the-count-s-family/chapters/27

Languages
Turkish (Türkçe)

### To Reproduce

1. Name of connector Manga Kitsu https://kitsu.io/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Its true that mangakitsu is dead, thanks for the info 👍 but kitsu.io has no content at all,  its uses to track what you read and watch :D
