### ISSUE TITLE
[Site Request] Manga Tepesi

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6579]
**Name of the website**
Manga Tepesi

**Website urls (examples below)**
- Site: https://mangatepesi.com/
- Manga List: https://mangatepesi.com/mangalistesi
- Manga example: https://mangatepesi.com/manga/murim-login/10
- Chapter online viewer example: https://mangatepesi.com/manga/murim-login/91-bolum/1919

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already asked 6 times, please search before posting useless duplicates.
