### ISSUE TITLE
[<Uzay Manga>] Connector not working

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6585]
### Is there an existing issue for this connector?

- [ ] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [x] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list is not loading in HakuNeko. However, everything is fine when I use it within a browser. The URL is still the same, I think. A year ago, I mentioned this problem. Because of the Cloudflare, you couldn't fix. However, when I entered the website today, Cloudflare screen didn't appear. So can you check it again. I was waiting for this moment for a year.

Name of the website
Uzay Manga

Website urls (examples below)

Site: https://uzaymanga.com/
Manga List: https://uzaymanga.com/search
Manga example: https://uzaymanga.com/manga/6/bir-holdingin-en-kucuk-oglu
Chapter online viewer example: https://uzaymanga.com/manga/6/bir-holdingin-en-kucuk-oglu/490/57-bolum

Languages
List of languages supported by the website
Turkish (Türkçe)

I even tried using VPN. Nothing has changed. Interestingly, sometimes when HakuNeko is not working, I try using a VPN and it starts to work not only for this website (Uzay Manga), in generally. It didn't work this time.

### To Reproduce

1. Name of connector Uzay Manga https://uzaymanga.com/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Seriously, check already opened ISSUES  !!!!!!!!!!
