### ISSUE TITLE
Request site support for H Chinese Manhua

### ISSUE THREAD

**Issue by RnckO** [manga-download/hakuneko#659]
As the title says, it's manhua sites tailored for cultured people ( ͡° ͜ʖ ͡°) with aplenty materials For Academic Purpose.

贝贝动漫网
https://www.bbdmw.com/

绅士漫画网
http://www.ssmh.cc/

绅士漫画网 <-- altho 2 site similar name, but this one is less laggy
www.zxneo.com

** Just for trivia : 绅士 = Gentleman. aka...... MEN WITH CULTURES

**Comment by 27136773** [comment]
Please make a single ticket for each requested website, handling multiple issues in a single ticket is to confusing for the developers in case of discussion, feedback loops and status changes.
