### ISSUE TITLE
[Beetoon] fake images

### ISSUE THREAD

**Issue by metoobz** [manga-download/hakuneko#6592]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
So i have been trying to download Chainsaw man which has been great up until Volume 7. it has been EXTREMELY frustrating. NOBODY has it.
I found it on Beetoon and one other site i cannot recall.
it is able to find the manga and get all the scans, but google feedback pages open between each scan, so when you preview every other image is an error. when the downloader sees this, it freaks out and errors and won't download. The one i'm on is Chainsaw Man chapter 72, beetoon.
Please help, this is really frustrating and overwhelming. let me know if you need more information. this is extremely confusing for me already so i may have missed something.

**To Reproduce**
1. choose beetoon
2. Search or find chainsaw man and click
3. Find chapter 70 (if this chapter doesn't do it, try others, its realy inconsistent.)
4. preview, see missing images
5. download it and have it fail
6. view console, see the URL's that have issues

**Expected behavior**
it should preview without any failed images between the actual manga, should not open google feedback or should skip past it somehow, and fully download the manga chapter

**Screenshots**

**Context (please complete the following information):**
 - OS: Windows 10
![HakuNekoErr](https://github.com/manga-download/hakuneko/assets/154104140/7e5db39d-084f-4dc2-bb04-096a7bbf5b2a)
![HakuNekoErr1](https://github.com/manga-download/hakuneko/assets/154104140/54d5eed8-f9f9-4d49-96e2-96253a662bd9)

 - HakuNeko Version [e.g. 6.17]

**Additional context**
the other site had a similar problem with getting wrong URLS but gave me bin's instead of JPEGS

**Comment by MikeZeDev** [comment]
they insert fake images 

![image](https://github.com/manga-download/hakuneko/assets/10671518/5af5a8b7-3d24-4817-b1ce-02f73df4dc2c)

As for the bin problems find the website and open another issue.

**Comment by metoobz** [comment]
thank you!! i'm not sure what to do from here. why don;t we just add FunManga? are they hard to work with?
