### ISSUE TITLE
[Bug] 403 forbidden

### ISSUE THREAD

**Issue by henry-cotton** [manga-download/hakuneko#6596]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Did a fresh install of Hakuneko from the window install exe. Started the app through the desktop shortcut it created, and it came up with "checking for updates". Then the screen shows a "Forbidden. You don't have permission to access URL". The URL it was trying to load was the Virus GIF that I started seeing last year; that was what caused me to uninstall.

**To Reproduce**
1. Install Hakuneko
2. Start Hakuneko app

**Expected behavior**
I should have seen the home UI

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/72087779/2b1a1b12-044f-4b5b-99fb-e75f3c7d2f2a)

**Context (please complete the following information):**
 - OS: Windows 10 22H2
 - HakuNeko Version 6.17

**Additional context**
I don't know if this is a bug or my PC/IP is just blocked for some reason.

**Comment by MikeZeDev** [comment]
Url may be dead but you should not trigger this unless special circumstances . Ask Ronny on discord. He knows whats going on.
