### ISSUE TITLE
[ComicBushi]  became Comic Growl

### ISSUE THREAD

**Issue by Noahzel** [manga-download/hakuneko#6603]
**Name of the website**
Comic Growl

**Website urls (examples below)**
- Site: https://comic-growl.com

**Languages**
English

**Website relationship*
It's a rebranded version of Comic Bushiroad WEB.

**Additional details**
I was told on Discord that it's coreview. And that Bushiroad now redirects to it, so that it should be a URL change request.

**Comment by MikeZeDev** [comment]
Dont open a site request if its just an url change, fill a "website change"
