### ISSUE TITLE
[Site Request] webdexscans

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6604]
**webdexscans**
webdexscans

**Website urls (examples below)**
- Site: https://webdexscans.com/
- Manga List: https://webdexscans.com/series-genre/webdexscans/
- Manga example: https://webdexscans.com/series/legend-of-star-general/
- Chapter online viewer example: https://webdexscans.com/series/legend-of-star-general/chapter-168/

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6018
