### ISSUE TITLE
[Cuu Truyen] https://cuutruyen.net/

### ISSUE THREAD

**Issue by qd74** [manga-download/hakuneko#6608]
**Cuu Truyen**
https://cuutruyen.net/

**Website urls (examples below)**
- Site: https://cuutruyen.net/
- Manga List: https://cuutruyen.net/newest
- Manga example: https://cuutruyen.net/mangas/855
- Chapter online viewer example: https://cuutruyen.net/offline/mangas/855/chapters/27857

**Languages**
List of languages supported by the website
Vietnamese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5226
