### ISSUE TITLE
[ReadComicOnline.li] Connector not working (Cloudflare)

### ISSUE THREAD

**Issue by ftfckr** [manga-download/hakuneko#6609]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

RCO.li now uses Cloudflare, hits redirection issue (#2933)

### To Reproduce

![image](https://github.com/manga-download/hakuneko/assets/54716748/28680c23-8430-4811-9fbf-1cf1f754b2c9)

**Comment by DarklySatanic** [comment]
The connector is working fine - You can easily get around the Cloudflare issue because there's a popup box that asks you to confirm if you're human.

<img width="1266" alt="image" src="https://github.com/manga-download/hakuneko/assets/115671373/d0efdcc1-b37c-415e-9089-bf93b46f5394">

**Comment by ftfckr** [comment]
Confirmed, seems like they've turned it off as there's no challenge anymore.

**Comment by DarklySatanic** [comment]
Unfortunately that isn't correct, though it does take a while for it to pop up.

<img width="947" alt="image" src="https://github.com/manga-download/hakuneko/assets/115671373/09a70617-9f61-425f-97ea-5da1a5106461">

Not debilitating, it just means you may have to babysit the application as you download stuff. I'm just grateful that this is a thing, and yeah, the Cloudflare is annoying, but.. Take the bad with the good, eh?

**Comment by ftfckr** [comment]
That's ReCaptcha, not CloudFlare.  ReCaptcha works fine.

**Comment by MikeZeDev** [comment]
Yeah, but i tested a bit and i dont see cloudflare anymore. There is indeed Cloudflare IIRC.

**Comment by DarklySatanic** [comment]
Aren't Cloudflare and ReCaptcha the same?

**Comment by MikeZeDev** [comment]
> Aren't Cloudflare and ReCaptcha the same?

Not at all, not even the same company. Recaptcha is a captcha by Google, Cloudflare is way more than captchas, its the company name too

**Comment by DarklySatanic** [comment]
Interesting! 
Okay, so basically the issue isn't getting around Cloudflare, which I know for sure is used on ReadComicOnline (at least it was) but getting around the ReCapcha? Is it just as difficult to bypass?

**Comment by ftfckr** [comment]
No, the issue was getting around CloudFlare.  Hakuneko handles ReCaptcha just fine.  It was, specifically, the interstitial check that CloudFlare does that was the problem.  This is, IIRC, part of their "I'm Under Attack" mode that site owners can turn on or off.  At the time I opened this issue, RCO had turned that on, but it would appear that they have now turned it off.

**Comment by DarklySatanic** [comment]
Ah I see.
But basically, Hakuneko still requires monitoring, no? Like, it wouldn't be a good idea to leave it running for a few hours when you're afk due to the capcha?
