### ISSUE TITLE
[<niconico seiga>] Connector not working

### ISSUE THREAD

**Issue by SecretArmy** [manga-download/hakuneko#6615]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Can't fetch the manga list.
<img width="837" alt="Untitled" src="https://github.com/manga-download/hakuneko/assets/23245869/907b56d2-e1c8-4dac-a9de-7e2d7239bd86">

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Can you find me something that can be viewed without needed to be logged ?

**Comment by SecretArmy** [comment]
Probably need an acc to view any manga on the site.

**Comment by SecretArmy** [comment]
While the manga list fetch working on nightly only (normal one still broken), for some reason can't download the chapter. Can view the ch. from the site. So my guess is need to login somehow since the site need login first to view the ch. I don't know should I open new issue or not so for now just add this here. 
https://i.imgur.com/xc66f7h.png

**Comment by MikeZeDev** [comment]
Make sure you are logged

**Comment by SecretArmy** [comment]
how? login from chrome?

**Comment by MikeZeDev** [comment]
How about reading the manual ?  https://hakuneko.download/docs/manual-website-interaction/ :)

**Comment by SecretArmy** [comment]
Well, that fixed that but only in nightly, the normal one still broken can't fetch manga list, but can dl ch.. Can see the list because I fetch it in nightly before.

**Comment by MikeZeDev** [comment]
I dont understand what you want to say. Nothing should work in stable. Everything should work in nightly and thats all. Fixes will come in stable after nightly.  A new stable is on the way.

**Comment by SecretArmy** [comment]
If the fix will come to stable then, the all is good since I can just use nightly till it came to stable, since idk when will it came to stable hence that comment before. Anyway thanks for the fix and Happy new year.
