### ISSUE TITLE
manganato Connector not working

### ISSUE THREAD

**Issue by DgBeast** [manga-download/hakuneko#6617]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

connector does not paste / is not recognized. some connectors do work on same website.

### To Reproduce

1. Name of connector: https://chapmanganato.to/manga-id986060

**Comment by MikeZeDev** [comment]
manganato and their multiplication of domains 🤦 

(Connector refers to the website plugin in hakuneko btw)
