### ISSUE TITLE
Can you tell me about the bypass cloudflare system which hakuneko is using?  

### ISSUE THREAD

**Issue by minhduc1212** [manga-download/hakuneko#6626]
I just want to know the knowledge about the bypass cloudflare system of hakuneko so can you tell me about this.
Next, I also want to know why hakuneko crawl the data from web but hakuneko doesn't meet the block.
Thank you very much

**Comment by MikeZeDev** [comment]
There is not. Hakuneko is not able to bypass Cloudflare for a while now. Electron version is too old and its a pain to update.
There is a reason i made this tag https://github.com/manga-download/hakuneko/issues?q=is%3Aissue+is%3Aopen+label%3ACloudflare and why those issues are not closed.

We work for a bypass in Haruneko.

**Comment by minhduc1212** [comment]
> There is not. Hakuneko is not able to bypass Cloudflare for a while now. Electron version is too old and its a pain to update. There is a reason i made this tag https://github.com/manga-download/hakuneko/issues?q=is%3Aissue+is%3Aopen+label%3ACloudflare and why those issues are not closed.
> 
> We work for a bypass in Haruneko.

It means that hakuneko can not download some webs using cloudflare :V 
Thank you very much!
