### ISSUE TITLE
[<Piccoma.com>] Connector not working

### ISSUE THREAD

**Issue by ErickShadow12** [manga-download/hakuneko#6627]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

When I select the manga, its chapters do not appear.
![Captura de pantalla 2023-12-29 105029](https://github.com/manga-download/hakuneko/assets/126554747/d706665a-8867-49c4-ad0a-092e3fab742c)

### To Reproduce

![Captura de pantalla 2023-12-29 105029](https://github.com/manga-download/hakuneko/assets/126554747/3d926aad-4418-4df1-a3b2-41e6343de888)

3. Name of chapter (if manga update is working)

**Comment by MikeZeDev** [comment]
Fix already ready

**Comment by ErickShadow12** [comment]
How do I get the connector you fixed from Piccoma to work?
