### ISSUE TITLE
[Cmoa] Connector not working completely(Only get 50 chapters)

### ISSUE THREAD

**Issue by RanoTsubasa** [manga-download/hakuneko#6628]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

When the number of chapters is over 50, the Chapter List only shows 50 chapters.

### To Reproduce

Like this page 
https://www.cmoa.jp/title/101051

**Comment by MikeZeDev** [comment]
this is stupid bug :D
