### ISSUE TITLE
[Site Request] ebookjapan.yahoo.co.jp

### ISSUE THREAD

**Issue by ErickShadow12** [manga-download/hakuneko#6630]
**Name of the website**
ebookjapan.yahoo.co.jp

**Website urls (examples below)**
- Site: https://ebookjapan.yahoo.co.jp/
- Manga List: https://ebookjapan.yahoo.co.jp/lists/stories/?sort=update
- Manga example: https://ebookjapan.yahoo.co.jp/books/797142/A004692243/
- Chapter online viewer example: https://ebookjapan.yahoo.co.jp/viewer/free/B00164692242/

**Languages**
List of languages supported by the website
Japones
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/228
