### ISSUE TITLE
[Site Request] pocketcomics.com

### ISSUE THREAD

**Issue by ErickShadow12** [manga-download/hakuneko#6631]
**Name of the website**
pocketcomics.com

**Website urls (examples below)**
- Site: https://www.pocketcomics.com/
- Manga List: https://www.pocketcomics.com/menu/all_comic/read_for_free
- Manga example: https://www.pocketcomics.com/comic/9731
- Chapter online viewer example: https://www.pocketcomics.com/comic/9731/chapter/2/product

**Languages**
List of languages supported by the website
Ingles
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4222. Twice in a row, please check before opening tickets.
