### ISSUE TITLE
[Site Request] MangaOnline

### ISSUE THREAD

**Issue by MrBertemes** [manga-download/hakuneko#6633]
**Name of the website**
Manga Online

**Website urls (examples below)**
- Site: https://mangaonline.biz/
- Manga List:https://mangaonline.biz/manga
- Manga example: https://mangaonline.biz/manga/jujutsu-kaisen/
- Chapter online viewer example: https://mangaonline.biz/capitulo/jujutsu-kaisen-capitulo-247/

**Languages**
Portuguese

**Comment by MikeZeDev** [comment]
Already asked. Dont open duplicate tickets please. https://github.com/manga-download/hakuneko/issues/6283
