### ISSUE TITLE
[KSGroupScans] Connector not working most of the time

### ISSUE THREAD

**Issue by Sildran** [manga-download/hakuneko#6634]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Hi, 
It has been 3 weeks since I started having trouble loading chapters from KSGroupScans. 
Sometimes it works for around 30 minutes / 1 hour before been unable to load again, but for the rest of the time I get an error :

![image](https://github.com/manga-download/hakuneko/assets/6168457/bbf6fed8-ca8b-4f9b-bb46-ab7e1ad9bbf3)

### To Reproduce

1. Name of connector : KSGroupScans
 
2. Name of manga (if connector update is working) : Any

3. Name of chapter (if manga update is working) : Any

5. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : 

callbacks-registry.ts:46 Uncaught (in promise) Error: ERR_FAILED (-2) loading 'https://ksgroupscans.com/'
    at rejectAndCleanup (electron/js2c/browser_init.js:6126)
    at WebContents.stopLoadingListener (electron/js2c/browser_init.js:6167)
    at WebContents.emit (events.js:210)
apply @ callbacks-registry.ts:46
(anonymous) @ remote.js:297
(anonymous) @ remote.js:277
emit @ events.js:210
onMessage @ init.ts:51
2Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "https://ksgroupscans.com/" within the given timeout of 60 seconds!
    at Request.mjs:368

**Comment by Sildran** [comment]
I forgot to add that I can't update the manga list either, and to unfold the yellow error.

![image](https://github.com/manga-download/hakuneko/assets/6168457/4409eb9b-9447-401f-9a35-d2ef4efc6801)

**Comment by MikeZeDev** [comment]
That kind of **** is hard to diagnose :/. I dont have this problem, and i am unable to reproduce it. :/

**Comment by Sildran** [comment]
Oh :/ I'm using the nightly windows portable amd64 if this can be of any help.

**Comment by MikeZeDev** [comment]
The only this i see is maybe there was a nasty ad interfering on the page. It would explain why it seems to be random.

**Comment by Sildran** [comment]
I have the same issue with MangaSushi : sometimes it works for an hour, and doesn't for the rest of the day : 

![image](https://github.com/manga-download/hakuneko/assets/6168457/2df3781a-723a-48f8-bc97-9d6505b9984b)

KsGroupScan works right now, here is what I get : 

![image](https://github.com/manga-download/hakuneko/assets/6168457/608d2771-3432-4453-a5a4-201fa39c28e2)

**Comment by MikeZeDev** [comment]
Mangasushi problem is totally unrelated, event if its the same error

As for KsGroupScan , the error you see is normal. There is more than one way to get chapters on a Marada website, we just try them all, and one failed :D
