### ISSUE TITLE
[Mangafire] Connector not working

### ISSUE THREAD

**Issue by vansAl21** [manga-download/hakuneko#6636]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

The connector I'm trying to use is mangafire.to. The manga list seems to work fine, however, when I want to open the chapter list none seem to work. I remember this connector worked just fine a few months ago. I already tried uninstalling and installing again, refreshing, and these don't seem to work out. I'd appreciate if this manga site worked cause it has many language options and I really like that ><

### To Reproduce

1. Name of connector: mangafire
2. Name of manga (if connector update is working): Blue Exorcist
3. Name of chapter (if manga update is working): no chapter appears on the program
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![Captura de pantalla 2023-12-30 180620](https://github.com/manga-download/hakuneko/assets/155272464/845f2f33-140a-4194-9977-09f402e5a9ad)

**Comment by ignaciocastro** [comment]
Can't recreate on Nightly. Considering Mangafire is under Cloudflare you might be getting rate-limited since you're asking for 1334 pages every time you reload the manga list.

![image](https://github.com/manga-download/hakuneko/assets/7141944/5dc73a54-ccc3-4141-ad16-7fe08e928b8b)

**Comment by vansAl21** [comment]
> Can't recreate on Nightly. Considering Mangafire is under Cloudflare you might be getting rate-limited since you're asking for 1334 pages every time you reload the manga list.
> 
> ![image](https://private-user-images.githubusercontent.com/7141944/293486504-5dc73a54-ccc3-4141-ad16-7fe08e928b8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5ODc0OTAsIm5iZiI6MTcwMzk4NzE5MCwicGF0aCI6Ii83MTQxOTQ0LzI5MzQ4NjUwNC01ZGM3M2E1NC1jY2MzLTQxNDEtYWQxNi03ZmUwOGU5MjhiOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzFUMDE0NjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIzYTNjZGI0MGIzOWMyMDI2NmIzZDE4ZjFiZmE2YWY5ZDViNGNhYWY1ZDllZGE3OWQ1YTc4NTRmYzE1NTBlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sF_9k-eHVSxDs6ETkxJaXKk-Q9kznXpldnbUWfGfl8o)

Thank you very much! What should I do for it to work for me? :(

**Comment by MikeZeDev** [comment]
Had been fixed 2 months ago i guess https://github.com/manga-download/hakuneko/pull/6361 ? 

Did you really tried nightly like its written?
