### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [manga-download/hakuneko#6641]
I have read about [this issue](https://github.com/manga-download/hakuneko/issues/6439), but as homebrew maintainer, I'd still like to request a new release so that we can refresh the downstream packages (it also gives user a sense this project is very much alive), let me know if that makes better sense. Thanks!!

Happy new year!

**Comment by chenrui333** [comment]
This is the current package status

![image](https://github.com/manga-download/hakuneko/assets/1580956/6029faa9-ed58-4af6-bac2-207c5b9ce6c2)

**Comment by MikeZeDev** [comment]
The thing is, its autopupdating scripts at launch . There is no need/plan to change the engine, hence no new "version". A new "version" is on the way, meaning nightly changes will be merged to stable. Soon (tm)

**Comment by Sheepux** [comment]
No action planned by the maintainers. There is no need for a new client release.
No need to reopen issues, you can still comment in previous ones.
