### ISSUE TITLE
[Site Request] Perf Scans

### ISSUE THREAD

**Issue by BehaviourGSN** [manga-download/hakuneko#6642]
**Name of the website**
Perf Scans

**Website urls (examples below)**
- Site: https://perf-scan.fr/
- Manga List: https://perf-scan.fr/comics
- Manga example: https://perf-scan.fr/series/the-martial-god-who-regressed-back-to-level-2-1704150000876
- Chapter online viewer example: https://perf-scan.fr/series/the-martial-god-who-regressed-back-to-level-2-1704150000876/chapitre-20
**Languages**
French

**Comment by MikeZeDev** [comment]
Already done https://github.com/manga-download/hakuneko/pull/6510

**Comment by BehaviourGSN** [comment]
Under what name because I can't find them ?

**Comment by MikeZeDev** [comment]
Its written "PerfScan". If you had tried nightly version you'd have seen it, and not opened an useless issue :D

**Comment by BehaviourGSN** [comment]
Thanks for the information, sorry for the inconvenience, I won't lie to you, I didn't know the difference between the two versions, thanks for the help.
