### ISSUE TITLE
[Site Request] FR SCANS

### ISSUE THREAD

**Issue by BehaviourGSN** [manga-download/hakuneko#6645]
**Name of the website**
FR SCANS

**Website urls (examples below)**
- Site: https://fr-scan.com/
- Manga List: https://fr-scan.com/manga/
- Manga example: https://fr-scan.com/manga/peerless-battle-spirit/
- Chapter online viewer example: https://fr-scan.com/manga/peerless-battle-spirit/chapitre-291-vf/

**Languages**
French

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5864. Please search before asking 😔

**Comment by BehaviourGSN** [comment]
This time it's a mistake on your part. Sure, there are other sites with the same name, but this one isn't a duplicate. if you check they don't have the same url or the same interface

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/eb451fd6-17e7-4d34-a74a-31805dd401e7)

![image](https://github.com/manga-download/hakuneko/assets/10671518/ef07e73a-d4c1-47cf-9929-ae3d69abca7d)


Urls are the same, therefore its the same website.
