### ISSUE TITLE
[<Webtoon Hatti>] Connector not working

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6649]
### Is there an existing issue for this connector?

- [x] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [x] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

I don't know why, but the chapters are not downloading. There is no problem with the other website's webtoon in hakuneko. 'Webtoon Hatti' is also working in a normal browser. For all the webtoons at Webtoon Hatti in hakuneko, names of the webtoons and the number of chapters are right but none of them are not downloading. I am using hakuneko 8.3.4

![Adsız](https://github.com/manga-download/hakuneko/assets/127633031/77c0282b-ca9e-48d7-a15f-ab35ca457fa1)

![Adsız](https://github.com/manga-download/hakuneko/assets/127633031/eeca4389-d0d1-4448-b5f5-015e30804fc1)

### To Reproduce

1. Name of connector Webtoon Hatti
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
I am afraid but i have same problems in both hakuneko AND a real browser

![image](https://github.com/manga-download/hakuneko/assets/10671518/02b86ec8-1dfe-4e32-93cf-2f95d77c118d)

![image](https://github.com/manga-download/hakuneko/assets/10671518/9e6d2717-7452-4d86-97d7-9c862f871103)


Picture said i may need a turkish IP if i translated correctly?

**Comment by MikeZeDev** [comment]
Can you try something? Close Hakuneko, replace the content of  the file "Webtoonhatti.mjs on your computer, with  this

```
import WordPressMadara from './templates/WordPressMadara.mjs';

export default class WebtoonHatti extends WordPressMadara {

    constructor() {
        super();
        super.id = 'webtoonhatti';
        super.label = 'Webtoon Hatti';
        this.tags = [ 'webtoon', 'turkish' ];
        this.url = 'https://webtoonhatti.net';
    }

    async _getPages(chapter) {
        const excludes = [
            /tr2.png$/i,
            /b2.jpg$/i,
            /romantiktr\.tr/i
        ];
        const images = await super._getPages(chapter);
        return images.filter(picture => {
            const pic= JSON.parse(atob(new URL(picture).searchParams.get('payload')));
            return !excludes.some(rgx => rgx.test(pic.url));
        });
    }
}
```

and retry?  The problem is : they add a junk picture at the end so download fail.

**Comment by Mehmet20032003** [comment]
I had tried to use the new code and it was working. Somedays the new code gone and the old code come back. When this happend I change the code within the new code and it again start working. However a week ago, It started doesn't work again. Even though I'm using the new code, I can't download.
![Adsız](https://github.com/manga-download/hakuneko/assets/127633031/20790f02-2f25-40e3-9574-3fb58e9c477e)

**Comment by MikeZeDev** [comment]
Its normal that the code revert back to the old. You modify a cache, and when Hakuneko updates it rewrites your changes.

As for the website its a pain in the butt to test myself because of their ip thing.

Also having the error message would have helped. What does the error says, press F12?

**Comment by MikeZeDev** [comment]
Try this one maybe : https://github.com/manga-download/hakuneko/blob/WebtoonHatti/src/web/mjs/connectors/WebtoonHatti.mjs

**Comment by Mehmet20032003** [comment]
The new code is not working too. I also tried the previous new code, it is still not working. When I push F12, my screen brightness raising. there is a shortcut on my F12, but when I push F12 button with 'Fn' button. this screen comes. I don't know computer terminology, so I am not sure is that you want.

![Adsız1](https://github.com/manga-download/hakuneko/assets/127633031/718fb127-6fb0-4c3c-9886-fc4179c20bd5)


Loading Engine: HakuNeko
hakuneko://plugins/:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
index.html:61 Loading Frontend: frontend@classic-dark
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
loadClassicPolymer @ index.html:76
mjs/connectors/templates/VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:347)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ mjs/connectors/templates/VRV.mjs:305
mjs/connectors/templates/VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:347)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ mjs/connectors/templates/VRV.mjs:305
mjs/connectors/templates/VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:347)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ mjs/connectors/templates/VRV.mjs:305
mjs/engine/Settings.mjs:420 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
(anonymous) @ mjs/engine/Settings.mjs:420
mjs/engine/BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
(anonymous) @ mjs/engine/BookmarkManager.mjs:137
index.html:1 A cookie associated with a resource at http://vrv.co/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
index.html:1 A cookie associated with a cross-site resource at http://webtoonhatti.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
fkneko.what/1.jpg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
mjs/engine/InterProcessCommunication.mjs:13 TypeError: Failed to fetch
(anonymous) @ mjs/engine/InterProcessCommunication.mjs:13
connector://webtoonhatti/?payload=eyJ1cmwiOiJodHRwczovL2ZrbmVrby53aGF0LzEuanBnIiwicmVmZXJlciI6Imh0dHBzOi8vd2VidG9vbmhhdHRpLm5ldC93ZWJ0b29uL2EtbW9kZXJuLW1hbi13aG8tZ290LXRyYW5zbWlncmF0ZWQtaW50by10aGUtbXVyaW0td29ybGQvYm9sdW0tMjcvP3N0eWxlPWxpc3QifQ%3D%3D:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
mjs/engine/DownloadJob.mjs:115 TypeError: Failed to fetch Array(21)
_downloadPages @ mjs/engine/DownloadJob.mjs:115
DevTools failed to parse SourceMap: hakuneko://cache/js/protobuf.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/js/hls.light.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/sm/4f4f84956292156efc04b79e1131dc7c3a51794b7b3d62b43ed5eaca1b36d71e.map

**Comment by MikeZeDev** [comment]
https://fkneko.what/1.jpg , weird url.. Are they trying to fight with us? 🤔

**Comment by MikeZeDev** [comment]
They really dont like us apparently they keep changing it , there is even a cute 
![image](https://github.com/manga-download/hakuneko/assets/10671518/ff9183c6-5713-4139-85b2-05a375ccb703)

**Comment by MikeZeDev** [comment]
New file should work, until they change it again. https://github.com/manga-download/hakuneko/blob/webtoonhatti/src/web/mjs/connectors/WebtoonHatti.mjs

**Comment by Mehmet20032003** [comment]
it's broke again

**Comment by Mehmet20032003** [comment]
> New file should work, until they change it again. https://github.com/manga-download/hakuneko/blob/webtoonhatti/src/web/mjs/connectors/WebtoonHatti.mjs
it's broke again
