### ISSUE TITLE
[Bug] F12 no longer works

### ISSUE THREAD

**Issue by billsargent** [manga-download/hakuneko#6651]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
F12 has always worked for me to see transfers and examine the console and error logs. F12 seems to do nothing now.

**To Reproduce**
2. Hit F12.

**Expected behavior**
The webrowser developer tools.

**Screenshots**
No screenshots because nothing happens.

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version 6.1.7

**Additional context**
I reccently moved the hakuneko install to my NAS and run it from there instead of from my laptop.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5738

Its probably a weird Electron bug
