### ISSUE TITLE
[<bentomanga>] Connector not working

### ISSUE THREAD

**Issue by Yama2007** [manga-download/hakuneko#6654]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

When i refresh the connector i have status 403
![Capture d'écran 2024-01-06 031948](https://github.com/manga-download/hakuneko/assets/67700895/fe5f054e-d582-4256-acd4-9d2eb0aac3b9)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
We know already, please search before asking. Its unfixable : https://github.com/manga-download/hakuneko/issues/6009
