### ISSUE TITLE
Komiktap sometimes it works, sometimes it can't be accessed (Manga List, Chapter List & Download)

### ISSUE THREAD

**Issue by enjoe842** [manga-download/hakuneko#6658]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Sometimes it works, sometimes it can't be accessed (Manga List, Chapter List & Download)

### To Reproduce

Site: https://komiktap.me/
Manga list: https://komiktap.me/a-z-list/
Manga example: https://komiktap.me/manga/queen-bee-andrew/
Chapter online viewer example: https://komiktap.me/queen-bee-chapter-301/

**Comment by MikeZeDev** [comment]
If website doesnt answer sometimes what can a mere browser (Hakuneko) do? .
Since its random ofc we cant reproduce the problem, and code wise there is nothing to change.

If website is unstable, use another 🤷
