### ISSUE TITLE
[<cypherscans>] Connector not working

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6660]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

manga list is not loading

### To Reproduce

1. Name of connector: cypherscans
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![123](https://github.com/manga-download/hakuneko/assets/123682535/b3e9119f-426c-4f45-a18d-ab8319c889bf)

**Comment by MikeZeDev** [comment]
Site is just slow as * and plagued with ads apparently.

**Comment by MikeZeDev** [comment]
Today it worked 🤷 
![image](https://github.com/manga-download/hakuneko/assets/10671518/9f4c8970-42b6-47b7-a2ee-da64c4c9ad0e)
