### ISSUE TITLE
[Bug] Hakuneko not installing in Ubuntu 22

### ISSUE THREAD

**Issue by user7415** [manga-download/hakuneko#6662]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Downloaded the hakuneko latest stable installer but tried also with nightly installer. Hakuneko does install but not boot.

**To Reproduce**
download latest or nightly
sudo dpkg -i provided_hakuneko_file.deb
start hakuneko

**Expected behavior**
Hakuneko booting correctly

**Screenshots**
![hakuneko_bug](https://github.com/manga-download/hakuneko/assets/32248087/ca4ab2cd-9504-4a25-9a3b-0413866e1f44)

**Context (please complete the following information):**
 - OS: Ubuntu 22 lts last updates
 - HakuNeko Version 6.1.7 latest but same with nightly

**Additional context**
I tried in the guide also with the alternate launch without gpu acceleration or thing but does not work the same...

**Comment by Sheepux** [comment]
can you try with haruneko ?
https://github.com/manga-download/haruneko

Edit: woops no linux releases yet.

**Comment by user7415** [comment]
> can you try with haruneko ? https://github.com/manga-download/haruneko
> 
> Edit: woops no linux releases yet.

Is a new fork of hakuneko? If so can i Kindly Request to use Firefox instead of Electron? so that scripts like ublock origin could work in order to avoid malware...

by the way it seems it doesn't exist a linux version yet..

**Comment by Sheepux** [comment]
it's now NWjs instad of electron and no it's still using chrome. There are no bundles tools that uses firefox. Also ublock origin exists for chrome (electron/nwjs).

and yes, as my edit said (that you quoted), there's no linux version yet :)

**Comment by ignaciocastro** [comment]
I couldn't reproduce this on a fresh Ubuntu 22.04 installation. Could you please open up the app on terminal (just write hakuneko-desktop) and show the result when it crashes?

**Comment by user7415** [comment]
H

> it's now NWjs instad of electron and no it's still using chrome. There are no bundles tools that uses firefox. Also ublock origin exists for chrome (electron/nwjs).
> 
> and yes, as my edit said (that you quoted), there's no linux version yet :)

I see if you guys develop on a browser with noscript or ublock origin support can you mind of turning it on automatically by default inside the browser in hakuneko? Please mind us users, manga websites are full of advertisings full of malwares and malicious scripts.

Not displaying the webpages by hiding the output does not mean that the malwares are not executed, with noscript and ublock origin things would change, thanks in advance!

**Comment by user7415** [comment]
> I couldn't reproduce this on a fresh Ubuntu 22.04 installation. Could you please open up the app on terminal (just write hakuneko-desktop) and show the result when it crashes?

Here, tried both with and without the --disable-gpu option
```

user@ubuntu:~$ hakuneko-desktop

Usage:
  /usr/lib/hakuneko-desktop/hakuneko [OPTIONS]

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default


--------------
Framework Info
--------------
Electron : 6.1.7
Chrome   : 76.0.3809.146
Node     : 12.4.0


-------------
Configuration
-------------
Update URL           : https://manga-download.github.io/hakuneko/6.1.7/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : /home/user/.cache/hakuneko-desktop
UserData Directory   : /home/user/.config/hakuneko-desktop

[13328:0110/193349.377292:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
user@ubuntu:~$ hakuneko-desktop --disable-gpu

Usage:
  /usr/lib/hakuneko-desktop/hakuneko [OPTIONS]

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default


--------------
Framework Info
--------------
Electron : 6.1.7
Chrome   : 76.0.3809.146
Node     : 12.4.0


-------------
Configuration
-------------
Update URL           : https://manga-download.github.io/hakuneko/6.1.7/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : /home/user/.cache/hakuneko-desktop
UserData Directory   : /home/user/.config/hakuneko-desktop

[13457:0110/193413.604337:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
```

**Comment by ignaciocastro** [comment]
@user7415, could you try running it with the `--no-sandbox` flag instead?

**Comment by user7415** [comment]
> @user7415, could you try running it with the `--no-sandbox` flag instead?

I tried it, with `--no-sandbox` flag it works correctly, I was able to update the client via the first load with the updater however if I remove the flag the error is back here.

**Comment by Sheepux** [comment]
That's an electron bug having issues with some drivers. As we're using an old electron version and not releasing a new version of hakuneko, this would be solved in haru (that is now using an up to date nwjs)

**Comment by user7415** [comment]
I pretty see, so in this case what we would to do with this bug? Leaving the post here for others that would need to install hakuneko with ubuntu 20/22 during this period that haruneko isn't available?

PS: Have you read the previous post of adding ublock/noscript addon (with selected domains pre-authorized) automatically integrated in order to avoid getting malware using haruneko? It can be done? Or do you have some other solution for that? Thank you very much in advance.

**Comment by Sheepux** [comment]
Regarding the anti adblock we have an internal blacklist. relates to https://github.com/manga-download/hakuneko/issues/1196 (see the original answer, but things have changed since then as electron is able to add extensions).
Open a new feature request if needed as it's not related to the current ticket.
Hakuneko is considered feature complete/on-deprecation and will not integrate any new feature.

I'll close this ticket as it can be found with the search.
