### ISSUE TITLE
docker version

### ISSUE THREAD

**Issue by sflix** [manga-download/hakuneko#6663]
Hello, 
I don't know if this has been requested, but i've read thats its is possible (not ideal, but possible) to do a docker version of an electron program. If possible could you do a docker version?
A docker version would be ideal, that way the program could be managed via a web explorer in any device and a nas can be used for the storage.
it would be the closes version of an *arr 

Thank you.

**Comment by MikeZeDev** [comment]
Already been asked , wont come as its a path to automation and this is something we will never do. Its against Hakuneko philosophy.
