### ISSUE TITLE
[Site Request] VF Scan

### ISSUE THREAD

**Issue by 1MarONE** [manga-download/hakuneko#6664]
**Name of the website**
VF Scan

**Website urls (examples below)**
- Site: https://www.vfscan.cc/
- Manga List: https://www.vfscan.cc/manga/
- Manga example: https://www.vfscan.cc/manga/hajimete-no-gal/
- Chapter online viewer example: https://www.vfscan.cc/scan-hajimete-no-gal-154/

**Languages**
French

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Same answer than here : https://github.com/manga-download/hakuneko/issues/5632
