### ISSUE TITLE
[Shinigami ID] Downloads aren't working

### ISSUE THREAD

**Issue by hachi-zy** [manga-download/hakuneko#6667]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

The domain has changed from shinigami.moe to shinigamitoon.com, and I have tried to change the domain to the latest one. The function to get the list of chapters works, but the image function does not. After inspecting the elements on their website, it turns out they have added a new function to load the images. So, if I open the chapter while the inspect element is active, the image will not appear until the inspect element is closed. Therefore, the script in hakuneko might produce null when getting the image because there is no image at the beginning (this is the conclusion I have come to, so it might be wrong).

*Edit: i tried to show preview of the chapter and it says "There was no content found ..."

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Just when i changed the domain for it in Haru 😢 Wonderful they started to crypt data
