### ISSUE TITLE
[Site Request] Sushi-Scan

### ISSUE THREAD

**Issue by ran17nee** [manga-download/hakuneko#6672]
**Name of the website**
Sushi-Scan

**Website urls (examples below)**
- Site: https://sushiscan.net/
- Manga List: https://sushiscan.net/catalogue/
- Manga example: https://sushiscan.net/catalogue/comme-les-autres/
- Chapter online viewer example: https://sushiscan.net/comme-les-autres-volume-7/

**Languages**
French

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
You didnt even check the program before requesting, right? 
![image](https://github.com/manga-download/hakuneko/assets/10671518/c5ad831f-31bb-4ed4-be35-2e815d93280e)

**Comment by ran17nee** [comment]
Sorry that "I didn't check the program".
I use hakuneko almost everyday and I'm used to "copy-paste" rather than loading the connector. The copy-link feature didn't work so I "assumed" that the connector isn't in the list, my apologies. 
That said, the connector is not working (not loading, neither is the copy-paste working), so I'll open another issue.
Thank you for your hard work.

**Comment by ran17nee** [comment]
My bad. Just checked and it looks like the issue can't be solved because of the cloudflare or something (excuse my ignorance). I won't bother you then, hoping it gets fixed someday.

**Comment by MikeZeDev** [comment]
Its ok, you couldnt have guessed :)
