### ISSUE TITLE
[Site Request] Lethe Scans

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6673]
**Name of the website**
Lethe Scans

**Website urls (examples below)**
- Site: https://www.lethescans.com/
- Manga List: https://www.lethescans.com/seriler/
- Manga example: https://www.lethescans.com/manga/the-100th-regression-of-the-max-level-player/
- Chapter online viewer example: https://www.lethescans.com/the-100th-regression-of-the-max-level-player-bolum-19/

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website got htaccess login
