### ISSUE TITLE
[Site Request] NyxManga

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6675]
**Name of the website**
NyxManga

**Website urls (examples below)**
- Site: https://nyxmanga.com/
- Manga List: https://nyxmanga.com/manga/
- Manga example: https://nyxmanga.com/manga/bilge-okuyucunun-bakis-acisi/
- Chapter online viewer example: https://nyxmanga.com/bilge-okuyucunun-bakis-acisi-bolum-183/

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
You requested at least 10 websites and still you dont understand you have to search before if it hasnt been requested? 

https://github.com/manga-download/hakuneko/issues/6231 pls
