### ISSUE TITLE
Saikai Scan 

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6678]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

Hello! the site changed its "address" due to some sites being banned because of dmca

"New" Website: https://saikaiscans.net
Manga example: https://saikaiscans.net/comics/contos-de-demonios-e-deuses
Chapter online viewer example: https://saikaiscans.net/ler/comics/contos-de-demonios-e-deuses/26850/capitulo-32-borboleta

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
You opened an issue 2 weeks ago for this website its still opened, why do you open another? 😡 
Its just unfixable anyway. Most PTBR website got the Cloudflare tag meaning its useless to requests FIXES 😢
