### ISSUE TITLE
[<LezhinUS>] Connector not working

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#6686]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

When we refresh the list from lezhinus is fetching the list from lezhinkr and only shows korean comics

### To Reproduce

When we refresh the list from lezhinus is fetching the list from lezhinkr and only shows korean comics

**Comment by MikeZeDev** [comment]
Lezhin websites use the same api and langage is set by cookies and other things, maybe they changed stuff
