### ISSUE TITLE
[CxC comic] Connector not working

### ISSUE THREAD

**Issue by Froktime** [manga-download/hakuneko#6688]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

I can't download full chapters
=> https://cxc.today/zh/store/hulurd/book/6794  (sample link)
![ảnh](https://github.com/manga-download/hakuneko/assets/98095197/9df3d179-1434-4b78-9383-2bf3ef26a403)

There are a total of 17 chapters but Hakuneko only shows 14 chapters
![ảnh](https://github.com/manga-download/hakuneko/assets/98095197/75a73646-9ecd-4917-ab76-1084542a5076)
![ảnh](https://github.com/manga-download/hakuneko/assets/98095197/d7dcdaa4-2e63-4e7c-a029-191a5ce71817)

### To Reproduce

Some manhuas are fully downloadable, but some are missing a few chapters or more than half

**Comment by MikeZeDev** [comment]
No offense but on the page chapters goes up to 14 for me. 
![image](https://github.com/manga-download/hakuneko/assets/10671518/6ce1077a-d3ed-413a-9d57-4763e90c036e)

I'll assume its about paid chapters then.
Chapter list is cached to avoid overloading servers, once its read you cant update it unless you restart haku.

If you listed the chapters BEFORE purchasing / logging into your account on Hakuneko ofc you will miss some.
Close Hakuneko, and login inside BEFORE listing chapters.


If you still dont see paid chapters i am afraid this will require more coding and lending a paid account credential to a dev, and tbh we dont have the time for that.

**Comment by Froktime** [comment]
> No offense but on the page chapters goes up to 14 for me. ![image](https://private-user-images.githubusercontent.com/10671518/297738063-6ce1077a-d3ed-413a-9d57-4763e90c036e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDMzODcsIm5iZiI6MTcwNTY0MzA4NywicGF0aCI6Ii8xMDY3MTUxOC8yOTc3MzgwNjMtNmNlMTA3N2EtZDNlZC00MTNhLTlkNTctNDc2M2U5MGMwMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OGI1MGQzZWUwYTFmMWFkNjRiMzdjMjg0NDQxY2IyNzc3ZGJjYThkODkxNjYxMzZmMWNkZDRiOTJmYzE5ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s2SwXhtbs5N0n_iERwtCaWDapIEilrWqYTzijyIzR9c)
> 
> I'll assume its about paid chapters then. Chapter list is cached to avoid overloading servers, once its read you cant update it unless you restart haku.
> 
> If you listed the chapters BEFORE purchasing / logging into your account on Hakuneko ofc you will miss some. Close Hakuneko, and login inside BEFORE listing chapters.
> 
> If you still dont see paid chapters i am afraid this will require more coding and lending a paid account credential to a dev, and tbh we dont have the time for that.

I found out the reason. That's because the website doesn't save my login on Hakuneko so i can't access R18 chapters . I hope this can be fixed. I also realized that i couldn't log in via cookie if I wanted to log in in another browser (by extension cookie editor).

**Comment by Froktime** [comment]
> No offense but on the page chapters goes up to 14 for me. ![image](https://private-user-images.githubusercontent.com/10671518/297738063-6ce1077a-d3ed-413a-9d57-4763e90c036e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM4MzQsIm5iZiI6MTcwNTY0MzUzNCwicGF0aCI6Ii8xMDY3MTUxOC8yOTc3MzgwNjMtNmNlMTA3N2EtZDNlZC00MTNhLTlkNTctNDc2M2U5MGMwMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDU0MjQzYzQ4NmZmODhiNzJhODUwZjFmNzU2NDVmMzY1Mjc4NWRlNmExNTE4OTRkZTY4ZTY0MGEyNWYzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X3f6v6gFRpadkBVm4MqrmWW9QJsUazvn2sMQY-3XIAA)
> 
> I'll assume its about paid chapters then. Chapter list is cached to avoid overloading servers, once its read you cant update it unless you restart haku.
> 
> If you listed the chapters BEFORE purchasing / logging into your account on Hakuneko ofc you will miss some. Close Hakuneko, and login inside BEFORE listing chapters.
> 
> If you still dont see paid chapters i am afraid this will require more coding and lending a paid account credential to a dev, and tbh we dont have the time for that.

Thank you for your replying. I have solved the problem.
