### ISSUE TITLE
[Site Request ]Mangadenizi

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6691]
**Name of the website**
Mangadenizi
**Website urls (examples below)**
- Site:https://www.mangadenizi.net/
- Manga List: https://www.mangadenizi.net/manga-list
- Manga example: https://www.mangadenizi.net/manga/assassination-classroom
- Chapter online viewer example: https://www.mangadenizi.net/manga/assassination-classroom/180.4

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Dont ask for a new website, ask for an address change  instead. https://github.com/manga-download/hakuneko/blob/93f7054aa28789b5d8479619e856bc07cc6f1c5c/src/web/mjs/connectors/MangaDenizi.mjs#L6
