### ISSUE TITLE
https://www.lezhinus.com

### ISSUE THREAD

**Issue by Akyshaa** [manga-download/hakuneko#6693]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

This is loading the list from the Korean website.

### To Reproduce

![Captura de tela 2024-01-20 172539](https://github.com/manga-download/hakuneko/assets/157246376/54f2e745-225e-4967-ace3-2b3eb1f33848)

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/3a337466-6ceb-43fb-b2ac-8e68d1b62703)

Why opening a new ticket for the same website? Search before and dont waste your time pls
