### ISSUE TITLE
[Website Change ] mangapanda.onl to replace mangapanda.com

### ISSUE THREAD

**Issue by ibanobu** [manga-download/hakuneko#6695]
**Name of the website**
[thewebsitename](https://mangapanda.onl/)

**Website urls (examples below)**
- Site: https://mangapanda.onl/
- Manga example: https://mangapanda.onl/manga/hoshizora-no-karasu
- Chapter online viewer example: https://mangapanda.onl/chapter/hoshizora-no-karasu/chapter-9

**Languages**
Not Sure... Maybe English

**Website relationship*
Might be a port of the old website content, under the new domain

**Comment by MikeZeDev** [comment]
Sure but, are they even related? 
Also its seems to be another mangahub clone, not sure its worth.
