### ISSUE TITLE
[<MangaEffect>] Connector not working

### ISSUE THREAD

**Issue by Torablue** [manga-download/hakuneko#6698]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Can load the chapter list just fine, new chapters included. But I can't download it.

### To Reproduce

1. Name of connector MangaEffect
2. Name of manga (if connector update is working) Tensei Kizoku, Saikyou de Saisoku
3. Name of chapter (if manga update is working) 57, 10 - 13
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) Failed to load within the given timeout of 60 seconds.

**Comment by MikeZeDev** [comment]
Fix done make sure to use nightly build and wait for it to be merged.
