### ISSUE TITLE
[Bug] Hakuneko nightly and stable does not run on Ubuntu 22.04

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#6700]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I try Nightly version 8.3.4 and stable version 6.1.7 and it does not work on ubuntu 22.04
**To Reproduce**
1. Install the app
2. open the app

**Expected behavior**
it should work

**Screenshots**
<img width="713" alt="image" src="https://github.com/manga-download/hakuneko/assets/29157187/db2c7883-944d-43d2-96ac-79021cdfb942">

<img width="906" alt="image" src="https://github.com/manga-download/hakuneko/assets/29157187/d16682ba-a266-48ab-a97d-4a23e569f1a9">

<img width="791" alt="image" src="https://github.com/manga-download/hakuneko/assets/29157187/1918e8c9-462a-428e-bfda-6728be763e17">

<img width="930" alt="image" src="https://github.com/manga-download/hakuneko/assets/29157187/7bcd5cad-53e1-4398-8bc4-c1c20164fcef">

**Context (please complete the following information):**
 - Ubuntu 22.04
 - HakuNeko Version 6.1.7 and 8.3.4

**Additional context**

**Comment by Sheepux** [comment]
Probably duplicate https://github.com/manga-download/hakuneko/issues/5792
Did you use search first ?
