### ISSUE TITLE
[<InfernalVoidScans>] Connector not working

### ISSUE THREAD

**Issue by nadtooBCS** [manga-download/hakuneko#6701]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list not loading.

![Screenshot 2024-01-23 065715](https://github.com/manga-download/hakuneko/assets/65632827/80117b96-fbee-4051-a698-43d3b3e27c64)

### To Reproduce

1. Name of connector - void-scans.com
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Fixed. Make sure to use nightly version and wait for the fix to be merged. Thanks for reporting.
