### ISSUE TITLE
[MangaHub] Unable to read Manga/Manhwa

### ISSUE THREAD

**Issue by Davidbolt121199** [manga-download/hakuneko#6703]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

All Manga and Manhwa chapters shows host name not verified 
![Screenshot_2024-01-23-07-10-04-946_app mihon-edit](https://github.com/manga-download/hakuneko/assets/121578582/d0708924-7b3f-4e75-b300-180a3a7588e2)

### To Reproduce

1. MangaHub
2. All Manga and Manhwa should be able to read.
3. All chapters of Manga and Manhwa should be able to load without error.

**Comment by MikeZeDev** [comment]
If you REALLY had tried nightly build like you said Hakuneko wouldnt have contacted this address (mnghubcdn), because nightly fix CHANGED THIS URL :D.

https://github.com/manga-download/hakuneko/commit/93f7054aa28789b5d8479619e856bc07cc6f1c5c

Please READ and FOLLOW the instructions properly,

**Comment by Davidbolt121199** [comment]
Can you send instructions please.

**Comment by Davidbolt121199** [comment]
Nightly is for windows, Mac and Linux. I need it for Android.

**Comment by MikeZeDev** [comment]
There is no Hakuneko for android, what are you doing ?
