### ISSUE TITLE
[<Asura Scans TR>] Connector not working Domain change

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6707]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The URL of Armoni Scans will change or has already changed. The new URL is again https://asurascans.com.tr/

Translation of the image: The Armoni Scans series will now continue on asurascans.com.tr We are waiting for you at our new address! 
![WhatsApp Görsel 2024-01-24 saat 11 13 24_ec66d27a](https://github.com/manga-download/hakuneko/assets/127633031/bf6044ed-c090-4640-b3d4-24a1053b1c2d)

### To Reproduce

1. Name of connector Asura Scans TR
2. Name of manga (if connector update is working) 
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
What would be a week without Asura changing domain, right? ;)

**Comment by MikeZeDev** [comment]
Oh and they changed from Mangastream to Madara again
