### ISSUE TITLE
[Baozimh] There is bin file when download

### ISSUE THREAD

**Issue by black0888** [manga-download/hakuneko#6708]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

when download chapter, sometimes there is some image that become bin file like screenshot below
![WM-Screenshots-20240124123048](https://github.com/manga-download/hakuneko/assets/77179150/d81a7409-14ad-4338-8bfd-eca6d6f3524d)

one more, if possible maybe the image source can be change to image that less watermark
link image that show on website:
https://s1.baozimh.com/scomic/sijin-yuewenmanhuakexinwenhua/0/373-z34s/16.jpg

link image that less watermark
https://static-tw.baozimh.com/scomic/sijin-yuewenmanhuakexinwenhua/0/373-z34s/16.jpg

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Bao servers are not the most stable, to say the least. IIRC those bin are random 🤷 .

**Comment by MikeZeDev** [comment]
Also no offense but the two pictures are identical, or i am too sleepy to see the difference

**Comment by black0888** [comment]
seems like they change it again, before there is wm like this
![16](https://github.com/manga-download/hakuneko/assets/77179150/f0169021-78ac-4a9b-8bdd-087c2fa1ae6a)
I download this image before make post here, and if I remember correctly when I post here, the watermark is on top left not on top right like the one that I downloaded
