### ISSUE TITLE
[<Lezhin US>] Manga list doesn't update correctly.

### ISSUE THREAD

**Issue by Akyshaa** [manga-download/hakuneko#6709]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Only 290 stories appear. There should be more than 1000 stories. And no matter how many times I update the list, the number doesn't change, it's still 290.

**Comment by MikeZeDev** [comment]
If you are not satisfied with the number of mangas in the list use paste feature. Official websites "lists" are a very often a pain to parse and not complete.

**Comment by Akyshaa** [comment]
Yes, yesterday the problem of the list loading in another language was
fixed, but now the list isn't loading correctly. Only 290 appear, when
there should be more.

**Comment by MikeZeDev** [comment]
Website api stops at such number 🤷

**Comment by Akyshaa** [comment]
Anyway, thank you very much and sorry for taking up your time.
