### ISSUE TITLE
[<Tappytoon>] Manga list doesn't update correctly.

### ISSUE THREAD

**Issue by Akyshaa** [manga-download/hakuneko#6710]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list doesn't update correctly. Only 100 stories appear. Every time the list is updated, the mangas change, but it never goes over 100.

### To Reproduce

Tappytoon

**Comment by MikeZeDev** [comment]
Gotta check but its probably the website that limits to 100 and nothing can be done.
Edit : Yes, api is blocked to 100 results
