### ISSUE TITLE
Cannot download from welovemanga.one, only website's loading gif is available

### ISSUE THREAD

**Issue by Triramama** [manga-download/hakuneko#6711]
Hello I was wondering if you could fix the issue with "welovemanga", the website puts this loading gif before it fetches the pages from the server, but hakuneko is not able to process this so every chapter only has the gif (and their scanlation recruitment ad). It looks like this, when i add chapters to dl list, the only thing that gets downloaded are these two pictures:
![image](https://github.com/manga-download/hakuneko/assets/97356540/dbf831d0-7093-4163-a299-11716d96a708)
I'm on rev. 6.1.7, welovemanga is the only raw chapter provider that doesn't watermark the images, so if you could adjust the script so it can receive the images that are loaded later, it would be great, cheers!

**Comment by MikeZeDev** [comment]
Mangalist doesnt load anyway, they absolutely want javascript pfff
