### ISSUE TITLE
[Site Request] Amuy Scans

### ISSUE THREAD

**Issue by mangareader4** [manga-download/hakuneko#6716]
**Name of the website**
Amuy Scans

**Website urls (examples below)**
- Site: https://apenasmaisumyaoi.com/
- Manga List: https://apenasmaisumyaoi.com/manga/
- Manga example: https://apenasmaisumyaoi.com/manga/meurei/
- Chapter online viewer example: https://apenasmaisumyaoi.com/manga/meurei/capitulo-60/

**Languages**
Português

**Additional details**
Madara Theme

**Comment by MikeZeDev** [comment]
Can you SEARCH before asking pls?  😢 https://github.com/manga-download/hakuneko/issues/6186
