### ISSUE TITLE
[Bug][cxc] chapter eorror/ [Question] hakuneko function question

### ISSUE THREAD

**Issue by rsgpwxfvc** [manga-download/hakuneko#6718]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**

chapter information:

  {
    "connectorID": "cxc",
    "mangaID": "/store/31/book/4383",
    "chapterID": "/store/31/book/4383/chapter/14376",
    "chapterTitle": "# 7 - DAY7: to / 去\b、給"
  }

This chapter can be viewed through the Preview Panel,but this chapter cannot be downloaded

**Expected behavior**
 this chapter can be downloaded

**Screenshots**
<img width="619" alt="1" src="https://github.com/manga-download/hakuneko/assets/150799318/c6b1c23b-1f10-4b76-b367-d3788af1cb92">
<img width="396" alt="2" src="https://github.com/manga-download/hakuneko/assets/150799318/45bb31f2-7edd-442d-8764-efd73f5f2467">

**Context (please complete the following information):**
Windows11
hakuneko-desktop_8.3.4_windows-portable_amd64

**Additional context**

**Comment by rsgpwxfvc** [comment]
In addition, I would like to ask about the functions of hakuneko


1.Output the error record of Download Queue
Can the error records I marked in the picture be exported?

<img width="396" alt="2" src="https://github.com/manga-download/hakuneko/assets/150799318/ffbea3a1-643f-47f6-8300-3ca124144282">


___________________________________________________________________________________
2.batch download:
Add all chapters of multiple comics to the "Download Queue" at one time

___________________________________________________________________________________
Do these two functions currently not exist?

**Comment by MikeZeDev** [comment]
Could be an invalid character in path, i see a / in chapter name, wtf with this manga

* 1 is no
* 2 You can filter chapters then click download all. With regexp which i admit could be complicated

**Comment by MikeZeDev** [comment]
Also giving the id and paths is great but i cant use them to select the same manga than you , so i cant test the manga.

Having the fully qualified manga url would help so i can paste it because i cant copy paste manga url pr name from a picture, and since cant type in this langage.

**Comment by MikeZeDev** [comment]
Ok we fail to properly clean the path from invalid chars. There is still a \u0008 in this 🗡️ 
![image](https://github.com/manga-download/hakuneko/assets/10671518/30a47aa7-75aa-4788-b8be-4ec96a9a81a6)

Thanks for signaling that issue 🙏 Fix incoming.

**Comment by rsgpwxfvc** [comment]
thank you for your help

Regarding question 2
<img width="396" alt="299835274-ffbea3a1-643f-47f6-8300-3ca124144282" src="https://github.com/manga-download/hakuneko/assets/150799318/14de14aa-8f55-4c9d-b3e7-ccdef62abe2c">

Example:
I want to add the works in the blue frame to "Download Queue" at once


I know that the function marked in red circle is used to download all chapters of a work

**Comment by MikeZeDev** [comment]
No "mass mangas download in one click" is planned. We are against it.
