### ISSUE TITLE
[Site Request] Mangatoto

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#6729]
**Name of the website**
Mangatoto.com

**Website urls (examples below)**
- Site: https://mangatoto.com/
- Manga List: https://mangatoto.com/browse
- Manga example: https://mangatoto.com/series/13653/fairy-tail-blue-mistral
- Chapter online viewer example: https://mangatoto.com/chapter/260606

**Languages**
English and Indonesian 

**Website relationship*
I believe this is the mirror site of bato and it is nice to have a backup

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
No. Change Batoto url in settings to this one if you want, its just a batoto clone after all
