### ISSUE TITLE
[Feature]在网页端使用

### ISSUE THREAD

**Issue by xzyl4303** [manga-download/hakuneko#6735]
这个软件很不错。希望可以在服务器部署到网页上，这样就可以在不能安装软件的电脑上使用了

**Comment by MikeZeDev** [comment]
Use english please.

**Comment by xzyl4303** [comment]
This software is very good. I hope it can be deployed on the server to the web page so that it can be used on computers that cannot install the software.

**Comment by Sheepux** [comment]
no it cannot. It's a desktop app
