### ISSUE TITLE
HydraX download RangeError: stderr maxBuffer length exceeded

### ISSUE THREAD

**Issue by dodieboy** [manga-download/hakuneko#674]
![2](https://user-images.githubusercontent.com/9015764/69108878-f807bd00-0ab0-11ea-8f76-51d401a68a14.png)

**Comment by dodieboy** [comment]
But the downloader work for ep 109

**Comment by 27136773** [comment]
Looks like there is to much output from ffmpeg when the file is multiplexed to MKV
Further investigation required
