### ISSUE TITLE
[Site Request] cloudrecess

### ISSUE THREAD

**Issue by comicsforlife** [manga-download/hakuneko#6741]
**Name of the website**
the cloud recess

**Website urls (examples below)**
- Site: https://cloudrecess.io/
- Manga List: https://cloudrecess.io/manga/
- Manga example: https://cloudrecess.io/manga/sunkissed
- Chapter online viewer example: https://cloudrecess.io/manga/sunkissed/40

**Languages**
English

**Comment by konkonchum** [comment]
I second this, since this is such a hq source.
I would greatly appreciate it!

**Comment by Arekkusu1998** [comment]
I support it too: it's a very good source.

**Comment by MikeZeDev** [comment]
Geoglocked cant do

**Comment by Arekkusu1998** [comment]
@comicsforlife and @konkonchum, I can no longer access [Cloudrecess](cloudrecess.io) and I don't know how to contact the Admin. The Cloudflare barrage loops endlessly. My access was neither banned nor restricted, so I don't know if it's just me or it's the website that's having problems.

**Comment by comicsforlife** [comment]
I guess the website is down

Em ter., 26 de mar. de 2024 às 11:22, Arekkusu1998 ***@***.***>
escreveu:

**Comment by MikeZeDev** [comment]
Website down
