### ISSUE TITLE
Hunters Scan

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6742]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

hello! all very well? I hope so. The former HUNTERS SCAN site has changed hosts.

"New" Website: https://huntersscan.xyz
Manga example: https://huntersscan.xyz/manga/devorador-de-aco
Chapter online viewer example: https://huntersscan.xyz/ler/devorador-de-aco-capitulo-24

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
This url is the same used in Hakuneko. https://github.com/manga-download/hakuneko/blob/6d13602ae1d4b8ef33c0f03e0db1fb4c58ecf9aa/src/web/mjs/connectors/HunterScan.mjs#L10 and website is not responding  at all, nothing we can do

![image](https://github.com/manga-download/hakuneko/assets/10671518/553a554b-bd4b-42cc-8082-4ff0d71d7592)

Please check if website works or not in browser before opening issues 😔
