### ISSUE TITLE
Manhwa Time Connector not working

### ISSUE THREAD

**Issue by HumanBlazing** [manga-download/hakuneko#6746]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Website has changed it is now https://www.manhwatimez.com/, listed connector is manhwatime.xyz

### To Reproduce

1. Name of connector - manhwatime
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

Website no longer exist and changed name and website link.

**Comment by MikeZeDev** [comment]
Image CDN cause problems with Hakuneko, It says HTTP2  errors, no wonder because its using HTTP3
Its an electron problem. Wont fix
