### ISSUE TITLE
[LunarScans] Connector not working

### ISSUE THREAD

**Issue by AzureLance24** [manga-download/hakuneko#6747]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

It is now CloudFlare protected.
Trying the challenge results in an infinite loop which I saw as a known issue.
I'm opening an issue just so it can go under the CloudFlare tag & future reference.
Are there any remedies for this currently in hakuneko?

### To Reproduce

1. LunarScans
2. _
3. _
4. Errors:   
Fetch failed loading: GET "https://lunarscan.org/series/list-mode/".

**Comment by MikeZeDev** [comment]
>  Are there any remedies for this currently in hakuneko?

You are out of luck. This is not a pinned issue for nothing :/

![image](https://github.com/manga-download/hakuneko/assets/10671518/7274df8d-fd8c-40ac-bc46-e8da852bfa0e)

**Comment by AzureLance24** [comment]
rip, thx anyways

**Comment by MikeZeDev** [comment]
no more CF
