### ISSUE TITLE
[Site Request] Turkmanga

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6749]
**Name of the website**
Turkmanga

**Website urls (examples below)**
- Site: https://turkmanga.com.tr/
- Manga List: https://turkmanga.com.tr/mangalar
- Manga example: https://turkmanga.com.tr/manga/pick-me-up
- Chapter online viewer example: https://turkmanga.com.tr/manga/pick-me-up/bolum-1

**Languages**
Turkish (Türkçe) 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Do you have some memory troubles? Its not the first time you ask for a website you already asked yourself a few weeks ago. 
Stop opening useless issues https://github.com/manga-download/hakuneko/issues/6674

**Comment by Tianzhou2** [comment]
> **Name of the website** Turkmanga
> 
> **Website urls (examples below)**
> 
> * Site: https://turkmanga.com.tr/
> * Manga List: https://turkmanga.com.tr/mangalar
> * Manga example: https://turkmanga.com.tr/manga/pick-me-up
> * Chapter online viewer example: https://turkmanga.com.tr/manga/pick-me-up/bolum-1
> 
> **Languages** Turkish (Türkçe)
> 
> *_Website relationship_ If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
> 
> **Additional details** Add any other context details that you may have found (like template to reuse)

merhaba bisey soracaktım görürsen cevap verir misin
