### ISSUE TITLE
[Site Request] Manga Fire

### ISSUE THREAD

**Issue by tpdump** [manga-download/hakuneko#6755]
**Name of the website**
Manga Fire

**Website urls (examples below)**
- Site: https://mangafire.to/home
- Manga List: https://mangafire.to/added
- Manga example: https://mangafire.to/manga/kkumeseo-jayuro.924km
- Chapter online viewer example: https://mangafire.to/read/kkumeseo-jayuro.924km/en/chapter-118

**Languages**
List of languages supported by the website
- english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Patched 4 months ago, supported since March 2023 , do you live in a time bubble perhaps? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/a0857351-a790-4bf3-8ac0-488a61190485)
