### ISSUE TITLE
[<manhuafast>] Connector not working

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6760]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Manga list is not refreshing and showing up

### To Reproduce

1. Name of connector: manhuafast
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/123682535/781d567b-fb88-4f0b-9bc8-f68beef45f8f)

**Comment by MikeZeDev** [comment]
Cloudflare, that usual for this website, use another website.

![image](https://github.com/manga-download/hakuneko/assets/10671518/742334ab-7705-45bb-9395-126715cfe70b)

**Comment by MikeZeDev** [comment]
No more CF
