### ISSUE TITLE
Remove Assorted Scans (Accepted Removal Request)

### ISSUE THREAD

**Issue by ObserverOfTime** [manga-download/hakuneko#6764]
### QUESTIONAIRE

Which website should be removed?
**Assorted Scans**

Why should this website be removed from HakuNeko?
**Because you refused to be identifiable.**

#### In case of Traffic
1. How much traffic is caused by HakuNeko?
**That's the question, isn't it?**
2. How much is it compared to overall traffic (percentage)?
**N/A**
3. How did you measure those analytics (framework)?
**N/A**
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
**N/A**
5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
**Yes.**

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
**Yes.**
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
**No. Supported tools use a custom UA.**
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
**No.**

#### In case of Monetization
1. Are you using Donations?
**No.**
2. Are you using Advertisements?
**No.**

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
Make sure to meet the conditions for removal:
- ✅ met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- ❌ must provide direct download links for all chapters

**Comment by ObserverOfTime** [comment]
Direct download links are available for logged in users.

**Comment by 27136773** [comment]
Downloads seems to be working, removal request is accepted and waiting for a contributor to remove it.
Website may be re-added in case the conditions are no longer met.
