### ISSUE TITLE
[Site Request] comick.cc

### ISSUE THREAD

**Issue by aihooo444** [manga-download/hakuneko#6767]
**Name of the website**
comick not the same as ComicK that is already on hakuneko
**comick.cc**
- Site: https://comick.cc/
- Manga List: https://comick.cc/
- Manga example: https://comick.cc/comic/00-yu-yu-hakusho-digital-colored-comics?lang=en
- Chapter online viewer example: https://comick.cc/comic/00-yu-yu-hakusho-digital-colored-comics/okNYY-chapter-8-en

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Since coloredmanga.com is down this is the only place you can find a lot of the colored manga chapters.

**Comment by MikeZeDev** [comment]
I am afraid those are the same, api results are totally identical, .cc or .ink. I will close this ticket. Feel free to reopen it if you have proofs that those websites are different.

**Comment by aihooo444** [comment]
Actually I think you are correct but it is not pulling a full list of Manga just for example the first two manga i search for is not showing up on the app but is showing up on the website Urusei Yatsura and Yu Yu Hakusho.
Let me know if I am doing something wrong
![image](https://github.com/manga-download/hakuneko/assets/29587859/a077b637-c284-41f4-9281-4ab26dbb15c1)


![image](https://github.com/manga-download/hakuneko/assets/29587859/eafeb74e-fba5-44b9-a53e-067d6e6126a0)

**Comment by aihooo444** [comment]
forgot to show that it is on the comick.cc website 
![image](https://github.com/manga-download/hakuneko/assets/29587859/8028ee7a-2e31-4bda-9401-18c57b823035)
![image](https://github.com/manga-download/hakuneko/assets/29587859/e25ee0e0-8a9f-47e7-a61b-d7ee2db16e78)

**Comment by MikeZeDev** [comment]
Its a different problem. And no one can change anything.

If you go on the website their manga list stops after a fixed number of pages no matter what you do.
Before it was 100 pages now its down to 30, meaning our manga list will be incomplete.

![image](https://github.com/manga-download/hakuneko/assets/10671518/b1a0a4e3-7a12-4430-990f-2b36ef133cf4)

Find the manga you want on the website, copy its url, and use[ copy paste feature](https://hakuneko.download/docs/FAQ/#copy-and-paste) in Hakuneko. 

We made it so it accepts comick.cc/.app/.fun/.ink links :D

**Comment by aihooo444** [comment]
Ok thanks I didn't know about the copy paste feature I'll give it a try
thanks
