### ISSUE TITLE
Scantrad Union : err_name_not_resolved

### ISSUE THREAD

**Issue by Zarh** [manga-download/hakuneko#677]
Hi

I use the nightly version : https://github.com/manga-download/hakuneko/commits/bf9c84c58d401cc43079beea021f649c68c9b91a

When I try to download a chapter from scantrad union I have this message : 
![err_name](https://user-images.githubusercontent.com/8205047/69193639-86b72100-0b27-11ea-9fc3-5ab52f303530.png)

**Comment by 27136773** [comment]
Website changed domain

**Comment by Zarh** [comment]
Thanks !
