### ISSUE TITLE
[Site Request] DMMブックス (DMM Books)

### ISSUE THREAD

**Issue by waoffles** [manga-download/hakuneko#6772]
**Name of the website**
DMMブックス (DMM Books)

**Website urls**
- Site: https://book.dmm.com/
- Manga List: https://book.dmm.com/list/
- Manga example: https://book.dmm.com/product/775829/b388atabd00336/
- Chapter online viewer example: https://book.dmm.com/free_streaming/b388atabd00336/?cid=FglfSVtRA11XDh1IQVkCQgIRaV9UBAYKWlpWElMHUwBVUgMPSlATV106QkxBUwdaCAtRCwEVEEsDDEQPRgxYXjoHXF5bBw__&lin=0&sd=0

**Languages**
Japanese

**Website relationship*
None

**Additional details**
The path for paid version directed to https://book.dmm.com/streaming/...

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/4317 please search before asking
