### ISSUE TITLE
[<manhwas men >] Connector not working

### ISSUE THREAD

**Issue by necropower** [manga-download/hakuneko#6780]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

it just doesnt download anything, it returns 404 error. preview also doesnt work.

### To Reproduce

1. manhwas net

2. any manga, but i am trying on 'my fantasies are cumming to life' for this issue

3. all chapters have problems

4.

Failed to load resource: the server responded with a status of 404 ()
5629 log entries are not shown.
DevTools failed to parse SourceMap: hakuneko://cache/js/protobuf.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/js/hls.light.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/sm/4f4f84956292156efc04b79e1131dc7c3a51794b7b3d62b43ed5eaca1b36d71e.map
Connector.mjs:434 GET https://manhwas.men/manga/my-fantasies-are-cumming-to-life-uncensored-english/1.00 521

**Comment by MikeZeDev** [comment]
Cloudflare use another website

**Comment by MikeZeDev** [comment]
No more cloudflare.
