### ISSUE TITLE
[Site Request] Kingofmanga

### ISSUE THREAD

**Issue by MohaDC** [manga-download/hakuneko#6783]
**Name of the website**
Kingofmanga

**Website urls (examples below)**
- Site: https://kingofmanga.com/
- Manga List: https://kingofmanga.com/genres/%d8%a5%d8%b9%d8%a7%d8%af%d8%a9-%d8%a5%d8%ad%d9%8a%d8%a7%d8%a1/
- Manga example: https://kingofmanga.com/manga/1867564943-ancient-herbalist/
- Chapter online viewer example: https://kingofmanga.com/1986811557-ancient-herbalist-chapter-1/

**Languages**
Arabic

**Website relationship*
Improved version of ozulscans

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Cant do

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6489
