### ISSUE TITLE
[Site Request] https://m.happymh.com/

### ISSUE THREAD

**Issue by MangaSY** [manga-download/hakuneko#6785]
**Name of the website**
m.happymh

**Website urls (examples below)**
- Site: https://m.happymh.com/
- Manga List: https://m.happymh.com/latest
- Manga example: https://m.happymh.com/manga/lihunhouqianfuchenglewodezhongquan
- Chapter online viewer example: https://m.happymh.com/reads/lihunhouqianfuchenglewodezhongquan/4031860

**Languages**
Chinese

**Website relationship*
Improved version of baozimh.com

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Like stated here, its redirecting to https://ac.qq.com/ for me https://github.com/manga-download/hakuneko/issues/3390

**Comment by MangaSY** [comment]
https://m.happymh.com/ is a free manhua/manga/manhwa website and https://ac.qq.com/ is a manhua paid app. So it's not redirecting. Please reconsider. Thank you.

**Comment by MikeZeDev** [comment]
If i ever paste https://m.happymh.com/ in my browser i end up on https://ac.qq.com which iirc is already supported. I dont know how it is for you, but its redirecting for me. If i tell you its redirecting , its redirecting 🤷. 

Even impersonating a mobile phone, its redirecting. 

If dev cant access to the website it just wont be done. Its not possible.

**Comment by MikeZeDev** [comment]
And the cherry on top : on mobile, with a VPN, i got stopped by Cloudflare captcha. It means its no use because Hakuneko wont be able to handle this website. Give up 😔
