### ISSUE TITLE
[Site Request] bomtoon

### ISSUE THREAD

**Issue by kikk8eee** [manga-download/hakuneko#6786]
**Name of the website**
bomtoon

**Website urls (examples below)**
- Site:  https://www.bomtoon.com/bom/comic/main
- Manga List:  https://www.bomtoon.com/bom/comic/weekly
- Manga example: https://www.bomtoon.com/detail/sabita
- Chapter online viewer example: https://www.bomtoon.com/viewer/sabita/1

**Languages**
korean

**Website relationship*
N/A

**Additional details**
https://chromewebstore.google.com/detail/fatkun-batch-download-ima/gjnbhjpcpiegmooelafaphjciekfindc?

**Comment by MikeZeDev** [comment]
Please dont  open issues for already requested website https://github.com/manga-download/hakuneko/issues/2701
