### ISSUE TITLE
https://sushiscan.net/catalogue/inu-yasha/ Connector not working

### ISSUE THREAD

**Issue by adanhedel** [manga-download/hakuneko#6787]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hello, 
seems there were already some issues with this site, some solved, but I still get no list of mangas for this site. 
Here's the link to the mnga I'm interested in:
https://sushiscan.net/catalogue/inu-yasha/

Thanks, if you can manage to make it worked properly.
cheers

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by adanhedel** [comment]
infact, it's all sushiscan site that isn't listed yet, right?

**Comment by MikeZeDev** [comment]
https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+sushiscan&type=issues

 https://github.com/manga-download/hakuneko/issues/5615
