### ISSUE TITLE
[Bug] Tappytoon (Any Lanugage) Website won't load ("Open in a new window" Feature)

### ISSUE THREAD

**Issue by xVotexX** [manga-download/hakuneko#6788]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When I try to open the Tappytoon website in a new window, it does not load completely and is frozen. I cannot interact with any of the buttons and the loading circle does not rotate.

**To Reproduce**
1. Go to the Connectors List
2. Search for Tappytoon
3. Open any of the three Websites (English, French, German) in a new Window

**Expected behavior**
The Website should load completely and i should be able to navigate through the site (e.g. To Log in, browse Webtoons etc.)

**Screenshots**
What it **should** look like:
![image](https://github.com/manga-download/hakuneko/assets/160360993/14e8c48d-143f-4cd7-a1fc-b8682a0df0e7)

What it **actually** looks like:
![image](https://github.com/manga-download/hakuneko/assets/160360993/19694146-24fa-46ab-910d-e15991ed8895)

What it **actually** looks like: _(Login Page)_
![image](https://github.com/manga-download/hakuneko/assets/160360993/3928d26b-7262-4b20-bc2e-1d87540bfc0f)

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version: 6.1.7

**Additional context**
So far I have only noticed this problem with the "Tappytoon" websites.
When I open the website in my normal browser, everything loads perfectly and I have no problems at all.

**Comment by MikeZeDev** [comment]
Duplicate: Use search before asking please.

https://github.com/manga-download/hakuneko/issues/6612

**Comment by xVotexX** [comment]
> Duplicate: Use search before asking please.
> 
> #6612

I did use the search before asking. 
I thought this would be different because the manga list actually loads and I can see all available free pages. 
#6612 described that he could not do that
The only problem I had was that opening the website in a new window did not work.
However, this morning I tried the nightly build and it worked.
