### ISSUE TITLE
[Jiangzaitoon] Connector not working

### ISSUE THREAD

**Issue by kaikai-chan** [manga-download/hakuneko#6790]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Site has changed.
Name of the website:
Jiangzaitoon

•	Site:  https://jiangzaitoon.info
•	Manga List: https://jiangzaitoon.info/manga/
•	Manga example:  https://jiangzaitoon.info/manga/isimsiz-cicek/
•	Chapter online viewer example: https://jiangzaitoon.info/manga/isimsiz-cicek/bolum-1/

Language: Turkish

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
doesnt matter, Cloudflare = it wont work

**Comment by kaikai-chan** [comment]
Site has changed again.(and again and again and…)
Name of the website:
Jiangzaitoon

• Site: https://jiangzaitoon.dev/
• Manga List: https://jiangzaitoon.dev/manga/
• Manga example:  https://jiangzaitoon.dev/manga/sevgili00/
• Chapter online viewer example:  https://jiangzaitoon.dev/manga/sevgili00/bolum-1/

Turkish
