### ISSUE TITLE
[<Manga-Tr>] Connector not working

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6803]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

![1](https://github.com/manga-download/hakuneko/assets/145361770/80a93fbf-fc64-43ed-9a91-de496cc0549e)
![2](https://github.com/manga-download/hakuneko/assets/145361770/c937091d-d484-484d-af57-af25949d0143)

### To Reproduce

1. Name of connector https://manga-tr.com/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
"works for me" 🤷 .That said, many manga require login but thats unrelated

**Comment by Tianzhou2** [comment]
> "works for me" 🤷 .That said, many manga require login but thats unrelated

I can't open it either.

**Comment by MikeZeDev** [comment]
What does console say when you try to load list
