### ISSUE TITLE
[<ComicK>] Connector not working

### ISSUE THREAD

**Issue by abelluis124** [manga-download/hakuneko#6804]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Site has changed.
Name of the website: 
ComicK

• Site: https://comick.io/
• Manga List: https://comick.io/home
• Manga example: https://comick.io/comic/00-jujutsu-kaisen
• Chapter online viewer example: https://comick.io/comic/00-jujutsu-kaisen/6ZnODgkh-chapter-251-en

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
You clearly didnt TRY NIGHTLY because it works on nightly, dont just check boxes without following instructions

**Comment by abelluis124** [comment]
> You clearly didnt TRY NIGHTLY because it works on nightly, dont just check boxes without following instructions

When I try using the clipboard it doesn't work at all (and I'm using the nightly version.) I tried it on other websites and it did work. The regular website function works but I'm trying to find something specific that doesn't show up when I look up the website through Hakuneko.

**Comment by MikeZeDev** [comment]
I see .
1 ) You didnt mention the clipboard
2 ) Connector accept .app, .ink, .cc . This website is driving me nuts because of its TLD
```       return /https?:\/\/comick\.(app|ink|cc)/.test(uri.origin);  ```

replace io by app ink or cc 🤷

**Comment by abelluis124** [comment]
> I see . 1 ) You didnt mention the clipboard 2 ) Connector accept .app, .ink, .cc . This website is driving me nuts because of its TLD ` return /https?:\/\/comick\.(app|ink|cc)/.test(uri.origin); `
> 
> replace io by app ink or cc 🤷

Yeah, that ended up working thank you so much.

**Comment by Sharpavis** [comment]
Please help I tried all the steps above but comick still won't work

**Comment by MikeZeDev** [comment]
Dont talk on an old issue open another one. If those words are too hard to understand (you asked for easy english) then please use a translator 🙏 

Please understand that necro posting (commenting on old topics) is bad internet practice .

**Comment by Sharpavis** [comment]
I don't understand what you are saying please say in simple english
