### ISSUE TITLE
[<Piccoma>] Connector not working

### ISSUE THREAD

**Issue by minahoku** [manga-download/hakuneko#6805]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Manga list isn't refreshing

### To Reproduce

![a](https://github.com/manga-download/hakuneko/assets/15166229/a61aaeca-6593-49ff-9842-a2e8bef2e8a8)

1. Name of connector Piccoma
2. Name of manga (if connector update is working) https://piccoma.com/web/product/2238?etype=episode
3. Name of chapter (if manga update is working) https://piccoma.com/web/viewer/2238/109575
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Dont open duplicate issues https://github.com/manga-download/hakuneko/issues/6627
