### ISSUE TITLE
[ComicWalker] website change

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6806]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

ComicWalker [has renewal their site to new name "KadoComi"](https://comic-walker.com/topics/news/018dc259-f230-78f5-83e1-98cb8d4e03ec). Hakuneko can't fetch any manga series and chapter list, also clipboard not working.

### To Reproduce

1. Name of connector: ComicWalker
2. Name of manga (if connector update is working): All
3. Name of chapter (if manga update is working): All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### Screenshots

![image](https://github.com/manga-download/hakuneko/assets/2475440/5572e279-910b-44d4-9932-a6a3af1929a8)

**Comment by devmatcha** [comment]
[Manga List](https://comic-walker.com/search/content)
[Chapter List example](https://comic-walker.com/detail/KC_004228_S/episodes/KC_0042280001100011_E?episodeType=latest)

**Comment by MikeZeDev** [comment]
Got it done in [Haruneko](https://github.com/manga-download/haruneko/pull/506) . 
Gotta wait a bit for Hakuneko
