### ISSUE TITLE
[Site Request] https://suryatoon.com/

### ISSUE THREAD

**Issue by KeskinDeniz** [manga-download/hakuneko#6811]
**Name of the website**
[thewebsitename](https://suryatoon.com/)

**Website urls (examples below)**
- Site: https://suryatoon.com/
- Manga List: https://suryatoon.com/manga/
- Manga example: https://suryatoon.com/manga/return-of-the-bloodthirsty-police/
- Chapter online viewer example: https://suryatoon.com/return-of-the-bloodthirsty-police-chapter-50/

**Languages**
ENG

**Website relationship*
no

**Additional details**
-

**Comment by MikeZeDev** [comment]
There is already an issue opened for this website like, right in front of your eyes, in the front page.

![image](https://github.com/manga-download/hakuneko/assets/10671518/45285bdf-4531-4ad7-8b2f-3bb28aa6e392)

👀

**Comment by MikeZeDev** [comment]
Duplicate #6807

**Comment by KeskinDeniz** [comment]
sorry i didnt check, i only make suggestion
