### ISSUE TITLE
[Site Request] COMIC Nettai

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6812]
**Name of the website**
COMIC Nettai (COMIC熱帯)

**Website url**
- Site: https://www.comicnettai.com/
- Manga List: https://www.comicnettai.com/comics
- Manga example: https://www.comicnettai.com/book/31
- Chapter online viewer example: https://www.comicnettai.com/publus/viewer.html?cid=eyJpdiI6InE2dXJxNnVycTZ1cnE2dXJxNnVycXc9PSIsInZhbHVlIjoiSFVnZDdGZVZjY2RRWGdRcGxHbFUvendsWXQyRUZXMVJrWHo5eFp6VlpFUEM3c1Z1RlZvTjZCVGZoMWNMbHZaWnBtMUNHSXdYY0NtanBqNzVxWS9nemRrWStsWWNEYkYwdkNRVDZlcklnbHM9IiwibWFjIjoiZjU4YjYwOWE3MTA1NmQ1NDExZTNjYmE0MGRlYzNmNTdhNzU3NjMzOTQ3NTIzOTZhYjcxOGE4OWIzNWM3NjIzZiJ9

**Languages**
Japanese

**Additional details**
Use PUBLUS for reader

**Comment by MikeZeDev** [comment]
And its a publus version our template cant handle. I figured how it works, but you wont see this in Hakuneko.

We need to find a proper way to code an useful template in Haruneko. 

Ho, same version that Comicboost perhaps?

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6724
