### ISSUE TITLE
[Site Request] Comic Walker

### ISSUE THREAD

**Issue by potato899** [manga-download/hakuneko#6813]
**Name of the website**
Comic Walker

**Website urls (examples below)**
- Site: https://comic-walker.com/
- Manga List: https://comic-walker.com/daily/sat
- Manga example: https://comic-walker.com/detail/KC_005312_S/episodes/KC_0053120000100011_E?episodeType=first
- Chapter online viewer example: https://comic-walker.com/detail/KC_005312_S/episodes/KC_0053120000100011_E?episodeType=first
**Languages**
Japanese
English

**Comment by potato899** [comment]
Nevermind, I just saw a website changed ticket, waiting for it to be implemented in hakuneko.

**Comment by RemReZero123** [comment]
hello. I was also wanting this site to be added and I was just wondering if your latest/last comment here means they will be adding the site? Do you know how long this normally takes? Thanks!

**Comment by potato899** [comment]
I don't know, I only read one manga from there, Elden Ring, so I just copy/pasted the link onto the clipboard and it got the manga and the chapters after they fixed the new domain, but afaik the site itself is not on the list you can choose and browse.

**Comment by MikeZeDev** [comment]
name changed, its available as kadocomi,

**Comment by potato899** [comment]
True, I was referring to the old name comic walker, >I seem to recall not being in the browser list, could be wrong, thanks for the heads up.
