### ISSUE TITLE
[Bug] Unable to sign in with google account

### ISSUE THREAD

**Issue by rueze** [manga-download/hakuneko#6814]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Unable to log in into account using "google sign in". For example trying to log in Bilibili Comics website using google sign in. Any website that require log in with google account is not working as long as its google sign in.

**To Reproduce**
1. Typing in Bilibili Comics website.
2. Click on the top right small button to log in.
3. click continue with google.
4. proceed to log in google account.
5. unable to log in and give error mentioning "This browser or app may not be secure, try again."

**Expected behavior**
Was hoping to be able to log in with google account as everything seems to have google log in nowadays.

**Screenshots**
https://imgbox.com/j5jJx56t

**Context (please complete the following information):**
 - OS: Windows 10 64-bit
 - HakuNeko Version 6.17 Portable

**Additional context**
n/a

**Comment by MikeZeDev** [comment]
Its known, blame google. Wont fix as it require upgrading browser engine and it will break everything
