### ISSUE TITLE
[<Manhuascan>] Connector not working

### ISSUE THREAD

**Issue by Tmp341** [manga-download/hakuneko#6816]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I was trying to add some manhuas (tried both 6.1.7 and nightly). It seems they've changed their url to [manhuascan.com](https://manhuascan.com/)

https://github.com/manga-download/hakuneko/blob/93c651bad56151deb4c7fc98e085a250bb1357a9/src/web/mjs/connectors/ManhuaScan.mjs#L10

### To Reproduce

1. Select Manhuascan
2. Try to update the list 
3. 
![hakuneko](https://github.com/manga-download/hakuneko/assets/1683388/f3e98d0b-ba7b-4aa9-8aa6-6d6f7bf9bf79)

**Comment by MikeZeDev** [comment]
.Io works
![image](https://github.com/manga-download/hakuneko/assets/10671518/7a1cb9f2-5ab9-43ce-9482-0ba412b95274)

Hakuneko works
![image](https://github.com/manga-download/hakuneko/assets/10671518/638640bb-592d-4d14-8dd7-115c00e72102)

**Comment by Tmp341** [comment]
That's weird. I couldn't connect to .io domain via browser. Thought they've changed domain. After your comment, tried with GoodbyeDPI, and it worked. Thanks.

**Comment by MikeZeDev** [comment]
You filled the ticket and answered that it load in browser when it doesnt.  Please read forms properly. If you cant access the website outside haku ofc haku wont work its just a browser :p

**Comment by Tmp341** [comment]
> You filled the ticket and answered that it load in browser when it doesnt. Please read forms properly. If you cant access the website outside haku ofc haku wont work its just a browser :p

It was loading as .com, not as .io. Checked last commit for the connector, so i thought it was changed at some point and nobody reported/figured it out.

**Comment by MikeZeDev** [comment]
Nobody reported it because .io works, hakuneko uses .io, and the problem was probably ISP censorship on your end :D
Anyway, nice to see you figured it out 👍
