### ISSUE TITLE
[Feature] Built-in Benefit to Increase Performance of Image Load Times

### ISSUE THREAD

**Issue by galpt** [manga-download/hakuneko#6818]
**Is your feature request related to a problem? Please describe.**
I'm opening this so anyone can discuss about improving image load times for potentially any manga websites as long as the image is cache-able.

Also I've tried to search if there's a similar issue like this, but there's none. So I guess this will be one of a kind.

**Describe the solution you'd like**
Implement a caching proxy like [wsrv.nl](https://wsrv.nl/) or [0ms mirrors](https://0ms.dev/mirrors/) to improve image load times performance.

This suggestion will:
1. Make image load times more predictable for most users;
2. Give users the ability to compare it to wsrv.nl;
3. Reducing server load for the manga websites when users want to download certain manga chapters.

The code implementation should be quite simple since the logic is only about adding a prefix (i.e. `https://0ms.dev/mirrors/`) to the manga image URLs.

When users want to download certain manga chapters, instead of downloading from the original image URLs, the app should download the images from the caching proxy URL, so multiple downloads of the same manga chapters won't end up being slow or burdening the manga websites, at least for the next 24 hours.

> [!NOTE]
>
> This is a caching proxy, not the typical HTTP(S) proxy for bypassing censorship or something like that.
It is affecting the performance & reliability when users want to load manga images without the need to save them offline.

**Describe alternatives you've considered**
Implement either [wsrv.nl](https://wsrv.nl/) or [0ms mirrors](https://0ms.dev/mirrors/), but 0ms mirrors is what I think better since it doesn't modify the original images, so the Hakuneko app will be the one to decide whether it needs to convert the downloaded images or not.

**Context (please complete the following information):**
 - Release v6.1.7

**Additional context**
To give everyone an idea about how useful is this if it gets implemented, we can compare the manga image URL with & without using the [caching proxy](https://0ms.dev/mirrors/) I mentioned above.

### Scenario: Reading manga images without using image proxy

_Figure 1. The image below shows us that loading all the manga images will be slow for some users, without using any image proxy at all._

![benchmark without 0ms caching proxy](https://github.com/KotatsuApp/Kotatsu/assets/34034590/d6499a12-ba69-4844-9232-3326e6bdef46)

### Comparison: Measuring image load time for a specific manga image URL

_Figure 2. The below image shows us the load time for [specific image URL](https://images2.imgbox.com/9d/09/Dsgt8CzJ_o.jpg), without using any image proxy._

![benchmark without 0ms caching proxy - first try](https://github.com/KotatsuApp/Kotatsu/assets/34034590/604569d4-cb0d-4cb3-8e94-b89043a7cbbf)

_Figure 3. The below image shows us the load time for [specific image URL](https://images2.imgbox.com/9d/09/Dsgt8CzJ_o.jpg), after using [0ms caching proxy](https://0ms.dev/mirrors/images2.imgbox.com/9d/09/Dsgt8CzJ_o.jpg)._

![benchmark with 0ms caching proxy - second try](https://github.com/KotatsuApp/Kotatsu/assets/34034590/ab90851a-288f-4bd1-a8a2-148dcc2e286e)

### How to Use: Image URL structure

_Figure 4. The image URL without using the caching proxy._

![benchmark without 0ms caching proxy - real url](https://github.com/KotatsuApp/Kotatsu/assets/34034590/a8f3b9d7-8bd5-4092-9512-829c3bd9de8c)

_Figure 5. The image URL after using the caching proxy._

![0ms caching proxy - how to use](https://github.com/KotatsuApp/Kotatsu/assets/34034590/6d72ef62-6d32-4288-a094-4696951cc191)

**Comment by galpt** [comment]
I know there's a feature for users to set proxy, but that's quite technical for any users who just want to use Hakuneko without setting up their own proxy solutions, and like mentioned above, most proxy solutions are for bypassing censorship, not caching.

Caching can happen at different levels, either on the user's machine (local), from the manga websites (remote), or even both remote & local. Supported with the above screenshots, I feel like this suggestion will make a difference, at least in performance.

A checkbox that can be toggled on/off and _"it just works"_ is what this suggestion is all about.

**Comment by Sheepux** [comment]
You can provide a caching proxy if you want to, but that would be unrelated to hakuneko.
Hakuneko won't provide a global caching service (it hosts content, hakuneko is not a content provider, it's a web scrapper for offline reading).
Yes it's slower, but we won't cross that line.

Edit: didn't see that it's a global service and not a self hosted solution.
Using their service would make it easy for website to ban HN users., and in such case having to tell users to disable it would be a pain.
I still think putting HN the responsibility to provide a cache service would cross the line a bit. I also don't think that many users download the same thing within 24h, the probability is low (we don't have THAT much users)

**Comment by galpt** [comment]
Very unfortunate but I get your point. Closing this issue.

**Comment by Sheepux** [comment]
Thanks for the suggestion tho (i don't know if you saw the edited message). I'll ping the other contributors about this for second opinions.
Also i don't know if the modified HTTP request that we do would be lost in the process

**Comment by galpt** [comment]
To add to my previous suggestion, it's inspired from Kotatsu, which is clearly not providing any content, just a manga reader with the ability to download them for offline read  (sound similar? both apps can do this).
https://github.com/KotatsuApp/Kotatsu/issues/357
This could give the idea of not providing the "content" but only the features.
A small footnote in the app telling user to turn it off just in case something breaks is mostly enough to prevent unneccessary questions.

I understand if a project already has crystal clear milestones then it'll be harder to even consider adding new features.
So I don't mind if this got rejected.

Again, this issue was just a suggestion and I did mention at the very top that I'm also up for a discussion, in case anybody's really into this kind of performance improvement.

**Comment by galpt** [comment]
> Thanks for the suggestion tho (i don't know if you saw the edited message). I'll ping the other contributors about this for second opinions.

Don't worry, I saw it even when the message got edited.
Discussing with other contributors is good, maybe some of them have experiences in this kind of topic and can give different opinions.

I just feel like closing the issue for now.
Anybody can just reopen it again later, or ask for it to be reopened if needed.

> Also i don't know if the modified HTTP request that we do would be lost in the process

As for that, I believe the contributors can just try this themselves (if they have the time ofc) since how it works is only by adding a prefix to the manga image URL (already explained above). So there shouldn't be a lot of code changes (compared to adding support for new manga websites).

If you can get the image URLs from any manga website, then those images will work out-of-the-box with the caching proxy, most of the time.
