### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by Homer68** [manga-download/hakuneko#6819]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Impossible to refresh https://www.japscan.ws

Hakuneko can't fetch any manga series and chapter list, also clipboard not working.
The new website is https://www.japscan.lol

### To Reproduce

1. Name of connector  https://www.japscan.ws      (French)
2. Name of manga (if connector update is working) All
3. Name of chapter (if manga update is working) All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Search before asking, use a proper title, unsolvable, Duplicate, etc... https://github.com/manga-download/hakuneko/issues/4657
