### ISSUE TITLE
[Site Request] Mangadex

### ISSUE THREAD

**Issue by n3nuzzzz** [manga-download/hakuneko#6820]
**Website name**
Mangadex

**Website urls (examples below)**
- Site: https://mangadex.org
- Manga List: https://mangadex.org/titles
- Manga example: https://mangadex.org/title/34b14264-f96b-422b-8244-0329a895df90/raise-wa-tanin-ga-ii
- Chapter online viewer example: https://mangadex.org/chapter/9483f290-f7cb-417f-8c3f-75355919ca17

**Languages**
Italian, Mexican, English, Russian, Chinese, Japanese, Spanish, Portuguese

**Comment by MikeZeDev** [comment]
Support for MD was added 5 years ago and its still working. 👀 https://github.com/manga-download/hakuneko/commit/4d0af6153b291747f862b9833b2ce09e6c91ed40#diff-423936f1717e0f23dff9ab0f9ce85f20dc715154854b67709a326d0358eb1095
