### ISSUE TITLE
[ReadComicOnline] Downloads stop after completing CAPTCHA

### ISSUE THREAD

**Issue by ftfckr** [manga-download/hakuneko#6821]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
After completing a CAPTCHA for ReadComicOnline, the download list gets stuck.

**To Reproduce**
Unclear

**Expected behavior**
Downloads do not get stuck.  Alternatively, some control exists to resume downloads.

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version nightly

**Additional context**
From the F12 console:
`remote.js:224 
Uncaught Error: Object has been destroyed
    at electron/js2c/browser_init.js:6863
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6706)
    at IpcMainImpl.emit (events.js:210)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930)
    at WebContents.emit (events.js:210)
exception @ remote.js:224
metaToValue @ remote.js:228
descriptor.get @ remote.js:147
_fetchUICleanup @ Request.mjs:411
(anonymous) @ Request.mjs:366
setTimeout (async)
(anonymous) @ Request.mjs:365
fetchUI @ Request.mjs:346
_getPages @ KissComic.mjs:67
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:111
Promise.then (async)
getPages @ Chapter.mjs:109
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49`

**Comment by MikeZeDev** [comment]
As its hard to reproduce the captcha, its harder to reproduce this :/
Also their download servers are kinda unstable and the console error you pasted could be unrelated.

They even activate cloudflare sometimes https://github.com/manga-download/hakuneko/issues/6609

It could be interesting to see the other errors, This one often pops without hindering downloads.

**Comment by ftfckr** [comment]
Looking at the stack trace, might that be in Electron itself?  RCO has some particularly obnoxious popups, so wondering whether something like closing one of those might trigger it.

**Comment by MikeZeDev** [comment]
> Looking at the stack trace, might that be in Electron itself? RCO has some particularly obnoxious popups, so wondering whether something like closing one of those might trigger it.

Its true that nasty ads sometimes interfere with page loading. We use an host blacklist system but obviously its not perfect.
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/engine/Blacklist.mjs

**Comment by MikeZeDev** [comment]
Closed for inactivity
