### ISSUE TITLE
[Feature] Provide download controls to stop/start download list

### ISSUE THREAD

**Issue by ftfckr** [manga-download/hakuneko#6822]
**Is your feature request related to a problem? Please describe.**
See #6821.  When this happens, there is seemingly no way to resume the downloads, and the app must be restarted, losing the download list in the process.

**Describe the solution you'd like**
Controls to start/stop the download list.  This would prove useful not only for restarting stuck downloads, but for manually starting and stopping the queue more generally.

One possible form is a start/stop toggle button next to the show/hide download list toggle.

**Context (please complete the following information):**
 - Your current HakuNeko Version: nightly

**Comment by MikeZeDev** [comment]
Wont be done in Hakuneko. Duplicate https://github.com/manga-download/hakuneko/issues/8

Maybe be done in hakuneko successor, Haruneko.
