### ISSUE TITLE
[Feature] Save/restore download list

### ISSUE THREAD

**Issue by ftfckr** [manga-download/hakuneko#6823]
**Is your feature request related to a problem? Please describe.**
See #6821.  When this happens, there is seemingly no way to resume the downloads, and the app must be restarted, losing the download list in the process.

**Describe the solution you'd like**
The download list should be saved, and then restored on app startup.  Triggers for save could include:
* Downloads being added
* Downloads being completed
* Exiting the app
* Periodically on a timer

This could be gated as an option, but it seems like sensible default behaviour to have the option enabled by default.

**Context (please complete the following information):**
 - Your current HakuNeko Version: nightly

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/1163
Planned in Haruneko.
