### ISSUE TITLE
[<Manhuaplus] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#6824]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Also no chapters showing. I think the site may have been reformatted. It looks different and stopped working yesterday or day before when the changes were made.

<img width="1117" alt="Screenshot 2024-02-25 at 9 59 41 AM" src="https://github.com/manga-download/hakuneko/assets/70929406/bec58aa9-e173-4c8d-b78f-659b924a1421">
<img width="1420" alt="Screenshot 2024-02-25 at 10 00 22 AM" src="https://github.com/manga-download/hakuneko/assets/70929406/6c548601-1e3c-4fc3-8cd4-0870308242aa">
<img width="1065" alt="Screenshot 2024-02-25 at 10 09 44 AM" src="https://github.com/manga-download/hakuneko/assets/70929406/eda9c572-4222-4c7b-a5bc-903f8a9e8085">
<img width="1115" alt="Screenshot 2024-02-25 at 10 14 59 AM" src="https://github.com/manga-download/hakuneko/assets/70929406/4b0f9913-7d4a-4da3-a631-2144b7370416">

Thanks!

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Perhaps its the .com/.org problem

**Comment by MikeZeDev** [comment]
Website itself is fucked up look what i got 
![image](https://github.com/manga-download/hakuneko/assets/10671518/a7285fad-3ea0-43bd-81b6-a7883a31b9a5)

**Comment by tsentered** [comment]
Anything is possible, but from what I saw it only stopped working yesterday. It’s awesome that you guys changed it to Org by the way, thank you.Sent from my iPhoneOn Feb 25, 2024, at 10:59 AM, MikeZeDev ***@***.***> wrote:﻿
Perhaps its the .com/.org problem

**Comment by tsentered** [comment]
That’s really weird though I haven’t gotten any of the cloud fair stuff. The website definitely looks different than it did a week ago.They make too many changes. Either way thank you for even checking.Sent from my iPhoneOn Feb 25, 2024, at 11:05 AM, Alex Sanders ***@***.***> wrote:﻿Anything is possible, but from what I saw it only stopped working yesterday. It’s awesome that you guys changed it to Org by the way, thank you.Sent from my iPhoneOn Feb 25, 2024, at 10:59 AM, MikeZeDev ***@***.***> wrote:﻿
Perhaps its the .com/.org problem

**Comment by MikeZeDev** [comment]
OK they changed template, thats  no more madara, i am on it

Please avoid answering by email it gives an ugly blob of text. Use the website

**Comment by tsentered** [comment]
Awesome, thank you. What would be the best way for me to learn the stuff?Sent from my iPhoneOn Feb 25, 2024, at 11:26 AM, MikeZeDev ***@***.***> wrote:﻿
OK they changed template, thats  no more madara, i am on it
Please avoid answering by email it gives  and ugly blob of text. Use the website
