### ISSUE TITLE
[Bug] HakuNeko will not launch on Fedora - W/ Fix

### ISSUE THREAD

**Issue by ItzDabbzz** [manga-download/hakuneko#6826]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**
Found out a interesting bug today. On Fedora you are required to add `--no-sandbox` to the end of the electron start command in order to to get the ui to launch.

--no-sandbox

**To Reproduce**
1. Download from FlatPak
2. Install
3. Launch
4. Instantly crash no error.
5. Download source
6. Build source & Launch
7. Error received!
`[551429:0226/083701.910209:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.`

**Expected behavior**

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/45545996/6903ee3f-fab2-462c-9763-8f0c4539e884)
![image](https://github.com/manga-download/hakuneko/assets/45545996/f424c85b-6768-4caf-ba3e-fdc4372c9edd)

**Context (please complete the following information):**
 - OS: Linux Fedora
 - HakuNeko Version Current Source

**Additional context**
Fixed with  `--no-sandbox` at the end of electron command
`
    "start:dev": "electron . --update-url=DISABLED --cache-directory=./src/web --disable-http-cache --no-sandbox",
`

**Comment by MikeZeDev** [comment]
Related : https://old.reddit.com/r/Fedora/comments/qm3qm1/fedora_35_most_electron_apps_are_not_starting/

Thanks for the heads up and the workaround.

I bet it could be fixed by updating Electron (https://github.com/Kong/insomnia/issues/4332 ) , and its something we wont do because its too much a hassle and we are working on Haruneko.

Probably gonna close this as "wont fix"

**Comment by Sheepux** [comment]
it's a bit more complex as it seems to be a chrome bugs that also exists in latest nwjs and electron.
no sandbox workaround has been given for a while on haku ;) https://github.com/manga-download/hakuneko/issues/6455
More details in the haruneko's deeper analysis https://github.com/manga-download/haruneko/issues/514
