### ISSUE TITLE
[<MangaDex>] Connector not working

### ISSUE THREAD

**Issue by MelissaECosta** [manga-download/hakuneko#6829]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

When attempting to load the manga list for MangaDex, receive the following error message:
Failed to update manga list for MangaDex

Failed to receive content from 
...//api.mangadex.org/manga?limit=100&...
(statu: 400)

### To Reproduce

1. Choose the MangaDex connector from the list
2. Now click the synchronize button
3. While attempting to load the list of manga you'll receive a status 400 error in a popup window, see below.

Error message:
Failed to update manga list for MangaDex

Failed to receive content from 
...//api.mangadex.org/manga?limit=100&...
(statu: 400)

**Comment by MikeZeDev** [comment]
This error message means you didnt used nightly like you said. Please read and follow instructions before randomly checking boxes.
Nightly build would have worked for manga list even when Mangadex was down yesterday, since nightly use a another servers as cache.
