### ISSUE TITLE
Mangago chapters won't download

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#683]
> **From:** HakuNeko User

Two out of the entire manga will not download no matter what. http://www.mangago.me/read-manga/yuuutsu_na_asa/

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Which two?

**Comment by 27136773** [comment]
Both chapters contain broken images and therefore the chapter cannot be downloaded...
This cannot be fixed in HakuNeko, report the broken images to MangaGo website owner
