### ISSUE TITLE
[< Lezhin (English) >] Connector not working

### ISSUE THREAD

**Issue by abyss3658** [manga-download/hakuneko#6830]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

On Monday it was working fine and i could download chapters, but today when I  Log Into my accounts for Lezhin.. and copy past the URL... it was only spinning and after 2-3 minutes it stopped spinning and just go back to how it was before! 
The manga and chapters was not showing and URL did not even load
![Snimka zaslona 2024-02-27 153923](https://github.com/manga-download/hakuneko/assets/161481926/e2d391e1-fb1b-4550-bd55-b53d1ba11009)
![Snimka zaslona 2024-02-27 154013](https://github.com/manga-download/hakuneko/assets/161481926/2f57bfc7-382b-4e2b-a3d4-fc02e58d0a3e)

### To Reproduce

1. Name of connector https://www.lezhinus.com/en
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by Arekkusu1998** [comment]
I confirm everything @abyss3658 wrote: same timing, same responses to the baseline questionnaire, same error. I would also like to add that not even work the connectors for:

- < Lezhin **(Korean)** > (https://www.lezhin.com/ko)
- < Lezhin **(Japanese)** > (https://www.lezhin.jp/)
- < Batoto (by AnyACG) > (https://battwo.com/)
