### ISSUE TITLE
[Site Request] stellarsaber

### ISSUE THREAD

**Issue by Omar7Emad** [manga-download/hakuneko#6831]
-Name of the website
Stellar Saber

-Website urls

   Site:
https://stellarsaber.pro/
   Manga List:
https://stellarsaber.pro/%d8%a7%d9%84%d9%85%d8%b4%d8%a7%d8%b1%d9%8a%d8%b9/
   Manga Example:
https://stellarsaber.pro/manga/vagabond/
   Chapter online viewer example:
https://stellarsaber.pro/vagabond-%d8%a7%d9%84%d9%81%d8%b5%d9%84-1/

-Languages
Arabic

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/6190bfb4-d81d-47ed-a1cc-cf88046cd36d)

**Comment by Omar7Emad** [comment]
i'm sorry, they changed their website to a new one.

**Comment by MikeZeDev** [comment]
If website doesnt exists in haku , there is a ticket  and changed url, you can mention the url change in the opened ticket.
I wont be done in hakuneko by someone of the team anyway.

If you want the url to be changed in Haruneko make a ticket in Haruneko github.

Again, no need for duplicate ticket ^^
