### ISSUE TITLE
[Site Request] Mangadistrict

### ISSUE THREAD

**Issue by Nyaa27** [manga-download/hakuneko#6832]
**Name of the website**
mangadistrict
**Website urls (examples below)**
- Site: https://mangadistrict.com/
- Manga List: https://mangadistrict.com/read-scan/
- Manga example: https://mangadistrict.com/read-scan/wreck-my-bias/
- Chapter online viewer example: https://mangadistrict.com/read-scan/wreck-my-bias/chapter-1/

**Languages**
List of languages supported by the website
English
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Search before !
Duplicate https://github.com/manga-download/hakuneko/issues/5515
