### ISSUE TITLE
[Site Request] arabtoons.net in hakuneku

### ISSUE THREAD

**Issue by dbzkato** [manga-download/hakuneko#6833]
**Name of the website**
arabtoons.net

**Website urls (arabtoons.net)**
- Site: https://arabtoons.net/
- Manga List: https://arabtoons.net/مانجا/
- Manga example: https://arabtoons.net/manga/change-wife/
- Chapter online viewer example: https://arabtoons.net/manga/change-wife/الفصل-25/

**Languages**
arabic

**Website relationship*
no
**Additional details**
manha

**Comment by MikeZeDev** [comment]
Third time the charm today : please search before asking .

![image](https://github.com/manga-download/hakuneko/assets/10671518/d90eb260-9b04-459b-8374-75933f04cfa1)

**Comment by dbzkato** [comment]
In hakuneku my friend not haru
Becuse hakuneku is stable and there's download chapter as pdf

**Comment by MikeZeDev** [comment]
You opened an issue when there is already an opened issue. Its called a duplicate, it has nothing to do with haru.
