### ISSUE TITLE
[<ComicK>] Connector not working

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6836]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The Manga list is not refreshing

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/123682535/d27e4944-a7b8-4ba7-b6d3-c4f79712df8a)

**Comment by MikeZeDev** [comment]
Cant reproduce. Make sure you properly followed instructions in tickets to ensure the problem isnt on your end.
Press F12 Check console errors (only the caused when trying to update)

**Comment by KeePach** [comment]
same problem, can't use this connector, when using f12 to see errors, it say's " GET https://comick.io/v1.0/search 404  Connector.mjs:460"

**Comment by MikeZeDev** [comment]
Dont hijack a closed ticket
