### ISSUE TITLE
[https://web.mangahot.jp/] Manga Hot

### ISSUE THREAD

**Issue by storyteller24** [manga-download/hakuneko#6838]
**Name of the website**
Manga Hot

**Website urls (examples below)**
- Site: https://web.mangahot.jp/
- Manga example: https://web.mangahot.jp/works/detail.php?work_code=z_R0226&utm_source=mangahotjp
- Chapter online viewer example: https://web.mangahot.jp/works/view.php?story_id=31491&utm_source=mangahotjp

**Languages**
Japanese

**Note
Comic Zenon's Monthly Comic Magazines

**Comment by MikeZeDev** [comment]
Another day, another bunch of duplicate requests.

https://github.com/manga-download/hakuneko/issues/6255
