### ISSUE TITLE
Add Lhnovels

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#684]
[Lhnovels](https://lhnovels.net/ )

**Comment by 27136773** [comment]
Seems to be FlatManga template (like RawLH and so on ...)

**Comment by XenonR** [comment]
Cloudflare: 523 - Origin is unreachable

**Comment by XenonR** [comment]
Cloudflare: 522 - Connection timed out

**Comment by 27136773** [comment]
Still not reachable (522 Error) => closing ticket
