### ISSUE TITLE
Customize List Widths in the UI

### ISSUE THREAD

**Issue by eggen1231** [manga-download/hakuneko#6840]
**Is your feature request related to a problem? Please describe.**
Some titles are too long to read in full, or I can’t see the volume or chapter numbers. However, if I could customize the UI by adjusting the width of the Manga List and Chapter List, the problem would be solved.

**Describe the solution you'd like**
1. Adjust Width with Mouse:
Click and drag the column separator to make the Manga List or Chapter Lister column narrower or wider according to their preference.
2. Lock Settings:
Implement a button that allows users to lock in their customized column width settings. This way, they can maintain their preferred layout.

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Additional context**
Now:
![image](https://github.com/manga-download/hakuneko/assets/161766497/fcdcf49b-4f12-4dd6-af31-2933e9824d98)

With changed widht for the lists: 
![image](https://github.com/manga-download/hakuneko/assets/161766497/dd1839d2-02b7-4136-aa5c-ad05fb8ae99c)

**Comment by MikeZeDev** [comment]
@Sheepux  Perhaps in Haruneko? 

Wont be done in Hakuneko anyway

**Comment by Sheepux** [comment]
1. Done in haru
2. Not persistent yet but could be a thing

**Comment by Sheepux** [comment]
see also: https://github.com/manga-download/haruneko/issues/313
