### ISSUE TITLE
[ScanManga] Connector not working

### ISSUE THREAD

**Issue by MatthisFauvet** [manga-download/hakuneko#6841]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

# Error on *ScanManga* website connector

Hello everyone, I just encounter a problem when i tried to connect to ScanManga website from Hakuneko website list.

Websites url : 
- Site : https://www.scan-manga.com/?home
- Manga exemple (that i tried) : https://www.scan-manga.com/7468/Ao-no-Hako.html

## Issue

When i selected website and  refreshed manga list, this error apperd 

![image](https://github.com/manga-download/hakuneko/assets/122635096/fb7565c3-bd7a-4cf7-a228-70ce67bee7f0)

Thanks yall for your help

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/3460
