### ISSUE TITLE
this code working fine and manga list coming but no chapter list some help 

### ISSUE THREAD

**Issue by dbzkato** [manga-download/hakuneko#6843]
this code working fine and manga list coming but no chapter list ...some help  please i know you are busy but i.m trying and thanks                                                                                                         
--------------------------------------------------------------------------------------------

import WordPressMadara from './templates/WordPressMadara.mjs';

export default class Arabtoons extends WordPressMadara {

    constructor() {
        super();
        super.id = 'arabtoons';
        super.label = 'arabtoons';
        this.tags = [ 'manha', 'arabic' ];
        this.url = 'https://arabtoons.net/';
    }

**Comment by MikeZeDev** [comment]
Make a Pull Request, dont open an issue for that

Plus : i already gave you the answer
