### ISSUE TITLE
[Feature] Allow resizing of manga list and chapter list

### ISSUE THREAD

**Issue by j-o-e-s** [manga-download/hakuneko#6845]
Would it be possible to enable resizing of the manga, chapter, and download lists? Most manga titles are too long to fit in the list as are the chapter titles if Vol & Ch #s are included. The download list shows only a few downloads at a time.

**Describe the solution you'd like**
If possible, would really like if the column widths could be resized, similiar to other OS applications where the vertical border can be clicked and dragged to resize.

**Describe alternatives you've considered**
It would also work if the manga & chapter lists were horizontal on the left size instead of vertical. It would allow for far more text to be displayed. Or, a setting in the menu that allows for specifying the width.

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7

**Additional context**
Setting the width style to 30em for both "hakuneko-mangas" and "hakuneko-chapters" tags works. Adding a height tag to style .show for "hakuneko-jobs"/"div class="list show"" with 200px works.

**Comment by MikeZeDev** [comment]
It has been asked yesterday so, same answer https://github.com/manga-download/hakuneko/issues/6840
