### ISSUE TITLE
[Feature] Add server icon to manga list

### ISSUE THREAD

**Issue by j-o-e-s** [manga-download/hakuneko#6846]
**Is your feature request related to a problem? Please describe.**
Is it possible to put the server icon as a column in the manga list? Its frustrating trying to figure out which servers a manga belongs too without having to open the download directory and hunt it down that way.

**Describe the solution you'd like**
As the first column in the manga list (left of text), the server icon should be displayed. Please use the same one in the bookmarks list if possible.

**Describe alternatives you've considered**
Opening the download folder and searching for the manga, then looking at the parent folder to determine which server it resides on.

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.1.7

**Additional context**
If possible, it would be a nice addition to be able to right-click the icon and have the server manga list be loaded instead of going to bookmarks, finding the server, then clicking on it.

**Comment by MikeZeDev** [comment]
Done in haruneko. Not scheduled in Hakuneko
