### ISSUE TITLE
[ManHuaGui] Connector not working

### ISSUE THREAD

**Issue by realabertian** [manga-download/hakuneko#6850]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Any manhua just can't show the chapter list

### To Reproduce

1. ManhuaGui
2. https://www.manhuagui.com/comic/32450/
3. click this mangua, the chapter list is not update
4. No any error log

open the site in chrome is just ok
![image](https://github.com/manga-download/hakuneko/assets/64790396/fd07f8d0-2247-4dc4-bf1c-1967d52a869f)

**Comment by MikeZeDev** [comment]
Cant reproduce the  problem

![image](https://github.com/manga-download/hakuneko/assets/10671518/e56db39f-d46d-4218-aba6-c6d0699eccaf)

Cant you access to the website in read browser? Disable you antivirus? you really tried nightly?

**Comment by realabertian** [comment]
> Cant reproduce the problem
> 
> ![image](https://private-user-images.githubusercontent.com/10671518/309541378-e56db39f-d46d-4218-aba6-c6d0699eccaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjU0OTcsIm5iZiI6MTcwOTQ2NTE5NywicGF0aCI6Ii8xMDY3MTUxOC8zMDk1NDEzNzgtZTU2ZGIzOWYtZDQ2ZC00MjE4LWFiYTYtYzZkMDY5OWVjY2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDExMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiODhhZTI3ODUxYzE4ZmQyMTc0ZDMyMTFjNmZkYmUyZDA0YzM1ODk0MzQ3M2M3MjYxMTBjODA5YWEwZDVkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cKEL4CSvXjLNogWJScWi7zBIuSKM5Arxfi4ugHhIy7Q)
> 
> Cant you access to the website in read browser? Disable you antivirus? you really tried nightly?

it's seem the app has cache problem

**Comment by realabertian** [comment]
I'm trying the steps to reproduce the cache problem

**Comment by realabertian** [comment]
The root cause is that if you refresh continuously without logging in, you will be blocked by the website. It only takes a few refreshes for my IP to trigger. The tolerance of the website may be related to your IP address region.

The blocking occurs in Get Manga Chapter List

**Comment by MikeZeDev** [comment]
Well then there is nothing we can do 🤷 . Sorry

**Comment by realabertian** [comment]
> Well then there is nothing we can do 🤷 . Sorry

I'm trying to add some header to the chatper request, but the code did not take effect
ManHuaGui:
`
export default class ManHuaGui extends SinMH {

    constructor() {
        super();
        super.id = 'manhuagui';
        super.label = '看漫画 (ManHuaGui)';
        this.tags = [ 'webtoon', 'chinese' ];
        this.url = 'https://www.manhuagui.com';
        this.requestOptions.headers.set('cookie', 'some cookie content');
        this.requestOptions.headers.set('authority', 'www.manhuagui.com');
        this.requestOptions.headers.set('cache-control', 'max-age=0');
        this.requestOptions.headers.set('accept-language', 'en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7,ja-JP;q=0.6,ja;q=0.5,zh-CN;q=0.4');
        this.requestOptions.headers.set('accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7');

`

I tried to break the point to view the header of the request object constructed during actual execution, and found that the headers I configured were not filled in. I don't know why this happened.

Use the curl command in the terminal with these headers to bypass website blocking. it works.

**Comment by realabertian** [comment]
> > Well then there is nothing we can do 🤷 . Sorry
> 
> I'm trying to add some header to the chatper request, but the code did not take effect ManHuaGui: ` export default class ManHuaGui extends SinMH {
> 
> ```
> constructor() {
>     super();
>     super.id = 'manhuagui';
>     super.label = '看漫画 (ManHuaGui)';
>     this.tags = [ 'webtoon', 'chinese' ];
>     this.url = 'https://www.manhuagui.com';
>     this.requestOptions.headers.set('cookie', 'some cookie content');
>     this.requestOptions.headers.set('authority', 'www.manhuagui.com');
>     this.requestOptions.headers.set('cache-control', 'max-age=0');
>     this.requestOptions.headers.set('accept-language', 'en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7,ja-JP;q=0.6,ja;q=0.5,zh-CN;q=0.4');
>     this.requestOptions.headers.set('accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7');
> ```
> 
> `
> 
> I tried to break the point to view the header of the request object constructed during actual execution, and found that the headers I configured were not filled in. I don't know why this happened.
> 
> Use the curl command in the terminal with these headers to bypass website blocking. it works.

Just add a prefix 'x-', it works @MikeZeDev  maybe we can provide a cookie input items to users to help users bypass block

**Comment by MikeZeDev** [comment]
Manually Input cookie? No, we are not gonna add something like this. Its a bad workaround, its ugly.

Moreover

>"The blocking occurs in Get Manga Chapter List"
> "it's seem the app has cache problem"

Problem? Its not a problem. Its on purpose. Once you fetch chapter list it stays cached until you close the app, to avoid doing more requests on servers. What we lack is a way to force the reload but its not a "bug" per se.

You talked about login. Are there more chapters available after login? Or you are just login for the purpose of testing their IP block? 

Anyway, its too much a hassle, most users will just use a VPN .

**Comment by realabertian** [comment]
A workaround:  just using hakuneko web browser function to open the website and login (keep your cookie info) , than any request make by hakuneko will append cookie info , which will bypass the block

**Comment by MikeZeDev** [comment]
> A workaround: just using hakuneko web browser function to open the website and login (keep your cookie info) , than any request make by hakuneko will append cookie info , which will bypass the block

Thats a good way i guess thanks for that <3
