### ISSUE TITLE
[Neox Scans] Domain change

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6858]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

hello. The images are no longer loading.

 Website: https://nexoscans.net
Manga example: https://nexoscans.net/manga/ordea-6_67_214_1-l/
Chapter online viewer example: https://nexoscans.net/manga/ordea-6_67_214_1-l/cap-99/

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Images are not loading for me even in browser.  I am afraid this is something i cant fix in that case.

Do you remember this?
![287452606-3e247272-f181-42af-af3f-4cec8faadfdb](https://github.com/manga-download/hakuneko/assets/10671518/d0d352bf-8af3-4903-b158-7359fb784ec7)

Use a website that is not fucked up for non pt-br perhaps?

**Comment by MikeZeDev** [comment]
Wait they changed domain. Maybe that the problem.

**Comment by CristianoLBR** [comment]
Hello! I think they switched domains again. Could you take a look please.

**Comment by MikeZeDev** [comment]
Makeanother ticket dont talk on a close one
