### ISSUE TITLE
[<Ares Manga>] Connector not working

### ISSUE THREAD

**Issue by SatanHere** [manga-download/hakuneko#6864]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The site domain changed from "https://aresmanga.net/" to "https://fl-ares.com/"

### To Reproduce

1. Name of connector : Ares manga
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

old templete if it help you 
Website urls (examples below)

    Site: https://aresmanga.net/
    Manga List: https://aresmanga.net/series/
    Manga example: https://fl-ares.com/series/gods-webnovel/
    Chapter online viewer example: https://fl-ares.com/gods-webnovel-chapter-31/

**Comment by MikeZeDev** [comment]
But its already changed it to aresnov.org  (in haruneko) which is see now became [manhuascarlet](https://manhuascarlet.com/) which is INDEED AresManga.

Plus, the website you linked is behind cloudflare, so it cant be used

**Comment by SatanHere** [comment]
does it gonna merge to hakuneko ? or should i start using haruneko ?

**Comment by MikeZeDev** [comment]
I wont use a domain with cloudflare , its no use, it work work.  Not In hakuneko.
Both are in haruneko now but only the one i mentioned (ManhuaScarlet) will work anyway.
