### ISSUE TITLE
[Site Request] MajorScans

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6869]
**Name of the website**
Major Scans

**Website urls (examples below)**
- Site: https://www.majorscans.com
- Manga List: https://www.majorscans.com/manga/
- Manga example: https://www.majorscans.com/manga/bad-ending-maker/
- Chapter online viewer example: https://www.majorscans.com/bad-ending-maker-bolum-1/
**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
You dont remember your own issues? https://github.com/manga-download/hakuneko/issues/6232
