### ISSUE TITLE
[Site Request] FleksyScans

### ISSUE THREAD

**Issue by xavimaa** [manga-download/hakuneko#6874]
**Name of the website**
FleksyScans

**Website urls (examples below)**
- Site: https://flexscans.com/
- Manga List: https://flexscans.com/manga
- Manga example: https://flexscans.com/manga/troublesome-sister
- Chapter online viewer example: https://flexscans.com/manga/troublesome-sister/76

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
The site looks like toonily.me and mangabuddy.com
Maybe **MadTheme**?

**Comment by MikeZeDev** [comment]
Nah its custom made, or a template i dont recognize.

**Comment by MikeZeDev** [comment]
FuzzyDoodle 🍜

**Comment by MikeZeDev** [comment]
Website was DMCAed
