### ISSUE TITLE
[Site change] comickiba Became ManhuaGold

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6875]
**ManhuaGold**
Manhuagold

**Website urls (examples below)**
- Site: https://manhuagold.top/
- Manga List: https://manhuagold.top/filter
- Manga example: https://manhuagold.top/manga/i-am-the-fated-villain
- Chapter online viewer example: https://manhuagold.top/manga/i-am-the-fated-villain/chapter-139

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Changed issue type, cause its an "existing website" technically. They rebranded.
