### ISSUE TITLE
[<Apkomik>] wrong input link web

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#6879]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

![image](https://github.com/manga-download/hakuneko/assets/112748173/d9adbb63-fb14-4146-9494-2f3db4ae1319)
![image](https://github.com/manga-download/hakuneko/assets/112748173/ed954683-3afe-4c1e-911b-92baef1e06bb)
![image](https://github.com/manga-download/hakuneko/assets/112748173/56a743c9-1e59-4b92-bbc6-94eab16a11aa)
wrong input link website https://apkomic.cc/  > https://apkomik.cc/ correct

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
🤦

**Comment by MikeZeDev** [comment]
Well, this website is cloudflared, it no use fixing the url anyway
