### ISSUE TITLE
[<Sirenkomik>] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#6880]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

![image](https://github.com/manga-download/hakuneko/assets/112748173/483eb47c-0af8-4341-8e5b-47282f8b1e78)
ccant load chapter

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Electron shit hit the fan again 🤷 
![image](https://github.com/manga-download/hakuneko/assets/10671518/c45b4308-0390-4079-911c-ee76f4634492)

![image](https://github.com/manga-download/hakuneko/assets/10671518/6ed66517-fcf7-4b58-8e24-e68f1f703b3e)

Not sure its fixable. Its not the first time for this website i bet its crappy ads again? There a plenty of id website in Hakuneko, maybe you should use another one and ditch this one? 🤷 

Its painful for you and for us too. Thanks for reporting anyway 👍

**Comment by MikeZeDev** [comment]
OK so i made a workaround, but on this website, 90% of the chapters i open in my real browser end up empty (404 errors).
Pictures are just missing on the (maaaaaaaany) CDN they use. Nothing we can do without magic.

![image](https://github.com/manga-download/hakuneko/assets/10671518/b70cc78f-3317-4346-b646-230d9dcc4629)
![image](https://github.com/manga-download/hakuneko/assets/10671518/62b0f156-b156-432d-baa3-590788ea6a15)
![image](https://github.com/manga-download/hakuneko/assets/10671518/38dcc0f7-7515-4fc9-9c4e-c4e73cebe68e)

If you cant download a chapter in the future make sure its working on the website before. No need to report an issue if the chapter is broken on website too.

**Comment by MikeZeDev** [comment]
Also, there is no simple way to remove the ads they put in chapters pictures. Url are similar and random
![image](https://github.com/manga-download/hakuneko/assets/10671518/632cd6ee-715a-4d9d-bba1-7b95a05af88c)
