### ISSUE TITLE
[<Manwha Freak>] Connector not working

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#6883]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

can't view chapter

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/manga-download/hakuneko/assets/123682535/36cb5345-84cb-4598-992b-5a924963136b)
![image](https://github.com/manga-download/hakuneko/assets/123682535/34c51e77-9f94-4640-ad83-701f50ad1afd)
![image](https://github.com/manga-download/hakuneko/assets/123682535/5f6d3c1a-4061-4264-b944-c66adc9ad0b4)

**Comment by MikeZeDev** [comment]
* None of the errors and warning are related to the website.
* I cant reproduce the problem
![image](https://github.com/manga-download/hakuneko/assets/10671518/31af6d2a-2843-4a58-8028-5e63d963badc)

Please try to reproduce the problem and them paste the errors that appears. not those that are already here when you launch the program.

**Comment by MikeZeDev** [comment]
Nevermind, its probably the thing fixed [a week ago](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/ManhwaFreak.mjs) and you didnt use nightly like instructed. Did i waste my time?
