### ISSUE TITLE
[OmegaScans] Connector not working

### ISSUE THREAD

**Issue by xavimaa** [manga-download/hakuneko#6892]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hello, the connector doesn't work because the site has been updated and the interface has been changed.

### To Reproduce

1. Name of connector : OmegaScans
2. Name of manga (if connector update is working) : all
3. Name of chapter (if manga update is working) : all
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
There is a template update :/ Need to fix it, Omegascans, Templescans, Perfscans
