### ISSUE TITLE
[Site Request] https://lermanga.org

### ISSUE THREAD

**Issue by legendarysnake0** [manga-download/hakuneko#6903]
**Name of the website**
Lermanga 

**Website urls (examples below)**
- Site: https://lermanga.org/
- Manga List: https://lermanga.org/mangas/
- Manga example: https://lermanga.org/mangas/naruto/
- Chapter online viewer example: https://lermanga.org/capitulos/naruto-capitulo-699/

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
none

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/6347
