### ISSUE TITLE
new website MangaFire

### ISSUE THREAD

**Issue by wolfsarebest** [manga-download/hakuneko#6907]
**Name of the website**
MangaFire

**Website urls (examples below)**
- Site: https://mangafire.to/home

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Excuse me ? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/1d4fc1f2-a0d5-4bd1-8d77-986ec0d1b634)

Website is supported since march 2023, are you using a time machine?

**Comment by wolfsarebest** [comment]
my bad, I found it. However, it does take a lot of time to load, is there
anything you can do? Also when I download some manga as PDF the pages are
uneven in size, is there a way of solving this problem? I included an
image of this problem below.

Thank you.

**Comment by MikeZeDev** [comment]
> it does take a lot of time to load

We cant fix your internet or their server 😢

> some manga as PDF the pages 

 Pdf is the worst idea tbh. We cant really do anything about sizes. Download as CBZ and use an adhoc viewer.

**Comment by wolfsarebest** [comment]
Ok, I'll check it out.

Thank you.
