### ISSUE TITLE
[Not working]  GriMelek changed domain

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#6908]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The site's address has been renewed

### To Reproduce

1. Name of connector GriMelek
2. Name of manga (if connector update is working) https://grimelek.co/
3. Name of chapter (if manga update is working) https://grimelek.co/seri/please-go-home-akutsu-san-2/bolum-124/ 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Its because we need to be logged to view chapter that it wasnt done, what a silly idea...

**Comment by MikeZeDev** [comment]
Could you try changing the url yourself in Siyahmelek.mjs and see it works after you login?

**Comment by Tianzhou2** [comment]
> Could you try changing the url yourself in Siyahmelek.mjs and see it works after you login?

I don't know how to change

**Comment by MikeZeDev** [comment]
Notepad

**Comment by Tianzhou2** [comment]
> Notepad

what Notepad?

**Comment by Tianzhou2** [comment]
> Notepad

How can I change the address?

**Comment by MikeZeDev** [comment]
1) Read whatt i wrote
2) you dont need, its done  
![image](https://github.com/manga-download/hakuneko/assets/10671518/51b17491-f65b-4b6a-a3f8-5a7061b025b8)
