### ISSUE TITLE
[Mangatx] Changed domain

### ISSUE THREAD

**Issue by sakamadzudzo** [manga-download/hakuneko#6911]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Noticed their page changed so maybe that is the issue.
Mangatx no longer showing any mangas in the list

### To Reproduce

1. Mangatx

**Comment by MikeZeDev** [comment]
Domain changed
