### ISSUE TITLE
MangaArab.mjs

### ISSUE THREAD

**Issue by someoneAr** [manga-download/hakuneko#6914]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

mngaar.com is now mangaae.com

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
But it doesnt ? 
![image](https://github.com/manga-download/hakuneko/assets/10671518/44c406b0-56fa-48a6-bad3-7bdfda6483f2)

**Comment by MikeZeDev** [comment]
And it doesnt matter since both websites : 

* are Cloudflared meaning they wont work with Hakuneko
* their chapters are located on https://manga.ae which is down
