### ISSUE TITLE
slimeread

### ISSUE THREAD

**Issue by Luiz-gusmao** [manga-download/hakuneko#6917]
**Name of the website**
    slimeread

**Website urls (examples below)**
- Site: https://slimeread.com/
- Manga List: https://slimeread.com/pesquisa-obras/pesquisar
- Manga example: https://slimeread.com/manga/5602/sanken-rokku
- Chapter online viewer example: https://slimeread.com/ler/5602/cap-1

**Languages**
PT-BR

**Comment by MikeZeDev** [comment]
dont request already requested websites 

https://github.com/manga-download/hakuneko/issues/6446
