### ISSUE TITLE
[sushiscan.net] Connector not working

### ISSUE THREAD

**Issue by Gregt59** [manga-download/hakuneko#6919]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Hello, (First time posting)
I'm Trying to connect to Sushi Scans
On the APP after pressing F12 got this : 

Failed to load resource: the server responded with a status of 403
Connector.mjs:434 GET https://sushiscan.net/manga/list-mode/ 403

Trying to open the website through the app and get blocked at cloudflare's protection
Website is working correctly 

### To Reproduce

1. Sushi Scans then Sync button. (Nothing appear + Error in F12 menu ) 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Failed to load resource: the server responded with a status of 403
Connector.mjs:434 GET https://sushiscan.net/manga/list-mode/ 403

**Comment by MikeZeDev** [comment]
SEARCH . We know. cant do

https://github.com/manga-download/hakuneko/issues/5615
