### ISSUE TITLE
[Site Request] slimeread

### ISSUE THREAD

**Issue by Xlr11** [manga-download/hakuneko#6920]
**Name of the website**
slimeread

**Website urls (examples below)**
- Site: https://slimeread.com/
- Manga List: https://slimeread.com/pesquisa-obras/pesquisar
- Manga example: https://slimeread.com/manga/3585/level-1-no-saikyou-kenja-noroi-de-saikakyuu-mahou-shika-tsukaenai-kedo-kami-no-kanchigai-no-mugen-no-maryoku-o-te-ni-ire-saikyou-ni
- Chapter online viewer example: https://slimeread.com/ler/3585/cap-0

**Languages**
List of languages supported by the website: Portuguese

**Comment by MikeZeDev** [comment]
Asked plenty of times, cant do
![image](https://github.com/manga-download/hakuneko/assets/10671518/a05f5826-bba7-4fac-9892-04d27ded3e18)
