### ISSUE TITLE
[<saikaiscans.net>] Connector not working

### ISSUE THREAD

**Issue by Xlr11** [manga-download/hakuneko#6921]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Their website changed the name, before it was called: "saikaiscan", now it is "saikaiscans", maybe that's why it's not working.
When you open the link through HakuNeko, you are sent to their discord and not the website.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
You keep requesting stuff that cant be fixed  :/

![image](https://github.com/manga-download/hakuneko/assets/10671518/fb006ce2-b667-4ae2-b054-6e5e6fa25f90)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6620. Please SEARCH before losing our time
