### ISSUE TITLE
[Neox] Connector not working

### ISSUE THREAD

**Issue by CristianoLBR** [manga-download/hakuneko#6922]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

Hello! I think they switched domains again. Could you take a look please.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Mind telling us new domain in that case? :D

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/fa14b3c7-746e-41ac-a402-5c366329fc5d)

**Comment by MikeZeDev** [comment]
You said domain change but didnt provide new domain pls

**Comment by MikeZeDev** [comment]
I tested with a vpn, It Works Flawlessly.

If pictures are missing its a website problem i guess. Give precise manga and chapter name if you want this ticket to be reopened.
