### ISSUE TITLE
[MAGKAN] website change

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#6926]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Kansai team of MAG Garden has renewal their site and change viewer to Comici, also can use ComiciID for login to use site like Young Champion or Comic Ride.

### To Reproduce

1. Name of connector: MAGKAN
2. Name of manga (if connector update is working): All
3. Name of chapter (if manga update is working): All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): Haven't any error appear on devtool but manga list not appear.

**Comment by MikeZeDev** [comment]
Nice catch. Another easy fix that simplify a website connector, i love that.
