### ISSUE TITLE
[Site Request]The Blank

### ISSUE THREAD

**Issue by celeste-ex3** [manga-download/hakuneko#6932]
**The Blank**
*theblank*

**Website urls**
- Site: https://theblank.net/
- Manga List: https://theblank.net/manga/
- Manga example: https://theblank.net/manga/turning-it-around/
- Chapter online viewer example: https://theblank.net/manga/turning-it-around/chapter-1/

**Languages**
English

*Website relationship*
Nearly Same Content and Style as Omega Scans

**Additional details**
Mainly focuses on Pornhwa (18+ Manga, Webtoons, Manhwa, Manhua, etc.)

**Comment by MikeZeDev** [comment]
Search before asking. https://github.com/manga-download/hakuneko/issues/6514
