### ISSUE TITLE
[Site Request] Olimpo Scanlation

### ISSUE THREAD

**Issue by ElijahS9** [manga-download/hakuneko#6938]
Olimpo Scanlation

- Site: https://olimposcans.com/
- Manga List:
- Manga example: https://olimposcans.com/comic-iniciando-sesion-en-10000-aos-en-el-futuro.html
- Chapter online viewer example: https://olimposcans.com/leer-iniciando-sesion-en-10000-aos-en-el-futuro-capitulo-107.html

**Languages**
Spanish

**Website relationship*
I'm not sure but I think it's a backup of the other page called "olympus" URL - https://visorolym.com/
but until now it has never changed its domain and everything that is uploaded on "olympus" is also uploaded here, that's why I think it could be a backup since the main website keeps changing its domain

**Comment by MikeZeDev** [comment]
Do not request already requested websites. !

Duplicate https://github.com/manga-download/hakuneko/issues/6286
