### ISSUE TITLE
[Site Request] Lxmanga

### ISSUE THREAD

**Issue by Stragytek** [manga-download/hakuneko#6939]
**Name of the website**
Lxmanga

**Website urls**
- Site: https://lxmanga.cc/
- Manga List: https://lxmanga.cc/danh-sach?page=2
- Manga example: https://lxmanga.cc/truyen/saimin-musume-to-tennen-mama
- Chapter online viewer example: https://lxmanga.cc/truyen/saimin-musume-to-tennen-mama/oneshot

**Languages**
Vietnamese

**Website relationship**
new domain for lxmanga.net

**Comment by MikeZeDev** [comment]
Already supported as LXHENTAI

Open a ticket "website change " for lxhentai
