### ISSUE TITLE
[Site Request] henvn

### ISSUE THREAD

**Issue by Stragytek** [manga-download/hakuneko#6940]
**Name of the website**
henvn

**Website urls (examples below)**
- Site: https://henvn.tv/
- Manga List: https://henvn.tv/danh-sach.html
- Manga example: https://henvn.tv/36774-doc-truyen-nguoc-nhin-la-anh-duong.html
- Chapter online viewer example: https://henvn.tv/36774-69057-xem-truyen-nguoc-nhin-la-anh-duong-chap-1.html

**Languages**
Vietnamese

**Comment by MikeZeDev** [comment]
Cloudlare , wont code it

**Comment by MikeZeDev** [comment]
And like always, user didnt search before ....
Duplicate https://github.com/manga-download/hakuneko/issues/5394
