### ISSUE TITLE
[JapScan] Connector not working

### ISSUE THREAD

**Issue by svnlixie** [manga-download/hakuneko#6941]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The connector isn't working probably due to a change in the website handle : it was japscan.to and now became japscan.lol, resulting in an error on HakuNeko when refreshing.
The website itself works very well.

### To Reproduce

1. Name of connector : JapScan
2. Copy any relevant error message that appears in a popup : "Failed to update manga list for Japscan. Cannot read property 'text' of undefined."

**Comment by MikeZeDev** [comment]
Duplicate .

Probably work in Haruneko, wont be fixed in Haku, no one wants to do that.

Jaspcan is painful https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+japscan&type=issues
