### ISSUE TITLE
[NetTruyen] Connector not working

### ISSUE THREAD

**Issue by minsnguyen** [manga-download/hakuneko#6948]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

it seems to have issues to bypass cloudflare.

The manga list cannot be refreshed.

All references to existing mange bookmark are lost.

### To Reproduce

1. Name of connector: NetTruyen
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
The resource https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/cmg/1/DFIMNfvwiTpEDfZo6fVPIeNL%2FU5QxAgAgpeWOZhb5WA%3D was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by MikeZeDev** [comment]
use another website.

**Comment by minsnguyen** [comment]
what about this source. it does not have cloudflare

https://nettruyenco.vn/

**Comment by MikeZeDev** [comment]
change url in settings, there is a setting for that website.
