### ISSUE TITLE
[NHATTRUYEN] Connector not working

### ISSUE THREAD

**Issue by minsnguyen** [manga-download/hakuneko#6949]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

the source of the connector has been changed.

From: NHATTRUYENTOP.COM
TO: https://nhattruyenbing.com/

### To Reproduce

1. Name of connector: NhatTruyen
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Domain not found

**Comment by MikeZeDev** [comment]
Damn VT websites they change url every days ;-;

**Comment by MikeZeDev** [comment]
I have https://nhattruyento.com/ too, both are cloudflared there is no point changing an url for a cloudflared website.
Bump this again when CF is no more.

**Comment by MikeZeDev** [comment]
Now both are nhattruyenss LMAO thats ridiculous
