### ISSUE TITLE
[QUESTION] Speed up Hakuneko load times.

### ISSUE THREAD

**Issue by MadaHaz** [manga-download/hakuneko#6950]
**This was the closest thing I could select in regards to my question.**

Hakuneko takes a long time to load. Once the program launches it stays on a white screen until it has finished loading. I wanted to see what took it so long to load and it seems like the issue is loading the connectors and their images. I removed all the connectors except for 4 and it loaded faster.

Is there a way to speed up the loading of all the connectors? Also could you please point me to where in the files the actual loading of all the connectors is done? I'm having trouble finding it.

Sorry if this might be the wrong place to ask this.
Thanks in advance for any info provided.

**Context (please complete the following information):**
 - Ran this on an updated nightly build.

**Comment by MikeZeDev** [comment]
There is nothing to do, afaik no one ever complained.

**Comment by MadaHaz** [comment]
Have to ask but does it usually take about a minute to load the app? My laptop is a bit low end so now I'm thinking it might just be me.

**Comment by MikeZeDev** [comment]
Its on your end. Keep in mind that Hakuneko is a browser. A fully fledged Chromium (Electron) based program. 
Mine take less that 10 seconds to open tho. Perhaps its time to close unnecessary stuff on computer idk? 

Anyway nothing we can do, especially when our eyes are turned to Haruneko.
