### ISSUE TITLE
[comicブースト (Comic Boost)] Connector not working

### ISSUE THREAD

**Issue by MadaHaz** [manga-download/hakuneko#6952]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The chapters can't be viewed or downloaded in Hakuneko.
If I try to do either I get a timeout error from Hakuneko.
![Screenshot 2024-04-09 031323](https://github.com/manga-download/hakuneko/assets/62794648/9ac91c68-2842-4442-9091-6ff647d086b0)

When downloading I get the error from the console log.

### To Reproduce

It may be easier to use a link, https://comic-boost.com/content/00390001
1. **Connector:** comicブースト (Comic Boost)
2. **Manga Name:** 結界師への転生
3. **Chapter:** Chapter 47
4. Error popup shown above. Error log:
```
Error: Failed to load "https://comic-boost.com/product/00390067" within the given timeout of 60 seconds!
    at Request.mjs:385 EventTarget {manga: EventTarget, id: "/product/00390067", title: "第47話", file: {…}, language: "", …}file: {name: "第47話", extension: ".pdf", full: "第47話.pdf"}id: "/product/00390067"language: ""manga: EventTarget {connector: ComicBoost, id: "/content/00390001", title: "結界師への転生", status: "available", chapterCache: Array(2), …}pageCache: []pageProcess: falsestatus: "failed"title: "第47話"__proto__: EventTarget
_getPageList @ Connector.mjs:618
```

**Comment by MikeZeDev** [comment]
* They changed something in page unscrambling
* No one reported that chapter list is paginated. We get only first page of chapters :D . Fixed that as a bonus
