### ISSUE TITLE
[<Doujindesu>] Connector not working CLOUDFLARE

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#6965]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

![clop](https://github.com/manga-download/hakuneko/assets/81703465/b8ba2a50-ed43-436a-b5bd-50644d37366a)

### To Reproduce

1. Doujindesu
2. https://doujindesu.tv/

**Comment by MikeZeDev** [comment]
duplicate https://github.com/manga-download/hakuneko/issues/6594
