### ISSUE TITLE
[Daum] Connector not working, should now be webtoon.kakao.com

### ISSUE THREAD

**Issue by prog-z-99** [manga-download/hakuneko#6966]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] Read, but related issue is closed without proper solution.

### Is the website of the connector working properly ?

- [X] Current connector does not work, but the connector should be re-connected to the new website.

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The website [webtoon.daum.net](webtoon.daum.net) was acquired by Kakao, and was rebranded to [Kakao webtoon](webtoon.kakao.com) (separate from Kakao page, a similar, but different service). The connector entry should be removed, and possibly re-connected to Kakao webtoon instead. 
an update of the #4712 issue.

Would be nice since the service provided is different than Kakao Page, and there are different series/promotion/account access present in Kakao Webtoon compared to Kakao Page.

### To Reproduce

1. Daum 웹툰
2. Shows `Failed to update manga list for Daum 웹툰`
`ERR_NAME_NOT_RESOLVED https://webtoon.daum.net`

**Comment by MikeZeDev** [comment]
We know, but we are not adding support to complex websites anymore in Hakuneko. We are working hard on Haruneko.
