### ISSUE TITLE
[Site Request] TCB Scans (backup)

### ISSUE THREAD

**Issue by MarqFJA87** [manga-download/hakuneko#6967]
**Name of the website**
TCB Scans

**Website urls (examples below)**
- Site: https://tcbscans.me/
- Manga List: https://tcbscans.me/projects
- Manga example: https://tcbscans.me/mangas/6/my-hero-academia
- Chapter online viewer example: https://tcbscans.me/chapters/7711/my-hero-academia-chapter-420

**Languages**
English

**Website relationship**
Seems to be the group's new domain, as the original URL (https://tcbscans.com/) now redirects there.

**Comment by MikeZeDev** [comment]
Cloudflare cant do

**Comment by MarqFJA87** [comment]
What do you mean?

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/27c81442-0937-431d-b584-092c8331c2e6)
Pinned issue : https://github.com/manga-download/hakuneko/issues/2933

**Comment by MarqFJA87** [comment]
Dammit, that sucks.

**Comment by TKCeegit** [comment]
@MikeZeDev I posted about an alternative site which doesn't have the Cloudflare problem https://github.com/manga-download/hakuneko/issues/7005, have you checked that out?

**Comment by MikeZeDev** [comment]
Mentioning someone or another issue is pointless. I check all issues.

**Comment by TKCeegit** [comment]
Well, that's good to know. But I noticed that the site wasn't added to Hakuneko despite that it works, so I just thought I would reach you directly and maybe find out what's the deal.

**Comment by MikeZeDev** [comment]
It wont unless some external contributor do it. Main devs are focused on hakuneko successor.

**Comment by TKCeegit** [comment]
Which is what I only found out about on Discord a few days ago. Until then, I still thought work was going for Haku so that's on me, sorry about that.

**Comment by MikeZeDev** [comment]
Dont be sorry. Contributors can add new websites tho and it may eventually be added to Haru.

**Comment by TKCeegit** [comment]
Okay, then I think the usual sites which I read from from are probably already added e.g. Mangasee, Mangahasu, Mangakatana. I just hope this project won't take as long as that Pokemon Sage fangame to launch.

**Comment by MarqFJA87** [comment]
It seems that TCB Scans have finally settled on a stable domain instead of a backup/provisional one, now at tcbscans.me, so I have updated the OP accordingly. Hopefully the Cloudflare issue isn't a factor with this one.

EDIT: I see that it's already included and accessible on the app, so this request is moot.
