### ISSUE TITLE
Can't download Novels I own from cmoa 

### ISSUE THREAD

**Issue by shablul77** [manga-download/hakuneko#6972]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
when trying to download novels on cmoa I get an error that there is no content

**To Reproduce**
1. Copy cmoa novel page URL (in my case https://www.cmoa.jp/title/1101276378/ and https://www.cmoa.jp/title/1101246158/)
2. Go to HakuNeko
3. Click on"the icon for "paste manga links from clipboard
4. Scroll down in Manga List to the title (in my case either 魔獣になった傭兵のおっさんが、憧れの騎士に拾われた話 or アステリズムに花束を 百合SFアンソロジー )
5. Click on title
6. Scroll down in the Chapter List to the title
7. IF you click on the cloud icon to download then you see DOWNLOAD FAILED error while hovering the mouse on top of the triangle icon where the cloud icon was 
OR
7. IF you click on the image icon to see the contents of the novel you will get a pop up error message saying "There was no content found for..."

<img width="788" alt="Screenshot 2024-04-16 190410" src="https://github.com/manga-download/hakuneko/assets/167227420/7fa9ea8a-876c-4e94-a1d4-f3aa2679e4e2">

**Expected behavior**
The novel being downloaded as images to the folder specified with the rest of whatever I downloaded.

**Screenshots**

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 6.17

**Additional context**
I tried looking around in the GitHub and the Discord server and didn't notice any bug report or something about this so I assume this has to do with either a failed automation or not knowing how to save these files? 
I did find a way to save the novel as images manually so tell me if the issue is the latter and I'll specify (even took pictures just in case).

Adding this just in case, this is only happening with novels and other manga I own do work. Adding example screenshots to a manga I own at cmoa and did manage to download using HakuNeko to show that I do have access to these novels.
<img width="641" alt="Screenshot 2024-04-16 190244" src="https://github.com/manga-download/hakuneko/assets/167227420/87566d6c-fa2f-4494-845b-86cefb1b9b8c">
<img width="669" alt="Screenshot 2024-04-16 190346" src="https://github.com/manga-download/hakuneko/assets/167227420/f327f76e-a7f8-4f84-95a8-8472a40f96cb">
<img width="666" alt="Screenshot 2024-04-16 190355" src="https://github.com/manga-download/hakuneko/assets/167227420/37d34b22-866b-4827-ac4c-3143e1ebfe6a">
<img width="653" alt="Screenshot 2024-04-16 190403" src="https://github.com/manga-download/hakuneko/assets/167227420/4a296dbe-78f3-4d16-8197-8298ff66ace0">

**Comment by MikeZeDev** [comment]
One question , only one : 

Are those Novel, i mean, text only? 

If thats the case its normal. We didnt even know there was novels on this website .

Otherwise it could be a login problem. Dev cant test paid content, for obvious reasons.

Could it be a new SpeedBinb version?

**Comment by shablul77** [comment]
well except for occasional pages it's mostly text yea
アステリズムに花束を 百合SFアンソロジー has a manga chapter and 魔獣になった傭兵のおっさんが、憧れの騎士に拾われた話 has occasional illustrations but that's it

the site does have novels but I don't recommend from experience lol 
I originally got those 2 there because of circumstances but they're accessed like the comics so you can't mark or copy any text hence looking up words you don't know is a lot of traditional hard work xD

I honestly don't know about the SpeedBinb question sorry...

**Comment by MikeZeDev** [comment]
Just checked , those are pictures.  Checked the speedbinb quickly, and yeah its like there is no picture in the returned data that is veeeeery weird, there is no error at all

Gotta check this on Haruneko just in case. I really dont get it and speedbinb  is a complex fellow.

**Comment by MikeZeDev** [comment]
Same thing in Haruneko :/. They use a different script for "novels", or at least for the titles you mentioned.

Does this look like the novel text to you? (ignore the junk chars) ? Cause i cant read Japanese :D
I've seen an "I'm Fine" in plaintext english so i guess that is the problem.

![image](https://github.com/manga-download/hakuneko/assets/10671518/ac2cee23-6586-44e2-8641-8de7621ec632)

If they render the html like that, i am afraid this is not much we can do. Novels are unsupported in SpeedBinb websites and most likely wont. SpeedBinb is already a nightmare.

**Comment by shablul77** [comment]
> Does this look like the novel text to you?

Actually it is from the first chapter of the novel!
(Except for the junk lol)

Sad to hear there's not much to do :(

Thank you for checking though <3
