### ISSUE TITLE
[Zinmanga] Connector not working

### ISSUE THREAD

**Issue by Kiriri01** [manga-download/hakuneko#6973]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Hai, I found out that The Website of "Zinmanga" url is changed. Please help to update the url, because the old one didn't work even in my normal browser. Thank you.

### To Reproduce

1. Name of connector : https://zinmanga.io/
2. Name of manga : All Manga/Manhwa
3. Name of chapter : All Manga/Manhwa
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

![image](https://github.com/manga-download/hakuneko/assets/97859566/0a05f43b-dbf8-4824-9f9e-59124028f03f)

The old Url is : https://zinmanga.com/
Changed to be : https://zinmanga.io/

**Comment by MikeZeDev** [comment]
Wrong? https://mangazin.org/

**Comment by Kiriri01** [comment]
i checked, it's https://zinmanga.io/

![image](https://github.com/manga-download/hakuneko/assets/97859566/bbddeb6f-f3af-402e-adc4-c8c0d7f5c44b)

**Comment by MikeZeDev** [comment]
Nope. I'll stick to mangazin.org since it seems to be the real successor of the old zinmanga. I mean, manga identifiers are the same, you cant fake that unless you stole their database. A clone website dont need to go that way.

Keiyoushi repo made a separate extension for your io website. And their zinmanga is also mangazin.org. I guess i am not wrong.

**Comment by Kiriri01** [comment]
But, i tried to refresh, the list still not refresh. The popup msg showed like this 

![image](https://github.com/manga-download/hakuneko/assets/97859566/3ccf2acf-39ff-4b89-8c18-6371a940e100)

I kinda confuse why it's still error, even in my standar browser mangazin.org working pretty well.
Thank you

**Comment by MikeZeDev** [comment]
Use nightly
