### ISSUE TITLE
[Feature]https://blogtruyen.vn/

### ISSUE THREAD

**Issue by ryannguyentran** [manga-download/hakuneko#6974]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by MikeZeDev** [comment]
Please use the proper template "Website suggestion" and fill it properly .
