### ISSUE TITLE
[TOPMANHUA] Connector not working

### ISSUE THREAD

**Issue by Kiriri01** [manga-download/hakuneko#6975]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hai, i tried to refresh manga list to get new manhwa, but it didn't work. I tried in 2 different devices, still didn't work in both. But when i open the website in my standard Browser, it working so well.

### To Reproduce

1. Name of connector : https://manhuatop.org/
2. Name of manga : Screw the Noble Life, I’m Going Home (https://manhuatop.org/manhua/screw-the-noble-life-i-m-going-home/)
3. Name of chapter : All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

![image](https://github.com/manga-download/hakuneko/assets/97859566/4889210f-cd00-466f-ab9e-e376e7ba97e5)

**Comment by MikeZeDev** [comment]
* its not "manhuatop.org" but "topmanhua.com". 
* And nothing we can do , change website
![image](https://github.com/manga-download/hakuneko/assets/10671518/ec48b0fc-cbaa-4ae4-ba4d-0cfcff40e221)

**Comment by Kiriri01** [comment]
so, i need to req new issue for change website? 
I will req new one for ask your help.
Thank you

**Comment by MikeZeDev** [comment]
> so, i need to req new issue for change website? I will req new one for ask your help. Thank you

No. You dont get it.

You asked for a different website. One that is not supported. Topmanhua will stay topmanhua.
Open a "website suggestion" issue if you want to request Manhuatop addition. But perhaps someone already asked for it, look before opening a ticket :D

**Comment by Kiriri01** [comment]
Aaah, i will look for it first. And thank you for you ^^

**Comment by Zakarax** [comment]
I also often checking this site and they change from topmanhua.com to https://manhuatop.org/

**Comment by MikeZeDev** [comment]
yup, now that issue is valid :D
