### ISSUE TITLE
[Site Request] COMIC FANS

### ISSUE THREAD

**Issue by zeoint** [manga-download/hakuneko#6976]
**Name of the website**
COMICFANS

**Website urls (examples below)**
- Site: https://bilibilicomics.net/
- Manga List: NONE
- Manga example: https://bilibilicomics.net/episode/183-i-just-can-t-bring-myself-to-bully-a-child
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
ENGLISH

**Website relationship*
COPY OF BILIBILICOMICS.COM (KIND OF).

**Additional details**
NO LOGIN FEATURE NECESSARY. ALL COMICS ARE ACCESSIBLE.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6876
