### ISSUE TITLE
[lezhin-en] Purchased comics do not show up in list

### ISSUE THREAD

**Issue by manhwa** [manga-download/hakuneko#70]
Hi,

My purchased comics do not show up in the chapter list. For instance, I bought all of Phermone Holic, and only the first chapter and special (free) show in the download.

1. Open HakuNeko
2. Add log in information
3. Open console
4. Search Lezhin for Phermone Holic
5. Verify that login succeeded on the Network tab
6. Only 2 chapters show in the chapter list <-- issue

Thanks!

**Comment by 27136773** [comment]
Unfortunately i have no purchased comics on lezhin and therefore i cannot determine the conditions to show purchased comics.

Could you provide the source code of the chapter website after login by typing the following into your browser address bar: `view-source:https://www.lezhin.com/en/comic/pheromone_holic`

[Pheromonic-Holic (Non-Purchased)](https://github.com/manga-download/hakuneko/files/3126122/pheromonic-holic.json.txt)

**Comment by manhwa** [comment]
I did a quick diff of the Purchased + Non-Purchased, and the info seems to not be stored there but as a part of a separate request. 

To make it easier for you, I can paypal you some funds to experiment with

Purchased Pheromonic-Holic: https://pastebin.com/C1mNBPnC (with redacted userID)

https://www.lezhin.com/api/v2/contents/pheromone_holic/users?type=comic&country_code=us&_=${REDACTED}

Output: https://pastebin.com/egDEgajM

**Comment by 27136773** [comment]
I think the provided information was enough to solve this issue with rev. 9596879c
Please check if HakuNeko will now allow to access purchased chapters.

**Comment by manhwa** [comment]
Looks like it's working for Pheremone Holic. I'll test on another comic tomorrow and let you know how it goes.

**Comment by 27136773** [comment]
Assumed to be fixed
