### ISSUE TITLE
9anime mirror problems

### ISSUE THREAD

**Issue by ms308680** [manga-download/hakuneko#700]
Hello, for about the past 4-5 days, 9anime sources have been spitting out "Cannot read property "1" of null on F5 and Mycloud.  While MP4upload has been hit or miss or takes forever. 

RonnyToday at 5:05 PM
OK it seems the video mirrors (e.g. F5) added a new security layer... this will probably take some time to fix

**Comment by 27136773** [comment]
Seems to be quite stable => closed
