### ISSUE TITLE
[AnimePahe] Connector not working

### ISSUE THREAD

**Issue by heyaclizun** [manga-download/hakuneko#7001]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I tried downloading anime from animepahe, but it errors saying [Referenceerror: hls is not defined]. I tried with other sites, same problem as well. I tried to download manga/manhwa chapters, it works well. Only with anime becomes error.

**Expected behavior**
I want to download anime again, with no errors.

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/167687500/36d3b1c2-9869-4e08-8a59-5f322f143d7d)

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 6.1.7
<img width="405" alt="Screenshot 2024-04-21 202530" src="https://github.com/manga-download/hakuneko/assets/167687500/7efc4eae-c2ac-450a-a372-3a3860cea649">

**Comment by MikeZeDev** [comment]
Your problem is that it changed url. I changed it from .com to .ru and i am fine. Fix on the way.

![image](https://github.com/manga-download/hakuneko/assets/10671518/cf9cf94b-731b-4116-a335-dc943edf5ec7)

**Comment by heyaclizun** [comment]
Sorry, I cannot understand how to do it. What will I do step-by-step?

**Comment by MikeZeDev** [comment]
1) You use nightly build
2) You wait for the linked Pull request to be "MERGED"

**Comment by heyaclizun** [comment]
Will I merge it manually or the system does it? How can I know that it was successfully merged?

**Comment by heyaclizun** [comment]
Hello, I am using Nightly and the anime chapters are showing, but I still can't download. It shows errors such as (TypeError: Failed to fetch) and (TypeError: playlist.match is not a function). What to do?
![image](https://github.com/manga-download/hakuneko/assets/167687500/92a4e668-c6ab-49b6-ad3d-40694c8878f3)
![image](https://github.com/manga-download/hakuneko/assets/167687500/1ee5865c-6dce-427a-a199-7063960f94f3)

**Comment by MikeZeDev** [comment]
This is a separate problem and there is nothing we can do about HTTP2 PROTOCOL ERROR
