### ISSUE TITLE
[< Lezhin (English) > ] Unknown character, fail to download

### ISSUE THREAD

**Issue by yimeji** [manga-download/hakuneko#7004]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Unknown character (see screenshot, the "rectangle") appear in episode name in hakuneko web browser and episodes that have that character fail to be downloaded. Checked in chrome, there is no such character appear.

The episode is free for anyone to check.

in Hakuneko
![Screenshot 2024-04-23 042020](https://github.com/manga-download/hakuneko/assets/89035153/d7a59a44-1923-4082-b292-b5aba36a1e08)

in Chrome
![Screenshot 2024-04-23 044604](https://github.com/manga-download/hakuneko/assets/89035153/a026ccee-c34b-427b-9f82-84bbfbd5bcbb)

### To Reproduce

1. Lezhin English
2. A World Without You
3. Epilogue - Season 1 Creator's Note (Free chapter)

**Comment by MikeZeDev** [comment]
For verification purposes, cant you give us the manga link please?

**Comment by yimeji** [comment]
Her you go
https://www.lezhinus.com/en/comic/without_you_en

**Comment by MikeZeDev** [comment]
Well i wonder how you can even download something considering this PR is not merged..  🤷 . This website should not work at all.

https://github.com/manga-download/hakuneko/pull/6834

**Comment by yimeji** [comment]
I use instructions here (link below).
Works for me for english site but not korean.

https://github.com/manga-download/hakuneko/issues/6961#issuecomment-2049217196

**Comment by MikeZeDev** [comment]
I see can you then test with the modified file from this PR? https://github.com/manga-download/hakuneko/pull/6721
https://raw.githubusercontent.com/manga-download/hakuneko/7c608a005adcee40e0bc7e4857b4e816b1c815c1/src/web/mjs/engine/Storage.mjs

I ma busy i have to fix my mess.

**Comment by yimeji** [comment]
Tried and it works now.
