### ISSUE TITLE
[Site Request] TCB Scans (Another Backup/Alternative Site)

### ISSUE THREAD

**Issue by TKCeegit** [manga-download/hakuneko#7005]
**Name of the website**
TCB Scans

**Website urls (examples below)**
- Site: https://tcbscans-manga.com/
- Manga List: https://tcbscans-manga.com/manga/
- Manga example: https://tcbscans-manga.com/manga/one-piece/ 
- Chapter online viewer example: https://tcbscans-manga.com/manga/one-piece/chapter-1112/

**Languages**
English

**Website relationship*
Backup/alternative for the original TCB Scans site, which has been down for two weeks and counting.

**Comment by MikeZeDev** [comment]
No need for backup we have original it works fine (in haru)

**Comment by TKCeegit** [comment]
Okay, no problem and thank you. I couldn't figure out how to use Haru when I first installed it but I know now so it's all good. By the way, I saw someone put up a suggestion for Bato.to v3 (https://github.com/manga-download/hakuneko/issues/5953) and I checked Haru to see which version is there. It has v2 just like Haku so if the dev team can switch from v2 to v3 in Haru please do.
