### ISSUE TITLE
[Mangacross] Connector not working (site now changed to Championcross)

### ISSUE THREAD

**Issue by Suzushiiro** [manga-download/hakuneko#7006]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Mangacross updated to a whole new site called Championcross and it seems like they've changed basically everything.

Example series page: https://championcross.jp/series/899dda204c3f2/pagingList?s=2&page=0&limit=50
Example chapter page:  https://championcross.jp/episodes/c402c0075627c

### To Reproduce

1. Attempt to pull up Mangacross manga list
2. "Unexpected token < in JSON at position 0" error

**Comment by MikeZeDev** [comment]
Oh, they use Comici viewer, awesome.

**Comment by sakuhanachan** [comment]
also it's can use ComiciID for access paid manga (but must login from specify site like Championcross must login from Championcross)
