### ISSUE TITLE
[<manhwaland.org>] Domain Change

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#7009]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The domain website has been change

### To Reproduce

1. Manhwaland.org change to https://manhwaland.vip

**Comment by MikeZeDev** [comment]
What about https://manhwaland.lat, that now redirect to https://manhwaland.to? 

Because i used https://manhwaland.lat in Haruneko :/.

**Comment by andillk** [comment]
i think that is different website cause time update of manga chapter is not same.

**Comment by MikeZeDev** [comment]
its ink
