### ISSUE TITLE
i provide you some code to download mangas from Vietnamese sites

### ISSUE THREAD

**Issue by thugdang** [manga-download/hakuneko#701]
now hakuneko can't download any of Vietnamese sites. because of hotlink? maybe.
i found a way to download mangas from plenty of Vietnamese sites. i really love the way hakuneko works so hope you can support Vietnamese sites again.
you can check the userscipt in the link below:
https://forum.blogtruyen.vn/tool/manga-comic-downloader-44325
thanks for reading!
//i'm not own this tool

**Comment by 27136773** [comment]
Closed to hide from the list of open issues.
