### ISSUE TITLE
[Tapas.io] Connector not working

### ISSUE THREAD

**Issue by Asriel2137** [manga-download/hakuneko#7029]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I'm unable to load the list of series from tapas. I've logged in through manual interaction (and it shows me as being logged in).

`Failed to update manga list for Tapas

Unexpected token < in JSON at position 0`

### To Reproduce

1. Tapas.io
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Connector.mjs:579 SyntaxError: Unexpected token < in JSON at position 0

**Comment by Asriel2137** [comment]
I followed the steps in #2820 to log into tapas

**Comment by MikeZeDev** [comment]
> I followed the steps in #2820 to log into tapas

Doesnt matter, they updated their website, nothing works anymore. 

Since i have to code the support for this website in Haruneko i am gonna start with that, i'll eventually fix it for Hakuneko right after too but no ETA on that, since we are very busy.

**Comment by Asriel2137** [comment]
In the meantime, which function is being called to download chapters from a specific comic? Can I just hack a quick download through console?

**Comment by Asriel2137** [comment]
Actually, after looking into the code, it looks like it would have to be rewritten. I may have a look later.

**Comment by MikeZeDev** [comment]
You are free to submit a PR, i would gladly review it. https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/Tapas.ts may help you.

The thing is, Haruneko cant handle Novels yet
