### ISSUE TITLE
Rawsenmanga don't work

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#703]
Can't load mangalist

**Comment by 27136773** [comment]
Cannot be reproduced on my end, could this have been a temporary website hosting issue?
<img width="1232" alt="Screen Shot 2019-12-18 at 10 11 08 PM" src="https://user-images.githubusercontent.com/27136773/71123684-7d32de80-21e3-11ea-8683-38df9ad2712b.png">

**Comment by Ever4engel** [comment]
yes i confirm that it was a temporary website hosting issue on hakuneko (not in the website)
it work's well now 
thanks i'll close this ticket
