### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by So4nk** [manga-download/hakuneko#7031]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
With both the websites "Sushi Scans" at https://sushiscan.net/ and "JapScan" at https://www.japscan.lol/. The cloudflare is stuck.

**To Reproduce**
1. Go to 'website'
2. Scroll down to 'Sushi Scans'
3. Click on 'open the website in a new window"

**Expected behavior**
Once I've clicked on "I am not a robot" the website should be unlock and I should be able to download from it

**Context (please complete the following information):**
 - OS:  Windows10
 - HakuNeko Version  6.17

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/938c9850-eba0-41fb-be94-df2de665d1c4)

Its the SEARCH function .Use this. If you had used it you would have seen this https://github.com/manga-download/hakuneko/issues/4657 and this https://github.com/manga-download/hakuneko/issues/5615 .

1) No need to open an issue when there are already some opened for the same reasons.
2) Especially with just [BUG] as a title.
3) And when it should have been one website per issue.
3) Its not fixable. Every scraper on the planet have problem with Cloudflare. See the pinned issue? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/0005c729-6bd5-4806-8fb5-55572ee98c72)

All those website cant be fixed , they are all tagged Cloudflare.
https://github.com/manga-download/hakuneko/issues?q=is%3Aissue+is%3Aopen+label%3ACloudflare

Closing this issue as duplicate.
