### ISSUE TITLE
RizzComics

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7044]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The site's address has been renewed

### To Reproduce

1. Name of connector RizzFables 
2. Name of manga (if connector update is working)https://rizzfables.com/
3. Name of chapter (if manga update is working)https://rizzfables.com/chapter/r2311170-the-counts-youngest-son-is-a-player-chapter-54
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Bruh. You keep opening issues for a while now.  Reporting bugs is always appreciated but you still check the box that you used nightly without using nightly? 
And you still dont search before opening an issue? Whats wrong with you? 

https://github.com/manga-download/hakuneko/pull/7039/files

**Comment by Tianzhou2** [comment]
> Bruh. You keep opening issues for a while now. Reporting bugs is always appreciated but you still check the box that you used nightly without using nightly? And you still dont search before opening an issue? Whats wrong with you?
> 
> https://github.com/manga-download/hakuneko/pull/7039/files

I don't know how to change the address
