### ISSUE TITLE
[Site Request] manga-zip

### ISSUE THREAD

**Issue by OzonoX9** [manga-download/hakuneko#7047]
**Name of the website**
manga-zip

**Website urls (examples below)**
- Site: https://manga-zip.info/home.i1/
- Manga List: https://manga-zip.info/a-z/
- Manga example: https://manga-zip.info/dl/お嬢と番犬くん.i7/

**Languages**
-Japanese

**Comment by MikeZeDev** [comment]
I really wish people would search before opening issues https://github.com/manga-download/hakuneko/issues/4347
