### ISSUE TITLE
omegascans.org[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by GyreRaven** [manga-download/hakuneko#7048]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Connects and refreshes the manga list. None of the chapters work
![image](https://github.com/manga-download/hakuneko/assets/133878656/e87b2f9a-f128-4615-ab8e-27fbdb97c76e)
. Tried several. Website works.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Another day, another person who doesnt search before opening an issue : https://github.com/manga-download/hakuneko/issues/6892 . I wonder if people can read.

**Comment by GyreRaven** [comment]
Hi,


I did do a small check before posting it.
Since I've seen no open issues with it, I presumed It is not used often and
waited several weeks.
I have now checked it on two different PC's, with DIfferent OS, and new
fresh install and the chapters still doesn't load.
If it is on my end, then mea culpa, but this is the error I get when
looking at the console when trying to load the two newest on the site
(Fresh install, win11):
[image: image.png]


Op vr 3 mei 2024 om 16:07 schreef MikeZeDev ***@***.***>:

**Comment by MikeZeDev** [comment]
There is something wrong with updating: Its fixed on github tho.. Maybe its a CDN caching issue.

1)  Make sure you [use nightly version ](https://github.com/manga-download/hakuneko/releases). I mean this hakuneko update problem must be temporary.

2) Feel free to try deleting program code cache if you want, just in case.

* Close Hakuneko
* Press your Windows key + R key, type `%LOCALAPPDATA%` in the box, then press Enter. 
* Delete `hakuneko-desktop` folder
* Start Hakuneko. It will update itself, if may become unresponsive/blank for a moment.

**Comment by GyreRaven** [comment]
I see.
Thanks for the reply.
I wanted to exclude it being my own wrongdoing or that I've checked a wrong
setting somewhere( hence tested on another PC and fresh download)
I do appreciate the work done, because the other connectors that I do
frequently use still work more than satisfactory.
This one I don't use so much, but wanted to share the issue, partly to
exclude my own stupidity, as I mentioned before.

Kind regards.
