### ISSUE TITLE
[Site Request] Nicomanga

### ISSUE THREAD

**Issue by Torablue** [manga-download/hakuneko#7049]
**Name of the website**
Nicomanga

**Website urls (examples below)**
- Site: https://nicomanga.com/
- Manga List: https://nicomanga.com/manga-list.html
- Manga example: https://nicomanga.com/manga-izure-saikyou-ni-itaru-tensei-mahoutsukai.html
- Chapter online viewer example: https://nicomanga.com/read-izure-saikyou-ni-itaru-tensei-mahoutsukai-chapter-19.html

**Languages**
Japanese (RAW)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
FlatManga

**Comment by Torablue** [comment]
> FlatManga

??
There's no FlatManga in Hakuneko or Haruneko tho.

**Comment by MikeZeDev** [comment]
> > FlatManga
> 
> ?? There's no FlatManga in Hakuneko or Haruneko tho.

Its using Flatmanga template, this info is not directed to you.

**Comment by MikeZeDev** [comment]
BTW, duplicate : https://github.com/manga-download/hakuneko/issues/6398
