### ISSUE TITLE
[Site Request] championcross.jp

### ISSUE THREAD

**Issue by hxcian** [manga-download/hakuneko#7050]
**Name of the website**
champion cross

- Site:[ championcross.jp](https://championcross.jp/)
- Manga List: https://championcross.jp/category/manga
- Manga example: https://championcross.jp/series/f73ae48c59e62/
- Chapter online viewer example: hhttps://championcross.jp/episodes/f3708ac000a6b/
- 
**Languages**
japan

**Comment by MikeZeDev** [comment]
Invalid issue.
* Duplicate : https://github.com/manga-download/hakuneko/issues/7006
* Fixed by https://github.com/manga-download/hakuneko/pull/7007
