### ISSUE TITLE
[Site Request] [Site:] https://lekmanga.net/        the websitename is : Mangalek

### ISSUE THREAD

**Issue by Vrfeed** [manga-download/hakuneko#7054]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- [Site:] https://thewebsiteurl/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://thewebsiteurl/manga/themanganame.html
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
What is your thoughts on this? 

https://github.com/manga-download/hakuneko/issues/6909

**Comment by MikeZeDev** [comment]
Invalid request : you ask for an already supported website .

https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/Mangalek.mjs#L10

**Comment by Vrfeed** [comment]
i try it many times but not working at all

**Comment by MikeZeDev** [comment]
> i try it many times but not working at all

In that case open a "not working" issue not a "website suggestion" issue . If you do that, please make sure to follow the instructions and dont blindly check boxes , because lekmanga works on my end.
