### ISSUE TITLE
[Site Request] Manhua Top

### ISSUE THREAD

**Issue by MangaMod** [manga-download/hakuneko#7060]
**Name of the website**
Manhua Top

**Website urls (Manhua Top)**
- Site: https://manhuatop.org/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://manhuatop.org/manhua/the-jangsan-tiger/
- Chapter online viewer example: https://manhuatop.org/manhua/the-jangsan-tiger/chapter-1/

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
https://manhuaus.com

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Invalid issue : Website already supported. Use nightly, like you should have since its written in issue template .

https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/TopManhua.mjs
