### ISSUE TITLE
[<Doujindesu>] Connector not working

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#7062]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Sometime only can to open and when i want download it's will error. I think the problen is still cloudflare you can see from screenshoot i give.

### To Reproduce

Doujindesu
![dodes](https://github.com/manga-download/hakuneko/assets/81703465/fd33c081-ebb3-4e56-bc73-f644a4787a05)

**Comment by MikeZeDev** [comment]
CloudFlare indeed, change website, it wont be fixed. Dont open useless issue please, there is already one.

https://github.com/manga-download/hakuneko/issues/6594

**Comment by wow2134** [comment]
> CloudFlare indeed, change website, it wont be fixed. Dont open useless issue please, there is already one.
> 
> #6594

okee thanks
