### ISSUE TITLE
[<Mangalek>] Website not working

### ISSUE THREAD

**Issue by Vrfeed** [manga-download/hakuneko#7064]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

*

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
* Checked : no problem. 
* Ticket miss important informations like : error message in console.

**Comment by Vrfeed** [comment]
when i click on refresh nothing show on manga list 
even if i click on website new window on the app show message 404
Not Found
The resource requested could not be found on this server!

**Comment by MikeZeDev** [comment]
Sorry for asking that again but : Are you using nightly build ? 

* You checked the box but everyone check the box without following instructions, its not personal i have to make sure.
* There is an error on our end that can cause Hakuneko not updating so you may not have latest patches. Mangalek support was updated recently.

Whats the url you have for mangalek? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/c5fc857e-c2c7-4413-9355-d6996f8380ef)

**Comment by Vrfeed** [comment]
![Cap_mangalek](https://github.com/manga-download/hakuneko/assets/114469988/6ea7bf0e-7fb0-4d94-a674-7819b8ac60b8)

i am using hakuneko  v6.1.7
how can i get the last version please ?

**Comment by MikeZeDev** [comment]
I knew it..... 🤦 
When you filled the issue, there is a link to nightly, you were supposed to USE IT, check if it works, and continue with the issue in case it doesnt work

![image](https://github.com/manga-download/hakuneko/assets/10671518/6984115a-f215-4328-a828-17a5ad035831)

Yet you checked it and DID NOT test nightly 😔 

I should really put a checkbox "i acknowledge i have to give you all my organs"

People want to gain time, dont test nightly, dont read and in the end they lose time and dev lose time too.

**Comment by Vrfeed** [comment]
I am sorry, the submit comment button was not working. I thought it might be the checkbox, so I checked all of them. Thank you for your help. I tried using the nightly version and it finally worked. There are many Arabic websites that are not working; I will try to report them later.

**Comment by MikeZeDev** [comment]
> I am sorry, the submit comment button was not working. I thought it might be the checkbox, so I checked all of them. Thank you for your help. I tried using the nightly version and it finally worked. There are many Arabic websites that are not working; I will try to report them later.

Sure. Reports are always welcome 😉
