### ISSUE TITLE
Lekmanga/ Mangalek

### ISSUE THREAD

**Issue by TheLimeonade** [manga-download/hakuneko#7073]
**Name of the website**
Lekmanga/mangalek

**Website urls (examples below)**
- Site: https://lekmanga.net/
- Manga List: https://lekmanga.net/manga/
- Manga example: https://lekmanga.net/manga/the-game-that-i-came-from/
- Chapter online viewer example: https://lekmanga.net/manga/the-game-that-i-came-from/1/

**Languages**
Arabic

**Website relationship*
Mangalek was shutdown, this is the new link/ alternative

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Use nightly
