### ISSUE TITLE
[Website not Working] Zebrack does not open in built-in browser. Cannot log in.

### ISSUE THREAD

**Issue by rillant** [manga-download/hakuneko#7080]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Zebrack does not open in built-in browser, screen just stays blank. 

**To Reproduce**
1. Go to connectors.
2. Search for Zebrack.
3. Click to open website in new window.

**Expected behavior**
Zebrack website to load so I can log in and rip paid content.

**Screenshots**
![afbeelding](https://github.com/manga-download/hakuneko/assets/139340338/36f24fc6-c08f-41cd-946f-2e7a551cd729)

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 6.17

**Additional context**
This problem does not happen for other sites like Comic Days or Manga Pocket:

![afbeelding](https://github.com/manga-download/hakuneko/assets/139340338/aedbbf2f-2798-4dbb-bdb6-9fb445d31ec1)

**Comment by MikeZeDev** [comment]
Someone on discord (perhaps you?) confirmed it works using nightly.
I assume , like 99% of people filling an issue that you didnt follow instructions and didnt use nightly ? 

Oh , you used wrong template so you didnt have the instruction.

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/d15a842a-b55e-446a-addb-ca7912b9d670)
![image](https://github.com/manga-download/hakuneko/assets/10671518/08917330-c54f-495b-9ebf-53e65fecbb99)

**Comment by MikeZeDev** [comment]
Wont fix, use nightly build where it works.
