### ISSUE TITLE
[<TOPTOON(탑툰)>] Connector not working

### ISSUE THREAD

**Issue by teledong** [manga-download/hakuneko#7083]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Some Page are not download & failed to download pages

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Incorrect issue, fill the template properly

**Comment by MikeZeDev** [comment]
Cant reproduce, it works.

![image](https://github.com/manga-download/hakuneko/assets/10671518/c5e415b5-c897-4a10-9545-2679b28fe6de)

 Fill the ticket properly or it will be closed, we lack informations. Did you try to download locked chapters without paying the website? Because you just cant, its obvious.

**Comment by MikeZeDev** [comment]
Closing a dead issue.

**Comment by teledong** [comment]
Recent Manga Download Error (Some img return 404)

![Image](https://github.com/user-attachments/assets/d26e3717-b13d-411a-8a4a-145d02d692b5)

Here is F12(Dev tool) Log...
![Image](https://github.com/user-attachments/assets/006e2f8b-effe-4494-9e9a-4dc1ddab519f)
![Image](https://github.com/user-attachments/assets/a9b9f046-5469-432a-86e6-9217e0a00d59)

But Option "Ignore Error On Download" Enabled, Download without problem...

**Comment by MikeZeDev** [comment]
> But Option "Ignore Error On Download" Enabled, Download without problem...

OFC it skips 404 errrors meaning you will miss files i dont think its considered as WORKING.

Ngl, cant diagnose stuff on such websites without people feeding us manga url because we cant read the characters.

**Comment by teledong** [comment]
Oh.. You are Right... 404 Error occur specific page....

![Image](https://github.com/user-attachments/assets/e6e6af3f-4710-4ae4-8b60-32f71bcf3963)
It's funny.. only these page occur 404 error....

So... how can i help???

**Comment by teledong** [comment]
only 4, 6, 8, 9,12, 14 page occur 404 error...

**Comment by MikeZeDev** [comment]
Still no manga link.

**Comment by teledong** [comment]
oh.. here is the link

https://toptoon.com/comic/ep_list/resume

**Comment by teledong** [comment]
> Still no manga link.

119 to 121 << error occur (4,6,8,9,12,14 file)

web-browser fine (show all img)
