### ISSUE TITLE
[Omegascans] Connector not working

### ISSUE THREAD

**Issue by OnlineHaku** [manga-download/hakuneko#7084]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

In Hakuneko, All (I believe) of the chapters are shown as 0/0. I am currently using a Macbook Air, and I am not sure if this is a problem from the app itself or the computer. I am using the Hakuneko Desktop app. 

### To Reproduce

1. Choose Omegascans Connector
2. Select any Manwha
3. No chapters are available
4. No error text is viewed, but when Omegascans is popped out from the Hakuneko app, after a while of loading (it will seem normal with all the manwha but with a loading symbol on the “search series” and on the billboard (?)), it will say, "Application error: a client-side exception has occurred (see the browser console for more information)."

**Comment by MikeZeDev** [comment]
You would not have validated this ticket opening if you had properly followed the instructions inside the template. 
Use nightly, refresh manga list, and next time please read..

![image](https://github.com/manga-download/hakuneko/assets/10671518/4685168c-9adc-4334-a91a-1f7dd2d0942b)
![image](https://github.com/manga-download/hakuneko/assets/10671518/78327ecb-b05a-47a7-a07e-a91dbaa044a4)

In case you really tried nightly, sorry then, people just never read .
Website template changed too much, i had to change manga id fto handle websites that uses new and old template.
In case of doubt, refresh manga list, always.
