### ISSUE TITLE
[Site Request] TCB Scans (new site)

### ISSUE THREAD

**Issue by TKCeegit** [manga-download/hakuneko#7091]
**Name of the website**
TCB Scans

**Website urls (examples below)**
- Site: https://www.tcbscans.net/
- Manga List: https://www.tcbscans.net/manga/
- Manga example: https://www.tcbscans.net/manga/my-hero-academia/
- Chapter online viewer example: https://www.tcbscans.net/manga/my-hero-academia/chapter-423/

**Languages**
English 

**Website relationship*
Looks to be TCB Scans' new site since their previous site https://tcb-scans.com/ is unaccessible now.

**Comment by MikeZeDev** [comment]
Official (.me) has been added to Haruneko, no need for this one
