### ISSUE TITLE
[Site Request] manhwatop.com

### ISSUE THREAD

**Issue by blueboned** [manga-download/hakuneko#7093]
**Name of the website**
manhwatop.com

**Website urls (examples below)**
- Site: https://manhwatop.com/
- Manga List: https://manhwatop.com/manga/
- Manga example: https://manhwatop.com/manga/the-whale-star-the-gyeongseong-mermaid/
- Chapter online viewer example: https://manhwatop.com/manga/the-whale-star-the-gyeongseong-mermaid/chapter-0/

**Languages**
- English

**Website relationship*
- None

**Additional details**
- Null

**Comment by MikeZeDev** [comment]
You didnt even open the app. This website was added 4 years ago 🤦 

![image](https://github.com/manga-download/hakuneko/assets/10671518/1b5d9700-e458-451f-9d21-c3ac47bc0b23)

**Comment by blueboned** [comment]
I apologize for my lack of Research OwO

i thought it was not there because
i searched directly by Manga, not by Website

Whale Star: The Gyeongseong Mermaid this Manhwa can only be found at
ManhwaTop
so i figured that ManhwaTop wasn't on list .



[image: image.png]
