### ISSUE TITLE
[Site Request] Daycomics

### ISSUE THREAD

**Issue by bunsnbiscuits** [manga-download/hakuneko#7094]
**Name of the website**
Daycomics

**Website urls (examples below)**
- Site: https://daycomics.com
- Manga List: https://daycomics.com
- Manga example: https://daycomics.com/content/102010
- Chapter online viewer example: https://daycomics.com/content/102010/126058

**Languages**
English

**Website relationship*
This appears to be the English counterpart to the Korean website, Toptoon, which there is a current connection for.

**Additional details**
N/A

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/ba217230-547b-40a6-9366-14a31e532916)

Can you please not open duplicate issue?
