### ISSUE TITLE
[Site Request] m.happymh.com

### ISSUE THREAD

**Issue by DEVMAX01** [manga-download/hakuneko#7095]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://m.happymh.com/
- Manga List: https://m.happymh.com/latest
- Manga example: https://m.happymh.com/manga/shenwutianzun
- Chapter online viewer example: https://m.happymh.com/reads/shenwutianzun/4408185

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/8a20912e-1359-4c09-87b4-e3a7736c6b27)

Can you please search before opening duplicate issue?

**Comment by MikeZeDev** [comment]
Reading the other issues would have helped you to understand its impossible to do as its redirecting to acqq.
https://github.com/manga-download/hakuneko/issues/6785

**Comment by ZAX-MILLION** [comment]
I am not a programmer, but after conducting some research, I discovered that the redirection issue occurs only in certain countries. For instance, it does not redirect in the UK and Italy, but it does redirect in France. Is there any way to circumvent this issue?

**Comment by MikeZeDev** [comment]
Using a VPN , of course. But if you had read the issue linked previously you would have seen that i tried and then i was hit with Cloudflare. 
https://github.com/manga-download/hakuneko/issues/2933.

When i said give up i mean it. Cloudflare dont like my VPN and switching to others is a pain.

**Comment by ZAX-MILLION** [comment]
thanks for the answers and sorry for the disturb
