### ISSUE TITLE
[Feature] Chapter Range Search

### ISSUE THREAD

**Issue by Alleexxi** [manga-download/hakuneko#7096]
**Is your feature request related to a problem? Please describe.**
I read some chapters from a manga online and i dont want to download the chapters i already read.

**Describe the solution you'd like**
So its possible to search for a chapter range:

List:
Chapter 1
Chapter 2
Chapter 3

Search:
2-3

Output:
Chapter 2
Chapter 3

**Describe alternatives you've considered**
-

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]
Latest

**Comment by Sheepux** [comment]
you can use regexp in the filter: to generate a numeric range you can use https://3widgets.com/
Also haruneko introduced multi chapter selection (shift & ctrl)

**Comment by MikeZeDev** [comment]
Should it be closed? 🤔

**Comment by Alleexxi** [comment]
ig
