### ISSUE TITLE
[<Manganato>] One Punch Man wont show in the hakuneko but on the website it does

### ISSUE THREAD

**Issue by swagkingcole27** [manga-download/hakuneko#7100]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

So , I really wanted to download One-Punch Man from the Manganato thru Hakuneko and when I connected to the Manganato and searched "one punch man " I only found some hentai version of it that is on the website. Im dont really know why is it happening but i've read that it might be URL problem , anyways pls help idk what to do

### To Reproduce

1. Manganato
2. One-Punch Man (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Then paste the manga link? https://hakuneko.download/docs/interface/#manga-list

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/29673299-6a1e-4288-b756-cf5924a26571)
