### ISSUE TITLE
[<mangagezgini>] Connector not working

### ISSUE THREAD

**Issue by NekoManga** [manga-download/hakuneko#7102]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

sad boy not dowland chapters

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
There is no website mangagezgini in hakuneko 🤷 

![image](https://github.com/manga-download/hakuneko/assets/10671518/13f1c8e1-6d22-4c64-b2c3-b4de88cac942)
