### ISSUE TITLE
[Piccoma FR] Connector not working

### ISSUE THREAD

**Issue by kraken56400** [manga-download/hakuneko#7113]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Hello, 

I can't download or open chapters on Piccoma's connector, i have this message : "the chapter 'x' is neither public, nor purchased!'
I have this message on the free's chapters and on the purchased's chapters

For information, i use the 8.3.4 Nightly build

### To Reproduce

1. Name of connector = Piccoma FR
2. Name of manga (if connector update is working) : ex : "la nouvelle vie du mage blanc"
3. Name of chapter (if manga update is working) : free chapter = 1 or 2
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : 
![Capture d'écran 2024-05-29 161411](https://github.com/manga-download/hakuneko/assets/73166542/6e7aa4f2-9cf2-4e56-a57d-425adf54ae5c)

![Capture d'écran 2024-05-29 153730](https://github.com/manga-download/hakuneko/assets/73166542/5facb8fb-0e22-44aa-afeb-20f24910a852)
![Capture d'écran 2024-05-29 153753](https://github.com/manga-download/hakuneko/assets/73166542/11e67862-2d13-4699-ae12-83c3ca394222)

![Capture d'écran 2024-05-29 161516](https://github.com/manga-download/hakuneko/assets/73166542/fd3f2f34-92f6-4271-98c6-84f1b9efe045)
![Capture d'écran 2024-05-29 161555](https://github.com/manga-download/hakuneko/assets/73166542/bed92c36-6d43-4d38-aa70-8f1663fe01cf)

**Comment by MikeZeDev** [comment]
Little api change

**Comment by kraken56400** [comment]
problem resolved thank you very mush :)

**Comment by MikeZeDev** [comment]
Dont close until its merged

**Comment by drakniste** [comment]
Hello

Despite my connection to the Piccoma FR site, the download that I have in my possession fails.,

**Comment by MikeZeDev** [comment]
Yeah, and thats why this issue is opened.

Fix is not **approved** yet, meaning

* It has to be reviewed by another dev. 
* Its still bugged for users 
* Posting other messages just saying "it doesnt work" wont achieve anything. Its a waste of time for everyone.

Thats how development works.

OP just took the fixes changes and patched the file manually so he said that its working. Dont bother doing that .
Use NIGHTLY BUILD and wait.
