### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7120]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Doesn't load the mangalist and when i checked with f12 this is the error.
Name of the website is: https://reaperscans.com/
![image](https://github.com/manga-download/hakuneko/assets/133435955/97bb2b1b-54a9-45c8-bbe4-56e372f7b5c9)

To reproduce simply pick reaperscans in the website field and refresh the manga list.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Dont open duplicate issue, learn to read pls.

https://github.com/manga-download/hakuneko/issues/5488

**Comment by howtopay** [comment]
Sorry I filtered "ReaperScans" when I checked for duplicates but I didn't check "Reaper Scans" with a space my mistake.
