### ISSUE TITLE
[<ManhwaTop>] Connector not working

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7121]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

The chapter list won't load when you click on a manga.
Name: [Manhwatop](https://manhwatop.com/)

### To Reproduce

Select manhwatop in hakuneko
Load the manga's .
Click on a manga.
No chapters load.
![image](https://github.com/manga-download/hakuneko/assets/133435955/f0ffb86d-adf6-461d-a250-6a1726ce4c40)
![image](https://github.com/manga-download/hakuneko/assets/133435955/8afb84a2-a7e1-4129-a2b8-64dd204c953a)

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/a027566a-ddae-4420-a67d-6b317d461148)

**Comment by MikeZeDev** [comment]
You are getting Cloudflared for unknown reasons, and i dont. There is nothing to do . If you really tried nightly *staaaaaare* 

![image](https://github.com/manga-download/hakuneko/assets/10671518/638b1000-cbbd-42f3-87d0-804320e12ecf)

i'd suggest you to use another website. Or retry when they lower CF level.

**Comment by howtopay** [comment]
I was on a vpn, I'm stupid.
