### ISSUE TITLE
[<Mangapark.today>] Website not working

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7122]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The website is down in normal browser and gives error I don't think the website is up anymore.
I would suggest changing it to [Mangapark.net](https://mangapark.net/)

### To Reproduce

1. Name of connector: Mangapark.today
4. ![image](https://github.com/manga-download/hakuneko/assets/133435955/d9323b34-1cc6-4db2-9b62-58d6cad30267)

**Comment by MikeZeDev** [comment]
> I would suggest changing it to [Mangapark.net](https://mangapark.net/)

We are not randomly changing a website for another, that would be a very bad idea. Please dont suggest such thing :D

Website is just dead, we know that for a while. tho
