### ISSUE TITLE
[Site Request] Nero Scans

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7123]
**Name of the website**
Magus Manga And Nero Scans

**Website urls (examples below)**
- Site: https://neroscans.com
- Manga List: https://neroscans.com/?s=
- Manga example: https://neroscans.com/series/8622440958-tyrant-wants-a-better-life/
- Chapter online viewer example: https://neroscans.com/blog/2024/05/02/5628286033-tyrant-wants-a-better-life-chapter-1/

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

It has two names Magus Manga And Nero Scans Both are the same url but different names.

**Additional details**
Add any other context details that you may have found (like template to reuse)

It doesn't have cloudflare.

**Comment by MikeZeDev** [comment]
For some reason i cant find the previous issue, but its already added in haruneko, so i guess there is already an issue for it.

Closing as duplicate
