### ISSUE TITLE
[<MangaDex>] Bug

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7125]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

MangaDex Offers multiple languages English,Indian,French etc.... But this is a problem since it's not separated into a new connector you can't bulk download and if you do you'll end up downloading a bunch of languages, and I don't got the patience to click 200 times depending on the chapters of the manga.

![image](https://github.com/manga-download/hakuneko/assets/133435955/74fb9bcb-b29c-4b54-a869-6e465b7ed2eb)

### To Reproduce

1. Name of connector: MangaDex
2. Select MangaDex as connector
3. Pick Any Manga
4. Bulk Download a bunch of random languages and cry.

**Comment by howtopay** [comment]
It took me 6 minutes just to click to a 100 chapters.......................

**Comment by MikeZeDev** [comment]
Just read the manual it exists for a reason

**Comment by Sheepux** [comment]
Actual response : use the language filter ...
(Mike, chill down)

**Comment by MikeZeDev** [comment]
> Actual response : use the language filter ... (Mike, chill down)

Which is in the manual. 🤷
