### ISSUE TITLE
[Site Request] Hentai20

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7131]
**Name of the website**
Hentai20

**Website urls (examples below)**
- Site: https://hentai20.io/
- Manga List: https://hentai20.io/manga/
- Manga example: https://hentai20.io/manga/dating-sim-short-story-the-dating-simulator-cheat-code/
- Chapter online viewer example: https://hentai20.io/dating-sim-short-story-the-dating-simulator-cheat-code-chapter-1/

**Languages**
English

**Additional details**
__IMPORTANT__
I've seen that there have been previous site requests about hentai20; however, they were closed due to "Cloudflare." However, I checked the site, and their Cloudflare protection is non existent. I even tested it by using curl to download a jpg from the website, and it worked. I also made ChatGPT code a Python script that downloads it based on the manga title, and it worked (I know some Python, so I corrected the errors made by ChatGPT). So, if even a Python script works, then I'm like 99% sure that they lowered or disabled Cloudflare.

**Comment by howtopay** [comment]
So check if Cloudflare is low, or is still there and if it is true then perhaps you could add it?

**Comment by MikeZeDev** [comment]
Search. Use it. And stop opening useless issues 🙏 

https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+hentai20&type=issues
