### ISSUE TITLE
[<Aqua Manga>] Domain Change

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7133]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Domain has changed from aquamanga,com to aquamanga.org.
![image](https://github.com/manga-download/hakuneko/assets/133435955/19dc043a-2109-430e-90fd-a1447a2cf714)

### To Reproduce

1. Select AquaManga
2.Load the manga by refreshing

**Comment by MikeZeDev** [comment]
Next time you open a domain change issue, if the website is down, specify the new url.
