### ISSUE TITLE
[<Void Scans>] Domain Change

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7135]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

So there has been existing issues about voidscans.com releated to infernal void scans but the issue isn't resolved and it is listed as closed (in hakuneko if you pick void scans it still gives 403 error since it is now https://hivescans.com/) and it still says voidscans.com error so it hasn't been updated even tho the issue is listed as closed.

### To Reproduce

Not Needed

**Comment by MikeZeDev** [comment]
Stop reporting every dead website or youll open hundred of issues
