### ISSUE TITLE
[<FunManga>] Website Is Down

### ISSUE THREAD

**Issue by howtopay** [manga-download/hakuneko#7136]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Website is Down no alternative or similar domain has been found.
funmanga.com is down

### To Reproduce

Not Needed

**Comment by MikeZeDev** [comment]
Stop reporting every dead website or youll open hundred of issues 😢 

You see that pinned thing? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/7f5e9085-c3ac-4aea-94b2-a97a80f56429)

Have fun :D
