### ISSUE TITLE
[Bug] Image sizes are inconsistents

### ISSUE THREAD

**Issue by vegaPunk555** [manga-download/hakuneko#7137]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by vegaPunk555** [comment]
Images don't line up in PDF when manga are downloaded, and they have different height and width from one another also when trying to download same chapter comes multiple times in download probably cause of showing multiple translators at once please show proper sites where I can get mangas or manwhas all lined up properly from download

**Comment by MikeZeDev** [comment]
1) Please give a more explicit title than "bug" 😢 
2) Its not directly website related so you are free to delete the template in first message and write your own
3) One problem per issue
4) Use. comma, dots, and carriage returns pls. 

We basically add pictures in PDF as they are on the website. I wonder what can be done about that?
Anyway, PDF is the worst choice when it comes to viewing manga. Using a proper viewer and CBZ or just images would have allowed it to choose a particular zoom / ratio for viewing, perhaps.

Sorry, I didnt understood the rest, tbh (refers to point 4).

**Comment by Sheepux** [comment]
As Mike said: 
- Images are provided as the website provides (use alternative website if you don't like the one you've used. No we don't suggest websites)
- for translators exclusion, use filters
