### ISSUE TITLE
[<Mangageko (mgeko.com)>] Failed to Update manga list.

### ISSUE THREAD

**Issue by Sunghiba** [manga-download/hakuneko#7138]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Mangegeko Website manga list isn't updating. 
This error comes.
Failed to update manga list for mangageko
Cannot Read Property 'textcontent' of undefined.

i've added a screenshot below
![Annotation 2024-06-02 132420](https://github.com/manga-download/hakuneko/assets/171477270/d701f8a3-5557-4cdb-adf4-9178f767f9fe)

### To Reproduce

1. Mangageko
2. Update not working
3. Cannot read property 'textcontent' is undefined.

**Comment by MikeZeDev** [comment]
They changed pagination look LMAO

**Comment by Sunghiba** [comment]
> They changed pagination look LMAO

I've no idea about coding, so do i have to do something like copy paste to fix or ? (
