### ISSUE TITLE
[<ManhwaFreak>] Chapters are not showing up (There was no content error)

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#7144]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

When I try to download or view a new chapter Its showing the below error:
![image](https://github.com/manga-download/hakuneko/assets/95138799/ea02ea87-11fa-44b3-86ee-4dadf2c7f0f4)

In their website I can view any and every chapter without login or pay.

### To Reproduce

1. ManhwaFreak
2. Any Manga
3. Any new chapter

**Comment by MikeZeDev** [comment]
Cloudflare use another website

**Comment by MikeZeDev** [comment]
no more cf
