### ISSUE TITLE
[<Immortal Updates>] Domain Change

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#7145]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The website domain has changed to https://mortalsgroove.com/, I have tried to change the website in the mjs file and it works.

![image](https://github.com/manga-download/hakuneko/assets/95138799/740e916e-7cac-4a94-a830-79141fa24b1d)
![image](https://github.com/manga-download/hakuneko/assets/95138799/e4e7ab27-4bcd-4ad1-a91e-395c0c3163ec)

### To Reproduce

1. Immortal Updates.
2. Refresh list not working

**Comment by Murshid7absi** [comment]
import WordPressMadara from './templates/WordPressMadara.mjs';

export default class MortalsGroove extends WordPressMadara {

    constructor() {
        super();
        super.id = 'mortalsgroove';
        super.label = 'Mortals Groove';
        this.tags = [ 'webtoon', 'english' ];
        this.url = 'https://mortalsgroove.com/';
    }
}

**Comment by MikeZeDev** [comment]
Thanks for telling us.

We are not gonna create another, its the same website after all.
the proper way to submit code is to fork the repository, and make a PR :)

Ofc ill fix the url
