### ISSUE TITLE
[<Rizz Comics>] Connector blocks the IP (Temporarily) after 1 refresh or 1 download - Cloudflare

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#7146]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The website blocks my IP address (Temporarily) after clicking on a new chapter or refreshing the manga list like below it will show the first time viewing its fine, but after clicking on another manga it shows no chapters and blocks my IP(Temporarily):
1.
![image](https://github.com/manga-download/hakuneko/assets/95138799/57ede073-7e6c-4efd-84e1-610399d570a5)
2.
![image](https://github.com/manga-download/hakuneko/assets/95138799/3b5d4bd0-cbb5-4051-82df-0bb1cfa36386)
3.
![image](https://github.com/manga-download/hakuneko/assets/95138799/a4b5897f-e3d0-4d84-8c6b-d593e6b98fad)

### To Reproduce

1. Rizz Comics
2. Any Manga will work
3. go to another manga and it will not work and will block your IP (Temporarily)

**Comment by MikeZeDev** [comment]
There is nothing we can do. Use another website or wait
