### ISSUE TITLE
[Feature] Download without subFolders

### ISSUE THREAD

**Issue by NX171** [manga-download/hakuneko#7151]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have some automation that works on folder only thus I would like to be able to download chapters without creating a subFolder for each mangas. 
Basically, I want all manga to be downloaded directly into one directory since I'm already renaming chapters' names using chapters' Title Format setting.

``` 
# Current download is: 
~/Directory/MangaName/Chap 1.pdf
# What I'd like is : 
~/Directory/Chap 1.pdf
```

**Comment by MikeZeDev** [comment]
Pretty sure id wont be done as there are name collisions risks. You can however use a post command to move files up a directory.

**Comment by NX171** [comment]
Thank You, this is one setting I missed and a good workaround. Everything is working now.

**Comment by NX171** [comment]
Thank You, this is one setting I missed and a good workaround. Everything is working now.

**Comment by Sheepux** [comment]
Could be a feature with a warning in such case (duplicates)
I believe that there aren't many case where you download an item with the same name

**Comment by MikeZeDev** [comment]
> Could be a feature with a warning in such case (duplicates) I believe that there aren't many case where you download an item with the same name

He asked for '/manga folder/\<chaptername>.pdf" . Chapter name is very prone to create duplicates but i may have misunderstood 🤷

**Comment by Sheepux** [comment]
Oh, it's not title name, but chaptername. So indeed: NOPE
Could be a valid case for ~/Directory/MangaName_Chap 1.pdf
