### ISSUE TITLE
[Site Request] comickiba Became ManhuaGold.top

### ISSUE THREAD

**Issue by GuChanggee** [manga-download/hakuneko#7184]
ManhuaGold
Manhuagold

Website urls (examples below)
Site: https://manhuagold.top/
Manga List: https://manhuagold.top/filter
Manga example: https://manhuagold.top/manga/i-am-the-fated-villain
Chapter online viewer example: https://manhuagold.top/manga/i-am-the-fated-villain/chapter-139

Languages
English

*Website relationship
Comickiba.com is now dead and its now completely changed into manhuagold.top
because comickiba.com domain is dead kindly add this as new connecter, i've attached SS of old Comickiba inside tachiyomi
which doesn't work anymore because the domain comickiba.com doesn't lead anywhere (its dead).

Additional details
![image](https://github.com/manga-download/hakuneko/assets/172676072/981eacfa-b568-43ed-b366-590a1cefeca7)
![image](https://github.com/manga-download/hakuneko/assets/172676072/6543167d-1985-4299-b439-fba96a6a9034)

![image](https://github.com/manga-download/hakuneko/assets/172676072/981eacfa-b568-43ed-b366-590a1cefeca7)
![image](https://github.com/manga-download/hakuneko/assets/172676072/6543167d-1985-4299-b439-fba96a6a9034)

there was another closed issue in march related to this but ig its not solved yet.
https://github.com/manga-download/hakuneko/issues/6875

**Comment by MikeZeDev** [comment]
You didnt follow the instructions which are "try nightly". Yet you checked "ive tried nightly".
Because its fixed on nightly

Please dont open useless tickets and say stuff like "its not fixed" when its fixed.
