### ISSUE TITLE
[Manhuagold] Cant get manga list or chapters

### ISSUE THREAD

**Issue by GuChanggee** [manga-download/hakuneko#7185]
Comickiba now Known as Manhuagold.top Doesn't Work In Nightly Either, It gives timeout and doesn't load manga list. (if doubtfull please check)
thank you for what you do and kindly fix it asap i need some manhua in my life.

![image](https://github.com/manga-download/hakuneko/assets/172676072/9c3ae3de-001c-4f71-b278-5b2362c9ac6f)
![image](https://github.com/manga-download/hakuneko/assets/172676072/0b7038c6-a69f-4ec9-9291-0973948895b1)

**Comment by GuChanggee** [comment]
![image](https://github.com/manga-download/hakuneko/assets/172676072/14b0f56f-615a-4115-b872-5003c79de34f)
![image](https://github.com/manga-download/hakuneko/assets/172676072/e2c9ef71-5fe6-4a7c-932d-cc30e147112d)
nope not loading

**Comment by MikeZeDev** [comment]
AH they changed for .com ?

**Comment by MikeZeDev** [comment]
Website changed something, my bad
