### ISSUE TITLE
[Site Request] https://kunmanga.com/

### ISSUE THREAD

**Issue by Reoira** [manga-download/hakuneko#7193]
**Name of the website**
[kunmanga](https://kunmanga.com/)

**Website urls (examples below)**
- Site: https://kunmanga.com/
- Manga List: https://kunmanga.com/manga/
- Manga example: https://kunmanga.com/manga/a-stepmothers-marchen/
- Chapter online viewer example: https://kunmanga.com/manga/a-stepmothers-marchen/chapter-0/

**Languages**
English

**Website relationship*

**Additional details**

**Comment by MikeZeDev** [comment]
Duplicate : https://github.com/manga-download/hakuneko/issues/7076.

Please search before opening issues
