### ISSUE TITLE
[<Line Webtoon (English)>] Connector not working

### ISSUE THREAD

**Issue by CoCuCoH41k** [manga-download/hakuneko#7194]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I used a Webtoon downloader before, but from latest week or earlier i got a ERR_CONNECTION_RESET every time when im trying to use it. i tried hakuneko, but still this error. 
![image](https://github.com/manga-download/hakuneko/assets/70099291/2768ff06-8e27-43e1-b674-1d8b938c6d45)

### To Reproduce

1. Line Webtoon (English)
2. Any manga
3. Any chapter
4. ![image](https://github.com/manga-download/hakuneko/assets/70099291/2768ff06-8e27-43e1-b674-1d8b938c6d45)

**Comment by MikeZeDev** [comment]
If you got the same error than with the other downloader, perhaps the problem is on your end? 🤷 

Edit : tried a random "canvas" url, it works : 
![image](https://github.com/manga-download/hakuneko/assets/10671518/23a09c38-d8e9-447a-98a4-2f185d0af4af)

Checked website in browser? Antivirus ? 🤷
