### ISSUE TITLE
[mangafreak] Connector not working

### ISSUE THREAD

**Issue by czarnynight** [manga-download/hakuneko#7195]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

website changed it's address and i can't download any manga from it since then. 
current name and dominie is https://ww1.mangafreak.me 
previous was 
w15.mangafreak.net

### To Reproduce

1. mangafreak
2. all, for eg TENSEI SHITARA SLIME DATTA KEN 
3. don't see them
4. index.html:46 Loading Engine: HakuNeko
hakuneko://plugins/:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
Settings.mjs:349 Failed to load HakuNeko settings! Error: ENOENT: no such file or directory, open 'C:\Users\Nu-13\Downloads\+\hakuneko-desktop_8.3.4_windows-portable_amd64\userdata\hakuneko.settings'
load @ Settings.mjs:349
index.html:61 Loading Frontend: frontend@classic-light
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
loadClassicPolymer @ index.html:76
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\Nu-13\Downloads\+\hakuneko-desktop_8.3.4_windows-portable_amd64\userdata\hakuneko.mangas.mangafreak'
(anonymous) @ Connector.mjs:215
MangaFreak.mjs:22 Assigned URL 'https://mangafreak.net' to MangaFreak
ww1.mangafreak.me/Manga/Tensei_Shitara_Slime_Datta_Ken:1 Failed to load resource: the server responded with a status of 403 ()

**Comment by MikeZeDev** [comment]
Fine, gotta update that but it'spointless as website use Cloudflare

**Comment by czarnynight** [comment]
mind me asking why it's pointless ? it's not the only manga website on it.

**Comment by MikeZeDev** [comment]
Please dont close the issue by yourself .
Website use Cloudflare, meaning even with good url it wont work.

If you had searched before opening an issue (like you should have) you would have seen the mangafreak one 😏 and perhaps not opened this one.
