### ISSUE TITLE
error occurs when downloading mangas

### ISSUE THREAD

**Issue by DDS55** [manga-download/hakuneko#7198]
Yes, I read [the troubleshooting guide]

error occurs when downloading mangas

Push the button to download

download of mangas

 Windows10
 HakuNeko Version 6.17

I started downloading a lot of mangas with the program, but after I did a system restore because of problems caused by Windows Updates, I was never able to download mangas using the program again. Could you help me?
![3](https://github.com/manga-download/hakuneko/assets/173188330/3a254cca-3d3e-4aa3-9111-b6289458e8a2)

**Comment by MikeZeDev** [comment]
Issue not properly filled. Critical informations missing.
