### ISSUE TITLE
[<YoungChampion & ChampionCross>] Connector not working

### ISSUE THREAD

**Issue by iKyel** [manga-download/hakuneko#7200]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

The list is not working
![Screenshot 2024-06-20 163530](https://github.com/manga-download/hakuneko/assets/111947701/a83d4c70-2d49-4f7b-a29a-36ba7c892125)

### To Reproduce

1. YoungChampion and ChampionCross
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
You pasted /episodes/ links. Hakuneko need a /series/ link

I.e https://youngchampion.jp/series/a8dc41f0c15bd

Like the ones on this page : https://youngchampion.jp/series/list

Same for Championcross. Not sure why you used clipboard tho

**Comment by MikeZeDev** [comment]
That said, manga list need a little fix :D

**Comment by iKyel** [comment]
> You pasted /episodes/ links. Hakuneko need a /series/ link
> 
> I.e https://youngchampion.jp/series/a8dc41f0c15bd
> 
> Like the ones on this page : https://youngchampion.jp/series/list
> 
> Same for Championcross. Not sure why you used clipboard tho

how dumb am i, sorry for wasted your time

**Comment by MikeZeDev** [comment]
Its fine its not exactly user friendly.
