### ISSUE TITLE
[Site Request] Sushi-scan

### ISSUE THREAD

**Issue by Mikkoww** [manga-download/hakuneko#7205]
**Name of the website**
Sushi-scan

**Website urls (examples below)**
- Site: https://sushiscan.net
- Manga List: https://sushiscan.net/catalogue/
- Manga example: https://sushiscan.net/catalogue/2-wind-breaker-nii-satoru/
- Chapter online viewer example: https://sushiscan.net/wind-breaker-nii-satoru-chapitre-112/

**Languages**
French

**Comment by MikeZeDev** [comment]
🤦 

Are you kidding? 


https://github.com/manga-download/hakuneko/blob/7171aa22bf9c944dc2487fc5141df58ea63a9b0a/src/web/mjs/connectors/SushiScans.mjs#L4
