### ISSUE TITLE
[Site Request] komikindo.link

### ISSUE THREAD

**Issue by wow2134** [manga-download/hakuneko#7207]
**komikindoMe**
komikindo.link

**Website urls (examples below)**
- Site: https://komikindo.link/
- Manga List: https://komikindo.link/manga/
- Manga example: https://komikindo.link/manga/a-man-who-takes-away/
- Chapter online viewer: https://komikindo.link/a-man-who-takes-away-chapter-01/

**Languages**
Indonesian

**Website relationship*
kanzenin.info
komiktap.me

**Additional details**
My country really likes blocking websites, so this is one of the mirror websites that is not blocked. Hopefully this won't be blocked later

**Comment by MikeZeDev** [comment]
Duplicate issue. Search before !
https://github.com/manga-download/hakuneko/issues/7008

**Comment by wow2134** [comment]
okay sorry my mistake
