### ISSUE TITLE
Doesn't open on macOS

### ISSUE THREAD

**Issue by AlexoDess211** [manga-download/hakuneko#7209]
I'm on macOS Sequoia 15 Developer beta, and hakuneko can't be opened because of the Apple security thing. I tried double-click, didn't work. Right click > Open, didn't work. How do I do ?
<img width="307" alt="Screenshot" src="https://github.com/manga-download/hakuneko/assets/128230185/47b116b7-1328-48dc-a753-c11eb8832afb">
Image translation in English:
"HakuNeko Desktop.app" app didn't open
Apple could not confirm that the app "HakuNeko Desktop.app" doesn't contains malware susceptible to cause damage to your Mac or violate your privacy.
Blue button text : Place in the bin
Grey button text : Done

**Comment by MikeZeDev** [comment]
C'est un problème général sur Mac je crois et ca n'a pas particulièrement de choses à voir avec Hakuneko.

Une petite recherche google aurait été plus adéquate que de demander ici :) Malheureusement je n'ai aucune idée du comment ne possédant pas de Mac.

**Comment by Sheepux** [comment]
https://support.apple.com/fr-fr/guide/mac-help/mh40616/mac
