### ISSUE TITLE
[ReadComicOnline.li] Connector not working

### ISSUE THREAD

**Issue by OnagasVessel** [manga-download/hakuneko#7214]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

i try to read something from here but everything is showing as chapter 0/0 when I look at a title, and when i refresh, nothing happens 

### To Reproduce

1. Name of connector - readcomicsonline.li
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Got chapters, manga list is refreshing. 
Cant diagnose with more informations : manga link, console output that appears when errors occurs (Press F12)

Keep in mind that this website is prone to have bad servers, Recaptcha and Cloudflare anti bot.

**Comment by OnagasVessel** [comment]
Manga link - https://readcomiconline.li/Comic/Action-Comics-1938

console output - Failed to load resource: the server responded with a status of 403 ()

**Comment by MikeZeDev** [comment]
Error 403 for this website mean you were either hit by Cloudflare (give up) or rate limited / temp banned / banned.
Could you provide a screenshot of the Network request that end with the 403 error and make sure the screenshots display the server response like the HTML on the right.

Similar to this . 
![image](https://github.com/manga-download/hakuneko/assets/10671518/2558d4aa-25c7-4e5a-bab1-290842b2816d)

Your problem wont be solved but its interesting to see if its CloudFlare again or just a rate limit.

**Comment by MikeZeDev** [comment]
Closed because no more feedback provided, and its probably Cloudflare.
