### ISSUE TITLE
[<Manwha Freak>] They opened a new website

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#7215]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Domain change

New Domain: https://manhwafreak.site/

### To Reproduce

1. Name of connector: Manwha Freak
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
But the org website still works.

**Comment by IsamiTahara** [comment]
It does but, I can't view or download new chapters.

**Comment by MikeZeDev** [comment]
> It does but, I can't view or download new chapters.

Because they are on the other website. No wonder. Its not a bug anyway.

**Comment by MikeZeDev** [comment]
Dead website
