### ISSUE TITLE
Bato (byAnyACG) Connector not working

### ISSUE THREAD

**Issue by Nanashi87** [manga-download/hakuneko#7220]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

The site opens even on the connector popup but the chapters won't show images or download, have tried multiple manga/chapters .  The chapters and manga does seem to update but attempting to show images in viewer or download times out, showes the over 60 sec popup.
![hn](https://github.com/manga-download/hakuneko/assets/37065458/0d4c2414-d36b-416d-a68c-955cfb479e74)
![hn1](https://github.com/manga-download/hakuneko/assets/37065458/110c8743-c2a9-4a67-9a9a-6d8a34a3aac2)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Fix your website url in settings. See the double //?

**Comment by Nanashi87** [comment]
Thank you, when I updated the site address in settings I can't believe I missed that.
