### ISSUE TITLE
[Webtoons.com] Connector not working

### ISSUE THREAD

**Issue by BeamerPi** [manga-download/hakuneko#7221]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

attempting to retrieve manga from line webtoons [english] using manual URL Copy & Paste method since the site doesn't have a manga list according to the HakuNeko interface.
After clicking on the clipboard, the manga shows in the list but chapters lists do not populate.

### To Reproduce

1. Name of connector 
[Line Webtoons (English)]

2. Name of manga (if connector update is working)
Freaking Romance
connector does not work, used manual URL clipboard entry
https://www.webtoons.com/en/romance/freaking-romance/episode-16-not-a-threat/viewer?title_no=1467&episode_no=16

3. Name of chapter (if manga update is working)
episode 16

4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
no error message is displayed
console log:
Connector.mjs:215 _getUpdatedMangasFromFile Error: ENOENT: no such file or directory, open 'C:\Users\user\AppData\Roaming\hakuneko-desktop\hakuneko.mangas.linewebtoon-en'
(anonymous) @ Connector.mjs:215
Connector.mjs:579 Error: This website does not provide a manga list, please copy and paste the URL containing the chapters directly from your browser into HakuNeko.
    at LineWebtoonEN._getMangas (LineWebtoon.mjs:43)
    at LineWebtoonEN._getMangaList (Connector.mjs:576)
    at Connector.mjs:99 LineWebtoonEN
_getMangaList @ Connector.mjs:579
index.html:1 A cookie associated with a cross-site resource at http://webtoons.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
index.html:1 A cookie associated with a resource at http://webtoons.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
index.html:1 A cookie associated with a cross-site resource at http://www.webtoons.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
Settings.mjs:420 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
(anonymous) @ Settings.mjs:420
DevTools failed to parse SourceMap: hakuneko://cache/js/protobuf.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/js/hls.light.min.js.map
DevTools failed to parse SourceMap: hakuneko://cache/sm/4f4f84956292156efc04b79e1131dc7c3a51794b7b3d62b43ed5eaca1b36d71e.map

**Comment by MikeZeDev** [comment]
If you pasted this : https://www.webtoons.com/en/romance/freaking-romance/episode-16-not-a-threat/viewer?title_no=1467&episode_no=16 

you pasted a **chapter** URL. Hakuneko need a **manga** url .

There is no chapter list in the page you pasted, so hakuneko cant list chapters, its simple.

![image](https://github.com/manga-download/hakuneko/assets/10671518/4cf39286-7d64-4910-8307-ce48c75feb7b)

**Comment by BeamerPi** [comment]
Thank you, my mistake. (troubleshooting for a friend and was assured the URL was the one needed)

**Comment by BeamerPi** [comment]
Sorry once again, so the problem is that the chapters after 16 won't show up. They are behind a daily pass mechanism that seems to only be available via the mobile interface for webtoons. if signed into their account they can view chapter 17 and 18 on their phone, but cannot view them from HakuNeko. (I hope this gets viewed)
@MikeZeDev

**Comment by MikeZeDev** [comment]
Login in Hakuneko before pasting perhaps?
