### ISSUE TITLE
[MintManga] Connector not working

### ISSUE THREAD

**Issue by XyHbDyHb** [manga-download/hakuneko#7230]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

MintManga (old URL: https://23.mintmanga.live/) split site in two: 
1) new URL for MintManga is https://mintmanga.com/
2) new site URL is https://seimanga.me/ (related issue #7118)

### To Reproduce

1. MintManga
2. any
3. any
4. -

**Comment by MikeZeDev** [comment]
* old url is still alive (its 24 and not 23 but 23 redirect to 24 so its fine) and Hakuneko seems to work

![image](https://github.com/manga-download/hakuneko/assets/10671518/2be1616e-62ca-4336-a51c-353adc00cff5)

* there is already an issue for seimanga

As long as old url still work its not really an url change its a new website. If you want the com one open a website suggestion ticket.

Spoiler : the team dont add websites to Hakuneko anymore as we are working on Haruneko. It may eventually ends up in Haruneko.
