### ISSUE TITLE
[<BlogTruyen>] Missing mangas in list

### ISSUE THREAD

**Issue by Beanbaba** [manga-download/hakuneko#7240]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Some manga is not in the list. but the website still have them.

### To Reproduce

1. Name of connector : https://blogtruyenmoi.com/
2. Name of manga (if connector update is working)
https://blogtruyenmoi.com/23693/girls-und-panzer-ribbon-no-musha
and other manga have name GIRLS und PANZER

**Comment by MikeZeDev** [comment]
Use copy paste

![image](https://github.com/manga-download/hakuneko/assets/10671518/ea0b1b7f-9876-4247-a6f9-56361ef605ef)

Edit : Gathering manga list is troublesome, you get stopped by server after a few request, we cant do miracles. Like i've said, pasting is the solution.

![image](https://github.com/manga-download/hakuneko/assets/10671518/fce137ef-8caf-4787-80f3-bc2ac9672aa0)
