### ISSUE TITLE
Can't load the page (Doujindesu)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#725]
when i try to use the browser feature this the result:
![doujindesu](https://user-images.githubusercontent.com/45929526/69836836-25f1bc00-127e-11ea-86d9-4f2da7d38e37.PNG)

**Comment by 27136773** [comment]
Probably new domain

**Comment by MIRVOUS** [comment]
this  the new url = "https://www.doujindesu.in/"

**Comment by dodieboy** [comment]
should be fixed now

**Comment by 27136773** [comment]
Verified, works for me with singapore proxy
