### ISSUE TITLE
Manga Galaxy

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7250]
**Name of the website**
Manga Galaxy

**Website urls (examples below)**
- Site: https://mangagalaxy.me/
- Manga List: https://mangagalaxy.me/series/
- Manga example: https://mangagalaxy.me/series/genesis-of-the-battle-god/
- Chapter online viewer example: https://mangagalaxy.me/genesis-of-the-battle-god-chapter-1/

**Languages**
English
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Murshid7absi** [comment]
Site: https://mangagalaxy.org/
Manga List: https://mangagalaxy.org/series/
Manga example: https://mangagalaxy.org/series/genesis-of-the-battle-god/
Chapter online viewer example: https://mangagalaxy.org/genesis-of-the-battle-god-chapter-1/
