### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by ilikepokemon2009** [manga-download/hakuneko#7251]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

When I try to connect with mangadex in the connector section, it won't connect. This error message(listed below) is what pops up:
![image](https://github.com/manga-download/hakuneko/assets/94278435/1bcbdffa-a427-460d-a4d9-0d50a0750aa7)

any way to fix this?

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Increase throttling in settings or use clipboard. There is nothing we can do its their servers

**Comment by ilikepokemon2009** [comment]
Clipboard??

**Comment by ilikepokemon2009** [comment]
wait nvm
