### ISSUE TITLE
[Site Request] Komiklovers

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#7252]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://komiklovers.com/
- Manga List: https://komiklovers.com/komik/?order=update
- Manga example: https://komiklovers.com/komik/the-possessed-genius-gaming-stream/
- Chapter online viewer example: https://komiklovers.com/the-possessed-genius-gaming-stream-chapter-11/

**Languages**
List of languages supported by the website
-Indonesia
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
You cant even remember your own issue? 🥇 https://github.com/manga-download/hakuneko/issues/7066
