### ISSUE TITLE
[Manhwax] Connector not working

### ISSUE THREAD

**Issue by LazyPandaSenpai** [manga-download/hakuneko#7253]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Reconstruction of the bug:
1. Select the "Manhwax"-Connector
2. Click the Refresh Button

The Manga list is not refreshing. The Refresh is done after 5 seconds and nothing happens.

I also didn't find any configurable variables in the settings.
Is the connector nno longer supported?

### To Reproduce

Reconstruction of the bug:
1. Select the "Manhwax"-Connector
2. Click the Refresh Button

No error-messages, because nothing is happening

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/71b0446b-d324-4aec-bd47-226baf65559e)

![image](https://github.com/user-attachments/assets/231d9a4a-e73a-4743-a2d2-2ea50fe0e963)

Issue instructions are not just decorations :D

**Comment by MikeZeDev** [comment]
its org now
