### ISSUE TITLE
[Tapas] Chapter not listed

### ISSUE THREAD

**Issue by yimeji** [manga-download/hakuneko#7256]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

1) Hakuneko able to recognize series but no chapter will be listed when clicked.

2) Chapter images cannot be viewed/won't load on Hakuneko browser but can be view on regular browser (chrome/firefox).

### To Reproduce

1. select a series and copy series URL (ex: https://tapas.io/series/tomorrows-number-1/)
2. paste URL on Hakuneko and series title appear
3. click on series title
4. No chapter is listed.

**Comment by MikeZeDev** [comment]
we already know https://github.com/manga-download/hakuneko/pull/7222
