### ISSUE TITLE
[Site Request] Lezhin Spanish

### ISSUE THREAD

**Issue by cloudbladed1** [manga-download/hakuneko#7258]
**Name of the website**
Lezhin Es

**Website urls (examples below)**
- Site: https://www.lezhin.es/
- Manga List: none
- Manga example: https://www.lezhin.es/detail/drivers-high
- Chapter online viewer example: https://www.lezhin.es/viewer/drivers-high/1

**Languages**
Spanish

**Website relationship*
Lezhin English
Lezhin Japanese
Lezhin Korean

**Additional details**

None

**Comment by MikeZeDev** [comment]
Would you care to search first please? https://github.com/manga-download/hakuneko/issues/4110
Plus, its already done in Haruneko 😮‍💨
