### ISSUE TITLE
[<Hakuneko>] hakuneko shows blank/white screen. there is no errors in the console, there is actually nothing at all in the console

### ISSUE THREAD

**Issue by Hannahcide** [manga-download/hakuneko#7259]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

hakuneko shows blank/white screen. there is no errors in the console, there is actually nothing at all in the console

### To Reproduce

![image](https://github.com/user-attachments/assets/95b36ff7-61f0-4246-9fe1-1ab9c4457c97)

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/3431
