### ISSUE TITLE
Please this website wutopiacomics

### ISSUE THREAD

**Issue by hemantkgurjar** [manga-download/hakuneko#726]
Please add https://www.wutopiacomics.com/

**Comment by 27136773** [comment]
Layout looks similar to one of the exisitng websites... need to find which one and if the template is compatible

**Comment by skymach2083** [comment]
please add htpps://serimanga.com

**Comment by 27136773** [comment]
> please add htpps://serimanga.com

This ticket is for wutopiacomics, serimaga is already tracked in #461

**Comment by Robonau** [comment]
this should be closed wutopia comics was implemented
