### ISSUE TITLE
[Site Request] Visualikigai

### ISSUE THREAD

**Issue by cloudbladed1** [manga-download/hakuneko#7263]
**Name of the website**
Visualikigai

**Website urls (examples below)**
- Site: https://visualikigai.com
- Manga List: https://visualikigai.com/series/lucia/
- Manga example: https://visualikigai.com/series/lucia/
- Chapter online viewer example: https://ikigaimangas.ragnarokscanlation.net/capitulo/986122395577319425/

**Languages**
Spanish

**Website relationship*
Yugenmanga, but it does not exist, ikigaimangas, now they have changed domains again.

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
https://visorikigai.nipase.com/

**Comment by MikeZeDev** [comment]
No more series, gotta rename it as https://github.com/manga-download/hakuneko/issues/7419
