### ISSUE TITLE
[<EarlyManga>] Connector not working

### ISSUE THREAD

**Issue by La-michi** [manga-download/hakuneko#7266]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

When i try to refresh to get manga list, it gives an error
![image](https://github.com/user-attachments/assets/b821e7fa-ded4-482b-b4b0-4a43073f408d)

I've Checked The Last time Commit was on  (Jan 3, 2023),
Kindly Fix it, Thanks a lot.

### To Reproduce

Site name - EarlyManga
Site url - https://earlym.org/home
error -
![image](https://github.com/user-attachments/assets/ebb16d2d-41bd-4408-8e7e-942a50c19c5c)

**Comment by MikeZeDev** [comment]
Okay. What did they do again. 😔

**Comment by La-michi** [comment]
> Okay. What did they do again. 😔

No Idea 💡

**Comment by MikeZeDev** [comment]
If you really want it working use [Haruneko](https://github.com/manga-download/haruneko)

**Comment by MikeZeDev** [comment]
Website is dead
