### ISSUE TITLE
[<ComicK>] Manga list isn't Complete?

### ISSUE THREAD

**Issue by La-michi** [manga-download/hakuneko#7269]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hi, ComicK (https://comick.io/), Have more than 30,000 manga, But when refresh the Hakuneko Comick Connecter only loads 1400.
![image](https://github.com/user-attachments/assets/a4f9fed1-e349-4cab-bcfc-fff79bc52a96)

### To Reproduce

ComicK ([https://comick.io/](https://comick.io/))
for example this manhua is on comicK website but isn't in Hakuneko Connector.
[https://comick.io/comic/catastrophic-necromancer
](https://comick.io/comic/catastrophic-necromancer
)
also kindly increase timeout current timeout is 60 sec which cannot load 30,000+ site (after fixing).

**Comment by MikeZeDev** [comment]
Read previous issues
