### ISSUE TITLE
Agitoon (changing the domain)

### ISSUE THREAD

**Issue by Mehrdad1391** [manga-download/hakuneko#7270]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Hi, I wanted to ask if there is way for me to change Agitoon website manually in the Hakuneko or not? If there is no way for it I wanted to ask you to change it from 'https://agit185.come' to 'https://agitwebtoon.xyz'. Since the https://agitwebtoon.xyz/ site doesn't need any cloudflare pass, If you could it do it I would really appreciate it. thanks for all of your hard work.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Not sure we should do that. Haruneko (note the RU) is totally able to bypass CloudFlare, we should stick to the "official" url 🤷

**Comment by MikeZeDev** [comment]
Cant reach website
