### ISSUE TITLE
[Site Request] nicomanga

### ISSUE THREAD

**Issue by iKyel** [manga-download/hakuneko#7273]
**Name of the website**
Nicomanga

**Website urls (examples below)**
- Site: https://nicomanga.com/
- Manga List: https://nicomanga.com/manga-list.html
- Manga example: https://nicomanga.com/manga-seinaru-otome-to-himegoto-wo.html
- Chapter online viewer example: https://nicomanga.com/read-seinaru-otome-to-himegoto-wo-chapter-1.html

**Languages**
English

**Website relationship*
https://weloma.art/
https://welovemanga.one/

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6398 .Search Feature,  use it. otherwise you kills kittens.

![image](https://github.com/user-attachments/assets/5b56678c-6c40-4f18-9a66-c32e2f6648ff)

**Comment by iKyel** [comment]
> Duplicate #6398 .Search Feature, use it. otherwise you kills kittens.
> 
> ![image](https://private-user-images.githubusercontent.com/10671518/350550451-5b56678c-6c40-4f18-9a66-c32e2f6648ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NDc5NjIsIm5iZiI6MTcyMTQ0NzY2MiwicGF0aCI6Ii8xMDY3MTUxOC8zNTA1NTA0NTEtNWI1NjY3OGMtNmM0MC00ZjE4LTlhNjYtYzMyZTJmNjY0OGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDAzNTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2M2RjODYzY2Q5YzQ1M2RlYTM0MDRiYmE1M2QyMjI2M2YzYjVhZmViYzBlYjNhNTJhYjE4NTQ2ODJmYjhkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OIgrkPLr-0I0cocKuMHzTHMrRpT6GCsZAg5xaUKlAk8)

I'm sorry, because I did not find the connector in Haku and Haru's source code, so I thought it was not mentioned.
