### ISSUE TITLE
[Site Request] gogoanime (anitaku), for anime

### ISSUE THREAD

**Issue by jacobgerritz** [manga-download/hakuneko#7276]
**Name of the website**
Gogoanime

**Website urls (examples below)**
- Site: anitaku.to
- Manga List: https://anitaku.pe/anime-list.html
- Manga example: https://anitaku.pe/category/monster
- Chapter online viewer example: https://anitaku.pe/monster-episode-16

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Are you, perhaps, kidding? https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+gogoanime&type=issues

Duplicate
