### ISSUE TITLE
[Site Request] Vortex Scans

### ISSUE THREAD

**Issue by Lordsneak** [manga-download/hakuneko#7277]
**Name of the website**
Vortex Scans

**Website urls (examples below)**
- Site: https://vortexscans.org/home
- Manga List: https://vortexscans.org/series
- Manga example: https://vortexscans.org/series/ranker's-return
- Chapter online viewer example: https://vortexscans.org/series/ranker's-return/chapter-1

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Use Haruneko 

https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/VortexScans.ts

**Comment by Lordsneak** [comment]
> Use Haruneko
> 
> https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/VortexScans.ts

How to use Haruneko, I don't know how to run app ? any tutorial please.

**Comment by ghost** [comment]
@Lordsneak I don't really know how to properly use the browser extention haruneko either, but at least here is [the repository of Haruneko](https://github.com/manga-download/haruneko/releases). I don't really know why there is a new version of it now, but you can see by the dates that this is the current version of hakuneko. [Here](https://haruneko-docs.pages.dev/user-manual/setup.html) is also the user manual of Haruneko, which includes some tutorials on how to install and use it, though there are still some sections left out. I hope this helps
