### ISSUE TITLE
mangafire

### ISSUE THREAD

**Issue by rigobertox60** [manga-download/hakuneko#7278]
### Is there an existing issue for this connector?

- [ ] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Manga fire shows all mangas available but no chapters. 

### To Reproduce

1. Manga fire
2. Any manga
3. all chapters are unavailable
4. none

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/21c94eaf-67b4-4c9f-b29a-970880cad8d8)

Cant reproduce.  Please specify a manga for testing. Make sure you properly followed instructions

**Comment by rigobertox60** [comment]
[image: image.png]

Im selecting the same manga, but for me it says, 0/0 chapter

**Comment by rigobertox60** [comment]
Im selecting the same manga, but for me it says, 0/0 chapter
![Screenshot 2024-07-26 090153](https://github.com/user-attachments/assets/77d08a14-c276-4d0e-9aa0-fc14461b19e7)

**Comment by rigobertox60** [comment]
this happens with any manga, With mangafire connector. i tried other connectors, they work.

**Comment by MikeZeDev** [comment]
I need to make sure you didnt check boxes without reading and that you tried the proposed solutions before opening a ticket for something that is already solved 👀 . A problem with chapters was identified and fixed 9 months ago and if you had read properly the issue's template you probably wouldnt have opened the issue at all as the solution is most likely inside.

**Comment by MikeZeDev** [comment]
In other words, did you try nightly like its suggested? Because you said yes.

![image](https://github.com/user-attachments/assets/b99a82e1-4da8-4605-8425-89fcb8defcbc)

**Comment by rigobertox60** [comment]
I assumed this asked if i had download nightly build, i have. Also it was working for about a week. than it stopped working. first chapters didnt load, now manga dont download either. I refresh it

**Comment by MikeZeDev** [comment]
No need to redownload it. 

Press F12, try to get chapters, what does console said ?

**Comment by rigobertox60** [comment]
I press f12 this is what it gives me
![Screenshot 2024-07-27 083646](https://github.com/user-attachments/assets/588121c6-a2e4-421f-ad21-834e84ba27fc)
![Screenshot 2024-07-27 083700](https://github.com/user-attachments/assets/672bfee9-dcf9-4dab-911b-3aba5b2b874a)
![Screenshot 2024-07-27 083709](https://github.com/user-attachments/assets/63bafb5d-0372-43fa-a78f-43fe7f887e48)

**Comment by MikeZeDev** [comment]
So for some reason the website blocks you. Are you able to open it in browser? Did you check after deactivating antivirus, firewall? 
Did you tried with a VPN? i dont have such problems 🤷

**Comment by rigobertox60** [comment]
i can access mangafire no problem on my browser, on all my devices. I Also disabled my antivirus / Firewalls and And re launched hakuneko and it doesnt fix anything. i do not have a vpn.

**Comment by MikeZeDev** [comment]
Then i am afraid i dont know whats going on. This error 403 is not reproductible
