### ISSUE TITLE
[Toonily.com] Connector not working

### ISSUE THREAD

**Issue by forestpas3** [manga-download/hakuneko#7292]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Two days ago it work properly. The site was down for a day for updates. HakuNeko can't connect since.

```
Failed to update manga list for Toonily
Cannot read property 'href' of undefined
```

### To Reproduce

1. Name of connector : Toonily
2. _Name of manga (if connector update is working)_
3. _Name of chapter (if manga update is working)_
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
```
Connector.mjs:434 GET https://toonily.com/ 500
fetchDOM @ Connector.mjs:434
_getMangas @ Toonily.mjs:34
_getMangaList @ Connector.mjs:576
(anonymous) @ Connector.mjs:99
Promise.then (async)
updateMangas @ Connector.mjs:98
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96
Connector.mjs:579 TypeError: Cannot read property 'href' of undefined
    at Toonily._getMangas (Toonily.mjs:35)
    at async Toonily._getMangaList (Connector.mjs:576) Toonily {id: "toonily", label: "Toonily", tags: Array(3), isLocked: false, initialized: true, …}
```

**Comment by MikeZeDev** [comment]
weird 500 error, hum. You got the same if you try do disable family mode on their website. Since we do that by default, we got the error.

I wonder what to do. Clearing that "adult" flag will reduce the available manga to a mere 300 when there was more than 1000.

**Comment by forestpas3** [comment]
> weird 500 error, hum. You got the same if you try do disable family mode on their website. Since we do that by default, we got the error.
> 
> I wonder what to do. Clearing that "adult" flag will reduce the available manga to a mere 300 when there was more than 1000.

I just saw on their discord, it seems it is an error on their side and not Hakuneko.
TBH, I did not check when I put the issue in, if by changing the family mode changes anything.
I will close the issue if their fix for their site fixes Haku.

**Comment by forestpas3** [comment]
It was because of the family mode.
Closing the issue.
