### ISSUE TITLE
[Site Request] https://manta.net/en

### ISSUE THREAD

**Issue by manhwamyworld** [manga-download/hakuneko#7295]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://manta.net/en
- Manga List: https://manta.net/en
- Manga example: https://manta.net/en/series/under-the-oak-tree?seriesId=1255
- Chapter online viewer example: https://manta.net/en/series/under-the-oak-tree/episodes/s1-episode-1?episodeId=4782

**Languages**
List of languages supported by the website
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
Manhuatop

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
>  Manhuatop? 

I fail to see relationship between them.

Also, did you read previous issues? 
https://github.com/manga-download/hakuneko/issues/6089
https://github.com/manga-download/hakuneko/issues/5333

Third party Login is a PAIN.  I leave that open in case someone want to do it.
