### ISSUE TITLE
[Pixiv Comics] Download aren't working

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#7297]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Pixiv Comics change episode's api path from ``https://comic.pixiv.net/api/app/episodes/<episodenumber>/read_v3`` to  ``https://comic.pixiv.net/api/app/episodes/<episodenumber>/read_v4``, and download aren't working after this update.

### To Reproduce

1. Name of connector: Pixiv Comics
2. Name of manga (if connector update is working): All
3. Name of chapter (if manga update is working): All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![image](https://github.com/user-attachments/assets/9fce02df-13a9-4723-a146-41d3cfab4bc4)

from browser's devtool
![image](https://github.com/user-attachments/assets/a6958c40-6a3c-45eb-9d44-d23962b96755)

**Comment by sakuhanachan** [comment]
~~note: I try change api path to v4 on cache file and found download slower as another problem.~~

edit: nvm, look like it's my connection problem.

**Comment by MikeZeDev** [comment]
Its not you, they indeed changed the endpoint to v4 .
BUT they also changed hashing parameter.
