### ISSUE TITLE
[<https://visortmo.com/>] Connector not working visortmo

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#7300]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Chapter download error.

### To Reproduce

1. Name of connector visortmo
2. Name of manga (if connector update is working) Any
3. Name of chapter (if manga update is working) 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

Some chapters of any manga have an error when downloading. Just download a page and finish it. Even using the redownload option there is a solution.
![Sin título](https://github.com/user-attachments/assets/3e6b4c65-d48c-4d69-b996-843f022ec0de)

**Comment by MikeZeDev** [comment]
Another day, another duplicate https://github.com/manga-download/hakuneko/issues/7238

Search first or youll kill kittens
