### ISSUE TITLE
No new chapters available for download from Mangakakalot 

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#731]
> **From:** HakuNeko User

It has been over a week now that I haven't been able to download anything from Mangakakalot.  

When I click on my favorite, not only does it only show the chapters that have already been downloaded, but it is shown as offline- chapters (in other words, the colour of the folders are gray instead of yellow.) eg. "I am a child of this house", "Lie by the pillow", "Haomen Qifu de Chuntian", "Chuan Yue Xi Yuan 3000 Hou"

Some of them are also out of date, in other words, hakuneko is stuck at chapter 263 while the site is already at chapter 270. eg. "I am a child of this house", "Haomen Qifu de Chuntian", "Chuan Yue Xi Yuan 3000 Hou"

I have tried to copy and paste the link.  Although it displays the manga the link is associated with, when I click on the "manga side" it doesn't retrieve anything (0/0).

I also tried to fetch the manga by going to its hosting site and retrieving the manga in this manner, but that wasn't successful either.

When I tried to open the manga directly through hakuneko, I was able to readd it online, but I could still not download it.

Am I doing something wrong?  I've tried restarting the application multiple times, but it didn't work either.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
The mangas you are mentioned do no longer exist on MangaKakalot website, they are hosted on MangaNel. You have to re-bookmark them from MangaNel
