### ISSUE TITLE
[lezhin] Connector not working

### ISSUE THREAD

**Issue by strayfb** [manga-download/hakuneko#7311]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

I can't download R19 episodes that I was able to download before. The lezhin I opened from Hakuneko doesn't work.
![Ekran görüntüsü 2024-08-07 140211](https://github.com/user-attachments/assets/08decb52-c259-42d5-b2d4-390804dd911f)
It looks like this all the time. The homepage and other pages do not load.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
🤦 
![image](https://github.com/user-attachments/assets/29345ab6-8442-4365-bca8-75fc1b1cd1a3)

**Comment by strayfb** [comment]
ah bana yardımcı olun lütfen

**Comment by MikeZeDev** [comment]
There is already a bug report for the SAME website on the VERY FIRST PAGE, how hard it is to understand that duplicate tickets are useless? 

![image](https://github.com/user-attachments/assets/90df1067-f532-4728-80d8-5855be0bd65c)

You blindly checked that but didnt care about instructions. **Read**, for god's sake, read before 🙏
