### ISSUE TITLE
[<lezhin>] Connector not working

### ISSUE THREAD

**Issue by strayfb** [manga-download/hakuneko#7312]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

I can't open lezhin in Hakuneko. A blank page appears and I can't upload the episodes I purchased

Uncaught SyntaxError: Unexpected token .
_next/static/chunks/3680-570469e9499f608d.js:1 Uncaught SyntaxError: Unexpected token .
_next/static/chunks/2590-f7f37cf2f6cc6dea.js:5 Uncaught SyntaxError: Unexpected token .
_next/static/chunks/app/%5Blanguage%5D/error-13311fe077d7235c.js:5 Uncaught SyntaxError: Unexpected token .
_next/static/chunks/2731-40ce576e4ff95921.js:1 Uncaught SyntaxError: Unexpected token .
The resource https://static.criteo.net/js/ld/ld.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.lezhinus.com/third-party/fb-pixel.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://install.appsilon.kr/js/appsilon_conv_lezhin.min.js?v1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
3629-c15ed30b5f07f525.js:1 [GLOBAL_ERROR]:  ChunkLoadError: Loading chunk 4038 failed.
(timeout: https://www.lezhinus.com/_next/static/chunks/4038-4e8bef71ee631ef1.js)
    at Object.b.f.j (https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:4988)
    at https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:1406
    at Array.reduce (<anonymous>)
    at Function.b.e (https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:1372)
    at https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:18881
    at https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:19083
    at t (https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:19286)
window.console.error @ 3629-c15ed30b5f07f525.js:1
a @ global-error-05e7439ac2a5b58b.js:1
rE @ 443919cb-aeb4f98848ca4af8.js:1
iZ @ 443919cb-aeb4f98848ca4af8.js:1
ia @ 443919cb-aeb4f98848ca4af8.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1
il @ 443919cb-aeb4f98848ca4af8.js:1
nb @ 443919cb-aeb4f98848ca4af8.js:1
nw @ 443919cb-aeb4f98848ca4af8.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1
3629-c15ed30b5f07f525.js:1 [GLOBAL_ERROR]:  ChunkLoadError: Loading chunk 4038 failed.
(timeout: https://www.lezhinus.com/_next/static/chunks/4038-4e8bef71ee631ef1.js)
    at Object.b.f.j (https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:4988)
    at https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:1406
    at Array.reduce (<anonymous>)
    at Function.b.e (https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:1372)
    at https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:18881
    at https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:19083
    at t (https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:19286)
window.console.error @ 3629-c15ed30b5f07f525.js:1
a @ global-error-05e7439ac2a5b58b.js:1
rE @ 443919cb-aeb4f98848ca4af8.js:1
iZ @ 443919cb-aeb4f98848ca4af8.js:1
ia @ 443919cb-aeb4f98848ca4af8.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1
il @ 443919cb-aeb4f98848ca4af8.js:1
oJ @ 443919cb-aeb4f98848ca4af8.js:1
nb @ 443919cb-aeb4f98848ca4af8.js:1
nw @ 443919cb-aeb4f98848ca4af8.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1
3629-c15ed30b5f07f525.js:1 ChunkLoadError: Loading chunk 4038 failed.
(timeout: https://www.lezhinus.com/_next/static/chunks/4038-4e8bef71ee631ef1.js)
    at Object.b.f.j (https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:4988)
    at https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:1406
    at Array.reduce (<anonymous>)
    at Function.b.e (https://www.lezhinus.com/_next/static/chunks/webpack-f1785de1ea9674dc.js:1:1372)
    at https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:18881
    at https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:19083
    at t (https://www.lezhinus.com/_next/static/chunks/3629-c15ed30b5f07f525.js:2:19286)
window.console.error @ 3629-c15ed30b5f07f525.js:1
l_ @ 443919cb-aeb4f98848ca4af8.js:1
n.callback @ 443919cb-aeb4f98848ca4af8.js:1
nB @ 443919cb-aeb4f98848ca4af8.js:1
nV @ 443919cb-aeb4f98848ca4af8.js:1
aq @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
a9 @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
a9 @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
a9 @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
a9 @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
a9 @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
a9 @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
a9 @ 443919cb-aeb4f98848ca4af8.js:1
aY @ 443919cb-aeb4f98848ca4af8.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1
is @ 443919cb-aeb4f98848ca4af8.js:1
nb @ 443919cb-aeb4f98848ca4af8.js:1
nw @ 443919cb-aeb4f98848ca4af8.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1
3629-c15ed30b5f07f525.js:1 Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iZ (443919cb-aeb4f98848ca4af8.js:1)
    at ia (443919cb-aeb4f98848ca4af8.js:1)
    at 443919cb-aeb4f98848ca4af8.js:1
    at il (443919cb-aeb4f98848ca4af8.js:1)
    at oJ (443919cb-aeb4f98848ca4af8.js:1)
    at nb (443919cb-aeb4f98848ca4af8.js:1)
    at nw (443919cb-aeb4f98848ca4af8.js:1)
    at 443919cb-aeb4f98848ca4af8.js:1
window.console.error @ 3629-c15ed30b5f07f525.js:1
t @ 3629-c15ed30b5f07f525.js:1
o @ 3629-c15ed30b5f07f525.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1
is @ 443919cb-aeb4f98848ca4af8.js:1
nb @ 443919cb-aeb4f98848ca4af8.js:1
nw @ 443919cb-aeb4f98848ca4af8.js:1
(anonymous) @ 443919cb-aeb4f98848ca4af8.js:1

![Ekran görüntüsü 2024-08-07 140211](https://github.com/user-attachments/assets/5c0c8c8f-4ce5-400b-853b-7e687671d97a)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Stop opening useless tickets

**Comment by strayfb** [comment]
I just wanted some help. Sorry.
