### ISSUE TITLE
[Site Request] MangaDistrict

### ISSUE THREAD

**Issue by TheAidenPierce** [manga-download/hakuneko#7316]
**Name of the website**
MangaDistrict

**Website urls (examples below)**
- Site: https://mangadistrict.com/
- Manga List: https://mangadistrict.com/read-scan/
- Manga example: https://mangadistrict.com/read-scan/the-hero-returns/
- Chapter online viewer example: https://mangadistrict.com/read-scan/the-hero-returns/chapter-1/

**Languages**
English

**Additional details**
I've found a working tachiyomi extension which you can refer but as you know its for android. Therefore, I wanted a connector to use on PC.
https://github.com/keiyoushi/extensions/blob/repo/apk/tachiyomi-en.mangadistrict-v1.4.41.apk
Thank you very much.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5515  . Search before pls.
