### ISSUE TITLE
Scanmanga (fr) can't read '1' of null 

### ISSUE THREAD

**Issue by foxan54** [manga-download/hakuneko#732]
Hello
i use hakuneko for some times now i have a problem with "Scanmanga" it's a site FR. 
I can't download or read with this site.  the error message is "can't read '1' of null "
thank you for your help in advance

Sorry for my english i speak a little english.

**Comment by 27136773** [comment]
Which version are you using, 5.0.8 or nightly?

**Comment by foxan54** [comment]
Oh sorry I forgot to specify I try with the 2 version (5.0.8 and 6.1.5)

**Comment by 27136773** [comment]
Cannot be reproduced.
Please provide a manga/chapter where the problem occurs.

**Comment by 27136773** [comment]
No further response => closed

**Comment by Genoclara** [comment]
Hi, 
First, WOW, your program is Amazing ! \(^0^)/
Second, I have the same problem with all version, join pic.
Do you know what I can do ?
Thanks ^^
![Hakuneko](https://user-images.githubusercontent.com/54775607/74957854-705f8080-5408-11ea-8e7b-a00f4329851c.jpg)
