### ISSUE TITLE
[<GourmetScans.mjs>] Connector not working

### ISSUE THREAD

**Issue by BillyBob1354** [manga-download/hakuneko#7322]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Can fetch the chapter list but fails to download with a timeout.

### To Reproduce

1. GourmetScans.mjs
2. Any manga
3. Any chapter
4. Error: Failed to load "ht<span>tp</span>s://gourmetsupremacy.com/project/_(ANY-"project"-URL)_" within the given timeout of 60 seconds!

**Comment by MikeZeDev** [comment]
website is too damn slow loading picture decryption components.. 😮‍💨

**Comment by MikeZeDev** [comment]
If you want a faster fix, you should start using [Haruneko](https://github.com/manga-download/hakuneko/).  Fix is pending for Haruneko to and will come faster.
