### ISSUE TITLE
https://m.happymh.com/

### ISSUE THREAD

**Issue by Nawalice** [manga-download/hakuneko#7325]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://m.happymh.com/
- Manga List: https://m.happymh.com/latest
- Manga example: https://m.happymh.com/manga/wuliandianfeng
- Chapter online viewer example: https://m.happymh.com/reads/wuliandianfeng/4652549

**Languages**
Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Please.... https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+happymh&type=issues

Its redirecting to Tencent Manga. Which is already supported. From a chinese ip its even worst : 无法显示此网页，因为服务器停止响应。 Stop asking for the impossible.
