### ISSUE TITLE
[Site Request] manga plaza

### ISSUE THREAD

**Issue by BLUEBELL234** [manga-download/hakuneko#7326]
manga plaza
manga plaza

Website URL
https://mangaplaza.com/

**Languages**
List of languages supported by the website
English
Japanese
im not sure what other languages  

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
not that I can see 
**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Already requested. Why no one is using search?

**Comment by BLUEBELL234** [comment]
??? it does not appear in hakuneko. if it is there, please assist me on how to have it appear on my end. thank you.
