### ISSUE TITLE
[<kiryuu, kombatch, manhwaland>] Connector not working

### ISSUE THREAD

**Issue by wow2134** [manga-download/hakuneko#7327]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

web change domain,

kiryuu.id move to kiryuu.org
kombatch.com move to kombatch.cc

now about manhwaland
https://github.com/manga-download/hakuneko/issues/7009#issuecomment-2074210272
if you use https://manhwaland.lat/, now redirect to https://www.manhwaland.ink/
However i think https://www.manhwaland.ink and https://www.manhwaland.vip they are no different, they just take projects from [komiktap](https://komiktap.info/). But komiktap is blocked from our country while manhwaland keeps changing its domain so we can read it without vpn.

i use [Nightly version](https://github.com/manga-download/hakuneko/releases/tag/nightly-20200705.1)

Thank you, if I am wrong please tell me

### To Reproduce

1. Name of connector: kiryuu, kombatch, manhwaland

**Comment by wow2134** [comment]
unfortunately, i don't understand about programming.
If I understand programming, if it's just changing domains, I don't think I need to report something like this.

**Comment by MikeZeDev** [comment]
* Fork the repo
* find relevant javascript files
* change url
* Profit

But yeah, i know about them. I am currently fixing A LOT of domains in Haruneko
Truth be told, i thought kombatch was dead. Gotta port it to Haruneko :D

**Comment by wow2134** [comment]
thanks sir..
