### ISSUE TITLE
Japscan.to

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#733]
> **From:** HakuNeko User

Hello, can't connect to Japscan.to for french scans . I got an error message. And many and many chapters download fails.

<details><summary>What has been done?</summary>

</details>

**Comment by foxan54** [comment]
salut

Tu essaie de télécharger les quels chap ? car chez moi japscan fonction.

**Comment by 27136773** [comment]
Are you using version 5.0.8 or the latest nightly build?

**Comment by Sojirokenji** [comment]
Bonjour, j'ai un problème, certain manga comme Tenkuu Shinpan Arrive, ou Act-Age n'apparaisse pas.
Merci d'avance

**Comment by Ever4engel** [comment]
Japscan work's well.

**Comment by 27136773** [comment]
Cannot be reproduced with latest nightly build.
No further response => closed
