### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by sain21** [manga-download/hakuneko#7330]
### Is there an existing issue for this connector?

- [x] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

connector update is not working
Error message: Failed to update manga list fpr MANGA Plus by Shueisha - invalid wire type 4 at offset 1
![Screenshot 2024-08-15 154007](https://github.com/user-attachments/assets/2e1ff930-5f53-456d-b4bc-853ba3be4811)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Dont fill duplicate issues.https://github.com/manga-download/hakuneko/issues/7110
