### ISSUE TITLE
[TempestScans] Connector not working

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7331]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The site's address has been renewed

### To Reproduce

1. Name of connector Tempest Scans
2. Name of manga (if connector update is working) https://tempestscans.net/
3. Name of chapter (if manga update is working) https://tempestscans.net/whats-our-hero-doing-0/
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
whats the difference with https://tempestfansub.com/ ?
