### ISSUE TITLE
[<Hiperdex>] Connector not working

### ISSUE THREAD

**Issue by AppKiller1412** [manga-download/hakuneko#7334]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

the list is not loading

### To Reproduce

1. Hiperdex

**Comment by MikeZeDev** [comment]
Cloudflare no need to open an issue
