### ISSUE TITLE
[Site Request] michikusacomics

### ISSUE THREAD

**Issue by iKyel** [manga-download/hakuneko#7340]
**Name of the website**
michikusacomics

**Website urls (examples below)**
- Site: https://michikusacomics.jp/
- Manga List: https://michikusacomics.jp/product
- Manga example: https://michikusacomics.jp/product/midorichan
- Chapter online viewer example: https://michikusacomics.jp/wp-content/uploads/data/13_midorichan/01/index.html

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by iKyel** [comment]
> **Name of the website** michikusacomics
> 
> **Website urls (examples below)**
> 
> * Site: https://michikusacomics.jp/
> * Manga List: https://michikusacomics.jp/product
> * Manga example: https://michikusacomics.jp/product/midorichan
> * Chapter online viewer example: https://michikusacomics.jp/wp-content/uploads/data/13_midorichan/01/index.html
> 
> **Languages** Japanese
> 
> *_Website relationship_ If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
> 
> **Additional details** Add any other context details that you may have found (like template to reuse)

damn, sorry, i found out the same request for this site, please close this

**Comment by MikeZeDev** [comment]
you can close it by yourself :D
