### ISSUE TITLE
[<NameOfConnector>] Connector not working

### ISSUE THREAD

**Issue by PokemonAlpha** [manga-download/hakuneko#7346]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Bonjour,

J'ai progressivement perdu la possibilté de telecharger les chapitres ( voir ces derniers disparaissent

![Capture d'écran 2024-08-19 213555](https://github.com/user-attachments/assets/ce59622c-5646-4a44-b94b-b699cd9a7e89)
 sur les différents connecteurs et la j'en ai plus qui fonctionnent correctement.

Cordialement,
Matthieu

![Capture d'écran 2024-08-19 213135](https://github.com/user-attachments/assets/4d260fc2-730f-4364-9f42-830900b59439)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
* Bonjour. "J'en ai plus un", ca n'aide pas a dépanner. Il nous faut des noms, tout les noms

* Japscan est en guerre depuis des années avec Hakuneko, Tachiyomi, etc... C'est normal que ca pete tout le temps. On a pas toujours le temps de corriger le tir. Ca marche peut etre avec [Haruneko](https://github.com/manga-download/haruneko/) ?

* Quand au site "ScanFR", il aurait peut etre fallut vérifier avant d'en parler si ce n'était pas le site lui meme qui avait un problème. Dans un navigateur par exemple. En fait, https://www.scan-fr.org est un site mort, et nous ne pratiquons par la nécromancie :D

* Beaucoup de site francophones utilisent Cloudflare, auquel cas on ne peut rien faire non plus.

* Je vais laisser ce ticket ouvert si jamais il y d'autres sites à signaler mais je craint que l'on ne soit déjà au courant pour tous.
SURTOUT pour Japscan https://github.com/manga-download/hakuneko/issues/4657 https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+japscan&type=issues

**Comment by PokemonAlpha** [comment]
Merci^^

**Comment by PokemonAlpha** [comment]
J'en aurais bien profité le temps que ça a duré^^
