### ISSUE TITLE
[Site Request] Olympus Scanlation

### ISSUE THREAD

**Issue by Geounix** [manga-download/hakuneko#7353]
**Name of the website**
Olympus Scanlation

**Website urls (examples below)**
- Site: https://leerolymp.com/
- Manga List: https://leerolymp.com/series
- Manga example: https://leerolymp.com/series/comic-indo-abne-doce14124142
- Chapter online viewer example: https://leerolymp.com/capitulo/91015/comic-indo-abne-doce14124142

**Languages**
Spanish

List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/blob/e40bc3a02c6d38d2a3e98f19bbf82ed8becf03b3/src/web/mjs/connectors/OlympusScanlation.mjs#L4

Make proper ticket 'Website change"; not "website suggestion" . 
Or dont bother and use Haruneko, its up to date here

https://github.com/manga-download/haruneko/blob/bb12b74dfc504bfe718d05ac43b7173c936dd960/web/src/engine/websites/OlympusScanlation.ts#L2
