### ISSUE TITLE
[<LuminousScans>] Connector not working

### ISSUE THREAD

**Issue by dnet890** [manga-download/hakuneko#7354]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

They are moving to https://radiantscans.com/

### To Reproduce

1. Search Luminous scan
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
<img width="549" alt="image" src="https://github.com/user-attachments/assets/00dab2dd-0266-440f-9536-058ca0644637">

**Comment by MikeZeDev** [comment]
Please open a "Website Suggestion" issue to request Radiant Scans if not already supported or requested.
