### ISSUE TITLE
[Batoto (by AnyACG)] Connector not working

### ISSUE THREAD

**Issue by imnotagamedev** [manga-download/hakuneko#7355]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Whenever you click on the refresh manga list button, it prompts an error tab that says "Cannot read property 'text' of undefined"
![image_2024-08-23_005524857](https://github.com/user-attachments/assets/25a553c3-a366-44f7-8c9b-5072d52bbd45)

### To Reproduce

1. Batoto (by AnyAGC)
2. doesn't work on any manga, the manga list won't update
4. Failed to update manga list for Batoto (by AnyAGC) cannot read property 'text' of undefined
![image](https://github.com/user-attachments/assets/88698fd6-e06c-4210-98f4-13c7d68ecbbf)

**Comment by MikeZeDev** [comment]
Please check the url you have for this website in settings, as batoto has many mirrors/ clones. And make sure the website is not down itself. 

Default url https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/Batoto.mjs works for me.
