### ISSUE TITLE
[https://manhuaplus.com/ Connector not working

### ISSUE THREAD

**Issue by guyver1111** [manga-download/hakuneko#7356]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

the list of manga is shortly and not updated with the content of manga list of the website

### To Reproduce

1. Manhuaplus
2. Connector update doesn't working. By example battle through the heaven isn't charged. same for TODAG

**Comment by MikeZeDev** [comment]
We are using manhuaplus.org, as they recommended to use this because of server issues, If you want a manga from manhuaplus.com you wont get it, its not a bug.
