### ISSUE TITLE
[ComicK] Connector nor Copy & Paste working

### ISSUE THREAD

**Issue by orn8** [manga-download/hakuneko#7358]
### Is there an existing issue for this connector?

- [x] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Upon selecting ComicK in the connectors, it will give you a 403 error message when refreshing in the Network debug menu. I have tried Nightly and the copy paste system does not appear to be working. I have also tried replacing the TLD with `.app`, `.ink`, and `.cc`, but the error persists.

### To Reproduce

1. Name of connector: ComicK
2. Name of manga (if connector update is working): N/A
3. Name of chapter (if manga update is working): N/A
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): 
```
GET https://api.comick.io/v1.0/search?limit=49&page=1 403
```

**Comment by orn8** [comment]
Another observation: The ComicK connector successfully scans once after a reinstall of the software, and does not work again until another reinstall.

**Comment by MikeZeDev** [comment]
Reinstall has nothing to do with that and will change absolutely nothing.

**Comment by orn8** [comment]
Hmm. the copy paste system just started working again all of a sudden. All issues seem to have disappeared. Perhaps ComicK's API had a short outage earlier? Not sure. Anyway, thanks for your help.
