### ISSUE TITLE
[Site Request] Manga Tilkisi (majorscans became Manga Tilkisi)

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7361]
**Name of the website**
Manga Tilkisi

**Website urls (examples below)**
- Site: https://www.mangatilkisi.com/
- Manga List: https://www.mangatilkisi.com/manga/
- Manga example: https://www.mangatilkisi.com/manga/dukun-en-buyuk-oglu-olarak-reenkarne-oldum/
- Chapter online viewer example: https://www.mangatilkisi.com/manga/dukun-en-buyuk-oglu-olarak-reenkarne-oldum/bolum-1/

**Languages**
Turkish

**Website relationship*
they closed the old site and moved to the new site

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Website doesnt answer right now

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/6619
