### ISSUE TITLE
[Site Request] Mangachap

### ISSUE THREAD

**Issue by Torablue** [manga-download/hakuneko#7364]
**Name of the website**
Mangachap

**Website urls (examples below)**
- Site: https://mangachap.com/
- Manga List: https://mangachap.com/manga-genre/manga/
- Manga example: https://mangachap.com/manga/drawing-the-greatest-mangaka-becomes-a-skilled-martial-artist-in-another-world/
- Chapter online viewer example: https://mangachap.com/manga/drawing-the-greatest-mangaka-becomes-a-skilled-martial-artist-in-another-world/chapter-113/

**Languages**
English

**Website relationship*
Replacing mangaeffect soon, seems like in the process of moving now. Not all manga got copied yet.

**Additional details**
-

**Comment by MikeZeDev** [comment]
Merged with Mangaread.org
