### ISSUE TITLE
[Site Request] bilingualmanga

### ISSUE THREAD

**Issue by 123ban** [manga-download/hakuneko#7366]
Name of the website
bilingualmanga

Website urls (examples below)
Site: https://bilingualmanga.org/
Manga List: https://bilingualmanga.org/?page=1&ls=jp
Manga example: https://bilingualmanga.org/manga/66c961572b8cae2e3bbd1442?lang=en
Chapter online viewer example: https://bilingualmanga.org/manga/66c961572b8cae2e3bbd1442?lang=en&chen=0&chjp=0&enp=0&jpp=0#img_store

Languages
English
Japanese

*Website relationship

Additional details

**Comment by MikeZeDev** [comment]
Search before pls https://github.com/manga-download/hakuneko/issues/6923

**Comment by 123ban** [comment]
This site seems to be alive.
