### ISSUE TITLE
[Welovemanga.one] Connector not working

### ISSUE THREAD

**Issue by vsatyamesc** [manga-download/hakuneko#7371]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Manga List - https://welovemanga.one/manga-list.html
The connector can Fetch the manga and the chapters.

![image](https://github.com/user-attachments/assets/0e72dd51-2100-493e-bf41-f41a7c2c6927)
There's problem in downloading and when you try to open the images, via the icon it shows that following dialog.

**Comment by MikeZeDev** [comment]
I see.

`        return nodes.map(image => this.createConnectorURI(image.dataset.original.replace(/\n/g, '')));`

there is no "dataset.original" but "dataset.srcset".
