### ISSUE TITLE
[Site Request] scan-manga

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/hakuneko#7372]
**Name of the website**
scan-manga

**Website urls (examples below)**
- Site: https://www.scan-manga.com
- Manga List: https://www.scan-manga.com/scanlation/liste_series.html
- Manga example: https://www.scan-manga.com/5278/Martial-Peak.html
- Chapter online viewer example: https://www.scan-manga.com/lecture-en-ligne/Martial-Peak-Chapitre-1404-FR_421374.html

**Languages**
French

**Website relationship*
linked with perfscan

**Additional details**

**Comment by MikeZeDev** [comment]
pourquoi demander un site déja supporté?  😮‍💨 

https://github.com/manga-download/hakuneko/blob/4a58ff173a763681c76b275070c1f3e1e841f427/src/web/mjs/connectors/ScanManga.mjs#L12

Je préviens le site lui meme est un peu pété, faudra utiliser la fonction copier coller de Hakuneko.
