### ISSUE TITLE
[Mangahere] Error 500

### ISSUE THREAD

**Issue by 3scythe** [manga-download/hakuneko#7376]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I tried downloading using mangahere.cc links but it does not load any manga after putting the link... when I try to open the hakuneko browser version it says page error 500
![z](https://github.com/user-attachments/assets/db1526de-5e12-4876-929b-188d82c58d72)

### To Reproduce

1. mjs/connectors/MangaFox.mjs
![z2](https://github.com/user-attachments/assets/5c48b0ec-1a8f-4f48-b99c-38d437661f21)

**Comment by MikeZeDev** [comment]
Website have problems since the update

**Comment by MikeZeDev** [comment]
[MANGAHERE] If you got error 500, use connector button to open website, press F12 to display DevTools, Clear cookies, close the window an retry

![image](https://github.com/user-attachments/assets/57426716-35ba-4b04-aac6-5bbf0ec8cc66)

![image](https://github.com/user-attachments/assets/73a0071d-6b33-4a5e-acaa-71d5c8a63e71)

![image](https://github.com/user-attachments/assets/a5268912-6490-44b7-9cb0-47ddb267f9d4)

**Comment by Sheepux** [comment]
just wait until the website is working (open your standard browser)
