### ISSUE TITLE
[Site Request] https://blogtruyen.vn/

### ISSUE THREAD

**Issue by tanksugar** [manga-download/hakuneko#7377]
**Name of the website**
[thewebsitename](https://blogtruyen.vn/)

**Website urls (examples below)**
- Site: https://blogtruyen.vn/

**Languages**
Việt Nam

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
* Open a duplicate issue for Mangaplus https://github.com/manga-download/hakuneko/issues/7378
* Open a duplicate issue for BlogtruyenVN https://github.com/manga-download/hakuneko/issues/6977

Please stop wasting your time and my time by opening useless duplicates. Use the search feature.
