### ISSUE TITLE
Tumangaonline does not allow download

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#738]
When trying to download any title, it sends an error after 2 minutes.

![1](https://user-images.githubusercontent.com/53885246/70102912-9181b380-1607-11ea-8861-dbd8bb99118b.jpg)

After 2 minutes.

![2](https://user-images.githubusercontent.com/53885246/70102950-b2e29f80-1607-11ea-9b11-00c92254fd6b.jpg)

**Comment by hypoflex** [comment]
could you press F12 to open the dev-tool, and go to the network tab, before downloading. and screenshot what happens in the devtool after downloading.

**Comment by DarkBlooDStone** [comment]
![das](https://user-images.githubusercontent.com/53885246/70286638-f53be600-1799-11ea-816d-0c11af3cc679.jpg)

**Comment by 27136773** [comment]
TuMangaOnline has currently an IP ban system for to many requests
