### ISSUE TITLE
[Baozihm] Connector not working 

### ISSUE THREAD

**Issue by Kotycer** [manga-download/hakuneko#7381]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

![Screenshot 2024-09-02 023621](https://github.com/user-attachments/assets/81f682f9-c4d2-4a7a-8b8f-ce8086756523)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by Sheepux** [comment]
Just read the message that says to use copy/paste url ?

**Comment by Kotycer** [comment]
Ok if I copy the URL of the manga chapter then Where to Paste it in The software

**Comment by Kotycer** [comment]
> Just read the message that says to use copy/paste url ?

so where to paste the URL in the APK

**Comment by Kotycer** [comment]
> Just read the message that says to use copy/paste url ?


Ok if I copy the URL of the manga chapter then Where to Paste it in The software

so where to paste the URL in the APK

**Comment by Sheepux** [comment]
spaming won't get you a faster reply .
As such I will not give a quick answer as you are rude but "you can find such information in the documentation" or just typing the same question in google ...
