### ISSUE TITLE
MangaKu not work well

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#739]
i tried to changes the script, but it not working well. this result :
![mangaku](https://user-images.githubusercontent.com/45929526/70121908-21743b80-16a2-11ea-9bb2-55a5a466e520.PNG)
the manga list is not title only and i can't found the source of image.

For _getMangaList = this.fetchDOM(request, 'div#data.dftmgk ul a.tooltip');
For _getChapterList = this.fetchDOM(request, 'div#content-b div[style*="-moz-border-radius"] a');
For _getPageList = Can't i found

**Comment by dodieboy** [comment]
It is hell to find the source of image. It auto redirect me to home page when I open the dev tool. But managed to find this.
The div.xVXmOEXku will change class name for different mange if i'm not wrong
![image](https://user-images.githubusercontent.com/9015764/71099720-b9b80780-21ee-11ea-842f-5583d8b7f19a.png)

**Comment by dodieboy** [comment]
For _getMangaList, can use this to fix the long name: this.fetchDOM(request, 'div#data.dftmgk div.npx ul li a.tooltip');

**Comment by 27136773** [comment]
Is this issue still pending or solved?

**Comment by dodieboy** [comment]
pending
