### ISSUE TITLE
[Pixiv Comic] Download aren't working

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/hakuneko#7393]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Get Error 400 and error message "不正なリクエストです" on ``read_v4`` path when download all chapter.  
Note: This problem appear both Haku and Haru.

### To Reproduce

1. Name of connector: Pixiv Comic
2. Name of manga (if connector update is working): All
3. Name of chapter (if manga update is working): All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): 
![image](https://github.com/user-attachments/assets/58bd4512-4cfa-4ae5-beb5-0deb6049bdd4)

![image](https://github.com/user-attachments/assets/ba12a3da-704c-4515-86cb-0ef5e09ee58e)

**Comment by MikeZeDev** [comment]
They just changed crypto constant, not a big deal
