### ISSUE TITLE
[Site Request] rumanhua

### ISSUE THREAD

**Issue by Ana9x** [manga-download/hakuneko#7395]
**Name of the website**
rumanhua

**Website urls (examples below)**
- Site: https://www.rumanhua.com/
- Manga List: https://www.rumanhua.com/rank/1
- Manga example: https://www.rumanhua.com/OjQQNRi/
- Chapter online viewer example: https://www.rumanhua.com/OjQQNRi/hrsGwwH.html

**Languages**
Chinese

**Comment by MikeZeDev** [comment]
Search first pls.https://github.com/manga-download/hakuneko/issues/7320
