### ISSUE TITLE
1st Kiss Manga issue?

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#740]
Maybe it’s just on my end, but 1st Kiss Manga doesn’t seem to be loading all the mangas and chapters that are available lately.

**Comment by dodieboy** [comment]
work fine for me

**Comment by siennk** [comment]
Yeah I just tried again, it doesn’t work for me.

It only loads some of the manga titles. And for the ones that show, even their chapters aren’t showing now.

**Comment by hypoflex** [comment]
issue could not be reproduced, could you please state more specific which manga does not load the chapters? so the issue could be further inspected.

**Comment by siennk** [comment]
Some titles that aren’t listing at all are:
The Naive Mr. Lu
Boss, You Need a Spanking
I’m the Great Immortal

**Comment by 27136773** [comment]
Cannot be reproduced on my end, could this have been a temporary issue of the website's host?

![image](https://user-images.githubusercontent.com/27136773/70930272-1243a500-2035-11ea-9e26-fbf3a5dfb3d1.png)

**Comment by siennk** [comment]
Okay I’ll have to try again from my end. If that still doesn’t, I’ll try redownloading the program to see if it clears up the problem.

**Comment by 27136773** [comment]
No further response => closed

**Comment by AsunaKai** [comment]
I would like to comment that the webite does appear but as of late pnce i go from one chapter to another i will get an 403 Forbidden error webpage and as of today ive been getting redirected to another url thats says 1stkissmanga.com but its connected to word press but after deleting browser history and refreshing alot am i able to get back to original site. I just was wandering are they shutting the site down? Switching servers? Or is there anything i can do..

**Comment by 27136773** [comment]
I still have no problems, tried with random mangas in HakuNeko and also in browser

**Comment by awchau** [comment]
i also get the 403 Forbidden error page, and it's happened twice already. Im not really sure how to fix it or why it keeps appearing.....

**Comment by 27136773** [comment]
Further analysis required ...

**Comment by AsunaKai** [comment]
its weird but today for some reason ive got 403 forbidden error again and i was just reading manga a few days ago.... ive tried deleteing browser history and refreshing but thats mot quite working anymore

**Comment by rattpakk** [comment]
Yeah me too i cant access 1stkiss theres a 403 Forbidden message :(

**Comment by 27136773** [comment]
The website itself shows this error, HakuNeko cannot work if not even the website is working
