### ISSUE TITLE
[Site Request] MangaGalaxy

### ISSUE THREAD

**Issue by edsporfekt** [manga-download/hakuneko#7403]
**Name of the website**
Manga Galaxy

**Website urls (examples below)**
- Site: https://mangagalaxy.net/home
- Manga List: https://mangagalaxy.net/series
- Manga example: https://mangagalaxy.net/series/the-hero-became-the-duke's-eldest-son
- Chapter online viewer example: https://mangagalaxy.net/series/the-hero-became-the-duke's-eldest-son/chapter-37

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
bruh .....https://github.com/manga-download/hakuneko/issues/7250
