### ISSUE TITLE
[Feature] Allow downloading multiple chapters into one directory

### ISSUE THREAD

**Issue by schaboomafoo** [manga-download/hakuneko#7406]
quality of life feature for importing downloaded chapters into manga readers
something like when you click "download all chapters currently shown in the filtered and sorted list" but into one directory
assume there would be issue of order of images in context of multiple chapters, could either allow custom ordering or go alphabetically considering in most contexts it would be multiple directories like "vol.01 ch.001, ... ch.002, ch.003, ch.004, ..."

**Comment by 27136773** [comment]
See comment https://github.com/manga-download/hakuneko/issues/6962#issuecomment-2116113940 in related ticket #6962
➔ Rejected
