### ISSUE TITLE
[Site Request] wfwf

### ISSUE THREAD

**Issue by Piffi25** [manga-download/hakuneko#7408]
**Wfwf / 늑대닷컴**
wfwf / 늑대닷컴

**Website urls (examples below)**
- Site: https://wfwf349.com
- Webtoon List: https://wfwf349.com/ing 
- Webtoon example: https://wfwf349.com/list?toon=3965
- Chapter online viewer example: https://wfwf349.com/view?toon=3965&num=145&title=%B0%D9%B9%E93%BA%CE53%C8%AD

**Languages**
Korean

**Website relationship*
Website changes the number in intervals

**Comment by MikeZeDev** [comment]
use search ? https://github.com/manga-download/hakuneko/issues/6848
