### ISSUE TITLE
[<Reaperscans>] Downloaded chapter images are in bin format

### ISSUE THREAD

**Issue by AppKiller1412** [manga-download/hakuneko#7409]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

i tried to download overgeared chapter 245 in haruneko using the reaperscans plugin, it opened the manga and chapter list without any problem and i can read the chapter in haruneko but when i downloaded the chapter all the images were in bin format.
![Screenshot 2024-09-20 194542](https://github.com/user-attachments/assets/e8daa79b-ebd6-4994-a2c7-7ee6fb6b0259)

### To Reproduce

1. Reaperscans
2. overgeared
3. chapter 245
4. it downloads the chapter but it is in bin format

**Comment by MikeZeDev** [comment]
Its not supposed to be fixed in Hakuneko https://github.com/manga-download/hakuneko/issues/7319, use Haruneko.

**Comment by AppKiller1412** [comment]
i am talking about haruneko not hakuneko

**Comment by AppKiller1412** [comment]
> Its not supposed to be fixed in Hakuneko #7319, use Haruneko.
i am talking about haruneko not hakuneko, this is happening in haruneko, pls check it out
