### ISSUE TITLE
[Volume] volume style download

### ISSUE THREAD

**Issue by Souravi785** [manga-download/hakuneko#741]
First time using hakuneko. Is it possible to download chapters into one folder like how a manga volume is. I mean how a manga volume is 150 or 200 pages. Downloading 8/10 chapters and compiling them in the same folder instead of different folders.

**Comment by 27136773** [comment]
No this is not possible, the structure is
`Manga Directory` > `Chapters`
There is no additional hierarchy for volumes, most websites not even provide volume information.
However, you can write and add your own post processing script in HakuNeko settings to achieve what you want, but i'm afraid i have no time to help with this...
