### ISSUE TITLE
[ManhwasNet.mjs] Connector not working

### ISSUE THREAD

**Issue by negareni** [manga-download/hakuneko#7417]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hello everyone, the problem is that the list of manga and its chapters is not updated (only what I already downloaded appears). I already tried to update Hakuneko as the troubleshooting guide says, but it still doesn't work, I hope you can help me. Thank you for your time and help.

### To Reproduce

1. ManhwasNet.mjs
2. All manga.
3. All chapters.
4. No errors appear, it just doesn't load anything.

**Comment by MikeZeDev** [comment]
Works fine https://i.imgur.com/1Dx7qIU.png

Retry refreshing mangas list with dev tools opened (press F12) and check for errors in network tab or console tab

**Comment by negareni** [comment]
ok we will try again, thanks for your time.

**Comment by negareni** [comment]
Sorry for the inconvenience but I still get an error, here is the screenshot.
![Screenshot 2024-09-22 194116](https://github.com/user-attachments/assets/abb72c83-bed7-4077-bc6f-b74fb1c69b71)

Thank you for your help.

**Comment by MikeZeDev** [comment]
I dont have those weird 403 errors, whatever i do. If you are able to open the website in a real browse**r, and providing you didnt check this without thinking** 

![image](https://github.com/user-attachments/assets/ff7b9daa-e0f8-4771-96d0-a63d6b5e5e58)

i am unable to help you.

**Comment by negareni** [comment]
ok, thanks for your time.
