### ISSUE TITLE
[Site Request] Ikigai Mangas

### ISSUE THREAD

**Issue by negareni** [manga-download/hakuneko#7419]
**Name of the website**
Ikigai Mangas

**Website urls (examples below)**
- Site: https://lectorikigai.efope.com/
- Manga List: https://lectorikigai.efope.com/series/
- Manga example: https://lectorikigai.efope.com/series/el-regreso-del-jugador-congelado/
- Chapter online viewer example: https://lectorikigai.erigu.com/capitulo/1005269008835018755/

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
The website uses the Qwik framework (I got it from here https://builtwith.com/ , I was reviewing how to create the scraper in their guide but I am really lost)

**Comment by MikeZeDev** [comment]
Thanks for providing  a hint about framework, very few people are doing that 👍

**Comment by MikeZeDev** [comment]
I knew it ! Its the same as https://lectorikigai.ejehu.com, already done in Haruneko.  Discord link is the same, mangas are the same. Any reason i should add it? Which one is a clone?

**Comment by negareni** [comment]
Sorry, I didn't know there was another thread like this. I'll check the GitHub folder for what was mentioned. Thanks for your time.
