### ISSUE TITLE
[<KadoComi / Comicwalker>] Chapter's titles are incorrect

### ISSUE THREAD

**Issue by Miraihi** [manga-download/hakuneko#7421]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

[<KadoComi / Comicwalker>] 
The problem is simple - every chapter has the same name. Probably the wrong parsing.
![hakuneko_dliQf6RToV](https://github.com/user-attachments/assets/b3e203c8-a3da-4363-99e0-715a35c2b4a8)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
There are two problem in fact 👍 

1) You didnt post a link to the affected manga. I, being a dirty gaijin, am unable to read or write japanese, therefor i ma unable to find this mange on the website in order to perform a diagnosis. 

2) The problem is : we are using the WEBSITE API to gather chapter informations. The informations should be accurate.

**Comment by Miraihi** [comment]
Well, the title of manga in question is `ラブ・バレット`, but the problem persists no matter the what manga I try to view/download.

Essentially, when I download a chapter it downloads just fine, but when I try to download the next one it overwrites the previous one since the filenames are identical.

**Comment by MikeZeDev** [comment]
![AGU7rSX](https://github.com/user-attachments/assets/ad62e543-9b86-4f4c-aaf7-3314e074986b)
Its working as intended 🤷

**Comment by Miraihi** [comment]
Alright, the problem has been fixed by changing the "Chapter title format" option (It's been %M% originally). I probably has been a bit too hasty with the bug report, excuse me.
![hakuneko_HCV4d3QZgN](https://github.com/user-attachments/assets/cb87e0f6-9c7b-46ff-a1c5-0108d2c1208f)
