### ISSUE TITLE
[Site Request] firescans

### ISSUE THREAD

**Issue by Mammad211** [manga-download/hakuneko#7424]
**Name of the website**
firescans

**Website urls (examples below)**
- Site: https://firescans.xyz/
- Manga List: https://firescans.xyz/manga-2/
- Manga example: https://firescans.xyz/manga/the-ultimate-wantless-godly-rich-system/
- Chapter online viewer example: https://firescans.xyz/manga/the-ultimate-wantless-godly-rich-system/chapter-14/

**Languages**
english

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
bruh https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+firescans&type=issues
