### ISSUE TITLE
[<weebcentral>] Connector not working Haruneko

### ISSUE THREAD

**Issue by Mammad211** [manga-download/hakuneko#7426]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

its not possible to see or download chapters

### To Reproduce

1. weebcentral
2. Name of manga https://weebcentral.com/
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![ScreenShot_20240924202806](https://github.com/user-attachments/assets/b8134f74-7a90-4edc-bedf-752345676d89)

**Comment by MikeZeDev** [comment]
**Post this in haruneko github.**
They changed in the meantime :/ initially chapters name where clean

**Comment by MikeZeDev** [comment]
Closed as invalid as its not Haruneko Github. Fix incoming https://github.com/manga-download/haruneko/pull/784

**Comment by 27136773** [comment]
Duplicate of #7407
