### ISSUE TITLE
[Site Request] MangaHub.io

### ISSUE THREAD

**Issue by SauceyNuggets420** [manga-download/hakuneko#7429]
**Name of the website**
MangaHub

**Website urls (examples below)**
- Site: https://mangahub.io
- Manga List: https://mangahub.io/search
- Manga example: https://mangahub.io/manga/apotheosis
- Chapter online viewer example: https://mangahub.io/chapter/apotheosis/chapter-1

**Languages**
English

**Website relationship*
Domains with same design:
https://mangareader.site/
https://mangafox.fun
https://mangakakalot.fun
https://mangahere.onl

**Additional details**

**Comment by MikeZeDev** [comment]
Are you kidding? Its supported in Hakuneko for years (before 2019). Did you even open the program?
