### ISSUE TITLE
Zeroscan is not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#743]
> **From:** HakuNeko User

They moved site from wordpress and that seems to be the root of the problem. Can not update list anb shows no chapters in titles. Thank you!

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by hypoflex** [comment]
#747 closed due to duplicate
