### ISSUE TITLE
[Bug] I can't connect haruneko with hakuneko

### ISSUE THREAD

**Issue by negareni** [manga-download/hakuneko#7430]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I don't have the option to connect the haruneko extension to haruneko.

**To Reproduce**
1. Open Haruneko
2. Go to Settings
3. I don't have the option to enable RPC.

**Expected behavior**
Can you tell me in which link is the configuration, is there any file to change? I have the latest version in use, but I do not have the RPC option.

**Screenshots**
![Screenshot 2024-09-25 102312](https://github.com/user-attachments/assets/8b6df433-9d15-40bf-b98b-3104aaee7377)

**Context (please complete the following information):**
 - OS: Windows11
 - HakuNeko Version 6.17@1cc7a

**Additional context**
I just want to know how I can connect it with the extension, thanks for your time.

**Comment by MikeZeDev** [comment]
Huuuuuuuu? There is no extension support sur [Hakuneko](https://github.com/manga-download/hakuneko/). Its for [Haruneko ](https://github.com/manga-download/haruneko/)

This ticket is nonsense, therefore invalid.

**Comment by negareni** [comment]
Sorry, I thought they were connected because I read it here:
https://github.com/manga-download/haruneko-assistant/blob/master/docs/Connect%20with%20HakuNeko.md

Excuse me, could you tell me how to use Haruneko?
