### ISSUE TITLE
[PMScans] Change domain

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#7435]
**Name of the website**
https://rackusreads.com

**Website urls (examples below)**
- Site: https://rackusreads.com
- Manga List: https://rackusreads.com/project/
- Manga example: https://rackusreads.com/manga/a-streamer-in-the-past/
- Chapter online viewer example: https://rackusreads.com/a-streamer-in-the-past-chapter-33/

**Languages**
En

**Website relationship*

**Additional details**

**Comment by MikeZeDev** [comment]
Rackus is old PMSCANS

https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/PMScans.mjs#L10

I ma gonna change this too a Website change request, and change the domain only.
