### ISSUE TITLE
[Sushiscan] Connector not working 

### ISSUE THREAD

**Issue by DrTenma12345** [manga-download/hakuneko#7437]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Hello,
when I try to download chapters from https://sushiscan.fr the list of manga appears but not the chapters themself making it impossible to download.
If you have the chance to fix it that would be amazing.
Thanks for all your work.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5615. People dont read issue template and doesnt search before. Plus, its Cloudflare i wonder how you are able to get manga list with that o_o it should not work at all

Edit : there is no Sushiscan.fr in Hakuneko, yan cant possibly download from it, We have a sushiscan.net. aaaaand... there is CloudFlare too, give up it cant be fixes
