### ISSUE TITLE
[Site Request] adumanga

### ISSUE THREAD

**Issue by Leo4Bey** [manga-download/hakuneko#7438]
**Adu Manga**

**Website urls**
- Site: https://adumanga.com/
- Manga List: https://adumanga.com/manga/
- Manga example: https://adumanga.com/manga/blue-lock/
- Chapter online viewer example: https://adumanga.com/blue-lock-bolum-1/

**Languages**
Turkish

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/issues/7318 Use search and dont open duplicates its annoying and its slowing development.
