### ISSUE TITLE
TMOFANS CONNECTOR

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#744]
> **From:** HakuNeko User

tmofans connector any download is working

<details><summary>What has been done?</summary>

</details>

**Comment by hypoflex** [comment]
connector tmofans was not found, did you mean TuMangaOnline?

**Comment by 27136773** [comment]
This is an ongoing battle between HakuNeko and TuMangaOnline... it will be updated when i'm back from vacation

**Comment by 27136773** [comment]
See #738
