### ISSUE TITLE
[Baozihm ] Connector not working 

### ISSUE THREAD

**Issue by cyldo** [manga-download/hakuneko#7440]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Connector.mjs:579 Error: This website provides a manga list that is to large to scrape, please copy and paste the URL containing the images directly from your browser into HakuNeko.
    at Baozimh._getM
![Screenshot 2024-09-28 004746](https://github.com/user-attachments/assets/54145aa1-5628-42d8-818b-b7e6fee9b845)
angas (Baozimh.mjs:24)
    at Baozimh._getMangaList (Connector.mjs:576)
    at Connector.mjs:99 
Baozimh
_getMangaList	@	Connector.mjs:579

------------------------------------------------------------------------------------------------
[- his website provides a manga list that is too large to scrape, please copy and paste the URL containing the images directly from your browser into HakuNeko -]

----- **In HakuNeko Software Where do I paste the Copied link of the manga Can you tell me in detail, Bro**

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by Sheepux** [comment]
did you do as the error message says ? Copy the link and paste it ?

**Comment by cyldo** [comment]
In HakuNeko Software Where do I paste the Copied link of the manga Can you tell me in detail, Bro
    or
 Where to paste the Copied link can you tell me sir in detail

**Comment by MikeZeDev** [comment]
Please read the manual, dont open issues when the solution is within the manual or can be found with your favorite search engine.

https://duckduckgo.com/?t=ffab&q=Hakuneko+copy+paste&ia=web
