### ISSUE TITLE
[Adumanga] Connector not working

### ISSUE THREAD

**Issue by agnamuda** [manga-download/hakuneko#7443]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Connector is added but can't use it, someone opened a issue for it not much long ago.

### To Reproduce

1. Adumanga
2. 
3. 
4. Error: No matching connector found for URL https://adumanga.com/manga/wind-breaker/

**Comment by MikeZeDev** [comment]
Issue is tagged 
![image](https://github.com/user-attachments/assets/509761c2-0426-4677-bf3f-54284df04901)

Use Haruneko, it wont be done in Hakuneko . 🤦
