### ISSUE TITLE
[Site Request] Ikiru

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#7444]
**Name of the website**
Ikiru

**Website urls (examples below)**
- Site: https://ikiru.me/
- Manga List: https://ikiru.me/manga/
- Manga example: https://ikiru.me/manga/superstar-from-age-0/
- Chapter online viewer example: https://ikiru.me/superstar-from-age-0-chapter-46-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Please add it to Haruneko too if it’s a bit difficult to find on Hakuneko, thanks

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by MikeZeDev** [comment]
alreadu done one Haruneko since its redirecting from old mangatale
