### ISSUE TITLE
[<Merlin Scans>] Connector not working

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7445]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

when I refresh the list, the squads do not arrive

### To Reproduce

1. Name of connector https://merlinscans.com/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
There is no Merlin Scan in Hakuneko

![image](https://github.com/user-attachments/assets/9d7fc6f7-2c9a-4ba3-a819-c42fa426ef3f)


Even searching "merlin" in hakuneko files gives nothing

**Comment by MikeZeDev** [comment]
Haruneko issues goes to Haruneko github 🤦
