### ISSUE TITLE
[TraduccionesAmistosas.mjs] Connector not working

### ISSUE THREAD

**Issue by negareni** [manga-download/hakuneko#7448]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

The connector is not working, I can't download anything or view the manga list. The domain has changed to https://traduccionesamistosas.eyudud.net/, I have already tried to change the domain name but it still doesn't load anything.

Sorry, can I ask an additional question? If it's not too much trouble, could you tell me how to use Haruneko? I've already downloaded it but I don't know how to start it. Thank you for your time.

### To Reproduce

1. TraduccionesAmistosas.mjs
2. All mangas.
3. All charpters.
4. This appears when using F12: 
![Screenshot 2024-09-29 184215](https://github.com/user-attachments/assets/333cfde9-1007-4559-9801-defa34bdc3b1)

**Comment by MikeZeDev** [comment]
Changing the domain is pointless. Website Changed.

If you have trouble launching Haruneko perhaps its because you got the source code and not the binary [release](https://github.com/manga-download/haruneko/releases).

Website totally changed, use [Haruneko](https://github.com/manga-download/haruneko/releases)

**Comment by negareni** [comment]
Thanks, I'll use it now.
