### ISSUE TITLE
windows app scale

### ISSUE THREAD

**Issue by hypoflex** [manga-download/hakuneko#745]
in windows 10 when sizing the window to the top to snap it to maximum height it glitches out till the full extend of the chapter. see video
https://i.gyazo.com/b793741f690c735749c7fea180af1b8c.mp4

**Comment by 27136773** [comment]
I cannot reproduce the issue.
Furthermore, based on the scroll bar in the video it looks like all images can be shown correctly within the visible area.
Seems like the bottom of the application is just hidden behind the task bar, maybe it is set to something like autohide?

**Comment by hypoflex** [comment]
yea it seemed to scale itself way below the taskbar.
currently running latest rivision #535f8edb1a which seems to not have this issue. 
will close the issue for now but keep a eye out in case i see it again.

i should've noted which version i had the issue on... my mistake on that

**Comment by 27136773** [comment]
Was probably an issue with electron prior to 6.1.7
