### ISSUE TITLE
[NatsuID] Downloaded chapter images are in bin format 

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#7451]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

the chapters I downloaded on the site are in .bin format, not only in NatsuID, but also Kiryuu, ikuru(mangatale) please help.. the same thing I also experienced in haruneko.. Thanks

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Not on every chapter apparently 
![image](https://github.com/user-attachments/assets/d799f47b-213e-4f7b-84c3-f01a7ef9efc7)

Its not your first issue you should know how to follow the instruction right? 

![image](https://github.com/user-attachments/assets/565d9460-491e-47a9-b328-6b5c450321e0)

**Comment by MikeZeDev** [comment]
Old chapters may have been deleted, so no amount of magic will fix them

![image](https://github.com/user-attachments/assets/72cfb1a2-fdad-47bf-8ee0-cc6c912dfc11)

But the first thing to check BEFORE opening an issue like that is : "is the chapter ok on the website? " so i assume your problem is not those 404 errors.

**Comment by MikeZeDev** [comment]
Closed as : 

* OP did not provide necessary infos
* Cant reproduce
