### ISSUE TITLE
[Sites Request] Some websites

### ISSUE THREAD

**Issue by Infel1** [manga-download/hakuneko#7452]
**Websites urls**
 https://seriesemperor.com/
 https://leerolymp.com/
 https://hadesnofansub.com/
 https://mg.mundodrama.site/
 https://tresdaos.com/
 https://panconcola.com/
 https://taurusmanga.com/
 https://shadowmangas.com/
 https://mh.cookni.net/
 https://theblank.net/
 https://visorscamber-scans.com/
 https://latan.visorsmr.com/
 https://traduccionesamistosas.eyudud.net/

**Languages**
 -Spanish

**Comment by MikeZeDev** [comment]
Rejected, one website by request. Please follow the instructions or dont open tickets, thanks.
