### ISSUE TITLE
[<Doujindesu>] Connector not working

### ISSUE THREAD

**Issue by klinnxz** [manga-download/hakuneko#7453]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

please add new connectors for doujindesu

### To Reproduce

1. Name of connector : https://doujindesu.tv/
![dddd](https://github.com/user-attachments/assets/fae02400-56ec-485c-9b20-cea01e1ba291)

2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
> ask to add it as connector when it already exists
> do not search for existing issue 
> an old issue exists and its unsolvable because the problem is Cloudflare

Closed as duplicate, unsolvable, and we both lost our time because you didnt search first.  Read the instructions please. Dont open duplicates issues.

https://github.com/manga-download/hakuneko/issues/6594
