### ISSUE TITLE
[ Samurai Scan] domain changed

### ISSUE THREAD

**Issue by Infel1** [manga-download/hakuneko#7454]
**Name of the website**
_Samurai_

**Website urls (examples below)**
- https://latan.visorsmr.com/?swcfpc=1

**Languages**
-Spanish

**Comment by negareni** [comment]
Use this code and it works:

import WordPressMadara from './templates/WordPressMadara.mjs';

export default class SamuraiScan extends WordPressMadara {

    constructor() {
        super();
        super.id = 'samuraiscan';
        super.label = 'Samurai Scan';
        this.tags = [ 'webtoon', 'spanish' ];
        this.url = 'https://latan.visorsmr.com/';
    }
}

You just have to save it as a file "XXXX.mjs" (in my case it is samuraiscan.mjs) and place it in the top of "C:\hakuneko-desktop_6.1.7\cache\mjs\connectors".

**Comment by wow2134** [comment]
@negareni wow thx, maybe it can be used as a reference for other websites

**Comment by MikeZeDev** [comment]
> @negareni wow thx, maybe it can be used as a reference for other websites

It only applies to similar websites ofc .

@negareni you know you can submit it ? With a proper icon (64x64px, PNG, no extension) and removing the trailing slash it will be fine.

**Comment by MikeZeDev** [comment]
Bruh, its already added 🤦 

![image](https://github.com/user-attachments/assets/14f6093c-f08e-4591-bc63-d3ad3221b111)

In that case make a Website change request not a "Website suggestion" 😢
