### ISSUE TITLE
[Site Request] Renta

### ISSUE THREAD

**Issue by reddy791** [manga-download/hakuneko#7455]
**Name of the website**
Renta

**Website urls (examples below)**
- Site: https://www.ebookrenta.com/
- Manga List: https://www.ebookrenta.com/renta/sc/frm/newrelease/?rsi=c&genm=Yaoi_Manga
- Manga example: https://www.ebookrenta.com/renta/sc/frm/item/146512/
- Chapter online viewer example: https://jp-dre2.ebookrenta.com/sc/view_timg_en/1536da689cfc31d7c6/9-2427547-84/rbc1002/index.view

**Languages**
English manhua manga official

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Another day, another people not using search feature

https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+ebookrenta&type=issues

Duplicate https://github.com/manga-download/hakuneko/issues/4159
