### ISSUE TITLE
[Site Request] Mangaworldadult

### ISSUE THREAD

**Issue by FrederikaBern** [manga-download/hakuneko#7456]
**Name of the website**
Mangaworldadult

**Website urls (examples below)**
- Site: https://www.mangaworldadult.net/
- Manga List: https://www.mangaworldadult.net/archive
- Manga example: https://www.mangaworldadult.net/manga/734/rain
- Chapter online viewer example: https://www.mangaworldadult.net/manga/734/rain/read/5f78dd410a01bf41420ffe97

**Languages**
Italian

**Website relationship*
https://www.mangaworld.ac/

**Comment by MikeZeDev** [comment]
1) Search first https://github.com/manga-download/hakuneko/issues/4810 😮‍💨 
2) Already done in Haruneko as the tag says, uses haruneko

**Comment by FrederikaBern** [comment]
Sorry again for the trouble, but on Hakuneko I only find “Mangaworld” and not “Mangaworldadult” so I thought it should be added.

**Comment by MikeZeDev** [comment]
I have written Haruneko.
