### ISSUE TITLE
[Site Request] renta.papy.co.jp

### ISSUE THREAD

**Issue by ErickShadow12** [manga-download/hakuneko#7458]
**Name of the website**
renta.papy.co.jp

**Website urls (examples below)**
- Site: https: https://renta.papy.co.jp/
- Manga List: https://renta.papy.co.jp/renta/sc/frm/newrelease?sort=new&term=w0&site_type=c&genre=%BE%AF%BD%F7%CC%A1%B2%E8
- Manga example: https://renta.papy.co.jp/renta/sc/frm/item/346834/title/2553232/
- Chapter online viewer example: https://dre-viewer.papy.co.jp/sc/view_timg2/8e7827dc5ad885ec85/9-2421656-84/FIX001/index.view

**Languages**
List of languages supported by the website
Japan
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)
-is an official platform
-in haruneko, it may work.

**Comment by MikeZeDev** [comment]
https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+renta&type=issues
