### ISSUE TITLE
[Site Request] 嗨皮漫画 

### ISSUE THREAD

**Issue by suikodoen13** [manga-download/hakuneko#7460]
Request for new manga website:
https://m.happymh.com/

**Comment by MikeZeDev** [comment]
Bruh : https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+happymh&type=issues

* Being asked how many time? Search before.
* Impossible to do as it redirect to tencent comics for any contributor that tried

**Comment by vetp** [comment]
This site has a double Cloudflare protection — one to access the main site and another to access the image server.

**Comment by MikeZeDev** [comment]
Doesnt change the fact that website redirect to Tencent Comic or is inaccessible with my Chinese IP.
Inaccessible website = wont be added
