### ISSUE TITLE
[Site Request] m.blogtruyenmoi.com

### ISSUE THREAD

**Issue by Katsuco** [manga-download/hakuneko#7461]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://m.blogtruyenmoi.com/
- Manga List: https://m.blogtruyenmoi.com/danhsach/tatca
- Manga example: https://m.blogtruyenmoi.com/28832/one-shot-kamen-rider-black-part-x-mau-vat-mo-phong-so-7
- Chapter online viewer example: https://m.blogtruyenmoi.com/c645884/one-shot-kamen-rider-black-part-x-mau-vat-mo-phong-so-7-part-x

**Languages**
Vietnamese
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Search feature. Use it, please.

https://github.com/manga-download/hakuneko/issues/5927
