### ISSUE TITLE
[AniWave.se] New AniWave URL

### ISSUE THREAD

**Issue by twig046** [manga-download/hakuneko#7464]
AniWave

- Site: https://aniwave.se/
- Anime List: https://aniwave.se/anime-list/
- Anime example: https://aniwave.se/anime-watch/isekai-shikkaku/

**Languages**
English
Japanese

**Website relationship*
Aniwave.to (Down)

**Comment by MikeZeDev** [comment]
Its a clone, website is closed

**Comment by twig046** [comment]
could you add this one anyways?
