### ISSUE TITLE
[<Manga Tilkisi>] Connector not working

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7467]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The site's address has been renewed

### To Reproduce

1. Name of connector  Manga Tilkisi 
2. Name of manga (if connector update is working) https://www.manga-tilkisi.com/
3. Name of chapter (if manga update is working)https://www.manga-tilkisi.com/manga/kopyalayip-yapistirarak-zindanlari-fethediyorum/bolum-16/
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
There is no Manga Tilkisi  in Hakuneko.

**Comment by Tianzhou2** [comment]
> There is no Manga Tilkisi in Hakuneko.

I am using hakuneko-nw-v0.92.0-win-version.When you change the site address, the site remains the same.For example, they changed it again and it remains that way.
new adress https://www.mangatilkisi.com/
