### ISSUE TITLE
mangapark Connector not working

### ISSUE THREAD

**Issue by ailingstorm** [manga-download/hakuneko#7469]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

all mangapark related connectors point to non existing links 
.link, .org etc 
correct link is .com 

### To Reproduce

1. try to use either mangapark, mangapark (acg) or mangapark today connector 
2. it doesn't work because those sites it points to dont exist

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/2275847a-4c81-4115-9d2e-79c1af7cd0b4)

* Mangapark.org works

![image](https://github.com/user-attachments/assets/0b354a35-8928-4495-ae3c-63f90b400c1a)

* MangaPark.net works
![image](https://github.com/user-attachments/assets/553086b3-cda9-4025-99c2-2b4666fba621)

* There is no .link in Hakuneko

* Today is dead for years we know that.

Problem is inexistant and only on your end, for whatever reason.

**Comment by MikeZeDev** [comment]
I assume they are unreachable in your browser too so you declared them as "Dead". Since they are not dead at all, there is nothing we can do.
You should search for the reason why you cant reach those websites. Government blocking ? 

The common advice would be to use a VPN or at least an alternative DNS server on your computer.
Hakuneko is not meant to bypass censorship 😔 .

**Comment by ailingstorm** [comment]
its cool (tho maybe you ought to remove the connector for the site u know is dead) i could never get it to connect from hakuneko for whatever reason, i do use a vpn and tried it with the vpn both on and off; i eventually got the sites to load from my browser. so something is screwy but it may well be in my setup. sorry for wasting your time.

**Comment by MikeZeDev** [comment]
If we start removing dead websites now we will never see the end. We have limited time, and we are focusing on [Haruneko](https://github.com/manga-download/haruneko/) :D
