### ISSUE TITLE
Unable to download ZeroScan list

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#747]
> **From:** HakuNeko User

Hi, I just wanted to report that it seems like something is broken with ZeroScans and possible a few other websites where I'm able to access the the website from the internal browser but when I try to download the list I get this error message https://i.imgur.com/buj0Jx9.png I've gone through the troubleshooting steps that was shown before this report message and none seem to change anything.

I'm using the latest nightly build (20191122.1) on Windows 10, 1909

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by hypoflex** [comment]
according to the hakuneko its trying to pull a admin page. which  to me sounds pretty weird. connector has to be reviewed.
