### ISSUE TITLE
[<Manga Galaxy>] Connector shows last 10 chapters in haruneko

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#7474]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

All the mangas in the connector show the latest 10 chapters only (like from chap 130 - 139) and if a new chapter 140 drops then 130 will disappear.
![image](https://github.com/user-attachments/assets/9811df12-4aa5-4112-b49d-1d6896ee4554)

in the website you can see the previous chapters
![image](https://github.com/user-attachments/assets/117ed9b9-a5de-4b18-88bd-04cdff9f60d7)

### To Reproduce

1. Manga Galaxy (mangagalaxy.net)
2. Any Manga
3. only last 10 chapters of manga appear

**Comment by MikeZeDev** [comment]
Post an issue in Haruneko github  🤦

**Comment by Murshid7absi** [comment]
Ok, but last I posted an issue on haruneko I got the same reply and to post on hakuneko
