### ISSUE TITLE
[Feature] Update to supported version of electron

### ISSUE THREAD

**Issue by Starmania** [manga-download/hakuneko#7476]
**Is your feature request related to a problem? Please describe.**
Every Cloudflare problem. And electron support.

**Describe the solution you'd like**
Bump electron version to at least 30.0.0 (Chromium 124.0.6367.49, V8 12.4, and Node.js 20.11.1)

**Describe alternatives you've considered**
Put it off until tomorrow

**Context (please complete the following information):**
 - 62c4d5e741259f70f9ee4b21babd54eb29bf19dc

**Additional context**
I think that if no one has done it so far, it must be creating big problems. So I suggest I take care of it myself. 

But first, I'm trying to figure out why it's stuck. So I open this issue as a meta-issue, which says what needs to be done, progress and resolution

**Comment by Sheepux** [comment]
hakuneko cannot be updated due to major regressions. See the pinned issue https://github.com/manga-download/hakuneko/issues/2933
If you want an updated version use haruneko https://github.com/manga-download/haruneko it's a full rework

**Comment by Starmania** [comment]
Ok, I will take a look to the new version
