### ISSUE TITLE
[Site Request] Batcave.biz

### ISSUE THREAD

**Issue by TheDaringDevil** [manga-download/hakuneko#7477]
**Name of the website**
[Batcave](https://batcave.biz/)

**Website urls (examples below)**
- Site: https://batcave.biz
- Manga List: https://batcave.biz/comix/
- Manga example: https://batcave.biz/16696-transformers-2023.html
- Chapter online viewer example: https://batcave.biz/reader/16696/112571

**Languages**
List of languages supported by the website: English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ..."): N/A

**Additional details**
Add any other context details that you may have found (like template to reuse): N/A

Edit: Wasn't aware there was a duplicate issue of this, my mistake. Feel free to delete/close this if you want

**Comment by MikeZeDev** [comment]
If you see its a duplicate you can close it yourself "as not planned"  :D
