### ISSUE TITLE
[Zebrack (ゼブラック)] Login not working

### ISSUE THREAD

**Issue by nickstu** [manga-download/hakuneko#7478]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

I'm trying to download some chapters that I have purchased from Zebrack
I managed to login (I saw that this is only possible using the Nightly build, so I'm using that, I'm currently on 8.3.4. Login works fine, I can see my account from the browser within Hakuneko
I managed to find the chapterlist by pasting the URL, so the connector tab is showing [Clipboard]
Download don't go past 12 free chapters, even though I have bought the first two volumes
I might just be doing something dumb and it's my fault

### To Reproduce

1. Connector: Zebrack (although I'm pasting the url, so the connector tab shows Clipboard)
2. Name of manga ラーメン赤猫
3. Name of chapter 十三杯目先輩風は凪
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

EDIT: having figured out the problem, I updated the description
I bought volumes, but hakuneko is looking for chapters
chapters look like this
https://zebrack-comic.shueisha.co.jp/title/34726/chapter/566687/viewer
but volumes look like this
https://zebrack-comic.shueisha.co.jp/title/34726/volume/136159/viewer
is there a way I can use it to download the volumes?
I suppose I could look at the code and figure it out, but maybe there's an easy way?

if someone could point me to the relevant script maybe I can change it myself

**Comment by MikeZeDev** [comment]
* Did you used a third party account? If  you did used a third party account its not even worth investigating its kinda guaranteed not to work

* Once you fetched chapters the list is cached until you restart hakuneko so better login first then go to the manga.

* Perhaps you should provide the manga url ? 

* Thats something hard to diagnose as devs wont pay to test.

**Comment by nickstu** [comment]
I think I found out the reason
I bought volumes, but hakuneko is looking for chapters
chapters look like this
https://zebrack-comic.shueisha.co.jp/title/34726/chapter/566687/viewer
but volumes look like this
https://zebrack-comic.shueisha.co.jp/title/34726/volume/136159/viewer

is there a way I can use it to download the volumes?
I suppose I could look at the code and figure it out, but maybe there's an easy way?

**Comment by nickstu** [comment]
update:
I digged into the code and found the Manga class

I changed the constructor to 

```
        const parts = id.split('/');
        parts[3] = 'volume';
        id = parts.join('/');
        this.id = id;
```

so that now it fetches and downloads volumes instead of chapters. kinda hacky but it worked!

**Comment by MikeZeDev** [comment]
Perhaps Haruneko works?

**Comment by nickstu** [comment]
Yes, it works.
I'm just curious if there's a way to do what I did without hacking the code
But the Issue can be closed
