### ISSUE TITLE
[Welovemanga.one] Connector not working and can not read 'property' replace of undefined

### ISSUE THREAD

**Issue by ch4rlygit** [manga-download/hakuneko#7479]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

can not read the manga list from welovemanga.one take forever loading, so i use manual url manga name from clipboard (https://welovemanga.one/2099/), it succeed but when i click download one of the chapter list, it is failed saying  "cannot read property 'replace' of undefined"

### To Reproduce

1. Welovemanga (because connector cannot fetch the list so i use url from clipboard (https://welovemanga.one/2099/)
2. [RYUUROUDEN: OUHA RIKKOKU-HEN - RAW](https://welovemanga.one/2099/)
3. chapter 69
4. cannot read property 'replace' of undefined
![CaptureError2](https://github.com/user-attachments/assets/49051d9c-2da4-47cf-adcc-f5fc1219c120)

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/ce8eb2c2-0d28-46dd-95af-a90b73035ab0)

Preview does the same things that downloading. IIrc this website and similar one got anti DDoss, perhaps you triggered it?

**Comment by ch4rlygit** [comment]
Hi, today i tried it again, and it is the same error showing "cannot read property 'replace' of undefined" . I only open one apps which is Hakuneko, nothing else. I dont know what to do.

**Comment by MikeZeDev** [comment]
And since i cant reproduce the problem i dont know whats going on. Posting more message saying it doesn't work wont help.
