### ISSUE TITLE
Add Site: Viz Media's Shonen Jump Vault

### ISSUE THREAD

**Issue by MrKimiko** [manga-download/hakuneko#748]
https://www.viz.com/shonenjump

jdownloader 2 does rip the manga using login credentials, but you have to jump from VPN to VPN.

I love this app that you created. It works wonderful for Crunchyroll.

**Comment by Ever4engel** [comment]
This website work with a VPN

**Comment by MrKimiko** [comment]
> This website work with a VPN

I live in Florida so as far as I know it works if you use a VPN within the United States. I have to jump from VPN to VPN within the United States whenever there is an error that occurs with jdownloader. Also it can help you extend past the 100 chapters a day limit but not by much.

**Comment by XenonR** [comment]
I like the page and gave it a shot. Can confirm VPN required and **pictures are scrambled**. So it's far above my proficiency level...

**Comment by gary360** [comment]
How do you unscramble the image?

**Comment by gary360** [comment]
> I like the page and gave it a shot. Can confirm VPN required and **pictures are scrambled**. So it's far above my proficiency level...

How do you unscramble the image

**Comment by 27136773** [comment]
It is all shown in the source code of the PR
