### ISSUE TITLE
[Site Request] SlimeRead

### ISSUE THREAD

**Issue by Johan307** [manga-download/hakuneko#7482]
**Name of the website**
Slime Read

**Website urls (examples below)**
- Site: https://scrap.slimeread.com/
- Manga List: https://scrap.slimeread.com/pesquisa-obras/pesquisar
- Manga example: https://scrap.slimeread.com/manga/264/monstro
- Chapter online viewer example: https://scrap.slimeread.com/ler/264/cap-162

**Languages**
Portuguese

**Website relationship*

**Additional details**

**Comment by MikeZeDev** [comment]
bruh https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+slimeread&type=issues
