### ISSUE TITLE
[Site Request] Utoon

### ISSUE THREAD

**Issue by IsamiTahara** [manga-download/hakuneko#7488]
**Utoon**
Utoon

**Website urls (examples below)**
- Site: https://utoon.net/
- Manga List: https://utoon.net/manga/
- Manga example: https://utoon.net/manga/the-game-that-i-came-from/
- Chapter online viewer example: https://utoon.net/manga/the-game-that-i-came-from/chapter-313/

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Literally no one knows how to use search today 😢 .

https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+Utoon&type=issues
