### ISSUE TITLE
[<TuMangaOnline>] Connector not working

### ISSUE THREAD

**Issue by Wormzhao** [manga-download/hakuneko#7489]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

It just doesn't show the list of manga, I assume it has to do with the website address changing. The connector shows: URL: https://visortmo.com However, the site has changed its address to: https://zonatmo.com. Another important detail is that even by copying the URL of some manga, Hakuneko does not detect any chapter.

### To Reproduce

1. TuMangaOnline
2. None
3. None
4. Failed to update manga list for TuMangaOnline. This website does not provide a manga list, please copy and paste the URL containing the chapters dorectry from your browser into HakuNeko

**Comment by MikeZeDev** [comment]
There is already an issue literally one the same first page you are posting. Come on, use your eyes.
