### ISSUE TITLE
Komiku not work well

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#749]
the getmangalist, getchapterlist and previews or download feature is not work propely. so, I tried to fix and it worked well. (maybe, cause i just test in 1 manga).
here's the fix:

this.queryMangas = 'div#a-z ol li.ranking1 h4 a';
this.queryChapters = 'section#chapter table.chapter tbody._3Rsjq tr td.judulseries a.iklan';
this.queryPages = 'div#readerareaimg.konten source[src]:not([src=""])';

please commit it to master because i not join / make a branch
thank you.

**Comment by 27136773** [comment]
I cannot access the website, could this be region locked for indonesia?

**Comment by MIRVOUS** [comment]
maybe(i don't know how to check the region lock, but this site is use cloudflare)

**Comment by dodieboy** [comment]
yup, it is region locked for Indonesia only. tried using vpn and it work.
