### ISSUE TITLE
[Site Request] Comic Fans

### ISSUE THREAD

**Issue by crystaluna** [manga-download/hakuneko#7490]
**Name of the website**
Comic Fans

**Website urls (examples below)**
- Site: https://bilibilicomics.net/
- Manga List: https://bilibilicomics.net/explore.html
- Manga example: https://bilibilicomics.net/comic/2179-the-saintess-has-a-showdown.html
- Chapter online viewer example: https://bilibilicomics.net/episode/414-she-s-the-saint.html

**Languages**
English

**Website relationship*
copy of Bilibilicomics before it Shutdown.

**Comment by MikeZeDev** [comment]
Bruh [github](https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+Comicfans&type=issues)
