### ISSUE TITLE
[Site Request] Yuramanga

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#7498]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://www.yuramanga.my.id/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://www.yuramanga.my.id/series/i-quit-the-heros-party/
- Chapter online viewer example: https://www.yuramanga.my.id/i-quit-the-heros-party-chapter-50-bahasa-indonesia/

**Languages**
List of languages supported by the website
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
How many time should i tell you? Search BEFORE opening duplicates. https://github.com/manga-download/hakuneko/issues/6456
