### ISSUE TITLE
[<OlympusScanlation.mjs>] Connector not working

### ISSUE THREAD

**Issue by negareni** [manga-download/hakuneko#7503]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

It does not allow downloading, nor does it update.
I was trying to change the url to the new one that has "zonaolympus@com/" (change @ to .) following the logic shown in the code "\\\hakuneko/blob/master/src/web/mjs/connectors/OlympusScanlation.mjs" but it doesn't work.
The errors that it shows with f12 are the following:
![Screenshot 2024-10-18 193100](https://github.com/user-attachments/assets/c5b9b2b7-e2eb-47e6-84e3-4abd158d365c)
![Screenshot 2024-10-18 193122](https://github.com/user-attachments/assets/c7d5edfa-8cf2-4e96-a107-1e1a6daa2d66)
Could you please update it?
PD: Hmm.. now that I check the discord for that scanlation they say that this week they will be changing to that new url (zonaolympus@com/ (change @ to .) ) and that the previous domains will stop working, so I leave it as information here, since it is possible that the information on the website will change within this week. Thank you for your time and help.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Wait its not https://leerolymp.com ? derp they are annoying. 
Your problem is that now they force the need of "type" parameter when fetching mangas. 

```js
   async _getMangasFromPage(page) {
        const uri = new URL(`/api/series?page=${page}&direction=asc&type=comic`, this.apiUrl);
```

Just fixed it in Haruneko btw ^^

**Comment by negareni** [comment]
Thank you very much for the help, I've been busy these days so I'm just connecting, thanks again.
