### ISSUE TITLE
[Site Request] Weeb Central

### ISSUE THREAD

**Issue by Nem-z** [manga-download/hakuneko#7510]
**Weeb Central**
Weeb Central

**Website urls (examples below)**
- Site: https://weebcentral.com/
- Manga List: N/A
- Manga example: https://weebcentral.com/series/01J76XY7E9FNDZ1DBBM6PBJPFK/One-Piece
- Chapter online viewer example: https://weebcentral.com/chapters/01J76XYYR7R8A4C9QK5HW9KVCJ

**Languages**
English

**Website relationship**
It's the new domain of MangaSee and MagaLife

**Additional details**
Current MangaSee connector isn't working anymore because of the changes.
FAQ where it's stated it's the new hostname for MangaSee and MangaLife: https://weebcentral.com/faq

**Comment by MikeZeDev** [comment]
Derp https://github.com/manga-download/hakuneko/issues/7407
