### ISSUE TITLE
-

### ISSUE THREAD

**Issue by nickstu** [manga-download/hakuneko#7511]

**Comment by MikeZeDev** [comment]
Everyday, at least one people post an already existing issue. 

https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+bookwalker&type=issues

https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+book+walker&type=issues

I wonder if github should use fancy colors for the search button ?

**Comment by nickstu** [comment]
sorry, in my defense I have to say I searched for it but ended up on haruneko instead of hakuneko, then opened the issue on hakuneko through the website. I understand your frustration, but I assure you I did think of that
