### ISSUE TITLE
Removal Request for [DGTeam]

### ISSUE THREAD

**Issue by Mattdgt** [manga-download/hakuneko#7513]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Which website should be removed?
dgtread.com

Why should this website be removed from HakuNeko?
Because other sites take scans to earn on their sites without even putting us in credits

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
Yes but at least let's make the process more difficult for them
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?
Yes I have
3. Have you already protections in place to prevent scraping (e.g. CloudFlare, Captcha, Link Encryption, ...)
Cloudflare

#### In case of Monetization
1. Are you using Donations?
nope
2. Are you using Advertisements?
yep

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by MikeZeDev** [comment]
Please note that this comment only reflect my personal opinion.

If your website already use CloufFlare captcha there is no way it should working in Hakuneko anyway 🤷 .
Its already making mainstream scrapers life hard enough. Mihon users are also struggling with that. I can see its not activated right now.

If your main concern are credits maybe you can include light but hard to remove watermarks. Its not like you are complaining about bandwidth or server costs which are more concerning than rippers imho. Everyone hate rippers but removal wont stop them.

In the past some of my work was ripped many times, i perfectly understand the frustration but i think this request is a bit pointless as rippers can barely use Hakuneko with CloudFlare, For now.

**Comment by Robonau** [comment]
he may be using cloudflare but he ain't using any of the protections it affords, no captcha, no wait for cloudflare screen, nothing, literally any scraper will be able to scrape it

**Comment by antoine-sncf** [comment]
Note: user also requested to add a website.
https://github.com/manga-download/hakuneko/issues/7481
Removal requests cannot be 2 sides of the same coin.

**Comment by Sheepux** [comment]
Note: user also requested to add websites.
https://github.com/manga-download/hakuneko/issues/7481 https://github.com/manga-download/hakuneko/issues/7480
Removal requests cannot be 2 sides of the same coin.

**Comment by Mattdgt** [comment]
I use wordpress cloudflare so sometimes it works and sometimes it doesn't. I tried using hakuneko and it downloads the scans. So I'm probably doing something wrong... It was easier for me to have the site removed from hakuneko than to set up new protections that could make reading unpleasant for our fans.
For sheepux... Adding sites for translating chapters from Japanese to Italian is different from adding sites for profit without doing anything.

**Comment by 27136773** [comment]
There is no website [DGTeam](https://github.com/search?q=repo%3Amanga-download%2Fhakuneko%20dgteam&type=code) in HakuNeko

The closest match would be https://dgtread.com, which is not qualified for removal as condition `I` is not fulfilled:
_must provide download links_

**Comment by 27136773** [comment]
Duplicate #1331
