### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MelissaECosta** [manga-download/hakuneko#7514]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Below is the error that I receive in the Item List window upon selecting a manga:

C_<FetchProvider_Fetch_CloudFlareChallenge>: The request to "https://vyvymanga.net/manga/the-invicible-princess-is-bored-again-today" was rejected by CloudFlare Anti-Bot detection. Make sure to bypass CloudFlare before accessing the content of this website (e.g., with the HakuNeko Assistant browser extension).
The request to "https://vyvymanga.net/manga/the-invicible-princess-is-bored-again-today" was rejected by CloudFlare Anti-Bot detection. Make sure to bypass CloudFlare before accessing the content of this website (e.g., with the HakuNeko Assistant browser extension).

**To Reproduce**
1. Choose the VyManga connector from the list.
2. Find "Experienced forecast" manga and select it.
3. See error.
NOTE: This seems to be happening whenever ANY manga is selected from this connector. 

**Expected behavior**
Should see the list of comics available. 

**Screenshots**
See error message

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version - Unable to see this information. When I go to Using version XXX, I see an error message. Not sure if that's relevant. 

**Additional context**

**Comment by MikeZeDev** [comment]
You opened an Haruneko issue on HaKuneko github 🤦 
Plus its cloudflare, read the manual, use Haruneko assistant withing Chrome 

There is nothing to fix
