### ISSUE TITLE
[Site Request] corocorocomic

### ISSUE THREAD

**Issue by CderF** [manga-download/hakuneko#7515]
**Name of the website**
corocorocomic

**Website urls (examples below)**
- Site: https://www.corocoro.jp/
- Manga List: https://www.corocoro.jp/rensai
- Manga example: https://www.corocoro.jp/title/149
- Chapter online viewer example: https://www.corocoro.jp/chapter/29711/viewer

**Languages**
japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Bruh https://github.com/manga-download/hakuneko/issues/5715
