### ISSUE TITLE
[comicborder] Connector not working

### ISSUE THREAD

**Issue by kanjieater** [manga-download/hakuneko#7516]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

https://comicborder.com/ manga wont load anymore 

### To Reproduce

1. comicborder
2. ビジャの女王 https://comicborder.com/episode/3269754496603914265
3. All chapters
4. None

**Comment by MikeZeDev** [comment]
you can still paste link for now

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/b7c61ccb-dfc0-49ed-8b04-3f1ce3f35a9b)

List fetched just fine
