### ISSUE TITLE
[Site Request] MangaRose

### ISSUE THREAD

**Issue by ZIRKOB** [manga-download/hakuneko#7518]
**Name of the website**
MangaRose

**Website urls (examples below)**
- Site: https://mangarose.net/
- Manga List: https://mangarose.net/manga/
- Manga example: https://mangarose.net/manga/god-of-martial-arts/
- Chapter online viewer example: https://mangarose.net/manga/god-of-martial-arts/288-2/

**Languages**
arabic

**Comment by MikeZeDev** [comment]
Already supported https://github.com/manga-download/hakuneko/blob/0afb0231c1fdcba8aac78143395bec2d74e064f1/src/web/mjs/connectors/MangaRose.mjs#L4

Its a domaine change, make a proper issue not a "website suggestion"

**Comment by ZIRKOB** [comment]
Ur wrong this is new Arabic website not turkish they just has the same name
