### ISSUE TITLE
[<TMOManga,NovelCool,MiauScan,tumangaonline>] Connector not working

### ISSUE THREAD

**Issue by lilo115** [manga-download/hakuneko#7519]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Aparece los nombre de todos los mangas del sitio pero no los capitulos todos estan vacios. 

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
1) One issue per website, dont be lazy
2) English please
2) You made at least one duplicate. There is already a tumangaonline issue on the same page you are posting. Lazyness much? 

* TMOManga : cant reproduce problem
* NovelCool (ES) : cant reproduce problem
* Miauscan: domain change
