### ISSUE TITLE
Newest manga updates aren't listed

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#752]
> **From:** HakuNeko User

I've been struggling for over two weeks to download chapters from series that I've been following.  
At Mangakakalot/Manganel, a certain series (Chuan Yue Xi Yuan 3000 Hou, the listing only shows what I have already downloaded (which was from ch332 to 353) but when I open the site via the browser OR hakuneko, the manga is already at chapter 374.

This is also the issue with Mangakakalot/Manganel's Fei Xi Yan Xue.  It only shows the already downloaded chapters (available offline) and stops at ch286 while it has already reached ch321.

 I've  been following these manga's at these specific sites because they are more up to date than the other sites.  

I've been using Hakuneko because it has an easy User Interface. 

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by dodieboy** [comment]
It works fine for me. Have you tried updating the manga list by pressing the small refresh button on the right?
![image](https://user-images.githubusercontent.com/9015764/70859974-73487b80-1f56-11ea-818c-64c705630246.png)

**Comment by 27136773** [comment]
See: #731
See: #737
