### ISSUE TITLE
Yaoi Manga Online

### ISSUE THREAD

**Issue by ginmoz** [manga-download/hakuneko#7521]
**Name of the website**
Yaoi Manga Online

**Website urls (examples below)**
- Site: https://yaoimangaonline.com/
- Manga List: https://yaoimangaonline.com/yaoi-manga/
- Manga example: https://yaoimangaonline.com/a-man-of-virtue-by-ggang-e-wook-eng/
- Chapter online viewer example: https://yaoimangaonline.com/a-man-of-virtue-by-ggang-e-wook-eng/2/

**Languages**
- English
- Japanese
- Chinese
- Korean
- Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Another day another duplicate https://github.com/manga-download/hakuneko/issues/4907
