### ISSUE TITLE
[Site Request] cuutruyen

### ISSUE THREAD

**Issue by enzief** [manga-download/hakuneko#7526]
**Name of the website**
cuutruyen

**Website urls (examples below)**
- Site: https://cuutruyen.net/
- Manga List: https://cuutruyen.net/newest
- Manga example: https://cuutruyen.net/mangas/1163
- Chapter online viewer example: https://cuutruyen.net/mangas/1163/chapters/21721

**Languages**
Vietnamese

**Website relationship*
Current domain names:
- cuutruyen.net
- hetcuutruyen.net
- nettrom.com
- cuutruyenpip7z.site

**Additional details**
Each page is stored on the server sliced and scrambled. The website utilizes JS function to de-scramble the pages before displaying.

**Comment by MikeZeDev** [comment]
https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+cuutruyen&type=issues

Moreover : 
![image](https://github.com/user-attachments/assets/c7c76405-9502-4ea1-a59a-c6663942e0b8)

Use nightly 🤦 Or Haruneko
