### ISSUE TITLE
[Bug] HakuNeko Configuration Bug

### ISSUE THREAD

**Issue by Kharlitoz21** [manga-download/hakuneko#7528]
When using the "One by one" option in the Network section of the settings in HakuNeko, the configuration resets automatically to "Concurrent" after exiting the settings menu. This change causes high CPU usage while downloading chapters, affecting overall performance. Since I cannot keep the setting on "One by one," my PC experiences significant strain. If someone could help me with this, I would greatly appreciate it.

![image](https://github.com/user-attachments/assets/222dfad5-e9f0-4042-8faf-55b72179faa7)

**Comment by Sheepux** [comment]
As written in the screenshot "placeholder they do nothing"
Also if there is an issue with haru, create it in haru's git
