### ISSUE TITLE
[Lezhin] Connector not working

### ISSUE THREAD

**Issue by reddy791** [manga-download/hakuneko#7530]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

In Haruneko. I'm encountering an issue on LezhinUS where pasted media links do not display any content, despite being logged in. I pressed F12, and there appears to be an error, which I’ve added  below. I noticed Lezhin recently updated its website, and I’m unsure if this issue is related or if a fix is in progress or if it occurs only me(but other connectors work fine), since I searched and didn't see anyone talking about it.

### To Reproduce

1. LezhinUS
2. All 'Cause I'm Cute-https://www.lezhinus.com/en/comic/cuzimcute
3. 
4. 

actions.ts:40 C_<Frontend_Media_PasteLink_NotFoundError>
    at HTMLButtonElement.L [as __click] (https://haruneko.pages.dev/M2T4BUG4/FrontendClassic.js:26:8632)

**Comment by MikeZeDev** [comment]
Use haruneko github for haruneko issues
