### ISSUE TITLE
[Feature]Add an option to decide whether download metadata.json file

### ISSUE THREAD

**Issue by guohao414** [manga-download/hakuneko#7533]
Some Website like 'tonarinoyj' used a json file which contains image links when chapter-page loaded.
Could you make a setting option so we can export this json file into the chapter folder.
Filename maybe like 'metadata.json' or '[chaptername].json'.

 - HakuNeko Version [6.1.7]

**Comment by MikeZeDev** [comment]
I dont see the use for it. Its too much a niche case. 🤷

**Comment by Sheepux** [comment]
I also don't see any use cases for that. I vote for closing it

**Comment by guohao414** [comment]
If I got the json file,I can download the image even though the chapter expired for free reading.
But just as you said, It's nothing more than a niche case, so I suggest make it an optional function rather than a fixed function.
Thank you guys for review，unfortunately I guess I'll just have to figure it out myself.
