### ISSUE TITLE
[<Newtoki/Manatoki>] Connector not working

### ISSUE THREAD

**Issue by hiimusagi** [manga-download/hakuneko#7535]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

newtoki/manatoki changed to https://newtoki465.com/ 
Cannot read property 'href' or undefined 
![image](https://github.com/user-attachments/assets/571517e7-f139-4517-9dfa-edc45a2a411a)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
change url in settings this is wht its make for

**Comment by hiimusagi** [comment]
I already changed the url in the settings section and still the same result.

**Comment by MikeZeDev** [comment]
Deleted posts as newtoki is not manatoki. Also you should know that tokis website use cloudflare so they are unusable in Hakuneko.
