### ISSUE TITLE
[<mangaz>] Connector not working (no content found)

### ISSUE THREAD

**Issue by Tenome** [manga-download/hakuneko#7540]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Mangaz is shutting down in a couple of weeks, so hopefully you can fix this one soon. It finds the book and chapter, but gives an error when trying to download it.

Random URL to test
https://www.mangaz.com/book/detail/205631
https://vw.mangaz.com/navi/205631/i:0

### To Reproduce

Nightly 582f36
ばにかの。 漫画演出版
![image](https://github.com/user-attachments/assets/8368aa4b-2f0a-43d8-9e9e-59bacfbc1b6f)
![image](https://github.com/user-attachments/assets/9da79126-221c-404c-8422-d52284edb274)

**Comment by MikeZeDev** [comment]
As site will be closed, it wont be fixed. However, it works with [Haruneko ](https://github.com/manga-download/hakuneko)if you replace /book/ with /series/ in manga link.

https://www.mangaz.com/series/detail/205631

![image](https://github.com/user-attachments/assets/b7e7345d-941c-43b7-ac62-c80d0f3b699a)
![image](https://github.com/user-attachments/assets/081cf5d2-c006-4d8a-aebe-5980ed8800b1)

**Comment by MaDmonkey3311** [comment]
Iam having same issue and didnt find any fix for it
