### ISSUE TITLE
[Site Request] Elder Manga

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7541]
**Name of the website**
Elder Manga

**Website urls (examples below)**
- Site: https://eldermanga.com/
- Manga List: https://eldermanga.com/search
- Manga example: https://eldermanga.com/manga/8/seytanin-geri-donusu
- Chapter online viewer example: hhttps://eldermanga.com/manga/8/seytanin-geri-donusu/4/-bolum

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Way to complex to code for a website with only 6 manga

**Comment by Tianzhou2** [comment]
> Way to complex to code for a website with only 6 manga

new mangas will be added over time

**Comment by MikeZeDev** [comment]
Then we will reconsider it.
