### ISSUE TITLE
[Site Request] The Blank

### ISSUE THREAD

**Issue by montypeshi** [manga-download/hakuneko#7546]
**Name of the website**
The Blank

**Website urls (examples below)**
- Site: https://theblank.net/
- Manga List: https://theblank.net/manga/
- Manga example: https://theblank.net/manga/sextopwatch/
- Chapter online viewer example: https://theblank.net/manga/sextopwatch/chapter-1/

**Languages**
English

**Website relationship*
Original Website

**Additional details**
Hentai, Webtoons

**Comment by MikeZeDev** [comment]
search before 😢 . Posting duplicate issues kill kitten.

https://github.com/manga-download/hakuneko/issues/6514
