### ISSUE TITLE
[Site Request] Scan-Manga

### ISSUE THREAD

**Issue by Angor-de-Redjak** [manga-download/hakuneko#7547]
**Name of the website**
Scan-Manga
**Website urls (examples below)**
- Site: https://www.scan-manga.com/
- Manga List: https://www.scan-manga.com/scanlation/liste_series.html
- Manga example: https://www.scan-manga.com/20/Trace.html
- Chapter online viewer example: https://www.scan-manga.com/lecture-en-ligne/Trace-Chapitre-10-FR_3685.html

**Languages**
French

Thanks for reading my request!
Some of those works are really hard to find nowadays, especially old ones...

**Comment by MikeZeDev** [comment]
What the point of requesting websites that are already supported? Please tell me? 

![image](https://github.com/user-attachments/assets/1cc3e81f-4730-4a20-a7f9-13ef88f58721)
