### ISSUE TITLE
[ScanManga] Connector not working

### ISSUE THREAD

**Issue by Angor-de-Redjak** [manga-download/hakuneko#7548]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I got a 403 Error when trying to refresh the mangas list

If I try to open it in the embedded browser, I get stuck into a loop of "Please check you're a humain being" and I cannot pass it...
![image](https://github.com/user-attachments/assets/daac1840-d24a-4584-bb6f-c6563d3d7412)

### To Reproduce

1. Select ScanManga
2. Try to Refresh the manga list
![image](https://github.com/user-attachments/assets/a5b593b7-282b-4967-bf36-6decc0ae1ac3)

**Comment by MikeZeDev** [comment]
Duplicate + Cloudflare cant fix. Search first pls 

https://github.com/manga-download/hakuneko/issues/3460
