### ISSUE TITLE
[Site Request] imperiodabritannia

### ISSUE THREAD

**Issue by Lapot300** [manga-download/hakuneko#7550]
**Name of the website**
imperiodabritannia

**Website urls **

- Site: https://imperiodabritannia.com
- Manga List: https://imperiodabritannia.com/projetos/
- Manga example: https://imperiodabritannia.com/manga/profissao-sem-valor-domador-de-dragoes/
- Chapter online viewer example: https://imperiodabritannia.com/manga/profissao-sem-valor-domador-de-dragoes/capitulo-51/

**Languages**
Portuguese

**Comment by Lapot300** [comment]
I created a pull request implementing this connector #7551

**Comment by 27136773** [comment]
This ticket was closed without the PR being completed, was this done by intention?

**Comment by Lapot300** [comment]
@ronny1982  Yes, I closed it on purpose. I'm sorry if that was wrong; I thought that from now on, you could respond to me via the pull request instead of this issue.
