### ISSUE TITLE
[Site Request] Re-yume

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#7553]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://www.re-yume.my.id/
- Manga List: https://www.re-yume.my.id/p/daftar-komik.html
- Manga example: https://www.re-yume.my.id/2024/10/ao-no-hako.html
- Chapter online viewer example: https://www.re-yume.my.id/2024/11/ao-no-hako-chapter-152.html

**Languages**
List of languages supported by the website
Indonesia
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
thats a new level, now you are making duplicates of your own requests 👏https://github.com/manga-download/hakuneko/issues/6744
