### ISSUE TITLE
[<NEWTOKI>] Connector not working

### ISSUE THREAD

**Issue by FrostAlev2** [manga-download/hakuneko#7554]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Attempting to synchronize the local manga list with the online list from newtoki results in an "Failed to update manga list for NewToki: Cannot read property 'href' of undefined" error window.

![image](https://github.com/user-attachments/assets/a6d36e74-da9d-4ea3-9e47-4a1a285ecf8d)

### To Reproduce

1. Attempt to Synchronize NewToki's Manga List.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/7067
