### ISSUE TITLE
[Site Request] Cuu Truyen

### ISSUE THREAD

**Issue by LVBin0210** [manga-download/hakuneko#7560]
**Name of the website**
Cuu Truyen

**Website urls (examples below)**
- Site: https://cuutruyen.net/
- Manga List: https://cuutruyen.net/newest
- Manga example: https://cuutruyen.net/mangas/152
- Chapter online viewer example: https://cuutruyen.net/mangas/152/chapters/32743

**Languages**
Vietnamese

**Comment by MikeZeDev** [comment]
Are you for real? Did you even open the program? 

https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+cuutruyen&type=issues

![image](https://github.com/user-attachments/assets/8d644f21-e4fa-4fa7-a813-7c6ed3e28e12)

**Comment by LVBin0210** [comment]
Sorry sir I don’t understand what you mean? I checked on the bookmarks and
found out that this website didn’t show up. So I made a request. If I was
violated anything please let me now. Thank you.

Vào Th 5, 21 thg 11, 2024 lúc 19:51 MikeZeDev ***@***.***> đã
viết:
