### ISSUE TITLE
[<Tenkai>] Connector not working

### ISSUE THREAD

**Issue by negareni** [manga-download/hakuneko#7562]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

When trying to update the manga list or enter a link with the (paste media link) button, haruneko closes. Could you help me please (https://tenkaiscan.net/).

### To Reproduce

1. Tenkai
2. All mangas
3. All chapters
4. The program just closes, no message is displayed.

**Comment by MikeZeDev** [comment]
Cloudflare cant fix use another website

**Comment by negareni** [comment]
Thanks for trying, I'll wait until they can fix it to continue with what I downloaded from there.
