### ISSUE TITLE
[Asura Scans {Asuracomics.net}] Connector not working

### ISSUE THREAD

**Issue by Point744orSMT** [manga-download/hakuneko#7573]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Asura Scans changed domain again and new one dosent work
new Link :https://asuracomic.net/

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Dont open duplicates https://github.com/manga-download/hakuneko/issues/7281
