### ISSUE TITLE
[<TBCscans>] Connector not working (domain changed)

### ISSUE THREAD

**Issue by MarqFJA87** [manga-download/hakuneko#7574]
**Name of the website**
TCB Scans

**Website urls (examples below)**
- Site: https://tcbscans.me/
- Manga List: https://tcbscans.me/projects
- Manga example: https://tcbscans.me/mangas/25/my-hero-academia-one-shot-you-re-next
- Chapter online viewer example: https://tcbscans.me/chapters/7782/my-hero-academia-one-shot-you-re-next-chapter-1

**Languages**
English

**Website relationship*
Current site address for the TCB Scans group.

**Comment by MikeZeDev** [comment]
I ma sorry but there is .me, .net, .com. Which one is the real one ? Can someone really tell ? I am not fond of adding copycats.

**Comment by MarqFJA87** [comment]
I'm fairly certain that the .me domain is the legit one; the layout is exactly the same as the original site, and it's what I found linked to when I looked up one of their torrents on Nyaa.si. The .com one isn't even working on my end, too, whether on desktop (it just redirects to a blank white /lander page) or via HakuNeko.

**Comment by MikeZeDev** [comment]
Then you should have opened a "website change" issue and not a "website suggestion" issue. I can see that just changing the domain is enough (it works the same) and that its already .me in haruneko

**Comment by MarqFJA87** [comment]
Oh, sorry. I was looking at a recent similar request to make sure that I got this one done correctly. Should've been paying more attention.
