### ISSUE TITLE
[HaruNeko] Search form/button only works for sensitive case letters

### ISSUE THREAD

**Issue by noorhakim** [manga-download/hakuneko#7577]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Search form/button only works for sensitive case letters.

**Expected behavior**
Hope it's works for both lowercase or uppercase

**Screenshots**
![image](https://github.com/user-attachments/assets/3f062bc0-a6c0-4eee-9eb5-f8845462d60f)
![image](https://github.com/user-attachments/assets/edd449b1-0e90-4fa5-98d7-29739b4280e5)

**Context (please complete the following information):**
 - OS: Win 10
 - HakuNeko [HaruNeko]

**Comment by MikeZeDev** [comment]
Report that in **Haruneko** Github, its HaKUneko here 😔
