### ISSUE TITLE
[Site Request] Mahastro

### ISSUE THREAD

**Issue by Lucas-Zxc** [manga-download/hakuneko#7579]
**Name of the website**
Mahastro

**Website urls (examples below)**
- Site: https://manhastro.com/
- Manga List: https://thewebsiteurl/mangalist.html
- Manga example: https://manhastro.com/lermanga/the-reincarnation-of-the-forbidden-archmage/
- Chapter online viewer example: https://manhastro.com/lermanga/the-reincarnation-of-the-forbidden-archmage/capitulo-32/

**Languages**
Portuguese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Please search before opening duplicate tickets

https://github.com/manga-download/hakuneko/issues/6969
