### ISSUE TITLE
[Site Request] Manga UP! (Global)

### ISSUE THREAD

**Issue by erictbar** [manga-download/hakuneko#7580]
**Name of the website**
Manga UP!

**Website urls (examples below)**
- Site: https://global.manga-up.com/
- Manga List: https://global.manga-up.com/search
- Manga example: https://global.manga-up.com/manga/499
- Chapter online viewer example: https://global.manga-up.com/manga/499/57142

**Languages**
English

**Website relationship*
Appears to be the English version of https://www.manga-up.com

**Additional details**
Recently added website for existing official iOS & Android app. I have purchased chapters I can help test.

**Comment by erictbar** [comment]
My apologies, I read the news as the site being new and I didn't even check. The site does have an existing connection ("Manga UP" isn't very search engine optimized) however, the connector appears to be broken, even with free chapters.

```
MangaUpGlobal.ts:71 Uncaught (in promise) Exception<Plugin_Common_Chapter_UnavailableError>: The chapter is not available (not purchased/unlocked/public)!
    at MangaUpGlobal_default.FetchPages (http://localhost:3000/src/engine/websites/MangaUpGlobal.ts:44:13)
    at async Chapter.Update (http://localhost:3000/src/engine/providers/MediaPlugin.ts:72:28)
    at async MediaItemPreview.EntryChanged (http://localhost:3000/src/frontend/fluent-core/components/MediaItemPreview.ts:60:7)
```

**Comment by MikeZeDev** [comment]
hahah ok. Next time open the "non working issues" in Haruneko github ^^ please
