### ISSUE TITLE
[<mangalek>] mangalek domain change

### ISSUE THREAD

**Issue by PD-ZIRO** [manga-download/hakuneko#7581]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Hello my friend Mikezedev, do you remember me? I apologize for the hacked links on the server; someone hacked my account, and I recovered it after a long time. How are you? You have many requests as usual, so do your best. What about the MangaLek site?

### To Reproduce

Name of the website
Mangalek

Website urls:

Site: https://lekmanga.net/
Manga List: https://lekmanga.net/manga/
Manga example: https://lekmanga.net/manga/lonely-attack-on-a-different-world/
Chapter online viewer example: https://lekmanga.net/manga/lonely-attack-on-a-different-world/119/

Languages
Arabic

**Comment by MikeZeDev** [comment]
Invalid request .
https://github.com/manga-download/hakuneko/blob/044128a247f41b7b18698ba129b4fc4248b8a968/src/web/mjs/connectors/Mangalek.mjs#L4

Url was updated 9 months ago.
