### ISSUE TITLE
[<Batoto (by AnyACG) https://bato.to>] Connector not working

### ISSUE THREAD

**Issue by HeyyGoldfish** [manga-download/hakuneko#7587]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Clicking on the download button will just end in error. I have tried on a MacOS and Windows 10.
The Chapter List loads when choosing from Bookmarks or Clipboard. The preview images also works. But downloading will present an _TypeError: Failed to fetch_.
Also noting that the Manga List does not load if _Batoto (by AnyACG)_ was chosen as connectors.
<img width="1072" alt="Screenshot 2024-12-07 at 6 35 21 AM" src="https://github.com/user-attachments/assets/a8bfd775-f712-43ec-86a6-fb1e0983104e">

### To Reproduce

1. Batoto (by AnyACG) https://bato.to
2. Any manga (Sample: Secret Lady- https://bato.to/series/97151/secret-lady)
3. Any chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
- TypeError: Failed to fetch
- net::ERR_CONNECTION_RESET
<img width="1070" alt="Screenshot 2024-12-07 at 6 47 11 AM" src="https://github.com/user-attachments/assets/8001c833-fda3-40ff-ad18-c9c9d7121dd8">

**Comment by HeyyGoldfish** [comment]
Console errors on Nightly Build:
<img width="1116" alt="Screenshot 2024-12-07 at 12 45 20 PM" src="https://github.com/user-attachments/assets/7cb206b6-5144-4c84-a929-38c1f1e77402">
https://chromestatus.com/feature/5633521622188032

I'm not sure if this is related but bato.to has a new website version that has a different URL format:
v2x- 
https://bato.to/series/97151/secret-lady
https://bato.to/chapter/3119799
v3x- 
https://bato.to/title/97151-secret-lady
https://bato.to/title/97151-secret-lady/3119799-ch_108

**Comment by MikeZeDev** [comment]
1) You are using bookmarks. If website url format changes or manga id change bookmarks dont get updated. Try on an updated manga list and not on a bookmark

2) Unable to reproduce. Not surprising with ERR_CONNECTION_RESET, its probably something on your end 🤷 

![image](https://github.com/user-attachments/assets/9d15028b-ced5-46ee-8326-981c3232ad8a)

**Comment by HeyyGoldfish** [comment]
Nothing loads if I just access Batoto from connectors:
<img width="1114" alt="image" src="https://github.com/user-attachments/assets/e92cb876-4c62-4a93-a610-138ef3a25962">
