### ISSUE TITLE
[Site Request] weeb central

### ISSUE THREAD

**Issue by SirWillem1** [manga-download/hakuneko#7590]
**Name of the website**
weeb central

**Website urls (examples below)**
- Site: https://weebcentral.com/
- Manga List: https://weebcentral.com/search
- Manga example: https://weebcentral.com/series/01J76XYE3130E1W5HKTJ7VD912/Sakamoto-Days
- Chapter online viewer example: https://weebcentral.com/chapters/01J76XZ4A7ZKB7GZRNQ10AGB02

**Languages**
English

**Website relationship*
it's the new website by the creator of mangasee123

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
..... https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+weebcentral&type=issues

**Comment by 27136773** [comment]
Duplicate of #7407
