### ISSUE TITLE
[yaoiscan>] Connector not working

### ISSUE THREAD

**Issue by aniloveer** [manga-download/hakuneko#7593]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

i can see the titles but the chapters aint loading

### To Reproduce

1. Name of connector. yaoi scans 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/c59b6ab6-4980-4f71-a79e-12ae9301ef42)

Cloudflare, cant fix use another website
