### ISSUE TITLE
[Toonily.com] Connector not working

### ISSUE THREAD

**Issue by drummingdemon** [manga-download/hakuneko#7595]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Trying to load Bookmarks from the site or using the Clipboard or simply loading Toonily and _then_ trying to load a manga's chapters results in 403 errors. From browser I can see the chapters just fine and they load as well. I've tried with a different external IP address, tried using CloudFlare Warp and also tried two different VPN providers - same result.

### To Reproduce

1. Connector: `Toonily.com`
2. https://toonily.com/webtoon/eleceed/

```
Connector.mjs:438 GET https://toonily.com/webtoon/eleceed/ 403
fetchDOM @ Connector.mjs:438
_getChapters @ WordPressMadara.mjs:93
_getChapterList @ Connector.mjs:599
(anonymous) @ Manga.mjs:134
(anonymous) @ Manga.mjs:133
Promise.then (async)
_getUpdatedChaptersFromWebsite @ Manga.mjs:132
(anonymous) @ Manga.mjs:98
Promise.then (async)
getChapters @ Manga.mjs:94
onSelectedMangaChanged @ chapters.html:244
runObserverEffect @ property-effects.html:217
runEffectsForProperty @ property-effects.html:162
runEffects @ property-effects.html:128
_propertiesChanged @ property-effects.html:1662
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
__enableOrFlushClients @ property-effects.html:1555
_flushClients @ property-effects.html:1530
_propertiesChanged @ property-effects.html:1658
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
runNotifyEffects @ property-effects.html:261
_propertiesChanged @ property-effects.html:1665
_flushProperties @ properties-changed.html:341
_flushProperties @ property-effects.html:1510
_invalidateProperties @ property-effects.html:1482
set @ property-effects.html:1817
onMangaClicked @ mangas.html:313
handler @ template-stamp.html:96
(anonymous) @ templatize.html:149
```

**Comment by MikeZeDev** [comment]
Cloudflare, give up.
