### ISSUE TITLE
[Toonily.com] Connector not working

### ISSUE THREAD

**Issue by forestpas3** [manga-download/hakuneko#7597]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Website update: Login is needed to see all manga

### To Reproduce

1. toonily.com + deactivate family mode
2. all NSFW

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/11759863-7daf-4b2f-97cd-d84b3199e957)
