### ISSUE TITLE
[readcomiconline.li/i] Downloading Gifs

### ISSUE THREAD

**Issue by Lio-gif** [manga-download/hakuneko#7598]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

It's Downloading GIFs after the 2nd page, the first 2 pages are just fine 

And the GIFs are just a white with nothing on it

### To Reproduce

1. readcomiconline.li
2. Green Lantern (2023) {But also some others}
3. every chapter

**Comment by MikeZeDev** [comment]
I am afraid i dont have the problem

**Comment by MustangKoschei** [comment]
> I am afraid i dont have the problem

I am also having the same issue. I have done all the steps Leo-gif has and nothing has helped.

**Comment by MikeZeDev** [comment]
That doesnt help please kindly refrain just saying "me too" :D. 

At least do you download all chapters page + those gif? Or those gif are replacing real pages? 
What does network tab says? (Press F12)

**Comment by Lio-gif** [comment]
Hi, I wanted to check the network tab, and now it works.

But it was replacing the real pages
