### ISSUE TITLE
[Site Request] sushiscan.fr

### ISSUE THREAD

**Issue by kERNEL93** [manga-download/hakuneko#7600]
**Name of the website**
sushiscan

**Website urls **
- Site: https://sushiscan.fr/
- Manga List: https://sushiscan.fr/catalogue/
- Manga example: https://sushiscan.fr/catastrophic-necromancer-chapitre-140/
- Chapter online viewer example: https://sushiscan.fr/catastrophic-necromancer-chapitre-54-vf/

**Languages**
French

**Website relationship*
https://sushiscan.net

Thanks HakuNeko

**Comment by MikeZeDev** [comment]
bruh .... https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+sushiscan&type=issues
