### ISSUE TITLE
[Feature] Post Command that Overrides any other download format

### ISSUE THREAD

**Issue by JackyYu510yt** [manga-download/hakuneko#7601]
**Is your feature request related to a problem? Please describe.**
I'm trying to download "leveling up with thumbs up" and it keeps downloading as a .webp. I tried using the Post Command listed in the FAQ (mkdir "%PATH%_conv" 2>nul & convert "%PATH%\*.webp" -scene 1 "%PATH%_conv\%03d.png") and changing it to .jpg and it worked once but now that I'm trying it again, it doesn't seem to do anything. Besides that, would it be possible to create a post command that would replace the contents of the original folder instead of creating a new folder with a suffix?

**Describe the solution you'd like**
Post command that replaces the images of the original folder with .jpg versions of the images.

**Describe alternatives you've considered**
Was given this post command but it didn't work for me

convert "%PATH%*.webp" -scene 1 "%PATH%%03d.jpg"

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 6.17]

**Additional context**
Not sure why the original post command stopped working. (I also tried changing it back to .png and it still outputs nothing) Here's a screenshot of the post command and the folder output.
https://i.imgur.com/FFaBJBQ.png
https://i.imgur.com/aTOdLZh.gif

**Comment by MikeZeDev** [comment]
Its up to you to find a converter software that REPLACE files in folder, or make a batch file to replace them by yourself.

**Comment by JackyYu510yt** [comment]
What would I even look for if I was trying to hire somebody to do it for me?
