### ISSUE TITLE
[Site Request] マンガBANGコミックス

### ISSUE THREAD

**Issue by FuFa088** [manga-download/hakuneko#7606]
**Name of the website**
マンガBANGコミックス

**Website urls**
- Site: https://comics.manga-bang.com/
- Manga List: https://comics.manga-bang.com/category/manga
- Manga example: https://comics.manga-bang.com/series/f599e72ae4b3c
- Chapter online viewer example: https://comics.manga-bang.com/episodes/4a5c6332f3220/

**Languages**
Japanese

**Website relationship*
No comment.

**Additional details**
No comment.

**Comment by MikeZeDev** [comment]
Not using search feature kills kitten. https://github.com/manga-download/hakuneko/issues/6859
