### ISSUE TITLE
[Site Request] mangadraft

### ISSUE THREAD

**Issue by isatheandalusi** [manga-download/hakuneko#7607]
Name of the website
Mangadraft

Website urls (examples below)

Site: https://www.mangadraft.com/

Manga List:
https://www.mangadraft.com/catalog/comics/popular
https://www.mangadraft.com/catalog/webtoons/popular
https://www.mangadraft.com/catalog/novels/popular
https://www.mangadraft.com/catalog/artbooks/popular

Manga example: https://www.mangadraft.com/manga/dragon-ball-kakumei-eng.en

Chapter online viewer example: https://www.mangadraft.com/reader/dragon-ball-kakumei-eng.en/458893

Languages

French
English

**Comment by Sheepux** [comment]
duplicate #5423
