### ISSUE TITLE
[Tapas] Connector not working- Non-original series don't appear listed

### ISSUE THREAD

**Issue by Sabr111** [manga-download/hakuneko#7611]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

It's not that the connector isn't working, but I didn't know how to list the issue! 
The problem is that it allows me to download Tapas Originals, but the Non-original series don't appear listed.

### To Reproduce

1. Tapas
2. The Magpie (https://tapas.io/series/The-Magpie/info)

**Comment by MikeZeDev** [comment]
Its working, if only you had somehow read the manual and tried to paste the manga link

https://tapas.io/series/The-Magpie/
![image](https://github.com/user-attachments/assets/7585b2c0-3416-4aa9-8568-f872ba7d3e09)

**Comment by Sabr111** [comment]
It wouldn't let me copy the link, it automatically deleted it, I'm going to try to reinstall it.
