### ISSUE TITLE
[<ScanManga>] Connector not working

### ISSUE THREAD

**Issue by TheRousse** [manga-download/hakuneko#7615]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

![mangascan](https://github.com/user-attachments/assets/5a58d4d9-36be-4b2e-83d8-9a94d4a01f5d)

### To Reproduce

1. ScanManga (scan-manga.com)
2. Magi-Sinbad-no-Bouken
3. Chapitre 1 
4. 403

**Comment by MikeZeDev** [comment]
Manga list never worked well on real browser, json file is empty anyway. Use Haruneko, website is weird

https://github.com/manga-download/haruneko
