### ISSUE TITLE
[ScanVf] thewebsitename

### ISSUE THREAD

**Issue by TheRousse** [manga-download/hakuneko#7616]
**Name of the website**
ScanVF

**Website urls (examples below)**
- Site: https://scanvf.org/
- Manga List: https://scanvf.org/manga
- Manga example: https://scanvf.org/manga/orient-samurai-quest
- Chapter online viewer example:  https://scanvf.org/scan/7782

**Languages**
French

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
dont open useless tickets pls https://github.com/manga-download/hakuneko/issues/7119
