### ISSUE TITLE
[batoto, mangago, flame] Connector not working

### ISSUE THREAD

**Issue by alexandriatale** [manga-download/hakuneko#7619]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I tried to download from batotoo.com, mangago.me and flamecomics.xyz, but none worked. The only working site is LINE WEBTOON. For the batoto and mangago, the website URL is correct, but it seems flamecomics changed site into flamecomics.xyz

I tried these URLs:
https://batotoo.com/series/71089/reminiscence-adonis
https://www.mangago.me/read-manga/2ha_dumb_husky_and_his_white_cat_shizun/

Open batoto / mangago from bookmark:
![Screenshot 2024-12-20 143122](https://github.com/user-attachments/assets/363859af-111e-4363-88e5-481fff2cd48d)

Open and update batoto / mangago from connectors:
![Screenshot 2024-12-20 143104](https://github.com/user-attachments/assets/619adcb9-eb27-49c7-a482-60b4d202965d)

Directly paste mangago URL:
![Screenshot 2024-12-20 143345](https://github.com/user-attachments/assets/ac87178a-1566-4af5-9400-1eb5c810d472)

I tried to download batoto from haruneko, but it also cannot work. The website on haruneko is bato.to.

When I open & update the connector, the title is like this:
![Screenshot 2024-12-20 144930](https://github.com/user-attachments/assets/32721800-0349-4b22-b4e4-7ab8ef27bf5d)

I try to look for a title "adonis":
![Screenshot 2024-12-20 144408](https://github.com/user-attachments/assets/68b24877-9a44-42b0-b4b2-8e2319448ba3)

While on the website, there's a lot of this title:
![Screenshot 2024-12-20 144416](https://github.com/user-attachments/assets/08eb506d-0a0d-4dc4-8b3c-a8cb31a7be8a)

I also can't directly paste the website URL. I'm at my wits end. Please help. Thank you

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
* One issue per website pls 
* Dont mix Hakuneko and Haruneko issues
* Report issues in the proper repository

* you are mixing batoto and batotoo. You pasted a batotoo link when the url we use is batato. Obviously we cant detect the website as the domain is different. Check batoto url in settings? 

* I ma afraid but pasting the mangago link works
![image](https://github.com/user-attachments/assets/5103fe97-a354-43f8-8b5c-8b888edf0bed)
 
* the crappy manga list in batoto is not our fault as they have a ton of manga some title are messed up but i ma gonna double check just in case.

* you are using bookmarks, and websites may have changed manga id so bookmarks became invalid. Dont use bookmark for troubleshooting, paste url or fetch manga list.
* flame problem is known and there is already an opened issue, no need to talk about it. Its even on the first page of issue, you didnt search much 
* 
![image](https://github.com/user-attachments/assets/fdb2a472-ccbb-43a6-ae78-1e8bfb92d750)

* etc...


CLosed as its a mess
