### ISSUE TITLE
[<DragonTranslation.mjs>] Connector not working

### ISSUE THREAD

**Issue by negareni** [manga-download/hakuneko#7625]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Good afternoon, I have been somewhat disconnected these weeks and now that I took the time to review the mangas, I was surprised to find that the connectors for these websites are not working: https://dragontranslation.net/ and https://manhwas.net/, in neither of the 2 programs, neither Haruneko nor Hakuneko (in the latter, the application closes when pressing the update button). Could these 2 websites be updated? I hope it is possible, thanks :D

### To Reproduce

1. DragonTranslation.mjs
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
CLoudflare. Meaning

* it wont work in Hakuneko, dont bother https://github.com/manga-download/hakuneko/issues/2933
* use Hakuneko assistant with Haruneko or Haruneko electron build  . The crash is a NWJS bug we reported to them and still waiting fo a fix. https://github.com/manga-download/haruneko/issues/750

**Comment by negareni** [comment]
OK, thanks for the information and Merry Christmas.
