### ISSUE TITLE
[ReadCOmicOnline]blank gif

### ISSUE THREAD

**Issue by LicketySplit21** [manga-download/hakuneko#7627]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
every page after the second is a blank page, saved as a .gif file when downloaded

**To Reproduce**
When downloading any comic (for me, Get Fury, but it can be any comic) from readcomiconline.li, or when previewing the images pre-download.

**Expected behavior**
For all of the images in the issue to be downloaded

**Screenshots**
https://imgur.com/a/XPfXhFZ

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 8.3.4

**Additional context**
Hopefully this info is appropriate here. I noticed that this was already marked as an issue, although the user stated it started working again and the issue was closed. Me, and others, have still consistently experienced this, and only with readcomiconline.li. I'm not a very techie person

**Comment by MikeZeDev** [comment]
Website is cancer and fight against Mihon and Hakuneko.
Since the problem cant be reproduced on our end i'd suggest either trying with Haruneko, either use another website.

In case you have the problem in Haruneko, open an issue in Haruneko github and then we will check.
