### ISSUE TITLE
[Site Request] TRMangaoku

### ISSUE THREAD

**Issue by Tianzhou2** [manga-download/hakuneko#7631]
**Name of the website**
TRMangaoku

**Website urls (examples below)**
- Site: https://trmangaoku.com/
- Manga List: https://trmangaoku.com/manga/?genres_collapse=on
- Manga example: https://trmangaoku.com/manga/pasli-bicak/
- Chapter online viewer example: https://trmangaoku.com/manga/pasli-bicak/bolum-11/

**Languages**
Turkish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
They really have no imagination with their names. Mangaoku, Mangaokutr, TrMangaoku, geez :D

**Comment by MikeZeDev** [comment]
Are you kidding? You even replied in the already existing issue https://github.com/manga-download/hakuneko/issues/6748 and you still post a duplicate? 

Because in case you are wondering, its already done.
