### ISSUE TITLE
[<NineMangaES>] Connector not working

### ISSUE THREAD

**Issue by D0KG0** [manga-download/hakuneko#7632]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

When trying to download the list I am getting this error.
![image](https://github.com/user-attachments/assets/aec30589-3742-4a61-82ee-bc7afd0d3699)

### To Reproduce

1. NineMangaES
2. try to download the list/refresh list

**Comment by baudetromain** [comment]
Looking into the console, the response to the request made by hakuneko is the following: `This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.`. The website is now protected by Cloudflare. I don't know how long has this connector not worked for, but there's probably no way to bypass this kind of protection.
![image](https://github.com/user-attachments/assets/8bc354e8-58e3-49ba-8f99-98949b90d84e)

**Comment by MikeZeDev** [comment]
Cloudflare give up
