### ISSUE TITLE
Tumangaonline does not work

### ISSUE THREAD

**Issue by TheDoom95** [manga-download/hakuneko#769]
When I select a manga, it doesn't show me the chapters.

**Comment by 27136773** [comment]
Are you using 5.0.8 or the latest nightly build?

**Comment by TheDoom95** [comment]
Yes, version 5.0.8

**Comment by 27136773** [comment]
It should work with the latest nightly build.
It will not be added to 5.0.8

**Comment by TheDoom95** [comment]
Thanks, it really works. I was with FDM for many months and it didn't do anything.
