### ISSUE TITLE
Bitdefender blocks static.hakuneko.download

### ISSUE THREAD

**Issue by PeterBurner** [manga-download/hakuneko#770]
# Description
As the headline says: Bitdefender blocks http://static.hakuneko.download/5.0.8/latest  
Every time I start HakuNeko, I get a notification that an infected web resource was blocked.
If I try to open the URL in my web browser, it shows a big warning:  
![grafik](https://user-images.githubusercontent.com/15011953/70935477-80da3000-2040-11ea-8636-cb75ae9cd1a6.png)  
Why is the website classified as dangerous? Is it save to whitelist this domain?  
And a bit off topic: Why dont you use HTTPS for updates?

**Comment by 27136773** [comment]
The domain is an alias for artifacts hosted on GitHub, e.g. http://manga-download.github.io/hakuneko/5.0.8/latest.

You can use the latest nightly build, it downloads updates directly from the [GitHub](https://github.com/manga-download/hakuneko/blob/087e3e5f90028fda902b57a0f27287bda01cae8e/src/app/Configuration.js#L26) domain.

HTTPS makes only sense when sensitive data is transferred, there is no need to protect an open source update patch. The update patch itself is signed with a private key to verify its integration.
