### ISSUE TITLE
higher resolution image on ganma.jp

### ISSUE THREAD

**Issue by 0xh3LL0** [manga-download/hakuneko#772]
looks like ganma load multiple image resolution, and then choose which one to view the best by detect our screen resolution, but can hakuneko download the highest resolution as possible?

i use [Download All Images](https://addons.mozilla.org/en-US/firefox/addon/save-all-images-webextension/) and [ImageAssistant Batch Image Downloader](https://addons.mozilla.org/en-US/firefox/addon/ia-batch-image-downloader/), and [this manga](https://ganma.jp/ESS) as a test

Download All Images can detect 464x656 and 768x1086

![extreme1](https://user-images.githubusercontent.com/23132217/70960272-2a590a00-20b1-11ea-8a79-cf23bb6860eb.png)

![extreme3](https://user-images.githubusercontent.com/23132217/70960295-38a72600-20b1-11ea-9ccd-82bb1aeee882.png)

while ImageAssistant only detect 640x905, same as what hakuneko capable to download right now.

![extreme2](https://user-images.githubusercontent.com/23132217/70960334-55435e00-20b1-11ea-95b1-a050d3af7697.png)

**Comment by 27136773** [comment]
HakuNeko uses the JSON API.
I cannot find any other resolutions besides the default image links.
I checked the API without user account or subscription, it is possible that higher resolutions are available with user account / subscription.
