### ISSUE TITLE
toonily, failed to receive content.

### ISSUE THREAD

**Issue by dragonofdragons** [manga-download/hakuneko#777]
![Capture](https://user-images.githubusercontent.com/52318393/71055810-fe0abf80-217c-11ea-9d12-1a0b430c5f43.PNG)
website: toonily.com
status: 500 error

**Comment by 27136773** [comment]
Cannot be reproduced on my end, the manga/chapter shows all images correctly.
Does it work for you on the website within your browser?

**Comment by dragonofdragons** [comment]
> Cannot be reproduced on my end, the manga/chapter shows all images correctly.
> Does it work for you on the website within your browser?

**Comment by dragonofdragons** [comment]
yeah, it's working on browser with in hakuneko also. but can download and view images by clicking on respective buttons

**Comment by 27136773** [comment]
Whats shown in error console and network log (F12)?

**Comment by dragonofdragons** [comment]
![Screenshot from 2019-12-21 22-21-52](https://user-images.githubusercontent.com/52318393/71310988-c2078100-2440-11ea-81ec-263e93d1c320.png)
![Screenshot from 2019-12-21 22-21-28](https://user-images.githubusercontent.com/52318393/71310989-c59b0800-2440-11ea-8531-4dc712682dfe.png)

**Comment by dragonofdragons** [comment]
> Whats shown in error console and network log (F12)?

isn't it serv

**Comment by dragonofdragons** [comment]
> Whats shown in error console and network log (F12)?

it is showing as above. i think hakuneko not able to show the images but its showing the new chapter, not able to download

**Comment by 27136773** [comment]
HTTP Status [500](https://www.westhost.com/knowledgebase/display/WES/What+Is+A+500+error) is an internal server error on the website. I don't know why you get it within HakuNeko but not from your Browser. I'm afraid i cannot help with this issue as this is not reproducible on my end. There was also no other response which states a similar problem.

**Comment by dragonofdragons** [comment]
> HTTP Status [500](https://www.westhost.com/knowledgebase/display/WES/What+Is+A+500+error) is an internal server error on the website. I don't know why you get it within HakuNeko but not from your Browser. I'm afraid i cannot help with this issue as this is not reproducible on my end. There was also no other response which states a similar problem.

last week i got same problem in tachiyomi also, but after some days i heard that they moved the extension to madara so i reinstalled the madara extension and the problem got solved. hope this information will be helpful

**Comment by 27136773** [comment]
As mentioned above it works fine on my end ,so unfortunately i cannot help with this issue...
There is nothing left i can do except closing the ticket
