### ISSUE TITLE
Can't download manga from MangaTown

### ISSUE THREAD

**Issue by ZackCelestial** [manga-download/hakuneko#779]
I try to download manga from MangaTown but it always fail and I thought it was my internet but when I try download from another website it just fine.

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
Make sure the website works in your browser.
Provide a sample manga/chapter that is not working.

**Comment by ZackCelestial** [comment]
The website in browser just fine and I try read it from there but nothing wrong and before I download it I try click the image for that manga there still no problem .

**Comment by 27136773** [comment]
Whats shown in error console and network log (F12)?

**Comment by ZackCelestial** [comment]
![Untitled 1](https://user-images.githubusercontent.com/59060327/71321530-6c40e080-24f5-11ea-8540-761b38da1d47.png)
![Uploading Untitled.png…]()

**Comment by ZackCelestial** [comment]
![Untitled](https://user-images.githubusercontent.com/59060327/71321541-9e524280-24f5-11ea-9271-31ba0449794b.png)

**Comment by ZackCelestial** [comment]
![Untitled 1](https://user-images.githubusercontent.com/59060327/71321545-a8744100-24f5-11ea-861f-681407164ed9.png)

**Comment by ZackCelestial** [comment]
is this the one ? that the manga I saw in the browser and just update today.

**Comment by 27136773** [comment]
Problem could be reproduced with `A Story About Treating a Female Knight - Chapter 86`
Next time please make sure to provide as much information as possible, e.g. which manga/chapter does not work.
The developers cannot check thousands of mangas from MangaTown for errors.

**Comment by ZackCelestial** [comment]
Wow now all manga from mangatown can download thank you (^.^)
