### ISSUE TITLE
Add KimCartoon

### ISSUE THREAD

**Issue by maxtron95** [manga-download/hakuneko#783]
Hi, I would like to suggest: https://kimcartoon.to/

**Comment by 27136773** [comment]
Looks similar to KissAnime and might re-use code.
Video sources seems to be from KissCartoon.

Video links from KimCartoon Beta Server can be extracted with the following injected script:
```javascript
$('select#selectQuality option').get().map(option => {
    return {
        resolution: option.textContent.trim(),
        stream: $kissenc.decrypt(option.value)
    };
});
```

**Comment by maxtron95** [comment]
@ronny1982 Since KimCartoon might reuse code from KissAnime, Do you think it is possible to use the KissAnime Script for KimCartoon?

**Comment by 27136773** [comment]
No, i don't think so

**Comment by maxtron95** [comment]
@ronny1982 Does KimCartoon use the HydraX servers?

**Comment by 27136773** [comment]
One of their mirror is HydraX

**Comment by maxtron95** [comment]
I was wondering if it will it be possible to see KimCartoon in a later version of HakuNeko?

**Comment by 27136773** [comment]
Maybe tomorrow, maybe never...
There is no forecast available.
Current velocity is slightly negative, there are more issues incoming then being resolved

**Comment by maxtron95** [comment]
@ronny1982 I am trying to write the script but I was wondering, Would I have to add an entire cartoon list from KimCartoon to the HakuNeko CDN repo, Like KissAnime, KissManga?

https://github.com/manga-download/hakuneko-cdn

**Comment by 27136773** [comment]
No, you can just parse through all pages of the cartoon list from the website.
First extract the page number from the pagination element, then loop through all cartoon pages and merge the results.

https://kimcartoon.to/CartoonList?page=1
https://kimcartoon.to/CartoonList?page=2
https://kimcartoon.to/CartoonList?page=3
...

See `_getMangas()`[🔗](https://github.com/manga-download/hakuneko/blob/10321f6c623361f01d1ed1264514e11d66d1acea/src/web/mjs/connectors/JapScan.mjs#L35)  and `_getMangasFromPage(page)`[🔗](https://github.com/manga-download/hakuneko/blob/10321f6c623361f01d1ed1264514e11d66d1acea/src/web/mjs/connectors/JapScan.mjs#L47) in e.g. JapScan

**Comment by MikeZeDev** [comment]
dead
