### ISSUE TITLE
There is no Export button

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#79]
> **From:** Makara

Hello, I have a long list of bookmarked manga and need to format soon. But there is no export button next to the import one. All I can do is import .db or .db3 files. Can someone plaese help me ? Thank you :)

**Comment by 27136773** [comment]
Just backup your [UserData](https://github.com/manga-download/hakuneko/wiki/User-Manual#2-directories) directory

**Comment by Sildran** [comment]
Thank you Ronny, I will try.

**Comment by 27136773** [comment]
Closed as it is assumed the question was answered.
