### ISSUE TITLE
In-depth settings for pdf/epub download no longer present

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#791]
(I'm new to using GitHub for more than downloading, so I'm not sure if this is the right place to put it, so please redirect me if I'm wrong.)

I have used Hakuneko awhile ago... about 2 years or so. Back then, I recall being able to set very specific settings for downloading (like numerical suffixing to compensate for "poor" ordering, whether pdf files would have a chapter per file or not [I believe the different chapter per file option was still in beta at the time], etc). Is there another way to access these settings, or were they removed to improve functionality?

**Comment by 27136773** [comment]
You may use `Chapter Title Format` and `Post Command` to achieve what you want.
Try ask discord community how they do it, maybe someone has the same desire.
