### ISSUE TITLE
azoramanga 

### ISSUE THREAD

**Issue by satyogi** [manga-download/hakuneko#802]
the www.azoramanga.com stop working 
and pleaes add https://mangalek.com/

**Comment by 27136773** [comment]
Cannot be reproduced.
Which version of HakuNeko are you using?
Which manga/chapter did not work?

Please create a separate issue for website requests:
One task one ticket so its clear when discussing things and managing changesets...

**Comment by satyogi** [comment]
ok 
hakuneko-desktop_6.1.5_windows-portable_amd64
all chapter is not working

**Comment by 27136773** [comment]
I'm afraid i cannot help with AzoraManga, it works just fine on my end.
Make sure your proxy and VPN settings are correct.
Also ensure there is no region lock for the website itself.

<img width="1232" alt="Screen Shot 2020-01-01 at 12 08 49 PM" src="https://user-images.githubusercontent.com/27136773/71640710-92057c80-2c8f-11ea-833b-0af559b53a19.png">
