### ISSUE TITLE
issue with loading complete chaps list of some l*zhin series

### ISSUE THREAD

**Issue by adsl3f** [manga-download/hakuneko#806]
hakuneko stopped showing complete chaps list of some lez series like this

https://prnt.sc/qevkwk

tried reinstall, resync nothing worked, i'm using the latest nightly build

i have more bought chaps but it doesnt show them anymore, the same thing for other series but what's confusing is there are some series that works fine

**Comment by Ever4engel** [comment]
Hakuneko show free chapters 
if you want to show all purshassed chapters for appetite you have to log in with your IDs in hakuneko.

**Comment by adsl3f** [comment]
> Hakuneko show free chapters
> if you want to show all purshassed chapters for appetite you have to log in with your IDs in hakuneko.

yes, i know, if you see i wrote: "hakuneko stopped showing ..". it was working fine and i have my account logged in

**Comment by Ever4engel** [comment]
Hum ok i see 

![id](https://user-images.githubusercontent.com/47645041/71410082-32322480-2644-11ea-8eed-4a7cbf8a7e2f.jpg)

don't work here ?

![Sans titre](https://user-images.githubusercontent.com/47645041/71410176-8dfcad80-2644-11ea-9067-965a0c451488.jpg)

type your ID here 
it should work. if not Lezhin could have changed some thing

**Comment by 27136773** [comment]
Unfortunately i cannot fix this.
A developer with a Lezhin subscription or purchased episodes is required to investigate and eventually solve this issue.

Will be closed within the next 10 days if no developer is picking up this issue.

**Comment by Ever4engel** [comment]
i assume adsl3f could help with his dev console
