### ISSUE TITLE
Cannot download certain chapters

### ISSUE THREAD

**Issue by chrisjiang1** [manga-download/hakuneko#807]
Trying to download vinland saga manga from kissmanga but cannot download chapter 154 for some reason. I can download the rest of the chapters fine. This is on my mac. Any way to fix this?

<img width="1216" alt="Screen Shot 2019-12-23 at 7 59 27 PM" src="https://user-images.githubusercontent.com/38926859/71392851-8f839280-25be-11ea-92a9-67978d020f37.png">

**Comment by 27136773** [comment]
See [FAQ](https://github.com/manga-download/hakuneko/wiki/FAQ) 6
