### ISSUE TITLE
Offline chapter mark

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#81]
Add the ability to mark chapters even when in offline mode.
The chaptermark could be matched by chapter ID and if this fails by chapter (file) name.

**Comment by Albirew** [comment]
If both ID and filename does not exists for a bookmark, it should still be shown.

**Comment by 27136773** [comment]
Further investigation is required to check if it is possible to show the chapter marker for the selected manga, even if neither the chapter ID matches, nor a corresponding chapter file exist.

**Comment by Albirew** [comment]
chaptermarks would need to store chapter name for each chapter so it can be shown and human-readable when there's no match

**Comment by 27136773** [comment]
It seems more complicated then expected to show a non-existing chaptermark, therfore #303 has been re-opened
