### ISSUE TITLE
(Version nightly) Some errors found in tumangaonline

### ISSUE THREAD

**Issue by TheDoom95** [manga-download/hakuneko#810]
1. Chapters like Hajime no ippo, One Piece ... among others. If these have many chapters and do not show them in the list to download. It's strange when I put Fairy tail with 446 chapters and adding the different Scans reach 886.
2. When I download any chapter: "Error: Invalid number of matching chapters for given ID found: 0"

**Comment by Ever4engel** [comment]
Ronny seed :

> TuMangaOnline is currently battling HakuNeko, everytime HakuNeko breaks their security they change it again. They probably also watching this discord channel to figure out when a fix is made and when i’m on vacation to make their next move.

**Comment by 27136773** [comment]
Solved by 535f8edb
