### ISSUE TITLE
Add TYPE-MOON subpage of web-ace

### ISSUE THREAD

**Issue by CrescentKohana** [manga-download/hakuneko#812]
It has content that is not found on the YoungAceUP subpage. Link here: https://web-ace.jp/tmca/

**Comment by 27136773** [comment]
Similarities:
https://web-ace.jp/schedule/
https://web-ace.jp/youngaceup/schedule/
https://web-ace.jp/tmca/schedule/

**Comment by CrescentKohana** [comment]
As an example, I don't I can find this https://web-ace.jp/tmca/contents/2000015/comics/2146/ with the application as it only searches the Young Ace UP catalogue/subpage (referring to this https://github.com/manga-download/hakuneko/issues/323).

Then again I might be mistaken, but I cannot seem to find a way to search manga not found in the Young Ace UP catalogue.

**Comment by 27136773** [comment]
The list of similarities was intended for development purposed only, it was not meant as suggestion for alternatives.

**Comment by 27136773** [comment]
TYPE-MOON will not be added, WebAce will be fixed to show the missing mangas from TYPE-MOON
