### ISSUE TITLE
Re-add Niadd

### ISSUE THREAD

**Issue by Neshunk69** [manga-download/hakuneko#816]
Would you can repare https://www.niadd.com/ and add es.niadd.com in spanish?
I try download manga but Failed to update manga list for Niadd

**Comment by 27136773** [comment]
Niadd is just a facade for NineManga.
Niadd may be added when they stop redirecting all their chapters to NineManga.

**Comment by wruizcanal** [comment]
Hi
It is true that it has ninemanga series but it also has many new series that are only in niadd. Check the url of the series so that you see that some say original and others say manga. The originals are only in niadd and there are many more updated series than elsewhere.

**Comment by 27136773** [comment]
Re-opened for analysis and assessment

**Comment by rs3mk** [comment]
from fmd https://github.com/fmd-project-team/FMD/blob/master/lua/modules/NiAdd.lua

**Comment by 27136773** [comment]
It seems only the mentioned [Originals](https://www.niadd.com/category/original/) are not available on nineanime, everything else is probably also available on nineanime.

**Comment by rs3mk** [comment]
That tag is misleading. These also do not appear:

https://es.niadd.com/original/10011089/chapters
https://es.niadd.com/original/10012850/chapters
https://es.niadd.com/original/10014071/chapters
https://es.niadd.com/original/10013625/chapters
https://es.niadd.com/original/10012152/chapters
....

Some scans use niadd to upload their work.

That original category you placed is for original work.

There are two original categories, one is the one you placed and the other is the one that does not appear and it is for works uploaded from niadd.

**Comment by newaccforhc** [comment]
How about just adding the URI method then?

**Comment by Darkmaster006** [comment]
Just wanted to add that it seems to redirect to gardenmanage dot com, example: https://www.gardenmanage.com/statuses/5400258.html (from chapter 1 here: https://es.niadd.com/original/10027709/chapters.html)

**Comment by MikeZeDev** [comment]
Now chapters redirect to "nineanime".
