### ISSUE TITLE
Add website (KomikGoID)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#817]
From = "https://komikgo.com"
To = "https://www.komikgo.co.id/"

**Comment by MIRVOUS** [comment]
And the template is changed to.
From = "WordPressMadara"
To = "WordPressEManga"

**Comment by MIRVOUS** [comment]
sorry I was mistaken, it turns out the two websites are different from each other

**Comment by 27136773** [comment]
Changed to `Add website KomikGoID`
