### ISSUE TITLE
Can't download (DoujinYosh)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#821]
When Preview :
![doujinyosh](https://user-images.githubusercontent.com/45929526/71611746-38894900-2bce-11ea-95f4-0120fcd8ecb0.PNG)
 When Download :
![doujinyosh2](https://user-images.githubusercontent.com/45929526/71611760-48089200-2bce-11ea-9dc5-8cda25f1e632.PNG)

**Comment by 27136773** [comment]
In fact this is an issue on DoujinYosh, they are prepending chapter links with an invalid domain.
However a filter can be added to correct their issue, so it is possible to read/download chapters that cannot even be shown on DoujinYosh.
