### ISSUE TITLE
Kyuroku don't work

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#822]
list that doesn't work

- Update manga list (synchronize)

- Chapter

- Download/preview

**Comment by 27136773** [comment]
I cannot reach the website, could this be region locked?
https://kyuroku.com

**Comment by 0xh3LL0** [comment]
i'm indonesian,
looks like the website is down, or either removed.

**Comment by 27136773** [comment]
I suggest to wait for the website being back online and then make a new issue if it is still not working in HakuNeko.

References: https://www.facebook.com/official.kyuroku
