### ISSUE TITLE
Cannot Read propertry of '1' of null on anime downloads

### ISSUE THREAD

**Issue by JohnDHowell54** [manga-download/hakuneko#855]
Hello, been having issues downloading anime on the latest release

Distro: Arch Linux & Mint 19.3 

The error: TypeError: Cannot read property '1' of null
Specific error log from console: TypeError: Cannot read property '1' of null at kissanime.html:96 > Chappter (anonymous) @ kissanime.html:108

When downloading anime from KissAnime. Tried Nichijou, Plastic Nee-San, AnoHana (all sub, multiple episodes each). They open on the site, however. I've reinstalled both stable and nightly.

**Comment by 27136773** [comment]
From the log it appears you are using version 5.0.8, which is frozen.
Please try one of the latest nightly builds and create a new ticket if the error still exist.
