### ISSUE TITLE
Site add: https://manga4life.com/

### ISSUE THREAD

**Issue by Solteszka** [manga-download/hakuneko#903]
https://mangalife.us/ recently changed their URL to https://manga4life.com/

**Comment by 27136773** [comment]
Already changed f832a5b0

**Comment by Solteszka** [comment]
Just needed to update the webiste in HakuNeko. Thanks mate.

________________________________
Feladó: ronny1982 <notifications@github.com>
Elküldve: 2020. január 9., csütörtök 23:14
Címzett: manga-download/hakuneko <hakuneko@noreply.github.com>
Másolatot kap: Solteszka <bagolyka94@hotmail.com>; Author <author@noreply.github.com>
Tárgy: Re: [manga-download/hakuneko] Site add: https://manga4life.com/ (#903)


Already changed f832a5b<https://github.com/manga-download/hakuneko/commit/f832a5b0ccfa1ae548b0c3d94c106a0581e7401c>

**Comment by C0rn3j** [comment]
Took me a while to find, this specific button needs to be pressed, otherwise the Manga list will load but chapters won't.

Thanks everyone.

![image](https://user-images.githubusercontent.com/1641362/74085858-c1bd5680-4a7d-11ea-8135-b706ba024504.png)
