### ISSUE TITLE
Can't download or view free CrunchyRoll manga chapters without premium even if it's not needed on site 

### ISSUE THREAD

**Issue by dmr111** [manga-download/hakuneko#905]
On CrunchyRoll, there's some manga titles that have all of their chapters be free for viewing without premium (example: Genshin Impact) and some other manga there allow the viewing of the newest chapter for free. 

However, the HakuNeko desktop app wouldn't download nor view any of such chapters as attempting to do so brings up a pop-up that says a subscription is required (even if it's not required to view the contents on the CrunchyRoll site).

Is there any way to fix this? I'm using the "Stable" version for 64-bit Windows. If there's not a way to fix this, then would it be possible to add it as an enhancement?

**Comment by 27136773** [comment]
Decision pending if HakuNeko should allow access to free content

**Comment by Ever4engel** [comment]
the decision is yours roony
(for the fair use it would be ok for free chapters with his personal id)

**Comment by 27136773** [comment]
Created voting on discord... waiting for community decision until Friday 17th, January

**Comment by 27136773** [comment]
Clear decision by voting to lift the restriction:
Free users with an account shall be able to download non-premium mangas
