### ISSUE TITLE
error blank Hakuneko 

### ISSUE THREAD

**Issue by djgerman10** [manga-download/hakuneko#915]
![1](https://user-images.githubusercontent.com/48584512/72213952-d6d2b400-34d6-11ea-9b02-b29f6ba6add8.png)
hakuneko is blank in windows 7

**Comment by djgerman10** [comment]
both versions are blank v5.0.8 (stable) and nightly-20200102.1

**Comment by djgerman10** [comment]
![q](https://user-images.githubusercontent.com/48584512/72214025-7d6b8480-34d8-11ea-825b-dee8deaba3bb.png)
I have all the visual ++ packages so I don't know what the problem

**Comment by djgerman10** [comment]
### fixed was directx

**Comment by 27136773** [comment]
See: #13
