### ISSUE TITLE
Site not work well (Komiku)

### ISSUE THREAD

**Issue by MIRVOUS** [manga-download/hakuneko#916]
screenshot 
in hakuneko :
![komiku](https://user-images.githubusercontent.com/45929526/72214387-52fae500-3533-11ea-8208-a0d5bf679d00.png)
In the website :
![komiku2](https://user-images.githubusercontent.com/45929526/72214395-91909f80-3533-11ea-8246-f10cf11740c5.png)

**Comment by MIRVOUS** [comment]
in the app. is blank. but in the site is there(the image)

**Comment by 27136773** [comment]
The website seems to be very slow when to many images are requested at the same time.
This is a problem of the website.
As workaround you can download the chapters and read them instantly in offline mode.

![image](https://user-images.githubusercontent.com/27136773/72221139-eba35c00-3557-11ea-8d6d-b2e680e9d67f.png)
