### ISSUE TITLE
problems with "kumanga"

### ISSUE THREAD

**Issue by Dgraid12** [manga-download/hakuneko#919]
I try to update the manga list of "Kumanga" and I get this error

can anybody help me?

![imagen](https://user-images.githubusercontent.com/53473707/72221062-6a36d400-352d-11ea-861f-af3976fc2a9e.png)

**Comment by 27136773** [comment]
This has been fixed in 9597fe07
The fix is not available for version 5.0.8 or below, you need the nightly build...
