### ISSUE TITLE
Not Downloading Chapters in UnionMangás [pt-br]

### ISSUE THREAD

**Issue by RenanMenck** [manga-download/hakuneko#923]
Hi, I can't download the recent chapters of UnionMangás as well as upload the images for reading, and the site is loading normally, the chapters on Union that were in the [bookmarks] are updated and show the chapters, but it is not possible to download, displaying the message: 'failed to fetch'
I use HakuNeko Nightly (6.1.7) and rev.67b111, windows 10 64bits

Thanks in advance for help ..

Also, the chapters are not loaded in 'MangaHost' and 'YesMangaBR' both pt-br ..

**Comment by dodieboy** [comment]
MangaHost Url change: from https://mangahosted.com to https://mangahost2.com/
YesMangaBR and UnionMangas work fine for me.

Can i know what manga you want to download?

**Comment by RenanMenck** [comment]
Actually I'm not being able to download all recent releases of Union,
![Nova Imagem (5)](https://user-images.githubusercontent.com/55268400/72328828-6c667300-3692-11ea-90f1-6d23bd67c4d2.jpg)
![Nova Imagem (6)](https://user-images.githubusercontent.com/55268400/72328860-7c7e5280-3692-11ea-9b93-66a997da985e.jpg)

But I realized that old chapters are loading images and downloading normally, is it only happening to me?
![Nova Imagem (7)](https://user-images.githubusercontent.com/55268400/72329035-cb2bec80-3692-11ea-826f-644f032fae95.jpg)

**Comment by RenanMenck** [comment]
It has already been closed, but I noticed that in the online reader there is a difference in the links to read the chapters, for example in the manga 'Darwins Game', chapter 53 is possible to view the images and download, from 54 onwards is not possible , and in the online reader chapter 53 is accessed by the link:
https://unionleitor.top/leitor/Darwins_Game/53
and 54 is accessed by the link:
unionmangas.top/leitor/Darwins_Game/54

consequently presenting to this difference in hakuneko:
Request URL: https://unionleitor.top/leitor/Darwins_Game/53
Request URL: https: //unionleitor.tophttp//unionmangas.top/leitor/Darwins_Game/54

I don't know if this can make a difference, but I leave this curiosity ..

**Comment by 27136773** [comment]
The provided fix solves exactly the issue you described

**Comment by RenanMenck** [comment]
Sorry for that, is that I still could not download and was curious about a possible cause ..

**Comment by 27136773** [comment]
Check your version, maybe you didn't got the update yet.
You need to restart HakuNeko, sometimes it can take some time because of CDN caches on the servers.
![image](https://user-images.githubusercontent.com/27136773/72383188-391bf680-371b-11ea-9171-21e5251de7e2.png)

**Comment by RenanMenck** [comment]
Yes, I realized that the update had not been done yet, should I create a new issue for MangaHost reader url change?
And thanks for all this work ..

**Comment by 27136773** [comment]
MangaHost URL was also updated
