### ISSUE TITLE
Wrong image file format

### ISSUE THREAD

**Issue by MT135** [manga-download/hakuneko#926]
When using Cut/Paste method for manga in Mangapark.net output image files are all format ".webp" instead of usual Jpeg.
All settings in Hakuneko remains the same, when I download manga using usual search drop-down method from Mangapark.net (or any other website), files are normal jpeg. Only when cut/paste method is used the result is .webp.

Can't use other method than cut/paste for mangapark.net since the anime list only goes down to letter "D"

**Comment by 27136773** [comment]
Can you please provide a sample manga/chapter where this problem occurs?

**Comment by 27136773** [comment]
The manga list is restricted to 10000 mangas, the website does not allow to browse for any more.
I cannot reproduce the image format issue. Tested some random manga, they are always WEBP, no matter if download from the list or by Copy & Paste.

**Comment by 27136773** [comment]
No further response => closed
