### ISSUE TITLE
KissAnime not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#928]
> **From:** HakuNeko User

Cannot download anything from KissAnime, because it is intergrating with RapidVideo. (Even the website no longer supports, nor uses, RapidVideo). Suggest you somehow change to one of the supported servers (Mp4Upload, Nova, or Beta).

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Have you tried the latest nightly build?
It uses HydraX servers

**Comment by 27136773** [comment]
No further response => closed
