### ISSUE TITLE
mangarock

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#94]
> **From:** HakuNeko User

some old and some new tittle didn't appear even in this lots updates this week

**Comment by 27136773** [comment]
Can you provide some sample titles that are missing?

**Comment by mangatabar** [comment]
well same here
![Capture](https://user-images.githubusercontent.com/46851278/57223661-fb65ba80-7030-11e9-926f-27f5f030d822.PNG)

**Comment by mangatabar** [comment]
and not just 1 tittle

**Comment by mangatabar** [comment]
![image](https://user-images.githubusercontent.com/46851278/57223729-41bb1980-7031-11e9-8a2d-8ec4d93a4f56.png)

**Comment by mangatabar** [comment]
some of them is updated 
![image](https://user-images.githubusercontent.com/46851278/57223774-67e0b980-7031-11e9-8904-b7c535b11f8e.png)

**Comment by mangatabar** [comment]
![image](https://user-images.githubusercontent.com/46851278/57223834-95c5fe00-7031-11e9-98c2-b73a47962a8e.png)

**Comment by mangatabar** [comment]
![image](https://user-images.githubusercontent.com/46851278/57223905-d7ef3f80-7031-11e9-81c9-21375018eb37.png)

**Comment by mangatabar** [comment]
FYI it more than 10 tittles

**Comment by mangatabar** [comment]
and the web is fine
![image](https://user-images.githubusercontent.com/46851278/57224113-87c4ad00-7032-11e9-8ca7-7b3d487ecc51.png)

**Comment by 27136773** [comment]
Cannot be reproduced, all listed mangas are showing the newest chapter for me.
HakuNeko does not use the website directly, it uses the provided API.
It is very unlikely, but maybe there is a delay between the availability of a new chapter release on the website and on the API.
Please check if the new chapters for the listed mangas are still not available for you.

**Comment by mangatabar** [comment]
well  its back normal now but yesterday i tried whole day. and trying to re install but the result the same

**Comment by mangatabar** [comment]
welp thanks for reply

**Comment by 27136773** [comment]
Issue closed since it seems to work now
