### ISSUE TITLE
gmanga

### ISSUE THREAD

**Issue by satyogi** [manga-download/hakuneko#941]
all chapter in https://gmanga.me/ dont appear 
please fix

**Comment by 27136773** [comment]
Chapter URL changed and needs to be implemented:
`this.url + '/api/mangas/' + manga.id + '/releases'`
https://gmanga.me/api/mangas/1844/releases

**Comment by satyogi** [comment]
how to do that

**Comment by 27136773** [comment]
This is a developer note
