### ISSUE TITLE
Image download fails for many websites [connector protocol unknown]

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#952]
> **From:** ronny1982

**Version:** [master@d6bedf](https://github.com/manga-download/hakuneko/commits/d6bedf)

The connector protocol seems not to be working anymore after electron update...

![image](https://user-images.githubusercontent.com/27136773/72670490-24eb3880-3a3e-11ea-9bc2-f4712f67d747.png)

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Created issue: electron/electron#21896
