### ISSUE TITLE
Add support for website: LINE Webtoon France [FR]

### ISSUE THREAD

**Issue by su0su0** [manga-download/hakuneko#961]
**Site name**: LINE Webtoon France
**URL**:  https://www.webtoons.com/fr/
**Language**: French
**Content**: French version of Naver's [LINE Webtoon](https://www.webtoons.com/en) (Hakuneko id: _linewebtoon-en_), same site structure.
**Free**: Yes
**Require account/login**: No

**Comment by 27136773** [comment]
Manga lists cannot be fetched right now (only copy paste will work)
The manga list needs to be implemented on the CDN service

**Comment by 27136773** [comment]
Added list to CDN
