### ISSUE TITLE
v6.1.7 Hangs on Launch on OS X v10.11.6 'El Capitan'

### ISSUE THREAD

**Issue by RandomDSdevel** [manga-download/hakuneko#964]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It just keeps on bouncing until it's stopped, but stuck in the Dock as if it's open but frozen without the indicator lit up underneath it, and I have to Force Quit it.  v5.0.8 launches just fine.  (My current hardware doesn't support upgrading past El Cap, though I'm getting a new machine soon.)

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I was actually able to reproduce this with v5.0.8.  Looks like an issue with [Gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)) verification even after confirming that I want to open HakuNeko despite it's not having a valid.developer ID signature.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ah, now I remembered what I did to work around Gatekeeper last time:  '`xattr -r`ing `com.apple.quarantine` naturally does the trick.  It still took _forever_ for HakuNeko to start up, though, and the main window took a while to show up, too.  Strange, v5.0.8 didn't take nearly _this_ long to load…

**Comment by 27136773** [comment]
Currently i don't know how to improve the user experience for macOS without paying the annual developer subscription fee...
When i install HakuNeko, i open the application by right-clicking on the package in the `Application` directory and from the popup select open (two times). After that i never get bothered by any security warnings again.

**Comment by RandomDSdevel** [comment]
@ronny1982:  

> Currently i don't know how to improve the user experience for macOS without paying the annual developer subscription fee...
> When i install HakuNeko, i open the application by right-clicking on the package in the Application directory and from the popup select open (two times). After that i never get bothered by any security warnings again.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yeah, that's how it usually works for me, too, except I often see the Gatekeeper verification step hang indefinitely; it's probably just a bug that Apple's already fixed in newer macOS releases.  Things are still slow once you get past that, however.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Note that I meant to say that I see Gatekeeper issues with unsigned apps; signed code works just fine.  Anyway, HakuNeko loads normally and regular speed now, so I'm going to close this issue as invalid.  Must just be some extra first-launch code that's running…
