### ISSUE TITLE
Can't Download 'Boku wa Mari no Naka'/'Inside Mari' Chapters 61 & 64

### ISSUE THREAD

**Issue by RandomDSdevel** [manga-download/hakuneko#965]
<details open>
  <summary>Steps I've Followed So Far</summary>

  - [x] Read [the Quick Start guide](https://git.io/hakuneko-quickstart).  
  - [ ] Tried [recommended Troubleshooting steps/checks](https://git.io/hakuneko-troubleshooting).  
  - [x] Tried [website interaction](https://git.io/hakuneko-websiteinteraction).  
  - [ ] [Searched for similar issues.](https://git.io/hakuneko-issuesearch)  
</details>

**OS Type and Version:**  Apple OS X v10.11.6 'El Capitan,' build 15G22010
**HakuNeko Desktop Client Version/Build:**  v6.1.7@a3b180
**Manga Source:**  KissManga
**Manga Name:**  _Boku wa Mari no Naka_, a. k. a. _Inside Mari_
**Manga Chapters:**  61 and 64
**HakuNeko Settings:**  <details><summary>Click to expand…</summary>

  Chapter File Format:  'Portable Document Format (*.pdf)'
  (All other preferences left set to their defaults.)  
</details>
**Console Logs:**  <details><summary>Click to expand…</summary>

```
DownloadJob.mjs:145 DOMException (20) ["https://2.bp.blogspot.com/-wyWso0I6Llg/Vkwkzfsjd8I/AAAAAAABmvQ/FBEiVq1--uE/s0-Ic42/000.jpg", "https://2.bp.blogspot.com/-fKqAo96FobY/Vkwkzeupb3I/AAAAAAABmvQ/JrwfXj0F-ZA/s0-Ic42/001.jpg", "https://2.bp.blogspot.com/-uviWxS2_yJs/VkwkzstYRDI/AAAAAAABmvQ/6Gs5uOdd4UI/s0-Ic42/002.jpg", "https://2.bp.blogspot.com/-foULGhxbMIc/Vkwkzq0PtkI/AAAAAAABmvQ/BE7d5MDPpCk/s0-Ic42/003.jpg", "https://2.bp.blogspot.com/-wk6Xbtu9CC4/Vkwkzz0156I/AAAAAAABmvQ/KNYRuN3pFdo/s0-Ic42/004.jpg", "https://2.bp.blogspot.com/-VGzoHGxntLs/Vkwkz34s2YI/AAAAAAABmvQ/F9MgcM3UcJk/s0-Ic42/005.jpg", "https://2.bp.blogspot.com/-CnKrOcx7wZA/Vkwk0EJdFHI/AAAAAAABmvQ/Yo0d1ppe7cA/s0-Ic42/006.jpg", "https://2.bp.blogspot.com/-U6s-L7MA68A/Vkwk0COKRiI/AAAAAAABmvQ/h0lRjMcYzE8/s0-Ic42/007.jpg", "https://2.bp.blogspot.com/-ZjNATMt23c4/Vkwk0WYZl7I/AAAAAAABmvQ/NDRHGR2SsUA/s0-Ic42/008.jpg", "https://2.bp.blogspot.com/-j4rgHysV3o4/Vkwk0es6p-I/AAAAAAABmvQ/K7l_cfLiT_E/s0-Ic42/009.jpg", "https://2.bp.blogspot.com/-XhVVtOeUqvA/Vkwk0h_poNI/AAAAAAABmvQ/5WoP6q5_194/s0-Ic42/010.jpg", "https://2.bp.blogspot.com/-UFK825WmNDw/Vkwk0pDGauI/AAAAAAABmvQ/KOr5m-8Cfxc/s0-Ic42/011.jpg", "https://2.bp.blogspot.com/-Uqb-drd8LIw/Vkwk0zmYlLI/AAAAAAABmvQ/eVhsUS7HLMw/s0-Ic42/012.jpg", "https://2.bp.blogspot.com/-fRl6C0YfyDA/Vkwk1SwzoeI/AAAAAAABmvQ/Oe_blw4rkxk/s0-Ic42/013.jpg", "https://2.bp.blogspot.com/-mBpXB5lFtIM/Vkwk1axi4RI/AAAAAAABmvQ/zOPAKa9RCDo/s0-Ic42/014.jpg", "https://2.bp.blogspot.com/-KJWiW9ILDPI/Vkwk1nOKFbI/AAAAAAABmvQ/SPzDlhWskZ4/s0-Ic42/015.jpg", "https://2.bp.blogspot.com/-L5NfoUTkTS8/Vkwk15xkxGI/AAAAAAABmvQ/M6uLzV0skto/s0-Ic42/016.jpg", "https://2.bp.blogspot.com/-89fKfVW2JyQ/Vkwk2GdR1FI/AAAAAAABmvQ/ftFN0pUTzVU/s0-Ic42/017.jpg", "https://2.bp.blogspot.com/-1lRh3gBfQlo/Vkwk2dZiNPI/AAAAAAABmvQ/ppFY8OWcyWk/s0-Ic42/018.jpg", "https://2.bp.blogspot.com/-5SklDsSYGJs/Vkwk2e89nyI/AAAAAAABmvQ/tmneecHMS9I/s0-Ic42/019.jpg"]
(20) ["https://2.bp.blogspot.com/-C_6Y4DlQDkA/Vox8LMnJSgI/AAAAAAACgPM/rnsmwzqTDaw/s0-Ic42/000.jpg", "https://2.bp.blogspot.com/-LdguhAgVZnE/Vox8KylQOjI/AAAAAAACgPM/fWWJNulPqz8/s0-Ic42/001.jpg", "https://2.bp.blogspot.com/-qM4J_qXV_Ps/Vox8K9qh3QI/AAAAAAACgPM/ix2DyczS7pE/s0-Ic42/002.jpg", "https://2.bp.blogspot.com/-LnDyakD36E8/Vox8La49lxI/AAAAAAACgPM/G-hFm2yEm5c/s0-Ic42/003.jpg", "https://2.bp.blogspot.com/-iPzQumM5IiI/Vox8LqfalMI/AAAAAAACgPM/NAG5dQErL3U/s0-Ic42/004.jpg", "https://2.bp.blogspot.com/-e9dxvKxpMgs/Vox8LqOX4FI/AAAAAAACgPM/V_wgOHJrA64/s0-Ic42/005.jpg", "https://2.bp.blogspot.com/-BfZrhWC9BXo/Vox8L5YeigI/AAAAAAACgPM/6m7jXxb5fyE/s0-Ic42/006.jpg", "https://2.bp.blogspot.com/-Z31_2K28u3I/Vox8L6pxmlI/AAAAAAACgPM/ElqagKlEL9g/s0-Ic42/007.jpg", "https://2.bp.blogspot.com/-Mj53ApgGHlY/Vox8MK_Y3UI/AAAAAAACgPM/J5clkrkNy2M/s0-Ic42/008.jpg", "https://2.bp.blogspot.com/-OdvVdA9JZxg/Vox8MDf35UI/AAAAAAACgPM/4c23DZmVV0A/s0-Ic42/009.jpg", "https://2.bp.blogspot.com/-41qO_LCRfBQ/Vox8MvZFziI/AAAAAAACgPM/VIPz_pv_qzE/s0-Ic42/010.jpg", "https://2.bp.blogspot.com/-N7ox1zsfy7U/Vox8NIFaE0I/AAAAAAACgPM/i7Fkse35zPM/s0-Ic42/011.jpg", "https://2.bp.blogspot.com/-6fWFtnwpfqU/Vox8NBe-5qI/AAAAAAACgPM/9a-qDCIdmko/s0-Ic42/012.jpg"
```

(There's more under disclosure triangles, probably a hierarchical, per-item breakdown, but I can't copy/paste that, unfortunately.)  
</details>

<hr />

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Note that this issue manifests on both v5.0.8 and v6.1.7.  (This issue may well be, at least in part, a duplicate of issues #7, #621, and/or #634, just for this particular manga and these specific chapters.)

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Er, that second line of logs should also begin with '`DownloadJob.mjs:145 DOMException`.'  Guess I didn't copy everything like I thought…?  (I'd edit the OP, but GitHub won't let me do that from this version of Safari…)

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(And I forgot to check those other two checkboxes I stuck in my OP, as well.  Apologies for the inconvenience.)

**Comment by 27136773** [comment]
Reproducible, preview works just fine, but download failed
https://kissmanga.com/Manga/Boku-wa-Mari-no-Naka
Probelem seems to be when saving images as PDF
