### ISSUE TITLE
Please add webnovel.com

### ISSUE THREAD

**Issue by Max25798** [manga-download/hakuneko#968]
Is it possible to add?

Thanks.

Edit 2 -
site: https://webnovel.com

**Comment by 27136773** [comment]
Webnovel (Comics) are already supported
Webnovel (Novels) are not yet: https://www.webnovel.com/category/list?categoryType=1

**Comment by Max25798** [comment]
> 
> 
> Webnovel (Comics) are already supported
> Webnovel (Novels) are not yet: https://www.webnovel.com/category/list?categoryType=1

There's a bug which skips while downloading in batch. Then again some comics single chapter cannot be downloaded. I tried it again after clearing out the userdata. Same result.

**Comment by 27136773** [comment]
> There's a bug which skips while downloading in batch. Then again some comics single chapter cannot be downloaded. I tried it again after clearing out the userdata. Same result.

Cannot be reproduced on my end with random mangas/chapters.
Please provide which manga/chapters did not work.
Make sure the manga/chapter works on the website, HakuNeko can only download chapters if they are available on the website.

**Comment by Max25798** [comment]
> 
> 
> > There's a bug which skips while downloading in batch. Then again some comics single chapter cannot be downloaded. I tried it again after clearing out the userdata. Same result.
> 
> Cannot be reproduced on my end with random mangas/chapters.
> Please provide which manga/chapters did not work.
> Make sure the manga/chapter works on the website, HakuNeko can only download chapters if they are available on the website.

I can confirm latest chapters does not work. It creates a folder in directory but no files inside. 
Example: Versatile Mage, Tales of demon and gods etc. Latest chapters are skipped instead of downloading.

**Comment by 27136773** [comment]
For [Tales of Demons and Gods](https://www.webnovel.com/comic/14622895506049901) only the first 60 chapters are free. Have you purchased any of the additional chapters which is not working?

<img width="1017" alt="Screen Shot 2020-01-22 at 6 08 33 AM" src="https://user-images.githubusercontent.com/27136773/72866998-b2988380-3cdd-11ea-9508-db3355ad9e20.png">

**Comment by Max25798** [comment]
No. Does it not download anything if its locked? So it can't be bypassed?

**Comment by 27136773** [comment]
No, HakuNeko will only give access to free/authorized content.
I updated the troubleshooting guide in the wiki to explicitly include this restriction.

**Comment by Sheepux** [comment]
(solved a recent WebNovel  issue and just saw this issue)
Closing as it's not an issue. Make sure to comment if there was still something (erm ..., 1,5 years ago)
