### ISSUE TITLE
Manhwahentai.com not working

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#97]
> **From:** HakuNeko User

the reader is not loading the images form manhwahentai.com anymore with the new update. please fix

**Comment by Manhwahentai** [comment]
manhwahenta.site is our new domain please use this as your new alternative.

**Comment by michaelr404** [comment]
Now there are a lot of fake sites, I think they move to new domain https://manhwahentai.me

**Comment by 27136773** [comment]
HakuNeko already supports the following two different websites:

- https://manhwahentai.site
- https://manhwahentai.me
