### ISSUE TITLE
Can't Command+Q new build

### ISSUE THREAD

**Issue by rebeccatkatz** [manga-download/hakuneko#970]
I can't use a shortcut to quit the new version of Hakuneko on mac osx. have to press the x button. Is this on purpose?

**Comment by 27136773** [comment]
Refering to electron `CMD + Q` was never supported and HakuNeko did not add a listener for this yet.
A Corresponding shortcut needs to be implemented in the client.

Further reading: https://memorytin.com/2018/04/24/electron-js-handle-cmdq-in-os-x/
