### ISSUE TITLE
TMO (tmofans) not working

### ISSUE THREAD

**Issue by gerardodinardo** [manga-download/hakuneko#975]
This one works for 2 or 4 days since the last update until today.

**Comment by 27136773** [comment]
Cannot be reproduced on my end

Describe in further detail "not working"
Provide manga/chapter that did not work as expected

**Comment by gerardodinardo** [comment]
Doesn't work pasting the url from the clipboard, by searching works as expected, but the chapters can't be downloaded due the following alert. 
![image](https://user-images.githubusercontent.com/30539376/73023438-d073fe80-3e2b-11ea-83ec-dd5231c40454.png)

pd: Sorry for not being detailed.
