### ISSUE TITLE
my bitdefender total security keep block this manga download

### ISSUE THREAD

**Issue by maryann411** [manga-download/hakuneko#978]
hi, need help first the my virus protector block this manga download for update and the new one will not work at all it keep saying i need to closes all file that are open but none is open .
and when it finely did  download using the potable one it just show the first page screen no  button or anything.
please fix 
this is what my bit defender keep saying
i have try use the exception it stay say it dangerous is it i hope not because i love this manga download so please help me please
Online Threat Prevention

We blocked this dangerous page for your protection:
http://static.hakuneko.download/5.0.8/latest
Accessed by: hakuneko.exe
Dangerous pages attempt to install software that can harm the device, gather personal information or operate without your consent.

**Comment by 27136773** [comment]
This may probably cause issue #13 
[Result from VirusTotal](https://www.virustotal.com/gui/url/b8cbb1f22bd22038b800ade0716552eb4705b5a21169ee6d8b6539e91e63b15c/detection)
With version 6.1.7 HakuNeko can download automatic updates directly from GitHub, but currently the GitHub Pages for this project are still configured to use the domain `static.hakuneko.download` for backward compatibility with all versions prior to 6.1.7

A possible solution is to introduce a second host which provides updates for all prior versions and listen to `static.hakuneko.download` and remove the domain from GitHub Pages for the latest and upcoming versions...

**Comment by 27136773** [comment]
Domain name has been removed for hosting of version 6.1.7 and above.
Prior versions are still using the domain and cannot be fixed.

**Comment by 27136773** [comment]
Does the problem still exist with HakuNeko 6.1.7?

**Comment by 27136773** [comment]
No further response => closed
