### ISSUE TITLE
Probleme Japscan.co

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#979]
> **From:** HakuNeko User

**Version:** [6.1.7@867186](https://github.com/manga-download/hakuneko/commits/867186)

hello 
I have a problem all the images download from japscan.co are .bin please fix this problem as soon as possible
thanks

<details><summary>What has been done?</summary>

☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction

</details>

**Comment by 27136773** [comment]
Please provide a manga/chapter for reproduction

**Comment by MikeZeDev** [comment]
Its probably related to the problem i just got : unable to display any images from any manga : console shows only 404 errors.

Dr stone, Dragon ball super, One piece, One punch man, etc.... Any chapter.

It works fine on browser. They changed something maybe.

**Comment by 27136773** [comment]
Yes, the way image links are provided had changed
