### ISSUE TITLE
japscan image extention .bin

### ISSUE THREAD

**Issue by megacin** [manga-download/hakuneko#986]
Hello hakuneko team to day japscan change somthing in his site so if i dounlad image from programe everthing is good but image look like this image.bin not jpg he is crypted can you fiexd please

**Comment by 27136773** [comment]
Which manga/chapter?

**Comment by megacin** [comment]
All manga in japscan.co was cryipted by this bin

Le ven. 24 janv. 2020 à 23:36, ronny1982 <notifications@github.com> a
écrit :

**Comment by 27136773** [comment]
See #979

**Comment by megacin** [comment]
whats i will do ? download programe or update or whats

**Comment by megacin** [comment]
Whats can i do ?? Could i update programe or doanloeded from bieging

Le ven. 24 janv. 2020 à 23:42, ronny1982 <notifications@github.com> a
écrit :

**Comment by 27136773** [comment]
Restart click version, check if auto-update has been installed, if not wait some minutes and restart again

![image](https://user-images.githubusercontent.com/27136773/73109736-53688800-3f04-11ea-9220-c1db10f5ba5b.png)

**Comment by megacin** [comment]
it stil not updated

**Comment by 27136773** [comment]
Whats your version/revision number?

**Comment by megacin** [comment]
![1](https://user-images.githubusercontent.com/48812724/73110514-f15d5200-3f06-11ea-9f4e-b6192a123674.PNG)
![2](https://user-images.githubusercontent.com/48812724/73110516-f1f5e880-3f06-11ea-9974-3319b834da5d.PNG)
![3](https://user-images.githubusercontent.com/48812724/73110517-f1f5e880-3f06-11ea-9758-b39b28102809.PNG)
this one and i have a fivver from you please

**Comment by 27136773** [comment]
You need to download new client 6.1.7

**Comment by megacin** [comment]
thank you can i have a fivver from you please please i have examn in my hight school they told as to builde this game Bulltricker. with languge c can i have this code please if you know how it work 
https://www.youtube.com/watch?v=lpeWLXtJ8yY

**Comment by 27136773** [comment]
I cannot help with your assignments

**Comment by megacin** [comment]
thank you
