### ISSUE TITLE
Mangabat

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#991]
> **From:** HakuNeko User

**Version:** [](https://github.com/manga-download/hakuneko/commits/)

Unable to download chapters from some of the mangas from mangabat.

<details><summary>What has been done?</summary>

</details>

**Comment by 27136773** [comment]
Download and install an update HakuNeko client.
These are probably cross references to affiliate MangaNel.
Consider using MangaNel instead of MangaBat.
