### ISSUE TITLE
[Japscan] new descrambling technique ?

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#996]
Hi,

Somes chapters has somes troubles with descrambled images : 

https://www.japscan.co/lecture-en-ligne/black-clover-quartet-knights/22/
https://www.japscan.co/lecture-en-ligne/je-m-adresse-a-toi-l-immortel/117/

Thanks for your job

**Comment by 27136773** [comment]
JapScan seems to use a new image scrambling method, which needs to be analyzed and implemented into HakuNeko.

**Comment by ghost** [comment]
It works !!!
Thanks a lot !

**Comment by ghost** [comment]
Re,

Doesn't work for this chapters :
https://www.japscan.co/lecture-en-ligne/prison-school/219/
https://www.japscan.co/lecture-en-ligne/psycho-pass-saison-2/0/

Can you re-open the issue ?
Thanks

**Comment by 27136773** [comment]
GitHub Pages deployment seemed to have some problems...
Restart HakuNeko and make sure you got the update

![image](https://user-images.githubusercontent.com/27136773/73550212-76cf8d80-4444-11ea-9a95-7e556ac0a227.png)

**Comment by Zarh** [comment]
I'm sry but it's still not working.
![Sans titre](https://user-images.githubusercontent.com/8205047/73578090-0f82ff00-447f-11ea-8853-6218e9af3286.png)

I tested it with several and I have "TypeError : failed to fetch". For example : https://www.japscan.co/lecture-en-ligne/kimetsu-no-yaiba/192/

Thank you.

PS: Do I have to open a new issue ?

**Comment by 27136773** [comment]
Works fine for me.
Try [troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) and [manual website interaction](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction).
Also try re-download the chapters as the images will be cached with every further attempt.

![image](https://user-images.githubusercontent.com/27136773/73580914-b7042f80-4487-11ea-8b9e-784d1096669f.png)

**Comment by 27136773** [comment]
I just saw you are using nightly build which is currently broken... you must use stable version 6.1.7 for now
See #952

**Comment by Zarh** [comment]
yaye it's working. thank you !
